### ISSUE TITLE
Issue with while exporting the library project to DLL on windows with fmt dependency

### ISSUE THREAD

**Issue by aksswami** [fmtlib/fmt#1000]
Hi, 

I am developing a cross platform library and using `spdlog` for logging. Which have fmt as dependency. Also using the `fmt` for string formatting. I have added fmt repo as submodule and using below in my CMakeList file.

```
add_subdirectory(vendor/fmt)
target_link_libraries(${XXX} PRIVATE fmt-header-only)
```

Using this, I was able to successfully use the `fmt` as well as `spdlog` on *inx and osx system. 
On window also, I am using same CMakeList in VS2017 for this project and was able to compile and run my unit test.

But when I try to export my lib as DLL, I am getting compile time error:-
```
Undefined scope (fmt)
```

Not sure reason behind this error. Any help will be much appreciated.

Thanks in advance.

**Comment by vitaut** [comment]
`Undefined scope (fmt)` doesn't look like a compiler error. Where do you get it? Could you post the full compilation output?

**Comment by vitaut** [comment]
Closing as it is not clear how to reproduce the issue, but feel free to reopen with additional details.

**Comment by masphei** [comment]
"Undefined scope xxx" is basically a kind of exception thrown by Swig
