### ISSUE TITLE
clang-format CI check

### ISSUE THREAD

**Issue by stryku** [fmtlib/fmt#1007]
Since there is the `.clang-format` file available, a CI check could be introduced to verify formatting before a merge.

**Comment by foonathan** [comment]
Sadly this is problematic as there are slight Changes between clang-format versions...

**Comment by stryku** [comment]
Specifying clang-format version that {fmt} uses is not an option?

**Comment by foonathan** [comment]
It would require that every contributor has that version installed as well.

Which I don't think is reasonable for something that are just slightly different line breaks and stuff.

**Comment by stryku** [comment]
I see, good point, thanks for an explanation.
