### ISSUE TITLE
Compile error of variadic template under gcc 4.6.3

### ISSUE THREAD

**Issue by sodevel** [fmtlib/fmt#1008]
The following code fragment

`
#if FMT_GCC_VERSION && FMT_GCC_VERSION < 405
template <typename... T> struct is_constructible : std::false_type {};
#else
template <typename... T>
struct is_constructible : std::is_constructible<T...> {};
#endif
`

causes this error with gcc 4.6.3 on my Ubuntu 12.04 machine

`
/fmt/core.h:341:53: sorry, unimplemented: cannot expand 'T ...' into a fixed-length argument list
`

Rising the version check to 407 solves this issue for me, but i didn't test extensive if this causes any side effects.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/dad1eec8427dc997570de3d8493918dd334b257c. Thanks for reporting!
