### ISSUE TITLE
std::ostream flags ussue

### ISSUE THREAD

**Issue by niXman** [fmtlib/fmt#1010]
Hi,

Using this code I expect to get this: `0.00002965-0.00002965`, but I got this: `0.00002965-2.965e-05`.
```cpp
std::cout.precision(8);
std::cout.flags(std::ios_base::fixed|std::ios_base::showpoint|std::ios_base::showbase);
double d = 0.00002965;
std::cout << d << "-";
fmt::print(std::cout, "{}", d);
std::cout << std::endl;
```

What am I doing wrong?

Thanks.

**Comment by mwinterb** [comment]
The ostream accepting overload of print only uses the ostream as a destination after formatting has occurred: the normal fmt formatting rules apply. It's more or less an optimization of `std::cout << fmt::format("{}", d);` (except it will ignore any ios flags that customize std::string's formatting).

**Comment by niXman** [comment]
You are right, I see: https://github.com/fmtlib/fmt/blob/master/include/fmt/ostream.h#L127

But what should I do to tell `fmtlib` to use `std::ostream` fmt opts?

**Comment by niXman** [comment]
> But what should I do to tell fmtlib to use std::ostream fmt opts?

I think its impossible... %)

**Comment by vitaut** [comment]
{fmt} is using format strings instead of I/O manipulators to control formatting:

```c++
fmt::print(std::cout, "{:.8f}", d);
```

**Comment by niXman** [comment]
This is a terrible decision, because I have to refactor the entire project.
Do you have a rationale why the library don`t use the `std::ostream`s flags when simple placeholders(`{}`/`{N}`) was used?

**Comment by vitaut** [comment]
{fmt} is a formatting library that implements Python- and printf-like formatting. It is completely unrelated to iostreams. The optional ostream output support is only provided for convenience. You can continue using iostreams, possibly alongside {fmt}, without refactoring anything.

**Comment by niXman** [comment]
> You can continue using iostreams, possibly alongside {fmt}, without refactoring anything.

Can you please explain?
