### ISSUE TITLE
Exported symbols in .data section

### ISSUE THREAD

**Issue by stv0g** [fmtlib/fmt#1013]
I noticed that fmtlib exports some symbols in my shared library in the `.data` section.

```
objdump -TC mylib.so | grep '\.data' | grep -v rel\.ro
```

```
00000000001ae960 u    DO .data	00000000000000a0  Base        fmt::v5::internal::basic_data<void>::POWERS_OF_10_64
00000000001ae920 u    DO .data	0000000000000028  Base        fmt::v5::internal::basic_data<void>::POWERS_OF_10_32
00000000001aea00 u    DO .data	00000000000000c9  Base        fmt::v5::internal::basic_data<void>::DIGITS
```

I am wondering why these symbols don't end up in the `.rodata` section?

**Comment by vitaut** [comment]
Not sure. Perhaps check the compiler documentation or SO: https://stackoverflow.com/questions/10818761/gcc-why-constant-variables-not-placed-in-rodata
