### ISSUE TITLE
Feature Request: `%{...}` placeholder instead of `{...}` for less escaping - `%%{}` instead of `{{...}}`

### ISSUE THREAD

**Issue by andry81** [fmtlib/fmt#1014]
Some time ago i've suggested to use a bit another syntax to introduce a less escaping instead of currently used:
https://github.com/fmtlib/fmt/issues/634#issuecomment-429853952

Is that having a sence or everybody already settled down with the current one?

Don't get me wrong, I don't want to break or rebuild anything, I just want to find out if everyone likes the current syntax.

**Comment by vitaut** [comment]
I think the question was extensively discussed in #634 and anyone interested can chime in there. No point in opening another issue.

**Comment by andry81** [comment]
I don't think anybody saw this, so opened a new one.
