### ISSUE TITLE
Migration guide from 4.x to 5.3?

### ISSUE THREAD

**Issue by ludekvodicka** [fmtlib/fmt#1016]
Hi there,

is there any some kind of migration guide? I tried to update my old 4.x version but it seems that new 5.x version has completely new API.

I used also a lot of inner functions like BasicWriter,Buffer,BasicFormatter, etc. and it seems that for example BasicWritter currently doesn't have any alternative in 5.3

Thanks

**Comment by vitaut** [comment]
Release notes describe changes, often with examples, e.g. https://github.com/fmtlib/fmt/releases/tag/5.0.0 . Let me know if you have any specific questions and I can point you to the new API.
