### ISSUE TITLE
Use version 5.3.0 in Visual Studio

### ISSUE THREAD

**Issue by MattiasEppler** [fmtlib/fmt#1017]
Hi. I used fmt in a older version in visual Studio. In this version it was enough to add format.h and format.cc to my project and include stdafx.h

Now I update to version 5.3.0. And replaced format.h and format.cc.
Do I need to add all files from include and src to my project?

**Comment by vitaut** [comment]
> Do I need to add all files from include and src to my project?

No. You'll need `core.h` and `format-inl.h` in addition to `format.h` and `format.cc`. The rest is optional.

**Comment by foonathan** [comment]
You shouldn't add them in the same folder, you'll get issues with the other headers.

**Comment by MattiasEppler** [comment]
Why. Is this only in case of fmtlib? Default in visual studio is same folder for h. and cpp.

**Comment by vitaut** [comment]
Updated docs in https://github.com/fmtlib/fmt/commit/bf6529f2ce688c3a19e42c790f0a0bd36f2a95b4.

The headers are placed in the `fmt` directory to prevent collisions.
