### ISSUE TITLE
What is the alternative for CustomBuffer and Writter in 5.x version?

### ISSUE THREAD

**Issue by ludekvodicka** [fmtlib/fmt#1018]
Is it possible to implement custom writer/buffer in version 5.x?

We have our own String class and I would like to write formats directly to it.

In 4.x version I used Derived CustomBuffer (from fmt::Buffer<char>) and CustomWritter (derived from  fmt::BasicWriter<char>).

But I don't see any similar option in 5.x version

I found "Custom allocators" section but I don't think it can be used to write to another class (for example directly to QString or to our own string).

Is there currently any way or should I have to copy a created string? ;-(

**Comment by vitaut** [comment]
> Is it possible to implement custom writer/buffer in version 5.x?

No, the writer API has been superseded by the iterator-based API.

> Is there currently any way or should I have to copy a created string?

If the destination string is compatible with `back_inserter`, then you can do:

```c++
MyString s;
fmt::format_to(std::back_inserter(s), ...);
```

Alternatively, you could write to a `memory_buffer` and copy or provide an appending iterator that works with your string type.
