### ISSUE TITLE
Using {:n} does not comma separate number by locale settings

### ISSUE THREAD

**Issue by Carandiru0** [fmtlib/fmt#1020]
{:n} does not for example take a number such as 123456789 and format it as 123,456,789 instead
This was using .print or .print_colored
I checked my locale settings, Windows 10,  to be sure number formatting with comma separation is enabled.

Cheers!

**Comment by vitaut** [comment]
This is a known issue. `snprintf` which is currently used for floating-point formatting doesn't (portably) support thousands separator.

**Comment by vitaut** [comment]
This has been fixed in 5.3.0 already:

```c++
fmt::print("{:n}", 123456789);
```
prints `123,456,789`.
