### ISSUE TITLE
Move `enable_if` from return types to template params

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#1023]
Move remaining `enable_if`s from return types to template params to reduce symbol sizes.

**Comment by eliaskosunen** [comment]
On clang, SFINAE in template parameters is 10x slower than in return types:

https://bugs.llvm.org/show_bug.cgi?id=36158  
https://twitter.com/ericniebler/status/958751241802104832

**Comment by vitaut** [comment]
![t11](https://user-images.githubusercontent.com/576385/52009996-2c11e300-2489-11e9-8cb6-aa0bd093617c.jpg)

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/c21c6b8c4b89b3a3abc88ecec0ffbb76481db325. Apart from shorter symbols, the code is now much cleaner and the compile times haven't changed much.
