### ISSUE TITLE
Use Grisu for FP formatting with precision

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#1032]
Currently Grisu is only used for the default (shortest decimal) formatting without precision. Investigate if it is possible to use it with given precision, at least when precision is relatively small.

**Comment by vitaut** [comment]
Fixed precision is partly implemented in https://github.com/fmtlib/fmt/commit/8af651be3925d67ce6f99c8345034f7194888c7b.

**Comment by vitaut** [comment]
Grisu is now used with fixed precision too (`f` & `F` specifiers). Need to enable it for `g` as well.

**Comment by vitaut** [comment]
As a nice side effect {fmt} beats printf now, even without any optimizations:

```
================= ============= ===========
Library           Method        Run Time, s
================= ============= ===========
libc              printf          1.01
libc++            std::ostream    3.04
fmt 1632f72       fmt::print      0.86
tinyformat 2.0.1  tfm::printf     3.23
Boost Format 1.67 boost::format   7.98
Folly Format      folly::format   2.23
================= ============= ===========
```

**Comment by vitaut** [comment]
Enabled Grisu for general format in https://github.com/fmtlib/fmt/commit/76d326a2a2c844735e7aaa6e19e73378f8f9bed5. Need to do the same for exponential.

**Comment by vitaut** [comment]
Exponent notation is done too.

**Comment by t-b** [comment]
I'm coming from #1244.

Unfortunately this is not yet working, or I'm doing something wrong.

```
#include <fmt/format.h>
#include <iostream>

int main() {

std::cout << fmt::format("{:.{}e}", 2.5, 0) << std::endl;
}
```

gives 

```
$ g++ --version
g++.exe (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
g++ -I fmt/include/ -D FMT_HEADER_ONLY test.cpp && ./a.exe
2e+00
```

but using MSVC gives

```
E:\projekte\JSON-XOP\src>cl test.cpp /I fmt/include /D FMT_HEADER_ONLY /EHsc
Microsoft (R) C/C++-Optimierungscompiler Version 19.16.27034 für x86
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

test.cpp
Microsoft (R) Incremental Linker Version 14.16.27034.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj

E:\projekte\JSON-XOP\src>test.exe
3e+00
```

Tested with f675cb88 (Remove redundant cast, 2019-12-08).

**Comment by vitaut** [comment]
Fixed form still uses `sprintf` as a fallback which is why you get different results (MSVC does rounding incorrectly).

**Comment by t-b** [comment]
@vitaut Thanks, but I'm using `e` which is exponential notation or? Could you give me a hint were the  code needs fixing?

**Comment by vitaut** [comment]
> I'm using e which is exponential notation or?

By fixed I meant any of `e`, `f`, `g` and their uppercase counterpart which use a given (fixed) precision as opposed to the default shortest representation where precision is determined by the input.

> Could you give me a hint were the code needs fixing?

Here's where the fallback is called if Grisu gives up:

https://github.com/fmtlib/fmt/blob/598e6042d1cb2d220bf0a868f463634adeaca7d7/include/fmt/format-inl.h#L1073

It needs to be replaced with a fixed-precision equivalent of `fallback_format`:

https://github.com/fmtlib/fmt/blob/598e6042d1cb2d220bf0a868f463634adeaca7d7/include/fmt/format-inl.h#L964

It might be a fair amount of work mostly to generalize `fallback_format` to work with a given precision.

**Comment by vitaut** [comment]
Note that the current behavior is not completely incorrect, it's just that the rounding mode is inconsistent between platforms.

**Comment by t-b** [comment]
@vitaut Thanks for the hints!

**Comment by vitaut** [comment]
{fmt} now uses the correct rounding even on systems with broken `printf` (e.g. Windows):

```c++
  fmt::print("{:.0e}", 2.5);
```
Output:
```
2e+00
```

**Comment by t-b** [comment]
@vitaut Thanks for the fix. I've just tested it and it works now for my use case as well.

FYI: We are using fmt inside https://docs.byte-physics.de/json-xop.
