### ISSUE TITLE
Integer to wchar_t

### ISSUE THREAD

**Issue by mrducks** [fmtlib/fmt#1034]
Apologies if I'm missing something obvious, but I'm attempting to use fmt::format_int to convert integral values to wide characters (wchar_t*) - but it seems this method only supports conversion to narrows characters.

What's the fastest way to achieve this result using fmtlib?

**Comment by vitaut** [comment]
Using `format_int` and copying the result to the wide target will likely be the fastest. You could also use `format_to(out, "{}", n)`.
