### ISSUE TITLE
Sublime Text syntax highlighting

### ISSUE THREAD

**Issue by Kronuz** [fmtlib/fmt#1037]
This is really not an "issue", but I don't know where else to put this... maybe this should be included somewhere in the docs or in the repo.

I created (or rather modified) a Sublime Text syntax definition for C++ with support for fmt formatted strings: https://gist.github.com/Kronuz/8ccba85296587243c3ffa07bb5cb19c8

Simply put it in the `Packages/User` directory (`Preferences -> Browse Packages... -> User`) and select the syntax from `View -> Syntax -> Open all with current extension as...` and select `C++ (fmt)`.

<img width="803" alt="screen shot 2019-02-08 at 3 34 04 pm" src="https://user-images.githubusercontent.com/56894/52507419-156d3980-2bb7-11e9-9bad-0aaa045b9302.png">

**Comment by vitaut** [comment]
This is great! Could you submit a PR adding this syntax definition to the `support` directory and possibly linking somewhere in the README with a note how to use?

**Comment by vitaut** [comment]
I've added the syntax definition to the support directory. Thanks!

**Comment by Kronuz** [comment]
Great! I’ll let you know if I make any other changes to it
