### ISSUE TITLE
Unsafe usage of named arguments

### ISSUE THREAD

**Issue by mikelui** [fmtlib/fmt#1038]
[Named arguments](https://github.com/fmtlib/fmt/blob/5.3.0/include/fmt/core.h#L1342) can be instantiated as follows:

    auto foo = fmt::arg("foo", 10);   

Because `named_arg`s store a reference, we now have a dangling reference in `foo`, and this now invokes undefined behavior if passed to `fmt::format`.

    fmt::print("{foo}", foo); // UB
    fmt::print("{foo}", fmt::arg("foo", 10)); //no problem

I had a use case where there were many args, and it was clearer to instantiate them as variables before passing them to `fmt::print`/`fmt::format`.

Although they _**are**_ called `named_args`, and could imply that they are only to be used _as arguments_, I'm not sure if this is intentional or not. Could either update the documentation to say this depending on whether it is considered user error or a bug.

**Comment by vitaut** [comment]
Well, `fmt::internal::named_arg` is internal for a reason. You are not supposed to use it or any other internal symbol in the library, even if the type name is hidden via `auto` (or should be prepared to face the consequences =)).

**Comment by mikelui** [comment]
True. Couldn't forwarding references be added without too much trouble, though (if hypothetically only C++17 was supported)?

```c++
template <typename T, typename Char>
struct named_arg : named_arg_base<Char> {
  T value;

  template <typename ...Args>
  named_arg(basic_string_view<Char> name, Args&&... args)
    : named_arg_base<Char>(name), value(std::forward<Args>(args)...) {}
};

template <typename T>
inline internal::named_arg<T, char> arg(string_view name, T&& arg) {
  return {name, std::forward<T>(arg)};
}

template <typename T, typename ...Args>
inline internal::named_arg<T, char> arg(string_view name, Args&&... args) {
  return {name, std::forward<Args>(args)...};
}
```

That lets us do:
```c++
auto foo = fmt::arg("foo", 10); // foo now holds an int
fmt::print("{foo}", foo); // no problemo

BigThing thing{};
auto bar = fmt::arg("bar", thing); // can still just hold a reference
fmt::print("{bar}", bar); // would have worked originally, too
```

The downside is that you'd lose some const-safety, and you'd have to change all your existing code to prevent moves:

```c++
fmt::print("{foo}", fmt::arg("foo", ExpensiveToMovePrintable{})); // ☹️ moves instead of using reference 
fmt::print("{foo}", fmt::arg<ExpensiveToMovePrintable>("foo")); // 🙂 perfect forwarding 
```
That's a pretty big downside I guess  😅

**Comment by foonathan** [comment]
What would work is require that the named argument objects are rvalues when passed to a format function.

**Comment by vitaut** [comment]
> Couldn't forwarding references be added without too much trouble, though (if hypothetically only C++17 was supported)?

This would require introducing extra copies which is a non-starter.

> What would work is require that the named argument objects are rvalues when passed to a format function.

Yes, this would work but is easy to work around with explicit moves.

I think having an internal symbol is a good enough even though it could be missed sometimes.

**Comment by vitaut** [comment]
That said I'm open to a PR that introduces argument forwarding and restring named_arg use to rvalues.

**Comment by mikelui** [comment]
@foonathan the issue there is it that it would have to be enforced at a documentation level, and would break currently valid code:

```c++
// is no longer valid
BigThing thing{};
auto bar = fmt::arg("bar", thing);
fmt::print("{bar}", bar);
```

...unless that is *not* valid. From @vitaut's response, it seemed like it is valid as long as it works. 
It would take some minor template wizardry to accomplish. An initial attempt (I'm sure I'm forgetting something):

```c++
template <typename>
struct is_named_arg : std::false_type {};

template <typename T, typename Char>
struct is_named_arg<internal::named_arg<T,Char>> : std::true_type {};

template <typename S, typename... Args>
inline FMT_ENABLE_IF_STRING(S, void)
    print(const S &format_str, Args&&... args) {
  static_assert(std::negation_v<std::disjunction<std::conjunction<std::is_lvalue_reference<Args>, is_named_arg<std::remove_reference_t<Args>>>...>>,
                "lvalue named args are not allowed");
  vprint(internal::to_string_view(format_str),
         internal::checked_args<S, Args...>(format_str, args...));
}

```

**Comment by mikelui** [comment]
> This would require introducing extra copies which is a non-starter.

I'm believe my [previous comment](https://github.com/fmtlib/fmt/issues/1038#issuecomment-462016498) didn't incur any extra copies, just an extra move. All related internal code would have to be modified to make sure `named_arg` was moved instead of copied, however. I haven't looked to much at the other internals, so if copying does happen there that would be a problem. It would create another constraint, that `T` is moveable as well, if `named_arg` s are passed around internally and we want to avoid copies.

**Comment by vitaut** [comment]
This would have an extra copy:
```c++
std::string s = ...;
auto foo = fmt::arg("foo", s);   
fmt::print("{foo}", foo);
```

> I might just submit a documentation PR

Please do.
