### ISSUE TITLE
Formatted output to file

### ISSUE THREAD

**Issue by nordlow** [fmtlib/fmt#1041]
What's the preferred way to perform 'fmt`-formatted output to a file?

Does it have (is it preferred) to be line-based output?

**Comment by vitaut** [comment]
> What's the preferred way to perform 'fmt`-formatted output to a file?

`fmt::print(FILE*, ...)`: http://fmtlib.net/latest/api.html#_CPPv2N3fmt5printEPNSt4FILEERK1SDpRK4Args

> Does it have (is it preferred) to be line-based output?

No, it doesn't. `fmt::print` works similarly to `printf`, just uses a different format string syntax and you can use it in the same way.

**Comment by nordlow** [comment]
Great, thanks!
