### ISSUE TITLE
Proposal: Add support for COM strings(CComBSTR)

### ISSUE THREAD

**Issue by AlexeyBudko** [fmtlib/fmt#1042]
It would great if it is possible to create COM string directly without intermediate conversion from std::[w]string.

Current:
`const std:string formattedString = fmt::format("Cool to format {} strings directly", "COM");
CComBSTR myComString(formattedString.c_str());`
Proposal:
`const CComBSTR myComString= fmt::format("Cool to format {} strings directly", "COM");

Thank you!

**Comment by vitaut** [comment]
Supporting COM types is out of scope of this library, but you can easily write such formatting function yourself, something along the lines of:

```c++
template <typename... Args>
CComBSTR bstr_format(fmt::string_view format, const Args&... args) {
  fmt::memory_buffer buf;
  fmt::format_to(buf, format, args...);
  return {buf.data(), buf.size()};
}

CComBSTR formattedString = bstr_format("Cool to format {} strings directly", "COM");
```
