### ISSUE TITLE
fmt library in the context of logging

### ISSUE THREAD

**Issue by skgbanga** [fmtlib/fmt#1044]
Hello,

Thanks for this great library.

First, I am aware of https://github.com/gabime/spdlog which builds on `fmt` to provide fast logging. One of the things `spdlog` does is this:

```
    try
    {
        using details::fmt_helper::to_string_view;
        fmt::memory_buffer buf;
        fmt::format_to(buf, fmt, args...);
        details::log_msg log_msg(source, &name_, lvl, to_string_view(buf));
        sink_it_(log_msg);
    }
```
More details: https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/details/logger_impl.h#L68

So `spdlog` formats the messages in the "fast" path and then transfer the buffer to a background thread (in async mode) to be written to a file later. 

In my opinion, this is suboptimal for user defined types which have relatively expensive `<<` operators. One example would be IP Address. 

```
std::ostream& operator<<(std::ostream& os, const IPAddr& a) {
  char str[INET_ADDRSTRLEN];
  inet_ntop(AF_INET, &a.addr, str, INET_ADDRSTRLEN);
  return os << str;
}
```

IPV4 address is a 32 bit number internally, but for representation uses `1.1.1.1` format. 

I think, one way in which these cases can be sped up is if we totally relegate the tasks of formatting to a background thread after memcpying all the needed information. (for custom types, this would mean copying over ostream function pointer to the background thread)

e.g. for a call like this:

```
LOG(INFO, "this is a {} msg', foo);
```

I will copy over `"this is a {}`, `foo`'s memory and `foo`'s streaming operator to an spsc queue and then call something like `fmt::internal::parse_format_string(format_str, custom_handler)` to get the final string. 

What do you think about this? Are there some kind of customization points that I can hook into to achieve the above stated?

Thanks for any pointers!

**Comment by skgbanga** [comment]
Or alternatively, any place where I can read more about this visitor interface. e.g. what is passed and when are these functions called. 

```
struct Handler : fmt::internal::error_handler {
  using Char = char;
  void on_text(const Char*, const Char*) { std::cout << "on text\n"; }

  void on_arg_id() { std::cout << "on arg id\n"; }
  void on_arg_id(unsigned id) { std::cout << "the id is " << id << '\n'; }
  void on_arg_id(fmt::basic_string_view<Char>) {
    std::cout << "on arg in string view "
              << "\n";
  }

  void on_replacement_field(const Char*) {
    std::cout << "on replacement field\n";
  }

  const Char* on_format_specs(const Char*, const Char*) {
    std::cout << "on format specs\n";
    return nullptr;
  };
};
```

**Comment by skgbanga** [comment]
Okay, I went through the source code of `fmt` and I think I understand what to do. 

Here is a quick summary of what I understand. 

`format_arg_store` copies all the user-supplied arguments on to the stack. It contains an array of `value_type` which could either be `value` or `basic_format_arg`  depending upon whether a number of arguments is less than 16 or not. 

`format_arg_store` is then passed into a type-erased `basic_format_args` which contains just references/pointers to the data stored in `format_args_store`. 

IF I can construct `basic_format_args` from storage of my choice such that `do_get` works correctly, the rest of the machinery should work along with it. That said, this is not an easy undertaking, and I will probably skip and live with my non `fmt` logger right now. :)

(this would also require adding a templated constructor to `basic_format_args` which is templatized on Storage, and initializes `values_` correctly)

btw, one minor point that I noticed:

```
auto store = fmt::make_format_args(1, 2, 3);
//  size of store, in this case, is 48 bytes. 16 byte for each of the value
```

```
auto store = fmt::make_format_args(1, 2, 3...16)
// size of store in this case if 576 bytes. 32 bytes for each of the `basic_format_arg` constructed`
```

Presence of `internal::type` (which is 4 bytes, although could be only 1 byte) in `basic_format_args` increased the size to 32 bytes (since it is not packed). I think you can use `__attribute__((packed))` to get some space saving. 


Please feel free to close the ticket.

**Comment by vitaut** [comment]
> I think, one way in which these cases can be sped up is if we totally relegate the tasks of formatting to a background thread after memcpying all the needed information. What do you think about this?

This might be as (or more) expensive as formatting because you'd have to copy objects as well as the format string, but it might be worth exploring.

> Are there some kind of customization points that I can hook into to achieve the above stated?

You can capture the arguments and the format string in a tuple and pass them around for later formatting as explained in https://github.com/fmtlib/fmt#faq. You don't need to plug into the argument handling machinery.

**Comment by rpopescu** [comment]
@vitaut : am I wrong in thinking this doesn't work correctly where an argument type is a pointer or reference that will not outlive the actual formatting?

**Comment by vitaut** [comment]
> am I wrong in thinking this doesn't work correctly where an argument type is a pointer or reference that will not outlive the actual formatting?

You are right, `format_args` assumes that arguments outlive the formatting call and avoid potentially expensive copying.

**Comment by rpopescu** [comment]
Thank you for confirming that.
The scenario, to clarify, is deferring formatting to a separate thread. Even if we have a mix of trivially copyable arguments with a no-lifetime-issues arguments, how would a logging framework such as spdlog be able to employ this?
If we memcpy the resulting tuple onto an inter-thread queue, on the other side we simply have bytes, and no type information - no way to get the right tuple back, use std::apply etc.
If we traverse the argument list we could use typeid and encode a series of (type, value)s.
Has anyone tried this?

**Comment by vitaut** [comment]
You'll need to capture arguments (e.g. in a tuple) and have some way to erase and recover type information, e.g.

```c++
struct message {
  virtual void log() = 0;
};

template <typename... Args>
struct typed_message {
  std::string format_str;
  std::tuple<Args...> args;

  void log() override {
    fmt::print(format_str, args...);
  }
};
```

Then you can construct message in one thread and pass it to another for actual logging.

**Comment by rpopescu** [comment]
Right, that's what I thought was the other option - generate the formatting function for each specific set of argument types. This could be quite expensive in compile time and code size, compared to the other option.
Thank you kindly for your input!
