### ISSUE TITLE
{fmt} can format custom type, but not with e.g. "{: ^18}"

### ISSUE THREAD

**Issue by dpacbach** [fmtlib/fmt#1047]
I am observing behavior where {fmt} is rejecting a format specifier _only for a custom type_.  Details: I have a simple custom type, along the lines of `struct Point { int x; int y; };` and I have formatter specialization for it that allows me to format it:

`fmt::format( "{}", Point{3,4} ); // yields "(3,4)"`

which works fine.  However, as soon as I supply a more complicated format specifier such as this:

`fmt::format( "{: ^10}", Point{3,4} ); // runtime error: unknown format specifier`

I would expect the above to just print: `"   (3,4)  "`, but instead I get an "unknown format specifier" error.  I know that the format specifier is fine because the following works:

`fmt::format( "{: ^10}", 3 ); // prints: "    3     "` (i.e., the number 3 padded with 9 spaces).

Is this expected?

**Comment by vitaut** [comment]
How did you implement your `formatter` specialization?

**Comment by dpacbach** [comment]
Thanks for the reply; here is my testing code to reproduce it:

```
struct Point {
  int x;
  int y;
};

namespace fmt {
template<>
struct formatter<Point> {
  template<typename ParseContext>
  constexpr auto parse( ParseContext& ctx ) { 
    return ctx.begin();
  }
  template<typename FormatContext>
  auto format( const Point& o, FormatContext& ctx ) { 
    return format_to( ctx.begin(), "({},{})", o.x, o.y );
  }
};
} // namespace fmt

void test_fmt() {
  fmt::print( "{}", Point{3, 4} ); // works
  fmt::print( "{: ^10}", 3 ); // works
  fmt::print( "{: ^10}", Point{3, 4} ); // runtime error
}
```

the `test_fmt()` function produces a runtime error on its third line.

**Comment by dpacbach** [comment]
Oh forgot to mention, I am using version 3f52336e6c4e87fa6ffc7168577d0d8fe6cf7866.

**Comment by vitaut** [comment]
Your parse method doesn't parse anything which is why only the empty input is accepted. A simple way to implement a `formatter` is to reuse one of the standard specializations, e.g.

```c++
#include <fmt/format.h>

struct Point {
  int x;
  int y;
};

template<>
struct fmt::formatter<Point> : formatter<std::string> {
  template<typename FormatContext>
  auto format(const Point& o, FormatContext& ctx) {
    return formatter<std::string>::format(fmt::format("({},{})", o.x, o.y), ctx);
  }
};
```

**Comment by dpacbach** [comment]
Thank you, that fixed it!
