### ISSUE TITLE
Partial formatting

### ISSUE THREAD

**Issue by epruesse** [fmtlib/fmt#1048]
Partially formatting a template string with only those parameters provided, leaving the replacement fields that cannot be filled untouched comes in handy occasionally, to avoid passing parameters around and re-formatting recurring parts of a string over and over.

I'm guessing an implementation wouldn't be too hard, but my understanding of fmtlib internals is limited at this point. I was picturing the following api:

```c++
auto tpl = "[{time:%T}] {user}@{host}: {msg}";
auto user_tpl = fmt::partial_format(tpl, fmt::arg("user", "Arthur"),
                                         fmt::arg("host", "titanic"));
// user_tpl = "[{time:%T}] Arthur@titanic: {msg}";
fmt::print(user_tpl, fmt::arg("time", now()), fmt::arg("msg", "What was the question?"));
```

The example is somewhat constructed. I see a number of use cases though:
 - performance - format strings containing a lot of mostly unchanging replacement fields could be simplified
 - separation - in the case above, the code calling `print` might only know the user by its ID and have no knowledge of host at all
 - robustness - an unexpanded `{argname}` can be preferable over an exception

**Comment by vitaut** [comment]
You could probably implement this reusing {fmt}'s format string parser and argument handling machinery, but I don't think it's generally useful enough to be worth the implementation complexity and inclusion in the library.

**Comment by mirzadeh** [comment]
I tried something like this using regex. Do you think it might be helpful? Or am I missing corner cases?
```c++
#include <string>
#include <regex>
#include <iostream>

#include <fmt/format.h>

template <typename Char, typename T>
inline std::string partial_format(const std::string& str, const fmt::detail::named_arg<Char, T>& arg)
{
    // This will match an argument of format {arg} or {arg:format_spec}
    const auto format_spec = "(:[^}]*)?";
    std::regex argexp(std::string("\\{") + arg.name + format_spec + "\\}");
    std::smatch sm;
    if (!std::regex_search(str, sm, argexp)) {
        throw std::invalid_argument(fmt::format("Could not find {} in {}.", arg.name, str));
    }

    return std::regex_replace(str, argexp,
        fmt::format(sm[0].str(), fmt::arg(arg.name, arg.value))
    );
}

template <typename Char, typename T, typename... Args>
inline std::string partial_format(const std::string& str, const fmt::detail::named_arg<Char, T>& arg, Args... args)
{
    return partial_format(
        partial_format(str, arg), args...
    );
}


int main()
{
    std::string filepath = "/path/to/Foo-{foo}/Bar-{bar:03d}/Baz-{baz}";
    fmt::print("{}\n",
        partial_format(filepath,
            fmt::arg("foo", "folder"), fmt::arg("bar", 42)
        )
    );
    return 0;
}
```

example: https://godbolt.org/z/6f3GzfMG9
