### ISSUE TITLE
Clarify docs re  fmt::make_format_args

### ISSUE THREAD

**Issue by epruesse** [fmtlib/fmt#1049]
It might be worthwhile to make it very clear in the documentation that `make_format_args` will not make copies of **anything**, including `named_arg` arguments created on-the-fly with `fmt::arg()`.

This looks good naively, will compile, and will actually (seem to) work correctly:

```c++
auto args = fmt::make_format_args(fmt::arg("key", value))  // BROKEN
auto msg = fmt::vformat("--{key}--", args);
```

It does, however, dereference parts of the stack that have been freed already...

Correct would be:
```c++
auto key_arg = fmt::arg("key", value);
auto args = fmt::make_format_args(key_arg);
auto msg = fmt::vformat("--{key}--", args);
```

**Comment by vitaut** [comment]
http://fmtlib.net/dev/api.html#_CPPv2N3fmt16make_format_argsEDpRK4Args already says that the returned object stores references 

> Constructs an format_arg_store object that contains references to arguments and can be implicitly converted to format_args.

but it might be worth clarifying further. PRs are welcome.

**Comment by mikelui** [comment]
Added documentation in #1051

**Comment by epruesse** [comment]
Thanks @mikelui
