### ISSUE TITLE
Add casting operators support

### ISSUE THREAD

**Issue by Kronuz** [fmtlib/fmt#1053]
I've found that `operator<<` used by the `fallback_formatter` is not enough for some cases. For instance, some of my objects are actually integers or floats (internally), and if I do `fmt::format("{:x}", obj);` that fails with "**format specifier requires numeric argument**".

Instead of only relying on `operator<<`, I propose using casting operators as well. I tried adding `operator int` to my object, it seems to work, but only if I don't have the `operator<<` or I don't include `fmt/ostream.h`... additionally, I couldn't make it work for `operator std::string`.

**Comment by vitaut** [comment]
Relying on casts has a number of problems with lifetime and ambiguities, but you can format one type as another in the following way:

```c++
struct int_like {
  int value;
};

template <>
struct fmt::formatter<int_like> : fmt::formatter<int> {
  auto format(int_like il, format_context& ctx) {
    return fmt::formatter<int>::format(il.value, ctx);
  }
};
```
