### ISSUE TITLE
Issues with fmt::format_to_n()

### ISSUE THREAD

**Issue by Devenec** [fmtlib/fmt#1056]
After running the following code

    char buffer[32];
    const fmt::format_to_n_result<char*> result = fmt::format_to_n(buffer, sizeof(buffer), "{}", 'A');

`result.size` is 0 when it should be 1.

Also, when changing the format string from `"{}"` to `"{} "` (adding a single space), `result.size` is 1 when it should be 2, and the contents of `buffer` is `" "` (a single space) following garbage as it's not null-terminated.

The {fmt} code running is from commit a97757736b8e4cf7ae5a911b9455fdcbae76563a and built with Visual Studio 2017 15.9.5 v141 toolset.

**Comment by abolz** [comment]
Seems like the output iterator is not incremented [here](https://github.com/fmtlib/fmt/blob/a97757736b8e4cf7ae5a911b9455fdcbae76563a/include/fmt/format.h#L2758):
```c++
*reserve(1) = value;
```
Changing this line to
```c++
auto&& it = reserve(1); *it++ = value;
```
fixes the issue, but I haven't run any other tests.

**Comment by abolz** [comment]
Has been changed in https://github.com/fmtlib/fmt/commit/f6fd38bb3ac22faf04a018d938ba0764644f1dce#diff-93ae8f33d84a6b0b08a62dc9a50f6b85L2344

**Comment by vitaut** [comment]
@abolz, that's probably it, thanks for investigating. Could you by any chance submit a PR with a small regression test?

**Comment by abolz** [comment]
Yes, sure.
