### ISSUE TITLE
How to change decimal point for FP numbers formatting?

### ISSUE THREAD

**Issue by uentity** [fmtlib/fmt#1057]
I have a simple task -- format floating point numbers in uniform way with dot decimal point regardless of locale used. What's a proper way to do that with `fmt::format`?

Documentation contains literally nothing on how to specify/change locale used by `fmt`, it only states that formatting of FP numbers is locale-dependent. I understand that if I change global locale it should affect the result produced, but this is a rather inconvenient way for me (I want to keep locale for application and just format numbers with dot decimal point in one dedicated task).

Even after searching through `fmt` source code I couldn't figure out the source it takes decimal point from. I will discover it eventually but maybe there's a simple answer that I just missed.
Thanks in advance.

**Comment by vitaut** [comment]
You can get a "C" locale and pass it to a format function as described in https://github.com/fmtlib/fmt/releases/tag/5.3.0 (section "Improved locale support").

**Comment by vitaut** [comment]
The next version of the library will also have locale-independent floating point formatting by default.

**Comment by uentity** [comment]
Oh, thanks for pointing that out.
I'm using `fmtlib` bundled with `spdlog` and forgot to update to recent version. That's why I was missing locale-related futures you mentioned.

And yes, I agree that locale-independent FP formatting should be the default. BTW maybe this behaviour can be turned on in current revision?

**Comment by vitaut** [comment]
> BTW maybe this behaviour can be turned on in current revision?

This behavior is already on in the `master` branch for IEEE754 floating point.

**Comment by uentity** [comment]
@vitaut did come testing, and this line:
```
fmt::format(std::locale::classic(), "{}", 3.14);
```
**did not** produce correct result (dot as decimal line) on `fmtlib` 5.3.0.
Master revision produces dot with both classic locale and without it at all.

This result forces me to switch to maintaine separate submodule for `fmtlib`. But maybe its for good :smiling_imp:

**Comment by uentity** [comment]
@vitaut I don't know, but I couldn't reproduce a case when decimal point changes depending on locale passed. All variants to call `fmt::format()` (with some locales or without) produce identical decimal point (which is dot in latest master revision).

**Comment by vitaut** [comment]
My bad. I double checked and the locale is not hooked into the floating-point formatting at the moment.

**Comment by Malayka** [comment]
@vitaut, hi! Can feature of "passed as arg locale"-dependent decimal separator be added to library? It would be great if yes.
At least, it's quite strange to see that thousands separators can be defined by locale, when decimal separator is not).

**Comment by vitaut** [comment]
> Can feature of "passed as arg locale"-dependent decimal separator be added to library?

Yes, it will be added.

**Comment by vitaut** [comment]
Floating point formatting is locale-independent now with `'.'` always used as a decimal point. A specifier for locale-dependent formatting will be added separately.
