### ISSUE TITLE
Yabut, exception etc.

### ISSUE THREAD

**Issue by stayprivate** [fmtlib/fmt#1065]
I quickly browse the Proposed Paper, found no reference to what I'm about to mention. Sorry if it was discussed else where.

<editorial>
As new feature are added to the language, we are encouraged to used them. Yet many off them do not fully cover the range of features that their predecessor offered. That's why, during conversation about C++ 11,14,... I often sentences start with yabut (Yes but).  This is a post about such case.  I really want to use fmt, but there is a case of yabut.
</editorial>

I can just picture an intern being task with replacing all stream operation, snprintf, etc with fmt::. There be major gain in readability, and often performance.  However there is one big risk that really concerns me. That a lone fmt::print, that is skipped during testing andcode coverage, has mismatched number of {} and argument, resulting in an exception that will disrupt program operation. In many cases it might be a good thing. I'm more worried about not critical cases where data is logged or print to screen, don't want to have a machine stop because of a missing {}. It's possible to check for that at compile time with extra code. IMHO it reduces readability and there no way to enforce it.  Streams do not suffer from this issue, snprintf on the other hand is vulnerable, to various degree, to similar issues. That brings me to the point  I'm attempting to make, the yabut case. Although snprintf is dangerous, these days it's not really an issue because compilers will check snprintf/printf arguments and show warnings. That's a peace of mind I see loosing with fmt.  So I was wondering if these checks done by compiler can be added to format proposal paper, forcing C++20(?) compilers to implement such a feature. That's assuming and hoping C++ standard covers compiler behaviour.  

See I want our team to use fmt:, but I can picture management coming back to me after a customer had some downtime because of a missing/extra {}, asking my why we did not stick to printf/snprintf.  For now I have disabled exception in the format lib and that may do the job, but I get the feeling C++20 implemenationf format will not.

Hope I'm making sense ;-)

**Comment by vitaut** [comment]
You cannot force compile-time checks because support for runtime format strings is essential for some use cases such as translation. However, it's easy to implement a wrapper function that intercepts exceptions and does something else in case of an error. For literal format strings, there are plans to make compile-time checks the default in the future. This will require some changes to the language, e.g. parametric expressions or `constexpr` arguments.

**Comment by stayprivate** [comment]
> You cannot force compile-time checks because support for runtime format strings is essential for some use cases such as translation.

This statement also applies to printf, yet it does not prevent current compiler from checking literal string anyway.

> However, it's easy to implement a wrapper function that intercepts exceptions and does something else in case of an error

Might be easy, but it's error prone, time consuming and create noise in the code. 

> For literal format strings, there are plans to make compile-time checks the default in the future. This will require some changes to the language, e.g. parametric expressions or constexpr arguments.

Great news, but in the mean time, sounds to me like it's less work to have the compiler do it, a la printf, Would not have to wait a couple of years for safer code.

Thanks for your contribution.
