### ISSUE TITLE
Generic exception message from mismatched arg count

### ISSUE THREAD

**Issue by fredlas** [fmtlib/fmt#1070]
I was just debugging a mysterious uncaught exception, with message "argument index out of range". Ultimately it turned out to be an existing fmt::format() that I had removed an argument from, but forgotten to remove the corresponding {}. Usually you'd expect people to be paying attention to what their string actually is, but in this case it was just "{}.{}.{}.{}".

Although #295 would be ideal, if that's not possible, could fmt at least have run-time errors like this clearly indicate that they're coming from fmt? If catching and rethrowing standard exceptions like this is too messy to be worth it, I understand, since this is kind of a user stupidity corner case. But, please consider it!

**Comment by vitaut** [comment]
Is the type of exception (`format_error`) not enough?

**Comment by vitaut** [comment]
I think massaging the error message would be too messy. You can identify the source of the error by type of stack trace.

**Comment by fredlas** [comment]
Actually, in this case there was a different stack trace getting printed - fmt::format, and what was calling it, were not in there. I guess that is also another corner case aspect, though.
