### ISSUE TITLE
Formatting for fixed-width with _two_ decimal places is resulting in _three_

### ISSUE THREAD

**Issue by tonyelewis** [fmtlib/fmt#1072]
I expect the expression:

~~~cpp
fmt::format( "{:.2f}", 0.01 )
~~~
&hellip;to result in `"0.01"s` but it's returning `"0.010"s`.

Thanks for all your hard work on this excellent library and on standardising it.

**Comment by tonyelewis** [comment]
In another example, I expect the expression:

~~~cpp
fmt::format( "{:7.3f}", 1E-35F )
~~~

&hellip;to result in `"  0.000"s` <sup><sub>(two spaces)</sub></sup> but it's returning `"1.00e-35"s`. Am I misunderstanding `f`?

**Comment by tonyelewis** [comment]
In case I _am_ misunderstanding&hellip;

The above two results are consistent with the number between the `.` and the `f` specifying the fixed-width's number of _significant figures_ rather than _decimal places_. But the [docs](http://fmtlib.net/latest/syntax.html#format-specification-mini-language) say it indicates:

> how many digits should be displayed after the decimal point

&hellip;and the expression:

~~~cpp
::fmt::format( "{:.2f}", 0.01F )
~~~

&hellip;returns `"0.01"s`.

**Comment by vitaut** [comment]
Thanks for reporting. The new floating-point formatting algorithm is being integrated into the `master` branch thus some temporary formatting weirdness. This will be addressed soon and in the meantime I recommend using one of the stable releases.

**Comment by vitaut** [comment]
I've also disabled the new algorithm for fixed formatting for now: https://github.com/fmtlib/fmt/commit/d560ddac25809020157ca98e6b3f55190a12774c, so your examples should produce expected results.

**Comment by tonyelewis** [comment]
Ah, OK. Thanks for the quick response and for fixing `master`. I've reverted to `5.3.0` and my tests now pass cleanly. I'm happy for this issue to be closed.

Again thanks for all you work on the library and on standardisation.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/3466d9c8451b7835af01539c100b0637f8c284d4 and https://github.com/fmtlib/fmt/commit/49d244c06582977491024ba15bb1663316fd2d05.

**Comment by tonyelewis** [comment]
Great stuff. Thanks for addressing this so quickly.
