### ISSUE TITLE
decimal type support on IBM i (AS/400) 7.3 ILE C++ compiler

### ISSUE THREAD

**Issue by kunichik** [fmtlib/fmt#1076]
IBM i compiler sptintf supports %D(n,m) format tag 
where n - numbers to comma, m - after.

and when I write:
```cpp
#include <decimal.h> //  IBM ILE C++ type 

decimal(15,0) amount = 1245;
std::sprintf("amount is %D(15, 2)", amount);
```
I get output:
> amount  is 12,45

can i get something like this with {fmt} ?

**Comment by vitaut** [comment]
You can do something like this by implementing a custom formatter for the decimal type using the extension API: http://fmtlib.net/latest/api.html#formatting-user-defined-types
