### ISSUE TITLE
Support systems without wchar.h / std::wstring

### ISSUE THREAD

**Issue by RedDwarf69** [fmtlib/fmt#1077]
I know it's hard to believe, but I do have a system with C++11 support... but no wchar.h in its C standard library, which makes GNU libstdc++ build correctly but without wstring.

Would it be possible to add a flag to disable wchar/wstring support from fmt, so it can be used in such a system?

**Comment by vitaut** [comment]
> Would it be possible to add a flag to disable wchar/wstring support from fmt, so it can be used in such a system?

If you are willing to do the work then sure =). It should be mostly a matter of adding a conditionally compiled type alias for `wchar_t` in https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h.

**Comment by vitaut** [comment]
Closing as there are no current plans to support this, but PRs are welcome.
