### ISSUE TITLE
Bikeshedding opportunity: modules

### ISSUE THREAD

**Issue by DanielaE** [fmtlib/fmt#1082]
I can do this now:

```
import fmt;

#include <iterator>

struct implicitly_convertible_to_string_view {
  operator fmt::string_view() const { return "foo"; }
};


int main() {
  auto result = fmt::format("{}", 42);
  fmt::format_to(std::back_inserter(result), "{}", 42);
  result = fmt::format("{}", implicitly_convertible_to_string_view());
}
```

Module `fmt` is created from the "regular" {fmt} headers using this module interface (Modules-TS syntax and semantic):
```
#include <cassert>
#include <cctype>
 ...
#include <type_traits>
#include <vector>

export module fmt;

#include "fmt/core.h"
#include "fmt/format.h"
#include "fmt/locale.h"
#include "fmt/ostream.h"
#include "fmt/printf.h"
#include "fmt/chrono.h"
#include "fmt/prepare.h"
#include "fmt/ranges.h"
#include "fmt/color.h"
```
Before I proceed with tagging the **true** interface function, types, etc. I'd like to bring up the following questions to discussion: 

- the **true** interface entities are tagged by preceding them with a macro `FMT_MODULE_EXPORT` like in
```
FMT_MODULE_EXPORT
template <typename Char> class basic_string_view {
 ...
};
```
  another name might be the more generic name `FMT_INTERFACE`. Any preferences?

- the module interface source file is called `fmt.ipp` located in subdirectory `src`. In VisualStudio parlance its preferred name is `fmt.ixx`, but in the discussions on the SG15 mailing list I've also seen names along the line of `fmt.cppm`. I am neutral in this regard and have therefore chosen neither of those, but selected a file extension which is treated as a C++ file in the VS ide. Putting this module interface source file into the `src` subdirectory rather than into the `include` subdirectory is based on the fact, that it needs to be compiled just like any other C++ TU. In fact, I generate a single `fmt.lib` from `fmt.ipp` and `format.cc` as in the non-module case. (Authoring and consumption of a module in VisualStudio/MSBuild is just the same as authoring and consumption of an old-fashioned static lib) . Any objections to this choice?

- In the module interface as shown above I've pre-included all headers before the module purview. Therefore their contents are not transitively made visible (because they are mentioned in the declarations of exported entities in the `fmt` module) when importing module `fmt`. Therefore I need to include header `iterator` in the example above. Otherwise, without pre-including all required headers before the module purview, I no longer need to include `iterator`. I am not exactly sure which semantic is nearer to the semantics of upcoming C++20 modules. Any thoughts on this?

**Comment by vitaut** [comment]
Very cool!

> Any preferences?

I'd go with `FMT_EXPORT` because it's shorter and closer corresponds to what it's expanded to (IIUC).

> Any objections to this choice?

No, we can always rename following whatever convention becomes widespread.

> Any thoughts on this?

I think it's reasonable not to overexport. If users want to use `back_inserter`, they should include/import `<iterator>`, not get it from {fmt}.

**Comment by vitaut** [comment]
BTW could you review [CONTRIBUTING.md](https://github.com/fmtlib/fmt/blob/ebec00138bd10e949ff34955bcb096387cd32acc/CONTRIBUTING.md), particularly the part about licensing, and comment here whether you agree with it being applied to your contributions, both past and future?

**Comment by DanielaE** [comment]
> I'd go with `FMT_EXPORT`

Unfortunately, `FMT_EXPORT` is already taken up (core.h, line 182):
```
#ifdef FMT_EXPORT
  define FMT_API __declspec(dllexport)
#endif
```

**Comment by vitaut** [comment]
We can rename the old `FMT_EXPORT` to something else e.g. `FMT_DLLEXPORT`. It's next to useless anyway.

**Comment by DanielaE** [comment]
Right. I will update my tags accordingly.

BTW, what's your opinion on the 'naked' throw statements in color.h, lines 289/298 and 318/327? Even the latest version of the msvc compiler 'honors' throwing from a `constexpr` function within the module purview with this nice message
```
d:\agent\_work\3\s\src\vctools\Compiler\CxxFE\sl\p1\c\ModuleWriter.cpp:4701: sorry: not yet implemented
```
and an ICE. :cry:
```
1>E:\fmt\vs\fmt\fmt.ipp(43,1): error C1001:  An internal error has occurred in the compiler.
1>E:\fmt\vs\fmt\fmt.ipp(43,1): error C1001: (compiler file 'd:\agent\_work\3\s\src\vctools\Compiler\CxxFE\sl\p1\c\ModuleUtilities.h', line 25)
1>E:\fmt\vs\fmt\fmt.ipp(43,1): error C1001:  To work around this problem, try simplifying or changing the program near the locations listed above.
1>E:\fmt\vs\fmt\fmt.ipp(43,1): error C1001: Please choose the Technical Support command on the Visual C++
1>E:\fmt\vs\fmt\fmt.ipp(43,1): error C1001:  Help menu, or open the Technical Support help file for more information
```
This is the only place in {fmt} with such a construct.

**Comment by vitaut** [comment]
> BTW, what's your opinion on the 'naked' throw statements in color.h, lines 289/298 and 318/327?

Well, we need to report an error there. Any suggestions how to workaround?

> This is the only place in {fmt} with such a construct.

Don't we throw in error handlers as well?

**Comment by DanielaE** [comment]
I haven't drawn final conclusions here. So far I am still in the process of investigating the ICE and creating an actionable code snippet for Microsoft to work on. My list of 'to be filed errors' is growing every day, and so does my knowledge to work around some of them. And then, VS2017 behaves much worse than VS2019. It feels pretty much like unchartered territory.

**Comment by vitaut** [comment]
I guess this can be closed now since bike-shedding opportunities have been discussed.
