### ISSUE TITLE
A problem about fmt::sprint

### ISSUE THREAD

**Issue by BIT-LQX** [fmtlib/fmt#1090]
I have already install fmt in the directory /usr/local/include. But when I $make, it reported error:‘sprintf’ is not a member of ‘fmt’. What happens and how can I fix it?Thanks a lot if you could share some advice!

**Comment by vitaut** [comment]
You should include `<fmt/printf.h>`. If you already do this please provide an example to reproduce the error.

**Comment by vitaut** [comment]
Closing for now but feel free to reopen with more details if the above comment didn't help.
