### ISSUE TITLE
Which header to use for format_to(OutputIterator)

### ISSUE THREAD

**Issue by Sarcasm** [fmtlib/fmt#1095]
I saw some noticeable difference in compile time between `fmt/core.h` and `fmt/format.h`.
So I try to include `fmt/format.h` very sporadically.

I used `fmt::format_to(OutputIterator it, ...)` in a file which included only `fmt/core.h`, and everything worked fine with GCC 6.3.1 (and `-std=c++11`).
Then, when switching to Clang 5.0.0 (and `-std=c++11`, and using the same stdlib as GCC, not libc++) for the build of my project (not fmt's build, which I didn't recompile in this case),
I got some link errors complaining about missing symbol.

If I use the `fmt/format.h` header, the link error disappear and the code works on both compiler.

So I'm wondering what is the right header to use for `fmt::format_to()`: `fmt/core.h` or `fmt/format.h`?

**Comment by vitaut** [comment]
In general you should include `fmt/format.h` for `format_to`. There is an overload in `fmt/core.h` but only for `back_insert_iterator`s of some containers with contiguous storage.

**Comment by Sarcasm** [comment]
Ok thank you.

FWIW, I was using a `std::back_inserter(str)` on an `std::string`.
