### ISSUE TITLE
snprintf incorrect format vs2017 ?

### ISSUE THREAD

**Issue by gerald5867** [fmtlib/fmt#1096]
Hello i tested fmt::snprintf on vs 2017 like this:

```
	char test[512];
	char test2[512];
	char test3[512];
	auto res = (fmt::snprintf)(test, 512, "hallo mein name ist : %s und ich bin %d jahre alt", "johnny", 43);
	std::cout << test << std::endl;
	auto res2 = (fmt::snprintf)(test2, 512, "%d", 43);
	auto res3 = (fmt::snprintf)(test3, 512, "%s", "Johnny");

```
The first one does only remove %s and %d resulting in 
`hallo mein name ist :  und ich bin  jahre altÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌ`

The other two replace the format specifier correctly with their value.
Also neither of them does a null termination? 

Am i missing something ? shouldnt fmt::snprintf work exactly like std::snprintf?

IDE Version was Visual Studio 201715.8.4

**Comment by vitaut** [comment]
Thanks for the bug report.

`snprintf` looks quite broken and, thinking more of it, it doesn't provide any value (it's kind of an optimization over `sprintf`, but you should use format functions if you care about performance, not `s(n)printf`), so I removed it. Either use `format_to_n`:

```c++
auto res = fmt::format_to_n(test, 512, "hallo mein name ist : {} und ich bin {} jahre alt", "johnny", 43);
// test contains "hallo mein name ist : johnny und ich bin 43 jahre alt"
```
or use `sprintf` and truncate the output.

Note that `format_to_n` doesn't write terminating NUL so you should either do it yourself our make a `string_view` out of data and size.
