### ISSUE TITLE
color specifiers for different parts of the message

### ISSUE THREAD

**Issue by dsvi** [fmtlib/fmt#1100]
Would it be nice if it was possible to do the following:
`print("normal text {italic}{fg_red}followed by emphasis {0} with argument {normal}and then back to normal.", 1);`
![example](https://user-images.githubusercontent.com/23555438/55275833-2b68c200-52fd-11e9-94de-7679f5c5b541.png)
in one format string, rather then having to call `print` a few times for different colors?
Also, calling `print` a few times does not fit well with internationalization. some languages may have different word order.

**Comment by vitaut** [comment]
Implementing any soft of markup is out of scope of the library, but you can do the same by recursive application of colored format.

**Comment by foonathan** [comment]
I have an idea that would allow a non-intrusive way to do that: We could implement a formatter for `text_style`, that way the example would be:

```
fmt::print("normal text {} followed by emphasis {} with argument {} and then back to normal", fmt::emphasis::italic | fg(fmt::color::red), 1, fmt::reset)`
```

(There would also need to be a fmt::reset I think)

**Comment by dsvi** [comment]
@foonathan that approach, even though, chattier, will have an advantage of  colors being easily configurable by user, rather than "hardcoded" to application.
An app may take them from system wide color scheme for example. 

@vitaut 
> any soft of markup is out of scope of the library

you kind of already have markups in 5.3 anyway ;)

**Comment by vitaut** [comment]
> you kind of already have markups in 5.3 anyway

Only if you consider C++ a markup language =). Customizing console output is borderline unrelated, but extending formatting language for styling is definitely out of scope. The infrastructure is reusable so you can add any form of markup on top of {fmt}. It doesn't have to live in the library itself.

**Comment by dsvi** [comment]
@vitaut what do you think about @foonathan's proposal?

**Comment by vitaut** [comment]
I have mixed feelings about it. On the one hand it's non-intrusive and simple to implement. On the other hand it mixes styling options with real arguments. Would be nice to see the real-world examples of the code that needs this before going into the API design.

**Comment by dsvi** [comment]
@vitaut pretty much anything that benefits from colors and string formatting together. clang for example ;)

**Comment by jeremyong** [comment]
Hey @vitaut, finding this late but I'm a fan of @foonathan 's proposal. I would make a change which wraps the object being printed in a style. For example:

```c++
    fmt::print("{} is red but {} is blue and italicized",
        fmt::fg(fmt::colors::red) | "Wine",
        fmt::fg(fmt::colors::blue) | fmg::emphasis::italic | "the ocean");
```

The main benefit is to provide immediate visual clarity to a section of the string (an error code or some other fragment) *without* needing to pollute the markup with extraneous braces.

The other benefit of this implementation is that the meta-formatter (which wraps a style and delegates the formatting to another type) automatically composes with `format_to`, `print`, and all the other format functions.

**Comment by jeremyong** [comment]
I've created proposal #1333 which implements the above idea as a quick sketch called "styled objects."

**Comment by vitaut** [comment]
Replied on #1333.
