### ISSUE TITLE
error C2084: function 'fmt::v5::internal::dummy_int fmt::v5::internal::_isnan(...)' already has a body

### ISSUE THREAD

**Issue by jeanga** [fmtlib/fmt#1104]
Hi,

When compiling using fmt (installed via vcpkg) on Windows, I get the following error message:
`F:\vcpkg\installed\x86-windows\include\fmt\format.h(279): error C2084: function 'fmt::v5::internal::dummy_int fmt::v5::internal::_isnan(...)' already has a body (compiling source file main.cpp)
F:\vcpkg\installed\x86-windows\include\fmt\format.h(278): note: see previous definition of '_isnan' (compiling source file main.cpp)`

Commenting this line in format.h solves the error message (with no apparent bad consequenses except being able to use this great library).

Thank you,
Jean Gautier

**Comment by vitaut** [comment]
This should be fixed in the master branch since `_isnan` has been removed.
