### ISSUE TITLE
Warnings with g++ 8.2.0

### ISSUE THREAD

**Issue by nlslatt** [fmtlib/fmt#1105]
Compiling using g++ 8.2.0 with -Wall -Wshadow -pedantic results in -Wshadow and -Wdangling-else warnings.  For me personally, the most critical to be remedied are the three distinct -Wshadow warnings coming from include/fmt/ostream.h (lines 25, 75, and 89) on the master branch.

[build.log](https://github.com/fmtlib/fmt/files/3044736/build.log)

**Comment by nlslatt** [comment]
Correction, there are four coming from ostream.h.  The final one is on line 105.

**Comment by vitaut** [comment]
Thanks for reporting this. Shadowing warnings are very noisy and in general have zero value which is why they are disabled by default (even in `-Wall`) when compiling {fmt} and are explicitly disabled in https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L71.

Also this diagnostics looks like a bug in gcc, please report there:

```
/home/nlslatt/tmp/fmt/include/fmt/core.h:131:33: warning: declaration of ‘buffer’ shadows a global declaration [-Wshadow]
 #  define FMT_DETECTED_NOEXCEPT noexcept
                                 ^~~~~~~~
```

**Comment by nlslatt** [comment]
If the shadow warnings are supposed to be explicitly disabled, then that feature does not appear to be working.  When I #include fmt headers in my own build, I get more than 600 shadow warnings originating in fmt.

**Comment by vitaut** [comment]
Sorry, I must have misunderstood the issue. Looking at the logs I saw you are building {fmt} itself with shadowing warnings enabled.

**Comment by nlslatt** [comment]
I sent a log from building fmt directly because my code is not publicly available.  I use fmt as header-only within my code.  The shadow warnings I'm seeing in my code all originate from fmt's ostream.h.

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/2808395481a36dbf1dcbd5b49e1488823f3c6f67 and https://github.com/fmtlib/fmt/commit/718f60accb16b7b65cc2aad389114dc500ae5f15.

**Comment by nlslatt** [comment]
Yes, thank you!
