### ISSUE TITLE
Compilation without dependency on std::string

### ISSUE THREAD

**Issue by brinkrob** [fmtlib/fmt#1106]
Has there even been any effort to get fmt compiling without a dependency on std::string?

I'm coming from the background of the games industry and being able to use fmt would be a huge benefit, but we are pretty sensitive to compile times and we currently do not allow usage of std::string.

We have our own string type, and I would exclusively use the fmt::format_to function with a fmt::memory_buffer.

The other alternative to removing usage of std::string, would be isolating the fmt library in a single translation unit.  In this case, a format function on our string type would just forward the arguments to the single compilation unit, however given that these things are variadic templates that wont work.

I spend some time trying to remove the include of <string>, but it kept coming back as a transitive include of things like <stdexcept> (which I also tried to disable since we don't use exceptions), or <iterator>.

Any other thoughts?  Have others attempted this before and failed?

**Comment by vitaut** [comment]
> Has there even been any effort to get fmt compiling without a dependency on std::string?

Not that I'm aware of. There was a more general effort to reduce compilation times which resulted in the [lightweight core API](http://fmtlib.net/latest/api.html#core-api) (`fmt/core.h`).

`<string>` itself is not the heaviest header: from my experiments it adds of the order of a 100 milliseconds of compile time per translation unit. This is mildly annoying but not a deal breaker since any nontrivial C++ codebase usually has much bigger contributors to compile time.

> We have our own string type, and I would exclusively use the fmt::format_to function with a fmt::memory_buffer.

`std::string` support doesn't prevent you from doing this.

> I spend some time trying to remove the include of , but it kept coming back as a transitive include of things like (which I also tried to disable since we don't use exceptions), or .

Looks like some parts of your comment have been swallowed.

**Comment by brinkrob** [comment]
I'm basing my desire to remove the string header on the compile time charts included in the {fmt} readme.  The difference between printf and printf+string is approximatly 16 seconds.


For my second sentence, it looks like Github swallowed the headers that were surrounded by brackets.  It should have read:

**Comment by vitaut** [comment]
> The difference between printf and printf+string is approximatly 16 seconds.

That's for the whole project consisting entirely of formatting code compiled sequentially. If you compute the actual per-translation-unit time you'll get the timing of the order of 100ms. And taking into account other factors such as parallel builds, the difference will be minor.

**Comment by vitaut** [comment]
Closing as I think the change would be fairly intrusive for little real benefit and irrelevant for most users. Modules will eliminate the overhead of re-parsing `<string>` numerous times anyway (I should probably run the compile-time benchmark with modules enabled when time permit).

**Comment by vitaut** [comment]
BTW there might be some easy hacky ways of doing this such as supplying a `<string>` header with just a minimal stub of `std::basic_string` if you are not afraid of stepping into the UB land.
