### ISSUE TITLE
format(fmt("{2}"), 42) does not produce compile time error

### ISSUE THREAD

**Issue by KerstinKeller** [fmtlib/fmt#1108]
In the readme.md it is stated that the following code
```
// test.cc
#define FMT_STRING_ALIAS 1
#include <fmt/format.h>
std::string s = format(fmt("{2}"), 42);
```
will produce a compile time error.

Building this sample with VS2015 I don't get anything, the program compiles fine, but throws a runtime exception.

What could be the issue here? I am using the newest fmt release 5.3.0.

**Comment by vitaut** [comment]
`constexpr` is known to be broken on VS2015 unfortunately so {fmt} has to fall back on runtime checks.
