### ISSUE TITLE
Handle utf8 character as a fill character in alignment 

### ISSUE THREAD

**Issue by dsvi** [fmtlib/fmt#1109]
If you use unicode symbols as fill character for alignment, you get runtime error
for example, for:
`print(u8" {:─<5}─{}\n", i, str);`
there supposed to be outputs like this
```
 0─────2019 March 27 06:32:41                                                                                                                                                 
 1─────2019 March 27 14:43:20                                                                                                                                                 
```
but there is runtime error:
`missing '}' in format string `

**Comment by vitaut** [comment]
Thanks for reporting. This is a known limitation: only single code units can be used in the fill field.

**Comment by vitaut** [comment]
`format_specs` can accommodate multibyte specs as of https://github.com/fmtlib/fmt/commit/e4f84ee1c625211217c13e86ca4bb49474e1ca08, but need to hook this to the parsing and formatting logic.

**Comment by vitaut** [comment]
{fmt} now supports UTF-8 code points as fill. For example

```c++
#include <fmt/core.h>

int main() {
  fmt::print(u8" {:─<5}─{}\n", 0, "2019 March 27 06:32:41");
}
```
prints
```
 0─────2019 March 27 06:32:41
```
as expected.

**Comment by gocarlos** [comment]
should this work out of the box?

this code: 
```cpp
  fmt::print(
                  "┌{0:─^{2}}┐\n"
                  "│{1: ^{2}}│\n"
                  "└{0:─^{2}}┘\n", "", "my great message.", 72);
  fmt::print(" {:─<5}─{}\n", 0, "2019 March 27 06:32:41");
```

creates this on windows
![image](https://user-images.githubusercontent.com/1331762/85925966-3281d580-b89c-11ea-9c75-fdc013f2928a.png)

**Comment by vitaut** [comment]
You should compile with `/utf-8`, otherwise MSVC will corrupt your string literals.
