### ISSUE TITLE
doc bug?

### ISSUE THREAD

**Issue by BillyDonahue** [fmtlib/fmt#1112]
In fmt/doc/index.rst, the "Safety" section, this snippet appears:

    format(fmt("The answer is {:d}"), "forty-two");

Since `fmt` is a namespace, this can't work as-is.
The `fmt` here should be some typename or function name, and then `format` can be looked up as `fmt::format` via ADL, but I can't figure out what `fmt` should have been.

Any ideas?

**Comment by foonathan** [comment]
There is a function like macro called `fmt`.

**Comment by BillyDonahue** [comment]
Oh, I see. But that macro is not enabled by default.
Maybe the doc bug is that this should be explained?
A naive attempt at testing it is otherwise pretty frustrating.
https://gcc.godbolt.org/z/uYGAAW

**Comment by vitaut** [comment]
It is explained in the docs: http://fmtlib.net/latest/api.html#c.fmt

**Comment by vitaut** [comment]
But you are right, the index page should be updated too.

**Comment by vitaut** [comment]
Added a link from the index page to the main `fmt(...)` docs in https://github.com/fmtlib/fmt/commit/a4969ebe063b605e5ca9c6c79dba44dc30f97f2d. Thanks for reporting!
