### ISSUE TITLE
to_wstring fails to convert from string to wstring

### ISSUE THREAD

**Issue by IAmTrial** [fmtlib/fmt#1116]
Prior to commit bb6842ba35206d4a2019366f450936f8428a7e0a, to_wstring was able to convert string to wstring. By replacing the old code with format, programs relying on this behavior no longer compile.

One of these scenarios solves this issue:
1. Conversion from string to wstring was never intended, so it was and never will be supported.
2. to_wstring was supposed to be the only safe way to convert from string to wstring.
3. format should support mixing wstring format and string input.

**Comment by IAmTrial** [comment]
Updated the issue after testing and finding that to_string **cannot** convert from wstring to string, but to_wstring can convert string to wstring.

**Comment by vitaut** [comment]
Old behavior was accidental. Mixing string and wstring is explicitly disallowed.

**Comment by degski** [comment]
@vitaut 

> Old behavior was accidental. Mixing string and wstring is explicitly disallowed.

Unfortunately this is a common use-case (on Windows), like when dealing with the filesystem (has to be a wide-string), the 'narrow strings' one converts from might actually be utf-8 encoded strings (obligatory when using any json and xml parsing libs), which you have/get by passing /utf-8. To be able to write correct programs mixing is [might be] required.

Before I 'discovered' the accidental fmt-functionality, I already added that functionality to my [base lib](https://github.com/degski/Sax/blob/master/include/sax/utf8conv.hpp).

**Comment by degski** [comment]
Yeah, I realize that now, it only 'worked' because I have a `en-US` system and purposely have a user-name for which utf-8 and ascii would yield the same narrow string. Wouldn't it be possible to provide overloads? I've updated [that code](https://github.com/degski/Sax/blob/master/include/sax/utf8conv.hpp) to also work with `std::string_view`.

**Comment by degski** [comment]
Okido!
