### ISSUE TITLE
Specialization of fmt::formatter followed by inclusion of <ostream.h> rejected by gcc

### ISSUE THREAD

**Issue by lubgr** [fmtlib/fmt#1118]
The following snippet fails to compile with any recent gcc version.

    #include <type_traits>
    #include <fmt/format.h>

    struct Test {};

    namespace fmt {
       template<>
          struct formatter<Test> : formatter<int> {
             template <typename FormatContext>
                auto format(const Test&, FormatContext &ctx) {
                   return formatter<int>::format(42, ctx);
                }
          };
    }
    
    // When moved on top of the specialization, it works fine:
    #include <fmt/ostream.h>

The error message is

> fmt/ostream.h:115:45: error: partial specialization of 'struct fmt::v5::convert_to_int<T, Char, void>' after instantiation of 'struct fmt::v5::convert_to_int<int, char, void>' [-fpermissive]
 template <typename T, typename Char> struct convert_to_int<T, Char, void> {

Contrary, clang happily compiles this. See [godbolt](https://godbolt.org/z/W2kS7r).

Thanks in advance for having a look! I could also try to fix it, but not today at least :)

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/5efb24dd2b0a64c8e826c69c70d1fded5e8571a6, thanks for reporting!

**Comment by lubgr** [comment]
Awesome, thanks for fixing it immediately!
