### ISSUE TITLE
Ambiguous functions in std namespace

### ISSUE THREAD

**Issue by Jerry-Ma** [fmtlib/fmt#1120]
Hi,

After commit https://github.com/fmtlib/fmt/commit/ab1474ef661a82175de693f79926f38bf11d6815 , the compat functions `begin`, `end`, `result_of` defined in `fmt::internal` is imported to namespace std, which results in ambiguous function calls when using e.g., `begin(const T&)`

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/d306585a3fa96b9d37e17585ce5fb96fcadc87c0. Thanks for reporting!
