### ISSUE TITLE
crash in floating point format

### ISSUE THREAD

**Issue by pauldreik** [fmtlib/fmt#1124]
Hi,
I did a very basic fuzzing attempt and found a segmentation fault. The following code crashes both with gcc and clang:
```C++
#include <fmt/core.h>

int main() {
float item=9.57489014e-4;
std::string message = fmt::format("\x7b\x3a\x2e\x30\x7d", item);
}
```
It also crashed for double (not necessarily with the same number), suspect it is the same issue.

**Comment by vitaut** [comment]
Great catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/736aa340c7df17a0ba00830bca29a0c7e20e60d3.
