### ISSUE TITLE
fmt::format_to returns wrong value when formatting chars.

### ISSUE THREAD

**Issue by domenn** [fmtlib/fmt#1125]
```C++
  std::array<char, 200> test_buf;
  auto pos1 = fmt::format_to(test_buf.data(), "hello{}", ' ');
  // test_buf is now "hello " which is expected.
  // But pos1 points to ' '. It should point to value after ' '.
  auto pos2 =
      fmt::format_to(pos1, "world{}{}{}{}{}{}", '!', ';', '1', '2', '3', '4');
  // test_buf is now helloworld4. pos2 points to 4.
  assert(*(pos2 - 1) == '4');
```

Expected behaviour: pos1 should point to the value after space, that would cause second format_to call to insert into correct place and text would be correct.

It appears that when using char, the count doesn't increment. So it points to latest character and therefore next formatting overwrites it.

This worked flawlessly in fmt 5.1. Error shows up when upgrading to version 5.3. I haven't tried versions between them.
Compiling with MSVC 19 (Visual Studio 2017)

**Comment by domenn** [comment]
I cloned the repo and tried to use library directly. Appears that the issue is not present in master branch, only in 5.3.0.

**Comment by vitaut** [comment]
As you've already found out, the issue has been fixed in `master`.
