### ISSUE TITLE
crash in grisu2_prettify

### ISSUE THREAD

**Issue by pauldreik** [fmtlib/fmt#1127]
Hi,
I found another crash through fuzzing sprintf. It gives a segmentation fault (using address sanitizer also works).
```cpp
#include <fmt/printf.h>

int
main()
{
  int a = -13;
  float b = -1e19;
  std::string message = fmt::sprintf("%.*%", a, b);
}
```
I think the reason is that
```cpp
it = copy_str<Char>(digits + full_exp, digits + size, it);
```
on [format.h line 1203](https://github.com/fmtlib/fmt/blob/5efb24dd2b0a64c8e826c69c70d1fded5e8571a6/include/fmt/format.h#L1203)
gets an invalid range. I added assert(full_exp<=size); which is triggered by this.

By the way, I pushed my fuzzers to [here](https://github.com/pauldreik/fuzzfmt) in case you or someone else wants to fuzz.

Thanks,
Paul

**Comment by vitaut** [comment]
Thanks! This is a bug in `fmt::sprintf` - negative precision should have been converted to zero (the check in prettifier is actually redundant). I didn't even know `printf` allows negative precision =). Fixed in https://github.com/fmtlib/fmt/commit/bd516e342969a7f5acfb36d87bba21c3e7ee9f7f.
