### ISSUE TITLE
Trailing zeroes when using `:g`

### ISSUE THREAD

**Issue by TheQwertiest** [fmtlib/fmt#1129]
**Docs:**
According to http://fmtlib.net/latest/syntax.html#grammar-token-int_type and https://en.cppreference.com/w/cpp/io/c/fprintf type `:g` must remove trailing zeroes:
> Unless alternative representation is requested the trailing zeros are removed, also the decimal point character is removed if no fractional part is left`.

**Current behaviour:**
```cpp
double arg = 0.1;
std::string output = fmt::format("{%.16g}", arg);
```
produces `0.1000000000000000`

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/40a79756407301a1beb87c9ecd1c2040bd9347a2, thanks for reporting!
