### ISSUE TITLE
Do not define char8_t

### ISSUE THREAD

**Issue by rokups** [fmtlib/fmt#1137]
fmt defines `char8_t` if this new builtin type is not yet supported by compiler. This poses an issue with alternate stl implementations like EASTL which [defines](https://github.com/electronicarts/EASTL/blob/master/test/packages/EABase/include/Common/EABase/eabase.h#L700-L712) same type as well. Maybe it is not a place of formatting library to define this kind of types?

**Comment by vitaut** [comment]
EASTL's implementation is broken because it defines `char8_t` as a macro, please report there. {fmt} defines a type it in its own namespace and only if it doesn't conflict with the standard definition.

**Comment by rokups** [comment]
Fair enough. Although they have reason of their own to use macro. Sucks.

**Comment by vitaut** [comment]
> they have reason of their own to use macro. 

Could you elaborate?

**Comment by rokups** [comment]
Comment there says:

> The Apple debugger is too stupid to realize char8_t is typedef'd to char, so we #define it.

**Comment by vitaut** [comment]
LOL, seems like they don't understand what `char8_t` is for, but anyway I'm open to making `char8_t` conditionally defined in {fmt} controlled via `FMT_USE_CHAR8_T` macro. A PR is welcome.

**Comment by vitaut** [comment]
On a second thought, it's trivial to workaround by undefining `char8_t` before including the fmt's headers. I still recommend reporting a bug to EASTL maintainers because it's broken on so many levels.

**Comment by rokups** [comment]
Yes ill see what can be done about it. Thanks.
