### ISSUE TITLE
asserts on NaN in duration

### ISSUE THREAD

**Issue by pauldreik** [fmtlib/fmt#1141]
Hi, 
using the most recent improvements on range checking in to_int https://github.com/fmtlib/fmt/commit/38a85502ed824d34a751ab4a122005a9d4454fd3 there is now a new assert triggering (don't trust the line number 382, it's from the fuzzing repo):
```
include/fmt/chrono.h:382: int fmt::v5::internal::to_int(T) [with T = double]: Assertion `(value >= (std::numeric_limits<int>::min)() && value <= (std::numeric_limits<int>::max)()) && "invalid value"' failed.
```

Fuzzing found that the assert triggers if fed with NaN. The below test cases capture what the fuzzer found (it is possible to trigger even without the trailing curly brace, but that leaves the test inactive in case the incorrect format string would be rejected by some other mechanism). I do not know what is supposed to happen if one tries to format a NaN duration?
Give me a shout if you want me to turn this into a pull request.
```cpp

TEST(ChronoTest, DurationIsFloatNaN) {
  const std::chrono::duration<float> d{std::nanf("1")};
  auto ignored=fmt::format("{:%I}",d);
}

TEST(ChronoTest, DurationIsDoubleNaN) {
  const std::chrono::duration<double> d{std::nan("1")};
  auto ignored=fmt::format("{:%I}",d);
}
```

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/ca978b3d21e05ba271b4e6dd6bddcd136c0908a5. Thanks for reporting!

> Give me a shout if you want me to turn this into a pull request.

No need for a separate PR, an example is perfectly fine.
