### ISSUE TITLE
Compile error under MSVC due to unsupported #warning directive.

### ISSUE THREAD

**Issue by rcane** [fmtlib/fmt#1143]
The `#warning` directive in time.h is not recognized by MSVC and therefor produces a compile error.

We could use `#pragma message("fmt/time.h is deprecated...")` under MSVC instead to at least get the message output.

**Comment by vitaut** [comment]
> We could use #pragma message("fmt/time.h is deprecated...") under MSVC instead to at least get the message output.

Seems reasonable. Could you submit a PR?
