### ISSUE TITLE
Consider not making FMT_USE_USER_DEFINED_LITERALS enabled by default

### ISSUE THREAD

**Issue by MerryMage** [fmtlib/fmt#1148]
This produces a warning under `-Wpendantic` on GCC 9.1. The feature this depends upon is non-standard. Unfortunately ISO C++ did not adopt the use of string literal operator templates taking a character pack.

**Comment by vitaut** [comment]
This is somewhat problematic because it will be a breaking change. However, you can disable user-defined literals by defining `FMT_USE_USER_DEFINED_LITERALS` to 0 when including {fmt}.

**Comment by vitaut** [comment]
Actually disabling just UDL templates on GCC 9 by default should be fine because it will fallback to runtime checks. Done in https://github.com/fmtlib/fmt/commit/a6e8ed15c47798d36b2e9160a6c0ad9970d84a1f.
