### ISSUE TITLE
Unexpected trailing zeros in to_string(double)

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#1153]
`std::cout << fmt::to_string(1234.0);`

Previously (for years) this was printing "1234".
Now it prints "1234.0" and, of course, [breaks someone's workflow](https://xkcd.com/1172/).

Probably related to #1129.

**Comment by vitaut** [comment]
Thanks for reporting. The default has changed to the shortest decimal representation to follow the standards proposal, so this is expected. If you want some specific format please use the `fmt::format` function instead.

**Comment by alabuzhev** [comment]
Ok, thanks.
And what the format string should be used then please?
#1129 mentions ":g", but `fmt::format("{0:g}", 1234.0)` gives "1234.", i.e. *with* the decimal point character.

**Comment by alabuzhev** [comment]
P.S.
Python: `"{0:.16g}".format(1234.0)` -> `1234`
C: `printf("%.16g", 1234.0);` -> `1234`

**Comment by vitaut** [comment]
`g` is a correct option and trailing `.` there is a bug.
