### ISSUE TITLE
warning when using spdlog

### ISSUE THREAD

**Issue by ranjan-ranjan** [fmtlib/fmt#1160]
https://github.com/gabime/spdlog/issues/1051

I am using spdlog with VS 2019. I have copy pasted the spdlog folder as given in the docs.
I got the following warnings:

1. spdlog\fmt\bundled\format-inl.h(722): warning C4244: 'argument': conversion from 'const unsigned __int64' to 'int', possible loss of data
2. spdlog\fmt\bundled\format-inl.h(722): note: This diagnostic occurred in the compiler generated function 'std::enable_if<sizeof(Double)==,bool>::type fmt::v5::internal::grisu2_format(Double,fmt::v5::internal::buffer &,fmt::v5::core_format_specs)'
3. spdlog\fmt\bundled\format-inl.h(722): warning C4244: 'argument': conversion from 'const unsigned __int64' to 'int', possible loss of data
4. spdlog\fmt\bundled\format-inl.h(722): note: This diagnostic occurred in the compiler generated function 'std::enable_if<sizeof(Double)==,bool>::type fmt::v5::internal::grisu2_format(Double,fmt::v5::internal::buffer &,fmt::v5::core_format_specs)'

**Comment by vitaut** [comment]
Thanks for reporting, but this has been fixed already.

**Comment by ranjan-ranjan** [comment]
I have used this recently. I got these warning.
Anyways, I will check it again.

**Comment by gabime** [comment]
@vitaut Is there an estimate for the next minor release date? I would like to integrate is spdlog

**Comment by vitaut** [comment]
> Is there an estimate for the next minor release date?

Some time after WG21 paper submission deadline (17 June), not sure exactly when yet. Floating point needs a bit more work and testing.
