### ISSUE TITLE
Custom formatters are stateless and global

### ISSUE THREAD

**Issue by davidchisnall** [fmtlib/fmt#1162]
This combination of properties introduces two issues.  The first is that you can't provide two formatters for the same type that do not conflict, unless they are in separate compilation units.

The second problem occurs when you have a type that is context dependent, for example a compressed encoding that refers to some state held by another class.  It may be possible to subclass `basic_format_context` to carry the extra information.  This is even apparent in simple types, where it impossible to implement a locale-aware data formatter that depends on something other than the global or per-thread locale (something that C++11 fixed for most of the C++ standard library and POSIX2008 fixed for most of the C standard library).

I'm grouping these two issues together because I suspect that the fix to either would address both: a mechanism for providing context-dependent state to the formatter.

**Comment by vitaut** [comment]
> The first is that you can't provide two formatters for the same type that do not conflict, unless they are in separate compilation units.

If you mean `formatter` specializations then this is by design and you shouldn't do it even in separate compilation units.

The way to provide multiple formatters or pass additional information is by wrapping in another type.

> it impossible to implement a locale-aware data formatter that depends on something other than the global or per-thread locale.

It is possible: you can access the locale through the format context.

**Comment by davidchisnall** [comment]
How do I pass the locale in from the format interface?  Can I use this mechanism to pass other things in?

**Comment by vitaut** [comment]
> How do I pass the locale in from the format interface?

You can do this via one of the functions defined in [`fmt/locale.h`](https://github.com/fmtlib/fmt/blob/master/include/fmt/locale.h) that take a locale argument, e.g.

```c++
#include <fmt/locale.h>

struct numpunct : std::numpunct<char> {
 protected:
  char do_thousands_sep() const override { return '~'; }
};

std::locale loc;
auto s = fmt::format(std::locale(loc, new numpunct()), "{:n}", 1234567);
// s == "1~234~567"
```

> Can I use this mechanism to pass other things in?

No.

**Comment by foonathan** [comment]
Well, technically you can create your own facet containing the formatting state and pass that in via the locale...
