### ISSUE TITLE
Possibility to build for Win32

### ISSUE THREAD

**Issue by itcotta** [fmtlib/fmt#1165]
Hey
I'm trying to get this to build as a Win32 lib (need to use it in an old Win32 application) but have had no way of sucessfully doing this on VS2019.  Is FMT Win32 compatible?

This is what I've done:
I have used cmake to generate the .sln.
I've have aftwards launched the FMT.sln and changed the solution platform to Win32
![image](https://user-images.githubusercontent.com/13465457/57827981-f8de3000-77a9-11e9-8352-d52d059d4bcb.png)

This is my build log from VS2019 when attempting to build with Win32 as my platform:

> 1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
2>------ Build started: Project: fmt, Configuration: Debug Win32 ------
3>------ Build started: Project: gmock, Configuration: Debug Win32 ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (ZERO_CHECK.vcxproj).  This can lead to incorrect clean and rebuild behavior.
2>format.cc
2>C:\Users\pcuser\Downloads\fmt-5.3.0\src\format.cc(8): fatal error C1083: Cannot open include file: 'fmt/format-inl.h': No such file or directory
3>gmock-gtest-all.cc
2>posix.cc
3>C:\Users\pcuser\Downloads\fmt-5.3.0\test\gmock-gtest-all.cc(39): fatal error C1083: Cannot open include file: 'gtest.h': No such file or directory
3>Done building project "gmock.vcxproj" -- FAILED.
4>------ Build started: Project: header-only-test, Configuration: Debug Win32 ------
5>------ Build started: Project: posix-mock-test, Configuration: Debug Win32 ------
2>C:\Users\pcuser\Downloads\fmt-5.3.0\src\posix.cc(13): fatal error C1083: Cannot open include file: 'fmt/posix.h': No such file or directory
2>Generating Code...
2>Done building project "fmt.vcxproj" -- FAILED.
6>------ Build started: Project: test-main, Configuration: Debug Win32 ------
5>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (gmock.vcxproj).  This can lead to incorrect clean and rebuild behavior.
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (gmock.vcxproj).  This can lead to incorrect clean and rebuild behavior.
4>header-only-test.cc
5>posix-mock-test.cc
4>C:\Users\pcuser\Downloads\fmt-5.3.0\test\header-only-test.cc(3): fatal error C1083: Cannot open include file: 'fmt/core.h': No such file or directory
4>header-only-test2.cc
5>C:\Users\pcuser\Downloads\fmt-5.3.0\test\posix-mock-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
5>format.cc
4>C:\Users\pcuser\Downloads\fmt-5.3.0\test\header-only-test2.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
4>test-main.cc
4>C:\Users\pcuser\Downloads\fmt-5.3.0\test\test-main.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
4>Generating Code...
5>C:\Users\pcuser\Downloads\fmt-5.3.0\src\format.cc(8): fatal error C1083: Cannot open include file: 'fmt/format-inl.h': No such file or directory
5>test-main.cc
4>Done building project "header-only-test.vcxproj" -- FAILED.
5>C:\Users\pcuser\Downloads\fmt-5.3.0\test\test-main.cc(9): fatal error C1083: Cannot open include file: 'gtest.h': No such file or directory
5>gtest-extra.cc
6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (gmock.vcxproj, header-only-test.vcxproj, posix-mock-test.vcxproj).  This can lead to incorrect clean and rebuild behavior.
5>C:\Users\pcuser\Downloads\fmt-5.3.0\test\gtest-extra.h(12): fatal error C1083: Cannot open include file: 'gmock.h': No such file or directory
5>util.cc
6>test-main.cc
5>C:\Users\pcuser\Downloads\fmt-5.3.0\test\util.h(12): fatal error C1083: Cannot open include file: 'fmt/posix.h': No such file or directory
6>C:\Users\pcuser\Downloads\fmt-5.3.0\test\test-main.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
6>gtest-extra.cc
6>C:\Users\pcuser\Downloads\fmt-5.3.0\test\gtest-extra.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
6>util.cc
5>Generating Code...
5>Done building project "posix-mock-test.vcxproj" -- FAILED.
6>C:\Users\pcuser\Downloads\fmt-5.3.0\test\util.h(12): fatal error C1083: Cannot open include file: 'fmt/posix.h': No such file or directory
6>Generating Code...
6>Done building project "test-main.vcxproj" -- FAILED.
7>------ Build started: Project: assert-test, Configuration: Debug Win32 ------
8>------ Build started: Project: chrono-test, Configuration: Debug Win32 ------
9>------ Build started: Project: core-test, Configuration: Debug Win32 ------
10>------ Build started: Project: custom-formatter-test, Configuration: Debug Win32 ------
11>------ Build started: Project: format-impl-test, Configuration: Debug Win32 ------
12>------ Build started: Project: format-test, Configuration: Debug Win32 ------
13>------ Build started: Project: gtest-extra-test, Configuration: Debug Win32 ------
14>------ Build started: Project: locale-test, Configuration: Debug Win32 ------
7>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (gmock.vcxproj, header-only-test.vcxproj, posix-mock-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
11>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, gmock.vcxproj, header-only-test.vcxproj, posix-mock-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
12>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, gmock.vcxproj, header-only-test.vcxproj, posix-mock-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
7>assert-test.cc
9>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, format-impl-test.vcxproj, format-test.vcxproj, gmock.vcxproj, header-only-test.vcxproj, posix-mock-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
8>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, core-test.vcxproj, format-impl-test.vcxproj, format-test.vcxproj, gmock.vcxproj, header-only-test.vcxproj, posix-mock-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
7>C:\Users\pcuser\Downloads\fmt-5.3.0\test\assert-test.cc(8): fatal error C1083: Cannot open include file: 'fmt/core.h': No such file or directory
7>Done building project "assert-test.vcxproj" -- FAILED.
15>------ Build started: Project: ostream-test, Configuration: Debug Win32 ------
10>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, chrono-test.vcxproj, core-test.vcxproj, format-impl-test.vcxproj, format-test.vcxproj, gmock.vcxproj, header-only-test.vcxproj, posix-mock-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
15>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, chrono-test.vcxproj, core-test.vcxproj, format-impl-test.vcxproj, format-test.vcxproj, gmock.vcxproj, header-only-test.vcxproj, posix-mock-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
12>format-test.cc
11>format-impl-test.cc
11>C:\Users\pcuser\Downloads\fmt-5.3.0\test\format-impl-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
8>chrono-test.cc
9>core-test.cc
8>C:\Users\pcuser\Downloads\fmt-5.3.0\test\chrono-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
9>C:\Users\pcuser\Downloads\fmt-5.3.0\test\core-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
8>Done building project "chrono-test.vcxproj" -- FAILED.
16>------ Build started: Project: posix-test, Configuration: Debug Win32 ------
11>Done building project "format-impl-test.vcxproj" -- FAILED.
17>------ Build started: Project: printf-test, Configuration: Debug Win32 ------
9>Done building project "core-test.vcxproj" -- FAILED.
18>------ Build started: Project: ranges-test, Configuration: Debug Win32 ------
14>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, chrono-test.vcxproj, core-test.vcxproj, custom-formatter-test.vcxproj, format-impl-test.vcxproj, format-test.vcxproj, gmock.vcxproj, header-only-test.vcxproj, ostream-test.vcxproj, posix-mock-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
15>ostream-test.cc
17>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, chrono-test.vcxproj, core-test.vcxproj, custom-formatter-test.vcxproj, format-impl-test.vcxproj, format-test.vcxproj, gmock.vcxproj, header-only-test.vcxproj, locale-test.vcxproj, ostream-test.vcxproj, posix-mock-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
18>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, chrono-test.vcxproj, core-test.vcxproj, custom-formatter-test.vcxproj, format-impl-test.vcxproj, format-test.vcxproj, gmock.vcxproj, header-only-test.vcxproj, locale-test.vcxproj, ostream-test.vcxproj, posix-mock-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
15>C:\Users\pcuser\Downloads\fmt-5.3.0\test\ostream-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
10>custom-formatter-test.cc
10>C:\Users\pcuser\Downloads\fmt-5.3.0\test\custom-formatter-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
13>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, chrono-test.vcxproj, core-test.vcxproj, custom-formatter-test.vcxproj, format-impl-test.vcxproj, format-test.vcxproj, gmock.vcxproj, header-only-test.vcxproj, locale-test.vcxproj, ostream-test.vcxproj, posix-mock-test.vcxproj, posix-test.vcxproj, printf-test.vcxproj, ranges-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
14>locale-test.cc
17>printf-test.cc
18>ranges-test.cc
18>C:\Users\pcuser\Downloads\fmt-5.3.0\test\ranges-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
17>C:\Users\pcuser\Downloads\fmt-5.3.0\test\printf-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
14>C:\Users\pcuser\Downloads\fmt-5.3.0\test\locale-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
10>Done building project "custom-formatter-test.vcxproj" -- FAILED.
18>Done building project "ranges-test.vcxproj" -- FAILED.
19>------ Build started: Project: time-test, Configuration: Debug Win32 ------
17>Done building project "printf-test.vcxproj" -- FAILED.
15>Done building project "ostream-test.vcxproj" -- FAILED.
14>Done building project "locale-test.vcxproj" -- FAILED.
13>gtest-extra-test.cc
19>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (assert-test.vcxproj, chrono-test.vcxproj, core-test.vcxproj, custom-formatter-test.vcxproj, format-impl-test.vcxproj, format-test.vcxproj, gmock.vcxproj, gtest-extra-test.vcxproj, header-only-test.vcxproj, locale-test.vcxproj, ostream-test.vcxproj, posix-mock-test.vcxproj, posix-test.vcxproj, printf-test.vcxproj, ranges-test.vcxproj, test-main.vcxproj).  This can lead to incorrect clean and rebuild behavior.
13>C:\Users\pcuser\Downloads\fmt-5.3.0\test\gtest-extra-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
13>Done building project "gtest-extra-test.vcxproj" -- FAILED.
19>time-test.cc
19>C:\Users\pcuser\Downloads\fmt-5.3.0\test\time-test.cc : fatal error C1041: cannot open program database 'C:\Users\pcuser\Downloads\fmt-5.3.0\build\test\Debug\vc142.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
19>Done building project "time-test.vcxproj" -- FAILED.
12>C:\Users\pcuser\Downloads\fmt-5.3.0\test\format-test.cc(23): fatal error C1083: Cannot open include file: 'fmt/format.h': No such file or directory
12>Done building project "format-test.vcxproj" -- FAILED.
20>------ Build started: Project: ALL_BUILD, Configuration: Debug Win32 ------
20>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (fmt.vcxproj, ZERO_CHECK.vcxproj).  This can lead to incorrect clean and rebuild behavior.
20>Done building project "ALL_BUILD.vcxproj".
========== Build: 2 succeeded, 18 failed, 0 up-to-date, 0 skipped ==========

**Comment by easyaspi314** [comment]
That seems like a build system issue. It doesn't like the build folder, and your include path seems wrong

**Comment by itcotta** [comment]
Was able to build in Win32 after uninstalling Cmake 64bit and installing the 32 bit version of it.
Also used VS2017 instead of VS2019.
