### ISSUE TITLE
Inconsistency with escaping braces in printf, compile-time vs runtime

### ISSUE THREAD

**Issue by barretpj** [fmtlib/fmt#1173]
I want to replace `sprintf("{%d}", i)` or `boost::str(boost::format("{%1%}") % i)` with an equivalent `fmt::sprintf` call.

`fmt::sprintf(FMT_STRING("{%d}"), 10)` fails the compile-time checks because the braces aren't quoted.

`fmt::sprintf(FMT_STRING("{{%d}}"), 10)` outputs `{{10}}` which is wrong because the braces remain doubled.

**Comment by vitaut** [comment]
`fmt::sprintf` doesn't support compile-time checks, so just remove `FMT_STRING`:

```c++
fmt::sprintf("{%d}", 10);
```

The check that is currently there has been added by mistake, I removed it in https://github.com/fmtlib/fmt/commit/291ba837f20e902ae7496e69d57181c25c24661b. Thanks for reporting.
