### ISSUE TITLE
CXX_STANDARD property on target "std-format-test" contained an invalid value

### ISSUE THREAD

**Issue by cup** [fmtlib/fmt#1175]
~~~
$ cmake -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++
-- CMake version: 3.6.2
-- Version: 5.3.1
-- Build type: Release
-- CXX_STANDARD: 14
-- Target 'doc' disabled (requires doxygen)
-- FMT_PEDANTIC: OFF
-- Configuring done
CMake Error in test/CMakeLists.txt:
  The CXX_STANDARD property on target "std-format-test" contained an invalid
  value: "17".
~~~

**Comment by cup** [comment]
Upgrading Cmake fixed issue:

~~~
$ cmake -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++
-- CMake version: 3.13.1
-- Version: 5.3.1
-- Build type: Release
-- CXX_STANDARD: 11
-- Target 'doc' disabled (requires doxygen)
-- FMT_PEDANTIC: OFF
-- Configuring done
-- Generating done
~~~

**Comment by eliaskosunen** [comment]
The value `17` for `CXX_STANDARD` property was introduced in CMake version 3.8. This should probably be fixed here: https://github.com/fmtlib/fmt/blob/291ba837f20e902ae7496e69d57181c25c24661b/test/CMakeLists.txt#L111-L114

by adding `AND (NOT CMAKE_VERSION VERSION_LESS 3.8)` in the condition

**Comment by vitaut** [comment]
This test should only run in CI. Fixed in https://github.com/fmtlib/fmt/commit/bb254d146bd379165d1180a42a689ab6898630fe, thanks for reporting.
