### ISSUE TITLE
After printing 4096 characters to stdout, FMT crashes on MSVC with SUBSYSTEM:WINDOWS

### ISSUE THREAD

**Issue by VZout** [fmtlib/fmt#1176]
When using Visual Studio 16.1.1, with C++20 enabled and the subsystem set to `WINDOWS` fmt crashes after outputting 4096 characters to stdout. (`FMT_THROW(system_error(errno, "cannot write to file"));`) Code to reproduce:

```cpp
for (auto i = 0; i < 5000; i++)
{
	std::string out = "Hello world this is a relatively long string to test fmt.";
	fmt::print(out);
}
```

Settings the subsystem to `CONSOLE` solves the issue. I haven't tested without C++20 or with an older version of Visual Studio 16.1.1. But calling `fwrite` directly doesn't crash for me.

Tested on FMT master/291ba837f20e902ae7496e69d57181c25c24661b (latest commit at the time of creating this issue.)

**Comment by foonathan** [comment]
> But calling fwrite directly doesn't crash for me.

Did you check the return value of fwrite?

**Comment by VZout** [comment]
I did, it returns 0 if I print 1 character at the time. and when printing longer strings the length of the string minus the amount of characters that exceed 4096 characters written in total. (hopefully that makes sense)

**Comment by foonathan** [comment]
If it returns 0 if you print 1 character, the write failed. fwrite just reports it silently whereas fmt throws an exception.

**Comment by VZout** [comment]
Yes calling `fmt::print` causes `FMT_THROW(system_error(errno, "cannot write to file"));` calling `fwrite` myself works fine.

**Comment by foonathan** [comment]
But it doesn't work fine, it reports an error. You just choose to ignore it.

It makes sense that this reports an error, after all it has no console to write stdout to. If you want to ignore that error, you either need a try-catch, or redirect stdout to some file.

**Comment by VZout** [comment]
Ah yes of course my bad.

**Comment by VZout** [comment]
Doesn't seem to be an issue with FMT. calling fwrite directly also stops writing after 4096 characters.
