### ISSUE TITLE
undefined behaviour in chrono formatting

### ISSUE THREAD

**Issue by pauldreik** [fmtlib/fmt#1179]
Reporting this as something I accidentally spotted while working with other problems.
This triggers integer overflow, in the "d = -d" statement of the chrono_formatter class.
```cpp
TEST(ChronoTest, intmin) {
  // assume two's complement
  EXPECT_EQ("-2147483648", fmt::format("{:%Q}", std::chrono::duration<std::int32_t>(std::numeric_limits<std::int32_t>::min())));
}
```

**Comment by pauldreik** [comment]
This is how I solved it on the fuzzing branch:
```cpp
   if (d.count() < 0) {
       //protect against signed integer overflow
       using TT=std::numeric_limits<Rep>;
       if(TT::is_integer && TT::is_signed) {
           if(d.count()==TT::min()) {
               FMT_THROW(format_error("value would cause UB"));
           }
       }
       d = -d;
   }
```

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/78daa50ffc5caf7aedd51d1b2d491e48568bf5ac. Thanks for reporting!

**Comment by pauldreik** [comment]
Unfortunately I think the fix is ineffective, the UB is just moved to ```val = -val;```  because val is rep (int in the example above).

There are several solutions I can think of:
- do like I did above (adds the cost of checking for every cal with signed integer types)
- in case rep is a signed integral type, make val be the next bigger size (int8->int16, int16->int32 etc) and only do the checking in case rep already is intmax_t. I guess this makes all code slower, since the formatting will always have to cater for more bits always, even if they are most likely not set?
- work with the standards committe to remove signed integer overflow from UB :)

**Comment by vitaut** [comment]
`rep` is an unsigned type now (either `unsigned` or an unsigned counterpart of `Rep`):

```c++
  using rep = typename std::conditional<
      std::is_integral<Rep>::value && sizeof(Rep) < sizeof(int), unsigned,
      typename make_unsigned_or_unchanged<Rep>::type>::type;
```
and negation on unsigned is well-defined.

**Comment by pauldreik** [comment]
Sounds good!
