### ISSUE TITLE
lgtm alerts

### ISSUE THREAD

**Issue by Garfield96** [fmtlib/fmt#1184]
lgtm automatically checks open source projects for common mistakes. Currently, fmt raises several alerts, which you can find [here](https://lgtm.com/projects/g/fmtlib/fmt/). Almost all alerts are not very serious. However, other projects using fmt also receive these alerts.
E.g. the following alert is caused by include/fmt/core.h:
![lgtm_alert](https://user-images.githubusercontent.com/15248220/58732436-cc552580-83f1-11e9-8b47-9291c5eea119.png)

**Comment by vitaut** [comment]
Thanks for the issue. This alert is rather meaningless because `error_handler` is an empty class and copy constructor would have not effect. I recommend reporting to lgtm, so that they improved quality of their lints.
