### ISSUE TITLE
char8_t doesn't seem to have a specialisation

### ISSUE THREAD

**Issue by cjdb** [fmtlib/fmt#1185]
This [C++2a example][example] using `char8_t`-based strings instead of `char`-based strings fails to compile using {fmt} 5.3.0. By the look of things, it seems that `char8_t` isn't supported yet.

Note: I don't mind using a trunk-based beta branch, but it looks as though there's some deprecations that haven't yet been documented.

[Update from trunk.][update]

[example]: https://godbolt.org/z/UFJsiJ
[update]: https://godbolt.org/z/6GIASk

**Comment by cjdb** [comment]
Updated link: https://godbolt.org/z/fyLq7m

**Comment by vitaut** [comment]
`char8_t` is supported: https://godbolt.org/z/uTggWV. However, mixing of `char` and `char8_t` strings is intentionally disallowed because in general it requires transcoding.
