### ISSUE TITLE
Replace fmt() macro by a user defined literal _fmt

### ISSUE THREAD

**Issue by AlexandreBossard** [fmtlib/fmt#1192]
I have issues (name collisions, msvc ICE, etc) with the *fmt()* macro and the FMT_STRING_ALIAS macro. 

I like this feature but, its macro name is impractical.

It would be better to exposed a user defined literal. Its definition would be always present, only its implementation would be differerent, following the FMT_STRING_ALIAS (or something else) definition.

```cpp
fmt::format("I have {:d} apples\n"_fmt, 2);
```

**Comment by vitaut** [comment]
> I like this feature but, its macro name is impractical.

You can use `FMT_STRING` instead (which doesn't need `FMT_STRING_ALIAS`): https://fmt.dev/dev/api.html#c.FMT_STRING or choose your own name:

```c++
#define myfmt(s) FMT_STRING(s)
fmt::format(myfmt("I have {:d} apples\n"), 2);
```

`_fmt` UDL would only work in C++20 or using a gcc extension.

**Comment by vitaut** [comment]
Closing since the `fmt` macro is not defined by default but a PR to optionally add UDL support is welcome.
