### ISSUE TITLE
read outside bounds

### ISSUE THREAD

**Issue by pauldreik** [fmtlib/fmt#1194]
Hi,
thanks for the performance advice on the fuzzer!
I switched to fmt::string_view and dropped the extra null. That gave me a crash in address sanitizer, which I reduced to the following test case:
```cpp
TEST(ChronoTest, outside) {
    try {
        const char format[] = {'{',':','{','A','}'};
        const auto N=sizeof(format);
        auto ignored=fmt::format(fmt::string_view(format,N),std::chrono::seconds{});
    }catch(...) {
     // dont care
    }
}
```

**Comment by vitaut** [comment]
Good catch. This looks like a regression in handling named arguments introduced by `fmt::prepare`. Fixed in https://github.com/fmtlib/fmt/commit/a38b99a188ad81c86b304d21d2cc6395fdc6c514.
