### ISSUE TITLE
MSVC 2017 Compile time errors when trying to include project.

### ISSUE THREAD

**Issue by gir489** [fmtlib/fmt#1201]
`Error (active)	E1866	attribute does not apply to any entity	Project	X:\Project\includes\fmt\include\fmt\core.h	469	
Error (active)	E1866	attribute does not apply to any entity	Project	X:\Project\includes\fmt\include\fmt\core.h	470	
Error	C2668	'fmt::v5::internal::arg_mapper<Context>::map': ambiguous call to overloaded function	Project	x:\Project\includes\\fmt\core.h	836	
Error	C2062	type 'unknown-type' unexpected	Project	x:\Project\includes\\fmt\core.h	998	
Error	C2039	'value': is not a member of '`global namespace''	Project	x:\Project\includes\\fmt\core.h	999	
Error	C3615	constexpr function 'fmt::v5::internal::encode_types' cannot result in a constant expression	Project	x:\Project\includes\\fmt\core.h	1101	
Error	C2131	expression did not evaluate to a constant	Project	x:\Project\includes\\fmt\core.h	1103	
`

**Comment by vitaut** [comment]
`master` works fine with MSVC2017: https://godbolt.org/z/_E5osy. If you still get the error, please provide a reproducible example.
