### ISSUE TITLE
Support ranges::view directly in fmt::print()

### ISSUE THREAD

**Issue by Daniel-G-W-Hug** [fmtlib/fmt#1202]
Ranges support in fmt/ranges.h works fine for standard containers, but not for range views directly (see example below). Can range views be supported by fmt directly?

This seems to be relevant, in case  ranges::to<>, which is proposed to convert range views into containers as a replacement for e.g. ranges::to_vector()- which itself is part of range-v3, but will not become part of Cpp20 according to my knowledge - does not make it into Cpp20.

// main.cpp
#include <vector>
#include <fmt/ranges.h>
#include "range/v3/all.hpp"
using namespace ranges;

int main() {
    std::vector<int> vi = {6,2,3,4,5,6,7,7,5,1,2,3,4};
    fmt::print("vi = {}\n",vi);

    auto is_even = [](int i) {return i % 2 == 0;};
    auto after_dropping_evens = vi | view::drop_while(is_even) | view::take(7);

    fmt::print("after_dropping_evens = {}\n",to_vector(after_dropping_evens));  // works after converting view into vector by to_vector()
    // fmt::print("after_dropping_evens = {}\n",after_dropping_evens);  // does not compile

    return 0;
}

**Comment by vitaut** [comment]
Support for the `ranges/v3` library can be done via the extension API: https://fmt.dev/latest/api.html#formatting-user-defined-types. Once C++20 is out we might add formatters for standard ranges directly into {fmt}.
