### ISSUE TITLE
Undefined reference fmt::v5::format_error::~format_error() when building dll

### ISSUE THREAD

**Issue by HazardyKnusperkeks** [fmtlib/fmt#1205]
Hi, same setup as in #1204.

I get multiple
> \<file>: (.text+0x2c): undefined reference to `fmt::v5::format_error::~format_error()'

The destructor was added in commit 1c3197b8d84884b0e16ba76b2c211ac35d2fa679 defined in `format-inl.h`, but in <file> I only `#include <fmt/format.h>`. I think it should be added there, or the class has to be exported.

**Comment by vitaut** [comment]
The destructor should be marked with `FMT_API`. Could you submit a PR?

**Comment by HazardyKnusperkeks** [comment]
Done.
