### ISSUE TITLE
FMT + GNU gettext() bug

### ISSUE THREAD

**Issue by SzykCech4** [fmtlib/fmt#1207]
Hi
At the begining I explain what and why I am doing with Fmt and Gnu gettext(), then I explain my bug (not minimal) example.

[What and why I am doing]
I am fedup with Qt library quircks and vendor lock to their custom Qml language on mobile platforms - I am C++ programmer and I want write programs in pure C++! So I try to write new core library in pure C++ (it can be base platform for many other libraries like Gui and transparent network calls). Essential part of this library is comfortable and modern string manipulations.
So: I need to have parametrized format strings (not sily fragmented by iostreams operators) in order to translate them properly. So I discover FMT library. In order to translate text I am stuck with GNU gettext() - I can't see any other option. Another feature I want to implement is internal library strings representation as "wide strings". From the very begining I realized that it involve very often usage gToWide() and gToNarrow() functions. But I can do this. So I implement two macros:
```
#define fr(Str, ...) fmt::format(Str, ##__VA_ARGS__)
#define tr(Str) gToWide(gettext(Str))

```
In order to make very easy translations like this:
```
std::wstring lError(fr(tr("Sender: {0}, error code: {1}, file: {2}, line: {3}"
        ", function: {4}\nError message:\n{5}")
        , aSenderName, aErrorCode, aFileName, aLineNumber
        , aFunctionName, aMessage));
```
I give great attention to quality from the very begining of writing this library, so I wrote few dozens unit tests. Almost all of them runs as expected, other I fixed quickly. But one remain and I cant manage to fix it.

[My (not minimal) example]
```
    try
    {
        throw EKT2_EXCEPTION(tr("My exception."), gComponent, eNotImportant);
    }
    catch(std::exception& aEx)
    {
        std::wcerr << fr(tr("Exception occurs! Message:\n{0}"), gToWide(aEx.what()))
            << std::endl << std::flush;
    }

```
Problem is with this code with translation to Polish language (without translation it works fine). In this code I throw my custom exception (std::exception subclass) with one simple parameter: translated "My exception" string and converted from char* to wide string (for formating purpose inside exception class and again converted to narrow string in order to pass it through overloaded const char* std::exception.what()). Next I catch this exception and translate to polish and convert to wide string "Exception occurs! Message:\n{0}" and convert what() otput to wide string in order to avoid fr error (it seems that it can't mix wstring with string). But I got error:
```
terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_filebuf::_M_convert_to_external conversion error: iostream error
```
I know this error well and I fix it in few places. It appears when I have first (format) string as wstring, and pass narrow string(s) as parameter(s). But as you can see I use gToWide on what() output so this is not a case (I suppose).

I attach full example. In order to compile it you have install Cmake, Gnu gettext and fmtlib. My system is Kubuntu 18.04 LTS.
Please help me brak out from Qt vendor lock library.
best regards
Szyk Cech
[FmtMacroBug.zip](https://github.com/fmtlib/fmt/files/3321942/FmtMacroBug.zip)

**Comment by vitaut** [comment]
This is an iostreams and not {fmt} error, perhaps coming from the conversion method (gToWide?)
