### ISSUE TITLE
fmt.dev API docs out of date?

### ISSUE THREAD

**Issue by BillyDonahue** [fmtlib/fmt#1208]
https://fmt.dev/latest/api.html still refers to time.h, but this was updated to chrono.h in api.rst.
https://github.com/fmtlib/fmt/blob/master/doc/api.rst

**Comment by vitaut** [comment]
`latest` links to the docs for the latest release. The docs for the unreleased development (`master`) branch are here: https://fmt.dev/dev/api.html.
