### ISSUE TITLE
custom formatter broken after-v5.30

### ISSUE THREAD

**Issue by BillyDonahue** [fmtlib/fmt#1209]
https://gcc.godbolt.org/z/EYGww4

I used to format my type to a `fmt::writer`, which is nice because fmt::writer is a concrete type, and I don't have to define the .append method in my header.

This works in `fmt-5.3.0` but not in trunk. Am I doing something unsupported? I am having a hard time figuring out how to make a `fmt::writer` in the trunk revision without encroaching on the `fmt::internal` namespace.

```

namespace fmt {
template <>
struct formatter<user::HostAndPort> {
    template <typename ParseContext>
    auto parse(ParseContext& ctx) -> decltype(ctx.begin()) {
        return ctx.begin();
    }

    template <typename FormatContext>
    auto format(const user::HostAndPort& hp, FormatContext& ctx) {
        fmt::writer w(ctx.out());
        hp.append(w);
        return ctx.out();
    }
};

}  // fmt

```

```candidate constructor not viable: no known conversion from 'fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::buffer<char> >, char>::iterator' (aka 'std::back_insert_iterator<fmt::v5::internal::buffer<char> >') to 'fmt::v5::internal::buffer_range<char>' for 1st argument```

Original code:
https://github.com/mongodb/mongo/blob/18ca0d551818d6c8274358b8e6444640bec93c88/src/mongo/util/net/hostandport.h#L164

**Comment by vitaut** [comment]
> Am I doing something unsupported?

Yes, `writer` was an undocumented API that was left over from an old design and made `internal` in preparation for the next major release.
