### ISSUE TITLE
fmt::format_to_n doesn't append trailing \0 character

### ISSUE THREAD

**Issue by hzeba** [fmtlib/fmt#1212]
As the title says, fmt::format_to_n() doesn't append the trailing \0 character when outputing to char[]. The version I'm using is 5.3.0.

This snippet:

```
char out[5] = {'1', '2', '3', '4', '\0'};
fmt::format_to_n(out, sizeof(out), "{}", "ab");

fmt::print("{}\n", out);
```

outputs:

```
ab34
```

which seems counter intuitive when compared to snprintf() & co. The workaround is:

```
char out[5] = {'1', '2', '3', '4', '\0'};
auto r = fmt::format_to_n(out, sizeof(out) - 1, "{}", "ab");
out[r.size] = '\0';
```

which looks a bit odd in the code.

Is this behavior by design? Am I missing something?

Thank you,

Hrvoje Zeba

**Comment by vitaut** [comment]
> Is this behavior by design?

Yes, this is by design. Null termination is often not needed and, if needed, can be achieved by appending `'\0'` explicitly.
