### ISSUE TITLE
Why this format throw exception

### ISSUE THREAD

**Issue by DinoStray** [fmtlib/fmt#1216]
`        fmt::format(
            R"({"id":{:s},"result":[[["mining.set_difficulty","00"],["mining.notify","00"]],"00",{:d}],"error":null})",
            "01015c6124934c8f97b72c180b24810a82f2550b7f2be925b77b0f5c0a4bf2dd12f018",
            8);`

I only want format 
{:s} ->"01015c6124934c8f97b72c180b24810a82f2550b7f2be925b77b0f5c0a4bf2dd12f018"
{:d} -> 8
this format throw exception:
"invalid format string"
why?

**Comment by vitaut** [comment]
You escaped braces, i.e. replace `{` and `}` with `{{` and `}}`: 

```c++
fmt::format( R"({{...}})", ...)
```
