### ISSUE TITLE
Formatting of floating point numbers does not respect locale settings

### ISSUE THREAD

**Issue by schoetbi** [fmtlib/fmt#1218]
I have the attached code and want to format the floating point number with an decimal comma instead of a point. This seems not to be implemented in write_double since the decimal separator is hard coded in [format.h](https://github.com/fmtlib/fmt/blob/ab0ba8a9d0ef694bfb346cd3b2f238e5e270d826/include/fmt/format.h#L1089):  

```
#include <iostream>
#include <fmt/format.h>
#include <fmt/locale.h>

struct numpunct : std::numpunct<char> {
  protected:
	char do_decimal_point() const override
	{
		return ',';
	}
};

int main(void) {
    std::locale loc;
    std::locale l(loc, new numpunct());
    std::cout << fmt::format(l, "{0:f}", 1.234567);
}
```

**Comment by vitaut** [comment]
`f` format specifier is locale-independent by design. #1084 will add the `n` specifier for locale-aware formatting.

**Comment by schoetbi** [comment]
@vitaut : Thanks you for the hint to #1084. As I understand it, it is mainly due to compatibility with the python format strings necessary to have ``n`` instead of ``f```. As a (novice) user of the api I would expect that the locale settings are respected if I use the first parameter to be an instance of std::locale:

```
std::locale loc;
std::locale loc_de(loc, new numpunct());
fmt::format(loc_de, "{0:f}", 1.234567);
```

It seems that in the previous code snipped I do provide explicit locale settings but they are not used because of the ``f``` specifier.

Did I understand this right? What would be the problem if the locale setting would be applied event to arguments with an format specifier ``f``? The only use case that I could think of would be a format string where I do want to format one floating point variable with locale settings and another variable without it. 

```
fmt::format(loc_de, "{0:f} {0:n}", 1.234567, 2.345678);
// gives 1.234567 2,345678
```
But I think this is very rare case.  Or are there other reasons I do not see?

**Comment by vitaut** [comment]
It's not just due to compatibility. It's an explicit design decision to give users control over the use of the locale. Passing locale to `format` doesn't change semantics of format specifiers, just makes the latter use the passed locale instead of the global one.

> What would be the problem if the locale setting would be applied event to arguments with an format specifier f?

See http://open-std.org/JTC1/SC22/WG21/docs/papers/2015/n4412.html for some background why locale-independent formatting is important.

**Comment by en-em** [comment]
> It's an explicit design decision to give users control over the use of the locale.

How does the user have control if he passes a locale argument to the function and the function simply ignores it?

> Passing locale to format doesn't change semantics of format specifiers, just makes the latter use the passed locale instead of the global one.

The grisu floating point formatter ignores both the global locale and the passed-in locale. The sprintf floating point formatter ignores the passed-in locale but respects the global locale. There is a glaring inconsistency here.

> why locale-independent formatting is important.

It is important, but the user specifically requested locale-dependent formatting by passing a locale argument in.

**Comment by vitaut** [comment]
> How does the user have control if he passes a locale argument to the function and the function simply ignores it?

The locale argument is not a way to control the behavior of individual format specifiers, it just overrides the global locale.

> The sprintf floating point formatter ignores the passed-in locale but respects the global locale. 

No, `sprintf` is only used for digit generation and it doesn't use the global C++ locale.

The `n` specifier is the way to enable locale-aware formatting. It's just not implemented yet for floating-point in `master`.

**Comment by schoetbi** [comment]
@vitaut Now I understand. The first parameter is here to overwrite the global locale, inside the format string n/f controls if a locale should be used or not. Thanks for the clarification.

**Comment by en-em** [comment]
> it just overrides the global locale.

Why override the locale if it is ignored anyway?

> No, sprintf is only used for digit generation and it doesn't use the global C++ locale.

Apparently not always. The locale-specific decimal point is used when when you use the A format specifier (that's what I was using for a quick and dirty test). It is indeed replaced with a period in other cases.

> The n specifier is the way to enable locale-aware formatting. It's just not implemented yet for floating-point in master.

There are several floating point format specifiers (f, e, a) and one needs too many letters not used by Python fmt to enable them all. Then Python introduces these letters for other purposes and you have an inconsistency on hand. One needs a different method to specify locale-aware output. Passing in a locale argument is a very good method indeed. It is inconsistent with the statement

> Passing locale to format doesn't change semantics of format specifiers, just makes the latter use the passed locale instead of the global one.

but this statement need not be considered a gospel. The global locale is C baggage and one doesn't need to be burdened by it. If one wants locale specific output, let them pass the locale in. Easy!

**Comment by vitaut** [comment]
> The locale-specific decimal point is used when when you use the A format specifier (that's what I was using for a quick and dirty test).

This is just an artifact of the current implementation and will be fixed, so don't read to much into it =). Also it uses the C locale, not C++.

> one needs too many letters not used by Python fmt to make locale-aware versions of all of them

It's enough to add at most one modifier, possibly reusing an existing one. Also 100% compatibility with Python is not a goal.

> The global locale is C baggage and one doesn't need to be burdened by it.

Dropping support for the global locale is a non-starter because it would introduce a huge usability regression compared to `str.format` and even `printf`.

Anyway, as commented elsewhere, {fmt} provides enough infrastructure to be able to implement your approach with moderate efforts. It doesn't have to be in the core library.
