### ISSUE TITLE
Suggestion: custom namespace

### ISSUE THREAD

**Issue by lgritz** [fmtlib/fmt#1219]
It would be great if software using fmt could `#define FMT_CUSTOM_NAMESPACE my_fmt` prior to the `#include <fmt/format.h>`, and that this would result in a custom namespace being applied, in order to absolutely positively safeguard against clashes with another software component (say, two separate libraries used by the same app) from being mismatched. I know that there is an inner namespace with the version number, but I wonder if two v5's originating at different snapshotted commits might mis-interact and would be served by being able to lock down a custom namespace.

**Comment by vitaut** [comment]
Thanks for the suggestion but I think it would be too messy. See https://github.com/fmtlib/fmt/issues/282#issuecomment-190958067 for a possible alternative.
