### ISSUE TITLE
Remove FMT_DEPRECATED from basic_writer/writer/wwriter?

### ISSUE THREAD

**Issue by chronoxor** [fmtlib/fmt#1220]
Is it possible to remove FMT_DEPRECATED from basic_writer/writer/wwriter? Just because it could be used in client code. 

For example for storing logging arguments and format them later (https://github.com/chronoxor/CppLogging/blob/master/source/logging/record.cpp)

**Comment by vitaut** [comment]
The undocumented writer API is a leftover from the old design. Please use the format API instead.

**Comment by chronoxor** [comment]
Victor, can you confirm that format API has all required functionality now to read format arguments from some buffer (e.g. memory stream or file) and format them according to the given format string? I need something like this function:
```
std::string RestoreFormat(std::string_view pattern, const std::vector<uint8_t> buffer)
{
  ...
}
```

Currently I parse the `pattern` format string, extract arguments from the `buffer` and write them into string using fmt::writer which is internal/deprecated for now. I know it's a hack of fmt internals, but it works! :)

**Comment by vitaut** [comment]
Well, you'll have to do the reading part yourself (which I guess you already do). There is nothing in the format or the old write API for that. But once they have been read you can construct the argument list dynamically with https://github.com/fmtlib/fmt/blob/bc14c6ee20869133a66a9f0f1d05a206e769f1c6/include/fmt/core.h#L1182
and pass it to one of the format functions that take `format_args` such as `vformat`.

**Comment by vitaut** [comment]
Closing as the write API will remain deprecated, but let me know if you have any questions regarding migration to the format API.
