### ISSUE TITLE
C style varargs support?

### ISSUE THREAD

**Issue by DaanDeMeyer** [fmtlib/fmt#1221]
I'm integrating with a C library that logs via a C style variadic callback function. Is there any way to log a C style format + varargs with fmt?

I found some older issues discussing this and it didn't seem possible then but I'm wondering if this is still the case.

**Comment by vitaut** [comment]
> Is there any way to log a C style format + varargs with fmt?

No. varargs are inherently unsafe and are not supported.

**Comment by DaanDeMeyer** [comment]
For reference, I solved the issue by just calling `vsnprintf` with a stack allocated array and the given format + args in the logging callback and passing the resulting formatted string to my logging function which takes a format and variadic template args which are then passed to fmt (no args are passed since the string is already formatted). 

```c++
static void log_cb(void *context, const char *format, ...)
{
  auto client = static_cast<client::impl *>(context);

  std::array<char, 1024> formatted;

  va_list args;
  va_start(args, format);

  vsnprintf(formatted.data(), formatted.size(), format, args);

  va_end(args);

  BNL_LOG_INFO(client->logger(), formatted.data()); // Calls `fmt` internally
}
```
