### ISSUE TITLE
Issue using "%.4lf" and very small value

### ISSUE THREAD

**Issue by alastairUK** [fmtlib/fmt#1222]
```
#include <iostream>

#include "fmt/printf.h"

#pragma comment(lib, "fmtd.lib")

int main()
{
    double someVerySmallValue = 7.2809479766055470e-15;

    printf("%.4lf\n", someVerySmallValue);

    fmt::printf("%.4lf\n", someVerySmallValue);

    printf("Done\n");
}
```

Produces the following on x86 MSVC 2019

0.0000
0.00001
Done

Weirdly in my actual project code I see 0.00000 when I would expect 0.0000

**Comment by vitaut** [comment]
Great catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/edd13fcc1cc4b0d3f24925118ac5cc745baea2b6.
