### ISSUE TITLE
Custom Formatter Specified outside of `fmt` namespace?

### ISSUE THREAD

**Issue by dpacbach** [fmtlib/fmt#1223]
Hi, is there a way (maybe relying on ADL?) to define a custom formatter for a type without having to go into the `fmt` namespace?  Ideally I'd like to define the formatter in the same namespace as where I declare the custom type.  Thanks

**Comment by vitaut** [comment]
No, `formatter` specializations must be in the `fmt` namespace.

**Comment by vitaut** [comment]
Although {fmt} could use `operator<<` if available and the latter can be found via ADL: https://fmt.dev/latest/api.html#std-ostream-support

**Comment by dpacbach** [comment]
Thanks; in that case, may I request a new feature that does the following:

1. Provides a customization point (formatter) to the user, similiar to `operator<<`, which does not require being in the `fmt` namespace.
2. Usage of it does not require including any of C++'s stream headers.

I think that using `operator<<` is a good idea, but I just got my application to the point where I use only {fmt} and do not include _any_ `iostream` headers from C++.  Could {fmt} provide another customization point that works like `operator<<` but does not use streams?  It doesn't even have to be an operator, could just be a function.

If not, any suggestions on how I could hack one together myself?  Thanks

**Comment by dpacbach** [comment]
Perhaps a better way to ask this question would be:

"Can we have an ADL-based formatting customization point for {fmt} that does not involve C++ streams?"

**Comment by vitaut** [comment]
I don't think it's a good idea to have multiple extension points for the same purpose. Apart from compile time performance, using ADL is problematic because there is no object to dispatch on during format string parsing. There are some workarounds but they are awkward. Is there any particular reason you'd like to use ADL?

**Comment by avikivity** [comment]
Without this, some types are unformattable.

Examples:

```c++
void foo() {
    struct moo {
    };
    fmt::print("{}", moo()); // error: no way to define fmt::formatter<{function scope}::moo>
};
```

and

```c++
template <typename T>
struct bar {
    struct moo {};
};

template <typename T>
struct fmt::formatter<bar<T>::moo> { ... }; // error: can't infer T
```

These could be fixed with a formatter_for(T) that returns a formatter object.

```c++
// fallback, in core.h
template <typename T>
constexpr auto formatter_for(const T&) {
   return fmt::formatter<T>();
};

void foo() {
    struct moo {
        friend constexpr auto formatter_for(const moo&) {
             struct moo_formatter { ... };
             return moo_formatter();
        }
    };
    fmt::print("{}", moo()); // uses moo_formatter
};

template <typename T>
struct bar {
    struct moo {
        friend constexpr auto formatter_for(const moo&) {
             struct moo_formatter { ... };
             return moo_formatter();
        }
    };
};
```


Apart from supporting those types that can't be named from namespace scope, it allows placing formatters close to the types they format, without the need to close and reopen namespaces or to place the formatters away.

**Comment by vitaut** [comment]
I don't think ADL will help you with a class defined at a function scope. But we ended up adding an ADL-based extension point (`format_as`), initially for enums and now extended to all user-defined types.

**Comment by no-more-secrets** [comment]
@vitaut Any chance that the ADL-based mechanism will be standardized?

**Comment by avikivity** [comment]
format_as() works, but requires some boilerplate: create an external named type, link the data from the unnamed type to the named type, write a formatter for the named type.
