### ISSUE TITLE
Platform dependent rounding: VS 2019 (Windows) vs clang++ (Mac OSX)

### ISSUE THREAD

**Issue by t-b** [fmtlib/fmt#1224]
The following program

```
#include <fmt/format.h>
#include <iostream>

int main()
{
	std::cout << fmt::format("{:.{}e}", 2.5f, 0) << std::endl;
}
```

results in 

```
2e+00
```

on MacOSX using

```
Thomass-iMac:json-xop ci$ clang++ --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Thomass-iMac:json-xop ci$
```

and in

```
3e+00
```

on Windows using

```
Microsoft Visual Studio Community 2019
Version 16.1.3
```

I would expect the rounding to be platform independent.

g++ (6.3.0) on windows has the same behaviour than clang on MacOSX.

FMT version: f6f0415b (typedef -> using, 2019-07-07)

**Comment by vitaut** [comment]
Floating-point formatting in exponential notation currently falls back on `sprintf`, so any rounding differences come from there. Closing since this issue is effectively the same as #1032. Once the latter is done formatting will be platform-independent (at least for IEEE754).

**Comment by t-b** [comment]
@vitaut Thanks for looking into it.
