### ISSUE TITLE
Big binary size with GCC ARM compiler

### ISSUE THREAD

**Issue by vidavidorra** [fmtlib/fmt#1226]
I'm trying to use {fmt} in an embedded application and was expecting the influence of this library to be somewhere between 30 and 50 KiB in binary size (based on [code bloat section in readme](https://github.com/fmtlib/fmt#compile-time-and-code-bloat)). What I've found out, based on some simple compile tests I've done, is that the increase in code size with using {fmt} is more in the range of 260 KiB up to almost 300 KiB.

The results of my tests are below and were with a single format statement (from the examples) and the following compile flags. I've also tried the `-s` flag suggested [here on SO](https://stackoverflow.com/a/50687156), but found no significant improvement.

```cmake
SET(LD_SYS_LIBS "-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group")

SET(CMAKE_C_FLAGS "-std=gnu11 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -O2 -g1 -DMBED_DEBUG -DMBED_TRAP_ERRORS_ENABLED=1 -mcpu=cortex-m3 -mthumb -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x100000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x20000")
SET(CMAKE_CXX_FLAGS "-std=gnu++17 -fno-rtti -Wvla -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fexceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -O2 -g1 -DMBED_DEBUG -DMBED_TRAP_ERRORS_ENABLED=1 -mcpu=cortex-m3 -mthumb -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x100000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x20000")
SET(CMAKE_ASM_FLAGS "-x assembler-with-cpp -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -O2 -g1 -DMBED_DEBUG -DMBED_TRAP_ERRORS_ENABLED=1 -mcpu=cortex-m3 -mthumb")
SET(CMAKE_CXX_LINK_FLAGS "-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,__malloc_r -Wl,--wrap,__free_r -Wl,--wrap,__realloc_r -Wl,--wrap,__memalign_r -Wl,--wrap,__calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m3 -mthumb -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x100000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x20000 -DMBED_BOOT_STACK_SIZE=1024")
```

This is using the following `arm-none-eabi-gcc` compiler version.

```
(GNU Tools for Arm Embedded Processors 7-2018-q2-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
```

Is this kind of increase in binary size expected or is there anything I can do to improve this? I'm using f6f0415b833e8ba32b7b641f00d01a7fd8dbb6be BTW but had roughly the same results with the 5.3.0 release.

| Size without {fmt} | Size with {fmt} | `-O` | `--spec=`     |
| ------------------ | --------------- | ---- | ------------- |
| 91,112             | 395,072         | 0    | `nosys.specs` |
| 69,356             | 339,312         | 1    | `nosys.specs` |
| 68,752             | 337,624         | 2    | `nosys.specs` |
| 71,340             | 341,928         | 3    | `nosys.specs` |
| 66,384             | 322,220         | s    | `nosys.specs` |
| 69,964             | 344,844         | g    | `nosys.specs` |

**Comment by vitaut** [comment]
Most efforts have been put into optimizing the per-call binary size (which is what the {fmt}'s code bloat benchmark reports) which is proportional to the number of calls. What you are observing is a fixed cost of statically linking with the whole library which is indeed around 200-300 kilobyte depending on the system.

You should be able to reduce the binary size by enabling link-time optimization which will remove unused symbols from your program. I don't remember exact numbers but there were some positive reports from users who did this.

**Comment by vidavidorra** [comment]
Thanks for the quick response and letting me know.

> What you are observing is a fixed cost of statically linking with the whole library which is indeed around 200-300 kilobytes depending on the system.

Was not aware of this based on the per-call binary size so thanks for explaining. Maybe it is useful for others to have this 200-300 KiB noted in the readme.

> You should be able to reduce the binary size by enabling link-time optimization which will remove unused symbols from your program. I don't remember exact numbers but there were some positive reports from users who did this.

I've been able to get it down but just a bit (about 20 KiB) using link time optimisation (LTO). I guess this is just not very suited for embedded systems with limited flash where 200 KiB is a lot, even if you have a 1 or 2 MiB. At least now I won't have to debug this issue any further. I'll probably just stick with the standard `printf`.

**Comment by vitaut** [comment]
Another discussion of using {fmt} in an embedded context is here: #758

**Comment by vitaut** [comment]
The current size is closer to 100k with `-DNDEBUG -flto` on macOS.

**Comment by ecorm** [comment]
Is it possible to make fmt use a slow but flash-efficient algorithm for printing decimal numbers, instead of Dragonbox?

**Comment by vitaut** [comment]
We are about to switch to https://github.com/vitaut/zmij which should be more compact (https://vitaut.net/posts/2026/complete-to-chars/).

**Comment by vitaut** [comment]
You can also turn off various features, see https://fmt.dev/dev/api/#binary-size-optimization

**Comment by ecorm** [comment]
Those are impressive numbers for zmij. Well done! Thank you for all your great contributions.

For embedded, you often only need formatting for display purposes or logging to a serial port, so the formatting doesn't need to be fast. It would be nice if fmt can be configured to use a naive-ish algorithm for printing decimal numbers, where it doesn't need to rely on a large table of constant values.
