### ISSUE TITLE
`count_digits()` could be faster

### ISSUE THREAD

**Issue by BillyDonahue** [fmtlib/fmt#1227]
All of this applies to the case where there's no `__builtin_clz` and we use the slower count_digit loop implementation.

```
// Integer division is slow so do it for a group of four digits instead
// of for every digit. The idea comes from the talk by Alexandrescu
// "Three Optimization Tips for C++". See speed-test for a comparison.

```
https://github.com/fmtlib/fmt/blob/a3a74672a0c09be935b1863b5deea8c085ba2b76/include/fmt/format.h#L682

He unrolled the div loop by 4 steps I think just to show that it helps a bit.
But he could have unrolled it all the way and gotten even faster code.

```
constexpr std::size_t pow10(std::size_t n) {
    std::size_t r = 1;
    for (std::size_t i = 0; i < n; ++i) {
        r *= 10;
    }
    return r;
}

inline int count_digits(uint64_t n) {
        if (n < pow10(1)) return 1;
        if (n < pow10(2)) return 2;
        if (n < pow10(3)) return 3;
        if (n < pow10(4)) return 4;
        if (n < pow10(5)) return 5;
        if (n < pow10(6)) return 6;
        if (n < pow10(7)) return 7;
        if (n < pow10(8)) return 8;
        if (n < pow10(9)) return 9;
        if (n < pow10(10)) return 10;
        if (n < pow10(11)) return 11;
        if (n < pow10(12)) return 12;
        if (n < pow10(13)) return 13;
        if (n < pow10(14)) return 14;
        if (n < pow10(15)) return 15;
        if (n < pow10(16)) return 16;
        if (n < pow10(17)) return 17;
        if (n < pow10(18)) return 18;
        return 19;
}

```

My own benchmarking shows this to more than 2x better.

```
BM_CountDigits<0>/18       8528 ns       8527 ns      81955   111.836M items/s  (orig)
BM_CountDigits<2>/18       3951 ns       3951 ns     174156   241.398M items/s  (unrolled)

```

**Comment by vitaut** [comment]
Thanks for the suggestion.

>  there's no __builtin_clz

Which platform is that? `__builtin_clz` or its equivalent is almost universally available.

**Comment by BillyDonahue** [comment]
I encountered this in gcc9, Linux x86_64, FWIW.

I was pasting the count_digits() algorithm into a `constexpr` function, so can't use `__builtin_clz`.

**Comment by vitaut** [comment]
This is better addressed by dispatching to different versions of `count_digits` depending on whether you are in a `constexpr` context or not. I don't think it's worth investing in optimizing the fallback implementation.

**Comment by vitaut** [comment]
Moreover, `count_digits` is not `constexpr`.
