### ISSUE TITLE
Checksum of fmt 5.3.0 tag

### ISSUE THREAD

**Issue by jslee02** [fmtlib/fmt#1234]
It seems the tag for `fmt` 5.3.0 has been changed because the checksum is different than one month ago. Could you please confirm that this is correct? This is to correctly update the `fmt` spack package (see: https://github.com/spack/spack/pull/12037).

**Comment by vitaut** [comment]
The tag hasn't changed since December. Not sure why the checksum is different, maybe GitHub made some compression-related changes.

**Comment by jslee02** [comment]
Thank you for the confirmation.
