### ISSUE TITLE
Question: Is printf style formatting still supported.

### ISSUE THREAD

**Issue by strasdat** [fmtlib/fmt#1242]
In the README it says

> fmt::printf("Hello, %s!", "world"); // printf format string syntax

However, when trying it out, it prints ``%s!`` for me.

Note: I'm not asking for printf-style support. I'd rather suggest to update the README.

**Comment by eliaskosunen** [comment]
Cannot reproduce: https://godbolt.org/z/MQRsu7

**Comment by strasdat** [comment]
I can reproduce it on gobolt, if using ``format`` instead of ``printf``: https://godbolt.org/z/IqTpVb

Possibly, I'm just using ``format`` wrongly?

**Comment by eliaskosunen** [comment]
`format`/`print` take Python-like `{arguments}`, `printf` takes printf-like `%arguments`

**Comment by strasdat** [comment]
I see, thanks! Probably best to add this statement to the readme.
