### ISSUE TITLE
Percentage and version 5.3.0

### ISSUE THREAD

**Issue by arnaudbrejeon** [fmtlib/fmt#1245]
Hi,

I started using this library for the first time and downloaded version 5.3.0.
When I run the code from the formatting examples:
`fmt::format("{0:f} or {0:%}", .635);`
I'm getting
`libc++abi.dylib: terminating with uncaught exception of type fmt::v5::format_error: invalid type specifier`

Is percentage supported as stated in the library documentation?

**Comment by mwinterb** [comment]
Percentage wasn't added until 79b79f329ea126c14d150d9b75668ed137b33c42,
which was a few months after the 5.3.0 release.

**Comment by arnaudbrejeon** [comment]
I see. Thank you.
