### ISSUE TITLE
Inconsistencies in floating-point formatting

### ISSUE THREAD

**Issue by BongoVR** [fmtlib/fmt#1247]
Hello,

there seem to be some issues with respect to floating-point formatting. I am using MSVC 2015 on a German Windows 10 and can see the following issues with the code below:
![fmt-float](https://user-images.githubusercontent.com/14230466/61774952-3d182d00-adf8-11e9-9a2f-66637b7461b6.png)

1.  The fmt library deviates from the iostreams library when handling thousands separators for integers. When using the C (resp. classic) locale, no thousands separators should be included.

2. However, the thousands separator is missing in the string formatted with the de_DE locale.

3. When using the locale-aware format string, the fractional digits are left out. However, using the locale-agnostic string, there is a trailing ".0" where it need not be.

4. When formatting an integer floating point number (e. g. 199.0) the g format specifier omits the decimal separator and produces wrong output. Number 199.1, for instance, works.

Additionally, there seems to be no possibility to combine the n format specifier with the g specifier at the same time so that there is no possibility to use locale-aware formatting.

BTW, the documentation states that the precision given with the format specifier g is the number of digits. It seems to be the case that the decimal separator is counted as a "digit" which is not correct. The strings in the output are 8 characters long but only show 7 digits.

Best regards

using tstring = std::wstring;
int main()
{
	std::locale normal("");
	std::locale::global(normal);
	setlocale(LC_ALL, "");

	const tstring seq = L"unbound, de_DE, C, classic";

	tstring text;
	try
	{
		std::wcout << text << std::endl;
		std::wcout << "\nstd::iostreams (" << seq << ") 12348563\n";
		std::wcout << 12348563 << L" <-> ";
		std::wcout.imbue(normal);
		std::wcout << 12348563 << L" <-> ";
		std::wcout.imbue(std::locale("C"));
		std::wcout << 12348563 << L" <-> ";
		std::wcout.imbue(std::locale::classic());
		std::wcout << 12348563 << std::endl;
		std::wcout << "\nfmt::format (" << seq << ") 12348563\n";
		text = fmt::format(_T("{0}"), 12348563);
		std::wcout << text << L" <-> ";
		text = fmt::format(normal, _T("{0:n}"), 12348563);
		std::wcout << text << L" <-> ";
		text = fmt::format(std::locale("C"), _T("{0:n}"), 12348563);
		std::wcout << text << L" <-> ";
		text = fmt::format(std::locale::classic(), _T("{0:n}"), 12348563);
		std::wcout << text << std::endl;

		std::wcout << "\nstd::iostreams (" << seq << ") 1485.63\n";
		std::wcout << 1485.63 << L" <-> ";
		std::wcout.imbue(normal);
		std::wcout << 1485.63 << L" <-> ";
		std::wcout.imbue(std::locale("C"));
		std::wcout << 1485.63 << L" <-> ";
		std::wcout.imbue(std::locale::classic());
		std::wcout << 1485.63 << std::endl;
		std::wcout << "\nfmt::format (" << seq << ") 1485.63\n";
		text = fmt::format(_T("{0}"), 1485.63);
		std::wcout << text << L" <-> ";
		text = fmt::format(normal, _T("{0:n}"), 1485.63);
		std::wcout << text << L" <-> ";
		text = fmt::format(std::locale("C"), _T("{0:n}"), 1485.63);
		std::wcout << text << L" <-> ";
		text = fmt::format(std::locale::classic(), _T("{0:n}"), 1485.63);
		std::wcout << text << std::endl;

		std::wcout << "\nfmt::format (" << seq << ") 199.0\n";
		text = fmt::format(_T("{0}"), 199.0);
		std::wcout << text << L" <-> ";
		text = fmt::format(normal, _T("{0:n}"), 199.0);
		std::wcout << text << L" <-> ";
		text = fmt::format(std::locale("C"), _T("{0:n}"), 199.0);
		std::wcout << text << L" <-> ";
		text = fmt::format(std::locale::classic(), _T("{0:n}"), 199.0);
		std::wcout << text << std::endl;

		std::wcout << "\nfmt::format (" << seq << ") 199.0\n";
		text = fmt::format(_T("{0:0<8g}"), 199.0);
		std::wcout << text << L" <-> ";
		text = fmt::format(normal, _T("{0:0<8g}"), 199.0);
		std::wcout << text << L" <-> ";
		text = fmt::format(std::locale("C"), _T("{0:0<8g}"), 199.0);
		std::wcout << text << L" <-> ";
		text = fmt::format(std::locale::classic(), _T("{0:0<8g}"), 199.0);
		std::wcout << text << std::endl;

		std::wcout << "\nfmt::format (" << seq << ") 199.1\n";
		text = fmt::format(_T("{0:0<8g}"), 199.1);
		std::wcout << text << L" <-> ";
		text = fmt::format(normal, _T("{0:0<8g}"), 199.1);
		std::wcout << text << L" <-> ";
		text = fmt::format(std::locale("C"), _T("{0:0<8g}"), 199.1);
		std::wcout << text << L" <-> ";
		text = fmt::format(std::locale::classic(), _T("{0:0<8g}"), 199.1);
		std::wcout << text << std::endl;
	}
	catch (fmt::format_error& e)
	{
		printf(e.what());
	}

**Comment by vitaut** [comment]
Thanks for reporting.

The `0<8g` giving "19900000" is meaningless but correct because you explicitly requested left alignment with zero padding =). You'll get the same behavior in Python:

```python
>>> "{0:0<8g}".format(199.0)
'19900000'
```

Formatting of `1485.63` looks correct as well:

```python
>>> locale.setlocale(locale.LC_ALL, "de_DE")
'de_DE'
>>> "{:n}".format(1485.63)
'1485,63'
```

I'll check the remaining two issues (unnecessary decimal point and thousands separator).

**Comment by BongoVR** [comment]
Thank you for your quick response.

However, I beg to differ. If I have a floating point variable that happens to be an exact integer, I would strongly prefer to get a result like "199.0000" and not a (huge) integer. After all, formatting works correctly if the value of the variable is not exactly integer (like 199.1 in the above example). If this bug is present in Python, there is still no reason to replicate it in C++. As it is, this is a real show-stopper.

About the second topic: Yes, 1485,63 looks correct. However, the output is different from the output of the iostreams library. And, it does not fully respect the Regional Settings from Windows. So, it seems that the locale information is not fully used with floating point variables. On the other hand, the integer variables (at the beginning) do correctly use the thousands separator, though.

Best regards

**Comment by vitaut** [comment]
> I would strongly prefer to get a result like "199.0000" and not a (huge) integer.

Then you should request to always output a decimal point with the `#` specifier:

```c++
auto s = fmt::format("{0:0<#8g}", 199.0); // s == "199.0000"
```
It will still make no sense if you have an exponent though, so it's not a correct way to pad with zeros. Please see the docs for details: https://fmt.dev/latest/syntax.html#format-specification-mini-language

The output of `fmt::format(std::locale::classic(), "{:n}", 12348563)` being "12,348,563" is also correct because the classic locale has the decimal separator `,`: https://godbolt.org/z/tXPKzg . I'm not sure why the decimal separator is ' ' on your platform for the "C" locale, it should normally be ',' as well. 
What does

```c++
std::use_facet<std::numpunct<wchar_t>>(std::locale("C")).thousands_sep();
```
return?

`199.0` is technically correct, but trailing zero and decimal point are redundant and should probably be dropped.

**Comment by vitaut** [comment]
The issue with broken "C" locale on Windows has been worked around in https://github.com/fmtlib/fmt/commit/3268531bc97c9036f7d582b0a2e7b66fdba18718. The remaining cases have the expected behavior and are consistent with Python's `str.format`.

**Comment by BongoVR** [comment]
One remark:

std::use_facet<std::numpunct<wchar_t>>(std::locale("C")).thousands_sep();
and
std::use_facet<std::numpunct<wchar_t>>(std::locale::classic()).thousands_sep();

do indeed return different values although the classic locale "Obtains a reference to the C++ locale that implements the classic "C" locale semantics." (https://en.cppreference.com/w/cpp/locale/locale/classic). So, this explains the differences for integers.

**Comment by lexxmark** [comment]
> 199.0 is technically correct, but trailing zero and decimal point are redundant and should probably be dropped.

@vitaut Do you think Python's str.format should surpass C++ streams in fmt library?

Because `std::cout << (float)42;` returns "42" (not "42.0" which is `fmt::format("{}", (float)42);` now)

**Comment by vitaut** [comment]
> Do you think Python's str.format should surpass C++ streams in fmt library?

{fmt} should follow the standard spec: https://eel.is/c++draft/format
