### ISSUE TITLE
[5.3.0] Windows 10 terminal color is not working

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [fmtlib/fmt#1249]
[There seems to be a problem with color in Win10 console in 5.3.0 version.](https://i.imgur.com/7VmaHH1.png)

**Comment by vitaut** [comment]
Color support requires a terminal that support ANSI escape codes: https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by IlyaStuurFedorov** [comment]
And still, there is a "Windows 10 Console" in the seventh column of that exact table.
