### ISSUE TITLE
FMT_HAS_INCLUDE

### ISSUE THREAD

**Issue by bumbar1** [fmtlib/fmt#1251]
Follow up on [issue 842](https://github.com/fmtlib/fmt/issues/842), commit [38ee424](https://github.com/fmtlib/fmt/commit/38ee424f3166932e8d492bc667e7d8bf771e9269) seems to break {fmt} on linux (ubuntu 16.04) with vscode (using intellisense):

![fmt](https://user-images.githubusercontent.com/2507237/61959742-5c63b580-afc4-11e9-8f82-dd29d7dc5349.png)

Removing the intellisense check builds fine.

**Comment by vitaut** [comment]
This looks like an editor not a build issue. In any case a PR is welcome but make sure that it doesn't break the MSVC workaround.

**Comment by vitaut** [comment]
Also `FMT_HAS_INCLUDE` is not required for {fmt} to work.
