### ISSUE TITLE
adl: FMT_STRING vs custom format_to

### ISSUE THREAD

**Issue by mwinterb** [fmtlib/fmt#1255]
I have a custom `format_to` function that's meant to be found through ADL, e.g. something like this:
https://gcc.godbolt.org/z/ohNntP
If `FMT_STRING` is used to provide the format string, the unconstrained `fmt::format_to` template is "now" picked up, presumably after commit 4d4b8c238d0ef7ed242d3fed550a3e85cbedd4e1, since converting the static_assert back to an enable_if allowed it to compile again. I'm currently compiling the tests and will hopefully run them soon so I may get my answer that way, but just in case someone else has done something similar,
- What was the reason for switching from `enable_if` to `static_assert`? The commit description is not enlightening on that point.
- `fmt::compile_string` is explicitly called out as being in the `fmt` namespace so that ADL finds the `fmt` functions, I'm guessing that's still a good idea?
- I'm guessing my format_to is a bad idea.

**Comment by vitaut** [comment]
> What was the reason for switching from `enable_if` to `static_assert`?

`enable_if` seemed unnecessary since there were no other `format_to` overloads in {fmt}. In general `static_assert` provides better error messages.

> I'm guessing that's still a good idea?

Yes.

if you really want to rely on ADL, I'd be open to a PR to reintroduce SFINAE in `format_to`, although I'd recommend namespace-qualifying the calls instead.

**Comment by mwinterb** [comment]
I'll try to see if I can resolve it in a way that keeps us both happy, which means retaining the `static_assert` in this case. (There's over 4000 calls to the should-be-namespace-qualified version, though technically only about 200 that "matter", so that's why I'm dreading your recommendation.)
