### ISSUE TITLE
Thousands separator in printf

### ISSUE THREAD

**Issue by davidrohr** [fmtlib/fmt#1257]
Is there any plan to support the ' (single quote) thousands separator for printf?
For me, `fmt::printf("test %'d\n", 123456);` throws an exception `invalid type specifier`.
I know it is not supported by all printf implementation, but on POSIX systems it is available, and I think it would be a valuable addition.

**Comment by vitaut** [comment]
No, there are no such plans at the moment. You could use the format API with a locale instead.
