### ISSUE TITLE
symbol clash when building `posix-mock-test` in VS2019 with static runtime

### ISSUE THREAD

**Issue by risa2000** [fmtlib/fmt#1258]
I am currently trying to add the `fmt` lib to the project, which builds with MSVC static runtime. It seems there is no support in the build scripts for that right now, so I am doing it with the hack by adding this to the top level CMakeList.txt:
```cmake
if(${CMAKE_VERSION} VERSION_GREATER_EQUAL 3.15)
  # Set policy to accept MSVC runtime selector (requires CMake >= 3.15)
  cmake_policy (SET CMP0091 NEW)
  set (CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
  message (STATUS "Building with static CRT.")
endif()
```
When building the compatible libs I noticed that while the libs (i.e. `fmt.lib`) build fine, the linker always complains when linking `posix-mock-test`:
```
LINK: command "C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1422~1.279\bin\Hostx64\x64\link.exe /nologo test\CMakeFiles\posix-mock-test.dir\posix-mock-test.cc.obj test\CMakeFiles\posix-mock-test.dir\__\src\format.cc.obj test\CMakeFiles\posix-mock-test.dir\test-main.cc.obj test\CMakeFiles\posix-mock-test.dir\gtest-extra.cc.obj test\CMakeFiles\posix-mock-test.dir\util.cc.obj /out:bin\posix-mock-test.exe /implib:test\posix-mock-test.lib /pdb:bin\posix-mock-test.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console test\gmock.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:bin\posix-mock-test.exe.manifest" failed (exit code 1169) with the following output:
libucrt.lib(strtod.obj) : error LNK2005: _strtod_l already defined in posix-mock-test.cc.obj
libucrt.lib(wsetlocale.obj) : error LNK2005: _create_locale already defined in posix-mock-test.cc.obj
libucrt.lib(wsetlocale.obj) : error LNK2005: _free_locale already defined in posix-mock-test.cc.obj
bin\posix-mock-test.exe : fatal error LNK1169: one or more multiply defined symbols found
ninja: build stopped: subcommand failed.
```

It seems that at least `strtod_l` is indeed defined in `posix-mock-test.cc` (I tracked it down to line 509 according to the preprocessor output). `libucrt.lib` is the POSIX CRT for the static linkage.

I am not really familiar with POSIX CRT in Windows, nor with the intentions of this particular test (others seem to compile fine), so I am just leaving it here for the record, so someone more knowledgeable can comment on this.

**Comment by vitaut** [comment]
This test won't work with the static runtime, so you should exclude it from the build as part of your changes.
