### ISSUE TITLE
Distinguishing "release" and "debug" build of the lib?

### ISSUE THREAD

**Issue by risa2000** [fmtlib/fmt#1259]
While building another project with the lib (MSVC), I need to maintain both Release and Debug version separately and link the right one according to the project target config.

So I added this to the top level `CMakeLists.txt`:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6e08aa5b..23f51dfb 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -162,6 +169,7 @@ endif ()

 add_library(fmt ${FMT_SOURCES} ${FMT_HEADERS} README.rst ChangeLog.rst)
 add_library(fmt::fmt ALIAS fmt)
+#set_target_properties(fmt PROPERTIES ARCHIVE_OUTPUT_NAME "fmt$<$<CONFIG:Debug>:d>")

 if (HAVE_STRTOD_L)
   target_compile_definitions(fmt PUBLIC FMT_LOCALE)
```
to add `d` to the debug build.
Would that be acceptable to include into the project?

**Comment by vitaut** [comment]
No, but you can get the target output name via CMake properties.

**Comment by risa2000** [comment]
The question was, if you would accept distinguishing the builds by name, not about this particular implementation.

**Comment by vitaut** [comment]
Not sure I follow. The names are already distinguished: https://github.com/fmtlib/fmt/blob/1dfa2591b3873a67bf5cd2fdb71d00b570096c51/CMakeLists.txt#L183

**Comment by risa2000** [comment]
Right! I guess I had to miscompile it somehow yesterday, when I added this "poor man's" distinction to the script. Please disregard this comment and excuse my mistake. All works as expected.
