### ISSUE TITLE
Best way to implement indentation with fmt lib?

### ISSUE THREAD

**Issue by risa2000** [fmtlib/fmt#1260]
This is rather a question than an issue. I am thinking about how to best implement a parametrized indentation, i.e. when I know how many spaces I need to print before the actual data. So far I came up with two options:
```c++
// ind has the number of spaces
std::string sf(ind, ' ');
fmt::print("{:s}{:s}", sf, mytext);
```
or
```c++
fmt::print("{:{}s}{:s}", "", ind, mytext);
```
The latter one seems more convoluted in format string, but somehow feels "cleaner" in passing only the `ind` and letting the `print` do the thing, while the former requires a string stub.

Is there any significant difference in performance or some other aspects?

I guess I would be happy, if there was an "empty type", which would honor width, fill, etc, but take no actual data, but it seems there is no such thing and an "empty type" simply defaults to string type.

**Comment by vitaut** [comment]
> Is there any significant difference in performance or some other aspects?

I don't think there is a significant difference, but if performance is critical you better benchmark. In the first case there is an extra string construction which can add overhead.

If you do this a lot, I'd recommend creating a separate function, something like:

```c++
template <typename... Args>
void print_indented(int indent, string_view format_str, Args&&... args) {
  fmt::print("{:{}}", "", indent);
  fmt::print(format_str, std::forward<Args>(args)...);
}
```

Then the usage will be simpler:

```c++
print_indented(ind, "{}", mytext);
```

**Comment by risa2000** [comment]
Great. Thanks for the function. I would not probably be able to coin this particular one myself right.

**Comment by risa2000** [comment]
Coming back to this topic in the perspective of C++20 standard for anyone interested. The aforementioned function:
```c++
template <typename... Args>
void print_indented(int indent, string_view format_str, Args&&... args) {
  fmt::print("{:{}}", "", indent);
  fmt::print(format_str, std::forward<Args>(args)...);
}
```
when compiled with the latest Visual Studio 2022 17.4.4 and with `-std:c++20` compiler switch emits an error:
>error C7595: 'fmt::v9::basic_format_string<char,const std::string &>::basic_format_string': call to immediate function is not a constant expression

I understand that the complain is about the compile-time parsing not working on `format_str` argument and while this could be solved by wrapping `format_str` into `fmt::runtime(format_str)` call, I believe it will turn even `constexpr` formats into runtime parseable.

So mimicking the fmt own implementation, I rewrote the function into:
```c++
template<typename... Args>
void print_indented(int indent, fmt::format_string<Args...> format_str, Args&&... args)
{
    fmt::print("{:{}}", "", indent);
    fmt::print(format_str, std::forward<Args>(args)...);
}
```
