### ISSUE TITLE
std::ostream& operator<< support does not compile with clang-cl, but does with msvc

### ISSUE THREAD

**Issue by risa2000** [fmtlib/fmt#1261]
While converting my app to `fmt` I noticed that one particular construct does not compile with `clang-cl`, but does with MSVC `cl` compiler.
I have following environment:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x64 (VS2019)

clang version 10.0.0 (https://github.com/llvm/llvm-project.git 29a3a503c0972da515209b953124f352e22bdc46)
Target: x86_64-pc-windows-msvc
Thread model: posix
```
and I am compiling it with basically same flags for both compilers:
```
clang-cl:
-m64 -fdiagnostics-absolute-paths  /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MTd   -std:c++17

msvc:
/DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MTd   -std:c++17
```
The problem is reproducible on this sample code:
```c++
#include <iostream>
#include <vector>

#include <fmt/format.h>
#include <fmt/ostream.h>

template<typename T>
//  Write std::vector to ostream
std::ostream& operator<<(std::ostream& os, const std::vector<T>& input)
{
    os << "{";
    bool more = false;
    for (auto const& i : input) {
        if (more)
            os << ", ";
        else
            more = true;
        os << i;
    }
    os << "}";
    return os;
}

int main(int argc, char* argv[])
{
    std::vector<uint32_t> nums = {19, 20};
    std::cout << "nums = " << nums << '\n';
    fmt::print("nums = {}\n", nums);
    return 0;
}
```
`clang-cl` spits out quite a lengthy log of errors: 
[fmt_clang_cl_error.txt](https://github.com/fmtlib/fmt/files/3465144/fmt_clang_cl_error.txt)
MSVC builds it and the code runs fine as well.

I am just curious, if someone could tell whether one or the other compiler is right, as I need this functionality and would like to do it "right", so it works on both compilers.

**Comment by vitaut** [comment]
I think that the problem is that your `operator<<` is not visible in `fmt/ostream.h` where the formatter is specialized. You can fix this by moving the operator to a header which is included before `fmt/ostream.h` or use `fmt/ranges.h` that provides formatting support for containers and ranges.

In general verloading of `operator<<` for `std::vector` is not a good idea. Normally you should be only providing such overloads for your own types.
