### ISSUE TITLE
Wrong library name in fmt.pc when building Debug.

### ISSUE THREAD

**Issue by ambitslix** [fmtlib/fmt#1264]
The wrong library name is configured in fmt.pc file when with CMAKE_BUILD_TYPE=Debug. 

As a result

$pkg-config --libs fmt

Returns -lfmt however the library name is actually "fmtd". The solution is to configure fmt.pc via variable. For example
...
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=@CMAKE_INSTALL_PREFIX@
libdir=@CMAKE_INSTALL_FULL_LIBDIR@
includedir=@CMAKE_INSTALL_FULL_INCLUDEDIR@
library=@FMT_LIBRARY_NAME@

Name: fmt
Description: A modern formatting library
Version: @FMT_VERSION@
Libs: -L${libdir} -l${library}
Cflags: -I${includedir}

Alternately change:

CMakeLists.txt:183

set_target_properties(fmt PROPERTIES
  VERSION ${FMT_VERSION} SOVERSION ${CPACK_PACKAGE_VERSION_MAJOR}
  **DEBUG_POSTFIX d**)

It seems unnecessary to have different names for library builds?

**Comment by vitaut** [comment]
`fmt.pc` currently expects that the release version of the library is installed. If you want to add support for debug libraries there, please submit a PR.

> It seems unnecessary to have different names for library builds?

It is convenient to distinguish between debug and release versions of the library and it allows placing them in one directory.

**Comment by ambitslix** [comment]
Debug libraries are easily generated separately by changing
CMAKE_INSTALL_PREFIX. The issue is in my view in generating wrong pc file.
It should derive from target file name.

**Comment by ambitslix** [comment]
I'm glad to add support for this are you ok with my solution in the ticket?

**Comment by vitaut** [comment]
> are you ok with my solution in the ticket?

I'm fine with the solution "to configure fmt.pc via variable". Thanks!
