### ISSUE TITLE
floating point default formatting

### ISSUE THREAD

**Issue by dixlorenz** [fmtlib/fmt#1270]
I just updated from a really old version of fmtlib (5 years) and some of my tests are failing; the current master formats
`fmt::format("{}", 100.0);` 
as "100.0", the old Version results in "100". I searched other issues and found a remark that "g" is the default for floats. Using "{:g}" would indeed result in "100". Also, according to the documentation for the "#" modifier: "Normally, a decimal-point character appears in the result of these conversions only if a digit follows it." 
As far as I can tell, "100" should be the correct output.

**Comment by vitaut** [comment]
I've corrected the description of the default format which now says:

> Similar to 'g', except that fixed-point notation, when used, has at least one digit past the decimal point. The default precision is as high as needed to represent the particular value.

This follows Python's convention. Please use the `g` format for the old behavior.

Thanks for reporting!
