### ISSUE TITLE
fmt 6.0.0 warning under mingw-w64-gcc 9.2.0

### ISSUE THREAD

**Issue by bbolli** [fmtlib/fmt#1274]
Hi!
When building fmt for mingw-w64, I get this warning:

    C:/Tools/git-sdk-64/usr/src/Pux-MINGW-packages/mingw-w64-fmt/src/fmt-6.0.0/src/format.cc:11:35: warning: type attributes ignored after type is already defined [-Wattributes]
       11 | template struct FMT_API internal::basic_data<void>;
          |                                   ^~~~~~~~~~~~~~~~

I'd be happy to provide a patch, but I'm not sure if `FMT_API` should be deleted here or if it should be added in the `basic_data<void>` definition in `include/fmt/format.h` (line 668).

**Comment by bbolli** [comment]
(Sorry, this is a duplicate of #1204)

**Comment by vitaut** [comment]
Looks like a GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50044. `FMT_API` shouldn't be deleted but a possible workaround is to define `FMT_EXTERN_TEMPLATE_API` to `FMT_API` when compiling on MinGW. In any case closing as a duplicate.
