### ISSUE TITLE
fmt 6.0.0 "error C2039: 'back_insert_range': is not a member of 'fmt'" compile error

### ISSUE THREAD

**Issue by lexxmark** [fmtlib/fmt#1281]
Tried to implement "Custom Formatting of Built-in Types" from [documentation](https://fmt.dev/latest/api.html)
Compile error in the 1st line:
`
using arg_formatter =
  fmt::arg_formatter<fmt::back_insert_range<fmt::internal::buffer>>;
`

**Comment by jeanga** [comment]
Yeah. It seems the samples from documentation were not updated from 5.X... 
We really need some guidance to help upgrade our code to 6.0.

**Comment by jeanga** [comment]
I found test/std-format-test.cc to be helpful but the docs definitely need some update :*)
