### ISSUE TITLE
Formatting floating point no longer uses locale decimal

### ISSUE THREAD

**Issue by dconnet** [fmtlib/fmt#1289]
I have a unit test that verifies locale differences. When upgrading libfmt to v6, that now fails. I don't see anything in the docs that allow me to use locale settings. This applies to the 'f' and 'g'. (specifically, I'm using "{:.{}f}" and "{:g}")

When I'm in a french locale, I'm expecting 3.14 to be "3,14"

**Comment by vitaut** [comment]
Version 6.0 switched to locale-independent formatting by default: https://github.com/fmtlib/fmt/releases/tag/6.0.0. For locale-specific formatting, please use the `n` specifier.

**Comment by dconnet** [comment]
The documentation specifically says "Number. This is the same as 'd', except that it uses the current locale setting to insert the appropriate number separator characters." Attempting to use 'n' for the formats I originally mentioned does not work.

3.14 produces "3.1" when used with ("{:.{}d}", 2, 3.14)

**Comment by vitaut** [comment]
As commented on the other issue, the documentation needs updating because it currently only documents the integer `'n'`.
