### ISSUE TITLE
Unable to print floating point in current locale

### ISSUE THREAD

**Issue by dconnet** [fmtlib/fmt#1291]
Since fmt has switched to locale-independent, it's not possible to print floating point in a specific locale with specific formatting.
```
	double p = 3.1416;
	fmt::print("%{:.2f}\n", p);
	fmt::print("%{:.2n}\n", p);
```
The first line works (locale-independent). The 2nd prints 3.1 

Edit: I just noticed it appears to be an off-by-one issue.
```
	fmt::print("%{:.3n}\n", p);
```
will print 3.14

**Comment by vitaut** [comment]
The reason the second line prints `3.1` is because precision in `n` (and `g`) specifies the maximum number of digits to print:

> For a given precision p >= 1, this rounds the number to p significant digits and then formats the result in either fixed-point format or in scientific notation, depending on its magnitude.

Looks like floating-point 'n' is missing from the docs though - I need to fix that.

**Comment by dconnet** [comment]
Is there any way with 'n' to print with a specified number of places always? For instance, I need to always display 2 decimals (no matter how large the number is) - even for a number like 2.1 (which should display as 2.10).

**Comment by vitaut** [comment]
You can request to output trailing zeros with `#`:

```c++
auto s = fmt::format("{:#.3n}", 2.1); // s == "2.10"
```

**Comment by vitaut** [comment]
The 'n' specifier is documented now: https://fmt.dev/dev/syntax.html
