### ISSUE TITLE
error: attribute does not apply to any entity

### ISSUE THREAD

**Issue by ugenehan** [fmtlib/fmt#1297]
OS:win10
IDE:VS2017

when using fmtlib in my project,error occured like as:
E1866 error: attribute does not apply to any entity
core.h line:486

**Comment by p1m3nt** [comment]
same problems here, how do you solve it? thanks.

**Comment by aslyansky-m** [comment]
Fixed it by commenting **FMT_DEPRECATED** in core.h and format.h (lines where VS  pointed to an error).

**Comment by trojanfoe** [comment]
Simply `#define FMT_DEPRECATED` before `#include <fmt/format.h>` in the code that uses fmtlib; no need to mess with the fmtlib source.

**Comment by litterbug23** [comment]
E1866 error    FMT_STRING
