### ISSUE TITLE
grisu_prettify emits -Wstrict-overflow with GCC 9.1.0

### ISSUE THREAD

**Issue by hswhite33** [fmtlib/fmt#1298]
Compiling a project with {fmt} 6.0.0 using -Wstrict-overflow=3 or higher and -O2 or higher emits a warning from the `fmt::v6::internal::grisu_prettify` function.

Sample code:
```
#define FMT_HEADER_ONLY
#include "fmt/format.h"

int main() {
    fmt::format("Hello, {}", "world");
}
```

Compile with
```
g++ main.cpp -std=c++17 -O2 -Wstrict-overflow=3
```

Outputs:
```
main.cpp: In function ‘It fmt::v6::internal::grisu_prettify(const char*, int, int, It, fmt::v6::internal::gen_digits_params, Char) [with Char = char; It = fmt::v6::internal::counting_iterator<char>]’:
main.cpp:7:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
    7 | }
      | ^
```

I believe I've narrowed it down to this line: https://github.com/fmtlib/fmt/blob/466128de00f4cfbcf45f076edb1db0f451a3fa9b/include/fmt/format.h#L1031

Not sure if this is an issue with the {fmt} library or with GCC itself

**Comment by vitaut** [comment]
`digits` is an array of `size` elements and `size` is greater than 0, so there is no issue here. I'm not sure how to communicate it to gcc to silence this false positive without adding redundant checks.

**Comment by tg-m** [comment]
When building with `GCC 11.2` (cross compilation for ARM actually) the warning disappeared somewhere between versions `8.0.1` and `8.1.1`.  So it somewhat resolved itself (at least when I encountered it today :)).

I built with:
```
gcc -std=c++17 -O3 -Wstrict-overflow=5 + circa 200 other -Wflags
```
