### ISSUE TITLE
Compatibility with C++20 std::format

### ISSUE THREAD

**Issue by whannes** [fmtlib/fmt#1299]
Hi Victor

Congratulations, I just read it now that your proposal finally made it into C++20. Thank you so much for maintaining this wonderful library!

What is not fully clear to me: fmtlib provides _more_ than what will be integrated into the standard, correct? So in case I wanted guarantee drop-in compatibility with C++20, is there a "compatibility mode" that can be enabled to enforce this? 

Background is that I am working in a project where the drop-in compatibility would be a requirement in order to allow me to integrate fmtlib into the project.

BR, whannes

**Comment by vitaut** [comment]
> fmtlib provides more than what will be integrated into the standard, correct?

Yes.

> is there a "compatibility mode" that can be enabled to enforce this?

There is no such mode but the C++20 formatting facility is mostly compatible with a subset of {fmt}, particularly `fmt::(v)format`, `fmt::(v)format_to`, `fmt::formatted_size` and the extension API.

**Comment by whannes** [comment]
Thanks!

**Comment by chiumichael** [comment]
> fmtlib provides _more_ than what will be integrated into the standard, correct?
I hope that when that does come out the readme gets updated with what more fmtlib does

**Comment by tburt** [comment]
Hi Victor, thanks for all your work! Do you know if the ostream compaitibility (as in fmt/ostream.h) will be available in the c++20 implementation? Best, T

**Comment by vitaut** [comment]
> Do you know if the ostream compaitibility (as in fmt/ostream.h) will be available in the c++20 implementation?

There will be no ostream compatibility interface in C++20.

**Comment by tburt** [comment]
> There will be no ostream compatibility interface in C++20.

Okay, thanks Victor
