### ISSUE TITLE
Using with other string types (EASTL)

### ISSUE THREAD

**Issue by amerkoleci** [fmtlib/fmt#1300]
Hi,

Probably not an issue, would be possible to use fmt library with custom std::string implementation, for example (https://github.com/electronicarts/EASTL)?

Thanks

**Comment by vitaut** [comment]
Yes. You'll need to provide an overload of `to_string_view` for the custom string type as explained in https://fmt.dev/latest/api.html#_CPPv2N3fmt14to_string_viewEPK4Char.

**Comment by amerkoleci** [comment]
I saw that, but what about not depending on stl containers? 
I mean completely remove std::string usage etc.

**Comment by vitaut** [comment]
There are no plans to remove `std::string` support but you don't have to use it. The core library doesn't require any other standard containers.
