### ISSUE TITLE
fmt 5.3.0 sprintf("%s", size_t{}) throws invalid type specifier

### ISSUE THREAD

**Issue by C4rsten** [fmtlib/fmt#1302]
fmt 4.0.0 introduced
> %s format specifier can be used with any argument type.
    fmt::printf("%s", 42);

In fmt 5.3.0 it does not work anymore for `size_t` arguments:
`sprintf("%s", size_t{});` 
throws "invalid type specifier".

**Comment by vitaut** [comment]
This was removed in version 5 IIRC. Please use `%d` instead which also works with any integer type but is somewhat less confusing.
