### ISSUE TITLE
fmt::compile and format_to - not work as expected with fmt::memory_buffer

### ISSUE THREAD

**Issue by gabime** [fmtlib/fmt#1303]
It doesn't update its size, nor grow it dynamically if needed (as opposed to the regular format_to(..))

Reproduce (prints empty string):
```c++
    auto cf = fmt::compile<int>("Hello {}");
    fmt::memory_buffer buf;
    fmt::format_to(buf.begin(), cf, 123);
    std::cout << fmt::to_string(buf) << std::endl;
```

**Comment by vitaut** [comment]
`buf.begin()` is an iterator pointing to the beginning of an empty container, so writing to it won't work. If you want to append then pass a `back_insert_iterator` instead:

```c++
    auto cf = fmt::compile<int>("Hello {}");
    fmt::memory_buffer buf;
    fmt::format_to(std::back_inserter(buf), cf, 123);
    std::cout << fmt::to_string(buf) << std::endl;
```

**Comment by gabime** [comment]
Great. Thanks for the fast response!
