### ISSUE TITLE
Fail to cmake/compile in raspberry pi

### ISSUE THREAD

**Issue by kenjichanhkg** [fmtlib/fmt#1304]
I’m trying to compile fmt 6.0.0 in raspberry pi
But it failed to just cmake

![E1DCFCE8-519C-46D6-919C-8EADC2FD7746](https://user-images.githubusercontent.com/7701160/64483624-43435b00-d238-11e9-93c5-1b2e651c7564.png)

**Comment by kenjichanhkg** [comment]
If I use the system default GCC 4.6.3. I could cmake but got a lot of compile errors

**Comment by vitaut** [comment]
The CMake error is unrelated to {fmt} - looks like gcc is misconfigured on your system.

GCC 4.6.3 is too old and not supported by {fmt} 6.0 but it is supported by version 5.
