### ISSUE TITLE
fmt::v6::internal::fallback_format multiply defined Visual Studio 2017

### ISSUE THREAD

**Issue by bowie7070** [fmtlib/fmt#1306]
First off, thanks for the great library. It is such an improvement over the type unsafe sprintf/print.

I have a project that was compiling and linking under both clang/linux and Visual Studio/win32. I am now getting errors from Visual Studio while linking:

```
1>test-cases.obj : error LNK2005: "void __cdecl fmt::v6::internal::fallback_format(class fmt::v6::internal::fp const &,int)" (?fallback_format@internal@v6@fmt@@YAXABVfp@123@H@Z) already defined in test-cases-2fx.obj
1>C:\Users\owe043\Documents\svn-RiskLab\Containers\trunk\Release\catch-gen-MC.exe : fatal error LNK1169: one or more multiply defined symbols found
```

I have tried to bisect the problem and I have that commit 6649b8e0ca57d65b193b932384c685d70c078b1c is good (I'm consuming via svn so this is what they look like to me):

> 5594 | victor.zverovich | 2019-09-08 07:23:19 +1000 (Sun, 08 Sep 2019) | 2 lines
> 
> value -> bigit

The next commit ac71d853be1ed4f0abe673974281cb10d85f7fc7 doesn't compile for me:

> r5595 | victor.zverovich | 2019-09-08 10:28:59 +1000 (Sun, 08 Sep 2019) | 2 lines
> 
> Refactor normalize and clean up

The next commit 0887887e2396e52ab9798cc84404712653c6aa71 is the first bad commit:

> r5596 | victor.zverovich | 2019-09-08 11:10:36 +1000 (Sun, 08 Sep 2019) | 2 lines
> 
> Implement left shift

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/c6d1a94a9f949727d75e8e5f7596426eaf7e5956. Thanks for reporting!

**Comment by bowie7070** [comment]
Can confirm that resolves the problem for me.

Happy to help. Thanks for fixing it so quickly.
