### ISSUE TITLE
Ambiguous functions with ostream.h and const char * conversion

### ISSUE THREAD

**Issue by EmilyMansfield** [fmtlib/fmt#1309]
I'm working with some legacy code that defines a type with an implicit conversion to `const char *`, but I also have types with an `operator<<`. Including both `ostream.h` and `format.h` causes a compile error on GCC and Clang due to an ambiguous call to `map`, for example

```cpp
#include <fmt/format.h>
#include <fmt/ostream.h>

struct MyBadType {
    operator const char *() const { return "whoops"; }
};

int main() {
    std::string s = fmt::format("{}", MyBadType{});
}
```
Godbolt: https://godbolt.org/z/XkXue4

fails to compile.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/f29901097faaa36ed3df42f5a5f622447b8c2086. Thanks for reporting!
