### ISSUE TITLE
FileTest.FdopenError fails with musl libc

### ISSUE THREAD

**Issue by orivej** [fmtlib/fmt#1313]
`FileTest.FdopenError` [expects](https://github.com/fmtlib/fmt/blob/6.0.0/test/posix-test.cc#L373) that `fdopen(-1, "r")` returns `EBADF`, but this call is not an error in musl [by design](https://musl.openwall.narkive.com/TmVQtnII/musl-bugs-found-through-gnulib#post5): its [fdopen](https://git.musl-libc.org/cgit/musl/tree/src/stdio/__fdopen.c?id=v1.1.23) never sets errno to `EBADF`. (In this case musl returns a `FILE*` without error. An attempt to use this file will fail with `EBADF`.)

**Comment by vitaut** [comment]
This test is redundant, so I removed it in https://github.com/fmtlib/fmt/commit/20fdb88a1cedb1da3048dfd14637eb108d1f6808. Thanks for reporting!
