### ISSUE TITLE
fmt 6.0.0 Warning -Wshadow

### ISSUE THREAD

**Issue by aggsol** [fmtlib/fmt#1314]
Compiler
```sh
$ gcc --version
gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
```

Warning
```
fmt-src/include/fmt/format.h: In function ‘constexpr void fmt::v6::internal::parse_format_string(fmt::v6::basic_string_view<Char>, Handler&&)’:
fmt-src/include/fmt/format.h:2442:10: warning: declaration of ‘struct fmt::v6::internal::parse_format_string(fmt::v6::basic_string_view<Char>, Handler&&)::writer’ shadows a global declaration [-Wshadow]
   struct writer {
          ^~~~~~
fmt-src/include/fmt/format.h:1703:48: note: shadowed declaration is here
 using writer = basic_writer<buffer_range<char>>;
                                                ^
```

You could consider adding `SYSTEM` with the `target_include_directories` That way warnings are isolated away from calling projects. See [here for details](https://cmake.org/cmake/help/latest/command/target_include_directories.html)

**Comment by vitaut** [comment]
Could you provide an example that triggers the warning? I couldn't repro it in https://godbolt.org/z/C_3CfD.

**Comment by aggsol** [comment]
@vitaut I am still on it, I have trouble re-crating the circumstances from my project.

**Comment by vitaut** [comment]
This was fixed in https://github.com/fmtlib/fmt/commit/f5556225a4df3d8567334135e50706cec51a826c.
