### ISSUE TITLE
no matching function vformat

### ISSUE THREAD

**Issue by mircodezorzi** [fmtlib/fmt#1318]
After upgrading to fmt 6.0.0-1 and re-compiling my source code I've started to get this error:

```
error: no matching function for call to ‘vformat(std::string&, fmt::v6::format_arg_store<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >)’
   76 |   std::string url = fmt::vformat(format, fmt::make_format_args(args...));      
```

I've checked the release notes for the library but couldn't see any mentions of a change to neither `vformat` or `make_format_args`.

**Comment by vitaut** [comment]
I don't see anything wrong with the code. Could you post a reproducible example?

**Comment by mircodezorzi** [comment]
Here's a minimal working example of the source code:

```c++
#include <fmt/format.h>
#include <string>
#include <iostream>

template <typename... Args>
std::string foo(std::string format, const Args&... args)
{
	return fmt::vformat(format, fmt::make_format_args(args...));
}

int main() {
	std::cout << foo("{}", 42);
}
```

To compile:
```
g++ -o main foo.cpp -lfmt 
```

**Comment by vitaut** [comment]
Ah, the problem is that `vformat` takes `string_view<Char>` and if you pass `std::string` it won't deduce template argument. Moreover there will be unnecessary string copy. To fix this change `std::string` to `fmt::string_view`:

```c++
template <typename... Args>
std::string foo(fmt::string_view format, const Args&... args) {
	return fmt::vformat(format, fmt::make_format_args(args...));
}
```
or convert `format` from `std::string` to `fmt::string_view` by calling `fmt::to_string_view`.
