### ISSUE TITLE
set_dynamic_spec compares signed integers against unsigned

### ISSUE THREAD

**Issue by rwy0717** [fmtlib/fmt#1319]
the problematic comparison is at [include/fmt/format.h:2091](https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L2091), resulting in this message:
```
../external/fmt/include/fmt/format.h:2091:17: warning: comparison of integer expressions of different signedness: ‘long long unsigned int’ and ‘int’ [-Wsign-compare]
 2091 |   if (big_value > max_value<int>()) eh.on_error("number is too big");
```

The complete error message is quite large due to template expansion.

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/758446c80d64cd03fe04bb12b028c992ed7bb063. Thanks for reporting!

**Comment by rwy0717** [comment]
Thank you for fixing!
