### ISSUE TITLE
Avoid inclusion dependency fmt/format.h when specialize Formatting User-defined Types

### ISSUE THREAD

**Issue by slonm** [fmtlib/fmt#1321]
Let i want add adopt some JSON libray for use in my project against FMT. I am preparing header-adapter json.h to my project. It will has compatibility layer definition for tier different types casts and conversions from or to json. Will be good avoid include whole fmt library to this header because not all modules which use JSON will use FMT.

This time it looks like (according to documentation):
```
#include <fmt/format.h>
namespace fmt {
		template <>
		struct formatter<nlohmann::json> {

			template <typename ParseContext>
			constexpr auto parse(ParseContext &ctx) {
				return ctx.begin();
			}

			template <typename FormatContext>
			auto format(const nlohmann::json &p, FormatContext &ctx) {
				return format_to(ctx.begin(), "{}", p.get<std::string>());
			}
		};
}
```

This time can do it with formatter forward declaration:
```
namespace fmt {
	namespace v5 {
		// A formatter for objects of type T.
		template <typename T, typename Char, typename Enable>
		struct formatter;
		template <>
		struct formatter<nlohmann::json,char,void> {

			template <typename ParseContext>
			constexpr auto parse(ParseContext &ctx) {
				return ctx.begin();
			}

			template <typename FormatContext>
			auto format(const nlohmann::json &p, FormatContext &ctx) {
				return format_to(ctx.begin(), "{}", p.get<std::string>());
			}
		};
	}
	using namespace v5;
}
```
Obviously usage of internal namespace v5 is not good and not forward compatible.

Also looks in many cases is enough to overload converson from type to string or string_view (this json particular case also). Then will be good make additional simplified formatter overload for something like this:
```
namespace fmt {
    template<typename CharT>
    auto to_string(const nlohmann::json& p) {
        return p.get<std::basic_string<CharT>>();
    }
}
```
This to_string could return std::basic_string or std::basic_string_view depend of implementation.

**Comment by vitaut** [comment]
If you are using C++14 or later you can just do this:

```c++
template <>
struct fmt::formatter<nlohmann::json> : fmt::formatter<std::string> {
  auto format(const nlohmann::json &p, format_context& ctx) {
    return format_to(ctx.out(), "{}", p.get<std::string>());
  }
};
```

https://godbolt.org/z/pq9ojw

without referring `v5` namespace (it's not an internal namespace BTW) or defining `parse`.

Conversion to `std::string` would be unsafe and is not supported intentionally.

**Comment by slonm** [comment]
The main thing of this issue it avoid include fmt/format.h for specialize formatter. Your suggestion is not conform it. My example with forward declarations from v5 namespace is conform it

**Comment by vitaut** [comment]
Then you have to define a trivial `parse` function. We could a simple formatter that provides such function although it will be of limited use. You could also provide `to_string_view` function if your type is string-like if which case `formatter` specialization is not needed.

**Comment by slonm** [comment]
>Then you have to define a trivial `parse` function.

`parse` function is less inconvenience. I can't specialize formatter without forward declaration of formatter and it placed in `v5` namespace. Moreover `v5` namespace defined as `namespace` or `inline namespace` depend of compiler (basically depend of macro in core.h).

>You could also provide to_string_view function if your type is string-like if which case formatter specialization is not needed.

Hmm. Interesting. Is it possible add reference to that ability to documentation chapter [Formatting User-defined Types](https://fmt.dev/latest/api.html#formatting-user-defined-types)?

**Comment by vitaut** [comment]
`to_string_view` addresses a very narrow use case (only string-like types with contiguous storage) and easy to misuse which is why it's not advertised.
