### ISSUE TITLE
`fmt::join` does not support tuples

### ISSUE THREAD

**Issue by jeremyong** [fmtlib/fmt#1322]
Currently, `fmt::join` appears to only function on containers/ranges that support `begin` and `end`. It would be extremely convenient if `fmt::join` used the `is_tuple_like` trait to format each element with the separator as well.

**Comment by vitaut** [comment]
Sounds reasonable. Will be happy to accept a PR =).

**Comment by jeremyong** [comment]
@vitaut I'm looking at this now. Can I use `if constexpr` or are you trying to maintain backwards compatibility? I'd like to avoid using SFINAE unless absolutely needed

**Comment by vitaut** [comment]
SFINAE is generally preferred for portability reasons but it's OK to use `if constexpr` for new non-essential features.

**Comment by jeremyong** [comment]
I see that `is_tuple_like` is defined in `ranges.h`, but `join` is defined in `format.h`. The options are to put the specialization for tuples of `join` inside `ranges.h` or to move `is_tuple_like` to `format.h`. Thoughts?

**Comment by vitaut** [comment]
I suggest putting it in `ranges.h` together with `is_tuple_like`. Eventually we should move the other overload of `join` there too. It's in `format.h` mostly for historical reasons.

**Comment by jeremyong** [comment]
OK I'll work on this tonight after work, thanks
