### ISSUE TITLE
`fmt::format` regresion using 6.0.0 when using bitfields

### ISSUE THREAD

**Issue by Lilolbet** [fmtlib/fmt#1323]
The following minimal piece of code used to work with previous versions of fmt, but 6.0.0 appears to regress in behaviour. Probably more functions are affected other than `fmt::format`.

```
#include <fmt/format.h>
#include <iostream>
       
struct foo{
int bar:4;
int bar2:4;
  foo(){
    bar = 4;
    bar2 = 5;
  }
};


int main(){
   foo a;
   // error: cannot bind bitfield ‘a.foo::bar’ to int&
   std::cout << fmt::format("Bitfield value is {}", a.bar); 
}
```

A manual cast to int fixes the problem, but I think this should not be needed. Therefore I assume this is a regression? 

E.g. this is what I currently use for a quick workaround:
`std::cout << fmt::format("Bitfield value is {}", (int)a.bar);`

**Comment by vitaut** [comment]
That's an unfortunate consequence of using perfect forwarding: https://github.com/fmtlib/fmt/issues/1284#issuecomment-525778606. Manual cast is the recommended workaround for now.

**Comment by Lilolbet** [comment]
Ah, sorry! I was searching using 'bitfield' and not 'bit-field'. Did not see the issue already opened. Manual cast it is then! :)
