### ISSUE TITLE
feature request, something like f-string in python

### ISSUE THREAD

**Issue by yusisc** [fmtlib/fmt#1327]
As the document shows, `fmt` support syntax as
```
string str0 = "right";
string str1 = "happy";
std::string s = fmt::format("I'd rather be {1} than {0}.", str0, str1);
```
which is python like syntax.

---
Could there be syntax like
```
string str0 = "right";
string str1 = "happy";
std::string s = fmt::format(f"I'd rather be {str1} than {str0}.");
```
which is like python f-string.

Thank you.

**Comment by vitaut** [comment]
It is not possible in C++ right now but there is a proposal that may allow it in the future: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1819r0.html.
