### ISSUE TITLE
Proposal: styled objects

### ISSUE THREAD

**Issue by jeremyong** [fmtlib/fmt#1333]
See the code snippet and possible implementation sketch:

```c++
fmt::print("The sky is {}", fmt::fg(fmt::colors::royal_blue) * "blue");
// prints the string with the word "blue" in blue
```

This is immediately possible with the following addition:

```c++
namespace fmt {
    template <typename T>
    struct styled_object
    {
        text_style ts;
        const T& value;
    };

    template <typename T>
    [[nodiscard]] constexpr auto operator*(text_style lhs, const T& rhs) noexcept
    {
        return styled_object<T>{lhs, rhs};
    }

    template <typename T>
    struct formatter<styled_object<T>>
    {
        template <typename PC>
        constexpr auto parse(PC& ctx)
        {
            return ctx.begin();
        }

        template <typename FC>
        constexpr auto format(const styled_object<T>& so, FC& ctx)
        {
            auto styled_text = ::fmt::vformat(so.ts, "{}", basic_format_args<FC>{format_arg_store<FC, T>{so.value}});
            return format_to(ctx.out(), "{}", styled_text);
        }
    };
} // namespace fmt
```

The above code works but with limitations. Note first the wonky usage of `vformat` because no overload of `format_to` currently takes a text style. Also, this code will break if a custom format string is used at the originating source. For example, if we did instead:

```c++
fmt::print("The number 4 in binary is {:b}", fmt::bg(fmt::colors::red) * 4);
```

but I believe this is an easy thing to remedy (?).

Thoughts?

**Comment by vitaut** [comment]
That's an interesting idea. However, in addition to the limitations that you've mentioned I am concerned that it adds complexity for a relatively narrow use case and uses operator overloading in an unorthodox way. You can already achieve the same behavior with nested `format`:

```c++
print("The sky is {}", format(fg(fmt::color::royal_blue), "blue"));
```

**Comment by jeremyong** [comment]
Thanks, I'll probably leave this as-is in my own code. I care more about the overhead of formatting an intermediate string.

**Comment by jeremyong** [comment]
Ergonomically, making a string with differently styled fragments will require N such intermediates (one per style including the default one)
