### ISSUE TITLE
format.cc needs -DFMT_USE_GRISU in order to use grisu formatting

### ISSUE THREAD

**Issue by orivej** [fmtlib/fmt#1335]
Sorry if this is a known and expected issue, but I had an impression that even if `format.cc` is compiled without `-DFMT_USE_GRISU`, grisu formatting can be used by defining `FMT_USE_GRISU` before including fmt headers. (I thought so because this is an example in 6.0.0 release notes, and because `grisu-test` specifically defines this macro.) However, since `format.cc` instantiates some functions such as `vformat_to` that ultimately invoke `arg_formatter_base::operator()<double>` which calls either `write_double<USE_GRISU = false>` or `write_double<USE_GRISU = true>` depending on `-DFMT_USE_GRISU`, it turns out that if the linker selects `arg_formatter_base::operator()<double>` from `format.cc` compiled without `-DFMT_USE_GRISU`, grisu formatting will not be used. Conversely, if `format.cc` is compiled with grisu, but the program includes fmt headers without grisu, grisu formatting may still be used.

You may try reproducing this using the following program, but this should be compiler and linker-dependent (I'm using Clang 7 with LLD on Linux):
```
#define FMT_USE_GRISU 1
#include <fmt/format.h>
int main() { fmt::print("{}\n", double(0.1f)); }
```
(The expected output is `0.10000000149011612`, but actually it prints `0.1`. In my case it was important that `fmt::format` is never called, even in `void unused() { fmt::format(""); }`, or grisu formatting becomes enabled. You may find my [floatbits](https://github.com/orivej/unix/blob/master/floatbits/main.go) useful for debugging precision issues of floating point numbers.)

I guess that the simplest fix is to unconditionally enable grisu formatting and remove all `FMT_USE_GRISU`.

**Comment by vitaut** [comment]
The example is somewhat unclear but you do need to compile both your code and the {fmt} library with `FMT_USE_GRISU` set. Grisu implementation is stable and will be enabled by default in the next minor release.
