### ISSUE TITLE
Possible to validate fmt string at compile time in wrapper function?

### ISSUE THREAD

**Issue by HastyMarly** [fmtlib/fmt#1340]
I have a wrapper function like:

    template <typename S, typename... Args>
    std::string myformatter(const S& fmt_string, Args... args)
    {
        return fmt::format(FMT_STRING(fmt_string), std::forward<Args>(args)...);
    }

But the macro errors out on gcc9 w/ std=c++17 presumably because some type info/size is lost. Are there any patterns that might allow verification to occur here in the wrapper so FMT_STRING or fmt() don't need to be specified at each callsite?

**Comment by vitaut** [comment]
You don't need to do anything. If the format string is a compile-time string, it will be validated automatically when you call `fmt::format` from your function. For example

```c++
#include <fmt/format.h>

template <typename S, typename... Args>
std::string myformatter(const S& fmt_string, Args... args) {
  return fmt::format(fmt_string, std::forward<Args>(args)...);
}

int main() {
  myformatter(FMT_STRING("{:d}"), "foo");
}
```

will give an expected error (https://godbolt.org/z/gvwzmv):

```
...
include/fmt/format.h:1212:13: note: non-constexpr function 'on_error' cannot be used in a constant expression
    handler.on_error("invalid type specifier");
            ^
...
```

**Comment by HastyMarly** [comment]
Thanks for your reply however my question was specifically around how to move the FMT_STRING call within the wrapper function. Is this possible?

**Comment by vitaut** [comment]
`FMT_STRING` takes a string literal as an argument, e.g. FMT_STRING("foo") so you cannot use it as in your example. But you also don't need it for checking already created compile-time format string.

**Comment by HastyMarly** [comment]
OK thanks, I was hoping to basically enable compile-time checking everywhere to my log() function without each log statement needing to write FMT_STRING... I suppose I will need to wrap my log function in a LOG() macro that automatically wraps the literal in FMT_STRING.
