### ISSUE TITLE
MemoryBufferTest.MoveCtor provokes undefined sanitizer

### ISSUE THREAD

**Issue by orivej** [fmtlib/fmt#1344]
When [`MoveCtor` performs `check_move_buffer`](https://github.com/fmtlib/fmt/blob/b6011453/test/format-test.cc#L283), the buffer allocator becomes null [as expected](https://github.com/fmtlib/fmt/blob/b6011453/test/format-test.cc#L270), but then `MoveCtor` attempts to use it to [allocate a dynamic buffer](https://github.com/fmtlib/fmt/blob/b6011453/test/format-test.cc#L287). UBSAN reports this as a reference binding to a null pointer at [TestAllocator.allocate](https://github.com/fmtlib/fmt/blob/b6011453/test/mock-allocator.h#L55). I think that this succeeds nevertheless because a typical `std::allocator<char>::allocate` does not use `this`, so it does not crash when `this` is null.

**Comment by vitaut** [comment]
Good catch. The test should really create a new buffer before doing the dynamic allocation part.
