### ISSUE TITLE
Is fmt::print thread-safe?

### ISSUE THREAD

**Issue by tankiJong** [fmtlib/fmt#1348]
Hi, 

I was testing the code in multiple threads and I observed different behavior for `fmt::print`:
With code
```
      fmt::print( fmt::fg( fmt::color::blue ), "worker init\n" );
```
I got:
![image](https://user-images.githubusercontent.com/8042676/66368411-2d73a380-e966-11e9-9736-96e92a0183f4.png)

With code
```
      fmt::print( fmt::fg( fmt::color::blue ), "worker {} init\n", mId );
```
I got:
![image](https://user-images.githubusercontent.com/8042676/66368472-5f850580-e966-11e9-9c40-c033f3d598c6.png)

Notice that items were missing color. And the only difference in code is just two lines above.

So I am wondering is that because the `print` is not thread-safe? Or actually some other issues going on.

Thanks for the help :)

**Comment by vitaut** [comment]
It is thread-safe in the sense that there are no data races but the output is not atomic meaning that text style changes and the text from different threads may interleave. It can be made atomic by placing both escape sequences that control text style and the formatted text into memory_buffer and then writing them to file in one go. PRs are welcome =).
