### ISSUE TITLE
VS2017 multiple defined symbols

### ISSUE THREAD

**Issue by bowie7070** [fmtlib/fmt#1362]
I have updated to:

commit 3a15ea3ea554858cd80c4709819e582791fbf232

and now I get errors of the form:

9>gen-MC-shifts.obj : error LNK2005: "char * __cdecl fmt::v6::internal::sprintf_format<float>(float,class fmt::v6::internal::buffer<char> &,struct fmt::v6::internal::sprintf_specs)" (??$sprintf_format@M@internal@v6@fmt@@YAPADMAAV?$buffer@D@012@Usprintf_specs@012@@Z) already defined in gen-MC-known.obj

I am using Visual Studio 2017. 

I believe that b87ac4d84063f74c89120a751d6d5b16fff54036 is the first bad commit.

Please let me know if you need additional information.

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/0e94b931a200e8cdf9c5b4df057295267dfc6362. Thanks for reporting.

**Comment by bowie7070** [comment]
Thanks for the quick fix. I'll be able to confirm in a couple of days but
I'm sure it's right now.
