### ISSUE TITLE
Visual Studio solution / project generation incorrect

### ISSUE THREAD

**Issue by draeger-charles-wilson** [fmtlib/fmt#1365]
The CMake Windows Visual Studio solution / project generation is incorrectly creating the debug settings. Both debug and release projects are created with C++ runtime library set to Multi-threaded DLL (/MD). The debug versions should be set to Multi-threaded Debug DLL (/MDd). This causes a rabbit hole worthy linker error when you attempt to use the debug library with a project with correct settings.

'''
1>test-main.lib(test-main.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in assert-test.obj
1>test-main.lib(test-main.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in assert-test.obj
1>MSVCRTD.lib(initializers.obj) : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
1>C:\Users\wilsonch\Downloads\fmt-6.0.0\build\bin\Debug\assert-test.exe : fatal error LNK1319: 2 mismatches detected
1>Done building project "assert-test.vcxproj" -- FAILED.
'''

**Comment by vitaut** [comment]
AFAICS fmt doesn't override the runtime library settings so it should be the default chosen by CMake. I don't have a Windows machine at hand to experiment with but would be happy to accept a PR to workaround this.

**Comment by vitaut** [comment]
Closing per comment above but PRs are welcome if there is some way to workaround this in a CMake config.
