### ISSUE TITLE
Locale based float formatting with precision

### ISSUE THREAD

**Issue by dirkvdb** [fmtlib/fmt#1372]
When specifying a precision with locale based formatting, the result switches to scientific format
```
#define FMT_HEADER_ONLY 1
#include <fmt/format.h>
#include <fmt/locale.h>
int main() {
fmt::print(fmt::format(std::locale::classic(), "{:n}\n", 7975.3569));
fmt::print(fmt::format(std::locale::classic(), "{:.2n}\n", 7975.3569));
}
```
outputs
```
7975.36
8e+03
```
fmt version 6.0.0
Is this expected?
[Godbolt](https://godbolt.org/z/vxpmel)

**Comment by vitaut** [comment]
This is expected because `n` is the same as `g`, except that it uses the current locale setting to insert the appropriate number separator characters. And `g` can switch between fixed and exponent notation. You'll get the same behavior in `printf`:

```c++
printf("%g\n", 7975.3569);   // 7975.36
printf("%.2g\n", 7975.3569); // 8e+03
```

**Comment by dirkvdb** [comment]
So it is not possible to get fixed notation using a specified locale?

**Comment by vitaut** [comment]
No. Right now {fmt} follows Python's `str.format` in allowing only the `n` specifier to use the locale. However, I'm considering adding a modifier that can be used together with `f`, `g` and `e` for locale-specific formatting.

**Comment by dirkvdb** [comment]
I would love to see it supported. I had to revert to iostreams now.
Do you know if the c++20 std::format has locale support?

**Comment by vitaut** [comment]
> Do you know if the c++20 std::format has locale support?

Right now it has the same locale support as {fmt} and there is a proposal to add a modifier that I mentioned earlier.
