### ISSUE TITLE
Minimal VIsual Studio version for fmt 6.0.0

### ISSUE THREAD

**Issue by uilianries** [fmtlib/fmt#1373]
Hi!

I'm building spdlog 1.4.2 + fmt 6.0.0 and I have an error message only when building with Visual Studio 14. I'm curious if fmt 6.0.0 requires a C++11 feature which is not supported by MSVC14.

#### Environment
OS: Windows 10
FMT Version: 6.0.0
Build Type: Debug
Compiler: Visual 14
Compiler Runtime: MTd

#### Logs

https://c3i.jfrog.io/c3i/misc/logs/pr/180/7/spdlog/1.4.2/9172f274abc0e0d0afcbc0284c6b5a7967936d5f/create_stdout.txt

#### Related issue:
- https://github.com/conan-io/conan-center-index/pull/180

Regards!

**Comment by vitaut** [comment]
MSVC version numbering is a bit of a mess but if 14 corresponds to 2015 (_MSC_VER == 1900) then it should be supported. The log only shows a warning promoted to an error via the /X flag. I'd recommend compiling without /X.

**Comment by vitaut** [comment]
Here are MSVC compiler versions {fmt} is continuously tested on: https://ci.appveyor.com/project/vitaut/fmt

**Comment by uilianries** [comment]
Nice! Spasibo for your quickly answer! I'll disable that flag.
