### ISSUE TITLE
Output of fmt doesn't match C's printf for 'g'

### ISSUE THREAD

**Issue by Queueless** [fmtlib/fmt#1376]
I'm replacing a home grown safe format library with fmt and here is a test case where the output doesn't match:

sprintf("%g", 0.000000456) -> 4.56e-07
fmt::sprintf("%g", 0.000000456) -> 4.56000e-07

I found that FMT_USE_GRISU set to zero fixes my problem, so this algorithm appears to not generate equivalent output.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/40414b34468046ed84eb2897682d49964986c467. Thanks for reporting.
