### ISSUE TITLE
clang sanitizer complains when trying to output negative integers

### ISSUE THREAD

**Issue by t-b** [fmtlib/fmt#1377]
91f7619c (Fix Visual Studio 2019 pedantic warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?), 2019-10-14)

on macosx using xcode 

```
Thomass-iMac:~ ci$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

when doing something like

```
  const int INDENT_COMPACT = -1;
  const int INDENT_WIDE    = 10;

   auto str = "Intendation must be between {} (compact) or {} (wide indentation)."_format(INDENT_COMPACT, INDENT_WIDE));
```

I get

```
/fmt/format.h:1374:36: runtime error: unsigned integer overflow: 0 - 4294967295 cannot be represented in type 'unsigned int'
    #0 0x16451428b in void fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::write_decimal<int>(int) format.h:1374

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/ci/work/builds
```

**Comment by vitaut** [comment]
This is weird because unsigned integer overflow is not a UB in C++. Also I wasn't able to reproduce it on your example or reduced one (https://godbolt.org/z/oq-O3I). Could you provide more details on how to repro (perhaps there are some additional compiler flags that affect this)?

**Comment by t-b** [comment]
@vitaut Thanks for looking into it. You have to pass the sanitize integer option as well, sorry for the sloppy report.

Here is an example https://godbolt.org/z/8xva4e.

**Comment by t-b** [comment]
@vitaut And yes unsigned integer overflow is not UB.

**Comment by vitaut** [comment]
Should be worked around in https://github.com/fmtlib/fmt/commit/58c6f8c7f5e02ad396eb0e39fcf441bdb714ca1c.

**Comment by t-b** [comment]
@vitaut Thanks!
