### ISSUE TITLE
std::format

### ISSUE THREAD

**Issue by DBJDBJ** [fmtlib/fmt#1379]
I might have missed something ... I can not find `std::format` referent implementation?

**Comment by vitaut** [comment]
`fmt::format` is a reference implementation of `std::format`. It is in a different namespace because {fmt} is not a standard library and shouldn't define names in `std`.

**Comment by DBJDBJ** [comment]
Many thanks @vitaut 

I am slightly confused: it appears std::format is a subset of fmt::format?

One might expect C++20 std will contain <format> ? All in one header which now is not the case.
There is talk about this "std branch" but it is not in the fmt github as of today?

I beg to differ {fmt} appears not to be the "reference implementation of std::format" ... 
There is currently no implementation as described in the [WG21 doc](https://fmt.dev/Text%20Formatting.html#Implementation)?

**Comment by vitaut** [comment]
> it appears std::format is a subset of fmt::format?

Yes.

> One might expect C++20 std will contain ?

C++20 will contain everything described in the paper (http://wg21.link/p0645): `format`, `format_to`, `format_to_n`, `formatted_size` and the extension API (`formatter` specializations).

> There is talk about this "std branch" but it is not in the fmt github as of today?

That's because the `std` branch has been merged into `master` after the paper has been published.

**Comment by DBJDBJ** [comment]
ok ... call me spoiled but :) can we have one header file [as described in the summary](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0645r10.html#format.syn) .. with top level namespace for example `std_fmt` ... :)

**Comment by vitaut** [comment]
Unfortunately there is no header that **only** has what's in the standard and it would be a lot of work to maintain such subset. However, if you want **all** that's in the standard (modulo minor inconsistencies that are being fixed) then `fmt/format.h` is your header and `std_fmt` is just `fmt`.

**Comment by DBJDBJ** [comment]
@vitaut many thanks for dialogue. I understand there is probably no "fmt team" and it is only you., and you are busy

**Comment by dkozel** [comment]
I came looking for the same thing as DBJDBJ, a bridge to use std::format in a C++14 project since we're unlikely to be able to move to C++20 for another 5+ years sadly (we're only moving to c++14 this year).

It would be very helpful to have a note somewhere about discrepancies between `fmt/format.h` and `std::format` in C++20.

Thanks for all your work on the standard and for making this library easy to include in projects!

**Comment by vitaut** [comment]
> It would be very helpful to have a note somewhere about discrepancies between fmt/format.h and std::format in C++20.

Opened a separate issue: #1686.

**Comment by DBJDBJ** [comment]
Great, we are getting somewhere at last. Thanks to @vitaut again.
I am also vitally interested in char8_t  handling, but that is a wider story where {fmt} position me thinks is best to avoid it ...
