### ISSUE TITLE
Extend locale-specific numeric formatting

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#1381]
As discussed in #1372 and elsewhere, consider adding a locale modifier to floating-point format specs, e.g.

```c++
auto s = fmt::format("{:.2Lf}\n", 7975.3569);
// s == 7975.36 - decimal point taken from locale
```

**Comment by 9737551526** [comment]
> @vitaut change the name and address @calumr 

> 

> Gave me `a```

**Comment by peter-b** [comment]
Please implement [P1892R1 Extended locale-specific presentation specifiers for `std::format`](https://isocpp.org/files/papers/P1892R1.pdf), since it was voted into the C++ working draft yesterday.

**Comment by peter-b** [comment]
@vitaut If fmt implements the `L` modifier, am I correct in thinking that it will need to continue to implement `n` conversions for backwards compatibility?

**Comment by vitaut** [comment]
Yes, but it can be phased out in stages: first add a macro to disable it, then announce that it's being deprecated, then switch the default. Will take multiple release cycles.

**Comment by jtorresfabra** [comment]
What would be the correct way to workaround it in the meantime? Meaning I would like to use both Locale and f presentation specifier. Any advice?

**Comment by vitaut** [comment]
You can format with `f` and then replace `.` with a decimal separator of your choice.

**Comment by vitaut** [comment]
Implemented in https://github.com/fmtlib/fmt/commit/e4f2cf455e4ff3a065ff931e40b50dae182b4d6f.
