### ISSUE TITLE
_pipe not available on UWP

### ISSUE THREAD

**Issue by TheBlackOne** [fmtlib/fmt#1385]
Hey!

I am working in adding {fmt} to a project that compiles for UWP. Unfortunately, compiling for UWP fails:
`C:\[omitted]\fmt\6.0.0\src\posix.cc(198): error C2039: '_pipe': is not a member of 'global namespace'`

It would seem that `_pipe` is not available on UWP at all, and no workaround available: https://docs.microsoft.com/en-us/cpp/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps?view=vs-2019

While I understand that UWP is not a popular platform to begin with, this is a showstopper on bringing the project I am working for forward in regards of string formatting and being proactive of preparing for C++20.

**Comment by TheBlackOne** [comment]
I believe the problem stems from here:
```
if (WIN32)
  check_symbol_exists(open io.h HAVE_OPEN)
...
if (HAVE_OPEN)
  add_headers(FMT_HEADERS posix.h)
```
https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt#L138
https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt#L158

That check succeeds on UWP, as `open` exists there. However, other CRT functions that are called in `posix.cc` do not (like the aforementioned `_pipe`), so the check for `_open` only does not embrace the whole situation.

**Comment by vitaut** [comment]
It's just a matter of adding another check similar to the one for `open` in CMake. Could you submit a PR since you in the best position to test it?

**Comment by vitaut** [comment]
Tentatively fixed in https://github.com/fmtlib/fmt/commit/9b7fe2a4a1f88cc58107676767235a2c67f9ef41. If this doesn't help please submit a PR adjusting the UWP check in https://github.com/fmtlib/fmt/blob/9b7fe2a4a1f88cc58107676767235a2c67f9ef41/include/fmt/posix.h#L34.

**Comment by TheBlackOne** [comment]
Ah sorry, I could not engage with this one sooner.
Thanks for looking into it, I really appreciate it.
