### ISSUE TITLE
Linux compilation using X11's header Xos.h failed, due to macro definition "index(s, c)"

### ISSUE THREAD

**Issue by BoneCrasher** [fmtlib/fmt#1388]
Using libfmt on linux in conjunction with X11 headers I encountered a name collision with the macro `index(s, c)` defined in `Xos.h`.

If `fmt/format.h` is included *AFTER* `Xos.h`, this code in `format.h` will fail to compile:

```cpp

  arg_id_kind kind;
  union value {
    FMT_CONSTEXPR value() : index(0u) {}
    FMT_CONSTEXPR value(int id) : index(id) {}
    FMT_CONSTEXPR value(basic_string_view<Char> n) : name(n) {}

    int index;
    basic_string_view<Char> name;
  } val;
```
with
`error: macro "index" requires 2 arguments, but only 1 given
     FMT_CONSTEXPR value() : index(0u) {}`

since `index(...)` expects two arguments.

**Comment by vitaut** [comment]
Worked around in https://github.com/fmtlib/fmt/commit/50912fb35be9f533a3b24e730bc6439be608e479.
