### ISSUE TITLE
Better document the extension API

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#1395]
Improve the docs: https://fmt.dev/latest/api.html#formatting-user-defined-types, particularly documenting what the inputs and the outputs are in `parse` and `format` and provide a more interesting example.

**Comment by peter-b** [comment]
Am I right to suspect the "more interesting example" include suppressing a leading `-` when a floating point number happens to be rounded to all-zeroes?

**Comment by vitaut** [comment]
That's not what I had in mind but now I'm considering `-` suppression as an example =).
