### ISSUE TITLE
compile time format strings (FMT_STRING) does not work on VS2013

### ISSUE THREAD

**Issue by solstice333** [fmtlib/fmt#1396]
https://fmt.dev/5.3.0/index.html mentions that fmt is compatible with Visual Studio VC12 2013 (or at least that's what I think is meant by "MSVC 18.0 (2013)"). 

However in the release notes for fmt 5.0.0 (https://github.com/fmtlib/fmt/releases), it mentions "Compile-time checks require relaxed constexpr (C++14 feature) support. If the latter is not available, checks will be performed at runtime". 

Furthermore, https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140)?redirectedfrom=MSDN mentions that `constexpr` is not supported for Visual Studio 2013. 

Can someone confirm that the documentation at https://fmt.dev/5.3.0/index.html means to say that fmt 5.3.0 is mostly compatible with Visual Studio VC12 2013 **except** for compile time format strings? Or is there documentation that shows which features of fmt 5.3.0 are compatible with VC12 and which aren't? 

WRT the issue posted here https://github.com/fmtlib/fmt/issues/1108. I don't get any sort of "fallback behavior". Instead for...

```
#include <string>

#define FMT_HEADER_ONLY
#include "fmt/format.h"

int main() {
		 std::string s = fmt::format(FMT_STRING("{}"), "foo");
}
```

the compilation fails saying

```
1>  foo.cpp
1>c:\users\knavero\foo\foo.cpp(7): error C2899: typename cannot be used outside a template declaration
1>c:\users\knavero\foo\foo.cpp(7): error C2664: 'main::str::main::str(const main::str &)' : cannot convert argument 1 from 'main::<lambda_441329ac2c1ece25712824046c0aa1ab>::()::str' to 'const main::str &'
1>          Reason: cannot convert from 'main::<lambda_441329ac2c1ece25712824046c0aa1ab>::()::str' to 'const main::str'
1>          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>c:\users\knavero\foo\foo.cpp(7): error C2664: 'main::str::main::str(const main::str &)' : cannot convert argument 1 from 'main::<lambda_441329ac2c1ece25712824046c0aa1ab>::<helper_func_cdecl>::str' to 'const main::str &'
1>          Reason: cannot convert from 'main::<lambda_441329ac2c1ece25712824046c0aa1ab>::<helper_func_cdecl>::str' to 'const main::str'
1>          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>c:\users\knavero\foo\foo.cpp(7): error C2664: 'main::str::main::str(const main::str &)' : cannot convert argument 1 from 'main::<lambda_441329ac2c1ece25712824046c0aa1ab>::<helper_func_vectorcall>::str' to 'const main::str &'
1>          Reason: cannot convert from 'main::<lambda_441329ac2c1ece25712824046c0aa1ab>::<helper_func_vectorcall>::str' to 'const main::str'
1>          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

Any thoughts on this? Thanks.

**Comment by vitaut** [comment]
> Can someone confirm that the documentation at https://fmt.dev/5.3.0/index.html means to say that fmt 5.3.0 is mostly compatible with Visual Studio VC12 2013 except for compile time format strings?

Sort of. {fmt} 5.3 is mostly compatible with MSVC 2013. Optional features such as compile-time checks that require modern C++ constructs may not work on all compilers and MSVC 2013 has known bugs and severely lacking C++11 support.

**Comment by solstice333** [comment]
Well, I tinkered around the code surrounding `FMT_STRING`. I see now why you need that lambda local struct. I tried externalizing it, and I see why that won't work too...oh well. The idea of compile time format strings is nice though.
