### ISSUE TITLE
Support locale with compiled format

### ISSUE THREAD

**Issue by dlaugt** [fmtlib/fmt#1402]
Could we support the locale override with compiled format?

The following code doesn't compile:
```cpp
  auto compiled_format = fmt::compile<int>(FMT_STRING("{:n}"));
  for (int i = 0; i < 10000; ++i)
  {
    char buf[100];
    auto end = fmt::format_to(buf, std::locale("en-US"), compiled_format, i);
    *end = '\0';
  }
```

**Comment by vitaut** [comment]
This is expected. Format string compilation is just a prototype and supports only a small subset of features.
