### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by tdegeus** [fmtlib/fmt#1408]
I've opened a PR to add a conda-forge package for **{fmt}** (https://github.com/conda-forge/staged-recipes/pull/10140). Would any of the developers/maintainers/contributors like to join me as a maintainer of this package? If yes, you'd have to acknowledge this in a comment to the PR. 

Currently there is still a build issue on Windows:
```none
fatal error C1083: Cannot open include file: 'cstdint': No such file or directory
```
Is this a know issue? Is there a workaround?

My search yielded:
* https://stackoverflow.com/questions/20427614/vc6-fatal-error-c1083-cannot-open-include-file-stdint-h
* https://stackoverflow.com/questions/12970293/why-microsoft-visual-studio-cannot-find-stdint-h/12970619#12970619
* https://stackoverflow.com/questions/6688895/does-microsoft-visual-studio-2010-support-c99/6689014#6689014
* https://stackoverflow.com/questions/126279/c99-stdint-h-header-and-ms-visual-studio

From this it seems that two options are to [use boost](http://www.boost.org/doc/libs/1_36_0/boost/cstdint.hpp) or to [change the source](https://stackoverflow.com/a/127166/2646505). The former is I think entirely unwanted, while the latter is feasible.

**Comment by tdegeus** [comment]
The package is live: https://github.com/conda-forge/fmt-feedstock

It would be great if:
* Developers/maintainers/contributors would like to join me as a maintainer of this package.
* The listed Windows error is fixed, such that all Windows builds can be enabled.

**Comment by vitaut** [comment]
Thanks for doing this!

> Would any of the developers/maintainers/contributors like to join me as a maintainer of this package?

While I would be happy to join, I know nothing about conda and would be pretty useless as a maintainer there. Does being a maintainer actually mean anything, isn't it possible to submit package updates via PRs?

> Is this a know issue?

No. AFAICS Windows builds pass. Which compiler version?

> Is there a workaround?

Does replacing `<cstdint>` with `<stdint.h>` fix the issue?

**Comment by vitaut** [comment]
> Conda could be added to the documentation.

Could you submit a PR adding installation instructions for conda to 
https://github.com/fmtlib/fmt/blob/master/doc/usage.rst?

or post them here and I'll update the docs.

**Comment by tdegeus** [comment]
@vitaut 

> Thanks for doing this!

Happy to, thanks for the great library!

> > Would any of the developers/maintainers/contributors like to join me as a maintainer of this package?
> While I would be happy to join, I know nothing about conda and would be pretty useless as a maintainer there. Does being a maintainer actually mean anything, isn't it possible to submit package updates via PRs?

Yes, conda feedstocks can be updated like any git repository with PRs. The only benefit of being a maintainer would be that you'd have push rights on the conda-feedstock. I.e. you could merge the PRs. 

> > Is this a known issue?

> No. AFAICS Windows builds pass. Which compiler version?

As an absolute non-expert for Windows that is a tough question for me to answer ;). I would guess Visual Studio 2008.

> > Is there a workaround?

> Does replacing <cstdint> with <stdint.h> fix the issue?

We could try by adding a patch to the feedstock (and fix the source later, if it indeed fixes the problem). Here's my go: https://github.com/conda-forge/fmt-feedstock/pull/2

> > Conda could be added to the documentation.

> Could you submit a PR adding installation instructions for conda to https://github.com/fmtlib/fmt/blob/master/doc/usage.rst?
> or post them here and I'll update the docs.

Sure I'll open a PR for the docs!

**Comment by tdegeus** [comment]
@vitaut 

In fact is leads to a Linux failure:

```bash
format.h:39:10: fatal error: stdint: No such file or directory
 #include <stdint>
```

**Comment by vitaut** [comment]
`stdint.h`, not `stdint`. In any case MSVC 2008 will only work with {fmt} 4.x.

> The only benefit of being a maintainer would be that you'd have push rights on the conda-feedstock. I.e. you could merge the PRs.

Please add me as a maintaner then.

**Comment by tdegeus** [comment]
@vitaut Will do. Let's simply keep the most recent MSVC for conda then.
