### ISSUE TITLE
[docs] Add side-bar with contents

### ISSUE THREAD

**Issue by tdegeus** [fmtlib/fmt#1411]
It took me a while to realise that [fmt.dev](https://fmt.dev/latest/index.html) is in fact the documentation because I scrolled down too fast (hiding the top bar). I think it would be much more intuitive to have a side-bar with the contents always shown (like on readthedocs.io, this style could be used).

**Comment by vitaut** [comment]
Thanks for the suggestion. Side bars are not mobile-friendly and this would duplicate the top navigation, so I'm not sure if it's worth it.
