### ISSUE TITLE
Support for char16_t/u16string?

### ISSUE THREAD

**Issue by kihoku** [fmtlib/fmt#1412]
Is u16string supported ? 
fmt supports u16string  according to this ticket[(Support for char16_t/u16string?)](https://github.com/fmtlib/fmt/issues/698).
However, `std::u16string s = fmt::format(u"{The answer is {}.}", 42);` does't work.(v 6.0.0)

**Comment by vitaut** [comment]
`u16string` is supported: https://godbolt.org/z/StJm43. You might need to use a recent compiler version.

**Comment by kihoku** [comment]
@vitaut It can be compiled, but it throw fmt::v6::format_error.

**Comment by vitaut** [comment]
That's unrelated to `u16string`. Your format string has unescaped braces.

**Comment by kihoku** [comment]
Thank you so much.
Is user-defined type supported for u16string?

**Comment by vitaut** [comment]
Yes if the user-defined `formatter` specialization supports `char16_t`.

**Comment by vitaut** [comment]
That said I'd recommend avoiding `char16_t` and using `char` with UTF-8 for better portability and less code bloat.
