### ISSUE TITLE
Support C++ 20 ranges/views

### ISSUE THREAD

**Issue by richard-vock** [fmtlib/fmt#1413]
Given that both, fmt as well as ranges will make it into C++20 it would be awesome if we could print ranges, i.e. the following code:

    #include <fmt/format.h> 
    #include <fmt/ranges.h>      
    #include <experimental/ranges/ranges>           
    namespace views = std::experimental::ranges::views; 
                                                     
                                                    
    int                                                                                
    main() 
    {              
        auto list = views::iota(1, 10) 
                  | views::filter([] (int v) { return v < 5; }); 
     
        fmt::print("{}\n", list);
    }

...would print list as if it was a std::vector.

I tested this with both, Niebler's range-v3 as well as the proposed STL2 variant (cmcstl2). Both fail to compile due to CV qualifier constraints in fmt 6.0.0.

Error output (the range-v3 is magnitudes worse w.r.t. readability):
https://pastebin.com/nnc9dH1a

**Comment by vitaut** [comment]
Could you submit a PR relaxing the constraints you are referring to?

**Comment by richard-vock** [comment]
I can look into it - might take a while though.

**Comment by DBJDBJ** [comment]
https://en.cppreference.com/w/cpp/utility/format/formatter

**Comment by vitaut** [comment]
This can be done via the extension API without changing {fmt} but a PR would still be welcome provided that it can be done in a generic way without adding an external dependency.
