### ISSUE TITLE
Grisu: trailing zero with fixed, precision=0, and showpoint

### ISSUE THREAD

**Issue by planet36** [fmtlib/fmt#1417]
When printing in fixed notation with precision=0 and showpoint , there is a trailing zero when Grisu is enabled.

Using g++ 9.2.1 and libfmt master branch (9108b25da901ff02df622a087b8781fe38ef898f)

The following code illustrates this
```
#include <fmt/format.h>
#include <iostream>

int main()
{
	std::cout << "FMT_VERSION=" << FMT_VERSION << '\n';
	std::cout << "FMT_GCC_VERSION=" << FMT_GCC_VERSION << '\n';
#ifdef FMT_USE_GRISU
	std::cout << "FMT_USE_GRISU=" << FMT_USE_GRISU << '\n';
#else
	std::cout << "FMT_USE_GRISU not defined\n";
#endif

	double x = 123.0;
	int precision = 0;

	std::cout.precision(precision);

	std::cout << "cout: " << std::showpoint << std::fixed << x << '\n';
	std::cout << "fmt:  " << fmt::format("{:#.{}f}", x, precision) << '\n';

	return 0;
}
```

Outputs:
```
FMT_VERSION=60001
FMT_GCC_VERSION=902
FMT_USE_GRISU=1
cout: 123.
fmt:  123.0

```

**Comment by vitaut** [comment]
Good catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/28d7191c277eb679c0e7d6469de36755087afc3b.

**Comment by planet36** [comment]
On a related note...
Running the same example code, but with Grisu _disabled_, I noticed a change in output introduced in commit ded1e767.

> FMT_VERSION=60001
> FMT_GCC_VERSION=902
> FMT_USE_GRISU=0
> cout: 123.
> fmt:  123.000000

Using the prior commit (c7edd8e5) outputs:

> FMT_VERSION=60001
> FMT_GCC_VERSION=902
> FMT_USE_GRISU=0
> cout: 123.
> fmt:  123.

**Comment by vitaut** [comment]
FP formatting was being refactored =). Should be fixed now.

**Comment by planet36** [comment]
On another related note, when printing scientific notation, there is a missing decimal point.

```
	std::cout << "cout: " << std::showpoint << std::scientific << x << '\n';
	std::cout << "fmt:  " << fmt::format("{:#.{}e}", x, precision) << '\n';
```

Outputs

> cout: 1.e+02
> fmt:  1e+02
