### ISSUE TITLE
Use fmt-head-only with MinGW raise an compile error

### ISSUE THREAD

**Issue by liwangqian** [fmtlib/fmt#1420]
```cpp
const auto &near = m_lookahead.value();
```
error: expected unqualified-id before '=' token

when change the variable `near` to `near_`, the compile success, it seems the symbol `near` is defined in MinGW header file `windef.h` as bellow:
```c
#define FAR
#define far
#define NEAR
#define near
#ifndef CONST
#define CONST const
```

**Comment by vitaut** [comment]
{fmt} is not responsible for macros defined in Windows headers. A simple solution is not to use the header-only mode or to undefine the macro.
