### ISSUE TITLE
Unexpected compile time error when forbidden rvalue operator const char*

### ISSUE THREAD

**Issue by Alek86** [fmtlib/fmt#1421]
Maybe it's a known limitation, sorry for bothering in this case.
This code generates a compiler error (tried with VS 2015 and godbolt with clang 6.0.0):

    #include <fmt/core.h>
    class PString {
    public:
        const char* c_str() const { return "11"; }
        operator const char*() const& { return c_str(); }
        operator const char*()& { return c_str(); }
        operator const char*() const&& = delete;
        operator const char*()&& = delete;
    };
    int main() {
        PString str;
        fmt::print("{}", str);
    }

Not a big deal, because it's easily bypassed by adding code below. But maybe you want to address it anyway.

    template <>
    struct fmt::formatter<PString> {
      constexpr auto parse(format_parse_context& ctx) { return ctx.begin(); }
      template <typename FormatContext>
      auto format(const PString& ct, FormatContext& ctx) {
        return format_to(ctx.out(), "{}", ct.c_str());
      }
    };

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/99b6e928d402379a7cda9a435649ee17261d866d. Thanks for reporting.
