### ISSUE TITLE
Question: Is there a way to build fmt without reliance on ostream?

### ISSUE THREAD

**Issue by kammce** [fmtlib/fmt#1429]
I'm attempting to use this for an embedded project, but the inclusion and usage of iostream results in a 150kB increase in my binary size. I feel that, among other things, this is contributing the most to the size increase of the binary.

Is there a way to disable this?

**Comment by vitaut** [comment]
Yes, just don't include `fmt/ostream.h` anywhere in your project. {fmt} itself doesn't use ostream.

**Comment by kammce** [comment]
What about including fmt/printf.h which does import ostream? I'll try a bit more to see where I'm linking in ostream.

**Comment by vitaut** [comment]
Right, avoid `printf.h` as well. The core library (`core.h`, `format.h`, `format-inl.h`) doesn't use iostreams.
