### ISSUE TITLE
[Win32 DLL] Don't inherit from std::runtime_error

### ISSUE THREAD

**Issue by marti4d** [fmtlib/fmt#1430]
Hey there. Just wanted to say I love this library - It's awesome :)

So... When compiling the two '.cc' files into a Windows DLL, I do the correct thing and compile with `FMT_EXPORT` defined and I get the following warning many times:

```
include\fmt\format.h(626): warning C4275: non dll-interface class 'std::runtime_error' used as base for dll-interface class 'fmt::v6::format_error'
vc\tools\msvc\14.16.27023\include\stdexcept(157): note: see declaration of 'std::runtime_error'
```

It appears that the root cause of this is that `std::runtime_error` is part of libc++ and isn't included in the DLL exports, so exporting it is potentially dangerous if the user of the DLL isn't using the exact same version of libc++.

**Comment by vitaut** [comment]
Thanks!

`format_error` should inherit from `std::runtime_error` both conceptually and for consistency with `std::format`. Moreover, passing C++ objects across DLL boundary is dangerous in general unless the same version of the standard library is used everywhere, so it's no different here. That said I'd be open to a PR to suppress the warning provided that it's not too intrusive.
