### ISSUE TITLE
Some tests fail on ppc64 BE

### ISSUE THREAD

**Issue by luigino** [fmtlib/fmt#1431]
fmt 6.0.0 on openSUSE Tumbleweed, see [log](https://github.com/fmtlib/fmt/files/3904540/fmt_ppc64be.txt).
No apparent problem on ppc64le.

**Comment by vitaut** [comment]
Tentatively fixed in https://github.com/fmtlib/fmt/commit/bb205d940d8929d086eadb59705349dbdaa1a274. Could you confirm that it solved the problem?

**Comment by luigino** [comment]
Improved, but [no dice](https://github.com/fmtlib/fmt/files/3905615/fmt_ppc64be_2.txt) :disappointed:

**Comment by vitaut** [comment]
Oops, I forgot to actually swap bytes effectively rendering my "fix" a noop 🤦. Committed take two and some follow-up fixes, hopefully https://github.com/fmtlib/fmt/commit/ba6e330fd3a9c2d859d651c59d6206620940a265 will work.

**Comment by luigino** [comment]
I can confirm the problem is solved on both ppc64be and s390x.

**Comment by vitaut** [comment]
Awesome, thanks!
