### ISSUE TITLE
Question: add color to custom formatter

### ISSUE THREAD

**Issue by rianquinn** [fmtlib/fmt#1436]
I would like to use {fmt} to output a std::source_location with a specific format that includes terminal color to an existing fmt::print statement. For example:

```
fmt::print("Hello World: {}\n", std::source_location::current());
```

might produce something like
"Hello World: \<green\>file name\<end\>:\<yellow\>line\<end\>"

I cannot figure out how to use a user-defined formatter to do this. Any ideas?

**Comment by vitaut** [comment]
You can do it as follows:

```c++
#include <fmt/color.h>

struct myloc {
  const char* file;
  int line;
};

template <> struct fmt::formatter<myloc> {
  auto parse(format_parse_context& ctx) { return ctx.begin(); }

  template <typename FormatContext>
  auto format(myloc loc, FormatContext& ctx) {
    return format_to(ctx.out(), "{}:{}",
        fmt::format(fg(color::green), "{}", loc.file), loc.line);
  }
};

int main() {
  fmt::print("{}\n", myloc{"foo", 42});
}
```

Normally you should provide formatter specialization only for types you control which is why I use `myloc` instead of `source_location`. Also `format` can be optimized avoiding additional `std::string` construction. See also https://fmt.dev/dev/api.html.

**Comment by rianquinn** [comment]
The above worked. Is there any better reference documentation, or an example of how to avoid the std::string? I am not really sure what APIs in the documentation you are referring to.

**Comment by vitaut** [comment]
I meant using a preallocated buffer (e.g. https://fmt.dev/dev/api.html#_CPPv2N3fmt19basic_memory_bufferE) and `format_to`. It probably doesn't matter since I/O time will dominate.
