### ISSUE TITLE
while creating appium node for android devices using udid"Error: Syntax error in node configuration file: Unexpected token P in JSON at position 0"

### ISSUE THREAD

**Issue by sandeepsdhiwar** [fmtlib/fmt#1441]
appium --nodeconfig asus.json -p 4727 -bp 5727 -U K1AAGF039953CZW --no-reset
[Appium] Welcome to Appium v1.15.1
[Appium] Non-default server args:
[Appium]   port: 4727
[Appium]   bootstrapPort: 5727
[Appium]   nodeconfig: asus.json
[Appium]   udid: K1AAGF039953CZW
[Appium]   noReset: true
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"K1AAGF039953CZW"}'
[Appium]   --no-reset => --default-capabilities '{"noReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: K1AAGF039953CZW
[Appium]   noReset: true
[Appium] Error: Syntax error in node configuration file: Unexpected token P in JSON at position 0
[Appium]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:79:13)
[Appium]     at errorAndThrow (/usr/local/lib/node_modules/appium/lib/grid-register.js:48:12)
[Appium]     at postRequest (/usr/local/lib/node_modules/appium/lib/grid-register.js:26:3)
[Appium]     at <anonymous>
Fatal Error: Syntax error in node configuration file: Unexpected token P in JSON at position 0
    at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:79:13)
    at errorAndThrow (/usr/local/lib/node_modules/appium/lib/grid-register.js:48:12)
    at postRequest (/usr/local/lib/node_modules/appium/lib/grid-register.js:26:3)
    at <anonymous>

**Comment by vitaut** [comment]
Looks unrelated to {fmt}.
