### ISSUE TITLE
Percentage formatting broken in 6.1.0

### ISSUE THREAD

**Issue by federico-busato** [fmtlib/fmt#1448]
Example: [link](https://godbolt.org/z/-p2Nrv)

**Comment by vitaut** [comment]
`%` is deprecated and changed to an opt-in. It can be enabled by compiling with the `FMT_DEPRECATED_PERCENT` macro defined to 1 but will be removed in the future for consistency with `std::format` and to avoid overhead for the common case. A better option is to provide a `percent` type and use the extension API to implement this feature:

```
fmt::print("{}", percent(0.42));
```

**Comment by federico-busato** [comment]
Please update the documentation to highlight that percentage formatting is deprecated

**Comment by vitaut** [comment]
Good idea. Removed it from the docs altogether: https://github.com/fmtlib/fmt/commit/4f4d87661655781ee23bb8860c07afe67b301111
