### ISSUE TITLE
Compile-time format validation doesn't work in 6.*

### ISSUE THREAD

**Issue by alex3d** [fmtlib/fmt#1453]
It seems `FMT_STRING` compile-time format validation is broken in 6.0.0 and 6.1.0

**Comment by vitaut** [comment]
Seems to be working on 6.0 and master: https://godbolt.org/z/FcE6Kz

**Comment by alex3d** [comment]
Ok, validation doesn't work only with c++11. Probably I've missed c++14 requirement somewhere in docs.
