### ISSUE TITLE
fmt-targets.cmake issue

### ISSUE THREAD

**Issue by lbWC** [fmtlib/fmt#1456]
When I use "-DCMAKE_INSTALL_INCLUDEDIR = fmtxx" to compile fmt, the "INTERFACE_INCLUDE_DIRECTORIES" of set_target_properties (fmt :: fmt ...) in fmt-targets.cmake is still "$ {_ IMPORT_PREFIX} / include" instead of "$ { _ IMPORT_PREFIX} / fmtxx ", is this a bug or is there something wrong with my compilation method

**Comment by lbWC** [comment]
But <includedir> in fmt.pc is correct

**Comment by vitaut** [comment]
I think it's set in https://github.com/fmtlib/fmt/blob/4f4d87661655781ee23bb8860c07afe67b301111/CMakeLists.txt#L174 Is there any particular reason you want to change it?

**Comment by lbWC** [comment]
But includedir = $ {prefix} / fmtxx in the file fmt.pc,
If I use the shell to automatically compile fmt and put the header files elsewhere, then use find_package to find fmt will have problems

**Comment by vitaut** [comment]
A PR to make install include directory configurable would be welcome.

**Comment by vitaut** [comment]
Closing for now but as commented earlier:

> A PR to make install include directory configurable would be welcome.
