### ISSUE TITLE
format-impl-test fails to link using MacPorts Clang

### ISSUE THREAD

**Issue by athrun22** [fmtlib/fmt#1461]
On macOS, the format-impl-test fails to link when using the MacPorts Clang compiler. This is due to the "ifdef __apple_build_version__" check in the format-impl-test.cc file for value_extractor class. This only checks if the Clang compiler is Apple's Clang, but not whether Apple's libc++ is being linked. Simply replacing the macro with TARGET_OS_MAC corrects my issue, but I don't think this is very robust. I recommend using CMake's [CheckCXXSourceRuns](https://cmake.org/cmake/help/latest/module/CheckCXXSourceRuns.html) to reliably detect whether __int128_t and __uint128_t are available.

**Comment by vitaut** [comment]
`apple_build_version` should just be replaced with `FMT_USE_INT128`.

**Comment by athrun22** [comment]
Well... isn't that convenient? :) The test runs successfully when I replace ```apple_build_version``` with ```FMT_USE_INT128```.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/73a16b827f71e9d2b18f77418a56d6610d04926d.
