### ISSUE TITLE
Specifier 'n' does not format precision properly

### ISSUE THREAD

**Issue by dconnet** [fmtlib/fmt#1465]
The following test produces "4e+01" instead of the proper "42.3":
`fmt::format(L"{:.{}n}", 42.34, 1);`

Using the 'f' specifier works as expected.
(testing with v6.1.1)

**Comment by vitaut** [comment]
`4e+01` is the correct output because `n` is a general, not fixed format:

> This is the same as 'g', except that it uses the current locale setting to insert the appropriate number separator characters.

https://fmt.dev/latest/syntax.html

**Comment by dconnet** [comment]
Is there any way to have a fixed format that uses locale settings for number separators? Or should I open a feature request for that?

**Comment by vitaut** [comment]
> Is there any way to have a fixed format that uses locale settings for number separators?

No

> Or should I open a feature request for that?

It's already tracked in https://github.com/fmtlib/fmt/issues/1381, so no need to open another issue.

**Comment by dconnet** [comment]
Ah - thx! Now I know what to watch!
