### ISSUE TITLE
Broken ABI without soname change

### ISSUE THREAD

**Issue by eli-schwartz** [fmtlib/fmt#1471]
Projects linked to libfmt.so.6.0.0 are broken when they try to load libfmt.so.6.1.1 due to the missing symbol: `_ZN3fmt2v68internal14sprintf_formatIdEEPcT_RNS1_6bufferIcEENS1_13sprintf_specsE`

See e.g. https://bugs.archlinux.org/task/64802

**Comment by eli-schwartz** [comment]
Broken by ded1e7679ecddbfc3209fc9fa6058f597c02a5c2 I guess?

**Comment by vitaut** [comment]
I've reintroduced `sprintf_format` in https://github.com/fmtlib/fmt/commit/ae7c50185dacb005ae1660ce5b2980eb12414993 to restore the ABI compatiblity:

```
$ nm -gU  libfmt.6.dylib  | grep sprintf
0000000000002130 T __ZN3fmt2v68internal14sprintf_formatIdEEPcT_RNS1_6bufferIcEENS1_13sprintf_specsE
0000000000002430 T __ZN3fmt2v68internal14sprintf_formatIeEEPcT_RNS1_6bufferIcEENS1_13sprintf_specsE
```

Thanks for reporting!

**Comment by eli-schwartz** [comment]
Thanks, I've confirmed the solution on my end by backporting this patch into our fmt package and locally rebuilding/testing it.

I guess it probably makes sense for you to release a hotfix soon, so that the distros which have already upgraded can get this change automatically.

**Comment by vitaut** [comment]
Thanks for the confirmation. I do plan to release 6.1.2 which will include this and other fixes shortly.
