### ISSUE TITLE
format_to_n doesn't format characters with printf-style format strings

### ISSUE THREAD

**Issue by timwoj** [fmtlib/fmt#1473]
Similar to https://github.com/fmtlib/fmt/issues/778, but with `printf`-style format strings:

This code snippet:

```
char tmp[25];
auto res = fmt::format_to_n(tmp, 25, "%d", 12345);
printf("%lu\n", res.size);
printf("%s\n", tmp);
```

results in this output:

```
2
%d
```

It appears to work completely fine with python-style format strings like `{}`.

**Comment by vitaut** [comment]
`format_to_n` uses Python-style format strings.
