### ISSUE TITLE
cannot copy fmt_memory_buffer into another one

### ISSUE THREAD

**Issue by krmrmethod** [fmtlib/fmt#1474]
Hi, I'm fairly new to C++. 

I'm trying to copy the contents of one memory buffer into another but I get this error:

>C2280	'fmt::v6::basic_memory_buffer<char,500,std::allocator<char>> &fmt::v6::basic_memory_buffer<char,500,std::allocator<char>>::operator =(const fmt::v6::basic_memory_buffer<char,500,std::allocator<char>> &)': attempting to reference a deleted function	160	

What I'm trying to do is the following:

`fmt::memory_buffer text;`
`fmt::memory_buffer text2;`

`fmt::format_to(text, "Hello {}", "world");`

`text2 = text;`

I don't understand what is happening since the definition of the basic_memory_buffer class includes `basic_memory_buffer& operator=(basic_memory_buffer&& other)`

Any help is much appreciated.

**Comment by vitaut** [comment]
`memory_buffer` is a move-only class. You cannot copy it, only move:

```
text2 = std::move(text);
```
but normally you shouldn't do it either.

**Comment by krmrmethod** [comment]
Thank you for the response.
