### ISSUE TITLE
missing decimal point with scientific, precision=0, and showpoint

### ISSUE THREAD

**Issue by planet36** [fmtlib/fmt#1476]
With this format string `{:#.{}e}` and precision=0, there is a missing decimal point in the output using fmt::format compared to std::ostringstream.

Version info:
> FMT_VERSION=60102
> FMT_GCC_VERSION=902
> FMT_USE_GRISU=1

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/8b41362a0ae8d454b870cae86b22380f00157303. Thanks for reporting.
