### ISSUE TITLE
cmake file is using incorrect tools for checking if a stymbol exists

### ISSUE THREAD

**Issue by killerbot242** [fmtlib/fmt#1478]
When I cmake configure the library as stand-alone I get : 
-- Looking for strtod_l - found

However when I use it as a sub-project, it fails to find this.
-- Looking for strtod_l - not found 

I think the cause is due to using the incorrect set of tool/function.
include(CheckSymbolExists)  ==> check_symbol_exists()
=====> this happens within the C compiler, while we are targeting a C++ library here, right ?

When I adjust the CMakeLists.txt into : 
include(CheckCXXSymbolExists)
if (WIN32)
  check_cxx_symbol_exists(_strtod_l "${strtod_l_headers}" HAVE_STRTOD_L)
else ()
  check_cxx_symbol_exists(strtod_l "${strtod_l_headers}" HAVE_STRTOD_L)
endif ()

then it works as expected.

problems detected on linux, with gcc 7.4  (C++ standard did not matter, tried 11 and 17)

References : 
https://cmake.org/cmake/help/latest/module/CheckCXXSymbolExists.html
https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html

**Comment by killerbot242** [comment]
I was used from within a project that did not specify a language, something like this : 

project(fmt-sub)
add_subdirectory(fmt)

**Comment by vitaut** [comment]
`strtod_l` is a C symbol so `check_symbol_exists ` is the correct way to find it. This could be a an issue with specific version of CMake that you are using - I wasn't able to repro with CMake 3.11.1. In any case `strtod_l` is an optional symbol so it doesn't affect the main functionality of the library.

**Comment by killerbot242** [comment]
I will do some further experiments, and report back.
I used cmake 3.16.

**Comment by killerbot242** [comment]
I did some more experiments, see the attached zip file for an stripped down CMakeLists.txt, and the one I added on top.

The top CMakeLists.txt is : 
cmake_minimum_required(VERSION 3.1.0 FATAL_ERROR)
project(testfmt)
add_subdirectory(fmt-6.1.2)

And the reduced fmt one is:
cmake_minimum_required(VERSION 3.1.0)

# Use newer policies if available, up to most recent tested version of CMake.
if(${CMAKE_VERSION} VERSION_LESS 3.11)
  cmake_policy(VERSION ${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION})
else()
  cmake_policy(VERSION 3.11)
endif()

project(FMT CXX)

set(strtod_l_headers stdlib.h)

include(CheckSymbolExists)
check_symbol_exists(strtod_l "${strtod_l_headers}" HAVE_STRTOD_L)


with the following cmake invocation (on either level):cmake -D CMAKE_BUILD_TYPE=Release -H. -Bbuild/Release

In fmt directory this leads to:
-- The CXX compiler identification is GNU 7.4.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for strtod_l
-- Looking for strtod_l - found
-- Configuring done
-- Generating done

====> found
====> NOTE : no attempts made to look for C compiler

However the top project did not specify a language (so it will try bot C and C++ : from cmake manual : By default C and CXX are enabled if no language options are given.), then the outcome is:-- The C compiler identification is GNU 7.4.1
-- The CXX compiler identification is GNU 7.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Configuring done
-- Generating done

===> NOT found

Now something interesting, let's adjust in the fmt CMakeLists.txt the project line into:
project(FMT CXX C)
or even 
project(FMT)

then we get : 
-- The CXX compiler identification is GNU 7.4.1
-- The C compiler identification is GNU 7.4.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Configuring done
-- Generating done

===> NOT found

So the symbol is there, right, my system is not changing.

What does this gives on your system with the older cmake you have ?


If it is optional and does not affect the functionality then why do we search for it, and next to that having consistent behavior is nice (sub project or master project should make no difference),

Although it might be a C symbol, it needs to be looked for under the correct compiler, being here the C++ compiler, since that is the targeted one, and that is more or less what the cmake reference is saying about this symbol checking (see links in my original post).
==> I am not sure if that is the correct way to interpret this so I am surely not stating it is like that.

Curious on how it will turn out on your system .... ;-) 
[HAVE_STRTOD_L.tar.gz](https://github.com/fmtlib/fmt/files/3973632/HAVE_STRTOD_L.tar.gz)

**Comment by vitaut** [comment]
Looks like a CMake issue, so I recommend reporting there, otherwise I wouldn't bother investigating it any further.

**Comment by killerbot242** [comment]
ok will do so, what did your system gave as output (3.11.1)?

**Comment by codicodi** [comment]
I was able too reproduce this issue too and i think I pinned down the cause.
1. `check_symbol_exists` uses a C compiler if one was picked up already, otherwise it falls back to C++ compiler.
2. In glibc, `strtod_l` is not available by default when using C compiler


```
$ cat test.c 
#include <stdlib.h>

int main()
{
    strtod_l(NULL, NULL, 0);
    return 0;
}
$ gcc test.c
test.c: In function ‘main’:
test.c:5:5: warning: implicit declaration of function ‘strtod_l’; did you mean ‘strtoull’? [-Wimplicit-function-declaration]
    5 |     strtod_l(NULL, NULL, 0);
      |     ^~~~~~~~
      |     strtoull
```
but it is available with C++ compiler
```
$ g++ test.c
$ 
```
or when one requests GNU extensions
```
$ gcc -D_GNU_SOURCE test.c
$

```

**Comment by killerbot242** [comment]
so this means that my initial suggestion to use the cxx variants is correct, and it is not a cmake issue ?

**Comment by codicodi** [comment]
More like a glibc/gcc quirk. I guess cxx variant would work, yeah
