### ISSUE TITLE
when to use FMT_SAFE_DURATION_CAST

### ISSUE THREAD

**Issue by killerbot242** [fmtlib/fmt#1482]
Hi,
I was wondering when to define that, the CMakeLists.txt does : 
`if (FMT_SAFE_DURATION_CAST)
  target_compile_definitions(fmt PUBLIC FMT_SAFE_DURATION_CAST)
endif()

and the file using it : include/fmt/chrono.h
#ifndef FMT_SAFE_DURATION_CAST
#  define FMT_SAFE_DURATION_CAST 1
#endif
`

and then several 
#if FMT_SAFE_DURATION_CAST
#endif

and some test : 
test/fuzzing/README.md:cmake ..  -DFMT_SAFE_DURATION_CAST=On -DFMT_FUZZ=On -DFMT_FUZZ_LINKMAIN=Off -DFMT_FUZZ_LDFLAGS="-fsanitize=fuzzer"

made we wonder, is it needed after all ? And if need in some cases, then when to I need to specify which value of the cmake invocation ?

**Comment by vitaut** [comment]
You shouldn't use `FMT_SAFE_DURATION_CAST`.

**Comment by killerbot242** [comment]
thanks
