### ISSUE TITLE
fmt warnings clogging up console window.

### ISSUE THREAD

**Issue by Andy608** [fmtlib/fmt#1486]
Hi all,
I read another issue on here about warnings appearing in Visual Studio 2019 after compiling to source code and opening up the project. In the other issue, the answer said these warnings are just noise and can safely be ignored. Is there a way to turn off the warnings in Visual Studio? If not can these warnings be fixed in a future release? It's annoying having a wall of 25+ warnings in my error list from a project I don't have control over when I want to focus on warnings/errors from my own project.

If anyone knows a way to hide the warnings coming from the fmt include files I would greatly appreciate it!

![fmt_warnings](https://user-images.githubusercontent.com/7517525/71231880-aa53bf80-22bd-11ea-89b8-bc734038bd29.png)

The other issue I'm referencing is this one: https://github.com/fmtlib/fmt/issues/1131

Thanks,
Andy608

**Comment by vitaut** [comment]
These warnings are completely meaningless and I recommend complaining to Microsoft esp. since at least one of them on the screenshot actually points to their standard library =D. The first one is from spdlog, not {fmt} but the ones in {fmt} we could probably suppress until MS fixes this nonsense.

**Comment by Andy608** [comment]
Lol alright thanks for the quick reply. I'll just have to ignore the warnings for now.

**Comment by vitaut** [comment]
Changed the two cases that make sense to enum classes. In general, since these are not compiler warnings but code (style) analyzer "warnings" which are known to be of a poor quality in Visual C++, I recommend not using the code analyzer or running it only on your code.
