### ISSUE TITLE
improve cmake source consumption

### ISSUE THREAD

**Issue by killerbot242** [fmtlib/fmt#1487]
In order to improve being consumed as sources, in another cmake project, there are some things that can be improved.
One of the most important aspects is to ensure that the name of the targets we add, are "unique". In here I just focus on the library part, but the same could be argued for the "test targets".

So basically here we have two targets, for which we want to ensure an unique name:
- fmt
- fmt-header-only
it might be possible we end up in a cmake project where some other fmt library might exist, and then the build process breaks. Namespacing can help, but today cmake brings this to the table as aliases, so though we can nicely refer to the library when using it : fmt::fmt, during source consumption the "fmt" target remains in scope.

In several places, quoting here "Professional CMake : A Practical Guide", the following guideline is given: The main limitation is that CMake target names must be unique across the whole set of projects being combine... If projects are following a naming convention that uses a project specific prefix or something similar, then this limitation is fairly easy to avoid. For those projects that do use project specific target names. the name of the binary that is created can still be controller separately using the OUTPUT_NAME target property.
Quote from Chapter 27.

Now what would that mean for the fmt library.
In short the target name could switch from "fmt" to "fmt_fmt" (so the intended namespace prefixed with an underscore, as said just some convention). As a side effect the library outcome would now be called : libfmt_fmt.a, for that purpose that OUTPUT_NAME exists, so we can control it to become libfmt.a
In CMake language this is :
add_library(fmt_fmt ${FMT_SOURCES} ${FMT_HEADERS} README.rst ChangeLog.rst)
add_library(fmt::fmt ALIAS fmt_fmt)

and all other target_xxx_xxx methods of course refer to fmt_fmt.
set_target_properties(fmt_fmt PROPERTIES
  VERSION ${FMT_VERSION} SOVERSION ${CPACK_PACKAGE_VERSION_MAJOR}
  DEBUG_POSTFIX d
  OUTPUT_NAME fmt)

And tests and such also refer to fmt_fmt now.

And also care needs to be taken for the generated cmake config mode files to get the original fmt name in there.

So one could argue, that all that extra care is annoying and why bother, fair argument. But from the users perspective, we want to ensure he/she can nicely source consume out library.

Hopefully cmake will improve in future so that for example the namespace name can be used directly,internally, or other improvements.

Personally I think, the extra effort is worthwhile.

What do you think ?

If you want I can try to work it out in a PR, for the lib itself I already have something, I still need to adjust for the generate cmake configuration files.

**Comment by killerbot242** [comment]
another idea, more a matter of style :

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}
  "${CMAKE_CURRENT_SOURCE_DIR}/support/cmake")

basically this is appending to an existing (well it doesn't even have to exist) string,
maybe the following is more clear intent : 

string(APPEND CMAKE_MODULE_PATH  "${CMAKE_CURRENT_SOURCE_DIR}/support/cmake")

**Comment by vitaut** [comment]
Thanks for the suggestion but I don't think it's worth the trouble. The `fmt` name and prefix is unique enough in the same way the `fmt` namespace is.
