### ISSUE TITLE
support wstring?

### ISSUE THREAD

**Issue by mengdj** [fmtlib/fmt#1488]
support wstring? and like boost::format
boost::format("%s %d") fmt;
fmt%"1";
fmt%1;

**Comment by vitaut** [comment]
`wstring` is already supported:

```c++
std::wstring s = fmt::format(L"{}", 42);
```

**Comment by szdytom** [comment]
document this feature in a better place

**Comment by gurachan** [comment]
> ```c++
> std::wstring s = fmt::format(L"{}", 42);
> ```

says 
![image](https://user-images.githubusercontent.com/12135498/144695450-53454e0b-dedd-4039-b6ca-9f5c875ce5e4.png)

**Comment by OnurKader** [comment]
I think you need to `#include <fmt/xchar.h>`.

[godbolt](https://godbolt.org/z/cjbdscYjo)
