### ISSUE TITLE
Possibility to specify min and max number of digits after the decimal point

### ISSUE THREAD

**Issue by robinchrist** [fmtlib/fmt#1490]
I'm used to using the [Angular Decimal Pipe](https://angular.io/api/common/DecimalPipe).
With the Angular Decimal Pipe, you can specify minimum and maximum number of digits after the decimal point.

Is there already a way to specify this for the fixed point format?

**Comment by vitaut** [comment]
No, you can only specify exact number of digits with precision. Please see https://fmt.dev/latest/syntax.html.
