### ISSUE TITLE
fmt::format_to_n truncating_iterator may be used uninitialized

### ISSUE THREAD

**Issue by bwpow** [fmtlib/fmt#1491]
When compiling with gcc 8.2.1 with -Wall -Wextra and calling fmt::format_to_n, compiler warns about possibly uninitialized truncating_iterator. This is caused by property
`mutable typename traits::value_type blackhole_;`
in `class truncating_iterator<OutputIt, std::false_type>` in format.h.

Changing the line to (example) `mutable typename traits::value_type blackhole_ {0};` fixes the issue, but it should be probably initialized with proper value_type value.

**Comment by vitaut** [comment]
Could you post a complete godbolt example reproducing the warning?

**Comment by vitaut** [comment]
I was not able to reproduce this: https://godbolt.org/z/dh9um2.
