### ISSUE TITLE
MSVC warning

### ISSUE THREAD

**Issue by Naios** [fmtlib/fmt#1493]
b6e19e5953b

MSVC 2017 15.9.18 throws the following warning:

```
fmt\include\fmt\format-inl.h(1354): warning C4267: warning C4267: 'Argument': conversion from 'size_t' to 'DWORD', possible loss of data
```

https://github.com/fmtlib/fmt/blob/b6e19e5953bd049343ae37db162cffb2605215f1/include/fmt/format-inl.h#L1353-L1354

**Comment by chronoxor** [comment]
https://github.com/fmtlib/fmt/pull/1492
