### ISSUE TITLE
Add a possibility to specify min and max number of digits after the decimal point

### ISSUE THREAD

**Issue by robinchrist** [fmtlib/fmt#1494]
Follow up of #1490: Possibility to specify min and max number of digits after the decimal point 

This would be a great addition to fmt (see [Angular DecimalPipe](https://angular.io/api/common/DecimalPipe) for a description)

**Comment by vitaut** [comment]
Thanks for the suggestion. {fmt} implements Python's `str.format` and `printf` - other formats such as DecimalPipe are out of scope of the library. However, you can implement support for it yourself using the extension API.
