### ISSUE TITLE
Deprecated percentage formatting example

### ISSUE THREAD

**Issue by robinchrist** [fmtlib/fmt#1495]
From the documentation:

```
format("{0:f} or {0:%}", .635);
// Result: "0.635000 or 63.500000%"
```

Percentage formatting was deprecated some time ago and will be removed in the future.
The corresponding entry from the syntax section was removed in 4f4d876 (#1448), but the example is still present in the documentation (doc/syntax.rst)

**Comment by vitaut** [comment]
Good catch, removed the example as well.
