### ISSUE TITLE
Add support for std::filesystem::file_time_type 

### ISSUE THREAD

**Issue by stayprivate** [fmtlib/fmt#1497]
Very complicated to used fmt::format with std::filesystem::file_time_type.

**Comment by vitaut** [comment]
You can add a formatter for `std::filesystem::file_time_type` via the extension API (e.g. by delegating to `formatter<time_t>`): https://fmt.dev/latest/api.html#formatting-user-defined-types. It doesn't need to be in the core library.

**Comment by eliaskosunen** [comment]
`std::filesystem::file_time_type` is an alias to `std::chrono::time_point`, which arguably could be supported by `<fmt/chrono.h>` (only `std::chrono::duration` is supported at this time)
