### ISSUE TITLE
Add tests to format-test.cc

### ISSUE THREAD

**Issue by planet36** [fmtlib/fmt#1498]
Both `format("{:#.0f}", 0.01)` and `format("{:#.0f}", 0.5)` should return `"0."` (like std::ostringstream does), but they return `"0"` and `"0.."`, respectively

Please add some tests to test-format.cc like the following:
```
EXPECT_EQ("0.", format("{:#.0f}", 0.01));
EXPECT_EQ("0.", format("{:#.0f}", 0.5));
```

**Comment by vitaut** [comment]
Good catch, thanks! Fixed and added tests in https://github.com/fmtlib/fmt/commit/c85efef3126eabde097761ae080ca007ba46d926.
