### ISSUE TITLE
User-defined types formatter for printf

### ISSUE THREAD

**Issue by ludekvodicka** [fmtlib/fmt#1499]
I'm migrating from 4.x to 6.x and I didn't find a way how to correctly define printf formatter for user data types.

It seems that fmt::formatter works only for `fmt::format` but not for `fmt::sprintf`

```
template <>
struct fmt::formatter<USER_DATA_TYPE> {};
```

also, the original way via format_arg method doesn't work now:

```
void format_arg(fmt::BasicFormatter<char> &f, const char *&format_str/, const USERT_DATA_TYPE &s)
```

Can you please point me how to implement it now? Because of backward compatibility I'm not able to migrate all `%s,` to `{}` across all projects.

Thanks

**Comment by ludekvodicka** [comment]
Ok, I just found it in one of the unit test files (right after I posted the question, obviously ;-) ).


For printf() formatting it's necessary to define << operator:

```
template <typename Char>
std::basic_ostream<Char>& operator<<(std::basic_ostream<Char>& os,
	const  USER_DATA_TYPE& value)
{
      os << value.AsString();
	return os;
}
```

**Comment by vitaut** [comment]
In general, printf formatting is for migrating legacy code. If you want to format user-defined types I recommend using the format API i.e. `fmt::format`, `fmt::print`, etc.

**Comment by ludekvodicka** [comment]
I agree. New code already using fmt:format. But we have a lot of legacy code which still using prinf() semantic.

But the overloading operator << solved the problem.

Thanks for all replies!

**Comment by HeeMyung** [comment]
Hello. guys. I'm working on moving format from v4.xx to 8.1.1 which is up to date version atm.
I've found this issue said it can handle with custom data type for fmt::sprintf if we have operator<<. But I think this not work on my type.
Is this valid approaches for this version as well?
sorry for poor English.

**Comment by vitaut** [comment]
I would recommend using the format API instead of printf. The latter is mostly for legacy use cases.

**Comment by vadz** [comment]
Is the regression with not using `operator<<()` overloads for user-defined types in `fmt::sprintf()` any more intentional? I am not sure if this is really the case as I don't see anything about it in the changelog, but if it really is, could you please reconsider it?

We have migrated our code to `fmt` a few years ago but we didn't/couldn't update all the existing printf-like format strings, of course, so we used `fmt::sprintf()` for them, but now we can't update to fmt v10 because nothing compiles any longer.

**Comment by vitaut** [comment]
Extension API has never been designed to work with legacy `printf` API because the formats are incompatible. The default format "worked" by accident in some versions.

**Comment by vadz** [comment]
Thanks for the explanation, I had no idea it only worked by accident in fmt v7, it seemed pretty useful to use `%s` for printing any objects with a known conversion to string (via `ostringstream`).
