### ISSUE TITLE
Missing fmt::vformat_to for precompiled format strings?

### ISSUE THREAD

**Issue by ludekvodicka** [fmtlib/fmt#1501]
I'm not able to find any way how to use precompiled format strings together with fmt::format_args and buffer or iterator output.

there is no `fmt::vformat_to` or other similar function.

I'm looking for as fastest as the possible functions for converting ints/floats/... to strings.

**Comment by vitaut** [comment]
This is by design: it makes sense to use either type erasure or precompiled strings but not both.

For the fastest int and float formatting use `format_int` and `format_to` respectively.
