### ISSUE TITLE
fmt::vformat_to together with make_format_args returns invalid values

### ISSUE THREAD

**Issue by ludekvodicka** [fmtlib/fmt#1502]
Sorry for bothering again, but I found very strange bug.

The bug occurs only in release mode (not in debug mode) in VS2019, 32-bit, with latest fmt version (6.1.2).

	using custom_allocator = std::allocator<char>;

	using custom_memory_buffer =
		fmt::basic_memory_buffer<char, fmt::inline_buffer_size, custom_allocator>;

	using custom_string =
		std::basic_string<char, std::char_traits<char>, custom_allocator>;

	custom_allocator alloc;
	custom_memory_buffer buf(alloc);
	fmt::format_args argspack = fmt::make_format_args(42);

	fmt::vformat_to(buf, "{}", argspack);
	custom_string str(buf.data(), buf.size(), alloc);
	TEST_CHECK_EQUAL(str, "42");

This code fills "32"  to str. The value is still "32" no matter how many times I run the code. But, in case I change args to 0-10, the result value is "-2". It seems that it's not some memory garbage, but I'm not sure what these values mean.

Bug occurs only when make_format_args is used together with vformat_to is used. On the other side, this code is perfectly ok:

	using custom_allocator = std::allocator<char>;

	using custom_memory_buffer =
		fmt::basic_memory_buffer<char, fmt::inline_buffer_size, custom_allocator>;

	using custom_string =
		std::basic_string<char, std::char_traits<char>, custom_allocator>;

	custom_allocator alloc;
	custom_memory_buffer buf(alloc);
	fmt::format_to(buf, "{}", 42);
	custom_string str(buf.data(), buf.size(), alloc);
	TEST_CHECK_EQUAL(str, "42");

The Bug occurs also when constructing format_args from variadic param:

		template <typename ...Args>
		inline void test(fmt::string_view format_str, const Args& ... args)
		{
			fmt::printf_args argspack = fmt::make_printf_args(args...);
			vtest(str, format_str, argspack);
		}

**Comment by ludekvodicka** [comment]
Even more simplified test case with the same invalid behavior:

	using custom_memory_buffer = fmt::basic_memory_buffer<char>;
	using custom_string = std::basic_string<char>;

	custom_memory_buffer buf;
	fmt::format_args argspack = fmt::make_format_args(42);

	fmt::vformat_to(buf, "{}", argspack);
	custom_string str(buf.data(), buf.size());
	TEST_CHECK_EQUAL(str, "42");

**Comment by ludekvodicka** [comment]
The issue seems to be in make_format_args, not in the memory buffer. This use case is invalid too:

	fmt::format_args argspack = fmt::make_format_args(42);
	std::string str = fmt::vformat("{}", argspack);
	TEST_CHECK_EQUAL(str, "42");

All use cases still returning "32"

**Comment by ludekvodicka** [comment]
I'm still trying to find the root of the issue and it seems that the problem is directly in make_format_args:

https://www.dropbox.com/s/nt0iplnzrxdx47l/devenv_2019-12-29_22-59-08.png?dl=1

**Comment by ludekvodicka** [comment]
I did a few more tests now and the problem is in /O2 optimization settings. In case I turned it off (/Od), everything works ok. 

Also, I'm testing it on this fragment:

```
	fmt::format_args argspack = fmt::make_format_args((int)42);
	std::string str = fmt::vformat("{}", argspack);
```

and it depends on where you put it. If I put it directly to main(), it works always. If I put it inside the unit tests (tests based on boost tests), it's not working when /O2 is turned on.

Unfortunately, I'm not able to resolve it fully, because I don't fully understand the logic behind the argument packing.

**Comment by ludekvodicka** [comment]
And the last post about this issue....

I tried it on a completely new project on header-only mode with the still same result. So the issue is definitely inside the fmt library.

```
#include <iostream>

#define FMT_HEADER_ONLY 
#include <fmt/format.h>

int main()
{
	fmt::format_args argspack = fmt::make_format_args((int)42);
	std::string str = fmt::vformat("{}", argspack);
	std::cout << str;
	return 0;
}
```

result is:

7339188

Screenshot of project
https://www.dropbox.com/s/xn8awjbmpri8q39/2019-12-30_13-21-33.png?dl=0

Please let me know if and how to fix the issue or if you need any assistance.

**Comment by ludekvodicka** [comment]
I did a few more tests.

It seems that `{ fmt::make_printf_args(42) }` works ok, but not `{fmt::printf_args}` :


	fmt::format_args argspack = fmt::make_format_args((int)42);
	std::string str = fmt::vformat("{}", argspack);
	std::cout << "1=" << str << "\n";

	fmt::printf_args argspack2 = fmt::make_printf_args((int)42);
	str = fmt::vsprintf("%d", argspack2);
	std::cout << "2=" << str << "\n";

	fmt::printf_args argspack3 = fmt::make_printf_args(42);
	str = fmt::vsprintf("%d", {argspack3});
	std::cout << "3=" << str << "\n";

	auto argspack4 = fmt::make_printf_args(42);
	str = fmt::vsprintf("%d", {argspack4});
	std::cout << "4=" << str << "\n";

	str = fmt::vsprintf("%d", {fmt::make_printf_args(42)});
 	std::cout << "5=" << str << "\n";


```
1=2
2=2
3=2
4=42
5=42
```

**Comment by vitaut** [comment]
`make_format_args` returns `format_arg_store` (https://fmt.dev/latest/api.html#_CPPv2N3fmt16make_format_argsEDpRK4Args), not `format_args` so by converting it to `format_args` you are creating a temporary which is immediately destroyed leading to a dangling reference. Normally `make_format_args` should be used as follows:

```
vformat(format_str, make_format_args(...));
```

**Comment by ludekvodicka** [comment]
This explains a lot.

I found that format_arg_store<Context, Args...> is returned, but I thought it's handled by format_args.

The reason why I tried to solve it is that your recommended way doesn't work.

`vformat(format_str, make_format_args(...));`

returns

```
: error C2672: 'fmt::v6::vformat': no matching overloaded function found
: error C2784: 'std::basic_string<Char,std::char_traits<Char>,std::allocator<_Other>> fmt::v6::vformat(const S &,fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<Char>>,Char>>)': could not deduce template argument for 'fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<Char>>,Char>>' from 'fmt::v6::format_arg_store<fmt::v6::format_context,int>'

fmtlib32\include\fmt\core.h(1457): message : see declaration of 'fmt::v6::vformat'
```

The only way how to make it work is to do:

`vformat(format_str, { make_format_args(...) } );`

And this (wrongly) leaded me to try to `fmt::format_args argspack = fmt::make_format_args((int)42);`

**Comment by vitaut** [comment]
I clarified this in the docs: https://github.com/fmtlib/fmt/commit/455a7c0787617d748fb2307e3783f39942b463f6. Hopefully we'll get something like https://herbsutter.com/2018/09/20/lifetime-profile-v1-0-posted/ and will be able to automatically catch issues like this in the future.

**Comment by ludekvodicka** [comment]
Great, these lines in docs explain it perfectly.

Can I ask why it is necessary to encapsulate make_format_args with initializer_list {} ?

`vformat(format_str, { make_format_args(...) } );`

vs

`vformat(format_str, make_format_args(...) );

?

Thanks

**Comment by vitaut** [comment]
Braces may be necessary if there is a dependency on a template parameter (e.g. the parameter is `basic_format_args<Char>` where `Char` is a template parameter) because in this case implicit conversion from `format_arg_store` to `basic_format_args` won't happen automatically.

**Comment by vitaut** [comment]
As of https://github.com/fmtlib/fmt/commit/c8dd9cc99da8464fce62dfd1e4304c9e74587a47 braces around `make_format_args` are no longer necessary.

**Comment by iaanus** [comment]
Braces are still required for `vformat_to`, though. This code does not compile without them:
 
> ```c++
> using iterator = std::ostreambuf_iterator<char>;
> using context = fmt::basic_format_context<iterator, char>;
> fmt::vformat_to(iterator(std::cout), "Hello {}\n",
>                 fmt::make_format_args<context>("world"));
> ```

Tested for fmt 6.1.2 on Visual Studio 2019 (16.4.5 with /std:c++latest) and on gcc 9.3 (https://godbolt.org/z/tARv97).

**Comment by vitaut** [comment]
> Braces are still required for vformat_to

Not in `master` or 6.2: https://godbolt.org/z/d7C_k7
