### ISSUE TITLE
The format_to functions claim OutputIterator support but actually expect a back_insert_iterator

### ISSUE THREAD

**Issue by mikezackles** [fmtlib/fmt#1506]
Thanks for a useful library!

As best I can tell, both `container_type` and `operator=` are specific to [back_insert_iterator](https://en.cppreference.com/w/cpp/iterator/back_insert_iterator), and not a part of [OutputIterator](https://en.cppreference.com/w/cpp/named_req/OutputIterator). So these functions don't actually support output iterators.

It seems like either the code needs to be modified to use just the OutputIterator operations or the documentation should be updated.

**Comment by mikezackles** [comment]
(Note that I ran into this using `format_to_n`. Perhaps it is just specific to `internal::truncating_iterator`?

**Comment by vitaut** [comment]
`format_to_n` supports iterators other than `back_insert_iterator`, e.g. 

```c++
#include <fmt/format.h>

int main() {
  char buf[10];
  fmt::format_to_n(buf, 10, "{}", 42);
}
```

https://godbolt.org/z/Pg_aQ_

**Comment by mikezackles** [comment]
My mistake, I should've given an example: https://godbolt.org/z/_edHPs

**Comment by vitaut** [comment]
Thanks for the example. Should be fixed in https://github.com/fmtlib/fmt/commit/9e3f3e8cff6f10b97e78920f9bf69450b706d635.

**Comment by mikezackles** [comment]
Awesome, thank you!
