### ISSUE TITLE
Helper function to optionally validate number of arguments?

### ISSUE THREAD

**Issue by tagsemb** [fmtlib/fmt#1507]
I am aware of the conscious decision to not check for extra arguments as mentioned in #492.

However, I would very much like a wrapper function where I can get a compile-time error on too many arguments passed to format(), as it is a common source of bugs in my experience, and I've yet to encounter a need for allowing extra arguments.

Is it possible to implement a function such as for example fmt::aformat() that wraps fmt::format() in addition to checking for extra arguments?

If this has no hope of making it into the library, does anyone have any pointers on how I could write such a function?

**Comment by vitaut** [comment]
There are no plans to provide this functionality in {fmt}. If you want to do it yourself, a good place to start is `internal::vformat_to`: https://github.com/fmtlib/fmt/blob/cd0b3f9695c2199979e04438472bdb3521374408/include/fmt/format.h#L3091-L3100

You'll have to implement a similar function with extra checks in your `format_handler`.
