### ISSUE TITLE
MSVC warning

### ISSUE THREAD

**Issue by torsten48** [fmtlib/fmt#1511]
fmt version 6.1.2, with VS2017 (MSVC 19.16) shows the following warning:

> fmt/format.h(311): warning C4574: '_SECURE_SCL' is defined to be '0': did you mean to use '#if _SECURE_SCL' ?

**Comment by vitaut** [comment]
Can be suppressed by changing `#ifdef` to `#if defined(_SECURE_SCL) && _SECURE_SCL`. Could you submit a PR?
