### ISSUE TITLE
CMake Error: "No known features for CXX compiler "GNU"" when targeting Zephyr OS (ARM GCC)

### ISSUE THREAD

**Issue by RonAmihai** [fmtlib/fmt#1514]
I'm trying to use fmtlib with [Zephyr RTOS](https://github.com/zephyrproject-rtos/zephyr) application. 
My environment is MSYS2 (Mingw W64) with ARM GCC compiler (arm-none-eabi, GCC 9.2.1) 

Zephyr's C++ STD support is enabled of course.

I'm adding the fmtlib manually using `add_subdirectory`. 
However, CMake fails to link `fmt::fmt` to the project's target, with the following output: 

```
C:\Dev\CMake\bin\cmake.exe -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=C:/Dev/Toolchains/ARM-EMB/bin/arm-none-eabi-gcc.exe -DCMAKE_CXX_COMPILER=C:/Dev/Toolchains/ARM-EMB/bin/arm-none-eabi-g++.exe -GNinja -DBOARD=nucleo_f091rc C:\Users\ronam\Documents\Projects\hello_world
Zephyr version: 2.1.0
-- Found PythonInterp: C:/Dev/Python/3.8/python.exe (found suitable version "3.8.1", minimum required is "3.4") 
-- git describe failed: fatal: not a git repository (or any of the parent directories): .git;
   BUILD_VERSION is left undefined
-- Selected BOARD nucleo_f091rc
-- Found west: C:/Dev/Python/3.8/Scripts/west.exe (found suitable version "0.6.3", minimum required is "0.6.0")
-- Loading C:/Dev/Frameworks/Zephyr/boards/arm/nucleo_f091rc/nucleo_f091rc.dts as base
Devicetree configuration written to C:/Users/ronam/Documents/Projects/hello_world/cmake-build-debug/zephyr/include/generated/generated_dts_board.conf
Parsing Kconfig tree in C:/Dev/Frameworks/Zephyr/Kconfig
Loaded configuration 'C:/Users/ronam/Documents/Projects/hello_world/cmake-build-debug/zephyr/.config'
No change to 'C:/Users/ronam/Documents/Projects/hello_world/cmake-build-debug/zephyr/.config'
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- The ASM compiler identification is GNU
-- Found assembler: C:/Dev/Toolchains/ARM-EMB/bin/arm-none-eabi-gcc.exe
-- Cache files will be written to: C:\Users\ronam\AppData\Local/.cache/zephyr
-- Version: 6.1.2
-- Build type: Debug
-- CXX_STANDARD: 17
-- Performing Test has_std_17_flag
-- Performing Test has_std_17_flag - Success
-- Performing Test has_std_1z_flag
-- Performing Test has_std_1z_flag - Success
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES - Failed
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Failed
-- Performing Test FMT_HAS_VARIANT
-- Performing Test FMT_HAS_VARIANT - Failed
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Configuring done
CMake Error in CMakeLists.txt:
  No known features for CXX compiler

  "GNU"

  version 9.2.1.


CMake Generate step failed.  Build files cannot be regenerated correctly.

[Failed to reload]
```

I've checked the library on normal app targeting Mingw-W64-GCC (9.2.1) or CLang (9.0.0) in my env (also with usage of `add_subdirectory`), it works fine there.

Am I missing something here?

**Comment by vitaut** [comment]
I recommend asking in the CMake mailing list what may be causing "No known features for CXX compiler" error.

As a workaround you could try setting `FMT_REQUIRED_FEATURES` to empty in https://github.com/fmtlib/fmt/blob/cd0b3f9695c2199979e04438472bdb3521374408/CMakeLists.txt#L72

**Comment by RonAmihai** [comment]
> I recommend asking in the CMake mailing list what may be causing "No known features for CXX compiler" error.
> 
> As a workaround you could try setting `FMT_REQUIRED_FEATURES` to empty in
> 
> https://github.com/fmtlib/fmt/blob/cd0b3f9695c2199979e04438472bdb3521374408/CMakeLists.txt#L72

Setting the above CMake variable does solve the above issue, but does not seem to compile. 

Anyways, I've noticed that usage of the libraries bumps up the flash usage of my microcontroller controller to about 70% (!).
I guess fmtlib includes `<iostream>` usage internally and that's the reason for that.

So using it now on those embedded targets is not realistic.

But thank you for helping, in the future I would like to contribute (optional) optimization feature to solve this issue though.

**Comment by vitaut** [comment]
iostream support is optional: if you don't use `fmt/ostream.h`, it won't be compiled in. I also recommend enabling LTO.

**Comment by YaelBx** [comment]
Hi @vitaut,
I am trying also to use fmt library in some C++ classes in Zephyr.
No compilation issues, but seems like my Zephyr program freezes when trying to using it.
In the end did you manage to make it work ?
