### ISSUE TITLE
fmt/chrono.h Unused Template Warning

### ISSUE THREAD

**Issue by jwillikers** [fmtlib/fmt#1524]
The `fmt/chrono.h` header produces an `unused-template` warning on clang for the function `format_chrono_duration_unit`. This is probably due to the templated function being static, from what I can tell.

**Comment by vitaut** [comment]
Thanks for reporting. It shouldn't really be static - could you submit a PR?

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/9bd9738da024a12f79a72e664aaeaf2004d2e640.

**Comment by jwillikers** [comment]
@vitaut Thanks! I can totally submit a PR next time. 👍👍
