### ISSUE TITLE
slow compilation times when including fmt/format.h

### ISSUE THREAD

**Issue by ankut** [fmtlib/fmt#1537]
I am seeing singnificantly slower compilation times when including fmt/format.h with a single trivial fmt::format(“hello {}”, 5) use, as compared to fmt/core.h. However, since i would like to do FMT_STRING() validation at compile time, i am forced to include the format.h header. The compilation time goes up regardless of using the macro. Is there any way that i could have compile time format string checking, without the steep compilation time penalty? I tried on several recent gcc versions and saw the same compilation time hit. Any guidance on this is appreciated.

**Comment by vitaut** [comment]
Compile-time checks require all of the format string parsing logic from `fmt/format.h`. You could speed up your builds by using precompiled headers or by only enabling checks in CI or some other build mode, e.g.

```c++
// helper header:
#if CI
# include <fmt/format.h>
#else
# include <fmt/core.h>
# define FMT_STRING(s) s
#endif
```

**Comment by marlowa** [comment]
Precompiled headers? How will that work on linux/g++?

**Comment by vitaut** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html. Note that this issue is somewhat outdated since `consteval`-based format string compilation doesn't require including `fmt/format.h`.
