### ISSUE TITLE
Link of "Implementation of C++20 std::format" is dead.

### ISSUE THREAD

**Issue by mudream4869** [fmtlib/fmt#1540]
```
* Implementation of `C++20 std::format <https://fmt.dev/Text%20Formatting.html>`__.
```
The link is dead. Should it be [https://en.cppreference.com/w/cpp/utility/format](https://en.cppreference.com/w/cpp/utility/format) ?

**Comment by vitaut** [comment]
Fixed, thanks for catching this!
