### ISSUE TITLE
Respect Parent Project's use of CMAKE_RUNTIME_OUTPUT_DIRECTORY

### ISSUE THREAD

**Issue by jwillikers** [fmtlib/fmt#1545]
The use of `CMAKE_RUNTIME_OUTPUT_DIRECTORY` in the CMakeLists.txt file does not allow parent projects to override it.
Would it be possible to only set that variable if it is not already set?
The CMake code to accomplish follows below.
```cmake
if(NOT CMAKE_RUNTIME_OUTPUT_DIRECTORY)
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
endif()
```

**Comment by jwillikers** [comment]
You might also want to use [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html).
```cmake
if(NOT CMAKE_RUNTIME_OUTPUT_DIRECTORY)
  include(GNUInstallDirs)
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR})
endif()
```

**Comment by vitaut** [comment]
> Would it be possible to only set that variable if it is not already set?

Sure, a PR is welcome.

> You might also want to use GNUInstallDirs.

I suggest keeping `bin` for simplicity.

**Comment by jwillikers** [comment]
I'll get a PR ready.
