### ISSUE TITLE
 undefined reference to `fmt::v6::internal::is_output_iterator<char*>::value

### ISSUE THREAD

**Issue by Boddlnagg** [fmtlib/fmt#1548]
In my specific setup (I have integrated fmtlib and its unit tests into a custom build system), I'm getting the following linker error in the unit tests:
```
fmt/test/format-test.cc:216: undefined reference to `fmt::v6::internal::is_output_iterator<char*>::value'
```

The compiler is GCC8. On Windows it works.

According to https://stackoverflow.com/a/30277639 using `static const bool value = ...` is probably not a good idea. But it might also be me doing something wrong ...

**Comment by vitaut** [comment]
Does https://github.com/fmtlib/fmt/commit/24924128e32fba8011037e21454426458f99d13b fix the issue?

**Comment by vitaut** [comment]
Should be fixed now but feel free to reopen if you still see the issue. Thanks for reporting!

**Comment by Boddlnagg** [comment]
I can confirm that it is now indeed fixed. Thanks!
