### ISSUE TITLE
custom ostream formatter vs namespace vs clang

### ISSUE THREAD

**Issue by anordal** [fmtlib/fmt#1550]
I have basically https://github.com/fmtlib/fmt/issues/952#issuecomment-456186620 with a namespace:

```
#include <fmt/ostream.h>
#include <iostream>

namespace something{ struct Custom {}; }

std::ostream& operator<<(std::ostream& os, const something::Custom&)
{
	return os << "Ok";
}

int main()
{
	// Compiles with Gcc and Clang
	std::cout << something::Custom() << '\n';

	// Compiles with Gcc, but not Clang
	fmt::print("{}\n", something::Custom());
}
```

I don't know if this is a compiler bug, but it seems that clang + libfmt = `operator<<` not found.

The absurd thing is that it compiles (with both compilers, also the non-libfmt example) if I move `operator<<` into the namespace. That is not supposed to compile (if my understanding of argument dependent lookup is correct) – I learned this from the exact opposite experience.

Libfmt tested:
* libfmt 6.1.2-1.2 (OpenSuse package)
* latest git (dc22360)

Compilers tested:
* g++ 9.2.1
* g++ 7.4.1
* clang++ 9.0.0
* clang++ 6.0.1

**Comment by vitaut** [comment]
I think clang is correct here because `operator<<` should be defined in the `something` namespace for ADL to work.

**Comment by anordal** [comment]
I agree, after finding back my "exact opposite experience". That was with [a type alias in the namespace](https://stackoverflow.com/questions/53784120/can-i-namespace-the-ostream-operator). I forgot that distinction.
