### ISSUE TITLE
Rounding floats with fixed precision after decimal point, but no trailing zeros

### ISSUE THREAD

**Issue by dalboris** [fmtlib/fmt#1551]
In my application, I want to format floats/doubles with the following desiderata:
1. they never use the scientific notation
2. they are rounded with a fixed number of decimals (let's say, 8 decimals)
3. trailing zeros are removed

I obviously can't use the `e`, `g`, and `none` format, otherwise `0.00001` becomes `1e-05`.

The natural choice is `{:.8f}`, that is, fixed precision, but unfortunately, it keeps trailing zeros: 

```
fmt::print("{:.8f}", 0.00001);  // => "0.00001000"  (I'd like "0.00001")
```

The above behavior of {fmt} is the same as  `std::ostringstream o; o << std::fixed << std::setprecision(8) << x`, and the same as  `sprintf("%.8f", x)`, so it makes sense. Currently, I use ostringstream and manually remove the trailing zeros as a post-processing step.

Is there a better way using {fmt} which wouldn't require the post-processing step? Maybe with a custom formatter? If not, would it make sense to add such feature to {fmt}?

Thank you!

**Comment by vitaut** [comment]
There is no built-in way to drop trailing zeros in fixed mode. It seems easy to do as a postprocessing step as you do already and I don't think it needs to be in the core library.

**Comment by dalboris** [comment]
Thanks for the answer, fair enough. Although for completeness, the post-processing step is less trivial than it seems, as is always the case with floating points. For example:

```
fmt::format("{:.8f}", 1000000000000.2); // => "1000000000000.19995117"
```

I've actually spent to time to finally fix a few of those corner cases today, while porting to {fmt}. My post-processing does multiple passes:

1. Read from the left up to `n` significant digits, where `n = numeric_limits<T>::digits10` (6 for float, 15 for double)

```
1000000000000.19995117
              ^
          15th significant digit
```

2. If you do reach a n-th significant digit (often, you reach the end of the string before), then round at this position (reading the (n+1)-th significant digit if any to know whether to round up of down), propagating carry as required. This removes all the "garbage digits" which are meaningless

```
1000000000000.20000000
```

3. Remove trailing zeros

```
1000000000000.2
```

(note: in this case, it is the same result as if directly calling `fmt::format("{}", 1000000000000.2)`)

If you're curious, the code is [here](https://github.com/vgc/vgc/blob/73b8e62f6fd5ea7e0076be61d8ff3e48816feb45/libs/vgc/core/stringutil.h#L276) together with some [test cases](https://github.com/vgc/vgc/blob/73b8e62f6fd5ea7e0076be61d8ff3e48816feb45/libs/vgc/core/tests/test_stringutil.cpp#L94). It's nowhere near the complexity of implementing a dtoa function from scratch, but it isn't completely trivial either, and there are a few corner cases not to miss (e.g.,  handling the minus sign if the carry propagate to an extra leading digit, handling nan/inf, jumping over the decimal point, not removing trailing zeros if there aren't any decimal point, etc.).

With hindsight, I feel that it might have actually been easier and more accurate to implement this behavior by post-processing the output of the forced scientific notation instead. In particular, while the choice of rounding at the `numeric_limits<T>::digits10`th significant digit is safe and give predictable, non-surprising results, it does lose precision on cases where one or two extra digits would actually still round-trip. For example, the largest odd integer that can be exactly represented by a float is `16777215`, but my code would round it to `16777200`.

However, I'm not sure if there is an "automatic precision" mode for the forced scientific notation, like for the default mode? It seems to use a precision of 6 by default, but if I specify the precision myself, I end up with the same issues as my current post-processing (I have to decide myself where to round, instead of relying of a smarter dedicated library for that). Perhaps the best is actually to post-process the default mode `"{}"`, and check whether we get a scientific notation or not.

Anyway, I'm always surprised by how hard it is to actually format numbers with the desiderata in my OP, which I believe is the "most intuitive" formatting which should be the default for most user-facing values in a user interface:
1. You don't want to scare users off with a scientific notation
2. You want a max number of decimals (application-dependent, possibly a user preference), because smaller values are irrelevant for the user (e.g., less than 0.01mm in a CAD application)
3. But you don't want trailing zeros (shortest representation is better)
4. And you don't want meaningless garbage digits either, outside of the precision range of the floating point

I really wish there was an easy way to achieve that, as it is my most common use case. Implementing it myself means I can't use convenient code such as:

```
fmt::format("The values are {:??} and {:??}.", x, y);
```

I have instead to build the string incrementally, for example:

```
std::ostringstream o;
o << "The values are " << my_format(x) << " and " << my_format(y) << ".";
```

Loosing all the elegance of the {fmt} library. In fact, I'm in fact implementing my own stream classes just because of this, so I can do the following instead. But ideally it'd be better not to have to go to such length.

```
MyStringWriter s;
s << "The values are " << x << " and " << y << ".";
```

**Comment by vitaut** [comment]
> However, I'm not sure if there is an "automatic precision" mode for the forced scientific notation, like for the default mode?

No, there is no such mode.

If you implemented one then you can plug it in via the usual [extension API](https://fmt.dev/latest/api.html#formatting-user-defined-types):

```c++
fmt::format("The values are {} and {}.", myscientific(x), myscientific(y));
```

**Comment by dalboris** [comment]
That's a neat idea, thanks. There didn't seem to be a way to define custom formatters for built-in types, but what you're suggesting is to define a class `myscientific` wrapping a built-in type, then writing a custom formatter for that?

That makes it also easier to implement my own `vgc::format`, automatically wrapping all floats and doubles, but forwarding all other args as is to `fmt::format`. Would that make sense?

**Comment by dalboris** [comment]
Sorry, it appears I was blind, this is awesome:

https://fmt.dev/latest/api.html#custom-formatting-of-built-in-types

**Comment by vitaut** [comment]
I'd recommend using the extension API which is more stable (and compatible with future `std::format`) instead of custom formatting of built-in types. The latter is there mostly for legacy reasons.

**Comment by dalboris** [comment]
Ok, thanks for clarifying. At least I know my options better, I'll see with more practice what seems to suit my use case best. I'm actually thinking it might be best to implement a custom `my_format(settings, format_str, args...)`, mimicking the interface of `fmt::format(locale, format_str, args...)`, but using an application-dependent MyFormatSettings object rather than std::locale, for more fine-grained control over number formatting, word-wrap, indentation settings, etc., which could be user preferences (use case: export as XML, JSON, or similar).

**Comment by elfprince13** [comment]
@dalboris - any chance of open-sourcing your solution?

**Comment by dalboris** [comment]
@elfprince13 It's already open-sourced :) The license is Apache 2.0, I'm the sole copyright owner. Here's a permalink to my current solution, it only uses C++11 :

https://github.com/vgc/vgc/blob/ae0617ebaf7a591c0c0b25e8f4a5818edb8d1838/libs/vgc/core/format.h#L295

The function is:

```
template<typename OStream, typename FloatType>
typename std::enable_if<std::is_floating_point<FloatType>::value>::type
write(OStream& out, FloatType x)
{
    ...
}
```

It's a template specialization of a generic `write(out, x)` function. The template parameter `OStream` can be any type implementing the following functions, with the same semantics as std::ostream:

```
OStream& put(char c);
OStream& write(const char* s, std::streamsize count);
```

Note that in this implementation, the desired "max number of digits after the decimal point" is a built-in value: 12. Just change the following line to choose another value:

```
fmt::format_to(b, " {:.12f}", x);
```

I tested this function quite extensively (see [here](https://github.com/vgc/vgc/blob/ae0617ebaf7a591c0c0b25e8f4a5818edb8d1838/libs/vgc/core/tests/test_format.cpp)), but I don't guarantee that there are no bugs.

Unfortunately, I didn't take the time yet to implement a solution that integrate better with fmt, using the extension API.

**Comment by elfprince13** [comment]
That's super helpful, thanks!
