### ISSUE TITLE
to_string with custom types

### ISSUE THREAD

**Issue by andrei-dragusanu** [fmtlib/fmt#1552]
The documentation for `fmt::to_string` states that it does not support user-defined types with custom formatters, however its current implementation appears that it does:
1. Is this a documentation error?
2. Should it forward it's arguments instead (`T&&` value and `std::forward`), so you can also do something like this:
```c++
fmt::to_string(fmt::join(fields, "|")); // currently static assert failure: views should not be passed as lvalues
```
_PS: how about a `fmt::join_to_string(range, separator)`?_

**Comment by vitaut** [comment]
> Is this a documentation error?

Yes. Thanks for catching this.

`to_string` is mostly a replacement for `std::to_string`. I don't think there is much value in adding support for `join` there or adding other APIs which are easily expressed via `format`.

**Comment by vitaut** [comment]
Updated the docs in https://github.com/fmtlib/fmt/commit/3bafd0749b8d1493bc728bd823b8a68297fd6fa4.
