### ISSUE TITLE
String formatter that escapes control characters

### ISSUE THREAD

**Issue by robinchrist** [fmtlib/fmt#1555]
Hi,

I think it would be really useful if there was a string formatter which automatically escapes control sequences.

e.g.
```
std::string_view testSv = "bla\nfoo!\tc++\0is\aamazing!"sv;
auto str = fmt::format("This could be a log message: {:S}", testSv);
std::cout << "str: " << str << std::endl;
```
should give
`str: This could be a log message: bla\nfoo!\tc++\0is\aamazing!`
instead of
```
str: This could be a log message: bla
foo!    c++isamazing!
```

Note that I only used `:S` as a format specifier for the sake of demonstration, i.e. to show that the default formatter should behave as before.

**Comment by vitaut** [comment]
It should be pretty straightforward to write a function to escape a string and use it with {fmt}:

```c++
auto str = fmt::format("This could be a log message: {}", escaped(testSv));
```

**Comment by robinchrist** [comment]
...with an unnecessary allocation, string instantiation, deallocation and destructor call, even though `testSv` is a string_view?

**Comment by vitaut** [comment]
`escaped` doesn't have to return `std::string`. You can use small buffer optimization if perf is critical.

**Comment by robinchrist** [comment]
I'm talking about the exact opposite: Large buffers.

Assuming that small buffer optimisation is automatically used anyway, this shouldn't be a problem.

**Comment by vitaut** [comment]
Sure, you can optimize `escaped` as you like since it doesn't have to return `std::string`.

**Comment by foonathan** [comment]
In particular, `escaped` doesn't need to do any work. It's sole purpose is changing the type, so you can customize the formatter for the return type, which then escapes the string.

**Comment by pkubanek** [comment]
There is now ? - fmt::format("{:?}", "test\n") - available.
