### ISSUE TITLE
fatal error C1001: An internal error has occurred in the compiler. visual studio 2019 with fmtlib chrono.h

### ISSUE THREAD

**Issue by cppdev-123** [fmtlib/fmt#1556]
see here
https://developercommunity.visualstudio.com/content/problem/920243/fatal-error-c1001-an-internal-error-has-occurred-i-49.html

**Comment by vitaut** [comment]
Thanks for reporting. Closing since it's a bug in MSVC not {fmt}, but a PR with a workaround would be welcome.
