### ISSUE TITLE
code bloat: float writing code built but not used

### ISSUE THREAD

**Issue by TojNALvViV** [fmtlib/fmt#1557]
I'm trying to use fmtlib in an embedded environment (Arm Cortex M4 w/64kB of code space). Adding a single use of fmtlib (fmt::format("the answer is {}", 42)), about 30kB of code is generated. This is after FMT_STATIC_THOUSANDS_SEPARATOR is used (otherwise over 100kB of code is generated) and appropriately configured toolchains.

Looking into it, I see that a large amount of code related to formatting floating point numbers is included, despite it not being used. Does anyone know why this might be?

**Comment by vitaut** [comment]
This is expected. `fmt::format`, as `printf`, needs to know how to format all built-in types including floating-point numbers.

**Comment by TojNALvViV** [comment]
While I understand that some hypothetical compiler might come along and prove to itself that not all built-in types are actually formatted in some given program, wouldn't it be better for fmt::format to internally "dispatch", based on the types of arguments passed to it, to internal variants that each know how to format some subset of the available types?

**Comment by vitaut** [comment]
In general it's not possible because format strings can be provided at runtime. However, it will be possible with format string compilation which is currently WIP.

**Comment by vitaut** [comment]
#1590 allows disabling floating point support.
