### ISSUE TITLE
There is a three times faster double-to-string implementation

### ISSUE THREAD

**Issue by erthink** [fmtlib/fmt#1559]
https://erthink.github.io/dtoa-benchmark/

For now it generates only a raw ASCII representation, e.g. -22250738585072014e-324 without dot and '\0' at the end (since that was enough for my purposes). If you are interested, I am ready to refine this code for use in `{fmt}`. In this case, I would like to hear exactly what is needed.

Regards,
Leonid.

------

![dtoa-benchmark](https://github.com/erthink/dtoa-benchmark/raw/master/results/filtered_randomdigit_i7-7820@2.90_linux-x86_64-gcc9.2_randomdigit_time.png)

These results are obtained on i7-7820HQ CPU @ 2.90GHz, GNU C++ 9.2.1, x86-64 Linux.
The speedup is based on `sprintf`'s _Sum_ values.

Function      |  Min ns |  RMS ns  |  Max ns |   Sum ns  | Speedup |
:-------------|--------:|---------:|--------:|----------:|--------:|
null          |     1.2 |    1.200 |     1.2 |      20.4 |   N/A   |
erthink       |    21.4 |   33.381 |    43.9 |     558.1 | ×23.5   |
ryu           |    35.3 |   50.011 |    65.7 |     835.4 | ×15.7   |
emyg          |    38.1 |   58.310 |    69.7 |     983.2 | ×13.3   |
milo          |    37.8 |   59.819 |    71.8 |    1007.7 | ×13.0   |
floaxie       |    24.5 |   68.028 |    92.4 |    1089.8 | ×12.0   |
fmt           |    75.3 |  101.532 |   130.8 |    1712.2 | ×7.7    |
doubleconv    |    69.7 |  103.070 |   134.0 |    1731.4 | ×7.6    |
grisu2        |   101.6 |  119.538 |   137.8 |    2024.3 | ×6.5    |
fpconv        |   102.6 |  145.437 |   167.5 |    2454.2 | ×5.3    |
stb           |   188.8 |  191.082 |   198.6 |    3248.1 | ×4.0    |
sprintf       |   700.1 |  772.833 |   827.7 |   13119.8 | ×1.0    |
ostrstream    |  1058.4 | 1133.081 |  1187.4 |   19250.5 | ×0.7    |
ostringstream |  1110.9 | 1196.817 |  1267.8 |   20327.0 | ×0.6    |

**Comment by erthink** [comment]
Direct links:
  - implementation source = https://github.com/erthink/erthink/blob/master/erthink_d2a.h
  - tests = https://github.com/erthink/erthink/blob/master/test/d2a.cxx

**Comment by vitaut** [comment]
Very interesting, thanks for sharing. A PR to improve the {fmt}'s implementation (which is located [here](https://github.com/fmtlib/fmt/blob/master/include/fmt/format-inl.h#L1039)) would be welcome. Note that {fmt} implements Grisu3, not Grisu2, because the latter doesn't provide the shortness guarantee.
