### ISSUE TITLE
Help integrating {fmt} into CMake 

### ISSUE THREAD

**Issue by cristianadam** [fmtlib/fmt#1562]
CMake has issue [#19671 Bundle and use fmt in CMake code](https://gitlab.kitware.com/cmake/cmake/issues/19671) which I'm trying to fix with the MR [#4392 fmt: Add version 6.1.2](https://gitlab.kitware.com/cmake/cmake/merge_requests/4392).

The quick test bot complained about an _include what you use_ [warning](https://open.cdash.org/viewBuildError.php?type=1&buildid=6374124), which got disabled as {fmt} 3rd party code to CMake is.

The merge request went into staging, and the nightly build picked up quite some [warnings / errors](https://open.cdash.org/index.php?project=CMake&date=2020-02-26). These errors come from compilers like Intel Compiler, SunCC, AIX XLClang. 

The nightly builds suite also has older GCC versions like 4.8, which issue warnings.

How should I proceed in integrating {fmt} into CMake?

**Comment by vitaut** [comment]
Thanks for reporting. The constexpr/assert issue on old clang should be worked around in https://github.com/fmtlib/fmt/commit/b2d3a86ec0865c2771191d674e85d31d22d5b1da. I'm not entirely sure what "Multiple declaration ..." errors mean in Solaris build.

**Comment by vitaut** [comment]
I can look into the remaining issues but PRs are welcome too.

**Comment by vitaut** [comment]
Error of the form
```
/home/kitware/Dashboards/CMake/Builds/Intel 17.0.3/CMake/Utilities/cmfmt/include/fmt/core.h(1389): error: expression must have a constant value
    static_assert(all_true<(!std::is_base_of<view, remove_reference_t<Args>>() ||
                            ^
```
should be already worked around in master (they also only occurred on old compilers).

**Comment by vitaut** [comment]
The issue with `normalize` tentatively fixed in https://github.com/fmtlib/fmt/commit/bed134a4aad3de93b2ba0e1a59a51b662243b7e8.

**Comment by cristianadam** [comment]
I've added the two fixes in [MR4392](https://gitlab.kitware.com/cmake/cmake/merge_requests/4392) and the nightly build looks a bit [better](https://open.cdash.org/index.php?project=CMake&date=2020-02-29).

**Comment by vitaut** [comment]
The fix for

```
/home/kitware/Dashboards/CMake/Builds/Intel 16.0.0/CMake/Utilities/cmfmt/include/fmt/core.h(1385): error: expression must have a constant value
    static_assert(all_true<(!std::is_base_of<view, remove_reference_t<Args>>() ||
                            ^
```

can be backported from `master` by replacing

```c++
std::is_base_of<view, remove_reference_t<Args>>()
```
with 
```c++
std::is_base_of<view, remove_reference_t<Args>>::value
```

See https://github.com/fmtlib/fmt/blob/58e6c84f5a3258a9cf9cd465fd9b1a9423d62f8e/include/fmt/core.h#L1460

and similarly for other errors of the same form replace `foo()` with `foo::value`.

**Comment by cristianadam** [comment]
[MR 4392](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4392) got closed because of the Solaris compiler. Bummer.

**Comment by cristianadam** [comment]
https://www.oracle.com/tools/developerstudio/ seems to be available at no cost. From https://docs.oracle.com/cd/E77782_01/pdf/E77789.pdf it looks they package GCC.

**Comment by vitaut** [comment]
Too bad. I'm not sure how to workaround broken SFINAE on the Solaris compiler but suggestions/PRs are welcome.
