### ISSUE TITLE
Help with custom type formatter

### ISSUE THREAD

**Issue by kc9jud** [fmtlib/fmt#1565]
I'm trying to write a parser/formatter for a custom numeric type. I've looked at the documentation in the API reference (https://fmt.dev/latest/api.html?highlight=tuple#formatting-user-defined-types), but I want to avoid re-implementing the full formatting language.

I have a type HalfInt (defined in https://github.com/nd-nuclear-theory/am/blob/master/halfint.h) which stores (obviously) half-integers. I would like there to be three ways to format them:

1) `{:f}` -> `HalfInt(1,2)` is formatted as `"0.5"`, `HalfInt(2,2)` is formatted as `"1.0"`
2) `{:d}` -> `HalfInt(1,2)` raises an exception, `HalfInt(2,2)` is formatted to `"1"`
3) `{:g}` -> `HalfInt(1,2)` is formatted to `1/2`, `HalfInt(2,2)` is formatted to `"1"`

I think I can do these simple cases by just following the existing docs:
```cpp
namespace fmt {

template <>
struct formatter<HalfInt> {
  char presentation = 'g';

  template <typename ParseContext>
  constexpr auto parse(ParseContext& ctx) {
    auto it = ctx.begin(), end = ctx.end();
    if (it != end && (*it == 'd' || *it == 'f' || *it == 'g')) presentation = *it++;

    // Check if reached the end of the range:
    if (it != end && *it != '}')
      throw format_error("invalid format");

    // Return an iterator past the end of the parsed range:
    return it;
  }

  template <typename FormatContext>
  auto format(const HalfInt& h, FormatContext& ctx) {
    if (presentation == 'f')
    {
      return format_to(ctx.out(), "{:.1f}", float(h));
    }
    else if (presentation == 'd')
    {
      if (!h.IsInteger()) throw format_error("non-integer value");
      return format_to(ctx.out(), "{:d}", int(h));
    }
    else
    {
      if (h.IsInteger())
        return format_to(ctx.out(), "{:d}", int(h));
      else
        return format_to(ctx.out(), "{:d}/2", h.TwiceValue());
    }
  }
};

}  // namespace fmt
```

However, I want to add support for filling, signs, zero-padding (for `{:f}` and `{:d}`), widths, and alignments. Is there a general function for parsing these into a struct, or do I need to rewrite the parser myself?

**Comment by vitaut** [comment]
This is the function for parsing standard format specifiers: https://github.com/fmtlib/fmt/blob/2161a73f2bbd723700ca6cebe1ae49d41201a10e/include/fmt/format.h#L2444

It is not part of the public API though although I plan to eventually provide this functionality publicly.

**Comment by kc9jud** [comment]
@vitaut is there any update on providing a public API for parsing standard format specifiers? Scrolling through the issue list, it looks like a pretty common request, so it might be worth keeping an issue open to collect requests/track progress.

**Comment by vitaut** [comment]
The parsing API is still private but there have been some improvements to handling type/presentation specifiers. Whether this issue is open or not doesn't really matter because it's on my TODO list regardless.
