### ISSUE TITLE
Can we make FMT_DEBUG_POSTFIX as a cache variable

### ISSUE THREAD

**Issue by deryck1031** [fmtlib/fmt#1566]
Currently there is no way to disable adding 'd' in debug build with lib name like libfmtd.a.  Can you 
please make it configurable?  'd' is added by below code:

set(FMT_DEBUG_POSTFIX d)

**Comment by vitaut** [comment]
Sure. Could you submit a PR?

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/0c6919ec7202bdfba6cb7911d7ad6b69d91dcd09.
