### ISSUE TITLE
`precision` field doesn't support leading zeros

### ISSUE THREAD

**Issue by xumingkuan** [fmtlib/fmt#1579]
I wrote `fmt::format("{:.02f}", 1.234)` but it gave me an error message: `missing '}' in format string`.

`fmt::format("{:.2f}", 1.234);` worked for me.

I think leading zeros should also be supported, as python supports both `'{:.2f}'.format(1.234)` and `'{:.02f}'.format(1.234)`.

**Comment by vitaut** [comment]
Leading zeros in precision are allowed now. Thanks for reporting.
