### ISSUE TITLE
PGI compiler does not handle FMT_FALLTHROUGH correctly

### ISSUE THREAD

**Issue by federico-busato** [fmtlib/fmt#1583]
The PGI compiler can set `FMT_GCC_VERSION >= 700`, but it does not recognize `gnu::fallthrough`
error:
`fmt/format.h", line 1268: error #1097: unknown attribute "gnu::fallthrough"`

Possible fix:
```cpp
#  elif FMT_GCC_VERSION >= 700 && !defined(__PGI)
#    define FMT_FALLTHROUGH [[gnu::fallthrough]]
```
Tested with PGI 20.1

**Comment by vitaut** [comment]
Applied the suggested fix in https://github.com/fmtlib/fmt/commit/941d5e147a2875226a25877196dab32ac629a67d. Thanks!
