### ISSUE TITLE
debugger output

### ISSUE THREAD

**Issue by greg7mdp** [fmtlib/fmt#1585]
Not an issue, but a question. 
Is there a plan to use formatters for user defined types (if they exist) to improve the output in debuggers (similar to Visual Studio visualizers)? That would be awesome!

**Comment by vitaut** [comment]
Debugger integration is out of scope of this project but the library can probably be used to improve debugger output for UDTs.

**Comment by greg7mdp** [comment]
Thanks for the answer!
