### ISSUE TITLE
Build error Clang < 5.0 constexpr function never produces a constant expression

### ISSUE THREAD

**Issue by scamille** [fmtlib/fmt#1587]
I get build errors after upgrading to fmt 6.1.2 when building with clang < 5.0, eg. with clang 3.9

```
/util/fmt/core.h:735:20: error: constexpr function never produces a constant expression [-Winvalid-constexpr]

FMT_CONSTEXPR bool is_integral_type(type t) {

                   ^

./util/fmt/core.h:736:3: note: both arms of conditional operator are unable to produce a constant expression

  FMT_ASSERT(t != named_arg_type, "invalid argument type");

  ^

./util/fmt/core.h:234:8: note: expanded from macro 'FMT_ASSERT'

      ((condition)                         \

       ^
```

Unfortunately I cannot find any solid information whether this really is only a clang problem/bug, or something which newer versions/gcc just don't complain about.

We build with --std=c++14. See https://travis-ci.org/github/simulationcraft/simc/jobs/661165928 for the CI build showing the problems.

I was able to reproduce this locally with clang-3.9 and clang-4.0, but not with clang-5.0 or clang-6.0.

**Comment by vitaut** [comment]
This was worked around in https://github.com/fmtlib/fmt/commit/b2d3a86ec0865c2771191d674e85d31d22d5b1da.

**Comment by scamille** [comment]
Thanks for the quick response.
