### ISSUE TITLE
Color formatting doesn't work for wide strings

### ISSUE THREAD

**Issue by Spirrwell** [fmtlib/fmt#1594]
Hello there!

I don't know if wide strings are intended to not be supported by color formatting, but it seems like a bug.

To put simply, this does not work:

`fmt::print( fmt::fg( fmt::color::red ), L"This is a wide formatted string\n" );`

If you look at this line here: https://github.com/fmtlib/fmt/blob/master/include/fmt/color.h#L415

It uses std::strlen and if you try to format a wide string with this, it fails to compile as std::strlen assumes 'char' is the type.

I've tried replacing it with this:

`return buffer + std::char_traits<Char>::length(buffer);`

This seems to work just fine for me. But I haven't done a whole lot of testing.

**Comment by vitaut** [comment]
Thanks for reporting. Could you submit a PR with your suggested fix and a test in `test/color-test.cc`?
