### ISSUE TITLE
Non-null-terminated string with precision in printf

### ISSUE THREAD

**Issue by devinamatthews** [fmtlib/fmt#1595]
The man page for printf states, "If a precision is specified, no more bytes than the number specified are written, but no partial multibyte characters are written. Note that the precision determines the number of bytes written, not the number of wide characters or screen positions. *The array must contain a terminating null wide character, **unless a precision is given and it is so small that the number of bytes written exceeds it before the end of the array is reached.***" (Emphasis mine).

In `arg_formatter_base::write(const char_type*)`, the string length is unconditionally computed:
```C++
auto length = std::char_traits<char_type>::length(value);
```
I found that changing this to:
```C++
size_t length = 0;
while (!std::char_traits<char_type>::eq(value[length], char_type(0))
    && length != specs_->precision) ++length;
```
fixed the problem, at least in my case. An example usage that leads to this behavior is:
```C++
char foo[] = {'H', 'e', 'l', 'l', 'o'};
fmt::printf("%.5s\n", foo);
```

**Comment by vitaut** [comment]
Great catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/0463665ef136d685fe07a564d93c782456456d3d.
