### ISSUE TITLE
format_spec for elements in range formatting

### ISSUE THREAD

**Issue by rbrugo** [fmtlib/fmt#1599]
I can't find a way to apply `format_spec` to ranges elements.
For example, the following code throws:
```cpp
fmt::format("{:.1}", std::vector{1.11, 2.22}) == "{1.1, 2.2}"
```
There is a way to achieve this?

**Comment by vitaut** [comment]
You can do this with `fmt::join`:

```c++
fmt::print("[{:.1}]", fmt::join(std::vector{1.11, 2.22}, ", "));
```
This prints `[1.0, 2.0]`.
