### ISSUE TITLE
Default formatting for float value

### ISSUE THREAD

**Issue by spitfire2** [fmtlib/fmt#1600]
I had lots of double to format and the precision is ".2f". I need to do like below:
`fmt::format("{:.2f}{:.2f}{:.2f}{:.2f}{:.2f}{:.3f}", a, b,c,d,e,f);`

Is there a way that I can set a default format string for double (my needs is {:.2f}) then the below code has the same behavior with the above code buy I can rewrite it as well?
`fmt::format("{}{}{}{}{}{:.3f}", a, b,c,d,e,f);`

PS: I know ":g" but it's not what I want.

**Comment by vitaut** [comment]
There is no way to change the default formatting.
