### ISSUE TITLE
How to format floating point into fixed width with `g` type

### ISSUE THREAD

**Issue by xylosper** [fmtlib/fmt#1605]
When I use `fmt::format("{: #08g}", ...)` to format floating-point values, I get:

```
 1.0 -> " 1.000000"
-1.0 -> "-1.000000"
 0.0 -> " 0.00000"
```

Is this expected behavior? I expected " 0.000000" for 0.0 so that all formatted results fit into same columns.
How can I get " 0.000000" for 0.0 with fmt?

**Comment by vitaut** [comment]
The current version of {fmt} produces aligned output:

```
#include <fmt/core.h>

int main() {
  fmt::print("{: #08g}\n", 1.0);
  fmt::print("{: #08g}\n", -1.0);
  fmt::print("{: #08g}\n", 0.0);
}
```

prints

```
 1.00000
-1.00000
 0.00000
```

https://godbolt.org/z/hUu5_e
