### ISSUE TITLE
Compiling fmt::print(L"Testing") fails

### ISSUE THREAD

**Issue by risa2000** [fmtlib/fmt#1609]
With VS2019 16.5.1, and `fmtlib` from the repo, I cannot compile following code:
```c++
#include <fmt/format.h>

int main(int argc, char* argv[])
{
    fmt::print(L"Testing");
    return 0;
}
```
The error I am seeing is:
>>------ Build All started: Project: fmt_test, Configuration: x64-Debug ------
  [1/2] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\HostX64\x64\cl.exe  /nologo /TP -DFMT_LOCALE -ID:\Dev\include -ID:\Dev\crtdll\include /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd   -std:c++17 /showIncludes /FoCMakeFiles\fmt_test.dir\fmt_test.cpp.obj /FdCMakeFiles\fmt_test.dir\ /FS -c ..\..\..\fmt_test.cpp
  FAILED: CMakeFiles/fmt_test.dir/fmt_test.cpp.obj 
  C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\HostX64\x64\cl.exe  /nologo /TP -DFMT_LOCALE -ID:\Dev\include -ID:\Dev\crtdll\include /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd   -std:c++17 /showIncludes /FoCMakeFiles\fmt_test.dir\fmt_test.cpp.obj /FdCMakeFiles\fmt_test.dir\ /FS -c ..\..\..\fmt_test.cpp
D:\Dev\crtdll\include\fmt\core.h(1782): error C2664: 'void fmt::v6::internal::vprint_mojibake(FILE *,fmt::v6::string_view,fmt::v6::format_args)': cannot convert argument 2 from 'fmt::v6::basic_string_view<wchar_t>' to 'fmt::v6::string_view'
  D:\Dev\crtdll\include\fmt\core.h(1783): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  D:\Dev\crtdll\include\fmt\core.h(1662): note: see declaration of 'fmt::v6::internal::vprint_mojibake'
  ..\..\..\fmt_test.cpp(5): note: see reference to function template instantiation 'void fmt::v6::print<wchar_t[8],,0>(const S (&))' being compiled
          with
          [
              S=wchar_t [8]
          ]
  ninja: build stopped: subcommand failed.

Build All failed.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/80ce222ca64be694f2bf6472169e571d14c68dd3. Thanks for reporting.
