### ISSUE TITLE
Force `0x` prefix instead of `0X` with format `{:#X}`

### ISSUE THREAD

**Issue by polyvertex** [fmtlib/fmt#1611]
This is similar to #439.

I need to modify the way integers are formatted when the type `x` or `X` is specified. More specifically:

1. always cast the value to an unsigned
2. force the `0x` prefix instead of `0X` when format `{:#X}` is specified, but still keep the remaining digits upper-cased (i.e. `0xBEEF`, not `0XBEEF` nor `0xbeef`)

`1.` is covered by the [example in the documentation](https://fmt.dev/latest/api.html#custom-formatting-of-built-in-types).

However I fail to find a (clean) way to achieve `2.` without going through a painful process of reimplementing a writer class and using internals of *fmt*. Just lower-casing `format_specs::type` does not serve my purpose here because it also affects the `<digits>` part, not only the `<prefix>`.

Did I miss something?
Am I doomed to do `fmt::format("0x{:X}", value)` instead?

PS1: the `FormatSpec` class of the previous major versions of the library allowed to do that easily by overriding its `type_prefix` method (I was unconditionally lower-casing the value, which did not impact the `type` itself). But it seems former `type_prefix` has been replaced by the `format_specs::alt` flag, which is not helpful in my use case.

PS2: here is my uncompiled boilerplate code that achieve `1.`:

```c++
template <typename Char>
class custom_arg_formatter : ::fmt::arg_formatter<::fmt::buffer_range<Char>>
{
private:
    typedef ::fmt::arg_formatter<::fmt::buffer_range<Char>> SuperT;

public:
    custom_arg_formatter(
            ::fmt::format_context& ctx,
            ::fmt::format_parse_context* parse_ctx = nullptr,
            ::fmt::format_specs* spec = nullptr)
        : SuperT(ctx, parse_ctx, spec)
        { }

    using SuperT::operator();

    template <
        typename T,
        FMT_ENABLE_IF(
            ::std::is_integral<T>::value &&
            ::std::is_signed<T>::value)>
    auto operator()(T value)
    {
        if (this->specs())
        {
            const auto type_lc = this->specs()->type | 0x20;  // lower case
            if (type_lc == 'x')  // || type_lc == 'b')
            {
                typedef ::std::make_unsigned<T>::type unsigned_type;
                return SuperT::operator()<unsigned_type>(value);
            }
        }

        return SuperT::operator()(value);
    }
};
```

**Comment by vitaut** [comment]
There is no built-in format specifier to do this but you can either use `"0x{:X}"` or provide a wrapper type with custom formatting.
