### ISSUE TITLE
Using libfmt on bare metal

### ISSUE THREAD

**Issue by thmxv** [fmtlib/fmt#1617]
Hi,
I am using libfmt in a bare metal project without dynamic allocation support and not linking against libstdc++. I am not using all the libfmt API as fmt::print () and fmt::format() seem to require dynamic allocation. For now I am just using fmt in the following code but I plan on also using fmt::format_to_n() in the future.
```c++
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
#include <fmt/format.h>
#pragma GCC diagnostic pop

template <typename T>
struct PrintOutputIt {
    using value_type = T;
    using iterator_category = std::output_iterator_tag;
    using difference_type = void;
    using pointer = void;
    using reference = void;
    using _Unchecked_type = PrintOutputIt; // Mark iterator as checked.

    PrintOutputIt& operator*() { return *this; }
    PrintOutputIt& operator++() { return *this; }
    PrintOutputIt& operator++(int) { return *this; }
    PrintOutputIt& operator=(const T& value) {
        std::fputc(value, stdout);
        return *this;
    }
};

template <typename S, typename... Args>
inline void print(const S& format_str, Args&&... args) {
    using CharT = fmt::char_t<S>;
    fmt::format_to(
        PrintOutputIt<CharT>(), format_str, std::forward<Args>(args)...);
}
```
To make it all work, without linking with libstdc++, I add to: 
- Recompile my toolchain with `--disable-extern-template`, to avoid undefined references to `std::allocator<char>`
- Provide the following stubs
```c++
#include <clocale>
#include <locale>

namespace std {

void __throw_out_of_range(char const*) {
    panic("Exception thrown");
}

void __throw_out_of_range_fmt(char const*, ...) {
    panic("Exception thrown");
}

void __throw_bad_alloc() {
    panic("Exception thrown");
}

void __throw_bad_cast() {
    panic("Exception thrown");
}

locale::locale(const locale&) throw() {
    panic("Unimplemented");
}

locale::locale() throw() {
    panic("Unimplemented");
}

locale::~locale() throw() {
    panic("Uninplemented");
}

size_t locale::id::_M_id() const throw() {
    panic("Unimplemented");
    return 0;
}

} // namespace std
```
It seems to work OK for now, switching from using printf to this with newlib (not nano) optimizing for size and using LTO, my project went from using 60K to using 80K. Which is not perfect but acceptable.

However I am unsure if this is a correct use of the public stable API and how brittle/robust it can be considered to be.

I also have a lot of compiler warnings regarding `int_writer` violating the one definition rule, which seems to be caused by the use of a custom output iterator.

**Comment by thmxv** [comment]
I just tried 6.2.0, with FMT_USE_FLOAT=0 FMT_USE_DOUBLE=0 FMT_USE_LONG_DOUBLE=0 and the memory usage dropped down to 43K, so better than printf.

**Comment by vitaut** [comment]
You can
1. disable the use of locales by compiling with the `FMT_STATIC_THOUSANDS_SEPARATOR` macro defined
2. disable exceptions with compiler options and define `FMT_THROW` to `panic`

making the stubs unnecessary.

**Comment by SanderBouwhuis** [comment]
@vitaut 
If locales are disabled with FMT_STATIC_THOUSANDS_SEPARATOR, what will we be missing? Does it only involve separators like , and .? Or does it also affect chrono?
More than that?

**Comment by thmxv** [comment]
Thanks for the additional info.

I was already defining `FMT_STATIC_THOUSANDS_SEPARATOR` but to 1, just defining it empty did the job.

I was already disabling exceptions for all targets inside my projects.

I could not define `FMT_THROW` from cmake because function-like macros cannot be passed by the command line but defining it before including `fmt/format.h` works if using fmt-header-only, if using fmt then the library is compiled without the definitions and the code using the library is compiled with the definitions.

Regarding the ODR linker warnings I am working hard on identifying the cause, my guess is that I am using cmake wrong. I use fmt in a library and this library is used by an executable. Because the library include fmt/format.h in a header, I have to make the libfmt headers available to the executable. I did that by using `target_link_libraries(my_lib PUBLIC fmt::fmt-header-only)`

third_party/CMakeLists.txt
```cmake
add_subdirectory(fmt-6.2.0)

# Definitions are now in code including fmt because FMT_THROW cannot 
# be passed by command line

# target_compile_definitions( fmt
#     PUBLIC FMT_STATIC_THOUSANDS_SEPARATOR
#         FMT_USE_FLOAT=0 FMT_USE_DOUBLE=0 FMT_USE_LONG_DOUBLE=0)
# 
# target_compile_definitions( fmt-header-only
#     INTERFACE FMT_STATIC_THOUSANDS_SEPARATOR
#         FMT_USE_FLOAT=0 FMT_USE_DOUBLE=0 FMT_USE_LONG_DOUBLE=0)
# 
```
my_lib/CMakeLists.txt
```cmake
target_link_libraries(my_lib PUBLIC fmt::fmt-header-only)
```

my_exec/CMakeLists.txt
```cmake
target_link_libraries( my_exec PRIVATE my_lib)
```

**Comment by thmxv** [comment]
Apparently this is a valid usage of cmake. 

I found the issue was caused by using `set_target_properties(my_lib PROPERTIES CXX_EXTENSIONS OFF)` for the library and not the executable. Stupid mistake on my part that was unnoticed until now.

**Comment by vitaut** [comment]
> If locales are disabled with FMT_STATIC_THOUSANDS_SEPARATOR, what will we be missing?

`,` will always be used instead of a locale-specific digit separator. Chrono specifiers that don't rely on locale will continue to work, others won't.
