### ISSUE TITLE
printf support for `memory_buffer`

### ISSUE THREAD

**Issue by timblechmann** [fmtlib/fmt#1619]
currently there's no way to printf to a `memory_buffer` (or an insert iterator). this makes it a little cumbersome to create a `std::string` without paying for `streams`.
would be a nice feature to have

**Comment by vitaut** [comment]
Thanks for the suggestion. There are no plans to extend the `printf` API because it is only there for migrating legacy code. I recommend using the format API instead.

**Comment by timblechmann** [comment]
fair enough ...

unfortunately i'm working with a lot of legacy code. it's less likely to run into regressions when having to modify the format strings (some of them are generated)
