### ISSUE TITLE
Unable to format std::wstring as user-defined type

### ISSUE THREAD

**Issue by darwin** [fmtlib/fmt#1621]
I need to print some wstrings. Fmt complains "mixing character types is disallowed". After a bit of googling and reading issues here I understand that this is by design, because fmt does not do any conversions.

My idea was to treat std::wstring as used-defined type and implement conversion inside format:
https://godbolt.org/z/AXJHhs

Unfortunately this "mixing characters" check seems to be too early before fmt tries to apply user-defined types.

Using a wrapper type seems to work as expected:
https://godbolt.org/z/5beZ_c

**Comment by vitaut** [comment]
{fmt} doesn't provide a way to override formatting of built-in and string types but as you have already found out it's possible to use wrapper types to achieve this.
