### ISSUE TITLE
MSVC C4355 warning

### ISSUE THREAD

**Issue by jbuechner** [fmtlib/fmt#1622]
When compiling `format.cc` or when using `fmt::format` inside other projects, MSVC reports a C4355 for https://github.com/fmtlib/fmt/blob/3860edc5d9e7e9a7431d30b7f98cbb206688d0a5/include/fmt/format.h#L2143 and https://github.com/fmtlib/fmt/blob/3860edc5d9e7e9a7431d30b7f98cbb206688d0a5/include/fmt/format.h#L2146

examplary compiler output
```
format.h(2148,1): error C4355: 'this': used in base member initializer list (compiling source file format.cc)
```

For our own projects we treat this warning as error.

I would like to suppress the warning inside the format.h file and can prepare a pull request for the required change.

**Comment by vitaut** [comment]
A PR is welcome but please make sure that the warning is fixed/suppressed locally. This can be done by hiding `this` behind an accessor.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/e30d8391e401f74a48d822c64d96f965ff16c722.
