### ISSUE TITLE
MSVC warning C4566

### ISSUE THREAD

**Issue by erengy** [fmtlib/fmt#1625]
Using Visual Studio 2019 Version 16.5.3 (`_MSC_VER == 1925`) on Windows with Japanese system locale (code page 932), this line:

https://github.com/fmtlib/fmt/blob/3860edc5d9e7e9a7431d30b7f98cbb206688d0a5/include/fmt/core.h#L327

...gives the following [warning](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4566):

```
warning C4566: character represented by universal-character-name '\u00B5' cannot be
represented in the current code page (932)
```

The issue was introduced in 08ca40ea9139b9066843e93e308927dc7bb69819.

**Comment by vitaut** [comment]
Tentatively fixed in https://github.com/fmtlib/fmt/commit/36ea32640fecc775d16fd337c447762bede3eac1. Could you confirm that the warning is gone since I don't have a Windows machine at hand?

**Comment by erengy** [comment]
I can confirm that the warning is now suppressed. Thanks!
