### ISSUE TITLE
Question about using "{:#.6g}" specifier

### ISSUE THREAD

**Issue by risa2000** [fmtlib/fmt#1630]
I am trying to print `double` array from my program in a specific manner, but cannot find the right formatting specifier. The following code emulates my situation:
```c++
#include <fmt/format.h>

int main(int argc, char* argv[])
{
    std::vector<double> position = { -0.03175000101327896, 0.0, 0.0 };
    fmt::print("position = [{}]\n", fmt::format("{}", fmt::join(position, ", ")));
    fmt::print("position = [{}]\n", fmt::format("{:.6f}", fmt::join(position, ", ")));
    fmt::print("position = [{}]\n", fmt::format("{:.6g}", fmt::join(position, ", ")));
    fmt::print("position = [{}]\n", fmt::format("{:#.6g}", fmt::join(position, ", ")));
    return 0;
}
```
The output looks like this:
```
position = [-0.03175000101327896, 0.0, 0.0]
position = [-0.031750, 0.000000, 0.000000]
position = [-0.03175, 0, 0]
position = [-0.03175, 0.00000, 0.00000]
```
Now, what I would like to print is this:
```
position = [-0.03175, 0.0, 0.0]
```
I did not find a way to specify this format, i.e. a mixture of `{}` (= keep at least one zero after the decimal point) and `{:.6g}` (i.e. remove trailing zeros, if not needed).

What I found interesting is that `{:#.6g}` actually comes close to that, by removing the trailing zero from the first item, but then probably keeps applying the same format to remaining fields. Should not it actually behave as in what I am looking for, i.e. printing `[-0.03175, 0.0, 0.0]`?

If not, is there possibly some other way I overlooked to get this format?

**Comment by vitaut** [comment]
You can't selectively remove trailing zeros but you can write a function that checks for zero and prints it specially.
