### ISSUE TITLE
Windows char* is not UTF-8.

### ISSUE THREAD

**Issue by sayurin** [fmtlib/fmt#1632]
`fmt::windows_error` has system error message, and it is encoded using `fmt::internal::utf16_to_utf8`. But in Windows, `char*` is not UTF-8. Following code should use `FormatMessageA` instead of `FormatMessageW`.

https://github.com/fmtlib/fmt/blob/f733882b55779c68d2b1fbbe978f10c11113b6cd/src/os.cc#L113-L142

**Comment by vitaut** [comment]
That's intentional. {fmt} avoid legacy Windows APIs such as `FormatMessageA` in favor of Unicode-based ones.

**Comment by sayurin** [comment]
`FormatMessageA` is one of approach.

Look at [`_Winerror_message` of Microsoft/STL](https://github.com/microsoft/STL/blob/a0fffa10761d17aa59fd1b298fea9999b18b257b/stl/src/syserror.cpp#L117-L126) and [it's history](https://github.com/microsoft/STL/blob/eb4a486c8312e575251d886bfd2e1b4e0c2c371d/stl/src/syserror.cpp#L111-L136). It is implementation of `std::system_error::what()`.
Currently, `FormatMessageA` is used. But if you think to avoid, use `FormatMessageW` and `WideCharToMultiByte(CP_ACP, ...)`.

**Comment by sayurin** [comment]
@vitaut, at {fmt}, what is encoding of `char*` ?

I think [if `FMT_UNICODE` set, `char*` is UTF-8](https://github.com/fmtlib/fmt/blob/e9fdea90b535054557b3e10d7c427fd44b8c99b2/include/fmt/core.h#L339-L342). But if unset, what encoding?
Maybe it is platform depend. If so, I concerned about byte representaion of `"µs"` at chrono.h. For example, Windows uses ANSI encoding. And at Japanese Windows, ANSI is Shift_JIS. And Shift_JIS has no `µ` char.

**Comment by vitaut** [comment]
{fmt} is mostly encoding-agnostic. If some legacy encoding is used as the literal encoding then the compiler might convert `µ` to some garbage.

**Comment by sayurin** [comment]
@vitaut, yes. Once compiler convert  `µ` char to another code, At runtime it cannot recover to unicode.
So I [wrote `wide_to` template class](https://github.com/fmtlib/fmt/compare/master...sayurin:use-wide_to) that is alternative of utf8_to_utf16 class, and use it. How about this?

**Comment by vitaut** [comment]
Since it only affects one case I think it would be much easier to check if unit is micro in https://github.com/fmtlib/fmt/blob/7f723fbcb8eccc50f6efe988a97db6c9d7f18b28/include/fmt/chrono.h#L785 and handle it specially.
