### ISSUE TITLE
6.2.0 and master does not compile with FMT_EXCEPTIONS=0

### ISSUE THREAD

**Issue by kwesolowski** [fmtlib/fmt#1634]
I am trying to use fmt in embedded setting, when a lot of its features makes it better than STL/printf solutions, but unfortunately, target is missing rtti and exceptions.

Seems the code "tries" to support that, but include order fails:

`Building all
[3/5] Building CXX object software/external/fmt-master/CMakeFiles/fmt.dir/src/os.cc.o
FAILED: software/external/fmt-master/CMakeFiles/fmt.dir/src/os.cc.o 
/usr/bin/c++  -DFMT_EXCEPTIONS=0 -DFMT_NOEXCEPT=0 -DFMT_UNICODE=0 -I../software/external/fmt-master/include -std=gnu++11 -MD -MT software/external/fmt-master/CMakeFiles/fmt.dir/src/os.cc.o -MF softw
are/external/fmt-master/CMakeFiles/fmt.dir/src/os.cc.o.d -o software/external/fmt-master/CMakeFiles/fmt.dir/src/os.cc.o -c ../software/external/fmt-master/src/os.cc
In file included from ../software/external/fmt-master/include/fmt/format.h:44:0,
                 from ../software/external/fmt-master/include/fmt/os.h:26,
                 from ../software/external/fmt-master/src/os.cc:13:
../software/external/fmt-master/include/fmt/core.h:358:35: error: expected ‘;’ at end of member declaration
   FMT_CONSTEXPR basic_string_view() FMT_NOEXCEPT : data_(nullptr), size_(0) {}
                                   ^
<command-line>:0:14: error: expected unqualified-id before numeric constant
../software/external/fmt-master/include/fmt/core.h:358:37: note: in expansion of macro ‘FMT_NOEXCEPT’
   FMT_CONSTEXPR basic_string_view() FMT_NOEXCEPT : data_(nullptr), size_(0) {}
                                     ^~~~~~~~~~~~
In file included from ../software/external/fmt-master/include/fmt/format.h:44:0,
                 from ../software/external/fmt-master/include/fmt/os.h:26,
                 from ../software/external/fmt-master/src/os.cc:13:
../software/external/fmt-master/include/fmt/core.h:361:62: error: expected ‘;’ at end of member declaration
   FMT_CONSTEXPR basic_string_view(const Char* s, size_t count) FMT_NOEXCEPT
                                                              ^
<command-line>:0:14: error: expected unqualified-id before numeric constant
../software/external/fmt-master/include/fmt/core.h:361:64: note: in expansion of macro ‘FMT_NOEXCEPT’
   FMT_CONSTEXPR basic_string_view(const Char* s, size_t count) FMT_NOEXCEPT
                                                                ^~~~~~~~~~~~
<command-line>:0:14: error: expected initializer before numeric constant
../software/external/fmt-master/include/fmt/core.h:380:56: note: in expansion of macro ‘FMT_NOEXCEPT’
       const std::basic_string<Char, Traits, Alloc>& s) FMT_NOEXCEPT
                                                        ^~~~~~~~~~~~
<command-line>:0:14: error: expected initializer before numeric constant
../software/external/fmt-master/include/fmt/core.h:387:40: note: in expansion of macro ‘FMT_NOEXCEPT’
   FMT_CONSTEXPR basic_string_view(S s) FMT_NOEXCEPT : data_(s.data()),
                                        ^~~~~~~~~~~~
In file included from ../software/external/fmt-master/include/fmt/format.h:44:0,
                 from ../software/external/fmt-master/include/fmt/os.h:26,
                 from ../software/external/fmt-master/src/os.cc:13:
`

**Comment by kwesolowski** [comment]
I see similar issues being closed, but still I get pretty reproducible results. 

Would you accept PR adding new fmt-no-exceptions and fmt-no-exceptions-header-only targets to cmake so this can get caught earlier in tests?

**Comment by vitaut** [comment]
> Would you accept PR adding new fmt-no-exceptions and fmt-no-exceptions-header-only targets to cmake so this can get caught earlier in tests?

Yes. One target (`fmt-no-exceptions`) is enough and it should only be enabled in CI, i.e. when configured with `FMT_PEDANTIC` in CMake.

**Comment by kwesolowski** [comment]
So using without exceptions should not be supported by CMake by calling add_subproject?

Agree that reusing "just sourcecode" and crafting own cmake might be easier sometimes, but not using exceptions is sometimes broader (i.e. Google and their guidelines).

**Comment by vitaut** [comment]
> So using without exceptions should not be supported by CMake by calling add_subproject?

Not as an additional target. It could be supported as a separate configuration option but that's independent of the question of testing with exceptions disabled.

**Comment by vitaut** [comment]
BTW {fmt} compiles fine with exceptions disabled: https://godbolt.org/z/Czj8b8. The reason that you get an error is that you define `FMT_NOEXCEPT` to 0.

**Comment by kwesolowski** [comment]
Thanks, I found this as well, seems issue is more convoluted and partially on compiler side.

Thanks for remaining answers :)
