### ISSUE TITLE
[Question] Use fmtlib for custom string type?

### ISSUE THREAD

**Issue by carlcc** [fmtlib/fmt#1638]
Hi,

As the title said.

I have wrote my version of String type which uses uint32_t as character type, now I want to add the amazing format function with fmtlib.

Currently my solution is converting my String type to std::string with UTF8 encoding, then invoking fmtlib to do the course, and finally reconstructing back to my String. It is obviously inefficient, so I want to known if there is a better way?

P.S.
My apologize if there was a similar topic (I think this should be a common question), but I indeed can not find it...

Regards.

**Comment by vitaut** [comment]
It is possible to add support for custom string types (see https://fmt.dev/latest/api.html#_CPPv2N3fmt14to_string_viewEPK4Char) but `uint32_t` won't work as a character type because it is not distinguishable from a number.
