### ISSUE TITLE
Can this library be used as standalone?

### ISSUE THREAD

**Issue by audryste** [fmtlib/fmt#1639]
I would like to use this as shared library (built with C++), but in delphi? 
For example it is possible import C shared libraries:
`function sprintf(S: PAnsiChar; const Format: PAnsiChar): Integer; cdecl; varargs; external 'msvcrt.dll';`

this let use C function as sprintf
I would like to use functionf fmt::format in the same manner as shared library fmt.dll without actual header file.
Is it achievable and if yes how?

**Comment by vitaut** [comment]
It is possible to consume the library without a header by calling the type-erased API such as `vformat` but you'd need to provide formatting arguments in a form compatible with `basic_format_args`: https://github.com/fmtlib/fmt/blob/5944fcad375e6cdbbd66f3d161a846efd5d16385/include/fmt/core.h#L1525-L1554
I'm not sure how to do it in Delphi.
