### ISSUE TITLE
👋 microsoft/terminal now uses {fmt}

### ISSUE THREAD

**Issue by DHowett-MSFT** [fmtlib/fmt#1642]
Hi! The README suggested that I file an issue to let you know about a project using {fmt}.

https://github.com/microsoft/terminal (the new Windows Terminal/old windows console host) has taken a dependency on {fmt}.

Excellent library. Thanks a lot!

:smile:

**Comment by vitaut** [comment]
Added in https://github.com/fmtlib/fmt/commit/9e2ad7cf686c463443ddb495aafe7c84b97ee022, thanks!
