### ISSUE TITLE
fmt::format_to and long strings

### ISSUE THREAD

**Issue by bouda1** [fmtlib/fmt#1645]
Hi,

Sorry for this message which is not a bug but rather a question. I looked for a forum but couldn't find one.
I played with fmt and was very impressed with the results I got. Well done!

In my project, we save a large text file (100,000 characters or more) every minute. We create this file using std::ostringstream.
I tried to replace it with several calls to fmt::format_to applied on a memory_buffer object.
For this, I made several calls to fmt::format_to with a rather long string and a good twenty variables to inject.
The first time, I used fmt::arg() to inject them. My results were slower than with std::stringstream.

I tried to reserve the memory_buffer before filling it to avoid reallocations. But std::stringstream gave me even better results.

I removed the calls to fmt::arg() thinking that the parsing would be less penalized. But it didn't improve the results much and again std::stringstream was faster.

Given the performance of your library on smaller strings, I guess I missed something. Do you have any suggestions?

Thank you.

**Comment by vitaut** [comment]
`memory_buffer` is mostly optimized for small/medium-size output, so you could try formatting to `std::string` directly instead if your output is very large. The difference could be due to different reallocation strategies - `memory_buffer` grows by 1.5x to avoid wasting memory while some implementations use a 2x grow factor. It's hard to say for sure, but if you provide a benchmark I can take a look.

**Comment by bouda1** [comment]
Thank you very much.
I tried to make a little program that replicates my problem. I changed fmt::memory_buffer to std::string. The code is simpler than the original but does the same kind of things.

`#include <fmt/format.h>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>

std::string old_one() {
  std::ostringstream oss;
  int a = 5;
  double b = 3.14;
  double c = 1.0 / 3;

  for (int i = 0; i < 100000; i++) {
    oss << "\tvalue a = " << a << "\n"
      "\tvalue b = " << std::fixed << std::setprecision(2) << b << "\n"
      "\tvalue c = " << c << "\n";
  }
  return oss.str();
}

std::string new_one() {
  std::string buf;
  int a = 5;
  double b = 3.14;
  double c = 1.0 / 3;

  for (int i = 0; i < 100000; i++)
    fmt::format_to(std::back_inserter(buf),
        "\tvalue a = {}\n\tvalue b = {:2f}\n\tvalue c = {:2f}\n", a, b, c);

  return buf;
}

std::string new_one1() {
  static size_t len = 60000;
  std::string buf;
  buf.reserve(len);
  int a = 5;
  double b = 3.14;
  double c = 1.0 / 3;

  for (int i = 0; i < 100000; i++)
    fmt::format_to(std::back_inserter(buf),
        "\tvalue a = {}\n\tvalue b = {:2f}\n\tvalue c = {:2f}\n", a, b, c);

  if (buf.size() > len)
    len = buf.size();
  return buf;
}

int main(int argc, char **argv) {
  if (argc > 1) {
    if (strcmp(argv[1], "old") == 0) {
      for (int i = 0; i < 100; i++)
        std::string v(old_one());
    }
    else if (strcmp(argv[1], "new") == 0) {
      for (int i = 0; i < 100; i++)
        std::string v(new_one());
    }
    else {
      for (int i = 0; i < 100; i++)
        std::string v(new_one());
    }
  }
  return 0;
}
`
I compiled this with
g++ -O2 test.cc libfmt.a on a Debian testing.

I get the following results:
`david@dev-dbr:~$ time ./new_a.out old

real	0m6,490s
user	0m6,166s
sys	0m0,324s
david@dev-dbr:~$ time ./new_a.out new

real	0m7,870s
user	0m7,474s
sys	0m0,383s
david@dev-dbr:~$ time ./new_a.out new1

real	0m7,849s
user	0m7,509s
sys	0m0,340s
david@dev-dbr:~$
`

**Comment by vitaut** [comment]
What {fmt} library version do you use?

**Comment by bouda1** [comment]
I use the 6.0.0 version.

**Comment by vitaut** [comment]
There is a bug in `new_one` and `new_one1`: there should be `.2f` instead of `2f` because precision is preceded with `.`

More importantly, the run time of this microbenchmark is likely dominated by floating-point formatting so you'll only get improvement when using a recent version of {fmt} which enables fast binary to decimal floating-point formatter. For example with version 6.2.0 I got:

```
$ time ./a.out old
real	0m4.568s
user	0m4.323s
sys	0m0.244s

$ time ./a.out new
real	0m2.731s
user	0m2.459s
sys	0m0.271s
```
i.e. {fmt} was 1.67x faster.

**Comment by bouda1** [comment]
OK, Thank you.
