### ISSUE TITLE
Format duration in milliseconds or less

### ISSUE THREAD

**Issue by artemyarulin** [fmtlib/fmt#1646]
HI, first of all thanks for your library, happy using that.

I wonder given 
```
auto duration = std::chrono::milliseconds(2) + std::chrono::microseconds(2);
``` 
is there a way to format this to get `2.002ms`. Reading https://github.com/fmtlib/fmt/blob/master/test/chrono-test.cc and http://en.cppreference.com/w/cpp/chrono/c/strftime I guess it's out of the scope of this library as I don't see format specifiers less than a second. Workaround from https://github.com/fmtlib/fmt/blob/master/test/chrono-test.cc#L332-L339 is a nice one but I wonder if there is a better way?

**Comment by mwinterb** [comment]
If you store the duration as a `std::chrono::duration<double, std::milli>` it looks like that works out:
https://gcc.godbolt.org/z/2f5Apm

**Comment by artemyarulin** [comment]
All right, I'll use this casting, thanks again :)
