### ISSUE TITLE
Problem insert library

### ISSUE THREAD

**Issue by WiDuAlK12** [fmtlib/fmt#1653]
Hi, i try to insert fmt library to my project, but i don't really know what miss. if i complile it's everything ok, but when i want to use fmt::format function, i get errors...
https://imgur.com/MDUYNN4

https://imgur.com/a/cFyrjty

https://imgur.com/KMu1ZTV

i try to make my own .lib file but dont't work. What i missed doing?

**Comment by vitaut** [comment]
You need to link with the fmt library e.g. using `target_link_libraries` in CMake: https://fmt.dev/latest/usage.html#usage-with-cmake
