### ISSUE TITLE
6.2.0 is less embedded friendly in comparison to 5.3.0

### ISSUE THREAD

**Issue by kwesolowski** [fmtlib/fmt#1654]
Hi,

Playing with IAR and GHS compilers I see some places (mostly os.h/os.cpp) where for example:

EINTR retry is done for "not windows", FILE * operations are included etc. Most of the functionality is perfectly "in RAM", but those few pieces leak os related items. Would you like to reduce such "heave OS" dependencies? What would be preferred Pull Request?

**Comment by kwesolowski** [comment]
Example patch (definitions would need to move outside lib). Or maybe just better mechanism to exclude os dependant features? 

+#define FMT_RETRY(result, expression) result = (expression)
+#define FMT_RETRY_VAL(result, expression, error_result) result = (expression)
+
+#ifndef FMT_RETRY
 // Retries the expression while it evaluates to error_result and errno
 // equals to EINTR.
 #ifndef _WIN32
 #  define FMT_RETRY_VAL(result, expression, error_result) \
     do {                                                  \
@@ -69,10 +73,11 @@
 #else
 #  define FMT_RETRY_VAL(result, expression, error_result) result = (expression)
 #endif
 
 #define FMT_RETRY(result, expression) FMT_RETRY_VAL(result, expression, -1)
+#endif

**Comment by vitaut** [comment]
`os.h/os.cc` are non-essential and can be excluded from the build. You only need `format.cc` and headers. I am open to a PR to add a CMake flag (e.g. `FMT_OS`) to control whether to include OS-specific APIs.

**Comment by kwesolowski** [comment]
Will make a PR.
