### ISSUE TITLE
"declaration shadows a local variable" Clang warning

### ISSUE THREAD

**Issue by tigerw** [fmtlib/fmt#1658]
```
fmt/include/fmt/printf.h:507:12: error: declaration shadows a local variable [-Werror,-Wshadow]
  auto end = str + specs.precision;
       ^
fmt/include/fmt/printf.h:469:15: note: previous declaration is here
  const Char* end = parse_ctx_.end();
```

when testing [this](https://travis-ci.org/github/cuberite/cuberite/jobs/681736050) build using master @ f19d6679435b66086d3dd3216acd1d637ca1d4c4.

Seems like it doesn't like [this line](https://github.com/fmtlib/fmt/blob/master/include/fmt/printf.h#L507).

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/3c114d091b6dc7ea978be8d87323af62b9c1db5b.
