### ISSUE TITLE
Possible memory allocations

### ISSUE THREAD

**Issue by alaurenzi** [fmtlib/fmt#1665]
Hi, and thanks for sharing this really nice library. I am interested in using it inside a realtime environment, where dynamic memory allocation is forbidden. I think I'll make use of the `format_to_n` API together with a fixed size char container, that I'll then dispatch to a non-realtime thread for the actual printing. This should rule out any call to the `grow()` method, which contains a call to the allocator, am I right?

 I have also seen a call to `operator new` inside `void arg_map<Context>::init(const basic_format_args<Context>& args) `, which makes me think I need to avoid named arguments.

Is there anything else I should be aware of in terms of avoiding allocations?

Thank you in advance
Arturo

**Comment by vitaut** [comment]
> This should rule out any call to the grow() method, which contains a call to the allocator, am I right?

Right.

> I have also seen a call to operator new inside void arg_map<Context>::init(const basic_format_args<Context>& args) 

This is no longer used and is there only for ABI compatibility. Named arguments don't dynamically allocate as of https://github.com/fmtlib/fmt/commit/8a4630686e2dd24900897298c4ae1362de749ed8.

> Is there anything else I should be aware of in terms of avoiding allocations?

Built-in formatters don't allocate memory but user-defined ones can. Also floating-point formatting can sometimes fall back to `s(n)printf` and the latter can potentially allocate.

**Comment by cjappl** [comment]
Hi @vitaut ,

> Also floating-point formatting can sometimes fall back to s(n)printf and the latter can potentially allocate.

Can you elaborate on when this fallback would happen? Or where I can look in the code to find it? Thank you!

**Comment by vitaut** [comment]
The fallback in question has been removed already.
