### ISSUE TITLE
`std::__ios_failure` when using `fmt/ostream.h`

### ISSUE THREAD

**Issue by suo** [fmtlib/fmt#1666]
Hey, in PyTorch we have some very involved code for printing out Tensor values to a stream that seems to fail when we try to use `fmt` on it. I've extracted a small reproduction of the issue here:
```
#include <fmt/format.h>
#include <fmt/ostream.h>

struct FormatGuard {
  FormatGuard(std::ostream & out)
  : out(out), saved(nullptr) {
    saved.copyfmt(out);
  }
  ~FormatGuard() {
    out.copyfmt(saved);
  }
private:
  std::ostream & out;
  std::ios saved;
};


struct Foo {
    std::string hello;
};

std::ostream& operator<<(std::ostream& os, const Foo& foo) {
    FormatGuard guard(os);
    os << foo.hello;
    return os;
}

int main() {
    auto f = Foo{"hello"};
    std::cout << f << std::endl;
    fmt::print("{}\n", f);
    return 0;
}
```

Compiling and running this code (fmt version 6.2.0, clang version 10) produces the following output:
```
hello  # the regular std::cout
terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_ios::clear: iostream error
```

I'm not familiar with iostreams, so maybe the FormatGuard is at fault here and you should tell me to go away 😛 . But I thought I'd ask if you had anything jumped out to you.

**Comment by vitaut** [comment]
I don't know why `copyfmt` throws when exception mask is set but I implemented a workaround in  https://github.com/fmtlib/fmt/commit/8f511fc12f62fa4ef8995b67a51849550c4f127f by setting the mask after `operator<<`. Thanks for reporting.

**Comment by vitaut** [comment]
And here's Billy O'Neal's explanation why the exception is thrown:

> Ah, there badbit is still set because rdbuf() == nullptr, and you turned on the exception mask asking for badbit. The call to exceptions(value) inside copyfmt is attempting to clear the flags but clear() forces badbit back on when rdbuf()==nullptr

**Comment by suo** [comment]
Thanks for such a quick fix :)
