### ISSUE TITLE
stream indenting

### ISSUE THREAD

**Issue by PaulTopping** [fmtlib/fmt#1671]
I am using this library on my own personal projects and love it. Since people working on this project are presumably C++ stream experts, I seek advice here. Is there a recommended way to add indenting support to an output stream? I am surprised to find no good solution to this problem in all the usual places. In more detail, what I'm looking for is a way to filter output such that any newline is followed by indentation spaces or tabs according to a current indent level which is part of the stream's state. 

I suspect this is not something that fmtlib would handle but, of course, the desired solution should be compatible with it. I ask here because if there's a solution in modern C++, perhaps this group would know about it.

**Comment by vitaut** [comment]
I'd go with something like this (https://godbolt.org/z/mpmu47):

```c++
#include <fmt/format.h>

struct indenter {
  int indent;

  template <typename... Args>
  void print(fmt::string_view format_str, const Args&... args) {
    fmt::print("{:{}}", "", indent);
    fmt::print(format_str, args...);
  }
};

int main() {
  auto indie = indenter{2};
  indie.print("foo\n");
  indie.indent = 4;
  indie.print("bar\n");
}
```
where `print` to stdout can be replaced with a `print` to any stream.

Output:
```
  foo
    bar
```

**Comment by PaulTopping** [comment]
Thanks. It's a bit of a cheat since it counts on each indie.print call to output exactly one line. It may well do for my project though.

A more robust solution would involve filtering the stream for newlines and adding the indent spaces or tabs. AFAIK, this is not really fmt's job. I've been playing around with this solution https://github.com/spacemoose/ostream_indenter. It seems to work with fmt but only if I specify the stream explicitly:

`fmt::print(cout,"this works\n");`
`fmt::print("doesn't work\n");`

By "works", I mean that the \n is output with indenting after it. I would have thought those two were equivalent. This ostream_indenter project seems to be a bit hacky but I was surprised it worked differently depending on whether cout was given to print.

**Comment by vitaut** [comment]
> I was surprised it worked differently depending on whether cout was given to print.

`fmt::print` uses `stdout` not `cout` which may explain the difference.
