### ISSUE TITLE
Suggestion for wording around Unicode encoding

### ISSUE THREAD

**Issue by gh-andre** [fmtlib/fmt#1672]
First, let me thank you for this library. It is great.

This issue is just a suggestion and I am not looking for any resolution. Please feel free to close this issue right away.

This phrase in the docs:

> Strings are assumed to be Unicode-encoded unless the FMT_UNICODE macro is set to 0.

, is somewhat misleading in that there is no such thing as Unicode encoding, as Unicode characters are always represented in the code in one of the UTF encodings. Moreover, the `char` encoding is implementation specific and cannot be just assumed encoded as UTF-8 in the code unless explicitly prefixed with `u8`. That is, GCC will use whatever is in `-finput-charset=` and VC++ assumes it to be whatever user's character set is.

Some of the `fmt` examples will not work in all environments. The example with the character lines and corners (i.e. `"┌{0:─^{2}}┐\n"`) will not work on Windows because these characters cannot be represented in Win1252 and other commonly used character sets (unless the source file is saved as UTF-8, but this produces bizarre results throughout the code - `"\u00B5"` will be in Win1252 and `"┌"` in UTF-8, and should be avoided).

I suggest changing "Unicode-encoded" to some form of UTF-8-encoded wording to make it clear what is expected. 

Also prefixing example strings that contain characters outside the basic character set with `u8` would make it more clear how to handle non-ASCII characters and will also work with universal character names, like this:
```
fmt::print(
 u8"┌{0:─^{2}}┐\n"
 u8"│{1: ^{2}}│\n"
 u8"└{0:─^{2}}┘\n", "", "Hello, world!", 20);
```
`"Hello, world!"` contains only characters from the basic character set, so doesn't need the prefix.

Lastly, wide characters may not be Unicode at all. On Windows they may be treated as UCS-2, so `wcslen(L"\U0001B000")` doesn't recognize surrogate pairs and returns `2`, while GCC interprets them as UTF-32 and returns `1`. 

Andre

**Comment by vitaut** [comment]
Thanks for the suggestions. "Unicode-encoded" may not be the best wording but it doesn't imply existing of a single Unicode encoding. It just means "in some encoding that implements Unicode". It's a relatively common term, even used in the wikipedia page on Unicode: https://en.wikipedia.org/wiki/Unicode:

> are widely used in Unicode-encoded texts

> Some of the fmt examples will not work in all environments.

That's expected.

**Comment by gh-andre** [comment]
Ok, thanks for replying. 

I will note that Wikipedia is for the general public, so they can be as liberal in their wording as they want, which they do a lot. For development purposes going to the source is probably a good idea:

https://unicode.org/faq/utf_bom.html

Anyway, thanks again for your work.
