### ISSUE TITLE
Add API option for multiple-iteration formatting.

### ISSUE THREAD

**Issue by maybebotornot** [fmtlib/fmt#1673]
I have following issue:
I want user to provide an fmt format while filling it in two iterations.

1) pre-processing format. E.g., `{working_directory}/folder/{}` - formatting with `working_directory="./out/"` -> `"./out/folder/{}/"`
2) final formatting - filling the remaining `{}`.

I am unable to find any API in `fmt` that allows me to do that. I could do a work-around by supplying two formats - one for each formatting and putting one into another... but I don't like it.

If `fmt::format` simply ignored `{...}` that do not have an argument supplied - it'd solve the issue. I don't ask to change behaviour of `fmt::format` - only add an extra function that behaves in such a manner.

It could've helped a lot in cases where one part of the code can supply only portion of the arguments and forwards it to another class that fills the rest.

Maybe call the feature "partial formatting"? As one is allowed to fill only a portion of the parameters.

**Comment by vitaut** [comment]
There are no such feature and no plans to add it. If you can modify the format string then you can place extra curlies around placeholders you don't want to format, e.g. `{working_directory}/folder/{{}}`.

**Comment by maybebotornot** [comment]
@vitaut the problem is that now user has to write more complex input, something like: `{working_directory}/folder/{{}} | input_file_{:5d}` and I want to reduce unnecessary workload from users to bare minimum. This isn't a complex feature to add, i.e., one just needs to ignore parameters thst weren't supplied.

**Comment by maybebotornot** [comment]
@vitaut wait... I misunderstood what you wrote previously. It solves the problem. The only issue now is that couldn't find it anywhere in documentation. Advise you to add some example of `fmt::format("{{}}")` in the doc.

**Comment by vitaut** [comment]
https://fmt.dev/latest/syntax.html:

> If you need to include a brace character in the literal text, it can be escaped by doubling: {{ and }}.
