### ISSUE TITLE
Make dynamic_format_arg_store reusable

### ISSUE THREAD

**Issue by vsolontsov-ll** [fmtlib/fmt#1674]
It must be easy to make the dynamic_format_arg_store reusable by adding method `clear()`. Also adding method `reserve(num_args, num_named_args)` can improve memory management.

**Comment by vitaut** [comment]
PRs are welcome =).

**Comment by vsolontsov-ll** [comment]
Will do. The only trouble - I see no simple way to test reserve() method.

**Comment by vitaut** [comment]
https://github.com/fmtlib/fmt/blob/7f723fbcb8eccc50f6efe988a97db6c9d7f18b28/test/mock-allocator.h if you feel adventurous.

**Comment by vsolontsov-ll** [comment]
Right....:-)
Well, as of now dynamic_format_arg_store<> is not parameterized by allocator. I'm not infected by TDD that much. Do you see a reason for adding allocator there besides testing trivial method?

**Comment by vitaut** [comment]
No, I'm OK not testing whether reserve does anything useful since it's just an optimization and doesn't affect correctness. It's enough to test that it doesn't break things.
