### ISSUE TITLE
Question about generated code size - am I holding this wrong?

### ISSUE THREAD

**Issue by sztomi** [fmtlib/fmt#1676]
I wanted to find a good alternative to `boost::lexical_cast<string>(int)` that generates less code. After some experiments on Compiler Explorer, I was surprised to see that fmt generated more code than boost::lexical_cast. I ended up using `std::to_string`, but ran a couple more experiments and was surprised to find that there is a 4x size increase between fmt 4.2 and 6.2 (for the same code, same flags, same compiler). Why does this happen, and am I supposed to do something differently to decrease the code size? 

This is the code, compiled with clang 9.0, with `-O2`. https://godbolt.org/z/SXLDU4

```cpp
#include <boost/lexical_cast.hpp>

#include <string>

void lexical_cast() {
    auto x = boost::lexical_cast<std::string>(1234);
}

// -------

#include <fmt/format.h>

void fmt_convert() {
    auto x = fmt::format("{}", 1234);
}

// -------

#include <string>

void to_string_convert() {
    auto x = std::to_string(1234);
}
```

Summary:

  | Code size | Multiplier
-- | -- | --
std::to_string | 435847 | 1
lexical_cast | 1165849 | 2.674904267
fmt 4.2 | 3544508 | 8.132459326
fmt 6.2 | 14151966 | 32.47003191
fmt 6.2 C++17 | 13964677 | 32.04031919
fmt 6.2 FMT_STRING, C++17 | 13966847 | 32.04529801

**Comment by vitaut** [comment]
Compiling 

```c++
#include <fmt/format.h>

int main() {
  return fmt::format("{}", 1234).size();
}
```
on the current `master` gives:
```
% g++ test.cc -O3 -I include -std=c++17 src/format.cc -DNDEBUG
% ls -l a.out
-rwxr-xr-x  1 viz  staff  106768 May  9 13:53 a.out
% strip a.out
% ls -l a.out
-rwxr-xr-x  1 viz  staff  91208 May  9 13:53 a.out
```
i.e. 91k stripped binary including all of the library code.

As you can see from godbolt per-call code is pretty small:

```
fmt_convert():                       # @fmt_convert()
        sub     rsp, 56
        mov     qword ptr [rsp], 1234
        lea     rdi, [rsp + 24]
        mov     r8, rsp
        mov     esi, offset .L.str
        mov     edx, 2
        mov     ecx, 2
        call    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v6::internal::vformat<char>(fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<fmt::v6::type_identity<char>::type> >, fmt::v6::type_identity<char>::type> >)
        mov     rdi, qword ptr [rsp + 24]
        lea     rax, [rsp + 40]
        cmp     rdi, rax
        je      .LBB0_2
        call    operator delete(void*)
.LBB0_2:
        add     rsp, 56
        ret
```
(about the same as `to_string`).

**Comment by vitaut** [comment]
-O2 is even smaller:

```
% g++ test.cc -O2 -I include -std=c++17 src/format.cc -DNDEBUG
% strip a.out
% ls -l a.out
-rwxr-xr-x  1 viz  staff  87120 May  9 14:06 a.out
```

**Comment by vitaut** [comment]
BTW `master` is more godbolt-friendly: https://godbolt.org/z/32vXx-

**Comment by sztomi** [comment]
So why am I getting such different numbers in the compiler explorer I linked?

**Comment by vitaut** [comment]
That's just template code that would be removed by linker. You can include `fmt/core.h` instead of `fmt/format.h` to get rid of it.

**Comment by vitaut** [comment]
See also http://www.zverovich.net/2020/05/21/reducing-library-size.html
