### ISSUE TITLE
Sprintf is broken in 6.2.1

### ISSUE THREAD

**Issue by blackyblack** [fmtlib/fmt#1679]
When including printf.h (#include <fmt/printf.h>) fmt namespace leaks to the higher level so all methods after the header are in the fmt:: namespace. Does not happen after downgrade to the 6.2.0.

**Comment by vitaut** [comment]
I wasn't able to repro:

```c++
#include <fmt/printf.h>

void f() {}

int main() {
  f(); // compiles, fmt::f() doesn't
  fmt::print("{}", 42);
}
```
Please provide an self-contained example illustrating the issue.

**Comment by blackyblack** [comment]
It seems problem occurs when interferring with spdlog (https://github.com/gabime/spdlog).
Example:
`#ifndef FMT_HEADER_ONLY
#define FMT_HEADER_ONLY
#endif //FMT_HEADER_ONLY

#include <spdlog/spdlog.h>
#include <fmt/format.h>

void f() {}

int main() {
  f(); // compiles, fmt::f() doesn't
  fmt::print("{}", 42);
}`

Compiles ok.

`#ifndef FMT_HEADER_ONLY
#define FMT_HEADER_ONLY
#endif //FMT_HEADER_ONLY

#include <spdlog/spdlog.h>
#include <fmt/printf.h>

void f() {}

int main() {
  f(); // compiles, fmt::f() doesn't
  fmt::print("{}", 42);
}`

Does not compile. Namespace leaks out.

**Comment by vitaut** [comment]
Doesn't look like an {fmt} issue, please report to spdlog. IIRC spdlog has a way to replace the bundled {fmt} with an external one.
