### ISSUE TITLE
Document the differences between {fmt} and std::format

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#1686]
From #1379:

> It would be very helpful to have a note somewhere about discrepancies between fmt/format.h and std::format in C++20.

**Comment by DBJDBJ** [comment]
@vitaut  I am not knowledgeable about a ceremony ... but who or how is giving you some time frame when to incorporate this into `<format>`?  I assume clang, gnu and msft will take from you that header on some date? Or they will just go ahead and implement it and then ask you to approve? And what about compiler vendors? Is WG21 coordinating any of this? Interesting ...

**Comment by foonathan** [comment]
They will implement it mostly from scratch using the formal specification here: http://eel.is/c++draft/format

**Comment by DBJDBJ** [comment]
Excuse my ignorance, I know that is possible to do. But. Is it not to be expected Victor's implementation is of the best quality? Tried and tested and such ... 

None of them writes "bugless code", so why not just cooperating here on the reference implementation? 

Disclosure: I am not keen on log philosophical threads (anywhere) but this strikes me as odd ... Why would I use (by definition and possibly) inferior implementation when I have this one here?

DBJ

**Comment by vitaut** [comment]
> Is it not to be expected Victor's implementation is of the best quality?

It is both of the best and of the worst quality because it's the only implementation right now.

Implementers are welcome to use {fmt} or any portion of it as they see fit.

**Comment by foonathan** [comment]
An issue with fmt is that it has a lot of workarounds for various older compilers and weird OSes. A standard library implementation of a C++20 feature probably has fewer compatibility issues to worry about. They also need to _Uglify the implementation, so they can't directly copy it anyway.

**Comment by DBJDBJ** [comment]
I am glad everybody is having fun. Who is uglifying and who is copying @foonathan? 

Basically there is no answer to "...Why would I use (by definition and possibly) inferior implementation when I have this one here?."

**Comment by foonathan** [comment]
> "Why would I use (by definition and possibly) inferior implementation when I have this one here?."

1. It might support too many older systems with lots of workarounds that can be cleaned up.
2. The implementation can leverage other C++20 library features they have to implement anyway, like `<charconv>`.
3. The implementation has to use _Ugly or __ugly identifiers, so can't use this one directly without renaming a lot.

**Comment by DBJDBJ** [comment]
Many thanks ...

**Comment by jdemeule** [comment]
Hello,

Speaking about difference between {fmt} and std::format, there are a point about floating point formatting that I do not understand.
In {fmt}, format("{}", 0.) will return “0.0”, as far as my research go, this is to follow python behavior.
However in the C++ specification, no type for double is specified as:

> “[…] equivalent to `to_chars(first, last, value)`"

where the effect is described as:

> "value is converted to a string in the style of printf in the "C" locale. The conversion specifier is f or e, chosen according to the requirement for a shortest representation (see above); a tie is resolved in favor of f."

And the "above" note is:

> "The functions that take a floating-point value but not a precision parameter ensure that the string representation consists of the smallest number of characters such that there is at least one digit before the radix point (if present) and parsing the representation using the corresponding from_­chars function recovers value exactly".

We miss currently several implementation of to_chars to double check the behavior, the only one implemented is the Microsoft one and it seems that to_chars(…, …, 0.) without precision return [“0”](https://github.com/microsoft/STL/blob/66b0885e308a88ff5db0481c95123dcfa6f3cbeb/tests/std/tests/P0067R5_charconv/double_to_chars_test_cases.hpp#L83).
Did I miss understood something or do we face a difference between {fmt} and std::format?

Thanks for your input.

**Comment by vitaut** [comment]
Looks like a minor difference, we should change it to follow the spec.

**Comment by vitaut** [comment]
The docs now have a section describing the differences: https://fmt.dev/dev/api.html#compatibility-with-c-20-std-format. Most of the differences have already been eliminated.

**Comment by schaerfo** [comment]
Hello, I am from the future. The piece of documentation mentioned above is now located at: https://fmt.dev/dev/api/#compatibility-with-c20-stdformat

(Please don't delete, Google led me here instead of directly to the documentation)

**Comment by vitaut** [comment]
Fixed the link, thanks.
