### ISSUE TITLE
Macro for default format of user structs

### ISSUE THREAD

**Issue by aminya** [fmtlib/fmt#1690]
It would be very nice if there was a macro to adapt a struct and define a default printing method for it.
```
FMT_Struct(A, a, b, c);  // defines a formatter<T> method
```

There is a similar functionality in boost:

(but it requires calling `boost::fusion::for_each(obj, std::cout << arg1 << "\n");` manually):
```c++
#include <string>
#include <iostream>
#include <boost/fusion/adapted/struct.hpp>
#include <boost/fusion/include/for_each.hpp>
#include <boost/phoenix/phoenix.hpp>
using boost::phoenix::arg_names::arg1;

struct A
{
    int a;
    int b;
    std::string c;
};

BOOST_FUSION_ADAPT_STRUCT(A, a, b, c);

int main()
{
    const A obj = { 1, 2, "Hi!" };
    boost::fusion::for_each(obj, std::cout << arg1 << "\n");
};
```
------------------

You can also use a macro from MACE::reflect:
http://bytemaster.github.io/mace/group__mace__reflect__typeinfo.html
http://bytemaster.github.io/mace/reflect_8hpp.html#a4cc4edb664826109b34fdf28909bd0a3
```c++
  struct A {  std::string hello; };
  struct B : A { 
    std::string world;  
    int other;
  };

  MACE_REFLECT( A, (hello) )
  MACE_REFLECT_DERIVED( B, (A), (world)(other) )
```

In the future, once we have [Reflection TS](https://www.bing.com/videos/search?q=Reflection+TS&docid=608007407070154070&mid=2DDFB89D928DCEE49F902DDFB89D928DCEE49F90&view=detail&FORM=VIRE), we can use the standard libraries.

**Comment by vitaut** [comment]
Thanks for the suggestions. I am not sure it belongs to the core library but you can do it via the extension API.
