### ISSUE TITLE
better options for thousands

### ISSUE THREAD

**Issue by cruisercoder** [fmtlib/fmt#1695]
It would be nice if there were additional and easier options to specify comma formatting.  Setting the global locale affects stream output in surprising ways, and it seems a bit heavy to include it in every fmt argument just to get it and include an additional header.

auto s = fmt::format(std::locale("en_US.UTF-8"), "{:n}", 1234567890);

Could we get a fmt only global to set?

**Comment by vitaut** [comment]
This already works (https://godbolt.org/z/uDnssH):

```c++
auto s = fmt::format(std::locale("en_US.UTF-8"), "{:n}", 1234567890);
```

You can wrap it in your own function to avoid passing the locale explicitly or using the global locale.

**Comment by cruisercoder** [comment]
That's an ok option, although it takes users out of the library a bit.  I'm also wondering if there is a known cost to passing it it and/or using it whether or not use {:n} so I know what users are paying for when I redirect them the wrapped function.

**Comment by vitaut** [comment]
Locale-aware formatting is slower than locale-independent one but not that bad. `fmt::format(loc, "{:L}", n)` is roughly 70% faster than `ostringstream`:

```
------------------------------------------------------------------------
Benchmark              Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------
ostringstream      18281 ns        18245 ns        40207 items_per_second=5.48095M/s
format_locale      10798 ns        10779 ns        59411 items_per_second=9.27736M/s
```

**Comment by cruisercoder** [comment]
now that we have a locale independent comma separator function, would it be possible to regular  :L format specifier in a non-local context?
