### ISSUE TITLE
Please document compiling shared libraries

### ISSUE THREAD

**Issue by sab24** [fmtlib/fmt#1701]
Hi,

The CMake config by default does not generate .so files on Linux. This is done by setting 
-DBUILD_SHARED_LIBS=1 in the cmake command as in
```
cd fmt
mkdir build
cd build
cmake  -DBUILD_SHARED_LIBS=1  ..
make
```

Please document this somewhere, it can save some time for those who need it.

**Comment by vitaut** [comment]
It's already documented in https://fmt.dev/latest/usage.html#building-the-library but thanks for the suggestion.

**Comment by sab24** [comment]
Ah, sorry, I searched for dynamic library, not shared library.
