### ISSUE TITLE
support vformat_to into an external buffer?

### ISSUE THREAD

**Issue by 0x8000-0000** [fmtlib/fmt#1704]
I have tried formatting using vformat_to into a buffer that I manage:

```
std::vector<char> myBuf;
fmt::vformat_to(std::back_inserter(myBuf), format, args);
```

But this fails to compile since there is no such specialization. Is it missing intentionally, or was just a "nobody asked for it yet" case?

**Comment by 0x8000-0000** [comment]
The reason I'm not trying to avoid `fmt::basic_memory_buffer` is because I'm going to std::move the contents of that vector across an API boundary and I would like to keep `fmt` out of the interface, and I don't want to pay for an extra memcpy.

**Comment by 0x8000-0000** [comment]
https://github.com/fmtlib/fmt/blob/51bf9cfacb644659e5d9c7e6fe66396726f2f4f4/include/fmt/core.h#L1720

Do we need here to indicate that std::vector<Char> is contiguous?

**Comment by vitaut** [comment]
> Do we need here to indicate that std::vector is contiguous?

Not here for reasons I explained in the PR but you can mark it as contiguous in your code.
