### ISSUE TITLE
C2491 error in MSVC2019

### ISSUE THREAD

**Issue by patlecat** [fmtlib/fmt#1710]
When using this in my code with MSVC2019 under Win10 using C++17, I get the error C2491:
`Error C2491: 'fmt::v6::format_error::~format_error': definition of dllimport function not allowed (1, 1)`

```
#include <fmt/core.h>
std::string sf= fmt::format("I'd rather be {1} than {0}.", "right", "happy");
fmt::print("Hello, {}!", "world");  // Python-like format string syntax
```

**Comment by vitaut** [comment]
Are you trying to use a shared library and header-only mode?

**Comment by patlecat** [comment]
Could be, but I honestly don't know since vcpkg is doing it's magic behind the scenes. What is the header-only include file(s) to use instead?

**Comment by vitaut** [comment]
> What is the header-only include file(s) to use instead?

Just usual `fmt/format.h` etc. See also https://fmt.dev/latest/usage.html#usage-with-cmake

Closing for now since I wasn't able to repro (https://godbolt.org/z/8RTuAV) but feel free to reopen with more details.

**Comment by patlecat** [comment]
@vitaut Actually since I'm not using CMake (yet) I found that it was necessary to use this line and simply copy all the header files to my project instead. Maybe you want to add this info for MSVC users?
`#define FMT_HEADER_ONLY`

**Comment by vitaut** [comment]
Use of header-only mode is discouraged.
