### ISSUE TITLE
C4910 warning treated as error VS 2019

### ISSUE THREAD

**Issue by sunnlok** [fmtlib/fmt#1712]
I am getting
`
format.h(762,44):error C2220: the following warning is treated as an error
format.h(762,44): warning C4910: 'fmt::v6::detail::basic_data<void>': '__declspec(dllexport)' and 'extern' are incompatible on an explicit instantiation
`
when trying to compile fmt via cmake.
No special options are set.

**Comment by vitaut** [comment]
What library version do you use?

**Comment by sunnlok** [comment]
For fmt? I pulled from master.

**Comment by vitaut** [comment]
Could you give a commit hash? master is a moving target.

**Comment by sunnlok** [comment]
that would be 16aec06179a2c2661be77fd9ba3b202955de0c0b

**Comment by vitaut** [comment]
The warning should be fixed in https://github.com/fmtlib/fmt/commit/795b47a7b56c0e6c64a90159373d88f80994f885. Thanks for reporting.
