### ISSUE TITLE
How to use fmt in Clion project?

### ISSUE THREAD

**Issue by Zhukovdpua** [fmtlib/fmt#1713]
I completed cmake build and make without errors:
`mkdir build`
`cd build`
`cmake ..`
`make`

What I should do next to use fmt in Clion project?
When trying to write `#include <fmt/core.h>` in a source code I get `fmt/core.h: No such file or directory`

I have ubuntu 20.04

**Comment by vitaut** [comment]
You should add fmt's include directory to the include path. Please refer to the CLion documentation on how to do it.
