### ISSUE TITLE
The type of width and precision arguments is not validated at compile-time

### ISSUE THREAD

**Issue by HolyBlackCat** [fmtlib/fmt#1715]
Those two lines:
```
fmt::format(FMT_STRING("{:{}}"), 12.3, "");
fmt::format(FMT_STRING("{:.{}}"), 12.3, "");
```
both compile and throw exceptions at runtime, due to width/precision argument type not being integral.

Since other similar problems are diagnosed at compile-time when using `FMT_STRING`, it should probably happen here as well.

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/48e0a59222f2e1200193fd83a7c55ea3879dd8dc. Thanks for catching this.
