### ISSUE TITLE
DeepCode discovered a possible leak

### ISSUE THREAD

**Issue by patlecat** [fmtlib/fmt#1718]
Running deepcode on this lib it detected this possible leak in core.h [(DeepCode):](https://www.deepcode.ai/)

> Leaking memory. typed_node [:1285] is allocated on the heap and never freed. In function push [:1284] .
> Line 1285
[Problem description](https://www.deepcode.ai/app/gh/fmtlib/fmt/795b47a7b56c0e6c64a90159373d88f80994f885/_/%2Finclude%2Ffmt%2Fcore.h/cpp%2Fdc%2FCppMemoryLeak/1285/code)

**Comment by vitaut** [comment]
The memory is owned by [`unique_ptr`](https://en.cppreference.com/w/cpp/memory/unique_ptr): https://github.com/fmtlib/fmt/blob/795b47a7b56c0e6c64a90159373d88f80994f885/include/fmt/core.h#L1285
