### ISSUE TITLE
Next major release?

### ISSUE THREAD

**Issue by TerensTare** [fmtlib/fmt#1719]
I recently read your interesting article [here](https://www.zverovich.net/2020/05/21/reducing-library-size.html) about breaking changes coming to {fmt}. I got immeadiately "attracted" by the benefits that these changes will bring to the library and its users, so I decided to ask: is there a planned release date for those changes?

**Comment by vitaut** [comment]
No specific date but the plan is to have the new release in the next few months. In the meantime you can use `master` - it has all the improvements and is quite stable.
