### ISSUE TITLE
is fmt support CUDA ?

### ISSUE THREAD

**Issue by lindadoudou** [fmtlib/fmt#1720]
| env | value |
| :-- | :-- |
| system | Ubuntu |
| gcc | 7.5 |
| cuda | 10.0.130 |
| cmake | 3.16.5 |
| fmt | 6.2.2 |

I find out the cuda test code didn't real work on gpu.
![image](https://user-images.githubusercontent.com/13118142/84254592-01876e00-ab44-11ea-9a7e-34d5c4e13168.png)
It's more like use nvcc build normal "cpu" code.

so I add some cuda test.
![image](https://user-images.githubusercontent.com/13118142/84254969-883c4b00-ab44-11ea-827b-9a921830d1ef.png)
![image](https://user-images.githubusercontent.com/13118142/84254989-95f1d080-ab44-11ea-9dbe-a47accde2147.png)

Then, I try to use fmt in `__global__` function, here comes the problem.
![image](https://user-images.githubusercontent.com/13118142/84255197-dc472f80-ab44-11ea-9e51-1e7f30bb6bf6.png)

![image](https://user-images.githubusercontent.com/13118142/84255289-fb45c180-ab44-11ea-99ab-bc3192cdb95f.png)

- `fmt::format` is a host function, and only device function can be called in global function.
- fmt relays on std functions, but std is not support in cuda

So, is fmt support cuda ?????

**Comment by Petross404** [comment]
What is that supposed to mean?

**Comment by lindadoudou** [comment]
fmt won't work on gpu.

**Comment by vitaut** [comment]
{fmt} should compile with CUDA and work on host but not on GPU AFAIK.
