### ISSUE TITLE
FMT_ENFORCE_COMPILE_STRING does not work with FMT_HEADER_ONLY

### ISSUE THREAD

**Issue by marc-groundctl** [fmtlib/fmt#1723]
When I attempt to compile the following file, it fails because `format-inl.h` uses format strings without wrapping them in `FMT_STRING`.
```c++
#define FMT_ENFORCE_COMPILE_STRING
#define FMT_HEADER_ONLY

#include <fmt/format.h>
```

Godbolt sample: https://godbolt.org/z/dbyxF2

**Comment by vitaut** [comment]
This configuration is not supported - you should use the {fmt} as a library (the default) with `FMT_ENFORCE_COMPILE_STRING`.

**Comment by dnmiller** [comment]
Can you add this to the API documentation? I was about to submit the same issue before discovering this.

**Comment by vitaut** [comment]
This works with the current version: https://godbolt.org/z/jqesM8K5j.
