### ISSUE TITLE
6.2.1: Inconsistent formatting between Windows and Linux

### ISSUE THREAD

**Issue by 0x8000-0000** [fmtlib/fmt#1726]
Considering some code like this:

```
std::chrono::system_clock::time_point timestamp;

...
fmt::print("{:>10}\n", timestamp - getStartTime());
```

Windows builds prints:
```
2840[1/10000000]s
```

Linux build prints:
```
139916ns
```

**Comment by mwinterb** [comment]
That's to be expected. system_clock::duration on MSVC matches the precision of Windows's FILETIME, which is 10ths of microseconds. And libstdc++ uses nanoseconds.

**Comment by 0x8000-0000** [comment]
Understood; so if I want consistency I should not use fmt/chrono.h but instead convert duration to long and add my own time suffix?

Will std::format produce consistent formatting of chrono elements?

**Comment by vitaut** [comment]
You can cast duration to the units you want to get consistent output both with {fmt} and `std::format`. `system_clock` is system-specific by design.
