### ISSUE TITLE
6.2.1 Unresolved external symbol with MSVC

### ISSUE THREAD

**Issue by arookas** [fmtlib/fmt#1731]
I have a C++ .EXE that embeds {fmt} 6.2.1, and a C++ .DLL that is compiled against the .EXE. I define `FMT_EXPORT` when building the executable. and `FMT_SHARED` when building the library.

If I understand the source correctly, this should declare all necessary symbols `__declspec(dllexport)` and `__declspec(dllimport)`; however, I'm getting unresolved symbol errors when I'm building the DLL:

```
unresolved external symbol "void __cdecl fmt::v6::detail::assert_fail(char const *,int,char const *)"
unresolved external symbol "public: void __thiscall fmt::v6::detail::error_handler::on_error(char const *)"
unresolved external symbol "public: virtual __thiscall fmt::v6::format_error::~format_error(void)"
unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl fmt::v6::detail::grouping_impl<char>(class fmt::v6::detail::locale_ref)"
unresolved external symbol "char __cdecl fmt::v6::detail::thousands_sep_impl<char>(class fmt::v6::detail::locale_ref)"
unresolved external symbol "char __cdecl fmt::v6::detail::decimal_point_impl<char>(class fmt::v6::detail::locale_ref)"
unresolved external symbol "int __cdecl fmt::v6::detail::format_float<double>(double,int,struct fmt::v6::detail::float_specs,class fmt::v6::detail::buffer<char> &)"
unresolved external symbol "int __cdecl fmt::v6::detail::format_float<long double>(long double,int,struct fmt::v6::detail::float_specs,class fmt::v6::detail::buffer<char> &)"
unresolved external symbol "int __cdecl fmt::v6::detail::snprintf_float<double>(double,int,struct fmt::v6::detail::float_specs,class fmt::v6::detail::buffer<char> &)"
unresolved external symbol "int __cdecl fmt::v6::detail::snprintf_float<long double>(long double,int,struct fmt::v6::detail::float_specs,class fmt::v6::detail::buffer<char> &)"
unresolved external symbol "public: static unsigned int const * const fmt::v6::detail::basic_data<void>::zero_or_powers_of_10_32"
unresolved external symbol "public: static unsigned __int64 const * const fmt::v6::detail::basic_data<void>::zero_or_powers_of_10_64"
unresolved external symbol "public: static char const * const fmt::v6::detail::basic_data<void>::digits"
unresolved external symbol "public: static char const * const fmt::v6::detail::basic_data<void>::hex_digits"
unresolved external symbol "public: static char const * const fmt::v6::detail::basic_data<void>::signs"
unresolved external symbol "public: static char const * const fmt::v6::detail::basic_data<void>::left_padding_shifts"
unresolved external symbol "public: static char const * const fmt::v6::detail::basic_data<void>::right_padding_shifts"
```

What am I doing wrong?

**Comment by vitaut** [comment]
> I define FMT_EXPORT when building the executable. and FMT_SHARED when building the library.

It's the other way around. I recommend using CMake which will defined all of these for you automatically: https://github.com/fmtlib/fmt/blob/5aa5c9873877b79c2588d5f33ad9910b02488b00/CMakeLists.txt#L231

**Comment by arookas** [comment]
Thanks for the reply!

In my case, I have two separate projects:
- An executable file (my game engine) which embeds and integrates {fmt} statically
- A DLL (my game's code) which has access to and uses the {fmt} code exported from the executable.

Tinkering with it some more yesterday, I noticed _format.cc_ eventually includes _core.h_. I had defined `FMT_EXPORT` in a wrapper header for _core.h_ instead of through the compiler (this way the DLL doesn't need to care about defining `FMT_SHARED`). For some reason this made the symbols not exported, even though in all other cases they're properly marked for export.

Do you know of a clean way to work around this? Right now I'm modifying _format.cc_ to include my wrapper header (and thus also define `FMT_EXPORT`).

**Comment by vitaut** [comment]
I recommend using compiler flags instead of wrapper headers.
