### ISSUE TITLE
Could excessive arguments be included in compile-time check at least via define?

### ISSUE THREAD

**Issue by Predelnik** [fmtlib/fmt#1732]
Currently excessive arguments are not checked in compile-time and always ignored, but in reality they are similar to unused arguments in a function and may signify some bug or typo which happened e.g. during refactoring. As an example I found a format string which had wrong format specifier `%s` instead of `{}` and this problem was just silently ignored.

Example of the program where I would like to see compile-time errors:
https://gcc.godbolt.org/z/zeZMin

**Comment by vitaut** [comment]
There are no plans to turn this into an error but you can write your own formatting function with extra an extra check.

**Comment by Predelnik** [comment]
Well then is there any easy way to get number of replacement fields in `FMT_STRING` in compile-time? Otherwise it sounds like manually rewriting compile time checking.

**Comment by vitaut** [comment]
You could use https://github.com/fmtlib/fmt/blob/5aa5c9873877b79c2588d5f33ad9910b02488b00/include/fmt/format.h#L2585 but note that it's a part of the internal API.

**Comment by t-b** [comment]
@Predelnik Can you share your patch? I'd be interested in having excess argument number errors as well.
