### ISSUE TITLE
fmt::format_to fails to compile with incomplete pointer type

### ISSUE THREAD

**Issue by sehoffmann** [fmtlib/fmt#1733]
```
include/spdlog/fmt/bundled/core.h:985:20: error: invalid application of 'sizeof' to an incomplete type 'lws'
    static_assert(!sizeof(T), "formatting of non-void pointers is disallowed");
```

One argument to the format call is of type `struct lws*` which is a pointer to an incomplete/forward-declared struct.

As a workaround the pointer can be cast to `void*` before passing it to `fmt::format_to()`

**Comment by vitaut** [comment]
This is intentional. Pointers should be wrapped in `fmt::ptr` or cast to `void*` when printing:

```c++
fmt::print("{}", fmt::ptr(p));
```
