### ISSUE TITLE
Format.h introduces indirectly macros which cause that std::min becomes invalid code in header-only mode

### ISSUE THREAD

**Issue by bernd5** [fmtlib/fmt#1735]
Hello,

unfortunately "format.h" / "format-inl.h" includes "windows.h" which defines a lot of macros like 
```
#define min(a,b)            (((a) < (b)) ? (a) : (b))
```
This breaks for example calls to std::min ...

So please do not add non standard headers which define macros. Macros are really bad!

If you need to call some windows specific os-functions you can just declare and call them.
This works only for functions defined in kernel32.dll because this dll is loaded always.

**Comment by vitaut** [comment]
`format-inl.h` includes `windows.h` with min/max disabled: https://github.com/fmtlib/fmt/blob/9a4cc88426831595a29147cc32539c8141752267/include/fmt/format-inl.h#L27-L31

Also it's recommended to use {fmt} as a static library in which case `windows.h` is not included from public headers at all.
