### ISSUE TITLE
Build fails "format.h:76:13: error: expected unqualified-id before ‘!’ token..." & more

### ISSUE THREAD

**Issue by chrispsommers** [fmtlib/fmt#1742]
make
[  1%] Building CXX object CMakeFiles/fmt.dir/src/format.cc.o
In file included from /home/chris/fmt/include/fmt/format-inl.h:20:0,
                 from /home/chris/fmt/src/format.cc:8:
/home/chris/fmt/include/fmt/format.h:76:13: error: expected unqualified-id before ‘!’ token
         && (!defined(__EDG_VERSION__) || __EDG_VERSION__ >= 520)
...
...hundreds of lines more of errors

$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

commit 4e94c649f9a6767b2e359842aee0a2e771ae1835
failed with previous commit too

I can build branch 4.x just fine.

**Comment by vitaut** [comment]
Will be fixed in https://github.com/fmtlib/fmt/commit/978521bb8111ac70b3b64173c1c4299df794e1d8. Thanks for reporting.

**Comment by chrispsommers** [comment]
I just verified the fix works, thanks for the super-fast response!
