### ISSUE TITLE
visibility attribute not supported warnings on mingw64

### ISSUE THREAD

**Issue by mizvekov** [fmtlib/fmt#1743]
Compiling with GCC 10.1 for windows (mingw64) produces a bunch of these kinds of warnings:

```
fmt/format-inl.h: In member function '__dt_del ':
fmt\format-inl.h(213,18): warning G2331D7DD: visibility attribute not supported in this configuration; ignored [-Wattributes]
    213 | FMT_API FMT_FUNC format_error::~format_error() FMT_NOEXCEPT = default;
```

So yeah, visibility attribute is not supported for windows target.

Note: `__has_atttribute` is not an option to solve this, it will still evaluate to true.

**Comment by vitaut** [comment]
Removed the non-portable attribute in https://github.com/fmtlib/fmt/commit/3135d95fd9030b2e324b8745e00b3597072e8c7b. Thanks for reporting.
