### ISSUE TITLE
Bundled Hedley library incompatible with Intel C++ for windows

### ISSUE THREAD

**Issue by mizvekov** [fmtlib/fmt#1745]
I created this issue upstream: [https://github.com/nemequ/hedley/issues/39](url)
I discovered when trying to use fmt. You should update it when that is fixed :)

**Comment by vitaut** [comment]
I'm not sure I understand the problem. Do you get an error when compiling {fmt} with Intel compiler?

**Comment by mizvekov** [comment]
Yes, it will define macros to expand to GCC `__attribute__` syntax, which is not supported for Intel compiler on windows, where Intel compiler goes for MSVC dialect compatibility instead of GCC (which is the case for the linux version).
Currently Hedley assumes only the linux variant exists.

**Comment by vitaut** [comment]
Could you provide a PR?

**Comment by mizvekov** [comment]
Well this quick and dirty patch is enough to get it compiling:
```
--- a/external/json/inc/nlohmann/thirdparty/hedley/hedley.hpp
+++ b/external/json/inc/nlohmann/thirdparty/hedley/hedley.hpp
@@ -111,7 +111,7 @@
 #if defined(JSON_HEDLEY_INTEL_VERSION)
     #undef JSON_HEDLEY_INTEL_VERSION
 #endif
-#if defined(__INTEL_COMPILER) && defined(__INTEL_COMPILER_UPDATE)
+#if !defined(_MSC_VER) && defined(__INTEL_COMPILER) && defined(__INTEL_COMPILER_UPDATE)
     #define JSON_HEDLEY_INTEL_VERSION JSON_HEDLEY_VERSION_ENCODE(__INTEL_COMPILER / 100, __INTEL_COMPILER % 100, __INTEL_COMPILER_UPDATE)
 #elif defined(__INTEL_COMPILER)
     #define JSON_HEDLEY_INTEL_VERSION JSON_HEDLEY_VERSION_ENCODE(__INTEL_COMPILER / 100, __INTEL_COMPILER % 100, 0)
```
But the problem is, a proper PR would not only stop using GCC dialect, but also make Hedley implement the MSVC dialect it supports, and that is more involved.

**Comment by vitaut** [comment]
I still don't follow. What is Hedley and how it is related to {fmt}?

**Comment by mizvekov** [comment]
Oh my, I am so sorry, this was supposed to go to the `nlohmann/json` project instead. I had something else for you I might come back later, sorry please close!

**Comment by vitaut** [comment]
No worries =)
