### ISSUE TITLE
-Wsign-conversion warning with Clang10 on Windows

### ISSUE THREAD

**Issue by 0x8000-0000** [fmtlib/fmt#1747]
include\fmt/format.h(560,71): error: implicit conversion changes signedness: 'std::size_t' (aka 'unsigned long long') to 'stdext::checked_array_iterator<char *>::difference_type' (aka 'long long') [-Werror,-Wsign-conversion]
  std::uninitialized_copy(begin, end, make_checked(ptr_, capacity_) + size_);

**Comment by vitaut** [comment]
Which {fmt} version?

**Comment by 0x0000-7C00** [comment]
>=6.2.1 with Clang 10 on Windows 10

**Comment by 0x0000-7C00** [comment]
{fmt} >= 6.2.1

**Comment by 0x8000-0000** [comment]
https://github.com/fmtlib/fmt/blob/5de62af604a5ada7bb1de579227210423976b092/include/fmt/format.h#L569

**Comment by 0x8000-0000** [comment]
https://docs.microsoft.com/en-us/cpp/standard-library/checked-array-iterator-class?view=vs-2019#op_add takes a stdext::checked_array_iterator<T*>::difference_type as argument to operator +.
