### ISSUE TITLE
Need some help sort out this crash

### ISSUE THREAD

**Issue by shawncao** [fmtlib/fmt#1748]
I build my binary on one Ubuntu machine (gcc version 9.3.0 (Ubuntu 9.3.0-11ubuntu0~18.04.1)), I pack it into a docker image. 
On another Ubuntu machine, I ensured the same version GCC installed and run this container crashed with these stacks

Since the frame points to fmt - I came here seeking some help, it may or may not related to libfmt. 
BTW, I tried compile/link my binary with either -DFMT_HEADER_ONLY=1 on or off, behaviors the same. 

I would appreciate any suggestions/questions how to root cause this... thanks!

------------------------------------------------------------------------------------------------

node_1    | *** Aborted at 1593657835 (Unix time, try 'date -d @1593657835') ***
node_1    | *** Signal 4 (SIGILL) (0x4671de) received by PID 1 (pthread TID 0x7f6784e6fb40) (linux TID 1) (code: illegal operand), stack trace: ***
node_1    |     @ 000000000068a3db folly::symbolizer::(anonymous namespace)::signalHandler(int, siginfo_t*, void*)
node_1    |                        /home/shawncao/folly/folly/experimental/symbolizer/SignalHandler.cpp:438
node_1    |     @ 0000000000000000 (unknown)
node_1    |     @ 00000000004671de fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::detail::buffer<char> >, char>::iterator fmt::v6::vformat_to<fmt::v6::arg_formatter<std::back_insert_iterator<fmt:
:v6::detail::buffer<char> >, char>, char, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::detail::buffer<char> >, char> >(fmt::v6::arg_formatter<std::back_insert_iterator<fmt::v6::detail::buffer<c
har> >, char>::iterator, fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::detail::buffer<char> >, char> >, fmt::v6::detail::locale_ref)
node_1    |                        -> /build/gcc-9-zxnWP6/gcc-9-9.3.0/build/x86_64-linux-gnu/libgcc/../../../src/libgcc/config/i386/crtfastmath.c
node_1    |     @ 00000000004549fa RunServer()
node_1    |                        -> /build/gcc-9-zxnWP6/gcc-9-9.3.0/build/x86_64-linux-gnu/libgcc/../../../src/libgcc/config/i386/crtfastmath.c
node_1    |     @ 000000000044869e main
node_1    |                        -> /build/gcc-9-zxnWP6/gcc-9-9.3.0/build/x86_64-linux-gnu/libgcc/../../../src/libgcc/config/i386/crtfastmath.c
node_1    |     @ 0000000000021b96 __libc_start_main
node_1    |     @ 000000000044ff89 _start
node_1    |                        -> /build/gcc-9-zxnWP6/gcc-9-9.3.0/build/x86_64-linux-gnu/libgcc/../../../src/libgcc/config/i386/crtfastmath.c

**Comment by vitaut** [comment]
`SIGILL` means "illegal instruction", so this doesn't look related to {fmt}. Make sure that you compile your code in a way compatible with the target platform.

**Comment by shawncao** [comment]
Thanks @vitaut !
Sorry for asking more. I compared build host cpuinfo and target host cpuinfo, I'm not sure which property matters and how to adjust my build (cmake) script to make it compatible, If you know how to look into this, could you please give a little more guidance, appreciate it.

> build host
`processor	: 35
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
stepping	: 4
microcode	: 0x200005e
cpu MHz		: 3400.002
cache size	: 25344 KB
physical id	: 0
siblings	: 36
core id		: 17
cpu cores	: 18
apicid		: 35
initial apicid	: 35
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 6000.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual`

> target host
`processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU @ 2.30GHz
stepping        : 0
microcode       : 0x1
cpu MHz         : 2300.000
cache size      : 46080 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma
 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 4600.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual`

**Comment by shawncao** [comment]
Never mind - I found I had native arch optimization in my build option. 
I removed the `-march=native` from my build script, and now it works well.
