### ISSUE TITLE
"Deprecated" specifiers

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#1752]
> * Replaced the ``'n'`` format specifier with ``'L'`` for compatibility with
>   ``std::format`` (`#1624 <https://github.com/fmtlib/fmt/issues/1624>`_).
>   The ``'n'`` specifier can be enabled via the ``FMT_DEPRECATED_N_SPECIFIER``
>   macro.
> 
> * The ``'='`` format specifier is now disabled by default for compatibility with
>   ``std::format``. It can be enabled via the ``FMT_DEPRECATED_NUMERIC_ALIGN``
>   macro.

Compatibility with ``std::format`` is nice, but what about compatibility with Python?
If these are marked as "deprecated", for how long they will be available?
Will the syntax diverge even more in the future?

**Comment by vitaut** [comment]
> Compatibility with `std::format` is nice, but what about compatibility with Python?

Compatibility with Python has been discussed and in these particular cases it has been decided that improving the syntax was more important.

> If these are marked as "deprecated", for how long they will be available?

They will be available until the next major release which normally happens once a year.

> Will the syntax diverge even more in the future?

It's very unlikely. There will have to be a very compelling reason to change the standard specs and both backward compatibility and Python compatibility will be taken into account.
