### ISSUE TITLE
Regression? undefined reference when using different compiler

### ISSUE THREAD

**Issue by Phygon** [fmtlib/fmt#1753]
I just tried to upgrade from fmt 6.2.1 to fmt 7.0.0.
I compiled fmt with the default compiler (GCC 8.3 on Debian Buster), while the application is compiled with the most current clang++.

Reduced example code:
```
#include <fmt/format.h>
int main()
{
        fmt::memory_buffer mb;
        fmt::format_to(mb, "Hello {}!", 42);
}
```
Compiled with:
`clang++ -std=c++14 -o test test.cpp -lfmt`

This results in the following error:
```
/usr/bin/ld: /tmp/test-cbfe70.o: in function `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::detail::buffer<char> >, char>::iterator fmt::v6::format_to<char [10], int, 500ul, char>(fmt::v6::basic_memory_buffer<char, 500ul, std::allocator<char> >&, char const (&) [10], int&&)':
test.cpp:(.text._ZN3fmt2v69format_toIA10_cJiELm500EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_6detail6bufferIT2_EEES7_E8iteratorERNS0_19basic_memory_bufferIS7_XT1_ESaIS7_EEERKT_DpOT0_[_ZN3fmt2v69format_toIA10_cJiELm500EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_6detail6bufferIT2_EEES7_E8iteratorERNS0_19basic_memory_bufferIS7_XT1_ESaIS7_EEERKT_DpOT0_]+0x88): undefined reference to `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::detail::buffer<char> >, char>::iterator fmt::v6::detail::vformat_to<char>(fmt::v6::detail::buffer<char>&, fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::detail::buffer<fmt::v6::type_identity<char>::type> >, fmt::v6::type_identity<char>::type> >)'
```
A similar error is printed when using clang++ for the fmt library and g++ for the test. No error if the compiler matches. With fmt 6.x, this also works without error.

**Comment by SpaceIm** [comment]
I have similar undefined references when fmt 7.0.0 is compiled as a shared lib and then consumed in a simple cpp executable (`FMT_SHARED` is defined of course)

**Comment by vitaut** [comment]
Interesting. For some reason gcc doesn't resolve the `buffer_context<char>` alias to `basic_format_context<...>` which results in a symbol mismatch.

**Comment by vitaut** [comment]
Here's a minimal repro: https://godbolt.org/z/4C2Bd8

**Comment by vitaut** [comment]
Also discussed here: https://twitter.com/vzverovich/status/1280338087579488256

**Comment by vitaut** [comment]
Worked around in https://github.com/fmtlib/fmt/commit/fbf3b943cc9a515d76956d8e766455201f11fd7d. Thanks for reporting.

**Comment by vitaut** [comment]
@Phygon, this looks like a bug in gcc so I recommend reporting there.
