### ISSUE TITLE
confusion over format.h vs core.h

### ISSUE THREAD

**Issue by PaulTopping** [fmtlib/fmt#1755]
Although I have searched here and on stackoverflow for hints as to which of these headers to use when, I am still very confused. Actually, my code compiles and runs fine regardless of whether I #include format.h or core.h but there's a hint that I would get better diagnostics with one over the other, though I forget which. There's reference to a header-only implementation in the docs but it isn't clear why there are two implementations and how to choose one over the other. In the 7.0 release notes it says, "It is still recommended to use fmt/core.h instead of fmt/format.h ..." but I'm not sure if that advice is to be followed in all cases. Finally, whatever the distinction between these two headers, their names give me no hint of their relationship. If anything, format.h sounds like it gives all library functionality but core.h gives on the essentials and leaves out some stuff. If so, what is left out?

**Comment by vitaut** [comment]
The documentation describes the differences between `fmt/core.h` and `fmt/format.h` (https://fmt.dev/latest/api.html):

> `fmt/core.h`: the core API providing argument handling facilities and a lightweight subset of formatting functions
> `fmt/format.h`: the full format API providing compile-time format string checks, output iterator and user-defined type support

and lists specific functions.

If you need any of "compile-time format string checks, output iterator and user-defined type support" then use `fmt/format.h`, otherwise use `fmt/core.h`.
