### ISSUE TITLE
\fmt\format.h(526): warning C26812: The enum type 'fmt::v7::detail::char8_type' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).

### ISSUE THREAD

**Issue by Zorono** [fmtlib/fmt#1759]

**Comment by vitaut** [comment]
This is not a compiler warning and this enum is not an enum class intentionally.

**Comment by Zorono** [comment]
yes it is...
Iam using Visual studio 2019 Community

**Comment by Zorono** [comment]
and the compiler is just recommending `enum class` instead...

**Comment by vitaut** [comment]
That's an analyzer warnings, it is known to produce a lot of noise.
