### ISSUE TITLE
Remove potentially allocating containers from integer_writer::on_num()

### ISSUE THREAD

**Issue by kammce** [fmtlib/fmt#1762]
## Setting

In the process of attempting to reduce the binary size impact of this library for an embedded project, I noticed that malloc/free and operator new/delete were being linked into the binary via the std::basic_string constructor. 

The sample code I used to make sure that no potentially allocating container was being used was the following:

```C++
#define FMT_HEADER_ONLY
#define FMT_STATIC_THOUSANDS_SEPARATOR ','
#define FMT_USE_FLOAT 0
#define FMT_USE_DOUBLE 0
#define FMT_USE_LONG_DOUBLE 0
#include "third_party/fmt-7.0.0/include/fmt/format.h"

#include <array>
#include <cstddef>

template <class T, size_t buffer_size>
class FormatBuffer
{
 public:
  using value_type = T;

  size_t size()
  {
    return size_;
  }

  size_t max_size()
  {
    return buffer_size;
  }

  void push_back(T & value)
  {
    buffer_[size_++] = value;
  }

  void push_back(const T & value)
  {
    buffer_[size_++] = value;
  }

  void push_back(T && value)
  {
    buffer_[size_++] = value;
  }

  T * data()
  {
    return buffer_.data();
  }

  size_t size_ = 0;
  std::array<T, buffer_size> buffer_{};
};

int main()
{
  FormatBuffer<char, 256> buffer;
  fmt::format_to_n(std::back_inserter(buffer), buffer.max_size(),
                    "Argument = {}", 5);
  return 0;
}
```

## Problem

This code shouldn't require the allocating functions to be pulled in, but it does. This is due to the fact that `integer_writer::on_num()` uses a `std::string` to hold its locale set of characters. Also, `basic_memory_buffer` uses `std::allocator` which will cause the allocating functions to be linked in as well. By switching `std::string` to `std::string_view` and from `basic_memory_buffer` to `std::array`, the linking of malloc and free can be eliminated, given the above approach.

**Comment by vitaut** [comment]
Closing for now per discussion in #1763 but a PR is welcome provided that it can be done in a non-intrusive way.

**Comment by kammce** [comment]
@vitaut thinking on this now, after looking back at the library from a clean slate, I wonder, does basic_memory_buffer, ever really allocate when used with the fmt library? In what scenario would the size grow beyond the given size, or the `fmt::inline_buffer_size` variable. Because if the basic_memory_buffer basically never allocates, then giving it the abort allocate may be reasonable. Maybe even if removing it all together could work as well.

**Comment by vitaut** [comment]
> does basic_memory_buffer, ever really allocate when used with the fmt library?

Yes, it's used in multiple places some of which can potentially allocate (one such case I mentioned in the PR). In the common case there are no allocations but we should handle exotic cases gracefully.
