### ISSUE TITLE
Build test posix-mock-test failed with MSVC static runtime (MT/MTd)

### ISSUE THREAD

**Issue by dvetutnev** [fmtlib/fmt#1765]
libucrt.lib(strtod.obj) : error LNK2005: _strtod_l already defined in posix-mock-test.cc.obj
libucrt.lib(wsetlocale.obj) : error LNK2005: _create_locale already defined in posix-mock-test.cc.obj
libucrt.lib(wsetlocale.obj) : error LNK2005: _free_locale already defined in posix-mock-test.cc.obj
bin\posix-mock-test.exe : fatal error LNK1169: one or more multiply defined symbols found

Build log: https://ci.appveyor.com/project/dvetutnev/conan-fmt/build/job/ny95310an2cms3ml
Version: 7.0.1
Tested on MSVC 2017 and MSVC 2019

**Comment by vitaut** [comment]
You should define the CMake variable `MSVC_BUILD_STATIC` when building with static runtime.

**Comment by dvetutnev** [comment]
May be rename this variable to MSVC_STATIC_RUNTIME?
And add autodetect by CMAKE_CXX_FLAGS?

**Comment by vitaut** [comment]
Sure, a PR would be welcome.
