### ISSUE TITLE
Undefined reference problem when using with cmake and libtorch.

### ISSUE THREAD

**Issue by kilasuelika** [fmtlib/fmt#1768]
I use following code in CMakeLists.txt to link with fmt and libtorch:

```
find_package(fmt)
target_link_libraries(mp fmt::fmt)

list(APPEND CMAKE_PREFIX_PATH ~/libtorch/share/cmake/Torch)
find_package(Torch)
target_link_libraries(mp ${TORCH_LIBRARIES})


```

Then when I use print() function, there is an error **undefined reference to fmt::v7::detail::vformat**.

However, if I don't use torch and only use fmt library, there is no problem and everything is OK.

**Comment by vitaut** [comment]
Could you post the full error message?

**Comment by kilasuelika** [comment]
> Could you post the full error message?

Now I confirm that the problem is due to `format()`, not `print()`. It looks like that this is a linking problem due to libtorch. Error:
```
<img width="958" alt="批注 2020-07-13 012859" src="https://user-images.githubusercontent.com/8265798/87252795-8ac5f380-c4a8-11ea-9c3c-ef078fa4cfc7.png">
```

Please see my minimum example to reproduce the problem.
CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.10)
project(main)
set(CMAKE_C_COMPILER /usr/bin/gcc CACHE PATH "" FORCE)
set(CMAKE_CXX_COMPILER /usr/bin/g++ CACHE PATH "" FORCE)

add_executable(mp src.cpp)

#Add fmt library
find_package(fmt)
target_link_libraries(mp fmt::fmt)

#torch
list(APPEND CMAKE_PREFIX_PATH ~/libtorch/share/cmake/Torch)
find_package(Torch)
target_link_libraries(mp ${TORCH_LIBRARIES})


target_compile_features(mp PUBLIC cxx_std_20)
add_custom_command(TARGET mp POST_BUILD
	COMMAND echo "----------------------------------------------"
	COMMAND ./mp
	COMMAND echo "----------------------------------------------")

```

src.cpp:
```
#include<iostream>
#include<fmt/core.h>
#include<torch/torch.h>

//using namespace std;
using std::cout, std::endl;
using namespace fmt;

int main(){
	//torch::Tensor a;
	std::cout<<format("Hello {}",789)<<std::endl;	
};

```
Remark:
1. If don't use libtorch. There is no problem.

**Comment by vitaut** [comment]
How does link command look like (you can get it with `VERBOSE=1 make`)?

**Comment by kilasuelika** [comment]
> How does link command look like (you can get it with `VERBOSE=1 make`)?

<img width="960" alt="Unt" src="https://user-images.githubusercontent.com/8265798/87452268-9b56a500-c633-11ea-9351-b7e4d1aba092.png">
Please see this picture.

**Comment by kilasuelika** [comment]
> How does link command look like (you can get it with `VERBOSE=1 make`)?

<img width="960" alt="Unt" src="https://user-images.githubusercontent.com/8265798/87453094-9b0ad980-c634-11ea-936a-b5322f5c49e4.png">
Please see this picture.

**Comment by kilasuelika** [comment]
> How does link command look like (you can get it with `VERBOSE=1 make`)?

Here is the result if don't use libtorch:
<img width="960" alt="批注 2020-07-15 004833" src="https://user-images.githubusercontent.com/8265798/87453408-0bb1f600-c635-11ea-9158-6b48ef9c2b12.png">

**Comment by vitaut** [comment]
The problem is that libtorch uses {fmt} as a header-only library https://github.com/pytorch/pytorch/blob/b952eaf668e3a7cb5f8a459526612f0ebb24c1f9/torch/CMakeLists.txt#L87 while you are trying to link with a static library. These configurations are mutually exclusive.

**Comment by kilasuelika** [comment]
> The problem is that libtorch uses {fmt} as a header-only library https://github.com/pytorch/pytorch/blob/b952eaf668e3a7cb5f8a459526612f0ebb24c1f9/torch/CMakeLists.txt#L87 while you are trying to link with a static library. These configurations are mutually exclusive.

Thank you so much!
