### ISSUE TITLE
FMT_COMPILE vs FMT_STRING vs ""_format()

### ISSUE THREAD

**Issue by leolchat** [fmtlib/fmt#1772]
The documentation is not extremely clear about the difference between the 3 ways I found to have compile-time format string checks. I would like to try to PR an improvement to the documentation, but first I need to be sure

- Is there a difference as to what they can check? In my quick survey I could not find an example rejected by one but not the others.
- Is there a preferred one? Compiler verbose output seems shorter with the `FMT_STRING` version, but not using a macro is nice, or is the speed boost from `FMT_COMPILE` usually worth it?

Bonus question, is there one which has a chance to land in `std::format`?

**Comment by vitaut** [comment]
> Is there a difference as to what they can check?

Yes, `FMT_STRING` always does compile-time checks while `_format` only if a compiler supports UDL templates extensions.

> Is there a preferred one?

`FMT_STRING` and `FMT_COMPILE` serve different purposes. If you only need checks then use `FMT_STRING`. If you want to avoid format string parsing overhead then use `FMT_COMPILE` (this is rarely needed) and note that:

> Format string compilation can generate more binary code compared to the default API and is only recommended in places where formatting is a performance bottleneck.

**Comment by leolchat** [comment]
Thanks for clarifying. I would say the documentation could be more explicit. I gave it a try.
