### ISSUE TITLE
How to increase performance for programs which do not use all the CPU cores at run-time?

### ISSUE THREAD

**Issue by simonhf** [fmtlib/fmt#1776]
Many programs have single threaded business logic for good reason; it's a lot simpler to develop. Or they are designed not to, or they don't need to use all the CPU cores available at run-time. So when you start adding instrumentation in the format of log lines, the more log lines output at run-time, the slower the program is going to run. Each call to `fmtlib` will effectively pause the actual business logic of the program for a short time, before resuming.

Is there a way to shorten that short pause even further by deferring the `fmtlib` business logic to another thread or process? For example, if the `fmtlib` call does different business logic (faster and simpler; i.e. copying memory) and instead of parsing and formatting, it only copies the format string and arguments to some kind of permanently allocated, round robin, working memory... then a different thread or process which can also see the copy of the format string and arguments, can perform the actual intended `fmtlib` business logic but on a different CPU core? Effectively moving `fmtlib` business logic from one CPU core to another. Let's say if the 'copy' only takes half the time of the regular `fmtlib` parsing and formatting, surely that means the program can output twice as many log lines in the same wall-clock time?

Does `fmtlib` already have similar functionality? Do any of its alternatives have such functionality? If not, how about creating it?

**Comment by vitaut** [comment]
No, but you could capture format string and arguments yourself and format them in a separate thread.
