### ISSUE TITLE
Reduce Binary Size by Removing <typename Uint> from int_writer

### ISSUE THREAD

**Issue by kammce** [fmtlib/fmt#1778]
## Current Situation

Current class template parameters for int_writer:

```C++
template <typename OutputIt, typename Char, typename UInt> struct int_writer {}
```

## Proposal

Removing `<typename UInt>` from the structure template parameters. This would eliminate a few of the template instances generated of the int_writer structure. Simply replacing the Uint with uint64_t showed a 2476 byte reduction for the following:

- Compiler: arm-none-eabi-gcc
- Processor: cortex-m3
- Optimization level: -Os -fno-lto
- float/double/long double all disabled

What do you all think? I'm thinking of either using the largest data size or something along those lines in order to eliminate this template parameter.

**Comment by kammce** [comment]
I understand that using the largest data type is a naive approach, but maybe some sort of type erasure can help to remove that template parameter.

**Comment by vitaut** [comment]
Thanks for the suggestion - I commented on the PR.

BTW you might want to try using format string compilation (https://fmt.dev/latest/api.html#compile-api) - this will give you more code per-call but potentially smaller overall binary if don't have too many formatting function calls.
