### ISSUE TITLE
cmake error with older cmakes on FMT 7.0

### ISSUE THREAD

**Issue by phlptp** [fmtlib/fmt#1779]
I am getting some errors on older CMake when using FMT as a subproject

```
CMake Error at dependencies/cmake/share/cmake-3.4/Modules/CMakeParseArguments.cmake:147 (set):
  set given invalid arguments for CACHE mode.
Call Stack (most recent call first):
  ThirdParty/fmtlib/CMakeLists.txt:31 (cmake_parse_arguments)
  ThirdParty/fmtlib/CMakeLists.txt:49 (set_verbose)
CMake Error at ThirdParty/fmtlib/CMakeLists.txt:33 (list):
  list sub-command REMOVE_AT requires list to be present.
Call Stack (most recent call first):
  ThirdParty/fmtlib/CMakeLists.txt:49 (set_verbose)
```

Specifically CMake 3.4  with gcc 4.9 
I tried a few things to bypass it but didn't work so far.   For the moment I am reverting back to 6.2.

This seems to have been introduced in #1702

**Comment by vitaut** [comment]
`cmake_parse_arguments` is broken in CMake 3.4 but I implemented a workaround in https://github.com/fmtlib/fmt/commit/18024853b6090746984fb23fe27e6f3525aa9820. Thanks for reporting.
