### ISSUE TITLE
unresolved external symbols while trying to include fmt

### ISSUE THREAD

**Issue by schpinkeldinkel** [fmtlib/fmt#1780]
windows powershell > cd fmt-master > bash
mkdir build
cd build
cmake -g"Visual Studio 16 2019 Win64" -DBUILD_SHARED_LIBS=TRUE ..
make
make test
//everything is okay so far, no errors. however as suggested by usage.html no visual studio sln or vproj files are generated anywhere. 

//c++ configured to use clang via
sudo apt-get install clang
sudo update-alternatives --config c++
//then selecting clang++
//otherwise i get cxx cant find compiler errors

//so i try to work with what i'm given...
c++>general>additional include directories = fmt-master/include
linker>gerneral>additional library directories = fmt-master/build
linker>input>addition dependencies = libfmt.a
//fmt-master/build includes libfmt.a, libfmt.so, libfmt.7, libfmt.7.0.1. i believe libfmt.a to be the most likely lib to link, though i tried to build through windows linux shell and no libfmt.a was produced.

// so i includes headers , on debug i receive unresolved external symbol errors on fmt::v7::vprint & fmt::v7::detail::vprint_mojibake in object files. 
//invalid or corrupt file libfmt.a
//does my project platform toolset need to be LLVM since i built fmt with clang++?

and so my issue is cmake doesn't seem to produce a library i can work with, is this due to my system wide c++ change to clang++, or some incorrect build variables? perhaps a missing component i need from visual studio installer? the fact no snl or vproj files were produced tells me i'm doing something wrong.

**Comment by vitaut** [comment]
I recommend using CMake: https://fmt.dev/latest/usage.html. It's hard to say what's wrong in your build configuration but since the test built successfully CMake build should work too.

**Comment by schpinkeldinkel** [comment]
sudo make install
//to install the library after building and tests, still are no VS files as suggested, and still same error persists. you can't comment even on why no VS files are generated?

**Comment by vitaut** [comment]
Please see https://cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html. Also StackOverflow might be a better question to ask general questions like this.
