### ISSUE TITLE
fmt::format_to_n with locale ':L' does not work correctly

### ISSUE THREAD

**Issue by stvriver** [fmtlib/fmt#1782]
I have the issue since I upgraded fmt to version 1.7.1 and built to dll.
In versions before 1.7.x I use "{:n}" for grouping numbers without any issue. Please take a look to the code below for details.

```
#include <iostream>
#include "fmt/format.h"
int main()
{
	try {
		std::locale::global(std::locale("en-US")); // "en_US.UTF-8";
	}
	catch (const std::exception& e)  {
		fmt::print("Set global locale to \"en-US\" failed: {}", e.what());
	}

	char buff[16] {};
	auto
	out = fmt::format_to_n(buff, std::size(buff), FMT_STRING("{} {}"), 12345, (char)67);
	fmt::print("{}\n", buff); // "12345 C", OK!

	memset(buff, 0, sizeof(buff));
	out = fmt::format_to_n(buff, std::size(buff), FMT_STRING("{:L} {}"), 12345, (char)67);
	fmt::print("{}\n", buff); // print " C,345", I expect "12,345 C".

	return 0;
}
```

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/b17d5c4f5d5c7dd9a0f5518f3a45e398098b2026. Thanks for reporting!

**Comment by stvriver** [comment]
Hi vitaut,

Could you please make a patch to 7.0.1 for walking around the issue?.
There are many improvements in version fmt-7.0.x, I do not want to downgrade back to fmt-6.x just to have a small feature.

Thanks.

**Comment by vitaut** [comment]
I plan to make another patch release shortly.

**Comment by vitaut** [comment]
https://github.com/fmtlib/fmt/releases/tag/7.0.2

**Comment by stvriver** [comment]
Thanks for your effort.
Unfortunately, running the sample (in my first post) with 7.0.2 shows the exact issue existing in 7.0.1.
However the issue does not happen in the "master".

**Comment by stvriver** [comment]
Did you update the fix to tags/7.0.2 or just to "master"? I have not found the way to test your fix.
Also, this issue has not been fixed, should you reopen it?

**Comment by vitaut** [comment]
`master`, releases are not updated retroactively.

**Comment by hangdongxue** [comment]
I tried 7.0.3 locale still not working for float number. e.g. if I set language as "italian". when print out decimal point, it prints as "." instead of ","

**Comment by vitaut** [comment]
```c++
#include <fmt/core.h>
#include <locale>

int main() {
  std::locale::global(std::locale("it_IT.UTF-8"));
  fmt::print("{:L}\n", 4.2);
}
```
prints 
```
4,2
```

**Comment by hangdongxue** [comment]
I try to print a float number with precision like
fmt::print("{1:.{0}f}", 1, 4.2);
it doesn't print out correct decimal point
it used to work in version 5

**Comment by vitaut** [comment]
Please open a separate issue.
