### ISSUE TITLE
join() forces const-ness on the range which prevents it accepting some range-v3 ranges

### ISSUE THREAD

**Issue by tonyelewis** [fmtlib/fmt#1784]
Thanks so much for all your fantastic work on fmt, standardisation and Tweeting.

The following attempt to combine range-v3 with fmt fails to compile under Clang or GCC (`-std=c++17 -fsyntax-only`) ([Godbolt](https://godbolt.org/z/9shjWc)) :

~~~cpp
#include <fmt/core.h>
#include <fmt/ranges.h>

#include <range/v3/view/filter.hpp>

using ::std::array;
using ::std::literals::string_literals::operator""s;
using ::std::string;

namespace views = ::ranges::views;

int main() {
    const array some_strs{ "a"s, "bb"s, "ccc"s };
    ::fmt::join(
        some_strs | views::filter(
            [] (const string &x) { return x.length() != 2; }
        )
        ,
        ""
    );
}
~~~

I'm pretty sure the problem is caused by the `const`s around [`format.h:3388`](https://github.com/fmtlib/fmt/blob/7a01c9c52320e7f42a31882b00378fd940b68d31/include/fmt/format.h#L3388). The range-v3 design involves some views (such as `filter` in the example above) updating internal state (eg a cached iterator) so they have `const`-only `begin()` / `end()`, which means a `const` reference to such a view is not a valid range. See "View const-ness" on https://ericniebler.github.io/range-v3/ for more info.

**Comment by vitaut** [comment]
Thanks for the suggestion. A PR to make the range requirements more compatible with ranges-v3 would be welcome.

**Comment by tonyelewis** [comment]
Thanks. I've submitted #1786 as you'll see above.

BTW, I'm seeing various test failures in GCC and under sanitizers. Are these know issues or should I submit issues for them?

**Comment by vitaut** [comment]
> Are these know issues or should I submit issues for them?

Please submit an issue.

**Comment by tonyelewis** [comment]
Thanks.
