### ISSUE TITLE
I think {fmt} should have an option to cmake configuration to switch building for a dll or a static library.

### ISSUE THREAD

**Issue by stvriver** [fmtlib/fmt#1785]
Currently the default build type for Visual Studio is static library. Every time after generating projects for Visual Studio build from cmake configuration, I have to manually change build type from static to dynamic dll, defining FMT_EXPORT, and changing file extension from .lib to .dll. I think it's better to add one more option to the cmake file to automate the switch.

**Comment by vitaut** [comment]
Thanks for the suggestion but CMake has an option for this already: https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html
