### ISSUE TITLE
Cannot pass named arg twice

### ISSUE THREAD

**Issue by artemyv** [fmtlib/fmt#1788]
I have a template function that receives fmt::arg list and has to call 2 other functions each one calls the fmt::format as a result compilation error core.h(1653): error C2338: passing views as lvalues is disallowed occurs
Simplified example

`template <typename... Args>
inline std::string formatmock(const std::string& format_str, const std::string& format_str2,  Args&&... args) {
    fmt::format(format_str, (args)...) +  fmt::format(format_str2,std::forward<Args>(args)...);
}

TEST(FmtArg, namedpasssimple)
{
    std::string message = formatmock("The answer is {value}","The answer is {value}", fmt::arg("value", 42));
    ASSERT_EQ(message, "The answer is 42The answer is 42");
}`

How can I pass named arguments twice?

**Comment by vitaut** [comment]
You can do it as follows:

```c++
#include <fmt/core.h>

template <typename... Args>
std::string formatmock(const std::string& format_str,
                       const std::string& format_str2, Args&&... args) {
  return fmt::format(format_str, Args(args)...) +
         fmt::format(format_str2, Args(args)...);
}

int main() {
  formatmock("The answer is {value}", "The answer is {value}",
             fmt::arg("value", 42));
}
```
https://godbolt.org/z/7KKjzx

**Comment by artemyv** [comment]
Thank you, it is working
