### ISSUE TITLE
Proper way to disable exceptions

### ISSUE THREAD

**Issue by hsdk123** [fmtlib/fmt#1793]
Hi, I was wondering if setting `FMT_EXCEPTIONS` to 0 would be the way to go, or if there's something else. I also thought it might be useful to have a cmake option to configure this as well.

**Comment by vitaut** [comment]
`FMT_EXCEPTIONS` is normally defined automatically when you compile with exceptions disabled. You can use the usual CMake mechanism to pass compiler options.
