### ISSUE TITLE
Colors dont work on a normal console window

### ISSUE THREAD

**Issue by auth12** [fmtlib/fmt#1794]
fmt::print(fg(fmt::color::green) | fmt::emphasis::bold, "$> ");

example output : 
`[1m[38;2;000;128;000m$> [0m27ec3180000
[1m[38;2;000;128;000m$> [0mcurrent server version 0.1.0.
[1m[38;2;000;128;000m$> [0m1:FpK4]E-.4i->0.1.0 2`

**Comment by foonathan** [comment]
What console/terminal emulator are you using? On what OS?

**Comment by auth12** [comment]
Windows, I guess fmt doesn't support windows console colors, I have to use SetConsoleTextAttribute in order to print colored text

**Comment by DHowett** [comment]
Sorry, I know this is an old thread. To get control sequences working in the Windows console, you will want to `SetConsoleMode(...)` to enable `ENABLE_VIRTUAL_TERMINAL_PROCESSING` on the output handle. This is not the default for compatibility reasons (sorry!)

**Comment by rebb** [comment]
> 
> 
> Sorry, I know this is an old thread. To get control sequences working in the Windows console, you will want to `SetConsoleMode(...)` to enable `ENABLE_VIRTUAL_TERMINAL_PROCESSING` on the output handle. This is not the default for compatibility reasons (sorry!)

Should this work on a Windows 7 system ?
I tried to do it using the following snippet, but it didn't help - control sequences still just print directly.
I wonder how the colorama library for Python handles this.

```
HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
DWORD dwMode = 0;
GetConsoleMode(hOut, &dwMode);
dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
SetConsoleMode(hOut, dwMode);
```

**Comment by vitaut** [comment]
Color support is available starting from Windows 10: https://en.wikipedia.org/wiki/ANSI_escape_code#DOS,_OS/2,_and_Windows.

**Comment by ThePizzaMuncher** [comment]
> Sorry, I know this is an old thread. To get control sequences working in the Windows console, you will want to `SetConsoleMode(...)` to enable `ENABLE_VIRTUAL_TERMINAL_PROCESSING` on the output handle. This is not the default for compatibility reasons (sorry!)

Sorry for necroing _again_, but I can’t get that to work when I include FMT. When I don’t include FMT, it functions, but if I do I get issues like `identifier "STD_INPUT_HANDLE" is undefined` (on `HANDLE h0ut = GetStdHandle(STD_INPUT_HANDLE);`),  `identifier "ENABLE_VIRTUAL_TERMINAL_PROCESSING" is undefined` and `too few arguments in function call` (on `SetConsoleMode(ENABLE_VIRTUAL_TERMINAL_PROCESSING)`)

**Comment by vitaut** [comment]
`STD_INPUT_HANDLE` is not used in the current version of {fmt}.

**Comment by ThePizzaMuncher** [comment]
This was a combination of things randomly working and not working, and me being a complete oaf.
