### ISSUE TITLE
Missing named argument substitued by positional argument

### ISSUE THREAD

**Issue by thpoll83** [fmtlib/fmt#1796]
I tested this with 7.0.1 (but couldn't see a fitting fix in 7.0.2):

The following line will produce the string "1.0-1.000000", but there is no named argument specified:
auto expr = fmt::format("{namedArg}-{:f}", 1.0);

I expected an exception.

It correctly fails to compile when using  fmt::format(FMT_STRING("{namedArg}-{:f}", 1.0));

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/21c8b5c1421ae04df00a97e4c396ffb7b26916bc. Thanks for reporting!
