### ISSUE TITLE
Alternate form of general format is missing trailing zeros

### ISSUE THREAD

**Issue by Kingcom** [fmtlib/fmt#1797]
According to the syntax documentation, the alternate form should cause general format floating point values to not suppress trailing zeros:
> The '#' option causes the “alternate form” to be used for the conversion. [...] In addition, for 'g' and 'G' conversions, trailing zeros are not removed from the result.

This seems to be unimplemented with the current master, ```parse_float_type_spec``` only uses the alt flag to determine if a decimal point should be shown. As a result, the following format string does not show any trailing zeros:
```
fmt::print("{:#.17g}", 0.875);
```

I've tested various older versions, and it seems to be a regression introduced between 6.0.0 and 6.1.0.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/4fd95e4b4d18be6be8fd8f6c8d685ad62e43de46. Thanks for reporting.
