### ISSUE TITLE
Linker error when using wide char literals with fmt/core.h

### ISSUE THREAD

**Issue by Kingcom** [fmtlib/fmt#1799]
The following code results in a linker error due to a missing fmt::v7::detail::vformat<wchar_t,0> symbol using Visual Studio 2017:
```
#include <fmt/core.h>
...
fmt::format(L"");
```

Including ```fmt/format.h``` fixes the error.

**Comment by vitaut** [comment]
That's expected, quoting the documentation:

> fmt/format.h defines the full format API providing compile-time format string checks, wide string, output iterator and user-defined type support.

**Comment by Kingcom** [comment]
Okay. I expected something like that, but thought it could have been unintentional as the error only occurs when linking, while most other errors are already checked and caught during the compilation.
