### ISSUE TITLE
Alignment of integer has changed

### ISSUE THREAD

**Issue by gsjaardema** [fmtlib/fmt#1801]
If i use the `L` or `n` formatting of integers with a specified value for `FMT_STATIC_THOUSANDS_SEPARATOR`, the default alignment seems to have changed with version 7.0.0 and later.  Below is the behavior I am seeing:
```
(base) s1041980:fmt((HEAD detached at 7.0.0))> cat test.C
#define FMT_STATIC_THOUSANDS_SEPARATOR ','
#define FMT_DEPRECATED_N_SPECIFIER

#include <string>
#include <fmt/ostream.h>

int main() {
  fmt::print("Check alignment of integer {:14L}\n", 1000);
}
```

Version 7.0.0,  Note that the integer that is output is left-justified in the 14 width field:
```
(base) s1041980:fmt((HEAD detached at 7.0.0))> g++ -DFMT_HEADER_ONLY --std=c++14 -o align_test test.C -I include; ./align_test
Check alignment of integer 1,000
```
Now, with version 6.2.1, the integer is right-justified (which should be the default as I read documentation):
```
(base) s1041980:fmt((HEAD detached at 6.2.1))> g++ -DFMT_HEADER_ONLY --std=c++14 -o align_test test.C -I include; ./align_test
Check alignment of integer          1,000
```

Am I using this correctly?  If so, was this an intentional change in the default alignment?
Thanks.

**Comment by vitaut** [comment]
> Am I using this correctly?

Yes.

> If so, was this an intentional change in the default alignment?

No.

That's a bug in locale-specific integer formatting. Fixed in https://github.com/fmtlib/fmt/commit/279d698e1b37f3f0a9b5c21b12198894d31c381d, thanks for reporting.

**Comment by gsjaardema** [comment]
Thanks for the quick response.  Awesome library.
