### ISSUE TITLE
fmt::join with lambda formatter

### ISSUE THREAD

**Issue by Warchant** [fmtlib/fmt#1805]
Do you think it is worth to add an overload to fmt::join, which accepts a lambda formatter? I.e.

```C++
std::set<2DPoint*> set;
std::string f = fmt::join(set.begin(), set.end(), ';', 
      [](2DPoint* t){ 
        return fmt::format("x={}, y={}", t->x, t->y);
      });
```

This construction is really simpler (than adding custom formatter) when you need to log this type once. In my case, I want to format and print a message when assert fails.

**Comment by vitaut** [comment]
Sure, a PR is welcome.
