### ISSUE TITLE
Width type checks with FMT_COMPILE()

### ISSUE THREAD

**Issue by OnurKader** [fmtlib/fmt#1809]
I assume it's the same problem with #1715, so feel free to close this if it's a duplicate

```cpp
	std::string str = fmt::format(FMT_COMPILE("{:>{}}"), "Whoops", 15);
	fmt::print("Wow: {}\n", str);
```

Results in a runtime exception
```
terminate called after throwing an instance of 'fmt::v7::format_error'
  what():  width is not integer
```

**Comment by vitaut** [comment]
Dynamic width wasn't implemented in `FMT_COMPILE` but it is as of https://github.com/fmtlib/fmt/commit/54daa0864afb57e9d12c26f50a4c4e2f1e2d5dea.

**Comment by OnurKader** [comment]
Thank you <3

Have a lovely day!
