### ISSUE TITLE
7.0.3 FMT_STRING() causing "unused type alias" warning on MacOS with clang 9.0

### ISSUE THREAD

**Issue by madscientist** [fmtlib/fmt#1824]
I've just updated to fmt 7.0.3 and I'm seeing a warning from _some_ uses of FMT_STRING() on MacOS (only: works fine on GNU/Linux with GCC and on Windows with MSVC 16 (2019)).  Weirdly, not all uses cause the warning and I've so far not been successful trying to create a cut-down version.

I wondered if anyone here had any hints or tips or have seen this before; if not I'll keep trying to generate a repro case.

I'm using clang 9.0.1 installed via macports:
```
$ /opt/local/bin/clang++-mp-9.0 --version
clang version 9.0.1
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-9.0/bin
```
and in the uses where FMT_STRING() fails I get warnings like this:
```
mycode.cpp:60:39: error: unused type alias 'char_type' [-Werror,-Wunused-local-typedef]
                    String::fmtString(FMT_STRING("{} overflow unary minus for {}"),
                                      ^
.../common/fmt/include/fmt/format.h:2865:23: note: expanded from macro 'FMT_STRING'
#define FMT_STRING(s) FMT_STRING_IMPL(s, fmt::compile_string)
                      ^
.../common/fmt/include/fmt/format.h:2846:13: note: expanded from macro 'FMT_STRING_IMPL'
      using char_type = fmt::remove_cvref_t<decltype(s[0])>;      \
            ^
```
Other uses of FMT_STRING() (in this same build) are OK and builds of this same code work with GCC and MSVC.

**Comment by madscientist** [comment]
Examining the code that fails, it's in a deep set of templates calling templates, etc. that I simply have not been able to unravel into a reproducible test case.  Although I'm generally skeptical of these accusations, my suspicion is that this is a compiler issue (esp. since the same code works fine in GCC and MSVC).  Unfortunately MacOS support is not that important to us (it's used only internally for some people who like to develop on MacOS and I don't have a MacOS system myself) and I've run out of time to invest in this issue, so I've added `-Wno-unused-local-typedef` to my clang builds and am moving on.

This issue can be closed, or if someone wants to dig into it I can try to scrape together some more time to try things / answer questions.

**Comment by vitaut** [comment]
The alias is used here: https://github.com/fmtlib/fmt/blob/951e0d23331e3f4678527ea1b9e1b3821df40dc1/include/fmt/format.h#L2893 so this looks like an issue with clang - please report there.

**Comment by pauldreik** [comment]
For reference to whoever encounters this in the future:

This warning happened also to me compiling a C++17 project using Qt Creator on Debian Buster. I believe the warning comes from the builtin clang checks in Qt Creator, rather than from the compilation. It happens also on the Qt Creator version in Ubuntu 20.04.

The way to silence it is the following patch:
```patch
diff --git a/include/fmt/format.h b/include/fmt/format.h
index 633fa119..401ffc6d 100644
--- a/include/fmt/format.h
+++ b/include/fmt/format.h
@@ -2140,7 +2140,7 @@ constexpr auto compile_string_to_view(std_string_view<Char> s)
     /* Use the hidden visibility as a workaround for a GCC bug (#1973). */ \
     /* Use a macro-like name to avoid shadowing warnings. */               \
     struct FMT_GCC_VISIBILITY_HIDDEN FMT_COMPILE_STRING : base {           \
-      using char_type = fmt::remove_cvref_t<decltype(s[0])>;               \
+      using char_type FMT_MAYBE_UNUSED = fmt::remove_cvref_t<decltype(s[0])>;               \
       FMT_MAYBE_UNUSED FMT_CONSTEXPR explicit                              \
       operator fmt::basic_string_view<char_type>() const {                 \
         return fmt::detail::compile_string_to_view<char_type>(s);          \
```

The annoying thing for me is that I can not reproduce it anymore, but I believe it started happening when formatting std::string_view objects.

**Comment by madscientist** [comment]
Just for clarity we don't use Qt Creator.  I'm not sure exactly what is meant by "builtin clang checks in Qt Creator"; maybe you mean the default set of clang compilation options that Qt Creator uses when it compiles code?  It could be that there is some overlap between those options and what we use of course.
