### ISSUE TITLE
Build warning C4127 on Windows using MSVC 19.26.288806 in C++20 mode

### ISSUE THREAD

**Issue by mbeckh** [fmtlib/fmt#1825]
The code
```cpp
std::string x = fmt::format("{}", std::chrono::system_clock::now().time_since_epoch())
```
produces warning C4127 ("conditional expression is constant, consider using 'if constexpr' statement instead") for the following lines
```text
fmt\chrono.h: line 75
fmt\chrono.h: line 83
fmt\chrono.h: line 94
fmt\chrono.h: line 96
fmt\chrono.h: line 197
fmt\chrono.h: line 213
```
Latest verification of warning with master at commit f9f02df.

**Comment by vitaut** [comment]
https://github.com/fmtlib/fmt/blob/master/include/fmt/chrono.h#L75 and similar should be wrapped in a call to `const_check`. A PR is welcome.

**Comment by vitaut** [comment]
Suppressed the warnings in #1825.
