### ISSUE TITLE
Feature Request: fmt::join that takes an invocable member or function

### ISSUE THREAD

**Issue by operativeF** [fmtlib/fmt#1826]
There are quite a few times where we need to access a member object or function of an object being iterated over. For example:
```
// We must do this:
std::vector<std::filesystem::path> paths { some paths... };
for(auto&& path : paths)
{
    fmt::print("{}\n", path.string());
}

// Or something like this:
std::string all_paths;
for(auto&& path : paths)
{
    all_paths += fmt::format("{}\n", path.string());
}
fmt::print("{}", all_paths);

// Ideally, we could do something like this:
fmt::print("{}", fmt::join(paths, "\n", &std::filesystem::path::string);
```
I say ideally, but I've already implemented this. You just give it an invocable object and it invokes it per item in the container. I haven't added constraints on the object yet, so there's still some work to be done. Is this something that is a good idea, or are there pitfalls somewhere? I used std::invoke here, so it requires C++17 and I haven't looked into making it available for C++11 or 14, though it doesn't look difficult (just like another local implementation of string_view).

**Comment by vitaut** [comment]
Thanks for the suggestion. I don't think this needs to be in the core library - it's easy to implement yourself (which you already did =)).
