### ISSUE TITLE
compiling errors fmt 4.1.0 on gnu compiler 4.4.7

### ISSUE THREAD

**Issue by rounaksingh** [fmtlib/fmt#1833]
Hi,
As per the documentation, fmt 4.1.0 supports old compiler. So, I am trying to compile fmt 4.1.0 on gnu compiler 4.4.7. But it is giving me errors while compiling. I understand that the variadic templates are not supported in this compiler. Is it possible to compile? Am I missing some argument to cmake  or make?

Thank you very much

Output of cmake: I am running cmake in the build directory of fmt project.

$ cmake ..
-- CMake version: 2.8.12.2
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Version: 4.1.0
-- Build type: Release
-- Performing Test HAVE_STD_CPP11_FLAG
-- Performing Test HAVE_STD_CPP11_FLAG - Failed
-- Performing Test HAVE_STD_CPP0X_FLAG
-- Performing Test HAVE_STD_CPP0X_FLAG - Success
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES - Failed
-- Performing Test SUPPORTS_INITIALIZER_LIST
-- Performing Test SUPPORTS_INITIALIZER_LIST - Success
-- Performing Test SUPPORTS_ENUM_BASE
-- Performing Test SUPPORTS_ENUM_BASE - Success
-- Performing Test SUPPORTS_TYPE_TRAITS
-- Performing Test SUPPORTS_TYPE_TRAITS - Failed
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Failed
-- Looking for open
-- Looking for open - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test HAVE_FNO_DELETE_NULL_POINTER_CHECKS
-- Performing Test HAVE_FNO_DELETE_NULL_POINTER_CHECKS - Success
-- Performing Test HAVE_FNO_EXCEPTIONS_FLAG
-- Performing Test HAVE_FNO_EXCEPTIONS_FLAG - Success
-- Configuring done
-- Generating done
-- Build files have been written to: ~/Ro/fmt-4.1.0/build

Errors while make:
$ make
Scanning dependencies of target fmt
[  3%] Building CXX object fmt/CMakeFiles/fmt.dir/posix.cc.o
In file included from ~/Ro/fmt-4.1.0/fmt/posix.h:30,
                 from ~/Ro/fmt-4.1.0/fmt/posix.cc:15:
~/Ro/fmt-4.1.0/fmt/format.h:4058: error: ‘begin’ is not a member of ‘std’
~/Ro/fmt-4.1.0/fmt/format.h:4058: error: ‘begin’ is not a member of ‘std’
~/Ro/fmt-4.1.0/fmt/format.h:4058: error: ‘begin’ is not a member of ‘std’
~/Ro/fmt-4.1.0/fmt/format.h:4058: error: ‘begin’ is not a member of ‘std’
~/Ro/fmt-4.1.0/fmt/format.h:4058: error: template argument 2 is invalid
~/Ro/fmt-4.1.0/fmt/format.h:4064: error: ‘begin’ is not a member of ‘std’
~/Ro/fmt-4.1.0/fmt/format.h:4064: error: ‘begin’ is not a member of ‘std’
~/Ro/fmt-4.1.0/fmt/format.h:4064: error: ‘begin’ is not a member of ‘std’
~/Ro/fmt-4.1.0/fmt/format.h:4064: error: ‘begin’ is not a member of ‘std’
~/Ro/fmt-4.1.0/fmt/format.h:4064: error: template argument 2 is invalid
make[2]: *** [fmt/CMakeFiles/fmt.dir/posix.cc.o] Error 1
make[1]: *** [fmt/CMakeFiles/fmt.dir/all] Error 2
make: *** [all] Error 2

gnu compiler: 
$ g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)

**Comment by rounaksingh** [comment]
I just found a same previous issue. #692
I will try.

**Comment by rounaksingh** [comment]
Hi 
Update on issue:
I tried compiling the latest commit from branch 4.x . Attached file shows the terminal output of cmake and make. After compiling, libfmt.a is created, although the tests are not completely compiling. Attached log file shows the output of make test.
[fmt_cmake_make_maketest.txt](https://github.com/fmtlib/fmt/files/5104592/fmt_cmake_make_maketest.txt)

I tried testing the libfmt.a file . It seems to be doing its job. I think the test failed are gtest and gmock related. Please let me know if I am correct. 

********************************************************************************
*Requesting the admin to change the link at the bottom (for the old compiler) on the doc website https://fmt.dev/latest/index.html from tag 4.1.0 to the branch 4.x . or even a mention of the branch would work*
**********************************************************************************

Thank you!

**Comment by vitaut** [comment]
Closing since this is fixed in #692 but a PR to fix tests and/or update the docs is welcome.
