### ISSUE TITLE
Localization specifier :L not working on Apple and :n not working on MSVC or WSL-GNU

### ISSUE THREAD

**Issue by frankkopp** [fmtlib/fmt#1839]
I have noticed that the same code on PC (MSVC 19.26), Ubuntu on WSL with g++-10 and Apple (AppleClang 12.0) does not behave similar:

On PC PC (MSVC 19.26) and g++-10 on WSL only {:L} works for localiued numbers - {:n} does NOT work
On AppleClang 12.0 only {:n} works but not {:L}

My test code:
```
#include <fmt/core.h>

#include <gtest/gtest.h>
using testing::Eq;

TEST(Playground, format) {
  fmt::print("{:L}", 123456789);
}
```

On Apple with {:L} this crashes with error message: "C++ exception with description "invalid type specifier" thrown in the test body."
Same on PC and g++ but with the other specifier.

I retrieve the fmt lib through CMAKE FetchContent (see below) and can therefore be sure to have the same version on the three different platforms. 

CMAKE:
```
# FMT
message("Downloading/Update FMT")
FetchContent_Declare(
        fmt
        GIT_REPOSITORY https://github.com/fmtlib/fmt.git
        GIT_TAG 7.0.3
)
FetchContent_MakeAvailable(fmt)
include_directories(
        ${fmt_SOURCE_DIR}/include
)
```

Bug?

**Comment by vitaut** [comment]
I was not able to repro: your example compiles and runs without error on macOS with {fmt} 7.0.3. You might have a different version installed somewhere.
