### ISSUE TITLE
Add support for ranges with non-const begin/end to fmt/ranges.h

### ISSUE THREAD

**Issue by dvhwgumby** [fmtlib/fmt#1840]
Is there a plan to support c++20 ranges (filter and transform) with fmtlib?

I was confused that ranges.h doesn't support C++ ranges, so if not you might want to change the name of the header.

For ease or checking, here's cppreference's example for ranges adapted for fmt.

```
#include <iostream>
#include <ranges>
#include <vector>

#include <fmt/format.h>
#include <fmt/ranges.h>

int main () {

    std::vector<int> ints{0,1,2,3,4,5};
    auto even = [](int i){ return 0 == i % 2; };
    auto square = [](int i) { return i * i; };
 
    auto filtered    { ints | std::views::filter(even) };
    auto transformed { filtered | std::views::transform(square) };

    for (int i : transformed)
      std::cout << i << ' ';
    std::cout << std::endl;

    fmt::print("join raw vector: {}\n", fmt::join(ints, ","));

    // won't compile
    //fmt::print("filtered range: {}\n", filtered);
    //fmt::print("join filtered range: {}\n", fmt::join(filtered, ",");
 }
```

**Comment by vitaut** [comment]
`fmt::join` already supports that as of #1786: https://godbolt.org/z/Wehsza. A PR to do the same elsewhere is welcome.

**Comment by dvhwgumby** [comment]
Thanks.  I don't know how to get godbolt to load nonstandard libraries so could only send you source code.   std::views::transform works too.

So not sure what PR you might be thinking of: that
```
fmt::print("fmt raw vector: {}\n", some_view);
```
should print the same as 
```
fmt::print("fmt raw vector: {}\n", some_vector_of_ints);
```
?

thanks,

**Comment by vitaut** [comment]
> So not sure what PR you might be thinking of: that ... should print the same as ... ?

Yes

**Comment by vitaut** [comment]
Support for ranges with non-const `begin`/`end` has been added in #1953.
