### ISSUE TITLE
fmt/color.h: fmt::format_to not implemented for fmt::text_style

### ISSUE THREAD

**Issue by Naios** [fmtlib/fmt#1842]
e66ba16923be2a1bcb6b841df7a64a0b3ac4be4d

Currently it is not possible to format a colorized string to a `fmt::memory_buffer` using `fmt::format_to(memory_buffer, fmt::text_style(...` or through any other function because the overload is missing.

It would be great if the missing overload for `fmt::format_to(memory_buffer, fmt::text_style` could be added.

Overall the color API is inconsistent with the format API and not all format functions support a `fmt::text_style` overload. Maybe the color API could be aligned in general with the format API.

**Comment by Andersama** [comment]
I also just ran into this issue. My work around though not completely templated looks like this:
```c
template <size_t N> struct ansi_esc_sequence {
	uint8_t tail;
	uint8_t opts[N];
};

template <size_t N> struct fmt::formatter<ansi_esc_sequence<N>> : public fmt::formatter<string_view> {
	template <typename FormatContext>
	auto format(const ansi_esc_sequence<N>& p, FormatContext& ctx) noexcept {
		if constexpr (N > 0) {
			return fmt::format_to(ctx.out(), "\033[{}{}"sv, fmt::join(&p.opts[0], &p.opts[0] + N, ";"),
				(char)p.tail);
		}
		else {
			return fmt::format_to(ctx.out(), "\033[{}"sv, (char)p.tail);
		}
	}
};
```
It's a bit of a pain to specify the colors w/ the ansi sequence this way, definitely in full agreement it was strange to try to avoid this by using color.h only to find format_to wasn't implemented.

**Comment by vitaut** [comment]
The color API is for terminal output thus it supports only a subset of functions.
