### ISSUE TITLE
Unable to use <chrono> formatting in string literals

### ISSUE THREAD

**Issue by mattgodbolt** [fmtlib/fmt#1846]
In this example:

```cpp
#include <fmt/format.h>
#include <fmt/chrono.h>

#include <chrono>
#include <string>

std::string test1(std::chrono::system_clock::time_point time) {
  auto t = std::chrono::system_clock::to_time_t(time);
  return fmt::format("The date is {:%FT%TZ}.", fmt::localtime(t));
}

std::string test2(std::chrono::system_clock::time_point time) {
  using namespace fmt::literals;
  auto t = std::chrono::system_clock::to_time_t(time);
  return "The date is {:%FT%TZ}."_format(fmt::localtime(t));
}
```

The `test2` fails to compile, seemingly as the constructor for formatter is not constexpr : https://github.com/fmtlib/fmt/blob/e66ba16923be2a1bcb6b841df7a64a0b3ac4be4d/include/fmt/chrono.h#L1081 (assuming that's even possible?)

**Comment by mattgodbolt** [comment]
(See also https://godbolt.org/z/WY3MT5 )

**Comment by vitaut** [comment]
Thanks for the report. That's expected: `std::tm` formatter is not `constexpr` because it relies on system APIs and therefore it doesn't support compile-time checks including `constexpr` `_format`.

**Comment by vitaut** [comment]
The solution is to use `fmt::format` instead of `_format` which is recommended anyway.

**Comment by mattgodbolt** [comment]
Oh! This is news to me: is `_format()` to be deprecated? I've been using it liberally since the beginning, and so it would be good to know if so!

**Comment by vitaut** [comment]
> is _format() to be deprecated?

No plans to deprecate it but it's an uportable hack and not recommended.

**Comment by mattgodbolt** [comment]
Thanks @vitaut ! That's a shame; but I'll start migrating away from it.
