### ISSUE TITLE
Shorthand for 0x{:X}

### ISSUE THREAD

**Issue by VelocityRa** [fmtlib/fmt#1849]
## Issue
Capitalized hex numbers formatted like `0xDEADBEEF` are the most common, yet afaik there's no quick way to do this besides typing out `0x{:X}` for every number.

There _is_ the "alternate form" specifier `{:#x}`, but currently it prints one of the following depending on whether it's `x` or `X`:
- `0xdeadbeef`
Lowercase hex is not very common and it being next to the `x` is not as easy to read.
- `0XDEADBEEF`
I have never, ever, seen `0X` as a hex prefix anywhere.

## Proposed solutions
1) Make `{:#X}` use `0x` as prefix instead of `0X`.
2) Some form of toggle for this.

I suggest `1)` since as I said I have looked at a _lot_ of hex numbers and never seen it once being used.

Thanks for your time!

**Comment by vitaut** [comment]
Thanks for the suggestion. There are no plans to extend format specifications but you can wrap a number in your own type and provide a custom formatter.

**Comment by VelocityRa** [comment]
Wrap every single number I need to print just for this?
I print numbers in hundreds of places. This sounds like more work and maintenance burden than having to type `0x` each time.

**Comment by vitaut** [comment]
Another option is to write your own formatting function that maps double to your type with custom formatting. {fmt}'s standard format specifiers are pretty much fixed at this point for compatibility with Python and `std::format`.

**Comment by VelocityRa** [comment]
Hmm, okay. Thank you.
