### ISSUE TITLE
Is there a way to avoid printing -0.00?

### ISSUE THREAD

**Issue by SanderBouwhuis** [fmtlib/fmt#1862]
I have noticed that when I print floating point numbers I regularly get -0.0 or -0.00 and so forth instead of 0.0 and 0.00. I understand this is technically correct, but I would like to avoid it to prevent confusion with users/customers. Telling a customer the total amount is '-0.00' is just bad in my opinion.

I use this:
fmt::format(FMT_STRING("{:.{}f}"), dValue, u8TotDecimals)

Is there a way I can avoid this with fmtlib?

**Comment by vitaut** [comment]
You can use the usual extension API to customize formatting including removal of sign: https://fmt.dev/latest/api.html#formatting-user-defined-types
