### ISSUE TITLE
[Windows] std::filesystem::path formating \ as \\

### ISSUE THREAD

**Issue by jeanga** [fmtlib/fmt#1864]
When formatting std::filesystem::path on Windows, fmt::format(L"{}", std::filesystem::path(L"c:\\windows\\system32\\kernel32.dll")) is rendered as "c:\\windows\\system32\\kernel32.dll" instead of "c:\windows\system32\kernel32.dll" leading to the display of an invalid path the the user.

Is this intentional?

**Comment by vitaut** [comment]
{fmt} doesn't provide a formatter for path so whatever output you observe is produced by something else, possibly `operator<<` via the ostream interface.
