### ISSUE TITLE
Please consider allowing mis-matched character types

### ISSUE THREAD

**Issue by AtnNn** [fmtlib/fmt#1865]
Even if there are user-defined formatters for `char16_t const*` or `wstring`, fmt refuses to format them into `char`, static_asserting that "formatting of non-void pointers is disallowed" or "mixing character types is disallowed".

The application I'm working on, like many others, has to juggle data in many different encodings coming from various third-party API. I would like to be able to define custom formatters or mappings that would allow

```
std::u16string s;
fmt::format("{}{}", s, L"");
```

Would you be open to a PR that allows these types if they `has_formatter`? Or perhaps a PR that allows customizing the arg_mapper in user code?

**Comment by vitaut** [comment]
This is by design: {fmt} and C++20 `std::format` never do implicit transcoding. You can do transcoding yourself by providing an appropriate `formatter` specialization (and a wrapper type).

**Comment by AtnNn** [comment]
Would you consider changing the design to allow omitting the need for a wrapper type?

I might be wrong, but it seems to be allowed in C++20. [cppreference even lists](https://en.cppreference.com/w/cpp/utility/format/formatter) this as one of the standard specialisations:

```
template<> struct formatter<char, wchar_t>;
```

**Comment by vitaut** [comment]
No, this cannot be changed. `char` -> `wchar_t` is the only conversion that is allowed and it doesn't do transcoding.
