### ISSUE TITLE
Incomplete 'chrono' extension documentation

### ISSUE THREAD

**Issue by ghassanpl** [fmtlib/fmt#1866]
It says the library supports `strftime-like date and time formatting` but it only seems to support it for old-style `time` types, and does not mention that. For `std::chrono::duration` the documentation does not state the valid syntax (and e.g. 'Y' is perhaps non-obviously not supported). There is also no information on the `localtime` and `gmtime` functions, even though `localtime` is used in the example.

**Comment by vitaut** [comment]
{fmt} supports strftime formatting of both time and durations (https://godbolt.org/z/K8s4Mc) so that part of documentation is correct. Otherwise PRs to improve the docs are welcome.

**Comment by ngc92** [comment]
At least for `std::chrono::duration` the `strftime`formatting is not really appropriate, because e.g.
```
fmt::print("strftime-like format: {:%S}\n", 3h + 15min + 30s);
```
outputs `30` and not `11730`. That might be worth pointing out in the documentation.

**Comment by vitaut** [comment]
Expanded the docs a bit and added the [Chrono Format Specifications](https://fmt.dev/dev/syntax.html#chrono-specs) section. Further improvements are welcome.
