### ISSUE TITLE
Libfmt parses some unicode characters as alignment indicators

### ISSUE THREAD

**Issue by barcharcraz** [fmtlib/fmt#1870]
```c++
#include <fmt/format.h>
#include <string_view>
#include <string>


int main() {
    fmt::print(L"{:*\x343E" L"8}", L"\x343E");
}
```

this program prints:

```
*******㐾
```

This is because the 㐾 alignment character is narrowed to '>' [here](https://github.com/fmtlib/fmt/blob/f80ed64dd949a6fce14afe6b6dcf4c16362e986a/include/fmt/format.h#L2504). Shutout to @miscco for pointing this one out over on the microsoft stl repo.

**Comment by vitaut** [comment]
Good catch, thanks. Fixed in https://github.com/fmtlib/fmt/commit/5b5a597198038e1d67969ec5212d8eb8ab2e8dd4.
