### ISSUE TITLE
Question: Is fmt thread-safe?

### ISSUE THREAD

**Issue by AlbertoEAF** [fmtlib/fmt#1872]
Hello,

I'm replacing code in LightGBM to write models by using fmt::format and some other methods.

Is this library thread-safe? Any part of the API is not thread-safe?

Today I had my program freeze, and later runs instead crashed with a segfault. If it had been always segfaults I'd say I screwed up somewhere for sure, but having the program freeze forces me to watch out for threading issues as well.

Most likely I made a mistake somewhere but just wanted to know if the library is thread-safe as debugging threading issues is not trivial. 

I'd appreciate any input on this as I couldn't find documentation regarding this.
Thank you! :)

**Comment by vitaut** [comment]
All formatting API is thread-safe, see also https://github.com/fmtlib/fmt/issues/1348#issuecomment-539717108

The only API that is not thread-safe is the experimental `fmt::ostream` API: https://github.com/fmtlib/fmt/blob/f674434a6700c14b938b4c8507abc104154a92d6/include/fmt/os.h#L380-L381

**Comment by AlbertoEAF** [comment]
Thank you @vitaut ! :)
