### ISSUE TITLE
Bug: Shortest floating point representation: redundant trailing 0's

### ISSUE THREAD

**Issue by AlbertoEAF** [fmtlib/fmt#1873]
Hello,

I am using fmt::format to print numbers in several formats. One of them is floating point in shortest representation, but when numbers come out in scientific notation I sometimes have trailing 0's.

**Original call**
`snprintf(buffer, buf_len, "%g", value)`

**New call**
`fmt::format("{:g}", value)`

Up to now, writing many floating point numbers, all the mismatches I have are with the scientific notation and trailing zeros. This are some kinds of mismatches I'm having (red = original code output, green = new code output):
![image](https://user-images.githubusercontent.com/3976753/93372856-668de680-f84c-11ea-9767-10610c8d56a8.png)

![image](https://user-images.githubusercontent.com/3976753/93372875-6db4f480-f84c-11ea-9e63-d5b3b1b01af1.png)

I know this seems "irrelevant" but it's enough to disturb LightGBM as is currently implemented.

Any suggestions? Am I calling something wrong? Is it supposed to happen?
_(I really need this working this week, so I can for the time being do a pass over the output buffer and trim trailing 0's but let's say that's neither "fast" nor "the correct way")._

Thank you!

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/7e6827521aeec2b9f7a43258e6d08406834e667f, thanks for reporting!
