### ISSUE TITLE
Fixed floating point precision format has different results than expected

### ISSUE THREAD

**Issue by AlbertoEAF** [fmtlib/fmt#1875]
Hello,

I was porting `snprintf(..., "%.17g", value)` calls to `fmt::format("{:.17g}", value)` ones but I get dramatically different results between both. The image shows snprintf's outputs in red and the same output with fmt in green:

![image](https://user-images.githubusercontent.com/3976753/93407792-e0dd5b80-f88a-11ea-816a-9c6ff1f19c02.png)

![image](https://user-images.githubusercontent.com/3976753/93407835-feaac080-f88a-11ea-924e-5e6565480db3.png)

Whilst snprintf is printing with at most 17 significant digits as the printf format spec says http://www.cplusplus.com/reference/cstdio/printf/, fmt is not.

In this case the solution seems to be to cut the output buffer by truncation, and it would result in the same as the reference value.

Believing that most cases I have more digits of precision with fmt, I tried lowering its format to `{:.16g}` just to see what happened:

![image](https://user-images.githubusercontent.com/3976753/93407218-855e9e00-f889-11ea-999d-1f88d556c80b.png)

however, lots of values now have the same number of digits as snprintf (and not 16 significant digits, unlike snprintf's 17 significant digits). Also, with the reduced precision I see errors between the new output values at 16 digits precision that are larger than rounding error against sprintf's 17-digit precision prints.

If I'm doing something wrong please tell me!

Thank you!

**Comment by vitaut** [comment]
Thanks for reporting.

I tried the first example and it produces the same result in `printf` and `print`:

```c++
  auto value = 51.1559678912162785;
  fmt::print("{:.17g}\n", value);
  printf("%.17g\n", value);
```

Output:

```
51.155967891216278
51.155967891216278
```

Could you provide a repro and the {fmt} version that you use?

**Comment by vitaut** [comment]
Closing as I wasn't able to repro but feel free to reopen with more details.
