### ISSUE TITLE
Use _lzcnt_u32 and _lzcnt_u64 instead of _BitScanReverse & _BitScanReverse64

### ISSUE THREAD

**Issue by jk-jeon** [fmtlib/fmt#1876]
It seems that MSVC generates poorer codes with `_BitScanReverse` & `_BitScanReverse64` compared to `_lzcnt_u32` & `_lzcnt_u64`. Related: https://github.com/facebook/zstd/pull/2257

**Comment by vitaut** [comment]
Could you submit a PR by any chance?

**Comment by jk-jeon** [comment]
Hmm.. I'm not sure if `zstd`'s solution I linked is the best thing we can do. It detects availability of BMI using the presence of `__AVX2__` macro, but it seems this macro is turned off unless the user specifies `/arch:AVX2` or `/arch:AVX512` options. I think there are tons of projects out there that do not use these flags, and also tons of projects that do use these flags. So perhaps depending on the `__AVX2__` is a great way to open the door into the ODR hell? Which one do you think is the best?
1. Continue to use `_BitScanReverse` & `_BitScanReverse64` although they are suboptimal. (I guess it is highly probable that they will continue to be suboptimal for a long time.)
2. Use `__AVX2__` macro to detect availability of BMI instructions, although there might be ODR issues.
3. Use `_lzcnt_u32` and `_lzcnt_u64` unconditionally, although it makes {fmt} not able to support CPU's before Haswell.
4. Use `_lzcnt_u32` and `_lzcnt_u64` by default, but falls back into `_BitScanReverse` & `_BitScanReverse64` when there is a user-defined macro, like `FMT_USE_BSR_INSTEAD_OF_LZCNT`, although this is an API-breaking change for some users.

**Comment by vitaut** [comment]
I think detection based on `__AVX2__` is fine. It definitely shouldn't be the default for portability reasons.

**Comment by mwinterb** [comment]
As a leading question: in the context which fmtlib currently uses `clz` (the `count_digits` functions), what's the objection to the generated code? The cmovne from the zstd example doesn't occur since fmtlib doesn't branch on the success of `_BitScanReverse` because it guarantees that 0 will never be passed. There are definitely codegen issues (some fixable), but I think they're unrelated to the use of bsr vs lzcnt. Do you (@jk-jeon) have a pending caller that needs a defined result if 0 is passed in?

FWIW, Microsoft chose to implement `countl_zero` as switching on `__AVX2__` to use either lzcnt or falling back on a runtime switch to use lzcnt or emulating it with bsr. So their choice was for ODR hell.

**Comment by jk-jeon** [comment]
> As a leading question: in the context which fmtlib currently uses `clz` (the `count_digits` functions), what's the objection to the generated code? The cmovne from the zstd example doesn't occur since fmtlib doesn't branch on the success of `_BitScanReverse` because it guarantees that 0 will never be passed. There are definitely codegen issues (some fixable), but I think they're unrelated to the use of bsr vs lzcnt. Do you (@jk-jeon) have a pending caller that needs a defined result if 0 is passed in?

No, I had an impression that `bsr` is slower than `lzcnt` and it turned out that that's not the case for most of mainstream CPU's. And then I found the above `zstd` issue so again believed that `bsr` is slower, but after looking at the issue again now I realized that the suboptimal code was nothing but an artifact of `bsr` being undefined for the input 0. There might be some codegen issue as you have mentioned, but it should be marginal I guess.

> FWIW, Microsoft chose to implement `countl_zero` as switching on `__AVX2__` to use either lzcnt or falling back on a runtime switch to use lzcnt or emulating it with bsr. So their choice was for ODR hell.

Wow. That's very disappointing to me.


Anyway, let's close this issue. It seems there are not so many reasons to insist on using `lzcnt`.

**Comment by foonathan** [comment]
FYI, this is the Microsoft implementation of `std::countl_zero`: https://github.com/microsoft/STL/blob/master/stl/inc/bit#L230
