### ISSUE TITLE
Undefined behavior due to shift value being too big.

### ISSUE THREAD

**Issue by MichaelTrikergiotis** [fmtlib/fmt#1884]
When running clang analyzer on a project that includes the fmt library I found some undefined behavior.

https://github.com/fmtlib/fmt/blob/cd4af11efc9c622896a3e4cb599fa28668ca3d05/include/fmt/format-inl.h#L441 For the fmt code above there is a shift by 896 on a variable of type uint64_t. Because the shift value is too big it will produce shift count overflow which is undefined behavior. 

clang analyzer produces the following error message :
```
441:36 warning: Assigned value is garbage or undefined
```

If we change the code above so the shift and assignment are in different lines then clang analyzer gives a more detailed error message that point us to the shift being too big :
```
warning: The result of the left shift is undefined due to shifting by '896', which is greater or equal to the width of type 'fmt::v7::detail::fp::significand_type'
```
</br></br>
fmt has to disallow shift values larger or equal to the width of the type. One possible solution for that, but with the disadvantage that it can be considered slow due to the modulo operation, is :

```c++
if (min_normal_e > e) half_ulp <<= ((min_normal_e - e) % std::numeric_limits<significand_type>::digits); 
```

**Comment by vitaut** [comment]
Could you provide a repro?

**Comment by vitaut** [comment]
Actually this code is no longer used, I removed it in https://github.com/fmtlib/fmt/commit/aa729bf25b5c6d220c1da90623bbf93501adfbd4.

**Comment by MichaelTrikergiotis** [comment]
Sorry for not providing a repro. I don't know your release policy and if I am allowed to ask but around what date can we expect a new stable release with this code removed ?

**Comment by vitaut** [comment]
Some time in the next two months or so. BTW this issue is likely a false positive.
