### ISSUE TITLE
Separate shortest and given precision floating-point formatting

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#1889]
As discussed in #1882 it's better to separate shortest floating-point formatting from the one with a given precision so that the former can be optimized.

**Comment by dalle** [comment]
By the way, is there a rationale that {} and {:g} differs when formatting floating-points?

The default is "g" in std::iostreams and boost::format. Other languages; .NET-based (C#, F#, VB.NET, ...), Rust.
The default is "g with at least one digit past the decimal point" in fmt::format. Other languages; Python.

**Comment by vitaut** [comment]
The default gives you round trip guarantees while `g` does not. This is out of scope of the current issue though, please keep unrelated discussion separate.

**Comment by vitaut** [comment]
Mostly done and {fmt} is now faster than ryu on dtoa-benchmark:
![image](https://user-images.githubusercontent.com/576385/95639413-30a7e080-0a4d-11eb-8ad5-761e80286dca.png)
