### ISSUE TITLE
A bug about ansi string on Windows

### ISSUE THREAD

**Issue by scarsty** [fmtlib/fmt#1892]
On windows, some local characters are encoded with two bytes, the unsigned int value of the first byte is more than 128, which means the following byte is not a single, but should be combined with the first as one wide character. Sometimes the value of the second byte can be less than 128, even the same to '{' or '}', but we should not deal it as a format character.

For an example:

`
std::string s = fmt::format("調{}", 1);
`

This will cause an error on Windows when the code file is encoded with cp936, because the code of '調' in cp936 is D57B and 7B is also the code of '{'.

This will not happen when using utf-8, but if we are programming on Windows, we cannot ignore it. Is there plan to fix this?

**Comment by vitaut** [comment]
{fmt} preserves the original encoding that may or may not be multibyte.

**Comment by scarsty** [comment]
> {fmt} preserves the original encoding that may or may not be multibyte.

It's great,but how to enable it?

**Comment by vitaut** [comment]
There is nothing to enable, that's the default behavior: https://godbolt.org/z/q4E361.

**Comment by scarsty** [comment]
> There is nothing to enable, that's the default behavior: https://godbolt.org/z/q4E361.

I think it is not right, the default code on Windows is ANSI, but this web page is using utf-8. As I don't know how to change the encoding of the web page, I used Visual Studio and the source file was encoded with ANSI (here I am using cp936). The 
assembly code is like this:

`
int main()
{
006AD7C0  push        ebp  
006AD7C1  mov         ebp,esp  
006AD7C3  push        0FFFFFFFFh  
006AD7C5  push        6B5F2Dh  
006AD7CA  mov         eax,dword ptr fs:[00000000h]  
006AD7D0  push        eax  
006AD7D1  sub         esp,100h  
006AD7D7  push        ebx  
006AD7D8  push        esi  
006AD7D9  push        edi  
006AD7DA  lea         edi,[ebp-10Ch]  
006AD7E0  mov         ecx,40h  
006AD7E5  mov         eax,0CCCCCCCCh  
006AD7EA  rep stos    dword ptr es:[edi]  
006AD7EC  mov         eax,dword ptr [__security_cookie (06C2024h)]  
006AD7F1  xor         eax,ebp  
006AD7F3  mov         dword ptr [ebp-10h],eax  
006AD7F6  push        eax  
006AD7F7  lea         eax,[ebp-0Ch]  
006AD7FA  mov         dword ptr fs:[00000000h],eax  
006AD800  mov         ecx,offset _615A64E9_ConsoleApplication1@cpp (06C503Ch)  
006AD805  call        @__CheckForDebuggerJustMyCode@4 (0671E33h)  
    std::string s1 = fmt::format("調{}", 1);
006AD80A  mov         dword ptr [ebp-0FCh],1  
006AD814  lea         eax,[ebp-0FCh]  
006AD81A  push        eax  
**006AD81B  push        offset string "\xd5{{}" (06BAABCh)**  
006AD820  lea         ecx,[s1]  
006AD823  push        ecx  
006AD824  call        fmt::v7::format<char [5],int,char> (06714F1h)  
006AD829  add         esp,0Ch  
006AD82C  mov         dword ptr [ebp-4],0  
    return s1 == "調1";
006AD833  push        offset string "\xd5{1" (06BAAC4h)  
006AD838  lea         eax,[s1]  
006AD83B  push        eax  
006AD83C  call        std::operator==<char,std::char_traits<char>,std::allocator<char> > (0671285h)  
006AD841  add         esp,8  
006AD844  movzx       ecx,al  
006AD847  mov         dword ptr [ebp-108h],ecx  
006AD84D  mov         dword ptr [ebp-4],0FFFFFFFFh  
006AD854  lea         ecx,[s1]  
006AD857  call        std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > (0671D25h)  
006AD85C  mov         eax,dword ptr [ebp-108h]  
}

`

**Comment by vitaut** [comment]
{fmt} preserves the original encoding so if you used a legacy encoding (not recommended), it will be used as is. Please refer to the documentation of your compiler on how to change the encoding.

**Comment by scarsty** [comment]
Maybe Microsoft can repair it in std::format.

**Comment by vitaut** [comment]
I looked at the assembly in more details and I see what you mean now. In general legacy code pages are not recommended (even by Microsoft itself) but a PR to work around this issue is welcome. A more future-proof solution is to switch to UTF-8.

**Comment by scarsty** [comment]
> I looked at the assembly in more details and I see what you mean now. In general legacy code pages are not recommended (even by Microsoft itself) but a PR to work around this issue is welcome. A more future-proof solution is to switch to UTF-8.

To tell the encoding of a string is very hard, so I guess a macro and a template specialization is suitable. And for ANSI string, we cannot search a character from two directions because the leading character has to be checked.

```
#ifdef FMT_ANSI
template <bool IS_CONSTEXPR, typename Handler>
FMT_CONSTEXPR_DECL FMT_INLINE void parse_format_string(
    basic_string_view<char> format_str, Handler&& handler) {
  auto begin = format_str.data();
  auto end = begin + format_str.size();
  const char* p = begin;
  while (p != end) {
    auto c = *p;
    ++p;
    if (c <= 0) ++p;
    if (c == '{') {
      handler.on_text(begin, p - 1);
      begin = p = parse_replacement_field(p - 1, end, handler);
    } else if (c == '}') {
      if (p == end || *p != '}')
        return handler.on_error("unmatched '}' in format string");
      handler.on_text(begin, p);
      ++p;
      if (c <= 0) ++p;
      begin = p;
    }
  }
  handler.on_text(begin, end);
  return;
}
#endif
```
This is enough for me but I am not sure it can work well for other code pages.
