### ISSUE TITLE
Missing "FMT_EXTERN_TEMPLATE_API" in struct declarations?

### ISSUE THREAD

**Issue by moiwi** [fmtlib/fmt#1896]
When I try to compile format.cc with MSVC 2019 I get

format.h(878,1): warning C4251: 'fmt::v7::detail::basic_data<T>::divtest_table_for_pow5_32': struct 'fmt::v7::detail::divtest_table_entry<uint32_t>' needs to have dll-interface to be used by clients of struct 'fmt::v7::detail::basic_data<T>'
format.h(878): message : see declaration of 'fmt::v7::detail::divtest_table_entry<uint32_t>'
format.h(897): message : see reference to class template instantiation 'fmt::v7::detail::basic_data<T>' being compiled
format.h(879,1): warning C4251: 'fmt::v7::detail::basic_data<T>::divtest_table_for_pow5_64': struct 'fmt::v7::detail::divtest_table_entry<uint64_t>' needs to have dll-interface to be used by clients of struct 'fmt::v7::detail::basic_data<T>'
format.h(879): message : see declaration of 'fmt::v7::detail::divtest_table_entry<uint64_t>'
format.h(881,1): warning C4251: 'fmt::v7::detail::basic_data<T>::dragonbox_pow10_significands_128': struct 'fmt::v7::detail::uint128_wrapper' needs to have dll-interface to be used by clients of struct 'fmt::v7::detail::basic_data<T>'
format.h(821): message : see declaration of 'fmt::v7::detail::uint128_wrapper'
format.h(878,1): warning C4251: 'fmt::v7::detail::basic_data<void>::divtest_table_for_pow5_32': struct 'fmt::v7::detail::divtest_table_entry<uint32_t>' needs to have dll-interface to be used by clients of struct 'fmt::v7::detail::basic_data<void>'
format.h(878): message : see declaration of 'fmt::v7::detail::divtest_table_entry<uint32_t>'
format.h(915): message : see reference to class template instantiation 'fmt::v7::detail::basic_data<void>' being compiled
format.h(879,1): warning C4251: 'fmt::v7::detail::basic_data<void>::divtest_table_for_pow5_64': struct 'fmt::v7::detail::divtest_table_entry<uint64_t>' needs to have dll-interface to be used by clients of struct 'fmt::v7::detail::basic_data<void>'
format.h(879): message : see declaration of 'fmt::v7::detail::divtest_table_entry<uint64_t>'
format.h(881,1): warning C4251: 'fmt::v7::detail::basic_data<void>::dragonbox_pow10_significands_128': struct 'fmt::v7::detail::uint128_wrapper' needs to have dll-interface to be used by clients of struct 'fmt::v7::detail::basic_data<void>'
format.h(821): message : see declaration of 'fmt::v7::detail::uint128_wrapper'

It seems "FMT_EXTERN_TEMPLATE_API" is missing in the declarations of uint128_wrapper and divtest_table_entry.

**Comment by vitaut** [comment]
Could you submit a PR since you are in the best position to check that it silences the warning?

**Comment by vitaut** [comment]
#1898
