### ISSUE TITLE
Noob question: Compiling issues - missing strtod_l and locale_t

### ISSUE THREAD

**Issue by AlbertoEAF** [fmtlib/fmt#1901]
Hello,

I used fmt to replace numeric->string conversions in LightGBM https://github.com/microsoft/LightGBM/pull/3405 and whilst in many environments it compiles and works very fast, there are some systems where it doesn't compile. I don't understand why. CMakeLists claims `strtod_l` was found:

```
-- Looking for strtod_l - found
-- Configuring done
```

but then the compilation fails. See lines 704 and 708 for instance: https://travis-ci.org/github/microsoft/LightGBM/jobs/730024056
![image](https://user-images.githubusercontent.com/3976753/94260319-db85ae00-ff27-11ea-83b8-f0e426f5a9ae.png)

Any ideas of what's the cause? 

I believe it's something really basic and stupid from my part but don't know what I'm missing.

Thank you!

P.S.: This library is **awesome** - easy, featureful and FAST!! Thank you for that!

**Comment by vitaut** [comment]
`fast_double_parser.h` is not a part of {fmt}. Here's the detection code in case you want to replicate it in your project:

https://github.com/fmtlib/fmt/blob/34179b3354915f48134689f412e3a7eb363356a4/CMakeLists.txt#L165-L175

**Comment by AlbertoEAF** [comment]
Thank you, my bad!
