### ISSUE TITLE
Incorrect example for padded hex byte with prefix

### ISSUE THREAD

**Issue by TehWan** [fmtlib/fmt#1902]
In the documentation, under "**Format String Syntax**", the example for "_Padded hex byte with prefix and always prints both hex characters_" is incorrectly specifying 4 characters padding, but the description mentions 2 characters, and the output shows 2 characters.

Incorrect:
```
fmt::format("{:#04x}", 0);
// Result: "0x00"
```

Correct output:
```
fmt::format("{:#04x}", 0);
// Result: "0x0000"
```

Intended version according to description:
```
fmt::format("{:#02x}", 0);
// Result: "0x00"
```

**Comment by vitaut** [comment]
Thanks for reporting but example looks correct: the result is padded to the width of 4, it's not the padding of 4.

**Comment by TehWan** [comment]
That seems counter intuitive when `{:04x}` gives you `0000` and `{:#04x}` is `0x00`
