### ISSUE TITLE
msvc compilation issue with "Simplify windows handling (#1903)"

### ISSUE THREAD

**Issue by NelsonEloi** [fmtlib/fmt#1904]
Good day,

If in your code you already include <windows.h>, this commit causes some problems,

As is it will cause the following error
error C2733: 'WriteConsoleW': you cannot overload a function with 'extern "C"' linkage
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\consoleapi.h(244,1): message : see declaration of 'WriteConsoleW'

I've trying changing the signature back to using Windows defines to see what happens and then I get
extern "C" BOOL __stdcall WriteConsoleW( HANDLE hConsoleOutput,
	CONST VOID* lpBuffer,
	DWORD nNumberOfCharsToWrite,
	LPDWORD lpNumberOfCharsWritten,
	LPVOID lpReserved );
warning C4273: 'WriteConsoleW': inconsistent dll linkage
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\consoleapi.h(244,1): message : see previous definition of 'WriteConsoleW'

The best compromise I manage was to use your signature but change the extern "C" to __declspec( dllimport )
__declspec( dllimport ) int __stdcall WriteConsoleW( void* hConsoleOutput,
	const void* lpBuffer,
	uint32_t nNumberOfCharsToWrite,
	uint32_t* lpNumberOfCharsWritten,
	void* lpReserved );

Thank very much for your wonderful library
Nelson

**Comment by vitaut** [comment]
I wasn't able to repro this: https://ci.appveyor.com/project/vitaut/fmt/builds/35421078. Please provide the full error message including source locations.

**Comment by NelsonEloi** [comment]
Hello,

Please find attached and example, at line 2886 of format-inl.h you'll find a comment out 'WriteConsoleW' that works

Complete error is:
1>------ Build started: Project: test, Configuration: Debug x64 ------
1>Source.cpp
1>C:\test\fmt\include\fmt\format-inl.h(2886,26): error C2116: 'WriteConsoleW': function parameter lists do not match between declarations
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\consoleapi.h(244): message : see declaration of 'WriteConsoleW'
1>C:\test\fmt\include\fmt\format-inl.h(2886,26): error C2733: 'WriteConsoleW': you cannot overload a function with 'extern "C"' linkage
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\consoleapi.h(244,1): message : see declaration of 'WriteConsoleW'
1>Done building project "test.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

[test.zip](https://github.com/fmtlib/fmt/files/5288653/test.zip)


Thank you very much

**Comment by vitaut** [comment]
I tried to repro on godbolt since I don't have a Windows machine at hand, but to no avail: https://godbolt.org/z/fYhcbW. What MSVC version do you use?

**Comment by NelsonEloi** [comment]
In godbolt I can reproduce it if I remove the namespace detail, and I'm at a loss with this, because if the namespaces are different we shouldn't have a conflict, or I'm missing something

My version is:
Microsoft Visual Studio Professional 2019 Version 16.7.4
cl.exe -> Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111 for x64
sdk -> 10.0.19041.0

godbold sdk is 10.0.18362.0

https://godbolt.org/z/aWe43r

**Comment by NelsonEloi** [comment]
Got it, its related with the Conformance mode /permissive-

https://godbolt.org/z/b88hTc

**Comment by vitaut** [comment]
Thanks for the repro; should be fixed in https://github.com/fmtlib/fmt/commit/79694d424cc32686fb5b5801d2506d30235a4fdf.

**Comment by vitaut** [comment]
#1905 1905

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/3ae88147e223788dddfdf5d3739c98c5d6574c18.
