### ISSUE TITLE
Override a formatter for a built in type?

### ISSUE THREAD

**Issue by TD22057** [fmtlib/fmt#1907]
I have a library that keeps internal data in `double` and want to output that data with units where the format is controlled by the user.  Currently we do something like this to format a local double as a velocity.

```
double x = ...;
o << Unit::format( x, UnitType::velocity() );
```
I'd like to use fmt and override the double formatter to handle a custom format specifier if it's present so I could do something like this:
```
o << fmt::format( "{velocity:unit}", x );
```
and then pass through to the regular double formatter if unit isn't in the formatting code.   

I'm guessing since the formatter is found by looking for templates in the fmt namespace (vs a registry or factory), this isn't possible but I thought I would ask.

Thanks.

**Comment by foonathan** [comment]
```
o << fmt::format("{}", Unit(x, UnitType::velocity));
```

**Comment by vitaut** [comment]
You can either do what @foonathan suggested or map `double` to some other type and provide a `formatter` specialization for it. This type can support arbitrary format specifiers.
