### ISSUE TITLE
Appending memory_buffer to strings

### ISSUE THREAD

**Issue by slzatz** [fmtlib/fmt#1909]
If I create a memory_buffer and format it and then clear it and format it again and append it to a std::string without providing the size of the buffer, it will append the length of the original buffer even though it was cleared.  I can't find anywhere in the documentation suggesting that you need to provide the size of the buffer to std::string::append but maybe that is the case.  Would be helpful to have this clarified.
  
    std::string ab;
    std::string ab0;
    fmt::memory_buffer buf;
    fmt::format_to(buf, "{}", "12");
    std::cout << "memory buffer size: " << buf.size() << std::endl;
    ab.append(buf.data());
    std::cout << "ab = " << ab << std::endl; 
    buf.clear();
    std::cout << "memory buffer size: " << buf.size() << std::endl;
    fmt::format_to(buf, "{}", "x");
    std::cout << "memory buffer size: " << buf.size() << std::endl;
    ab0.append(buf.data());
    std::cout << "ab0 = " << ab0 << std::endl;

The output is:

    memory buffer size: 2
    ab = 12
    memory buffer size: 0
    memory buffer size: 1
    ab0 = x2

**Comment by foonathan** [comment]
The memory buffer is not null-terminated. You need to call the append overload taking pointer and size.

**Comment by slzatz** [comment]
Thanks for the clarification.
