### ISSUE TITLE
error: expected identifier before ‘char8_t’

### ISSUE THREAD

**Issue by aubi1kenobi** [fmtlib/fmt#1910]
Hi,

Trying to compile the first Seastar (which uses fmt) sample, I get this error when compiling:
                 from ./src/SeaStarTest1.cpp:11:
/usr/local/include/fmt/format.h:435:8: error: expected identifier before ‘char8_t’
  435 | struct char8_t {
      |        ^~~~~~~
/usr/local/include/fmt/format.h:435:16: error: expected unqualified-id before ‘{’ token
  435 | struct char8_t {

Compiler flags: c++2a
Gcc 9.2. and 10.2.

**Comment by vitaut** [comment]
There is no `struct char8_t` in {fmt}'s master. Seastar is probably using an old version.

**Comment by aubi1kenobi** [comment]
Ok, txs for your promt reply, will try and compile from source.
