### ISSUE TITLE
Workaround for GCC -Wduplicated-branches, again

### ISSUE THREAD

**Issue by mjanzen** [fmtlib/fmt#1912]
I see that [Issue 573](https://github.com/fmtlib/fmt/issues/573) fixed a duplicated-branches warning from gcc 7.1, back in 2017.  I'm trying out fmtlib 7.0.3 with gcc 7.5.0, and am running into a similar duplicated-branches warning.

The fmtlib code has moved around since then, but following the example in commit bef89db I was able to add the same workaround to fmtlib 7.0.3 by changing 1 to +1 in fmt/core.h in lines 913 and 925.

**Comment by mjanzen** [comment]
I don't have permission to do a pull request, but here's a patch:

`$ git diff -p HEAD~1
diff --git a/include/fmt/core.h b/include/fmt/core.h
index 9f030e38..5ceed591 100644
--- a/include/fmt/core.h
+++ b/include/fmt/core.h
@@ -910,7 +910,7 @@ template <typename Char> struct named_arg_info {
 template <typename T, typename Char, size_t NUM_ARGS, size_t NUM_NAMED_ARGS>
 struct arg_data {
   // args_[0].named_args points to named_args_ to avoid bloating format_args.
-  T args_[1 + (NUM_ARGS != 0 ? NUM_ARGS : 1)];
+  T args_[1 + (NUM_ARGS != 0 ? NUM_ARGS : +1)];
   named_arg_info<Char> named_args_[NUM_NAMED_ARGS];

   template <typename... U>
@@ -922,7 +922,7 @@ struct arg_data {

 template <typename T, typename Char, size_t NUM_ARGS>
 struct arg_data<T, Char, NUM_ARGS, 0> {
-  T args_[NUM_ARGS != 0 ? NUM_ARGS : 1];
+  T args_[NUM_ARGS != 0 ? NUM_ARGS : +1];

   template <typename... U>
   FMT_INLINE arg_data(const U&... init) : args_{init...} {}`

**Comment by mjanzen** [comment]
I don't have permission to do a pull request, but here's a quick patch:

[fmtlib.1912.patch.txt](https://github.com/fmtlib/fmt/files/5322365/fmtlib.1912.patch.txt)

**Comment by vitaut** [comment]
Added a workaround in #1914. Thanks for reporting.
