### ISSUE TITLE
Wrong output for fixed-precision floating-point format

### ISSUE THREAD

**Issue by jk-jeon** [fmtlib/fmt#1917]
Please look at the following code:

```cpp
#include <iostream>
#define FMT_HEADER_ONLY 1
#include "fmt/format.h"

int main () {
 std::cout << fmt::format("{:.1e}", 1e-34);
}
```

The output of the code is
```
1.00e-34
```
but the expected output is
```
1.0e-34
```
So fmt is putting one more `0`. The same is happening when the precision is set to larger values. It seems that this issue only happens for certain floating-point inputs.

**Comment by vitaut** [comment]
Good catch, thanks. Fixed in https://github.com/fmtlib/fmt/commit/a18b3fbbdceb6332c59341a44ad80bbe55f9a2dd.
