### ISSUE TITLE
Feature request: Split format from print functions - leaner lib and compatibility with R

### ISSUE THREAD

**Issue by AlbertoEAF** [fmtlib/fmt#1921]
Hello,

If all goes well we're going to use this library in LightGBM after this patch (https://github.com/microsoft/LightGBM/pull/3405), as we got the same outputs bit-by-bit with our older code and +35% performance with less code.

However, LightGBM does work with many languages, including R, and unfortunately R's central package repository CRAN is very stringent on specific operations like redirection to stdout which is not allowed in its binaries, which prevents us from using your library directly (https://github.com/microsoft/LightGBM/pull/3405#issuecomment-703203133): 
```
* checking compiled code ... NOTE
File ‘lightgbm/libs/lightgbm.so’:
  Found ‘___stderrp’, possibly from ‘stderr’ (C)
    Object: ‘external_libs/fmt/format.o’
  Found ‘___stdoutp’, possibly from ‘stdout’ (C)
    Object: ‘external_libs/fmt/format.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.
```

We are only using `fmt::format` and not the `fmt::print` family of functions. Do you think it's possible/easy to separate format from print functionality - e.g. `format.h` into `format_only.h` from `print_only.h` or something like that? This would likely reduce the size of this library even further, which is one of your library's key features. 

Maybe I didn't read enough and `core.h` or some other header is enough to have that?

Thank you once again :)

**Comment by vitaut** [comment]
Thanks for the suggestion. I don't think splitting the library is worth it but you can remove the unused symbols in the following ways:
* Compile with `--ffunction-sections` and link with `--gc-sections`.
* Use LTO.
* Use the header-only mode.
