### ISSUE TITLE
Custom formatting of bool

### ISSUE THREAD

**Issue by cschlosser** [fmtlib/fmt#1922]
Hi,

I often have to deal with bool flags signaling wether something is enabled/disabled, valid or invalid and so on.

It's easily possible to do something like this:

```cpp
fmt::format("Foo is valid? {}", foo);
```

but when doing something like

```cpp
fmt::format("Foo is valid? {} for '{}'", foo, bar);
```

it looks weird.

The current solution is:
```cpp
fmt::format("Foo is {} for '{}'", (foo ? "valid" : "invalid"), bar);
```
Would it be possible for a bool format specifier to specify the true/false case?

Just a first idea how this could look like:
```cpp
fmt::format("Foo is {:bool?valid#invalid} for '{}'", foo, bar);
```

Is something like this already possible and I just missed it?

**Comment by vitaut** [comment]
Please see #1907.

**Comment by cschlosser** [comment]
For anyone looking for a similar solution to this:

We ended up using https://github.com/aantron/better-enums instead because the linked issue wasn't really applicable for us without wrapping alot of external interfaces.
This turns then into something like this:
```cpp
BETTER_ENUM(Valid, bool, valid = true, invalid = false)

fmt::format("Foo is {} for '{}'", Valid::_from_integral(foo), bar);
```
