### ISSUE TITLE
Segmentation fault when using `dynamic_formatter` on user-defined type

### ISSUE THREAD

**Issue by peterazmanov** [fmtlib/fmt#1923]
This part of the `dynamic_formatter::format` causes segfault if `val` is of any user-defined type:
https://github.com/fmtlib/fmt/blob/7b50dc0b245f34661824cfe6ac7c4b5d5279db66/include/fmt/format.h#L3456-L3459

The call above leads to the call of this `arg_formatter::operator()` which tries to dereference `parse_ctx_` that is equal to `nullptr` (passed from `dynamic_formatter`):
https://github.com/fmtlib/fmt/blob/7b50dc0b245f34661824cfe6ac7c4b5d5279db66/include/fmt/format.h#L3138-L3143

The code in `arg_formatter` related to handling of `parse_ctx_` is dangerous, the `parse_ctx_` is initialized to `nullptr` by default and dereferenced without check, hence the issue.

The test to reproduce the issue (checked locally with GCC v9.3.1, fmt v7.0.3 and on godbolt with GCC v9.3, fmt v6.0.0):
```c++
#include <fmt/ostream.h>

#include <iostream>

struct B
{
    int value = 0;
};

struct A
{
    B b;
};

template <>
struct fmt::formatter<B> : fmt::formatter<int>
{
    template <class FormatCtx>
    auto format(B const & x, FormatCtx & ctx)
    {
        return fmt::formatter<int>::format(x.value, ctx);
    }
};

template <>
struct fmt::formatter<A> : fmt::dynamic_formatter<>
{
    template <class FormatCtx>
    auto format(A const & x, FormatCtx & ctx)
    {
        return fmt::dynamic_formatter<>::format(x.b, ctx);
    }
};

int main()
{
    A x;
    fmt::print(std::cout, "{}\n", x);
    std::cout << x.b.value << std::endl;
}
```

PS I know that `dynamic_formatter` is undocumented, but still...

PPS The usage example in comments for `dynamic_formatter` is outdated.

**Comment by vitaut** [comment]
`dynamic_formatter` is experimental and doesn't support user-defined types. A PR to add such support is welcome.
