### ISSUE TITLE
MSVC: Warning C4459: declaration of 'integral' hides global declaration

### ISSUE THREAD

**Issue by cjwijtmans** [fmtlib/fmt#1924]
Warnings are a no go in my project and are treated as errors.

> ```
> [build] C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx86\x86\cl.exe  /nologo /TP -DFMT_HEADER_ONLY=1 -DFMT_LOCALE -DFMT_SHARED /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd   /W4 /WX /std:c++latest /showIncludes /FoCMakeFiles\client.dir\src\client\DebugInterface.cpp.obj /FdCMakeFiles\client.dir\ /FS -c ..\src\client\DebugInterface.cpp
> [build] C:\usr\src\vcpkg\installed\x86-windows\include\fmt\format-inl.h(815): error C2220: the following warning is treated as an error
> [build] C:\usr\src\vcpkg\installed\x86-windows\include\fmt\format-inl.h(815): warning C4459: declaration of 'integral' hides global declaration
> [build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\concepts(78): note: see declaration of 'std::integral'
> [build] C:\usr\src\vcpkg\installed\x86-windows\include\fmt\format-inl.h(1113): note: see reference to function template instantiation 'fmt::v7::detail::digits::result fmt::v7::detail::grisu_gen_digits<fmt::v7::detail::grisu_shortest_handler>(fmt::v7::detail::fp,uint64_t,int &,Handler &)' being compiled
> [build]         with
> [build]         [
> [build]             Handler=fmt::v7::detail::grisu_shortest_handler
> [build]         ]
> [build] C:\usr\src\vcpkg\installed\x86-windows\include\fmt\format.h(1699): note: see reference to function template instantiation 'int fmt::v7::detail::format_float<double>(T,int,fmt::v7::detail::float_specs,fmt::v7::detail::buffer<char> &)' being compiled
> [build]         with
> [build]         [
> [build]             T=double
> [build]         ]
> [build] C:\usr\src\vcpkg\installed\x86-windows\include\fmt\format.h(3432): note: see reference to function template instantiation 'OutputIt fmt::v7::detail::write<char,std::back_insert_iterator<std::string>,T,0>(OutputIt,T)' being compiled
> [build]         with
> [build]         [
> [build]             OutputIt=std::back_insert_iterator<std::string>,
> [build]             T=float
> [build]         ]
> [build] C:\usr\src\vcpkg\installed\x86-windows\include\fmt\format-inl.h(1389): note: see reference to function template instantiation 'std::string fmt::v7::to_string<T,0>(const T &)' being compiled
> [build]         with
> [build]         [
> [build]             T=float
> [build]         ]
> [build] C:\usr\src\vcpkg\installed\x86-windows\include\fmt\core.h(1184): note: see reference to function template instantiation 'std::string fmt::v7::stringifier::operator ()<float>(T) const' being compiled
> [build]         with
> [build]         [
> [build]             T=float
> [build]         ]
> [build] C:\usr\src\vcpkg\installed\x86-windows\include\fmt\format-inl.h(1405): note: see reference to function template instantiation 'std::string fmt::v7::visit_format_arg<fmt::v7::stringifier,Context>(Visitor &&,const fmt::v7::basic_format_arg<Context> &)' being compiled
> [build]         with
> [build]         [
> [build]             Context=fmt::v7::format_context,
> [build]             Visitor=fmt::v7::stringifier
> [build]         ]```

compilable example.

```C++
#include <fmt/format.h>
#include <concept>
#include <iostream>

using namespace std;

int main()
{
cout << fmt::format("{}", "test");
}
```

**Comment by cjwijtmans** [comment]
compilable example.

```C++
#include <fmt/format.h>
#include <concept>
#include <iostream>

using namespace std;

int main()
{
cout << fmt::format("{}", "test");
}
```

**Comment by vitaut** [comment]
Doesn't repro on `master`: https://godbolt.org/z/v4P3jh.

**Comment by cjwijtmans** [comment]
What in the world? First of all you are using an online compiler. Secondly you used the compiler for 2015! Third why are you closing an issue if YOU failed to reproduce it without additional feedback? This feels rather like a cop-out.

**Comment by vitaut** [comment]
Feel free to reopen with more repro details if it does repro on `master`.

**Comment by cjwijtmans** [comment]
the command line is right up there buddy.

**Comment by cjwijtmans** [comment]
You did not even use my compilable code to demonstrate the issue you modified it. 🤦🏻‍♂️

**Comment by vitaut** [comment]
Unfortunately I don't have access to your computer =). The warning message clearly doesn't correspond to `master` and there is no `integral` definition in the global scope.

**Comment by mwinterb** [comment]
https://godbolt.org/z/hsEWG3
Repros without fmtlib. "I put a bunch of random symbols outside of your control in the global namespace and it's _your_ job to avoid colliding with them" is an interesting approach to bug reports.

**Comment by vitaut** [comment]
`integral` is defined in the `std` namespace so the declaration is not hidden. Please report this false positive to MSVC.

**Comment by cjwijtmans** [comment]
> `integral` is defined in the `std` namespace so the declaration is not hidden. Please report this false positive to MSVC.

I could do that, but next time do a better job of reproducing, please.

**Comment by horenmar** [comment]
Actually it's up to you to produce a minimal compilable and verifiable reproduction. And if you did that, you wouldn't have opened the issue. 🤷

**Comment by cjwijtmans** [comment]
> Actually it's up to you to produce a minimal compilable and verifiable reproduction. And if you did that, you wouldn't have opened the issue. 🤷

i did the command line, C++ version, compiler version and compilable code is all there. 🤦🏻‍♂️

**Comment by vitaut** [comment]
> I could do that, but next time do a better job of reproducing, please.

Sure, I didn't think `<concept>` was relevant and I don't have a windows machine at hand, thus have to rely on godbolt =).

In any case, let's not beat the dead horse.
