### ISSUE TITLE
I wonder if supporting the "string interpolation" idiom is being considered.

### ISSUE THREAD

**Issue by denchat** [fmtlib/fmt#1926]
```
auto name = " World";
format("Hello {name}");
```
Does the sugar idiom need some form of compilation reflection infrastructures to implement upon?

Should \<format> side implementation wait for the reflection wing to land first?

Shall \<format> not encourage such compile time burden?

**Comment by vitaut** [comment]
> Does the sugar idiom need some form of compilation reflection infrastructures to implement upon?

Not necessarily reflection but some form of language support.

> Shall <format> not encourage such compile time burden?

¯\_(ツ)_/¯

There is already a paper that proposes this.
