### ISSUE TITLE
std::thread::id needs a formatter

### ISSUE THREAD

**Issue by cjwijtmans** [fmtlib/fmt#1931]
`std::thread::id` is serializable to a `std::basic_ostream` through `operator <<` (https://en.cppreference.com/w/cpp/thread/thread/id/operator_ltlt).

**Comment by vitaut** [comment]
Thanks for the suggestion. `std::thread::id` is already formattable via the ostream interface (https://godbolt.org/z/EPE8qr):

```c++
#include <fmt/ostream.h>
#include <thread>

int main() {
  fmt::print("{}\n", std::this_thread::get_id());
}
```

**Comment by cjwijtmans** [comment]
not through fmt::format, which this issue is about. Not fmt::print

**Comment by cjwijtmans** [comment]
On a different note why is there no `fmt::print_to(std::ostream&, etc.)`.

I was using `fmt::format_to(std::ostream_iterator<char>(to), etc.);` which i am not too happy about.

> This works with all formatting functions (https://godbolt.org/z/PeqYdT):

You are right, the compiler was somehow mentioning a template with type `std::thread::id` when saying i needed to provide a custom formatter. Again the confusing compiler leading me astray.

**Comment by vitaut** [comment]
> On a different note why is there no fmt::print_to(std::ostream&, etc.).

There is a `print` overload that takes `ostream`: https://fmt.dev/latest/api.html#ostream-api

**Comment by tuvalkohl** [comment]
> This works with **all** formatting functions (https://godbolt.org/z/PeqYdT):
> 
> #include <fmt/ostream.h>
> #include <thread>
> 
> int main() {
>   fmt::format("{}\n", std::this_thread::get_id());
> }

I got here because I am also failing to compile the following line in my code:
```
auto const thread_id_str = fmt::format("{}", std::this_thread::get_id());
```
The link you provided shows a compilation error:
<img width="1920" height="935" alt="Image" src="https://github.com/user-attachments/assets/b05296a6-be99-4467-9b1d-b30ab35fff01" />

Did someone here manage to format a thread_id using `fmt::format()`? How did you do it?

Edit:
Was missing `#include <fmt/std.h>`. Now it works.

**Comment by phprus** [comment]
@tuvalkohl 

Use ``#include <fmt/std.h>`` for format ``std::thread::id``.
