### ISSUE TITLE
Posibility to misinterpret wide characters in more parts of the format string

### ISSUE THREAD

**Issue by barcharcraz** [fmtlib/fmt#1932]
https://github.com/fmtlib/fmt/blob/af283059612dd06c321dc509255ae9b003ca5e69/include/fmt/format.h#L2834

I believe this static cast should not exist, I found in our supported frontends we could get away with just no cast here, and let the case labels widen on their own, you may have to support compilers/warning levels that warn there.

Similar to #1870

**Comment by vitaut** [comment]
Right. A PR is welcome.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/20d4f2e83677be035a15693127e404c4a5d68ac9. Thanks for reporting.
