### ISSUE TITLE
MSVC 2019 warnings "conversion from 'unsigned __int64' to 'size_t', possible loss of data"

### ISSUE THREAD

**Issue by moiwi** [fmtlib/fmt#1935]
Commit 41d97e1 causes several MSVC 2019 warnings with "to_unsigned(size)":
format.h(1845,57): warning C4244: 'argument': conversion from 'unsigned __int64' to 'size_t', possible loss of data (compiling source file format.cc)
format.h(1846,56): warning C4244: 'argument': conversion from 'unsigned __int64' to 'size_t', possible loss of data (compiling source file format.cc)
format.h(1863,32): warning C4244: 'argument': conversion from 'unsigned __int64' to 'size_t', possible loss of data (compiling source file format.cc)
format.h(1876,32): warning C4244: 'argument': conversion from 'unsigned __int64' to 'size_t', possible loss of data (compiling source file format.cc)
format.h(1891,30): warning C4244: 'argument': conversion from 'unsigned __int64' to 'size_t', possible loss of data (compiling source file format.cc)

**Comment by MarcDirven** [comment]
Same here:

```
format.h(1845): warning C4244: 'argument': conversion from 'unsigned __int64' to 'size_t', possible loss of data [D:\a\cpp-lazy\cpp-lazy\build\install\_deps\fmt-build\fmt.vcxproj]
```

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/f468b203add3b04fb8fac473ec7a04ed64c429c1.
