### ISSUE TITLE
Classes derived from detail::buffer<T> declare non-virtual destructors

### ISSUE THREAD

**Issue by BartSiwek** [fmtlib/fmt#1936]
Compiling with gcc (GCC) 10.2.1 and `-Werror=non-virtual-dtor`:
```
error: ‘class fmt::v7::detail::counting_buffer<>’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
...
error: ‘class fmt::v7::basic_memory_buffer<wchar_t>’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
```

**Comment by mwinterb** [comment]
See this comment: https://github.com/fmtlib/fmt/pull/1934#issuecomment-708437273
But, it looks like making `counting_buffer`, `basic_memory_buffer`, etc. final addresses the warning in a proper way, if that's appropriate for those types: https://gcc.godbolt.org/z/7sb694.

**Comment by BartSiwek** [comment]
Thanks for the answer. While I understand that a decision has been made it makes using fmt in codebases who have that warning on (an warnings as errors) very difficult.
I can make a PR that adds the final keyword if that is the desired direction.

**Comment by BartSiwek** [comment]
And here is the PR #1937

**Comment by madscientist** [comment]
To me, this change is a mistake.  There's nothing wrong with not having a virtual destructor here and I think it's incorrect that the compiler warns about it like this.

Meanwhile not being able to subclass these is a real loss in functionality IMO.

Anyway, my $0.02.  Cheers!
