### ISSUE TITLE
Standard form of float always includes the ".0"

### ISSUE THREAD

**Issue by madscientist** [fmtlib/fmt#1943]
I'm using fmt 7.0.3 (on GNU/Linux with GCC 10.2).

When I format a simple `fmt::format("double {}", (double)90)` the result is `double 90.0`.  Based on my reading of the spec (and what used to be generated by fmt 5.3.0, which I was using previously) this is incorrect and the output should be just `double 90` (no decimal), because I didn't include the `#` to select the alternative form.

Am I misunderstanding something?

**Comment by OnurKader** [comment]
I'm not sure about which commit fixed it but it works as expected in trunk

[Godbolt Link](https://godbolt.org/z/3PMsbz)

**Comment by vitaut** [comment]
Same as #1893.

**Comment by madscientist** [comment]
Oh thanks!  I did search the issue tracker for this but that issue is described differently enough that I guess my search terms didn't match it... :(  I should have tried master HEAD first.

**Comment by vitaut** [comment]
No worries.
