### ISSUE TITLE
Alternate form for strings (and similar)

### ISSUE THREAD

**Issue by hellow554** [fmtlib/fmt#1946]
An alternate form for strings, which does print the escape sequences as string, instead of interpreting them would be nice, e.g.:

```cpp
auto s = "Diz\r\"Iz\"\n'a'\tString";
fmt::print("{}", s);
fmt::print("{:#}", s);
```

would print

```
Diz
"Iz"
'a'	String
"Diz\r\"Iz\"\n\'a\'\tString"
```

What is your oppinion on this? This would help debugging strings, because the escape sequences will be printed directly

**Comment by vitaut** [comment]
I don't think it's worth adding a format specifier but you can do this via the usual [extension API](https://fmt.dev/latest/api.html#formatting-user-defined-types):

```
fmt::print("{}", quoted(s));
```

**Comment by hellow554** [comment]
Tbh: the idea is stolen from the rust debug format, where you just write `println!("{:?}", "a\tb\nc");` and it does exactly what I described above.

The problem is, when I want to examine a vector full of bytes, I can write `fmt::print("[{:c}]", fmt::join(vec, ", "));` and get roughly the what I want, but because of some special characters, e.g. null bytes, tab, newline, etc the output looks weird. Tbh: I really don't know how to add a join specialization for it.

Please take a moment and think if an altneratate form for chars/strings wouldn't be worth adding.

**Comment by hellow554** [comment]
@vitaut what is your opinion?

**Comment by vitaut** [comment]
Same as before: this should be done via the usual extension API.
