### ISSUE TITLE
Not able to format custom string class

### ISSUE THREAD

**Issue by SparkyPotato** [fmtlib/fmt#1948]
I'm trying to format a custom string class with fmt, but no matter what I try, I get told to make a formatter specialization. This is my specialization which is present in the same header file as the String class.

```
namespace Spark
{
	using Char = wchar_t;
	Char* String::GetCharPointer();
}

template<>
struct fmt::formatter<Spark::String> : formatter<Spark::Char*>
{
	template<typename FormatContext>
	auto format(const Spark::String& string, FormatContext& context)
	{
		return fomatter<Spark::Char*>(string.GetCharPointer(), context);
	}
};
```
I cannot figure out what the problem is, hope someone can help.

**Comment by vitaut** [comment]
Since you are using wide strings (not recommended because they non-portable) you should provide a formatter specialization for `wchar_t`:
```c++
template<>
struct fmt::formatter<Spark::String, wchar_t> : formatter<Spark::Char*, wchar_t>
```
