### ISSUE TITLE
specializing `formatter<T>` without including `libfmt`

### ISSUE THREAD

**Issue by kitegi** [fmtlib/fmt#1950]
what i'm trying to do is define a specialization of `formatter<T>` for my user types, that should ideally work regardless of whether `fmt` is installed or not (so that i can unconditionally include it in some `all.hpp` that includes the entire library, for example)

the only thing that's required to implement custom formatting for user defined types is to specialize `fmt::{version}::formatter`. to do that, we need to have a visible declaration of the main `formatter` template.

the simplest way to do that is to include `<fmt/format.h>`, but that requires `fmt` to be installed, so that doesn't really work for my case

the other way is to forward declare `formatter`. for example:

```cpp
struct S {};

namespace fmt {
inline namespace v7 {

template <typename T, typename CharT, typename Enable> struct formatter;
template <> struct formatter<S, char, void> {
  char c{};

  // scans for a single character
  template <typename Parse_Context> auto parse(Parse_Context& ctx) {
    auto it = ctx.begin();
    if (it == ctx.end() or *it == '}') ctx.on_error("no character found");
    c = *it;
    return ++it;
  }

  template <typename Format_Context> auto format(S, Format_Context& ctx) {
    auto out = ctx.out();
    *out = c;
    ++out;
    return out;
  }
};
} // namespace v7
} // namespace fmt

#include <fmt/format.h>

auto main() -> int {
  char buf[128] = {};
  char* end = fmt::format_to(buf, "{:c} hello", S{}, S{});
  *end = '\0';
  fmt::print("{} world\n", buf);
}
```

there are two problems here that prevent us from writing this in a portable way: the namespace where `formatter` is declared depends on the installed version, and that the `template <typename T, typename CharT, typename Enable> struct formatter;` declaration isn't exposed in the api (or at least, i think?).

is declaring `formatter` in a version agnostic namespace (and either making the `Enable` template parameter part of the public api, or removing it), a viable option or is there a reason why we don't want that?

**Comment by vitaut** [comment]
The `formatter` declaration is a part of the public API. It is in the version-specific namespace intentionally since the API and ABI are incompatible between versions.
