### ISSUE TITLE
Error linking static build

### ISSUE THREAD

**Issue by joaosigma** [fmtlib/fmt#1951]
We are currently building fmt 5.3.0 as a static lib using these cmake arguments:
`-DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TARGET=Static -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_CXX_STANDARD=17 -DFMT_DOC=OFF -DFMT_TEST=OFF`

Everything works as expected and we don't have any problems. But if we upgrade to the latest build (7.0.3) with the same build parameters plus `-DFMT_OS=OFF`, we get the following link errors:
`../sdk/fmt/format.h:0: error: undefined reference to 'fmt::v5::internal::error_handler::on_error(char const*)'
../sdk/fmt/format.h:2010: error: undefined reference to 'fmt::v5::internal::error_handler::on_error(char const*)'
../sdk/fmt/format.h:3112: error: undefined reference to 'fmt::v5::internal::error_handler::on_error(char const*)'
../sdk/fmt/core.h:919: error: undefined reference to 'fmt::v5::internal::error_handler::on_error(char const*)'
../sdk/fmt/format.h:946: error: undefined reference to 'char fmt::v5::internal::thousands_sep_impl<char>(fmt::v5::internal::locale_ref)'
../sdk/fmt/format.h:0: error: undefined reference to 'fmt::v5::internal::basic_data<void>::ZERO_OR_POWERS_OF_10_32'
../sdk/fmt/format.h:0: error: undefined reference to 'fmt::v5::internal::basic_data<void>::DIGITS'
../sdk/fmt/format.h:0: error: undefined reference to 'fmt::v5::internal::basic_data<void>::DIGITS'
../sdk/fmt/format.h:946: error: undefined reference to 'char fmt::v5::internal::thousands_sep_impl<char>(fmt::v5::internal::locale_ref)'
../sdk/fmt/format.h:946: error: undefined reference to 'char fmt::v5::internal::thousands_sep_impl<char>(fmt::v5::internal::locale_ref)'
../sdk/fmt/format.h:0: error: undefined reference to 'fmt::v5::internal::basic_data<void>::ZERO_OR_POWERS_OF_10_64'
../sdk/fmt/format.h:0: error: undefined reference to 'fmt::v5::internal::basic_data<void>::DIGITS'
../sdk/fmt/format.h:0: error: undefined reference to 'fmt::v5::internal::basic_data<void>::DIGITS'
../sdk/fmt/format.h:946: error: undefined reference to 'char fmt::v5::internal::thousands_sep_impl<char>(fmt::v5::internal::locale_ref)'
../sdk/fmt/format.h:2736: error: undefined reference to 'void fmt::v5::internal::sprintf_format<double>(double, fmt::v5::internal::basic_buffer<char>&, fmt::v5::core_format_specs)'
../sdk/fmt/format.h:2736: error: undefined reference to 'void fmt::v5::internal::sprintf_format<long double>(long double, fmt::v5::internal::basic_buffer<char>&, fmt::v5::core_format_specs)'
../sdk/fmt/format.h:2736: error: undefined reference to 'void fmt::v5::internal::sprintf_format<double>(double, fmt::v5::internal::basic_buffer<char>&, fmt::v5::core_format_specs)'
../sdk/fmt/format.h:2736: error: undefined reference to 'void fmt::v5::internal::sprintf_format<long double>(long double, fmt::v5::internal::basic_buffer<char>&, fmt::v5::core_format_specs)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)`

Removing `-DFMT_OS=OFF` makes no difference.
Looking at the documentation, there's nothing missing. Is this a build issue or am I doing something wrong?

**Comment by vitaut** [comment]
I wasn't able to repro the issue. For example

```
git clone https://github.com/fmtlib/fmt.git
cd fmt
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TARGET=Static -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_CXX_STANDARD=17 -DFMT_DOC=OFF -DFMT_TEST=OFF
make
cat >> test.cc << EOF
#include <fmt/core.h>
int main() {
  fmt::print("{}", 42);
}
EOF
c++ test.cc -lfmt -std=c++17
./a.out
```
works as expected. You'll have to provide more details.

**Comment by vitaut** [comment]
Closing for now but feel free to reopen with a repro.

**Comment by joaosigma** [comment]
After the last comment, I built a project from scratch and the error was gone. Don't know how or what caused the issue to appear.
Anyway, thanks for your help.
