### ISSUE TITLE
putting the version information in a separate header

### ISSUE THREAD

**Issue by kitegi** [fmtlib/fmt#1952]
it would be nice to be able to detect the installed fmtlib version without having to include `fmt/core.h`, as just including it takes about 0.7 seconds.
would having a separate `fmt/version.h` file that defines `FMT_VERSION`, `FMT_BEGIN_NAMESPACE`, `FMT_END_NAMESPACE`, etc., be an acceptable solution?

**Comment by vitaut** [comment]
Splitting fmt/core.h is undesirable. Most of the include time comes from standard library headers that are likely to be included anyway in a non-trivial project.

**Comment by kitegi** [comment]
is there a practical reason why it's undesirable? it would be directly included in `core.h` so the users don't have to change anything about their current behavior. the only reason i can think of is maybe avoiding file cluter?

i know most of the overhead comes from the standard library, but not every project relies on it, (or at least not in every translation unit) so it's nice to be able to support fmt as an optional dependency without adding the cost to every TU. i think this would be a nice change with only a minor aesthetic disadvantage, since it would allow detecting the installed fmt version, which lets us forward declare the `formatter` template in the correct namespace (or skip it/use a fallback version if fmt isn't installed)

**Comment by vitaut** [comment]
It would increase the number of headers needed for minimal configuration and add clutter for minimal benefits.
