### ISSUE TITLE
fmt::print adds percentage symbol at the end

### ISSUE THREAD

**Issue by elvisoric** [fmtlib/fmt#1954]
This is my first time using fmt library, I wrote simple example, but the output was a little weird. Here is my example:

    #include <fmt/core.h>

    int main() {
      fmt::print("Hello World");
      return 0;
    }

And the output was `Hello World%`. I did not expect this. For me, this is undesirable behavior. Am I missing something here?

**Comment by vitaut** [comment]
`%` is printed by your shell to indicate that there is no newline, not by {fmt}.
