### ISSUE TITLE
Broken ABI in 7.1.0 without SONAME change

### ISSUE THREAD

**Issue by himikof** [fmtlib/fmt#1961]
In a recent 7.1.0 release, [this change](https://github.com/fmtlib/fmt/compare/7.0.3...7.1.0#diff-bdc6f79e8e9f5b4331d66fb785636a87d29f55cf729865e13925b4209424c878L3469-R3787) was made:
```diff
-extern template format_context::iterator detail::vformat_to(
-    detail::buffer<char>&, string_view, basic_format_args<format_context>);
+extern template void detail::vformat_to(detail::buffer<char>&, string_view,
+                                        basic_format_args<format_context>,
+                                        detail::locale_ref);
```
The old version of this function was a part of the exported library ABI, leading to the following error when linking together with the new library version:

spdlog.cpp:function spdlog::details::M_formatter<spdlog::details::null_scoped_padder>::format(spdlog::details::log_msg const&, tm const&, fmt::v7::basic_memory_buffer<char, 250ul, std::allocator<char> >&): error: undefined reference to 'fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<char> >, char>::iterator fmt::v7::detail::vformat_to<char>(fmt::v7::detail::buffer<char>&, fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<fmt::v7::type_identity<char>::type> >, fmt::v7::type_identity<char>::type> >)'

If this ABI break is intended, shouldn't the `SOVERSION` in `CMakeLists.txt` be set to something other than the major library version (7), or this release should have been 8.0.0 instead?

I haven't actually checked if there are other problems with the ABI in this release, because the full set of changes is huge. I suggest keeping a list of expected exported symbols in the source repository and checking for an exact match in CI to help catching these sorts of ABI breaks before release. Downstream consumers start to rely on a shared fmt library in many places (which is great!), and keeping the ABI stability and the SONAME in sync is generally expected.

**Comment by eli-schwartz** [comment]
Same thing happened in the past e.g. #1471

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/4081b2fe948aec01a49cc6e231bee4e02df3d61e. Thanks for reporting!
