### ISSUE TITLE
something is wrong with oss-fuzz link

### ISSUE THREAD

**Issue by alexezeder** [fmtlib/fmt#1979]
When I follow a [link](https://bugs.chromium.org/p/oss-fuzz/issues/list?colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary&q=proj%3Dfmt&can=1) for [oss-fuzz badge](https://oss-fuzz-build-logs.storage.googleapis.com/badges/fmt.svg) used in [README.md](https://github.com/fmtlib/fmt/blame/master/README.rst#L19) I get 

> The search query:
> proj=fmt
> did not generate any results.

message.

**Comment by vitaut** [comment]
The link is correct. There are currently no public results.

**Comment by vitaut** [comment]
In case you are interested there is some public (although not very useful) content now.

**Comment by alexezeder** [comment]
Thank you. Now it doesn't look so empty. I later found out that the project name was changed, that's why there were no results.

**Comment by vitaut** [comment]
Right, the old issues can be found here: https://bugs.chromium.org/p/oss-fuzz/issues/list?colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary&q=proj%3Dlibfmt&can=1
