### ISSUE TITLE
Add support for std::byte to fmt::join

### ISSUE THREAD

**Issue by hellow554** [fmtlib/fmt#1981]
There is the [`std::byte`](https://en.cppreference.com/w/cpp/types/byte) type since C++17.

It would be nice to have a built-in way to format them properly.

My current ad-hoc solution is

```cpp
template<> struct fmt::formatter<std::byte> : fmt::formatter<int> {
    template<class FormatContext> auto format(const std::byte &b, FormatContext &ctx) {
        return fmt::formatter<int>::format(std::to_integer<int>(b), ctx);
    }
};
```

**Comment by vitaut** [comment]
`std::byte` is already supported:

```c++
#include <fmt/core.h>

int main() {
  fmt::print("{}", std::byte(42));
}
```
prints `42` (https://godbolt.org/z/MKccMT).

**Comment by hellow554** [comment]
My bad:

https://godbolt.org/z/f3oTno

```cpp
#include <cstddef>
#include <vector>

#include <fmt/core.h>
#include <fmt/format.h>

int main() {
    std::vector<std::byte> vv;

    fmt::print("{}", fmt::join(vv, ","));
}
```

doesn't work

**Comment by MikeGitb** [comment]
Could this be related to https://github.com/fmtlib/fmt/issues/2014?

Btw.: I'd find it much more reasonable, if std::byte got formatted as hex by default (ideally with leading zeros if necessary) - it is supposed to represent raw memory after all, not an integral number.

**Comment by hellow554** [comment]
@MikeGitb it was an example to get it working for me. You can of course use `{:x}`, but having that as default? Hmm, not sure about it.

**Comment by MikeGitb** [comment]
@hellow554 : That was more meant for @vitaut, referring to the result of `  fmt::print("{}", std::byte(42));`  not about your workaournd for `container<std::byte>`, which of course should be consistent with formatting of a single `std::byte`. but I guess thats off topic for the problem at hand.

**Comment by vitaut** [comment]
Added a `formatter` specialization for `std::byte` in https://github.com/fmtlib/fmt/commit/4a6eadbde0619b249bde5e019d69e3e8afb02260, so it should work with `join` and other APIs. Thanks for reporting.

**Comment by phprus** [comment]
Without a `#include <cstddef>`, there will be a compilation error in GCC-7:
```
include/fmt/format.h:3556:20: error: ‘byte’ is not a member of ‘std’
 FMT_FORMAT_AS(std::byte, unsigned);
```
