### ISSUE TITLE
7.1.2: documentation build is not offline process

### ISSUE THREAD

**Issue by kloczek** [fmtlib/fmt#1983]
Looks like in https://github.com/fmtlib/fmt/blob/master/doc/build.py is hard coded blindly download sphinx without checking availability of necessary tools in build env.

**Comment by vitaut** [comment]
It downloads the compatible version of sphinx so that's expected.

**Comment by kloczek** [comment]
Why not to to just check is that installed compatible version?
Are you aware of that that most of the distribution build stacks for security reasons are completely cut off from public network?

**Comment by vitaut** [comment]
The probability that the installed version is a supported one is low but a PR is welcome.

**Comment by kloczek** [comment]
Moment .. if that is true why you are using outdated sphinx?
And again: what you've implemented is blocking build process not only on my build stack but on most of the Linux distribution build envs.
What is the problem with using latest sphinx and why you are still forcilng to use sphinx from 2016??
I'm trying to understand your intentions ..

**Comment by vitaut** [comment]
There are incompatibilities between sphinx versions so supporting more than one is not planned, outdated or not. I plan to switch to a newer version but it will also be pinned. Note that you don't need to build the docs yourself because every release archive such as https://github.com/fmtlib/fmt/releases/download/7.1.2/fmt-7.1.2.zip includes the documentation.

**Comment by vitaut** [comment]
I opened an issue to update the sphinx version: #1986.

**Comment by kloczek** [comment]
> There are incompatibilities between sphinx versions so supporting more than one is not planned, outdated or not. I plan to switch to a newer version but it will also be pinned

I have few thousands packages in my library amongst which +200 are using sphinx and looks like fmt is only one which is not able to use latest sphinx.
Hiding issues under the carpet (by closing tickets) is not right way dealing with issues.

**Comment by vitaut** [comment]
The issue is closed because there are no plans to change the build process for reasons I already explained.

**Comment by kloczek** [comment]
Sorry to dsay that but you did not explained why you are downloading sphinx and few other pythoin modules.
Did you ever try to use system isntalled sphinx amd/or latest sphinx 3.x?

**Comment by vitaut** [comment]
> Did you ever try to use system isntalled sphinx amd/or latest sphinx 3.x?

Yes
