### ISSUE TITLE
fmt master/fmt 6.2.1 + android studio : Undefined References

### ISSUE THREAD

**Issue by gmnail** [fmtlib/fmt#1985]
As I want to use fmt in arm, and put fmt into the Native c++ project, here is my import file：
![image](https://user-images.githubusercontent.com/33422945/98315880-3d036700-2014-11eb-8164-c67d2491c13a.png)

I just put all the .h file in "include" directory and two .cc file in src.

and I add the library with:
     include_directories(${CMAKE_SOURCE_DIR}/fmt)

but the project can  not build success, the err is undefined references, both try in the master and tag:6.2.1

![image](https://user-images.githubusercontent.com/33422945/98315744-ee55cd00-2013-11eb-9c2c-6848c782cda9.png)

how can I use it in android?

**Comment by vitaut** [comment]
It is not enough to set up include directories, you should link with the library.

**Comment by gmnail** [comment]
so can you tell me the details which library should I link with , instead of include directories, i can not find any other files should link. thank you~

**Comment by vitaut** [comment]
Please see https://fmt.dev/latest/usage.html
