### ISSUE TITLE
Missing fmt::print(std::ostream& ...) overload for text_styles

### ISSUE THREAD

**Issue by yeswalrus** [fmtlib/fmt#1988]
I'm not sure if it should be defined in ostream.h or color.h, but there is presently no way to fmt::print to an std::ostream using a text_style. Seems like a gap in the API?

**Comment by vitaut** [comment]
Thanks for the suggestion but I don't think it's worth adding to the core library. You can easily write such function yourself or, better, avoid ostream in the first place.
