### ISSUE TITLE
Pointer conversion only for void* pointers

### ISSUE THREAD

**Issue by wfjm** [fmtlib/fmt#1995]
I use tag ` 7.1.2` and `FMT_HEADER_ONLY`. When converting a `double*` type pointer I get a compile time error
```
fmt/core.h:1206:5: error: static assertion failed: formatting of non-void pointers is disallowed
     static_assert(!sizeof(T), "formatting of non-void pointers is disallowed");   
``` 

That restriction is surprising, and also in my view not compatible with C++20. The [std::formatter documentation](https://en.cppreference.com/w/cpp/utility/format/formatter) states

> The available pointer presentation types (also used for `std::nullptr_t`) are:
>    none, p: If `std::uintptr_t` is defined, produces the output as if by calling 
>    `std::to_chars(first, last, reinterpret_cast<std::uintptr_t>(value), 16)` with the 
>    prefix 0x added to the output; otherwise, the output is implementation-defined. 

It _as if_ `reinterpret_cast<std::uintptr_t>(value)` implies any pointer can be converted, not only `void*` pointers.

**Comment by vitaut** [comment]
This is intentional and consistent with C++20: http://eel.is/c++draft/format#formatter.spec-2.4
