### ISSUE TITLE
format_to_n will hang infinitely if buffer size is < required size of formatted string.

### ISSUE THREAD

**Issue by slicer4ever** [fmtlib/fmt#1996]
Doing:
```
char Buffer[4];
fmt::format_to_n(Buffer, 4, "{}", "ABCDE")
````
will hang infinitely as the code here:
https://github.com/fmtlib/fmt/blob/e29f93e8a85266e688bf6c6350df1ec8fba842b4/include/fmt/format.h#L606

```
void buffer<T>::append(const U* begin, const U* end) {
  do {
    auto count = to_unsigned(end - begin);
    try_reserve(size_ + count);
    auto free_cap = capacity_ - size_;
    if (free_cap < count) count = free_cap;
    std::uninitialized_copy_n(begin, count, make_checked(ptr_ + size_, count));
    size_ += count;
    begin += count;
  } while (begin != end);
}
```
Since try_reserve can not increase the capacity being a fixed size buffer, the free_cap will always be 0, and the program hangs due to this issue.

```
void buffer<T>::append(const U* begin, const U* end) {
  do {
    auto count = to_unsigned(end - begin);
    try_reserve(size_ + count);
    auto free_cap = capacity_ - size_;
    if(free_cap) {
        if (free_cap < count) count = free_cap;
        std::uninitialized_copy_n(begin, count, make_checked(ptr_ + size_, count));
    }
    size_ += count;
    begin += count;
  } while (begin != end);
}
```

Adding a check that free_cap is not 0 before we truncate count, and copy means that format_to_n will still report the needed buffer size to contain the string.  this is consistent with behavior such as:

```
char Buffer[4];
fmt::format_to_n(Buffer, 4, 10000);
```
where Size of the result of format_to_n will report 5 even though it filled buffer with '1000'.

I'm unsure if free_cap can temporarily be 0 in some instances, in which case an alternative check may need to be performed that we are working on a fixed sized buffer.

**Comment by vitaut** [comment]
Good catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/5bedcb665b04bacf4cfe72ffa393e9b13cce37a7.
