### ISSUE TITLE
override warning

### ISSUE THREAD

**Issue by killerbot242** [fmtlib/fmt#2000]
Hi, would you mind adjusting the os.h with this little adjusment :

  void grow(size_t) override final;   <============ added the keyword override

This is to avoid gcc (7.x) to complain that the method can be marked override (seems override/final is not considered a union in this version of the compiler?

many thanks

**Comment by vitaut** [comment]
Could you submit a PR?

**Comment by killerbot242** [comment]
will try, let's try to find out how that was done again, lot of effort for adding one word ;-)
but let me try

**Comment by killerbot242** [comment]
branch created, committed, trying to push it, fails.
so unable to create a PR out of it, can't get my change to remote/origin/whatever.

**Comment by killerbot242** [comment]
got one, but still don't understand much of this git magic, my master branch of fork remains behind according to github though it has been origin synec like in (https://gist.github.com/CristinaSolana/1885435)

anyhow, till the next PR I am safe now ;-)

https://github.com/fmtlib/fmt/pull/2001
