### ISSUE TITLE
2GIS (mobile version) uses fmt

### ISSUE THREAD

**Issue by JIghtuse** [fmtlib/fmt#2007]
It can be found in About -> Third-party libraries.

Kinda "home page" for online version: https://2gis.ru/
Mobile versions can be found an Google Play / App Store.

![Screenshot_20201111-214427](https://user-images.githubusercontent.com/908960/98827329-53248380-2469-11eb-9f3e-69da2aa2c8f6.png)

**Comment by vitaut** [comment]
Added to the project list, thanks!

**Comment by JIghtuse** [comment]
Thank you for fmt! :smiley_cat:
