### ISSUE TITLE
FMT_ENFORCE_COMPILE_STRING Does not have unit test coverage, could use API docs mention

### ISSUE THREAD

**Issue by yeswalrus** [fmtlib/fmt#2024]
`FMT_ENFORCE_COMPILE_STRING` is a super-useful feature that IMO could be developed more. At the very least though, I think it should be covered by some basic unit tests and have it's compatibility with different extension headers (chrono.h, etc) get covered in CI? I'm happy to do the work but I wanted to verify and come up with a plan. 2 options come to mind:
1) Wrap all format strings in all the existing tests with` FMT_STRING_TEST` or some similar macro that is defined as `FMT_STRING` if `FMT_ENFORCE_COMPILE_STRING` is set, and no-op otherwise. Testing of features that are incompatible with compile-time type checks would be `#ifdef`'d. Then add test targets in CMake for each test twice, once with FMT_ENFORCE_COMPILE_STRING defined and one without.
2) Create a new test file, `#define FMT_ENFORCE_COMPILE_STRING` at the top, and add some basic tests there.

1 is more intrusive and requires a lot of edits, but results in the greatest test coverage. 2 would be very straightforward to setup, but would add additional maintenance burden since any new modules would need to have tests added both to their own test file and to this new `enforce_compile_string_test.cc` file.

Additionally, it could use a mention in the Docs along with the fact that when enabled, runtime checked variants are still possible by using `vformat` and friends, while manually calling `fmt::to_string_view` and `fmt::make_format_args`.

**Comment by vitaut** [comment]
I agree that it would be useful to test `FMT_ENFORCE_COMPILE_STRING` and think that the less intrusive option 2 is the way to go. PRs to add such test and improve docs are welcome.

**Comment by vitaut** [comment]
`FMT_ENFORCE_COMPILE_STRING` will eventually go away since compile-time checked will be enabled by default (#2022).
