### ISSUE TITLE
Support zero-padding with pointers

### ISSUE THREAD

**Issue by AlexMax** [fmtlib/fmt#2025]
```c++
#include <cstdio>

#include "fmt/format.h"

int main()
{
    void* ptr = (void*)0x2993;
    printf("%010p\n", ptr);
    fmt::print("{:010}\n", ptr);
    return 0;
}
```

### Expected
```
0x00002993
0x00002993
```
### Actual
```
terminate called after throwing an instance of 'fmt::v6::format_error'
  what():  format specifier requires numeric argument
```

I can understand not wanting to open the whole set of numeric formatting options to pointers, but the lack of even a very basic "zero-pad to the width of a pointer" kind of odd.  Would adding this be in the cards?

**Comment by vitaut** [comment]
Sounds reasonable, a PR to lift the restriction on `0` would be welcome.

**Comment by vitaut** [comment]
Actually `0` is not valid for pointers in `printf`:

```
test.cc:8:14: warning: flag '0' results in undefined behavior with 'p'
      conversion specifier [-Wformat]
    printf("%010p\n", ptr);
            ~^~~~
```
and `std::format` so we should keep the current behavior for now.
