### ISSUE TITLE
User defined types cannot have custom formatters when defined by macros in a namespace

### ISSUE THREAD

**Issue by yeswalrus** [fmtlib/fmt#2031]
It is common to have macros for creating classes, ex: `ENUM_WITH_EXTENSTIONS(MyEnum, uint32_t)`.
Presently, because support for user defined types works via explicit template instantiation of fmt::formatter however, if ENUM_WITH_EXTENSIONS is used from within a namespace, ie
```
namespace my_namespace {
  ENUM_WITH_EXTENSIONS(SureWouldBeNiceToFormatMe, uint32_t, VAL1, VAL2, ...)
}
```
Then ENUM_WITH_EXTENSIONS cannot be extended to provide fmt support because you cannot pop out to the global namespace from within such a macro, unless I'm missing something.

Ideally, this would be used to make it so that formatting the extended enum with `{:s}` or `{}` would return the name, while `{:d}` would return the value as an integer.

**Comment by vitaut** [comment]
There are no plans to change the extension API so you'll have to define specializations separately, whether using macros or not.
