### ISSUE TITLE
Support for complex ranges

### ISSUE THREAD

**Issue by DavidAce** [fmtlib/fmt#2032]
Since fmt 7.1.2 I can't print ranged containers with `std::complex` anymore. In previous versions, an `#include <fmt/ostream.h>` was sufficient to get it working, and avoid an assertion error.

[Working example version 7.0.0](https://godbolt.org/z/cc7eWz):

```c++
#include <fmt/core.h>
#include <fmt/ostream.h>
#include <fmt/ranges.h>
#include <complex>

int main(){
    std::vector<std::complex<double>> vec (4, {3.14, -2.71});
    fmt::print("vec: {}\n", vec);
}
```
prints
```
vec: {(3.14,-2.71), (3.14,-2.71), (3.14,-2.71), (3.14,-2.71)}
```

In version 7.1.2 I now get this static assertion error:
```
error: static_assert failed due to requirement 'formattable<std::vector<std::complex<double>, std::allocator<std::complex<double> > > >()' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
```
Is there a new way of doing this?  I found no search results for `complex` on [fmt.dev](https://fmt.dev/latest/index.html). It would be neat if one could avoid typing out a formatter specialization.

**Comment by vitaut** [comment]
Same as #2014.
