### ISSUE TITLE
Add support for unicode width aligned

### ISSUE THREAD

**Issue by mrbeardad** [fmtlib/fmt#2033]
* version: 7.1.2
* problem: `fmt::format` does not take into acount width of characters.

**code**
```cpp
    std::cout << fmt::format("{:-<10}{}", "你好", "世界") << std::endl;
    std::cout << fmt::format("{:-<10}{}", "hello", "world") << std::endl;
```

**expected**
```txt
你好------世界
hello-----world
```

**Actual results**
```txt
你好--------世界
hello-----world
```
> `你` and `好` is 2 columns character. The source code of [neovim](https://github.com/neovim/neovim/blob/8a56bd944a944cf77a0b9f44b59098dae05b07a0/src/nvim/mbyte.h) may help you to implement this function.

**Comment by vitaut** [comment]
Improved width computation in https://github.com/fmtlib/fmt/commit/7e72673d87cc44340f4b808d0b536e4e191342b5. It should now give the expected result. Thanks for reporting.
