### ISSUE TITLE
clang++ with -Weverything complains about -Wdocumentation-unknown-command \rst and \endrst

### ISSUE THREAD

**Issue by wfjm** [fmtlib/fmt#2035]
When compiling with clang++-10 and `-Weverything` I get warnings like
```
...fmt/include/fmt/core.h:452:3: warning: unknown command tag name [-Wdocumentation-unknown-command]
  \rst
  ^~~~
.../fmt/include/fmt/core.h:465:3: warning: unknown command tag name [-Wdocumentation-unknown-command]
  \endrst
  ^~~~~~~
```

`core.h` has Doxygen documentation sections like
```
  /**
    \rst
    Constructs a string reference object from a C string computing
    the size with ``std::char_traits<Char>::length``.
    \endrst
   */
```

The [Doxygen manual](https://www.doxygen.nl/manual/commands.html) shows that there are indeed no `\rst` or `\endrst` special commands.

**Comment by vitaut** [comment]
Those are custom directives. They will eventually be removed and in the meantime I recommend not enabling `-Wdocumentation-unknown-command` which doesn't understand custom directives.

**Comment by wfjm** [comment]
Not using `-Wdocumentation-unknown-command` is not an option. We use it to scan the integrity of Doxygen documentation, and just we use now `fmtlib` we'll not stop that. It turns out that one can declare custom Doxygen commands in `clang` with
```
-fcomment-block-commands=<arg>,<arg2>...
    Treat each comma separated argument in <arg> as a documentation comment block command
```

So adding
```
-fcomment-block-commands=rst,endrst
```
helps. It be helpful if this is mentioned in the installation README.
