### ISSUE TITLE
Enum value evaluates to "true"

### ISSUE THREAD

**Issue by Sainan** [fmtlib/fmt#2036]
Assume an emum exists, for example, this:
```CPP
enum myEnum : uint8_t
{
	ONE = 1,
	TWO,
	THREE
};
```
With this, `fmt::to_string(TWO);` returns `"true"` — I expected `"2"`.

**Comment by vitaut** [comment]
Which library version?

**Comment by madscientist** [comment]
Did you mean `enum class` in your example?

**Comment by Sainan** [comment]
7.1.3. I did not mean enum class.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/33f9a6d3609c7001afc7019c8308f4af8942ce0a. Thanks for reporting!
