### ISSUE TITLE
fmt::join() not working without formatter specialisation

### ISSUE THREAD

**Issue by bluescarni** [fmtlib/fmt#2040]
Hello,

I don't know if this is the intended behaviour, but apparently ``fmt::join()`` does not work for types which do not provide a ``formatter`` specialisation, even if these types are streamable and can be formatted after the inclusion of ``fmt/ostream.h``.

Godbolt link exhibiting the issue: https://godbolt.org/z/7z3jbo

**Comment by vitaut** [comment]
I think adding support for streamable types is reasonable. PRs are welcome.
