### ISSUE TITLE
warning: ctor-dtor-privacy on gcc 9.3

### ISSUE THREAD

**Issue by Finkman** [fmtlib/fmt#2045]
When compiling:
```cpp
fmt::print( std::cout, "huhu {0:010d}", 123 );
```
with gcc 9.3 it pops the warning:

```
error: all member functions in class ‘fmt::v7::detail::is_streamable<T, Char>’ are private [-Werror=ctor-dtor-privacy]
[build]    75 | template <typename T, typename Char> class is_streamable {
```
when trying with clang 10.0 all is fine.

Tested with master and 7.1.3.

**Comment by vitaut** [comment]
This warning doesn't make much sense but a PR to suppress it is welcome.

**Comment by Finkman** [comment]
Last time you wrote:

> Thanks for the PR but the warnings should be fixed, not suppressed.

**Comment by vitaut** [comment]
Sure, fixing is preferable but since this warning is meaningless the only option is to suppress/workaround.

**Comment by Finkman** [comment]
agree. thx
