### ISSUE TITLE
unexpected behaviour of fmt::output_file

### ISSUE THREAD

**Issue by krox** [fmtlib/fmt#2046]
The default behaviour of `fmt::output_file` is to write to the start of the file but not remove any existing content. So if the existing file is bigger than what is then written to it, some old data will remain in the file.

I assume this is by design and not a bug. But I also think it is a very surprising default, because it is different from `std::ofstream` (destroys old file by default) and also `std::fopen` (destroys old file in both `w` and `w+` mode). So at least the documentation should be clear on this design choice.

This is particularly problematic because reading just the front page `README.rst` one gets the impression that `fmt::output_file` is the intended way to write text to a file, as there is no alternative mentioned. Alternatively, the front-page should mention either:

```
auto file = std::ofstream(...);
file << fmt::format(...);
```

Or:

```
auto file = std::fopen(...);
fmt::print(file, ...);
fclose(file);
```

I don't know which of these is preferred (and to me, both seem somwhat suboptimal honestly)

**Comment by foonathan** [comment]
This was fixed recently: https://github.com/fmtlib/fmt/commit/119f7dc3d6dc02a07167a69a929cdfee9c0626e9

**Comment by krox** [comment]
oh. Sorry, my bad for not checking.
