### ISSUE TITLE
missing '#include <cstddef>' in format.h

### ISSUE THREAD

**Issue by moiwi** [fmtlib/fmt#2047]
I get
```
fmt/format.h:3578:20: error: 'byte' is not a member of 'std'
 FMT_FORMAT_AS(std::byte, unsigned);
```
when compiling the current format.h.
I think
```
#include <cstddef>
```
is missing in format.h.

**Comment by vitaut** [comment]
Good catch, thanks. Fixed in https://github.com/fmtlib/fmt/commit/1f4a76d2c8867d102e8896f7a9c1a8a81743f1aa.
