### ISSUE TITLE
Questions about FMT_COMPILE

### ISSUE THREAD

**Issue by alexezeder** [fmtlib/fmt#2048]
I'm experimenting with `FMT_COMPILE` lately and here are a few points about it that are interesting for me. Note that my assumptions below can be wrong.

1. `FMT_COMPILE` (or I should probably say compile-time API) doesn't support [`arg_id`](https://fmt.dev/latest/syntax.html#grammar-token-arg_id). There are no tests for that and when I try to use `arg_id` in this API then a compiler is trying to tell me that it's unable to do this. I don't think it's impossible to implement but it just takes some time.

2. The compilation error with `arg_id` inside of `FMT_COMPILE`, as well as other non-valid for compile-time API format string I suppose, is non-intuitive. Here is an example: https://godbolt.org/z/ha38a6
At least for me, the error that there is no `type` is non-intuitive. Especially when there are implemented handling inside parsing code:
https://github.com/fmtlib/fmt/blob/4a6eadbde0619b249bde5e019d69e3e8afb02260/include/fmt/compile.h#L544
and strange check that allows the compiler to continue its journey to that no `::type` error:
https://github.com/fmtlib/fmt/blob/4a6eadbde0619b249bde5e019d69e3e8afb02260/include/fmt/compile.h#L573-L575
Of course, I can miss some case where it should go that path, so let me know.

3. The situation with a format string that has fewer replacement fields than the number of arguments that passed to the format function is valid. For example here are non-failing calls:
    ```cpp
    fmt::format(FMT_COMPILE("{}"), 42, 42);
    fmt::format(FMT_COMPILE(""), 42);
    ```
    The same usage on [Compiler Explorer](https://godbolt.org/z/j9ra1n).
    But the runtime API also sticks with this behaviour, even with `FMT_STRING` checks, so maybe there is some explanation for that.

**Comment by vitaut** [comment]
1. Right, some features including positional arguments are not yet implemented in format string compilation.

2. The idea is to fallback on runtime formatting for unsupported features but it still needs more work.

3. It is intentional and consistent with runtime format, `printf` and `std::format`.

**Comment by vitaut** [comment]
Positional arguments are supported in both `FMT_STRING` and `FMT_COMPILE`.
