### ISSUE TITLE
Color support for Windows (again)

### ISSUE THREAD

**Issue by FedorLap2006** [fmtlib/fmt#2052]
## Idea
Add normal color support for Windows, not only ASCII.

## Why does the library need this feature?
Because only win10 supports ASCII escape codes, and that doesn't mean that older Windows versions support that.
## How to implement?
`SetConsoleAttribute` and WinAPI functions like that.

## Environment
I'm currently working on `7.0.3` version of the library (I will update it soon). Also I'm using Windows with native `cmd.exe` terminal. I think that's enough to understand my problem.

## Styling (like underline, strike or italic)
I think that's not so necessary, but I'm really looking forward that feature, if that's possible.

---
_It seems someone is already made this thing... but somehow I don't see any mention of that in current code, and no one has opened issues in near time like that... so I did this._

**Comment by FedorLap2006** [comment]
Btw, why there's no issue templates? They will be really useful here.

**Comment by FedorLap2006** [comment]
And I think if no one will pay attention to this I will create a pull request when will find time.

**Comment by vitaut** [comment]
Thanks for the suggestion but I don't think it's worth doing considering that Windows 8 reaches its end of life in ~3 years and newer systems support standard ANSI escape sequences.
