### ISSUE TITLE
Missing Android.mk

### ISSUE THREAD

**Issue by n00b42** [fmtlib/fmt#2057]
The referenced [Android.mk](https://github.com/fmtlib/fmt/blob/master/Android.mk), referenced here: [Usage](https://github.com/fmtlib/fmt/blob/master/doc/usage.rst#android-ndk) does not exist.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/25a41b80fc8595c3213562e543de9acd615f7efc, thanks.
