### ISSUE TITLE
Adding fmtlib in an header only library

### ISSUE THREAD

**Issue by bhumitattarde** [fmtlib/fmt#2058]
Hello. I'm trying to write a header only library and would like to ship fmtlib (header only) directly with my library directory. Is it possible to do so? Do I just include `fmt` folder in my project? Would I still need to link something?
I looked at spdlog's implementation but couldn't quite grasp it. An example with cmake would be nice. Thank you.

**Comment by vitaut** [comment]
> Is it possible to do so?

Yes.

> Do I just include fmt folder in my project?

You can add the content of the https://github.com/fmtlib/fmt/tree/master/include directory to your project and define the `FMT_HEADER_ONLY` macro when compiling the code.

> Would I still need to link something?

Not if you are using a header-only configuration.

**Comment by alexezeder** [comment]
Or you can take [latest release](https://github.com/fmtlib/fmt/releases/latest), add the folder of unpacked release using `add_subdirectory` into your CMake project and link `fmt::fmt-header-only` to wherever target which needs header-only {fmt} using `target_link_libraries`.

This allows you to use a specific released {fmt} version without changing it somehow. You can even leave `fmt-x.x.x` version in the name as it could help you to manage lib versions in the future.
