### ISSUE TITLE
Feature request: please support std::complex<>

### ISSUE THREAD

**Issue by pfeatherstone** [fmtlib/fmt#2060]
:)

**Comment by s-viour** [comment]
I see some code that implements support for std::complex in `test/locale-test.cc`. Located here: https://github.com/fmtlib/fmt/blob/master/test/locale-test.cc#L113
Would this be the preferred implementation?

**Comment by vitaut** [comment]
> Would this be the preferred implementation?

That would be a good start.

**Comment by vitaut** [comment]
There are no plans to add a formatter for `complex` but it can be done via the usual extension API: https://fmt.dev/latest/api.html#formatting-user-defined-types.
