### ISSUE TITLE
Feature request: UTC time for chrono format 

### ISSUE THREAD

**Issue by elegracer** [fmtlib/fmt#2063]
Now format for time_point is localtime by default.

Could you please add support for UTC time format, like e.g. <https://github.com/HowardHinnant/date>?

**Comment by vitaut** [comment]
You can already do this using `gmtime` (https://godbolt.org/z/5j9scY):

```c++
#include <fmt/chrono.h>

int main() {
  std::time_t t = std::time(nullptr);
  fmt::print("{:%H:%M:%S}.", fmt::gmtime(t));
}
```

**Comment by elegracer** [comment]
Sorry for not making it clear.

Actually I need something like this.

```c++
#include <date/date.h>

using namespace std::chrono;
auto time = time_point_cast<milliseconds>(system_clock::now());
return date::format("%Y-%m-%dT%H:%M:%S", time);
```

The output will be like this `2020-12-13T07:06:15.430`, containing millisecond part.

**Comment by vitaut** [comment]
You can format time points in UTC as follows (https://godbolt.org/z/d4hxrP):

```c++
#include <fmt/chrono.h>

int main() {
  using namespace std::chrono;
  auto time = time_point_cast<milliseconds>(system_clock::now());
  fmt::print("{:%Y-%m-%dT%H:%M:%S}.", fmt::gmtime(time));
}
```

**Comment by elegracer** [comment]
Well, the result doesn't contain the millisecond part..

**Comment by vitaut** [comment]
A PR to add milliseconds is welcome provided that it is consistent with the standard =).

**Comment by elegracer** [comment]
I have this trick to do that, but a little bit ugly..

```c++
using namespace std::chrono;
auto time = time_point_cast<milliseconds>(system_clock::now());
fmt::print("{:%Y-%m-%dT%H:%M}{::%S}\n", fmt::gmtime(time), time.time_since_epoch());
```
