### ISSUE TITLE
Is/should predefining FMT_BEGIN_NAMESPACE be supported?

### ISSUE THREAD

**Issue by vadz** [fmtlib/fmt#2064]
I'd like to use fmt in my own shared library which is used by both my own code (i.e. various tools using this library) and user code (i.e. whatever others write using it). Moreover, I'd also like to be able to use fmt in my tools. However I do _not_ want to export `fmt::xxx` symbols from my shared library, as they could conflict with fmt already used in the user applications.

I thought doing something like
```cpp
  #define FMT_BEGIN_NAMESPACE namespace my_own_unique_ns { namespace fmt { namespace v7 {
  #define FMT_END_NAMESPACE } using namespace v7; }
```
before including fmt headers would allow me to do what I want, but unfortunately `format.cc` itself doesn't compile if I do this, neither with 7.1.3 nor latest master for several reasons (`FMT_ASSERT` refers to `::fmt` and there are also problems with `num_bits<int128_t>` etc).

Is this supposed to work in the first place? If yes, I could try to make a PR fixing this, but maybe this is not meant to be supported at all? And if it isn't, is there some other way to achieve what I want?

TIA!

**Comment by vitaut** [comment]
> Is this supposed to work in the first place?

No.

> And if it isn't, is there some other way to achieve what I want?

You could probably compile with `-fvisibility=hidden` or use some other mechanism to limit symbol visibility.

**Comment by vadz** [comment]
> > Is this supposed to work in the first place?
> 
> No.

Thanks for confirming this and sorry for misunderstanding, I thought that  the presence of `#ifndef FMT_BEGIN_NAMESPACE` test in the header indicated that it could be predefined.

> > And if it isn't, is there some other way to achieve what I want?
> 
> You could probably compile with `-fvisibility=hidden` or use some other mechanism to limit symbol visibility.

I'm already using visibility, of course, but this doesn't help because it hides fmt symbols completely inside the shared library while I still want to use them, just without conflicting with the symbols possibly present in the user code (which seems like a real possibility considering the popularity of fmt).

Looking at `fmt/core.h` again, it seems that there should be a very simple solution to this: just replace the literal `v7`, which occurs in only 3 places, with `FMT_INNER_NS` macro or something like this and allow predefining this one before including fmt headers. Would you be willing to merge a PR doing this?

**Comment by vitaut** [comment]
> Would you be willing to merge a PR doing this?

No.
