### ISSUE TITLE
How to output user defined type to std::wstring and std::string

### ISSUE THREAD

**Issue by okravets** [fmtlib/fmt#2066]
Hey !
I am trying to make formatter which will allow to format type to wide and not output.
How to achieve it?

```c++
typedef struct _GUID {
    unsigned long  Data1;
    unsigned short Data2;
    unsigned short Data3;
    unsigned char  Data4[ 8 ];
} GUIDX;

template<>
struct fmt::formatter<GUIDX>
{
  constexpr auto parse(fmt::format_parse_context& ctx)
  {
    return ctx.begin();
  }

  template<typename FormatContext>
  auto format(const GUIDX& guid, FormatContext& ctx)
  {
    return format_to(ctx.out(), "{{{:08x}-{:04x}-{:04x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}}}",
      guid.Data1, guid.Data2, guid.Data3, guid.Data4[0],
      guid.Data4[1], guid.Data4[2], guid.Data4[3], guid.Data4[4], guid.Data4[5], guid.Data4[6], guid.Data4[7]);
  }
};

int main() {
       GUIDX g {};
       auto wide = fmt::format(L"{}", g);
       auto single = fmt::format("{}", g);
}}
```

Thank you,
Olexandr

**Comment by vitaut** [comment]
You can do it as follows:

```c++
template <typename Char>
struct fmt::formatter<GUIDX, Char> {
  constexpr auto parse(basic_format_parse_context<Char>& ctx);

  template <typename FormatContext>
  auto format(const GUIDX& guid, FormatContext& ctx);
};
```

**Comment by okravets** [comment]
Thank you !

**Comment by okravets** [comment]
Victor, I 've tried to use your proposal, but without success.
Please take a look if you have time - https://godbolt.org/z/vf49Ph

Unfortunately, I am not really strong in templates.
It would be really nice to have example which demonstrates it.

Thank you,
Olexandr

**Comment by vitaut** [comment]
Looks like the vcpkg package of {fmt} on godbolt is pretty old and doesn't have `basic_format_parse_context`. You can workaround this by making parse a function template too: https://godbolt.org/z/EGj3j4. Also this

```c++
return format_to(ctx.out(), "{{{:08x}-{:04x}-{:04x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}}}", ...
```

will only work if Char is `char`. You could replace the format string with `L"{{{:08x}-{:04x}-{:04x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}}}"` for wide strings.

**Comment by okravets** [comment]
Thank you for answering! 
Internally, I am using newer version.
I would like to have one implementation of format method which will work with both char and wchar_t.
Could you advise how to achieve it?

**Comment by vitaut** [comment]
You can convert the literal `"{{{:08x}-{:04x}-{:04x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}}}"` into a `Char` array initialized with individual characters. In general I'd recommend avoiding `wchar_t` because it's non-portable.

**Comment by okravets** [comment]
Thank you !

Final version:
`template<typename Char>
struct fmt::formatter<GUID,Char>
{
  template<typename ParseContext>
  constexpr auto parse(ParseContext& ctx)
  {
    return ctx.begin();
  }

  template<typename FormatContext>
  auto format(const GUID& guid, FormatContext& ctx)
  {
    static constexpr Char guid_f[] = {
    '{','{','{',':','0','8','x','}','-',
    '{', ':','0','4','x','}','-','{', ':','0','4','x','}','-',
    '{', ':','0','2','x','}','{', ':','0','2','x','}','-',
    '{', ':','0','2','x','}','{', ':','0','2','x','}','{', ':','0','2','x','}',
    '{', ':','0','2','x','}','{', ':','0','2','x','}','{', ':','0','2','x','}','}','}', 0 };
    return format_to(ctx.out(), guid_f, guid.Data1, guid.Data2, guid.Data3, guid.Data4[0],
      guid.Data4[1], guid.Data4[2], guid.Data4[3], guid.Data4[4], guid.Data4[5], guid.Data4[6], guid.Data4[7]);
  }
};`
