### ISSUE TITLE
visual studio sprintf not work

### ISSUE THREAD

**Issue by heroesf** [fmtlib/fmt#2077]
Severity	Code	Description	Project	File	Line	Suppression State
`Error	C3487	'int': all return expressions must deduce to the same type: previously it was 'bool'	db	fmt-7.1.2\include\fmt\format.h	1821	
`

code problem:
`  int output_exp = fp.exponent + significand_size - 1;
  auto use_exp_format = [=]() {
    if (fspecs.format == float_format::exp) return true;
    if (fspecs.format != float_format::general) return false;
    // Use the fixed notation if the exponent is in [exp_lower, exp_upper),
    // e.g. 0.0001 instead of 1e-04. Otherwise use the exponent notation.
    const int exp_lower = -4, exp_upper = 16;
    return output_exp < exp_lower ||
           output_exp >= (fspecs.precision > 0 ? fspecs.precision : exp_upper);
  };`

https://imgur.com/mROz8v4

**Comment by vitaut** [comment]
Thanks for reporting but AFAICS all return paths already return bool: https://github.com/fmtlib/fmt/blob/cc09f1a6798c085c325569ef466bcdcffdc266d4/include/fmt/format.h#L1821
