### ISSUE TITLE
Targets should be mutually exclusive

### ISSUE THREAD

**Issue by friendlyanon** [fmtlib/fmt#2079]
CMake provides a way to emit disgnostics when 2 targets are linked againt that shouldn't be.

I think it should be an error to link against both the static/shared and the header only targets.

**Comment by vitaut** [comment]
Could you elaborate why you think they should be mutually exclusive?

**Comment by friendlyanon** [comment]
There are flags that are unnecessarily propagated to clients ([[1]](https://github.com/fmtlib/fmt/blob/c9dd1eb97d45648282c1c5b3d5e9d3ee38415065/CMakeLists.txt#L197-L206), [[2]](https://github.com/fmtlib/fmt/blob/c9dd1eb97d45648282c1c5b3d5e9d3ee38415065/CMakeLists.txt#L243-L245)) and the build artifact is unnecessarily linked against by dependents.

What are the benefits of allowing dependents to link against both targets?

**Comment by vitaut** [comment]
> There are flags that are unnecessarily propagated to clients ([1], [2]) and the build artifact is unnecessarily linked against by dependents.

If this is the only issue then I don't think it's worth complicating the CMake config.

**Comment by friendlyanon** [comment]
Complicating? This can be done in 3 lines of code:
```cmake
set_property(TARGET fmt fmt-header-only PROPERTY COMPATIBLE_INTERFACE_STRING FMT_LIB_KIND)
set_property(TARGET fmt PROPERTY INTERFACE_FMT_LIB_KIND built)
set_property(TARGET fmt-header-only PROPERTY INTERFACE_FMT_LIB_KIND header-only)
```

**Comment by vitaut** [comment]
Sure but the motivation is so weak that it's not worth it.

**Comment by friendlyanon** [comment]
I don't think an argument for correctness is "weak".  
A few weeks ago on reddit someone posted a guide for beginners that had questionable quality and used vcpkg to import {fmt}. I don't use vcpkg, but it seems it just prints all the targets a library provides and the author ended up linking against both the static and header only targets. I don't think this is the kind of material that should proliferate to people dipping their toes into C++ and ensuring correctness in this case takes 3 simple lines of code that is [clearly documented](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#compatible-interface-properties) to solve such problems.

I still do not know what would be the benefit of linking against both the static/shared and header-only targets that would leave room for allowing that kind of usage.

**Comment by vitaut** [comment]
I don't see any correctness issue here from what you've described so far. It doesn't make much sense to depend on header-only and static library, but I don't see a reason to explicitly forbid it.
