### ISSUE TITLE
API details about fmt::output_file?

### ISSUE THREAD

**Issue by 1oyue** [fmtlib/fmt#2084]
Hi I'm new to fmt and love it so much. But I can't find the details about fmt::output_file in the document. Also when I use it in Visual Studio, VS reports that "fmt doesn't have member function called output_file", but it can compile and run correctly. Also I found someone had the same question like me: https://zhiqiang.org/coding/output_file-of-fmt-is-weird.html. Is there any clue for me? Thanks~

**Comment by vitaut** [comment]
Added initial documentation in https://fmt.dev/dev/api.html#os-api, thanks for the suggestion. As for VS, intellisense is known to handle modern C++ features very poorly, in this case it probably can't handle `__has_include`.
