### ISSUE TITLE
Clarify fmt::memroy_buffer::data() does return a null-terminated string / add `.c_str()` method.

### ISSUE THREAD

**Issue by burnpanck** [fmtlib/fmt#2085]
First of all, thanks for this great library!

I had run into a problem caused by my misunderstanding of the behaviour of `memory_buffer::data()`. I used `fmt::memory_buffer` together with `fmt::format_to` to pass strings to a C-API, which of course expected a null-terminated string. I had been led to that by the very prominent example on the front page of the documentation:
```
fmt::memory_buffer out;
format_to(out, "For a moment, {} happened.", "nothing");
out.data(); // returns a pointer to the formatted data
```
While it doesn't say that the formatted data is null-terminated, it also doesn't state the opposite, and I had come to wrong conclusions. I couldn't find an explicit mention of null-termination in the API reference either.

Given that there are still poor souls out here who have to work with C-APIs, it might be useful to be explicit about null-termination, and potentially provide an example how to achieve that if needed. Since `memory_buffer` is auto-grow, why not add a `.c_str()` method that does add the null-byte if needed before returning the pointer? Currently, the least-verbose solution is to do `to_string(out).c_str()`, but I fear that this causes an extra unneeded copy.

**Comment by vitaut** [comment]
Thanks for the suggestion but  don't think `memory_buffer` should have `c_str` because it's not a string. You can do `format(...).c_str()` instead or append a terminated nul explicitly.
