### ISSUE TITLE
macOS build failure on XCode 7.2

### ISSUE THREAD

**Issue by pablo-odorico** [fmtlib/fmt#2089]
Hi, I found this build error when using fmtlib on an app built with XCode 7.2: [clang 7.0.2, llvm 3.7.0svn](https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_12.x_(since_Free_On-Device_Development)). This is a legacy platform that requires that XCode version.
fmtlib itself built okay with this compiler (I'm using `-DFMT_TEST=OFF`).

Newer XCode versions, VS2019 (Windows) and clang 3.8 (Linux) can build the app correctly.

The "Portability" section of the documentation suggests that this compiler should be supported. I tried not using `FMT_STRING` but it didn't help.

Any ideas/workarounds? Thanks.

```
<fmtpath>/include/fmt/core.h:1421:48: error: expected unqualified-id
template <typename T> int check(unformattable) {
                                               ^
<fmtpath>/include/fmt/core.h:1449:8: error: no template named 'is_reference_wrapper'; did you mean 'std::__is_reference_wrapper'?
struct is_reference_wrapper<std::reference_wrapper<T>> : std::true_type {};
       ^~~~~~~~~~~~~~~~~~~~
       std::__is_reference_wrapper
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:478:29: note: 'std::__is_reference_wrapper' declared here
template <class _Tp> struct __is_reference_wrapper
                            ^
<fmtpath>/include/fmt/core.h:1449:8: error: class template partial specialization of '__is_reference_wrapper' not in a namespace enclosing '__1'
struct is_reference_wrapper<std::reference_wrapper<T>> : std::true_type {};
       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:478:29: note: explicitly specialized declaration is here
template <class _Tp> struct __is_reference_wrapper
                            ^
<fmtpath>/include/fmt/core.h:1670:17: error: no template named 'is_reference_wrapper' in namespace 'fmt::v7::detail'; did you mean 'std::__is_reference_wrapper'?
      value = !(detail::is_reference_wrapper<T>::value ||
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                std::__is_reference_wrapper
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:478:29: note: 'std::__is_reference_wrapper' declared here
template <class _Tp> struct __is_reference_wrapper
                            ^
<fmtpath>/include/fmt/format.h:370:16: warning: unknown attribute 'no_sanitize' ignored [-Wunknown-attributes]
__attribute__((no_sanitize("undefined")))
               ^
<fmtpath>/include/fmt/core.h:1587:15: error: no matching function for call to 'make_arg'
        data_{detail::make_arg<
              ^~~~~~~~~~~~~~~~~
<fmtpath>/include/fmt/core.h:1626:10: note: in instantiation of member function 'fmt::v7::format_arg_store<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>, const std::__1::basic_string<char> >::format_arg_store' requested here
  return {args...};
         ^
<fmtpath>/include/fmt/core.h:2075:28: note: in instantiation of function template specialization 'fmt::v7::make_args_checked<const std::__1::basic_string<char> &, char [41], char>' requested here
  const auto& vargs = fmt::make_args_checked<Args...>(format_str, args...);
                           ^
```

**Comment by pablo-odorico** [comment]
Forgot to mention that the repro is with 7.1.3. I just tested version 5.3.0 and it the issue does not repro.

**Comment by vitaut** [comment]
Could you provide a repro? Also have your tried master? `is_reference_wrapper` is gone from `fmt/core.h` there.

**Comment by pablo-odorico** [comment]
Thanks for the response. After some testing these are the things I noticed:

1. Both on master and 7.1.3 this line fails to build on most platforms:
`include/fmt/os.h:374: static constexpr detail::buffer_size buffer_size;`
The issue is fixed by adding an initialiser
`include/fmt/os.h:374: static constexpr detail::buffer_size buffer_size {};`
I had actually fixed this before and forgot to mention it. Seems like an unrelated issue but worth fixing.

2. On MSVC 2017 (14.15.26726) if I build with `FMT_TEST=ON` I get this error:
`fmt/compile.h(704): fatal error C1001: An internal error has occurred in the compiler.`

3. Building on XCode7.2 using master:
- The `is_reference_wrapper` issue goes away as the code is no longer there
- `fmt/core.h:1442:48: error: expected unqualified-id` remains and it's not dependent on use, just header parsing.
- `fmt/core.h:1569:15: error: no matching function for call to 'make_arg'` remains on a simple header instantiation that looks like this: `#define logError(_FORMAT, ...) logString(fmt::format(FMT_STRING(_FORMAT), ##__VA_ARGS__))`. One thing to note is that this error is when the header is included from an mm file, but it may just be the first build target that includes it. I'm afraid in this configuration is not easy to provide a simple main.cpp repro.

**Comment by vitaut** [comment]
1. `fmt/os.h` is optional and may require a newer compiler but a PR to improve compatibility with older compilers is welcome.
2. Please report the compiler error to MSVC developers. If you are aware of a workaround, a PR is also welcome.
3. I wasn't able to repro the error with clang 3.7 (https://godbolt.org/z/6aj6n6) or 7.0 (https://godbolt.org/z/zz1P86). Feel free to reopen with a repro.

**Comment by pablo-odorico** [comment]
1. I think this one is worth fixing as it fails with multiple compilers when building the base library. Adding the initialiser list is quite low risk.
2. This issue is not a blocker as `FMT_TEST=ON` is not required for deployment platforms.
3. I think this may be specific to Apple's clang. In any case 5.3.0 works and it does what we need for now so it's okay to close. Once we can deprecate that legacy platform we can move to the latest version.

Thanks.
