### ISSUE TITLE
std::map<> custom formatting capabilities

### ISSUE THREAD

**Issue by szilardszaloki** [fmtlib/fmt#2090]
Hi Victor!

I'd like to print a `std::map<int, char>` in the following format: `{ { 1, '1' }, { 2, '2' }, { 3, '3' } }`.
With `fmt::join<>()`, I could get as close as: `{ (1, '1'), (2, '2'), (3, '3') }`.
Is there a way to customize how the `std::pair<int const, char>`s are getting formatted?

Thanks!

**Comment by vitaut** [comment]
You can't do it with `join` but you could write a custom formatter using the usual extension API (https://fmt.dev/latest/api.html#formatting-user-defined-types) or iterate over elements and print them individually.
