### ISSUE TITLE
Got C4996 warning when building an application with v140 toolset

### ISSUE THREAD

**Issue by wwriter** [fmtlib/fmt#2092]
Hi, first of all thank you for providing and maintaining this great library.
I encountered this warning/error(depending on SDL check flag) while I've been testing my project with v140 toolset.
When I write codes somewhat like below, 
``` cpp
#include <fmt/format.h>
#include <fmt/core.h>

int main()
{
  fmt::format(L"{}_{:04d}-{:02d}-{:02d}{}", L"filename", 2020, 1, 12, L".txt"};
  return 0;
}
```
I got this compile error, which says
``` 
C4996: 'std::uninitialized_copy_n::_Unchecked_iterators::_Deprecate': Call to 'std::uninitialized_copy_n' with parameters that may be unsafe 
- this call relies on the caller to check that the passed values are correct. 
To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
```

It seems to happen only when I set the project toolset to v140, and use wide characters.
( It works perfect if I use visual studio 2017(v141 toolset) **or** v140 toolset with narrow characters. )

I read through the issues somewhat similar to mine, but unfortunately I couldn't get any solutions from them.
Is there something that I can do to successfully build my project in that environment?
( Defining `_SCL_SECURE_NO_WARNINGS` is not a good option for me )

**Comment by vitaut** [comment]
Same as #1947.
