### ISSUE TITLE
Missing "fmt/args.h" after install

### ISSUE THREAD

**Issue by fbdtemme** [fmtlib/fmt#2096]
The args.h header seems to be missing in the include directory when installing the project with cmake.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/ac352081159f0aebe707fc55e216984f75c7e6ad. Thanks for reporting.

**Comment by prince-chrismc** [comment]
👋 There's been a few great fixes that have are unreleased... just curious is there any ETA when there will be a stable release?

**Comment by vitaut** [comment]
In a couple of weeks probably.

**Comment by prince-chrismc** [comment]
Thanks ❤️
