### ISSUE TITLE
fmt::format_to + exception = SIGABRT

### ISSUE THREAD

**Issue by ivan-volnov** [fmtlib/fmt#2097]
Hi!

I suppose I found a problem in the library.

A trivial example. I want to use a static string without any memory allocation and I want to get an exception if it fails because of the string size:

```C++
try {
    boost::beast::static_string<5> str;
    // it throws std::length_error in boost::beast::static_string::push_back()
    fmt::format_to(std::back_inserter(str), "test{}", 123);
}
catch (const std::length_error &e) {
    std::clog << "ee " << e.what() << std::endl;
}
```
As result, the app was terminated with SIGABRT

I think the problem is here:
```C++
~iterator_buffer() { flush(); }
```

While exception unwinding iterator_buffer's destructor is called and it tries to write to the buffer again

I believe you can use something like this:

```C++
// exception_count(std::uncaught_exceptions())

// in the destructor
if (exception_count == std::uncaught_exceptions()) {
    database->exec("COMMIT");
    return;
}
// Called during stack unwinding. Rollback and don't throw
try {
    database->exec("ROLLBACK");
} catch (const std::exception &e) {
    std::cerr << "Transaction rollback error: " << e.what() << std::endl;
}
```

**Comment by vitaut** [comment]
Good catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/ce519e939b91250e52cb0c7a760482f936d0c970.
