### ISSUE TITLE
Lightweight configuration for embedded systems

### ISSUE THREAD

**Issue by pfox89** [fmtlib/fmt#2108]
Due to the fast speed and small size of fmt, I'd like to be able to use it in very resource-constrained embedded systems for debugging output, but it seems like this would require an even more minimal configuration than is currently available.

In particular, I would want a configuration that:
1. Does not require std::string or any dynamic memory allocation (formatting can use fixed-size buffers only, or possibly a preallocated memory pool for allocating temporary buffers).
2. Doesn't include float, double, long double, long long, or other larger formatters to reduce size.
3. Doesn't depend on stdio or other OS features (only C/C++ library features that don't require underlying OS support).

It looks like none of these requirements are show-stoppers; it seems like this should be doable mostly by ifdefing unneeded code out, but it looks like I'd also have to make an alternate version of basic_memory_buffer that doesn't support dynamic expansion.

Does anyone else have interest in an extremely lightweight configuration of fmt? Any advice on acheiving?

**Comment by pfox89** [comment]
I've created a fork https://github.com/pfox89/fmt to work on this.

So far I've made it possible to compile on the IAR ARM compiler with a default library configuration (no file descriptors or locale support). 

Running tests will be more difficult, because googletest was not designed to work on embedded systems, and seems to assume everything that isn't Windows has full POSIX functionality.

**Comment by vitaut** [comment]
There has been some interest in using {fmt} on embedded systems and people have contributed a number of improvements in this area over time, for example #1590. Some comments:

1. It is possible to avoid dynamic memory allocations with `format_to` / `format_to_n`.
2. Floating point support can be disabled with `FMT_USE_{FLOAT,DOUBLE,LONG_DOUBLE}`.
3. If you don't use formatted I/O functions, those can be discarded by linker with LTO or similar and not contribute to binary size.

PRs to make embedded usage easier are welcome provided that they are not too intrusive.

**Comment by pfox89** [comment]
OK, good to know!

The things that concern me about this are:

1. I don't have any way to run unit tests on this, since googletest doesn't have a configuration for running without an OS. It appears some extensive patching to googletest would be necessary to fix this.
2. It looks like in several places the formatter creates a memorybuffer on the stack (e.g. in int_writer::on_num()). This would be OK for a small buffer, but memorybuffer is 500 bytes by default, which might be the whole stack on some embedded systems! I'd have to add an option to set a much smaller default, e.g. 16 bytes, and prevent the memorybuffer from being able to new more memory.
3. There doesn't seem to be any way to safely handle errors without exceptions. It seems like the choices are an exception or a noreturn assert failure. I need a way to return safely on failure, so a program can continue even if a formatting error occurs. Maybe it can be set up so that it supports writing a failure to the output and returning immediately?
4. It generates some *very* long symbol names. Some tools choke on these. Ideally we'd keep symbols under 256 characters. I'm not sure what can really be done about this non-intrusively, though.
    Example: 
    `void fmt::v7::detail::parse_format_string<(bool)0, char, fmt::v7::detail::format_handler<fmt::v7::detail::buffer_appender<char>, char, fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>> &>(fmt::v7::basic_string_view<char>, fmt::v7::detail::format_handler<fmt::v7::detail::buffer_appender<char>, char, fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>> & &&)::writer::operator ()(char const *, char const *)::string`

**Comment by vitaut** [comment]
> It appears some extensive patching to googletest would be necessary to fix this.

Unfortunately I don't have any good suggestions here.

> I'd have to add an option to set a much smaller default, e.g. 16 bytes, and prevent the memorybuffer from being able to new more memory.

A PR to add such configuration option to {fmt} is welcome.

> Maybe it can be set up so that it supports writing a failure to the output and returning immediately?

The library can be compiled with exceptions disabled but some work might be required to propagate errors as error codes in this case instead of calling `abort`. Then it would be possible to build an error code based API on top of {fmt}.

> Maybe it can be set up so that it supports writing a failure to the output and returning immediately?

I think this is doable with some tricks such as subclassing common specializations.

**Comment by vitaut** [comment]
Closing for now but PRs to improve embedded support are welcome.
