### ISSUE TITLE
Crashing when trying to append to a file

### ISSUE THREAD

**Issue by logicReasoner** [fmtlib/fmt#2112]
Under Microsoft Visual Studio Community 2019
Version 16.7.4, I get
` Unhandled exception at 0x007D45B9 in test.exe: Fatal program exit requested.`

when running the following code:
```
auto a1 = fmt::format("Hello there1!\n");
    auto outputFile = fmt::output_file("C:/a.txt", fmt::file::CREATE | fmt::file::APPEND);
    outputFile.print("Hello there2!\n");
```
the file gets created successfully, a1 contains `Hello there1!\n`
The crash happens on the third line `    outputFile.print("Hello there2!\n");`

**Comment by moiwi** [comment]
You don't give yourself write permission to this file. This works for me:

```
auto a1 = fmt::format("Hello there1!\n");
    auto outputFile = fmt::output_file("C:/a.txt", fmt::file::RDWR | fmt::file::CREATE | fmt::file::APPEND);
    outputFile.print("Hello there2!\n");
```
