### ISSUE TITLE
Automatically adds ^M ('\r') before each new line ('\n') on Windows

### ISSUE THREAD

**Issue by logicReasoner** [fmtlib/fmt#2115]
After compiling with Visual Studio and running the program, it automatically adds ^M characters before each \n character to the string stored in the file. Can this behavior be disallowed / configured somehow? I don't want to store any extra characters in the file.

```
auto outputFile = fmt::output_file("C:/a.txt", fmt::file::RDWR | fmt::file::CREATE | fmt::file::APPEND);
outputFile.print("blabla\nfoo\nbar");
```

**Comment by vitaut** [comment]
This is the behavior of the `_open` CRT function on Windows. You can add `_O_BINARY` flag to prevent translation of newlines.
