### ISSUE TITLE
<fmt/ranges.h> disables OpenCV pretty printing

### ISSUE THREAD

**Issue by pauljurczak** [fmtlib/fmt#2125]
I'm using gcc-10.1.0 and OpenCV 4.5.1-dev on Ubuntu 18.04.5. This code snippet:
```
#include <fmt/format.h>
#include <fmt/color.h>
#include <fmt/ostream.h>

using namespace std;
using fmt::print;
...
  auto m2 = Mat_<float>({2, 2}, {1, 2, 3, 4});
  cout << m2 << endl;
  print("{}\n", m2);
```
produces:
```
[1, 2;
 3, 4]
[1, 2;
 3, 4]
```
as expected. When I add `#include <fmt/ranges.h>` the result is undesirable:
```
[1, 2;
 3, 4]
{1.0, 2.0, 3.0, 4.0}
```

**Comment by vitaut** [comment]
That's expected, `fmt/ranges.h` provides `formatter` specialization for ranges.
