### ISSUE TITLE
Using fmt::localtime in wide-char format strings is broken

### ISSUE THREAD

**Issue by yNeo** [fmtlib/fmt#2127]
chrono.h:L416 is:
`FMT_CONSTEXPR auto parse(format_parse_context& ctx) -> decltype(ctx.begin()) {`
while it should be:
`FMT_CONSTEXPR auto parse(basic_format_parse_context<Char>& ctx) -> decltype(ctx.begin()) {`

**Comment by vitaut** [comment]
Could you submit a PR?

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/c5979d564e1ec40c383eaca610c8aa7cca1733a4.
