### ISSUE TITLE
Regression: custom ostream formatting doesn't work with namespaced types after v7

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#2130]
Version: latest

`operator<<` in global namespace should be discoverable as long as it is defined before fmt facilities.
And it worked like that at least until v7 ([godbolt](https://godbolt.org/z/MW481c)).

However, at some point after v7, presumably after [16cac46](https://github.com/fmtlib/fmt/commit/16cac46a094aa1b182494f1935c2267189262827#diff-39be774d509c569b421ee9c510ad5f6d306f4a187ce4540b03c761d77a087b32R61-R72), it stopped working ([godbolt](https://godbolt.org/z/W15bT8)).

The latest trunk works if the offending code is commented ([godbolt](https://godbolt.org/z/vj85nW)).

**Comment by LukeMauldin** [comment]
I have experienced this issue as well.

**Comment by vitaut** [comment]
https://github.com/fmtlib/fmt/commit/16cac46a094aa1b182494f1935c2267189262827 is a fix for #1766. Unfortunately I don't know how to make both cases work. Considering that defining `operator<<` in a different namespace from the type is not well-supported anyway (depends on the order of inclusion), I recommend moving it to the appropriate namespace where it can be found by ADL (https://godbolt.org/z/q3MPM6):

```c++
namespace ns
{
    class test {};

    std::ostream& operator<<(std::ostream& Stream, test const&)
    {
        Stream << "ns::test\n";
        return Stream;
    }
}
```
If someone knows a solution that doesn't break #1766, a PR would be welcome.

**Comment by vitaut** [comment]
Clarified the limitation in the docs: https://github.com/fmtlib/fmt/commit/d28101878a3d03fd7a83518aac957a9bd0ec2c52.

**Comment by alabuzhev** [comment]
> I recommend moving it to the appropriate namespace where it can be found by ADL

Unfortunately that's UB for std types :(

**Comment by vitaut** [comment]
You can also provide a `formatter` specialization that delegates to `operator<<`:

```c++
template <>
struct fmt::formatter<ns::test> : formatter<std::string> {
  auto format(const ns::test& t, format_context& ctx) {
    std::ostringstream os;
    os << t;
    return formatter<std::string>::format(os.str(), ctx);
  }
};
```
We could make it simpler, something like:

```c++
template <> struct fmt::formatter<ns::test> : fmt::ostream_formatter<ns::test> {};
```

**Comment by alabuzhev** [comment]
Thank you - a formatter specialization works as expected.
I've seen this API before, but it seemed quite cumbersome and I avoided it as long as `<<` worked.
