### ISSUE TITLE
Plus flag formatting with locale is broken

### ISSUE THREAD

**Issue by mp-t** [fmtlib/fmt#2133]
`fmt::format(std::locale("en_US.UTF-8"), "{:+L}", 100);` produces an out-of-bounds memory access and wrong output.

Possible output: "-100" or ",100" depening on the fmt version. 
Expected output: "100"

[Godbolt sample](https://godbolt.org/z/Y3vhYT)

**Comment by vitaut** [comment]
Fixed '+' handling with locale in https://github.com/fmtlib/fmt/commit/ee0fed639c78a36686b6cf50ac66fc7a87df9f28. Thanks for reporting.
