### ISSUE TITLE
Any simple api like fmt::print but which flushes ? 

### ISSUE THREAD

**Issue by jcelerier** [fmtlib/fmt#2134]
e.g. here (linux), doing fmt::print("foobar\n");  does not flush, I have to wait until what looks like a few hundred lines of content have been printed for things to be shown on my screen (which is fairly frustrating).
I'd rather not sprinkle my codebase with `fflush(stdout);`...

Thanks !

**Comment by vitaut** [comment]
There are not plans to add such API but you can either use `fflush` or write a function that flushes automatically.

**Comment by brenoguim** [comment]
> There are no plans to add such API but you can either use `fflush` or write a function that flushes automatically.

May I ask if the reason for not adding this to the plan due to lack of resources, or is it an explicit decision not to add this?
This was the very first issue we hit from migrating debug code out of `std::cout`. And we didn't migrate because of that.

We can create a header to implement this functionality, but I really think this will be really useful for everyone using fmt for debugging.

**Comment by vitaut** [comment]
You can add a function that combines printing and flushing, it doesn't have to be in the core library. {fmt} mostly follows printf API in separating these two independent pieces of functionality.

**Comment by vitaut** [comment]
Here's how it can be implemented:

```c++
template <typename... T>
void flushed_print(fmt::format_string<T...> fmt, T&&... args) {
  fmt::print(fmt, std::forward<T>(args)...);
  fflush(stdout);
}
```

**Comment by brenoguim** [comment]
I understand it's a very small snippet of code. But there are many small snippets of code that are worth providing to avoid multiple replications in all codebases, improve ergonomics and having the "it just works" feeling.
My main goal was to avoid the "but" effect when advertise fmt to our RD. Like "use for but, if you are using if for debugging be aware..."
I'll likely create an internal fmt fork to add this so I'll be fine, but maybe it's a point to reconsider. Maybe a twitter poll would be useful to gather more feedback? :)

**Comment by itmuckel** [comment]
This is incredibly annoying, when building something like a game, where you need instant console logs. I litter my code everywhere with 
```cpp
fmt::print("my_var: {}\n", varr);
std::fflush(nullptr);
```

Will the standard version of fmt also not flush by default? I think this is a very bad decision. 😕

**Comment by codeinred** [comment]
Flushing after every print would necessarily incur significant overhead, since flushing is a slow operation, so I don't think `fmt::print` should flush by default. However, a function `fmt::eprint` which *did* flush would probably be good

**Comment by OlafvdSpek** [comment]
> Flushing after every print would necessarily incur significant overhead, since flushing is a slow operation, so I don't think `fmt::print` should flush by default. However, a function `fmt::eprint` which _did_ flush would probably be good

What does the `e` stand for?

**Comment by kasufert** [comment]
> This is incredibly annoying, when building something like a game, where you need instant console logs. I litter my code everywhere with
> 
> ```c++
> fmt::print("my_var: {}\n", var);
> std::fflush(nullptr);
> ```
> 
> Will the standard version of fmt also not flush by default? I think this is a very bad decision. 😕

```c++
#define Log(x) fmt::print(x); std::fflush(stdout);
```
Yes I know macros are evil and the spawn of Satan himself but I don't think this one is doing too much harm...

**Comment by kiwixz** [comment]
fmt does not take the decision to buffer or not the output, it just forwards the content to the libc.

It is your responsibility to configure it with [setvbuf](https://en.cppreference.com/w/cpp/io/c/setvbuf) if you don't like its default behavior.

You can turn off buffering with:
```cpp
setvbuf(stdout, nullptr, _IONBF, 0);
```
