### ISSUE TITLE
detail::write optimization for array of chars

### ISSUE THREAD

**Issue by AndrewJD79** [fmtlib/fmt#2136]
Hi,

I'm new in the fmt library, so I'm sorry if the question is stupid or already answered.

I have question about following piece of code:
https://github.com/fmtlib/fmt/blob/7e72673d87cc44340f4b808d0b536e4e191342b5/include/fmt/format.h#L2283-L2293

Why there is no specialization for array of chars to avoid string length calculation when string literal passed to the function? Something like this:
```
template <typename Char, typename OutputIt, size_t N>
FMT_CONSTEXPR OutputIt write(OutputIt out, const Char (&value)[N]) {
  if (!value) {
    FMT_THROW(format_error("string pointer is null"));
  } else {
    auto length = N;
    out = write(out, basic_string_view<Char>(value, length));
  }
  return out;
}
```

Thank you

**Comment by vitaut** [comment]
`write` is an internal function and it doesn't need handle literal case itself.

**Comment by AndrewJD79** [comment]
Public function fmt::to_string  directly calls the write. 

For instance I have some templated code which forwards calls to  fmt::to_string. 
e.g.:
```
struct Foo {
   template <typename T>
   void log (const T& v)
   {
      m_out += fmt::to_string(v);
   }
private:
   std::string m_out;
};

Foo foo;
 foo.log("bar");

```
For example above fmt::to_string decays parameter from 'const char[4]&' to 'const char*'.

**Comment by vitaut** [comment]
We could provide an overload of `to_string` although it's probably not worth optimizing the case of converting a string into a string =).
