### ISSUE TITLE
Provide a mechanism to disable color formatting globally

### ISSUE THREAD

**Issue by allisonvacanti** [fmtlib/fmt#2137]
It would be nice to disable text styles globally. Ideally, both:

1. An API call or global variable for applications to use, and 
2. An environment variable that users could set when an application doesn't expose this option.

Some terminals (MSVC dev terminals are a glaring example) can't handle the formatting markup, and produce unreadable output when formatting is used (#1794).

#1549 suggests a way to implement this by placing special logic at every call into fmtlib, but this is burdensome and error prone. Having a library-wide solution for this problem would be fantastic.

If there's already a good workaround for this, please let me know. I found some closed issues that were related, but nothing that quite does what I'm looking for here.

**Comment by nenin-sc** [comment]
You can try do something like this to force win console in appropriate mode:
  
 HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
  DWORD dwMode = 0;
  GetConsoleMode(hOut, &dwMode);
  dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
  SetConsoleMode(hOut, dwMode);

**Comment by allisonvacanti** [comment]
That's a useful workaround, though I'll still need a way to disable color for file output, etc. 

I'll see about enabling this workaround in my app, but long term -- is this something that fmtlib could do automatically? It'd be great if this worked out-of-the-box.

**Comment by vitaut** [comment]
Thanks for the suggestion. I don't think that {fmt} should provide a mechanism to suppress color output based on the global state but you can easily write a formatting function that does this:

```c++
#include <fmt/color.h>

bool disable_color = false;

template <typename... Args>
void myprint(const fmt::text_style& ts, const Args&... args) {
  fmt::print(disable_color ? fmt::text_style() : ts, args...);
}

int main() {
  myprint(fg(fmt::terminal_color::red), "Hello\n");
  disable_color = true;
  myprint(fg(fmt::terminal_color::red), "Hello\n");
}
```
Godbolt: https://godbolt.org/z/bczTor

Additionally, it would be nice to fix color formatting on Windows and/or provide an API that enables ANSI escape sequences (basically what @nenin-sc suggested). PRs would be welcome =).

**Comment by allisonvacanti** [comment]
Fair enough :)

I'll probably just disable color on `cmd` for now, but if I find some time to fix it for real later I'll make a PR here.
