### ISSUE TITLE
Support ignoring formatting errors

### ISSUE THREAD

**Issue by Warchant** [fmtlib/fmt#2138]
In my app I would like to ignore all formatting errors (or maybe print a message?), instead of failing with an exception.

```
// ignore all formatting erros
#define FMT_THROW(...)
#include <fmt/format.h>

fmt::format("%s {}", "hello!", 42);
// execution continues...
```

But currently it is not possible, because `on_error` handler is `noreturn` here: https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L1931-L1933
and potentially in several other places.

Would it be possible to add support for this use-case?

**Comment by vitaut** [comment]
Thanks for the suggestion. You can catch errors in format strings at compile time (https://fmt.dev/latest/api.html#compile-time-format-string-checks) which will be enabled by default in the future (#2022). Other errors may not be recoverable. So I don't think it's worth investing into a mechanism to disable errors.
