### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Cozeee** [fmtlib/fmt#2139]
LNK1104	impossible d'ouvrir le fichier 'C:\Users\s7qua\OneDrive\Bureau\BigBaseV2-master\bin\lib\Debug\fmtlib.lib'	BigBaseV2	C:\Users\s7qua\OneDrive\Bureau\BigBaseV2-master\BigBaseV2\LINK	1

**Comment by vitaut** [comment]
Please provide repro details. My guess is that you should be linking with `fmtlibd.lib` instead of `fmtlib.lib` in debug mode.
