### ISSUE TITLE
sprintf equivalent to fmt::format_to

### ISSUE THREAD

**Issue by alzix** [fmtlib/fmt#2150]
Working with a logger (eg [spdlog](https://github.com/gabime/spdlog)) it is sometimes desirable to have POSIX like formatting as offered by fmt/printf.h.
Please consider adding intermediate API for performing `sprintf` functionality to a `basic_memory_buffer`.
Existing API returns a `vsprintf` returns a string.

Templates used in printf.h are a bit different from the template used in format.h - lacking the SIZE argument, which does not allow easy drop in replacement.

**Comment by vitaut** [comment]
There are no plans to support `basic_memory_buffer` in `sprintf` API because the latter is for migrating legacy code only, but a PR to add `snprintf` that prints to a fixed buffer would be welcome.
