### ISSUE TITLE
Performance regression since 7.0.0 on godbolt

### ISSUE THREAD

**Issue by BuzaL** [fmtlib/fmt#2153]
Comparing to 6.2.1 version, most of the format (expect FMT_COMPILE) getting about 4-5 times slower, regardless of C++ version and compiler:

https://godbolt.org/z/TGn1cx

**Comment by vitaut** [comment]
I wasn't repro this locally and compiling with `-DFMT_HEADER_ONLY` on godbolt shows no regression either (https://godbolt.org/z/E3Yzrr). @mattgodbolt, is it possible that CE has a debug version of the {fmt} library installed?

**Comment by mattgodbolt** [comment]
Hi there! How might I check?

**Comment by vitaut** [comment]
> How might I check?

I thought you might have a library build log. {fmt} cmake script prints the build type, e.g.:

```
-- Build type: Debug
```

**Comment by mattgodbolt** [comment]
It's all good, this is working as intended: we only build debug in Compiler Explorer as it stands. CC @partouf .

CE is not really designed for performance testing, so it's not bee a problem. And one can't easily see the results of linking against a static library either. We can look in to it if it's a problem

**Comment by vitaut** [comment]
Good to know, thanks for investigating! This is not a problem, just a bit surprising. Is there any particular reason debug build is the default?

**Comment by mattgodbolt** [comment]
Debug is the default as it gives the best library attribution (according to @partouf "mostly to not mix, but it also helps when inlining the libraries with being able to identify the library code")

**Comment by BuzaL** [comment]
@vitaut @mattgodbolt Thanks a lot to check it (unf. last night I've had only a browser to do...)

**Comment by mattgodbolt** [comment]
Thanks @BuzaL . This is a kick for us to consider options in Compiler Explorer.
