### ISSUE TITLE
Dynamic memory allocation in floating-point formatting

### ISSUE THREAD

**Issue by HFriberg** [fmtlib/fmt#2154]
I'm interested in using `fmt` for floating-point formatting in an environment where dynamic memory allocation is forbidden. In #1665 it was stated that

> Built-in formatters don't allocate memory [..., but] floating-point formatting can sometimes fall back to s(n)printf and the latter can potentially allocate.
_May 2020_

A few months later it was stated in #1526 that

> The internal FP formatter is now always used for IEEE 754 float and double formatting including for arbitrary precision.
_Sep 2020_

Does this mean that in the current stable release, floating-point formatting will never fall back to s(n)printf and thus guarantee never to make dynamic memory allocations? Or can this guarantee only be made for a subset of the [format specifiers](https://fmt.dev/latest/syntax.html#format-specification-mini-language)? It would be awesome if such guarantees were documented, so the extend of this feature (which may change of time) could be tracked across releases.

**Comment by vitaut** [comment]
There shouldn't be memory allocations for IEEE 754 `binary32` and `binary64` and locale-independent decimal format specifiers (anything other than `a`, `A`, `L`). `long double` can still allocate if it's different. A PR to mention it in the docs would be welcome.
