### ISSUE TITLE
Compile flags optimization

### ISSUE THREAD

**Issue by yamaken93** [fmtlib/fmt#2159]
I did not find any optimization(like -O3 or -O2) in the cmakelists.txt. Is it correct? I thought about compiling it with -O3 and -march=native but not sure which are the runtime risks.
Thanks.

**Comment by vitaut** [comment]
Build flags are automatically added by CMake (https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html) but you can override them. Please see CMake docs for details.

**Comment by yamaken93** [comment]
@vitaut thanks
