### ISSUE TITLE
Help with overload resolution

### ISSUE THREAD

**Issue by seanbaxter** [fmtlib/fmt#2162]
Hi Victor, I'm trying fix an issue in Circle that is preventing fmt from compiling. 

```cpp
instantiation: /home/sean/projects/fmt/include/fmt/core.h:1824:13
during instantiation of function template std::enable_if<true, fmt::detail::buffer_appender<char>>::type fmt::format_to(fmt::detail::buffer_appender<char>, const FMT_COMPILE_STRING&, fmt::string_view&, const char(&)[3])
template arguments: [
  'OutputIt' = fmt::detail::buffer_appender<char>
    class 'fmt::detail::buffer_appender' declared at /home/sean/projects/fmt/include/fmt/core.h:864:1
  'S' = FMT_COMPILE_STRING
    class 'FMT_COMPILE_STRING' declared at /home/sean/projects/fmt/include/fmt/format-inl.h:149:19
  'Args#0' = fmt::basic_string_view<char>&
    class 'fmt::basic_string_view' declared at /home/sean/projects/fmt/include/fmt/core.h:365:26
  'Args#1' = const char(&)[3]
  'enable' = bool true
]
inline auto format_to(OutputIt out, const S& format_str, Args&&... args) -> 
            ^
  error: /home/sean/projects/fmt/include/fmt/core.h:1827:20
  no viable candidates in call to 'vformat_to'
    argument 0 is lvalue fmt::detail::buffer_appender<char>
      fmt::detail::buffer_appender<char> declared at /home/sean/projects/fmt/include/fmt/core.h:864:1
    argument 1 is prvalue fmt::basic_string_view<char>
      fmt::basic_string_view<char> declared at /home/sean/projects/fmt/include/fmt/core.h:365:26
    argument 2 is lvalue const fmt::format_arg_store<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>, fmt::basic_string_view<char>, const char[3]>
      fmt::format_arg_store<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>, fmt::basic_string_view<char>, const char[3]> declared at /home/sean/projects/fmt/include/fmt/core.h:1545:1
    return vformat_to(out, to_string_view(format_str), vargs); 
                     ^
    candidate: /home/sean/projects/fmt/include/fmt/format.h:4052:13
    inline void vformat_to( 
                ^
      error: /home/sean/projects/fmt/include/fmt/core.h:1827:21
      cannot deduce parameter 'buf' with type fmt::detail::buffer<Char>& from argument lvalue fmt::detail::buffer_appender<char>
        return vformat_to(out, to_string_view(format_str), vargs); 
                          ^

    candidate: /home/sean/projects/fmt/include/fmt/core.h:1782:6
    void vformat_to( 
         ^
      error: /home/sean/projects/fmt/include/fmt/core.h:1827:21
      cannot deduce parameter 'buf' with type fmt::detail::buffer<Char>& from argument lvalue fmt::detail::buffer_appender<char>
        return vformat_to(out, to_string_view(format_str), vargs); 
                          ^

    candidate: /home/sean/projects/fmt/include/fmt/core.h:1802:6
    auto vformat_to(OutputIt out, const S& format_str, 
         ^
      error: /home/sean/projects/fmt/include/fmt/core.h:1827:54
      cannot deduce parameter 'args' with type fmt::basic_format_args<fmt::buffer_context<fmt::type_identity_t<Char>>> from argument lvalue const fmt::format_arg_store<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>, fmt::basic_string_view<char>, const char[3]>
        return vformat_to(out, to_string_view(format_str), vargs); 
                                                           ^

    candidate: /home/sean/projects/fmt/src/format.cc:36:1
    vformat_to(buffer<Char>& buf, basic_string_view<Char> format_str, 
    ^
      error: /home/sean/projects/fmt/include/fmt/core.h:1827:21
      cannot deduce parameter 'buf' with type fmt::detail::buffer<Char>& from argument lvalue fmt::detail::buffer_appender<char>
        return vformat_to(out, to_string_view(format_str), vargs); 
                          ^
```
The problem is a call to `vformat_to` at core.h:1827 finds four candidates, but none of them viable. 3 candidates take buffer<Char>& buf for parameter 0, which fails conversion. I think that is correct, as the argument is buffer_appender which seems unlikely to convert to buffer.. The last candidate is core.h:1827, and there I can't convert `format_arg_store` to `basic_format_args`. What should be going on here?

param type: `fmt::basic_format_args<fmt::buffer_context<fmt::type_identity_t<Char>>>`
arg type: `lvalue const fmt::format_arg_store<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>, fmt::basic_string_view<char>, const char[3]>`

There is this likely looking ctor:
```cpp
  template <typename... Args>
  constexpr FMT_INLINE basic_format_args(
      const format_arg_store<Context, Args...>& store)
      : basic_format_args(store.desc, store.data_.args()) {}
```

But the `format_arg_store` parameter would require specialization over a different context than `basic_format_context` (it would need `buffer_context`). I'm guessing there's another implicit conversion I'm missing? What's the desired conversion sequence for binding this argument to the parameter type?

Thanks

**Comment by seanbaxter** [comment]
When I comment out the FMT_GCC_VERSION < 409 guard in core.h:1550, format.cc compiles. Do I have this same template argument substitution bug alluded to? Do you remember the nature of this bug?

**Comment by vitaut** [comment]
This should be the matching overload: https://github.com/fmtlib/fmt/blob/772aeca3380605a8cc73cfb4fec606a28850c9df/include/fmt/core.h#L1800-L1804

> What should be going on here?

`format_arg_store` is implicitly convertible to `basic_format_args`: https://godbolt.org/z/rj6cYG.

`fmt::buffer_context<char>` is just an alias of `fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>`: https://github.com/fmtlib/fmt/blob/772aeca3380605a8cc73cfb4fec606a28850c9df/include/fmt/core.h#L1522-L1524

> Do I have this same template argument substitution bug alluded to?

It seems so.

> Do you remember the nature of this bug?

I don't know what the actual bug was (probably some issue with aliases) but IIRC the observable effect was the same - it didn't find the correct overload.

**Comment by seanbaxter** [comment]
Thanks Victor. That was a challenging one. In my code, format_arg_store was already convertible to basic_format_args, no problem. The issue was that the Char template parameter in buffer_context<Char> wasn't deducible from the argument type format_arg_store, because they're different templates. At this point I was treating it as a failed deduction, but I should have treated it as a non-deduction, and waited until template default arguments are set, because Char has a default type char_t<S>, and S was deduced by the earlier parameter.

The gcc 4.09 workaround made basic_format_args a base class of format_arg_store, so that deduction here actually worked, because the argument type had a base class specialization of the parameter class template.

Thanks. That seemed to have cleared up several issues.

**Comment by vitaut** [comment]
So can Circle now compile {fmt}?

**Comment by seanbaxter** [comment]
Simple examples work but some of the tests fail. ConstexprSpecsHandler in format-test.cc is what I'm hacking on now.parse_specs isn't getting me the right alignment and stuff. It'll get there.

**Comment by seanbaxter** [comment]
Aha! There are bit-fields in basic_format_spec being set during compile-time parsing. I didn't have the bitfield masks on to do the stores. Didn't even know it was valid in constexpr.
