### ISSUE TITLE
Feature request: formatting of floats without parsing format strings

### ISSUE THREAD

**Issue by mheiskan** [fmtlib/fmt#2165]
Our software formats weather data as SVG paths with 0.1 pixel precision and numerical observations and forecasts with parameter dependent precision. It would increase our service speed if such formatting could be specified without parsing a format string. For reference, our servers handle several hundreds of requests per second with WMS requests possibly containing tens of thousands of vertex coordinates.

We're aware of FMT_COMPILE, but unfortunately it requires C++17, which is not readily available in RHEL7.

I see your implementation details have an interface like this:

```
template <typename T>
int format_float(T value, int precision, float_specs specs, buffer<char>& buf) {
```

Could you consider making a similar public API for formatting floats so that format strings would not be needed at all?

**Comment by vitaut** [comment]
{fmt} only supports format string API. Note that format string parsing overhead is relatively small compared to floating-point formatting itself (and it can be improved further).

**Comment by mheiskan** [comment]
Fair enough. Any further speed improvements are most welcome.
