### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by pauljurczak** [fmtlib/fmt#2166]
Building the Library page https://fmt.dev/latest/usage.html#building-the-library has these lines:
`cmake -DBUILD_SHARED_LIBS=TRUE ...`
`cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE ...`

There should be `..` instead of `...` at the end.

**Comment by vitaut** [comment]
Thanks but this is intentional with `...` denoting additional cmake arguments and not parent directory.
