### ISSUE TITLE
Visual Studio 2019 16.9.0 issue

### ISSUE THREAD

**Issue by tksuoran** [fmtlib/fmt#2167]
After upgrading Visual Studio 2019 to version 16.9.0, I ran into compilation issue:

```
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include\optional(35): error C2131: expression did not evaluate to a constant
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include\optional(35): note: failure was caused by call of undefined function or one not declared 'constexpr'
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include\optional(35): note: see usage of 'std::nullopt_t::nullopt_t'
```

The issues only showed up in source files that included a header that contained

```
#define FMT_HEADER_ONLY
#include "fmt/format.h"
```

I dropped `FMT_HEADER_ONLY` and switched to `#include "fmt/core.h"` and only included `#include "fmt/format.h"` in source files and this worked around the issue.

This may be related to https://developercommunity.visualstudio.com/t/unexpected-error-c2131-expression-did-not-evaluate/1343697

**Comment by vitaut** [comment]
I wasn't able to repro this on godbolt: https://godbolt.org/z/8KnxG3. What compiler options do you use and could you provide a repro?

**Comment by tksuoran** [comment]
I'll try to make a repro tomorrow. It involved using std::optional<my non copyably, movable type>. Note that I think this is probably a bug in msvc and not fmt.

**Comment by tksuoran** [comment]
Try this: https://godbolt.org/z/3sMf7Y

Compiler options: `/std:c++latest`
```
#define FMT_HEADER_ONLY
#include <fmt/format.h> // comment this (avoid issue)

#include <cstddef>

namespace glm
{
	template<typename T, std::size_t N>
	constexpr std::size_t countof(T const (&)[N])
	{
		return N;
	}
}
// ; // uncomment this (workaround compiler issue)

#include <optional>
#include <filesystem>
#include <map>

auto main(int argc, char** argv) -> int
{
    static_cast<void>(argc);
    static_cast<void>(argv);
    return 0;
}
```

**Comment by vitaut** [comment]
Thanks for the repro. This looks like a compiler bug to me, please report to MSVC folks. If you have a workaround, a PR would be welcome too provided that it's not very intrusive.
