### ISSUE TITLE
vformat_to_n question

### ISSUE THREAD

**Issue by seanbaxter** [fmtlib/fmt#2168]
My compiler is breaking in the vformat_to_n tests in format-test.cc.

```cpp
instantiation: /home/sean/projects/fmt/include/fmt/core.h:1839:37
during instantiation of function template fmt::format_to_n_result<char*> fmt::vformat_to_n(char*, size_t, fmt::basic_string_view<char>, fmt::basic_format_args<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>>)
template arguments: [
  'OutputIt' = char*
  'Char' = char
  '3' = int 0
]
inline format_to_n_result<OutputIt> vformat_to_n( 
                                    ^
  error: /home/sean/projects/fmt/include/fmt/core.h:1845:26
  'count' is not a member of class fmt::detail::iterator_buffer<char*, char, fmt::detail::fixed_buffer_traits>
    class definition at /home/sean/projects/fmt/include/fmt/core.h:806:58
    return {buf.out(), buf.count()}; 
                           ^
```

In core.h:1845 buf.count() is being called on an `iterator_buffer`. The arguments I deduce are char* and char, so it chooses the partial template at core.h:806 which doesn't have a count() member function. 

The specific test code that triggers this is 
```cpp
TEST(FormatTest, FormatToN) {
  char buffer[4];
  buffer[3] = 'x';
  auto result = fmt::format_to_n(buffer, 3, "{}", 12345);
}
```
Pretty clearly OutputIt will be deduced as char* and Char as char, as shown in the error. So how does that count-less partial for iterator_buffer not get chosen?

**Comment by vitaut** [comment]
I think it should choose https://github.com/fmtlib/fmt/blob/6a9016ea600738ded2b90666d62b8f9bd241c00b/include/fmt/core.h#L781-L782 instead of https://github.com/fmtlib/fmt/blob/6a9016ea600738ded2b90666d62b8f9bd241c00b/include/fmt/core.h#L806
because the latter doesn't have the trait parameter.

**Comment by seanbaxter** [comment]
Ya that's it. Can't believe this has never showed up before.
