### ISSUE TITLE
Error when importing fmt from Conan

### ISSUE THREAD

**Issue by alexisfrjp** [fmtlib/fmt#2169]
* **Centos 7** and the `devtoolset-8` => works
* **Centos8 Stream + Conan** and gcc8 => doesn't work
* **Centos8 Stream + fmt header-only** and gcc8 => works

What's broken with Conan?

### Conan:
```
[requires]
fmt/7.1.3
```
### Error message:

> /home/alexis/.conan/data/fmt/7.1.3/_/_/package/a2582e1f57e524e15d7e84f4c862d0a472d3216f/include/fmt/core.h:2076:
> undefined reference to
> `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>,
> fmt::v7::format_args)' CMakeFiles/app_network.dir/app_network.cpp.o:
> In function `printMacAddress[abi:cxx11](unsigned long)':
> /home/alexis/.conan/data/fmt/7.1.3/_/_/package/a2582e1f57e524e15d7e84f4c862d0a472d3216f/include/fmt/core.h:2076:
> undefined reference to
> `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>,
> fmt::v7::format_args)'

* Is it a fmt problem?
* Is it a Conan problem?
* What can it be?!

**Comment by vitaut** [comment]
Looks like you are not linking with the library. Please report the issue to conan.

**Comment by trueman1990** [comment]
@alexisfrjp I want to check with you if this issue has been fixed? We also met this issue in some cases when importing fmt from Conan.

**Comment by alexisfrjp** [comment]
Yes it's fixed, it was not an fmt issue. Thanks.

**Comment by trueman1990** [comment]
> 

Great. Could you share with me how to fix this issue?

**Comment by alexisfrjp** [comment]
I think the issue was in the Conan's setting, using the wrong C++ ABI version for my OS/Centos7.
https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html

**Comment by trueman1990** [comment]
> I forgot but I think the issue was in the Conan's setting. Something related to the C++ ABI version, maybe the wrong setting for my OS/Centos7. https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html

I tried to set libstdc++ but it didn't work for me. Anyway, appreciate your help.

**Comment by trueman1990** [comment]
Thank you very much. I will try!
