### ISSUE TITLE
Test find-package-test (Failed)

### ISSUE THREAD

**Issue by phprus** [fmtlib/fmt#2171]
If ```FMT_PEDANTIC``` is ```ON``` and ```FMT_INSTALL``` is ```OFF``` (fmt is subproject) test ```find-package-test``` is failed.

Possible fix (```src/test/CMakeLists.txt```):
Replace ```if (FMT_PEDANTIC AND NOT WIN32)``` to ```if (FMT_INSTALL AND FMT_PEDANTIC AND NOT WIN32)```.

**Comment by vitaut** [comment]
Thanks for reporting, but `FMT_PEDANTIC` is an internal flag, it's not supposed to be used outside of {fmt}'s CI.
