### ISSUE TITLE
Applying different color to different parts

### ISSUE THREAD

**Issue by heraldofsolace** [fmtlib/fmt#2173]
Right now I can do -
```
fmt::print(fmt::fg(fmt::color::blue), "Copying {} to {}\n", from, to);
```
But this prints the whole line in blue. Is there a way I can print parts of the string in different colors? For example, the first argument in blue and the 2nd argument in red?

**Comment by vitaut** [comment]
You can either call `print` multiple times or write a `formatter` specialization that applies color to an argument.
