### ISSUE TITLE
UBSan reports array arithmetic error using fmt::join

### ISSUE THREAD

**Issue by ldalessa** [fmtlib/fmt#2175]
Not sure where it's coming from or if it's a false positive.

https://godbolt.org/z/56YG8s

edit: this is on master circa a1ea8a8, 7.0.0 is fine on godbolt, 7.1.3 is fine on my local debian machine

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/8f9db3fcb8d739de5720ebe7713db3591fbe0c1b, thanks for reporting.
