### ISSUE TITLE
When do static build, the libfmt.a can be generated but won't be installed to CMAKE_INSTALL_LIBDIR

### ISSUE THREAD

**Issue by gemfield** [fmtlib/fmt#2182]
This issue is related with https://github.com/pytorch/pytorch/pull/53825

When build pytorch static library, as a third party repo of pytorch, the libfmt.a can be generated, but missing in CMAKE_INSTALL_LIBDIR.

After build with command:
```bash
cmake --build . --target install -- "-j8"
```
In the build dir, we have:
```bash
root@build_libtorch:/gemfield/github/build# find . -name "*.a" | grep fmt
./lib/libfmt.a
root@build_libtorch:/gemfield/github/build# 
```

In the install dir, we have:
```bash
root@build_libtorch:/gemfield/github/libtorch_cuda/lib# find . -name "*.a" | wc -l
25
root@build_libtorch:/gemfield/github/libtorch_cuda/lib# find . -name "*.a" | grep fmt
root@build_libtorch:/gemfield/github/libtorch_cuda/lib#
```

**Comment by vitaut** [comment]
Thanks for reporting but I was not able to reproduce this. Library files are installed in the location specified by `CMAKE_INSTALL_LIBDIR` unless `FMT_LIB_DIR` is overriden:
```
$ git clone https://github.com/fmtlib/fmt.git
$ cd fmt
$ cmake -DCMAKE_INSTALL_LIBDIR=~/fmt/test-install .
$ cmake --build . --target install -- "-j8"
...
Install the project...
-- Install configuration: "Release"
-- Installing: /home/vagrant/fmt/test-install/libfmt.a
-- Installing: /home/vagrant/fmt/test-install/cmake/fmt/fmt-config.cmake
-- Installing: /home/vagrant/fmt/test-install/cmake/fmt/fmt-config-version.cmake
-- Installing: /home/vagrant/fmt/test-install/cmake/fmt/fmt-targets.cmake
-- Installing: /home/vagrant/fmt/test-install/cmake/fmt/fmt-targets-release.cmake
...
$ find ~/fmt/test-install -name "*.a" | grep fmt
/home/vagrant/fmt/test-install/libfmt.a
```

**Comment by gemfield** [comment]
@vitaut 
It turns out that whether to install libfmt.a is controlled by FMT_INSTALL option, which is determined by MASTER_PROJECT option. So the questions become to:
- why don't install libfmt.a when fmt is a submodule of pytorch(or other projects)?
- to install libfmt.a when build pytorch, what should I do/modify in PyTorch project, or in fmt project?

**Comment by vitaut** [comment]
> why don't install libfmt.a when fmt is a submodule of pytorch(or other projects)?

Whether {fmt} should be included in the install or not depends on the master project's use of the library. I am not sure if there is a good default here but in general I would expect a project not to install third-party libraries.

> to install libfmt.a when build pytorch, what should I do/modify in PyTorch project, or in fmt project?

I suggest setting `FMT_INSTALL` in the master project (pytorch) if you want {fmt} be included in its install target.

**Comment by gemfield** [comment]
@vitaut Thanks.
