### ISSUE TITLE
Enhancement / Feature Request: Parameterization of fill characters

### ISSUE THREAD

**Issue by Falkgaard** [fmtlib/fmt#2189]
Hello, love the library!

As is shown in [the documentation here](https://fmt.dev/latest/syntax.html), there's a pattern that goes along the lines of passing an empty string parameter, then using another parameter as the width in order to indent or repeat a fill character N times. However, it currently appears to be impossible to set the fill character in the same way, see the code below:

https://godbolt.org/z/3ffzMozjj

```
#include "fmt/core.h"

int main() {
   [[maybe_unused]] char indentSymbol = '_';
   int indentWidth = 4;
   fmt::print("{:.>{}}Test\n", "", indentWidth); // OK
// fmt::print("{:{}>{}}Test\n", "", indentSymbol, indentWidth); // ERR: "width is not integer" (huh?)
}
```

Is this an oversight or something that will be added? I've tried explicitly providing positional indices to the braces as well.

Best regards,
-Falkgaard

**Comment by vitaut** [comment]
Thanks for the suggestion and kind words. Unfortunately adding dynamic fill characters to the built-in formatters would introduce nontrivial overhead so I am not sure if it's worth doing. However, you can easily write a custom formatter that does this:

```c++
#include <fmt/core.h>

struct fill {
  char value;
  int width;
};

template <>
struct fmt::formatter<fill> {
  auto parse(format_parse_context& ctx) { return ctx.begin(); }

  auto format(fill f, format_context& ctx) {
    return std::fill_n(ctx.out(), f.width, f.value);
  }
};

int main() {
  fmt::print("{}\n", fill{'-', 10});
}
```
Output:
```
----------
```

**Comment by Falkgaard** [comment]
Cheers, that's fair.

I ended up just having storying the fmt string as a private C-string data member and made the set/change indent symbol functions directly alter the character at the index containing the fill character as a quick and dirty fix, but I'll try using your suggestion of a custom formatter the next time I touch that code since that sounds like a way more maintainable approach. Many thanks!

**Comment by Viatorus** [comment]
Hello @vitaut, can you please explain in short why a fill character would lead to nontrivial overhead but precision and width doesn't? I am technical interested.

**Comment by vitaut** [comment]
Precision and width also have this overhead and we'd like not to introduce more. In any case the format is pretty much fixed at this point.

**Comment by Viatorus** [comment]
Alright. Thank you. :)
