### ISSUE TITLE
Output buffer overrun in fmt::format_to_n

### ISSUE THREAD

**Issue by 0x8000-0000** [fmtlib/fmt#2191]
https://godbolt.org/z/zfKbxYhzj

The following program:

    #include <fmt/format.h>

    #include <string_view>
    #include <vector>

    int main()
    {
        std::vector<char> buffer(1024);

        const size_t firstChar = 32;
        const size_t lastChar = 120;

        for (size_t ii = 0; ii < 1024; ++ ii)
        {
            buffer[ii] = static_cast<char>((ii % (lastChar - firstChar)) + firstChar);
        }

        std::vector<char> output(2048);

        const auto result = fmt::format_to_n(output.data(), 512, "Answer: {}", std::string_view{buffer.data(), buffer.size()});

        fmt::print("Wrote {} characters\n", result.size);

        return 0;
    }

Prints:

    Wrote 1032 characters.

Expected:

    Wrote 520 characters.

**Comment by 0x8000-0000** [comment]
I tried adding a test in the main branch, but it does not fail, building with GCC10.2 and -DCMAKE_CXX_STANDARD=20:

    #ifdef FMT_USE_STRING_VIEW
    TEST(FormatTest, FormatToNTrim) {
      std::vector<char> inputBuffer(1024, ' ');
      std::vector<char> targetBuffer(2048);
      const auto result = fmt::format_to_n(targetBuffer.data(), 1024u, "Data: {}", std::string_view(inputBuffer.data(), inputBuffer.size()));
      EXPECT_EQ(1030u, result.size);
    }
    #endif

**Comment by alexezeder** [comment]
From [documentation](https://fmt.dev/latest/api.html#_CPPv2N3fmt18format_to_n_result4sizeE):

> `size_t size`
>     Total (not truncated) output size.

So, the correct way to determine the number of characters written:
```cpp
fmt::print("Wrote {} characters\n", result.out - output.data());
```

**Comment by vitaut** [comment]
As you've already found out `size` returns total and not truncated output size: https://fmt.dev/latest/api.html#_CPPv2N3fmt18format_to_n_result4sizeE.

**Comment by 0x8000-0000** [comment]
Thank you @alexezeder and @vitaut for the quick response!
