### ISSUE TITLE
GCC pragma and performance question

### ISSUE THREAD

**Issue by phprus** [fmtlib/fmt#2193]
Commit: https://github.com/fmtlib/fmt/commit/243d8bebd1cf1208a9d7b17269ccc148914572a3

https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Function-Specific-Option-Pragmas.html:
> This pragma allows you to set global optimization options for functions defined later in the source file. One or more strings can be specified. Each function that is defined after this point is treated as if it had been declared with one optimize(string) attribute for each string argument.

https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Common-Function-Attributes.html:
> The optimize attribute is used to specify that a function is to be compiled with different optimization options than specified on the command line.

So the attribute or pragma does override the command line?
For example, when using -O3 on the command line, the fmt code will be compiled using only the Og optimization level.

Or did I misunderstand the GCC documentation?

**Comment by vitaut** [comment]
It will be applied only when optimizations are disabled (in separate commit).

**Comment by vitaut** [comment]
https://github.com/fmtlib/fmt/commit/35c71ff536321475f688fe50424e3eb070868a94

**Comment by karna48** [comment]
https://github.com/fmtlib/fmt/issues/4295
