### ISSUE TITLE
Grouping character in format double value locale specific

### ISSUE THREAD

**Issue by vomikan** [fmtlib/fmt#2199]
Just a question.
How to format double value, for example, 123456.899 to 1,23,456.89 (en_IN locale)?

This code sample working fine only with integer value. 
![image](https://user-images.githubusercontent.com/6836805/112859902-f8a85e80-90bb-11eb-96b9-2c732827678c.png)

For double value group separator and decimal part disappears
![image](https://user-images.githubusercontent.com/6836805/112859854-e8907f00-90bb-11eb-9942-3a95f3967f6d.png)

I am using 7.1.3 
Build using:
• MSBuild 15.9.21.664
• Microsoft Visual Studio 15.0
• Microsoft Visual C++ 19.16.27045.0
• Windows SDK 10.0.17763.0
Running on:
• Windows 10 (build 19042), 64-bit edition
• Russian (windows-1251)

**Comment by vitaut** [comment]
This is not implemented yet: #1392.
