### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by YarikTH** [fmtlib/fmt#2200]
Last release 7.1.3 was released Nov 25, 2020.
Now 4 months have passed and there are 229 new commits in master.
https://www.timeanddate.com/date/durationresult.html?d1=25&m1=11&y1=2020&d2=&m2=&y2=
When the new release either 7.2.0 or 7.1.4 is planned?
Especially I'm interested in #2143, but I'm sure there are a lot of other good things that were added.

**Comment by vitaut** [comment]
I don't have a specific date but probably early summer (major release). Patch release can happen earlier if a critical issue is found.

**Comment by vitaut** [comment]
BTW `master` is quite stable so you don't have to wait for a new release, just pin to the specific commit you are interested in.

**Comment by Finkman** [comment]
I'd be happy, as well.
I need fixes like #2053. Otherwise I cannot use the lib by now
