### ISSUE TITLE
Feature request: truncate output files

### ISSUE THREAD

**Issue by BenjiHansell** [fmtlib/fmt#2203]
It seems that when I write to an output file which already exists, it is not truncated:

```c++
#include <fmt/os.h>

int main() {
  fmt::output_file("/path/to/file").print("AAAAA");
  // file contents is "AAAAA"
  fmt::output_file("/path/to/file").print("BBB");
  // file contents is "BBBAA", but it would be nice if it was "BBB"
}
```

`output_file` accepts some config flags, so I can hack around with undocumented FMT macros and get it to work how I want like this:

```c++
#include <fmt/os.h>

int main() {
  fmt::output_file("/path/to/file").print("AAAAA");
  // file contents is "AAAAA"
  fmt::output_file("/path/to/file").print("BBB", fmt::file::WRONLY | fmt::file::CREATE | FMT_POSIX(O_TRUNC));
  // file contents is "BBB"
}
```

Would it be possible to add an `fmt::file::TRUNC` option?  

It might also be worth making that the default.  I see no reason why someone would want `fmt::file::WRONLY | fmt::file::CREATE` (the current default) but be unhappy with `fmt::file::WRONLY | fmt::file::CREATE | fmt::file::TRUNC`.  Although that would be a breaking change.

**Comment by vitaut** [comment]
Same as #2018. There is `fmt::file::TRUNC` already and it is the default.
