### ISSUE TITLE
Arbitrary sys_time<Duration> types are not formattable out of the box

### ISSUE THREAD

**Issue by ecorm** [fmtlib/fmt#2208]
When attempting to format a `std::chrono::sys_time<Duration>`, where `Duration` is not the same as `std::chrono::system_clock::duration`, compilation fails with the static assertion:

> static_assert failed due to requirement '!std::is_same<const fmt::v7::detail::unformattable &, const fmt::v7::detail::unformattable &>::value' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization

Godbolt demo: https://godbolt.org/z/7Moc5cKrr

According to https://en.cppreference.com/w/cpp/chrono/system_clock/formatter, C++20's `format` accepts any duration type for `sys_time`.

[hinnant/date](https://github.com/HowardHinnant/date)'s `format` accepts any arbitrary `sys_time`:

```c++
using time_type =
    std::chrono::time_point<std::chrono::system_clock, std::chrono::seconds>;
time_type t{std::chrono::seconds{42}};
auto s = date::format(std::locale::classic(), "%S", t);
std::cout << s << "\n"; // prints 42
```

This is related to issue #2207 where one would want to `std::chrono::floor` a `sys_time` to the desired precision for formatting.

**Comment by vitaut** [comment]
Added support for time points with arbitrary durations in https://github.com/fmtlib/fmt/commit/06b3a1000ce062ad92e74f8a659b47f365d0688a. Thanks for reporting.
