### ISSUE TITLE
Is this is a bug with fmt 6.2.1?

### ISSUE THREAD

**Issue by ngrodzitski** [fmtlib/fmt#2214]
The following [snippet](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAFlJvoCqAZ0wAFAB4gA5AAYppAFZdSrZrVDIApACYAQjt2kR7ZATx1KmWugDCqVgFcAtrS4BmUlfQAZPLUwAcs4ARpjEINy8AA6oQoTmtHaOLu6kMXFmdL7%2BQU6h4ZFGmCaZtAwEzMQESc6unB7GmKYJ5ZUE2YEhYRGcRhVVNSn1fW0dufk9AJRGqA7EyBxSAPRLANQAKgCeUZirm7PEq2hYqwhhmKSrJKusqMzoq2qrmOLMTlHsAHSaMgCCOm4/MhHCdNG4bEICMQ/MAwdgfv9tIDaMCHKDwYQwswiMQ4QiAUCQbswTYqE4CEsaMQnNjPgg8X8EZDiA5TKsnJsAPrM1kEVaaADs%2Bj%2Bq1Wfj54kF%2BgFABEwcLfqLxXspYK5W4FWr5fi/jy2RzuVDedp%2BUKEaKDXq%2BUJVbLtSLVisxfRVkJ%2BRrHWt1gg8G6AO4kADWQjAYHNzr5AC9berNXaNTrfrQ3pghFFmAtVmS%2BarGX8CJh3qoC%2B6bAzflasyQaQQC7jwZajaY4aaFaKC0XscTwcDmEI3aJKiI7PQXgRy6K0LRIS8oodmA4iKt08QRBBB6vMCOC%2BJx9oAGxHAjiSat8Oi4iYAhzWiugjoEAgLwQUwn%2B2K01yvMfjsfLul3t%2B1WAAxatsW3McJ0eRdUCralsRfOhIXZLkrR0Q9mEuUD4OqOgdz3Q9X1PXMPwvK8bzgmtOSIF9j0%2BWYCAgaZ%2BW0bQY21M07VYy5mE%2BcQeM%2BTZJnfUUtUZeMFV/YtuzLNx4V1Js%2BSpGs6xJRsWVMNi5LPB0pP/ElAIHIctzwyC5PDKcZ3EOdoKXFc1w3YdTN3dCjxPHTSNWS9r2IW9IQfJ9rFot8EwdMT/l0ws/xLAzVCA7CawglzzIdBcl2UhDLL5dTjVczCQLA3DRxcg83OIs0HVFJ1vV9VYA2IYMQHPT1bNghj3RlNz6MXJiRNFFr2rBTqMoIajUAgBjLh0NjOLlbjHk%2BIRhNCzynUGtxhsKsaJsXKbWKWdj5t4yNlrbfqnW8iiGPfZrLt8yjsW219usY5jppjA7ZumgShAEk6%2BvCrUVvxWUWuTJxU3TTNs0TBFlRpPwmP5cSzv8x9mRhV12JWi1UMUk0nBtL6cda1ZxA6rNyUfEbtrRkBggzQNOT8EQqjCCAlr2mbpTm7RLkJ07wydN0hspghqcKiB3q%2B%2BaBflFrflYIRYKoZg8CV0Nw2zR853FKXWJFjbVjAKQYxN1YObwSMODPWVhIAVhsWhvtdS4hEWq3MCYwXxJlKRplYaR7fkVxZHkVBpDLPQDFdA5MwBTh5HFsPJmmQMQDcAVPgFe37YFbhWM4PO3EiAAOfcVGkbgQ%2BkORSAjqR5CEEAZFIZO5GmOBYCQNB3nVsJyEoXuon78JgFLjwqHVutm4gYJa/kYI/EqTZpET0he4h%2BgAHlaFYVew9ILAaXUdgF6PvBL2aAA3VNz5eJpF0WOvxWKc/WDwYJiBXuwsHPqE8BODXv7PgeEmBsA4DwUBggRASHPkoXoqh1AoAMAYFQn9m6wHBhwbMpBb7hCkPubQidU71yiKUZuUgAC0/khpaGjnoTgApVhUO3uvRozQLAQC8IMOonhrBjC6OEXo6R4h0F4coURpRBF5G6L0DhpRWgDHsLUZQCiWj9HaH4TosjhEjGUckPhkJRjaPGHI6Yys5gLC4AHIONdD4N3EOXKh%2B5uCrGAMgZAqxS6fDcBbXAhBrgJ0uHYPu7BDgJ1PFHfQegk4L1IenbQABOXxApklJKSQKGQ9Q3D23LqXSuUhq6kCAZwGQrdQ51wbk3Fubd4mkC7ogEADEoi7QoIhMJcjPD4BxMofgjAWBnygf04QYhJCHz9N/KIwDbFSGDqQSp4dpAJzqoQBAZNnGuPcZ47xvi4kpzThnbQnxS4Ck4NoPJMhS7JOSfuVxhTimlPKQs8%2B1SjC1Pbv7WZ2h7FVOkPsju0x8FxAsNwIAA) fails with fmt 6.2.1(and 6.2.0) and GCC 8.3/9.3/10.2.
```C++
// Type your code here, or load an example.
#include <string>
#include <iterator>
#include <fmt/format.h>

struct my_struct {
  int x{};
  int y{};
};

struct my_struct2 {
  my_struct s{};
  // int s ; // This works!
  int z{};
};

namespace fmt {

template <>
struct formatter<my_struct> {
  template <class ParseContext>
  constexpr auto parse(ParseContext& ctx) {
    return std::end(ctx);
  }

  template <class FormatContext>
  auto format(const my_struct& a, FormatContext& ctx) {
    return format_to(ctx.out(), "{};{}", a.x, a.y);
  }
};
template <>
struct formatter<my_struct2> {
  template <class ParseContext>
  constexpr auto parse(ParseContext& ctx) {
    return std::end(ctx);
  }

  template <class FormatContext>
  auto format(const my_struct2& a, FormatContext& ctx) {
    // This works:
    // auto out = ctx.out();
    // out = format_to(out, "{}", a.s);
    // out = format_to(out, "/{}", a.z);
    // return out;

    return format_to(ctx.out(), "{}/{}", a.s, a.z);
  }
};

} // namespace fmt


int main() 
{
  std::string s{};
  my_struct2 ms{};
  auto x = fmt::format_to(std::back_inserter(s), "{}", ms);
  // s = fmt::format("{}", ms); // Also fails!
  fmt::print("s = '{}' (size: {})\n", s, s.size());
}
```

It works as expected on with fmt 7.*
So I wonder if I'm doing something wrong or it has something to do with fmt 6.2.*.

Currently I go with workaround, which is pretty odd:
```C++
auto out = ctx.out();
out = format_to(out, "{}", a.s);
out = format_to(out, "/{}", a.z);
return out;
```

**Comment by vitaut** [comment]
Looks like a bug in 6.2.1 to me. I don't see anything obviously wrong in your code.
