### ISSUE TITLE
API to get list of named arguments from format string

### ISSUE THREAD

**Issue by KindDragon** [fmtlib/fmt#2219]
Hi. I want to implement a custom `fmtlib` style `print` function that will support only named arguments that will dynamically request from some storage (like JSON or YAML).

How I think it should work:
1. User sends me format string, something like `"Hello, {name}! The answer is {number}. Goodbye, {name}."`
2. I request a list of all named arguments in this string
3. Create `fmt::dynamic_format_arg_store<fmt::format_context>` and fill it with required values from storage (this storage can be very big).
4. Call `fmt::vformat()` with it and display the result

I can't do only point number 2 (based on what I found on https://fmt.dev/latest/api.html)

**Comment by vitaut** [comment]
{fmt} doesn't provide a public API to obtain argument names so you can either use the internal API https://github.com/fmtlib/fmt/blob/5a8bf1f6a3b5f2248bbe657aae1cdfb850802504/include/fmt/format.h#L3046-L3047

which is subject to change or do the parsing yourself.
