### ISSUE TITLE
fmt-header-only through cmake

### ISSUE THREAD

**Issue by kfsone** [fmtlib/fmt#2221]
After spending a couple of hours trying different variations of raw-cmake, then the cmake content functionality and finally cpm, I'm unable to use a non-vendored `fmt` import in fmt-header-only mode via cmake.

Made a minimal repro case:

https://github.com/kfsone/examples/tree/master/General/cmake-fmt

I've tried variations of linking the library private/public/interface/non-linked, setting the FMT_HEADER_ONLY flag from the command line, before/after cmake's `project()` statement, in the src CMakeLists.txt. At best, this just produces a "duplicate instantiation" error that suggests it's seeing both the header-only instantiation and trying to link against a compiled binary with it...

**Comment by vitaut** [comment]
Have you tried using fmt-header-only target as described in the docs: https://fmt.dev/latest/usage.html#usage-with-cmake?

**Comment by kfsone** [comment]
> Have you tried using fmt-header-only target as described in the docs: https://fmt.dev/latest/usage.html#usage-with-cmake?

Yes, I did read the documentation prior to spending several hours trying to get it to work, which is why it's exactly what is in the minimal repro case I provided.

![image](https://user-images.githubusercontent.com/323009/114222280-3b233400-9923-11eb-9bd6-603a02739937.png)

**Comment by alexezeder** [comment]
Ok, I found the problem in {fmt} that causes `undefined reference to` compilation errors, probably a new one.

It seems that {fmt} is not ready to be used in header-only mode with including only `fmt/core.h` header. For example, `fmt/format.h` has these lines: https://github.com/fmtlib/fmt/blob/273d8865e31659f69528623754c1742b2819ad26/include/fmt/format.h#L4030-L4035

but the `fmt/core.h` header doesn't include this `format-inl.h` header, in any case, it just doesn't have this code. Thus the final binary doesn't have function definitions.

As for the "duplicate instantiation" error, I don't really get its origin yet.

**Comment by kfsone** [comment]
> As for the "duplicate instantiation" error, I don't really get its origin yet, because I don't get this error yet.

I didn't dig into that, since the documentation introduced the -D in a "set this or if you are using cmake use fmt::fmt-header-only" setup, plus I was trying msvc at that point.

It repros pretty consistently for me across compilers and platforms, tho: https://gist.github.com/kfsone/c55c75850bb646f62f152f98645b6272

**Comment by kfsone** [comment]
> It seems that {fmt} is not ready to be used in header-only mode with including only `fmt/core.h` header. For example, `fmt/format.h` has these lines:

What would be the correct thing to include, then?

**Comment by vitaut** [comment]
Per https://fmt.dev/latest/api.html#core-api:

> In the header-only mode include fmt/format.h instead of fmt/core.h.

We should probably add a check that `fmt/core.h` is not included on its own in the header-only mode.

**Comment by vitaut** [comment]
Or maybe include format.h from core.h because the check may break if someone includes core.h and then format.h which makes no sense but can potentially happen via transitive includes.

**Comment by alexezeder** [comment]
> It repros pretty consistently for me across compilers and platforms, tho: https://gist.github.com/kfsone/c55c75850bb646f62f152f98645b6272

Did you have this error with that example - https://github.com/kfsone/examples/tree/master/General/cmake-fmt, without any changes applied?

**Comment by vitaut** [comment]
As of https://github.com/fmtlib/fmt/commit/99c2f7a349716411735411153d000767b6116f7b it's OK to include `fmt/core.h` in the header-only mode.
