### ISSUE TITLE
Compile-time trait to check if a type is formattable.

### ISSUE THREAD

**Issue by TobyBrull** [fmtlib/fmt#2225]
Couldn't find anything regarding this in the docs. What I want to do is basically the following.

```cpp
template<typename T>
void foo(T const& value) {
    if constexpr(fmt::is_formattable_v<T>) {
        fmt::print("foo called with value = {}", value);
    }
    else {
        fmt::print("foo called with value = ???");
    }
    further_process(value);
}
```

Alternatively (or additionally?) it might also we useful to have a a conditional formatting wrapper that would be usable as shown in the following.

```cpp
template<typename T>
void bar(T const& value) {
    fmt::print("foo called with value = {}", fmt::or_default(value, "???"));
    further_process(value);
}
```

Haven't thought about this in depth; maybe there is some technical reason why any of those suggestions is not possible?

**Comment by alexezeder** [comment]
The first code example actually works (with few changes): https://godbolt.org/z/nzWM7846h
