### ISSUE TITLE
Why does fmt round 0.5 rounded to 0, for zero decimals?

### ISSUE THREAD

**Issue by florisjonkman** [fmtlib/fmt#2227]
I fully implemented the fmt library in my project. But the last bug I found was that values previously where rounded to the higher bound (0.5 -> 1), while they currently are rounded to their lower bound (0.5 -> 0).

When trying to find the cause, I found:

```
double halfd = 0.5;
std::string str = fmt::format("{:.0f}", halfd ); // result: "0"

float halff = 0.5f
std::string str = fmt::format("{:.0f}", halff ); // result: "0"
```
I also tried, if the compiler maybe stores 0.5 as 0.49999999999..., but I could not find the cause.

I work with Microsoft Visual Studio 2017 with v140 compiler.

Does anybody know why fmt rounds 0.5 to 0, instead of 1. I previously used the standard printf library.

**Comment by alexezeder** [comment]
JFI, `std::printf` also rounds 0.5 to 0 with corresponding format string - https://godbolt.org/z/xK51rsv3s

**Comment by vitaut** [comment]
Round to nearest even (https://en.wikipedia.org/wiki/Rounding#Round_half_to_even) is the default rounding mode used in IEEE 754.

**Comment by florisjonkman** [comment]
I wasn't aware of rounding to nearest even integer was the default. Is it possible to bypass this method in FMT, and round X.5 to X+1, and X.49 to X ? For all integer values of X, even and uneven?

**Comment by vitaut** [comment]
Not with the default formatter but you could use the extension API for floating-point formatting with different rounding: https://fmt.dev/latest/api.html#formatting-user-defined-types. Why do you want to bypass it?
