### ISSUE TITLE
warning C4910: '__declspec(dllexport)' and 'extern' are incompatible on an explicit instantiation

### ISSUE THREAD

**Issue by moiwi** [fmtlib/fmt#2228]
Compiling format.h with FMT_EXPORT defined gives the warning

`format.h(998,71): warning C4910: 'fmt::v7::detail::basic_data<void>': '__declspec(dllexport)' and 'extern' are incompatible on an explicit instantiation (compiling source file os.cc)`

with Visual Studio 2019.
Why was

```
#ifndef FMT_EXPORTED

#endif
```

removed?

**Comment by vitaut** [comment]
It was removed in #2220 because of clang warnings. It seems that MSVC and clang handle dllexport in incompatible ways.

**Comment by vitaut** [comment]
We might need both `FMT_INSTANTIATION_DECL_API` and `FMT_INSTANTIATION_DEF_API` defined based on the compiler (sigh).

**Comment by denchat** [comment]
I'm trying to fix this at https://github.com/fmtlib/fmt/pull/2229 .
However I'm not sure that...

#ifndef FMT_EXPORTED
  extern template struct <name>
#endif

is also required by msvc.

I don't have msvc, please report back.

**Comment by moiwi** [comment]
It seems

```
#ifndef FMT_EXPORTED

#endif
```

is needed for MSVC. Without I still get ehe same warning

`'__declspec(dllexport)' and 'extern' are incompatible on an explicit instantiation`

**Comment by denchat** [comment]
Okey, I wrapped it up.

However, I've been thinking that msvc should never has seen `extern template` together with `dllexport` in the 1st place.
The preprocessor is supposed to behave like the previous one on msvc!?
That's odd or maybe I might have missed out something.

Please check again.

**Comment by moiwi** [comment]
#2229 fixes my problem.
Without "#ifndef FMT_EXPORTED" the preprocessor output is
```
template <typename T = void> struct __declspec(dllexport) basic_data {
  static const uint64_t powers_of_10_64[];
  //...
  static const uint64_t zero_or_powers_of_10_64[];
};
//...
extern template struct  basic_data<void>;
```
which results in the mentioned compiler warning.

**Comment by vitaut** [comment]
Thinking more of it, `basic_data` doesn't seem to need `dllexport` at all. At least I was able to build fmt dll with it removed (https://github.com/fmtlib/fmt/commit/8bc45503596581cde93007016e0d57acba67a908) and the tests work.

**Comment by vitaut** [comment]
@moiwi, @denchat, does https://github.com/fmtlib/fmt/commit/8bc45503596581cde93007016e0d57acba67a908 work for you?

**Comment by moiwi** [comment]
No, it doesn't work for me (with MSVC 2019).
I still get the line
`template <typename T = void> struct FMT_EXTERN_TEMPLATE_API basic_data {`
(which gets preprocessed to
`template <typename T = void> struct __declspec(dllexport) basic_data {`
) colliding with
`FMT_EXTERN template struct basic_data<void>;`
(which gets preprocessed to
`extern template struct basic_data<void>;`
)

It does however work if I remove "FMT_EXTERN_TEMPLATE_API" like that:
`template <typename T = void> struct /*FMT_EXTERN_TEMPLATE_API*/ basic_data {`

**Comment by vitaut** [comment]
OK, let's go with #2229 then. Thanks for testing.

**Comment by denchat** [comment]
https://github.com/fmtlib/fmt/pull/2241

The extern template's game is quite a mess between camps!?
Clang:  I don't like forward declaration of entity.
MSVC:  I don't like extern template on members.

Sigh.
