### ISSUE TITLE
Print the format string at the "invalid format string" error 

### ISSUE THREAD

**Issue by randomizedthinking** [fmtlib/fmt#2231]
This is a request that fmtlib would print out the format string when an "invalid format string" error is encountered. It would help users to pinpoint the foul line greatly.

I got the issue a couple of times -- each time, it would take a great deal of the time to locate the line caused the problem. It would be much easier if I know which format string caused the issue.

**Comment by vitaut** [comment]
Thanks for the suggestion but I don't think that copying potentially large user data in error path is a good idea. However, you can get the error location using a stack trace or catch such errors at compile time (https://fmt.dev/latest/api.html#compile-time-format-string-checks). Compile-time checks will eventually be done by default (#2022).

**Comment by randomizedthinking** [comment]
Understand, it is a problem to print out potential large user data. On the other hand, do you think it is possible to print out filename and line# information when a LOGERROR occurs?

**Comment by vitaut** [comment]
> On the other hand, do you think it is possible to print out filename and line# information when a LOGERROR occurs?

I think you can already do it by defining `FMT_ERROR` accordingly.

**Comment by alexezeder** [comment]
> I think you can already do it by defining `FMT_ERROR` accordingly.

Actually, it's `FMT_THROW` 😉

**Comment by vitaut** [comment]
Yeah, that's what I meant =)

**Comment by randomizedthinking** [comment]
Thanks, @alexezeder and @vitaut for pointing out `FMT_THROW`. It is exactly what I wanted.
