### ISSUE TITLE
MSVC warning C4365 with /Wall and FMT_STRING()

### ISSUE THREAD

**Issue by vid512** [fmtlib/fmt#2233]
Any FMT_STRING() usage causes a warning C4365 (un/signed mismatch), when compiling with MSVC (14.28.29910, from Visual Studio 2019) with /Wall:

```
#include <fmt/format.h>
void test() {
	fmt::format(FMT_STRING("a"));
}
```

Note: despite being displayed as warning C4365, this particular warning cannot be enabled with just #pragma warning(default:4365). You must use /Wall to trigger it. It also can't be disabled by /Wall /wd4365.

**Comment by vid512** [comment]
[CMake build log.txt](https://github.com/fmtlib/fmt/files/6305312/CMake.build.log.txt)

**Comment by vitaut** [comment]
Which {fmt} version?

**Comment by vid512** [comment]
version 7.1.3

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/6271406233585a9178592b0492b190786bf0ee98.
