### ISSUE TITLE
Problem printing Unicode characters

### ISSUE THREAD

**Issue by pauljurczak** [fmtlib/fmt#2234]
I'm using {fmt} v7.1.3 on Ubuntu 18.04.5 with gcc-10.1 and clang-10.0 compilers set to C++20. This snippet:
```
fmt::print(L"Cyrillic letter {}\n", L'\x42e');
```
produces:
```
terminate called after throwing an instance of 'fmt::v7::system_error'
  what():  cannot write to file: Success
Aborted (core dumped)
```
exception. I took this example from https://fmt.dev/latest/index.html?highlight=unicode. What am I doing wrong?

**Comment by vitaut** [comment]
The error means that `fputws` failed. I would recommend using UTF-8 `char` strings instead of `wchar_t` on Linux.

**Comment by pauljurczak** [comment]
Does it mean that en example I took from https://fmt.dev/latest/index.html?highlight=unicode is invalid? Should it be updated?

**Comment by vitaut** [comment]
If you are referring to this example

```c++
fmt::format(L"Cyrillic letter {}", L'\x42e');
```

then it should be OK. The error occurs when writing to `stdout`, not during formatting.
