### ISSUE TITLE
Custom string types not honoring width parameter in printf/sprintf.

### ISSUE THREAD

**Issue by videoredo** [fmtlib/fmt#2245]
I'm using fmt::sprintf() to emulate a legacy logging system and have added a custom output type using the following code:
```
template <typename Char> std::basic_ostream<Char> &operator<<( std::basic_ostream<Char> &os,
	const  QString &value )
{
	os << (const char *)value.toUtf8();
	return os;
}
```
Works well, but doesn't support width or alignment.  Is there a way to add string types earlier into the formatting process so that the 'specs' structure can be used to completely format this variable?

**Comment by vitaut** [comment]
Not with `sprintf` but you can use `fmt::format` and provide a `formatter` specialization, something like:

```c++
struct fmt::formatter<QString> : formatter<const char*> {
  auto format(const QString& s, format_context& ctx) {
    return formatter<const char*>::format((const char *)value.toUtf8(), ctx);
  }
};
```

**Comment by videoredo** [comment]
Thanks, we already have done that, but our product has hundreds of logging statements which currently use sprintf.  We plan on migrating to fmt::format over time, but it's too much effort to do all at once.  Would be glad to try and do a PR on this if you could point us in the right direction.

**Comment by vitaut** [comment]
`fmt::sprintf` intentionally provides a limited API similar to the one of standard `sprintf` to discourage its use.

**Comment by videoredo** [comment]
I understand, but since width and alignment works for standard “%s” formats in fmt::sprintf, it would be good to allow it’s support for custom string types.  One of the niceties of fmtlib is that it does support fmt::sprintf as a transitional step to fmt::format.  We would be glad to attempt this ourselves.

**Comment by vitaut** [comment]
You can implement your own function that wraps `fmt::sprintf` and translates exotic string types into supported ones, it doesn't have to live in {fmt}. Or look into automated migration using e.g. https://github.com/mikecrowe/clang-tidy-fmt and skip `fmt::sprintf` altogether.

**Comment by videoredo** [comment]
Thank you.
