### ISSUE TITLE
iOS build broken due to sys::system usage

### ISSUE THREAD

**Issue by saurik** [fmtlib/fmt#2248]
In 15c10b0c666d274b378cf63429babfa202623db4, a new function was added--say--which runs std::system... a function which is "unavailable" on iOS, breaking the build of this library on that platform.

```
In file included from vpn/shared/p2p/fmt/src/os.cc:13:
./vpn/shared/p2p/fmt/include/fmt/os.h:205:8: error: 'system' is unavailable: not available on iOS
  std::system(format("say \"{}\"", format(format_str, args...)).c_str());
       ^
/Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/usr/include/stdlib.h:190:6: note: 'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
1 error generated.
make: *** [out-ios/arm64/./vpn/shared/p2p/fmt/src/os.cc.o] Error 1
```

I believe the correct check to remove this would be `#ifndef TARGET_OS_IPHONE`.

**Comment by vitaut** [comment]
Thanks for reporting. Does https://github.com/fmtlib/fmt/commit/553022dc56c8ec9d6996e0c1b8918d3b4818b183 fix the problem?

**Comment by saurik** [comment]
Ugh... so, I've managed to make two mistakes in my attempt to guide you with "the correct check" :(.

1) TARGET_OS_IPHONE is actually set to either 1 *or 0* and so you can't use `#ifndef` and must use `#if !`.
2) TARGET_OS_IPHONE is not defined in this context unless you also `#include <TargetConditionals.h>`.

I've tested that this patch works:

```diff
diff --git a/include/fmt/os.h b/include/fmt/os.h
index 70c465b5..5955339e 100644
--- a/include/fmt/os.h
+++ b/include/fmt/os.h
@@ -14,6 +14,10 @@
 #include <cstdio>
 #include <cstdlib>  // for strtod_l

+#if defined __APPLE__
+#  include <TargetConditionals.h>
+#endif
+
 #if defined __APPLE__ || defined(__FreeBSD__)
 #  include <xlocale.h>  // for LC_NUMERIC_MASK on OS X
 #endif
@@ -201,7 +205,7 @@ FMT_API void report_windows_error(int error_code,
 #endif  // _WIN32

 // std::system is not available on iOS (#2248).
-#ifndef TARGET_OS_IPHONE
+#if !TARGET_OS_IPHONE
 template <typename S, typename... Args, typename Char = char_t<S>>
 void say(const S& format_str, Args&&... args) {
   std::system(format("say \"{}\"", format(format_str, args...)).c_str());
```

Another option is to use __IPHONE_OS_VERSION_MIN_REQUIRED, which is defined by the compiler itself, but the problem is that tvOS and watchOS are going to have the same issue and while those platforms usually also have the __IPHONE_OS_VERSION_MIN_REQUIRED set, I believe that is just some backwards-compatibility in AvailabilityInternal.h and I have no clue if Apple intends to maintain that...

**Comment by vitaut** [comment]
Thinking more of it, it's better to opt in instead of opt out platforms, so here's another tentative fix: https://github.com/fmtlib/fmt/commit/ce67532e8709e31aeb580e4b5a0371c6fddd8324.

**Comment by saurik** [comment]
Ah, of course: since that say command only exists on macOS in the first place. (Why, BTW, is fmt providing an OSX-specific text-to-speech function?... it isn't even "safe": if the string contains a quotation mark it can terminate the command and obtain arbitrary shell execution :(.) FWIW, this patch at least made fmt compile on iOS, if it is working for your use cases!

**Comment by bbolli** [comment]
> Why, BTW, is fmt providing an OSX-specific text-to-speech function?

@saurik, check the date of 15c10b0c...

**Comment by saurik** [comment]
"lol" :(

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/69bdc20a3c1271b58f0d052ffc6b2466c44ef649.
