### ISSUE TITLE
Use without streams and io

### ISSUE THREAD

**Issue by theShmoo** [fmtlib/fmt#2250]
Is there an option to use `fmt` without the dependency to streams and FILE *?

I need this to use fmt inside an Intel SGX Enclave. Where streams and IO operations are not available.

**Comment by vitaut** [comment]
iostreams are optional and you can use {fmt} without them (just exclude `fmt/ostream.h`, `fmt/printf.h` and `fmt/locale.h`). stdio is a required dependency but you could potentially provide some stubs that make {fmt} compile but do nothing on your platform.

**Comment by theShmoo** [comment]
thanks a lot! This library is great!
