### ISSUE TITLE
ostream.cc posix.cc printf.cc missing

### ISSUE THREAD

**Issue by AlexFundorin** [fmtlib/fmt#2254]
I have a project build on VS17 with an older version of fmt.
Now I want to recompile it with VS19.
Added fmt/core.h, fmt/format.h, fmt/format-inl.h, src/format.cc to "lib/fmt" folder, where I had the previous version.
Now I'm getting errors for ostream.cc, posix.cc and printf.cc missing from that folder. Those files exist in the old version of fmt, but not in the latest release.
I changed include from format.h to core.h, of cause. Deleted debug, release and .vs folders. Cleaned the build.

`1>format.cc
1>ostream.cc
1>c1xx : fatal error C1083: Cannot open source file: 'lib\fmt\ostream.cc': No such file or directory
1>posix.cc
1>c1xx : fatal error C1083: Cannot open source file: 'lib\fmt\posix.cc': No such file or directory
1>printf.cc
1>c1xx : fatal error C1083: Cannot open source file: 'lib\fmt\printf.cc': No such file or directory
1>imgui.cpp`

It's like my project is still using that old format.cc refence from somewhere inside the project.
I also checked Linker properties and overall configuration but can't find the issue with that.
It happens even when I comment the core.h string. There's no mention of format.cc in the source files, anymore.

**Comment by AlexFundorin** [comment]
It seems like something inside project.vcxproj and project.vcxproj.filters is still referring to that file, but, I have no idea how to fix it. Sorry, if this issue is unrelated to fmt.

**Comment by vitaut** [comment]
{fmt} doesn't have those files, you should probably remove references from your project file. Please refer to the documentation of your build system.

**Comment by AlexFundorin** [comment]
Yep. I manually cleaned the vcxproj files, deleted .vs and debug folder.

Now I'm having another issue. I googled it and saw you answering to several people that they need to include "format.h" instead of "core.h" if they are using the header-only format. I'm using format.h and my fmt folder has everything from include/fmt repository folder, although I also tried leaving only four main files in the folder.

Still can't use the lib properly. Getting LNK2019 and LNK2001 errors.

Screenshots, just in case: 
1. includes https://i.imgur.com/uGnQPMQ.png
2. folder https://i.imgur.com/u94JL4W.png
3. errors https://i.imgur.com/VIfzeVB.png

P.S. Sorry for not opening a new issue.

**Comment by AlexFundorin** [comment]
just found in your other comment that one needs to add this lines before include in order to use FMT as a header only library.
I hope this information was somewhere on the main page.

`#ifndef FMT_HEADER_ONLY
#define FMT_HEADER_ONLY
#endif`
