### ISSUE TITLE
FMT_COMPILE: replace constant values on compile time

### ISSUE THREAD

**Issue by milahu** [fmtlib/fmt#2264]
is there a {fmt} way to do this?

i want to generate the format string `"const 1234 = var {}\n"` on compile time
from the constant `const int someConst = 1234;`
and the "meta" format string `"const {} = var {}\n"`

```c++
#define FMT_HEADER_ONLY
#include "fmt/core.h"
#include "fmt/compile.h" // C++17

const int someConst = 1234;

int main() {
  for (int i = 0; i < 10; i++) {
    fmt::print(stdout, FMT_COMPILE("const {} = var {}\n"), someConst, i);
  }
}
```

actual result

```txt
g++ test.cc

grep 'const 1234 = var' test

grep ' = var' test
Binary file test matches
```

expected result

```txt
grep 'const 1234 = var' test
Binary file test matches
```

i also tried this with `-O2` but no success:

```c++
fmt::print(stdout, fmt::format("const {} = var {{}}\n", someConst), i);
```

this works, but then i must use `#define SOME_CONST 1234` as the single source of truth
on [godbolt](https://godbolt.org/z/T93nqGfWT), the format string is compiled to `.string "const 1234 = var {}\n"`
```c++
#define FMT_HEADER_ONLY
#include "fmt/core.h"
// https://stackoverflow.com/questions/5459868
#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define SOME_CONST 1234

int main() {
  for (int i = 0; i < 10; i++) {
    fmt::print(stdout, "const " STR(SOME_CONST) " = var {}\n", i);
  }
}
```

the [manual](https://fmt.dev/latest/api.html#c.FMT_COMPILE) says

> FMT_COMPILE(s)  
> Converts a string literal s into a format string that will be parsed at compile time and converted into efficient formatting code.

in my actual code, i want to replace constant values from an `enum class TypeId { TypeA, TypeB };`
so that
```c++
fmt::print(stdout, FMT_COMPILE("type = {} + value = {}\n"), TypeId::TypeA, someValue);
```
becomes
```c++
fmt::print(stdout, "type = 0 + value = {}\n", someValue);
```

keywords:
compile time template parameters
generate format string on compile time

**Comment by alexezeder** [comment]
> i want to generate the format string `"const 1234 = var {}\n"` on compile time

You can do this using {fmt} with C++20 enabled - https://godbolt.org/z/orqf8E51a
But as you can see, it forces the second `fmt::format()` call to use runtime API but not compile-time API, since we cannot use neither `FMT_COMPILE` macro nor `_cf` literal and [`fixed_string`](https://github.com/fmtlib/fmt/blob/9155e2de4c26792a0552ab350b41f946ad709742/include/fmt/format.h#L3890) is too specific. IMHO, `fixed_string` creation by some `fmt::format()` wrapper and passing to the next `fmt::format()` looks like a great feature, of course if it's even possible 🤔 

> this works
> on [godbolt](https://godbolt.org/z/T93nqGfWT), the format string is compiled to `.string "const 1234 = var {}\n"`

It's plain C:
```
"const " STR(SOME_CONST) " = var {}\n"
"const " "1234" " = var {}\n"
"const 1234 = var {}\n"
```
but if it works for you, then you may want to stick with that, because it's much easier for the compiler to process.

**Comment by milahu** [comment]
to summarize: the simple solution with a custom preprocessor

[types.def](https://github.com/milahu/nix/blob/parse-to-json-ast-playground/src/libexpr/nixexpr-node-types.def) - the single source of truth

```txt
ADD_TYPE(ExprLambda)
ADD_TYPE(ExprSet)
ADD_TYPE(ExprList)
```

[types.gen.sh](https://github.com/milahu/nix/blob/parse-to-json-ast-playground/src/libexpr/nixexpr-node-types.gen.sh) to generate `types.h`

<details>

```bash
#!/usr/bin/env bash

i='types.def'
o='types.h'

[ -e "$o" ] && { echo error: output file exists: $o; exit 1; }

typeNameList=()
while read line; do
  echo "$line" | grep '^ADD_TYPE' >/dev/null || { echo "skip line: $line"; continue; }
  typeName=$(echo "$line" | sed -E 's/^ADD_TYPE\(([^)]*?)\).*$/\1/')
  typeNameList+=("$typeName")
done < "$i"

res="// this file was auto-generated by $(basename $0) from $i\n"

res+="\n"
res+="#define TYPEID(type) TYPEID_##type\n"
res+="#define TYPEIDSTR(type) TYPEIDSTR_##type\n"
res+="\n"
# fixme: STR_HELPER returns "TYPEID_ExprVar" not "15"
#res+="#define STR_HELPER(x) #x\n"
#res+="#define TYPEIDSTR(type) STR_HELPER(TYPEID_##type)\n"
# STR_HELPER: https://stackoverflow.com/questions/5459868/concatenate-int-to-string-using-c-preprocessor

res+="\n"
typeId=1
for typeName in ${typeNameList[@]}; do
  res+="#define TYPEID_$typeName $typeId\n"
  typeId=$(( $typeId + 1 ))
done

res+="\n"
typeId=1
for typeName in ${typeNameList[@]}; do
  res+="#define TYPEIDSTR_$typeName \"$typeId\"\n"
  typeId=$(( $typeId + 1 ))
done

echo -e "$res" >"$o"
echo done "$o"
```

</details>

[types.h](https://github.com/milahu/nix/blob/parse-to-json-ast-playground/src/libexpr/nixexpr-node-types.h)

```c++
// this file was auto-generated by types.gen.sh from types.def

#define TYPEID(type) TYPEID_##type
#define TYPEIDSTR(type) TYPEIDSTR_##type

#define TYPEID_ExprLambda 1
#define TYPEID_ExprSet 2
#define TYPEID_ExprList 3

#define TYPEIDSTR_ExprLambda "1"
#define TYPEIDSTR_ExprSet "2"
#define TYPEIDSTR_ExprList "3"
```

[main.cc](https://github.com/milahu/nix/blob/parse-to-json-ast-playground/src/libexpr/nixexpr-as-json-arrays-fmt.cc)

```c++
fmt::print("[" TYPEIDSTR(ExprLambda) ",{},{}]", foo, bar);
```
so the preprocessor will generate the format string `"[1,{},{}]"`
