### ISSUE TITLE
FMT_COMPILE: arguments and placeholders

### ISSUE THREAD

**Issue by phprus** [fmtlib/fmt#2265]
If the number of arguments is more than the number of placeholders, then there is no error:
```
#include <fmt/format.h>
#include <fmt/compile.h>

int main() {
    char buf[1024];
    fmt::format_to(buf, FMT_COMPILE("{:d} {:d}"), 1,2,3);
}
```
https://godbolt.org/z/5x94rn4Wf

Is this expected behavior or a bug?

**Comment by alexezeder** [comment]
It's expected behavior - https://github.com/fmtlib/fmt/issues/2048#issuecomment-738955343.

**Comment by phprus** [comment]
I think this is a very unexpected behavior!
I expected that when using ```FMT_COMPILE``` there will be a check for the number of parameters. :(
