### ISSUE TITLE
Question about using custom error_code/fmt::system_error in C++11

### ISSUE THREAD

**Issue by phprus** [fmtlib/fmt#2266]
Tell me please why {fmt} uses its own implementation of ```int error_code``` and ```fmt::system_error```/```fmt::windows_error``` instead of ```std::error_code``` and ```std::system_error``` from C++11 standard?

**Comment by vitaut** [comment]
`fmt::system_error` and `fmt::windows_error` predate C++11 requirement. We could probably migrate to `std::system_error` now.

**Comment by vitaut** [comment]
Custom exception classes are gone now. Thanks for the suggestion.

**Comment by phprus** [comment]
Maybe need a replace ```fmt::error_code``` to ```std::error_code```?

https://github.com/fmtlib/fmt/blob/master/include/fmt/os.h#L122
https://github.com/fmtlib/fmt/compare/cleanup#diff-9fb4e28ec2b9c93ff34b557433378a7f22ebdef90a692bf372896f18347afa0bR72

**Comment by vitaut** [comment]
Maybe
