### ISSUE TITLE
Another project using fmt: fmtlog

### ISSUE THREAD

**Issue by MengRao** [fmtlib/fmt#2267]
Hi, I just created a C++ project which uses fmt: [fmtlog](https://github.com/MengRao/fmtlog). It's a C++ logging library using fmt syntax and faster than any other logging libraries. Could it be added on README page?  

Thanks a lot,
Meng

**Comment by vitaut** [comment]
Awesome, added to the projects list: https://github.com/fmtlib/fmt#projects-using-this-library.
