### ISSUE TITLE
Localization issue in vwindows_error

### ISSUE THREAD

**Issue by phprus** [fmtlib/fmt#2274]
Microsoft STL system error category use ```FormatMessageA``` to make error description (https://github.com/microsoft/STL/blob/a8efb53f4e571957671226271da20deb1e3832b8/stl/src/syserror_import_lib.cpp#L49).

On non-English Windows, ```std::system_category(). message()``` returns a result other than ```format_windows_error```.

Possible solution: Create custom utf8-ready ```error_category``` for using in vwindows_error (https://github.com/fmtlib/fmt/blob/master/src/os.cc#L105)

Failed tests (Russian Windows 7 SP1):
```
[----------] Global test environment tear-down
[==========] 55 tests from 6 test suites ran. (8 ms total)
[  PASSED  ] 52 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] util_test.utf16_to_utf8_error
[  FAILED  ] os_test.format_long_windows_error
[  FAILED  ] os_test.windows_error

 3 FAILED TESTS
```

**Comment by phprus** [comment]
And SEH exception:
```
F:\...\fmt\src\test\os-test.cc(131): error: Expected: (result)
!= (0), actual: 0 vs 0
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.

[  FAILED  ] os_test.format_long_windows_error (2 ms)
```

**Comment by phprus** [comment]
For test ```os_test.format_long_windows_error```: error in commit
https://github.com/fmtlib/fmt/commit/4b885c8633f2f47ceca04e341d7f771cf9b8e224#diff-9fb4e28ec2b9c93ff34b557433378a7f22ebdef90a692bf372896f18347afa0bL96-R105

**Comment by phprus** [comment]
I have implemented a prototype solution using utf8-ready error_category.
After testing, I will create a PR.

**Comment by vitaut** [comment]
A separate error category sounds like a good idea.

**Comment by phprus** [comment]
Separate error category need only for Windows.

**Comment by phprus** [comment]
Done: https://github.com/fmtlib/fmt/pull/2275
