### ISSUE TITLE
Use after move in format-inl.h

### ISSUE THREAD

**Issue by rsjaffe** [fmtlib/fmt#2278]
https://github.com/fmtlib/fmt/blob/0036a1d1953fd1ed81dc36e0513eff7258c6998d/include/fmt/format-inl.h#L545 uses bigits_ after it has been moved. There is further use of bigits_ in that function as well, some of which may be appropriate, some not.

```
void square() {
    basic_memory_buffer<bigit, bigits_capacity> n(std::move(bigits_));
    int num_bigits = static_cast<int>(bigits_.size());
```

**Comment by vitaut** [comment]
Good catch, thanks. This access happens to be benign but unnecessary - fixed in https://github.com/fmtlib/fmt/commit/02896dabee5b1df1b752d0af64f123bfea9f3ff9.
