### ISSUE TITLE
FMT_COMPILE(s) does not work with chrono example

### ISSUE THREAD

**Issue by toughengineer** [fmtlib/fmt#2280]
`chrono` example from here  
https://fmt.dev/latest/syntax.html  
works on its own
<details><summary>(click to expand the initial example)</summary>

```c++
#include <fmt/chrono.h>

auto t = tm();
t.tm_year = 2010 - 1900;
t.tm_mon = 6;
t.tm_mday = 4;
t.tm_hour = 12;
t.tm_min = 15;
t.tm_sec = 58;
fmt::print("{:%Y-%m-%d %H:%M:%S}", t);
```
</details>

but fails to compile with latest master with all latest major compilers when used with `FMT_COMPILE(s)` as explained here  
https://fmt.dev/latest/api.html#compile-api  
like this:

```c++
fmt::print(FMT_COMPILE("{:%Y-%m-%dT%H:%M:%S}"), t);
```

E.g. see  
https://godbolt.org/z/TzzG3cvGe

**Comment by vitaut** [comment]
Same as #1938.

**Comment by alexezeder** [comment]
But it works with this code: https://godbolt.org/z/3KG8P4zzz
So the code from the first message doesn't work because `fmt::print` doesn't have `FMT_COMPILE`-friendly overload.
