### ISSUE TITLE
fmt incompatible with C++/CLI?

### ISSUE THREAD

**Issue by pdxcodemonkey** [fmtlib/fmt#2285]
I have a library built using C++/CLI to talk to a C++ layer, and it blows up if I include `format.h`.   The following define is causing the issue:

```
  #if FMT_MSC_VER && !defined(FMT_BUILTIN_CLZLL) && \
    !defined(FMT_BUILTIN_CTZLL) && !defined(_MANAGED)
```
Here `_MANAGED` is true, causing the block to be skipped and the inline versions of `ctz` and `ctzll` not to be defined.  Compilation then fails in this block of format_inl.h:

```
#ifdef FMT_BUILTIN_CTZ
  int t = FMT_BUILTIN_CTZ(n);
#else
  int t = ctz(n);
#endif
```

And again here:

```
#ifdef FMT_BUILTIN_CTZLL
  int t = FMT_BUILTIN_CTZLL(n);
#else
  int t = ctzll(n);
#endif
```

because `FMT_BUILTIN_CTZ` et al are undefined, but there is also no intrinsic `ctz` or `ctzll` on the platform.

Is this by design, or just a bug?

**Comment by vitaut** [comment]
C++/CLI is not actively supported but I'm open to a PR to fix this issue, provided that the fix is non-intrusive.

**Comment by Brainy0207** [comment]
I hope it's ok to comment on a closed issue.
I just wanted to mention, that this issue is already fixed in master: https://github.com/fmtlib/fmt/issues/2176
