### ISSUE TITLE
Visual Studio picks up internal std::ostream despite including fmt/ostream.h

### ISSUE THREAD

**Issue by zcream** [fmtlib/fmt#2294]
I have #include <fmt/ostream.h> in my program.
Yet a compile with Visual Studio picks up the internal version of std::ostream for this code.

EDIT:- A similar problem is described here https://github.com/fmtlib/fmt/issues/1261 

@vitaut suggested `I think that the problem is that your operator<< is not visible in fmt/ostream.h where the formatter is specialized. You can fix this by moving the operator to a header which is included before fmt/ostream.h or use fmt/ranges.h that provides formatting support for containers and ranges.`

How do we manage this for classes ?
```
friend std::ostream& operator<<(std::ostream& out, const EmailAddress& email)
    {
        return out << email.name_ << " " << email.email_;
    }
typedef std::vector<EmailAddress> EmailAddresses;
std::ostream& operator<<(std::ostream& out, const EmailAddresses& emailAddresses);
```
And this is how the code is being used 
```
  out << addrs.front();
  for (auto it = addrs.begin() + 1; it != addrs.end(); ++it) {
    out << "," << *it;
  }
```
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\ostream(746,1): 
warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
```
The enable C++exception is not important, what I am concerned with is the use of the internal ostream.

**Comment by vitaut** [comment]
`operator<<` must be discoverable by ADL for it to work with formatting functions. If this is not possible you can define a `formatter` specialization instead as explained in https://github.com/fmtlib/fmt/issues/2130#issuecomment-797837427.
