### ISSUE TITLE
Reduce library size

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#2299]
Need to revisit library size optimizations (https://www.zverovich.net/2020/05/21/reducing-library-size.html) since there was a bit of a regression compared to 7.0:

```
% clang++ -std=c++17  -I include -O2 -DNDEBUG test.cc src/format.cc
% strip a.out
% ls -l a.out
-rwxr-xr-x  1 viz  staff  193960 May 20 11:50 a.out
```

For comparison 7.0 generates
```
-rwxr-xr-x  1 viz  staff  127472 May 20 11:53 a.out
```
with the latest clang and libc++. Looks like some of the regression is due to newer clang and standard library.

**Comment by vitaut** [comment]
7.1 is ~20k bigger probably because of adding Dragonbox.

**Comment by vitaut** [comment]
Most of the regression happened in 7.1 so should be easy to track down.

**Comment by vitaut** [comment]
The regression between 7.1.0 and 7.1.1 was to preserve ABI compatibility (https://github.com/fmtlib/fmt/commit/4081b2fe948aec01a49cc6e231bee4e02df3d61e) and is fixed now.

**Comment by vitaut** [comment]
~30k regression was caused by https://github.com/fmtlib/fmt/commit/b268f8815d28659f65f73d0119c4152265266fd4.

**Comment by sergiud** [comment]
Following #2293, I would suggest enabling `-fvisibility=hidden` and `-fvisibility-inlines-hidden` by default in `CMakeLists.txt`:
```cmake
set (CMAKE_CXX_VISIBILITY_PRESET hidden)
set (CMAKE_VISIBILITY_INLINES_HIDDEN ON)
```

```bash
$ du -h build-before/libfmt.so.7.1.4
244K
$ du -h build-after/libfmt.so.7.1.4
212K
```

I can provide a PR.

**Comment by vitaut** [comment]
> I would suggest enabling -fvisibility=hidden and -fvisibility-inlines-hidden by default

Good idea but I would suggest using target properties instead of global CMake flags.

> I can provide a PR.

Please do.

**Comment by vitaut** [comment]
With https://github.com/fmtlib/fmt/commit/b268f8815d28659f65f73d0119c4152265266fd4 regression fixed:

```
% clang++ -std=c++17  -I include -O2 -DNDEBUG test.cc src/format.cc && strip a.out && ls -l a.out
-rwxr-xr-x  1 viz  staff  161168 May 21 06:27 a.out
```

**Comment by sergiud** [comment]
CMake target properties would not provide any benefit here. On contrary, users will not be able to override the default choice by passing `CMAKE_CXX_VISIBILITY_PRESET` and `CMAKE_VISIBILITY_INLINES_HIDDEN` as cache variables.

**Comment by vitaut** [comment]
OK, just make sure that it works well with fmt used as a subproject, i.e. something like https://github.com/fmtlib/fmt/blob/18af1dc460ae8cfa437709b3473e9d6666df3702/CMakeLists.txt#L60

**Comment by vitaut** [comment]
Another ~15k regression: https://github.com/fmtlib/fmt/commit/a457e1636084f8df52682b82b744a4c1a4549a34

**Comment by alexezeder** [comment]
Brag time 😉

Some of the regressions can be found here - https://alexezeder.github.io/fmt_bnchmrk/
There are the results generated by [fmt_bnchmrk_gnrtr](https://github.com/alexezeder/fmt_bnchmrk_gnrtr) with [fmt_bnchmrk](https://github.com/alexezeder/fmt_bnchmrk) for {fmt}.
But I don't want to make any promises about the website (aka Pages) because it's running on Raspberry Pi, and if it dies, then there won't be any updates for the website. But the code will be available, I hope, forever.

**Comment by vitaut** [comment]
This is amazing, thanks for putting it together.

**Comment by vitaut** [comment]
After https://github.com/fmtlib/fmt/commit/5a2b88f6e9e6c27e55d5c72c3d1f03cf2396e3e8:

```
% clang++ -std=c++17 -I include -O2 -DNDEBUG test.cc src/format.cc && strip a.out && ls -l a.out
-rwxr-xr-x  1 viz  staff  143632 May 30 06:17 a.out
```

**Comment by vitaut** [comment]
This is slightly smaller than 7.1.0 so I think it's good enough and we could look at floating point separately.

**Comment by vitaut** [comment]
Here are results with LTO and -Os:

```
% clang++ -std=c++17 -I include -Os -flto -DNDEBUG test.cc src/format.cc && strip a.out && ls -l a.out
-rwxr-xr-x  1 viz  staff  101776 May 30 06:23 a.out
```
