### ISSUE TITLE
How to achieve something may called 'fixed point format with trailing spaces'?

### ISSUE THREAD

**Issue by Spammed** [fmtlib/fmt#2322]
I could use a format type '_fixed point format with trailing spaces_' to keep my program's favorite behavior.
The 'f' format is already very close to this:
```
std::format("{:6.2f}", 123.456) -> "123.46"
std::format("{:6.2f}", 78.9 )   -> " 78.90"
std::format("{:6.2f}", 1.0 )    -> "  1.00"
```
But there I would have to replace the trailing `'0'` by `' '` in a second pass.
to get this:
```
123.456 -> "123.46"
 78.9   -> " 78.9 "
  1.0   -> "  1.  "
```
(see e.g. here: https://godbolt.org/z/dbbG8ssre)

My imagination is going in the direction of:
`std::format("{:#6.2f}", 78.9 )   -> " 78.9 "` (note the '`#`')
or even to
`std::format("{:#6._2f}", 78.9 )   -> " 78.9_"` (note the '`_`' right after the `'.'`). 

Is such a format extension ever conceivable or a delusional idea?

**Comment by vitaut** [comment]
There is no such format in {fmt} so the easiest solution is to replace trailing zeros yourself as in your godbolt example. You can create a wrapper type and use the extension API (https://fmt.dev/latest/api.html#formatting-user-defined-types) to make it easier to use, e.g.

```c++
struct trailing_spaces {
  double d;
};

template <>
struct fmt::formatter<trailing_spaces> : formatter<double> {
  // Your formatting logic here.
};

auto s = std::format("{:6.2f}", trailing_spaces{123.456});
```
