### ISSUE TITLE
Inconsistent parameter ordering in localized `vformat_to`

### ISSUE THREAD

**Issue by DanielaE** [fmtlib/fmt#2327]
Overload for `char`:
```
template <typename OutputIt, typename Locale>
auto vformat_to(const Locale& loc, OutputIt out, string_view fmt, format_args args)
```
Overload for `Char` ≠ `char`:
```
template <typename Locale, typename S, typename OutputIt, typename... Args, typename Char = char_t<S>>
inline OutputIt vformat_to(
    OutputIt out, const Locale& loc, const S& format_str,
    basic_format_args<buffer_context<type_identity_t<Char>>> args);
```
Is this intended? All other localized API overloads take the locale as their first parameter.

**Comment by vitaut** [comment]
Good catch, thanks. This is not intended and in both cases the output iterator should go first (https://en.cppreference.com/w/cpp/utility/format/vformat_to).

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/832ec098fcdf4dcbf5476fea7ef7dce6f5c09bbd.
