### ISSUE TITLE
Documentation is sketchy, doesn't explain basic usage

### ISSUE THREAD

**Issue by yurivict** [fmtlib/fmt#2330]
The "Documentation" link in ```README``` doesn't explain basic use, for example how to format a floating point number with fixed number of digits before and after the period (```%05.03f```).

**Comment by vitaut** [comment]
The format string syntax is described in the Syntax section of the documentation: https://fmt.dev/latest/syntax.html.

> for example how to format a floating point number with fixed number of digits before and after the period (%05.03f)

The format is the same modulo delimiters (`{}` instead of `%`) i.e. `{:05.03f}` (https://godbolt.org/z/1vo1d5Ehx, note that the second zero is meaningless).
