### ISSUE TITLE
Formatting to a char16_t basic_memory_buffer with custom type and ostream<< operator throws

### ISSUE THREAD

**Issue by eligt** [fmtlib/fmt#2331]
The following sample program will segfault when built with GCC 9.3.0 (on Ubuntu 20.04).

```cpp
#include <fmt/core.h>
#include <fmt/ostream.h>

class CustomType
{
private:
	int test{42};
	
public:
	template <typename CharType>
	friend inline std::basic_ostream<CharType>& operator<<(std::basic_ostream<CharType>& os, const CustomType& var)
	{
		return os << var.test;
	}
};

int main(int argc, char *argv[])
{
	CustomType var;
	
	fmt::basic_memory_buffer<char16_t> outBuffer;
	outBuffer.reserve(64);
	outBuffer.clear();
	fmt::format_to(outBuffer, u"{}", var);
}
```

The error generated is:
> terminate called after throwing an instance of 'std::__ios_failure'
> what():  basic_ios::clear: iostream error

**Comment by vitaut** [comment]
iostreams don't work with `char16_t` and other exotic code unit types, it has nothing to do with {fmt}: https://godbolt.org/z/YrdbdTYPK.

**Comment by eligt** [comment]
I see. I thought it was working in certain cases and not others, which is why I reported it, but the only other case in my codebase is when printing char16_t* to the stream which obviously would work.
