### ISSUE TITLE
GCC 9.1.0 build error

### ISSUE THREAD

**Issue by acezzz** [fmtlib/fmt#2334]
I am getting following build errors using the current master version, while compiling using GCC 9.1.0. 

/fmt/include/fmt/format.h: In instantiation of ‘constexpr const char fmt::v7::detail::basic_data<>::digits [][2]’:
fmt/include/fmt/format.h:1073:22:   required from here
fmt/include/fmt/format.h:879:45: internal compiler error: in tsubst_copy, at cp/pt.c:16155
  879 |   FMT_API static constexpr const digit_pair digits[] = {
      |                                             ^~~~~~
0x5caf9a tsubst_copy
	../../gcc/cp/pt.c:16155
0x6ff980 tsubst_copy_and_build(tree_node*, tree_node*, int, tree_node*, bool, bool)
	../../gcc/cp/pt.c:19611
0x6feb6b tsubst_copy_and_build(tree_node*, tree_node*, int, tree_node*, bool, bool)
	../../gcc/cp/pt.c:19414
0x707494 tsubst_copy_and_build(tree_node*, tree_node*, int, tree_node*, bool, bool)
	../../gcc/cp/pt.c:18241
0x707494 tsubst_expr(tree_node*, tree_node*, int, tree_node*, bool)
	../../gcc/cp/pt.c:17917
0x70981c tsubst_expr(tree_node*, tree_node*, int, tree_node*, bool)
	../../gcc/cp/pt.c:15482
0x70981c tsubst_init
	../../gcc/cp/pt.c:15486
0x705532 regenerate_decl_from_template
	../../gcc/cp/pt.c:24155
0x705532 instantiate_decl(tree_node*, bool, bool)
	../../gcc/cp/pt.c:24699
0x673023 maybe_instantiate_decl
	../../gcc/cp/decl2.c:5300
0x673023 maybe_instantiate_decl
	../../gcc/cp/decl2.c:5284
0x674b68 mark_used(tree_node*, int)
	../../gcc/cp/decl2.c:5456
0x7317bf finish_id_expression_1
	../../gcc/cp/semantics.c:3777
0x7317bf finish_id_expression(tree_node*, tree_node*, tree_node*, cp_id_kind*, bool, bool, bool*, bool, bool, bool, bool, char const**, unsigned int)
	../../gcc/cp/semantics.c:3925
0x6cf309 cp_parser_primary_expression
	../../gcc/cp/parser.c:5723
0x6d30db cp_parser_postfix_expression
	../../gcc/cp/parser.c:7178
0x6dfc09 cp_parser_unary_expression
	../../gcc/cp/parser.c:8472
0x6bdb7f cp_parser_cast_expression
	../../gcc/cp/parser.c:9357
0x6be36a cp_parser_binary_expression
	../../gcc/cp/parser.c:9460
0x6bf107 cp_parser_assignment_expression
	../../gcc/cp/parser.c:9758
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.

**Comment by vitaut** [comment]
This is a gcc bug, please report via https://gcc.gnu.org/bugs/.

**Comment by acezzz** [comment]
You are right. This is an known bug and got fixed at GCC 9.3.0.  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90966

**Comment by vitaut** [comment]
Worked around in https://github.com/fmtlib/fmt/commit/8c1b22ba6d2758a0a7a3da04c5ad42beab5b130b.
