### ISSUE TITLE
gcc linkage error with exported using declaration

### ISSUE THREAD

**Issue by DanielaE** [fmtlib/fmt#2335]
See here: https://godbolt.org/z/b65oGo3G5

The compiler complains about exporting `detail::vprintf(detail::buffer<>, ..)` (printf.h:266) which has _module linkage_ through a using declaration `using detail::vprintf` (printf.h:280) which has _external linkage_.

Technically speaking, the using declaration will declare a _new_ name `::fmt::v7::vprintf` within an export group. This is ok because it is the first introduction of this name and can therefore be marked as `export` (here: in a group). Even though the using declaration ultimately refers to non-exported name `::fmt::v7::detail::vprintf` with _module linkage_, the new name in different namespace `::fmt::v7` has _external linkage_. Both names have the same declarative effect and the same semantic properties because they refer to The Same Thing™.

The problem is that it not clearly specified what should happen in this case: there's some implementation freedom iirc. I'd need to look into the standard for a definitive answer. Without digging deeper, msvc seems to create two linker symbols for the same function, one with _external linkage_ in namespace `fmt` and one with _module linkage_ in namespace `fmt::detail`, whereas gcc obviously doesn't like that whole idea at all. Technically are these two linkage types identical except for the name mangling.

I can see three options how to deal with that:

1. Move overload `detail::vprintf(detail::buffer<>, ..)` out of namespace `detail`. It's made visible in the public namespace `fmt` anyway by means of the using declaration. The latter can then be dropped and there's no more disagreement about the linkage of these names.
2. Don't make overload `detail::vprintf(detail::buffer<>, ..)` visible from namespace `fmt` through unqualified name-lookup, i.e. just drop the using declaration.
3. Drop the whole deprecated API family `{v}printf(detail::buffer<>, ..)`

**Comment by vitaut** [comment]
I removed the deprecated APIs in https://github.com/fmtlib/fmt/commit/272660e704bf7e1be7b9cae715478065639e9a13. Thanks for reporting.
