### ISSUE TITLE
call operator in custom data type is being called when I have a custom formatter

### ISSUE THREAD

**Issue by ashley-b** [fmtlib/fmt#2343]
When I create a custom formatter for boost::qvm::mat I get the following build error.
```
/opt/compiler-explorer/libs/fmt/7.1.3/include/fmt/core.h:1438:10: error: conversion from 'const boost::qvm::mat<double, 3, 3>' to 'value<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>>' is ambiguous
  return check<T>(arg_mapper<Context>().map(val));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/fmt/7.1.3/include/fmt/core.h:1587:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>, fmt::detail::type::custom_type, boost::qvm::mat<double, 3, 3>, 0>' requested here
        data_{detail::make_arg<
                      ^
/opt/compiler-explorer/libs/fmt/7.1.3/include/fmt/core.h:1626:10: note: in instantiation of member function 'fmt::format_arg_store<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>, const boost::qvm::mat<double, 3, 3>>::format_arg_store' requested here
  return {args...};
         ^
/opt/compiler-explorer/libs/fmt/7.1.3/include/fmt/core.h:2114:28: note: in instantiation of function template specialization 'fmt::make_args_checked<const boost::qvm::mat<double, 3, 3> &, char [6], char>' requested here
  const auto& vargs = fmt::make_args_checked<Args...>(format_str, args...);
                           ^
<source>:28:10: note: in instantiation of function template specialization 'fmt::print<char [6], const boost::qvm::mat<double, 3, 3> &, char>' requested here
    fmt::print("m: {}", m);
         ^
/opt/compiler-explorer/libs/fmt/7.1.3/include/fmt/core.h:1091:36: note: candidate constructor [with T = boost::qvm::mat<double, 3, 3>]
  template <typename T> FMT_INLINE value(const T& val) {
                                   ^
/opt/compiler-explorer/libs/boost_1_68_0/boost/qvm/mat.hpp:25:13: note: candidate function [with R = fmt::detail::value<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>>]
            operator R() const
            ^
1 error generated.
Compiler returned: 1
```
For some reason it is trying to call the "call operator" of the data and not my format method.
If I wrap the data in a proxy class this fixes the issue, but I feel I should not have to do this.

[Compiler Explorer](https://godbolt.org/#g:!((g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:4,endLineNumber:23,positionColumn:4,positionLineNumber:23,selectionStartColumn:3,selectionStartLineNumber:14,startColumn:3,startLineNumber:14),source:'%23include+%3Cfmt/format.h%3E%0A%0A%23include+%3Cboost/qvm/mat.hpp%3E%0A%0Ausing+mat3x3+%3D+boost::qvm::mat%3Cdouble,+3,+3%3E%3B%0A%0Atemplate+%3C%3E%0Astruct+fmt::formatter+%3Cmat3x3+%3E+final+%7B%0A++template+%3Ctypename+ParseContext%3E%0A++constexpr+auto+parse(ParseContext%26+ctx)+%7B%0A++++return+ctx.begin()%3B%0A++%7D%0A%0A++template+%3Ctypename+FormatContext%3E%0A++auto+format(const+mat3x3%26+m,+FormatContext%26+ctx)+%7B%0A++++auto+out+%3D+ctx.out()%3B%0A++++const+auto%26+a+%3D+m.a%3B%0A++++for+(const+auto%26+row+:+a)+%7B%0A++++++const+auto*+const+newLine+%3D+(%26row+%3D%3D+%26a%5B0%5D)+%3F+%22%22+:+%22%5Cn%22%3B%0A++++++out+%3D+fmt::format_to(out,+%22%7B%7D%5B+%7B:f%7D+%5D%22,+newLine,+fmt::join(row,+%22,+%22))%3B%0A++++%7D%0A++++return+out%3B%0A++%7D%0A%7D%3B%0A%0Avoid+print_matrix(const+mat3x3%26+m)%0A%7B%0A++++fmt::print(%22m:+%7B%7D%22,+m)%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:53.024714919416276,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang_trunk,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:boost,ver:'168'),(name:gsl,ver:lite),(name:fmt,ver:'713'),(name:spdlog,ver:'180')),options:'-std%3Dc%2B%2B20+-O3',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'x86-64+clang+(trunk)+(Editor+%231,+Compiler+%231)+C%2B%2B',t:'0')),k:46.97528508058374,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',m:50,n:'0',o:'',t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:14,fontUsePx:'0',wrap:'1'),l:'5',n:'0',o:'%231+with+x86-64+clang+(trunk)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),l:'3',n:'0',o:'',t:'0')),version:4)
```
#include <fmt/format.h>

#include <boost/qvm/mat.hpp>

using mat3x3 = boost::qvm::mat<double, 3, 3>;

struct fmt::formatter< boost::qvm::mat< double, 3, 3 > >  final
{
    template< typename ParseContext >
    constexpr auto parse(ParseContext& ctx)
    {
        return ctx.begin();
    }

    template < typename FormatContext >
    auto format(const boost::qvm::mat< double, 3, 3 >& m, FormatContext& ctx)
    {
        auto out = ctx.out();
        const auto& a = m.a;
        for (const auto& row : a)
        {
            const auto newLine = (&row == &a[0]) ? "" : "\n";
            out = fmt::format_to(out, "{}[ {:f} ]", newLine, fmt::join(row, ", "));
        }
        return out;
    }
};

void print_matrix(const mat3x3& m)
{
    fmt::print("m: {}", m);
}
```

**Comment by vitaut** [comment]
Worked around in https://github.com/fmtlib/fmt/commit/206000a017be86811c83ceac1bd3d26adc966521, thanks for reporting. Note that an unconstrained implicit conversion is an extremely bad idea, so I recommend reporting to boost.
