### ISSUE TITLE
Terminated after throwing 'fmt::v7::system_error'

### ISSUE THREAD

**Issue by sunmy2019** [fmtlib/fmt#2344]
I am writing codes for https://github.com/fmtlib/fmt/issues/2319 . During testing I found that:
Mixed using of "char" and "wchar" would cause this bug.

See https://godbolt.org/z/fWx84x8cv

This issue starts at release 6.0.0.

```cpp
#include <fmt/format.h>

int main () {
    fmt::print("{}",42);
    fmt::print(L"{}",42);
}
```

I searched this error in issues, nothing found. I post it here. I don't know if it's a feature or a bug, or a known issue.

**Comment by sunmy2019** [comment]
This looks like a feature. But since
```cpp
std::cout << 42;
std::wcout << 42;
```
can always works, I would love to see fmtlib to do the same.

**Comment by vitaut** [comment]
This is a stdio, not {fmt} problem. I wouldn't recommend using `wchar_t` with I/O at all.
