### ISSUE TITLE
Error C4430 Missing type specifier - int is accepted. Note: "default-int" is not supported by C ++

### ISSUE THREAD

**Issue by Eddcapone** [fmtlib/fmt#2347]
The project https://github.com/Pocakking/BigBaseV2 is using this library, but I can't build it, because your lib has a bug.

I get this error (and alot of others coming from your lib):

![image](https://user-images.githubusercontent.com/16349349/121562417-b5eaf700-ca19-11eb-8803-b2eed38f493d.png)

Error C4430 Missing type specifier - int is accepted. Note: "default-int" is not supported by C ++. fmtlib A: \ DEV \ BigBaseV2  \ vendor \ fmtlib \ src \ fmt.cc 1

**Comment by vitaut** [comment]
Don't include `fmt.cc` in your project. The easiest way to use {fmt} is via CMake: https://fmt.dev/latest/usage.html.
