### ISSUE TITLE
Question about ranges and formatting

### ISSUE THREAD

**Issue by TomSchammo** [fmtlib/fmt#2348]
I know that one can format individual numbers to print their hex values, and I know that one can also print whole vectors using ranges.

However I  didn't see a way to combine those. Is it possible to print the hex representation of every value in a vector for example?

**Comment by vitaut** [comment]
You can do it with `fmt::join` (https://godbolt.org/z/W5cYn498Y):

```c++
#include <fmt/format.h>
#include <vector>

int main() {
  auto v = std::vector{10, 20, 30};
  fmt::print("{:x}", fmt::join(v, ", "));
}
```

Output:

```
a, 14, 1e
```

**Comment by TomSchammo** [comment]
Thanks!
