### ISSUE TITLE
Formatting Range of std::byte

### ISSUE THREAD

**Issue by HazardyKnusperkeks** [fmtlib/fmt#2355]
After 9d7b53cb9baf4b1c3f00f9f70cf70753fc51a2d8 it's not possible to format a range (i.e. span or vector) of std::byte anymore. You have to use fmt::join. Is this the intended way?

**Comment by vitaut** [comment]
The correct fix would be to replace `has_formatter` with `is_formattable` in https://github.com/fmtlib/fmt/blob/d57b2a652538984448da91390331806d530ecfce/include/fmt/ranges.h#L315 but unfortunately it's broken in MSVC for some reason.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/60cd5ea3f29666dd80d316cb7f59bca07319723d. Thanks for reporting!
