### ISSUE TITLE
Concept check

### ISSUE THREAD

**Issue by klemens-morgenstern** [fmtlib/fmt#2358]
It would be really nice if a fmt::compile_string check could be put into a constexpr predicate, so that I could use it in a static_assert of c++20 concept.

**Comment by vitaut** [comment]
Thanks for the suggestion but `compile_string` is an implementation detail and not a part of the public API (or the `fmt` namespace).

**Comment by klemens-morgenstern** [comment]
Would you accept a PR? i am using it in c++20 with compile time strings so I can write ’format<"thingy {}">(42)’.

**Comment by vitaut** [comment]
No, I recommend using the UDL-based API, e.g. `format("thingy {}"_cf, 42)`.
