### ISSUE TITLE
consteval changes for fmt::basic_format_string break existing code

### ISSUE THREAD

**Issue by ldalessa** [fmtlib/fmt#2361]
It seems like at some point constructing a `fmt::basic_format_string` became `consteval`. We had been using forwarded format cstrings like https://godbolt.org/z/6jr1zfdsh, but this is no longer compiling. Should we be changing our client code (and if so, how?) or is this a regression that can be fixed at the library level.

**Comment by vitaut** [comment]
You are right, the API is being changed to enable compile-time checks in the upcoming major release. I recommend using 7.x until the API is stabilized and 8.0 is released.

**Comment by ldalessa** [comment]
Okay thank you. The 7-series bombards us with `warning: writing X bytes into a region of size 0 [-Wstringop-overflow=]` so we have been avoiding it. I'm relatively sure (really hopeful) that they're false positives.

**Comment by ldalessa** [comment]
Is there going to be a workaround for this issue in the 8 series?

**Comment by mwinterb** [comment]
Is the issue the stringop-overflow warnings? Or the `basic_format_string` change? If it's `basic_format_string`, you should follow the suggestion here: https://github.com/fmtlib/fmt/issues/2391#issuecomment-869043202. And if you need to use format strings generated at runtime, wrap them with `fmt::runtime()` before calling your wrapper.
I suppose you could also put the call to `runtime` in the implementation of the wrapper, but... no.
Also, while vitaut only mentions it for C++20, it works fine for previous language versions and `FMT_STRING()` still works there if you need to support pre-C++20.

**Comment by ldalessa** [comment]
I don't care at all about compile-time checking (never have, way too slow). I just wanted to forward a format string (c-string, std::string, whatever the user wants to give me) through a function to `fmt::print`. I don't see overflow warnings, just `consteval` problems that weren't an issue in the 7 series. 

I basically want the equivalent of what used to be possible in 7. 

Using `fmt::format_string` forces the format string to be `constexpr` which I don't want, and forcing callers to wrap something in `fmt::runtime` is a terrible API for my passthrough code. Is there really no non-`constexpr` solution in 8 other than that?

**Comment by mwinterb** [comment]
Putting `fmt::runtime` just in your forwarding function works fine:
https://godbolt.org/z/fMYj4x55h
And if you need to support < 8, you can check the FMT_VERSION macro to detect if fmt::runtime is available. FMT_STRING() won't work like it did in 7. I know you said you don't care compile time format string checking, but for others reading.

**Comment by vitaut** [comment]
You can either wrap a runtime string in `fmt::runtime` or provide a wrapper function that does it automatically. Note that compile time overhead from the checks is relatively small: we've migrated all the test suite of {fmt} to them and there was hardly any change to build times.

**Comment by ldalessa** [comment]
Oh, great.

I was confused by the statement:
> I suppose you could also put the call to runtime in the implementation of the wrapper, but... no.

but if that's possible that's fine.

It's also great news that compile-time checking has improved in performance. I had tried to use the checking macros in the past and it was just causing huge slowdowns.

**Comment by mwinterb** [comment]
Sorry for the confusion. My "but... no" was a personal judgement of it being distasteful to not get compile time checks. But I can see how that could easily be read as "but... no, that doesn't work". Especially since upgrading to v8 found several bugs in rarely executed code. So for me, `format_string` is the number 1 reason to switch to v8.

**Comment by marcusmueller** [comment]
Just adding this comment for posteriority, as this issue has all the right keywords to be found when this breaks, and it took me a while to realize [this](https://github.com/fmtlib/fmt/issues/2391#issuecomment-869043202) is the solution to

* solve the issue of C++20 + perfect forwarding of the fmt string failing
* while not wrapping everything in `fmt::runtime` (and thereby completely disabling compile time checks)


```c++
#include <fmt/core.h>

template<typename... T>
void log(fmt::format_string<T...> fmt, T&&... args) {
    // unrelated stuff here
    auto str = fmt::format(fmt, std::forward<T>(args)...);
    // other unrelated stuff here
}

int main() {
  log("{}", "test");
}
```

NB: this has also been tested with forwarding to `spdlog::logger::debug()` etc.

**Comment by milkpirate** [comment]
Hey, I am having trouble getting the wrapper to work, and I stumbled across this. I am not super familiar with C++ so please bear with me. My code looks like:

```cpp
class PamWrapper {
    public:
...
    template<typename... Args>
    void _log(const int priority, fmt::format_string<Args...> str, Args&&... args);
    template<typename... Args>
    void info(fmt::format_string<Args...> str, Args&&... args);

... 

template<typename... Args>
void PamWrapper::_log(const int priority, fmt::format_string<Args...> fmt, Args&&... args) {
    auto msg = fmt::format(std::forward<fmt::format_string<Args...>>(fmt), std::forward<Args>(args)...);
    pam_syslog(_pamHandle, priority, "%s", msg.c_str());
}

template<typename... Args>
void PamWrapper::info(fmt::format_string<Args...> fmt, Args&&... args) {
    _log(LOG_INFO, fmt, args...);
}
```
But I am still getting:
```bash
undefined symbol: _ZN10PamWrapper4_logIJiEEEviN3fmt2v919basic_format_stringIcJDpNS2_13type_identityIT_E4typeEEEEDpOS5_
```
on loading my `.so`.

I am using conan (cmake) and v9.0.0. Surely its a silly mistake, but I am not able to find it.

**Comment by marcusmueller** [comment]
@milkpirate that's a link-time error and hence unrelated to this issue. Please ask this on e.g. stackoverflow.com instead of on this bug issue!

In short, looks like you're not properly linking within your own project.
