### ISSUE TITLE
Undefined reference with FMT_HEADER_ONLY and core.h

### ISSUE THREAD

**Issue by dingjinx** [fmtlib/fmt#2362]
When building with FMT_HEADER_ONLY and including fmt/core.h.

gcc version 9.3.0 on linux

#include "fmt/core.h"

int main() 
{
  fmt::print("Hello, world!\n");
  return 0;
}

$g++ test1.cpp -L/fmt
/usr/bin/ld: /tmp/cciBXUGz.o: in function `main':
test1.cpp:(.text+0x81): undefined reference to `fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::appender, char> >)'
collect2: error: ld returned 1 exit status

Shouldn't this compile?
I got the same error on Windows.

**Comment by dingjinx** [comment]
I got the underline error by using  Visual Studio.

error LNK2019: unresolved external symbol "void __cdecl fmt::v7::detail::vprint_mojibake(struct _iobuf *,class fmt::v7::basic_string_view<char>,class fmt::v7::basic_format_args<class fmt::v7::basic_format_context<class fmt::v7::appender,char> >)" (?vprint_mojibake@detail@v7@fmt@@YAXPEAU_iobuf@@V?$basic_string_view@D@23@V?$basic_format_args@V?$basic_format_context@Vappender@v7@fmt@@D@v7@fmt@@@23@@Z) referenced in function "void __cdecl fmt::v7::print<>(class fmt::v7::basic_format_string<char>)" (??$print@$$V@v7@fmt@@YAXV?$basic_format_string@D$$V@01@@Z)

Thanks for replying.

**Comment by OnurKader** [comment]
I think you need to include `fmt/format.h` for the header-only mode.
[docs](https://fmt.dev/latest/api.html?highlight=header-only#core-api)
In master it includes `format.h` if it's header-only [code](https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L2999-L3001), [docs](https://fmt.dev/dev/api.html?highlight=header-only#core-api)

**Comment by vitaut** [comment]
Which library version do you use?

**Comment by dingjinx** [comment]
> Which library version do you use?

The latest 7.1.3

**Comment by dingjinx** [comment]
> I think you need to include `fmt/format.h` for the header-only mode.
> [docs](https://fmt.dev/latest/api.html?highlight=header-only#core-api)
> In master it includes `format.h` if it's header-only [code](https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L2999-L3001), [docs](https://fmt.dev/dev/api.html?highlight=header-only#core-api)

I got the same error when using the format.h

**Comment by vitaut** [comment]
There is no `appender` in 7.1.3, perhaps you have multiple conflicting versions of the library installed. I recommend uninstalling and getting one from here: https://github.com/fmtlib/fmt/releases/tag/7.1.3.

**Comment by vitaut** [comment]
I was not able to repro the issue on master either: https://godbolt.org/z/s4ersT4EM.
