### ISSUE TITLE
Inconsistent API in <color.h>

### ISSUE THREAD

**Issue by sunmy2019** [fmtlib/fmt#2364]
I found that in 0dd91e2 you move the wchar support into the `xchar.h`, which makes API of `fmt::print` inconsistent in `core.h` and `color.h`.

The former takes a `format_string<Args...>`, but the latter takes a `S` with `detail::is_string<S>::value == true`.

You may want to change this.

**Comment by vitaut** [comment]
The API in `fmt/color.h` is correct. To use `wchar_t` you need to include both `fmt/color.h` and `fmt/xchar.h`: https://godbolt.org/z/6Ezfzv67s.

**Comment by sunmy2019** [comment]
I was meaning the `format_string<Args...>` is FMT_CONSTEVAL, but the latter isn't. This inconsistency invalidates the following code like

```cpp
template<typename... Args>
void log(format_string<Args...> fmt, Args&&... args){
  if (some condition)
    fmt::print(fmt, std::forward<Args>(args)...);
  else
    fmt::print(fg(fmt::color::red), fmt, std::forward<Args>(args)...);
}
```
because `fmt::print` in `color.h` cannot take `format_string<Args...>`

Nor can I use the following code because `fmt` in the `core.h` needs to be constexpr (with consteval).

```cpp
template<typename S, typename... Args>
void log(const S& fmt, Args&&... args){
  if (some condition)
    fmt::print(fmt, std::forward<Args>(args)...);
  else
    fmt::print(fg(fmt::color::red), fmt, std::forward<Args>(args)...);
}
```

**This may be better, if we enable `fmt::print` in `color.h` to take a `format_string<Args...>`.**

---
PS. for this problem, I soon found that I can directly invokes `fmt::vprint`.

**Comment by sunmy2019** [comment]
> The API in `fmt/color.h` is correct. To use `wchar_t` you need to include both `fmt/color.h` and `fmt/xchar.h`: https://godbolt.org/z/6Ezfzv67s.

I was suggesting we could enable `fmt::print` in `color.h` to take a `format_string<Args...>`. At this time, `fmt::detail::is_string<fmt::format_string<>>::value ` is false. https://godbolt.org/z/cMa8Ydzaj

This is unsual, since `formar_string` sounds like a string, isn't it?

**Comment by vitaut** [comment]
You can do the following:

```c++
template<typename... Args>
void log(fmt::format_string<Args...> fmt, Args&&... args){
  if (true)
    fmt::print(fmt, std::forward<Args>(args)...);
  else
    fmt::print(fg(fmt::color::red), fmt::string_view(fmt), std::forward<Args>(args)...);
}
```
for now.

> format_string sounds like a string, isn't it?

`is_string` is going away so it doesn't really matter what it returns for `format_string`.
