### ISSUE TITLE
Add support for use in CUDA device-side code

### ISSUE THREAD

**Issue by eyalroz** [fmtlib/fmt#2366]
While libfmt can be compiled with NVCC and used in host side code (i.e. when running on the CPU), it would be quite useful - at least for debugging purposes - to have it available on the GPU as well.

I am considering making such an adaptation of the library.

**Comment by vitaut** [comment]
Thanks for the suggestion. There are no plans to add such support but a PR would be welcome provided that it's not too intrusive.

**Comment by eyalroz** [comment]
Can you perhaps characterize what aspects of potential changes would be considered too intrusive? e.g. is it impact on host-side performance? Lines added? Lines modified? Lines modified after preprocessing? etc.

**Comment by vitaut** [comment]
>  is it impact on host-side performance?

This is a good example. Adding substantial parts that are conditionally compiled is another one.

**Comment by eyalroz** [comment]
@vitaut : How substantial is substantial? For example, I would need to write 'decorated' versions of std::back_insert_iterator , a couple of standard library algorithms, maybe a chair traits function or two.

**Comment by vitaut** [comment]
This does sound excessive for supporting one system. Forking might be a better option.

**Comment by eyalroz** [comment]
@vitaut : Well, once you can assume C++20, then most of those go away, since enough of the standard library gets constexpr'ed. ... but it will be at least 4-5 years until you can assume CUDA code is C++20 :-(

Anyway, assuming no more unexpected additions CUDA support would mean an addition ~700 lines all included ( preprocessor directives, empty lines, comments etc.)

**Comment by eyalroz** [comment]
Also, suppose I make it a fork. Is it better, in your opinion, to fork off of 8.0.0 (which hopefully is forthcoming), or off of 7.1.3?

**Comment by vitaut** [comment]
I recommend forking the latest release (8.0).

**Comment by eyalroz** [comment]
@vitaut : Well, I have the basic fork up. I've only done a slight bit of testing, so there might be a few more glitches, and I will eventually try to have (almost) the entire test suite run for GPU-device-side use, but the work is essentially done.

Would you be willing to code-review the changes?

**Comment by vitaut** [comment]
> Would you be willing to code-review the changes?

Sure, I can take a look.
