### ISSUE TITLE
Why use std::uninitialized_fill_n for filling a buffer of Char's?

### ISSUE THREAD

**Issue by eyalroz** [fmtlib/fmt#2367]
In format-inl.h, the standard library function `std::uninitialized_fill_n()` is used to fill a buffer of some kind of char type (`char` or `wchar_t` are the typical ones). These types do not need any special treatment when uninitialized, so why not just  use the `fill_n()` already in fmt? Is there some clever rationale here?

**Comment by vitaut** [comment]
Elements may not be initialized so `uninitialized_fill_n` is more appropriate.
