### ISSUE TITLE
std::string_view as format string question

### ISSUE THREAD

**Issue by randian** [fmtlib/fmt#2369]
I've been using std::string_view constants as format strings e.g. "fmt::format("{}"sv, 123)". Is there a reason I should not do that? Does it inhibit any compile-time processing, for example? I noticed that fmt::format() didn't have a char array overload so it seemed like an std::string_view, with length available at compile time, would be marginally better than scanning a C string looking for a NUL character.

**Comment by vitaut** [comment]
It should work but there is no reason to do this as there is no performance benefit, just more unnecessary typing.
