### ISSUE TITLE
FMT_STATIC_THOUSANDS_SEPARATOR defined as wchar_t doesn't compile

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#2372]
```C++
#define FMT_STATIC_THOUSANDS_SEPARATOR static_cast<wchar_t>(rand())
```
MSVC: format-inl.h(120): error C2397: conversion from 'wchar_t' to 'Char' requires a narrowing conversion
GCC: format-inl.h:120:48: warning: narrowing conversion of '(wchar_t)rand()' from 'wchar_t' to 'char' inside { } [-Wnarrowing]

Perhaps an explicit cast needed?
```DIFF
diff --git a/format-inl.h b/format-inl.h
index a802aea5..687a5a85 100644
--- a/format-inl.h
+++ b/format-inl.h
@@ -117,7 +117,7 @@ template <typename Char> FMT_FUNC Char decimal_point_impl(locale_ref loc) {
 #else
 template <typename Char>
 FMT_FUNC auto thousands_sep_impl(locale_ref) -> thousands_sep_result<Char> {
-  return {"\03", FMT_STATIC_THOUSANDS_SEPARATOR};
+  return {"\03", static_cast<Char>(FMT_STATIC_THOUSANDS_SEPARATOR)};
 }
 template <typename Char> FMT_FUNC Char decimal_point_impl(locale_ref) {
   return '.';
```

**Comment by vitaut** [comment]
`FMT_STATIC_THOUSANDS_SEPARATOR` must be a `char` because it is used for both `char` and `wchar_t`.

**Comment by alabuzhev** [comment]
> `FMT_STATIC_THOUSANDS_SEPARATOR` must be a `char` because it is used for both `char` and `wchar_t`.

That looks like a quite artificial restriction, especially for Windows.

Anyway, found a workaround:
```C++
struct thousands_separator
{
	operator wchar_t() const
	{
		return some_wide_separator();
	}

	operator char() const
	{
		return static_cast<char>(operator wchar_t());
	}
};

#define FMT_STATIC_THOUSANDS_SEPARATOR (thousands_separator{})
```

Please don't break it :)
