### ISSUE TITLE
v8 regression when compiling with FMT_USE_USER_DEFINED_LITERALS=0

### ISSUE THREAD

**Issue by mbunkus** [fmtlib/fmt#2384]
The following small test program can be compiled just fine with e.g. 7.1.3, but it fails with 8.0.0:

```c++
#define FMT_USE_USER_DEFINED_LITERALS 0

#include <fmt/format.h>

int main() {
  return fmt::format("hello {0}", "world").size();
}
```

Error message with 8.0.0 & gcc 11:

```
/home/mosu/prog/video/mkvtoolnix/lib/fmt/include/fmt/format.h:2752:64: error: no template named 'udl_arg' in namespace 'fmt::v7::detail'
constexpr auto operator"" _a(const char* s, size_t) -> detail::udl_arg<char> {
                                                       ~~~~~~~~^
/home/mosu/prog/video/mkvtoolnix/lib/fmt/include/fmt/format.h:2753:11: error: cannot initialize return object of type 'int' with an lvalue of type 'const char *'
  return {s};
          ^
/home/mosu/prog/video/mkvtoolnix/lib/fmt/include/fmt/format.h:2768:16: error: no template named 'udl_formatter' in namespace 'fmt::v7::detail'
    -> detail::udl_formatter<char> {
       ~~~~~~~~^
/home/mosu/prog/video/mkvtoolnix/lib/fmt/include/fmt/format.h:2769:11: warning: too many braces around scalar initializer [-Wmany-braces-around-scalar-init]
  return {{s, n}};
          ^~~~~~
/home/mosu/prog/video/mkvtoolnix/lib/fmt/include/fmt/format.h:2769:12: error: cannot initialize return object of type 'int' with an lvalue of type 'const char *'
  return {{s, n}};
           ^
```

I've built without user-defined literals for years now because a) my program doesn't use them and b) there are a lot of warnings with `-Wpedantic` and user-defined literals activated (and I'm somewhat anal about warnings).

**Comment by alexezeder** [comment]
This probably will be fixed by https://github.com/fmtlib/fmt/pull/2376.

**Comment by DanielaE** [comment]
May be some additional tests for these specific compilation environments are in order.

**Comment by vitaut** [comment]
Fixed in #2376, thanks for reporting.

**Comment by mbunkus** [comment]
Thanks for fixing this one so quickly in particular and all the work you've all done of this fantastic library in particular. Over the years my MKVToolNix has used the `printf` family, the C++ I/O streams and Boost's `format` before finally discovering and convert to `fmt`. It is so well designed, such a joy to work with, so fast and type-safe on top of it that I pretty much recommend it to everyone doing C++ things. Again, thank you all so much!

**Comment by vitaut** [comment]
Thanks @zx2c4 for the actual fix =).
