### ISSUE TITLE
Provide a GPG signature of release tarball, or (signed) checksum files

### ISSUE THREAD

**Issue by augfab** [fmtlib/fmt#2385]
My project uses {fmt}.

In our CI/CD pipelines, we compile and install the library to be later used by the project.
To get the source, we download the tarball hosted by GitHub for each release, _e.g._ [7.1.3.tar.gz](https://github.com/fmtlib/fmt/archive/refs/tags/7.1.3.tar.gz). However, it's always dangerous to use stuff pulled from the Wide Wild Internet without doing any verification, so I opened this issue to propose an improvement.

What projects can do to remedy this, is to provide a signature of the tarball, or of a checksums file. The signature is obtained by a different canal (usually from a keyserver). This approach is followed by [GCC](https://gcc.gnu.org/mirrors.html) and [CMake](https://cmake.org/install/#download-verification).

Would it be possible for the {fmt} project to adopt this approach as well?

GPG signatures provide a strong indication that what I downloaded is legit.

An easier approach to put in place would be to publish just the hash of the release archives, _i.e._:
```shell
$ sha256sum --tag 7.1.3.tar.gz  7.1.3.zip  fmt-7.1.3.zip > fmt-7.1.3.sha256
$ cat fmt-7.1.3.sha256
SHA256 (7.1.3.tar.gz) = 5cae7072042b3043e12d53d50ef404bbb76949dad1de368d7f993a15c8c05ecc
SHA256 (7.1.3.zip) = 50f2fd9f697f89726ae3c7efe84ae48c9e03158a2958eea496eeaa0fb190adb6
SHA256 (fmt-7.1.3.zip) = 5d98c504d0205f912e22449ecdea776b78ce0bb096927334f80781e720084c9f
```
This file can then be used like so:
```shell
$ curl -L \
       -O https://github.com/fmtlib/fmt/releases/download/7.1.3/fmt-7.1.3.zip 
       -O https://github.com/fmtlib/fmt/releases/download/7.1.3/fmt-7.1.3.sha256
$ sha256sum --check --ignore-missing fmt-7.1.3.sha256
fmt-7.1.3.zip: OK
$ echo $?
0
```

This file can be created automatically as part of the release process.

What do you think?

**Comment by vitaut** [comment]
You can generate such signature yourself. Also releases don't change often and have corresponding git commit hashes which are effectively checksums. I don't think it's worth adding anything extra in {fmt} in this respect.

**Comment by augfab** [comment]
OK so the model is to trust-on-first-use.
That's what we already do, se we'll keep doing that :smile:
In any case, thanks for having taken my request into consideration.
