### ISSUE TITLE
Exotic characters, basic_format_string, and formatting to an output iterator issues

### ISSUE THREAD

**Issue by mwinterb** [fmtlib/fmt#2388]
Take this silly example:
https://gcc.godbolt.org/z/f3ce6Mb3n
```c++
#include <fmt/format.h>
#include <fmt/xchar.h>

#include <string>

#if 0
FMT_BEGIN_NAMESPACE
template <typename Char, typename... Args>
inline auto to_string_view(const basic_format_string<Char, Args...>& s)
-> basic_string_view<Char> {
    return s;
}
FMT_END_NAMESPACE
#endif

template <typename... Args>
std::wstring forwarder(
    fmt::wformat_string<Args...> fmtstring,
    Args&&... args) {
  std::wstring message;
  fmt::format_to(std::back_inserter(message), fmtstring, std::forward<Args>(args)...);
  return message;
}

std::wstring produce_a_wide_message()
{
    return forwarder(L"joe{}", 1);
}
```
The [logical overload](https://github.com/fmtlib/fmt/blob/d551b88a6d2ff1f2e47e1bc639fccad30f11b0a7/include/fmt/xchar.h#L130-L137) isn't being picked up because `basic_format_string` doesn't meet the requirements of `fmt::detail::is_string`, so there's no `char_t` defined for it. Switching the `#if 0` to `#if 1` fixes the compilation, but I'm assuming it's quite deliberate that basic_format_string doesn't meet the requirements of `is_string`. Switching "my" code to
```
fmt::vformat_to(std::back_inserter(message), fmt::wstring_view(fmtstring), fmt::make_wformat_args(args...));
```
also fixes things, but is this intended to work? The same example works fine with `char`.

**Comment by sunmy2019** [comment]
I reported similar issues a week ago.

https://github.com/fmtlib/fmt/issues/2364

**Comment by vitaut** [comment]
Please see https://github.com/fmtlib/fmt/issues/2364#issuecomment-864560043. TL;DR: `is_string` is going away.

**Comment by mwinterb** [comment]
Apologies. I had seen that issue, saw that is_string was going away, but since it was still in with the 8 release, thought maybe that had been reversed.
