### ISSUE TITLE
How to properly wrap fmt::format() and keep compile-time checks?

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#2391]
Subj.
I'd like to wrap it to add extra functionality (e.g. to implement a logger):

```C++
#include <string_view>

#include <fmt/format.h>

using namespace std::literals;

template<typename format, typename... args>
void log_by_value(format Format, args&&... Args)
{
    // unrelated stuff here
    auto Str = fmt::format(Format, std::forward<args>(Args)...);
    // other unrelated stuff here
}

template<typename format, typename... args>
void log_by_ref(format&& Format, args&&... Args)
{
    // unrelated stuff here
    auto Str = fmt::format(std::forward<format>(Format), std::forward<args>(Args)...);
    // other unrelated stuff here
}

int main()
{
    // Works, but old and sad
    log_by_value(FMT_STRING("{}"), "test");

    // This used to work in 7.x, now it doesn't
    log_by_ref(FMT_STRING("{}"), "test");

    // Works, but no compile-time check
    log_by_value(fmt::runtime("{:d}"), "test");
    log_by_ref(fmt::runtime("{:d}"), "test");

    // Doesn't work and not expected to work due to array to pointer decay 
    log_by_value("{}", "test");
    log_by_value("{}"sv, "test");

    // Doesn't work, any chance?
    log_by_ref("{}", "test");
    log_by_ref("{}"sv, "test");
}
```

Is there any way to do that naturally *and* have compile-time checks?

Godbolt:
https://godbolt.org/z/W5M9qMcc8

**Comment by vitaut** [comment]
You can do the following in C++20 (https://godbolt.org/z/6hz9xfzMP):

```c++
#include <fmt/core.h>

template<typename... T>
void log(fmt::format_string<T...> fmt, T&&... args) {
    // unrelated stuff here
    auto str = fmt::format(fmt, std::forward<T>(args)...);
    // other unrelated stuff here
}

int main() {
  log("{}", "test");
}
```
which gives compile-time checks without a macro.

**Comment by Folling** [comment]
Given your example with a `log` function. Is there a reason no overload for `fmt::print` exists that takes
a FILE, a text style, a `fmt::format_string`, and arguments?
The templated versions do not accept `fmt::format_string` as the `detail::is_string` function evaluates to false for them.
If that's unintended I'll open a new issue for that, it just seemed fitting to post it here.

**Comment by vitaut** [comment]
> Is there a reason no overload for fmt::print exists that takes a FILE, a text style, a fmt::format_string, and arguments?

Not all formatting functions have been migrated to the new API yet. I added a note in https://github.com/fmtlib/fmt/issues/2390#issuecomment-916277691.

**Comment by stryku** [comment]
Is it possible to create a wrapper that works nicely with `FMT_COMPILE` as well?
https://godbolt.org/z/7Pd36nrbe

**Comment by vitaut** [comment]
Format string compilation needs separate overloads, see the ones in `fmt/compile.h`.

**Comment by stryku** [comment]
But the overloads there require SFINAE on stuff from `details`
```
template <typename OutputIt, typename S, typename... Args,
          FMT_ENABLE_IF(detail::is_compiled_string<S>::value)>
FMT_CONSTEXPR OutputIt format_to(OutputIt out, const S&, Args&&... args)

template <typename OutputIt, typename CompiledFormat, typename... Args,
          FMT_ENABLE_IF(detail::is_compiled_format<CompiledFormat>::value)>
constexpr FMT_INLINE OutputIt format_to(OutputIt out, const CompiledFormat& cf,
                                        const Args&... args)
```
I believe it's not good to use implementation details.

**Comment by vitaut** [comment]
Yes, `is_compiled_string` is an implementation detail but a PR to make it public would be welcome.
