### ISSUE TITLE
Updated to 8.0.0 from 7.1.3 and now have compile issue with dynamic_format_arg_store<format_context>

### ISSUE THREAD

**Issue by abrownsword** [fmtlib/fmt#2393]
Updated to 8.0.0 and code that compiled fine with 7.1.3 now fails with:

`error: implicit instantiation of undefined template 'fmt::v7::dynamic_format_arg_store<fmt::v7::basic_format_context<fmt::v7::appender, char>>'`

The code involved is (in slightly stripped down form):

`
    #include "fmt/format.h"

    typedef fmt::format_context 			fmt_ctx;
    typedef fmt::basic_format_arg<fmt_ctx>	        fmt_arg;
    typedef fmt::basic_format_args<fmt_ctx>	        fmt_args;
    typedef fmt::dynamic_format_arg_store<fmt_ctx>  fmt_argsvec;

    fmt_argsvec args;        <<--- compiler gives error here
`

Any suggestions about what I might be doing wrong here?

**Comment by vitaut** [comment]
Make sure to include `fmt/args.h` where `dynamic_format_arg_store` is defined: https://godbolt.org/z/MxavKjc5W.

**Comment by Yitzi2** [comment]
> fmt/args.h

Thank you; I had the same issue in 8.1.1.  (I knew I needed an include, but not which file.)  Would it be possible to update the documentation at https://fmt.dev/8.1.1/api.html to provide this information about where such things are defined?

**Comment by vitaut** [comment]
We don't update the docs retroactively but this will be mentioned in the docs for the new version.
