### ISSUE TITLE
Warnings from {fmt} when using `xchar.h` header and `-fsigned-char` flag on ARM

### ISSUE THREAD

**Issue by alexezeder** [fmtlib/fmt#2400]
On the latest {fmt} version (8.0, `master`) I get these warnings just by including {fmt} headers (https://godbolt.org/z/arEYeq9rx):
```
/fmt/trunk/include/fmt/format.h:1026:17: warning: comparison of integer expressions of different signedness: 'const wchar_t' and 'const char' [-Wsign-compare]
 1026 |   return lhs[0] == rhs[0] && lhs[1] == rhs[1];
      |          ~~~~~~~^~~~~~~~~
...
/fmt/trunk/include/fmt/core.h:2092:14: warning: comparison of integer expressions of different signedness: 'const wchar_t' and 'char' [-Wsign-compare]
 2092 |     if (*out == value) return true;
      |         ~~~~~^~~~~~~~
```
from here:
https://github.com/fmtlib/fmt/blob/c3c27e5ab5a84d29a94fd3781a10eadc80a371a0/include/fmt/format.h#L1025-L1027
https://github.com/fmtlib/fmt/blob/c3c27e5ab5a84d29a94fd3781a10eadc80a371a0/include/fmt/core.h#L2088-L2095

These warnings are pretty logical since the signedness of char-types (`char` and `wchar_t`) is different in this case - https://godbolt.org/z/1Pdxbesvf.

Still, there are no warnings with {fmt} 7.1.3 - https://godbolt.org/z/T1qPjfoaG.

I'm not familiar with that part of the library, so maybe someone can find the cause of this regression in few seconds, for example, @vitaut 😉

**Comment by vitaut** [comment]
It's unclear why there were no warnings in 7.1.3 but I fixed them in https://github.com/fmtlib/fmt/commit/785908ee37f970513099704386f1befca25de625. Thanks for reporting.

**Comment by alexezeder** [comment]
Thank you for fixing this!
