### ISSUE TITLE
[MSVC][permissive-] ranges.h(395,41): error C2672: 'get': no matching overloaded function found

### ISSUE THREAD

**Issue by QuellaZhang** [fmtlib/fmt#2401]
Hi vitaut,

Tried to build fmt with /permissive- on MSVC and found the follow error, can you help look? Thanks!

**Repro steps:**

1. open VS2019 x86 tools command (VS2019 16.10.2)
2. git clone https://github.com/fmtlib/fmt
3. cd fmt
4. mkdir build && cd build
5. set _CL_=/permissive-
6. cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -A Win32 ..
7. cmake --build . --config Release --verbose -- /maxcpucount

**Repro command line:**
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\bin\HostX64\x86\CL.exe" /c /IE:\fmt\include /IE:\fmt\test\gtest\. /nologo /W1 /WX- /diagnostics:column /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D GTEST_HAS_STD_WSTRING=1 /D _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING=1 /D FMT_LOCALE /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /external:env:EXTERNAL_INCLUDE /external:W1 /Gd /TP /analyze- /errorReport:queue "E:\fmt\test\ranges-test.cc" /permissive-

[build.log](https://github.com/fmtlib/fmt/files/6731389/build.log)
**Error info:**
F:\gitP\fmtlib\fmt.git\include\fmt/ranges.h(395,41): error C2672: 'get': no matching overloaded function found [F:\gitP\fmtlib\fmt.git\build_x86\test\ranges-test.vcxproj]
F:\gitP\fmtlib\fmt.git\include\fmt/ranges.h(394,1): error C2784: 'tuple_element<_Idx,std::pair<_Ty1,_Ty2>>::type &std::get(std::pair<_Ty1,_Ty2> &) noexcept': could not deduce template argument for 'std::pair<_Ty1,_Ty2> &' from 'const std::tuple<float>' [F:\gitP\fmtlib\fmt.git\build_x86\test\ranges-test.vcxproj]
F:\gitP\fmtlib\fmt.git\include\fmt/ranges.h(394,1): error C2784: 'tuple_element<_Idx,std::pair<_Ty1,_Ty2>>::type &std::get(std::pair<_Ty1,_Ty2> &) noexcept': could not deduce template argument for 'std::pair<_Ty1,_Ty2> &' from 'const std::tuple<char,int &>' [F:\gitP\fmtlib\fmt.git\build_x86\test\ranges-test.vcxproj]
F:\gitP\fmtlib\fmt.git\include\fmt/ranges.h(394,1): error C2784: 'tuple_element<_Idx,std::pair<_Ty1,_Ty2>>::type &std::get(std::pair<_Ty1,_Ty2> &) noexcept': could not deduce template argument for 'std::pair<_Ty1,_Ty2> &' from 'const std::tuple<char,int,float>' [F:\gitP\fmtlib\fmt.git\build_x86\test\ranges-test.vcxproj]

**Comment by vitaut** [comment]
I don't have a Windows machine at hand to investigate this but a PR with a workaround would be welcome.

**Comment by QuellaZhang** [comment]
@vitaut Thanks, I can help with testing. And you say "workaround", do you think this is a complier issue? If so, I will confirm with them.

**Comment by vitaut** [comment]
> do you think this is a complier issue?

I am not sure but since it only happens on MSVC and specific configuration it's quite likely.

**Comment by joemmett** [comment]
This is due to differences in implicit dependencies in the standard template libraries. ranges.h needs <tuple> and gets it on other platforms from <memory>, but MSVC's STL doesn't have that implicit dependency. I have submitted a PR #2407 to add an explicit include of <tuple> to avoid relying on STL internals.
