### ISSUE TITLE
Feature request: add support for unit prefixes

### ISSUE THREAD

**Issue by ilyapopov** [fmtlib/fmt#2404]
A common task is to print numbers using unit prefixes. In computing it is often sizes in bytes (such as "743 kB"), but also other quantities in science, engineering, etc, (such as "1.34 ns"). Therefore, I believe it will be beneficial to the whole community if facilities for formatting numbers with unit prefixes would be included in fmtlib and maybe even in the standard.

Hereafter I describe how do I see this feature:

- Add new formats for integer and floating point numbers, that would add a unit prefix after the number (the unit itself, such as "B", would has to be included into the format string outside and just after of the "{}" placeholder). The usage would be like:
```cpp
fmt::print("{:.3?}B\n", 765432); // would produce "765.432 kB"
fmt::print("{:.2?}s\n", 1.342784e-9); // would produce "1.34 ns"
```
- Support three options: decimal prefixes (1024 -> "1.024 k"), binary prefixes with "i" (1024 -> "1.000 Ki") and binary prefixes without "i" (1024 -> "1.000 k")
- (maybe) Support short and long forms ("k" vs "kilo")
- An ability to specify alignment, width, and number of digits just like for integer/float numbers.

Alternatively, this would be implemented as a separate library on top of fmtlib, but since it is not possible to extend formats for built-in types, it would have to be a separate type:
```cpp
fmt::print("{:.3d}m\n", with_prefix{7.9864e-03}) // "7.986 mm"
```

**Comment by vitaut** [comment]
Thanks for the suggestion but the format string syntax for built-in types is pretty much fixed at this point. As you correctly point out it is possible to add units via wrapper types and the extension API.
