### ISSUE TITLE
Remove support for custom string-type from documentation

### ISSUE THREAD

**Issue by std-any-emplace** [fmtlib/fmt#2406]
As per https://fmt.dev/latest/api.html#_CPPv4I0_iEN3fmt14to_string_viewE17basic_string_viewI4CharEPK4Char custom string types are supported in v8.0.0.
#2405 was resolved as that being not the case anymore.

**Comment by vitaut** [comment]
Good catch, thanks.

**Comment by vitaut** [comment]
Removed the outdated apidoc in https://github.com/fmtlib/fmt/commit/5f8473914c6409cef62ec27f149bdde15e473298.
