### ISSUE TITLE
Formatting of std::filesystem::path stopped working in fmt 8.0

### ISSUE THREAD

**Issue by mikecrowe** [fmtlib/fmt#2409]
This code ([godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAFlJvoCqAZ0wAFAB4gA5AAYppAFZdSrZrVDIApACYAQjt2kR7ZATx1KmWugDCqVgFcAtrRDbSV9ABk8tTADlnACNMYi5eAAdUIUJzWjtHFzdSKJizOh8/QKcQsJ4jTBN02gYCZmICBOdXTgKiuNLygkyA4NDlITKKqqTazqaW7NyuAEojVAdiZA4pHQBmX2RHLABqTTmbKjx2IQBPTswndexNGQBBecXlzDWNqicCAHoaYidmAgA6BGPTi%2B0F2hLByrdabB6PCLEXwEKhfH7nX4AN1QeHQKyoEDQtE6K066BAIC2O32BEOBIi7wQa20ADYIiNfpoAOz6c4rdnoh7kqH0CA6bTM/RMgAimgArDZaPzSCt6etWWcOZyCNzoRj%2BToxUJxZLpbKGXMFczRQjztCVm9fBAGQiWb8lertNpHpgCMgIcwhEIAO7ofkGo0iqRjVjSMXyVyyeSoaQ2AwGXETKY3eaceQqqMjMYAaxAcwAnB989oZEynXMnfmmQAOMXuUNSbjyJxcGQyUiRuSkGNSeRCEDtjNyMZwWAwRAoVBOCLbULkShoaezsLAThrvjbUnEfsQILSLtBXzlXbSNOkRdOKwEADytFYJ6jpCwb3U7H38nwxEwpjwiMw/cfTBxG/BxSXfch6EKcDWDwIJiGPOwsHAggoRbKQ0zGfhGBYN98iw4QxEkR8lFqVR1BQeM9BUWD%2B1gWhmEvQkHlIP8whQhxaGzLNuwiYoAIAWjxdZhS0PQDBLFZ%2BOFe4CAAfXYzi%2B0Kb9iksawehqDxrEGNo8hSaJYjoDTlFSQzaB0nJ2j6ZSfzoRpunsaoOhs4p7OaXxWksvT%2BgcxJNJ89ysl00ZxkmaYQobcMO3AntxGrGl%2BJpbgVmAZBkBWNcPk4FYIFwQgSGpOZahWOwl3YYhCs4EYSso3R03fbjc20MUixkMUaTFIqaSZMVuBpNqaRUaQm1IFsxXbTto2kPsB1IIdg1IUcJwmAgIlA%2BdMSnGdyuUTB8CIPSsKYNgODwugCAIiRwO9eCIlPBbIojGLpGvUC1oIFZUCoFY4oSpKUrSjLOCynLSu20JKpGerMzGBBMGYLAwmtIbG2bEBxuix8exmwcGpzNwmQ%2BJkaWapkKxkat82LatiZRuYnqx6a5oaxbxyWiAkEXcGyAoTayvaVd1yJLcdz3R9D3o4gHzPC8r1ve9wOfNRgDfR9PxU39/3AoCQLAx9oSgx8YLghCMBmLsULwNCML4c7jtw3h8JEK7iOSMiNFq6igloqB6MYmSWPaKQmU4enuNQXi4gEoS5hE2qJKkmTZKZJT6gsCBPGM2pPAs4ZalM4os/0tI4lzqy6g1uyukqRzegr2ySmrsvvOrouAubkKhCTcKqpRqLJu7aRfsS5LUvSzLsty/aCtTGUweXQrtGquMxL0aHh3xisPi6pkZG4PrqxkbR4pRkaxom57eyMWb5pHNmkBW96Nq55dkj2/LDrtnDTsd87LqIrsN1mB3XQg9MMDMuw9leqtUCn1vrD3%2BmPIGIMIDz3KovKGzMYakDhgjdoyMGxn3RhfRmV9%2By42wbmLeO894HyPifBs9NMaQKZrfEM0htAQKmlfNhgdtxxBANwIAA%3D%3D)):
```
#include <filesystem>
#include <fmt/format.h>
#include <fmt/printf.h>

void f(const std::filesystem::path &p)
{
    fmt::print("{}\n", p);
    fmt::printf("%s\n", p);
}

int main()
{
    f("/etc/passwd");
}
```
compiles and runs successfully with fmt 7.1.3, but fails to compile with fmt 8.0.0 because it appears to want a custom formatter:
```
error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.
dev/latest/api.html#udt
```

This may be expected behaviour, but I couldn't find explicit mention of it anywhere in the 8.0.0 release notes.

**Comment by vitaut** [comment]
{fmt} never provided a formatter for `std::filesystem::path`. It probably worked by accident.

**Comment by mikecrowe** [comment]
It appears that `std::filesystem::path` has an `[operator string_type](https://en.cppreference.com/w/cpp/filesystem/path/native)` so it can be implicitly converted to a string. That operator will usually involve a copy so it's probably a good thing that it doesn't get used automatically now.

Since iostreams supports `std::filesystem::path`, would you look favourably upon a change that provided a formatter for `std::filesystem::path`? Perhaps in `fmt/filesystem.hpp` to mirror `fmt/chrono.h`?

**Comment by vitaut** [comment]
> Since iostreams supports std::filesystem::path, would you look favourably upon a change that provided a formatter for std::filesystem::path?

Sure.

> Perhaps in fmt/filesystem.hpp to mirror fmt/chrono.h?

I'd suggest puting formatters of standard library types in `fmt/std.h`.

**Comment by mikecrowe** [comment]
>> Perhaps in fmt/filesystem.hpp to mirror fmt/chrono.h?

> I'd suggest puting formatters of standard library types in fmt/std.h.

Do you mean:
1. Move the contents of `fmt/chrono.h` to `fmt/std.h` and add support for `std::filesystem::path` too.
2. Add `fmt/filesystem.h` with support for formatting `std::filesystem::path` and then invent `fmt/std.h` which includes both `fmt/chrono.h` and `fmt/filesystem.h`.
3. or something else?

(I think that I prefer option 2 since it means that people who want to minimise their build time have the option of avoiding including system headers that they don't need, but those that don't care can just include `fmt/std.h` and have everything work.)

**Comment by vitaut** [comment]
I meant adding new small standard formatters like the one for path to `fmt/std.h`. Chrono is big enough to deserve a separate header. I don't think we need a dedicated header for `filesystem`.

**Comment by mikecrowe** [comment]
OK. Although the `formatter for std::filesystem::path` and other standard types might be small, the <filesystem> and other headers that they will being in might not be. Nevertheless, I think that putting it in `fmt/std.h` is a good place to start. Thanks.

**Comment by ilyapopov** [comment]
The code already works if you add

```
#include <fmt/ostream.h>
```

**Comment by mikecrowe** [comment]
> The code already works if you add
> #include <fmt/ostream.h>

It does. The filename is passed through `std::quoted` so it gets extra quotes, but it always did previously. Having a dedicated formatter would allow that behaviour to be optional.
