### ISSUE TITLE
fmt part of std::lib?

### ISSUE THREAD

**Issue by VikingExplorer** [fmtlib/fmt#2411]
Given that fmt was incorporated into the C++ standard library, why would people continue to use this library?

https://en.cppreference.com/w/cpp/utility/format

Is it b/c it's going to take time to be available?   Only in msvc so far:  https://en.cppreference.com/w/cpp/compiler_support/20

**Comment by vitaut** [comment]
{fmt} provides a superset of functionality available in the standard: https://fmt.dev/latest/api.html. It's also compatible with C++11 while `std::format` will only be available starting from C++20.
