### ISSUE TITLE
There is no error if number of arguments is larger than number of format placeholders

### ISSUE THREAD

**Issue by ilyapopov** [fmtlib/fmt#2413]
With fmt 8.0.1, using C++17 and C++20 mode, the following code compiles and runs without exception:

```
fmt::print("{}\n", "foo", "bar");
```
Is this intended behavior?

**Comment by alexezeder** [comment]
This behavior is probably the most confusing one in {fmt}, but it's intended - https://github.com/fmtlib/fmt/issues/2048#issuecomment-738955343. The linked issue is about compile-time API, but there are some notes about runtime API too:
> It is intentional and consistent with runtime format, printf and std::format.

Maybe some additional functions can be added to the library to check the number of arguments. But actually, they can be added to the user code if needed.

There is a big advantage with this behavior though, you can pass all parameters that you have, while only those that you specified in format string would be printed:
```cpp
fmt::print("{a}{c}", "a"_a = "foo", "b"_a = 42, "c"_a = "bar");
```

**Comment by ilyapopov** [comment]
Thanks for pointing me to that comment. Indeed this makes sense.
