### ISSUE TITLE
Deprecated format_to memory_buffer overload: Please reconsider or provide alternative

### ISSUE THREAD

**Issue by Dani-Hub** [fmtlib/fmt#2420]
Since fmtlib 8 the following overload provided in `format.h` is deprecated:
```
template <typename... T, size_t SIZE, typename Allocator>
FMT_DEPRECATED auto format_to(basic_memory_buffer<char, SIZE, Allocator>& buf,
                              format_string<T...> fmt, T&&... args)
    -> appender;
```
It would be appreciated, if this deprecation could be either rethought or at least the code docs (e.g. of class template `basic_memory_buffer`) that still use this usage as example should be adjusted and a recommended replacement should be mentioned.

I tested as replacement for
```
fmt::memory_buffer buffer;
fmt::format_to(buffer, "{0} {1}", "Hello", "world");
```
the alternative
```
fmt::memory_buffer buffer;
fmt::format_to(std::back_inserter(buffer), "{0} {1}", "Hello", "world");
```
which works but leads to performance losses (measured via benchmark) of about 5% in release (and ~10% in debug) builds.

We use the now deprecated overload a lot in low-level functions where we still want to get compile-time validation (So vformat is not an alternative) and would like to keep the previous performance characteristics. 

Assuming that the idea behind the deprecation is to prevent problems compared to std::format_to, would it be possible to provide a differently named overload or within an additionally nested namespace? Note that providing such an overload by user-code is not only an unnecessary burden, but also not actually safe to do, because the deprecated overload delegates to `detail::vformat_to`, which is non-public API.

**Comment by vitaut** [comment]
Thanks for the suggestion but there are no plans to bring the deprecated overload back because passing `back_insert_iterator` or `appender` should be equivalent, but with clearer intent. A PR to address a regression if any would be welcome.

**Comment by Dani-Hub** [comment]
I'm surprised that this issue is closed without any action taken or even considered. Note that the issue discussion points out that the current documentation provides an example, that is now deprecated starting with fmtlib 8. The minimum that should be done as part of this issue is to fix the provided code doc of class template `basic_memory_buffer`.

**Comment by vitaut** [comment]
Reopening to update the docs.

**Comment by Dani-Hub** [comment]
Btw.: Thanks for the hint regarding `appender`: I just benchmarked it as replacement and would strongly suggest to mention in the docs the usage of `appender` instead of `std::backinserter`: I observed in release builds no observable difference and in debug builds a much less of regression.

**Comment by vitaut** [comment]
In principle there shouldn't be any difference between `appender` and `back_insert_iterator` but there could be some missed optimization at the moment.

**Comment by vitaut** [comment]
Updated examples to not use the deprecated API in https://github.com/fmtlib/fmt/commit/e41ac1f875b7a1c419beaf7ddf431a01fb530a92. Thanks for catching this.

**Comment by Dani-Hub** [comment]
Thanks for the fix, Victor! I should presumably open an improvement request regarding the noticable performance regression when switching to `std::back_inserter` usage (at least for Visual Studio, I didn't test other compilers yet), but let's keep that separate.
