### ISSUE TITLE
Compile failure with clang and c++20

### ISSUE THREAD

**Issue by lemourin** [fmtlib/fmt#2421]
Consider:
```
#include <fmt/format.h>
#include <string_view>

const std::string_view kFormatString;

int main() {
  fmt::format(kFormatString);
}
```

With clang 12.0.1 with fmtlib 8.0.1 this fails to compile with the following error:

```
clang++ test.cc -o test -lfmt -std=c++20
```

```
test.cc:7:15: error: call to consteval function 'fmt::basic_format_string<char>::basic_format_string<std::basic_string_view<char>, 0>' is not a constant expression
  fmt::format(kFormatString);
              ^
/usr/include/fmt/core.h:2839:56: note: read of non-constexpr variable 'kFormatString' is not allowed in a constant expression
  FMT_CONSTEVAL basic_format_string(const S& s) : str_(s) {
                                                       ^
/usr/include/fmt/core.h:2839:56: note: in call to 'basic_string_view(kFormatString)'
test.cc:7:15: note: in call to 'basic_format_string(kFormatString)'
  fmt::format(kFormatString);
              ^
test.cc:4:24: note: declared here
const std::string_view kFormatString;
                       ^
1 error generated.
```

* g++ 11.1.0 outputs a similar error
* fmtlib 7.1.3 works fine
* with std=c++17 fmtlib 8.0.1 works fine

**Comment by vitaut** [comment]
This is expected, format string must be known at compile time. To fix it make the string constexpr:

```c++
#include <fmt/format.h>
#include <string_view>

constexpr std::string_view kFormatString;

int main() {
  fmt::format(kFormatString);
}
```
or wrap in `fmt::runtime`.

**Comment by KambizAsadzadeh** [comment]
> This is expected, format string must be known at compile time. To fix it make the string constexpr:
> 
> ```c++
> #include <fmt/format.h>
> #include <string_view>
> 
> constexpr std::string_view kFormatString;
> 
> int main() {
>   fmt::format(kFormatString);
> }
> ```
> 
> or wrap in `fmt::runtime`.

As you know we can't use constexpr variables in function parameter.
But I need use function parameters from other json files;

**Example :** 
```
void functionTest(std::string_view content, const std::string& value) {
  return fmt::format(content, value);
}
```
What can I do?
