### ISSUE TITLE
How to install only the header-only version of fmt?

### ISSUE THREAD

**Issue by derived-coder** [fmtlib/fmt#2422]
Hi, I would like to build and install only the header only version of fmt.
But I cannot find a way to achieve this, I will get a bunch of include and also a static library installed (linux). but I do not want this.

How can I configure the project so:
That the installation will give me **One** header file and a cmake package config, which I can use to find and link against this header file?

FYI: Other libraries are using some post processing step in order to generate this big header file.

**Comment by vitaut** [comment]
Header-only applies to usage only not installation. You can ignore the installed library or remove it as a post-installation step. There is no way to merge headers either.

**Comment by derived-coder** [comment]
@vitaut 
Okay, then I would like to have this feature implemented.
