### ISSUE TITLE
How to log queue and map ?

### ISSUE THREAD

**Issue by shipleyxie** [fmtlib/fmt#2423]
You can log vector by include #include <fmt/ranges.h>, but can't log queue and map.
Could you please give me some suggestion how to achieve that ?

**Comment by vitaut** [comment]
You can format a map (https://godbolt.org/z/q1xT9178E):

```c++
#include <fmt/ranges.h>
#include <map>

int main() {
  auto m = std::map<int, int>();
  m[1] = 2;
  fmt::print("{}", m);
}
```

but not queue because the latter doesn't provide begin/end. You could use the extension API to write a formatter for queue: https://fmt.dev/latest/api.html#formatting-user-defined-types.
