### ISSUE TITLE
std::bad_alloc on date/time formatting

### ISSUE THREAD

**Issue by lkeegan** [fmtlib/fmt#2424]
On msys2 the following throws a `std::bad_alloc` exception ([example](https://github.com/lkeegan/fmt/commit/1e7e776dda88899bfb2cf497a62d75cd9b60e0a9), [msys2 ci output](https://github.com/lkeegan/fmt/runs/3074411247?check_suite_focus=true#step:4:151)):
```
auto t1 = std::chrono::system_clock::now();
fmt::format("{:%F %T}", t1)
```
The cause is that `%F` and `%T` are not supported by the underlying `strftime` implementation and it just returns an empty string, which fmt interprets as the buffer being too small, so it allocates more memory and repeats until the system runs out of memory. (looks like the same issue as https://github.com/fmtlib/fmt/issues/367)

Previously fmt had a heuristic to avoid this (https://github.com/fmtlib/fmt/commit/a5d0adf3953f0ae3e698d5b5702d1e5a7bf3d87e),
which was replaced with a nice solution that (tried to) guarantee a non-empty result from `strftime` (https://github.com/fmtlib/fmt/pull/2244), but apparently an empty result is still possible.

Maybe an upper bound on the memory allocated could be added, or the heuristic could be re-instated?

**Comment by vitaut** [comment]
This is clearly a bug in the `strftime` implementation, please report to the relevant project (msys?). I don't think we should reintroduce the heuristic but we could parse the format string ourselves and reject problematic specifiers as a workaround. A PR would be welcome.

**Comment by vitaut** [comment]
We no longer use `strftime` so the issue should be resolved.

**Comment by lkeegan** [comment]
That's great - thanks!
