### ISSUE TITLE
Custom OutputIterator, bulk copy optimization

### ISSUE THREAD

**Issue by IndianBoy42** [fmtlib/fmt#2430]
I want to make format_to work with a custom OutputIterator, which is a wrapper over a Serial port. such that `*out++ = byte` will start sending that byte over the serial port, something like `port->send(byte)`. This would technically work byte by byte as shown above. However we can get much more efficiency by sending an array at a time `port->send(bytes, len)`. One way would be to use `format_to` into a `uint8_t[N]` or even a vector back inserter, and then send from that buffer, but that would require me to allocate another intermediate buffer. This would be particularly bad as I am trying to make this work on an embedded microcontroller, where we would like to use malloc as little as possible. 

So my question is, is there some specialization (of std::memcpy or std::copy) that I could provide for my custom SerialOutputIterator, such that fmtlib will be able to use it rather than outputting byte by byte. 

Another usecase would be if I were trying to format_to a [circular buffer](https://embeddedartistry.com/blog/2017/05/17/creating-a-circular-buffer-in-c-and-c/). If you push to a circular buffer byte by byte, you will end up checking for the wrapping condition every single byte. On the other hand, if you push a whole array at once to the circular buffer, you can optimize that to one check for wrapping and 2 memcpys, which significantly more efficient

**Comment by vitaut** [comment]
> is there some specialization (of std::memcpy or std::copy) that I could provide for my custom SerialOutputIterator, such that fmtlib will be able to use it rather than outputting byte by byte.

There is none but if you are OK with using internal APIs you could use https://github.com/fmtlib/fmt/blob/561834650aa77ba37b15f7e5c9d5726be5127df9/include/fmt/core.h#L749

which gives control over buffering. Here's an example similar to your serial port use case but for writing into a file: https://github.com/fmtlib/fmt/blob/561834650aa77ba37b15f7e5c9d5726be5127df9/include/fmt/os.h#L400
