### ISSUE TITLE
Support flush() on ostream.

### ISSUE THREAD

**Issue by pikapi12321** [fmtlib/fmt#2435]
I noticed that flush() is a private member of ostream and cannot be called outside. I don't understand why it is designed to be private.

**Comment by vitaut** [comment]
A PR to make `flush` public is welcome.

**Comment by vitaut** [comment]
Made flush public in https://github.com/fmtlib/fmt/commit/bba0a9d9623c88ac0bdee34302651d51ac289c5f. Thanks for the suggestion.

**Comment by pikapi12321** [comment]
> Made flush public in [bba0a9d](https://github.com/fmtlib/fmt/commit/bba0a9d9623c88ac0bdee34302651d51ac289c5f). Thanks for the suggestion.

I've tried public flush() in my project's logger. It seems that flush() is not safe if another thread is constantly calling ostream::print() on the same ostream object. My debug build ran ok while my release build encountered segmentation fault. Problem went away after I removed my flushes.

**Comment by vitaut** [comment]
`ostream` is not thread-safe as mentioned in the docs: https://fmt.dev/latest/api.html#os-api. If you want to write from multiple threads you should use a different API or add synchronization.

**Comment by bl-ue** [comment]
Hey @vitaut! v8.0.1 was released a month before this feature...will you please consider cutting a new release?
