### ISSUE TITLE
Deprecated format_to(memory_buffer,...) in docs

### ISSUE THREAD

**Issue by gummif** [fmtlib/fmt#2436]
The format_to function taking a memory_buffer is deprecated, but it is unclear from the code/docs how it should be used, e.g. from the docs:
```c++
fmt::memory_buffer out;
fmt::format_to(out, "The answer is {}.", 42);
```
Which (I think) should be
```c++
fmt::memory_buffer out;
fmt::format_to(fmt::appender(out), "The answer is {}.", 42);
```
using the undocumented appender type. Is this correct?

**Comment by vitaut** [comment]
Thanks for reporting but this is already fixed in the latest docs: https://fmt.dev/dev/api.html (#2420).
