### ISSUE TITLE
Consteval error on C++20

### ISSUE THREAD

**Issue by KambizAsadzadeh** [fmtlib/fmt#2438]
Hi, 
As you know we can't use **constexpr** variables in function parameter.
But I need use function parameters from other json files.

**Example :**
```
std::string functionTest(std::string_view content, const std::string& value) {
  return fmt::format(content, value);//Error on compile time :)
}
std::cout << functionTest("The answer is {number}",  10);
```
How can I solve this problem?

**Error:**
```
error: call to consteval function 'fmt::basic_format_string<char, std::string>::basic_format_string<std::string, 0>' is not a constant expression
error: call to consteval function 'fmt::basic_format_string<char, std::string>::basic_format_string<std::string, 0>' is not a constant expression
  return fmt::format(text, val);
                     ^
note: non-literal type 'std::string' (aka 'basic_string<char>') cannot be used in a constant expression
```

**Comment by vitaut** [comment]
You can wrap the format string in `fmt::runtime` to disable compile-time checks:

```c++
std::string functionTest(std::string_view content, const std::string& value) {
  return fmt::format(fmt::runtime(content), value);
}
```
or pass it as `format_string` as {fmt} does.

**Comment by KambizAsadzadeh** [comment]
> You can wrap the format string in `fmt::runtime` to disable compile-time checks:
> 
> ```c++
> std::string functionTest(std::string_view content, const std::string& value) {
>   return fmt::format(fmt::runtime(content), value);
> }
> ```
> 
> or pass it as `format_string` as {fmt} does.

Thanks for your attention! @vitaut :)
