### ISSUE TITLE
Broken support for printing abstract classes with ostream adapter

### ISSUE THREAD

**Issue by PiotrZSL** [fmtlib/fmt#2439]
ENV: GCC 10 + FMT 8.0.1 (master) + FMT_COMPILE + fmt::format_to + reference to abstract class as argument.
Abstract class got friend operator <<.

Result: Compilation fails.
Issue looks to be caused by std::numeric_limits.
Fails with: limits:317:7: error: invalid abstract return type ‘<class name here>'.

Workaround:
format.h (ignored is_fast_float for classes) 
```
 567 template<typename T, bool = std::is_class<T>::value>
 568 struct Workaround : std::false_type
 569 {
 570 };
 571
 572 template<typename T>
 573 struct Workaround<T, false> : bool_constant<std::numeric_limits<T>::is_iec559 && sizeof(T) <= sizeof(double)>
 574 {
 575
 576 };
 577
 578 template <typename T>
 579 using is_fast_float = Workaround<T>;
```
ostream.h (added & to std::declval to create reference to type instead of rvalue).
```
 75 template <typename T, typename Char> class is_streamable {
 76  private:
 77   template <typename U>
 78   static bool_constant<!std::is_same<decltype(std::declval<test_stream<Char>&>()
 79                                               << std::declval<U&>()),
 80                                      void_t<>>::value>
```

**Comment by vitaut** [comment]
Please provide a repro.

**Comment by PiotrZSL** [comment]
Example:
```
#include <fmt/format.h>
#include <fmt/compile.h>
#include <fmt/ostream.h>

struct Abstract
{
    virtual ~Abstract() = default;
    virtual void print() = 0;
    friend std::ostream& operator<<(std::ostream& out, Abstract&);
};


void testFail(Abstract& value)
{
    fmt::memory_buffer buf;
    fmt::format_to(std::back_inserter(buf), FMT_COMPILE("{}"), value);
}
```

**Comment by vitaut** [comment]
Could you submit a PR by any chance?

**Comment by PiotrZSL** [comment]
> Could you submit a PR by any chance?
PR ? Could you elaborate ?

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/ee0659f8b6dafa84f90576ae85adc77c20517286. With this change your example compiles (with a missing const added). Thanks for reporting.
