### ISSUE TITLE
How do I format an array pointer?

### ISSUE THREAD

**Issue by 123qws** [fmtlib/fmt#2445]
It's great that fmt can format a vector, but the code below didn't compile if formating a C array pointer: https://godbolt.org/z/fjnvfE8fa

What's the simplest workaround?

**Comment by vitaut** [comment]
You can do it with `fmt::join` (https://godbolt.org/z/MKKzTxGf4):

```c++
#include <vector>
#include <fmt/ranges.h>

int main() {
  std::vector<int> v = {1, 2, 3};
  int v2[3] = {1,2,3};
  fmt::print("{}\n", fmt::join(v2, " "));
}
```

**Comment by 123qws** [comment]
Thanks!
