### ISSUE TITLE
Using CMAKE with CMAKE_CXX_STANDARD 20 stops any output from working. 

### ISSUE THREAD

**Issue by ifamakes** [fmtlib/fmt#2448]
After compiling as C++20 and including as a library in my C++20 project, including any of the fmt headers stops std::cout, printf, fmt::print, etc from outputting everything. commenting out the include allows output from the std library again, but fmt doesn't work.

**Comment by ifamakes** [comment]
I'm dumb and forgot to include the library file in my build dir.

**Comment by vitaut** [comment]
No worries, glad the problem is resolved.
