### ISSUE TITLE
False negative is_streamable as test_stream causes client code's constraint check to fail on templated operator<<

### ISSUE THREAD

**Issue by VaderY** [fmtlib/fmt#2449]
Hello,

I ran into a seemingly false negative `fmt::v8::detail::is_streamable` result in the following scenario which blocks fmt format/print usages with some type:

Some type might prefer templated `operator<<` implementation (ostream header independency, compile time saving, more optimization opportunity, devirtualization, better or custom stream type supports, etc...) like this:
```C++
struct SomeType {
	template <typename OStream> 
	friend OStream& operator<<(OStream& os, const SomeType& var) { ... }
};
```

But if such a type has a conditional `operator<<` (which is usually a useful thing for wrapper types) then `fmt::v8::detail::is_streamable` rejects the type
```C++
template <typename T>
struct SomeWrapperType {
	template <typename OStream>
		requires is_ostreamable<OStream, T>
	friend OStream& operator<<(OStream& os, const SomeWrapperType& var) { ... }
};
```

From what I understand the rejection occurs because the `operator<<` can be called with `test_stream` and not just with `std::ostream` and `test_stream` has disabled its `operator<<` so the client side constraint fail, which disables the overload, which sets is_streamable to false.

My question is why does `fmt::v8::detail::is_streamable<T, Char>` uses `fmt::v8::detail::test_stream<char>`  for testing? The related code has a comment "Checks if T has a user-defined operator<< (e.g. not a member of std::ostream)" but beyond that I cannot reason about why is this necessary. Otherwise a simple change of would allow SomeWrapperType to be usable:
```
...std::declval<test_stream<Char>&>() << std::declval<U>()... // from this
...std::declval<std::basic_ostream<Char>&>() << std::declval<U>()... // to this
```

It is likely that I am missing some crucial information or some corner case, but if I am right this change would useful.

Repo in godbolt [https://godbolt.org/z/PvYaqGjns](https://godbolt.org/z/PvYaqGjns)

**Comment by vitaut** [comment]
> My question is why does fmt::v8::detail::is_streamable<T, Char> uses fmt::v8::detail::test_stream<char> for testing?

`test_stream` is used to disable problematic `operator<<` overloads of built-in and standard library types.

The `ostream` compatibility layer is inherently limited and not very efficient. I would recommend providing a `formatter` specializations for `SomeWrapperType` instead.
