### ISSUE TITLE
fmt::join tuple does not support format specifiers

### ISSUE THREAD

**Issue by cgmb** [fmtlib/fmt#2451]
Using fmt 8.0.1:
```
#include <tuple>
#include <vector>
#include <fmt/format.h>
#include <fmt/ranges.h>

int main() {
  std::vector<int> a = { 1, 2, 3 };
  fmt::print("{:02}\n", fmt::join(a, ", "));

  std::tuple<int,int,int> b = std::make_tuple(1, 2, 3);
  fmt::print("{:02}\n", fmt::join(b, ", "));
}
```
Results in:
```
01, 02, 03
terminate called after throwing an instance of 'fmt::v8::format_error'
  what():  unknown format specifier
Aborted (core dumped)
```

When using `fmt::join`, I'd expect the given format specifier to be applied to each element in the tuple. An exception would only be thrown if the format specifier didn't make sense for one of the tuple's types.

**Comment by vitaut** [comment]
> I'd expect the given format specifier to be applied to each element in the tuple. An exception would only be thrown if the format specifier didn't make sense for one of the tuple's types.

That's an interesting idea. A PR would be welcome.
