### ISSUE TITLE
{fmt} 8 fails to format pointer types with formatter specializations

### ISSUE THREAD

**Issue by dominiklohmann** [fmtlib/fmt#2452]
Here's an example that works with {fmt} 7, but fails with {fmt} 8 ([godbolt](https://godbolt.org/z/7ba43Wfe3)):

```c++
#include <fmt/format.h>

struct X {};

template <>
struct fmt::formatter<X*> : fmt::formatter<std::string_view>
{
    template <class FormatContext>
    auto format(const X* value, FormatContext& ctx) -> decltype(ctx.out()) {
        return format_to(ctx.out(), "X*");
    }
};

int main() {
    X x;
    fmt::print("{}", &x);
}
```

This used to work with {fmt} 7, which did not complain about not being able to format pointer types if a formatter specialization for the pointer type existed.

I know this is kind of abusing the library, but this took me a while to figure out, so it'd be awesome to see this either fixed or clearly documented as a breaking change in the changelog.

**Comment by vitaut** [comment]
It happened to work by accident in earlier versions, I added an item to the changelog clarifying that it's not supported: https://github.com/fmtlib/fmt/commit/c2ed5f6863e05afc44ace43184f0024fed9e18ce. Thanks for the suggestion.
