### ISSUE TITLE
//usr/local/lib/libfmt.a(format.cc.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by RENyunfan** [fmtlib/fmt#2456]
I try to compile my work with cmake, but get errors below
```
/usr/bin/ld: //usr/local/lib/libfmt.a(format.cc.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC

```

I have added -fPIC in my CMakeLists like
```CMake
add_compile_options(-fPIC)
# or 
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
```

But no help. Any idea?

**Comment by vitaut** [comment]
Same as #548. You can build with [CMAKE_POSITION_INDEPENDENT_CODE](https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html).

**Comment by Cheaterman** [comment]
> Same as #548. You can build with [CMAKE_POSITION_INDEPENDENT_CODE](https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html).

Perhaps do this by default if _everyone_ is complaining...
