### ISSUE TITLE
fmt::format doesn't work with runtime non-char format strings

### ISSUE THREAD

**Issue by Boddlnagg** [fmtlib/fmt#2458]
I would expect the following to work:
```c++
#include "fmt/format.h"
#include "fmt/xchar.h"

int main() {
  return fmt::format(fmt::runtime(L"Hello, {}!"), L"world") == L"Hello, world!";
}
```

But it does not compile.
It seems to be failing to find the correct overload for `fmt::format` (from xchar.h) that goes with `basic_format_string<wchar_t>`.

The version without the `fmt::runtime` works correctly, but I need runtime-dynamic format strings to work for `wchar_t` and `char16_t`.

**Comment by vitaut** [comment]
Compile-time checks are not supported for wide strings so `fmt::runtime` doesn't make sense there.

**Comment by Boddlnagg** [comment]
Oh, that is sad, that compile-time checks are not supported for `wchar_t`/`char16_t` ... is is planned for the future?

**Comment by vitaut** [comment]
> is is planned for the future?

Yes
