### ISSUE TITLE
Missing runtime fmt_compile

### ISSUE THREAD

**Issue by mheiskan** [fmtlib/fmt#2460]
I tried to search the documentation well enough, but could not find out why a runtime format string parser is missing. In particular, if I want to print say a million doubles according to user settings, I'd have to generate the format string, which means the format string cannot be parsed at compile time. However, now the generated string has to be parsed a million times instead of just once to print a million doubles. According to perf the parsing takes much longer than the actual printing.

**Comment by mheiskan** [comment]
Oh, stupid me not assigning the result.

**Comment by mheiskan** [comment]
No, I misunderstood everything again. Reopening.

**Comment by vitaut** [comment]
If you mean format string compilation at runtime then it proved not to be particularly effective and has been removed in favor of compile-time format string compilation. Note that format string parsing has opportunities for optimizations and PRs would be welcome.
