### ISSUE TITLE
fmt::format_to_n for printf-like 

### ISSUE THREAD

**Issue by Roman-Koshelev** [fmtlib/fmt#2464]
For `fmt::format` is `fmt::sprintf`. But what about `fmt::format_to_n`?

**Comment by vitaut** [comment]
{fmt} doesn't provide a `format_to_n` equivalent for legacy `printf` but you can use `fmt::sprintf` and truncate.

**Comment by Roman-Koshelev** [comment]
But I don't need an extra dynamic alocation. Why not do it for the symmetry of the interface?

**Comment by vitaut** [comment]
There is little reason to do that because you could just use `snprintf` but a PR would be welcome.
