### ISSUE TITLE
[Question] How to print non-char basic_strings?

### ISSUE THREAD

**Issue by vatosarmat** [fmtlib/fmt#2466]
I am working with `poppler` library which uses `std::basic_string<unsigned short>`. How should I print such strings using `fmt`?
I see `char` is hardcoded in print function 😕 
`FMT_INLINE void print(format_string<T...> fmt, T&&... args)`  
`using format_string = basic_format_string<char, type_identity_t<Args>...>;`

**Comment by OnurKader** [comment]
Maybe something like:

```cpp
std::basic_string<unsigned short> data{1, 2, 3, 4, 5, 6};
fmt::print("Span: {}\n", std::span{data});
fmt::print("Join: {}\n", fmt::join(data, ", "));
```

[godbolt](https://godbolt.org/z/nMf1crxPP)
