### ISSUE TITLE
format string incompatible with data from struct with __attribute__((packed))

### ISSUE THREAD

**Issue by rudolpjo** [fmtlib/fmt#2468]
Can this be supported?
```
#include <fmt/core.h>

struct __attribute__((packed)) Foo
{
    uint8_t baz;
    uint32_t bar;
}

int main()
{
    Foo foo;
    foo.bar = 42;
    // This line will fail compilation with the error:
    // error: cannot bind packed field 'Foo::bar' to 'unsigned int&'
    std::string s = fmt::format("Hello {}", foo.bar);
    return 0;
}
```

**Comment by lefebvresam** [comment]
What is the meaning of the + in this case?

**Comment by vitaut** [comment]
`+` makes it into an expression that has a proper (unpacked) integer type

**Comment by lefebvresam** [comment]
I was searching on the internet about a good description about this. Do you have a valuable link?

**Comment by mwinterb** [comment]
> I was searching on the internet about a good description about this. Do you have a valuable link?

It's unary plus: https://learn.microsoft.com/en-us/cpp/cpp/unary-plus-and-negation-operators-plus-and?view=msvc-170, https://en.cppreference.com/w/cpp/language/operator_arithmetic#Unary_arithmetic_operators

**Comment by lefebvresam** [comment]
And is this anywhere described to use this operator for std::format to unpack?

**Comment by vitaut** [comment]
Not that I'm aware of. We should probably add it to the docs.

**Comment by vitaut** [comment]
Added a small section to the docs: https://fmt.dev/dev/api/#bit-fields-and-packed-structs
