### ISSUE TITLE
Error compiling with C++20

### ISSUE THREAD

**Issue by dmarian** [fmtlib/fmt#2473]
The following code compiles with C++17 but does not compile with C++20 using GCC 11.2.1:
```
#include <iostream>
#include <fmt/format.h>

void message (std::string msg) {
  std::cout << msg << std::endl;
}

void message(std::string format, const auto & ... args) {
  message(fmt::format (format, args...));
}

int main() {
  std::string something = "1, 2, 3";
  message ("Testing {}.", something);
}
```
To make it work, from `fmt/core.h`, in line 2928 I removed the FMT_CONSTEVAL macro.
I have fmt up to commit 74c1118964d0d943535c03d6c4e6f2d1449b61d6.

**Comment by vitaut** [comment]
That's expected. A format string should be known at compile time and if you want to pass a runtime string wrap it in `std::runtime`: https://github.com/fmtlib/fmt/releases/tag/8.0.0.
