### ISSUE TITLE
g++-10 compilation error when including fmt/ostream.h

### ISSUE THREAD

**Issue by MichaelTrikergiotis** [fmtlib/fmt#2479]
Including the `fmt/ostream.h` header when using `g++-10` with  `-std=c++20`, stops compilation with an error.

The issue doesn't exist with `clang 12` or the latest `MSVC`.

**compiler** : `g++ 10.3.0` with `-std=c++20`
**OS** : `Ubuntu 21.04`
**fmt** : `8.0.1`

The issue also exists in `fmt 8.0`.
This issue doesn't exist in `fmt 7.1.3`.

Working example :
```c++
#define FMT_HEADER_ONLY 
#include "fmt/core.h"

int main()
{
	fmt::print("Works.\n");
}
```
The above compiled with `g++-10 -std=c++20` with no problems.

Not working example, with link to godbolt : https://gcc.godbolt.org/z/7n6hPsdj8 :
```c++
#define FMT_HEADER_ONLY 
#include "fmt/core.h"
#include "fmt/ostream.h"

int main()
{
	fmt::print("Doesn't work.\n");
}
```
Trying to compile with `g++-10 -std=c++20`  :

```
In file included from bad.cpp:3:
fmt/ostream.h:123:8: error: partial specialization of ‘struct fmt::v8::detail::fallback_formatter<T, Char, typename std::enable_if<fmt::v8::detail::is_streamable<T, Char>::value, void>::type>’ after instantiation of ‘struct fmt::v8::detail::fallback_formatter<char [7], char, void>’ [-fpermissive]
  123 | struct fallback_formatter<T, Char, enable_if_t<is_streamable<T, Char>::value>>
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fmt/ostream.h:123:8: error: partial specialization of ‘struct fmt::v8::detail::fallback_formatter<T, Char, typename std::enable_if<fmt::v8::detail::is_streamable<T, Char>::value, void>::type>’ after instantiation of ‘struct fmt::v8::detail::fallback_formatter<char [3], char, void>’ [-fpermissive]
fmt/ostream.h:123:8: error: partial specialization of ‘struct fmt::v8::detail::fallback_formatter<T, Char, typename std::enable_if<fmt::v8::detail::is_streamable<T, Char>::value, void>::type>’ after instantiation of ‘struct fmt::v8::detail::fallback_formatter<char [1], char, void>’ [-fpermissive]
```

**Comment by OnurKader** [comment]
Removing the header only macro seems to fix the issue (I hope header only is not mandatory).

[godbolt](https://gcc.godbolt.org/z/4T9hEEYjn)

**Comment by MichaelTrikergiotis** [comment]
I need `fmt` in header only mode so removing the `#define FMT_HEADER_ONLY` macro is not possible for me.
The code in the post is just the smallest possible repro, and so I have included the macro on purpose.

**Comment by sunmy2019** [comment]
It is a design defect. To solve this, we need to reorganized the code.

```cpp
#include "fmt/core.h"
#include "fmt/ostream.h"

// this file should be the last, but it is now included in the `core.h`
#include "fmt/format-inl.h"
```

**Comment by sunmy2019** [comment]
A temporary fix would be https://gcc.godbolt.org/z/xn3YenGxe
```cpp
#include <fmt/core.h>
#include <fmt/ostream.h>
#define FMT_HEADER_ONLY
#undef FMT_FUNC
#define FMT_FUNC inline
#include <fmt/format-inl.h>

int main() {
  fmt::print("Doesn't work.\n");
}
```

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/20931baf1db555105c77aba5ae80aac51197f91c. Thanks for reporting!
