### ISSUE TITLE
A few functions in ranges.h need inlining

### ISSUE THREAD

**Issue by palacaze** [fmtlib/fmt#2481]
Recent changes in ranges.h introduced non-templated functions that are not inlined, thus breaking the ODR and triggering compilation errors.

**Comment by vitaut** [comment]
Please provide more details and ideally a repro.

**Comment by palacaze** [comment]
Sure, I created a test then the corresponding fix here https://github.com/palacaze/fmt/tree/ranges-odr

**Comment by vitaut** [comment]
Could you submit a PR with the fix since you already have one?

**Comment by palacaze** [comment]
Would you prefer a PR with only the fix or also the accompanying testcase?

**Comment by vitaut** [comment]
Test would be great, thank you!
