### ISSUE TITLE
has_formatter vs is_const_formattable

### ISSUE THREAD

**Issue by 3y3p4tch** [fmtlib/fmt#2485]
Hi,

I am trying to understand the codebase and I am struck at how `has_formatter` and `is_const_formattable` are different in their use cases (considering that we are trying to format a const type), how are they handled in `arg_mapper`, how it is related to implicit conversions and how exactly are implicit conversions handled.

What we want from a formatter for it to be able to format a data type is the `format` member function and `is_const_formattable` does exactly that, then why is `has_formatter` relevant? why can't `has_formatter` be replaced with `is_formattable` (as #2226 was trying to do)

Some insights from the devs would be appreciated
Thanks

**Comment by vitaut** [comment]
`has_formatter` and `is_const_formattable` are internal traits. The former checks if a type has a formatter specialization while the latter checks if a type's formatter doesn't mutate its argument.

`is_formattable` on the other hand is intended for users to check if a type is formattable.
