### ISSUE TITLE
fmt does not support filesystem on windows and caurse wield errors. 

### ISSUE THREAD

**Issue by cagev** [fmtlib/fmt#2486]
I'm using  fmt-8.0.1  and   spdlog  1.9.2 
on vs 2019 , version 16.11.2  with c++17 

#define DLOG(...) spdlog::debug(__VA_ARGS__)        

    DLOG("current path is {}", fs::current_path().c_str() );

will caurse erros: 

    严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2338	formatting of non-void pointers is disallowed	trade	D:\work\td\opt\fmt-8.0.1\include\fmt\core.h	1308	

if I change code to  
   DLOG("current path is {}", fs::current_path());

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2338	Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt	trade	D:\work\td\opt\fmt-8.0.1\include\fmt\core.h	1568	

should I use ? 
       DLOG("current path is {}", fs::current_path().string()); //works ok 

and all compile errors above  didn't show the line number of user's code , it's hard to location the error code . 

but all is ok on linux with gcc 8.x

**Comment by Brainy0207** [comment]
You are mixing wide and single byte characters.
filesystem::path is wstring (or wchar_t) under windows.
