### ISSUE TITLE
`format`-family methods should accept `args` as const references

### ISSUE THREAD

**Issue by 0x804d8000** [fmtlib/fmt#2487]
#2462 fixed an inconsistency between signatures of `format`-family methods, in a way that now all of them accept `args` as universal references. 

Unfortunately, universal references are not quite "universal" in that they can't be bound to bit fields, e.g.:

```cpp
struct C {
  int f : 1;
};

C c = {.f = 1};

void foo() {
  char buf[10];
  format_to_n(buf, 10, "{}", c.f);  // Compiles before #2462, no longer compiles now.
}
```

This might be a long-standing issue with `format` and `format_to`, I suppose.

To fix this, I suggest that we should instead accept `args` as const references for all of `format`-family methods.

**Comment by ethanvc** [comment]
人家才统一改成 universal referenece，你就来拆台了。

**Comment by 0x804d8000** [comment]
Thanks for mentioning P2418, I wasn't aware of it.
