### ISSUE TITLE
Formatting recursive types with latest fmt

### ISSUE THREAD

**Issue by jcelerier** [fmtlib/fmt#2488]
Hello,
I am updating fmt to the latest version and it seems that the consteval checks have issues with recursive types.

That is, here is a minimal version of my type:

```
struct value;
using variant = std::variant<std::vector<value>>;
struct value
{
  variant val;
};
```

And the error in godbolt: https://godbolt.org/z/nsboEn773

This worked previously.

I've tried:
- moving all the fmt::formatter function definitions out of the class bodies
- adding fmt::runtime calls to every format strings

but neither make the build pass :(

**Comment by jcelerier** [comment]
I can make it pass if I detemplatize stuff and use the explicit types if that can help

https://godbolt.org/z/xrPWv8d5K

**Comment by vitaut** [comment]
One problem is missing return in `std::visit`:

```c++
    return std::visit([&] (const auto& value) {
      return format_to(ctx.out(), "value: {}", value);
    }, v.val);
```

However, fixing it still gives an error:

```

 error: 'constexpr fmt::v8::detail::format_string_checker<Char, ErrorHandler, Args>::format_string_checker(fmt::v8::basic_string_view<Char>, ErrorHandler) [with Char = char; ErrorHandler = fmt::v8::detail::error_handler; Args = {value}]' called in a constant expression before its definition is complete
|       format_to(ctx.out(), "list: {}", val);
|       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I guess the problem is that one formatter specialization is defined in terms of the other leading to an infinite template instantiation recursion somewhere. I haven't digged into it yet.

**Comment by sunmy2019** [comment]
> I guess the problem is that one formatter specialization is defined in terms of the other leading to an infinite template instantiation recursion somewhere. I haven't digged into it yet.

The constexpr constructor of `format_string_checker` needs a complete definition of `formatter` of its `Args`.

But neither the `formatter<std::vector<value>>` or `formatter<value>` is complete when they are defined. So these two compiler crashes for the same reason, incomplete constructor of `format_string_checker`.

**Comment by sunmy2019** [comment]
Current implementation of constexpr `format_string_checker` won't allow a directed cycle in defining formatters.

**Comment by vitaut** [comment]
I think requiring complete `formatter` definitions is reasonable and an easy workaround is to outline one of the `format` definitions: https://godbolt.org/z/nzbfGKeer.
