### ISSUE TITLE
fmt::v8: bigint build failure with clang-10

### ISSUE THREAD

**Issue by jcelerier** [fmtlib/fmt#2490]
```C++
#define FMT_HEADER_ONLY
#include <fmt/format.h>
int main() 
{
  fmt::detail::bigint b;
  b.square();
}
```

causes

```
In file included from /opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:2983:
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format-inl.h:557:49: error: variable of non-literal type 'basic_memory_buffer<fmt::v8::detail::bigint::bigit, bigits_capacity>' (aka 'basic_memory_buffer<unsigned int, bigits_capacity>') cannot be defined in a constexpr function
    basic_memory_buffer<bigit, bigits_capacity> n(std::move(bigits_));
                                                ^
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:651:13: note: 'basic_memory_buffer<unsigned int, 32, std::allocator<unsigned int> >' is not literal because it has data member 'alloc_' of non-literal type 'std::allocator<unsigned int>'
  Allocator alloc_;
            ^
```

repro: https://godbolt.org/z/nT1TP4Wof ; maybe FMT_CONSTEXPR20 needs to start from clang-11 (where the above code compiles without issues)

**Comment by jcelerier** [comment]
e.g. something like 
```
#if ((__cplusplus >= 202002L) && \
     (!FMT_CLANG_VERSION || FMT_CLANG_VERSION >= 1100)) || \
    (__cplusplus >= 201709L && FMT_GCC_VERSION >= 1002)
#  define FMT_CONSTEXPR20 constexpr
#else
#  define FMT_CONSTEXPR20
#endif
``` 
(can make a pr if you want)

**Comment by alexezeder** [comment]
The error is actually caused by libstdc++ (GCC standard library) headers, not the Clang or libc++ (LLVM standard library) - https://godbolt.org/z/dbqre1TaW.

**Comment by phprus** [comment]
libstdc++ defined macro ```_GLIBCXX_RELEASE``` with major libstdc++ version.

**Comment by jcelerier** [comment]
I think that the libstdc++ version comes from the gcc version installed on the docker image used, which is what clang will use by default ; what would be interesting is to see whether clang-10 with libstdc++-11 would work. hmm..

**Comment by jcelerier** [comment]
and indeed, g++-9 in -std=c++2a mode does define __cplusplus to 201709 so this case is not encountered

**Comment by jcelerier** [comment]
```C++
#if ((__cplusplus >= 202002L) && \
     (!defined(_GLIBCXX_RELEASE) || _GLIBCXX_RELEASE > 9)) || \
    (__cplusplus >= 201709L && FMT_GCC_VERSION >= 1002)
#  define FMT_CONSTEXPR20 constexpr
#else
#  define FMT_CONSTEXPR20
#endif

```

**Comment by vitaut** [comment]
PR is welcome!

**Comment by alexezeder** [comment]
> ```c++
> #if ((__cplusplus >= 202002L) && \
>      (!defined(_GLIBCXX_RELEASE) || _GLIBCXX_RELEASE > 9)) || \
>     (__cplusplus >= 201709L && FMT_GCC_VERSION >= 1002)
> #  define FMT_CONSTEXPR20 constexpr
> #else
> #  define FMT_CONSTEXPR20
> #endif
> ```

Yeah, that should work - https://godbolt.org/z/vYP7MWfz9
