### ISSUE TITLE
Offering an implementation for width calculation as specified for std::format

### ISSUE THREAD

**Issue by robhz786** [fmtlib/fmt#2492]
Hi,
you might get interested in https://github.com/robhz786/string_width. 
It implements width calculation as specified for std::format ( taking into account grapheme clustering ).
I believe you will find it easy to integrate it into fmt's code.
But feel free to ask me for any help.

Regards
Roberto

**Comment by vitaut** [comment]
Thank you for the suggestion. Is https://github.com/robhz786/string_width/blob/main/include/string_width/detail/ch32_width_and_gcb_prop generated in some way?

**Comment by robhz786** [comment]
Yes, it is generated by a program that uses the latest version of ICU libraries.
But I haven't added it yet into the repo, but I will do it.

**Comment by robhz786** [comment]
Just added the generator of `ch32_width_and_gcb_prop`, but its code is messy.
Also added [its unit tests](https://github.com/robhz786/string_width/blob/main/tests/ch32_width_gcb_prop_tree.cpp). This one looks more readable.

**Comment by vitaut** [comment]
Thanks again. I'll close the issue for now since I don't have a plan to add grapheme clusterization right now but will keep this in mind when get to it.
