### ISSUE TITLE
Format specification docs for signs and zero values is unclear

### ISSUE THREAD

**Issue by seanmiddleditch** [fmtlib/fmt#2493]
The [format specification mini-language](https://fmt.dev/latest/syntax.html#format-specification-mini-language) documentation on the website states:

> Option | Meaning
> -- | --
> '+' | indicates that a sign should be used for both positive as well as negative numbers.
> '-' | indicates that a sign should be used only for negative numbers (this is the default behavior).
> space | indicates that a leading space should be used on positive numbers, and a minus sign on negative numbers.

The use of "positive" here should perhaps instead say "nonnegative" since they affect zero values.

e.g., `format("{+}", 0)` produces `"+0"`, but the documentation as written could be interpreted as expecting the result to be `"0"` with no sign.

**Comment by vitaut** [comment]
Fixed in https://fmt.dev/dev/syntax.html, thanks.
