### ISSUE TITLE
Linker error on Visual Studio 2019

### ISSUE THREAD

**Issue by acgetchell** [fmtlib/fmt#2496]
My latest build on Windows with Visual Studio 2019 surfaced the following issue:

```
ld-link: error: undefined symbol: public: static char const (*const fmt::v8::detail::basic_data<void>::digits)[2]
>>> referenced by C:\projects\cdt-plusplus\src\initialize.cpp
>>>               src\CMakeFiles\initialize.dir\initialize.cpp.obj
```

Details:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus#L7343

My previous build worked fine:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/40509390

I do not get this error on macOS or Linux:

https://github.com/acgetchell/CDT-plusplus/actions/runs/1224646512

**Comment by vitaut** [comment]
I'm not sure why you were getting a link error but `basic_data::digits` is no longer used in `master` so the error should go away.

**Comment by acgetchell** [comment]
It's still present as of 8.0.1.

https://ci.appveyor.com/project/acgetchell/cdt-plusplus#L7838
