### ISSUE TITLE
Lot of warnings with -Weverything flag

### ISSUE THREAD

**Issue by 3Hren** [fmtlib/fmt#250]
Hi!

Compiling with `-Weverything` produces a lot of warnings. Half of them are `-Wsign-conversion`, some `-Wswitch-enum`, some `-Wunused-member-function`.

Either I can try to fix it myself or to enclose them with pragmas or to wait for your participation.

**Comment by vitaut** [comment]
Hello!
Are you talking about Clang's `-Weverything`? If it enables all warnings this will probably give lots of false positives (warnings with lower rates of false positives included in `-Wall` and `-Wextra` should be addressed already). That said, PRs that fix or suppress these warnings are welcome.

**Comment by vitaut** [comment]
Sign conversion warnings should be fixed now (#281).

**Comment by vitaut** [comment]
`format.h` is warning-free as of https://github.com/fmtlib/fmt/commit/a201c6197715f6578f64cb96258c2d9dafeb1724. However, `-Weverything` has too much noise, so warnings elsewhere, if any, better be addressed case-by-case.
