### ISSUE TITLE
Using {fmt} on IBM i (AS/400) 7.4 ILE C++ compiler

### ISSUE THREAD

**Issue by d7d1cd** [fmtlib/fmt#2501]
**Problem**
When trying to use fmt version 4.x on an IBM i 7.4 operating system, I encountered the following problem. I added two files from fmt to the project: format.h and format.cc and defined the FMT_HEADER_ONLY macro. Then I wrote the following test code:
```
#include "fmt/format.h"
int main() {
    fmt::print("Hello, {}!", "world");
} 
```

Compilation was successful, but the application called abort on startup.

**Successful solution**
For a solution, I tried to specify the argument number in the format string and the launch was successful:
`fmt::print("Hello, {0}!", "world");`

**Analysis**
Examining the logs showed that abort occurs in the following function from format.h:
```
template <typename Char, typename AF>
inline internal::Arg BasicFormatter<Char, AF>::parse_arg_name (const Char * & s)
```

When entering this function, the start variable points to the string "}!", Which is probably wrong. By changing the code to this:
```
#include "fmt/format.h"
#include <iostream>
int main() {
  try {
    fmt::print("Hello, {}!", "world");
  } catch (std::exception& e) {
    std::cout << e.what();
  }
} 
```
I got the output "argument not found".

**Question**
How can I solve the problem I found?

**Comment by vitaut** [comment]
> the start variable points to the string "}!", Which is probably wrong. 

This part looks correct. The problem seems to be related to automatic argument indexing but it's hard to be more specific just from this information. Have you tried a more recent version of the library?

**Comment by d7d1cd** [comment]
> Have you tried a more recent version of the library?

Yes, initially I wanted to use the most recent version of the library, but I ran into the same problem as the user in this issue https://github.com/fmtlib/fmt/issues/1059, namely that my compiler is not fully supports C++11 (only a few features are supported).


>but it's hard to be more specific just from this

Can I execute something on my system to help you understand what is the cause of the error?

**Comment by d7d1cd** [comment]
I managed to find the cause and fix it. There is a function in the `format.h` file:
```
template <typename Char>
inline bool is_name_start (Char c) {
  return ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') || '_' == c;
}
```

However, in my system, there are more than capital letters of the Latin alphabet between the characters `'A'` and `'Z'`. There is such a set:
`ABCDEFGHI­ИЙКЛМПJKLMNOPQRНО}ЯРСЖ@STUVWXYZ`

As you can see, there are also `'}'` among the characters, so this function returns true when the format string is `"Hello {}"`, although it should return false.
I fixed the above function like this:
```
template <typename Char>
inline bool is_name_start (Char c) {
  return std::isalpha(c) || '_' == c;
}
```
In addition, the `BasicFormatter` function contains the following code:
```
template <typename Char, typename AF>
inline internal::Arg BasicFormatter<Char, AF>::parse_arg_name(const Char*& s) {
...
  } while (internal::is_name_start(c) || ​​('0' <= c && c <= '9'));
...
}
```

I fixed the second condition to `std::isdigit (c)`.
As a result, formatting without specifying argument numbers worked.
Tell me why the library did not initially use `std::isalpha` and `std::isdigit`, and can I have problems in the future when using the library if I made the above edits in the code?

**Comment by alexezeder** [comment]
> Tell me why the library did not initially use `std::isalpha` and `std::isdigit`

My guess here is that this is at least a bit but related to the performance.
As you can see:

- https://quick-bench.com/q/Y_qN-zGcxjlqBfD1NM_DN83QOM8 (GCC)
- https://quick-bench.com/q/PulTpz_YPG8TDX-SmrE7Tu383Sw (Clang + libstdc++)
- https://quick-bench.com/q/aXy_WD6kwWQpu1XaeMYaPWEvq68 (Clang + libc++)

there is a performance benefit for such simple comparisons. Furthermore, it works _probably_ not only for these std libraries, OS, or x86_64 arch (which is perhaps used by Quick C++ Benchmark runners) but for every known config, since even with Clang + libc++ (in this case `std::` calls are inlined) [the assembly seems to be more complex](https://godbolt.org/z/Wa7aoE9x5) for the function with `std::` calls.

So, yeah, the code in the library is incorrect for some configurations (like yours), but it looks like these configurations aren't very popular since this problem didn't show itself earlier. Anyway, for me, we can fix this with one extra configuration time check and macro switches with no overhead for other users.

**Comment by foonathan** [comment]
> I fixed the second condition to std::isdigit(c).

This shouldn't be necessary on a conforming system: https://eel.is/c++draft/lex.charset#3.sentence-3

**Comment by vitaut** [comment]
`isalpha` shouldn't be used because it's locale-dependent. In general {fmt} assumes an ASCII-based encoding but a PR to add support for more exotic ones would be welcome.

**Comment by mwinterb** [comment]
MSVC is the only compiler of the main 3 that recognizes that the three separate ranges are all adjacent:
https://gcc.godbolt.org/z/5dfnPs7GM
But checking if the 'a' -> 'z' range is continuous first and then using the ASCII-focused checks makes everyone happy.
Clang's codegen for the EBCDIC-friendly version gets crushed by the other two versions: https://quick-bench.com/q/GvI5GdUSAzovLuEtae3LzEOhTcQ. GCC's current codegen was introduced in 11.1 which quick-bench doesn't have available. GCC 10.3's code for the EBCDIC-friendly version actually does better than the obvious test in alexezeder's artificial benchmark.

Technically, MSVC x86-32 doesn't figure it out, which is weird. MSVC arm64 figures it out, though.
