### ISSUE TITLE
‘fmt::v8::detail::assert_fail(char const*, int, char const*)’undefined reference

### ISSUE THREAD

**Issue by HU-517** [fmtlib/fmt#2503]
hu@HU:~/Software/orthogonal-planes-master/build$ make
Consolidate compiler generated dependencies of target ppf_lib
[ 10%] Built target ppf_lib
Consolidate compiler generated dependencies of target tinyply
[ 21%] Built target tinyply
Consolidate compiler generated dependencies of target vis_lib
[ 42%] Built target vis_lib
Consolidate compiler generated dependencies of target corner_lib
[ 52%] Built target corner_lib
Consolidate compiler generated dependencies of target graph_lib
[ 78%] Built target graph_lib
Consolidate compiler generated dependencies of target PLY_PPDetectRefine
[ 84%] Linking CXX executable ../../ply_detect_refine/bin/PLY_PPDetectRefine
../libppf_lib.a(PairDetector.cpp.o)：in ‘std::make_unsigned<int>::type fmt::v8::detail::to_unsigned<int>(int)’：
PairDetector.cpp:(.text._ZN3fmt2v86detail11to_unsignedIiEENSt13make_unsignedIT_E4typeES4_[_ZN3fmt2v86detail11to_unsignedIiEENSt13make_unsignedIT_E4typeES4_]+0x1b)：对‘fmt::v8::detail::assert_fail(char const*, int, char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘fmt::v8::format_error::format_error(char const*)’中：
PairDetector.cpp:(.text._ZN3fmt2v812format_errorC2EPKc[_ZN3fmt2v812format_errorC5EPKc]+0x24)：对‘vtable for fmt::v8::format_error’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘fmt::v8::detail::throw_format_error(char const*)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail18throw_format_errorEPKc[_ZN3fmt2v86detail18throw_format_errorEPKc]+0x23)：对‘fmt::v8::format_error::~format_error()’undefined reference
PairDetector.cpp:(.text._ZN3fmt2v86detail18throw_format_errorEPKc[_ZN3fmt2v86detail18throw_format_errorEPKc]+0x28)：对‘typeinfo for fmt::v8::format_error’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘std::make_unsigned<long>::type fmt::v8::detail::to_unsigned<long>(long)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail11to_unsignedIlEENSt13make_unsignedIT_E4typeES4_[_ZN3fmt2v86detail11to_unsignedIlEENSt13make_unsignedIT_E4typeES4_]+0x1d)：对‘fmt::v8::detail::assert_fail(char const*, int, char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘Sophus::SO3Base<Sophus::SO3<double, 0> >::normalize()’中：
PairDetector.cpp:(.text._ZN6Sophus7SO3BaseINS_3SO3IdLi0EEEE9normalizeEv[_ZN6Sophus7SO3BaseINS_3SO3IdLi0EEEE9normalizeEv]+0x121)：对‘fmt::v8::vprint(fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)’undefined reference
PairDetector.cpp:(.text._ZN6Sophus7SO3BaseINS_3SO3IdLi0EEEE9normalizeEv[_ZN6Sophus7SO3BaseINS_3SO3IdLi0EEEE9normalizeEv]+0x191)：对‘fmt::v8::vprint(fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler>::on_error(char const*)’中：
PairDetector.cpp:(.text._ZN3fmt2v826basic_format_parse_contextIcNS0_6detail13error_handlerEE8on_errorEPKc[_ZN3fmt2v826basic_format_parse_contextIcNS0_6detail13error_handlerEE8on_errorEPKc]+0x5)：对‘fmt::v8::detail::error_handler::on_error(char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘void fmt::v8::detail::format_value<char, Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >(fmt::v8::detail::buffer<char>&, Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > const&, fmt::v8::detail::locale_ref)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail12format_valueIcN5Eigen9TransposeINS3_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEEEEvRNS1_6bufferIT_EERKT0_NS1_10locale_refE[_ZN3fmt2v86detail12format_valueIcN5Eigen9TransposeINS3_6MatrixIdLi4ELi1ELi0ELi4ELi1EEEEEEEvRNS1_6bufferIT_EERKT0_NS1_10locale_refE]+0x72)：对‘std::locale fmt::v8::detail::locale_ref::get<std::locale>() const’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘char const* fmt::v8::detail::parse_align<char, fmt::v8::detail::specs_checker<fmt::v8::detail::dynamic_specs_handler<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > >&>(char const*, char const*, fmt::v8::detail::specs_checker<fmt::v8::detail::dynamic_specs_handler<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > >&)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail11parse_alignIcRNS1_13specs_checkerINS1_21dynamic_specs_handlerINS0_26basic_format_parse_contextIcNS1_13error_handlerEEEEEEEEEPKT_SD_SD_OT0_[_ZN3fmt2v86detail11parse_alignIcRNS1_13specs_checkerINS1_21dynamic_specs_handlerINS0_26basic_format_parse_contextIcNS1_13error_handlerEEEEEEEEEPKT_SD_SD_OT0_]+0x66)：对‘fmt::v8::detail::assert_fail(char const*, int, char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘int fmt::v8::detail::parse_nonnegative_int<char>(char const*&, char const*, int)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail21parse_nonnegative_intIcEEiRPKT_S5_i[_ZN3fmt2v86detail21parse_nonnegative_intIcEEiRPKT_S5_i]+0x73)：对‘fmt::v8::detail::assert_fail(char const*, int, char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘char const* fmt::v8::detail::parse_width<char, fmt::v8::detail::specs_checker<fmt::v8::detail::dynamic_specs_handler<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > >&>(char const*, char const*, fmt::v8::detail::specs_checker<fmt::v8::detail::dynamic_specs_handler<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > >&)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail11parse_widthIcRNS1_13specs_checkerINS1_21dynamic_specs_handlerINS0_26basic_format_parse_contextIcNS1_13error_handlerEEEEEEEEEPKT_SD_SD_OT0_[_ZN3fmt2v86detail11parse_widthIcRNS1_13specs_checkerINS1_21dynamic_specs_handlerINS0_26basic_format_parse_contextIcNS1_13error_handlerEEEEEEEEEPKT_SD_SD_OT0_]+0x48)：对‘fmt::v8::detail::assert_fail(char const*, int, char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘void fmt::v8::detail::check_string_type_spec<char, fmt::v8::detail::error_handler&>(char, fmt::v8::detail::error_handler&)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail22check_string_type_specIcRNS1_13error_handlerEEEvT_OT0_[_ZN3fmt2v86detail22check_string_type_specIcRNS1_13error_handlerEEEvT_OT0_]+0x22)：对‘fmt::v8::detail::error_handler::on_error(char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘int fmt::v8::detail::get_dynamic_spec<fmt::v8::detail::width_checker, fmt::v8::basic_format_arg<fmt::v8::basic_format_context<fmt::v8::appender, char> >, fmt::v8::detail::error_handler>(fmt::v8::basic_format_arg<fmt::v8::basic_format_context<fmt::v8::appender, char> >, fmt::v8::detail::error_handler)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail16get_dynamic_specINS1_13width_checkerENS0_16basic_format_argINS0_20basic_format_contextINS0_8appenderEcEEEENS1_13error_handlerEEEiT0_T1_[_ZN3fmt2v86detail16get_dynamic_specINS1_13width_checkerENS0_16basic_format_argINS0_20basic_format_contextINS0_8appenderEcEEEENS1_13error_handlerEEEiT0_T1_]+0x245)：对‘fmt::v8::detail::error_handler::on_error(char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘int fmt::v8::detail::get_dynamic_spec<fmt::v8::detail::precision_checker, fmt::v8::basic_format_arg<fmt::v8::basic_format_context<fmt::v8::appender, char> >, fmt::v8::detail::error_handler>(fmt::v8::basic_format_arg<fmt::v8::basic_format_context<fmt::v8::appender, char> >, fmt::v8::detail::error_handler)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail16get_dynamic_specINS1_17precision_checkerENS0_16basic_format_argINS0_20basic_format_contextINS0_8appenderEcEEEENS1_13error_handlerEEEiT0_T1_[_ZN3fmt2v86detail16get_dynamic_specINS1_17precision_checkerENS0_16basic_format_argINS0_20basic_format_contextINS0_8appenderEcEEEENS1_13error_handlerEEEiT0_T1_]+0x245)：对‘fmt::v8::detail::error_handler::on_error(char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘void fmt::v8::detail::check_string_type_spec<char, fmt::v8::detail::error_handler>(char, fmt::v8::detail::error_handler&&)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail22check_string_type_specIcNS1_13error_handlerEEEvT_OT0_[_ZN3fmt2v86detail22check_string_type_specIcNS1_13error_handlerEEEvT_OT0_]+0x22)：对‘fmt::v8::detail::error_handler::on_error(char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘char const* fmt::v8::detail::do_parse_arg_id<char, char const* fmt::v8::detail::parse_width<char, fmt::v8::detail::specs_checker<fmt::v8::detail::dynamic_specs_handler<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > >&>(char const*, char const*, fmt::v8::detail::specs_checker<fmt::v8::detail::dynamic_specs_handler<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > >&)::width_adapter&>(char const*, char const*, fmt::v8::detail::specs_checker<fmt::v8::detail::dynamic_specs_handler<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > >&)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail15do_parse_arg_idIcRZNS1_11parse_widthIcRNS1_13specs_checkerINS1_21dynamic_specs_handlerINS0_26basic_format_parse_contextIcNS1_13error_handlerEEEEEEEEEPKT_SE_SE_OT0_E13width_adapterEESE_SE_SE_SG_[_ZN3fmt2v86detail15do_parse_arg_idIcRZNS1_11parse_widthIcRNS1_13specs_checkerINS1_21dynamic_specs_handlerINS0_26basic_format_parse_contextIcNS1_13error_handlerEEEEEEEEEPKT_SE_SE_OT0_E13width_adapterEESE_SE_SE_SG_]+0xba)：对‘fmt::v8::detail::assert_fail(char const*, int, char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘char const* fmt::v8::detail::do_parse_arg_id<char, char const* fmt::v8::detail::parse_precision<char, fmt::v8::detail::specs_checker<fmt::v8::detail::dynamic_specs_handler<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > >&>(char const*, char const*, fmt::v8::detail::specs_checker<fmt::v8::detail::dynamic_specs_handler<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > >&)::precision_adapter&>(char const*, char const*, fmt::v8::detail::specs_checker<fmt::v8::detail::dynamic_specs_handler<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > >&)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail15do_parse_arg_idIcRZNS1_15parse_precisionIcRNS1_13specs_checkerINS1_21dynamic_specs_handlerINS0_26basic_format_parse_contextIcNS1_13error_handlerEEEEEEEEEPKT_SE_SE_OT0_E17precision_adapterEESE_SE_SE_SG_[_ZN3fmt2v86detail15do_parse_arg_idIcRZNS1_15parse_precisionIcRNS1_13specs_checkerINS1_21dynamic_specs_handlerINS0_26basic_format_parse_contextIcNS1_13error_handlerEEEEEEEEEPKT_SE_SE_OT0_E17precision_adapterEESE_SE_SE_SG_]+0xba)：对‘fmt::v8::detail::assert_fail(char const*, int, char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘unsigned long long fmt::v8::detail::width_checker<fmt::v8::detail::error_handler>::operator()<int, 0>(int)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail13width_checkerINS1_13error_handlerEEclIiLi0EEEyT_[_ZN3fmt2v86detail13width_checkerINS1_13error_handlerEEclIiLi0EEEyT_]+0x2d)：对‘fmt::v8::detail::error_handler::on_error(char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘unsigned long long fmt::v8::detail::width_checker<fmt::v8::detail::error_handler>::operator()<unsigned int, 0>(unsigned int)’中：
PairDetector.cpp:(.text._ZN3fmt2v86detail13width_checkerINS1_13error_handlerEEclIjLi0EEEyT_[_ZN3fmt2v86detail13width_checkerINS1_13error_handlerEEclIjLi0EEEyT_]+0x2d)：对‘fmt::v8::detail::error_handler::on_error(char const*)’undefined reference
../libppf_lib.a(PairDetector.cpp.o)：在函数‘unsigned long long 
ply_detect_refine/CMakeFiles/PLY_PPDetectRefine.dir/build.make:137: recipe for target '../ply_detect_refine/bin/PLY_PPDetectRefine' failed
make[2]: *** [../ply_detect_refine/bin/PLY_PPDetectRefine] Error 1
CMakeFiles/Makefile2:258: recipe for target 'ply_detect_refine/CMakeFiles/PLY_PPDetectRefine.dir/all' failed
make[1]: *** [ply_detect_refine/CMakeFiles/PLY_PPDetectRefine.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vitaut** [comment]
`assert_fail` is defined here: https://github.com/fmtlib/fmt/blob/3d0c7ae385bcff3d0c152c358db67a222dd0628c/include/fmt/format-inl.h#L34

Please make sure that you link with the fmt library correctly.

**Comment by vitaut** [comment]
Closing for now but feel free to reopen with a self-contained repro.
