### ISSUE TITLE
Problem when using fmt::format on IBM i (AS/400) 7.4 ILE C++ compiler

### ISSUE THREAD

**Issue by d7d1cd** [fmtlib/fmt#2504]
**Problem**
I have a problem when using the `fmt::format` function from release 4.1, when the program consists of several translation units and `format.h` is included in more than one.

The test project had 2 translation units: a file with the `main` function (where I called `fmt::format`) and a `format.cc`. They were compiled successfully, but when building, the linker reported that the name was resolved several times (ODR violation). The name is the following (I apologize for the mangled name, but there is no tool on my system to do the de-mangling):
`__vftQ3_3fmt8internal12MemoryBufferXTcSP500TQ2_3std9allocatorXTc__Q2_3fmt6BufferXTc___Q2_3fmt8internal`

**Analysis**
From the mangled name, I guessed that the constructor of the `fmt::internal::MemoryBuffer` class is the problem. However, its definition is in the body of the class and its inclusion in different translation units should not lead to a violation of the ODR. I also found out that the problem can be reproduced by creating a variable of type `fmt::MemoryWriter` in `main`.
Probably, the problem is related to some kind of compiler bug, since it was not reproduced in C++ Builder on Windows, but I could not create a minimal test case to send to support.

**Solution**
During my analysis, I found that the problem does not occur when using the `fmt::print` function. Looking at its implementation, I saw that it is almost the same as that of `fmt::format`, but its implementation is located in `format.cc`, and not in `format.h`, like in `fmt::format`. After transferring the implementation to `format.cc`, the linker error disappeared and the application was built. However, the error persists when using `fmt::MemoryWriter`.

**Question**
Can you give any advice or comment on this problem and is the implementation of `fmt::format `in the header file an error?

**Comment by d7d1cd** [comment]
I determined that the problem is with [this](https://github.com/fmtlib/fmt/blob/4.x/fmt/format.h#L908) implementation. If you add the `inline` keyword, the error disappears. Obviously this is a bug in my compiler.

**Comment by vitaut** [comment]
Closing as this does appear to be a compiler bug.
