### ISSUE TITLE
fmv.dev has dead links

### ISSUE THREAD

**Issue by beached** [fmtlib/fmt#2513]
I did a search for `ostream` on fmt.dev and the first link `fmt::ostream` is giving a 404 https://fmt.dev/latest/search.html?q=ostream&check_keywords=yes&area=default

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/134aec40f08640993b299bf59758ad9bf4d016dd and the dev docs: https://fmt.dev/dev/ but need to rebuild the docs for other versions.

**Comment by vitaut** [comment]
Search should be working now. Thanks for reporting.
