### ISSUE TITLE
leading zeros with precession digit format?

### ISSUE THREAD

**Issue by uraymeiviar** [fmtlib/fmt#2519]
```cpp
double val = 13.21;
std::string valStr = fmt::format("{:03.1f}",val);
```

resulting to `"13.2"` , I am expecting `"013.2"`

**Comment by vitaut** [comment]
`3` is the total width not just the significand, so the output is correct. This is consistent with Python's `format`:

```python
>>> '{:03.1f}'.format(13.21)
'13.2'
```
