### ISSUE TITLE
Format ranges of std::byte

### ISSUE THREAD

**Issue by andreasWallner** [fmtlib/fmt#2523]
From #2355 it seemed to me that it is expected that we can use `fmt::join` to format `std::vector<std::byte>`.
Trying this with the current trunk this fails with gcc, clang and msvc (each in latest version) as can be seen here: https://godbolt.org/z/3qPGoTq49.

Expected result: `fmt::print("{:02x}", fmt::join(x, ""))` should work if `x` is `std::vector<std::byte>`
Current result: Compile error that states `std::byte` is not formattable.

**Comment by sunmy2019** [comment]
https://godbolt.org/z/s1j3Md4db
You are not using fmtlib trunk.

**Comment by andreasWallner** [comment]
Thanks, sorry for the oversight^^
