### ISSUE TITLE
how to format more args

### ISSUE THREAD

**Issue by duchuanLX** [fmtlib/fmt#2524]
LogTestFun("Default format: {} {} {} \n", 1, "22222", 10.5);

void LogTestFun(const char* format, ...){
	string strContext;
	strContext= fmt::print(format, ...);
}

how to format more args to string
or detail doc

**Comment by duchuanLX** [comment]
link:
https://github.com/fmtlib/fmt/issues/72

**Comment by duchuanLX** [comment]
@vitaut 
Does it support this feature/arglist now?

**Comment by vitaut** [comment]
varargs are intentionally not supported.

**Comment by duchuanLX** [comment]
> varargs are intentionally not supported.

thank U.
