### ISSUE TITLE
Feature request.  Full width padding modifier

### ISSUE THREAD

**Issue by beached** [fmtlib/fmt#2527]
Would it be possible to get a way to pad a number to it's full width.  Or did I miss that in the docs?  Sorry if this is a duplicate, I didn't see anything other issues with a search for padding

**Comment by vitaut** [comment]
What exactly do you mean by that? Could you give an example?

**Comment by beached** [comment]
`{:064b}` to print out a 64bit integer in binary with full 0 padding.  However, in generic code it's often unknown which width to use but commonly one wants all the bits.  It would be nice to say something like `{:0<something>b}` where `<something>` is some token that says use all the bits please.

**Comment by vitaut** [comment]
You can do it with dynamic width (https://godbolt.org/z/hfeKoWqrf):

```c++
#include <fmt/core.h>
#include <limits>

int main() {
  using N = uint32_t;
  auto n = N(42);
  fmt::print("{:0{}b}\n", n, std::numeric_limits<N>::digits);
}
```

**Comment by beached** [comment]
Right, this was more a feature request for a succinct way of saying without doing what we've had to do with iostreams and width/setw.  It's quite common to want full width.

**Comment by vitaut** [comment]
Thanks for the suggestions but there are no plans to add this as a built-in format specifier. If you do this often you can add a wrapper type that does this formatting by default, something like `format("{}", full_width(n))`.

**Comment by beached** [comment]
Is that because the format modifiers are not open to addition, or developer time? I mean would a patch be welcome?

**Comment by vitaut** [comment]
Format string syntax is mostly fixed at this point for compatibility with `std::format`. Any additions like this can be done via the normal extension API, they don't have to be in the core library.

**Comment by beached** [comment]
Thanks :)
