### ISSUE TITLE
Permit opting out of auto-optimization in GCC

### ISSUE THREAD

**Issue by mwinterb** [fmtlib/fmt#2528]
I don't know if this is what #2526 is attempting to address since there's not enough detail, but old GCC's targeting ARM (and AVR and MSP430) emit a warning on `#pragma GCC pop_options`, see https://godbolt.org/z/YqrGTGMEq. The ARM and AVR targets are using GCC's older than what fmtlib supports, but I know that ARM targeting GCC 4.8.3 as well as 4.9 based on [this bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59884) also emitted it, but godbolt doesn't have those specific versions.

**Comment by vitaut** [comment]
Implemented a workaround for the GCC bug in https://github.com/fmtlib/fmt/commit/012cc709d0abb0a963591413a746b988168e5e3a. You don't really need to opt out (although you could by defining `FMT_PRAGMA`).
