### ISSUE TITLE
access mode of files created by output_file is surprising

### ISSUE THREAD

**Issue by berthubert** [fmtlib/fmt#2530]
Hi,

In 8.0.1 at least, on POSIX, files created by fmt::output_file explicitly set themselves to be readable and writable by the user only. 

This led to some issues after I moved to fmt::output_file since all of a sudden my files could no longer be read by the web server.

POSIX custom is to set a broader default permission (0660 for example), and let the operator tone that down using their umask setting. 

Now it may be that fmt has a good reason for 0600 of course, but it is a bit surprising. There is also no way to change this mode.

Thoughts? Can I help?

   Bert (formerly powerdns_bert)

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/4a85db1ce15cbf232ddb9a8a6640b74dbcbc2cbd, now the default mode is `-rw-r--r--` which is consistent with `fopen`. Thanks for reporting.

**Comment by berthubert** [comment]
Thanks!

**Comment by arogge** [comment]
Sorry for digging this one up again.
If the intent is to mimic behaviour of `fopen()` then the patch is wrong. 
While FMT is setting `S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH`, POSIX mandates that it should be  `S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH`.

[fopen() in the Open Group Specification](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html) reads:
> If mode is w, wb, a, ab, w+, wb+, w+b, a+, ab+, or a+b, and the file did not previously exist, the fopen() function shall create a file as if it called the creat() function with a value appropriate for the path argument interpreted from pathname and a value of S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH for the mode argument.

The system will usually strip `S_IWGRP` and `S_IWOTH` based on the process' umask, which will result in the observed `-rw-r--r--` if umask was set to `022`. However with a umask of `002` `fopen()` would produce `-rw-rw-r--` and fmt should probably do the same.

I can do a pull request for that if you want.

**Comment by vitaut** [comment]
@arogge, good catch, thanks.

> I can do a pull request for that if you want.

Please, do.

**Comment by arogge** [comment]
See PR #2733
