### ISSUE TITLE
Format double with non-exponent notation

### ISSUE THREAD

**Issue by draveness** [fmtlib/fmt#2531]
How to format double to get the following results

```c++
// expected: 
fmt::format("{}", 10.00) // 10
fmt::format("{}", 10.1) // 10.1
fmt::format("{}", 123456789) // 123456789

// actual: 
fmt::format("{}", 10.00) // 10
fmt::format("{}", 10.1) // 10.1
fmt::format("{}", 123456789) // 1.23e-09
```

**Comment by vitaut** [comment]
The current version of {fmt} **will** give you the expected results:

```c++
  fmt::print("{}\n", 10.00); // 10
  fmt::print("{}\n", 10.1); // 10.1
  fmt::print("{}\n", 123456789.0); // 123456789
```
Output:
```c++
10
10.1
123456789
```
To get non-exponent notation in general use the `f` specifier as in `printf` (https://fmt.dev/latest/syntax.html#format-specification-mini-language).

**Comment by draveness** [comment]
What about decimals, e.g. 1.33e-05

**Comment by vitaut** [comment]
Not sure what the question is but please see the docs at https://fmt.dev/latest/syntax.html#format-specification-mini-language which describe format specifiers.
