### ISSUE TITLE
warning: macro "__OPTIMIZE__" is not used [-Wunused-macros]

### ISSUE THREAD

**Issue by Chnossos** [fmtlib/fmt#2532]
Fedora 32, GCC 10, fmt 8.0.1 header-only from Conan.

This warning is generated from every .cpp file compilation in debug mode when the `-Wunused-macros` switch is enabled.

**Comment by vitaut** [comment]
The macro is used here https://github.com/fmtlib/fmt/blob/0a985fd4c6115eae8a455b110a747b265d1af2d1/include/fmt/core.h#L282
so this looks like a false positive.

**Comment by vitaut** [comment]
@zethon this is clearly a gcc bug since the macro is used per my comment above so please report there. As a workaround you can either not add `-Wunused-macros` on problematic versions of gcc or set the `FMT_SYSTEM_HEADERS` CMake option.

**Comment by phprus** [comment]
Bug fixed in GCC 11:
https://godbolt.org/z/ofsTMTh3P
