### ISSUE TITLE
Compile error for runtime strings

### ISSUE THREAD

**Issue by ominusliticus** [fmtlib/fmt#2536]
I am incorporating the fmt library in my project using CMake and link it as a public library. 

When I build a C++ project targeted at Visual Studio platform, it's compiler and intellisense complain about this line of code

```C++
template <fmt::detail_exported::fixed_string Str>
constexpr auto operator""_a() 
    -> detail::udl_arg<remove_cvref_t<decltype(Str.data[0])>, sizeof(Str.data) / (decltype(Str.data[0])), Str> 
{
  return {};
}
```

which returns this error:
```
\fmt\include\fmt\format.h 2986: a literal operator template must have a template parameter list equivalent to '<char ...>'	
```

The C++ compiler version I am using is C++20. I am not passing any special flags to the compiler.

What do I have to do to fix this error?

**Comment by vitaut** [comment]
What compiler version and flags do you use? Could you provide a godbolt repro?

**Comment by ominusliticus** [comment]
I replaced all lines 
```C++
#if FMT_USE_NONTYPE_TEMPLATE_PARAMETERS
```
with
```C++
#if FMT_USE_NONTYPE_TEMPLATE_PARAMETERS && !defined(__INTELLISENSE__)
```
and that takes care of all the issues.
Thank you!

**Comment by vitaut** [comment]
Closing since this is a bug in intellisense. Please report to Microsoft.

**Comment by leewheel** [comment]
When change "#if FMT_USE_NONTYPE_TEMPLATE_PARAMETERS" to "#if FMT_USE_NONTYPE_TEMPLATE_PARAMETERS && !defined(__INTELLISENSE__)" , it's show another error ：

`#if FMT_USE_NONTYPE_TEMPLATE_PARAMETERS && !defined(__INTELLISENSE__)
template <detail_exported::fixed_string Str>
constexpr auto operator""_a()
    -> detail::udl_arg<remove_cvref_t<decltype(Str.data[0])>,
                       sizeof(Str.data) / sizeof(decltype(Str.data[0])), Str> {
  return {};
}
#  else
constexpr auto operator"" _a(const char* s, size_t) -> detail::udl_arg<char> {
  return {s};
}
#  endif`

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0442	too few arguments for class template "fmt::v8::detail::udl_arg"	fmt	C:\azerothcore-wotlk-Playerbot\deps\fmt\include\fmt\format.h	3036

**Comment by cppcooper** [comment]
> Closing since this is a bug in intellisense. Please report to Microsoft.

@vitaut are you sure about that? Maybe I'm misunderstanding what that template is actually doing, but it seems like it isn't following the standard and that's why intellisense is listing the error.
See: https://stackoverflow.com/a/53789085/1327399

**Comment by vitaut** [comment]
Yes, I'm sure. That answer is very out of date.
