### ISSUE TITLE
vsprintf, format_arg_store and formatter doesn't work

### ISSUE THREAD

**Issue by ludekvodicka** [fmtlib/fmt#2538]
Hi, 
I just updated fmt lib from 7.x to latest 8.0.1 but I'm not able to migrate my project.

In our project we're using `fmt::formatters `together with `format_arg_store<>` and `fmt::vsprintf`.

But it seems that formatters doesn't work for format_arg_store properly. I'm testing it on examples from the documentation on VS 2019 and getting following error:

```
1>vcpkg64\include\fmt\core.h(1568,59): error C2338: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
1>vcpkg64\include\fmt\core.h(1687): message : see reference to function template instantiation 'fmt::v8::detail::value<Context> fmt::v8::detail::make_arg<true,Context,fmt::v8::detail::type::custom_type,point,0>(const T &)' being compiled
1>        with
1>        [
1>            Context=fmt::v8::printf_context,
1>            T=point
1>        ]
1>\vcpkg64\include\fmt\core.h(1687): message : while compiling class template member function 'fmt::v8::format_arg_store<fmt::v8::printf_context,int,const char *,point>::format_arg_store(const int &,const char *const &,const point &)'
1>main.cpp(64): message : see reference to function template instantiation 'fmt::v8::format_arg_store<fmt::v8::printf_context,int,const char *,point>::format_arg_store(const int &,const char *const &,const point &)' being compiled
1>main.cpp(64): message : see reference to class template instantiation 'fmt::v8::format_arg_store<fmt::v8::printf_context,int,const char *,point>' being compiled
```

for testing, I'm  using formatted from the documentation and simple vsprintf snippet:

```
#include <fmt/format.h>

struct point {
	double x, y;
	friend std::ostream& operator<<(std::ostream& os, const point& d) {
		return os << d.x << '-' << d.y;
	}
};

template <> struct fmt::formatter<point> {
	char presentation = 'f';

	constexpr auto parse(format_parse_context& ctx) -> decltype(ctx.begin()) {
		auto it = ctx.begin(), end = ctx.end();
		if (it != end && (*it == 'f' || *it == 'e')) presentation = *it++;
		if (it != end && *it != '}')
			throw format_error("invalid format");
		return it;
	}

	template <typename FormatContext>
	auto format(const point& p, FormatContext& ctx) -> decltype(ctx.out()) {
		return format_to(
			ctx.out(),
			presentation == 'f' ? "({:.1f}, {:.1f})" : "({:.1e}, {:.1e})",
			p.x, p.y);
	}
};

int test()
{
	point p;
	fmt::format_arg_store<fmt::printf_context, int, const char*, point> as{ 42, "something", p };
	fmt::basic_format_args<fmt::printf_context> args(as);
	fmt::vsprintf("[%d] %s %s happened", args);
}
```

Are formatters still supported for arg_store? Is this a bug in fmt or is there any other way how to do that? 
Thanks

**Comment by vitaut** [comment]
ostream support should work (https://godbolt.org/z/hM1TGzen7):

```c++
#include <fmt/ostream.h>
#include <fmt/printf.h>

struct S {};

template <typename Char>
std::basic_ostream<Char>& operator<<(std::basic_ostream<Char>& os, const S& value) {
  return os << 42;
}

int main() {
  fmt::printf("%s", S());
}
```

> As far as I know, fmt::format isn't possible to run with %s. Any advice please?

`fmt::format` uses a different format specifier syntax (https://fmt.dev/latest/syntax.html) so instead of `%s` you would pass `{}`.

> In case that formatter<> is intended to be used with fmt::format family only, why fmt::make_printf_args(...); use it and return error To make type T formattable provide a formatter<T> specialization ?

The error message is for the common case of `format` / `print`. It's slightly misleading for `printf` since the latter doesn't provide an extension API.

> Can't this be the issue, that in v7, make_printf_args used operator << for conversion, but in v8 make_printf_args is using formatted<> which is not intended to be used with make_printf_args?

AFAICS `operator<<` still works.
