### ISSUE TITLE
CMakeLists.txt missing leading dash for mingw big object compile flag check

### ISSUE THREAD

**Issue by cc2x** [fmtlib/fmt#2540]
in the CMakeLists.txt file, the MINGW check shows this:

`check_cxx_compiler_flag("Wa,-mbig-obj" FMT_HAS_MBIG_OBJ)
`

shouldn't the compiler flag string start with a dash?

`check_cxx_compiler_flag("-Wa,-mbig-obj" FMT_HAS_MBIG_OBJ)`

I discovered this when trying to build develutionx with mingw. cmake was telling me it failed on fmt's big object check. I made this locally and it no longer showed a failure for this compiler option.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/1e96e01766463aeb7737acf4d9f1744d550073bd, thanks for reporting.
