### ISSUE TITLE
How to create a wrapper arround fmt?

### ISSUE THREAD

**Issue by derived-coder** [fmtlib/fmt#2542]
I would like the create a wrapper around fmt to hide this dependency for various reasons and define an own stable API.
I know fmt is a heavy template library. So I think with creating a wrapper, only a subset of fmt can be exported, with specializations.
Can you recommend a strategy how to do this?

**Comment by vitaut** [comment]
Not sure, maybe take a look at https://github.com/gabime/spdlog which bundles {fmt}. I don't think you can completely hide it without modules.
