### ISSUE TITLE
Problem with char array as format string?

### ISSUE THREAD

**Issue by TobyBrull** [fmtlib/fmt#2546]
I suspect the following should compile?
Found at https://github.com/scylladb/seastar/blob/master/tests/unit/log_buf_test.cc#L55

g++ version is 11.1.0
```
g++ --std=gnu+20 bug.cpp -o bug
```
```
#include <fmt/format.h>

#include <vector>

int main() {
  constexpr size_t size = 128;
  char str[size + 1];
  memset(str, 'a', size);
  str[size] = '\0';

  std::vector<char> buffer;
  auto it = buffer.begin();
  fmt::format_to(it, str, size);
}
```

**Comment by vitaut** [comment]
The format string must be known at compile time for compile-time checks. To pass a runtime string wrap it in `fmt::runtime` (https://godbolt.org/z/qv67b9dn5):

```c++
fmt::format_to(it, fmt::runtime(str), size);
```
