### ISSUE TITLE
Is it possible and easy to replace `{}` with `%#`?

### ISSUE THREAD

**Issue by sunlong169** [fmtlib/fmt#2548]
For our project, we are used to the use `%#` to represent a variable to be printed out. Is it possible and easy to replace `{}` with `%#` by modifying the source code of `{fmt}` (which would be used by ourselves )?

Thanks.

**Comment by vitaut** [comment]
It is possible. You can write your own formatting function that uses a different syntax and is based on the {fmt} infra similarly how it is done in `fmt::printf`: https://github.com/fmtlib/fmt/blob/master/include/fmt/printf.h.
