### ISSUE TITLE
conditional expansions

### ISSUE THREAD

**Issue by cruisercoder** [fmtlib/fmt#2556]
I want to format the members of a class in a comma delimited list but omitting empty members.  This is a common debug pattern.

struct person {std::string first,middle, last;};
person p({.first = "john", .last = "doe"});
fmt::format("{}", p);    // output (first: john, last: joe)

Is there an idiomatic way to approach this without a bunch of inline conditionals and separator handling?

**Comment by vitaut** [comment]
Not really. You'll have to implement all the formatting logic and handling empty fields yourself using the extension API: https://fmt.dev/latest/api.html#formatting-user-defined-types.
