### ISSUE TITLE
[MSVC][/std:c++latest][module] error C2065: 'oops_detail_namespace_is_visible': undeclared identifier

### ISSUE THREAD

**Issue by QuellaZhang** [fmtlib/fmt#2557]
Hi All,

I found the follow error when I build the latest source code of Fmt on MSVC with /std:c++latest and module enable, can you help confirm? I used VS2019 16.11.5.

**Build steps:**

1. git clone https://github.com/fmtlib/fmt.git fmt
2. cd fmt
3. enable module test on https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt#L89
4. mkdir build && cd build
5. cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -A x64 -DCMAKE_CXX_STANDARD=20 .. 
6. cmake --build . --config Release --verbose -- /maxcpucount

**Build log**:  [fmt_build.log](https://github.com/fmtlib/fmt/files/7387548/fmt_build.log)

**Error info:**
F:\build\fmt\test\module-test.cc(87,11): error C2065: 'oops_detail_namespace_is_visible': undeclared identifier.

**Comment by vitaut** [comment]
I don't think modules work in MSVC 2019. cc @DanielaE
