### ISSUE TITLE
Library infinite connection time problem

### ISSUE THREAD

**Issue by PabloLigeroIsla** [fmtlib/fmt#2579]
**The problem**
This code is the documented way to establish a connection using Paho:

```
  MQTTClient mqtt_client_;
  MQTTClient_create(&mqtt_client_, "tcp://localhost:1883", "client_id", MQTTCLIENT_PERSISTENCE_NONE, NULL);

  MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
  conn_opts.username = "username";
  conn_opts.password = "password";
  conn_opts.keepAliveInterval = 10;
  conn_opts.cleansession = 1;
  conn_opts.connectTimeout = 1; // <--

  if(MQTTCLIENT_SUCCESS != MQTTClient_connect(mqtt_client_, &conn_opts))
    return false;
```
Please note that a connection timeout of 1 second has been specified.

If the URI to connect to is valid but specifies a port where no daemon is listening (because, for example, the Broker is not started up), then MQTTClient_connect() will wait forever (well, "only" half million years)

**Explanation of the problem.**
The original code has this:

`millisecsTimeout - MQTTTime_elapsed(start)`
but both millisecsTimeout and MQTTTime_elapsed() are of an unsigned type.
So if MQTTTime_elapsed() returns a greater value than millisecsTimeout an overflow will happen.
The problem is exacerbated by the fact that if MQTTTime_elapsed() returns a value smaller but in that time the connection can't be established, then the code will be executed again (is in a loop).
So if the connection can't be established, the program will eventually overflow and will keep waiting forever.

**Proposed Solution**
pho.mqtt.c/src/MQTTClient.c
Line 1216: If condition
```
......

if (m->c->connect_state == TCP_IN_PROGRESS) /* TCP connect started - wait for completion */
{
Thread_unlock_mutex(mqttclient_mutex);
 -      MQTTClient_waitfor(handle, CONNECT, &rc, millisecsTimeout - MQTTTime_elapsed(start));
+	ELAPSED_TIME_TYPE elapsed = MQTTTime_elapsed(start);
+	ELAPSED_TIME_TYPE diff = 0;
+	if(millisecsTimeout > elapsed)
+		diff = millisecsTimeout - elapsed;
+	MQTTClient_waitfor(handle, CONNECT, &rc, diff);
Thread_lock_mutex(mqttclient_mutex);
.......
```

**Comment by OnurKader** [comment]
I think you're in the wrong repo friend

**Comment by PabloLigeroIsla** [comment]
Sure. sorry, my fault I will close the issue.
