### ISSUE TITLE
Warning on GCC 10.3

### ISSUE THREAD

**Issue by shreyasbharath** [fmtlib/fmt#2580]
Hello, thanks for a great library!

Just came across this warning when I tried to compile fmt:

```
format.h:512:27: error: enumerated and non-enumerated type in conditional expression [-Werror=extra]
  512 |     bool result = f(error ? invalid_code_point : cp,
  ```

**Comment by vitaut** [comment]
I wasn't able to repro it in https://godbolt.org/z/f7K7z6nfb. Could you provide more repro details, ideally a godbolt link?

**Comment by vitaut** [comment]
Closing but feel free to reopen with more repro details.
