### ISSUE TITLE
fmt::to_string return wrong result in android platform

### ISSUE THREAD

**Issue by zhuxiaoguang** [fmtlib/fmt#2581]
arm-linux-androideabi-clang++ 
Android clang version 5.0.300080  (based on LLVM 5.0.300080) api-level: 14
c++ standard: c++1z 

int i = 2280;
auto str = fmt::to_string(i);
// str = 280;

int i = 443;
auto str = fmt::to_string(i);
// str = 43;

int i = 6997;
auto str = fmt::to_string(i);
// str = 6997;

int i = 80;
auto str = fmt::to_string(i);
// str = 80;

**Comment by vitaut** [comment]
What {fmt} version you are using?

**Comment by zhuxiaoguang** [comment]
fmt-8.0.1

**Comment by zhuxiaoguang** [comment]
I use fmt-7.1.3 is correct.

**Comment by vitaut** [comment]
Could you bisect by any chance?

**Comment by vitaut** [comment]
Closing as I wasn't able to repro the issue.
