### ISSUE TITLE
`fmt::formatter` specialization with multiple concepts gives redefinition error

### ISSUE THREAD

**Issue by fardream** [fmtlib/fmt#2584]
I am trying to provide customized `fmt::formatter` for different custom types, which are narrowed by concepts. gcc 10.2.0 or 11.2.0 will give  redefinition error. Sample code below:

Two concepts are defined, `IsA` and `IsC`. It will have a redefinition error for `fmt::formatter`, but not for template class `E` defined right below.

```
#include <fmt/core.h>
#include <fmt/format.h>

class A {};
class B : A {};
class C {};
class D : C {};

template <typename T>
concept IsA = std::is_base_of_v<A, T>;
template <typename T>
concept IsC = std::is_base_of_v<C, T>;

template <IsA T>
struct fmt::formatter<T> {
  constexpr auto parse(format_parse_context &ctx) -> decltype(ctx.begin()) {
    auto it = ctx.begin(), end = ctx.end();
    while (it != end && *it != '}') {
      it++;
    }
    return it;
  }
  template <typename FormatContext>
  auto format(const T &p, FormatContext &ctx) -> decltype(ctx.out()) {
    return format_to(ctx.out(), "{:s}", "A");
  }
};

template <IsC T>
struct fmt::formatter<T> {  // this is the redefinition
  constexpr auto parse(format_parse_context &ctx) -> decltype(ctx.begin()) {
    auto it = ctx.begin(), end = ctx.end();
    while (it != end && *it != '}') {
      it++;
    }
    return it;
  }

  template <typename FormatContext>
  auto format(const T &p, FormatContext &ctx) -> decltype(ctx.out()) {
    return format_to(ctx.out(), "{:s}", "C");
  }
};

template <typename T>
class E {};
template <IsA T>
class E<T> {};
template <IsC T>
class E<T> {};  // but this one works

int main(int argc, char **argv) {
  return 0;
}
```

Error message:

```
test_fmt.cc:30:13: error: redefinition of 'struct fmt::v8::formatter<T>'
   30 | struct fmt::formatter<T> {
      |             ^~~~~~~~~~~~
test_fmt.cc:15:13: note: previous definition of 'struct fmt::v8::formatter<T>'
   15 | struct fmt::formatter<T> {
      |             ^~~~~~~~~~~~
```

**Comment by vitaut** [comment]
Could be a compiler bug related to specialization with namespace because the following gives the same error (https://godbolt.org/z/sc8nva1hz):

```c++
#include <type_traits>

class A {};
class B : A {};
class C {};
class D : C {};

template <typename T>
concept IsA = std::is_base_of_v<A, T>;
template <typename T>
concept IsC = std::is_base_of_v<C, T>;

namespace foo {
template <typename T>
struct E {};
}

template <IsA T>
struct foo::E<T> {};
template <IsC T>
struct foo::E<T> {};
```

**Comment by vitaut** [comment]
This observation also gives a workaround:

```
#include <fmt/core.h>
#include <fmt/format.h>

class A {};
class B : A {};
class C {};
class D : C {};

template <typename T>
concept IsA = std::is_base_of_v<A, T>;
template <typename T>
concept IsC = std::is_base_of_v<C, T>;

namespace fmt {
template <IsA T>
struct formatter<T> {
  constexpr auto parse(format_parse_context &ctx) -> decltype(ctx.begin()) {
    auto it = ctx.begin(), end = ctx.end();
    while (it != end && *it != '}') {
      it++;
    }
    return it;
  }
  template <typename FormatContext>
  auto format(const T &p, FormatContext &ctx) -> decltype(ctx.out()) {
    return format_to(ctx.out(), "{:s}", "A");
  }
};

template <IsC T>
struct formatter<T> {  // this is the redefinition
  constexpr auto parse(format_parse_context &ctx) -> decltype(ctx.begin()) {
    auto it = ctx.begin(), end = ctx.end();
    while (it != end && *it != '}') {
      it++;
    }
    return it;
  }

  template <typename FormatContext>
  auto format(const T &p, FormatContext &ctx) -> decltype(ctx.out()) {
    return format_to(ctx.out(), "{:s}", "C");
  }
};
}
```

**Comment by fardream** [comment]
> This observation also gives a workaround:
> 
> ```c++
> #include <fmt/core.h>
> #include <fmt/format.h>
> 
> class A {};
> class B : A {};
> class C {};
> class D : C {};
> 
> template <typename T>
> concept IsA = std::is_base_of_v<A, T>;
> template <typename T>
> concept IsC = std::is_base_of_v<C, T>;
> 
> namespace fmt {
> template <IsA T>
> struct formatter<T> {
>   constexpr auto parse(format_parse_context &ctx) -> decltype(ctx.begin()) {
>     auto it = ctx.begin(), end = ctx.end();
>     while (it != end && *it != '}') {
>       it++;
>     }
>     return it;
>   }
>   template <typename FormatContext>
>   auto format(const T &p, FormatContext &ctx) -> decltype(ctx.out()) {
>     return format_to(ctx.out(), "{:s}", "A");
>   }
> };
> 
> template <IsC T>
> struct formatter<T> {  // this is the redefinition
>   constexpr auto parse(format_parse_context &ctx) -> decltype(ctx.begin()) {
>     auto it = ctx.begin(), end = ctx.end();
>     while (it != end && *it != '}') {
>       it++;
>     }
>     return it;
>   }
> 
>   template <typename FormatContext>
>   auto format(const T &p, FormatContext &ctx) -> decltype(ctx.out()) {
>     return format_to(ctx.out(), "{:s}", "C");
>   }
> };
> }
> ```

Wonderful. I just confirmed this works. Thanks
