### ISSUE TITLE
is_std_string_like types

### ISSUE THREAD

**Issue by matt77hias** [fmtlib/fmt#2585]
**{fmt} version: main**
**compiler: MSVC**

I tried to use `{fmt}` with my own std-like string types, but I do not manage to compile the code without providing explicit formatters. I tried `eastl::string` as well to obtain a minimal reproducible example, and run into the exact same compilation problems:

```c++
#include <fmt/format.h>
#include <fmt/ranges.h>

static_assert(fmt::detail::is_std_string_like< eastl::string >::value);
static_assert(fmt::is_range< eastl::string, char >::value == false);

eastl::string s = "hello";
fmt::format("{}", s);
```
>\fmt\core.h(1657,62): warning C4840: non-portable use of class 'eastl::basic_string<char,eastl::allocator>' as an argument to a variadic function
>\fmt\core.h(1657,62): message : 'eastl::basic_string<char,eastl::allocator>::basic_string' is non-trivial
>\EASTL/string.h(502,3): message : see declaration of 'eastl::basic_string<char,eastl::allocator>::basic_string'
>\fmt\core.h(1657,62): message : the constructor and destructor will not be called; a bitwise copy of the class will be passed as the argument
>\EASTL/string.h(3900,10): message : see declaration of 'eastl::basic_string<char,eastl::allocator>'
>\fmt\core.h(1800): message : see reference to function template instantiation 'fmt::v8::detail::value<Context> fmt::v8::detail::make_arg<true,Context,fmt::v8::detail::type::custom_type,eastl::string&,0>(T)' being compiled
>        with
>        [
>            Context=fmt::v8::format_context,
>            T=eastl::string &
>        ]
>\fmt\core.h(1823): message : see reference to function template instantiation 'fmt::v8::format_arg_store<fmt::v8::format_context,eastl::basic_string<char,eastl::allocator>>::format_arg_store<eastl::string&>(eastl::string &)' being compiled
>\fmt\core.h(1823): message : see reference to function template instantiation 'fmt::v8::format_arg_store<fmt::v8::format_context,eastl::basic_string<char,eastl::allocator>>::format_arg_store<eastl::string&>(eastl::string &)' being compiled
>\fmt\core.h(3067): message : see reference to function template instantiation 'fmt::v8::format_arg_store<fmt::v8::format_context,eastl::basic_string<char,eastl::allocator>> fmt::v8::make_format_args<fmt::v8::format_context,eastl::string&>(eastl::string &)' being compiled
>test.cpp: message : see reference to function template instantiation 'std::string fmt::v8::format<eastl::string&>(fmt::v8::basic_format_string<char,eastl::string &>,eastl::string &)' being compiled
>\fmt\core.h(1679,7): error C2338: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt

I do not find a partial formatter specialization for types satisfying `is_std_string_like`. (`fmt/ranges.h` does contain a partial formatter specialization for types satisfying `is_range_` but not `is_std_string_like`, though.) So how are `is_std_string_like` types handled?

**Edit**: same for gcc and clang: https://godbolt.org/z/eq48nb3oe

**Comment by matt77hias** [comment]
Actually it works for gcc using -std=c++2b: https://godbolt.org/z/bET9xKrGG.
I suspect C++23's range constructor to `std::basic_string_view`.

Is it possible to add a fallback for that range constructor in the meantime?

**Comment by vitaut** [comment]
The `format` function call in your godbolt example doesn't actually use `is_std_string_like`. It uses convertibility to `string_view` to format `eastl::string`. I'm not sure why it works in C++23 but in general it's better to provide a formatter specialization than relying on conversions which might be disabled in the future.

**Comment by matt77hias** [comment]
Well it doesn't work because the convertibility depends on the newly added range constructor being present for `std::basic_string_view` in C++23.

And no it doesn't use `is_std_string_like`, but because `is_std_string_like` is true, there is not a fallback to the partial formatter specialization for ranges, because ranges satisfying `is_std_string_like` are excluded. So you end up in this odd situation where a `std::vector< char >` can be formatted, but `MyString< char >` cannot be formatted as it happens to satisfy `is_std_string_like`.

**Comment by vitaut** [comment]
Strings are not formatted as ranges intentionally so I don't see a problem there. In any case providing a formatter specialization is the way to go.

**Comment by matt77hias** [comment]
> Strings are not formatted as ranges intentionally

Fwiiw orthogonal to that:

```c++
#include <fmt/format.h>
#include <fmt/ranges.h>
#include <vector>

auto main() -> int
{
    std::vector v = { 'h', 'e', 'l', 'l', 'o' };
    fmt::print("{}", v);
    // ['h', 'e', 'l', 'l', 'o'] with -std=c++20
    // hello                     with -std=c++2b

    return 0;
}
```
https://godbolt.org/z/GKvhfd3qr

This is for gcc. Once VS 2022 is rolled out, one will see the same behavior change over there as well.

**Comment by vitaut** [comment]
> Fwiiw orthogonal to that ...

Good catch. A PR to fix this would be welcome.

**Comment by vitaut** [comment]
C++2b issue is caused by problematic implicit conversions introduced by http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1391r4.pdf. There are papers to fix this.
