### ISSUE TITLE
std::chrono::duration<double, ...> precision 0 seems wrong in v8

### ISSUE THREAD

**Issue by lukester1975** [fmtlib/fmt#2587]
Hello

I think this is a regression (judging by #1004 and #1012).

```
#include <fmt/chrono.h>

int main(int argc, char* argv[])
{
    std::chrono::duration<double, std::nano> a { 46.666667 };

    fmt::print("{}\n", a);
    fmt::print("{:.0}\n", a);
    fmt::print("{:.1}\n", a);
    fmt::print("{:.2}\n", a);

    fmt::print("{:.0%Q}\n", a);

    // Workaround
    fmt::print("{:.0f}{:%q}\n", a.count(), a);    
}
```

With v8.0.1 (https://godbolt.org/z/jMe7hGW6M):

```
46.6667ns
50ns
46.7ns
46.67ns
50
47ns
```

With 7.1.3 (https://godbolt.org/z/1WxxfhKd4) things are saner:
```
46.6667ns
47ns
46.7ns
46.67ns
47
47ns
```

If it should work, maybe `test/chrono-test.cc` needs a 0 dp test?

Thanks

**Comment by vitaut** [comment]
Looks like the problem is that https://github.com/fmtlib/fmt/blob/e67f92c55cb97558f2311a5fd544b9325b4651d0/include/fmt/chrono.h#L926

incorrectly uses 0 to denote "no precision". A PR to fix this would be welcome.

**Comment by lukester1975** [comment]
Well I don't know enough about the code to know if it's correct, but here's an attempt: #2588

Added a few more tests for rounding and precision 0 and they all pass, though maybe more could be added.

HTH
