### ISSUE TITLE
Can't print map<string, any> [duplicate, please remove]

### ISSUE THREAD

**Issue by FisherDock** [fmtlib/fmt#2589]
Hi,

I tried to print map<string, any> using {fmt}, but compiler(Clang12, C++17) says

In template: cannot pass object of non-trivial type 'std::map<std::basic_string<char>, std::any>' through variadic method; call will abort at runtime.

Is there a way to print the map container? I also want to convert the map to a JSON string.

Thank you.

**Comment by vitaut** [comment]
{fmt} doesn't provide a formatter for `std::any`, you'll need to provide your own via https://fmt.dev/latest/api.html#formatting-user-defined-types.
