### ISSUE TITLE
Separate overload/function for checking exact match of parameter count

### ISSUE THREAD

**Issue by sfc-gh-sgiesecke** [fmtlib/fmt#2593]
While it has been noted on #492 that there may be use cases where not all parameters are used, there are also use cases where this would be considered a misuse. 

> It might be reasonable to provide a separate overload that performs this check, or perhaps even allowing the user to specify which checks he wants with a bitflag mechanism

_Originally posted by @Folling in https://github.com/fmtlib/fmt/issues/492#issuecomment-916012098_

The actual check could be based on https://github.com/leoetlino/dolphin/commit/97eafa6babbf48235ce28826472c74b1a9952f5f

**Comment by vitaut** [comment]
Thanks for the suggestions. There are no plans to add such overload(s) to the core library but they can be implemented externally as shown in the linked commit.
