### ISSUE TITLE
Unexpected behaviour for mixing named and numerical arguments

### ISSUE THREAD

**Issue by littlelordy** [fmtlib/fmt#2596]
I have the following code

```
# include <fmt/core.h>

int main()
{
   fmt::print("The answer is {answer}, the integer is {:d}\n", fmt::arg("answer", 42), 1);
}
```
This outputs:
> The answer is 42, the integer is 42

To get the expected output 
> The answer is 42, the integer is 1

I need to add the numerical arg_id

```
...
   fmt::print("The answer is {answer}, the integer is {1:d}\n", fmt::arg("answer", 42), 1);
...
```
Is this the intended behaviour? I would've expected, that numerical arg_ids and named arg_ids are somehow distinguished and as long as the numerical arguments are in the right order the numerical arg_ids can be omitted like mentioned in the [Format String Syntax documentation](https://fmt.dev/latest/syntax.html#formatexamples).

**Comment by sunmy2019** [comment]
From the [Format String Syntax documentation](https://fmt.dev/latest/syntax.html#formatexamples)
> Named arguments can be referred to by their names or indices.

So it is intended. The order matters.

**Comment by littlelordy** [comment]
ok, thanks for the answer. I will close this ticket then.
