### ISSUE TITLE
formatting a pointer doesn't work for fmtlib 8.0.x

### ISSUE THREAD

**Issue by martinwuehrer** [fmtlib/fmt#2597]
Hi,

i wanted to format a pointer of a forward declared type with help of fmtlib.
This forward declared type is defined inside a C-library, which also provides a `get_string()`-function.
I wanted to create an ostream-operator-overload for this type and use the `get_string()`-function inside this overload.

I tried to sketch this idea in the following example:
```
#include <fmt/format.h>
#include <fmt/ostream.h>
#include <iostream>

struct ostream_formatable_hidden_t;
const char * get_string(const ostream_formatable_hidden_t* const) {
    return "ostream_formatable_hidden_t-instance";
}

std::ostream& operator<<(std::ostream& os, ostream_formatable_hidden_t* const inst) {
    os << get_string(inst);
    return os;
}

int main() {
    ostream_formatable_hidden_t* ofh{nullptr};
    std::cout << fmt::format("{}", ofh) << std::endl;
}

```
This sketch compiled with fmtlib 7.1.3 and if the binary was executed, it printed out `ostream_formatable_hidden_t-instance`.
However, if I take the same code and bump fmtlib to 8.0.1 I get the following compiler-error:
[compiler_error.txt](https://github.com/fmtlib/fmt/files/7520796/compiler_error.txt)
I am using gcc-10 on debian bullseye.

Then I tried the same with custom formatters instead of the ostream-operator:
```
#include <fmt/format.h>
#include <iostream>

struct formatter_formatable_hidden_t;
const char * get_string(const formatter_formatable_hidden_t* const) {
    return "formatter_formatable_hidden_t-instance";
}

template <> struct fmt::formatter<formatter_formatable_hidden_t*> {
  constexpr auto parse(format_parse_context& ctx) -> decltype(ctx.begin()) {
    auto it = ctx.begin();
    if (it != ctx.end() && *it != '}') {
      throw format_error("invalid format");
    }
    return it;
  }

  template <typename FormatContext>
  auto format(formatter_formatable_hidden_t* const inst, FormatContext& ctx) -> decltype(ctx.out()) {
    return format_to(ctx.out(), get_string(inst));
  }
};

int main() {
    formatter_formatable_hidden_t* ffh{nullptr};
    std::cout << fmt::format("{}", ffh) << std::endl;
}

```
This sketch compiled with fmtlib 7.1.3 and if the binary was executed, it printed out `formatter_formatable_hidden_t-instance`.
However, if I take the same code and bump fmtlib to 8.0.1 I get the following compiler-error:
[compiler_error_2.txt](https://github.com/fmtlib/fmt/files/7520814/compiler_error_2.txt)

So my question is: Why is it not possible to format a pointer with fmtlib 8.0.1 whereas it was possible with fmtlib 7.1.3?
And yes, I am aware about formatting a non-pointer type (see the code below), but as I already mentioned, I want to format a pointer originating from a c-library. (Therefore, all I have is the prototype of the class and nothing more.)

```
#include <fmt/format.h>
#include <fmt/ostream.h>
#include <iostream>

struct formatter_formatable_t {};
const char * get_string(const formatter_formatable_t&) {
    return "formatter_formatable_t-instance";
}

struct ostream_formatable_t {};
const char * get_string(const ostream_formatable_t&) {
    return "ostream_formatable_t-instance";
}

template <> struct fmt::formatter<formatter_formatable_t> {
  constexpr auto parse(format_parse_context& ctx) -> decltype(ctx.begin()) {
    auto it = ctx.begin();
    if (it != ctx.end() && *it != '}') {
      throw format_error("invalid format");
    }
    return it;
  }

  template <typename FormatContext>
  auto format(const formatter_formatable_t& inst, FormatContext& ctx) -> decltype(ctx.out()) {
    return format_to(ctx.out(), get_string(inst));
  }
};

std::ostream& operator<<(std::ostream& os, const ostream_formatable_t& inst) {
    os << get_string(inst);
    return os;
}

int main() {
    formatter_formatable_t ff;
    std::cout << fmt::format("{}", ff) << std::endl;

    ostream_formatable_t of;
    std::cout << fmt::format("{}", of) << std::endl;
}
```

**Comment by vitaut** [comment]
This is essentially the same issue as #2452.

**Comment by martinwuehrer** [comment]
Thank you, so what would you suggest instead?
Wrapping everything inside a non-pointer-type?

**Comment by vitaut** [comment]
Either dereferencing a pointer or using a wrapper type.

**Comment by martinwuehrer** [comment]
Ok thank you.
