### ISSUE TITLE
Types implicitly convertible to pointers aren't caught by non-void-pointer rejection

### ISSUE THREAD

**Issue by tellowkrinkle** [fmtlib/fmt#2598]
Attempting to format non-void, non-char pointers normally leads to a compiler error, but attempting to format a class with an implicit conversion to a non-void, non-char pointer (e.g. a `wchar_t`) is not caught.

[Example (click to view on compiler explorer):](https://gcc.godbolt.org/z/4cTrG9Kcz)
```cpp
#include <fmt/core.h>

template <typename T>
struct Pointer {
    T* value;
    operator T*() const { return value; }
};

/*
// Errors as expected
std::string format(wchar_t* p) {
    return fmt::format("{}", p);
}

// Errors as expected
std::string format(int* p) {
    return fmt::format("{}", p);
}
*/

// Should error as well, but instead formats as void*
std::string format(Pointer<wchar_t> p) {
    return fmt::format("{}", p);
}

// Should error as well, but instead formats as void*
std::string format(Pointer<int> p) {
    return fmt::format("{}", p);
}
```

**Comment by vitaut** [comment]
Turned this into an error in https://github.com/fmtlib/fmt/commit/5380ff4d8866d2f37d706859c6223bc22d17dc98. Thanks for reporting.
