### ISSUE TITLE
Error compiling with Visual Studio 2022 Platform Toolset v143 + /std:c++20 (but OK in Platform Toolset v142 or /std:c++17)

### ISSUE THREAD

**Issue by Spammed** [fmtlib/fmt#2608]
Hello Vitaut,
I have a problem with the latest version of Visual Studio respectively the related Platform Toolset v143 in combination with /std:c++20 or higher. 
This code [example ](https://godbolt.org/z/3v7Gr8xbY) does not compile (with Platform Toolset v143 + /std:c++20):
```
#define FMT_HEADER_ONLY
#include <fmt\core.h>

template<typename ...Args>
void fmt_out(Args&& ...args) {
	fmt::print(args...);
};

int main()
{
	fmt_out("Hello {}\n", "World");
}

```

with this error message (shortened):

> check_fmt.cpp(6,13): error C7595: 'fmt::v8::basic_format_string<char,const char (&)[6]>::basic_format_string': call to immediate function is not a constant expression
> check_fmt.cpp(6,13): message : failure was caused by a read of a variable outside its lifetime
> check_fmt.cpp(6,13): message : see usage of '<args_0>'
> check_fmt.cpp(11): message : see reference to function template instantiation 'void fmt_out<const char(&)[10],const char(&)[6]>(const char (&)[10],const char (&)[6])' being compiled
> 

There is no problem with Platform Toolset v143 with /std:c++17 or lower 
or with Platform Toolset v142 in any language setting.

In my opinion it is quite possible that the cause is a Visual Studio problem, but maybe {fmt} can work around it :-) .

**Comment by vitaut** [comment]
This is expected: the format string must be know at compile time. It can be fixed as follows:

```c++
#include <fmt/core.h>

template <typename ...Args>
void fmt_out(fmt::format_string<Args...> fmt, Args&& ...args) {
  fmt::print(fmt, args...);
};

int main() {
  fmt_out("Hello {}\n", "World");
}
```

**Comment by Spammed** [comment]
Oh!
Sorry for running in this issue (trap?) again,
If there is a way to drop an error message in cases like this that is instructive for people like me, that would be great.
(Would make the great library even easier to use.)
Thanks for pointing out what to do.

**Comment by vitaut** [comment]
I don't think we can improve the error message here.

**Comment by Spammed** [comment]
Not even with Concepts?
But that is beyond my horizon, 
so don't let me disturb you.

**Comment by vitaut** [comment]
This is more about the ability to evaluate an expression at compile-type rather than types so I don't think concepts apply here. IMHO the current message is not too bad even in msvc because it does suggest that `basic_format_string` is not a constant expression.

**Comment by Spammed** [comment]
Ok, yes. 
The current MSVC message hadn't given me the right idea, unfortunately. Probably a matter of practice.
Anyway, thanks for your patience and time.
