### ISSUE TITLE
Is there a way to find out how many arguments are required by a format string?

### ISSUE THREAD

**Issue by p-ranav** [fmtlib/fmt#2618]
### Expected Behavior:

```cpp
const auto num_args = fmt::required_args_count("Hello {}, My name is {}.");
// num_args == 2
```

Maybe such an API is internally available and could be exposed?

**Comment by vitaut** [comment]
There is no such API, only the general parsing method (internal): https://github.com/fmtlib/fmt/blob/201971e293be35a2b21296404d17129a0429e0c8/include/fmt/core.h#L2583-L2585.
