### ISSUE TITLE
arg_mapper question

### ISSUE THREAD

**Issue by seanbaxter** [fmtlib/fmt#2622]
I pulled the current version of this library to build with Circle, and the tests don't compile now. I'm hitting this static assert:

```
ODR used by: fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, fmt::join_view<const int*, const int*, char>>::format_arg_store(fmt::join_view<const int*, const int*, char>&)
/home/sean/projects/fmt/include/fmt/core.h:1827:77
            detail::mapped_type_constant<remove_cvref_t<T>, Context>::value>( 
                                                                            ^

  instantiation: /home/sean/projects/fmt/include/fmt/core.h:1677:67
  during instantiation of function template fmt::detail::value<fmt::basic_format_context<fmt::appender, char>> fmt::detail::make_arg(fmt::join_view<const int*, const int*, char>&)
  template arguments: [
    'IS_PACKED' = bool true
    'Context' = fmt::basic_format_context<fmt::appender, char>
      class 'basic_format_context' declared at /home/sean/projects/fmt/include/fmt/core.h:1714:45
    '2' = fmt::detail::type custom_type
    'T' = fmt::join_view<const int*, const int*, char>&
      class 'join_view' declared at /home/sean/projects/fmt/include/fmt/format.h:2749:1
    '4' = std::enable_if<true, int>::type 0
  ]
  FMT_CONSTEXPR FMT_INLINE auto make_arg(T&& val) -> value<Context> { 
                                                                    ^
    error: /home/sean/projects/fmt/include/fmt/core.h:1699:3
    ... included from /home/sean/projects/fmt/include/fmt/format.h:48:10
    ... included from /home/sean/projects/fmt/include/fmt/os.h:22:10
    ... included from /home/sean/projects/fmt/test/os-test.cc:8:10
    static_assert failed; message: "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
      static_assert( 
      ^
```

So there's a compiler bug, but it's hard to see what should be happening. Given that T is `fmt::join_view<const int*, const int*, char>&`, which of the 37 overloads of `arg_mapper::map` should be matching this argument? Right now the parameter is only matching the ellipsis version here:
  https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L1452,
so that the unwanted `unformattable` type is being returned.

I'm guessing that one of the traits in a constraint on a map overload is doing the wrong thing, knocking it out of the overload set, but I have no idea which overload it should be, or what the bad constraint is. Any clues are appreciated.

thanks,
sean

**Comment by vitaut** [comment]
`join_view` has a `formatter` specialization so this is the relevant overload: https://github.com/fmtlib/fmt/blob/ec3b097cb98f1f50c6e9f7fd2ddfae885522de74/include/fmt/core.h#L1436-L1444

**Comment by seanbaxter** [comment]
Thanks, that was helpful.
