### ISSUE TITLE
`operator bool` takes precedence over ostream after 6.1

### ISSUE THREAD

**Issue by timblechmann** [fmtlib/fmt#2624]
```
class Symbol
{
public:
  string string() const { return m_string; }
  operator bool() const { return !m_string.empty(); }

private:
  std::string m_string {"test"};
};

ostream& operator<< (ostream& os, const Symbol& symbol)
{
    os << symbol.string();
    return os;
}
```

the implicit bool conversion confuses fmt:
* 6.0: format / sprintf give "test"
* 6.1: format gives "true, sprintf gives "test"
* 6.2: format / sprintf give "true"

my coworker came up with this reproducer on godbolt: https://godbolt.org/z/ffGf49W43

**Comment by vitaut** [comment]
Unfortunately there is no good way to handle ambiguous cases like this. You can provide an `formatter` specialization to suppress the implicit conversion.

**Comment by timblechmann** [comment]
unfortunately the custom `formatter` is only applied with `fmt::format`, not with `fmt::sprintf`

**Comment by vitaut** [comment]
`sprintf` is mostly for migrating legacy code and doesn't support ostreams.
