### ISSUE TITLE
Is there a correct way to do post-translator checks? An analogue of msgfmt --check-format?

### ISSUE THREAD

**Issue by gendalph** [fmtlib/fmt#2626]
[Compiler Explorer C++ Editor #[object Object] Code.txt](https://github.com/fmtlib/fmt/files/7636713/Compiler.Explorer.C%2B%2B.Editor.object.Object.Code.txt)

**Comment by gendalph** [comment]
In my workflow I used compiler checks like printf ("%s", 1, 2);

And checks after translators msgfmt --check-format.

**Comment by gendalph** [comment]
This approach allowed us to minimize runtime errors and check everything at compile time and earlier.

However, my colleagues added several thousand messages using fmt::format and I got a headache in production after the translators.

And garbage in the code if the number of arguments is more than {} in the format string.

**Comment by vitaut** [comment]
I am not aware of any out-of-the-box solution but you could probably write a script that extracts format strings and checks that replacement fields are consistent with the ones in the translation database. For this you don't need to do full parsing just extract parts in `{...}`.

**Comment by gendalph** [comment]
**Thanks**.
This is fine for very simple lines with format like {} and of course I have to make such a simple script.

But for more complex constructs, it already looks like the _giblets_ of the gettext utility in which there are limited checks for the python stock - are there any plans to develop this part of gettext?

**Comment by vitaut** [comment]
There are no such plans at the moment.

**Comment by gendalph** [comment]
```
“Suffering is optional.”
– Haruki Murakami
```
И меркнет свет. И молкнут звуки,
И новые муки ищут руки.
И если боль твоя стихает,
Значит будет новая беда.

Кто виноват и в чем секрет,...

– Воскресение, Машина времени

I'll try to negotiate with the authors of gettext. Thank you for the attention.
