### ISSUE TITLE
interpreting { from argument 

### ISSUE THREAD

**Issue by hero2002** [fmtlib/fmt#2631]
so I am using 
```c++
fmt::format("{} {} \n", magic_enum::enum_name(type), lexeme);
```
which work correctly when I don't pass ``{`` in the lexeme 
it then interpret it as new arg 
and it throw  the argument not found error
how I can I avoid that error?
code example [https://godbolt.org/z/YGfhWj3PM](url)

**Comment by vitaut** [comment]
You should pass the string as an argument, not as a format string to `print`:

```c++
  auto s = std::string("{");
  auto o = fmt::format("{} {}\n", "LEFT_BRACE (2)", "{asdS}");
  fmt::print("{}", o);
```

In {fmt} 8.x and C++20 you'll get a compile-time error when trying to pass `std::string` as a format string.

**Comment by hero2002** [comment]
ahh thanks for the help
