### ISSUE TITLE
fmt::is_formattable is false for std::string

### ISSUE THREAD

**Issue by jsmolka** [fmtlib/fmt#2637]
Hello,
I am trying to create a C++20 concept to check if a type is formattable and `fmt::is_formattable` seems to be the way to go. Unfortunately `std::string` and `std::string_view` are `false` even though I suspected them to be `true`. Is that expected behavior / do you know a better way to check inside a concept?

**Comment by vitaut** [comment]
AFAICS `is_formattable` returns true for `string`: https://godbolt.org/z/fzfE5GGvj.

**Comment by jsmolka** [comment]
```cpp
int main() {
  fmt::print("{}\n", fmt::is_formattable<std::string>::value);
  fmt::print("{}\n", fmt::is_formattable<std::string>());
}
```

Prints `false` two times for me when using MSVC with `/std:c++latest`.

**Comment by vitaut** [comment]
Seems to be working on msvc too: https://godbolt.org/z/vaEKPrdEo.

**Comment by jsmolka** [comment]
I did some testing and it appears that including `<fmt/ostream.h>` causes the problem.
https://godbolt.org/z/fjrseEEsT

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/e4f0564aa64175eaef04fd1f4fb168a730b55072. Thanks for reporting.

**Comment by jsmolka** [comment]
Thank you for the great library. It's a joy to use :)
