### ISSUE TITLE
dynamic_format_arg_store move constructor is not automatically generated

### ISSUE THREAD

**Issue by lucpelletier** [fmtlib/fmt#2654]
dynamic_format_arg_store has a copy constructor but no explicitly declared move constructor / move assignment operator. These are not automatically generated and any attempts to call the move constructor of dynamic_format_arg_store results in calling the copy constructor. See the following link for quotes from the c++ standard that explicitly state when assignment operators / constructors are automatically generated:

https://stackoverflow.com/questions/4943958/conditions-for-automatic-generation-of-default-copy-move-ctor-and-copy-move-assi

If library maintainers agree that this is a problem that should be fixed, I'm happy to provide a PR to explicitly declare assignment operators and the move constructor.

**Comment by vitaut** [comment]
It is not a problem but a PR would be welcome provided that you have an actual use case that would benefit from this optimization.
