### ISSUE TITLE
Issue with using fmt::formatter<string_view>

### ISSUE THREAD

**Issue by brett19** [fmtlib/fmt#2656]
I've been fighting the following error for the last few hours while trying to build a custom formatter which inherits from the string_view formatter (as shown in the documentation).  I'm using the current master (as using 8.0.1 leads to complaints around `throw_format_error` not being defined).

Code:
```
template<>
struct fmt::formatter<Test> : formatter<string_view> {
    template<typename FormatContext>
    auto format(Test test, FormatContext& ctx) const
    {
        string_view name = "unknown";
        return formatter<string_view>::format(name, ctx);
    }
};
```

Error:
```
undefined reference to `decltype (({parm#2}.out)()) fmt::v8::formatter<fmt::v8::basic_string_view<char>, char, void>::format<fmt::v8::basic_format_context<fmt::v8::appender, char> >(fmt::v8::basic_string_view<char> const&, fmt::v8::basic_format_context<fmt::v8::appender, char>&) const'
```

Minimal Repro:
https://godbolt.org/z/9oYc4PdPz

**Comment by vitaut** [comment]
`fmt/core.h` only provides a subset of formatting functions, nor formatter specializations. For the latter you should include `fmt/format.h` as shown in the example: https://fmt.dev/latest/api.html#formatting-user-defined-types.
