### ISSUE TITLE
format_to with basic_memory_buffer deprecated but still mentioned in docs

### ISSUE THREAD

**Issue by tohammer** [fmtlib/fmt#2659]
Calling format_to with basic_memory_buffer was deprecated for 8.0.0 but the documentation seems not fully updated.
The docs for basic_memory_buffer still have the deprecated usage as an example.

Additionally, there seem to be no mention of this change in the changelog, it would be good to have it there and also mention how to transition to the now recommended usage.

**Comment by vitaut** [comment]
The example has been updated in https://fmt.dev/dev/api.html. I don't think `format_to` overload that takes `basic_memory_buffer` has ever been documented.

**Comment by vitaut** [comment]
Same as #2436.

**Comment by vitaut** [comment]
Added an entry to https://github.com/fmtlib/fmt/blob/master/ChangeLog.rst.
