### ISSUE TITLE
compile error with MSVC 2022 / 17.0.4, when used with non-literal format string

### ISSUE THREAD

**Issue by m5k8** [fmtlib/fmt#2660]
Hi,

I have a code like this:

`fmt::format(_("some text {} ..."), some_args)`

where _() is gettext translate(). It compiled fine with previous version of MSVC (2019 16.x), gcc 11 and clang 12&13.
After compiler upgrade to MSVC 2022 17.0.4 version, here comes the error report:

error C7595: 'fmt::v8::basic_format_string<char,lbxs::call_cmd &>::basic_format_string': call to immediate function is not a constant expression
message : failure was caused by call of undefined function or one not declared 'constexpr'
message : see usage of 'translate'

translate() returns const char*.

Compiler issue, or fmtlib issue?

**Comment by vitaut** [comment]
Format string must be known at compile time. To pass a runtime string, wrap it in `fmt::runtime`:

```c++
fmt::format(fmt::runtime(_("some text {} ...")), some_args)
```

**Comment by m5k8** [comment]
Thank you very much!
