### ISSUE TITLE
segfault with customer formatter

### ISSUE THREAD

**Issue by matthijs** [fmtlib/fmt#2666]
Hi,

I've created a minimal example that segfaults somehow (tested with clang 12.0.1) and using the latest release of fmt (8.0.1).

On godbolt: https://godbolt.org/z/W3hdPvKGG and pasted below if the link isn't accessible anymore:
```c++
#include <fmt/core.h>
#include <fmt/format.h>

#include <boost/multiprecision/cpp_dec_float.hpp>

using large_number_t =
    boost::multiprecision::number<boost::multiprecision::cpp_dec_float<15>>;

template <> struct fmt::formatter<large_number_t> {
  template <typename ParseContext>
  constexpr auto parse(ParseContext &ctx) -> decltype(ctx.begin()) {
    auto it = ctx.begin(), end = ctx.end();
    it++;
    if (it != end && *it != '}')
    {
      throw format_error("invalid format for large_number_t");
    }

    return it;
  }

  template <typename FormatContext>
  auto format(const large_number_t &value, FormatContext &ctx)
      -> decltype(ctx.out()) {
    return format_to(ctx.out(), "{}",
                     value.str(std::numeric_limits<large_number_t>::digits));
  }
};

int main(int argc, char **argv) {
  large_number_t x{"0.01"};
  fmt::print("{}", x);
  return 0;
}
```
I know that multiprecission can be printed by using the <fmt/ostream.h> but I use it a bit differently and thats why I need the custom formatter.

Probably I am doing something wrong here, but I dont understand what at this point and the gdb trace isnt that helpful (at least to me).

I am not sure if this is a bug or me doing something wrong.

Regards, Matthijs

**Comment by vitaut** [comment]
You are accessing past the end in `it++` (line 13).
