### ISSUE TITLE
Enable disambiguation between fmt/ranges.h and a user's formatter.

### ISSUE THREAD

**Issue by ldalessa** [fmtlib/fmt#2667]
When I have a class template that models `std::range` and I provide a `fmt::formatter` partial template specialization for that class template, and `fmt/ranges.h` happens to get included somewhere, the `fmtlib` range specialization and the UDT specialization become ambiguous.

https://godbolt.org/z/Mzhb1coMf

A temporary workaround proposed by @kitegi on `#include` was to copy over parts of the range specialization in order to force an order between the UDT formatter and the fmt/ranges.h.

https://godbolt.org/z/8Kr9GjbEG

**Comment by vitaut** [comment]
You can opt out a type from being detected as a range via the `fmt::is_range` trait:

```c++
template <std::floating_point T>
struct fmt::is_range<ns::Foo<T>, char> : std::false_type {};
```

https://godbolt.org/z/TaqPzc5s1

**Comment by ldalessa** [comment]
Oh, that's great, thank you. Maybe this could become a documentation PR associated with the discussion of UDT at https://fmt.dev/latest/api.html#udt?

**Comment by vitaut** [comment]
Sure, a PR would be welcome. I think it belongs in the https://fmt.dev/latest/api.html#ranges-and-tuple-formatting section.
