### ISSUE TITLE
error: 'const struct tm' has no member named 'tm_gmtoff'

### ISSUE THREAD

**Issue by HazardyKnusperkeks** [fmtlib/fmt#2670]
This is in chrono.h line 1080. And on line 1102 `tm_zone` is also not available.
I'm on Windows using msys2 MinGW.
I found something similar: http://hg.savannah.gnu.org/hgweb/octave/rev/1126c2907878

**Comment by phprus** [comment]
Possible fix: #2671
Test it please.

**Comment by HazardyKnusperkeks** [comment]
That fixes it, thanks.
