### ISSUE TITLE
Sign not working with integers with width specificator

### ISSUE THREAD

**Issue by fregate** [fmtlib/fmt#2679]
Hi

want to print [sign][width:2][fill:0] string (like +01)
format_spec ::=  [[fill]align][sign]["#"]["0"][width]["." precision]["L"][type]

[fill:0][+][2][d] => :0+2d
format("{:0+2d}", 1) == +1

format("{:+02d}", 1) == +1
format("{:0>+2d}", 1) == +1
,
so I printed it only with 2 parameters
format("{:c}{:02}", (1 < 0 ? '-' : '+'), std::abs(1))  == +01
is it the only way? Or I didn't understand spec?

Thanks in advance

**Comment by vitaut** [comment]
You can do it as follows:

```c++
fmt::print("{:+03}", 7);
```
Note that you have to use the width of 3 to account for the sign. Please see https://fmt.dev/latest/syntax.html for more details on the format string syntax.

**Comment by fregate** [comment]
Oh! [sign]-specifier also count as decimal place! Thanks! It is not obvious
