### ISSUE TITLE
UTF8 doesn't work with text styles

### ISSUE THREAD

**Issue by walge-laine** [fmtlib/fmt#2681]
I'm using vs2022 and have set `/utf-8` option.
Thr example code 
`fmt::print(
  "┌{0:─^{2}}┐\n"
  "│{1: ^{2}}│\n"
  "└{0:─^{2}}┘\n", "", "Hello, world!", 20);`
works fine.
But when I try to add some text style,
`fmt::print(fmt::fg(fmt::color::red),
  "┌{0:─^{2}}┐\n"
  "│{1: ^{2}}│\n"
  "└{0:─^{2}}┘\n", "", "Hello, world!", 20);`
the output get garbled.

**Comment by vitaut** [comment]
What output do you get?

**Comment by vitaut** [comment]
Probably the same as #1794. Note that not all versions of windows console support ANSI escape sequences.

**Comment by walge-laine** [comment]
> Probably the same as #1794. Note that not all versions of windows console support ANSI escape sequences. If this is a different issue please provide more details.

Sorry but I'm afraid it's not the same issue. To be clear, utf8 characters and text styles works fine individually, but they just cannot be combined.
```
fmt::print(
    "┌─┐\n"
    "│ │\n"
    "└─┘\n");
fmt::print(fg(fmt::color::red), "hello\n");
fmt::print(bg(fmt::color::green), "hello\n");
fmt::print(fg(fmt::color::red),
    "┌─┐\n"
    "│ │\n"
    "└─┘\n");
```
![image](https://user-images.githubusercontent.com/65618530/147686863-8e59c0cf-f6e9-4661-ace9-ce3b27f93090.png)
