### ISSUE TITLE
Chrono formatter does not work if FMT_STATIC_THOUSANDS_SEPARATOR is defined

### ISSUE THREAD

**Issue by gsjaardema** [fmtlib/fmt#2689]
In fmt-8.1.0, I get an undefined symbol warning if I use `#define FMT_STATIC_THOUSANDS_SEPARATOR ','`

For example:
```
#include "fmt/chrono.h"

std::string time_stamp(const std::string &format)
{
  if (format == "") {
    return std::string("");
  }

  time_t      calendar_time = std::time(nullptr);
  struct tm * local_time    = std::localtime(&calendar_time);
  std::string time_string   = fmt::format(format, *local_time);
  return time_string;
}

int main()
{
  std::string tsFormat = "[{:%H:%M:%S}] ";
  auto ts = time_stamp(tsFormat);
  fmt::print("{}\n", ts);
}
```

If I compile with `g++ -DFMT_HEADER_ONLY -I include time_stamp.C`, it works.  

If I compile with `g++ -DFMT_HEADER_ONLY -DFMT_STATIC_THOUSANDS_SEPARATOR=\',\' -I include time_stamp.C`, I get:
```
Undefined symbols for architecture x86_64:
  "__ZNK3fmt2v86detail10locale_ref3getISt6localeEET_v", referenced from:
      __ZN3fmt2v86detail10get_localeC1EbNS1_10locale_refE in ccDqSfBU.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

**Comment by vitaut** [comment]
Chrono formatting requires locale support while `FMT_STATIC_THOUSANDS_SEPARATOR` disables it so the error is expected although it could probably be diagnosed better.

**Comment by gsjaardema** [comment]
Up until 8.1.0, this worked fine.  It only broke with 8.1.0 release.  So did the requirement change at 8.1.0 and is this documented somewhere that you cannot now use chrono if `FMT_STATIC_THOUSANDS_SEPARATOR` is defined?

**Comment by vitaut** [comment]
The implicit requirement was always there but the locale support was not implemented until 8.1.0 which is why it happened to work. I don't think `FMT_STATIC_THOUSANDS_SEPARATOR` is documented anywhere at all (a PR to document it would be welcome).

**Comment by delaitre-manfrotto** [comment]
we have similar issue
we use FMT_STATIC_THOUSANDS_SEPARATOR because we target embedded and using locale just make the binary size way too big
we just need a simple way to deactivate all locale support from fmt while still having some kind of default formatting for fmt, including chrono support

**Comment by vitaut** [comment]
As commented elsewhere:

> A PR to conditionally compile locale dependency in chrono would be welcome.
