### ISSUE TITLE
8.1.1 map is deprecated 

### ISSUE THREAD

**Issue by NePutin94** [fmtlib/fmt#2705]
I use fmt v8.1.1.
Map is now [deprecated](https://github.com/fmtlib/fmt/blob/3c98f1a4cddfab42e9f8f85925d035412b7c1493/include/fmt/core.h#L1394) and when I do something like this:
```C++
        template<typename... Args>
        void func(const std::string& str, Args&& ... args)
        {
            auto str = vformat(str, fmt::make_format_args(args...));
        }
```
And I get a lot of warnings ```arg_mapper::map(const unsigned char*)``` is deprecated. How do I pass a raw string as a parameter correctly?

**Comment by vitaut** [comment]
You should only get a warning when passing `[un]signed char*` and not when passing normal strings and objects of other types, e.g. https://godbolt.org/z/Edc7KbnnW. If this is not the case please provide a self-contained example (preferably on godbolt) that reproduces the warning.

**Comment by NePutin94** [comment]
Yes, it is. In opengl ```glGetString()``` returns ```const unsigned char*```. Now there is only one way to pass a ```const unsigned char*``` string - by wrapping it in ```std::string```?

**Comment by vitaut** [comment]
> Now there is only one way to pass a const unsigned char* string - by wrapping it in std::string?

You can map it (via reinterpret_cast) to `const char*`.

**Comment by MarkCallow** [comment]
> You should only get a warning when passing [un]signed char* and not when passing normal strings and objects of other types

I got the warning when passing in an enum, e.g

```
enum foo {
   A = 0, B = -1, C = 1
} bar;
```

I had to add `static_cast<int>(bar)` to fix it. You can't use `reinterpret_cast` on an enum.

**Comment by vitaut** [comment]
You can also make enums formattable as integers with `format_as`, please see https://fmt.dev/latest/api.html#formatting-user-defined-types.

**Comment by MarkCallow** [comment]
> You can also make enums formattable as integers with format_as

The enum of interest is a non-class enum and is defined in the namespace of a package I am using:

```
namespace jpgd {
    enum jpgd_status { };
}
```

I cannot change that package so whatever I need to do has to be done outside the package's namespace declaration. I am struggling to see how to use `format_as` in this case. Is it possible or must I create an overloaded `<<` operator instead? If I could change the package, is it possible to use `format_as` with non-class enums?

**Comment by vitaut** [comment]
In general it is not recommended but you can define symbols in other "package" namespaces without changing those "packages". Alternatively you can use `fmt::underlying` or `std::to_underlying` at call sites instead of making an enum formattable.

**Comment by MarkCallow** [comment]
> In general it is not recommended

I don't have a choice so I did
```
namespace jpgd {
    int format_as(jpgd_status s) { return fmt::underlying(s); }
}
```
which works. Then I wanted to give my users more friendly output than a code number so I tried to implement a
formatter specialization following the example in the docs [here](https://fmt.dev/latest/api.html#formatting-user-defined-types).
```
template <> struct fmt::formatter<jpgd_status>: formatter<string_view> {
  // parse is inherited from formatter<string_view>.
  template <typename FormatContext>
  auto format(jpgd_status s, FormatContext& ctx) const -> decltype(ctx.out) {
      string_view name = "unknown";
      switch (s) {
        case JPGD_SUCCESS: name = "JPGD_SUCCESS"; break;
        case JPGD_FAILED: name = "JPGD_FAILED"; break;
        case JPGD_DONE: name = "JPGD_DONE"; break;
        case JPGD_BAD_DHT_COUNTS: name = "JPGD_BAD_DHT_COUNTS"; break;
        case JPGD_BAD_DHT_INDEX: name = "JPGD_BAD_DHT_INDEX"; break;
            ...
      }
      return formatter<string_view>::format(name, ctx);
    }
};
```

but I get `No matching member function for call to 'format'` at line 1314 in `core.h` and can't see what I am doing wrong. I'm using C++11 hence the trailing type declaration on the declaration of `format()`. I'm hoping you can provide a pointer to my error @vitaut.

**Comment by mwinterb** [comment]
ctx.out() is a function, not a data member.

**Comment by MarkCallow** [comment]
> ctx.out() is a function, not a data member.

A huge thanks to you @mwinterb. I could have stared at the code for hours and not seen that.
