### ISSUE TITLE
Got error in version 8.1.1 undefined reference to `std::locale fmt::v8::detail::locale_ref::get<std::locale>() const

### ISSUE THREAD

**Issue by ItayBar03** [fmtlib/fmt#2707]
```
fmt-src/include/fmt/chrono.h:826: undefined reference to `std::locale fmt::v8::detail::locale_ref::get<std::locale>() const'
collect2: error: ld returned 1 exit status
```
My compiler is riscv32-esp-elf-gcc

**Comment by vitaut** [comment]
Possibly the same as #2689. If not please provide a complete repro.

**Comment by ItayBar03** [comment]
Yes, this is the same issue, but once I remove this flag, the binary increased by 200kb or so, this is way to much for me

**Comment by delaitre-manfrotto** [comment]
we have similar issue
we use fmt on embedded but using locale just make the binary size way too big
