### ISSUE TITLE
Unspecified behavior in the library code

### ISSUE THREAD

**Issue by Roman-Koshelev** [fmtlib/fmt#2709]
The functions floor_log10_pow2(), floor_log2_pow10() and floor_log10_pow2_minus_log10_4_over_3() (from fmt/format-inl.h)  rely on unspecified behavior.
For example
```с++
inline int floor_log10_pow2(int e) FMT_NOEXCEPT {
  FMT_ASSERT(e <= 1700 && e >= -1700, "too large exponent");
  return (e * 1262611) >> 22;
}
```
Judging by the check, it is obvious that e can be negative.

"3. The value of E1 >> E2 is E1 right-shifted E2 bit positions. If E1 has an unsigned type or if E1 has a signed type and a non-negative value, the value of the result is the integral part of the quotient of E1/2^E2. If E1 has a signed type and a negative value, the resulting value is implementation-defined."

**Comment by vitaut** [comment]
These functions assume arithmetic shift. A PR to make them more portable would be welcome.

**Comment by Roman-Koshelev** [comment]
I would add a separate check that the shift is arithmetic. (and stopping compilation by static_assert if it is not).

**Comment by jk-jeon** [comment]
Jesus. I didn't know this. C++ is rough! :(
