### ISSUE TITLE
compile issue on Cygwin

### ISSUE THREAD

**Issue by phlptp** [fmtlib/fmt#2710]
I am getting a compile error on cygwin 3.3.3

```
/fmtlib/src/os.cc:207:27: error: ‘::fileno’ has not been declared; did you mean ‘file’?
  207 |   int fd = FMT_POSIX_CALL(fileno FMT_ARGS(file_));
      |                           ^~~~~~
fmtlib/include/fmt/os.h:58:36: note: in definition of macro ‘FMT_POSIX_CALL’
   58 | #    define FMT_POSIX_CALL(call) ::call
      |                                    ^~~~
fmtlib/src/os.cc: In member function ‘fmt::v8::buffered_file fmt::v8::file::fdopen(const char*)’:
fmtlib/src/os.cc:335:28: error: ‘::fdopen’ has not been declared; did you mean ‘fopen’?
  335 |   FILE* f = FMT_POSIX_CALL(fdopen(fd_, mode));
      |                            ^~~~~~
fmtlib/include/fmt/os.h:58:36: note: in definition of macro ‘FMT_POSIX_CALL’
   58 | #    define FMT_POSIX_CALL(call) ::call
      |                                    ^~~~

```

fmt is compiled as part of a CMake subproject.    It compiles fine in other contexts  including same compiler on different platforms. 
C++17  gcc 11.2  

This is  Cygwin 64 bit with the latest release of fmt.  Not sure if I should be supplying additional arguments or something else is going on here or where to look to fix it.

**Comment by vitaut** [comment]
I'm not sure why cygwin doesn't define `fdopen` (and `fileno`). If you have a workaround for this issue a PR would be welcome. You can disable this functionality via `cmake -DFMT_OS=OFF ...`

**Comment by vitaut** [comment]
According to https://stackoverflow.com/questions/15944051/error-fdopen-was-not-declared-found-with-g-4-that-compiled-with-g3 cygwin may disable POSIX APIs when compiling with `-std=c++11` or similar. The solution is to use `-std=gnu++11`. Closing as this doesn't look like a bug in {fmt} but as mentioned earlier a PR with a workaround would be welcome.

**Comment by phlptp** [comment]
Thanks, I tried a few things as workarounds but nothing worked including using `-std=gnu++17` and adding `-D_POSIX_C_SOURCE=200809`   
  
The `-DFMT_OS=OFF` did work though, I figured there had to a flag that controlled some of that, so that was what I was missing.
