### ISSUE TITLE
Request check format like printf

### ISSUE THREAD

**Issue by gendalph** [fmtlib/fmt#2723]
```
#include <fmt/core.h>
#include <fmt/printf.h>

int main() 
{
  printf ("%d \n", 1, 2, 3);
  fmt::printf ("%d \n", 1, 2, 3);

  printf ("", 1, 2, 3);
  fmt::printf ("", 1, 2, 3);
  return 0;
}

```

```
<source>:6:11: warning: too many arguments for format [-Wformat-extra-args]
    6 |   printf ("%d \n", 1, 2, 3);
      |           ^~~~~~~
```
```
<source>:9:11: warning: zero-length gnu_printf format string [-Wformat-zero-length]
    9 |   printf ("", 1, 2, 3);
      |           ^~
```

**Comment by vitaut** [comment]
Thanks for the suggestion but there are no plans to add compile-time checks to the legacy printf API.

**Comment by madscientist** [comment]
printf format checking is a feature supplied by the compiler.  For compilers that support it (clang and GCC) it's enabled by compiler attributes, and there's no reason that it can't be made to apply to any function by adding those attributes.  Before switching to fmt, I had many functions of my own that took printf-style format string and arguments and was always able to get the compiler to check them by applying these attributes.

Is there any reason to not add them to the fmt codebase as well?

**Comment by vitaut** [comment]
Unfortunately the gcc attribute is not a good fit here because it doesn't take into account that the API is already type safe and many specifiers are redundant.
