### ISSUE TITLE
`-mbig-obj` is incompatible with `-flto` on mingw compiler and cause problems linking the library in a project

### ISSUE THREAD

**Issue by VasiliPupkin256** [fmtlib/fmt#2726]
I think this is a bug in mingw compiler, but this library adds the switch to its interface https://github.com/fmtlib/fmt/blob/c5aafd8f9003c5f0ac1d9bc00d566fefe60996d7/CMakeLists.txt#L251-L256 and this trigger errors "plugin needed to handle lto object"

My system is Ubuntu 20.04 and I am compiling with 86_64-w64-mingw32

May be the requirement can be relaxed for 64 bit projects? What was the reason to include the flag into the config?

**Comment by vitaut** [comment]
IIRC it was added in response to reports similar to #1684. I think it should be OK to remove it as it is easy to add compiler flags via CMake or at least make it an opt in. A PR would be welcome.
