### ISSUE TITLE
Commit a70a4ae0530d5dd8448ade38c27ddac448a32bdc breaks formatting

### ISSUE THREAD

**Issue by tomba** [fmtlib/fmt#2727]
My test program:

```
	uint64_t val = 1;
	uint32_t numchars = 4;

	fmt::print("{:<{}}\n", val, numchars);
	fmt::print("{:<#0{}x}\n", val, numchars);
	fmt::print("{:<#0{}b}\n", val, numchars);
```

Before commit a70a4ae0530d5dd8448ade38c27ddac448a32bdc it prints:

```
1   
0x01
0b01
```

After:
```
1   
0x10
0b10
```

**Comment by vitaut** [comment]
The current output is correct because the left alignment is explicitly specified overriding the default (numeric) alignment. It is also consistent with Python:

```python
>>> "{:<{}}".format(1, 4)
'1   '
>>> "{:<#0{}x}".format(1, 4)
'0x10'
>>> "{:<#0{}b}".format(1, 4)
'0b10'
```

To get the numeric alignment (`0x01 ` / `0b01`) remove `<` from the format string.
