### ISSUE TITLE
Perfect forwarding problem?!

### ISSUE THREAD

**Issue by WarShoe** [fmtlib/fmt#2729]
I have a compilation error when I try to use fmtlib (FMT_VERSION 80101) with perfect forwarding. Anyone has a clue why?

Compilation: `g++ -std=c++20 -I ../../include f.cpp`
g++ (GCC) 10.2.0

https://www.cplusplus.com/forum/general/75064/

```
#include <fmt/format.h>
#include <fmt/ostream.h>

template<typename... U>
void myprint(U&&... u) {fmt::print(std::forward<U>(u)...);}

int main() {
    myprint("Hi {}",11);
}
```

```
f.cpp: In instantiation of ‘void myprint(U&& ...) [with U = {const char (&)[6], int}]’:
f.cpp:8:23:   required from here
f.cpp:5:35: error: ‘u#0’ is not a constant expression
    5 | void myprint(U&&... u) {fmt::print(std::forward<U>(u)...);}
      |                         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by mwinterb** [comment]
In C++20 mode, the formatting functions will automatically do format string checks. For that to occur, the format string needs to be a constant expression. "u" in this case is not. To properly wrap format / print, the first parameter should be a `fmt::format_string`. See https://github.com/fmtlib/fmt/issues/2373#issuecomment-865688788 for an example.

If the format string isn't known until runtime (i.e. for localization reasons), it can be wrapped with `fmt::runtime` as the comment above the linked comment does.
