### ISSUE TITLE
Is it possible to add a custom formatter in a cpp file?

### ISSUE THREAD

**Issue by derived-coder** [fmtlib/fmt#2730]
Instead of providing a class template, I would like to register a converter function to fmt.
Which gets called, when my type needs to be printed.

Is this possible?

**Comment by derived-coder** [comment]
Please explain why.

**Comment by vitaut** [comment]
The extension API is documented here: https://fmt.dev/latest/api.html#formatting-user-defined-types. There are no plans to add another one.
