### ISSUE TITLE
check_cxx_compiler_flag() for C++ standard failed on Visual Studio.

### ISSUE THREAD

**Issue by Aleksoid1978** [fmtlib/fmt#2734]
**cxx14.cmake**: **std=c++20** and others not supported by Visual Studio, should be **/std:c++20** and so on.

**Comment by vitaut** [comment]
Those checks are clang/gcc specific, you can pass options for other compilers via normal CMake mechanisms.

**Comment by Aleksoid1978** [comment]
If it's expected to fail on MSVC - why it's call on MSVC ?

**Comment by vitaut** [comment]
This is just a config check that is run on all compilers.

**Comment by Aleksoid1978** [comment]
Those. these checks do not affect the build in any way ?

**Comment by vitaut** [comment]
The "failures" are just informational. CMake tests various compiler capabilities, in this case whether certain options are supported so that we didn't have to hardcode clang, gcc and any other compatible compilers. So no, the failures don't affect the build.
