### ISSUE TITLE
Including `fmt/ranges.h` breaks custom formatters for templated range-like classes

### ISSUE THREAD

**Issue by arashbm** [fmtlib/fmt#2735]
Consider a templated class defining a simple view interface:
```c++
template <typename T>
class blaaah : public std::ranges::view_interface<blaaah<T>> {
    public:
        auto begin() const  { return a.cbegin(); }
        auto end() const  { return a.cend(); }
    private:
        std::vector<T> a{1, 2, 3};
};
```
with a simple custom formatter:
```c++
template <typename T>
struct fmt::formatter<blaaah<T>> {
    constexpr auto parse(format_parse_context& ctx) {
        auto it = ctx.begin(), end = ctx.end();
        if (it != end && *it != '}') throw format_error("invalid format");
        return it;
    }

    template <typename FormatContext>
    auto format(
        const blaaah<T>& a,
        FormatContext& ctx) -> decltype(ctx.out()) {
            return fmt::format_to(ctx.out(), "<blaaah of {} items>", a.size());
    }
};
```

Defining a custom formatter for this type works fine until someone somewhere imports `fmt/ranges.h`. Then compilation fails with:
`error: ambiguous template instantiation for 'struct fmt::v8::formatter<blaaah<int>, char, void>`.

Full example on [Compiler Explorer][generic].

Curiously, if the class `blaaah` above is not defined generic, [this behaviour is not consistent and compilation succeeds][nongeneric].

[generic]: https://godbolt.org/z/nvq9d74G8
[nongeneric]: https://godbolt.org/z/7E8zq5aKa

**Comment by arashbm** [comment]
Digging a bit through previous issues, there is a way to resolve this, by marking the class as not a range as far as fmt is concerned:

```c++
template <typename T>
struct fmt::is_range<blaaah<T>, char> : std::false_type {};
```

I'll close the issue.

**Comment by Finkman** [comment]
Thanks for the quick help.
Question: Doesn't a custom formater imply that the build-in formater for ranges should not be used?

**Comment by vitaut** [comment]
> Doesn't a custom formater imply that the build-in formater for ranges should not be used?

No. There is no built-in formatter for ranges, it uses the same extension mechanism.
