### ISSUE TITLE
Issue with CXX_Relaxed_constexpr on VS2017

### ISSUE THREAD

**Issue by tstrutz** [fmtlib/fmt#2736]
I am still encountering a problem compiling the library when using _MSC_VER 1929. (VS2017 V15.7.6)

I had to increment the value of FMT_MSC_VER to 1930 to get it to avoid compiling the statements.

The following code in core.h had to be changed to:
```c++
#ifndef FMT_USE_CONSTEXPR
#  define FMT_USE_CONSTEXPR                                           \
    (FMT_HAS_FEATURE(cxx_relaxed_constexpr) || FMT_MSC_VER >= 1930 || \
     (FMT_GCC_VERSION >= 600 && __cplusplus >= 201402L)) &&           \
        !FMT_NVCC && !FMT_ICC_VERSION
#endif
```

to get my code to compile.

**Comment by vitaut** [comment]
Could you submit a PR?

**Comment by phprus** [comment]
_MSC_VER 1929 on Visual Studio 2019 version 16.10, 16.11, not on VS2017 V15.7.6 (https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170)

Please post repro details, code sample,  build flags and compiler version.

**Comment by vitaut** [comment]
Closing for now since the version information doesn't look right but feel free to reopen with more repro details.
