### ISSUE TITLE
It should be possible to provide formatter for types convertible to pointers

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#2737]
The new detection of the convertibility to pointers prevent this breaking formatting of types like `watchman::w_string`.

**Comment by mwinterb** [comment]
... didn't you fix this exact case in #2717? Or did it re-break?

**Comment by vitaut** [comment]
LOL, I indeed fixed this. Thanks for pointing this out! Hard to keep track of all what's going on.
