### ISSUE TITLE
[c++20] consteval argument validation can be improved

### ISSUE THREAD

**Issue by timblechmann** [fmtlib/fmt#2739]
consteval format strings are great, as they can detect argument mismatches at compile-time.

e.g. this fails to compile:
```
fmt::print("aaa {} {}", 1);
```

however if the argument count exceeds the number of arguments in the format string, the code compiles:
```
fmt::print("aaa {} {}", 1, 1, 1); // 2 arguments are used, 3 are given. this compiles
```

it would be great, if this could also be caught at compile-time

**Comment by vitaut** [comment]
Thanks for the suggestion but the current behavior is intentional. Conceptually this is the same as unused arguments in any other function that should at most be a warning and there are valid use cases.

**Comment by vitaut** [comment]
(Same as #492)

**Comment by timblechmann** [comment]
thanks for the explanation. it kind of violates the principle of least surprise: missing arguments result in a compile error, while exceeding arguments are accepted.

> Conceptually this is the same as unused arguments in any other function that should at most be a warning and there are valid use cases.

i see. if there would be a way to emit a warning at compile-time, it would be great! this would bring the behaviour in line with how `-Wformat` validates `printf`
