### ISSUE TITLE
Symbol duplication with spdlog under MSVC (meson buildsystem).

### ISSUE THREAD

**Issue by B4mbus** [fmtlib/fmt#2741]
Hey. I'm trying to compile [my project](https://github.com/b4mbus/rip-spm) on windows. It compiles fine on my WSL but fails to compile on the host machine, with windows.

I have both spdlog and fmt as separate dependencies.

Here are the specs:

- compiler - msvc 19.30.30706 for x64
- linker - 14.30.30706.0
- arch - x86_64
- os - windows 10 pro
- fmtlib - latest, master/head (8.0.1 I suppose? No idea how to check it)
- spdlog - latest, master/head (1.9.2 I suppose? No idea how to check it)
- CMake version - 3.22.1
- Meson version - 0.60.2

Here's my whole meson.build:
```meson
project('rip-spm-words-counter', 'cpp', meson_version: '>=0.55.0', license: 'gpl3')

if(meson.get_compiler('cpp').get_id() == 'msvc') # have to do that to avoid MSVC breaking code with their min/max macros
  add_project_arguments('-DNOMINMAX', language: 'cpp')
endif

cmake = import('cmake')


dpp_sub_opts = cmake.subproject_options()
if host_machine.system() == 'linux' and meson.get_compiler('cpp').has_argument('-pthread')
  dpp_sub_opts.append_link_args('-pthread') # a quickfix for dpp not having -pthread for some reason
endif

release_type_opts = cmake.subproject_options()
if get_option('buildtype') == 'release' # unsafely assuming only 'release' and 'debug' are used let the world burn
  release_type_opts.add_cmake_defines({'CMAKE_BUILD_TYPE': 'RELEASE'})
  dpp_sub_opts.add_cmake_defines({'CMAKE_BUILD_TYPE': 'RELEASE'})
else
  release_type_opts.add_cmake_defines({'CMAKE_BUILD_TYPE': 'DEBUG'})
  dpp_sub_opts.add_cmake_defines({'CMAKE_BUILD_TYPE': 'DEBUG'})
endif

dpp_sub = cmake.subproject('dpp', options: dpp_sub_opts)

include_dirs = [
  include_directories('src')
]

dependencies = [
  dependency('threads'),

  dpp_sub.dependency('dpp'),

  cmake.subproject('fmtlib', options: release_type_opts).dependency('fmt'),
  cmake.subproject('spdlog', options: release_type_opts).dependency('spdlog'),
  cmake.subproject('range-v3', options: release_type_opts).dependency('range-v3')
]

src = 'src/'
source_files = [
  src / 'env/env.cpp',
  src / 'error_handler/handler.cpp',

  src / 'commands/help/help_command.cpp',

  src / 'startup/startup.cpp',
  src / 'commands/utils.cpp',
  src / 'main.cpp'   
]

executable_options = [
  'cpp_std=c++20' 
]

executable(
  'words-counter',
  source_files,
  dependencies: dependencies,
  include_directories: include_dirs,
  override_options: executable_options
)
```

and here are the MSVC's errors:

```
libspdlog.a(src_fmt.cpp.obj) : error LNK2005: "void __cdecl fmt::v8::detail::assert_fail(char const *,int,char const *)" (?assert_fail@detail@v8@fmt@@YAXPEBDH0@Z) already defined in src_commands_help_help_command.cpp.obj

libspdlog.a(src_fmt.cpp.obj) : error LNK2005: "public: void __cdecl fmt::v8::detail::error_handler::on_error(char const *)" (?on_error@error_handler@detail@v8@fmt@@QEAAXPEBD@Z) already defined in src_commands_help_help_command.cpp.obj

libspdlog.a(src_fmt.cpp.obj) : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl fmt::v8::vformat(class fmt::v8::basic_string_view<char>,class fmt::v8::basic_format_args<class fmt::v8::basic_format_context<class fmt::v8::appender,char> >)" (?vformat@v8@fmt@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$basic_string_view@D@12@V?$basic_format_args@V?$basic_format_context@Vappender@v8@fmt@@D@v8@fmt@@@12@@Z) already defined in 
```

I found an answer online that suggested to check if anything defines `FMT_HEADER_ONLY`, but I don't think so. It's not present in the build command invoked by the build system, I don't define it myself and I can clearly see the fmtlib being linked in the command.

**This problem references meson, spdlog and fmtlib, I did not know where to ask, so I asked here. If it's misfit, please let me know, thanks in advance.**

**Comment by eli-schwartz** [comment]
Can you try replacing the use of `cmake.subproject()` with `dependency('fmt'), dependency('spdlog'), dependency('range-v3')`, which will try to find system installed versions of all 3, and then handle subprojects by running the following commands:

```
meson wrap install fmt
meson wrap install spdlog
meson wrap install range-v3
```

All three are available in https://wrapdb.mesonbuild.com and build natively with meson using wrap dependency fallbacks for consistency. You may still need the cmake module for dpp (but you can try writing a meson.build for it following the Wrap dependency system manual) but I suspect this will probably simplify fmtlib integration for you. :)

**Comment by sylveon** [comment]
`spdlog` carries its own copy of fmt. define `SPDLOG_FMT_EXTERNAL` to have it use your copy of fmt.
