### ISSUE TITLE
Unable to compile dynamic_format_arg_store example 

### ISSUE THREAD

**Issue by Eskilade** [fmtlib/fmt#2745]
Your example code for dynamic_format_arg_store does not seem to be compiling:
https://godbolt.org/z/W6z7eqPMW

I've getting the same error locally.

**Comment by OnurKader** [comment]
Hmm, seems to compile on gcc 9.3 and up if it's not header only [godbolt](https://godbolt.org/z/G5jEd1bGT)

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/90325d0970b031be8872c60168aeb4cb09928815, thanks for reporting.
