### ISSUE TITLE
Drastic increase in compile time and linker memory use

### ISSUE THREAD

**Issue by code-affinity** [fmtlib/fmt#2751]
We have an application consisting of about 120K lines of C++ code that uses the fmt library extensively, mostly indirectly through logging with the spdlog library.

We recently upgraded from fmt 6.0.0 to 8.1.1, and spdlog 1.1.1 to 1.9.2.

Building with gcc-11 in a debug build configuration, our overall build times increased by 2.23X.  Our final link time increased by 2.83X.  Most importantly, the linker now uses 2.19X as much memory as it did before -- from 2.7GB to 5.9GB, even after applying every ld linker option to reduce memory use.

This 5.9GB is too much.  Our continuous integration server terminates the link process because of excessive memory use, and several of our developers are practically unable to build our application.

Is this amount of compile time, link time, and linker memory increase expected when upgrading to recent versions of fmt and spdlog?  Is there anything we can do to reduce these numbers (other than downgrading)?

**Comment by vitaut** [comment]
Are you using spdlog as a static library? https://github.com/gabime/spdlog#static-lib-version-recommended---much-faster-compile-times. The header-only mode can be slow to build and not recommended.

**Comment by code-affinity** [comment]
Hmm, we have certainly built a spdlog.a static library.  However, it appears that none of our CMakeLists.txt file explicitly name the spdlog::spdlog target in their target_link_libraries commands.  So perhaps we are not getting the advantage of the spdlog static library.

**Comment by vitaut** [comment]
If you don't link against spdlog then you are definitely consuming it (or at least fmt) in the header-only because otherwise you'd get linker errors. Closing for now but feel free to reopen if you have an example that shows build time increase in fmt.

**Comment by code-affinity** [comment]
Thank you.  Explicitly linking all of our targets to fmt::fmt and spdlog::spdlog, the overall build time is now only 1.21X its pre-upgrade value, and our linker memory requirement is only 1.07X its pre-upgrade value.
