### ISSUE TITLE
Linker reports warnings

### ISSUE THREAD

**Issue by dcblack** [fmtlib/fmt#2756]
On macOS 12.2 using CLion 2022.3 using Clang I get the following linker errors, which I think are attributable to the fmt library:

ld: warning: direct access in function 'fmt::v8::detail::format_error_code(fmt::v8::detail::buffer<char>&, int, fmt::v8::basic_string_view<char>)' from file '/usr/local/lib/libfmt.a(format.cc.o)' to global weak symbol 'fmt::v8::detail::do_count_digits(unsigned int)::table' from file 'CMakeFiles/formatting.dir/formatting.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'fmt::v8::detail::format_error_code(fmt::v8::detail::buffer<char>&, int, fmt::v8::basic_string_view<char>)' from file '/usr/local/lib/libfmt.a(format.cc.o)' to global weak symbol 'fmt::v8::detail::do_count_digits(unsigned int)::table' from file 'CMakeFiles/formatting.dir/formatting.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'int fmt::v8::detail::format_float<double>(double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)' from file '/usr/local/lib/libfmt.a(format.cc.o)' to global weak symbol 'fmt::v8::detail::do_count_digits(unsigned int)::table' from file 'CMakeFiles/formatting.dir/formatting.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'int fmt::v8::detail::format_float<double>(double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)' from file '/usr/local/lib/libfmt.a(format.cc.o)' to global weak symbol 'fmt::v8::detail::do_count_digits(unsigned int)::table' from file 'CMakeFiles/formatting.dir/formatting.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'int fmt::v8::detail::format_float<long double>(long double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)' from file '/usr/local/lib/libfmt.a(format.cc.o)' to global weak symbol 'fmt::v8::detail::do_count_digits(unsigned int)::table' from file 'CMakeFiles/formatting.dir/formatting.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'int fmt::v8::detail::format_float<long double>(long double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)' from file '/usr/local/lib/libfmt.a(format.cc.o)' to global weak symbol 'fmt::v8::detail::do_count_digits(unsigned int)::table' from file 'CMakeFiles/formatting.dir/formatting.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

**Comment by vitaut** [comment]
Could you provide repro details?

**Comment by vitaut** [comment]
This is likely due to different opitons used to compile {fmt} and your code. Closing for now but feel free to reopen with a self-contained repro.

**Comment by xorz57** [comment]
I am experiencing the very same issue too!
