### ISSUE TITLE
compilation broken since v80101

### ISSUE THREAD

**Issue by sehe** [fmtlib/fmt#2768]
I'm using `ostream.h` support to allow easy formattability of recursive variants (I tried just specializing `fmt::format<>` but it always refused because of the cyclic dependency on `format<>` instantiations; is it due to aggressive constexpr-ifications?).

Code previously compiled (e.g. 8.1.1-16-g5985f0a7)

Minimized from https://stackoverflow.com/a/71129718/85371:

````c++
#include <boost/variant.hpp>
#include <fmt/ostream.h>
#include <fmt/ranges.h>
#include <map>
#include <vector>

using Value = boost::make_recursive_variant< //
    int,                                     //
    std::vector<boost::recursive_variant_>   //
>::type;

struct Printer {
    std::ostream& _os;
    std::ostreambuf_iterator<char> _out{_os};
    Printer(std::ostream& os) : _os(os) {}

    template <typename... Ts>
    auto operator()(boost::variant<Ts...> const& v) const { boost::apply_visitor(*this, v); }
    auto operator()(auto const& v) const { return fmt::format_to(_out, "{}", v); }
};

std::ostream& operator<<(std::ostream& os, Value const& v) {
    Printer{os}(v);
    return os;
}

int main() {
    Value v;
    fmt::print("Value: {}\n", v);
}
````

Used to print the expected:
```
libfmt v80101
Value: 0
```

In recent versions it fails to compile. I tried to bisect from trunk to the known-good:

````bash
git bisect start
git bisect good 5985f0a7
git bisect bad 2b6f7fc7
git bisect run ./script.sh
git bisect log
````

Where `script.sh` is the simple

```bash
if make -C .; then
    if make -C ../..; then
        git bisect good
    else
        git bisect bad
    fi
else
    git bisect skip
fi
```

The output of bisect log:

```
git bisect start
# good: [5985f0a7d2a725f6e843e8bc1a01e052a31d8e0b] Fix overflow for chrono durations (#2722)
git bisect good 5985f0a7d2a725f6e843e8bc1a01e052a31d8e0b
# bad: [2b6f7fc7a3f8c5322d8f0abce8b056e89e82e9ff] Add partial support for extended precision FP
git bisect bad 2b6f7fc7a3f8c5322d8f0abce8b056e89e82e9ff
# good: [8a21e328b8dcb62a2901c499598366a0f5f3f4a5] Remove problematic constructibility check
git bisect good 8a21e328b8dcb62a2901c499598366a0f5f3f4a5
# good: [7dbe3dcdeda30ce11d9ca1c5743bd1a75464fa0c] Recover log10_2_significand
git bisect good 7dbe3dcdeda30ce11d9ca1c5743bd1a75464fa0c
# skip: [c04af4bfc74d2c963a8e353034203aedc4bb6908] Simplify remove_trailing_zeros
git bisect skip c04af4bfc74d2c963a8e353034203aedc4bb6908
# good: [5594edaf6790996a05515f3ff2f627daa312e2e5] Address https://github.com/fmtlib/fmt/issues/2763 (#2765)
git bisect good 5594edaf6790996a05515f3ff2f627daa312e2e5
# bad: [0a24a0714ef5f6ff4bbd17a43a17289133414338] Clz builtin may be not constexpr (Issue #2761) (#2762)
git bisect bad 0a24a0714ef5f6ff4bbd17a43a17289133414338
# good: [ba6f89c76ee20d4665c05f18e212b1446fe8d126] Update .bazelversion (#2766)
git bisect good ba6f89c76ee20d4665c05f18e212b1446fe8d126
# first bad commit: [0a24a0714ef5f6ff4bbd17a43a17289133414338] Clz builtin may be not constexpr (Issue #2761) (#2762)
```

## QUESTIONS

Is there a reason why this should no longer compile? If so, how would one make `Value` formattable?

**Comment by vitaut** [comment]
Although even with the above change the example is broken because there is a cyclic dependency between operator<< and formatter (each is defined in terms of another).

**Comment by sehe** [comment]
No worries, the initial response was clear enough to fix my problem (see https://stackoverflow.com/questions/71124228/boost-spirit-parsing-indended-list-of-items/71129718#comment125743018_71129718 for original context).

But I couldn't find any reference in the documentation regarding this breaking change, including the need to opt (in fact, the way I read the documentation suggests the opposite?) as well as the FMT_DEPRECATED_OSTREAM option. Should we create a ticket to improve that?

**Comment by vitaut** [comment]
This change hasn't been released yet, it is only in the current master. I'll bump the version number to make it a bit less confusing.

**Comment by sehe** [comment]
You're quite right. I don't know how I've missed it. Scanned repeatedly for it ¯\_(ツ)_/¯ I'm quite sure you shouldn't advertise the deprecated behavior, so that's all good then.
