### ISSUE TITLE
why use std::unique_ptr in emplace_arg()  by args.h line 129

### ISSUE THREAD

**Issue by huangzhentao** [fmtlib/fmt#2774]
![image](https://user-images.githubusercontent.com/5028674/154400545-ba08f3b3-5820-4aa1-bc6b-2af2ef205763.png)

it's only accesses `data_.size()` , why need declare std::unique_ptr before？

**Comment by vitaut** [comment]
It is used for RAII. You might find more details by looking at the PR that introduced it.
