### ISSUE TITLE
How to use alternate form for hex numbers with alignment attribute?

### ISSUE THREAD

**Issue by LeonSkoog** [fmtlib/fmt#2776]
Hello, 
I'm trying to display alternate form of hex number (with 0x prefix) with an alignment:
```
#include <fmt/format.h>

void print_hex(int num)
{
    fmt::print("{:>4#x}", num);
}
int main()
{
    print_hex(10);
}
```
But it triggers an exception: fmt::v8::format_error 

`fmt::print("{:>4x}", num);` works fine

Godbolt link: https://godbolt.org/z/d5E9zPdjW

**Comment by OnurKader** [comment]
`"{:4>#x}"` works I think

[godbolt](https://godbolt.org/z/Gzn7a56jW)

**Comment by LeonSkoog** [comment]
@OnurKader  it doesn't work :( 
I made another example where you can play:
```
#include <fmt/format.h>
#include <ranges>

int main() {
    auto nums = std::ranges::iota_view{0, 16*5};

    for(size_t columnCnt{0}; auto const &i: nums)
    {
        if(columnCnt++ % 16 == 0)
            fmt::print("\n");
        fmt::print("{:>4x} ", i);
    }
}
```

Godbolt: https://godbolt.org/z/5PTePjden

**Comment by vitaut** [comment]
`#` should precede width, not follow it: 

```c++
fmt::print("{:>#4x}", num);
```

Please refer to the documentation for the format string syntax: https://fmt.dev/latest/syntax.html#format-specification-mini-language
