### ISSUE TITLE
[v8.1.1] fmt linker error with fmt::format when used without text_style

### ISSUE THREAD

**Issue by nandanvasudevan** [fmtlib/fmt#2781]
`#define FMT_VERSION 80101`

# Problem statement
For the snippet 
```c++
const std::string sTest = fmt::format("Hello!");
```
I get the following error:
```c++
./include/fmt/core.h:3119: undefined reference to `fmt::v8::vformat[abi:cxx11](fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)'
collect2: error: ld returned 1 exit status
```

Checkout [`main.cpp`](https://github.com/nandanvasudevan/cpp_scratch_pad/blob/809b7a5db800902185a07ebac783b3352c82464a/src/main.cpp) for minimal example.

## Conan file
`fmt/8.1.1`

## CMakeLists.txt
```
find_package(fmt)
target_link_libraries(${PROJECT_NAME} PRIVATE fmt::fmt)
```

This is the project https://github.com/nandanvasudevan/cpp_scratch_pad/tree/fun_with_fmt

# Observation

I tried the same on [compiler-explorer](https://compiler-explorer.com/z/rov5vrscE) and it works without any problems.
It also compiles without complaints with `#define FMT_HEADER_ONLY`.

If I add a text_style like in the snippet below it works.
```c++
const std::string sTest = fmt::format(fmt::fg(fmt::color::blue),"Hello!");
```

---

Can someone help me figure this out?

**Comment by acxz** [comment]
Wanted to note, I'm getting a similar error but in a different file (`fmt/ranges.h`)

Here is the error message for me:
```bash
/usr/include/fmt/ranges.h:737:21: error: no matching member function for call to 'format'
                 .format(std::get<sizeof...(T) - N>(value.tuple), ctx);
```

**Comment by nandanvasudevan** [comment]
Am I supposed to use `fmt::to_string()` instead when I don't need a text style?

**Comment by vitaut** [comment]
This looks like an issue with the conan package which is maintained elsewhere. Please report to https://github.com/conan-io/conan.

**Comment by nandanvasudevan** [comment]
Just FYI.
It was due to improper conan configuration in my code. Sorry for the troubles.

**Comment by vitaut** [comment]
No worries. Glad it's resolved now.
