### ISSUE TITLE
[Question] How to use a debugger to step through the code

### ISSUE THREAD

**Issue by jmarrec** [fmtlib/fmt#2784]
Is there some kind of magic switch or cmake configuration options to be able to jump into fmt's source code in a debugger please?

I'm probably doing something stupid... but I can't seem to be able to set a breakpoint on `format` to step through it, even in `format_volatile_char` test (which shouldn't be resolved at compile time). https://github.com/fmtlib/fmt/blob/1ba69fb5a183ed0808123d849560abd19063f770/test/format-test.cc#L1407-L1410

I've tried this on gcc-10, with lldb-12:

```shell
# I tried without the visibility flags first
cmake -G Ninja -DCMAKE_BUILD_TYPE:STRING=DEBUG -DCMAKE_VISIBILITY_INLINES_HIDDEN:BOOL=OFF -DCMAKE_CXX_VISIBILITY_PRESET:STRING=Default -DFMT_TEST:BOOL=ON ../
ninja

lldb-12 ./bin/format-test -- --gtest_filter=*volatile*
```

```c++
(lldb) br set --file /path/to/fmt/test/format-test.cc --line 1409
(lldb) pro lau
[...]
[ RUN      ] format_test.format_volatile_char
Process 197620 stopped
* thread #1, name = 'format-test', stop reason = breakpoint 1.1
    frame #0: 0x00005555555c3591 format-test`format_test_format_volatile_char_Test::TestBody(this=0x000055555577db00) at format-test.cc:1426:3
   1423	
   1424	TEST(format_test, format_volatile_char) {
   1425	  volatile char c = 'x';
-> 1426	  EXPECT_EQ("x", fmt::format("{}", c));
   1427	}
   1428	
   1429	TEST(format_test, format_unsigned_char) {
(lldb) br set --method fmt::format
Breakpoint 2: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb) br set --method format
Breakpoint 3: 75 locations.
(lldb) br set --method format_to
Breakpoint 4: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
```

At this point, if I use `n` for next, no breakpoint is hit. And even if I use `s` to step through the code manually, I can see only gtest's internal stuff, not fmt's.

**Comment by vitaut** [comment]
Normally `-DCMAKE_BUILD_TYPE=Debug` should be enough to generate debug info.

**Comment by jmarrec** [comment]
I tested with clang-12. Same behavior, can seem to step through the code step by step.

I appreciate your time and effort for the library and understand you're busy, maintaining an open source library is probably tiring. Have a good one and thanks for fmt.

**Comment by vitaut** [comment]
BTW you might be able to put a breakpoint in `vformat` as a workaround (`b vformat`).

**Comment by jmarrec** [comment]
Putting a breakpoint in vformat does create a hit. Thank you!
