### ISSUE TITLE
is_printable is not compiled into the static lib

### ISSUE THREAD

**Issue by risa2000** [fmtlib/fmt#2786]
When building the static libs (on Windows), I noticed that function
```c++
bool __cdecl fmt::v8::detail::is_printable(unsigned int)
```
is exported from the `fmt.lib` but the implementation is not included.

This is a snippet for the `fmt.lib` symbol dump.
```
99D 00000000 SECT44B notype ()    External    | ?size@?$basic_string_view@_W@v8@fmt@@QEBA_KXZ (public: unsigned __int64 __cdecl fmt::v8::basic_string_view<wchar_t>::size(void)const )
99E 00000000 UNDEF  notype ()    External     | ?is_printable@detail@v8@fmt@@YA_NI@Z (bool __cdecl fmt::v8::detail::is_printable(unsigned int))
99F 00000000 SECT415 notype ()    External    | ?needs_escape@detail@v8@fmt@@YA_NI@Z (bool __cdecl fmt::v8::detail::needs_escape(unsigned int))
```

It guess the problem is that the implementation is in `format-inl.h` which is not compiled into the lib.

**Comment by vitaut** [comment]
Do you get an error or is it more of a theoretical question?

**Comment by risa2000** [comment]
I am building my static lib, which uses fmt lib and with it it pulls in also the exported symbol `is_printable`. Then when linking my app against my static lib and `fmt.lib`, the build fails because the inline version is not compiled in the app, and the non-inline version is missing from `fmt.lib`.

**Comment by vitaut** [comment]
`is_printable` is defined here: https://github.com/fmtlib/fmt/blob/0742606f199d9839123d36c5cb65c548f5f46f6e/include/fmt/format-inl.h#L2531. Note that it is not inline (except for the header-only mode).

**Comment by risa2000** [comment]
I might have misread `format.h` into thinking that `format-inl.h` is not included into the build when building against the static lib, but the fact is that `is_printable` is not compiled into the final `fmt.lib` (as shown in my snippet I posted above), and is nowhere else to find either.

So I might turn the question around. Is it supposed to be in `fmt.lib`? If not, then why is `fmt.lib` exporting the symbol for it? If yes, then there is clearly a problem with library build.

**Comment by vitaut** [comment]
I'm not sure why `is_printable` is not a part of the static library in your setup. I tried to repro it locally but to no avail:

```
$ nm -a libfmtd.a
...
0000000000002070 T fmt::v8::detail::is_printable(unsigned int)
```

**Comment by mwinterb** [comment]
`format.cc` includes `format-inl.h`: https://github.com/fmtlib/fmt/blob/c28500556a027fc3b84dc06e0021c719480fd1f3/src/format.cc#L8

**Comment by vitaut** [comment]
Do you use the default CMake config provided by {fmt}?

**Comment by vitaut** [comment]
Could you post the full `dumpbin` output?

**Comment by risa2000** [comment]
Here is the `dumpbin` output.

[fmt.lib.txt](https://github.com/fmtlib/fmt/files/8126332/fmt.lib.txt)

**Comment by vitaut** [comment]
According to the full dumpbin output `is_printable` **is** defined:

```
DAA 00000000 SECT57E notype ()    External    | ?is_printable@detail@v8@fmt@@YA_NI@Z (bool __cdecl fmt::v8::detail::is_printable(unsigned int))
```

I think the `UNDEF` entry is OK because it should be resolved to the one above by a linker.

**Comment by risa2000** [comment]
Hmm, I did not realize that the symbol could be exported more than once. I have to have some other problem then, because the linker fails, complaining about not finding this particular function. I am not at the machine which exhibits this behavior right now, but I will see if I could come up with some reproducible scenario.

**Comment by risa2000** [comment]
I did a quick test with the simple code which builds fine. So the problem must be in my convoluted case when linking my library which uses `fmtlib`.

fmt_test.cpp:
```c++
#include <fmt/format.h>

namespace fmt::v8::detail {
bool is_printable(unsigned int);
}

int main(int argc, char* argv[])
{
    auto test = fmt::v8::detail::is_printable(42);
    return test ? 0 : 1;
}
```
CMakeLists.txt:
```cmake
cmake_minimum_required (VERSION 3.15)
project (fmt_test)
set (CMAKE_CXX_STANDARD 17)
set (CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(fmt 8.0.0 REQUIRED HINTS D:/Work_OSS/fmt/out/install/x64-DLL-Release)

add_executable (fmt_test fmt_test.cpp )
target_link_libraries (fmt_test PRIVATE fmt::fmt)
```

**Comment by vitaut** [comment]
Closing for now then but feel free to reopen with a repro.

**Comment by scramsby** [comment]
I just hit this same issue when working through an upgrade and I think I tracked it down to an issue where we were building C++ static libs with two different C++ build systems that have slightly different toolchains or configs which caused different C++ name mangling of `is_printable()`. Our temporary hack workaround was to add `extern "C" { ... }` around the declaration and definition of the `is_printable()` function until we can fix the toolchain mismatch.
