### ISSUE TITLE
format localtime error

### ISSUE THREAD

**Issue by tiantianaixuexi** [fmtlib/fmt#2790]
i want  format time to string and write file . use fmt::print is success.  but i use fmt::format write to string is error
```
	std::time_t t = std::time(nullptr);


	std::string _formatstr = fmt::format("sss :{%Y-%m-%d %H:%M:%S}", fmt::localtime(t));
	
	fmt::print(fg(fmt::color::crimson) | fmt::emphasis::bold,
		_formatstr);

```

error core:
```
1>F:\dazzleServer\src\dazzleServer.cpp(19,39): error C3615: constexpr 函数“fmt::v8::basic_format_parse_context<char,fmt::v8::detail::error_handler>::on_error”不能生成常量表达式
1>F:\dazzleServer\src\third\fmt\core.h(667,27): message : 对未定义的函数或为未声明为“constexpr”的函数的调用导致了故障
1>F:\dazzleServer\src\third\fmt\core.h(667,27): message : 请参见“fmt::v8::detail::error_handler::on_error”的用法
```

**Comment by tiantianaixuexi** [comment]
> 会`fmt::print(fg(fmt::color::crimson) | fmt::emphasis::bold, "{}", _formatstr);`工作?


hello ,it is  std::string _formatstr = fmt::format("sss :{%Y-%m-%d %H:%M:%S}", fmt::localtime(t)); not work.

I still made a mistake changing the code to yours

**Comment by OnurKader** [comment]
Ahh there's a colon missing in the format specifier after the curly, {**:**%Y-%m-%d %H:%M:%S}. 

[godbolt](https://godbolt.org/z/o4xKjK65v)

**Comment by tiantianaixuexi** [comment]
thak.it is work
