### ISSUE TITLE
hex printing appears broken on trunk - 8.1.1 works 

### ISSUE THREAD

**Issue by oschonrock** [fmtlib/fmt#2792]
```c++
std::string s = fmt::format("{:x}", std::byte(42)); // s == 2a
```
gives wall of errors on trunk, using clang-13 or gcc-11.  Fine on 8.1.1

**Comment by vitaut** [comment]
This works but make sure to include `fmt/format.h` (https://godbolt.org/z/6e8e6PbEY):
```c++
#include <fmt/format.h>

int main() {
  std::string s = fmt::format("{:x}", std::byte(42));
}
```

**Comment by oschonrock** [comment]
I was including "fmt/core.h" as per your old example on SO... has this changed?

**Comment by vitaut** [comment]
Yeah, it worked with `fmt/core.h` accidentally because `byte` is a scoped enum. Now that scoped enums are not implicitly converted to ints, a formatter is needed which is provided by `fmt/format.h`.
