### ISSUE TITLE
Found 3 warnings, 1 error

### ISSUE THREAD

**Issue by FooqX** [fmtlib/fmt#2795]
I have found some warnings and an error in core and format headers. I suggest to fix them if this isn't intentionally done, especially the error in format header. I'm using Visual Studio 2022 and it's a C++ console application.

<details>
<summary>The issues</summary>

![ich2](https://user-images.githubusercontent.com/65967000/156880441-4d8027f4-45d0-4c4a-a31f-238e4f186490.png)
![infocoreheader](https://user-images.githubusercontent.com/65967000/156880442-ca6093b1-61c5-4dbc-a6d0-38fa44593362.png)
![fourtherror](https://user-images.githubusercontent.com/65967000/156880443-f816c085-ea53-45e5-b040-35e11ba1b17f.png)
![thirderror](https://user-images.githubusercontent.com/65967000/156880444-4c1c3a93-f3b6-4422-a510-c7eae77fb628.png)
![seconderror](https://user-images.githubusercontent.com/65967000/156880445-5d519689-4f39-4c90-ac54-f5f111bc7863.png)
![firsterror](https://user-images.githubusercontent.com/65967000/156880446-f42f5838-3e87-41fe-8c23-2bfa7cec430c.png)

</details>

**Comment by vitaut** [comment]
These look like issues in Intellisense, please report to Microsoft. If this is not the case please provide a self-contained repro, preferably on godbolt.
