### ISSUE TITLE
when consumed via `fmt-header-only` target, the cmake build still attempts to install the `fmt` library

### ISSUE THREAD

**Issue by abdes** [fmtlib/fmt#2798]
Expectation is that if the project using the fmtlib is only depending on `fmt-header-only`, the INSTALL actions of fmtlib should not try to install fmt library/dll and fail because the file does not exist.

**Comment by vitaut** [comment]
`fmt-header-only` affects usage not installation by design.

**Comment by vitaut** [comment]
I don't think it's documented anywhere (maybe in CMake) but I don't think we should modify installation behavior per-target.
