### ISSUE TITLE
Glibc extensions no longer supported in std::tm formatter

### ISSUE THREAD

**Issue by euclio** [fmtlib/fmt#2811]
In short, this assertion (using the `make_hour` function from the chrono tests) passes in 8.0.1 but fails in 8.1.0.

```cpp
EXPECT_EQ("8", fmt::format("{:%-I}", make_hour(8)));
```

According to `git bisect`, this regressed in 7911d8d3f56ec88f75e1f25663f4079ff2e9c67d.

Seems like this might be expected breakage given the goal of https://github.com/fmtlib/fmt/pull/2544, but [the documentation](https://fmt.dev/latest/syntax.html#chrono-specs) claims that the code uses the format specifiers from the system's `strftime`, which is no longer the case.

cc https://github.com/Alexays/Waybar/issues/1447

**Comment by vitaut** [comment]
This is indeed expected, updated the docs in https://github.com/fmtlib/fmt/commit/1f3d44b859ba55d6e71194e563e7ee477882c92e. Thanks for reporting.
