### ISSUE TITLE
error C4996: 'fmt::v8::detail::arg_mapper<Context>::map': was declared deprecated

### ISSUE THREAD

**Issue by bugproof** [fmtlib/fmt#2812]
Installed with vcpkg. Happens with version 8.1.1. Compiler: latest MSVC

`1>C:\vcpkg\installed\x64-windows-static\include\fmt\core.h(1706,42): error C4996: 'fmt::v8::detail::arg_mapper<Context>::map': was declared deprecated`

I managed to build by ignoring with `/wd"4996"`

**Comment by vitaut** [comment]
Most likely you are passing signed or unsigned char pointer which is deprecated. If this is not the case please provide a full repro.
