### ISSUE TITLE
Discussion: possible performance improvements

### ISSUE THREAD

**Issue by alexezeder** [fmtlib/fmt#2814]
I ran some benchmarks for a bit simplified versions of `fmt::print` and `fmt::format_to` with a single argument, i.e. a format string only. Something like this:
```
fmt::print("foo\n");
// and
fmt::format_to(buffer, "foobar");
// and
fmt::format_to(buffer, fmt::runtime("foobar"));
```
In other words, the library can skip some steps, like preparing arguments, passing them to internal functions and actual formatting. Is it really needed to address these usages? That's actually the question, I don't know. This is why it's not PR but a discussion, also it's not complete yet.

Here are the results:
| {fmt} function | old time | new time | performance improvement |
|----------------|----------|----------|-----------|
| print          | 109 ns   | 94.3 ns  | up to ~13% faster |
| format_to      | 9.54 ns  | 0.418 ns | up to ~96% faster |

All results, as well as the complete instruction to get your own results, can be found [in my legacy bnchmrk repo](https://github.com/alexezeder/fmt_bnchmrk_legacy/tree/skip_formatting).

<details>
<summary>Current diff</summary>

```diff
diff -Naur fmt_vanilla/include/fmt/core.h fmt_modified/include/fmt/core.h
--- fmt_vanilla/include/fmt/core.h      2022-03-15 18:20:58.000000000 +0300
+++ fmt_modified/include/fmt/core.h     2022-03-17 01:13:00.181587113 +0300
@@ -3157,6 +3157,13 @@
   return vformat_to(out, fmt, fmt::make_format_args(args...));
 }
 
+template <typename OutputIt,
+          FMT_ENABLE_IF(detail::is_output_iterator<OutputIt, char>::value)>
+FMT_INLINE auto format_to(OutputIt out, format_string<> fmt) -> OutputIt {
+  const auto& str = static_cast<string_view>(fmt);
+  return detail::copy_str<char>(str.begin(), str.end(), out);
+}
+
 template <typename OutputIt> struct format_to_n_result {
   /** Iterator past the end of the output range. */
   OutputIt out;
@@ -3235,6 +3242,15 @@
                            : detail::vprint_mojibake(f, fmt, vargs);
 }
 
+namespace detail {
+FMT_API void print(std::FILE*, string_view);
+}
+
+FMT_INLINE void print(std::FILE* f, format_string<> fmt) {
+  const auto& str = static_cast<string_view>(fmt);
+  detail::print(f, {str.data(), str.size()});
+}
+
 FMT_MODULE_EXPORT_END
 FMT_GCC_PRAGMA("GCC pop_options")
 FMT_END_NAMESPACE
diff -Naur fmt_vanilla/include/fmt/format.h fmt_modified/include/fmt/format.h
--- fmt_vanilla/include/fmt/format.h    2022-03-15 18:20:58.000000000 +0300
+++ fmt_modified/include/fmt/format.h   2022-03-17 00:58:16.677353685 +0300
@@ -859,10 +859,6 @@
 struct is_contiguous<basic_memory_buffer<T, SIZE, Allocator>> : std::true_type {
 };
 
-namespace detail {
-FMT_API void print(std::FILE*, string_view);
-}
-
 /** A formatting error such as invalid format string. */
 FMT_CLASS_API
 class FMT_API format_error : public std::runtime_error {
```
</details>

**Comment by vitaut** [comment]
I think these optimizations are not needed because in both cases more efficient APIs exist (`puts` and `copy`), not to mention format string compilation. But thanks for the suggestion anyway.

**Comment by alexezeder** [comment]
Yeah, that's true about more efficient API, but there are some advantages to have it in the library:
* it can be useful with some sort of variadic usages, in these cases, users can just use `fmt::` functions instead of handling usages without arguments by their own, of course if they even care about extra performance (but we care, don't we? 🙂);
* `print()` throws an exception in case if something goes wrong during printing, `puts`/`write` require another error-checking mechanism to be implemented, so they are not drop-in replacements in any place;
* it's my personal desire, but I really like when every printing functions look mostly the same, not some `std::puts("...")`/`std::fputs("...\n")`/`fmt::print("...\n")` zoo.

**Comment by vitaut** [comment]
I agree that there are some benefits but still not convinced if it's worth introducing separate overloads. BTW it seems to me that this optimization doesn't handle escaped braces correctly.

**Comment by alexezeder** [comment]
> BTW it seems to me that this optimization doesn't handle escaped braces correctly.

Sure, I completely forgot about that 🤦
