### ISSUE TITLE
How do I output a class for which << is overloaded?

### ISSUE THREAD

**Issue by VictorEijkhout** [fmtlib/fmt#2823]
With `cout` I can overload `operator<<(ostream& s,myobject& m)`. How is the equivalent mechanism with `fmtlib`?

**Comment by vitaut** [comment]
Quoting https://fmt.dev/latest/api.html#formatting-user-defined-types:

> To make a user-defined type formattable, specialize the formatter<T> struct template 

ostream operator<< support is also available: https://fmt.dev/latest/api.html#std-ostream-support
