### ISSUE TITLE
Any way to disable floating-point formatting?

### ISSUE THREAD

**Issue by jwt27** [fmtlib/fmt#2824]
I'd like to use fmt in some low-level code that needs to be compiled with `gcc -mgeneral-regs-only`.  This prevents the use of any floating-point operations and gcc will instead emit calls to software FP emulation routines.
As a result I'm seeing many undefined references to [all these functions](https://gcc.gnu.org/onlinedocs/gccint/Soft-float-library-routines.html) upon linking.

Would it be possible to add a macro, eg. `FMT_NO_FLOAT`. that disables all floating-point formatting?
Or alternatively, some way to ensure that floating-point functionality ends up in `format-inl.h` (and thus `libfmt.a`) and not in any other headers?

**Comment by jwt27** [comment]
```patch
--- a/include/fmt/format.h
+++ b/include/fmt/format.h
@@ -2314,6 +2314,30 @@ FMT_INLINE FMT_CONSTEXPR bool signbit(T value) {
   return std::signbit(static_cast<double>(value));
 }
 
+#ifdef FMT_NO_FLOAT
+
+template <typename Char, typename OutputIt, typename T,
+          FMT_ENABLE_IF(is_floating_point<T>::value)>
+FMT_CONSTEXPR20 auto write(OutputIt, T, basic_format_specs<Char>,
+                           locale_ref = {}) -> OutputIt {
+  throw format_error("FMT_NO_FLOAT");
+}
+
+template <typename Char, typename OutputIt, typename T,
+          FMT_ENABLE_IF(is_floating_point<T>::value &&
+                        !is_fast_float<T>::value)>
+inline auto write(OutputIt, T) -> OutputIt {
+  throw format_error("FMT_NO_FLOAT");
+}
+
+template <typename Char, typename OutputIt, typename T,
+          FMT_ENABLE_IF(is_fast_float<T>::value)>
+FMT_CONSTEXPR20 auto write(OutputIt out, T value) -> OutputIt {
+  throw format_error("FMT_NO_FLOAT");
+}
+
+#else
+
 template <typename Char, typename OutputIt, typename T,
           FMT_ENABLE_IF(is_floating_point<T>::value)>
 FMT_CONSTEXPR20 auto write(OutputIt out, T value,
@@ -2399,6 +2423,8 @@ inline auto write(OutputIt out, T value) -> OutputIt {
   return write(out, value, basic_format_specs<Char>());
 }
 
+#endif
+
 template <typename Char, typename OutputIt>
 auto write(OutputIt out, monostate, basic_format_specs<Char> = {},
            locale_ref = {}) -> OutputIt {
```

This seems to do the trick.

**Comment by vitaut** [comment]
There are `FMT_USE_FLOAT` and similar macros that disable floating-point.

**Comment by jwt27** [comment]
Somehow I totally missed those, thanks.
Do those introduce ODR violations when used?  The patch I posted earlier did so, that was a bad idea.

**Comment by vitaut** [comment]
> Do those introduce ODR violations when used?

If you compile all code with consistent options then no, otherwise not sure.

**Comment by jwt27** [comment]
Seems that they do, so that's not a solution.  I only have a few translation units where I can't use FP instructions.

**Comment by jwt27** [comment]
Looks like those `write()` functions only get instantiated when I use either `FMT_COMPILE` or any custom formatters.  So I guess the workaround is to not use those.
