### ISSUE TITLE
possibly operator<< degression?

### ISSUE THREAD

**Issue by risa2000** [fmtlib/fmt#2826]
After an update to the latest fmtlib (current branch) and building my project I noticed that the fmtlib started to complain about missing formatters for `std::thread::id`.

The following code does not compile if I uncomment the commented line:
```c++
#include <fmt/format.h>
#include <fmt/ostream.h>

#include <iostream>
#include <thread>

int main(int argc, char* argv[])
{
    std::cout << std::this_thread::get_id();
    //fmt::print("thread::id={}", std::this_thread::get_id());

    return 0;
}
```

I checked the `std` headers (Windows Visual Studio 19) and the `operator<<` is implemented in `thread` header as:
```c++
template <class _Ch, class _Tr>
basic_ostream<_Ch, _Tr>& operator<<(basic_ostream<_Ch, _Tr>& _Str, thread::id _Id) {
    return _Str << _Id._Id;
}
```
where `_Id._Id` is of type `_Thrd_id_t`, which is just an alias to `unsigned int`.

I thought this should work in `fmtlib` as well, or am I wrong?

**Comment by risa2000** [comment]
Just to add, after some more testing that also the custom `operator<<` implementation for custom types are no longer honored.

**Comment by vitaut** [comment]
This is essentially the same as #2768. Please see https://github.com/fmtlib/fmt/issues/2768#issuecomment-1040594969 for the fix.
