### ISSUE TITLE
MemoryWriter does not support std::put_time

### ISSUE THREAD

**Issue by duckie** [fmtlib/fmt#283]
`std::basic_ostream` supports the new `std::put_time` function.

I am not surprised since this is not the classic `<<` overload as according to the documentation: http://en.cppreference.com/w/cpp/io/manip/put_time. 

Not sure if cppformat should support it, but it would be nice.

**Comment by vitaut** [comment]
Good idea. It should be possible to do something like:

```c++
    std::time_t t = std::time(nullptr);
    std::tm tm = *std::localtime(&t);
    fmt::print("{:%c %Z}", tm);
```

with a custom formatting function.

**Comment by vitaut** [comment]
Time formatting has been implemented in https://github.com/cppformat/cppformat/commit/fa5ebd27d40348f019a58cc9035d7d6bf68b8ccf. Here's an example:

```c++
#include "fmt/time.h"

std::time_t t = std::time(nullptr);
fmt::print("The date is {:%Y-%m-%d}.", *std::localtime(&t));
```

This just needs to be documented.

**Comment by vitaut** [comment]
Done: http://fmtlib.net/dev/api.html#date-and-time-formatting
