### ISSUE TITLE
Compile error on using fmt as subdirectory in CMake

### ISSUE THREAD

**Issue by 0x6369616e** [fmtlib/fmt#2831]
Hello,
I'm trying to use the format library as a submodule in my project.. but it fails on compiling my source with the error: 

`fmt/include/fmt/format.h:1569:24: error: return type 'bool' must match previous return type 'int' when lambda expression has unspecified explicit return type`

Operating System: FreeBSD 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

Compile errors appear after including the following includes: 
`#include <fmt/format.h>`
`#include <fmt/format-inl.h>`
`#include <fmt/core.h>`

**Comment by vitaut** [comment]
AFAIC both return statements are consistent: https://github.com/fmtlib/fmt/blob/7ffe87c0bc8e69cd38941b92c0b33ab2e5cf3c57/include/fmt/format.h#L1564-L1570. What compiler version do you use?

**Comment by vitaut** [comment]
Closing as this looks like a compiler issue but feel free to reopen if this is not the case with more repro details.
