### ISSUE TITLE
Question: when building with FMT_EXCEPTIONS=0 and NDEBUG, are format errors UB?

### ISSUE THREAD

**Issue by mattiasljungstrom** [fmtlib/fmt#2834]
In a project with exceptions disabled and in release build, will (runtime) format errors be undefined behaviour or merely give incorrect / unintended results? (In debug build an assert is triggered.)

I've been testing various cases with lots of variations and everything seems stable so far, but I didn't find anything in the documentation about this. Can I assume that it's the intention of the library to never crash on invalid syntax? (In cases where it would throw exceptions.)

Thanks for your time and building this great library!

**Comment by vitaut** [comment]
There are no guarantees regarding errors with exceptions disabled and UB is possible. In general disabling exceptions is not recommended.

**Comment by mattiasljungstrom** [comment]
Thanks for the quick feedback!
