### ISSUE TITLE
Prebuilt doc handling

### ISSUE THREAD

**Issue by z3ntu** [fmtlib/fmt#2837]
Hi, I have a couple of notes regarding the docs that are included in release builds in `doc/html/`.

When you build in-tree with cmake (`cmake .`) then the docs are installed correctly with `make install`
But when you use a serapate build dir (`cmake -B build`) then the docs won't get installed with a `make install` - here we still want to get the docs installed

And even for the first scenario I don't get why it's guarded behind whether `doxygen` is installed - that won't be run at all when doing a normal build and `make install`.

Any clarification / fix for this would be appreciated.

**Comment by vitaut** [comment]
I'm not sure about `cmake -B build` but `make install` does install the docs when building/installing from a subdirectory. Note that you have to do `make doc` to build the docs before installation:

```
$ mkdir build
$ cd build
$ cmake ..
$ make
$ make doc
$ sudo make install
...
-- Installing: /usr/local/share/doc/fmt
-- Installing: /usr/local/share/doc/fmt/genindex.html
-- Installing: /usr/local/share/doc/fmt/syntax.html
...
```

**Comment by z3ntu** [comment]
Yes, then it builds the doc from scratch into `build/doc/html/` (and needs further dependencies during build-time) but in my opinion the behavior should be consistent between building `-B .` and `-B build` and if those prebuilt docs are available in the release package, then it should also install them in both cases without building them from scratch.

**Comment by vitaut** [comment]
I'm not sure where the inconsistency come from but open to a PR if it doesn't include the doc build into the default target.

**Comment by z3ntu** [comment]
So from what I understand this install directive https://github.com/fmtlib/fmt/blob/master/doc/CMakeLists.txt#L15-L17 triggers if there is something in `${CMAKE_CURRENT_BINARY_DIR}/html/` and if `CMAKE_CURRENT_BINARY_DIR` == `CMAKE_CURRENT_SOURCE_DIR` then it triggers on the prebuilt docs shipped in the release archive - even if you don't run the `doc` target to build the docs (as they're already built).

If those don't match then the prebuilt docs don't get installed (which is the case in out-of-tree builds).

A workaround for distro packaging could be after the normal build to run something like `cp -r $srcdir/doc/html $srcdir/build/doc/html` so those docs are in the build dir also to let cmake install them.
