### ISSUE TITLE
User defined fallback_formatter

### ISSUE THREAD

**Issue by W4RH4WK** [fmtlib/fmt#2838]
I am currently rewriting parts of a larger code base and I am unsure how to correctly connect existing infrastructure with fmt.

In that code base, the convention is to provide a `to_string` function along with your type.
In addition to this, there is a `to_string` template function that is enabled for the following types:
- types that have a `toString` member function
- types that can be used with `std::to_string`
- types that are convertible to string according to `std::is_convertible_v`

There is also a `has_to_string` type trait indicating whether this `to_string` mechanism is available.

Up until this point everything is independent of fmt.
Some types in this code base also have `fmt::formatter` specializations, but so far this did not lead to any conflicts.

Now I'd like to introduce a formatter that is enabled for types that use the `to_string` mechanism (according to our type trait `has_to_string`) and don't already have an `fmt::formatter` specialization.

I've put together an example that should contain all of the relevant code.
The string conversion utilities are inside a `foo` namespace.

<https://godbolt.org/z/fx3hjxTM9>

The example also contains 2 attempts for specializing a formatter:

1.  Results in ambiguity as there are already formatters for types that satisfy `has_to_string`.

2.  Triggers an incomplete type assertion.
    I don't fully understand this one, maybe related: [#2635](https://github.com/fmtlib/fmt/issues/2635).
    I also don't know whether it's a good idea to use `fmt::is_formattable` while implemenating a formatter as it seems like unwanted recursion.

I've also peeked at #1183 and `ostream.h` which uses `fallback_formatter`.
Semantically I think I want a fallback formatter here, similar to the one provided for the ostream operator.
Yet, this functionality seems to be only for internal use.

**Comment by vitaut** [comment]
Not 100% sure what exactly the question is but you could exclude types that have `std::to_string` from your specialization. I don't think you can use `is_formattable` in specialization of the same type because it would create a recursion.
