### ISSUE TITLE
Natural printing - A preliminary try

### ISSUE THREAD

**Issue by Mick235711** [fmtlib/fmt#2841]
`fmt::format` is fantastic, and fill up a significant string formatting hole in C++, and other language uniformly provide this kind of formatting too.

However... `fmt::print` is not so shiny. It currently appears as a convenient wrapper over `format`... so it does *formatted output*. While still common, this does leads to an unpleasant surprise:
```cpp
int x = 2;
fmt::print(x); // oops

std::vector vec{1, 2, 3};
auto some_range = vec | views::take(2);
fmt::print("{}\n", some_range); // Hmmm... 
```
In my opinion, the natural instinct to print an object would just be `print(obj)`... (In debugging times, I often just add `print(` and `)` wrappers to long expressions I want to print, and in C++ I have to additionally add `{}`... somewhat annoying? I'd say)

And this is (afaik) somewhat easy to support...?
```cpp
template<typename T>
void fmt::print(format_string<T...> fmt, T&&... args); // existing
// and other existing overloads...

// add one:
template<typename T>
void fmt::print(T&& obj) {fmt::print("{}", std::forward<T>(obj));}
```
Of course, this is just my personal opinion (summarized from day-to-day usage); the facility itself is great.

Currently the only valid single-argument invocation to `fmt::print` is `fmt::print("foo")` without format specifiers, which will be handled by the new overload to forward to `fmt::print("{}", "foo")`, which (I assume) has the same performance; so I don't see a problem here.

PS: This (of course) leads to a similar position to Python 3's `print()` function, where multiple arguments are supported: `print(a, b, c)` with separator default to a space (and additionally permit ending specification, etc). This is convenient for variadic arguments:
```cpp
template<typename... Ts>
void my_use(const Ts&... ts)
{
    // ...
    print(ts...);
}
```
where currently constructing something like `"{} {} {}"` with appropriate number of `"{}"`s is basically a non-starter (possible by constexpr string processing, but I assume no one wants to do this). However, I'm not proposing a similar facility due to:
1. We do not have language-supported named arguments (yet), and the current one simulated in `{fmt}` is for interpolated string literals. So separators basically have to be fixed.
2. `fmt::print("My name is {}.", "Mick")` is ambiguous.

If there's interest in this idea (single argument `fmt::print`), I can probably form a PR. Feel free to close if you think this is introducing too much complexity!😂

**Comment by vitaut** [comment]
Thanks for the suggestion. It is possible to add a new output function that does what you suggest (it shouldn't be part of print because at least because of ambiguous single string case) but I don't think it needs to be in the core library.
