### ISSUE TITLE
Some weird code in ostream.h

### ISSUE THREAD

**Issue by jcelerier** [fmtlib/fmt#2842]
I was reading the code and noticed the following: 

https://github.com/fmtlib/fmt/blob/master/include/fmt/ostream.h#L79

Introduced here:

https://github.com/fmtlib/fmt/commit/768061c85eafa4631acba555e06d5a6432b25093#diff-39be774d509c569b421ee9c510ad5f6d306f4a187ce4540b03c761d77a087b32L95

but maybe it's normal ?

**Comment by vitaut** [comment]
Good catch! I think this statement can be removed since it's a noop and all the required logic resides in `formatbuf` itself. A PR would be welcome.

**Comment by jcelerier** [comment]
Sure, doing that

**Comment by jcelerier** [comment]
PR in #2843
