### ISSUE TITLE
Getting compile issue with GCC-10.2.0 and c++20

### ISSUE THREAD

**Issue by rayhirak** [fmtlib/fmt#2845]
fmt/v8.0.1/include/fmt/ostream.h:123:8: error: partial specialization of 'struct fmt::v8::detail::fallback_formatter<T, Char, typename std::enable_if<fmt::v8::detail::is_streamable<T, Char>::value, void>::type>' after instantiation of 'struct fmt::v8::detail::fallback_formatter<const char*, char, void>' [-fpermissive]
  123 | struct fallback_formatter<T, Char, enable_if_t<is_streamable<T, Char>::value>>
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Getting compile issue with GCC-10.2.0 and c++20

**Comment by vitaut** [comment]
Please provide a self-contained repro, ideally on godbolt.

**Comment by vitaut** [comment]
Closing as I wasn't able to repro the issue in https://godbolt.org/z/Ta6qjh9cq. Feel free to reopen with more details.
