### ISSUE TITLE
Homebrew clang: `consteval` is broken

### ISSUE THREAD

**Issue by pitust** [fmtlib/fmt#2846]
On Homebrew clang, `consteval` does not seem to function correctly, similarly to apple clang. The reason is unfortunately too complex for my small brain to comprehend, but this code:
```c++
void do_log(const char* severity, const char* sevstr, std::string message) {
    fmt::print("{}{ >4}\x1b[0m {}\n", severity, sevstr, message);
}
```
fails to compile with this error: https://gist.github.com/pitust/d27cfbb6a82c8c5bf14fe38495248921

This seems to have been fixed for apple clang in 807ee5ec3152429f7103e825609f084c03a38ff4, but the issue persists in homebrew clang. A simple fix is to replace `!defined(__apple_build_version__)` with `!defined(__APPLE__)`, which correctly functions under homebrew clang 13.

Clang version:
```
$ clang --version
Homebrew clang version 13.0.1
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /opt/homebrew/bin
```

**Comment by vitaut** [comment]
Could you submit a PR with a fix and a short comment since you are in the best position to test the fix?

**Comment by mwinterb** [comment]
Does that run successfully? Isn't a colon needed after the opening brace
for the second substitution parameter?
`"{} {: >4}\x1b[0m {}\n"`

**Comment by vitaut** [comment]
Good catch, @mwinterb. The error is expected.

**Comment by pitust** [comment]
Oh, okay. The error message could use some clarity but i'm just nitpicking here. Thanks for help!
