### ISSUE TITLE
Link error on latest master for 32-bit Linux

### ISSUE THREAD

**Issue by glebm** [fmtlib/fmt#2851]
https://github.com/diasurgical/devilutionX/runs/5816428722?check_suite_focus=true

```
[100%] Linking CXX executable devilutionx
/home/runner/work/devilutionX/devilutionX/build/_deps/libfmt-src/include/fmt/core.h:2763:8: warning: type ‘struct float_specs’ violates the C++ One Definition Rule [-Wodr]
 struct float_specs {
  ...
```

**Comment by vitaut** [comment]
Looks like a configuration error, e.g. compiling different translation units with different versions of {fmt}. If this is not the case please provide a self-contained repro.

**Comment by glebm** [comment]
Looking further down the log, the actual error is:

```
/home/runner/work/devilutionX/devilutionX/build/_deps/libfmt-src/include/fmt/format.h:1559: undefined reference to `fmt::v8::detail::is_printable(unsigned int)'
```

**Comment by glebm** [comment]
Clearing the build cache on CI fixed it :shrug: Sorry for the noise

**Comment by vitaut** [comment]
No worries, glad it's resolved.
