### ISSUE TITLE
formatting a string with { generates an error in clangd

### ISSUE THREAD

**Issue by StandingPadAnimations** [fmtlib/fmt#2853]
So I have a string that generates an error message when it finds a misplaced {. However, when formatting the string with `fmt::format` like this:
```
fmt::format("Syntax Error: { found outside of function/if/else scope; Line {}", LineNumber)
```
clangd generates this error: 
```
Call to consteval function 'fmt::basic_format_string<char, unsigned int &>::basic_format_string<char [65], 0>' is not a constant expressionclang(invalid_consteval_call)
```

However, if I close the { with a }, the error goes away.

**Comment by OnurKader** [comment]
You need to escape the curlies by doubling them `{` should be `{{`
[godbolt](https://godbolt.org/z/8bP9aas7E)
[docs](https://fmt.dev/latest/syntax.html#format-string-syntax)
