### ISSUE TITLE
durations of floating point type or smaller than `long long` cause "conditional expression is constant" on MSVC

### ISSUE THREAD

**Issue by lefticus** [fmtlib/fmt#2854]
/W4 is required. Seems to happen in any version of {fmt}, cannot reproduce in GCC or Clang

They appear to be similar but unrelated warnings.

Here is a minimal repro:

https://compiler-explorer.com/z/Yve79WaTf

```cpp
#include <fmt/format.h>
#include <fmt/chrono.h>
#include <chrono>

int main()
{
  // this works
  //using milliseconds = std::chrono::duration<long long, std::milli>;

  // but this does not
  //using milliseconds = std::chrono::duration<int, std::milli>;

  // and neither does this
  using milliseconds = std::chrono::duration<double, std::milli>;

  fmt::print("ms {}", milliseconds{});
}
```

Warning stems from this line:

https://github.com/fmtlib/fmt/blob/d141cdbeb0fb422a3fb7173b285fd38e0d1772dc/include/fmt/chrono.h#L246-L260

and this line:

https://github.com/fmtlib/fmt/blob/d141cdbeb0fb422a3fb7173b285fd38e0d1772dc/include/fmt/chrono.h#L82-L87

**Comment by vitaut** [comment]
AFAICS this has been fixed in #2518 already.
