### ISSUE TITLE
Printf formatter<T> incorrect err msg

### ISSUE THREAD

**Issue by artoka** [fmtlib/fmt#2855]
Based on #2245, specializing `formatter<T>` for printf-style functions is not supported. 

Yet, attempting to `auto b = ::fmt::sprintf("%i %s", 1, color::blue);`, adapted from the `fmt::formatter<color>: ` example, will give:

`d:\wf2\code\lib\fmt\include\fmt\core.h(1720): error C2338: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt`

If this is not supported, the error seems incorrect?

**Comment by vitaut** [comment]
Yeah, the error message is the same for format and printf and is slightly misleading. Making type formattable doesn't make it sprintaffable.
