### ISSUE TITLE
How to copy  dynamic_format_arg_store<format_context>?

### ISSUE THREAD

**Issue by huangzhentao** [fmtlib/fmt#2857]
I used `fmt::dynamic_format_arg_store<fmt::format_context> _argStore;` 
to save the parameters. But I want to copy it to a new object, What should I do please?

**Comment by vitaut** [comment]
`dynamic_format_arg_store` doesn't support copying. You should use a tuple or some container for passing objects around and create a store when doing actual formatting.

**Comment by huangzhentao** [comment]
> 

thx a lot
