### ISSUE TITLE
`basic_format_string` should be convertible ignoring little differences?

### ISSUE THREAD

**Issue by onihusube** [fmtlib/fmt#2863]
I encountered an error when I made a function to append a process to an existing `std::string` object while formatting it.

```cpp
template <typename... Args>
void log(std::string& str, fmt::format_string<Args...> fmtstr, Args&&... args) {
  // First, find the length you need.
  const std::size_t add_len = fmt::formatted_size(fmtstr, args...);  // ng
  const std::size_t org_len = str.length();

  // reserve()
  str.reserve(org_len + add_len);

  // Format and output
  fmt::format_to(std::back_inserter(str), fmtstr, std::forward<Args>(args)...);
}
```

https://godbolt.org/z/eYGjavYhW

This is apparently due to the fact that the type of `std::format_string<Args...>` is slightly different depending on the presence or absence of `std::forward()`.

```cpp
template <typename... Args>
void log(std::string& str, fmt::format_string<Args...> fmtstr, Args&&... args) {
  // decltype(fmtstr) = fmt::basic_format_string<char, int> 
  const std::size_t add_len = fmt::formatted_size(fmtstr, args...);  // ng
  // fmt::formatted_size() 1st argument type = fmt::basic_format_string<char, int&> 

  ...
}
```

Therefore, in the user-defined constructor of `basic_format_string`, a conversion from `basic_format_string` to `string_view` is required, and since that of `basic_format_string` is not `constexpr`, it cannot be executed as a constant expression, resulting in an error.

The compilation will pass if you write

```cpp
template <typename... Args>
void log(std::string& str, fmt::format_string<Args...> fmtstr, Args&&... args) {
  const std::size_t add_len = fmt::formatted_size(fmtstr, std::forward<Args>(args)...);  // ok

  ...

  fmt::format_to(std::back_inserter(str), fmtstr, std::forward<Args>(args)...);
}
```

However, in this case, the argument may be moved twice.

To allow this code, it appears that the conversion must be allowed to ignore the little differences in `basic_format_string<Char, Args...>`. (Just making `basic_format_string::operator string_view()` `constexpr` would cause another error since it is not an immediate context).

I felt like I wasn't likely to encounter it very often, but I thought it was a pretty hard error to notice, so I am reporting it.

**Comment by vitaut** [comment]
This is expected. The arguments must be forwarded and they won't be moved twice.
