### ISSUE TITLE
[feature request] std::filesystem::path support

### ISSUE THREAD

**Issue by nicolasnoble** [fmtlib/fmt#2865]
Basically the title. It'd be nice to have a default support for `std::filesystem::path`. Right now we have to use `.string()`, which feels superfluous.

**Comment by realnc** [comment]
You can add support yourself with:

```c++
/* Make std::filesystem::path formattable.
 */
template <>
struct fmt::formatter<std::filesystem::path>: formatter<std::string_view>
{
    template <typename FormatContext>
    auto format(const std::filesystem::path& path, FormatContext& ctx)
    {
        return formatter<std::string_view>::format(path.string(), ctx);
    }
};
```

**Comment by nicolasnoble** [comment]
Sure, that too. I just think it'd be appropriate for direct support in fmt
itself.

**Comment by vitaut** [comment]
A PR to add a formatter specialization for path is welcome.

**Comment by vitaut** [comment]
A basic path formatter has been added in https://github.com/fmtlib/fmt/commit/f0903ad9df429f3a610da45de5161c076cf2d268.
