### ISSUE TITLE
CMake quesiton: "missing and no known rule to make it"

### ISSUE THREAD

**Issue by Mebus** [fmtlib/fmt#2868]
Hallo folks,

I have got a question. I am somewhat new to CMake. I am using fmtlib across several packages which I put together with CPM, but I keep getting this error:

```
[0/2] Re-checking globbed directories...
ninja: error: '_deps/fmt-build/libfmtd.a', needed by '_deps/mylib-build/libmylib.a', missing and no known rule to make it
```

Can somebody give me a tip on how to resolve this?

Mebus

**Comment by vitaut** [comment]
There is no enough information to say what's going wrong. Please make sure to follow the usage instructions in https://fmt.dev/latest/usage.html#usage-with-cmake and if you still get an error provide a full repro.
