### ISSUE TITLE
Support for char16_t/u16string?

### ISSUE THREAD

**Issue by msvetkin** [fmtlib/fmt#2874]
It seems that `u16string` is not supported anymore.
I have looked into another issues #698 and #1412 and it seems it used to be supported around version 7.0.0.
Example: https://godbolt.org/z/GPsdq4d7s

Is it still possible to implement in user code?

**Comment by vitaut** [comment]
`char16_t` is supported, you just need to include `fmt/xchar.h` (https://godbolt.org/z/76j9s4bqs):

```c++
#include <fmt/xchar.h>
#include <string>

int main() {
  std::u16string s = fmt::format(u"The answer is {}.", 42);
}
```
