### ISSUE TITLE
Argument conversion error

### ISSUE THREAD

**Issue by bloodgain** [fmtlib/fmt#2876]
I'm running into a strange argument conversion error using fmt under spdlog v1.9.2:

error C2664: 'void spdlog::logger::info<unsigned int&>(fmt::v8::basic_format_string<char,T &>,unsigned int &)': cannot convert argument 2 from 'unsigned int' to 'unsigned int &'
        with
        [
            T=fmt::v8::detail::bigint::bigit
        ]

I have the following definitions and use:

```cpp
// defined by MSVC in basetsd.h
typedef unsigned int UINT32, *PUINT32;

struct BITS {
    unsigned int bit00 : 1;
    unsigned int bit01 : 1;
    //      .
    //      .
    //      .
    // and so on until...
    unsigned int bit31 : 1;
};

// Current Time Register
struct CTR_REG {
    unsigned int current_time : 32;
};

union CTRRegisterType {
    UINT32 wholeDword;
    CTR_REG fields;
    BITS bits;
};

CTRRegisterType ctr;
ctr.wholeDword = 12345;  // assume any call that writes a 32 bit value here

const auto filelogger = spdlog::basic_logger_mt("filelog", "somefile.log");

// casting to ulong will compile
filelogger->info(" First Read Time: {}", static_cast<unsigned long>(ctr.fields.current_time));

// doing an assignment then writing to unsigned int will compile
unsigned int ctime = ctr.fields.current_time;
filelogger->info(" First Read Time: {}", ctime);

// using the value directly will NOT compile, giving the error
filelogger->info(" First Read Time: {}", ctr.fields.current_time);

// casting to uint will NOT compile either! What?
filelogger->info(" First Read Time: {}", static_cast<unsigned int>(ctr.fields.current_time));
````

As you can see, I'm doing C++ but doing a little bit of C-like low-level work. This is the first time I've run into integer conversion issues at compile time. If anything, I probably have some unsanitary implicit conversions that could bite me at run time eventually.

Sure, it works with static_cast to ulong or an extra variable assignment step, but aside from that not being quite correct, it's a hassle. I just converted us away from iostreams/fstreams and bad custom logger classes to spdlog, and I really don't want to have to deliver the news that we have to static_cast every time we want to print an integer from these unions/structs, as they are core to our project.

Both spdlog and my project were built using Using VS 2017 v15.9.42.

Any ideas what I might be doing wrong, or if this is a limitation in spdlog/fmt -- intentional or otherwise?

Thanks!

**Comment by bloodgain** [comment]
Cross-posted issue with spdlog:
https://github.com/gabime/spdlog/issues/2353

FYI, if it's something I can help fix, I _am_ willing to help!

**Comment by vitaut** [comment]
Unfortunately bit fields are not supported directly due to limitations of "perfect" forwarding. However, casting to `unsigned` works (https://godbolt.org/z/d6K73Tes4):

```c++
fmt::print(" First Read Time: {}", static_cast<unsigned int>(ctr.fields.current_time));
```

So this looks like an issue in spdlog.

**Comment by bloodgain** [comment]
Thanks for the clarification!
