### ISSUE TITLE
format() copies its result into std::string instead of writing directly

### ISSUE THREAD

**Issue by user-45-20** [fmtlib/fmt#2877]
Looking at the implementation of `fmt::format`, it calls `vformat(string_view fmt, format_args args)`, which looks like this:
```
FMT_FUNC std::string vformat(string_view fmt, format_args args) {
  // Don't optimize the "{}" case to keep the binary size small and because it
  // can be better optimized in fmt::format anyway.
  auto buffer = memory_buffer();
  detail::vformat_to(buffer, fmt, args);
  return to_string(buffer);
}

// to_string implementation
template <typename Char, size_t SIZE>
FMT_NODISCARD auto to_string(const basic_memory_buffer<Char, SIZE>& buf)
    -> std::basic_string<Char> {
  auto size = buf.size();
  detail::assume(size < std::basic_string<Char>().max_size());
  return std::basic_string<Char>(buf.data(), size);
}
```

It creates a temporary buffer, formats the string into that buffer, and then copies that result into an `std::string`, which is then returned.

Wouldn't it be possible to implement `vformat` in such a way that it constructs the result directly in an `std::string` instance, thus avoiding the copy? For instance, I can manually do this:

```
std::string out;
fmt::format_to(std::back_inserter(out), "Hello, {}", "world");
```

this will internally construct an `iterator_buffer<std::back_insert_iterator<std::string>>`, which will write directly to the string.

Looking at implementations of `std::format` in [Microsoft's STL](https://github.com/microsoft/STL/blob/39332e104d5274b8b1f48ebe380ba1dfc7ce4cc0/stl/inc/format#L3458) and [LLVM's libc++](https://github.com/llvm/llvm-project/blob/e547a333a43348a8a7ec9460f37696ecc5453e56/libcxx/include/format#L338), it seems they do it this way as well.

**Comment by vitaut** [comment]
While it is possible to do, whether it's a regression or an optimization may depend on the inputs. As you've already found out in cases where you want to write to a string directly you can use `format_to`.
