### ISSUE TITLE
unused variable zero

### ISSUE THREAD

**Issue by Sil3ntStorm** [fmtlib/fmt#2878]
`constexpr Char zero = static_cast<Char>('0');` in `do_write_float` (format.h) is not used in all cases, leading to an unused (constexpr) variable warning, which leads to compilation errors.
The issue is not present with 8.0.1, so it's a regression.

**Comment by vitaut** [comment]
Please provide a godbolt repro.

**Comment by Sil3ntStorm** [comment]
Godbolt doesn't have the facilities to reproduce this by the looks of it.

**Comment by vitaut** [comment]
Then please report to your compiler vendor because the constant in question is used.

**Comment by fredemmott** [comment]
For anyone else finding this from search:

- worked around in https://github.com/fmtlib/fmt/commit/3e28dc021cf38b14ac0e2b1a046f783e094bfffc
- bug in MSVC 2022 was reported to MS at https://developercommunity.visualstudio.com/t/CL-version-193231328-generates-false-w/10040986 and a fix is ready for a future update
