### ISSUE TITLE
Runtime error when passing single argument with curly braces.

### ISSUE THREAD

**Issue by drakbar** [fmtlib/fmt#2879]
[repro](https://godbolt.org/z/oGnzTesnr) <-- godbolt link

First off, awesome library! 

Secondly, I feel like this particular issue is partially a misuse of the `fmt::format` interface, but I am not fully committed to feeling since you can call `fmt::format` with a single argument that excludes curly braces. Such as:
```c++
#include <iostream>
#include <fmt/core.h>
std::cout << fmt::format("The answer is 42") << '\n';
```

However, if any curly braces are included it results in a runtime error, which in my opinion is the worst type of error. Example:
```c++
#include <iostream>
#include <fmt/core.h>
std::cout << fmt::format("The answer is {}") << '\n'; // results in runtime error
```
The fix is relatively simple, but I don't fully know the consequences of its implementation because of my lack of intimate knowledge of the library's inner workings.
```c++
// core.h
template <typename... T>
FMT_NODISCARD FMT_INLINE auto format(const char* arg) -> std::string {
  return std::string(arg);
}

template <typename... T>
FMT_NODISCARD FMT_INLINE auto format(std::string arg) -> std::string {
  return arg;
}
``` 
In my repro link is an example of code where this functionality makes more sense. I can create a PR but I am not fully aware of the contribution process. Anyways I wanted to toss out for feedback on concerns about this before I went any further.

**Comment by vitaut** [comment]
In C++20 you'll get a compile-time error: https://godbolt.org/z/o1aKjTTzf. I think changing the behavior for the zero-argument case is undesirable because it may hide a genuine error (missing argument) and would be inconsistent with `printf` and Python's `str.format.`

**Comment by drakbar** [comment]
Well that is good news that it works in C++20.

I am not sure what you mean that it would be inconsistent with `printf`, and yes it does not model python. I understand the reluctance to include these changes.  The code base is pretty tight and the additional functions will most assuredly increase compile time. 

While this does a pretty good job at modeling the feeling of python's string formatting. I feel like the curly brace limitation is quirky and something to me doesn't feel right. Considering that `json` is a prevalent format I would imagine that a much less frequently used character would be used as delimiters. Yes, I realized that there is a "workaround" doing things such as:
```c++
fmt::print(fmt::emphasis::bold | fg(fmt::color::dark_orange), "{}", json);
```
However, this doesn't feel right to me. Regardless, I am adding the changes to this thread for those who may run into this similar issue.
##### color.h
```c++
template <typename Char>
void vformat_to(buffer<Char>& buf, const text_style& ts, string_view str) {
  bool has_style = false;
  if (ts.has_emphasis()) {
    has_style = true;
    auto emphasis = detail::make_emphasis<Char>(ts.get_emphasis());
    buf.append(emphasis.begin(), emphasis.end());
  }
  if (ts.has_foreground()) {
    has_style = true;
    auto foreground = detail::make_foreground_color<Char>(ts.get_foreground());
    buf.append(foreground.begin(), foreground.end());
  }
  if (ts.has_background()) {
    has_style = true;
    auto background = detail::make_background_color<Char>(ts.get_background());
    buf.append(background.begin(), background.end());
  }
  buf.append(str.begin(), str.end());
  if (has_style) detail::reset_color<Char>(buf);
}
FMT_END_DETAIL_NAMESPACE

void print(std::FILE* f, const text_style& ts, const char* str) {
  auto buffer   = basic_memory_buffer<char>();
  detail::vformat_to(buffer, ts, string_view(str));
  buffer.push_back('\0');
  detail::fputs(buffer.data(), f);
}

void print(const text_style& ts, const char* str) {
  return print(stdout, ts, str);
}

void print(const text_style& ts, std::string str) {
  return print(stdout, ts, (const char*)str.data());
}
```
##### core.h
```c++
template <typename... T>
FMT_NODISCARD FMT_INLINE auto format(const char* arg) -> std::string {
  return std::string(arg);
}

template <typename... T>
FMT_NODISCARD FMT_INLINE auto format(std::string arg) -> std::string {
  return arg;
}

FMT_API void vprint(string_view str);
FMT_API void vprint(string_view fmt, format_args args);

FMT_INLINE void print(const char* str) {
  return vprint(string_view(str));
}

FMT_INLINE void print(std::string str) {
  return vprint(string_view(str));
}

FMT_INLINE void print(std::FILE* f, const char* str) {
  return vprint(f, string_view(str));
}

FMT_INLINE void print(std::FILE* f, std::string str) {
  return vprint(f, string_view(str));
}
FMT_MODULE_EXPORT_END
```
##### format-inl.h
```c++
FMT_FUNC void vprint(std::FILE* f, string_view str) {
  memory_buffer buffer;
  buffer.append(str.begin(), str.end());
  detail::print(f, {buffer.data(), buffer.size()});

FMT_FUNC void vprint(string_view str) {
  vprint(stdout, str);
}
```
##### ostream.h
```c++
FMT_MODULE_EXPORT
template <typename Char>
void print(std::basic_ostream<Char>& os, std::string str) {
  auto buffer = basic_memory_buffer<Char>();
  buffer.append(arg);
  detail::write_buffer(os, buffer);
}

FMT_MODULE_EXPORT
template <typename Char>
void print(std::basic_ostream<Char>& os, const char* str) {
  print(os, std::string(str));
}
```

##### simple example
```c++
#include <iostream>
#define FMT_HEADER_ONLY
#include <fmt/core.h>
#include <fmt/ostream.h>
#include <fmt/color.h>
#include <fmt/printf.h>

int main()
{
    const char* json    = "{\"name\": \"drakbar\", \"language\" : \"c++\"}\n";
    std::string jsonStr = std::string(json);

    std::cout << fmt::format(json);
    std::cout << fmt::format(jsonStr);
    fmt::print(fmt::emphasis::bold | fg(fmt::color::dark_orange), json);
    fmt::print(fmt::emphasis::bold | fg(fmt::color::light_sea_green), jsonStr);
    fmt::print(jsonStr);
    fmt::print(std::cout, json);
    fmt::print(std::cout, jsonStr);
    fmt::print(stderr, json);
    fmt::print(stderr, jsonStr);
    fmt::printf(json);
    fmt::printf(jsonStr);
    fmt::fprintf(stderr, json);
    fmt::fprintf(stderr, jsonStr);
    std::cout << fmt::sprintf(json);
    std::cout << fmt::sprintf(jsonStr);
}
```

**Comment by willeccles** [comment]
> I am not sure what you mean that it would be inconsistent with `printf`

For decades it has been the accepted practice that you should never call `printf` with a runtime string as an argument, as it may contain format specifiers and cause all sorts of fun bugs. For example, if you print a user's name, you should always do `printf("%s", user_name)` because it may contain format specifiers and cause issues with missing arguments (which is a big security hole).

`fmt` is smarter in that it actually reports the error instead of silently causing undefined behavior like `printf` would, but the same practice still applies: where you'd use `printf("%s", json)`, you should use `fmt::print("{}", json)`. Most compilers will even warn you if you call `printf` with a runtime string as its first argument.

Sorry for reviving an ancient thread, but this may be useful information for future readers.
