### ISSUE TITLE
Problem when using internal::FPUtil::isinfinity (fmt 4.x) on IBM i (AS/400) 7.4 ILE C++ compiler

### ISSUE THREAD

**Issue by d7d1cd** [fmtlib/fmt#2880]
**Problem**
When trying to run this code:
`std::cout << (fmt::BasicMemoryWriter<char>() << 4.2).str();`
I get the output of the text "inf".

**Analysis**
There is no _isinf_ function in the IBM i standard library. As a result, this condition is always false:
https://github.com/fmtlib/fmt/blob/3e8d2c57f3aee665e4672cd4e3fbf69cc2ebff2d/fmt/format.h#L464

**Question**
How to solve this problem, given that in the IBM i standard library in the complex file there is a class template _Ctr that has a static method _Isinf. It allows you to do the following:
`std::cout << std::boolalpha << std::_Ctr<double>::_Isinf(4.2);`
The output will be _false_.

**Comment by vitaut** [comment]
Version 4.x is no longer actively developed (although PRs with simple fixes are welcome). The current master doesn't use `isinf` for floating-point formatting, only chrono.h which is an optional header.

**Comment by vitaut** [comment]
> But why should I take the code from SO if I have an implementation of isinf in the form of std::_Ctr::_Isinf(x)?

You could try using `std::_Ctr::_Isinf` too.

> Is that how it was originally intended?

Yes, the dummy implementations don't do anything, they are just for SFINAE.

**Comment by d7d1cd** [comment]
But can I, since I want to use fmt only on a specific system, remove the dummy functions altogether and use the isinf implementation call from my standard library without checking?

**Comment by vitaut** [comment]
Sure
