### ISSUE TITLE
full round trip conversions of floating point numbers with grisu on sprintf by default

### ISSUE THREAD

**Issue by nevion** [fmtlib/fmt#2883]
I mean if someone is using fmt and sprintf and somewhat expecting python , the default expectations on floating point are round trip; just like fmt::format; if they want different they can specify that.  If it's contentious maybe we can set a macro?  How would you maintainable change the behavior if this wouldn't be come the default and had where printf syntax has it's reasons for prevailing over {} style?

https://godbolt.org/z/frGKqrnnv

**Comment by vitaut** [comment]
`sprintf` is mostly for migrating legacy code and we shouldn't be changing the behavior there. In new code or if you need round-trip guarantees, use `format`.
