### ISSUE TITLE
Providing an utility function to format_to a span ?

### ISSUE THREAD

**Issue by jcelerier** [fmtlib/fmt#2884]
Hi,

I'm using quite heavily in some code 

    std::span<char> buffer;
    ...
    fmt::format_to_n(buffer.data(), buffer.size(), "....");

and am wondering if it wouldn't make sense to have a format_to(span<T>, ...) overload directly which would be

```c++
template <typename Span, typename... T, FMT_ENABLE_IF(detail::is_some_kind_of_span<Span, char>::value)>
FMT_INLINE auto format_to(Span out, format_string<T...> fmt, T&&... args) 
  -> ?? 
{
  return vformat_to_n(out.data(), out.size(), fmt, fmt::make_format_args(args...));
}
```

(but maybe it should be called `format_to_trunc`, with a `format_to(span,...)` version doing what `format_to` with an iterator to something that cannot grow does, I guess throwing an expression at best and crashing at worse ?)

**Comment by jcelerier** [comment]
(same question for string_view ; to me string_view has no real point over std::span<char> but I imagine that the name encourages people to use it as a read-only view)

**Comment by vitaut** [comment]
Thanks for the suggestion. Since this is easily expressible via `format_to_n`, I don't think we should add yet another formatting function. However, you could add one in your project.
