### ISSUE TITLE
Test 'compile-fp-test' compilation fails on gcc 11 and clang 14

### ISSUE THREAD

**Issue by jrmelsha** [fmtlib/fmt#2886]
https://github.com/fmtlib/fmt/blob/7e4ad40171aa552d38cb99a5c181a0d7b150facc/include/fmt/format.h#L2341

```
error: ‘(+Inf - +Inf)’ is not a constant expression
```

Fails with both c++20 and gnu++20.

I will look into an equivalent constant evaluated expression.

**Comment by jrmelsha** [comment]
https://godbolt.org/z/qeo5bjbxT

Was due to `-O3`

**Comment by vitaut** [comment]
Worked around in https://github.com/fmtlib/fmt/commit/ae963e444fcdf1ad45f662e0c706568f34506528, thanks for reporting!
