### ISSUE TITLE
Regression: ostream support broken

### ISSUE THREAD

**Issue by jrmelsha** [fmtlib/fmt#2887]
Example taken from fmt docs:

```
#include <fmt/ostream.h>

class date {
  int year_, month_, day_;
public:
  date(int year, int month, int day): year_(year), month_(month), day_(day) {}

  friend std::ostream& operator<<(std::ostream& os, const date& d) {
    return os << d.year_ << '-' << d.month_ << '-' << d.day_;
  }
};

int main() {
  std::string s = fmt::format("The date is {}", date(2012, 12, 9));
}
```

Broken: https://godbolt.org/z/3KM6M7cbW
Working on previous release: https://godbolt.org/z/aaPnPfrPM
Effects: Clang, GCC, C++20

**Comment by jrmelsha** [comment]
I see that it is caused by `FMT_DEPRECATED_OSTREAM`. While I was able to fix my issues, I think this is an overall huge change and many dependencies use this functionality are currently broken on the master branch. Either way, would be a good thing to notate in the documentation to tell users that this is now the new norm. Thank you!

**Comment by vitaut** [comment]
It will be documented in release notes and in the developer docs: https://fmt.dev/dev/api.html#ostream-api.
