### ISSUE TITLE
format no longer working on c++20 and above

### ISSUE THREAD

**Issue by kitanatahu** [fmtlib/fmt#2893]
(https://godbolt.org/z/P8szrvdbE)

format no longer works with dynamic strings due to consteval with c++20 and c++2b

I suggest a version should be provided which is runtime evaluated, for use for example where the string is a template read from a file

**Comment by vitaut** [comment]
You can pass a dynamic (runtime) string by passing it in `fmt::runtime` (https://godbolt.org/z/5n33h66fW):

```
  std::string dynamic = "Hello there!";
  fmt::format(fmt::runtime(dynamic));
```

Quoting the documentation (https://fmt.dev/latest/api.html):

> To pass a runtime format string wrap it in [fmt::runtime()](https://fmt.dev/latest/api.html#_CPPv4I0EN3fmt7runtimeE13basic_runtimeI6char_tI1SEERK1S).
