### ISSUE TITLE
Add an option to reset direction override characters

### ISSUE THREAD

**Issue by TestingPlant** [fmtlib/fmt#2910]
If a right to left override character appears in a string, it can break the rest of the format string.

For example, with the following code ([link](https://godbolt.org/z/xeb3zq4Gq)):

```cpp
#include <fmt/core.h>
#include <string>

int main() {
    // \u202e is a right to left override
    const std::string filename = "\u202efilename";
    fmt::print("Do you want the file '{}' to be removed forever?\n", filename);
}
```

anything after the filename isn't readable.

One solution would be to add a new format specification like `p` (**p**reserve the format string) which adds an override for the original direction of the replacement field. For example, if the replacement field was originally left to right, it'd add a left to right override, and vice versa.

**Comment by vitaut** [comment]
The standard format specifiers are pretty much fixed at this point but you can either use an extension API to implement this or use the `?` specifier to escape `\u202e`: https://godbolt.org/z/9Y4nKqz77.
