### ISSUE TITLE
fmt::v8::format_error Generated when running

### ISSUE THREAD

**Issue by WWjsnt10** [fmtlib/fmt#2916]
When I try to format some strange path, the fmt lib generate the fmt::v8::format_error.

here is my code:
std::string path = /tmp/pipe_{163CE907-C4A9-4B29-9834-DD0D3B62ED04};
std::string name = "[2022-05-31]";
 return fmt::format("{} - {}",name,path);

**Comment by OnurKader** [comment]
You're missing double quotes in the `path` variable, can you post the actual code?

[Seems to work fine](https://godbolt.org/z/csxzdh8x3)
