### ISSUE TITLE
fmt without dynamic allocations?

### ISSUE THREAD

**Issue by basprins** [fmtlib/fmt#2926]
I am using fmt format on a microcontroller. It looks like it results in heap fragmentation (haven't proven it, so please forgive me if this is not possible). 
Is it possible to configure fmt so that it will only use memory on the stack? Or is fmt not designed for using it on microcontrollers with less intelligent heap management?

**Comment by vitaut** [comment]
You can use [`format_to`](https://fmt.dev/latest/api.html#_CPPv4I0DpEN3fmt9format_toE8OutputIt8OutputIt13format_stringIDp1TEDpRR1T) or [`format_to_n`](https://fmt.dev/latest/api.html#_CPPv4I0DpEN3fmt11format_to_nE18format_to_n_resultI8OutputItE8OutputIt6size_t13format_stringIDp1TEDpRR1T) to format into a stack-allocated buffer.
