### ISSUE TITLE
[MSVC] "More than one partial specialization matches the template argument list", one of them could be "fmt::detail::is_map<T>"

### ISSUE THREAD

**Issue by rturrado** [fmtlib/fmt#2930]
I'm working on: 4bb3af7a6ba4330284fb490b0f471172fda87f07
I'm basically doing this: https://godbolt.org/z/5EYWM91sa
And I'm finding that, with Visual Studio 2022 17.2.1, I get the following error:

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\type_traits(577,1): error C2752: 'fmt::v8::formatter<undirected_graph_map<char,int>,char,void>': more than one partial specialization matches the template argument list
  D:\Programacion\code\c++\the_modern_c++_challenge\build\NinjaMultiConfig\test\_deps\fmt-src\include\fmt\ranges.h(418,1): note: could be 'fmt::v8::formatter<T,Char,std::enable_if<fmt::v8::detail::is_map<T>::value,void>::type>'
  D:\Programacion\code\c++\the_modern_c++_challenge\include\the_modern_c++_challenge\chapter_06_algorithms_and_data_structures\problem_058_shortest_path_between_two_nodes.h(53,13): note: or       'fmt::v8::formatter<undirected_graph_map<Node,Distance>,char,void>'
```

I can fix the compiler error with:

``` 
template <typename Node, typename Distance>
struct fmt::is_range<undirected_graph_map<Node, Distance>, char> : std::false_type {};

template <typename Node, typename Distance>
struct fmt::detail::is_map<undirected_graph_map<Node, Distance>> : std::false_type {};
```

But 1) I understand I shouldn't be using `fmt::detail` in my code and 2), and most importantly, I am not sure I should need to add any of those two pair of lines (since everything seems to work fine in `gcc` without them).

**Comment by vitaut** [comment]
We could add `fmt::is_map` to disable the built-in `formatter` specialization for maps. A PR is welcome.

**Comment by rturrado** [comment]
I've been having a look at the fmt/ranges.h code, and I'm now thinking that this may be a no issue.

The problem here was that, since my `undirected_graph_map<Node,Distance>` had a `public: using mapped_type = Distance;`, that was making it a map to the eyes of `fmt` (if I understand correctly the code below):

```
template <typename Char>
struct is_std_string_like<fmt::basic_string_view<Char>> : std::true_type {};

template <typename T> class is_map {
  template <typename U> static auto check(U*) -> typename U::mapped_type;
  template <typename> static void check(...);

 public:
#ifdef FMT_FORMAT_MAP_AS_LIST
  static constexpr const bool value = false;
#else
  static constexpr const bool value =
      !std::is_void<decltype(check<T>(nullptr))>::value;
#endif
```

So, in this particular case, where my custom class, `undirected_graph_map`, only contains a `map` member, and I just want to print it as fmt prints a map, not only I don't need the two `is_range ... false_type`, and `is_map ... false_type` lines, but I don't need my custom formatter either.

PS. The only thing I'm wondering then is: since MSVC seems to be right here because there are actually two possible formatters, why is gcc not complaining?

**Comment by vitaut** [comment]
> I don't need the two is_range ... false_type, and is_map ... false_type lines, but I don't need my custom formatter either.

Great, I'm closing the issue then.

> The only thing I'm wondering then is: since MSVC seems to be right here because there are actually two possible formatters, why is gcc not complaining?

I am not sure.
