### ISSUE TITLE
Is there a known issue with ostream operator<< or am I doing something wrong?

### ISSUE THREAD

**Issue by mark-99** [fmtlib/fmt#2935]
My understanding is types which define ostream op<<() should be formattable provided you include <fmt/ostream.h>, from the docs and this SO answer: 

https://stackoverflow.com/questions/58596669/printing-using-fmt-library

However here's the exact thing from the SO answer and it doesn't work: https://godbolt.org/z/qacYhqh79

Here's another similar example: https://godbolt.org/z/qxqs45cqo

**Comment by mwinterb** [comment]
`ostream` support for a type was made opt-in. https://fmt.dev/dev/api.html#ostream-api. See #2357 for background.
