### ISSUE TITLE
[Feature request] support Argument-determined Width for ANSI escaped/formatted strings

### ISSUE THREAD

**Issue by AdelKS** [fmtlib/fmt#2942]
Hello,

In the process of writing code to display a table, I discovered that `{fmt}` doesn't support proper padding on ANSI escaped strings. A code is worth a thousand words:

```c++
#include <string>

#define FMT_HEADER_ONLY
#include <fmt/format.h>
#include <fmt/color.h>

using namespace std;
int main()
{
    std::string str = "test";
    std::string formatted_str = fmt::format(fmt::fg(fmt::color::red) | fmt::emphasis::bold, "{}", str);

    fmt::print("{:{}}|\n", str, 10);
    fmt::print("{:{}}|\n", formatted_str, 10);

    return 0;
}
```

Which outputs this:
```
test      |
test|
```
where "test" in the second line is colored in red and is bold.

For now I will work around that by manually padding strings, after [using a regex](https://stackoverflow.com/questions/14693701/how-can-i-remove-the-ansi-escape-sequences-from-a-string-in-python) to remove ANSI escape codes and know the real size of strings.

Thanks!

**Comment by vitaut** [comment]
Thanks for the suggestion but the semantics of width is pretty much fixed at this point. However, you can use the extension API to implement ANSI escape aware width computation via a wrapper type in your code.

**Comment by AdelKS** [comment]
Thank you for your prompt answer.

> the semantics of width is pretty much fixed at this point

Is there a technical documentation about it ? I couldn't find it unfortunately.

> However, you can use the extension API to implement ANSI escape aware width computation via a wrapper type in your code.

Noted

**Comment by vitaut** [comment]
The format string syntax including width is documented in https://fmt.dev/latest/index.html and http://eel.is/c++draft/format.
