### ISSUE TITLE
FMT LINKER ERROR 

### ISSUE THREAD

**Issue by Amayess** [fmtlib/fmt#2943]
Hi, am trying to reproduce this example https://github.com/isl-org/Open3D/blob/master/examples/cpp/RealSenseRecorder.cpp 

The example is using the Fmt library that i downloaded and linked with project but when i compile, this error happens :
![logging](https://user-images.githubusercontent.com/105653860/174611765-37bfdcf9-fb93-4290-98b9-fcb8cf7cab20.JPG)

Can anyone explain to me why, please ?

**Comment by vitaut** [comment]
The error suggests that you are not linking against the {fmt} library. Please see https://fmt.dev/latest/usage.html.
