### ISSUE TITLE
Confusing default double output

### ISSUE THREAD

**Issue by sashagsr** [fmtlib/fmt#2947]
Could you please clarify what are default rules of outputting double value?
The output of the following code snippet looks confusing:
````
const double d = 32567.17;
const double d1 = 123.4354;
const double d2 = 1234.123;
const double d3 = 32567.12345678901234;
const double d4 = 12.235;
const double d5 = 12.236;
const double d6 = 123456.123456;
const double d7 = 12345678.12345678;
spdlog::info("{} {} {} {} {} {} {} {}", d, d1, d2, d3, d4, d5, d6, d7);
````
Produces the following output:
````
[2022-06-22 15:03:48.777] [info] 32567.2 123.435 1234.12 32567.1 12.235 12.236 123456. 1.23457e+07
````
Some values are rounded, some seems to be just truncated, it is not clear when the scientific format is used.
Version is: SPDLOG_VERSION 1.4.2 with internal fmt
Thanks in advance.

**Comment by vitaut** [comment]
The default output in the current version of {fmt} is different (https://godbolt.org/z/Ev18cMd5E):

```
32567.17 123.4354 1234.123 32567.123456789013 12.235 12.236 123456.123456 12345678.12345678
```

It looks like the version of {fmt} included in spdlog 1.4.2 is old and doesn't have the shortest decimal representation with round-trip guarantee which is the current default.
