### ISSUE TITLE
warning: macro "__OPTIMIZE__" is not used [-Wunused-macros]

### ISSUE THREAD

**Issue by zethon** [fmtlib/fmt#2956]
I've hit #2532 which had no posted solution. The problem can be seen here: https://godbolt.org/z/n336cxob6

It does not seem to be a problem with gcc 11 and newer, but the problem can be reproduced with older versions of gcc and `-Wunused-macros`

If someone had a work-around that would be great.

**Comment by vitaut** [comment]
Please comment on the original report instead of opening duplicate issues.
