### ISSUE TITLE
When using User-defined Types formatter and ranges in 9.0.0, the compiler will output an error

### ISSUE THREAD

**Issue by orsmile** [fmtlib/fmt#2972]
8.1.1: https://godbolt.org/z/4M7zcEz39
trunk: https://godbolt.org/z/1Ma8hnjEf

The link above is a simple example
It compiles successfully in 8.1.1, but there is a compilation error in 9.0.0

**Comment by phprus** [comment]
The format function on the formatter needs to be const.

**Comment by phprus** [comment]
I think it's godbolt's bug.

Header only fmt works well: https://godbolt.org/z/Tboj5n1d1

**Comment by orsmile** [comment]
Thanks, it really works!
However, when I use clang to compile, I get the same error again.

**Comment by phprus** [comment]
```c++
#include <string_view>
```
and ``-std=c++17`` option:
https://godbolt.org/z/aM97GGc73

**Comment by orsmile** [comment]
After adding const to the formatter, I tested it in my own Linux environment, no matter header only or static link can be compiled normally.

Thanks for your help!
