### ISSUE TITLE
Compile time checks not always work

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#2973]
```C++
#include <fmt/format.h>

int main()
{
    fmt::print(FMT_STRING("{0:{1}}"), 1, '1');
}
```

### Expected
Compilation error

### Actual
The code compiles successfully and `fmt::v9::format_error("width is not integer")` it thrown at runtime.

https://godbolt.org/z/ch91v53Wa

**Comment by vitaut** [comment]
Same as #1715.
