### ISSUE TITLE
Individual argument's styling: special value to not change/touch a style

### ISSUE THREAD

**Issue by w3lld0ne** [fmtlib/fmt#2978]
It would be nice to have a possibility to use conditional styling of individual arguments. What is meant is to be able to use empty `fmt::styled()`, or `{}`, or `std::nullopt`, or any other special value and provide it as a placeholder when I don't need to change the style by some condition.

For example,

```
int my_value = 100;

fmt::print("my_value is {:d}, you should know it.", my_value == 100 ? fmt::styled(my_value, fg(fmt::color::terminal_color::green)) : fmt::styled_nochange(my_value));
```

I use `fmt::styled_nochange()` helper here because both left and right operands should have the same castable type, otherwise we could just write `my_value == 100 ? fmt::styled(my_value, fg(fmt::color::terminal_color::green)) : my_value`.

Currently if I want to style the individual argument conditionally I'm forced to provide a style replacement even for the case when I don't need to change it:

```
int my_value = 100;

fmt::print("my_value is {:d}, you should know it.", my_value == 100 ? fmt::styled(my_value, fg(fmt::color::terminal_color::green)) : fmt::styled(my_value, fg(fmt::color::terminal_color::white)));

// or...

fmt::print("my_value is {:d}, you should know it.", fmt::styled(my_value, my_value == 100 ? fg(fmt::color::terminal_color::green) : fg(fmt::color::terminal_color::white)));

// or...

fmt::print("my_value is {:d}, you should know it.", fmt::styled(my_value, fg(my_value == 100 ? fmt::color::terminal_color::green : fmt::color::terminal_color::white)));
```

The examples above 'work' but obviously depend on the current parameters of the console, it would only be a no-change when white fg color is already set.

**Comment by vitaut** [comment]
Thanks for the suggestion. You can already pass `{}` as the default style, e.g.

```c++
  fmt::print(
    "my_value is {:d}, you should know it.",
    my_value == 100 ?
      fmt::styled(my_value, fg(fmt::terminal_color::green)) :
      fmt::styled(my_value, {}));
```

https://godbolt.org/z/qMYGWaarb

So I don't think we need to introduce another API for this.

**Comment by W3LLD0NE** [comment]
You're right, this works fine. Probably I tested everything except that because for example `fmt::styled(my_value, my_value == 100 ? fg(fmt::terminal_color::green) : {});` leads to compilation error.

Can be closed indeed.
