### ISSUE TITLE
Question - how to use fmt::streamed with fmt::join?

### ISSUE THREAD

**Issue by iwubcode** [fmtlib/fmt#2980]
Imagine I have something like this:

```
#include <iostream>
#include <vector>

struct Example
{
  int a;
  float b;
};

std::ostream& operator<<( std::ostream& stream, const Example& e)
{
  stream << e.a << " & " << e.b;
  return stream;
}

// Somewhere else

#include <fmt/ostream.h>

void print_examples(const std::vector<Example>& examples)
{
  fmt::print("{}", fmt::join(examples, ","));
}
```

Apologies if I'm missing it but how can you use `fmt::streamed()` with `fmt::join()` ?

**Comment by vitaut** [comment]
You could probably use ranges to apply streamed to all elements but I'd recommend defining a proper formatter instead.

**Comment by iwubcode** [comment]
@vitaut - can you use the example above to show what you mean by "use ranges"?  Do you mean loop to a temporary buffer?  I guess I can't use `fmt::join` anymore?

The background is a situation where ostreams are sometimes client facing.  These interfaces can't easily change.

For now I can leverage `FMT_DEPRECATED_OSTREAM` but I was looking to leverage `fmt::streamed` where possible because you said the preprocessor flag was only temporary.

Could you introduce a `fmt::join_streamed`?

**Comment by mwinterb** [comment]
`FMT_DEPRECATED_OSTREAM` is temporary, but `fmt::ostream_formatter` is not if you want to reuse your existing `ostream` insertion operator. https://fmt.dev/dev/api.html#ostream-api. `fmt::streamed` is probably intended for light usages or cases where you do not own the type and so should not provide a formatter for it.

And "use ranges" would be something like this: https://gcc.godbolt.org/z/19j6s5PsM
