### ISSUE TITLE
Formatter cannot support char array

### ISSUE THREAD

**Issue by liwei-cpp** [fmtlib/fmt#2986]
For the following code:
```cpp
#include <iostream>
#include <fmt/format.h>

struct Str {};

namespace fmt
{
    template <>
    struct formatter<Str>
    {
        char formatString[4] = "{:}";
        auto constexpr parse(format_parse_context& ctx)
        {
            auto it = ctx.begin();
            while ((it != ctx.end()) && (*it != '}'))
            {
                ++it;
            }
            return it;
        }
        
        template <typename FormatContext>
        auto format(const Str& v, FormatContext& ctx) const
        {
            return format_to(ctx.out(), "{:}", 0);
            //return format_to(ctx.out(), formatString, 0);
        }
    };
}

int main()
{
    Str obj;
    std::cout << fmt::format("Hello {}\n", obj);
}
```

If the comment line is uncomment, then the compiling will fail. Is this expected? In fact even with the formatString defined inside the formatter, we can also create the constexpr formatter object. Inside the object the formatString is also constexpr. Then why we cannot use it as the second argument of the format_to?

Thanks!

**Comment by vitaut** [comment]
It is expected because the format string must be known at compile time. The fix is to make `formatString` constexpr or use the format string literal directly.
