### ISSUE TITLE
-Wstringop-overflow in GCC 12.1 at -O3 (not reproducible in GCC trunk)

### ISSUE THREAD

**Issue by hgkjshegfskef** [fmtlib/fmt#2989]
fmtlib: trunk
Repro: https://godbolt.org/z/7YM9oY4cj

Perhaps this is just to add to the collection of bogus `-Wstringop-overflow` warnings. Unless I'm using the library incorrectly. Seems to be fixed in GCC trunk (future version 13?). Note that the warning does not appear at -O2 and lower.

**Comment by vitaut** [comment]
This looks like a false positive which is fixed in the latest gcc so I don't think we should do anything about it. You can suppress the warning with `FMT_SYSTEM_HEADERS` or some other method.

**Comment by vitaut** [comment]
Worked around in https://github.com/fmtlib/fmt/commit/d9bc5f1320332db9a4bf7e103b0813b94e369304.
