### ISSUE TITLE
Use shared library Gtest (or prebuilt) to reduce filesize of tests

### ISSUE THREAD

**Issue by dimztimz** [fmtlib/fmt#2996]
The current setup bundles Gtest, builds it as static library and links all test to it, drastically increasing the size of each test executable. A minimal fix is to use Gtest as shared library. Additionally, on MinGW the linker is really slow and this fix will speedup things as it has less stuff to write into the executable files.

One can go to additional length and write logic that first tries to use a prebuilt library using `find_package()` in CMake and if that fails only then build your own.

The information that says using prebuilt Gtest is discouraged is outdated. Since [Ubuntu 20.04](https://packages.ubuntu.com/focal/libgtest-dev) and since [Debian Buster](https://packages.debian.org/buster/libgtest-dev) a proper prebuilt Google test is shipped. More information here on all [different ways to consume Gtest](http://numerical-stranger.blogspot.com/2020/07/using-googletest-from-ubuntu-packages.html).

**Comment by vitaut** [comment]
Thanks for the suggestion but the gtest library is pretty small (~600k on macOS) so I don't think it's worth complicating the build config. You can disable generation of test targets altogether with the `FMT_TEST` CMake variable.
