### ISSUE TITLE
Why Parse twice in format function

### ISSUE THREAD

**Issue by liwei-cpp** [fmtlib/fmt#2997]
For the current implementation, the parse is called twice in fmt::format, one is on compile time, used for some checking, one is on run-time, used for generate output. Are there any design concern that we cannot do the parse at compile time without doing the second parse at runtime? Thanks!

**Comment by vitaut** [comment]
We can do parsing at compile time only which is referred to as format string compilation in {fmt}: https://fmt.dev/latest/api.html#compile-api. The reason why it is an opt in is that

> Format string compilation can generate more binary code compared to the default API and is only recommended in places where formatting is a performance bottleneck.
