### ISSUE TITLE
c++20 compatibility

### ISSUE THREAD

**Issue by AndrewJD79** [fmtlib/fmt#2999]
Hi

Following code doesn't work in v9.0.0 and master when compiling with -std=c++20

```
#include <fmt/format.h>

int main() {

    const char* myformat = "{}";
    fmt::print(myformat, "value");
}
```

see on [godbold](https://godbolt.org/z/zWTbW658P)

**Comment by vitaut** [comment]
The format string must be known at compile time. Here is a fixed example:

```
#include <fmt/core.h>

int main() {
  fmt::print("{}", "value");
}
```
https://godbolt.org/z/ner683oqY

**Comment by AndrewJD79** [comment]
Are there any plans to provide API for legacy code (c++17 or less) which uses fmt in python style without requirement of compile time format string?
As I understand, compile time requirement is added for compatibilty with std::format but on the other hand such change significantly reduces versatility of the library and cause pain for everybody who  relay on old python-style behaviour.

**Comment by vitaut** [comment]
Runtime format strings are supported with `fmt::runtime`: https://fmt.dev/latest/api.html#_CPPv4N3fmt7runtimeE11string_view.
