### ISSUE TITLE
bit_cast `memcpy` warnings with `-Wall -Wextra`

### ISSUE THREAD

**Issue by fkallen** [fmtlib/fmt#3000]
format.h: In instantiation of ‘To fmt::v9::detail::bit_cast(const From&) [with To = fmt::v9::detail::uint128_fallback; From = long double; typename std::enable_if<(sizeof (To) == sizeof (From)), int>::type <anonymous> = 0]’:
...

format.h:290:12: warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘class fmt::v9::detail::uint128_fallback’ from an array of ‘const long double’ [-Wclass-memaccess]
 ` 290 |   std::memcpy(&to, &from, sizeof(to));`

**Comment by vitaut** [comment]
Could you provide a godbolt repro?

**Comment by fkallen** [comment]
The error does not appear on godbolt.

The reproducer is

```
#define FMT_HEADER_ONLY
#include <fmt/core.h>
```

When it is compiled with either 
`nvcc -std=c++14 -c -Xcompiler "-Wall" -Ifmt-master/include test1.cpp -o test1` 
or 
`g++ -std=c++14 -c -D__NVCC__  -Wall -I"fmt-master/include" test1.cpp -o test1` 
the warning occurs. 
There is no warning with `g++ -std=c++14 -c -Wall -I"fmt-master/include" test1.cpp -o test1`.

nvcc version is V11.5.119 , g++ version is 9.4.0

The warning disappears if in `format.h` line https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L290  is changed to `std::memcpy((void*)&to, &from, sizeof(to));` From the gcc documentation: 
>Explicitly casting the pointer to the class object to void * or to a type that can be safely accessed by the raw memory function suppresses the warning.

**Comment by vitaut** [comment]
This looks like a bug in gcc because it should check whether the type is trivially copyable, not trivial (same as bit_cast). But I suppressed the warning anyway in https://github.com/fmtlib/fmt/commit/e9ca7ea472a387639cef65a93037afcee26e4733. Thanks for reporting.

**Comment by SoapGentoo** [comment]
Likely due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104855#c5
