### ISSUE TITLE
Replace AppVeyor with Github actions

### ISSUE THREAD

**Issue by dimztimz** [fmtlib/fmt#3004]
AppVeyor is usually slow so it is good idea to replace it. Now it is kept because it provides Visual Studio 2015 and GitHub actions does not, it has VS2019.

But you can get the toolchain of VS2015 inside VS2019. VS2019 provides three toolchains:

- v140 (from VS2015)
- v141 (from VS2017)
- v142, the default.

According to the docs, all three are [already installed](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#workloads-components-and-extensions). I even noticed there Clang as toolchain inside VS.

You can use the CMake -T CLI switch or set the appropriate variable [CMAKE_GENERATOR_TOOLSET](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html) to select toolchain.

**Comment by vitaut** [comment]
That's a good idea. A PR would be welcome.
