### ISSUE TITLE
FMT_STRING("{:.{}f}") works in v80102 but not in v90000

### ISSUE THREAD

**Issue by SanderBouwhuis** [fmtlib/fmt#3006]
I have had this pattern for well over a year now and it always worked correctly. I updated to the latest master, and now I get errors:
```
...
wchar_t pwcValue[1024];
...
fmt::format_to_n(pwcValue, _countof(pwcValue)-1, FMT_STRING("{:.{}f}"), dValue, u8TotDecimals)
...

```
This is the error I get:
```
CDataCube.cpp(4653,97): error C3615: constexpr function 'fmt::v9::basic_format_parse_context<char,fmt::v9::detail::error_handler>::on_error' cannot result in a constant expression
Fmt\core.h(717,27): message : failure was caused by call of undefined function or one not declared 'constexpr' (compiling source file CDataCube.cpp)
Fmt\core.h(717,27): message : see usage of 'fmt::v9::detail::error_handler::on_error' (compiling source file CDataCube.cpp)
```

1. Why doesn't this work anymore?
2. Is there something I can change to make it working with the latest master?

**Comment by vitaut** [comment]
Please provide a godbolt repro.

**Comment by SanderBouwhuis** [comment]
I figured out the problem. If I change the FMT_STRING to wchar_t it does work:
Fails:
`FMT_STRING("{:.{}f}"), dValue, u8TotDecimals)`
Works:
`FMT_STRING(L"{:.{}f}"), dValue, u8TotDecimals)`

But, previously it worked. So, something must have changed. What is the reason you can't use char strings as input in combination with wchar_t output anymore since last month?

**Comment by vitaut** [comment]
In general mixing char and wchar_t strings is not recommended (and if possible disallowed). I was not able to repro the issue in https://godbolt.org/z/x6cGqKnsa though.

**Comment by SanderBouwhuis** [comment]
Ok, it doesn't matter. I changed my source code to not mix char with wchar_t anymore.

**Comment by vitaut** [comment]
Could be related to #3015.

**Comment by SanderBouwhuis** [comment]
@vitaut 
Not sure whether the commit related to https://github.com/fmtlib/fmt/issues/3015 fixed it, but I just checked and it works again.

Thanks for fixing this regression!
