### ISSUE TITLE
format string to json case occur exception

### ISSUE THREAD

**Issue by tocky0** [fmtlib/fmt#3013]
Use fmt lib to json data format, as flow,  
```
    std::string sf = R"({"type":{}, "id":"{}", "path":"{}"})";
    auto ss = fmt::format(sf, 1, 32, "abc");
    std::cout << ss << std::endl;
```
The json delim is `{` and `}`, this may some conflict with fmt. when run it, exception occur,
```
terminate called after throwing an instance of 'fmt::v8::format_error'
  what():  invalid format string
```
so how to resolve in json case?

**Comment by foonathan** [comment]
Use `{{` to print a literal `{` and `}}` to print a literal `}`.

**Comment by OnurKader** [comment]
You need to escape the curlies, `{{` and `}}`
`R"({{"type":{}, "id":"{}", "path":"{}"}})"`
[godbolt](https://godbolt.org/z/f9Tsf8Par)
[docs](https://fmt.dev/latest/syntax.html#format-string-syntax)
