### ISSUE TITLE
Compilation error when including complex.h and default g++ 11.2 standard

### ISSUE THREAD

**Issue by knjmooney** [fmtlib/fmt#3014]
The error can be worked around with -std=c++17

https://godbolt.org/z/1E847MnY3

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/5f774c0aed4af6494b412cd3883e0f09295bd79d. Thanks for reporting.

**Comment by knjmooney** [comment]
Thank you.

I believe there are other headers that have this issue, such as fmt/ranges.h. Would you like me to raise another issue/enumerate them?

**Comment by vitaut** [comment]
If there are more cases like this please post here and let's reopen the issue.

**Comment by knjmooney** [comment]
Sorry for the slow reply.

I repeated the original reproducer with all headers found in include/fmt. The only errors I see are with

* ranges.h
* std.h

I wasn't able to test with locale.h, that header didn't seem to exist on godbolt.

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/aec3bb5d0a0f01a8bdf97b6a68fc2458732a9b0d. Thanks.

**Comment by knjmooney** [comment]
Amazing, thanks for fixing!
