### ISSUE TITLE
Regression for size_t in width

### ISSUE THREAD

**Issue by gendalph** [fmtlib/fmt#3015]
8
https://godbolt.org/z/4Eq3a66hP

9
https://godbolt.org/z/78WE1d9zd

**Comment by phprus** [comment]
@vitaut 
And for ``short``/``unsigned short``...

This types is not defined in:

https://github.com/fmtlib/fmt/blob/756822ba39941e1e033f26e4c07547cc7058948c/include/fmt/core.h#L606-L619

``size_t`` may not be a typedef:
https://godbolt.org/z/rWTnzsGbG (gcc vs clang vs msvc).

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/7fb8d33f9d073222ed867726f8d3121312c690c5. Thanks for reporting.
