### ISSUE TITLE
Bugs with FMT_UNICODE, is_utf8(), GCC on Windows (MinGW) and -fexec-charset

### ISSUE THREAD

**Issue by dimztimz** [fmtlib/fmt#3016]
The dispatch mechanism with `is_utf8()` should be simplified an it should be made more robust. I found an edge case where it is not working. The steps to reproduce are bellow.

This is the source file, I put it inside the directory `test`:
```cpp
// test/unicode.cpp
#include <fmt/core.h>

int main() {
  // For GCC this is always 1 even if we use -fexec-charset. It is 0 only for
  // MSVC.
  static_assert((FMT_UNICODE) == 1, "");

  // because the above is 1, this returns true
  static_assert(fmt::detail::is_utf8(), "");

  static_assert(sizeof(fmt::detail::micro) == 2, "");  // not UTF-8

  fmt::print("кошка {}\n", 123);
}
```

I modify test/CMakeLists.txt
```cmake
add_fmt_executable(unicode unicode.cpp)
target_link_libraries(unicode fmt)
target_compile_options(unicode PRIVATE -fexec-charset=cp1251) # Windows 1251, Cyrillic
```

If you run the resulting executable under CMD then exception is thrown (`_isatty()` return true). If you run under the MSYS terminal (MinTTY) then garbage comes out (`_isatty` returns false).

Now I will point the relevant lines in core.h that can be improved:

https://github.com/fmtlib/fmt/blob/6567df7f2400835299ba3e52566497391d6b8dff/include/fmt/core.h#L259-L261
https://github.com/fmtlib/fmt/blob/6567df7f2400835299ba3e52566497391d6b8dff/include/fmt/core.h#L412-L419
https://github.com/fmtlib/fmt/blob/6567df7f2400835299ba3e52566497391d6b8dff/include/fmt/core.h#L3011-L3014
https://github.com/fmtlib/fmt/blob/6567df7f2400835299ba3e52566497391d6b8dff/include/fmt/core.h#L3285-L3290

I was also trying to hit that empty function `vprint_mojibrake` on Linux but noticed I can not, unless I manually modify the define `FMT_UNICODE`. I am not sure if it is supposed to be configurable by the user. Anyway, here is reproduction on godbolt: https://godbolt.org/z/43fqY4E8T

**Comment by dimztimz** [comment]
A minimal solution is to do the following:

1. Remove FMT_UNICODE
2. Rename `is_utf8()` to `is_not_windows_or_is_utf8()` and it should do what it says.

Is that acceptable?

**Comment by vitaut** [comment]
Thanks for the suggestion but I don't think we need to support legacy encodings by other mechanisms than `FMT_UNICODE`. `detail::is_utf8` is an internal symbol so there is no need to rename it either.

**Comment by dimztimz** [comment]
This is not the answer I wanted. The bug is still there.

Even more minimal fix is to replace

https://github.com/fmtlib/fmt/blob/6567df7f2400835299ba3e52566497391d6b8dff/include/fmt/core.h#L259-L261

With

```
 #ifndef FMT_UNICODE 
 #  ifdef _WIN32
 #    define FMT_UNICODE 0
 #  else
 #    define FMT_UNICODE 1
 #  endif
 #endif 
```

> I don't think we need to support legacy encodings 

You already support legacy encodings. Otherwise is_utf8() is not needed at all.

**Comment by vitaut** [comment]
> You already support legacy encodings. 

Yes, you are replying to only part of what I wrote which doesn't make sense in isolation =). The full sentence says:

> I don't think we need to support legacy encodings by other mechanisms than FMT_UNICODE.
