### ISSUE TITLE
Document bug?

### ISSUE THREAD

**Issue by fonqL** [fmtlib/fmt#3017]
I've noticed an example in the document.
https://fmt.dev/latest/api.html#_CPPv4I0EN3fmt6styledEN6detail10styled_argI14remove_cvref_tI1TEEERK1T10text_style
```
fmt::print("Elapsed time: {s:.2f} seconds",
           fmt::styled(1.23, fmt::fg(fmt::color::green) |
                             fmt::bg(fmt::color::blue)));
```
When running it I got a runtime error. I think it should be like :
```
fmt::print("Elapsed time: {s:.2f} seconds",
	           "s"_a = fmt::styled(1.23, fmt::fg(fmt::color::green) |
	                                     fmt::bg(fmt::color::blue)));
```

**Comment by vitaut** [comment]
Thanks for reporting but this has been fixed already: https://fmt.dev/dev/api.html.
