### ISSUE TITLE
already defined in xxx

### ISSUE THREAD

**Issue by alicera** [fmtlib/fmt#3018]
I try to upgrade the  8.1.1  ->  9.0.0 
```
" failed (exit code 1169) with the following output:
fmt.lib(fmt.dll) : error LNK2005: "public: __cdecl fmt::v9::format_error::format_error(char const *)" (??0format_error@v9@fmt@@QEAA@PEBD@Z) already defined in decoder.cpp.obj
fmt.lib(fmt.dll) : error LNK2005: "public: __cdecl fmt::v9::format_error::format_error(class fmt::v9::format_error const &)" (??0format_error@v9@fmt@@QEAA@AEBV012@@Z) already defined in decoder.cpp.obj
fmt.lib(fmt.dll) : error LNK2005: "public: virtual __cdecl fmt::v9::format_error::~format_error(void)" (??1format_error@v9@fmt@@UEAA@XZ) already defined in decoder.cpp.obj
test.exe : fatal error LNK1169: one or more multiply defined symbols found
ninja: build stopped: subcommand failed.
```

same problem  
https://github.com/fmtlib/fmt/issues/2011

**Comment by vitaut** [comment]
The issue doesn't reproduce on the CI shared build. You'll need to provide more repro details and/or check your build configs.

**Comment by vitaut** [comment]
The only change to `format_error` between the two versions is replacing `FMT_NOEXCEPT` with `noexcept` so it's likely an issue with your build config. You could use {fmt} tests as an example of working shared library config or switch to a static library. Closing for now as not reproducible but feel free to reopen with more details.
