### ISSUE TITLE
Extending the scientific notation format to control number of digits in the exponent

### ISSUE THREAD

**Issue by mpettit2253** [fmtlib/fmt#3022]
I need to generate scientific notation numbers with only 1 digit in the exponent.  The types being formatted are just doubles.  Is it possible in fmt or std::format to extend a format string such as "{:+12.6E1}"?  The format I'm after is ±9.999999E±9.  Currently I have to intercept the output and strip the extra 0 in the 2 digit exponent in the client code after the call to format.

**Comment by vitaut** [comment]
There is no built-in format specifier for that but you can write your one formatter (via a wrapper type) that does that.

**Comment by mpettit2253** [comment]
Thanks.  To make sure I understand that, there isn't a way to extend the format mini-language as applied to numerics generally (short of proposing a working contribution to the base library - not a bad challenge). Instead, in my program I have to cast the numeric value into a wrapper type so that my own parse/format override gets called to strip that zero.

**Comment by vitaut** [comment]
Right.
