### ISSUE TITLE
--as-needed from fmt link command causes pthread to misbehave

### ISSUE THREAD

**Issue by jheydebrand** [fmtlib/fmt#3023]
Commit e498ffbb3d6587c6b4e3d95359a35fc5da9c40eb added a `-Wl,--as-needed` linker option.
Current code for that linker option: https://github.com/fmtlib/fmt/blob/df56fdf883e3bb2832b3cff1ccc623ae0d66376d/CMakeLists.txt#L269

When linking fmt in a CMake project, this creates a link command line fragment similar to `[other things] libfmtd.so -Wl,--as-needed [more things]`
The behaviour of the final program can be influenced by the location of libfmt in the link command line since all other libraries that appear after fmt and its associated `--as-needed` will be affected by that option.

Specifically, I observed pthread's mutex methods to "do nothing" (i.e. perform no actual locking) when the `-pthread` option appears after fmt while they worked properly if pthread appeared before fmt on the linker command line.
After I removed the `--as-needed` from fmt's CMakeLists.txt, the mutex worked correctly in both cases again.

**Comment by vitaut** [comment]
I think we should remove this linker option completely. A PR would be welcome.

**Comment by phprus** [comment]
@vitaut PR: #3024
