### ISSUE TITLE
Question: what are the workaround to prevent fmtlib failure when C++ exceptions are disabled?

### ISSUE THREAD

**Issue by Dragnalith** [fmtlib/fmt#3031]
Hello,

When formatting error occur, fmtlib raise the error by throwing an exception. In an environment where exceptions are disabled it leads to a crash. 

In order to prevent the crash and handle the error without using exceptions,  given a formatting string and a set of arguments I would like to programmatically be able to know if the format will succeed or not.

I did not find such public API in the documentation. Is there any workaround to achieve what I wish?

**Comment by vitaut** [comment]
There is no such API but you could use compile-time format string checks: https://fmt.dev/latest/api.html#compile-time-format-string-checks.
