### ISSUE TITLE
static_assert failure message should include name of unformattable type

### ISSUE THREAD

**Issue by Pr0methean** [fmtlib/fmt#3034]
I recently got a build error from Fmt 9.0.0 in a library I was updating from 6.x, where the error was:
```
22:22:27 /local/p4clients/pkgbuild-1Mg1D/workspace/<proprietary>/Sender.cpp:142:17:   required from here
22:22:27 /opt/brazil-pkg-cache/packages/Fmt/Fmt-9.x.12.0/AL2_x86_64/DEV.STD.PTHREAD/build/include/fmt/core.h:1732:3: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
22:22:27    static_assert(
22:22:27    ^~~~~~~~~~~~~ 
```
Sender.cpp:142 is a logging call with multiple arguments, and a gap in our internal `includePath` tooling means I can't tell which argument is the unformattable one. Why not just output the type name when the assertion fails?

**Comment by vitaut** [comment]
I don't think we can print the type in the assertion itself but it should appear in the context, e.g.

> error: use of deleted function 'fmt::v9::detail::fallback_formatter<T, Char, Enable>::fallback_formatter() [with T = foo; Char = char; Enable = void]'

Here `foo` is the unformattable type.
