### ISSUE TITLE
lexical or preprocessor issue - redefinition of module

### ISSUE THREAD

**Issue by wg-d** [fmtlib/fmt#3035]
I have been looking for a solution to fix the below error.
`Lexical or Preprocessor Issue Group - Redefinition of module 'fmt'`

![Screenshot_4](https://user-images.githubusercontent.com/86578241/184504381-4f4b40c0-8762-4b68-b8cc-44b871a9a32e.png)

FYI, I attached the screenshot to show you the errors. I have gone through all solutions on stackoverflow and github but none of them gives a clear and relevant solution. As you can see, there are 12 errors in two categories. One is Lexical or Preprocessor Issue Group and another is Parse Issue. I have focused mainly on searching for the solution to first category issues but they all Lexical or Preprocessor Issue - ***.h file not found errors. So no helpful one found yet. I am building it in Xcode 13.4.1 after migrating from Xcode 12.

Thank you!

**Comment by vitaut** [comment]
{fmt} doesn't provide a modulemap. You should check where it is defined and report there.
