### ISSUE TITLE
valgrind makes {fmt} misbehave

### ISSUE THREAD

**Issue by LarsGullik** [fmtlib/fmt#3039]
https://godbolt.org/z/fqr35z7z3
(not reproducible on complier explorer since no valgrind there)

This is with 9.0.0, I have this peculiar problem.

```
#define FMT_HEADER_ONLY
#include "fmt/format.h"
#include <cassert>
int main()
{
        fmt::print("{}\n", FMT_VERSION);

        auto s = fmt::format("{}", 4.2l);
        fmt::print("{}\n", s);
        assert(s == "4.2");
}
```

Compiling directly in the git clone with
g++ -I include/ test.cpp

Running ./a.out:
```
$ ./a.out 
90000
4.2
```

Nothing strange there.

However running it with valgrind:
```
$ valgrind ./a.out 
90000
4.2000000000000001776
a.out: test.cpp:10: int main(): Assertion `s == "4.2"' failed.
```

I see the same on several machines, gcc 11.[2,3].

Do anyone have any idea what is happening?
Btw. version 8.1.1 does not have this problem, 9.0.0 and master does.

**Comment by LarsGullik** [comment]
It is a `long double` problem, `float` and `double` works just fine.

**Comment by vitaut** [comment]
Looks like valgrind doesn't support `long double` arithmetic:

> There is no support for 80 bit arithmetic. Internally, Valgrind represents all such "long double" numbers in 64 bits, and so there may be some differences in results.

**Comment by vitaut** [comment]
I think it's reasonable to assume that FP arithmetic works so I don't think we should be doing any heroics to workaround valgrind limitations. That said if there is an easy workaround, a PR would be welcome.
