### ISSUE TITLE
wchar_t format using locale does produce garbage when expecting a sign

### ISSUE THREAD

**Issue by mtillmann0** [fmtlib/fmt#3041]
Using locale dependent wide-char format on a signed integer will output garbage.

See https://godbolt.org/z/jozcMY4qd

As far as I can see the problem occurs in line
https://github.com/fmtlib/fmt/blob/9ff0f3a7d6a79194cc251407d34821ae59849937/include/fmt/format.h#L1998
where the cast to a 4-byte wchar_t will produce incorrect results when the value was previously set to
`prefix = 0x01000000 | '-';` in line 2028.
I cannot discern why the additional bit is set.

**Comment by vitaut** [comment]
Good catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/1f95c3438151a6f5371d03850a7fc8f019cc525e.
