### ISSUE TITLE
Conversions to and from fmt::basic_format_string

### ISSUE THREAD

**Issue by matt77hias** [fmtlib/fmt#3042]
I wonder whether it is possible to add support for
* a non-`consteval` `explicit` constructor in `fmt::basic_format_string` taking a null-terminated character string (~ `std::basic_string_view`);
* a non-`consteval` `explicit` constructor in `fmt::basic_format_string` taking a contiguous, sized, character range (~ `std::basic_string_view`);
* contiguous +  sized + borrowed range support for `fmt::basic_format_string` (~ `std::basic_string_view`).

The former two allow interoperability with custom string types without having to expose `fmt::basic_runtime`. Though, I am not sure how to declare the same set of constructors as `consteval` and non-`consteval` (`constexpr` in declaration + `if consteval` in definition?). The latter allows interoperability with `std::basic_string_view` or custom implementations their of without having to expose `fmt::basic_string_view`.

```c++
#include <fmt/core.h>
#include <type_traits>

struct CustomString
{
    [[nodiscard]]
    auto c_str() const noexcept -> const char* { return ""; };
};

template< typename C, typename... ArgTs >
using BasicFormatString = fmt::basic_format_string< C, std::type_identity_t< ArgTs >... >;
template< typename... ArgTs >
using FormatString = BasicFormatString< char, ArgTs... >;

auto main() -> int
{
  CustomString format;

  //FormatString<> f1{ format.c_str() };      // works without consteval support
  FormatString<> f2{ fmt::basic_runtime< char >{ .str = format.c_str() } };
  FormatString<> f3{ fmt::basic_runtime< char >{ format.c_str() } };

  //std::string_view v1{ f3 };                // fmt::basic_format_string is not a contiguous, sized char range
  std::string_view v1{ fmt::string_view(f3) };// std::string_view explicit range constructor

  return 0;
}
```
https://godbolt.org/z/ajq51976Y

**Comment by vitaut** [comment]
Thanks for the suggestions. The first two options are definitely not viable because they would enable bypassing compile-time checks. It is not super clear whether the third option is `consteval` or not but from the example it looks like no so the same applies to it.

Custom runtime string support could be done by overloading the `runtime` function. There are no conversions from runtime strings intentionally.

**Comment by matt77hias** [comment]
But what about:
`consteval` -> `constexpr`
`if constexpr` -> `if consteval` or `if (std::is_constant_evaluated)`

```c++
template <typename S, FMT_ENABLE_IF(std::is_convertible<const S&, basic_string_view<Char>>::value)>
FMT_CONSTEVAL FMT_INLINE basic_format_string(const S& s)
    : str_(s)
{
    static_assert(detail::count< (std::is_base_of<detail::view, remove_reference_t<Args>>::value && std::is_reference<Args>::value)...>() == 0, "passing views as lvalues is disallowed");
    #ifdef FMT_HAS_CONSTEVAL
    if constexpr (detail::count_named_args<Args...>() == detail::count_statically_named_args<Args...>())
    {
        using checker = detail::format_string_checker<Char, detail::error_handler, remove_cvref_t<Args>...>;
        detail::parse_format_string<true>(str_, checker(s, {}));
    }
    #else
    detail::check_format_string<Args...>(s);
    #endif
  }
```

=>

```c++
template <typename S, FMT_ENABLE_IF(std::is_convertible<const S&, basic_string_view<Char>>::value)>
FMT_CONSTEXPR FMT_INLINE basic_format_string(const S& s)
    : str_(s)
{
    static_assert(detail::count< (std::is_base_of<detail::view, remove_reference_t<Args>>::value && std::is_reference<Args>::value)...>() == 0, "passing views as lvalues is disallowed");
    if consteval (detail::count_named_args<Args...>() == detail::count_statically_named_args<Args...>())
    {
        using checker = detail::format_string_checker<Char, detail::error_handler, remove_cvref_t<Args>...>;
        detail::parse_format_string<true>(str_, checker(s, {}));
    }
    else
    {
        detail::check_format_string<Args...>(s);
    }
  }
```

The `consteval` on the constructor itself restricts the usage to a compile-time path.
Whereas `constexpr` allows both a compile and runtime path.

**Comment by vitaut** [comment]
The whole purpose of `basic_format_string` is to restricts the usage to compile-time. `constexpr` won't work there.

**Comment by matt77hias** [comment]
> The whole purpose of `basic_format_string` is to restricts the usage to compile-time.

If that would be the intended design, then of course I cannot argue with that. But it does not seem to be the case due to the presence of a 2nd `public` constructor:
```c++
basic_format_string(basic_runtime<Char> r) : str_(r.str) {}
```
implying that `basic_format_string` is supposed to handle format strings known at both compile time and runtime.

> `constexpr` won't work there.

`consteval` guarantees evaluation at compile time. `constexpr` does not, but in case it is evaluated at compile time, there still is the `if consteval`/`if (std::is_constant_evaluated)` to distinguish the compile time path from the runtime path, and add the additional compile time checks. My point is that the latter allows you to keep the compile time path as is, while at the same time it adds a runtime path without the need for a `basic_runtime` type to disambiguate it. So it will not break existing code while it adds functionality.

_The only grey zone is whether the `constexpr` constructor will be evaluated at compile time if possible, which is a compiler dependent decision._
```c++
constexpr auto f = basic_format_string< char >("test"); // compile time
const auto f = basic_format_string< char >("test"); // ?
auto f = basic_format_string< char >("test"); // ?
```

**Comment by vitaut** [comment]
I think you are missing how compile time checks work, please check https://www.zverovich.net/2021/06/16/safe-formatting-api.html for some details. Replacing `consteval` with `constexpr` is absolutely not possible and will break existing use cases.
