### ISSUE TITLE
Is there a way to handle string replacement with the current FMT library?

### ISSUE THREAD

**Issue by RebootTheSys** [fmtlib/fmt#3045]
Sorry if this is wrong place to post. I am currently using the FMT library for formatting text and it is great. I have some scenarios where I would like to just replace arguments {argIds} using the FMT style tokens in an existing string. Is there a way to utilize the library without having to create a new string each time? Like a find and replace using on_replacement_field. It is not quite clear to me if this is possible since the output iterator or string seems to be appended. I seem to always have to pass a empty string, format string, and variables/args. Basically, modify the format string and return it rather than creating a return string and providing a format too.

**Comment by vitaut** [comment]
> Is there a way to utilize the library without having to create a new string each time?

No and it would be hard to do in practice at least because the replacement text can be larger than the placeholder so you would have to parse and store parsed results somewhere. This would likely negate any perf benefits of formatting in place.
