### ISSUE TITLE
basic_ostream_formatter and fmt::streamed are locale-dependent

### ISSUE THREAD

**Issue by manxorist** [fmtlib/fmt#3046]
`fmt::basic_ostream_formatter` and `fmt::streamed` leak the currently active C++ locale to `operator<<` because the locale that gets imbued in a `basic_ostream` by default is a default constructed locale (which is a copy of the active global locale). See <https://github.com/fmtlib/fmt/blob/36c23bd5fd92ad846cdbf8b7ecd6a87b7d3efae4/include/fmt/ostream.h#L127>.
A correct `basic_ostream` `operator<<` is required to look at the stream locale in order to decide how it should format things.
This conflicts with documentation which claims that {fmt} is locale-independent by default unless an explicit locale is provided and/or the `L` format specifier is used.

In order to always achieve locale-independence, {fmt} should thus `imbue(std::locale::classic())` if no explicit locale is provided.

Test case: <https://godbolt.org/z/cso8d3Tos>:
```
#include <iostream>
#include <locale>

#include <fmt/core.h>
#include <fmt/ostream.h>

struct inspect_locale {
    friend std::ostream & operator<<(std::ostream & os, const inspect_locale &) {
        os << os.getloc().name();
        return os;
    }
};

template <>
struct fmt::formatter<inspect_locale>
    : fmt::ostream_formatter
{
};

int main() {
    {
        std::cout << fmt::format("{}", inspect_locale{}) << std::endl;
    }
    {
        std::locale::global(std::locale("en_US.UTF-8"));
        std::cout << fmt::format("{}", inspect_locale{}) << std::endl;
    }
    return 0;
}
```

**Comment by vitaut** [comment]
Thanks for the suggestion but I think if the user opts into ostream formatting then it should use the ostream locale. Locale-independence applies to native formatting.
