### ISSUE TITLE
{fmt} and/or ostream_formatter/fmt::streamed are very confused about text encoding

### ISSUE THREAD

**Issue by manxorist** [fmtlib/fmt#3047]
In the default recommended use of {fmt}, which means using `char` as the character type, `ostream_formatter` is confused about text encoding. It copies characters written to the `ostream` verbatim into the output buffer. However, that mixes up text encodings. {fmt} documents itself as using "`char`/UTF-8" (see <https://fmt.dev/latest/api.html>), however `operator<<` needs to look at the locale that is imbued in the `ostream` and then use the locale's narrow character encoding. In the default case (when the process did not set a locale (like e.g. via `std::locale::global(std::locale(""))`), this will be the `std::locale::classic()` or `"C"` locale, which in the general case does not use UTF-8 encoding. If the process configured the system-configured locale (or any other locale), it can be basically anything (and in particular is a locale that does not use UTF-8 in almost all Windows applications).

Test case: <https://godbolt.org/z/qq53ncv6W>:
```
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

#include <fmt/format.h>
#include <fmt/ostream.h>

struct lol_type {
    friend std::ostream & operator<<(std::ostream & os, const lol_type &) {
        const std::codecvt<wchar_t, char, std::mbstate_t> & conv = std::use_facet<std::codecvt<wchar_t, char, std::mbstate_t>>(os.getloc());
        const std::wstring in = L"löl";
        std::vector<char> tmp((conv.max_length() * in.length()) + 1, '\0');
        std::string out;
        {
            const wchar_t * from_next = nullptr;
            char * to_next = nullptr;
            std::mbstate_t state{};
            from_next = in.data();
            to_next = tmp.data();
            // skip codecvt error handling, not relevant to demonstrate the problem
            conv.out(state, in.data(), in.data() + in.length(), from_next, tmp.data(), tmp.data() + tmp.size(), to_next);
            out = std::string(tmp.data(), to_next);
        }
        /* os << out; */ /* // with en_US.ISO-8859-1 locale, this would be */ os << "l\xf6l";
        return os;
    }
};

template <>
struct fmt::formatter<lol_type>
    : fmt::ostream_formatter
{
};

int main() {
    // compiler explorer does not provide that locale
    std::string s = fmt::format( /* std::locale("en_US.ISO-8859-1"), */ "{} {}", lol_type{}, "löl");
    for (const auto c : s) {
        // output is not in any valid encoding
        std::cout << std::hex << std::setfill('0') << std::setw(2) << static_cast<int>(static_cast<unsigned char>(c)) << " ";
    }
    std::cout << std::endl;
    return 0;
}
```

Possible ways forward:
 1. imbue a locale which uses the intended (as documented) UTF-8 encoding. However, I doubt that is possible to do portably in practise as the locale names are platform-dependent and {fmt} does not know which are available. There might not even be any UTF-8 locale available at all on a given system. Providing only a {fmt}-tailored `codecvt` facet might also work.
 2. imbue the `std::locale::classic()` locale (when no explicit locale was given) and transcode the output to UTF-8 (which might imply a roundtrip through the wide locale encoding). This has the disadvantage of limiting the available character set to what the `"C"` locale supports.
 3. Leave the locale alone and transcode from whatever is the current active locale's narrow encoding. This however also has the disadvantage of limiting the available character set to what is representable in the locale's narrow character set (which might be less than full Unicode).
 4. imbue the `std::locale::classic()` locale (when no explicit locale was given) and statically check for `operator<<` availability for `basic_ostream` using the Unicode character types `char8_t`/`char16_t`/`char32_t` or the wide locale character set via `wchar_t`, use those to format the value, and transcode the output. This requires defining some character type preference precedence.
 5. `fmt/chrono.h` appears to already try to handle encoding, so maybe at the very least the same treatment should be brought to `ostream_formatter`/`fmt::streamed`. I have not reviewed whether what `chrono.h` does is sane/correct.
 6. Remove the claim that {fmt} is "`char`/UTF-8" from the documentation, and keep all Mojibake support.
 7. Remove `fmt::ostream_formatter`/`fmt::streamed` and pretend *{fmt} had always been at war with ostream*.

I strongly prefer options 4 or 6.

Now, this is not at all easy to fix, and IMHO shows the very fundamental design flaw in {fmt} of using a kitchen-sink character type as the recommended default and trying to enforce its encoding by documentation only.

This encoding confusion bug would highly likely have been caught during development if {fmt} had choosen to use an encoding type safe character type (like `char8_t` or `char32_t`) as its default/recommended character type (test case: <https://godbolt.org/z/nxac58oqn>:
```
#include <ostream>
#include <string>

#include <fmt/core.h>
#include <fmt/ostream.h>
#include <fmt/xchar.h>

struct compiletime_encoding_fuckup_detection_demonstrator {
    friend std::ostream & operator<<(std::ostream & os, const compiletime_encoding_fuckup_detection_demonstrator &) {
        os << "l\xf6l";
        return os;
    }
    friend std::wostream & operator<<(std::wostream & os, const compiletime_encoding_fuckup_detection_demonstrator &) {
        os << L"l\U000000f6l";
        return os;
    }
};

template <typename Char>
struct fmt::formatter<compiletime_encoding_fuckup_detection_demonstrator, Char>
    : fmt::basic_ostream_formatter<Char>
{
};

int main() {
    std::string yolostring = fmt::format("{}", compiletime_encoding_fuckup_detection_demonstrator{});
    std::wstring widestring = fmt::format(L"{}", compiletime_encoding_fuckup_detection_demonstrator{});
    //std::u32string utf32string = fmt::format(U"{}", compiletime_encoding_fuckup_detection_demonstrator{});
    //std::u16string utf16string = fmt::format(u"{}", compiletime_encoding_fuckup_detection_demonstrator{});
    //std::u8string utf8string = fmt::format(u8"{}", compiletime_encoding_fuckup_detection_demonstrator{});
    return 0;
}
```
).

**Comment by manxorist** [comment]
So, you willingly continue to ship broken code?

**Comment by vitaut** [comment]
@manxorist please stop spamming the repo with nonsensical claims.
