### ISSUE TITLE
Infinite recursion with bogus format-string

### ISSUE THREAD

**Issue by steffenb7333** [fmtlib/fmt#3055]
This causes an infinite template instantiation loop in gcc and clang without ever getting any useful hint about what is wrong with the format-string. Removing FMT_COMPILE yields an usable error message fragment `... ::on_error(((const char*)"unknown format specifier"))`. 
```
#include <fmt/compile.h>
int main()
{
    [[maybe_unused]] auto recurse = fmt::format(FMT_COMPILE("{:02x"), 0);
    return 0;
}
```

https://godbolt.org/z/KGjhv3jTv

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/391f922acc7b2da4001ad241a18b8b570d7d1d5f. Thanks for reporting!
