### ISSUE TITLE
Formatting of char8_t strings

### ISSUE THREAD

**Issue by Fedr** [fmtlib/fmt#3060]
In `fmt 7.1.3` one could format c++20 UTF-8 char8_t strings as follows:
```
fmt::format( u8"..." );
```
but starting from `fmt 8` it is not an option any more. Online demo: https://gcc.godbolt.org/z/dzGGosbT4

Is it disabled intentionally or it can be still done somehow differently?

**Comment by vitaut** [comment]
This is still supported ([but not recommended](https://www.think-cell.com/en/career/devblog/char8_t-was-a-bad-idea)), you just need to include `fmt/xchar.h`: https://gcc.godbolt.org/z/oxbMae743.
