### ISSUE TITLE
Color output doesn't work in Apple's Terminal.app?

### ISSUE THREAD

**Issue by rnikander** [fmtlib/fmt#3067]
I just tried the documentation example for color output:

```
fmt::print(fmt::emphasis::bold | fg(fmt::color::red),
           "Elapsed time: {0:.2f} seconds", 1.23);
```

It works in my IDE console (in AppCode), but in the Terminal.app, it's not bold or colored. I see color there from other programs, for example, from `brew`.

**Comment by vitaut** [comment]
Some terminals don't support full RGB colors. You could use `fmt::terminal_color` there instead.

**Comment by davidchisnall** [comment]
This appears to be a fairly recent regression.  The Apple terminal *does* support RGB colours and I was seeing coloured output on it from libfmt before an upgrade.

**Comment by vitaut** [comment]
I see the same behavior with {fmt} 6.0 which was released more than 3 years ago. RGB colors work in iTerm2 but not in Terminal but terminal colors work in both.

**Comment by yanggeorge** [comment]
> Some terminals don't support full RGB colors. You could use `fmt::terminal_color` there instead.

Very nice. Thanks. This problem has been bothering me for a few days.
