### ISSUE TITLE
Printable enum class no longer formattable

### ISSUE THREAD

**Issue by NewbieOrange** [fmtlib/fmt#3069]
```cpp
enum class Error {
  Success = 0,
  Unknown,
};

std::string to_string(const Error error) { return ""; }

std::ostream &operator<<(std::ostream &os, const Error &obj) { return os; }
```

For such a printable enum class, fmt::format works in 6.x, however in 9.0.0 (probably 8.x too) it no longer compiles.

Is this expected behaviour or regression?

https://godbolt.org/z/YoooMW5YW

**Comment by vitaut** [comment]
This is expected. You can make an enum formattable via `format_as` or a `formatter` specialization: https://fmt.dev/latest/api.html#formatting-user-defined-types.
