### ISSUE TITLE
Clang-msvc compiled fmt.lib interprets *NaN as inf.

### ISSUE THREAD

**Issue by denchat** [fmtlib/fmt#3070]
I compile `fmt.lib` using `clang-cl` against `vs2022` on Windows 11.
```
-DCMAKE_CXX_COMPILER="C:/Program Files/LLVM/bin/clang-cl.exe"
-DCMAKE_CXX_FLAGS="-fuse-ld=lld 
-fms-compatibility-version=19.33.31629 
--target=x86_64-pc-windows-msvc19.33.31629
```

<br>

The `format-test.exe` fails at `float_test`.

```
error: Value of: isnan(Float(limits::quiet_NaN()))
  Actual: false
Expected: true
```

<br>

I try run this.

```
    fmt::print("{:+},{:+}\n"
               , std::numeric_limits<double>::quiet_NaN() 
               , std::numeric_limits<double>::signaling_NaN() );

    std::cout << std::numeric_limits<double>::quiet_NaN() << ','
              << std::numeric_limits<double>::signaling_NaN() << '\n';
```

<br>
Which prints

```
+inf,+inf
nan,nan(snan)
```

**Comment by vitaut** [comment]
Do you (directly or indirectly) use `-ffast-math`?

**Comment by denchat** [comment]
Thank you. My MSVC `/fp:fast` setting causes this. 

Could we just have CMAKE override or at least detect this setting in CMAKE_CXX_FLAGS?

**Comment by denchat** [comment]
It's turns out MSVC `/fp:fast` doesn't interpret QNAN into INF.
It's clang itself.
By placing `-fhonor-nans` *_after_* `-ffast-math` on clang seems to fix this.

[[LIVE](https://compiler-explorer.com/z/MYWhE1n7K)]

Unfortunately `clang-cl.exe` v14.0.6 doesn't recognise `-fhonor-nans`. So only `clang-cl.exe` option is removing `/fp:fast` when compiling `fmt`.

**Comment by mwinterb** [comment]
> Unfortunately `clang-cl.exe` v14.0.6 doesn't recognise `-fhonor-nans`. So only `clang-cl.exe` option is removing `/fp:fast` when compiling `fmt`.

You may be able to add it with [/clang](https://clang.llvm.org/docs/UsersManual.html#the-clang-option).

**Comment by denchat** [comment]
>  You may be able to add it with [/clang](https://clang.llvm.org/docs/UsersManual.html#the-clang-option).

@mwinterb  No luck unfortunately.

```
clang-cl: warning: unknown argument ignored in clang-cl: '-fhonor-nans' [-Wunknown-argument]
clang-cl: error: no such file ordirectory: '/clang'
```
<br>
If I  change to `-Xclang -fhonor-nans`, the warning turns into an error.

```
error: unknown argument: '-fhonor-nans'
```
<br>
I wonder whether this can be considered as regression on clang side?

**Comment by denchat** [comment]
So this seems more like the nature of the compilation flag, perhaps it's out of scope of `fmt`. 

You may close this. Thank you.
