### ISSUE TITLE
Error compile with DPCPP LLVM 16

### ISSUE THREAD

**Issue by andreagen0r** [fmtlib/fmt#3078]
Kubuntu: 22.04
Compiler: DPCPP LLVM 16  
https://github.com/intel/llvm

``` shell
fmt/include/fmt/format.h:2477:11: error: cannot capture a bit-field by reference
      if (sign) *it++ = detail::sign<Char>(sign);

fmt/include/fmt/include/fmt/format.h:2418:8: note: 'sign' declared here
  auto sign = fspecs.sign;

fmt/include/fmt/core.h:2785:10: note: bit-field is declared here
  sign_t sign : 8;

fmt/include/fmt/os.h:20:
/home/andreagenor/code/external_libraries/fmt/include/fmt/format.h:2491:11: error: cannot capture a bit-field by reference
      if (sign) *it++ = detail::sign<Char>(sign);
```
I changed the lambda passing by value and now works fine

![diff](https://snipboard.io/8r7YW1.jpg)

**Comment by vitaut** [comment]
What {fmt} version do you use? Does the issue repro on the current master?

**Comment by andreagen0r** [comment]
This is in the current master f187274d3637403e1391deb69233b34b5e345d37

**Comment by andreagen0r** [comment]
This is in the current master f187274d3637403e1391deb69233b34b5e345d37

**Comment by vitaut** [comment]
Looks like a compiler bug because `sign` in
```
auto sign = fspecs.sign;
```
is not a bit field. Please report to the compiler vendor.

A PR with a workaround would be welcome too provided that it's not too intrusive.
