### ISSUE TITLE
fmt::printf("%.*f\n", 15, pi) makes linking fails unless linking against static lib or FMT_HEADER_ONLY defined.

### ISSUE THREAD

**Issue by denchat** [fmtlib/fmt#3079]
Without `-DFMT_HEADER_ONLY` , this statement

```
fmt::printf("%.*f\n", 15, pi);
```

makes the linking fails in both `clang` v14 and `gcc` v12
[[LIVE](https://compiler-explorer.com/z/MEn4MPq7a)]
<br>
In `clang-cl` v14, `lld-link` fails as below.
```
lld-link: error: void __cdecl fmt::v9::vprint(class fmt::v9::basic_string_view<char>, class fmt::v9::basic_format_args<class fmt::v9::basic_format_context<class fmt::v9::appender, char>>) was replaced
clang-cl: error: linker command failed with exit code 1 (use -v to see invocation)
```

In `clang-cl` v14, removing `-DFMT_SHARED` solves this.
<br>
It looks like dynamic precision `fmt::printf` causes problems on dynamic lib linking.

**Comment by denchat** [comment]
Now the current master [192859c](https://github.com/fmtlib/fmt/tree/192859c2b5dda3a015a7b1bf023f0c2475f0350c) doesn't have this issue. However the issue still shows on compiler explorer as link above.

You may close this. 

Thank you.

**Comment by vitaut** [comment]
Closing per email comment:

> Now the current master [192859c](https://github.com/fmtlib/fmt/tree/192859c2b5dda3a015a7b1bf023f0c2475f0350c) doesn't have this issue. However the issue still shows on compiler explorer as link above.
> You may close this.
> Thank you.

**Comment by denchat** [comment]
I'm sorry that I didn't clearify the deleted comment. I've mistaken that with **_static_** linking.

The issue is still standing.
