### ISSUE TITLE
Upgrade concern with "Disabled automatic std::ostream insertion operator"

### ISSUE THREAD

**Issue by maliberty** [fmtlib/fmt#3081]
I have an [existing program](https://github.com/The-OpenROAD-Project/OpenROAD) using spdlog & fmt.  The upgrade from 8.1.1 runs into issues with the change:
```
Disabled automatic std::ostream insertion operator (operator<<) discovery when fmt/ostream.h is included to prevent ODR violations. 
```

We have many classes with operator<< and it seems every one now needs an ostream_formatter to work when upgraded (or every use needs streamed which is even more places).  Is this the only methodology or is there a better one if we are not concerned with ODR violations.  This is a lot of churn to solve a problem we don't have.

[FMT_DEPRECATED_OSTREAM is to be removed and so isn't a solution]

Thanks

**Comment by vitaut** [comment]
`ostream_formatter` and `streamed` are the two general migration mechanisms but there is also `format_as` for enums: https://fmt.dev/latest/api.html#formatting-user-defined-types. You might also be able to define your own generic `formatter` specialization if you don't care about ODR violations.

**Comment by maliberty** [comment]
Fwiw I have gone from a very happy fmt to user to a very unhappy one over this single issue.  I consider this should be opt-in for people who have a specific ODR problem.  I don't see how I'll ever have an ODR issue in a program I control without any dependencies that use fmt.   I feel this is a common use model.

**Comment by maliberty** [comment]
I have not found any way to make a generic formatter that doesn't generate ambiguities with fmt.

**Comment by vitaut** [comment]
Why can't you provide `formatter` specializations? It's just one line per type.

**Comment by maliberty** [comment]
That could easily be several hundred such specializations for no particular purpose.  Further every class now needs to include fmt if it provides operator<<  even if it doesn't use fmt itself lest we have to put them at every site of usage.

**Comment by maliberty** [comment]
Further I have to teach every developer/contributor to do this one line.  I have to monitor it in code reviews.  I have it cluttering every header.  All in service of a non-problem.

**Comment by maliberty** [comment]
This is also an API breaking change resulting in

https://github.com/The-OpenROAD-Project/OpenROAD/issues/2220
https://github.com/The-OpenROAD-Project/OpenROAD/issues/2173
https://github.com/The-OpenROAD-Project/OpenROAD/pull/2097

**Comment by vitaut** [comment]
We'll look into adding an ADL-based opt in mechanism similar to what we have for enums and doesn't require including {fmt} headers. In the meantime you can define `FMT_DEPRECATED_OSTREAM` to continue using ostreams. It was specifically introduced for this purpose.

**Comment by maliberty** [comment]
Thanks I appreciate it very much

**Comment by maliberty** [comment]
Does it make sense to reopen this issue or open a new one for the ADL-based opt in?

**Comment by vitaut** [comment]
I opened a new issue: #3088.

**Comment by chiphogg** [comment]
> I consider this should be opt-in for people who have a specific ODR problem.

@maliberty, I read this line, and I was curious: what makes you think that people who have ODR violations of this type would know that they do?

If one translation unit calls `format` without including the explicit formatter definition, and another calls `format` _with_ the explicit definition, then my understanding is that the whole program is IFNDR (ill formed, no diagnostic required).  That means that it's _silently_ incorrect.  Wouldn't that suggest that many users could have this problem without knowing that they do?

Apologies in advance if I've misunderstood anything. 🙂

**Comment by maliberty** [comment]
Users who don't have this problem, which is common, should not be penalized.  There is a tradeoff.

**Comment by chiphogg** [comment]
I'll grant that it's common for users to not _know_ that they have this problem.  My question is: if the problem can be hard to detect, then why should we assume that "not knowing they have this problem" implies "not having this problem"?

**Comment by maliberty** [comment]
I can't speak for others but I can't imagine having this problem in well structured code.  It strikes me as an obscure corner rather than a hidden but common problem.  I've outlined all my concerns above about the tradeoffs that I find more of an issue.  You may disagree...
