### ISSUE TITLE
The godbolt examples referenced in issue #1931 formatting std::thread::id do not work

### ISSUE THREAD

**Issue by misuo** [fmtlib/fmt#3085]
When trying the examples in issue #1931 formatting `std::thread::id` they do not work - gets "error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"

Here screenshot from `fmt::format` example ...

![image](https://user-images.githubusercontent.com/21021375/188746311-17612936-d08e-4034-ba52-38c4fe03b71d.png)

**Comment by mwinterb** [comment]
You need to include the fmt/std.h header now instead of fmt/ostream.h.

**Comment by vitaut** [comment]
Please see https://fmt.dev/latest/api.html#std-api.

**Comment by misuo** [comment]
Thx. Changing to including `fmt/std.h` works.
