### ISSUE TITLE
"missing '}' in format string" regression in fmt v7

### ISSUE THREAD

**Issue by oxidase** [fmtlib/fmt#3086]
The following example on 1feb430faaac6bd8094e996861d6025f9903d34e
```
#include <fmt/format.h>
#include <iostream>
int main()
{
    std::cout << "FMT_VERSION " << FMT_VERSION << std::endl;
    std::cout << fmt::format("<{:}>", uint8_t{42}) << std::endl;
}
```
shows
```
FMT_VERSION 90101
terminate called after throwing an instance of 'fmt::v9::format_error'
  what():  missing '}' in format string
```
but not a problem with fmt v6
```
FMT_VERSION 60102
<42>
```

**Comment by vitaut** [comment]
Great catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/ecffca672656d6e4a2d39314237289f5740e8562. As a workaround you can remove `:` from the format string (it is redundant anyway).

**Comment by oxidase** [comment]
@vitaut thanks for quick fix!
