### ISSUE TITLE
Consider adding an ADL-based opt in for ostream

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#3088]
Per discussion in #3081 it might be good to have something similar to `format_as` for ostream before removing `FMT_DEPRECATED_OSTREAM`.

**Comment by maliberty** [comment]
Is there any plan to do this?

**Comment by vitaut** [comment]
Yes, it is still planned.

**Comment by vitaut** [comment]
This works now:

```c++
auto format_as(foo f) { return fmt::streamed(f); }
```

**Comment by TD22057** [comment]
We have this problem as well in a project with tons (500+) classes that used to be formatted with '{}' and operator<<.  Just so I'm clear, this still requires that every single one of those classes be modified to define format_as() for them right?  I'm assuming that defining a template for format_as somewhere won't work - meaning that fmt wouldn't cause the template to be instantiated automatically.

**Comment by vitaut** [comment]
`format_as` is just a normal function so you can make it a template, e.g.

```c++
#include <fmt/ostream.h>

struct foo {};

std::ostream& operator<<(std::ostream& os, foo) {
  return os << "foo";
}

template <
  typename T,
  std::enable_if_t<std::is_same_v<T, foo>, int> = 0>
auto format_as(T f) { return fmt::streamed(f); }

int main() {
  fmt::print("{}", foo());
}
```

https://godbolt.org/z/fnP5sEf7v

This example is a bit silly because it effectively constrains `T` to `foo` but you can put any constraint there.

**Comment by maliberty** [comment]
https://github.com/fmtlib/fmt/issues/3088 is a solution that they proposed but I haven't had a chance to try it.  Perhaps you could take a look?
