### ISSUE TITLE
How to round and format a double with argument?

### ISSUE THREAD

**Issue by zliucd** [fmtlib/fmt#3089]
Hi, 

I have a function to round a double to certain digits, my code reports runtime error.  

```
// n is the number of digits to round, e.g.,  3.1415926 => 3.14 if n =2
string round_double(double v, size_t n)
{
    string s;
    s = fmt::format("{:.{}f}", n, v);   // runtime error
 
   return s;
}
```

How to round  and format  a double with argument? Thanks.

**Comment by vitaut** [comment]
The argument order is incorrect since the first argument is the value and the second is the precision in your example:

```c++
s = fmt::format("{:.{}f}", v, n);
//               ^ arg 0  
//                  ^ arg 1
```

You could also use explicit argument indices.
