### ISSUE TITLE
Formatting using std::numpunct

### ISSUE THREAD

**Issue by asmaloney** [fmtlib/fmt#3094]
I've read through all the issues here around formatting numbers and I still haven't been able to get it to work.

I have an existing class `formatNumbers` which inherits `std::numpunct<char>`, implements `do_thousands_sep` & `do_grouping`, and lets me do this:

```cpp
ioStream << formatNumbers::on << total << formatNumbers::off << std::endl;
```
`formatNumbers::on` imbues the stream like so:

```cpp
ioStream.imbue( std::locale( ioStream.getloc(), new formatNumbers ) );
```

When I try to use `fmt::format`, I'm not getting the results I expect:

```cpp
ioStream << formatNumbers::on;
ioStream << fmt::format( "{:L}\n", total );
ioStream << formatNumbers::off;
```

It looks like [there was a fmt::format](https://github.com/fmtlib/fmt/issues/1162#issuecomment-492683449) which explicitly took a locale as an argument as outlined in [the standard](https://en.cppreference.com/w/cpp/utility/format/format), but I can't find it anywhere and the docs [imply it's no longer implemented](https://fmt.dev/latest/api.html#locale) since it isn't listed.

Any idea why this doesn't work or what I need to do to fix it?

**Note:** I am using `fmt::format` as a replacement for `std::format` until `std::format` is supported properly across more compilers. So I want to restrict use to just the C++20 standard.

_Aside:_ shouldn't `fmt::format` implement these since they are part of the standard?

```cpp
template< class... Args >
std::string format( const std::locale& loc,
                    std::format_string<Args...> fmt, Args&&... args );
template< class... Args >
std::wstring format( const std::locale& loc,
                     std::wformat_string<Args...> fmt, Args&&... args );
```

Thank you!

**Comment by vitaut** [comment]
An overload of `fmt::format` that takes a locale is defined here: https://github.com/fmtlib/fmt/blob/76705fc2eeaa5a28fcb80221906f363be4ed86e3/include/fmt/format.h#L4249

Locale type is a template parameter to avoid pulling expensive locale and iostreams headers.

**Comment by asmaloney** [comment]
Thanks Victor.

Why doesn't my code (using imbue) work as-is?

(It would be useful to have info about the overload in the docs - with an example.)

**Comment by vitaut** [comment]
> Why doesn't my code (using imbue) work as-is?

Not sure which code you are referring to. Please post a complete example on gobolot.

**Comment by asmaloney** [comment]
> Not sure which code you are referring to. 

The code in my question? 😆 

> Please post a complete example on godbolt.

Here it is with a few different attempts: https://godbolt.org/z/ssG5aT1e3

Thanks Victor.

**Comment by asmaloney** [comment]
Ah - I think I see why the second attempt doesn't work. `fmt::format` doesn't know about `std::cout`.

**Comment by vitaut** [comment]
> Ah - I think I see why the second attempt doesn't work. fmt::format doesn't know about std::cout.

Yes. You should do something like:
```
fmt::format(loc, "{:L}\n", 123456789);
```

**Comment by asmaloney** [comment]
As I pointed out in the comment, that doesn't compile.

```
<source>:45:18: error: no matching function for call to 'format'
    std::cout << fmt::format( loc, "{:L}", 123456789 );
                 ^~~~~~~~~~~
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h:3218:31: note: candidate function [with T = <const char (&)[5], int>] not viable: no known conversion from 'std::locale' to 'format_string<const char (&)[5], int>' (aka 'basic_format_string<char, const char (&)[5], int>') for 1st argument
FMT_NODISCARD FMT_INLINE auto format(format_string<T...> fmt, T&&... args)
                              ^
1 error generated.
ASM generation compiler returned: 1
<source>:45:18: error: no matching function for call to 'format'
    std::cout << fmt::format( loc, "{:L}", 123456789 );
                 ^~~~~~~~~~~
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h:3218:31: note: candidate function [with T = <const char (&)[5], int>] not viable: no known conversion from 'std::locale' to 'format_string<const char (&)[5], int>' (aka 'basic_format_string<char, const char (&)[5], int>') for 1st argument
FMT_NODISCARD FMT_INLINE auto format(format_string<T...> fmt, T&&... args)
                              ^
1 error generated.
Execution build compiler returned: 1
```

**Comment by vitaut** [comment]
You should include `fmt/format.h` per docs:

> fmt/format.h defines the full format API providing additional formatting functions and locale support.

https://fmt.dev/latest/api.html#format-api

**Comment by vitaut** [comment]
> Edit: Also - why wouldn't fmt::print work? It's using std::cout, right?

It is not using cout.

**Comment by asmaloney** [comment]
Ah - I was looking right above that in the **Locale** section.

I think adding an example of this in the docs would be useful.

Thanks for your help Victor!

**Comment by vitaut** [comment]
Updated the docs to include locale overloads in https://fmt.dev/dev/api.html#locale.
