### ISSUE TITLE
Removal of sphinx-bootstrap-theme repository breaks cloning of 1.x

### ISSUE THREAD

**Issue by speth** [fmtlib/fmt#310]
The removal of the `sphinx-bootstrap-theme` repository causes repositories which include this library as a submodule using any of the 1.x tags to fail when checking out submodules.

**Comment by vitaut** [comment]
Thanks for the bug report. Unfortunately, re-creating the repo doesn't work because the organization has been renamed, but you can either use non-recursive clone or update to version 2.0 which doesn't use git modules. Version 2.0 is mostly compatible with 1.x and fixes lots of issues.

**Comment by speth** [comment]
Ah, too bad that the organization name change makes this unfixable. I tried updating to 2.1, but had other issues there.

**Comment by vitaut** [comment]
Sorry for that. Let me know if I can help to resolve any issues with 2.x. Upgrading to 2.0 might be easier because it doesn't deprecate top-level headers.

**Comment by vitaut** [comment]
If you like I can make a patch release 1.1.1 fixing the issue with submodules.

**Comment by vitaut** [comment]
[Version 3.0.0](https://github.com/fmtlib/fmt/releases/tag/3.0.0) has been released. As discussed in #311, I recommend migrating to it.
