### ISSUE TITLE
Is there a method to calculate or estimate length of formatted string?

### ISSUE THREAD

**Issue by alecazam** [fmtlib/fmt#3101]
We currently use vsprintf, calling it the first time to get the length of the formatted string, resizing to that, and then calling it again to append the data.   This ability to get or at least estimate length appears to be missing in fmt.  This would be useful for appending to a string or string buffer, albeit at the cost of two formatting calls.

Also, since vsprintf is vararg based, there are very little dependencies in the header of say a logging system.   All argument processing is done in the .cpp file.  The format.h header also declares all the formatting code inline.   If there was a way to bury this in a .cpp, and reduce the code injected into every file then that would speed our adoption.

**Comment by vitaut** [comment]
You can get output size with `formatted_size`: https://fmt.dev/latest/api.html#_CPPv4IDpEN3fmt14formatted_sizeE6size_t13format_stringIDp1TEDpRR1T.

For reduced dependencies use `fmt/core.h`: https://fmt.dev/latest/api.html#core-api.
