### ISSUE TITLE
Long double errors: Clang, libc++, CUDA

### ISSUE THREAD

**Issue by j8asic** [fmtlib/fmt#3106]
Seems like `libc++` implementations of device functions do not support `long double` (i.e. CUDA doesnt have long double), so I am getting errors in `visit_format_arg`
The treatment for me was to use long doubles as regular double here:
https://github.com/fmtlib/fmt/blob/a48e3355a682b7e76d672c4dbd64aad2aad2ec6e/include/fmt/core.h#L1662

**Comment by vitaut** [comment]
{fmt} requires basic C++ support including `long double`. You might want to report an issue to NVIDIA asking them to at least make a sensible fallback.

**Comment by j8asic** [comment]
@vitaut so the `libc++` guys say they are right to disable `long double` math functions on the device https://godbolt.org/z/9Th19nWqP. So this bug I rewrite as: “fmt tries to call device math functions for long double, instead of appropriate host functions”

**Comment by vitaut** [comment]
No idea what this means but a PR with a workaround for CUDA will be welcome provided that it's not too intrusive.
