### ISSUE TITLE
msvc 17.3.4 c++20 consteval error with master and tag 9.1.0

### ISSUE THREAD

**Issue by ridilculous** [fmtlib/fmt#3107]
With msvc 17.3.4 i'm getting compilation errors with 9.1.0 and master (for `char` and `wchar_t`) but not with 9.0.0:

```
error C7595: 'fmt::v9::basic_format_string<char,std::string &>::basic_format_string': call to immediate function is not a constant expression
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xstring(2272,35): message : failure was caused by a read of a variable outside its lifetime
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xstring(2272,35): message : see usage of 'f'
error C7595: 'fmt::v9::basic_format_string<wchar_t,std::wstring &>::basic_format_string': call to immediate function is not a constant expression
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xstring(2272,35): message : failure was caused by a read of a variable outside its lifetime
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xstring(2272,35): message : see usage of 'f'
```

[godbolt string test](https://godbolt.org/z/jEcTczvee)

[godbolt wstring test](https://godbolt.org/z/v6W899vnW)

This is maybe related to #2455

**Comment by vitaut** [comment]
Format strings must be known at compile time by default, please see the docs: https://fmt.dev/latest/api.html#core-api.

**Comment by ridilculous** [comment]
Oh, thanks! I wasn't aware of [runtime format strings](https://fmt.dev/latest/api.html#_CPPv4N3fmt7runtimeE11string_view).

Is there a implicit ctor which makes the wstring version work in contrast to the string version? ([example](https://godbolt.org/z/4ahh8b53a))

**Comment by vitaut** [comment]
Compile-time checks for wide strings were only enabled recently. I guess the version on godbolt doesn't have them yet.
