### ISSUE TITLE
Compile Time Checks in Argument Lists Example do not work

### ISSUE THREAD

**Issue by H-M-H** [fmtlib/fmt#3108]
The code found here: https://fmt.dev/latest/api.html#argument-lists does not work as documented, there are no compile time checks, the following code compiles fine and produces a runtime error: https://godbolt.org/z/8oT34bhP1

My guess is that this is an error introduced with the switch from `make_args_checked` to `make_format_args`. The linked example code in the docs still assumes `make_args_checked` is present and thus fails to compile at the moment.

**Comment by vitaut** [comment]
Good catch, thanks. Updated an example in https://github.com/fmtlib/fmt/commit/3272a7a3ce3ea5e1f32327f8c70a9573ea8ec406. Godbolt: https://godbolt.org/z/6G3hG6roP.
