### ISSUE TITLE
hex outpuf 0xDEADBEEF not possible with format code

### ISSUE THREAD

**Issue by SGleissner-Leica** [fmtlib/fmt#3116]
Problem:
when using hex output, it is currently not possible mixing capital hex letters with 0x just by using a format code.

Example:
https://godbolt.org/z/PxrY4sq36

    fmt::format("{:#08x}", 3735928559)  =>  0xdeadbeef
    fmt::format("{:#08X}", 3735928559)  =>  0XDEADBEEF
    fmt::format("0x{:08X}", 3735928559)  =>  0xDEADBEEF

However, the last hex syntax variant is commonly used and better readable.

Possible solution:
instead of x/X as 'type', the usage of h/H might always use a small 0x

(the issue won't happen for binary values, as there are of course no letters used for the numeric value)

**Comment by vitaut** [comment]
The last line in your example does exactly that. Alternatively you can write a wrapper type with the desired formatting.

**Comment by wkingnet** [comment]
#1849 I suggest considering this request, 0xABCD is intuitive and beautiful style, 0xabcd and 0XABCD are too stupid
