### ISSUE TITLE
C++ 17 support?

### ISSUE THREAD

**Issue by SuperFola** [fmtlib/fmt#3126]
Hello, I have been searching for the C++ versions supported, but as far as I can tell the requirements are only 11 and above, and maybe 20 for some features (modules?).

However when I upgraded from 7.1.3 to 9.1.0 and compiled with various compilers (G++ 8-11, Clang 9-11, MSVC 17-19), with C++17 as the standard, I get a bunch of compile errors related to C++20 support, which I thought was optional.

Logs: https://github.com/ArkScript-lang/Ark/actions/runs/3177404001/jobs/5177801992

Am I doing something wrong, or should I just upgrade everything to C++20?

**Comment by vitaut** [comment]
C++17 is supported, see e.g. a recent build: https://github.com/fmtlib/fmt/actions/runs/3166780158/jobs/5156747791. Please provide a self-contained repro that doesn't involve other libraries.

**Comment by SuperFola** [comment]
Woops, that's right! I mistakenly compiled all .cc files, it is indeed working as intended.
