### ISSUE TITLE
const wchar[xxx] to std::format_string<T>

### ISSUE THREAD

**Issue by Teles1** [fmtlib/fmt#3127]
Hello, even after including <xchar.h> I'm getting a compiler error saying that it cant convert const wchar[xx] to std::format_string<>

https://godbolt.org/z/e4Tnd7eWf

**Comment by mwinterb** [comment]
You need to use `wformat_string`, and add other w-prefixes.
https://godbolt.org/z/jKosPjfe3

**Comment by Teles1** [comment]
Thank you
