### ISSUE TITLE
`std::quoted` is broken since 9.0.0

### ISSUE THREAD

**Issue by bebuch** [fmtlib/fmt#3131]
```cpp
#include <fmt/core.h>
#include <fmt/ostream.h>

#include <iomanip>

int main() {
    fmt::print("{}", std::quoted(""));
}
```

- https://godbolt.org/z/KsTb19reK

That compiled with 8.1.1, but not with 9.0.0, 9.1.0 and trunk.

**Comment by vitaut** [comment]
Including `fmt/ostream.h` no longer magically changes formatting behavior and an explicit opt in is required instead. Please see the docs: https://fmt.dev/latest/api.html#ostream-api. For quoting/escaping you can use the `?` specifier instead of `std::quote`.

**Comment by bebuch** [comment]
Thanks a lot!

**Comment by TheClonerx** [comment]
> For quoting/escaping you can use the ? specifier instead of `std::quote`.

This is not in the documentation! Is this intended?

**Comment by vitaut** [comment]
Not intended, a PR to add it to the docs would be welcome.
