### ISSUE TITLE
16 - unicode-test (Failed)

### ISSUE THREAD

**Issue by foryoung365** [fmtlib/fmt#3138]
log from LastTest.log:
==================

16/20 Testing: unicode-test
16/20 Test: unicode-test
Command: "I:/fmt-master/vsbuild/bin/Debug/unicode-test.exe"
Directory: I:/fmt-master/vsbuild/test
"unicode-test" start time: Oct 13 15:12 ?D1ú±ê×?ê±??
Output:
----------------------------------------------------------
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from unicode_test
[ RUN      ] unicode_test.is_utf8
[       OK ] unicode_test.is_utf8 (0 ms)
[ RUN      ] unicode_test.legacy_locale
I:\fmt-master\test\unicode-test.cc(47): error: Value of: (std::vector<std::string>{"袛蟹械薪褜 褌褘写薪褟: 锌薪", "袛蟹械薪褜 褌褘写薪褟: 袩邪薪"})
Expected: contains at least one element that is equal to "\xD0\x94\xD0\xB7\xD0\xB5\xD0\xBD\xD1\x8C \xD1\x82\xD1\x8B\xD0\xB4\xD0\xBD\xD1\x8F: \xC2\xA7\xD0\xB1\xC2\xA7\xD0\xAF"
    As Text: "袛蟹械薪褜 褌褘写薪褟: 搂斜搂携"
  Actual: { "\xD0\x94\xD0\xB7\xD0\xB5\xD0\xBD\xD1\x8C \xD1\x82\xD1\x8B\xD0\xB4\xD0\xBD\xD1\x8F: \xD0\xBF\xD0\xBD"
    As Text: "袛蟹械薪褜 褌褘写薪褟: 锌薪", "\xD0\x94\xD0\xB7\xD0\xB5\xD0\xBD\xD1\x8C \xD1\x82\xD1\x8B\xD0\xB4\xD0\xBD\xD1\x8F: \xD0\x9F\xD0\xB0\xD0\xBD"
    As Text: "袛蟹械薪褜 褌褘写薪褟: 袩邪薪" }
[  FAILED  ] unicode_test.legacy_locale (45 ms)
[----------] 2 tests from unicode_test (45 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (46 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] unicode_test.legacy_locale

 1 FAILED TEST
<end of output>
Test time =   0.10 sec

===========

**reproduce step**:
1.build fmt with cmake(Compiler: visual studio 2022 17.3.4  Community) , platform: x64
2.build solution
3.build RUN_TESTS
[LastTest.log](https://github.com/fmtlib/fmt/files/9771939/LastTest.log)

**Comment by vitaut** [comment]
Unfortunately the issue doesn't reproduce in a similar configuration: https://github.com/fmtlib/fmt/actions/runs/3253594907/jobs/5340998551. You need to provide more repro details and/or investigate the failure on your system e.g. by checking why transcoding in https://github.com/fmtlib/fmt/blob/51d3685efe0eb8a44656f9fd5dac6a04f4e58259/include/fmt/chrono.h#L352 doesn't work there.

**Comment by vitaut** [comment]
Closing for now but feel free to reopen with more repro details.
