### ISSUE TITLE
Clang-CL warning : declaration of 'Duration' shadows template parameter [-Wmicrosoft-template-shadow]

### ISSUE THREAD

**Issue by Epixu** [fmtlib/fmt#3140]
I get `fmt\chrono.h(2093,46): warning : declaration of 'Duration' shadows template parameter [-Wmicrosoft-template-shadow]` when building with latest clang-cl - other compilers don't seem to bother (tested on GNU 11.1.0 and MSVC2022).
As of [this commit](https://github.com/fmtlib/fmt/commit/9254cfa6f0cc9d6fc9eec0c16181bfbba08e75ec).

**Comment by vitaut** [comment]
Fixed in #3142.
