### ISSUE TITLE
pass formattable string as argument 

### ISSUE THREAD

**Issue by andriy-byte** [fmtlib/fmt#3141]
how to pass format to fmt::format not like in place created string

this is for example, well, logically it doesn't work
```
        return fmt::format("{" + correctDateTimeFormat.getFormat() + "}", std::chrono::system_clock::now());

```

**Comment by vitaut** [comment]
You need to wrap the string in `fmt::runtime` for this to work:

```c++
return fmt::format(fmt::runtime("{" + correctDateTimeFormat.getFormat() + "}"), std::chrono::system_clock::now());
```

Please see the docs: https://fmt.dev/latest/api.html#core-api.
