### ISSUE TITLE
linker complains that the symbol for `std::locale` is missing

### ISSUE THREAD

**Issue by maritalweeping** [fmtlib/fmt#3146]
I'm building `fmt v8.1.1` as follows via `cmake`. My compiler is Clang 14.0.6 and I'm building on a `debian:bullseye` (linux) docker image with `-libc++` and `CMAKE_CXX_STANDARD=20`.

```
FetchContent_Declare(
        fmt
        GIT_REPOSITORY https://github.com/fmtlib/fmt
        GIT_TAG 8.1.1
)
FetchContent_MakeAvailable(fmt)
target_compile_definitions(fmt PUBLIC FMT_CONSTEVAL=)
include_directories(${fmt_SOURCE_DIR}/include)
message(STATUS "fmt_SOURCE_DIR: ${fmt_SOURCE_DIR}")
```

where note that `FMT_CONSTEVAL` is set to **nothing** in order to avoid getting related errors.

However, I still run into the following error where the linker complains that the symbol for `std::locale` is missing:

```
/usr/bin/ld: _deps/fmt-build/libfmt.a(format.cc.o): undefined reference to symbol '_ZNSt6localeD1Ev@@GLIBCXX_3.4'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

How do I resolve this issue? Note that the above approach works perfectly fine while compiling on my M1 Mac mini runing `Apple-Clang 14.0`.

**Comment by vitaut** [comment]
There is no error when building with the default (`libstdc++`):

```
git clone --branch 8.1.1 https://github.com/fmtlib/fmt
cd fmt
cmake -DCMAKE_CXX_STANDARD=20
make
```
so I guess the problem is related to `libc++`. In any case `std::locale` is a part of the standard library so it doesn't look related to {fmt}. You might need to link with `libstdc++` where the symbol in question is defined.
