### ISSUE TITLE
vs2022 use /utf-8, if there are Chinese characters will be std::runtime_error

### ISSUE THREAD

**Issue by rise-worlds** [fmtlib/fmt#3152]
![image](https://user-images.githubusercontent.com/464270/197317328-95cc2ce5-6aac-4307-8f23-d63c3e438b25.png)

- c++
`fmt::print("中文字符：{}", 12345);`

- CMakeLists.txt
```
if (WIN32)
    add_definitions(-DWIN32_LEAN_AND_MEAN)
    add_definitions(-D_WIN32_WINNT=0x0601)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
    add_compile_options(/utf-8 /bigobj /EHsc)
endif()
```

**Comment by vitaut** [comment]
I was not able to repro the issue on the latest {fmt}. Compiling

```c++
#include <fmt/core.h>

int main() {
  fmt::print("中文字符：{}", 12345);
}
```
with
```
cl -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0601 -D_CRT_SECURE_NO_WARNINGS /utf-8 /bigobj /EHsc /I fmt/include unicode.cc fmt/src/format.cc
```
and running the generated binary doesn't produce an exception.

Most likely your source file is not in UTF-8 which causes a transcoding error or you are using an older version of {fmt}.
