### ISSUE TITLE
Support va_list in fmt::sprintf, or fmt::vsprintf

### ISSUE THREAD

**Issue by xis19** [fmtlib/fmt#3153]
`fmt::sprintf` supports printing old-style `printf` format string together with `...`. However, in my particular situation, we are using `va_list` and the interface comes from a 3rd-party library. Is it possible we support `fmt::vsprintf` for convenience use?

**Comment by xis19** [comment]
I have noticed that in the source code:

 * there is a `vsprintf` but the args is not `va_list`, but some custom text; also it has no documentation.
 * The only `va_list` reference is in `format-inl.h` which only used in Microsoft compiler.

**Comment by vitaut** [comment]
`va_list` won't be supported because it is inherently unsafe. You'll need to use C stdio functions for that.

**Comment by JasonDictos** [comment]
When handling the fuse logger callback, it gives you the format specifier and a va_list. We had to patch our own function together:
```
std::string string_sprintf(const char* format, ...)
{

  std::array<char, 1024> buffer; // For many cases 1024 is plenty.
  const size_t n = buffer.size();

  std::va_list arglist;
  va_start(arglist, format);
  int returned_value = vsnprintf(buffer.data(), n, format, arglist);
  va_end(arglist);

  if(returned_value < 0)
  {
    buffer[ 0 ] = '\0';
  }

  if(returned_value < static_cast<int>(n))
  {
    // Only when vsnprintf returned value is non-negative and less than n, the
    // string has been completely written.
    return buffer.data();
  }

  // n was too small.  Do it again with the size vsnprintf told us to use.
  const int dynamic_size = returned_value + 1; // "less than n" by a '\0'

  std::vector<char> dynamic_buffer;
  dynamic_buffer.reserve(dynamic_size);

  va_start(arglist, format);
  returned_value = std::vsnprintf(dynamic_buffer.data(), dynamic_size, format, arglist);
  va_end( arglist );

  return returned_value < 0 ? "" : dynamic_buffer.data();
}

```

Came here looking for a solution, would be handy!

**Comment by vitaut** [comment]
`va_list` is unsafe and inefficient. See https://fmt.dev/11.0/api/#type-erasure for a better alternative.
