### ISSUE TITLE
Making use of Nerd Fonts

### ISSUE THREAD

**Issue by p-vernaeckt** [fmtlib/fmt#3155]
Hi all.

I'm trying to make use of [Nerd fonts](https://www.nerdfonts.com/). I've been using them in my terminal/IDEs for a long while now, and I'd like to print their content using fmt.

For example if I want ot print a folder which hex value is `ea83` (see [here](https://www.nerdfonts.com/cheat-sheet)), fmt complains about the hex value being out of range.

Can someone point me to the right direction?

**Comment by OnurKader** [comment]
How are you printing it? Seems to work for me 
![2022-10-26_20-08-43](https://user-images.githubusercontent.com/33760623/198091658-41f091a9-3a00-449c-8840-983503e704a9.png)

[godbolt](https://godbolt.org/z/EehcWPbYK)
