### ISSUE TITLE
Write to ostream with colors

### ISSUE THREAD

**Issue by AntoinePrv** [fmtlib/fmt#3159]
Hello, and thank you for this project!

Right now we can print to a `std::ostream`
```cpp
  // With ostream
  fmt::print(
    std::cerr,
    "Elapsed time: {} seconds\n", 1.23
  );
```
And print with colors
```cpp
// With color
  fmt::print(
    fmt::emphasis::bold | fg(fmt::color::red),
    "Elapsed time: {} seconds\n", 1.23
  );
```
But we cannot do both.
I imagine that there is a good reason for having an `std::ostream` overload. What are the downsides of using `format` in the example below? Performances?
Is there a better way to do the following?
```cpp
// Desired output
std::cerr << fmt::format(
  fmt::emphasis::bold | fg(fmt::color::red),
  "Elapsed time: {} seconds\n", 1.23
);
```

Would it make sense to allow for something like the following?
```cpp
// Does not compile
fmt::print(
  std::cerr,
  fmt::emphasis::bold | fg(fmt::color::red),
  "Elapsed time: {} seconds\n", 1.23
);
```

Full example: https://godbolt.org/z/Ebre5s4Kc

**Comment by vitaut** [comment]
You can already use `print` with `stderr` which will likely be faster than the iostream version or use `format` with color and stream the output. I don't think we should add color/ostream overloads but you can easily write such function yourself.
