### ISSUE TITLE
enum Type { BOOL } cause macro conflit

### ISSUE THREAD

**Issue by liuying2999** [fmtlib/fmt#316]
i use fmt with gcc4.4.7 and old project, there are a lot a often-use macros , such as BOOL, byte, and so on,and cause compile failed.
so i change it as below:
enum Type {
	FT_NONE, FT_NAMED_ARG,
    // Integer types should go first,
    FT_INT, FT_UINT, FT_LONG_LONG, FT_ULONG_LONG, FT_BOOL, FT_CHAR, FT_LAST_INTEGER_TYPE = FT_CHAR,
    // followed by floating-point types.
	FT_DOUBLE, FT_LONG_DOUBLE, FT_LAST_NUMERIC_TYPE = FT_LONG_DOUBLE,
	FT_CSTRING, FT_STRING, FT_WSTRING, FT_POINTER, FT_CUSTOM
  };

**Comment by vitaut** [comment]
Please see #306 for a solution that doesn't require renaming.
