### ISSUE TITLE
format tuple that has pointer as one of the types

### ISSUE THREAD

**Issue by ilobilo** [fmtlib/fmt#3165]
how do I format a tuple that has pointer (that is not void*) as one of the types?
for example:
```c++
#include <fmt/ranges.hpp>
std::tuple<int*, const char*> tup { (int*)0x123, "Hello, World!" };
fmt::print("{}", tup);
```
It throws an error for int*

**Comment by vitaut** [comment]
Formatting of non-void pointers is disallowed so you need to convert the first tuple element to `void*`, e.g:

```c++
fmt::print("{}", std::tuple<void*, const char*>(tup));
```

https://godbolt.org/z/vrq1xfszn
