### ISSUE TITLE
[question] Is cross-compilation supported?

### ISSUE THREAD

**Issue by mirkobraic** [fmtlib/fmt#3166]
Hello, I'm developing a cross-platform C++ library using CMake, Ninja, Clang, and Conan. I've been able to cross-compile the library for Linux (from Windows) with a [prebuilt Ubuntu toolchain](https://gnutoolchains.com/ubuntu/). However, I've encountered problems while trying to add fmt Conan package. Here is my conanfile:

*conanfile.txt*
```
[requires]
fmt/9.0.0

[generators]
cmake

[options]
fmt:shared=True
```

I've also created two Conan profiles:

*clangwindows*
```
[settings]
os=Windows
arch=x86_64
compiler=clang
compiler.version=14
build_type=Release

[env]
CC=clang
CXX=clang++
CONAN_CMAKE_GENERATOR=Ninja

[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

*clanglinux*
```
[settings]
os=Linux
arch=x86_64
compiler=clang
compiler.version=14
build_type=Release

[env]
CC=clang
CXX=clang++
CONAN_CMAKE_GENERATOR=Ninja
CONAN_CMAKE_SYSROOT="C:/path/to/ubuntu/toolchain/x86_64-linux-gnu/sysroot"

[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

When I try to build the fmt package with command: `conan install . --build=fmt -pr:h=clanglinux -pr:b=clangwindows` it fails with the following error:

```
CMake Error at CMakeLists.txt:231 (add_library):
  The install of the fmt target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based or XCOFF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH
  variable may be set to avoid this relinking step.
```

Is there something I'm doing wrong or is there some incompatibility with Conan/Clang and the fmt package? I'm having difficulties understanding the root cause of the issue.

### Environment Details
Windows 10, 20H2
Clang 14.0.5
Conan 1.53.0
CMake 3.24.0
Ninja 1.10.2
Python 3.10.5

**Comment by vitaut** [comment]
I think this is more of a CMake question. The line https://github.com/fmtlib/fmt/blob/c4ee726532178e556d923372f29163bd206d7732/CMakeLists.txt#L231 is just a basic call to `add_library` and we don't do anything special with `RPATH` there.
