### ISSUE TITLE
Slightly misleading chrono extension documentation

### ISSUE THREAD

**Issue by eli-b** [fmtlib/fmt#3169]
The [Chrono Format Specifications](https://fmt.dev/dev/syntax.html#chrono-specs) section claims "the available presentation types ... for chrono durations and time points are" and then lists only 'H', 'M', and 'S'. This may lead the reader to believe the rest of the ~39 chrono_type characters only apply to `std::tm`, which I believe is incorrect.

Also, following #1866, the list of chrono presentation types should be expanded with a description for each type. If the types are meant to be the same as strftime's, this is not mentioned.

**Comment by vitaut** [comment]
The docs have been updated: https://fmt.dev/dev/syntax.html#chrono-specs.

**Comment by eli-b** [comment]
Thanks, @vitaut, this is a great improvement to the docs! And so quick, too...
