### ISSUE TITLE
formatting enum calls deprecated function

### ISSUE THREAD

**Issue by Diltsman** [fmtlib/fmt#3171]
I am able to reproduce this in both 9.1.0 and master.  I cannot figure out how to cause the warning in Compiler Explorer (godbolt.org).

When I compile I get this warning, pointing to the one version of `map()` that is deprecated.  Is there something that I should do to eliminate this warning?

```
/external-fmt/include/fmt/core.h:1551:50: warning: 'map' is deprecated [clang-diagnostic-deprecated-declarations]
    type_constant<decltype(arg_mapper<Context>().map(std::declval<const T&>())),
                                                 ^
/external-fmt/include/fmt/core.h:1745:32: note: in instantiation of template type alias 'mapped_type_constant' requested here
  return static_cast<unsigned>(mapped_type_constant<Arg, Context>::value) |
                               ^
/external-fmt/include/fmt/core.h:1902:28: note: in instantiation of function template specialization 'fmt::detail::encode_types<fmt::basic_format_context<fmt::appender, char>, SOME_ENUM_TYPE>' requested here
      (is_packed ? detail::encode_types<Context, Args...>()
                           ^
/external-fmt/include/fmt/core.h:1932:16: note: in instantiation of template class 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, SOME_ENUM_TYPE>' requested here
constexpr auto make_format_args(Args&&... args)
               ^
/external-fmt/include/fmt/core.h:3224:28: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, SOME_ENUM_TYPE &>' requested here
  return vformat(fmt, fmt::make_format_args(args...));
                           ^
/home/corona/src/external-fmt/include/fmt/core.h:1491:48: note: 'map' has been explicitly marked deprecated here
  FMT_DEPRECATED FMT_CONSTEXPR FMT_INLINE auto map(const T& val)
                                               ^
```

**Comment by Diltsman** [comment]
In looking through the {fmt} documentation in more detail, there appear to be four ways to deal with this:
1. Cast to int
2. Pass the enum via: fmt::underlying(MY_ENUM) - an extension beyond C++20
3. Override fmt_as() for the enum type - an extension beyond C++20
4. Specialize fmt::formatter for the enum type

Is there something else that I am missing?

**Comment by Diltsman** [comment]
This specialization for fmt::formatter appears to make things work while not preventing specialization for individual enum types.

template <typename T>
struct fmt::formatter<T, std::enable_if_t<std::is_enum<T>::value, char>> :
    fmt::formatter<typename std::underlying_type<T>::type> {
  template <typename FormatCtx>
  auto format(const T &a, FormatCtx& ctx) const {
    return fmt::formatter<typename std::underlying_type<T>::type>::format(static_cast<typename std::underlying_type<T>::type>(a), ctx);
  }
};

**Comment by MarvelDC** [comment]
Thanks @Diltsman !

Here's the working formatter without GitHub removing the angled brackets.
```cpp
template <typename T> struct fmt::formatter<T, std::enable_if_t<std::is_enum<T>::value, char>>: fmt::formatter<typename std::underlying_type<T>::type> {
    template <typename FormatContext>
    auto format(const T &a, FormatContext& ctx) const {
        return fmt::formatter<typename std::underlying_type<T>::type>::format(static_cast<typename std::underlying_type<T>::type>(a), ctx);
    }
};
```

To anyone reading, you can learn more at https://fmt.dev/latest/api.html#formatting-user-defined-types

**Comment by vitaut** [comment]
Defining such a `formatter` is not recommended. You should only define formatters for your types. It is better to add `format_as` in your namespace instead.
