### ISSUE TITLE
fmt::format_to stack hungry? 

### ISSUE THREAD

**Issue by basprins** [fmtlib/fmt#3172]
Hi,

I am using fmt format on a micro controller project. I am noticing a pretty heave impact on the stack usage. I made a small example to make clear what I am observing. I create an app which runs one free rtos task. The task is given 850 words of stack. The task doesn't do much other then format a string, and get the tasks remaining stack.

The results I found are shown below.

freertos task stack size : 850 words
string to format: "This is completely pointless 400.0"

I am comparing fmt format vs snprintf vs nothing.
snprintf(buffer, sizeof(buffer), "%s %s %s %s %f", "this", "is", "completely", "pointless", 400.0);
framework::format(etl_buffer, "{} {} {} {} {}", "this", "is", "completely", "pointless", 400.0);

fmt format
remaining stack: 172 words (debug build)
remaining stack: 312 words (release build)

snprintf
remaining stack: 546 words (debug build)
remaining stack: 562 words (release build)

nothing
remaining stack: 546 words (debug build)
remaining stack: 562 words (release build)

So obviously the "nothing" code still uses stack. It calls into freertos code, so that's fact of life for me. The part which worries me is that fmt claims so much on top, where I can't even tell the high water mark introduced by snprintf (it falls in the shadow of what freertos is doing). 

Does this sound familiar? Can I improve this by switching on certain compiler directives when I compile fmt? Or is this simply what it is, a super brilliant library, but not really suitable on a micro controller? Am I still doing something wrong? 

The code which produces above results 

```
static char buffer[400];
etl_string_400 etl_buffer;

static void test(void * parameter)
{
    while (1)
    {
        //snprintf(buffer, sizeof(buffer), "%s %s %s %s %f", "this", "is", "completely", "pointless", 400.0);
        //framework::format(etl_buffer, "{} {} {} {} {}", "this", "is", "completely", "pointless", 400.0);

        volatile auto remaining = _free_rtos.get_task_high_water_mark(nullptr);

        _free_rtos.delay(1000);
    }
}
```
For clarity the implementation of my wrapper

```
    template <const size_t size, typename... T>
    inline void format(etl::string<size> &output, const char* fmt, T&&... args)
    {
        fmt::format_to(std::back_inserter(output), fmt, std::forward<T>(args)...);
    }
```
Before anybody suggests that etl is the problem. I define the string container globally, it's passed as reference into `std::back_inserter`. So from where I am standing, no reason to explode my stack on aspect.

**Comment by basprins** [comment]
Forgot to mention, when I don't call into fmt::format_to, but only call into std::back_inserter, I don't see any high water mark as a result of that. So I am guessing fmt::format_to is making copies of the container. And a bit worried at the same time this is by design and the end of fmt format for me :). Hope you have good news for me!

**Comment by vitaut** [comment]
When the output iterator is not recognized as a `back_insert_iterator` to a contiguous container {fmt} will use buffering for performance reasons. The default buffer size is 256: https://github.com/fmtlib/fmt/blob/d2e89c8b080394e996d449371267365c223ca76b/include/fmt/core.h#L989

You can avoid this by specializing the `is_contiguous` trait if your container is contiguous similarly how it is done for `std::string`: https://github.com/fmtlib/fmt/blob/d2e89c8b080394e996d449371267365c223ca76b/include/fmt/core.h#L819-L820

If your container is not contiguous, you can reduce stack usage by defining a new `buffer` subclass with a smaller buffer size.

**Comment by basprins** [comment]
Hi @vitaut 
I am sorry, but I have another  question. As you probably already noticed, I am using etl template library. I am trying to figure out if I can define a container as contiguous, but I don't know if I am looking in the right place.

Of course, the etl container creates a contiguous buffer. The question is if they obey the "rule" so that fmt is capable of recognizing this. Or, is *user code* (my code) somehow capable of telling fmt that the container is contiguous? 

So should I dive into etl code? Or would you happen to have experience with etl too? 

Hope you can help me a bit further, thx

**Comment by basprins** [comment]
Aha, I think I start to understand. Let me drown a bit longer, maybe I will understand this, at some point :)

**Comment by vitaut** [comment]
Unfortunately I'm not familiar with etl but basically{fmt} is expecting a small subset of the vectorAPI.

**Comment by basprins** [comment]
Hi @vitaut 
I am not an expert, and not half the c++ programmer you are, but whatever I try, I come to the same conclusion. {fmt} is rather costly stackwise compared to snprintf.
```
char buffer_raw[500];
fmt::memory_buffer buffer;

void bla()
{
        auto[out, size] = fmt::format_to_n(buffer.data(), 500, "{} {} {} {} {} {}", "this", "is", "a", "bit", "sad", 3);
        //snprintf(buffer_raw, 500, "%s %s %s %s %s %d", "this", "is", "a", "bit", "sad", 3);
        volatile auto remaining = _free_rtos.get_task_high_water_mark(nullptr);
}
```
fmt stack used = 269 (words/uint32_t)
snprintf stack used = 51 (words/uint32_t)

Can you confirm I am using {fmt} the right way? 
Anything I can do to improve the stack usage?

Defining a smaller buffer has no impact.

```
fmt::basic_memory_buffer<char, 60> buffer;
```
Still results in the same stack consumption.

**Comment by vitaut** [comment]
It's essentially the same case as I explained before: `format_to_n` is using `iterator_buffer` which has an internal buffer of size 256 by default. You'll need to write your own buffer subclass to reduce that. A PR to make it configurable would be welcome.
