### ISSUE TITLE
[documentation] Non-working example for Argument Lists

### ISSUE THREAD

**Issue by steffenb7333** [fmtlib/fmt#3173]
The [example](https://godbolt.org/z/oba4Mc) linked to in [the Argument Lists section](https://fmt.dev/latest/api.html#argument-lists) results in a compile error.

```
<source>:13:13: error: no member named 'make_args_checked' in namespace 'fmt'
       fmt::make_args_checked<Args...>(format, args...));
...
```

**Comment by OnurKader** [comment]
The dev version [docs](https://fmt.dev/dev/api.html#argument-lists) seems to be different and compiles [godbolt](https://godbolt.org/z/Gab1q3jKE)

**Comment by vitaut** [comment]
This has been fixed in dev docs already.
