### ISSUE TITLE
[documentation] Missing documentation / missing mention of header args.h for fmt::dynamic_format_arg_store

### ISSUE THREAD

**Issue by steffenb7333** [fmtlib/fmt#3174]
[fmt::dynamic_format_arg_store](https://fmt.dev/latest/api.html#_CPPv4I0EN3fmt24dynamic_format_arg_storeE) is neither documented nor is the needed header `fmt/args.h` mentioned anywhere in the current documentation.

**Comment by vitaut** [comment]
Added to the docs in https://fmt.dev/dev/api.html#args-api. Thanks for the suggestion.
