### ISSUE TITLE
Allow removal of arguments from dynamic_format_arg_store

### ISSUE THREAD

**Issue by marack** [fmtlib/fmt#3176]
The `dynamic_format_arg_store` class currently only provides `push_back()` and `clear()` functions for modifying the contained arguments.  It would be very useful to allow removal of arguments via `pop_back()` and potentially even `resize()`.

My use case is that I have a set of "standard" named arguments that I want to use in a series of formatting operations, however each individual operation may also have several extra named arguments that are relevant only to that operation.  For example, a loop where each iteration of the loop has the same arguments except for one or two that depend on the particular loop iteration.

Ideally I could implement this by creating a single `fmt::dynamic_format_arg_store` and fill it with the constant arguments, then push/pop additional arguments for each iteration.

Note that I can't store reference wrappers to all the arguments up front and then modify the arguments during the loop, because each iteration may expose a different set of per-iteration arguments.  (In reality my use case is not a simple loop and the arg store is passed down into several different functions).

```C++
auto fmt_string = fmt::runtime(some_user_passed_format_string);

auto store = fmt::dynamic_format_arg_store<fmt::format_context>{};
store.push_back("foo"_a = 1);
store.push_back("bar"_a = "some constant");

for (auto const& item : container)
{
    switch (item.typ())
    {
    case some_type:
        store.push_back("count"_a = item.count());
        fmt::vprint(fmt_string, store);
        store.pop_back();
        break;
    case some_other_type:
        store.push_back("date"_ = item.date());
        store.push_back("time"_ = item.time());
        fmt::vprint(fmt_string, store);
        store.pop_back();
        store.pop_back();
        break;
    }
}
```

Is this a sensible thing to ask for?

Looking at the implementation of `fmt::dynamic_format_arg_store` it doesn't seem like it would be hard for me to implement, but I don't want to start if there's a reason why this functionality has been deliberately omitted.

**Comment by vitaut** [comment]
`dynamic_format_arg_store` is effectively a builder for `format_args` so I don't think we should support mutation. I recommend using some other mutable data structure to store your args and only construct arguments just before the call to a formatting function.
