### ISSUE TITLE
New warning with Clang for non-header only mode

### ISSUE THREAD

**Issue by mwinterb** [fmtlib/fmt#318]
All usages of "Data" in format.h trigger a new warning in clang, `-Wundefined-var-template`.

The fix is easy enough, after "`typedef BasicData<> Data;`", add:
```c++
#ifndef FMT_HEADER_ONLY
extern template struct BasicData<void>;
#endif
```

But I don't have access to enough compilers to identify the necessary feature test for extern template support, so I don't feel comfortable submitting a PR. GCC's C++11 status page just says "Yes" (going back to at least 4.3). Clang reports 2.9. I think MSVC has had support for them for "ages", possibly as far back as VS 2003, before they were standard. Intel is at least 11.1. Curiously, Visual Studio 2015's intellisense compiler complains `'extern template' cannot follow explicit instantiation of class "fmt::internal::BasicData<void>"`, which would suggest possibly this instead:
```c++
#ifndef FMT_HEADER_ONLY
#ifndef __INTELLISENSE__
extern template struct BasicData<void>;
#endif
#endif
```

Since it's a clang-only warning, one option would be to just use `FMT_HAS_FEATURE`, but I can't find a relevant feature test listed here:
http://clang.llvm.org/docs/LanguageExtensions.html#checks-for-standard-language-features
Another cheap option would be just be a check for `__clang__` being defined, but that would prevent prevent working with a pre-2.9 Clang.

The warning was added to clang here http://reviews.llvm.org/rL266719 and discussed here http://reviews.llvm.org/D12326

Sorry, this is far too many words for a simple thing, I just didn't feel comfortable submitting a PR for something I was pretty certain wouldn't work everywhere, and I don't have enough experience supporting multiple compilers at once to make an optimal choice.

**Comment by vitaut** [comment]
`BasicData` is not a variable template, so this looks like a bug in clang. What version of clang do you use and what is the full warning message?

**Comment by mwinterb** [comment]
Of course I should have included the full warning message, sorry. The warning is possibly confusingly named, but based on the idea behind the warning seems like it's correctly issued in this case.
One example:
```
fmt/format.h(839,38): warning : instantiation of variable 'fmt::internal::BasicData<void>::POWERS_OF_10_64' required here, but no definition is available [-Wundefined-var-template]
    return to_unsigned(t) - (n < Data::POWERS_OF_10_64[t]) + 1;
                                       ^
fmt/format.h(826,25):  note: forward declaration of template entity is here
    static const uint64_t POWERS_OF_10_64[];
                          ^
fmt/format.h(839,38):  note: add an explicit instantiation declaration to suppress this warning if 'fmt::internal::BasicData<void>::POWERS_OF_10_64' is explicitly instantiated in another translation unit
    return to_unsigned(t) - (n < Data::POWERS_OF_10_64[t]) + 1;
                                       ^
```

The clang build is their one of their Windows nightlies based on r268238 from May 2. I'll check with a Debian build (also nightly) hopefully tomorrow. And, yes, it's a nightly, and nightlies can have notable bugs (especially with the extra quirks that are enabled for MSVC compatibility), but a warning saying "this template was implicitly instantiated, but there was no definition found for it in this translation unit" seems correctly issued in this instance.

**Comment by vitaut** [comment]
Thanks for providing additional info. Could you check if https://github.com/fmtlib/fmt/commit/744c2824c5217c5a92dc48a2ff959d36dc8c760d fixes the problem?

**Comment by mwinterb** [comment]
Yes it did, thank you.
