### ISSUE TITLE
Self-referencing types fail to compile with v9

### ISSUE THREAD

**Issue by mattgodbolt** [fmtlib/fmt#3182]
Code that compiled with gcc on 8.* no longer compiles for 9.* (or indeed clang it seems): https://godbolt.org/z/PzvbnvP16

How might one (in general) handle recursive data structures like:
```cpp

struct Thing {
    using ArrayType = std::vector<Thing>;
    using Variant = std::variant<ArrayType, bool>;
    Variant v;
};
```

The newer check for "is_streamable" / "has_const_formatter" require a fully-formed formatter class which doesn't exist until the closing of the class. As the function is `auto` I don't know what type it returns to forward declare (or declare later). Is there a pattern to handle this kind of thing?

Thanks!

**Comment by mattgodbolt** [comment]
I tried wrapping any self-references in a simple type that held a pointer, and then separately handling the fmt specialisation for that reference type, but that still blew up. https://godbolt.org/z/qaPs66nYK

**Comment by mattgodbolt** [comment]
I think I got it working, in the most heinous way: https://godbolt.org/z/rK1vh5c6K

The "trick" is to separate the definition and declaration of the `format` function, which I do by this travesty:

```cpp
    template <typename FormatContext>
    auto format(const Thing &e, FormatContext &ctx) const
        -> decltype(fmt::format_to(ctx.out(), "{}", 123));
```

and then

```cpp
template <typename FormatContext>
auto fmt::formatter<Thing>::format(const Thing &e, FormatContext &ctx) const
    -> decltype(fmt::format_to(ctx.out(), "{}", 123)) {
// body goes here
}
```

but it seems very likely there's a more elegant way to get the return value of the `auto` function. Ideas welcomed!

**Comment by mwinterb** [comment]
The docs for `formatter` generally accept `fmt::format_context` as the `FormatContext` parameter, and specify the return type as `fmt::format_context::iterator`
https://fmt.dev/dev/api.html#formatting-user-defined-types
You may be able to do the same, or presumably at the very least, all possible FormatContext types will have a nested `iterator` type https://godbolt.org/z/f8Eje4e71

I don't know all of the reasons you would need to use a template parameter for the FormatContext. Generally it's if you need to support non-char code unit types, but it's possible `FMT_COMPILE` needs it, too?

**Comment by mattgodbolt** [comment]
>  I don't know all of the reasons you would need to use a template parameter for the FormatContext.

Me neither - every example uses `auto` everywhere so I assumed it was an important part of the contract

**Comment by mattgodbolt** [comment]
Ah! looks like the docs have been updated to use trailing return types. My code is all from pre-8 and copy pasted from the examples there. Thanks~
