### ISSUE TITLE
Hardcoding `CMAKE_CXX_STANDARD` breaks source-consuming downstream projects using `target_compile_features`

### ISSUE THREAD

**Issue by ChrisThrasher** [fmtlib/fmt#3189]
https://github.com/fmtlib/fmt/blob/a935ac3e60306f9220ed983eac97cb44a492171c/support/cmake/cxx14.cmake#L10-L12

For project consuming the latest release of fmt via `add_subdirectory` like seen [here](https://github.com/zakinadhif/Fyshx/blob/8a5cb8517589c24f9452ff110c962177b5e99261/CMakeLists.txt#L15-L19) who also use the modern `target_compile_features`-based approach to enable a specific language standard like C++17 have their builds broken by the above snippet. The above snippet can result in their requested language standard being overridden by the default language standard used in fmt unless they're careful to set `CMAKE_CXX_STANDARD` themselves before including fmt.

I see this is likely the case because the library claims to support CMake versions all the way back to 3.1, well before `target_compile_features` was added. Can the minimum version be raised to use `target_compile_features` or can we at least add some extra CMake code to us the modern language specification functions when possible?

**Comment by vitaut** [comment]
`target_compile_features` is available in CMake 3.1.3: https://cmake.org/cmake/help/v3.1/command/target_compile_features.html. A PR to bump the minimum required version and  replace `CMAKE_CXX_STANDARD` with something target-based would be welcome.

**Comment by ChrisThrasher** [comment]
The `cxx_std_xx` properties weren’t added until version 3.8. We’d have to make a more substantial minimum version increase. Is that okay?

**Comment by ChrisThrasher** [comment]
https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD

The value `17` for `CXX_STANDARD` also isn't supported until CMake 3.8.

**Comment by vitaut** [comment]
I suggest replacing `CMAKE_CXX_STANDARD` with `FMT_CXX_STANDARD` and using this variable to set the targets' `CXX_STANDARD` property. This way we don't need to bump cmake all the way to 3.8 (c++17 can be supported conditionally).

**Comment by ChrisThrasher** [comment]
What platforms are you supporting that are still limited to CMake version 3.1? That's quite old at this point. It may be worth it to let such users stick to the current release so that we can improve the experience for the majority of users who are using ~3.10 or newer.

**Comment by vitaut** [comment]
It's more about the question whether we need to bump the version rather than supporting some specific platform. Anyway, 3.8 is quite old version so it's probably OK to bump it if it makes things significantly simpler.

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/fmt/commit/daf0c44be7b4b5768e5892c46af5b347303321d4

Here's what I had in mind. Please correct me if C++11 is not in fact the minimum language standard.

**Comment by phprus** [comment]
@ChrisThrasher 
C++11 is the minimum supported language standard.

**Comment by ChrisThrasher** [comment]
See PR #3205
