### ISSUE TITLE
Question: Why is generic copy_str() implemented with a while loop instead of using std::copy()? (v9.1)

### ISSUE THREAD

**Issue by lano1106** [fmtlib/fmt#3190]
`fmt::format_to(std::ostreambuf_iterator<char>{o}, "{}", rhs);`

the result will be copied by the while loop instead of taking advantage of the std::copy specializations for ostreambuf_iterator provided by gcc (and possibly pretty much all the compilers out there!)

See for yourself in
/usr/include/c++/12.2.0/bits/streambuf_iterator.h

Also, I wonder if having fmt::format() returning a proxy to detect if it needs to transfer the memory_buffer into a string or if it can copy its content into an ostream has been considered...

Here is the context. I am pretty sure that this sort of code is very widespread among your userbase:

`cout << fmt::format("{}", thing_to_format);`

this is inefficient because there will be memory allocation and 2 string copies. A much better approach would be:
`fmt::format_to(std::ostreambuf_iterator<char>{o}, "{}", rhs);`

The proxy solution is what is used by std::put_time:
https://en.cppreference.com/w/cpp/io/manip/put_time

**Comment by lano1106** [comment]
I have just given my suggestion a try. After having replaced the copy_str() while loop for std::copy(), I got a bunch of weird compilation issues when compiling the tests. I assume that the while() loop was precisely to workaround those compilation errors... I am not sure if it would be possible to directly address at the core root those errors or if they are unavoidable.

That being said, by adding another copy_str() specialization for my particular use case, it did work perfectly well:
```

template <typename Char, typename InputIt>
FMT_CONSTEXPR auto copy_str(InputIt begin, InputIt end, std::ostreambuf_iterator<Char> out)
    -> std::ostreambuf_iterator<Char> {
  return std::copy(begin, end, out);
}
```

**Comment by mwinterb** [comment]
It was because <algorithm> gets more expensive to include in recent C++
versions.

https://github.com/fmtlib/fmt/commit/b5dac0f0f8a112fba7b01165c792cd2aa8659c05

In fmt/stream.h, there are overloads of print that take a std::ostream as
its destination that may address your immediate concerns.

**Comment by lano1106** [comment]
thx for pointing out the print() alternative. Yes, that would do it for me besides getting me farther away from std::format conformity...

For which compilers did the <algorithm> inclusion started to become heavy?
I am asking because simply dropping my experiment into my local fmt/core.h copy, it did compile fine everything without having to put back the preprocessor directive to include <algorithm>. This tells me that the std header file gets included from somewhere else... (with gcc)...

**Comment by lano1106** [comment]
How about a fmt::format() variation that would return the memory_buffer object possibly with 0 copy due to RVO?

I would prefer anything over getting a string implying a memory allocation & copy...

**Comment by vitaut** [comment]
Thanks for the suggestion but considering that there is already a better way to accomplish this (`print`) I don't think we need to do anything special for `ostreambuf_iterator`.

> How about a fmt::format() variation that would return the memory_buffer object possibly with 0 copy due to RVO?

You can already do this with `format_to`.
