### ISSUE TITLE
IAR compiler "unsupported FP"

### ISSUE THREAD

**Issue by mj8w** [fmtlib/fmt#3192]
With this compiler, format.h # 1482 is asserting "Unsupported FP". Is there anything I can do to avoid this situation? Can I ignore it?

**Comment by vitaut** [comment]
{fmt} requires IEEE754 `double`. If you don't use floating point you could define `FMT_USE_FLOAT` and `FMT_USE_DOUBLE` macros to 0 to disable this functionality.
