### ISSUE TITLE
What about benchmarks?

### ISSUE THREAD

**Issue by Roman-Koshelev** [fmtlib/fmt#3193]
The description contains the results of benchmarks, but their code and the ability to run are missing. The current results are probably very out of date. Also interesting is the comparison with std::format (in the libc++ implementation)

**Comment by vitaut** [comment]
Benchmarks reside in a separate repo (https://github.com/fmtlib/format-benchmark) pointed to from the README. I've updated speed test results (they are not that much different). A PR to add `std::format` support to format-benchmark would be welcome.

**Comment by Roman-Koshelev** [comment]
As far as I can see there is only itoa testing. And where are the benchmarks presented in the README of this repository?

**Comment by vitaut** [comment]
Please see https://github.com/fmtlib/fmt#benchmarks, it both points to the test and explains how to run it.
