### ISSUE TITLE
print c structs and enums?

### ISSUE THREAD

**Issue by infn-ke** [fmtlib/fmt#3194]
Any way to print c structs and enums? Something similar to boost fmtlib class formatter

https://www.boost.org/doc/libs/develop/libs/describe/doc/html/describe.html#example_fmtlib_class_formatter

**Comment by vitaut** [comment]
If you mean a generic formatter then there is no such thing in {fmt} but you can use the boost formatter that you linked to. You can also format enums as numbers with `format_as`: https://fmt.dev/latest/api.html.
