### ISSUE TITLE
Formatting a std::chrono::system_clock renders in local time, not in UTC

### ISSUE THREAD

**Issue by ned14** [fmtlib/fmt#3199]
For some time now we've had this in our cmake, so I figured time to upstream this:

```
  message(STATUS "NOTE: Patching '${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/fmt/chrono.h' to fix a formatting bug ...")
  file(READ "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/fmt/chrono.h" fmt_chrono_contents)
  string(REPLACE "  auto format(std::chrono::time_point<std::chrono::system_clock> val," "  auto format(std::chrono::time_point<std::chrono::system_clock, Duration> val," fmt_chrono_contents "${fmt_chrono_contents}")
  string(REPLACE "    return formatter<std::tm, Char>::format(localtime(val), ctx);" "    return formatter<std::tm, Char>::format(gmtime(std::chrono::time_point_cast<std::chrono::system_clock::time_point::duration>(val)), ctx);" fmt_chrono_contents "${fmt_chrono_contents}")
  file(WRITE "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/fmt/chrono.h" "${fmt_chrono_contents}")
```

Two things are changed here:

1. The `Duration` template parameter isn't passed through, breaking formatting time points with non-default duration types.

2. Formatting system clock time points is to UTC, not to localtime, as system clock specifically represents UTC not local time (if you want a local time point, use `chrono::local_t`). Microsoft's implementation of `std::format` agrees with this formatting interpretation i.e. system clocks format to UTC strings, local clocks format to local strings.

**Comment by vitaut** [comment]
The first change has already been applied. Could you by any chance submit the second one as a PR?

**Comment by ned14** [comment]
Last day of work for this year, so had a few spare minutes to get this done finally.

**Comment by ned14** [comment]
Apologies for the unprompted reply. Currently on holidays in the United States without any ability to write code, which is deliberate. Glad you figured out some way to merge it, will look into your remaining ask when I return to Europe in January.

**Comment by Jan-Otto-Bakkland-Volue** [comment]
Converting to local time not working as specified:
auto localTime = std::chrono::localtime(first_time)
![image](https://github.com/fmtlib/fmt/assets/116543087/5d643f2b-25fe-4bed-b482-dfb866c714eb)

or this:
  auto localTime = std::localtime(first_time); 
![image](https://github.com/fmtlib/fmt/assets/116543087/47897882-ca20-427d-9f0c-4e5cd1af63fe)

**Comment by vitaut** [comment]
@Jan-Otto-Bakkland-Volue, this doesn't look related to {fmt}. Please check cppreference or ask on StackOverflow.
