### ISSUE TITLE
Documentation: missing descriptions of chrono_type specifiers?

### ISSUE THREAD

**Issue by madscientist** [fmtlib/fmt#3201]
Looking at the table in https://fmt.dev/latest/syntax.html#chrono-specs I see only `H`, `M`, and `S` listed; are the rest of the specifiers for `chrono_type` missing or are they documented somewhere else?  I can't find them.  Are we supposed to look at the strftime() docs for more details or something like that?  If so it would be good to add that information to the docs.

Thx!

**Comment by vitaut** [comment]
The documentation has already been updated. This is the current snapshot: https://fmt.dev/dev/syntax.html#chrono-specs.
