### ISSUE TITLE
fmt::format_to appears to miss wchar_t overloads

### ISSUE THREAD

**Issue by jeanga** [fmtlib/fmt#3202]
Good day :-)

With fmt 9.1.0, I encounter an issue when I try to encapsulate format_to() into my log() function.
 
It appears format_to() compiles with a fmt::format_string but won't with a fmt::**w**format_string one.
(using std::wstring_view is not accepted because it's not a constant expression)

Here is my code:
```cpp
template <typename... Args>
inline void log(fmt::wformat_string<Args...>&& fmt, Args&&... args)
{
    fmt::wmemory_buffer buffer;
    fmt::format_to(std::back_inserter(buffer), std::forward<decltype(fmt)>(fmt), std::forward<Args>(args)...);
}
```

Here is the compiler explorer link https://godbolt.org/z/4GY5M6jje

Any hint on how I can wrap format_to for wide strings?

Thank you very much for fmt! It's an amasing library!

PS: I use MSVC 17.4 but it appears to repro with clang 10.0 too.

**Comment by vitaut** [comment]
You can use `vformat_to` for this (https://godbolt.org/z/55jxxahn3):

```c++
template <typename... Args>
inline void log(fmt::wformat_string<Args...> fmt, Args&&... args) {
  fmt::wmemory_buffer buffer;
  fmt::vformat_to(std::back_inserter(buffer), fmt::wstring_view(fmt),
                  fmt::make_wformat_args(args...));
}
```

Later versions of {fmt} will support compile-time checks in more places. In this particular case `vformat_to` is better because of fewer instantiations.

**Comment by jeanga** [comment]
Worked like a charm on first try!
Many thanks for your hard work on fmt, this is awesome!
I'm looking forward to the next releases with the support for more compile time checks!
(it found a number of format string errors in rarely used error message formatting already!)
