### ISSUE TITLE
va_list issues

### ISSUE THREAD

**Issue by hch557896** [fmtlib/fmt#321]
If there is a support function va_list
`
std::string StrTest(int x, ...)
{
	va_list args;
	va_start(args, x);
	std::string s = fmt::format("{0} {1} {0}.", args);
	va_end(args);
        return s;
}
`
`StrTest(1, "one", 2)`

**Comment by vitaut** [comment]
Varargs are not supported because they are inherently unsafe, but you can use variadic templates instead:

```c++
#include "fmt/format.h"

template <typename... T>
std::string StrTest(int x, const T & ... args) {
  return fmt::format("{0} {1} {0}.", args...);
}

StrTest(1, "one", 2);
```

**Comment by Spartan322** [comment]
`FMT_VARIADIC` is also a pre-C++11 option
