### ISSUE TITLE
sry i dont know how to reopen > warning C4307: “*” on VS2017 #3163

### ISSUE THREAD

**Issue by Qujamlee** [fmtlib/fmt#3211]
> I wasn't able to reproduce this in https://godbolt.org/z/baaGbjebz. Please provide more repro details.

There is indeed this problem, and I have reproduced it on the website you provided, but you need to choose x64msvc19.22 and earlier versions of the compiler.I copied the warning message:

x64 msvc v19.22 /std:c++latest /W2
Compiler stdout
example.cpp
<source>(5): warning C4307: '*': integral constant overflow
Program returned: 0

But using newer versions of the compiler does not have this warning. Why? Did the compiler do the optimization?
I'm doing the math, 
const uint32_t mod_inv_5 = 0xcccccccd = 3_435_973_837 (decimal), 
the square of it is 11_805_916_208_548_502_569, 
It does exceed the maximum range of uint32_t (4_294_967_295) ,
so the warning message seems reasonable, is it a bug?

_Originally posted by @Qujamlee in https://github.com/fmtlib/fmt/issues/3163#issuecomment-1329373638_

**Comment by vitaut** [comment]
For future reference: commenting on the original issue is enough, no need to open a duplicate.
