### ISSUE TITLE
Building with `-Weffc++`

### ISSUE THREAD

**Issue by gianzellweger** [fmtlib/fmt#3217]
I use {fmt} in some of my projects which are compiled with a lot of warnings including `-Weffc++`. This flag gives you guides to help follow C++ standards. When I compile with `g++`* however, the compiler throws a lot of warnings like this one for example:
```
~/fmt/include/fmt/core.h:2108:59: warning: 'operator=' should return a reference to '*this' [-Weffc++]
 2108 |   FMT_CONSTEXPR void operator=(basic_string_view<Char> s) {
      |                                                           ^
```
I now have three options:
* Remove `-Weffc++` from my builds and let my standard compliance suffer
* Remove `-Weffc++` from my `-Werror` so programs compile but I get a ton of warnings which at some point, I will start to ignore.
* Try to fix the source code of {fmt} myself and risk breaking someone else's legacy code if they update the library

<sup>*g++-12 (Homebrew GCC 12.2.0) 12.2.0</sup>

**Comment by vitaut** [comment]
In general fixing all possible warnings is a non-goal, we only focus on common ones such as `-Wall`. You can disable the warnings with `FMT_SYSTEM_HEADERS` or some other method.
