### ISSUE TITLE
Modifier for timezone offset result in compile error

### ISSUE THREAD

**Issue by dgnthr** [fmtlib/fmt#3220]
Hi,

I'm currently trying to print ISO8601 compatible time strings.

As per the specification I can print the timezone offset to UTC with the "%z" conversion specifier. This should for example print "+0100". Using the modifier E or O as in "%Ez" should print "+01:00". If I use either modifier I get a compile time exception FMT_THROW(format_error("invalid format"));

The example code I use is
```
#include <chrono>
#include <fmt/chrono.h>

int main() {
    auto time = std::time(0);
    auto LocalTime = std::localtime(&time);
    fmt::print("{:%z}\n", *LocalTime);
    fmt::print("{:%Oz}\n", *LocalTime);

    return 0;
}
```

Also see the example on compiler explorer https://godbolt.org/z/9cEvzKPn9

Am I doing something wrong? Thank you for your time!

**Comment by dgnthr** [comment]
I just checked the source code and saw that the modifiers (E, O) are not implemented for %z. I'll just use it without the colon.

**Comment by phprus** [comment]
Modifiers (``E``, ``O``) are not defined for ``%z`` format:
https://en.cppreference.com/w/cpp/chrono/c/strftime

**Comment by dgnthr** [comment]
I was referencing this https://en.cppreference.com/w/cpp/chrono/duration/formatter (close to the bottom).

> The modified commands %Ez and %Oz insert a : between the hours and minutes (e.g., -04:30).

**Comment by phprus** [comment]
@dgnthr 
PR: #3222

**Comment by dgnthr** [comment]
Wow! Amazingly fast. Thank you so much!
