### ISSUE TITLE
Is there a recommendation for implementing custom formatting that disallows any specifiers?

### ISSUE THREAD

**Issue by Delgan** [fmtlib/fmt#3221]
Hi there!

I'm implementing formatting of user-defined classes by specializing `fmt::formatter`.
However, I feel formatting directives for these classes does not make sense, and I would like to prohibit them.

I came up with the following solution ([Godbolt](https://godbolt.org/z/f5fMKxPvf)):

```cpp
#include <fmt/format.h>

struct Foo {};

struct SimpleFormatter : fmt::formatter<fmt::string_view>
{
    constexpr auto parse(fmt::format_parse_context& ctx) -> fmt::format_parse_context::iterator
    {
        auto it = ctx.begin();
        if (it != ctx.end()) {
            throw fmt::format_error(
                "This type does not support any formatting specifier.");
        }
        return it;
    }
};

template <>
struct fmt::formatter<Foo> : SimpleFormatter
{
    auto format(const Foo& detection, format_context& context) const
    {
        return format_to(context.out(), "{}", "Foo()");
    }
};


int main() {
  Foo foo;
  fmt::print("{}", foo);
  fmt::print("{:>10}", foo);  // NOK
}
```

I was wondering if this was somewhat the "best" way to implement such requirements or it could be improved somehow?
Maybe there already exist such formatter in `fmt` from which I could directly inherit?

Thanks.

**Comment by vitaut** [comment]
You don't need to do any checks in the `parse` function because if there are any unparsed specifiers the caller will produce an error. Also you don't use `fmt::formatter<fmt::string_view>` so inheriting from it is not needed either. Here's simplified code:

```c++
template <>
struct fmt::formatter<Foo> {
  constexpr auto parse(fmt::format_parse_context& ctx) {
    return ctx.begin();
  }

  auto format(const Foo& detection, format_context& ctx) const {
    return format_to(ctx.out(), "{}", "Foo()");
  }
};
```
https://godbolt.org/z/TvjYTxYjG

**Comment by Delgan** [comment]
Thanks for the answer! :+1: 

Just wondering,  do you think there is a point to provide such `simple_formatter` (name to be defined) in the `fmt` API, the same way `ostream_formatter` is provided?

I feel it should be used by default for most user types, the same way that in Python most objects (including default user classes) do not support formatting specifiers.
Of course, it's trivial to implement and use such base class. But it is more elegant to inherit a `fmt` struct directly and would guide the user about the canonical way to disable specifiers.

I can definitely open a PR if you're interested.
However, I understand perfectly if you prefer not to extend the API with such helper.

**Comment by vitaut** [comment]
I don't think we need to add such formatter to {fmt} because it is generally recommended to at least provide width/alignment e.g. by reusing other formatters.
