### ISSUE TITLE
There is no format specification for std::chrono

### ISSUE THREAD

**Issue by ujos** [fmtlib/fmt#3223]
Could you please add the `std::chrono` format specification on the `{fmt}` [SYNTAX](https://fmt.dev/latest/syntax.html#chrono-specs) web page.

I'm aware that `std::chrono` format specification mimics the `strftime` function format specification, however, the specification is still available in the [syntax.rst](https://github.com/fmtlib/fmt/blob/master/doc/syntax.rst#chrono-format-specifications) and in order to be more user friendly, would be great to repeat it on the SYNTAX page as well.

* `{fmt}` Version: 9.0

**Comment by vitaut** [comment]
The document you've linked to has already been updated to mention chrono types in https://fmt.dev/dev/syntax.html#chrono-format-specifications.

**Comment by ujos** [comment]
The link you provided points to `dev` (whatever it is). The link I provided points to ***latest***. 

Steps to reproduce:

1. Open https://fmt.dev/
2. Click "SYNTAX" (in the main menu on top)
3. Find "Chrono Format Specifications"

BTW, would be great to have a TOC on the top of the SYNTAX page :)

**Comment by mwinterb** [comment]
dev is current master. latest is the most recent release.

**Comment by ujos** [comment]
Well... What I say is that from the user perspective the documentation is not complete .

**Comment by ujos** [comment]
I mean I've opened the root web page ( https://fmt.dev/) and clicked the `SYNTAX` link. I had no option dev or latest.

**Comment by vitaut** [comment]
The documentation update will be included in the next release (similarly to code changes) but thanks for reporting anyway.
