### ISSUE TITLE
`format_to` chrono compilation failure with msvc 14.32 and 14.33(_MSC_VER=1932 and 1933) in C++20

### ISSUE THREAD

**Issue by Klaim** [fmtlib/fmt#3224]
This issue only appears when using msvc 14.32 and 14.33(_MSC_VER=1932 and 1933) in C++20 and I was not able to set that up in godbolt because only the last vcpkg version is visible. Here is the issue:
https://godbolt.org/z/f5b9hnPv4

Notes:
- changing to msvc 14.34 or latest will not hit that issue (so workaround: use latest msvc);
- this looks like a conflict somewhere related to how the standard library is implemented in that case; 
- I can reproduce the issue using clang 15.0.1 locally in which cases it uses the msvc version I have installed, which goes with last point; unfortunately I cannot reproduce this setup using compiler explorer;
- initially found when packaging for `build2` : https://github.com/build2-packaging/fmt/issues/4 ;
- affects at least 9.0.0 and 9.1.0

**Comment by vitaut** [comment]
Looks like the problem is that `std::format_to` is picked by ADL. The fix is to namespace qualify the call to `format_to`, i.e. change it to `fmt::format_to`: https://godbolt.org/z/3cYh3Gso9.

**Comment by Klaim** [comment]
@vitaut Damn, I just sent the package for publication but we can fix it in the test then
well I'll make a revision, thanks!

**Comment by vitaut** [comment]
Applied the workaround to the test in https://github.com/fmtlib/fmt/commit/3999fd193a452bb3adc442facbcd3eed3562edd2.
