### ISSUE TITLE
Typo in docs, or in the code (?)

### ISSUE THREAD

**Issue by klirichek** [fmtlib/fmt#3227]
<img width="788" alt="Снимок экрана 2022-12-14 в 18 13 53" src="https://user-images.githubusercontent.com/3593673/207581030-a89dff51-12d0-415e-b916-17614e1c9368.png">

I see this example in the docs, it looks wrong (not actually centered).

If code provides such output, seems that code need to be fixed.

If picture is wrong - seems, picture need to be fixed.

**Comment by vitaut** [comment]
I wasn't able to repro it:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/576385/207697339-eecf84a7-af8d-46f9-8fb6-879374d15410.png">

https://godbolt.org/z/zqGGdx1E7

If this still happens on the latest development version please provide more repro details.

**Comment by klirichek** [comment]
Oh...
That is error in cheatsheets, which looks so great, that I've decided it is official fmt documentation.
That's my miss.

(the typo is on https://hackingcpp.com/cpp/libs/fmt.html - and I think, it should be addressed to @muellan)

**Comment by hackingcpp** [comment]
@klirichek I've corrected the typo. Thanks for letting me know.
Strange, I originally created the output with fmtlib v7 and just copied it. Either there was a bug in v7 or I messed it up.
