### ISSUE TITLE
Localized formatting

### ISSUE THREAD

**Issue by Roman-Koshelev** [fmtlib/fmt#3233]
Currently, fmt::format only supports std::locale, which has some serious drawbacks. Support for the Unicode locale is important to me (which is also not always compatible with the posix locale). Are there any plans to support modern Unicode locales?

**Comment by vitaut** [comment]
There are no plans to support non-standard locale APIs at the moment. However, there is an experimental `format_facet` that supports Unicode: https://github.com/fmtlib/fmt/issues/1861#issuecomment-1236175349.
