### ISSUE TITLE
_wfopen support

### ISSUE THREAD

**Issue by Nekto89** [fmtlib/fmt#3234]
On Windows it is important to use UTF-16 file paths for opening files (at least until recent versions that allow using UTF-8 locale for WinAPI).

std::fstream has overload for std::wstring
for std::FILE* there is Windows-specific "_wfopen" method as a replacement for standard std::fopen.

Is it possible to provide a way to use fmt::output_file with UTF-16 encoded filepath?

**Comment by vitaut** [comment]
Supporting UTF-16 in a portable way is problematic but we could replace `sopen_s` with `_wopen` in

https://github.com/fmtlib/fmt/blob/master/src/os.cc#L224

This will allow passing UTF-8 paths. A PR to do this would be welcome.

**Comment by nenin-sc** [comment]
> This will allow passing UTF-8 paths.

Is it possible just transfer a handle to already opened file?

**Comment by vitaut** [comment]
> Is it possible just transfer a handle to already opened file?

It is not possible with the current API.

**Comment by Fros1er** [comment]
I'd like to work on this.
My current idea is adding a new ctor `file(wcstring_view path, int oflag);`, meanwhile cast UTF-8 path to UTF-16 in original ctor.
I wonder if it's a proper way to deal with the problem.

**Comment by vitaut** [comment]
Converting UTF-8 to UTF-16 and invoking `_wopen` on Windows makes sense but I don't think we should be adding a new ctor.

**Comment by Fros1er** [comment]
> Converting UTF-8 to UTF-16 and invoking `_wopen` on Windows makes sense but I don't think we should be adding a new ctor.

Maybe sometimes only `wchar_t *` is available. Converting from UTF-16 to UTF-8 then convert it back seems a little weird.

I'm not sure if this is a common situation.

**Comment by vitaut** [comment]
I think it would be OK to add a static "factory" function with the name that indicates that it is Windows-specific, e.g. `open_windows_file`, that takes a wide filename and returns `file`.
