### ISSUE TITLE
"Cannot format an argument. To make type T formattable provide a formatter<T> specialization..." message is mising in Visual Studio when passing a custom argument that needs formatter.

### ISSUE THREAD

**Issue by TrueWodzu** [fmtlib/fmt#3235]
Hi,

static assert message "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt" is very helpful in finding issues. However, it does not appear on Visual Studio compilers. Maybe something could be done in this regard?

Example: https://godbolt.org/z/x7arz61xP

**Comment by vitaut** [comment]
MSVC's diagnostics are known to be pretty bad and I am not aware of a way to workaround it. Perhaps you could provide feedback to its developers.
