### ISSUE TITLE
FMT_STRING compile time checking not working with vprint, vformat...

### ISSUE THREAD

**Issue by maxkunes** [fmtlib/fmt#3238]
I took the example from here: https://fmt.dev/latest/api.html#argument-lists and got it compiling with compiler explorer.
Unfortunately, it seems that compile time checking is not working properly with vprint or vformat... functions.

I assume I am doing something wrong, but the wiki doesn't seem to have any examples of this since the deprecation of `make_args_checked`. The wiki's godbolt link is using the old API that no longer compiles.

https://godbolt.org/z/KMTf13a1s shows the issue. Notice that we are getting a runtime error for something that should be a compile time error.

**Comment by mwinterb** [comment]
The documentation wasn't fully updated for 9.0.
https://fmt.dev/dev/api.html#argument-lists is the documentation for HEAD,
but the sample works fine for 9.0.

**Comment by maxkunes** [comment]
> 

Thanks for the quick response, that resolved the issue. Thanks!
