### ISSUE TITLE
Getting warnings when compiling with VS 2022

### ISSUE THREAD

**Issue by FerdinandStapenhorst** [fmtlib/fmt#3242]
Environment:
- Visual studio 2022 on Windows 10
- fmt 9.1.0

Source Code:

```
#include <fmt/core.h>
int main()
{
    fmt::print("{}", '\n');
}
```
Compiler flags: /permissive- /W4 /std:c++20 /sdl

Compiling shows the following warnings:

`Warning | C6285 | (<non-zero constant> \|\| <non-zero constant>) is always a non-zero constant.  Did you intend to use the bitwise-and operator? | HelloWorld | VcPkg\vcpkg\installed\x64-windows\include\fmt\core.h | 416 |  `

`Warning | C26437 | Do not slice (es.63). | HelloWorld | VcPkg\vcpkg\installed\x64-windows\include\fmt\core.h | 730 `

`Warning | lnt-logical-bitwise-mismatch | Using logical '!' when bitwise '~' was probably intended. | HelloWorld | VcPkg\vcpkg\installed\x64-windows\include\fmt\core.h | 2320 |  `

`Warning | lnt-assignment-equality | Assignment '=' used when equality '==' probably intended. | HelloWorld | VcPkg\vcpkg\installed\x64-windows\include\fmt\core.h | 2436 |  `

<img width="1282" alt="Screenshot 2022-12-22 at 22 48 39" src="https://user-images.githubusercontent.com/118904606/209231909-8fb51c55-aa9b-4ba7-a1ed-c7d4d6110dfe.png">

**Comment by vitaut** [comment]
I wasn't able to repro this on the current version: https://godbolt.org/z/Wc57oG8sb. The first warning even refers to a comment in 9.1.0, not to actual code: https://github.com/fmtlib/fmt/blob/9.1.0/include/fmt/core.h#L416 =). In any case, these all look like false positive and can be safely ignored or suppressed.
