### ISSUE TITLE
format __int128 as smaller ints

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [fmtlib/fmt#3246]
In the experiments formatting division of int128 is pretty slow. 
An `if < numeric_limints<std::int64_t>::max()`=> format like int64 seems like a substantial improvement.

There is an appache2 version of a slightly better idea but I don't know if you could use that license wise.

**Comment by vitaut** [comment]
Is there an actual use case where it makes a difference or is it mostly theoretical?

**Comment by DenisYaroshevskiy** [comment]
It's not the most critical but I have some metrics that show it's important

**Comment by vitaut** [comment]
Closing as there are no plans to do this but a PR would be welcome.
