### ISSUE TITLE
Wide string formatting

### ISSUE THREAD

**Issue by Roman-Koshelev** [fmtlib/fmt#3250]
1) Now you can do
```std::string str = fmt::format(...);```
but unfortunately not possible
```std::u16string  str = fmt::format<char16_t>(...);```

2) If I write code
```
std::wstring wout;
fmt::format_to(std::back_inserter(wout), "{}", "Привет мир");
```
it won't work as expected. 

3) I can easily fix it by writing
```
template <class Ty = char>
std::basic_string<Ty> my_format(...) {
    std::basic_string<Ty> out;
    fmt::format_to(My_Converter(out), ...);
    return out;
}
```
why isn't there one out of the box?

4) My_Converter will receive input byte by byte, making it difficult to implement efficiently. The format function dumps the result into the destination object in large chunks (512 bytes as far as I remember).

The standard library can convert char to other character types (std::codecvt, std::wstring_convert, etc). What prevents you from writing beautiful convenient wrappers (see the example above)?

**Comment by vitaut** [comment]
`fmt::format<char16_t>` is not a valid API but `char16_t` is already supported (https://godbolt.org/z/bcz673Tjx):

```c++
std::u16string s = fmt::format(u"{}", 42);
```

Mixing different code unit types is intentionally disallowed because it would involve hidden transcoding. You can transcode the whole string and not individual code units.

**Comment by Roman-Koshelev** [comment]
What's wrong with implicit transcoding?
It also seems to me quite normal that such code will work. Why not?
```fmt::format("...{}", std::u32string{});```

**Comment by vitaut** [comment]
It hides inefficiency and potential transcoding errors. In any case, providing general purpose transcoding facilities is out of scope of {fmt}. There are other libraries for that.
