### ISSUE TITLE
Compile time check support to check formatting type for both printf style and format style

### ISSUE THREAD

**Issue by NelsenEW** [fmtlib/fmt#3252]
Would be great to have a compile-time checks that can parse and decide if the following format is a printf or format style. This would allow a user defined function that accepts any format and will throw an error if the format is incompatible
``` c++

int main(){
  auto str1 = my_format("%d", not_constexpr_functint()); // compiled
  auto str2 = my_format("{}", not_constexpr_functint()); // compiled
  auto str3 = my_format("%s", std::vector{1,2,3,4}); // compile time error
  auto str4 = my_format("{}", std::vector{1,2,3,4}); // compiled
  ...
}
```

I think this can be implemented with some templates metaprogramming with constexpr using `if constexpr` to determine which function to be called.

**Comment by vitaut** [comment]
That's an interesting idea but I don't think it's possible at the least because `%d` is a valid format string in the format API which is interpreted as literal text. In any case I don't think such functionality needs to live in the core library.
