### ISSUE TITLE
Format string check ignores superfluous args

### ISSUE THREAD

**Issue by dermojo** [fmtlib/fmt#3253]
The format string checks catch errors cause by incompatible or missing arguments, but not additional arguments.

E.g. I would expect that the following code doesn't compile:

```c++
fmt::print("{}", 5, 7);
```

Compiler explorer link: https://godbolt.org/z/4YaszMhhh

P.S.: Thanks for this great library!

**Comment by vitaut** [comment]
Unused arguments are allowed as in Python's `str.format` this API is modeled after and ordinary functions.
