### ISSUE TITLE
Q: number of visible/printable UTF-8 characters

### ISSUE THREAD

**Issue by RalphSteinhagen** [fmtlib/fmt#3257]
Hi, this may have been possibly answered elsewhere:

Is there a portable way to get the number of the actual printed/formatted/visible non-control/non-formatting characters using fmt?
Here is a small example for illustration: https://compiler-explorer.com/z/vo3Mn7a1v

```cpp
using namespace std::literals;
std::string a = "\033[31-1-\033[0m";
fmt::print("'{}'\t-> byte {:2} vs. visible {} length\n", a, fmt::formatted_size("{}", a), 3);
fmt::print("'{}'\t-> byte {:2} vs. visible {} length\n", "😀"sv, fmt::formatted_size("{}", "😀"sv), 1);
```
Produces the following (visually) correct output and byte sizes:
```text
'-1-'	-> byte 11 vs. visible 3 length
'😀'	-> byte  4 vs. visible 1 length
``` 

I am aware of the [wcswidth](https://man7.org/linux/man-pages/man3/wcswidth.3.html) POSIX interface which is not portable enough. Thanks in advance.

**Comment by vitaut** [comment]
In general it is not solvable and {fmt} doesn't provide a public API for this but there is an internal function that estimates visible width: https://github.com/fmtlib/fmt/blob/6056e07125a2c84f5fb1b65e14bf8d851a840071/include/fmt/format.h#L712.

**Comment by vitaut** [comment]
Also `compute_width` gives the width in terminal columns so 😀 has a width of 2, not 1:

<img width="121" alt="image" src="https://user-images.githubusercontent.com/576385/210149341-39e31816-e32c-4716-b285-4435ab36478a.png">

**Comment by RalphSteinhagen** [comment]
@vitaut thanks a lot for the pointers, much appreciated. 👍

**Comment by RalphSteinhagen** [comment]
Was a bit curious, went a bit down the rabbit hole, especially after @vitaut's comment on the emoji width of '2' -- which wasn't an initial core requirement of mine but used just because ... -- but nicely illustrated further problems that the internal {fmt} width estimator cannot handle as of v9.

In case someone else stumbles over the same problem, looking for a practical solution, and arrives here: I eventually went for a [modified*](https://raw.githubusercontent.com/RalphSteinhagen/unicode_display_width/master/include/unicode/display_width.hpp) solution of [`unicode::display_width(...)`](https://github.com/p-ranav/unicode_display_width) by Pranav Srinivas Kumar. It's a simple single header-only library (MIT) that should be easily incorporable into any project.

See the compiler-explorer example [here](https://compiler-explorer.com/z/xo4G5ereM) for usage. Example output:
```cpp
// [...]
const std::string a = "\x1b[31mX\x1b[23;32mX\x1b[0m";
const std::string b = "😀";
const std::string c = "👩‍🔬";
fmt::print("'{}'\t-> byte {:2} vs. visible length unicode: {} fmt: {}\n", a, a.size(),
           unicode::display_width(a), fmt::v9::detail::compute_width(a));
fmt::print("'{}'\t-> byte {:2} vs. visible length unicode: {} fmt: {}\n", b, b.size(),
           unicode::display_width(b), fmt::v9::detail::compute_width(b));
fmt::print("'{}'\t-> byte {:2} vs. visible length unicode: {} fmt: {}\n", c, c.size(),
           unicode::display_width(c), fmt::v9::detail::compute_width(c));
```
yielding:
```text
'XX'	-> byte 19 vs. visible length unicode: 2 fmt: 19
'😀'	-> byte  4 vs. visible length unicode: 2 fmt: 2
'👩‍🔬'	-> byte 11 vs. visible length unicode: 2 fmt: 5
```
N.B. printed in a terminal/console the first 'X' plots as red, the second 'X' as green.

Enjoy!

P.S. might be worthwhile to add the zero-width-jointer and ANSI escape sequence handling also to fmt? :thinking:

**Comment by vitaut** [comment]
I am not sure if we should handle ANSI escape sequences in this API (need to think more about it) but we do plan to add grapheme clusterization which will address the 👩‍🔬 case.
