### ISSUE TITLE
fmtlib doesn't guarantee backwards compatibility?

### ISSUE THREAD

**Issue by Roman-Koshelev** [fmtlib/fmt#3258]
I've noticed that in newer versions fmtlib checks the format string at compile time and therefore doesn't work with the string passed in at run time (as it used to). Moreover, this problem can be encountered when using C++17 and wanting to upgrade to 20. I accidentally stumbled upon the fact that formatting flags also do not maintain compatibility (for example, the 'L' flag used to be 'n' ). I don't understand how it's possible

**Comment by vitaut** [comment]
Major versions include breaking changes. Please see https://github.com/fmtlib/fmt/releases for details. If you want to avoid that pin to specific version.
