### ISSUE TITLE
Feature request: `fmt::to_string`

### ISSUE THREAD

**Issue by netheril96** [fmtlib/fmt#326]
Basically the same as `std::to_string`. It should not be hard to implement as it is functionally equivalent to `fmt::format("{}", XXX)`. Reasons that I would like to use `fmt::to_string` in lieu of `std::to_string`:

* `std::to_string` is not available on C++03.
* `std::to_string` is horrendously slow on some implementations. Last time I checked, MSVC internally creates a `stringstream` for every `std::to_string` call.

**Comment by vitaut** [comment]
Good idea. It can even be implemented in a more efficient way than `fmt::format("{}", XXX)`, something like:

```c++
template <typename T>
std::string to_string(const T &value) {
  fmt::MemoryWriter w;
  w << value;
  return w.str();
}
```

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/b6c0cf9683736dffbad7a48016d2b08878102371. `fmt::to_string` is defined in a separate header, `fmt/string.h`.

**Comment by vitaut** [comment]
It's documented here: http://fmtlib.net/dev/api.html#_CPPv2N3fmt9to_stringERK1T

**Comment by alabuzhev** [comment]
Could you please add fmt::to_wstring as well?

**Comment by vitaut** [comment]
@alabuzhev Would you be willing to submit a pull request along the lines of b6c0cf9683736dffbad7a48016d2b08878102371? =)
