### ISSUE TITLE
Improve documentation for format_as

### ISSUE THREAD

**Issue by ropieur** [fmtlib/fmt#3266]
Hi,
I wanted to return an std::string when defining format_as for a enum class,  but I was faced to a compilation error complaining that the enum was not formattable, and the reason was not that clear enough to understand the root cause issue.
After diving into the code, I figured out that the return type for format_as must be an integral type, which documentation is fully silent about it.
My 2 cents

**Comment by vitaut** [comment]
Thanks for the suggestion. The plan is to relax this limitation in the next major release but if it doesn't work out for some reason we'll clarify this in the docs.

**Comment by vitaut** [comment]
`format_as` can now return arbitrary formattable types including `std::string`. For example

```c++
#include <fmt/format.h>

enum class color { red, green, blue };

auto format_as(color c) -> std::string {
  switch (c) {
  case color::red:
    return "red";
  case color::green:
    return "green";
  case color::blue:
    return "blue";
  }
  return "unknown";
};

int main() { fmt::print("{}\n", color::blue); }
```
prints
```
blue
```

**Comment by greg-is-kub** [comment]
As of now I still encounter this error : 
https://godbolt.org/z/zrT9v41oG

**Comment by vitaut** [comment]
@greg-is-kub in your example `format_as` is a member which is incorrect. Please see the docs: https://fmt.dev/latest/api.html#formatting-user-defined-types.

**Comment by ibzib** [comment]
@vitaut Even if `format_as` is defined as a standalone function in the same namespace, I still can't get user type formatting to work with plain classes/structs, only enum classes. Am I doing something wrong or is this a limitation of the library?

https://godbolt.org/z/ahYPz7nz5

**Comment by vitaut** [comment]
@ibzib you need a newer version of {fmt} to use `format_as`, please see https://github.com/fmtlib/fmt/releases

**Comment by ibzib** [comment]
Thank you @vitaut for the super quick reply. Looks like arbitrary classes are only supported in v10+.

**Comment by capitalistspz** [comment]
I experienced the same error on 12.2.0, I solved it by including `fmt/format.h` instead of just `fmt/base.h`. It confused me because returning an integer from `format_as` did not trigger the same error.
