### ISSUE TITLE
Support std formatters

### ISSUE THREAD

**Issue by iwubcode** [fmtlib/fmt#3268]
Fmt library should be able to leverage std formatters, it seems it cannot.

See https://godbolt.org/z/cqYYxMqWP

**Comment by vitaut** [comment]
I think it would be problematic but if one formatter is generic you can reuse it from the other.

**Comment by iwubcode** [comment]
I guess there is no desire to support this?  My hope was this would be similar to the ostream implementation, include a header and you're done.

Duplicating the formatter implementation is not ideal.

Were you thinking of partially reusing the std formatter in each use case like this?

```
// custom object
struct Point {
	int x;
	int y;
};

// Defined next to the object, somewhere else
template <>
struct std::formatter<Point> : std::formatter<std::string> {
	auto format(const Point& p, format_context& ctx) {
		return formatter<string>::format(
			std::format("[{}, {}]", p.x, p.y), ctx);
	}
};

// fmt
template <>
struct fmt::formatter<Point>
{
	template <typename FormatParseContext>
	auto parse(FormatParseContext& pc)
	{
		// Ideal scenario would be to mimic the format options of the std impl
		return pc.end();
	}

	template <typename FormatContext>
	auto format(const Point& p, FormatContext& ctx) const -> decltype(ctx.out()) {
		return std::format_to(ctxt.out(), p);
	}
};

// now...
fmt::print("point = {}", Point(2, 3);
```

**Comment by vitaut** [comment]
Implicit ostream formatting has been deprecated and is disabled by default due to various problems some of which would apply here. However, you can create a formatter that works both with {fmt} and `std::format` and use it in specializations:

```c++
template <template <typename...> class F>
struct index_formatter : F<int> {
  template <typename FormatContext>
  auto format(const Index& id, FormatContext& ctx) {
    return F<int>::format(id.id_, ctx);
  }
};

template <> struct std::formatter<Index> : index_formatter<std::formatter> {};
template <> struct fmt::formatter<Index> : index_formatter<fmt::formatter> {};
```

**Comment by iwubcode** [comment]
I forgot ostream stuff was deprecated.  Nice idea for the generic formatter, thanks @vitaut !
