### ISSUE TITLE
Using old version of the Bootstrap code

### ISSUE THREAD

**Issue by GrzegorzSpryszynski-TomTom** [fmtlib/fmt#3277]
fmt library uses code from [Bootstrap](https://getbootstrap.com) project ([fmt](https://github.com/fmtlib/fmt)/[doc](https://github.com/fmtlib/fmt/tree/master/doc)/bootstrap/) and ([fmt](https://github.com/fmtlib/fmt)/[doc](https://github.com/fmtlib/fmt/tree/master/doc)/[_static](https://github.com/fmtlib/fmt/tree/master/doc/_static)/fonts/) to generate documentation.

The Bootstrap code is very old (version ~3, when the latest is 5+) and some vulnerability checker tools (eg. Black Duck) recognise that as an Operational Risk.

The suggestion is to check if it can be upgraded to latest version or replaced with something else.

**Comment by vitaut** [comment]
Thanks for the suggestion. Considering that bootstrap is only used for the documentation I don't think it matters but a PR to update it would be welcome.
