### ISSUE TITLE
Is there a timeline for the next stable version?

### ISSUE THREAD

**Issue by ckerr** [fmtlib/fmt#3278]
An application I contribute to ([Transmission](https://github.com/transmission/transmission)) is currently using fmt 9.1.0. A user has reported [an issue](https://github.com/transmission/transmission/issues/4543) when using Transmission + fmt 9.1.0, but also reports that [it's fixed post-9.1.0](https://github.com/transmission/transmission/issues/4543#issuecomment-1382420092).

This isn't a demand for a release or anything like that; just asking for information. Transmission 4 is in a beta cycle right now so if a fmt stable release is on the horizon, I'd probably wait on it before ending our beta cycle.

**Comment by vitaut** [comment]
The work on version 10 has just begun and it will take a couple of months until it's ready. We don't have plans for a minor/patch release at the moment but if there are some critical bug fixes we might consider doing it.

**Comment by ckerr** [comment]
OK, thanks for the info!
