### ISSUE TITLE
Formatting chrono: off by one day

### ISSUE THREAD

**Issue by michael-brade** [fmtlib/fmt#3280]
Hi, when trying to format a `std::chrono::time_point` or `std::chrono::sys_days`, the day is off by one. For instance, formatting `now()` will print tomorrow's date. Here is a little test case:
```
#include <fmt/core.h>
#include <fmt/chrono.h>
#include <chrono>

int main() {
  fmt::print(fmt::format("{:%F}", std::chrono::system_clock::now()));
}
```
You can try it [here](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:3,endLineNumber:6,positionColumn:3,positionLineNumber:6,selectionStartColumn:3,selectionStartLineNumber:6,startColumn:3,startLineNumber:6),source:'%23include+%3Cfmt/core.h%3E%0A%23include+%3Cfmt/chrono.h%3E%0A%23include+%3Cchrono%3E%0A%0Aint+main()+%7B%0A++fmt::print(fmt::format(%22%7B:%25F%7D%22,+std::chrono::system_clock::now()))%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g122,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:fmt,ver:trunk)),options:'-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+12.2+(Editor+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+12.2',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+12.2+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

I tried to use current master and fmt down to 8.1.1 with always the same result. Compiler is gcc 12.2 on linux.

**Comment by vitaut** [comment]
The output looks correct. Please note that the time is in UTC by default which may explain the observed difference. You can convert it to local time before printing.

**Comment by michael-brade** [comment]
I see what you mean, since I used `now()`. But you an also try this:
```
#include <chrono>
#include <iostream>

#include <fmt/core.h>
#include <fmt/chrono.h>

int main() {
  using namespace std::literals;
  std::chrono::sys_days date { 2022y / 05 / 18 };
  std::cout << fmt::format("{:%F}", date) << std::endl;
}
```
This prints 2022-05-17.

And that is when using this timezone:

Current default time zone: 'America/Los_Angeles'
Local time is now:      Tue Jan 24 00:29:45 PST 2023.
Universal Time is now:  Tue Jan 24 08:29:45 UTC 2023.

Is this as it should be? If so, what would be the correct, time-zone independent code? (I thought using just dates, not time, should work...

**Comment by michael-brade** [comment]
BTW: I saw `local_days` but neither the type nor the operator compiles for me...

**Comment by michael-brade** [comment]
Ok, found a solution for the date: 
```c++
static std::string toString(std::chrono::sys_days value)
{
  std::chrono::year_month_day ymd{ value };	// from UTC back to local time/date
  return fmt::format("{:04}-{:02}-{:02}", static_cast<int>(ymd.year()), static_cast<unsigned>(ymd.month()), static_cast<unsigned>(ymd.day()));
}
```
Next, I'll search for a way to get the local time.

**Comment by vitaut** [comment]
> Is this as it should be? If so, what would be the correct, time-zone independent code?

I was not able to repro the date discrepancy on the new example either. It prints "2022-05-18" on https://godbolt.org/z/vc5E8oq99.

**Comment by michael-brade** [comment]
Ah, in compiler explorer they are using UTC. So you need to try this code, for example:
```
#include <chrono>
#include <iostream>

#include <fmt/core.h>
#include <fmt/chrono.h>

#include <time.h>
#include <stdlib.h>

int main() {
  setenv("TZ", "Atlantic/Cape_Verde", 1);
  tzset();

  using namespace std::literals;
  std::chrono::sys_days date { 2022y / 05 / 18 };
  std::cout << fmt::format("{:%F %z}", date) << std::endl;
}
```
As you can see, even a UTC-1 is enough to trigger this.

**Comment by michael-brade** [comment]
> Next, I'll search for a way to get the local time.

Just for reference, this is the easiest way I found:

```c++
// tzoffset = local - utc
int tzoffset = fmt::localtime(tp).tm_hour - fmt::gmtime(tp).tm_hour;
```

**Comment by vitaut** [comment]
OK, I managed to repro the discrepancy in gmtime. Reopening.

**Comment by MarekKnapek** [comment]
> int tzoffset = fmt::localtime(tp).tm_hour - fmt::gmtime(tp).tm_hour;

This would probably not work with time zones that are not integer multiple of hour. Yes, there are timezones with half hour difference.

**Comment by vitaut** [comment]
{fmt} 10.1.1 gives the expected result. For example (https://godbolt.org/z/oj8hd8rzv):

```c++
#include <iostream>
#include <fmt/chrono.h>

#include <time.h>
#include <stdlib.h>

int main() {
  setenv("TZ", "Atlantic/Cape_Verde", 1);
  tzset();

  using namespace std::literals;
  std::chrono::sys_days date { 2022y / 05 / 18 };
  std::cout << fmt::format("{:%F %z}", date) << std::endl;
}
```
prints 
```
2022-05-18 +0000
```
