### ISSUE TITLE
fmt chrono fails for clock minimum value

### ISSUE THREAD

**Issue by m5k8** [fmtlib/fmt#3282]
[https://godbolt.org/z/GbbvMb3bE](https://godbolt.org/z/GbbvMb3bE)

        #include <iostream>
        #include <chrono>
        #include <fmt/format.h>
        #include <fmt/chrono.h>
        
        int main(void)
        {
            // OK:
            // auto t = std::chrono::system_clock::time_point::max();
            // failure:
            auto t = std::chrono::system_clock::time_point::min();
            fmt::print("{}\n", t);
            return 0;
        }

Result:

        terminate called after throwing an instance of 'fmt::v9::format_error'
          what():  duration is too small

Code in `chrono.h:2113` explicitly checks for one second above min() and fails for value= min(). For max(), works OK. Until recently, it worked fine for min(). This commit: https://github.com/fmtlib/fmt/commit/240b728d813b52a9b616b1060f8fb52837ddb0c1 added the offending code. I'm not sure about the intent of this test. I discovered the issue, because one of my tests started to fail. min() value seems to be legal value, albeit used not too often.

**Comment by vitaut** [comment]
This is essentially the same issue as discussed in https://github.com/fmtlib/fmt/pull/3261#issuecomment-1383230222 except that UB has been replaced with a runtime error. A PR to allow time point values close to min would be welcome. cc @ShawnZhong

**Comment by ardi-nugraha** [comment]
Hi, is this issue still open?  I want to take it as my first contribution :)

**Comment by vitaut** [comment]
It is still open and contributions are welcome!

**Comment by ardi-nugraha** [comment]
Thanks for your response. May I ask why it's necessary to return an error if the time duration is too small? Is it because of integer overflow?

**Comment by vitaut** [comment]
Formatting min value works as of https://github.com/fmtlib/fmt/commit/8e42eef4950feb5d2b76574a9cd2591dfaae2449. Note that it is not particularly meaningful, we format whatever `gmtime` returns.
