### ISSUE TITLE
MinGW link error

### ISSUE THREAD

**Issue by winseros** [fmtlib/fmt#3283]
Compiling a simple program:

```c++
#include <iostream>
//not a header-only mode!
#include <fmt/core.h>

int main() {
    std::cout << fmt::format("{} {} {}", "Hello", 111, "World");
    return 0;
}


```

Causes errors on Windows:

MinGW GCC 12:

```
[1/2] Building CXX object CMakeFiles/fmtproj.dir/main.cpp.obj
[2/2] Linking CXX executable fmtproj.exe
FAILED: fmtproj.exe 
cmd.exe /C "cd . && C:\msys64\mingw64\bin\c++.exe -g  CMakeFiles/fmtproj.dir/main.cpp.obj -o fmtproj.exe -Wl,--out-implib,libfmtproj.dll.a -Wl,--major-image-version,0,--minor-image-version,0  vcpkg_installed/x64-windows/debug/lib/fmtd.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cmd.exe /C "cd /D C:\fmtproj\cmake-build-debug-mingw-installed && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/fmtproj/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/fmtproj/cmake-build-debug-mingw-installed/fmtproj.exe -installedDir C:/fmtproj/cmake-build-debug-mingw-installed/vcpkg_installed/x64-windows/debug/bin -OutVariable out""
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/fmtproj.dir/main.cpp.obj: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v9::format<char const (&) [6], int, char const (&) [6]>(fmt::v9::basic_format_string<char, fmt::v9::type_identity<char const (&) [6]>::type, fmt::v9::type_identity<int>::type, fmt::v9::type_identity<char const (&) [6]>::type>, char const (&) [6], int&&, char const (&) [6])':
C:/fmtproj/cmake-build-debug-mingw-installed/vcpkg_installed/x64-windows/include/fmt/core.h:3206: undefined reference to `__imp__ZN3fmt2v97vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
collect2.exe: error: ld returned 1 exit status
```

MinGW Clang 15:

```
[1/2] Building CXX object CMakeFiles/fmtproj.dir/main.cpp.obj
[2/2] Linking CXX executable fmtproj.exe
FAILED: fmtproj.exe 
cmd.exe /C "cd . && C:\msys64\clang64\bin\clang++.exe -g  CMakeFiles/fmtproj.dir/main.cpp.obj -o fmtproj.exe -Wl,--out-implib,libfmtproj.dll.a -Wl,--major-image-version,0,--minor-image-version,0  vcpkg_installed/x64-windows/debug/lib/fmtd.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cmd.exe /C "cd /D C:\fmtproj\cmake-build-debug-mingw-clang-installed && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/fmtproj/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/fmtproj/cmake-build-debug-mingw-clang-installed/fmtproj.exe -installedDir C:/fmtproj/cmake-build-debug-mingw-clang-installed/vcpkg_installed/x64-windows/debug/bin -OutVariable out""
ld.lld: error: undefined symbol: __declspec(dllimport) fmt::v9::vformat(fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char>>)
>>> referenced by vcpkg_installed/x64-windows/include/fmt/core.h:3206
>>>               CMakeFiles/fmtproj.dir/main.cpp.obj:(main)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

<details>
<summary>CMakeLists.txt</summary>

```
cmake_minimum_required(VERSION 3.24)
project(fmtproj)

set(CMAKE_CXX_STANDARD 20)

find_package(fmt CONFIG REQUIRED)

add_executable(fmtproj main.cpp)
target_link_libraries(fmtproj PRIVATE fmt::fmt)
```

</details>

<details>
<summary>
vcpkg.json
</summary>

```json
{
  "name": "fmtproj",
  "version": "1.0.0",
  "builtin-baseline": "e69dd972ba64840955f46704ecce6241bf607c0f",
  "dependencies": [
    "fmt"
  ]
}
```
</details>

Switching to WSL and using Linux GCC/Clang versions makes the code compile without any issues.

**Comment by vitaut** [comment]
This looks like a build config issue and vcpkg version of {fmt} is supported elsewhere. You might check with vcpkg folks or build the library yourself, here's a working mingw config for reference: https://github.com/fmtlib/fmt/blob/master/.github/workflows/windows.yml#L74.

**Comment by xkungxfu** [comment]
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(input_device.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v8::format<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::type, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::type>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: undefined reference to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(input_device.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v8::format<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::type, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::type, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::type>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: undefined reference to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(recording_service_impl.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v8::format<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::type>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: undefined reference to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: undefined reference to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(recording_config.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v8::format<int&, int, int&, int&, int&>(fmt::v8::basic_format_string<char, fmt::v8::type_identity<int&>::type, fmt::v8::type_identity<int>::type, fmt::v8::type_identity<int&>::type, fmt::v8::type_identity<int&>::type, fmt::v8::type_identity<int&>::type>, int&, int&&, int&, int&, int&)':
I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: undefined reference to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(device_context.cpp.obj):I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: more undefined references to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE' follow
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(device_service_windows.cpp.obj):device_service_windows.cpp:(.rdata$.refptr.CLSID_AudioInputDeviceCategory[.refptr.CLSID_AudioInputDeviceCategory]+0x0): undefined reference to `CLSID_AudioInputDeviceCategory'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(device_service_windows.cpp.obj):device_service_windows.cpp:(.rdata$.refptr.CLSID_VideoInputDeviceCategory[.refptr.CLSID_VideoInputDeviceCategory]+0x0): undefined reference to `CLSID_VideoInputDeviceCategory'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(device_service_windows.cpp.obj):device_service_windows.cpp:(.rdata$.refptr.CLSID_SystemDeviceEnum[.refptr.CLSID_SystemDeviceEnum]+0x0): undefined reference to `CLSID_SystemDeviceEnum'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by xkungxfu** [comment]
```

H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(input_device.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v8::format<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::type, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::type>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: undefined reference to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(input_device.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v8::format<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::type, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::type, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::type>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: undefined reference to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(recording_service_impl.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v8::format<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::type>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: undefined reference to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: undefined reference to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(recording_config.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v8::format<int&, int, int&, int&, int&>(fmt::v8::basic_format_string<char, fmt::v8::type_identity<int&>::type, fmt::v8::type_identity<int>::type, fmt::v8::type_identity<int&>::type, fmt::v8::type_identity<int&>::type, fmt::v8::type_identity<int&>::type>, int&, int&&, int&, int&, int&)':
I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: undefined reference to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(device_context.cpp.obj):I:/CXXTools/vcpkg/vcpkg-2023.06.20/packages/fmt_x64-windows/include/fmt/core.h:3119: more undefined references to `__imp__ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE' follow
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(device_service_windows.cpp.obj):device_service_windows.cpp:(.rdata$.refptr.CLSID_AudioInputDeviceCategory[.refptr.CLSID_AudioInputDeviceCategory]+0x0): undefined reference to `CLSID_AudioInputDeviceCategory'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(device_service_windows.cpp.obj):device_service_windows.cpp:(.rdata$.refptr.CLSID_VideoInputDeviceCategory[.refptr.CLSID_VideoInputDeviceCategory]+0x0): undefined reference to `CLSID_VideoInputDeviceCategory'
H:/CXXTools/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: screen-recorder/libscreen_recorder.a(device_service_windows.cpp.obj):device_service_windows.cpp:(.rdata$.refptr.CLSID_SystemDeviceEnum[.refptr.CLSID_SystemDeviceEnum]+0x0): undefined reference to `CLSID_SystemDeviceEnum'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by 384520505** [comment]
Change the fmt::fmt in CMakeLists.txt to fmt::fmt-header-only, and that should do the job

`target_link_libraries(HelloWorld PRIVATE fmt::fmt-header-only)`
