### ISSUE TITLE
Extra characters printed when formatting invalid UTF-8 with precision

### ISSUE THREAD

**Issue by lriesterer** [fmtlib/fmt#3284]
Formatting using string precision fails when there are non-ascii characters.

Here is a code to reproduce (first line works as expected, second doesn't as there is an extra "diamond-shaped" character printed):
```
#include <fmt/format.h>
int main()
{
    fmt::print(">>{:.6}<<\n", "1234567");
    fmt::print(">>{:.6}<<\n", "123456\xad");
    return 0;
}
```

https://godbolt.org/z/zzY4Y4Pec

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/c13753a70cc55f3b1c99fb8f8395e78e5f9cae43. Thanks for reporting!
