### ISSUE TITLE
Feature request: Escaped string

### ISSUE THREAD

**Issue by BenFrantzDale** [fmtlib/fmt#3285]
I keep finding myself wanting to directly write files like json, where if I do `fmt::format(\"{{\"{}\": \"{}\"}}", key, value)`, it appears to work until key or value has a quote in it. The solution I've come up with is as follows, but it feels like something that should come batteries-included:
https://godbolt.org/z/K4Ys6Ebv5
```c++
#include <fmt/format.h>

namespace detail {
//! A wrapper holding a view that should be escaped when output.
template <typename StringView = std::string_view>
struct ViewToEscape {
    // Data is just a string view and the character for a quote and for escaping.

    StringView sv;
    typename StringView::value_type quote = '"';
    typename StringView::value_type esc = '\\';

    using CharType = typename StringView::value_type;

    //! Copy to an output iterator: Quotes and escapes need escaping:
    template <typename OutCharIter>
    OutCharIter copy(OutCharIter out) const {
        *out++ = this->quote; // Start with a quote.
        auto needsEscaping = [this](CharType c) { return c == this->quote || c == this->esc; };
        for (CharType c : this->sv) {
            if (needsEscaping(c)) {
                *out++ = this->esc;
            }
            *out++ = c;
        }
        *out++ = this->quote; // Final quote.
        return out;
    }
};

} // namespace detail

//! "ViewToEscape" is a handle to allow special-cased formatting using fmt::formatter<ViewToEscape<StringView>>.
//! It places double-quotes around the string and escapes double-quotes and backslashes with a backslash, ala repr(s) in
//! Python. This is performed without allocations by using a view rather than escape(std::string) -> std::string.
template <typename StringView>
struct fmt::formatter<::detail::ViewToEscape<StringView>> {
    using V = ::detail::ViewToEscape<StringView>;

    template <typename ParseContext>
    constexpr auto parse(ParseContext& ctx) {
        return ctx.begin();
    }

    template <typename FormatContext>
    auto format(::detail::ViewToEscape<StringView> const& s, FormatContext& ctx) {
        return s.copy(ctx.out());
    }
};

//! "escaped" returns a formatable view of the string-view that escapes quotes and backslashes.
[[nodiscard]] inline constexpr detail::ViewToEscape<std::string_view> escaped(std::string_view sv,
                                                                              char q = '"',
                                                                              char e = '\\') {
    return detail::ViewToEscape<std::string_view>{sv, q, e};
}


int main() {
    fmt::print("Yikes!: {{{}: {}}}\n", "foo \" bar", "bar\\baz");
    fmt::print("Nice!: {{{}: {}}}\n", escaped("foo \" bar"), escaped("bar\\baz"));
}
```
prints:
```
Yikes!: {foo " bar: bar\baz}
Nice!: {"foo \" bar": "bar\\baz"}
```

Again, this seems very useful, but maybe there's a more fmt-idiomatic way to do it?

**Comment by vitaut** [comment]
Escaping is supported with the `?` specifier. For example

```c++
#include <fmt/core.h>

int main() {
  fmt::print("{{{:?}: {:?}}}\n", "foo \" bar", "bar\\baz");
}
```

prints

```
{"foo \" bar": "bar\\baz"}
```

**Comment by BenFrantzDale** [comment]
Sure enough! Thanks! https://godbolt.org/z/5dcde4rnh

Is this documented? I don't see "?" on https://fmt.dev/latest/syntax.html

**Comment by vitaut** [comment]
It is a new specifier that hasn't been documented yet. A PR to add it to the docs would be welcome.

**Comment by BenFrantzDale** [comment]
> It is a new specifier that hasn't been documented yet. A PR to add it to the docs would be welcome.

Exciting! When I dabbled in Rust for Advent of Code 2022, I found I like the `?` specifier. Do you intend for `?` to be a "debug" stringification ala Rust's and Python's `__repr__`, or do you intend it to be "escaped strings". On Godbolt it appears to only support strings right now... I'd love a general way to make my types debug-printable while not worrying about whether they should generally be stringifiable for production...

**Comment by BenFrantzDale** [comment]
> It is a new specifier that hasn't been documented yet. A PR to add it to the docs would be welcome.

Exciting! When I dabbled in Rust for Advent of Code 2022, I found I like the `?` specifier. Do you intend for `?` to be a "debug" stringification ala Rust's and Python's `__repr__`, or do you intend it to be "escaped strings". On Godbolt it appears to only support strings right now... I'd love a general way to make my types debug-printable while not worrying about whether they should generally be stringifiable for production...

**Comment by vitaut** [comment]
It can be used in other places where debug is different from the default.
