### ISSUE TITLE
chrono.h: warning C4819: The file contains a character that cannot be represented

### ISSUE THREAD

**Issue by felixdollack** [fmtlib/fmt#3289]
fmt-src\include\fmt/chrono.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss

The Japanese Kanji characters in this comment break the build for me on Windows 11 with MCVS 17.4.1 2022 Community Edition:

https://github.com/fmtlib/fmt/blob/a2c05a10ec875712bfee739a05ed99fc3915f4e9/include/fmt/chrono.h#L663

I guess other people don&t have this issue since the line exists since 4 years.
Any guess as to why this could be happening?

**Comment by vitaut** [comment]
{fmt} headers are stored in UTF-8. You might need to communicate this to your compiler or ignore/suppress the warning which is meaningless anyway since the character in question is in a comment.

**Comment by felixdollack** [comment]
Thank you for the hint @vitaut.

For anyone who might have the same problem in the future,
add `/utf-8` to your compiler options in Visual Studio or to your cmake file
```
add_compile_options("$<$<C_COMPILER_ID:MSVC>:/utf-8>")
add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
``` 
https://developercommunity.visualstudio.com/t/warning-c4819-to-file-saved-in-utf-8-encoding/176752#T-N1092308
