### ISSUE TITLE
Test of FormatIntLocale fails on Fedora 24

### ISSUE THREAD

**Issue by daveisfera** [fmtlib/fmt#329]
Fedora 24 and Fedora Rawhide (25) were recently updated to gcc 6.1.1 and all of the tests pass on Fedora Rawhide but the test of FormatIntLocale fails on Fedora 24. Here's the verbose test output of the failure:

    3: [ RUN      ] FormatterTest.FormatIntLocale
    3: /builddir/build/BUILD/fmt-3.0.0/test/format-test.cc:1218: Failure
    3: Value of: format("{:n}", 1234567)
    3:   Actual: "1234567"
    3: Expected: "1,234,567"
    3: [  FAILED  ] FormatterTest.FormatIntLocale (0 ms)

What can I do to help find the source of this issue?
Thanks,
Dave

**Comment by vitaut** [comment]
Thanks for another bug report. Is `en_US.utf-8` in the list of locales as printed by the `locale -a` command? If not, what is the list of locales returned by this command?

**Comment by daveisfera** [comment]
`en_US.utf-8` show up (with a lot of other entries) in F23 and F25, but here's the output from running `locale -a` on F24:

    locale: Cannot set LC_CTYPE to default locale: No such file or directory
    locale: Cannot set LC_MESSAGES to default locale: No such file or directory
    locale: Cannot set LC_COLLATE to default locale: No such file or directory
    C
    C.utf8
    POSIX
    zu_ZA
    zu_ZA.utf8

It sounds like this is a bug with Fedora 24 and not really with `fmt`. Any ideas on what the offending package is?

**Comment by vitaut** [comment]
I am not sure what's up with locales on F24, but it's probably a good idea to make `FormatIntLocale` more robust anyway as there is no guarantee that `en_US.utf-8` is installed. Should be fixed in https://github.com/fmtlib/fmt/commit/5b106083e79b0f6c2f3850fa1c0ac0a69b81e595.

**Comment by vitaut** [comment]
Also as of https://github.com/fmtlib/fmt/commit/e2a332e5df1783580c42f62eb7f4bef04d8000b2, the test uses a mock instead of relying on system locales.
