### ISSUE TITLE
Is it possible to build fmt while RTTI compile flag is off?

### ISSUE THREAD

**Issue by T-rvw** [fmtlib/fmt#3291]
In current codebase, `dynamic_cast` will be used in fmt : https://github.com/fmtlib/fmt/blob/cae9bf45b964655c240f1fac23d5df30c54add15/include/fmt/ostream.h#L82

**Comment by vitaut** [comment]
ostream interface is optional so you might be able to do this if you don't use iostreams with {fmt}.
