### ISSUE TITLE
compilation error with filesystem path in tuple and join (msvc)

### ISSUE THREAD

**Issue by reder2000** [fmtlib/fmt#3298]
Hi, I have a strange compiler error when printing a path in a tuple with join.
The error does not occur if I format the path somewhere before (so I have a workaround)
This error pops up for msvc, msvc-clang and weirdly for  msys2-mingw64, but not for linux-gcc.
Here's a link [goldbolt](https://godbolt.org/z/3z78s5jP7)

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/e0748e61ddc0cbef840596bf9748199a2197e613. Thanks for reporting.

**Comment by reder2000** [comment]
Thanks for fixing it. Looking at the fix, this is arcane!
