### ISSUE TITLE
Add support for feeding arguments separately to specification of the format string

### ISSUE THREAD

**Issue by skebanga** [fmtlib/fmt#330]
[`boost::format`](http://www.boost.org/doc/libs/1_61_0/libs/format/index.html) allows you to feed arguments using `operator%`.

> A format object is constructed from a format-string, and is then given arguments through repeated calls to operator%.
> Each of those arguments are then converted to strings, who are in turn combined into one string, according to the format-string.

Is this possible with `fmt`?

## Example:

```
#include <iostream>
#include <boost/format.hpp>

int main()
{
    // specify the format string
    boost::format formatter("You can feed arguments like this: %d %d %d %d");

    // feed arguments later
    for (int i = 0; i < 4; ++i)
        formatter % i;

    std::cout << formatter.str() << '\n';

    return 0;
}
```

**Comment by vitaut** [comment]
Feeding arguments separately is not supported and I don't see an efficient way to do this (see also #184). However, it is possible to achieve similar effect with the [write API](http://fmtlib.net/latest/api.html#write-api):

```c++
#include "fmt/format.h"
#include <iostream>

int main() {
  fmt::Writer writer;
  writer << "You can feed arguments like this:";
  for (int i = 0; i < 4; ++i)
    writer << ' ' << i;
  std::cout << writer.str() << '\n';
}
```

You won't be able to use positional arguments, of course, but [you can use format strings](http://fmtlib.net/latest/api.html#_CPPv2N3fmt11BasicWriter5writeE15BasicCStringRefI4CharE7ArgList) for individual arguments.

**Comment by skebanga** [comment]
Our internal logging implementation uses printf style formatting

```
LOG_INFO("You can feed arguments like this: %d %d %d %d", 0, 1, 2, 3);
```

At the call site we obtain an `Args` object from a lock-free queue, and store each argument in a union,  together with the format string.

```
class Args
{
public:
    template<typename... Ts>
    void set(const char* fmt, Ts...);

    std::string str() const;
private:
    union ArgT
    {
        const double   d;
        const uint64_t u;
        const int64_t  i;
        const void*    p;
    };
    static_assert(sizeof(ArgT) == 8, "unexpected size");

    using Pool      = mem::Pool<96>;
    using Allocator = Pool::Allocator<ArgT>;
    using ArgVector = std::vector<Allocator::value_type, Allocator>;

    Pool        _pool;
    const char* _fmt;
    ArgVector   _args;
};
```

A background logging thread then pops these `Args` objects off the queue, creates a `boost::format` object with the format string, and then parses the format string to find the type of each argument, and feeds each argument from the relevant union member.

```
std::string Args::str() const
{
    boost::format formatter(_fmt);

    bool modifier = false;
    auto it = _args.begin();
    for (const char* fmt = _fmt; *fmt; ++fmt)
    {
        ...
            switch (*fmt)
            {
                ...
                case 'c': // char
                case 'C':
                    formatter % char(it->i);
                    ++it;
                    break;
                case 'd': // integer
                case 'i':
                    formatter % it->i;
                    ++it;
                    break;
                ...
            }
        }
    }
    return formatter.str();
}
```

We've found this is the fastest way to log on the critical path, as all it involves is copying fundamental types, and the occasional deep copy of a string argument.

We have an optimization for "static strings" where we know the lifetime of the string will outlast the logging of it, so in this instance we only shallow copy the `const char*` pointer, rather than making a deep copy. 99% of all strings we log are static strings.

The only issue is that `boost::format` is **very** slow, so on occasion it is possible for producing threads to fill up their queues, as the logging thread can't consume them fast enough.

This only really happens in exceptional circumstances, but it can happen.

Anyway, just thought I'd share the motivation behind the request.

**Comment by vitaut** [comment]
In this case you can convert arguments stored in `Args` into `fmt::ArgList` and pass it to `fmt::printf` or similar which accepts printf-like format strings. The API for building `fmt::ArgList` is not pretty as it is designed for efficiency. As in Args`, primitive types are copied while strings and user-defined arguments are stored by reference.

Here's a little example showing how to construct an argument list dynamically:

```c++
  enum {NUM_ARGS = 2};
  typedef fmt::internal::ArgArray<2> ArgArray;
  typename ArgArray::Type array;
  array[0] = ArgArray::template make<fmt::BasicFormatter<char> >(42);
  array[1] = ArgArray::template make<fmt::BasicFormatter<char> >(43);
  fmt::ArgList args(fmt::internal::make_type(42, 43), array);
  fmt::printf("%d %d", args);
```

**Comment by skebanga** [comment]
Thanks for the reply - I'll check it out!

**Comment by Mark-Joy** [comment]
Hello @vitaut ,

How to construct an argument list dynamically in the below situation?

```
typedef fmt::internal::ArgArray<ArgList::MAX_PACKED_ARGS - 1> ArgArray;
// va is a vector of objects
for (auto v : va)
{
	obj = v;
	if (obj.get_type() == sol::type::number)
	{
		array[i] = ArgArray::template make<fmt::BasicFormatter<char> >((double)v);
	}
	else if (obj.get_type() == sol::type::boolean)
	{
		array[i] = ArgArray::template make<fmt::BasicFormatter<char> >((bool)v);
	}
	else if (obj.get_type() == sol::type::string)
	{
		string strtemp = v;
		array[i] = ArgArray::template make<fmt::BasicFormatter<char> >(strtemp);
	}
	++i;
}
fmt::ArgList args(fmt::internal::make_type(???????), array);
```

Thank you!

**Comment by vitaut** [comment]
You won't be able to use variadic overload of make_type, but you can
probably use a single-argument overload and combine the return values using
bitwise OR as it is done here:
https://github.com/fmtlib/fmt/blob/master/fmt/format.h#L2166

Note that this won't work:

        string strtemp = v;
        array[i] = ArgArray::template make<fmt::BasicFormatter<char> >(strtemp);

because it stores a pointer to a string strtemp which is immediately
destroyed.

HTH,
Victor

**Comment by Mark-Joy** [comment]
Thank you!!
I am able to make it work with below code:

```
typedef fmt::internal::ArgArray<ArgList::MAX_PACKED_ARGS - 1> ArgArray;
typename ArgArray::Type array;
uint64_t ArgArrayType = 0;
vector<shared_ptr<string>> vstr(ArgList::MAX_PACKED_ARGS);
int ivstr = 0;

for (auto v : va)
{
	obj = v;
	if (obj.get_type() == sol::type::number)
	{
		array[i] = ArgArray::template make<fmt::BasicFormatter<char> >((double)v);
		ArgArrayType = ArgArrayType | (fmt::internal::make_type(1.0) << (i * 4));
	}
	else if (obj.get_type() == sol::type::boolean)
	{
		array[i] = ArgArray::template make<fmt::BasicFormatter<char> >((bool)v);
		ArgArrayType = ArgArrayType | (fmt::internal::make_type(false) << (i * 4));
	}
	else if (obj.get_type() == sol::type::string)
	{
		vstr[ivstr] = make_shared<string>(va.get<string>(i));
		array[i] = ArgArray::template make<fmt::BasicFormatter<char> >(*vstr[ivstr++]);
		ArgArrayType = ArgArrayType | (fmt::internal::make_type(" ") << (i * 4));
	}
	++i;
}
```

**Comment by Mark-Joy** [comment]
Hello @vitaut ,
Since I have to construct the `ArgList `manually, I got some unwanted behaviors due to the check and assignment of `use_values` 

Can I propose the below changes to fix the errors and still keep the correctness of current code?
1> in `format.h` from
````javascript
ArgList(ULongLong types, const internal::Value *values)
  : types_(types), values_(values) {}
  ArgList(ULongLong types, const internal::Arg *args)
  : types_(types), args_(args) {}
...
...
bool use_values = type(MAX_PACKED_ARGS - 1) == Arg::NONE;
```` 
to
````javascript
bool use_values; 
ArgList(ULongLong types, const internal::Value *values)
  : types_(types), values_(values), use_values(true){}
  ArgList(ULongLong types, const internal::Arg *args)
	  : types_(types), args_(args), use_values(false) {}
````
2> and in `format.cc` from
````javascript
bool use_values = args.type(ArgList::MAX_PACKED_ARGS - 1) == internal::Arg::NONE;
if (use_values) {
...
}
````
to
```javascript
if (args.use_values) {
...
}
````

**Comment by vitaut** [comment]
`ArgList` is designed to be as small as possible to avoid unnecessary overhead compared to `printf`, so adding another member is undesirable.

**Comment by Mark-Joy** [comment]
Isnt it the same size? we already had the use_values variable, nothing is added

**Comment by vitaut** [comment]
Then I probably misunderstood your proposal. Are you not suggesting to make `use_values` a member variable?

**Comment by Mark-Joy** [comment]
But we remove the old `use_values` variable hence code size is same. I tried compiling in 2 cases, and still no change in my code size.

**Comment by vitaut** [comment]
The difference is that `ArgList` is constructed on the caller side and there are normally more callers than formatters. Besides `use_values` is redundant because it's value is determined by the value of `types_`. What exactly is the problem that you want to solve with this?

**Comment by Mark-Joy** [comment]
````javascript
#define MAX_ARGS 20
typedef fmt::internal::ArgArray<MAX_ARGS> ArgArray;
typename ArgArray::Type array;
uint64_t ArgArrayType = 0;
....
````

I used `for loop` to construct the `ArgList`, the ArgList may have less than 15 member depends on the loop.
When it has less than 15, everything is going wrong way. `ArgList` save values in `internal::Arg` but read the values in `internal::Value`.
It took me a while to check the code and realized that I have to set the arg_type(15) to a number different than Arg::NONE.

If my MAX_ARGS less than or equal 15, I have to be carefull not to set the arg_type(15) to any other value than than Arg::NONE.
That's quite confusing

**Comment by vitaut** [comment]
When the number of arguments is less than `MAX_PACKED_ARGS`, `ArgList` stores arguments in the `values` array. Don't try setting `arg_type(15)` to something other than `Arg::NONE` because this will break the logic in `ArgList`. If you assign `Arg` to `Value` it will just slice off the unnecessary type information which is fine, because for packed arguments the type information is stored separately.

**Comment by katnellayappan** [comment]
Hi,

In fmt library version 5.1.0 and above, ArgList has been removed. What is the best way to get similar functionality in fmt v5.x? I see that format_arg_store has been added but not sure how one can dynamically add Arg elements into it.

Thanks
-Kat
