### ISSUE TITLE
M1 pro macbook can not catch the fmt::format_error

### ISSUE THREAD

**Issue by wendajiang** [fmtlib/fmt#3300]
When I use the vformat/vprint and the code likely

```
#include <fmt/core.h>
#include <fmt/args.h>
#include <fmt/format.h>
#include <iostream>

int main() {
    std::string format = "hello world, {} {}";
    fmt::dynamic_format_arg_store<fmt::format_context> store;
    int a = 4;
    store.push_back(4);

    try {
        fmt::vprint(format, store);
    } catch(fmt::format_error &e) {
        std::cerr << "some error: " << e.what() << std::endl;
    }
    
    return 0;
}
```
The godbolt link is https://godbolt.org/z/jf636Mreo, and the behavior is right.

But on my m1 pro macbook, the code not catch fmt::format_error exception, I only use catch(...) to catch all exception.

**Comment by vitaut** [comment]
Please provide more details, in particular what exception is being thrown instead of `format_error` and the stack trace.

**Comment by wendajiang** [comment]
Strangely, throwed exception is 
<img width="686" alt="image" src="https://user-images.githubusercontent.com/13445879/218003965-024896f7-526a-4032-b7d3-9243b697d955.png">

And the stack is 
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/13445879/218004056-c7e4d24c-7c33-46ae-bdaa-6d8ff271793a.png">

**Comment by phprus** [comment]
MacBook Pro M1 Max:

```
phprus@mbp fmt % uname -a
Darwin mbp 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 arm64

phprus@mbp fmt % clang++ -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

phprus@mbp fmt % clang++ -I/path/to/fmt/include /path/to/fmt/build/libfmt.a -std=c++20 1.cpp

phprus@mbp fmt % ./a.out
some error: argument not found
```

and ``c++17``, ``c++14``

**Comment by wendajiang** [comment]
Yes, I use the clang++/g++-12 manually compile, and the result is right. But default in the Clion, and run directly, the exception happen. Maybe I should close this issue and check the Clion configuration.
