### ISSUE TITLE
fmt::print references uninitialized stack memory on windows when passing constexpr param

### ISSUE THREAD

**Issue by Ch40zz** [fmtlib/fmt#3310]
Hi, I recently hit this weird bug and I wasn't exactly sure if it was a compiler bug, an STL bug or a bug in fmt.
When using `fmt::print` to print a constexpr/consteval string param, the generated code references unintiailized stack memory: https://godbolt.org/z/ojfKssWvM (EDIT: Found an even shorter repro: https://godbolt.org/z/GaxqM6Wo8)
This has been tested with msvc and clang on windows. Clang on linux works just fine which hints to a problem with MS STL.
It could however also be an issue with how an STL function is used within the library.
Screenshot in case godbolt link is down:

![godbolt repro](https://i.imgur.com/HWV6H2R.png)

**Comment by vitaut** [comment]
This doesn't look like a bug in {fmt} because we cannot distinguish a string returned from a `consteval` function from a string literal and the latter obviously works. I recommend reporting to Microsoft.

**Comment by user-45-20** [comment]
Hey, just FYI - this is indeed not an fmt problem, I found a repro of this issue that doesn't use fmt at all and reported it at https://developercommunity.visualstudio.com/t/Invalid-code-generation---consteval-func/10312598
