### ISSUE TITLE
How to preserve trailing 0 when formatting scientific notation number.

### ISSUE THREAD

**Issue by twinkles-twinstar** [fmtlib/fmt#3315]
I expect to format a float and always include the decimal point with a trailing 0 when it is an integer. For example like this:
```
A1: 4 -> 4.0
A2: 4e+100 -> 4.0e+100
B1: 4.123+100 -> 4.123+100
B2: 4.123 -> 4.123
```

I use `"{#g}"` for formatting, A1, B1, B2 are all as I want, but the output of A2 is `4.e+100`, is there any way to append a `0` between `4.` and `e` ?

**Comment by twinkles-twinstar** [comment]
I tried modifying the `do_write_float` function in `format.h` so that the output of `4e+100` changed from `4.e+100` to `4.0e+100`, but I didn't know much about the project and didn't know if doing so would introduce any bugs.

```cpp
if (use_exp_format()) {
    int num_zeros = 0;
    if (fspecs.showpoint) {
      num_zeros = fspecs.precision - significand_size;
      if (num_zeros < 0) num_zeros = 0;
      if (num_zeros == 0 && significand_size == 1) num_zeros = 1; // here is my code
```

**Comment by vitaut** [comment]
The output of A2 is "4.00000e+100" because `g` uses the precision of 6 by default. There is no built-in way of getting the format you want, you'd need to find out the magnitude and specify the precision yourself, e.g. 

```c++
fmt::print("{:#.2g}", 4e+100);
```
Or you could massage the output and insert `0` after `.` if needed.

**Comment by twinkles-twinstar** [comment]
My typo, I was using `"{#}"` instead of `"{#g}"` .
My confusion is, `Normally, a decimal-point character appears in the result of these conversions only if a digit follows it.` .
When using the alt flag, fmt will add a decimal point and a trailing 0 to floating point strings in fixed format, but if the output is in exponent notation format, fmt will add a decimal point but not output a trailing 0.
This may seem odd, why not make the exponent notation format's alt mode behavior consistent with the fixed format?

**Comment by vitaut** [comment]
We should be consistent with `std::format` which doesn't currently say that `#` should add any digits after `.`: http://eel.is/c++draft/format#string.std-6. So we could either make the fixed format not add `0` after `.` or submit an LWG issue asking to clarify whether `0` should be added or not.

**Comment by vitaut** [comment]
Fixed the issue in https://github.com/fmtlib/fmt/commit/98699719f85445e0ab4a962c0b1a2a0218289814. It doesn't help in your case but at least we now follow the `std::format` spec plus fixed and exponential representations are consistent.
