### ISSUE TITLE
C++20 Consteval compilation fail

### ISSUE THREAD

**Issue by Gregofi** [fmtlib/fmt#3316]
Hi, the following doesn't work on gcc 12 c++20. Probably something with constevalness,
see https://godbolt.org/z/ehEeraEde. If you instead call `print("Hello, {}", argv[0])` it works.
The same problem appears to be on newest version on clang also.

Seems like gcc11 also has problem with it, although gcc10 works fine: https://godbolt.org/z/zode7K5aa

**Comment by vitaut** [comment]
The problem is that you are passing arguments by a forwarding references but don't actually forward them. To fix add the missing `std::forward` (https://godbolt.org/z/bWjcdWxh8):

```c++
template<typename... Args>
inline void print(fmt::format_string<Args...> format_str, Args&& ...args) {
    fmt::print(stderr, format_str, std::forward<Args>(args)...);
}
```
