### ISSUE TITLE
ostream support is broken

### ISSUE THREAD

**Issue by adah1972** [fmtlib/fmt#3318]
Given this test code:

```cpp
#include <vector>
#include <fmt/core.h>
#include <fmt/ostream.h>

using namespace std;

std::ostream& operator<<(std::ostream& os, const std::vector<int>& v)
{
    for (int n : v) {
        os << n << ' ';
    }
    return os;
}

int main()
{
    vector<int> v{1, 2, 3};
    fmt::print(stdout, "{}\n", v);
}
```

It works with GCC 9/10/11 (both C++17 and C++20/C++2a modes) and fmt v8.1.1 (as well as many earlier versions).

From fmt v9.0.0 (up to head in master), the code above always fail.

Also, even with fmt v8.1.1, I am not able to make it work with GCC 12 or Clang.

**Comment by vitaut** [comment]
There were multiple problems with automatic ostream insertion operator discovery and it was disabled in v9. Please see the docs on how to provide an explicit ostream-based formatter: https://fmt.dev/latest/api.html#ostream-api. Note that you shouldn't normally overload `operator<<` or provide a `formatter` for types you don't own such as `std::vector<int>`.

**Comment by adah1972** [comment]
`vector` is just an example: I actually used to use [a range stream outputter](https://github.com/adah1972/output_range), which worked with older versions of fmt for years.

Still glad to know that there is a solution (and the fmt/ranges.h option, which I had missed so far). Thanks.

**Comment by harryjwright** [comment]
This is the biggest issue with this library I have found. When everyone is so used overloading the `<<` operator, why not focus on support for that out of the box? It doesn't make any sense.
