### ISSUE TITLE
How to use from C? Is it possible?

### ISSUE THREAD

**Issue by plajjan** [fmtlib/fmt#3320]
Hi, I would like to use the fmt library from C. On the frontpage it's declared how fmt is `{fmt} is an open-source formatting library providing a fast and safe alternative to C stdio and C++ iostreams.`. Is it really a replacement to C stdio so that I can call it from arbitrary C code, or is this quote more playing on functinoality similar to C stdio?

How can I use fmt from C?

**Comment by plajjan** [comment]
I'm rather familiar with C but don't have much exposure to C++ and no experience whatsoever in mixed C / C++ projects and have no idea how that is supposed to work. I just don't know what to expect from the fmt library here, like am I supposed to be able to call it from C? If not, then why does it say it's a safe alternative to C stdio? Shouldn't there be at least one usage example of how to call it from C if that is possible?

**Comment by vitaut** [comment]
{fmt} doesn't provide a C API at least because C lacks facilities to implement such API in a type-safe way. It is a safe alternative to stdio in C++ but since this is a C++ library the latter part is implied.

**Comment by plajjan** [comment]
Ok, thanks for the clarification!
