### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by icls1337** [fmtlib/fmt#3327]
I saw a comparison between fast_io and fmt before but couldn't find it since, I just remember discussing it with vitaut.

**Comment by vitaut** [comment]
I did some tests a while ago: https://gist.github.com/vitaut/7ec12070347e4f4ee3f70d64950f7a10.

**Comment by vitaut** [comment]
> I remember there was also a discussion with the author?

Mostly nonsensical comments. We had to ban him for spamming the project and they seemed to refocus on spamming the Rust community.
