### ISSUE TITLE
Cannot use std::forward<Args> anymore for VS2020 in the case of wstring 

### ISSUE THREAD

**Issue by shashigowdak** [fmtlib/fmt#3329]
fmt::format for wstring is not working in VS 2020. Below code used to work in VS 2019   

        template <typename... Args>
        void Trace(std::wstring_view theMessage, Args&&... theVariables)
        {
            std::wstring_view formattedMessage = fmt::format(theMessage, std::forward<Args>(theVariables)...);
        }
the error is
error C2039: 'parse': is not a member of 'fmt::v9::detail::fallback_formatter<value_type,wchar_t,void>'

However, it works fine without <T> variadic args 
std::wstring_view formattedMessage = fmt::format(L"Message {}", 10);

I want to pass variadic args to fmt::format as in the first example. Please suggest

Thanks

**Comment by vitaut** [comment]
I don't think it is related to `forward`. In C++20 the format string needs to be known at compile time so you should pass `fmt::wformat_string<Args...>` instead of `wstring_view`: https://godbolt.org/z/PY7d5bn4n.

**Comment by shashigowdak** [comment]
Thank you. I am sorry for the wrong message earlier. Actually, the issue is in my client code. I am passing std::string for variadic args

Format(L"Can it work {} {}", "MayBe", true);

This one is failing with "error C2039: parse.." and it expects wstring like L"MayBe". 

Thanks again!
