### ISSUE TITLE
ErrInfo:error: too few arguments to function ‘unsigned char fmt::v9::detail::format_as(std::byte)

### ISSUE THREAD

**Issue by wangjun92** [fmtlib/fmt#3330]
Errinfo:
/usr/local/include/spdlog/fmt/bundled/core.h:1334:56: error: too few arguments to function ‘unsigned char fmt::v9::detail::format_as(std::byte)’ 1334 |   template <typename U, typename V = decltype(format_as(U())),

My Question:
when I compile my projects with 【SET(CMAKE_CXX_STANDARD 17)】 in my CMakeLists.txt，getting the error befor。
“ decltype(format_as(U())) ” changed to "decltype(format_as(std::declval()()))" works good.

Do we need to consider the compatibility to c++17 standard？

**Comment by vitaut** [comment]
Please provide a godbolt repro.

**Comment by vitaut** [comment]
I wasn't able to repro the issue: https://godbolt.org/z/45MsTaqsG. Closing for now but feel free to reopen with repro details.

**Comment by Lord-Kamina** [comment]
Hi. I think I found at least one case where this is reproduced... if cpprestsdk is installed, there's a clash with their godforsaken `U()` macro.

**Comment by hhxdestiny** [comment]
> Hi. I think I found at least one case where this is reproduced... if cpprestsdk is installed, there's a clash with their godforsaken `U()` macro.

@Lord-Kamina @vitaut  +1

**Comment by bansalnvn** [comment]
@Lord-Kamina did you find a workaround as well ?

**Comment by Lord-Kamina** [comment]
There is a define for cpprest that turns off that macro,`_TURN_OFF_PLATFORM_STRING` and of course you gotta replace any calls to it.

**Comment by SirPustekuchen** [comment]
You can undef the macro 'U' around every include of spdlog/... in your project, e.g.
```
#pragma push_macro("U")
#undef U
#include <spdlog/logger.h>
#pragma pop_macro("U")
```
