### ISSUE TITLE
Formatting untyped enums throw exception

### ISSUE THREAD

**Issue by soroush** [fmtlib/fmt#3332]
Trying to format an enum value as an integer, throws if `ostreams` header is included. Remove the following include and it works fine.

```C++
#include <iostream>
#include <fmt/format.h>
#include <fmt/ostream.h> // Problem

enum UNTYPED {A = 42, B, C};

int main() {
    std::cout << fmt::format("The answer is: {:d}\n", A);
    return 0;
}

```

**Environment**
Windows: 11 22H2
msvc:19.34.31942 x86_64
fmt: 8.1.1

https://godbolt.org/z/vTPY4j96d

**Comment by vitaut** [comment]
This should have been fixed in {fmt} 9.x already.

**Comment by ghosty141** [comment]
> This should have been fixed in {fmt} 9.x already.

Could you please link the commit? Thanks!

**Comment by vitaut** [comment]
Enums require a formatter or `format_as` as of version 9.0. You can use the corresponding version tag.
