### ISSUE TITLE
error: call to consteval function 'fmt::basic_format_string::basic_format_string' is not a constant expression

### ISSUE THREAD

**Issue by martincmartin** [fmtlib/fmt#3336]
With clang++ v 14, and trunk libfmt.

Godbolt repro: https://godbolt.org/z/GhGWsE783

 error: call to consteval function 'fmt::basic_format_string<char, unsigned long &>::basic_format_string<std::basic_string<char>, 0>' is not a constant expression

**Comment by vitaut** [comment]
Format strings must be known at compile time. Please see the docs: https://fmt.dev/latest/api.html#core-api.
