### ISSUE TITLE
v9.1.0 gcc 6 compilation error: use of 'fmt::v9::detail::count_digits` before deduction of 'auto'

### ISSUE THREAD

**Issue by glebm** [fmtlib/fmt#3339]
Error message:

```
include/fmt/format.h:1116:4: error: use of 'fmt::v9::detail::count_digits(UInt)::<lambda(UInt)> [with int BITS = 4; UInt = long long unsigned int]' before deduction of 'auto'
   return [](UInt m) {
          ~~~~~~~~~~~~
     int num_digits = 0;
     ~~~~~~~~~~~~~~~~~~~
     do {
     ~~~~
       ++num_digits;
       ~~~~~~~~~~~~~
     } while ((m >>= BITS) != 0);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     return num_digits;
     ~~~~~~~~~~~~~~~~~~
   }(n);
   ~^~~
```

CI job: https://app.circleci.com/pipelines/github/diasurgical/devilutionX/17077/workflows/5baa3d10-eb3f-48d1-89f0-b8297057feea/jobs/108883 (from https://github.com/diasurgical/devilutionX/pull/5875)

Not quite sure what this error means.

**Comment by glebm** [comment]
Perhaps the lambda needs an explicit return type, let's see if it helps

**Comment by glebm** [comment]
The explicit return type helps but the result is another error:

```
include/fmt/format.h:1241:8: error: uninitialized variable 'buffer' in 'constexpr' function
   Char buffer[digits10<UInt>() + 1];
        ^~~~~~
```

https://app.circleci.com/pipelines/github/diasurgical/devilutionX/17078/workflows/eeb9881e-ed3d-46c3-93d5-239b5100e56e/jobs/108888

**Comment by vitaut** [comment]
Closing per discussion in #3340 as it looks like a side effect of already fixed issue.
