### ISSUE TITLE
How to use the FMT_VARIADIC macro for constructors?

### ISSUE THREAD

**Issue by Migsi** [fmtlib/fmt#334]
Hello,

this isn't really an issue, more a question (and suggestion) which would be the best way to use the  FMT_VARIADIC macro for constructors?

I'm asking, because we recently switched over to fmtlib and I have to change the code of an older embedded system. Our Logger class is called via a method, which I wrapped with the macro and everything went fine, but our Error class gets called by it's constructor. Modifying the macro that it won't have a return type lead to compiling errors, so I was wondering if there is any possible way to support constructors too?

**Comment by vitaut** [comment]
`FMT_VARIADIC` won't work with ctors, but you can use `FMT_VARIADIC_CTOR` instead, for example:

```c++
class SystemError : public internal::RuntimeError {
 private:
  void init(int err_code, CStringRef format_str, ArgList args);

 public:
  FMT_VARIADIC_CTOR(SystemError, init, int, CStringRef);
};
```

The constructors generated by `FMT_VARIADIC_CTOR` will call the `init` method.

**Comment by vitaut** [comment]
BTW the example is taken from here: https://github.com/fmtlib/fmt/blob/dc1e36fa0e4e3d69f11cb028a0b56910a6fa3c3f/fmt/format.h#L2247

**Comment by Migsi** [comment]
Thank you for the quick response!

I guess I looked over the code too fast... I apologize for that :/

**Comment by vitaut** [comment]
No worries, it's not a part of the public API so it's hard to notice.

**Comment by Migsi** [comment]
After trying this way to generate my constructor, I've still got compile errors. It says:

```
libcommon/errorkms.h: In constructor `Error::Error(ErrorType, const char*, 
   const T0&)':
libcommon/errorkms.h:93: error: type/value mismatch at argument 1 in template 
   parameter list for `template<class Char> class fmt::internal::MakeValue'
libcommon/errorkms.h:93: error:   expected a type, got `Char'
libcommon/errorkms.h: In constructor `Error::Error(ErrorType, const char*, 
   const T0&, const T1&)':
libcommon/errorkms.h:93: error: type/value mismatch at argument 1 in template 
   parameter list for `template<class Char> class fmt::internal::MakeValue'
libcommon/errorkms.h:93: error:   expected a type, got `Char'
libcommon/errorkms.h:93: error: type/value mismatch at argument 1 in template 
   parameter list for `template<class Char> class fmt::internal::MakeValue'
libcommon/errorkms.h:93: error:   expected a type, got `Char'
libcommon/errorkms.h: In constructor `Error::Error(ErrorType, const char*, 
   const T0&, const T1&, const T2&)':
```
and so on...

Might there be a problem with the type conversion inside the library, or is it wrong, to try access the macro with other types than in the example?

Here's my code how I call the whole thing:

```
void Error::generateError(enum ErrorType t, const char *mess, const fmt::ArgList args) {
        memset(&_errorData, 0 , sizeof( struct ErrorData) );
        memset(&_errorContext, 0 , sizeof( struct ECErrorContextStruct) );
        _errorData.errorType = t;
        _errorData.timestamp = (unsigned int) TimeStamp(TimeStamp::NOW).s();
        _errorText = fmt::format(mess, args);
    }

    void Error::generateAndLogError(enum ErrorType t, enum SystemModule m, const string& functionName, const char *mess, const fmt::ArgList args) {
        memset(&_errorData, 0 , sizeof( struct ErrorData) );
        memset(&_errorContext, 0 , sizeof( struct ECErrorContextStruct) );
        _errorData.errorType = t;
        _errorData.errorModule = m;
        _errorData.timestamp = (unsigned int) TimeStamp(TimeStamp::NOW).s();
        strncpy( _errorData.functionName, functionName.c_str(), sizeof(_errorData.functionName) );
        _errorText = fmt::format(mess, args);
        if( _errorData.errorType != ERROR_TYPE_OK )
          logger().log(LOG_ERR, m , functionName, _errorText );
    }

  public:

    /*Error(enum ErrorType t, const char *mess ){
      generateError(t, mess, fmt::ArgList());
    }*/
    FMT_VARIADIC_CTOR(Error, generateError, ErrorType, const char*);

    /*Error(enum ErrorType t, enum SystemModule m, const string& functionName, const char *mess="" ) {
      generateAndLogError(t, m, functionName, mess, fmt::ArgList());
    }*/
    FMT_VARIADIC_CCTOR(Error, generateAndLogError, ErrorType, SystemModule, const string&, const char *);
```

I've added a custom version of the macro to get my second constructor working, which needs 4 arguments.

**Comment by vitaut** [comment]
Forgot to mention that you need to add

```c++
typedef char Char;
```
to your `Error` class.

**Comment by Migsi** [comment]
That solved my problem! Thank you very very much!

**Comment by vitaut** [comment]
Let me know how it goes.

**Comment by Migsi** [comment]
Everything went fine, it compiled, and now it seems to work flawlessly!

The only problem I had (or better I'm still having) is to guarantee, all strings which now use the fmtlib, got translated to the fmt syntax. I wrote a small parser application, but it seems to sometimes "forget" entries... 
Is there already any other tool which helps to switch over to the fmtlib?

**Comment by vitaut** [comment]
> Everything went fine, it compiled, and now it seems to work flawlessly!

Great!

> Is there already any other tool which helps to switch over to the fmtlib?

Not that I'm aware of.
