### ISSUE TITLE
v9.1.0 gcc6 compilation error: uninitialized variable in constexpr function

### ISSUE THREAD

**Issue by glebm** [fmtlib/fmt#3341]
On GCC6, after fixing #3339, the build fails with:

```
include/fmt/format.h:1241:8: error: uninitialized variable 'buffer' in 'constexpr' function
   Char buffer[digits10<UInt>() + 1];
        ^~~~~~
```

https://app.circleci.com/pipelines/github/diasurgical/devilutionX/17078/workflows/eeb9881e-ed3d-46c3-93d5-239b5100e56e/jobs/108888 (https://github.com/diasurgical/devilutionX/pull/5875)

(extracted from https://github.com/fmtlib/fmt/issues/3339#issuecomment-1465157607)

**Comment by phprus** [comment]
Already fixed in master:

https://github.com/fmtlib/fmt/blob/cbc7b8d5c1a0a88671fa1497d9e09197fde334f2/include/fmt/format.h#L1345

**Comment by glebm** [comment]
Thanks! Fixed by https://github.com/fmtlib/fmt/pull/3066
