### ISSUE TITLE
link error: undefined reference to `gmtime_r`

### ISSUE THREAD

**Issue by glebm** [fmtlib/fmt#3344]
On Amiga GCC6 on master:

> /opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: Source/CMakeFiles/libdevilutionx.dir/capture.cpp.obj:(.text._ZN3fmt2v96detail9tm_writerISt20back_insert_iteratorINS0_19basic_memory_bufferIcLj500ESaIcEEEEcNSt6chrono8durationIxSt5ratioILx1ELx1EEEEE22format_utc_offset_implI2tmLi0EEEvRKT_NS1_14numeric_systemE+0x4a): undefined reference to `gmtime_r'

https://app.circleci.com/pipelines/github/diasurgical/devilutionX/17087/workflows/b37bbcab-f027-4766-b057-91aa272ba35e/jobs/108932 (https://github.com/diasurgical/devilutionX/pull/5875)

Here, `gmtime_r` is listed as C23: https://en.cppreference.com/w/c/chrono/gmtime

**Comment by vitaut** [comment]
This is more of an issue with system headers than {fmt} because they lie about existence of `gmtime_r` which causes this linker error (the headers define a function but the library doesn't provide it). That said a PR to workaround this would be welcome.

**Comment by glebm** [comment]
Yeah that's entirely possible with that toolchain.

However, there are only 2 uses of `gmtime_r` in chrono.h and they do not seem to be guarded by any checks, so `chrono.h` always tries to use `gmtime_r`.

We've stopped using `chrono.h` so not an issue for us anymore but libfmt should probably contain some checks for `gmtime_r` availability.

**Comment by vitaut** [comment]
> However, there are only 2 uses of gmtime_r in chrono.h and they do not seem to be guarded by any checks, so chrono.h always tries to use gmtime_r.

This is not correct. Here is the code that detects presence of `gmtime_r`: https://github.com/fmtlib/fmt/blob/d9bc5f1320332db9a4bf7e103b0813b94e369304/include/fmt/chrono.h#L519-L552

**Comment by glebm** [comment]
Ah, I've missed the `using namespace fmt::detail;`, thanks for pointing it out. 👍
