### ISSUE TITLE
Formatting returns -0

### ISSUE THREAD

**Issue by ColleenCurtin** [fmtlib/fmt#3346]
When the value is negative and has more decimal points as 0 than the precision value it gets formatted as -0. It should return 0.
Example: -0.0002 with precision 2 returns -0.00 instead of 0.00

https://godbolt.org/z/6n11KPK1r

**Comment by vitaut** [comment]
This is expected and consistent with Python's `str.format` this API is modeled after as well as other formatting facilities. For example:

```python
>>> "The answer is {:.{}f}.".format(-0.0002, 2)
'The answer is -0.00.'
```
