### ISSUE TITLE
CMake error while running pedantic tests

### ISSUE THREAD

**Issue by trldp** [fmtlib/fmt#3350]
When compiling with -DFMT_PEDANTIC=On, the four pedantic tests (compile-error-test, find-package-test, add-subdirectory-test and static-export-test fail) to pass with the following error.
`
CMake Error at /<<PKGBUILDDIR>>/CMakeLists.txt:234 (target_compile_features): target_compile_features The CXX_STANDARD property on target "fmt" contained an invalid value: "".
`
I noticed the error on Ubuntu 22.04, but it also seems to occur on other versions of Ubuntu. A build full log can be found at https://launchpadlibrarian.net/655683674/buildlog_ubuntu-jammy-amd64.fmtlib_8.1.1-1~git202303122016+3~ubuntu22.04.1_BUILDING.txt.gz.

**Comment by vitaut** [comment]
`FMT_PEDANTIC` is mostly for {fmt}'s own CI, there is no reason to enable it elsewhere.
