### ISSUE TITLE
fmt::detail::print with a text style miss wchar_t overloads

### ISSUE THREAD

**Issue by przemkovv** [fmtlib/fmt#3357]
With 9.1.0 (and trunk), I found a similar issue to #3202, but with a style `fmt::print` overload.
With the following code:
```cpp
    const auto style = fg(fmt::color::white) | fmt::emphasis::bold;
    fmt::print(style, L"{}", L"foo"); // doesn't compile
    fmt::print(style, "{}", "foo"); // compiles
    fmt::print(L"{}", L"foo"); // compiles
```
Compilers (msvc and clang) complain that there is no proper function overload for `std::wstring_view` and the only available one is `fmt::detail::print(std::FILE* f, string_view text)`.
At the same time, the above code works with fmt 8.1.1.

See https://godbolt.org/z/GcGKMY6Pq for reproducer (msvc with 9.1.0, clang with fmt trunk and 8.1.1)

**Comment by przemkovv** [comment]
A workaround is to use:
```cpp
fmt::print(L"{}", fmt::styled(L"foo", style));
```

**Comment by vitaut** [comment]
Thanks for reporting but wide stream support is mostly there for migrating legacy code. Considering that text styles is an {fmt}-specific feature I don't think we need to make it work with legacy APIs.

**Comment by przemkovv** [comment]
Sounds reasonable, thanks! 😀
