### ISSUE TITLE
FMT_COMPILE slower than uncompiled

### ISSUE THREAD

**Issue by jonashaag** [fmtlib/fmt#3358]
Not sure if this is a representative example, I just wanted you to know in case it is:

Code: https://godbolt.org/z/hzq7Kz3rs

If I run this with

```
hyperfine './a.out 100000'
```

I get 8.1 ms for `FMT_COMPILE` and 6.9 ms when not using `FMT_COMPILE`.

**Comment by vitaut** [comment]
`FMT_COMPILE` can indeed be slower in some cases. Usually it is faster on simple cases such as formatting of built-in or string types.
