### ISSUE TITLE
No throwing version of fmt::format

### ISSUE THREAD

**Issue by hsdk123** [fmtlib/fmt#3359]
Hi, I was wondering if there might be a no throwing version of fmt::format. 

I'm currently using emscripten, and the default tends to be to crash in the case of exceptions. 
https://emscripten.org/docs/optimizing/Optimizing-Code.html

**Comment by vitaut** [comment]
There is no such version but you can avoid most exceptions by using compile-time checks. Other exceptions are mostly coming from the standard library, e.g. memory allocation can throw (at least in theory).

**Comment by hsdk123** [comment]
@vitaut What would you mean `by using compile-time checks`?

**Comment by vitaut** [comment]
> What would you mean by using compile-time checks?

https://fmt.dev/latest/api.html#compile-time-format-string-checks

**Comment by hsdk123** [comment]
> > What would you mean by using compile-time checks?
> 
> https://fmt.dev/latest/api.html#compile-time-format-string-checks

Thanks,
```
template<typename ... Args>
std::wstring format_string(const std::wstring_view format, Args ... args)
{
try {
	return fmt::format(FMT_STRING(format), args ...);
}
catch (...) {
	return std::wstring(format);
}
}
```
would you know why the above won't compile?

error:
```
format_string::<lambda_1548137e035b79862e6e36159e3299bd>::()::FMT_COMPILE_STRING::operator fmt::v9::basic_string_view<wchar_t>(void) const': function cannot access 'format'
```

**Comment by vitaut** [comment]
It won't compile because the format string is not known at compile time.
