### ISSUE TITLE
Feature Request: support fmt::print("%S", L"wchar str")

### ISSUE THREAD

**Issue by builden** [fmtlib/fmt#337]
RT

**Comment by vitaut** [comment]
`fmt::print` accepts Python-like, not printf-like specifiers. Moreover, it's not clear what should be the behavior of formatting a wide string into a narrow one. Should it convert encoding and which one?

**Comment by vitaut** [comment]
I'm closing this for now but feel free to reopen clarifying what you are trying to do.
