### ISSUE TITLE
please help with rounding issue.

### ISSUE THREAD

**Issue by zalmoxis2019** [fmtlib/fmt#3370]
Hello,
     Please tell me how to round this, so that the output is 2.5? The default seems to use grisu_gen_digits algo that outputs 2.6.
p.s i tried using std::fesetround(FE_TOWARDZERO); since this works with snprintf but grisu doesn't care :p
```
std::fesetround(FE_TOWARDZERO);
string s = fmt::format("round me the way i want {:.{}f}", 2.56, 1); //output: "round me the way i want  2.6" ...
cout << s << endl;
```

**Comment by vitaut** [comment]
Formatting functions use round to nearest. If you wand something different you'll have to do it yourself before passing the value to a formatting function.

**Comment by kharedevansh11** [comment]
here the formating function itself rounds to the nearest number. For rounding it off to your desired way you can use floor() or ceil() function accordingly. make sure to import cmath library.
#include<cmath>
