### ISSUE TITLE
Vulnerability detected by security scan in core.h

### ISSUE THREAD

**Issue by eugrin** [fmtlib/fmt#3371]
cpp/enum-index (in thirdparty/spdlog/include/spdlog/fmt/bundled/core.h:2031

When accessing array values_ with index id, the upper bound of an enum is used to check the upper bound of the array, but the lower bound is not checked.
2029 arg.type_ = type(id);
2030 if (arg.type_ == detail::type::none_type) return arg;
2031 arg.value_ = values_[**id**];
2032 return arg;
2033 }

**Comment by vitaut** [comment]
Thanks for reporting but the error makes no sense because `id` is not an enum, `detail::type::none_type` is neither lower nor upper bound and the actual checks are done by other means. Please report this to the vendors of the tool you used for the scan.
