### ISSUE TITLE
Vulnerability detected by security scan in format.h

### ISSUE THREAD

**Issue by eugrin** [fmtlib/fmt#3372]
cpp/infiniteloop (in thirdparty/spdlog/include/spdlog/fmt/bundled/format.h:1966

In count_separators comparison between call to expression of type unknown and num_digits of wider type int.
1964 int count = 0;
1965 auto state = initial_state();
1966 while (**num_digits > next(state)**) ++count;
1967 return count;
1968 }

**Comment by vitaut** [comment]
This is also a bug in the tool you are using because `next` returns `int`: https://github.com/fmtlib/fmt/blob/4e3f38105866c5ffb90cc01ceb72ea7f4bb98ad5/include/fmt/format.h#L2109.
