### ISSUE TITLE
Allow to disable inline namespaces

### ISSUE THREAD

**Issue by igoloe** [fmtlib/fmt#3376]
Please add a way to disable inline namespaces via define, as i.e. done by nlohman.json
https://json.nlohmann.me/features/namespace/

Rationale
- interoperability. inline namespaces are not supported by specific compiler extensions, i.e. c++/cli
- decoupling. inline namespaces make it hard to declare formatter without including complete fmt.
- ...

Dont get me wrong. I think inline namespaces are a great thing for versioning.

**Comment by vitaut** [comment]
You could probably do with with `FMT_BEGIN_NAMESPACE` although I wouldn't recommend it.

**Comment by igoloe** [comment]
Problem is, that redefining the namespace macros via the commandline of some compilers or analysis tools, does not work, because of included blanks. 

You may also choose to use something like forced includes, where the defines are placed before any fmt header is ever seen, but again its compiler vendor specific.

**Comment by igoloe** [comment]
Closed to early.

I could easily offer a PR.

**Comment by vitaut** [comment]
If you tooling is so limited that it doesn't accept spaces then I suggest using a wrapper header. We shouldn't introduce macros for this.
