### ISSUE TITLE
[MSVC][c++latest] error C2668: 'std::format_to': ambiguous call to overloaded function

### ISSUE THREAD

**Issue by Zhaojun-Liu** [fmtlib/fmt#3377]
Hi all,
I tried to build Fmt with VS2022 on Windows, but it failed due to error C2668. Could anyone look at this issue? Thanks in advance.

**Environment:**
VS2022 + Windows Server

**Repro steps:**
1. Open a VS 2022 x64 Native Tools command.
2. git clone https://github.com/fmtlib/fmt F:\gitP\fmtlib\fmt
3. git -C "F:\gitP\fmtlib\fmt" reset --hard 4a4a2a2
4. set _CL_= /std:c++latest
5. mkdir F:\gitP\fmtlib\fmt\build_amd64 and cd F:\gitP\fmtlib\fmt\build_amd64
6. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 ..
7. cmake --build . --config Release --verbose -- /maxcpucount

**Expected result:**
Build successfully.

**Actual result:**
```
"F:\gitP\fmtlib\fmt\build_amd64\ALL_BUILD.vcxproj" (default target) (1) ->
       "F:\gitP\fmtlib\fmt\build_amd64\test\format-impl-test.vcxproj" (default target) (19) ->
       (ClCompile target) -> 
         F:\gitP\fmtlib\fmt\test\format-impl-test.cc(304,5): error C2668: 'fmt::v9::format_to': ambiguous call to overloaded function [F:\gitP\fmtlib\fmt\build_amd64\test\format-impl-test.vcxproj]


       "F:\gitP\fmtlib\fmt\build_amd64\ALL_BUILD.vcxproj" (default target) (1) ->
       "F:\gitP\fmtlib\fmt\build_amd64\test\args-test.vcxproj" (default target) (3) ->
         F:\gitP\fmtlib\fmt\test\args-test.cc(47,12): error C2668: 'std::format_to': ambiguous call to overloaded function [F:\gitP\fmtlib\fmt\build_amd64\test\args-test.vcxproj]


       "F:\gitP\fmtlib\fmt\build_amd64\ALL_BUILD.vcxproj" (default target) (1) ->
       "F:\gitP\fmtlib\fmt\build_amd64\test\format-test.vcxproj" (default target) (18) ->
         F:\gitP\fmtlib\fmt\test\format-test.cc(1642,12): error C2668: 'std::format_to': ambiguous call to overloaded function [F:\gitP\fmtlib\fmt\build_amd64\test\format-test.vcxproj]
         F:\gitP\fmtlib\fmt\test\format-test.cc(1664,12): error C2668: 'std::format_to': ambiguous call to overloaded function [F:\gitP\fmtlib\fmt\build_amd64\test\format-test.vcxproj]
         F:\gitP\fmtlib\fmt\test\format-test.cc(1685,5): error C2668: 'std::format_to': ambiguous call to overloaded function [F:\gitP\fmtlib\fmt\build_amd64\test\format-test.vcxproj]
         F:\gitP\fmtlib\fmt\test\format-test.cc(1726,3): error C2668: 'std::format_to': ambiguous call to overloaded function [F:\gitP\fmtlib\fmt\build_amd64\test\format-test.vcxproj]
         F:\gitP\fmtlib\fmt\test\format-test.cc(1864,3): error C2668: 'std::format_to': ambiguous call to overloaded function [F:\gitP\fmtlib\fmt\build_amd64\test\format-test.vcxproj]

    23 Warning(s)
    7 Error(s)
```

**More:**
I tried to use namespace to qualify the call to format_to, i.e. change it to fmt::format_to, it will build ok.

**Detailed log:**
[build.log](https://github.com/fmtlib/fmt/files/11189192/build.log)

**Comment by vitaut** [comment]
msvs probably pulls in `<format>` for no good reason causing ambiguities. A PR to qualify problematic calls would be welcome.

**Comment by Zhaojun-Liu** [comment]
> Microsoft "STL" probably pulls in `<format>` for no good reason causing ambiguities. A PR to qualify problematic calls would be welcome.

Hi @vitaut, I made a PR #3378 to fix this issue, could you please help review and approval it? Thanks.

**Comment by bebuch** [comment]
Today I encountered the same problem with MSVC and LLVM on Windows. Can you please create a new release? I am only allowed to use releases and this makes it impossible to use the latest version.

**Comment by vitaut** [comment]
We don't make releases on request but the work on the new one has already begun.
