### ISSUE TITLE
C++Builder compilation error

### ISSUE THREAD

**Issue by rjdgtn** [fmtlib/fmt#338]
try to build format.h by
C++Builder 10 Seattle Version 23.0.21418.4207
for Win32 Debug with 'classic' Borland compiler 
take fmt from commit 0d9870d

[bcc32 Error] format.h(1130): Cannot generate template specialization from 'LConvCheck<T,(value)>'

**Comment by rjdgtn** [comment]
On format-3.0.0 has such error:
[bcc32 Error] format.h(2061): > expected

**Comment by vitaut** [comment]
I am afraid bcc32 won't be supported because even C++98 seems to be rather broken there. That said I'm willing to accept PRs that improve compatibility with this compiler provided that they are not too intrusive.
