### ISSUE TITLE
custom formatter c++20 "all to immediate function is not a constant expression" issue

### ISSUE THREAD

**Issue by muffmolch** [fmtlib/fmt#3383]
How can this issue been solved?
**compile optione: Visual Studio 2022, >=17.5.0, c++20, fmt 9.1.0**

~~~cpp
CLocalDateTime ldt;
auto s = fmt::format("Test {:ts}", ldt);
~~~

~~~cpp
template <typename Char> struct fmt::formatter<CLocalDateTime, Char>
{
   CStdStr<Char> m_time_format;

   // Parses format specifications of the form .
   constexpr auto parse(basic_format_parse_context<Char>& ctx) -> decltype(ctx.begin())
   {
      auto it = ctx.begin(), end = ctx.end();
      while( it != end && *it != '}' ){
         m_time_format += *it++;
      }
      if( it != end && *it != '}' ){ // Check if reached the end of the range:
         throw format_error("invalid format");
      }
      return it; // Return an iterator past the end of the parsed range:
   }

   // Formats ldt using the parsed format specification (presentation) stored in this formatter.
   template <typename FormatContext>
   auto format(const CLocalDateTime& ldt, FormatContext& ctx) const -> decltype(ctx.out())
   {
      static_assert(std::is_same<FormatContext::char_type, Char>::value, "chars-type must be equal");

      if( m_time_format.Equals(CStdStr<Char>("ts"), false)  ){
// follwong line seems to produce the error (only for c++20):
         return fmt::format_to(ctx.out(), "{}", ldt.LocalToString<CStdStr<Char>>(TimeFormat::DTDefOString()).c_str());
      }

      throw format_error(fmt::format("fmt::format_arg: CLocalDateTime - unknown formatter option '{}' in format string", CStdStr<char>(m_time_format)));
   }
};
~~~

compile error:
~~~bash
error C7595: 'fmt::v9::basic_format_string<char,CLocalDateTime &>::basic_format_string': call to immediate function is not a constant expression
1>E:\DitecLibs\Packages\fmt\fmt_9_1_0\include\fmt\core.h(2745,71): message : failure was caused by call of undefined function or one not declared 'constexpr'
1>E:\DitecLibs\Packages\fmt\fmt_9_1_0\include\fmt\core.h(2745,71): message : see usage of 'fmt::v9::formatter<CLocalDateTime,char,void>::formatter'
~~~
**using c++17 everything is fine!**

(btw: this error I also gain at this statements:
~~~cpp
std::string f("Test {}");
auto s = fmt::format(f, 9);
~~~

actually we are using:

~~~cpp
auto s = fmt::format( fmt::runtime(f), 9);
~~~

to get rid of this error, without liking that solution.)

**Comment by vitaut** [comment]
Please provide a godbolt repro that shows the error.

**Comment by mwinterb** [comment]
Has CStdStr been constexpr-ified?

**Comment by sunmy2019** [comment]
Will the removal of `CStdStr<Char>` compile the program?

**Comment by muffmolch** [comment]
> Has CStdStr been constexpr-ified?
don't think ths. It's a very old class ... But at what postition should the error come from because of missing constexpr?

> Will the removal of CStdStr<Char> compile the program?
I reduces the formatter to (besides it does not makes sense):
`template <typename Char> struct fmt::formatter<CLocalDateTime, Char>
{
   // Parses format specifications of the form .
   constexpr auto parse(basic_format_parse_context<Char>& ctx) -> decltype(ctx.begin())
   {
      auto it = ctx.begin(), end = ctx.end();
      while( it != end && *it != '}' ){
      }
      if( it != end && *it != '}' ){ // Check if reached the end of the range:
         throw format_error("invalid format");
      }
      return it; // Return an iterator past the end of the parsed range:
   }

   // Formats ldt using the parsed format specification (presentation) stored in this formatter.
   template <typename FormatContext>
   auto format(const CLocalDateTime& ldt, FormatContext& ctx) const -> decltype(ctx.out())
   {
      static_assert(std::is_same<FormatContext::char_type, Char>::value, "chars-type must be equal");

      throw format_error(fmt::format("fmt::format_arg: CLocalDateTime - unknown formatter option '{}' in format string", "TEST"));
   }
};`
still no success

**Comment by muffmolch** [comment]
> Please provide a godbolt repro that shows the error.

How to?

**Comment by muffmolch** [comment]
~~~cpp
CLocalDateTime ldt;
auto t1 = fmt::format("Test {:ts}", ldt); // compile error
auto t2 = fmt::format("Test {}", ldt); // no compile error
auto t3 = fmt::format( fmt::runtime("Test {:ts}"), ldt);
~~~
Can anyone explain? We also run into asio compile build errors and figiered out that the /permissive compile flag does not work with aio. thus we are using /permissive- now, but the fmt-error is still there

**Comment by sunmy2019** [comment]
> How to?

Play with https://godbolt.org/z/8nTPqv1Tn

**Comment by sunmy2019** [comment]
>       while( it != end && *it != '}' ){
>       }


You got an infinite loop here. Try to include a minimal reproducing example.

**Comment by sunmy2019** [comment]
I am produce the (not minimal) reproducing example:

https://godbolt.org/z/do68Yf5af

**Comment by muffmolch** [comment]
> > ```
> >   while( it != end && *it != '}' ){
> >   }
> > ```
> 
> You got an infinite loop here. Try to include a minimal reproducing example.

I got the problem:

~~~cpp
#include <fmt/format.h>

struct point {
	double x, y;
};

template <> struct fmt::formatter<point> {
	// Presentation format: 'ff' - fixed, 'ee' - exponential.
	std::string presentation = "ff";

	// Parses format specifications of the form ['f' | 'e'].
	constexpr auto parse(format_parse_context& ctx) -> decltype(ctx.begin()) 
	{
		auto it = ctx.begin(), end = ctx.end();
		while( it != end && *it != '}' ){
			presentation += *it++;
		}

		if( it != end && *it != '}' ){ // Check if reached the end of the range:
			throw format_error("invalid format");
		}

		return it; // Return an iterator past the end of the parsed range:	
	}

	template <typename FormatContext>
	auto format(const point& p, FormatContext& ctx) const -> decltype(ctx.out()) {
		if( presentation == "ff" ){
			return fmt::format_to(ctx.out(), "({:.1f}, {:.1f})", p.x, p.y);
		}
		return fmt::format_to(ctx.out(), "({:.1e}, {:.1e})", p.x, p.y);
	}
};


int main( int argc , char** argv )
{
	point p = { 1, 2 };
	std::string s1 = fmt::format("{:ff}", p); 
	std::string s2 = fmt::format(fmt::runtime("{:ff}"), p); 
}
~~~

this examples works. But replaceing the member variable `presentation´with out CStdStr<Char> class, results to the non constant error. That's seems to be the constexpr problem already mentioned by another user. May you help me out, what part of that class has to be constepxr-fyed?

**Comment by muffmolch** [comment]
> I am able to produce the (not minimal) reproducing example, but I don't have time to look into it.
> 
> https://godbolt.org/z/do68Yf5af
> 
> With C++20, the format string checking will be done at compile time, but your formatted struct cannot be constructed at compile time, so I think that caused a failure.
> 
> If you remove this `CStdStr<>` inside the `formatter<...>`, it compiles.

Yes, you're right. But may you tell me, what to do, to make that CStdStr<Char> constexpr compliant?

**Comment by sunmy2019** [comment]
The class constructor.

std::string has a constexpr constructor since c++20.

https://en.cppreference.com/w/cpp/string/basic_string/basic_string

**Comment by muffmolch** [comment]
@sunmy2019 thanks for all. it's the missing constepxr. Meanwhile I rewrote the formatter for our purpose and it works. but nevertheless we have to put the CstdString class into this century ;-)

**Comment by ScottHutchinson** [comment]
@muffmolch I'm having the same issue. Do you remember exactly how you worked around it? Did you fork this repo? Thanks

**Comment by muffmolch** [comment]
Meanwhile we are using this for runtime expressions:

`FMT_BEGIN_NAMESPACE

	template <typename string_type, typename... Args, typename Char = typename char_type_of< string_type >::type //>
			, FMT_ENABLE_IF(std::is_same<Char, char>::value || std::is_same<Char, wchar_t>::value)>
	auto formatrt(const string_type& format_str, Args&&... args) -> std::basic_string<Char>
	{
		return format(fmt::runtime(std::basic_string<Char>(format_str)), args...);
	}

FMT_END_NAMESPACE`
