### ISSUE TITLE
Background colour can be added to the following line

### ISSUE THREAD

**Issue by mark-grimes** [fmtlib/fmt#3384]
Under some circumstances, colouring the background also colours everything after the newline on the next line.  I can trigger this by printing many empty lines, whereas the same code works fine if I don't print the empty lines beforehand.  This is not reproduced on godbolt.org for x86, godbolt.org won't run the code for armv8 (which is my system).

Example code:
```cpp
#include <fmt/core.h>
#include <fmt/color.h>

int main( int argc, char* argv[] )
{
	// Printing successive newlines triggers the bug. Without this loop all text is fine.
	for( int a=0; a< 100; ++a ) fmt::print( "\n" );

	fmt::print( fg(fmt::terminal_color::black) | bg(fmt::terminal_color::bright_red), "This line is correct\n" );
	fmt::print( fg(fmt::terminal_color::red) | bg(fmt::terminal_color::white), "This line has everything after the text in bg(bright_red)\n" );
	fmt::print( fg(fmt::terminal_color::green), "This line has everything after the text in bg(white)\n" );
	fmt::print( fg(fmt::terminal_color::yellow), "This line is fine\n" );

	return 0;
}
```

<img width="932" alt="Screenshot 2023-04-13 at 15 41 03" src="https://user-images.githubusercontent.com/6480160/231795431-81146f82-8c11-4efd-a9c0-4978d23796e0.png">

System: macOS 13.3.1 (22E261), Apple M1 Max
Apple Terminal version: 2.13 (447)
bash shell
fmt git commit: 75f3b1c09485986427b8a46272f6b9570366e1aa Use add_module_library
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0

**Comment by mark-grimes** [comment]
I've been playing around and I think this might be a bug in Apple Terminal.  Using the same executable repeatedly without recompiling (but without the `for` loop printing empty lines), it will print the text fine many times and then start displaying it incorrectly.
I think it's when Terminal has to scroll the display to show the text.

I'll leave this open for now for discussion, but the more I look at it I don't think this is fmt's fault.

**Comment by sunmy2019** [comment]
Since ANSI escape codes are merely some particular texts, maybe it will only look through a buffer with limited size so that some of the escape codes have been flushed out?

**Comment by mark-grimes** [comment]
Not sure why it's doing it, but it's definitely Terminal.  If I redirect output to a file and then keep doing `cat output.txt` it will print fine until it needs to start scrolling.  Sorry for the noise.
