### ISSUE TITLE
Support formatting nested exceptions

### ISSUE THREAD

**Issue by Krzmbrzl** [fmtlib/fmt#3385]
As far as I can tell, support for formatting regular exceptions has been added via #3062 and this was then extended by #3076.
However, this implementation is currently missing support for _nested_ exceptions (see e.g. https://cplusplus.com/reference/exception/nested_exception/ and https://riptutorial.com/cplusplus/example/18879/nested-exception).

When dealing with nested exceptions, simply calling `what()` only reveals the message of the topmost exception, but all messages from the nested exceptions (which are typically more interesting) are ignored. In order to print all messages, something along the line of this is typically used ([source](https://cplusplus.com/reference/exception/throw_with_nested/))
```cpp
// recursively print exception whats:
void print_what (const std::exception& e) {
    std::cerr << e.what() << '\n';
    try {
        std::rethrow_if_nested(e);
    } catch (const std::exception& nested) {
        std::cerr << "nested: ";
        print_what(nested);
    }
}
```

It'd be great if formatting an exception with this library would also print the messages of the nested exceptions in order to save users the hassle of having to take care of this themselves.

However, since implementing this requires rethrowing, I guess this is incompatible with builds that disable exceptions altogether (which, as I understand it, is a support case for this library). I guess there has to be some preprocessor magic to remove this feature in builds without exceptions.

Godbolt: https://godbolt.org/z/Yc3KsY193 (currently fails to compile as apparently the version of `fmt` that is used doesn't support exceptions yet)

**Comment by Skylion007** [comment]
> However, since implementing this requires rethrowing, I guess this is incompatible with builds that disable exceptions altogether (which, as I understand it, is a support case for this library). I guess there has to be some preprocessor magic to remove this feature in builds without exceptions.

it actually doesn't require rethrowing necessarily, but it may require RTTI otherwise. (Dynamic cast to nested exception and then get the exception ptr of the nested exception).

**Comment by ShawnZhong** [comment]
I can successfully get an [`exception_ptr`](https://en.cppreference.com/w/cpp/error/exception_ptr) from a nested exception, but there is not much you can do with it other than calling [`rethrow_exception`](https://en.cppreference.com/w/cpp/error/rethrow_exception) on it. 

If you are comfortable with casting `exception_ptr` to a `std::exception *` (which is definitely UB), then the following code snippet would work: 

```cpp
void print_exception(const std::exception &e) {
  fmt::print("{}\n", e.what());
  if (auto nep = dynamic_cast<const std::nested_exception *>(&e)) {
    auto ptr = nep->nested_ptr();
    print_exception(**(std::exception **)(&ptr));
  }
}
```

**Comment by vitaut** [comment]
Closing since it is possible to do this via the usual extension API but a PR to add this to the existing formatter would be welcome too.
