### ISSUE TITLE
Blacklisted license error because of iptux libs, could you please take care of it?

### ISSUE THREAD

**Issue by vikasjagdale92** [fmtlib/fmt#3389]
While scanning our project with blackduck we have getting blacklisted licence error because of iptux libs, could you please take care of it?
Below are the details,

libs    : iptux - 0.8.3+git20211122
path    : node_modules/couchbase/deps/lcb/contrib/gtest-1.8.1/include/
scan    : Blackduck - Blacklisted License
couchbase : ~4.2.2 (this is the primary dependancy)

**Comment by vitaut** [comment]
I have no idea what iptux is but {fmt} doesn't use it.
