### ISSUE TITLE
fmtlib assumes access to a console if _WIN32 is defined, which isn't always the case

### ISSUE THREAD

**Issue by AlexMax** [fmtlib/fmt#3393]
In `format-inl.h`, there are functions that are available behind a _WIN32 define that we believe is inappropriate.  In some instances, _WIN32 is defined, but there is no console available, which means functions like `WriteConsoleW` don't exist.  It would be nice if there was a way to configure fmtlib to omit these functions, because as it stands every time we update fmtlib we have to modify the header to change the defines used to guard access to console printing functions.

The reason I am being vague is that the specific environment I'm using fmtlib in is under NDA, and I'm not sure how specific I can be without violating it.

**Comment by vitaut** [comment]
Thanks for the suggestion but I'm not sure how can we support platforms we know virtually nothing about. You could create a stub for `WriteConsoleW` to mimic the Windows API.

**Comment by vitaut** [comment]
Closing per comment above.

**Comment by AlexMax** [comment]
> Closing per comment above.

@vitaut Sorry for not getting back to you sooner.  After some consideration, I think I was a little bit overcautious.  I'll be able to have an answer for you within an hour or two.

**Comment by AlexMax** [comment]
Okay, I think I have something for you, @vitaut .

If you take a peek inside `<consoleapi.h>` on Windows, you'll note that the forward declaration for both WriteConsole functions is guarded by the following define:

```c++
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)
```

This define comes from `<winapifamily.h>`, which can give you the whole skinny on what's up with these partitions.  I am on a platform that defines `WINAPI_PARTITION_GAMES`, so most of the header is greyed out to me.  And if the header doesn't exist, I think that it's safe to say that the symbol doesn't exist either.

You do have an interesting idea about defining my own version of `WriteConsole` that could perhaps pipe output to `OutputDebugString` or something similar.  However, I'm not sure if that would get past the `_isatty` check or not, and that function is _also_ guarded by partition checks, though this one includes `GAMES`.

So I'm not 100% sure what the best solution would be.  The behavior that would be most useful, imho, would be the following, in very rough pseudocode form:

```python
if platform_has_console() and _isatty():
    WriteConsole()
if platform_has_debug() and _DEBUG:
    OutputDebugString()
if write_console_ok or output_debug_string_ok:
    return True
else:
    return False
```

**Comment by vitaut** [comment]
A PR to replace the `_WIN32` check for `write_console` with a more specific one would be welcome. Trying to print to a debug window doesn't belong there but you can write your own formatting function that does that.
