### ISSUE TITLE
Feature Requested: Make Cout-able objects Formattable

### ISSUE THREAD

**Issue by YanB25** [fmtlib/fmt#3396]
I was wondering if it is possible to make any *cout-able* objects transparently *formattable*?

For example, for the legacy codes (`struct Person`) that overload `operator<<`:
``` c++
struct Person
{
    std::string name;
    int age;
};

std::ostream &operator<<(std::ostream &os, const Person &p)
{
    os << "{Person name: " << p.name << ", age:" << p.age << "};
    return os;
}
```

I wish to make `Person` directly formattable:

``` c++
Person person{.name = "name", .age = 20};
fmt::format("The person is {}", person);
```

**Comment by vitaut** [comment]
Not implicitly but there is https://fmt.dev/latest/api.html#ostream-api.
