### ISSUE TITLE
Unable to format string with packed field

### ISSUE THREAD

**Issue by Mulf** [fmtlib/fmt#3401]
To be short, [this code](https://godbolt.org/z/o67dqvzvb) can't be compiled. 

To be more specific, fmt::format is unable to format std::string with field from a packed object. 

code:
```C++
// test.cpp
#define FMT_HEADER_ONLY
#include "fmt/core.h"
#include "fmt/ranges.h"
#include <string>

struct __attribute__((aligned(4),packed))  Point {
    Point(int ix, int iy): x{ix}, y{iy}{}
    int x;
    int y;
};

int main() {
    Point p{3, 4};
    auto s = fmt::format("Point: x={:d}, y={:d}\n", static_cast<int>(p.x), p.y);
    fmt::print("{}\n", s);
}
```

compiler:     `g++ 11.3.0`
command:  `g++ -o test test.cpp`

error: 
```
test.cpp: In function ‘int main()’:
test.cpp:14:78: error: cannot bind packed field ‘p.Point::y’ to ‘int&’
   14 |     auto s = fmt::format("Point: x={:d}, y={:d}\n", static_cast<int>(p.x), p.y);
      |                                                                            ~~^
```

remark: as we can see in the hint of error, there is not problen with `static_cast<int>(p.x)`, but the `p.y` can't be used in the formatted string.

My question: is it possible to format string with field from a packed object?
Thanks.

**Comment by vitaut** [comment]
Same as #2468.
