### ISSUE TITLE
Forwarding of `args` in `xchar.h`

### ISSUE THREAD

**Issue by Boddlnagg** [fmtlib/fmt#3408]
In the same vein as https://github.com/fmtlib/fmt/issues/2462, I think that `format_to_n` in `xchar.h` should take args as `Args&&...` [instead of `const Args&...`](https://github.com/fmtlib/fmt/blob/f8c9fabd948e4b3caea30d3c281018b0308491bf/include/fmt/xchar.h#L206). For `format_to` in `xchar.h` this is already the case.

`make_wformat_args` should probably also be changed to match `make_format_args` in forwarding the `args`.

**Comment by Epixu** [comment]
I'm currently working around a similar issue
They are currently taken as [mutable Args&... ](https://github.com/fmtlib/fmt/blob/130b8fcdb9a14b0e032c40e498110eee63288892/include/fmt/core.h#L1814)
The comment above states that "_Arguments are taken by lvalue references to avoid some lifetime issues._"
And this is an implementation detail, so I suppose it's our responsibility to adapt.
Although, make_format_args is used extensively in custom formatters afaik, so the devs might still reconsider it having the proper interface eventually.

**Comment by vitaut** [comment]
@Epixu, `make_format_args` should only be used in custom formatting functions, not in custom formatters. You should use `format_to` instead of `vformat_to`:

```c++
      return fmt::format_to(ctx.out(), "{}", static_cast<std::string_view>(asText));
```
