### ISSUE TITLE
fmt::format thread safety

### ISSUE THREAD

**Issue by GilbertoTheMighty** [fmtlib/fmt#3417]
Hello, I have a class like this:
```
class formatter{
    std::string format;
public:
    formatter(int p){
        format= "{:." + std::to_string(p) + "f}";
    }

    void doFormat(std::string &input, double num){
        input.append(fmt::format(format, num));
    }
```

I have a bunch of threads and all of them have its own instance of this class with different format precision.
As a result I have misformatted output of some formats.
How to use format thread safe?

**Comment by vitaut** [comment]
`fmt::format` is thread-safe. Perhaps you are accessing input from multiple threads without synchronization. Hard to say anything more specific without a repro.
