### ISSUE TITLE
fmt ignores locale

### ISSUE THREAD

**Issue by mdickie** [fmtlib/fmt#342]
```
    std::setlocale(LC_ALL, "de_DE");
    std::time_t t = std::time(nullptr);
    std::tm *local_tm = std::localtime(&t);
    assert(local_tm != nullptr);
    fmt::print("de_AT: {:%A, %e. %B %Y}\n", *local_tm);
```
Output:
```
de_AT: Sunday, 12. June 2016
```
I found this Issue #305 but i honestly don't know how to apply it on my code.

**Comment by vitaut** [comment]
Time formatting uses `strftime` so the current locale should apply. Do you have `de_AT` locale installed? You can get the list of locales with the following command:

```
locale -a
```

**Comment by vitaut** [comment]
Here's the output that I get after installing `de_AT` locale:

```
de_AT: Sonntag, 12. Juni 2016
```
