### ISSUE TITLE
Reelase notes fail to mention FMT_EXPORT was renamed to FMT_LIB_EXPORT in v10

### ISSUE THREAD

**Issue by ToddWilsonBertec** [fmtlib/fmt#3423]
Not the end of the world, but having this documented in the release notes would be helpful for folks that use this define

**Comment by vitaut** [comment]
Good catch, thanks. Will update the notes.

**Comment by vitaut** [comment]
https://github.com/fmtlib/fmt/commit/0398ba42ca996ba3bfe8492c262370cb6ebd3cd0
