### ISSUE TITLE
[10.0.0] Use of std.h fails without RTTI enabled

### ISSUE THREAD

**Issue by dandee** [fmtlib/fmt#3426]
Trying to use "fmt/std.h" results in compilation error when RTTI is disabled.

```
/project/../../src/extlib/fmt/include/fmt/std.h:290:32: error: use of typeid requires -frtti
    const std::type_info& ti = typeid(ex);
                               ^
```

Reproduction:
https://godbolt.org/z/9fnbK3E5x

**Comment by vitaut** [comment]
We don't officially support building with RTTI disabled but a PR that makes that usage conditional would be welcome provided that it is not too intrusive. Alternatively, you can use {fmt} without `fmt/std.h` since the latter only provides some optional standard library formatters.
