### ISSUE TITLE
PVS report on master branch

### ISSUE THREAD

**Issue by TheNetos** [fmtlib/fmt#3431]
First, thanks for the cool library! ❤️ 

Second, running it through the [PVS static analyzer](https://pvs-studio.com/en/pvs-studio/) on Windows (MSVC v142 x64) revealed some possible problems.
Reports received on the master branch, commit 75bfe57614c0f595a26163aa151b422932e83d86

Full reports:

* [FMT.plog.zip - PVS internal report format](https://github.com/fmtlib/fmt/files/11467524/FMT.plog.zip)
* [fullhtml.zip - Exported HTML report](https://github.com/fmtlib/fmt/files/11467527/fullhtml.zip)
* [fullhtml.pdf - Exported in PDF format HTML report](https://github.com/fmtlib/fmt/files/11467557/fullhtml.pdf)

I hope this will be helpful.

**Comment by vitaut** [comment]
Interesting, thanks for sharing.
