### ISSUE TITLE
Specify minimum number of decimal digits

### ISSUE THREAD

**Issue by christosg88** [fmtlib/fmt#3435]
This is more of a question/request:

Is there a way to specify a "minimum number of decimal digits" for floating-point values?

e.g.

```cpp
double d1 = 3.0;
fmt::format("{:???.2f}", d1);  // should return "3.00"
double d2 = 3.1415;
fmt::format("{:???.2f}", d2);  // should return "3.1415"
```

Is something like this supported or _could_ it be supported?
I read the docs and I don't think that this exists currently.

**Comment by vitaut** [comment]
There is no built-in way to do this. You could probably do some post- or pre-processing to achieve this effect.
