### ISSUE TITLE
knxd fails to crosscompile with fmtlib/fmt 10.0.0

### ISSUE THREAD

**Issue by tru7** [fmtlib/fmt#3436]
compiling knxd with libfmt <= 9.1.0 worked but now fails with libfmt-10.0.0. I have no idea what the reason is.

Details:
In file included from /var/local/truniger/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/fmt/format.h:49,
                 from trace.h:33,
                 from common.h:34,
                 from apdu.h:32,
                 from eibnetip.h:33,
                 from eibnetserver.h:33,
                 from eibnetserver.cpp:20:
/var/local/truniger/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/fmt/core.h: In instantiation of 'fmt::v10::detail::value<Context> fmt::v10::detail::make_value(T&&) [with Context = fmt::v10::basic_printf_context<fmt::v10::appender, char>; T = const ConnType&]':
/var/local/truniger/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/fmt/core.h:1711:29:   required from 'fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v10::basic_printf_context<fmt::v10::appender, char>; type <anonymous> = fmt::v10::detail::type::custom_type; T = const ConnType&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]'
/var/local/truniger/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/fmt/core.h:1827:77:   required from 'fmt::v10::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const ConnType&}; Context = fmt::v10::basic_printf_context<fmt::v10::appender, char>; Args = {ConnType}]'
/var/local/truniger/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/fmt/core.h:1844:31:   required from 'constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T&& ...) [with Context = basic_printf_context<appender, char>; T = {const ConnType&}]'
/var/local/truniger/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/fmt/printf.h:649:49:   required from 'int fmt::v10::fprintf(FILE*, const S&, const T& ...) [with S = const char*; T = {ConnType}; Char = char; FILE = FILE]'
trace.h:183:17:   required from 'void Trace::TracePrintf(int, const char*, const Args& ...) [with Args = {ConnType}]'
eibnetserver.cpp:956:7:   required from here
/var/local/truniger/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/fmt/core.h:1691:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1691 |       formattable,
      |       ^~~~~~~~~~~
/var/local/truniger/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/fmt/core.h:1691:7: note: 'formattable' evaluates to false
make[6]: *** [Makefile:572: eibnetserver.o] Error 1

**Comment by vitaut** [comment]
It appears that `enum` support in `printf` has been accidentally affected by the change in the `format` functions. Will look into it.

**Comment by vitaut** [comment]
Thinking more of it, we shouldn't make `printf` handle enum in a different way than `format` does. So the way to fix the error is to either provide an explicit conversion to `int` (or whatever the underlying type of that particular enum is):

```c++
int format_as(ConnType t) { return t; }
```

or convert the argument to the underlying type at the call site using `fmt::underlying`, `std::to_underlying` or a cast, e.g.

```c++
fmt::printf("%d", fmt::underlying(t));
```

**Comment by tru7** [comment]
I don't understand why you closed it. The problem is still there with latest master, right?

**Comment by tru7** [comment]
thank you, but I'm not directly involved in the knxd project but I will inform.
Now the knxd project and all others are forced to put variants for different fmtlib/fmt versions in their source code, right?

**Comment by vitaut** [comment]
> Now the knxd project and all others are forced to put variants for different fmtlib/fmt versions in their source code, right?

No, because both solutions (`format_as` and `underlying`) work with older versions of {fmt}. The only difference is that the newer version requires them rather than just allows.
