### ISSUE TITLE
Fails to compile basic program when using clang and `std=c++2b`

### ISSUE THREAD

**Issue by vypxl** [fmtlib/fmt#3437]
Today I upgraded my system, and suddenly fmt does not compile anymore. I have used it together with clang and c++23 for a while and never had issues until now.

System:
`Linux 6.2.12-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Apr 20 14:17:37 UTC 2023 x86_64 GNU/Linux`
Friend confirmed it also happens on arch linux.

`clang++ -- version`
```
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Steps to reproduce: 

```
git clone https://github.com/fmtlib/fmt
echo '#include <fmt/format.h>' > bug.cpp
clang++ -I fmt/include -std=c++2b bug.cpp
```

Expected output: Compiles successfully

Actual output:
```
In file included from bug.cpp:1:
In file included from fmt/include/fmt/format.h:36:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/cmath:3716:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/specfun.h:43:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/stl_algobase.h:67:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/stl_iterator.h:2618:35: error: missing 'typename' prior to dependent type name 'iterator_traits<_It>::iterator_category'
      { using iterator_category = iterator_traits<_It>::iterator_category; };
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

I only noticed this issue with fmt, is it an fmt bug, or a clang bug, or a libstdc++ bug?

**Comment by vypxl** [comment]
Note, `g++` compiles successfully (except for the fact that there is no main method in bug.cpp)

**Comment by phprus** [comment]
Please, test next source:
```
echo '#include <cmath>' > bug.cpp
```

I guess, this is incompatibility between libstdc++13 and clang-15 (Only clang-16 is support more optional typename: https://en.cppreference.com/w/cpp/compiler_support).

**Comment by vypxl** [comment]
cmath, and the next headers all have the problem.
I did some digging. The error stems from `<bits/std_iterator.h>` (as the error message says). 

Weirdly, in the gcc source I can't find the erronous line, only the correct version: https://github.com/gcc-mirror/gcc/blob/1871740c7803c2aea20f651f57b413bc425a051c/libstdc%2B%2B-v3/include/bits/stl_iterator.h#LL2338C70-L2338C70

The last change there was 2 years ago?

**Comment by vypxl** [comment]
I think this is not an fmt bug, sorry for that.
But where should I report it?

**Comment by vitaut** [comment]
I suggest reporting to libstdc++. They should have some checks to ensure that optional typename is actually supported.

**Comment by vypxl** [comment]
Just for reference, turns out it is indeed an incompatibility issue between clang 15 and libstdc++ 13. When using c++2b, libstdc++ assumes it can use the 'make typename more optional' feature, which clang only supports from version 16.

So @phprus was right.

My solution: just put the missing typename into that header file lol
Or you could downgrade gcc 12 / upgrade to clang 16.

**Comment by loynoir** [comment]
Same `stl_iterator.h:2618:35`

Workaround

```cmake
set_property(TARGET foobar PROPERTY CXX_STANDARD 20)
```
