### ISSUE TITLE
Visual studio 2017 can no longer compile code including xchar.h

### ISSUE THREAD

**Issue by edo9300** [fmtlib/fmt#3438]
The title really says it all, I was trying to update my program to work with the the v10 release, but kept getting random errors, I managed to shrink them down to a very basic program
https://godbolt.org/z/91YdGosxY
```cpp
#include <fmt/format.h>
#include <fmt/xchar.h>

int main() {
  fmt::print("hello world\n");
}
```
As soon as ``#include <fmt/xchar.h>`` is removed the program compiles properly

**Comment by edo9300** [comment]
Actually it's "enough" to just include that header file to make the compiler fail to compile anything
```cpp
#include <fmt/xchar.h>

int main() {
    return 0;
}
```

**Comment by vitaut** [comment]
Looks like a bug in MSVC, please report to Microsoft. As a workaround you can disable `constexpr` by setting the `FMT_USE_CONSTEXPR` macro to 0.
