### ISSUE TITLE
fmt 10 won't format using a cast operator

### ISSUE THREAD

**Issue by madscientist** [fmtlib/fmt#3440]
Godbolt doesn't seem to have support for fmt 10.0.0 yet, so I can't provide a link.  But this code has worked correctly with all versions of fmt up to and including 9.1: it's failing in fmt 10.0.0:
```
#include <fmt/format.h>

struct foo {
    operator const char *() const { return foo; }
    const char* foo;
};

void show(foo &f) {
    fmt::print("{}", f);
}
```
Is it expected that cast operators no longer work?

**Comment by NIKEA-SOFT** [comment]
I support, I also wanted to leave an issue on this topic, in version 10 (fmt) my code broke and now the cast operators have stopped working.

**Comment by madscientist** [comment]
That is frustrating.  I have many of types of all kinds (not just hundreds of enums, but wrapper classes, templates, etc.) which used to format correctly with no extra work, that will require significant amounts of new code with fmt 10.  format_as, which is limited in its abilities, shouldn't be suggested as the panacea for this loss of capability; it may work for enum (but still must be added everywhere) but it's insufficient for all the places that used to work easily and now require custom formatters to be created, with the associated overhead.

I'll have to stay with fmt 9.1 for now and hope for improvements in the future, or else a week where I don't have anything better to do than write boilerplate code.

**Comment by vitaut** [comment]
You should be able to solve this with a few generic `format_as` functions. For example, all your enums need a single function, not one per enum. There is even one in {fmt} which only needs to be injected in your namespace via a `using` declaration: https://github.com/fmtlib/fmt/blob/552c43aba9d2f4fcc5309d49e586ddc90c90348c/include/fmt/format.h#L4353

Similarly for other targets of implicit conversions.

**Comment by madscientist** [comment]
Sorry, but I'm too dumb to understand your comment.  I have enums at global scope, and I have enums inside classes.  Unfortunately we don't use namespaces in a large majority of our code.  Simply adding *using fmt::format_as;* at global scope doesn't seem to make a difference so that must not be what you meant.  The only way I have found to avoid errors is to create *auto format_as(Enum e) noexcept { return fmt::underlying_t<Enum>(e); }* or something similar to that, for every *Enum* type (or *Class::Enum* for enum types declared inside classes).  It also doesn't work for my string-like classes (such as the one in my example above); I need to write an explicit format_as() for it.

As for my wrapper for std::atomic<> and other templated types, I haven't found any alternative to writing a full formatter such as:
```
template <typename T>
struct bar {
    operator T() const { return base.load(); }
    std::atomic<T> base;
};

template <typename T>
struct fmt::formatter<bar<T>> : formatter<T>
{
    template <typename FormatContext>
    auto format(const bar<T>& b, FormatContext& ctx) const {
        T v = b;
        return formatter<T>::format(v, ctx);
    }
};
```
If there are easier ways to handle all this that would be great!

**Comment by madscientist** [comment]
Oh I see it's actually fmt::enums::format_as.  OK I'll investigate this.

**Comment by madscientist** [comment]
Hm, it works _except_ that some but not all of my enums yield link errors, like `error: undefined reference to 'format_as(MyEnum)'`.  I haven't figured out yet why these particular enums are not liked.  I'll have to investigate more deeply.

**Comment by madscientist** [comment]
The link errors related to enums were due to some leftover attempts I made at solving this problem that I forgot to clean up.  All good now.  If anyone has any ideas on if there's a more straightforward way to solve my other issues, than writing a custom formatter, I'm interested in hearing it.
