### ISSUE TITLE
format_as not working properly with non char strings

### ISSUE THREAD

**Issue by edo9300** [fmtlib/fmt#3441]
Since the removal of the ADL ``to_string_view`` lookup in the latest version, I tried replacing that usage by using the new ``format_as`` approach to format my custom types as if they were strings, but I'm encountering various issues when making my type be formatted as a string type that is not a ``basic_string<char>``.

This is how i was using the ``to_string_view`` approach ant that worked up to 9.1.0
https://godbolt.org/z/hqaGKWMvz

this is using ``format_as``
https://godbolt.org/z/odMz4a9fc

Based off the docs and release notes I expect them to behave the same way, but ``format_as`` only works when I'm formatting a ``char`` string.
Is it intentional, or a regression?

**Comment by vitaut** [comment]
You are right, `format_as` only supports `char`. You'll need to provide a `formatter` specialization for other code unit types.

**Comment by vitaut** [comment]
The `printf` implementation only supports a subset of types. I would recommend switching to `format` functions, especially if you want to format user-defined types.
