### ISSUE TITLE
make_format_args API change, breaking C++20 compat

### ISSUE THREAD

**Issue by tycho** [fmtlib/fmt#3443]
So in commit 8f18e72df576ebfbd088a57a5c6cae8d4d0fc3dc the type of `args` for `fmt::make_format_args` changed from `T&&` to `T&`. This no longer matches the C++20 standard library equivalent:

https://en.cppreference.com/w/cpp/utility/format/make_format_args

It's my understanding that the intent of this project is to be as close to a drop-in replacement for std::format as possible. It also looks like C++20's choice of the `T&&` type follows this defect report:

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2418r2.html

To explain why I'm reporting this, spdlog does this:

```cpp
    // common implementation for after templated public api has been resolved
    template<typename... Args>
    void log_(source_loc loc, level::level_enum lvl, string_view_t fmt, Args &&... args)
    {
        bool log_enabled = should_log(lvl);
        bool traceback_enabled = tracer_.enabled();
        if (!log_enabled && !traceback_enabled)
        {
            return;
        }
        SPDLOG_TRY
        {
            memory_buf_t buf;
#ifdef SPDLOG_USE_STD_FORMAT
            fmt_lib::vformat_to(std::back_inserter(buf), fmt, fmt_lib::make_format_args(std::forward<Args>(args)...));
#else
            fmt::vformat_to(fmt::appender(buf), fmt, fmt::make_format_args(std::forward<Args>(args)...));
#endif

            details::log_msg log_msg(loc, name_, lvl, string_view_t(buf.data(), buf.size()));
            log_it_(log_msg, log_enabled, traceback_enabled);
        }
        SPDLOG_LOGGER_CATCH(loc)
    }

```

Which no longer works with `T&`:

> 3>...\spdlog\include\spdlog\logger.h(374,54): error : no matching function for call to 'make_format_args'
> 3>...\spdlog\include\spdlog\logger.h(90,9): message : in instantiation of function template specialization 'spdlog::logger::log_<const char *>' requested here
> 3>..\..\code\script.cpp(688,3): message : in instantiation of function template specialization 'spdlog::logger::log<const char *>' requested here
> 3>...\spdlog\include\spdlog\spdlog.h(344,46): message : expanded from macro 'SPDLOG_LOGGER_ERROR'
> 3>...\spdlog\include\spdlog\spdlog.h(306,19): message : expanded from macro 'SPDLOG_LOGGER_CALL'
> 3>...\fmt\include\fmt\core.h(1812,16): message : candidate function [with Context = fmt::basic_format_context<fmt::appender, char>, T = <const char *>] not viable: expects an lvalue for 1st argument

**Comment by vitaut** [comment]
The change is intentional: it is unsafe to pass rvalue references to `make_format_args`. I plan to submit a paper to fix this in the standard as well. As for the spdlog issue, it should be easily fixable by removing forwarding which doesn't make sense anyway.

**Comment by tycho** [comment]
Understood, thank you for taking a look.
