### ISSUE TITLE
warning C4800 emitted for fmtlib 10.0.0

### ISSUE THREAD

**Issue by adesitter** [fmtlib/fmt#3444]
When building
  return WriteConsoleW(reinterpret_cast<void*>(_get_osfhandle(fd)), u16.c_str(),
                       static_cast<uint32_t>(u16.size()), &written, nullptr);

Visual Studio 2019 with suitable warning emits:

fmt\include\fmt\format-inl.h(1460,23): warning C4800: Implicit conversion from 'int' to bool. Possible information loss

  return WriteConsoleW(reinterpret_cast<void*>(_get_osfhandle(fd)), u16.c_str(),
                       static_cast<uint32_t>(u16.size()), &written, nullptr) != 0;
would fix it.

**Comment by vitaut** [comment]
Could you submit a PR?

**Comment by msmolensky** [comment]
It is a different issue:

fmt/format.h(1055,56): warning C4275: non dll-interface class 'std::runtime_error' used as base for dll-interface class 'fmt::v10::format_error'

In v 10.0.0, FMT_CLASS_API macro is missing in core.h (lines 191 and 197) and in format.h (line 1055) which causes the above warning in MSVC

**Comment by vitaut** [comment]
As already commented elsewhere:

> Looks the same as #3444. If it's a different issue please provide a godbolt repro.
