### ISSUE TITLE
LWG 3636

### ISSUE THREAD

**Issue by ecatmur** [fmtlib/fmt#3447]
Per https://cplusplus.github.io/LWG/issue3636, formatters should have `format() const`. Failure to enforce this impedes compatibility with standard formatting i.e. once we've written formatters for fmt, we need to go and add `const` on `format()` to make them compatible with std::format.

Please consider enforcing that `formatter<T>::format()` specialization member functions can be called `const`. Perhaps this could be done with deprecation initially.

**Comment by ecatmur** [comment]
```c++
#include <fmt/format.h>
#include <format>

struct A {};
template<>
struct fmt::formatter<A> {
    auto format(A, auto& ctx) /* const */ -> decltype(ctx.out());
    constexpr auto parse(auto& ctx) { return ctx.begin(); }
};
template<>
struct std::formatter<A> : fmt::formatter<A> {};

int main() {
    (void) fmt::format("{}", A()); // 1
    (void) std::format("{}", A()); // 2
}
```

compiles (1) but fails to compile (2). Uncommenting the `/* const */` makes both compile. https://godbolt.org/z/jWPGs49Ka

**Comment by infdahai** [comment]
maybe just add the `const` flag to the template.

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/d70729215fba1d54862e407b626abf86ddf409bf.
