### ISSUE TITLE
strtod_l() not found for Android arm64-v8a configuration

### ISSUE THREAD

**Issue by gomons** [fmtlib/fmt#345]
When I build the library using android-ndk-r10e for arm64-v8a configuration and I get error:
`fmt/posix.h:387:48: error: 'strtod_l' was not declared in this scope`

**Comment by vitaut** [comment]
Thanks for the bug report. Does https://github.com/fmtlib/fmt/commit/c7739536e8e1ec844527620a2669393a6e3df130 fix the problem?

**Comment by gomons** [comment]
I downloaded version 3.0.0 and make changes like in c773953 and the error disappeared. Thank you a lot!
