### ISSUE TITLE
Add more previous Release versions in Version Switcher?

### ISSUE THREAD

**Issue by hwhsu1231** [fmtlib/fmt#3455]
I noticed that the [Documentation](https://fmt.dev/10.0.0/) of `fmt` is generated by Sphinx. And there is a Version Switcher displayed in its Navigation Bar, which reminds me of the [CMake Documentation](https://cmake.org/cmake/help/latest/). However, there are only `9.0.0`, `9.1.0`, and `10.0.0` currently. I wondered why not add more previous Release versions in Version Switcher?

It seems that the documentations of those previous versions still exist:

* 8.0.0: https://fmt.dev/8.0.0/
* 7.0.0: https://fmt.dev/7.0.0/
* 6.0.0: https://fmt.dev/6.0.0/
* 5.0.0: https://fmt.dev/5.0.0/

![image](https://github.com/fmtlib/fmt/assets/71438617/22c995d0-d021-4d44-b324-57b44cec59a7)

**Comment by vitaut** [comment]
Thanks for the suggestion but those version are no longer supported so there is no need to clutter the menu.

**Comment by hwhsu1231** [comment]
It seems that items available in Version Switcher are hardcoded in fmt Documentation:

https://github.com/fmtlib/fmtlib.github.io/blob/612b83dcf8cec92fa7be8f422b5ad754f1902538/10.0.0/index.html#L77-L81

How about take CMake for reference, using a [version_switch.js](https://cmake.org/cmake/help/version_switch.js) to implement?

**Comment by vitaut** [comment]
The site is statically generated, we don't need JS for that.
