### ISSUE TITLE
Consistent format for integral floats

### ISSUE THREAD

**Issue by jwnimmer-tri** [fmtlib/fmt#3456]
This is halfway between a question and a bug report of a regression.  I'm not sure which.

Here's the sample program (on [godbolt](https://godbolt.org/z/9Po6W8j37)):

```c++
#include <fmt/format.h>

std::string PrettyFormat(double x) {
  return fmt::format("{:#}", x);
}

int main() {
  fmt::print("{}\n", PrettyFormat(1.11));
  fmt::print("{}\n", PrettyFormat(1.1));
  fmt::print("{}\n", PrettyFormat(1.0));
}
```

---

My projects allow the user to build against almost any version of fmt.  I would like my project's formatted output to be consistent no matter which version of fmt the user selects, for better reproducibility.

I would like to find a spelling for `PrettyFormat` that produces the same output on all versions of fmt:
```
1.11
1.1
1.0
```

For version 9 and prior, the pattern `{:#}` always appended the trailing `0` on integral floating-point values.  (The pattern `{}` has varied over time as to whether the `.0` was appended, depending on the version of fmt, but `{:#}` had been consistent.)

As of fmt 10, the final number now prints as `1.` with no trailing zero, and I cannot figure out any formatting syntax that produces my desired result.

---

My first question is whether this change was intentional?  I did not see it mentioned in the release notes.  I also looked over all of the mentioned PRs in the release notes that seemed like they might affect this, and I didn't see it discussed there either.

If the change was intentional, it might be worth amending the release notes to clarify for other people with the same question, that the empirical formatting behavior has changed.

If the change was intentional, does anyone have a suggestion for a format syntax that produces what I want in fmt 10?  Ideally it would also work with prior fmt versions, but I'm okay with `#ifdef` based on fmt version if need be.

I'm hoping to avoid formatting to a string and then manually tacking on `0` if the string ends with `.`, since I suspect that would be a performance pessimization.

**Comment by vitaut** [comment]
The old behavior didn't conform to the spec (http://eel.is/c++draft/tab:format.type.float), wasn't documented in {fmt} and was changed for compatibility with `std::format`. I'll mention this in the changelog. There is no builtin method to get the exact format you want so you'll have to append zero in case of a trailing `.` (possibly putting this in a custom `formatter`). If you'd like the behavior of `#` changed, I recommend opening an LWG issue: https://www.open-std.org/jtc1/sc22/wg21/docs/lwg-prep.html.

**Comment by jwnimmer-tri** [comment]
Perfect, thanks for the clarification.
