### ISSUE TITLE
Formatting Eigen matrices with fmt 9+

### ISSUE THREAD

**Issue by jdumas** [fmtlib/fmt#3465]
Hi.

The following piece of code used to work fine under fmt 8:
```c++
#include <Eigen/Dense>
#include <fmt/format.h>
#include <fmt/ostream.h>

#include <iostream>

void foo() {
    Eigen::MatrixXd M;
    std::cout << fmt::format("matrix {}", M) << std::endl;
}
```

However, this fails to compile on fmt 9+. Reading the release notes, it seems that fmt no longer uses the `<<` operator to format custom types?? So what is the point of  `#include <fmt/ostream.h>` then?

Do you have any advice on how Eigen types should be formatted? I'd rather avoid having to pad all my args with `fmt::streamed(M)`, which will make fmt and spdlog unusable for practical purposes. I cannot define a `format_as()` or a `fmt::formatter<>` for those types either, since they are from a shared third-party library.

I'm a bit stumped as to what's the best way to move forward on this, in a way that can keep my code compatible with fmt 8 and 9+ at the same time.

**Comment by vitaut** [comment]
`fmt/ostream.h` provides APIs such as `fmt::ostream_formatter` to opt into formatting via `std::ostream`: https://fmt.dev/latest/api.html#ostream-api.

Ideally Eigen would provide formatters for its types. It can even be done without introducing a hard dependency on {fmt}, something like

```c++
#if __has_include(<fmt/core.h>)
#  include <fmt/core.h>

// Provide formatter specializations or overloads of format_as.
#endif
```

The next best option is using `fmt::streamed`.

**Comment by jdumas** [comment]
Can you provide some context as to why the old `<<` behavior was removed? As things stand, even if the Eigen folks add support for custom formatters, it's gonna be a while before a new stable release come out with this feature. I can't add a custom fmt::formatter in my own library, because it's gonna cause ODR violations if other people do the same... And adding `fmt::streamed` everywhere is gonna be a nightmare of readability.

I really wish there was a way to write a custom formatter in user-space without requiring adding to the original type's namespace.

**Comment by vitaut** [comment]
As stated in release notes it was first deprecated and then remove mostly because of ODR violations although there were other less glaring problems as well (e.g. incompatibility with `std::format`).

> I really wish there was a way to write a custom formatter in user-space without requiring adding to the original type's namespace.

`formatter` specializations are not added to the original type's namespace.

The only way to do what you want is to define your own (wrapper) formatting function because otherwise there will always be a potential for some conflict between user-defined formatters, regardless of how they are specified.

**Comment by jdumas** [comment]
Honestly I'm very surprised that `std::format` itself doesn't support printing custom types via the `operator <<`. Imho this is gonna make it very impractical and slow down adoption considerably. But hey maybe in 2050 everyone will finally support custom std formatter...

Can you give an example of ODR violation caused by the old `operator <<` behavior? In which case is that an issue?

> formatter specializations are not added to the original type's namespace.

My bad. But the problem still remains, that if client libraries define a partial formatter specialization for a third-party type (in this case Eigen matrices), we'll end up right back were we started (ODR violations due to conflicting formatter specialization). So I don't see how not supporting `operator <<` solves anything tbh.

> The only way to do what you want is to define your own (wrapper) formatting function because otherwise there will always be a potential for some conflict between user-defined formatters, regardless of how they are specified.

Do you have a suggestion on how I could go about it? I am mostly using `fmt` through spdlog. Should I ask the spdlog folks directly? Or do you know if I can define my own logger type that forwards arguments through `fmt::streamed` when available rather than resulting in a compile error?

**Comment by mwinterb** [comment]
> Honestly I'm very surprised that `std::format` itself doesn't support printing custom types via the `operator <<`. Imho this is gonna make it very impractical and slow down adoption considerably. But hey maybe in 2050 everyone will finally support custom std formatter...
> 
> Can you give an example of ODR violation caused by the old `operator <<` behavior? In which case is that an issue?
> 
https://github.com/fmtlib/fmt/issues/2357

**Comment by vitaut** [comment]
You could probably wrap a logging function but I don't know enough about spdlog to give a specific suggestion.

**Comment by jdumas** [comment]
> https://github.com/fmtlib/fmt/issues/2357

Thanks for the reference. So, if I understand correctly, the problem is that we have this overloaded `map` function, that expands to different functions whether or not `ostream` is in scope. And because these functions have the same signature we end up with an ODR violation?

@vitaut do you think this is something that could be avoided with inlined namespaces, where you'd put the overloaded ostream-based `map` function for example?

**Comment by vitaut** [comment]
The model was fundamentally broken and couldn't be fixed with inline namespaces or anything else. The only way you can make implicit ostream support work is by providing your own formatting function with a custom mapping illustrated on the following example:

```c++
#include <fmt/ostream.h>

struct Matrix {
  friend std::ostream& operator<<(std::ostream& os, const Matrix&) {
    return os << "matrix";
  }
};

template <typename T>
decltype(auto) map(T& arg) {
  if constexpr (std::is_same_v<T, Matrix>)
    return fmt::streamed(arg);
  else
    return arg;
}

template <typename... T>
std::string myformat(fmt::string_view fmt, T&&... args) {
  return fmt::format(fmt::runtime(fmt), map(args)...);
}

int main() {
  auto s = myformat("{}", Matrix());
  fmt::print("{}", s);
}
```

https://godbolt.org/z/s9v13cecs
