### ISSUE TITLE
errors about c2666 c2899

### ISSUE THREAD

**Issue by Z-SmallRock** [fmtlib/fmt#3469]
hey ! When compiling with vs2015, I found a lot of errors. The following is the vs version and error information. What can I do to deal with this problem? Looking forward to your reply.
![26b087846bdd912761f9143e9936fc8](https://github.com/fmtlib/fmt/assets/43021784/fba62699-f945-46d3-9185-2f6a72f249bf)
![0c7a53ca9fd2bc8c10c83ce196f2b35](https://github.com/fmtlib/fmt/assets/43021784/44d80fe4-d8ae-4126-9872-89d58354b65b)

**Comment by vitaut** [comment]
MSVC 2015 is likely too broken to compile {fmt} which requires at least some minimal C++ standard compatiblity.
