### ISSUE TITLE
 chrono: undefined behavior: store to null pointer converted to trap

### ISSUE THREAD

**Issue by scamille** [fmtlib/fmt#3470]
When trying to upgrade from fmt 9 to fmt 10, I encountered an issue with one of our "embedded" targets, a Qualcomm Hexagon DSP.
Unfortunately, I can not give an example replicating the exact error on compiler explorer since the target is not supported. I know that this pretty much makes it impossible to easily replicate.
A simple example that leads to an error with the custom compiler would be [this](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:6,positionColumn:1,positionLineNumber:6,selectionStartColumn:1,selectionStartLineNumber:6,startColumn:1,startLineNumber:6),source:'%23include+%3Cfmt/chrono.h%3E%0A%23include+%3Cfmt/format.h%3E%0A%0A%23include+%3Calgorithm%3E%0A%23include+%3Coptional%3E%0A%0Aint+main()+%7B%0A++++auto+now%7Bstd::chrono::system_clock::now()%7D%3B%0A++++auto+in_time_t++++%3D+std::chrono::system_clock::to_time_t(now)%3B%0A++++auto+milliseconds+%3D+std::chrono::duration_cast%3Cstd::chrono::milliseconds%3E(now.time_since_epoch()).count()+%25+1000%3B%0A++++const+std::string+timestamp+%3D+fmt::format(%22%7B:%25Y%25m%25d_%25H%25M%25S%7D_%7B:03d%7D%22,+fmt::localtime(in_time_t),+milliseconds)%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang1100,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:fmt,ver:trunk)),options:'-O2+-Wall+-fno-zero-initialized-in-bss+-fdata-sections+-Wall+-Wextra+-Wpedantic+-O3+-DNDEBUG+-fPIC+-pthread+-std%3Dc%2B%2B20+-Werror',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+11.0.0+(Editor+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+11.0.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+11.0.0+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

I replicated the problem with both the 10.0.0 release (a0b8a92e3d1532361c2f7feb63babc5c18d00ef2) and current master(bd393456ed94a5d64bb6078aa3fa477ceeb621d9)
The following error logs are from a 10.0.0 build.

Error message:
```text
[build] In file included from x.cpp:8:
[build] In file included from include/fmt/chrono.h:21:
[build] /include/fmt/format.h:2460:20: error: undefined behavior: store to null pointer converted to trap [-Werror,-Wundefined-optimized]
[build] FMT_CONSTEXPR auto write(OutputIt out, T value) -> OutputIt {
[build]                    ^
```

Relevant build settings:
```
 -DHEXAGON -mv69 -G0 -Wall -fno-zero-initialized-in-bss -fdata-sections -mhvx -mhvx-length=128B -Wall -Wextra -Wpedantic -O3 -DNDEBUG -fPIC -pthread -std=c++20 -Werror -MD -MT x.cpp.obj -MF x.cpp.obj.d -o 
```

Compiler seems to be a custom build of Clang/LLVM version 11.0.0
```
hexagon-clang++ --version

QuIC LLVM Hexagon Clang version 8.5.15
Target: hexagon
Thread model: posix
```

Furthermore, the issues only appears with `-O2` or `-O3` optimization level, not with `-O1`.

The same happens with another version of this "hexagon compiler" which is based on clang 13.0.0

At this point, I really don't know whether this is a (general) compiler issue, something in fmt that also gets exposed on this platform, or maybe also something specific to chrono on that platform.

**Comment by vitaut** [comment]
It's hard to say anything specific without a repro. I would recommend trying to debug where the null pointer is coming from and/or bisect to the commit that introduced the problem.
