### ISSUE TITLE
core.h is using deleted constructor

### ISSUE THREAD

**Issue by yitzchak** [fmtlib/fmt#3472]
It appears that https://github.com/fmtlib/fmt/blob/b2106f3639dda5b311966047d1a146edc5f4e663/include/fmt/core.h#L2523
is referring to the deleted constructor https://github.com/fmtlib/fmt/blob/b2106f3639dda5b311966047d1a146edc5f4e663/include/fmt/core.h#L1061-L1067

**Comment by vitaut** [comment]
This error indicates that you are trying to format a type that doesn't have a formatter. If you post the full error including context we can tell exactly what the problematic type is.
