### ISSUE TITLE
Examples for UDT formatters in the documentation won't work with compiled format strings

### ISSUE THREAD

**Issue by erinacio** [fmtlib/fmt#3487]
The examples in [API Reference :: Formatting User-Defined Types](https://fmt.dev/10.0.0/api.html#formatting-user-defined-types) use `format_context` for the second parameter of `format` method. This won't work with `FMT_COMPILE(...)` or `..._cf` as the format context type with compiled format string would be a different one. This is neither documented in [API Reference :: Formatting User-Defined Types](https://fmt.dev/10.0.0/api.html#formatting-user-defined-types) nor in [API Reference :: Format String Compilation](https://fmt.dev/10.0.0/api.html#format-string-compilation), and the compilation error message is `error: call to 'write' is ambiguous` which looks confusing to me, taking me half an hour to find the root cause. Would be great if such information is added to the documentation and the examples for udt formatters are updated for supporting compiled format strings.

**Comment by vitaut** [comment]
Clarified in https://github.com/fmtlib/fmt/commit/95e1ea57371fc044524574c170d53d97cdec2a13. Thanks for the suggestion.
