### ISSUE TITLE
Passing the field width as an argument

### ISSUE THREAD

**Issue by gnzlbg** [fmtlib/fmt#349]
How do I pass the field width as an argument? All the examples that use a field width have it hardcoded in the string, e.g.,  `format("{:<30}", "left aligned");`

**Comment by vitaut** [comment]
And applying to your example, @gnzlbg, what @mwinterb wrote, we get:

```c++
format("{:<{}}", "left aligned", 30);
```

**Comment by gnzlbg** [comment]
Thanks you two!
