### ISSUE TITLE
How to use the fmt::print() function correctly to output wstring and wchar_t to the console window?

### ISSUE THREAD

**Issue by Tanya2007** [fmtlib/fmt#3490]
Please tell me how I can use the fmt::print function for wstring and the wchar_t buffer. I'm writing the following code: 

`#include <fmt/xchar.h>` 
`std::wstring v = L"name";`
`fmt::vprint(fmt::wstring_view(L"Hello{}"), fmt::make_wformat_args(v)); `

But the program compiles with an error:
"no matching function for call to 'fmt::v10::basic_format_args<fmt::v10::basic_format_context<std::back_insert_iterator<fmt::v10::detail::buffer<wchar_t> >, wchar_t> >::basic_format_args(std::wstring&)"
Tell me how to fix the error? Or what function should I use to output wide characters to the console?
Thank you in advance)

**Comment by vitaut** [comment]
```c++
#include <fmt/xchar.h>

int main() {
  std::wstring v = L"name";
  fmt::print(L"Hello{}", v); 
}
```

**Comment by Tanya2007** [comment]
Thank you very much, it really works when wstring is in Latin. But when I try to apply Cyrillic the program compiles, but when I start I get an error: "Hello terminate called after throwing an instance of 'std::system_error'
  what():  cannot write to file: Illegal byte sequence". 

`#include <fmt/xchar.h>`

`int main() `
`{`
 ` std::wstring v = L"Таня";`
  `fmt::print(L"Hello {}", v); `
`}`

Please tell me how I can use fmt to output Cyrillic to the console?

**Comment by vitaut** [comment]
#3491
