### ISSUE TITLE
How to use the fmt::print() function correctly to output the Cyrillic wstring and wchar_t to the console window?

### ISSUE THREAD

**Issue by Tanya2007** [fmtlib/fmt#3491]
Please help me. When I try to apply Cyrillic the program compiles, but when I start I get an error: "Hello terminate called after throwing an instance of 'std::system_error'
what(): cannot write to file: Illegal byte sequence".

`#include <fmt/xchar.h>`

`int main() `
`{`
 `std::wstring v = L"Таня";`
`fmt::print(L"Hello {}", v); `
`}`

Please tell me how I can use fmt to output Cyrillic to the console?

**Comment by vitaut** [comment]
The error comes from `fputws`, not {fmt}. In general using wide strings for console output is not recommended. A more reliable way to print Unicode portably is to use ordinary strings (https://godbolt.org/z/v69n3vPfx) and compile with `/utf-8` on Windows.

**Comment by Tanya2007** [comment]
Yes, it works when the string is a set of char characters, but when debugging such a string, I see not Cyrillic, but some hieroglyphs. The IDE normally displays Cyrillic in the debugger, only if these are wide characters. We'll have to come up with a crutch again. And I was so happy when I found your library that it can normally output Cyrillic to the console. Sadness ((.
