### ISSUE TITLE
Formatting std::filesystem::path on Windows escapes valid path character

### ISSUE THREAD

**Issue by DominikGrabiec** [fmtlib/fmt#3495]
On Windows formatting a `std::filesystem::path` results in all directory separators being escaped as it's using the generic string escaping function.

Using this simple program:
```
#include <filesystem>
#include <fmt/std.h>

int main()
{
	std::filesystem::path path{"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE"};
	fmt::print("fmt: {}\n", path);
	return 0;
}
```
**Actual Result:**
`fmt: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE"`

**Expected result:**
`fmt: "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE"`

The simplest solution might be to just _not_ escape the path on Windows other than enclosing it in quotes.

**Comment by vitaut** [comment]
This is consistent with ostream, the C++ escaping and allows escaping quotes themselves. You can format unquoted path by passing `path.string()` or similar.
