### ISSUE TITLE
bug report: format error when using `fmt::fg` and brackets "{}"

### ISSUE THREAD

**Issue by bowen-xu** [fmtlib/fmt#3498]
An error raises when we have
```Cpp
auto str1 = fmt::format(fmt::fg(fmt::rgb(193,137,191), "{instance}");
```

However, it would be ok if we use

```Cpp
auto str1 = fmt::format(fmt::format(fmt::fg(fmt::rgb(193,137,191), "{{}}"), "{instance}");
```

There seems some bug on the color formating.

**Comment by vitaut** [comment]
There are two bugs in your first example, a missing closing parenthesis and unescaped braces. Here's a fixed version:

```c++
auto str1 = fmt::format(fmt::fg(fmt::rgb(193,137,191)), "{{instance}}");
```

Please see the docs: https://fmt.dev/latest/index.html.
