### ISSUE TITLE
Can't format atomic enum class

### ISSUE THREAD

**Issue by mark-99** [fmtlib/fmt#3499]
Hi, if you have an atomic<T> where T is not a fundamental type, but does itself have a formatter, e.g. an enum class, it doesn't format.

https://godbolt.org/z/hszK48oqx

Here is my workaround, not sure if there's a better way to do it?

```
template<class T>
struct fmt::formatter<std::atomic<T>> : formatter<T>
{
    template<typename FormatContext>
    auto format(std::atomic<T> const& x, FormatContext& ctx) const
    {
        return formatter<T>::format(x.load(), ctx);
    }
};
```

**Comment by vitaut** [comment]
You could also use `format_as`, see https://fmt.dev/latest/api.html#formatting-user-defined-types.

**Comment by vitaut** [comment]
{fmt} doesn't provide a formatter for `std::atomic` but a PR to add one would be welcome.
