### ISSUE TITLE
conflict with  CoreServices.h under Mac OSX

### ISSUE THREAD

**Issue by gabime** [fmtlib/fmt#350]
As reported [here](https://github.com/gabime/spdlog/issues/113) by spdlog users

**Comment by vitaut** [comment]
Thanks for the bug report. I've localized the problem to the `check` macro defined in ` AssertMacros.h` and will fix it shortly.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/8631694021ccba79b6907b27ccca6f23575ea31a.
