### ISSUE TITLE
ADD_LIBRARY for library fmt without any source files

### ISSUE THREAD

**Issue by 07anhad** [fmtlib/fmt#3501]
-- CMake version: 3.8.2
-- Version: 10.0.1
-- Build type: Release
You have called ADD_LIBRARY for library fmt without any source files. This typically indicates a problem with your CMakeLists.txt file
-- FMT_PEDANTIC: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /xyz/xyz/anhadp/fmt-lib/fmt-master

**Comment by 07anhad** [comment]
Might be a problem with my cmake command, not able to understand it
On a linux system

/grid/common/pkgs/cmake/v3.8.2/bin/cmake -DBUILD_SHARED_LIBS=TRUE /xyz/xyz/anhadp/fmt-lib/fmt-master

**Comment by vitaut** [comment]
Sources are added via `target_sources` so you can ignore this message from an old version of CMake.
