### ISSUE TITLE
Unexcepted SIGSEGV upon calling fmt::format

### ISSUE THREAD

**Issue by florimond-collette** [fmtlib/fmt#3503]
Today we encountered an unexpected SIGSEGV. Platform Linux 32-bit. Compiler GCC 5.4.0.

> received signal SIGSEGV, Segmentation fault.
> 0xdb3b86a6 in __memmove_ssse3_rep () from /lib/libc.so.6
> (gdb) where
> #0  0xdb3b86a6 in __memmove_ssse3_rep () from /lib/libc.so.6
> #1  0xaadc2f61 in std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<char> (__first=0x5a353125 "", __last=0xd055519a "", __result=0x9dfd008 "") at /usr/local/include/c++/5.4.0/bits/stl_algobase.h:384
> #2  0xaae06bb6 in std::__copy_move_a<false, char const*, char*> (__first=0x5a353125 "", __last=0xd055519a "", __result=0x9dfd008 "") at /usr/local/include/c++/5.4.0/bits/stl_algobase.h:402
> #3  0xaae06b4b in std::__copy_move_a2<false, char const*, char*> (__first=0x5a353125 "", __last=0xd055519a "", __result=0x9dfd008 "") at /usr/local/include/c++/5.4.0/bits/stl_algobase.h:440
> #4  0xaae06aba in std::copy<char const*, char*> (__first=0x5a353125 "", __last=0xd055519a "", __result=0x9dfd008 "") at /usr/local/include/c++/5.4.0/bits/stl_algobase.h:472
> #5  0xaae0690b in std::__uninitialized_copy<true>::__uninit_copy<char const*, char*> (__first=0x5a353125 "", __last=0xd055519a "", __result=0x9dfd008 "") at /usr/local/include/c++/5.4.0/bits/stl_uninitialized.h:93
> #6  0xaae0407a in std::uninitialized_copy<char const*, char*> (__first=0x5a353125 "", __last=0xd055519a "", __result=0x9dfd008 "") at /usr/local/include/c++/5.4.0/bits/stl_uninitialized.h:126
> #7  0xaadfff5f in std::__uninitialized_copy_n<char const*, unsigned int, char*> (__first=0x5a353125 "", __n=1981816949, __result=0x9dfd008 "") at /usr/local/include/c++/5.4.0/bits/stl_uninitialized.h:666
> #8  0xaadf892a in std::uninitialized_copy_n<char const*, unsigned int, char*> (__first=0x5a353125 "", __n=1981816949, __result=0x9dfd008 "") at /usr/local/include/c++/5.4.0/bits/stl_uninitialized.h:682
> #9  0xaadf194f in fmt::v10::detail::buffer<char>::append<char> (this=0xd831bd2c, begin=0x5a353125 "", end=0xd055519a "") at /var/opt/h/format.h:884
> #10 0xaadee46e in fmt::v10::detail::copy_str<char, char const*> (begin=0x5a353125 "", end=0xd055519a "", out=...) at /var/opt/h/core.h:1608
> #11 0xaadeb582 in fmt::v10::detail::copy_str_noinline<char, char const*, fmt::v10::appender> (begin=0x5a353125 "", end=0xd055519a "", out=...) at /var/opt/h/format.h:652
> #12 0xaade97d5 in fmt::v10::detail::write<char, fmt::v10::appender> (out=..., value=...) at /var/opt/h/format.h:3918
> #13 0xaadeb47f in fmt::v10::detail::default_arg_formatter<char>::operator()<fmt::v10::basic_string_view<char> > (this=0xd831bc0c, value=...) at /var/opt/h/format.h:4005
> #14 0xaadec1ed in fmt::v10::visit_format_arg<fmt::v10::detail::default_arg_formatter<char>, fmt::v10::basic_format_context<fmt::v10::appender, char> > (arg=..., vis=...) at /var/opt/h/core.h:1595
> #15 fmt::v10::detail::vformat_to<char>(fmt::v10::detail::buffer<char>&, fmt::v10::basic_string_view<char>, fmt::v10::detail::vformat_args<char>::type, fmt::v10::detail::locale_ref)::format_handler::on_replacement_field(int, char const*) (id=<optimized out>, this=<optimized out>) at /var/opt/h/format.h:4592
> #16 fmt::v10::detail::parse_replacement_field<char, fmt::v10::detail::vformat_to<char>(fmt::v10::detail::buffer<char>&, fmt::v10::basic_string_view<char>, fmt::v10::detail::vformat_args<char>::type, fmt::v10::detail::locale_ref)::format_handler&>(char const*, char const*, fmt::v10::detail::vformat_to<char>(fmt::v10::detail::buffer<char>&, fmt::v10::basic_string_view<char>, fmt::v10::detail::vformat_args<char>::type, fmt::v10::detail::locale_ref)::format_handler&) (begin=0x81ffffbd '\377' <repeats 67 times><error: Cannot access memory at address 0x82000000>, end=0xd831bca8 ",\275\061\330\"", handler=...) at /var/opt/h/core.h:2475
> #17 0xaade80d7 in fmt::v10::detail::parse_format_string<false, char, fmt::v10::detail::vformat_to<char>(fmt::v10::detail::buffer<char>&, fmt::v10::basic_string_view<char>, fmt::v10::detail::vformat_args<char>::type, fmt::v10::detail::locale_ref)::format_handler>(fmt::v10::basic_string_view<char>, fmt::v10::detail::vformat_to<char>(fmt::v10::detail::buffer<char>&, fmt::v10::basic_string_view<char>, fmt::v10::detail::vformat_args<char>::type, fmt::v10::detail::locale_ref)::format_handler&&) (handler=..., format_str=...) at /var/opt/h/core.h:2541
> #18 fmt::v10::detail::vformat_to<char> (buf=..., fmt=..., args=..., loc=...) at /var/opt/h/format.h:4619
> #19 0xaade52a9 in fmt::v10::vformat[abi:cxx11](fmt::v10::basic_string_view<char>, fmt::v10::basic_format_args<fmt::v10::basic_format_context<fmt::v10::appender, char> >) (fmt=..., args=...) at /var/opt/h/format-inl.h:1440
> #20 0xab006e43 in fmt::v10::format<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, double&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (fmt=...) at /var/opt/h/core.h:2817

Is it a known issue?

**Comment by vitaut** [comment]
I don't remember seeing this one. Please provide a repro.

**Comment by vitaut** [comment]
Closing for now but feel free to reopen with a repro.
