### ISSUE TITLE
fmt::v5 alternatives in fmt::v10

### ISSUE THREAD

**Issue by 07anhad** [fmtlib/fmt#3504]
Hi, can you please help me with the following

1) which version of gcc compiler is compatible with version 10 of FMT library? As I am getting this internal compiler error -

`/it/sjclapa09p3_scratch01/abc/expire_2023_09_30/abc_scratch/mydir/FMT/fmt-master/include/fmt/core.h:2637:77: internal compiler error: in cxx_eval_bit_field_ref, at cp/constexpr.c:2360
   FMT_CONSTEXPR bool error = (parse_format_string<true>(s, checker(s)), true);
                                                                             ^
0x6ff8b3 cxx_eval_bit_field_ref
    /tmp/gcc-v6.3.0p2/gcc.source/gcc/cp/constexpr.c:2360
0x6ff8b3 cxx_eval_constant_expression
    /tmp/gcc-v6.3.0p2/gcc.source/gcc/cp/constexpr.c:3994
0x702b44 cxx_eval_binary_expression
    /tmp/gcc-v6.3.0p2/gcc.source/gcc/cp/constexpr.c:1831
0x6fe466 cxx_eval_constant_expression
    /tmp/gcc-v6.3.0p2/gcc.source/gcc/cp/constexpr.c:3951
`

**2) Which fmt API to use for changing the buffer size?**

**3) What is the alternative of fmt::buffered_file (version 5) in fmt version 10?**

**Comment by vitaut** [comment]
> which version of gcc compiler is compatible with version 10 of FMT library?

{fmt} is compatible with gcc 4.4 and later. Please report internal compiler errors to gcc.

> Which fmt API to use for changing the buffer size?

Not sure what you mean by that. In general you don't need to deal with any buffer sizes yourself.

> What is the alternative of fmt::buffered_file (version 5) in fmt version 10?

`buffered_file` is available in version 10.

**Comment by 07anhad** [comment]
> {fmt} is compatible with gcc 4.4 and later. Please report internal compiler errors to gcc.
> 
> I have tried many possible ways to fix it, but still the internal compiler error keeps occurring at fmt/core.h:2670
