### ISSUE TITLE
Header only build

### ISSUE THREAD

**Issue by 07anhad** [fmtlib/fmt#3506]
Hi @vitaut,

How can I build a header only version of this library by defining the FMT_HEADER_ONLY macro while building this library.

When I am implementing `#define FMT_HEADER_ONLY` above the `#include "fmt/core.h"` its giving an error

**Comment by vitaut** [comment]
There is nothing to build in the header-only mode, see https://fmt.dev/latest/usage.html#usage-with-cmake how to use it from CMake.
