### ISSUE TITLE
fmt::join format vector of pointers

### ISSUE THREAD

**Issue by OfekShochat** [fmtlib/fmt#3507]
I'm trying to format a fmt::join call on a vector of pointers. Apparently, that's not how it works, and I can't just format that. I tried defining a formatter just for the pointer one, but that also didn't work.

my regular formatter:
```c++
template<typename Char>
struct fmt::formatter<BasicBlock, Char> {
    // 'v' - view
    // 'd' - debug
    char presentation = 'v';

    // https://fmt.dev/latest/api.html
    constexpr auto parse(format_parse_context &ctx) -> format_parse_context::iterator {
        auto it = ctx.begin(), end = ctx.end();
        if (it != end && (*it == 'v' || *it == 'd')) {
            presentation = *it++;
        }

        // Check if reached the end of the range (this is comptime so exceptions are ok?):
        if (it != end && *it != '}') {
            throw format_error("invalid format");
        }

        return it;
    }

    template<typename FormatContext>
    format_context::iterator format(BasicBlock const &block, FormatContext &ctx) {
        basic_memory_buffer<Char> buf;
        auto out = std::back_inserter(buf);

        fmt::format_to(out, "b{}(", block.get_id());
        for (auto const &arg : block.phi_args()) {
            fmt::format_to(out, "{}, ", arg.value());
        }
        fmt::format_to(out, ")", block.get_id()); // weird

        return detail::write(ctx.out(), basic_string_view<Char>(buf.data(), buf.size()));
    }
};
```
How should I print that vector? I'm confused, the error suggests ( error: static assertion failed due to requirement 'formattable': Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt) that I have to do an additional thing to move forward. 
What would resolve this?
Thanks

**Comment by vitaut** [comment]
If you want to format the pointer value, you need to convert it to `(const) void*` or wrap in `fmt::ptr`: https://fmt.dev/latest/api.html#_CPPv4I0EN3fmt3ptrEPKv1T.

**Comment by OfekShochat** [comment]
I don't want the pointer value, I probably was unclear. I have a vector of pointers to `BasicBlock`s. I'd like to print that vector and its items (their values)

**Comment by vitaut** [comment]
In this case you need to dereference a pointer to get (a reference to) the object and pass it to the formatting function.

**Comment by OfekShochat** [comment]
I did that, defined a formatter for it being a BasicBlock *, dereferenced it and passed it to the other one. It still complained that it is not formattable

**Comment by vitaut** [comment]
Most likely the problem is that you are trying to use the `formatter` specialization before it is fully defined. Outlining the `format` member function might help.

**Comment by mwinterb** [comment]
join also requires the formatter's format to be const.
