### ISSUE TITLE
Allow providing arguments in a loop or simple creation of ArgList

### ISSUE THREAD

**Issue by wiggisser** [fmtlib/fmt#351]
I would love to use this library in my app because of the named parameters, but I didn't find a possiblity to solve the following usecase:

I want read the format string and the parameters from a database, so during compile time I do not know the number of arguments in the formatstring yet. Is there a possibility to provide the formatting arguments in for instance a loop (lkie it is possible with boost::format) or create an ArgList and add a variable number of fmt::arg elements to it and then call the format?

Something like this (pseudocode)
string fmtstring = //read format string from database
ftm::ArgList fmtargs =   //read variable number of argument names and values from database
ftm::format(fmtstring, fmtargs);

**Comment by vitaut** [comment]
Thanks for the suggestions, it has been discussed in #330 already.
