### ISSUE TITLE
switch statement does not contain a default clause

### ISSUE THREAD

**Issue by 4kangjc** [fmtlib/fmt#3510]
There is a default clause in the implementation of stl, but libfmt does not
https://github.com/fmtlib/fmt/blob/13156e54bf91e44641ce3aac041d31f9a15a8042/include/fmt/core.h#L1652
https://github.com/microsoft/STL/blob/40640c6df9754ea031f8df7c720b89714d19df97/stl/inc/format#L779

![image](https://github.com/fmtlib/fmt/assets/73515066/c1c3e3a2-87c7-4418-8269-fe2ccc1ff435)

**Comment by vitaut** [comment]
This switch doesn't need a default clause.

**Comment by 4kangjc** [comment]
> This switch doesn't need a default clause.

I know, but it will cause compile errors if -Wswitch-default is on

**Comment by vitaut** [comment]
Suppressing all possible warnings is a non-goal but you can do it yourself with the `FMT_SYSTEM_HEADERS` CMake variable or other method.

**Comment by 4kangjc** [comment]
> Suppressing all possible warnings is a non-goal but you can do it yourself with the `FMT_SYSTEM_HEADERS` CMake variable or other method.

OK. I see.
