### ISSUE TITLE
People use buf.data() directly

### ISSUE THREAD

**Issue by apivovarov** [fmtlib/fmt#3513]
Quite often I see that people convert `memory_buffer` to string by simply using `buf.data()`. As a result - end of string might contain some garbage. Any ideas how to prevent it and force people to use `fmt::to_string(buf)`?

Code with the issue
```
#include <fmt/format.h>

int main() {
  auto buf = fmt::memory_buffer();
  fmt::format_to(std::back_inserter(buf), "Test");
  std::string s1 = buf.data();
  std::string s2 = fmt::to_string(buf);
  fmt::print("Bad string: {}, len: {}\n", s1, s1.size());
  fmt::print("Good string: {}, len: {}\n", s2, s2.size());
  return 0;
}
```
Output
```
Bad string: Test?, len: 6
Good string: Test, len: 4
```

**Comment by beojan** [comment]
Maybe it could also do with a `to_string_view` option, which points to the same memory as the buffer?
