### ISSUE TITLE
Install doesn't install header files

### ISSUE THREAD

**Issue by mborn-adi** [fmtlib/fmt#3517]
On Windows, install only installs everything except the header files. In CMakeLists.txt, the install is set up like this:
```
  # Install the library and headers.
  install(TARGETS ${INSTALL_TARGETS} EXPORT ${targets_export_name}
          LIBRARY DESTINATION ${FMT_LIB_DIR}
          ARCHIVE DESTINATION ${FMT_LIB_DIR}
          PUBLIC_HEADER DESTINATION "${FMT_INC_DIR}/fmt"
          RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
```
But nowhere else are the header files marked "PUBLIC_HEADER".

Adding
```
set_property(TARGET fmt PROPERTY PUBLIC_HEADER ${FMT_HEADERS})
```
in line 289 right after
```
add_library(fmt::fmt ALIAS fmt)
```
does just that. But cmake is not my strongest suit.

Best Regards,
Mathias

**Comment by vitaut** [comment]
I was managed to repro this on macOS and it looks like a recent regression related to modules work.

**Comment by rxguy** [comment]
I am getting this today with Fedora Linux.

**Comment by vitaut** [comment]
Header installation was working on https://github.com/fmtlib/fmt/commit/75f3b1c09485986427b8a46272f6b9570366e1aa.

**Comment by vitaut** [comment]
Bisected the regression to 13156e54bf91e44641ce3aac041d31f9a15a8042.
