### ISSUE TITLE
Sigfault (crash) on armeabi-v7a Android (32 bit Android)

### ISSUE THREAD

**Issue by raidenluikang** [fmtlib/fmt#3518]
https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L1939   This line code crashed on armeabi-v7a Android OS. 

For details see https://github.com/gabime/spdlog/issues/2793

**Comment by vitaut** [comment]
Please provide a repro, ideally on godbolt.

**Comment by raidenluikang** [comment]
Following stacktrace received:
1. https://github.com/fmtlib/fmt/blob/master/include/fmt/format-inl.h#L1424

2. https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L2522

3. https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L1732

4. https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L1939

**Comment by raidenluikang** [comment]
>>Please provide a repro, ideally on godbolt.

Godbolt not supported run armeabi-v7a executable,If I am not mistaken . And this is not actual problem. I can't reproduce stable crashing test in 32-bit x86 linux ), sorry.   

First time crashed   `std::int64_t id = ...;   std::string str = fmt::format("{:019}, id); `   code. 
Second time crashed   `std::string dynamic_name = .... ;  fmt::format("some_class[{}]::some_method", dynamic_name);`  code.

But I see in code, that accessed array without checking it actual size. Only check less it 15 or not. But that code `value_` pointer points array which size may be less than 15. 

I retry some random generated tests for catching error, tomorrow. In 32-bits architecture.

**Comment by raidenluikang** [comment]
I can't find crashing format example, yet.

But my be  this is interesting: [godbold example](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:11,endLineNumber:12,positionColumn:11,positionLineNumber:12,selectionStartColumn:11,selectionStartLineNumber:12,startColumn:11,startLineNumber:12),source:'%0A%23include+%22fmt/format.h%22%0A%23include+%22fmt/core.h%22%0A%23include+%3Cstdio.h%3E%0A%23include+%3Cstdint.h%3E%0A%23include+%3Climits.h%3E%0A%23include+%3Cstring_view%3E%0A%0Atemplate%3Ctypename+S,+typename+...Args%3E%0Avoid+format_to_simulate(const+S%26+format_str,+Args%26%26...+args)%0A%7B%0A%09const+auto%26+vargs+%3D+fmt::make_format_args(format_str,+args...)%3B%0A%09%0A%09using+memory_buf_t+%3D+fmt::basic_memory_buffer%3Cchar,+250%3E%3B%0A%09%0A%09fmt::detail::locale_ref+loc%7B%7D%3B//nullptr%0A%09%0A%09memory_buf_t+buf%3B%0A%09%0A%09//using+iterator+%3D+fmt::buffer_context%3Cchar%3E::iterator%3B%0A%09%0A%09auto+out+%3D+fmt::detail::buffer_appender%3Cchar%3E(buf)%3B%0A%09%0A%09const+auto%26+format_args+%3D+vargs%3B+%0A%09fmt::buffer_context%3Cchar%3E+context(out,+format_args,+loc)%3B%0A%09static_assert(sizeof(int)+%3D%3D+4,+%22we+assume+sizeof(int)+%3D%3D+4%22)%3B%0A%0A%0A%09for+(int+h+%3D+0%3B+h+%3C+8%3B+%2B%2Bh)%0A%09%7B%0A%09%09%0A%09%09int+id+%3D+(1U+%3C%3C+31)+%7C+(h+%3C%3C+28)%3B%0A%09%09printf(%22id+%3D+%25d%5Cn%22,+id)%3B%0A%09%09auto+arg+%3D+context.arg(id)%3B%0A%09%09if+(!!arg)%7B%0A%09%09%09printf(%22arg+not+found%5Cn%22)%3B%0A%09%09%7D+else+%7B%0A%09%09%09printf(%22arg+found%5Cn%22)%3B%0A%09%09%7D%0A%09%7D%0A%7D%0A%0Aint+main()%0A%7B%0A%09int64_t+id+%3D+1231%3B%0A%09std::string_view+format_str+%3D+%22%7B:019%7D%22%3B%0A%09format_to_simulate(format_str,+id)%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:36.07097025735303,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g94,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:fmt,ver:trunk)),options:'-std%3Dc%2B%2B17+-ggdb+-fsanitize%3Daddress+-fno-omit-frame-pointer+-static-libstdc%2B%2B+-static-libasan+-lrt',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+9.4+(Editor+%231)',t:'0')),k:27.814593687902768,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+13.1',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+9.4+(Compiler+%231)',t:'0')),k:36.1144360547442,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Comment by vitaut** [comment]
Closing as it is not actionable without a repro but feel free to reopen with more details. Argument ids shouldn't be negative (in "{:019}" the id should be zero) so you might want to investigate where it is coming from.
