### ISSUE TITLE
How to adapt to changed chrono formatting?

### ISSUE THREAD

**Issue by wAuner** [fmtlib/fmt#3520]
Version 10 gives me unusable results when formatting `system_clock` timepoints. What do I need to change?
Test case:
```
#include <chrono>
#include <fmt/chrono.h>

using namespace std;
using namespace std::chrono_literals;
using namespace std::string_literals;
using namespace fmt::literals;

int main(int argc, char *argv[]) 
{
   fmt::print("{:%a, %d %b %Y %H:%M:%S %z}\n", chrono::system_clock::now());
   
   chrono::time_point<chrono::system_clock> clock {10s + 1000us};
   fmt::print("{:%a, %d %b %Y %H:%M:%S %z}\n", clock);
}
```
Version 9.2:
```
Tue, 04 Jul 2023 13:20:20 +0200 // that's what I want
Thu, 01 Jan 1970 01:00:10 +0100 // ¯\_(ツ)_/¯ don't know why the tz is now +1
```

Version 10:
```
Tue, 04 Jul 2023 11:20:27.105726 +0000
Thu, 01 Jan 1970 00:00:10.001000 +0000
```
I couldn't figure out
a) how do I get the seconds back w/o decimal points,
b) how to get the UTC timezone correctly displayed.

Any help is appreciated.

**Comment by vitaut** [comment]
In both cases {fmt} 10.0 follows the standard spec so I recommend checking the std::chrono docs. One way to truncate fractional seconds is

```c++
   auto sec = std::chrono::duration_cast<std::chrono::seconds>(clock.time_since_epoch());
   fmt::print("{:%S}\n", sec);
```

As for the timezone you probably need to convert the time from system which is in UTC to local.
