### ISSUE TITLE
fmt::ostream object declaration

### ISSUE THREAD

**Issue by 07anhad** [fmtlib/fmt#3524]
Hi @vitaut 

In my c++ program, I have opened the `fmt::output_file` api like,

`fmt::ostream out = fmt::output_file(file.c_str(), fmt::buffer_size=4096)`

When I am passing this `out` to a file pointer like, 

`FILE* fp = func1(arg1, arg2, out); `   and this is being received in some function say `func 2` , there when I have to pass `out` in file pointer of `func1` , while initializing and fmt object in `func2` like `fmt::ostream out;`

I guess fmt::ostream object adapts std::ostream but still the following error arises, 

**path/to/fmt/os.h:402:3 note:   candidate expects 2 arguments, 0 provided
path/to/example.cpp:2770:18: error: no matching function for call to 'fmt::v10::ostream::ostream()'
     fmt::ostream out;** 

What can be the issue here?

Thanks

**Comment by vitaut** [comment]
`fmt::ostream` doesn't have the default constructor and is unrelated to `std::ostream`. If unsure, you can use `std::ostream` which is also supported by {fmt}.
