### ISSUE TITLE
Question: Which Sphinx theme are you using?

### ISSUE THREAD

**Issue by manuel-wagesreither** [fmtlib/fmt#3525]
Greetings,

The footer of https://fmt.dev says the site was created using Sphinx. I'd like to ask for details on the theme you are using, as it looks real nice!

I browsed https://sphinx-themes.org/ but couldn't find it there.

Warmest regards,
Manuel

**Comment by vitaut** [comment]
We use a custom theme: https://github.com/fmtlib/fmt/blob/a474916560e0189871e4122ed6cf2522e4320073/doc/conf.py#L107
