### ISSUE TITLE
Data is getting corrupted with fmt::memory buffer if size is approx greater than 5850

### ISSUE THREAD

**Issue by toritesh** [fmtlib/fmt#3528]
#include <fmt/format.h>

int main () 
{
double const d = 123.45678;
fmt::memory_buffer buf;
for(size_t i = 0; i < 450; ++i) {
    format_to(std::back_inserter(buf), "{:e}\n", d);
}
auto ptrToFormattedData  = buf.data();
auto sizeOfFormattedData = buf.size();
fmt::print("{}\n", ptrToFormattedData);
fmt::print("Size = {}\n", sizeOfFormattedData);
return 0;
}

Compiler path : https://godbolt.org/

Output 👍 
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
68e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.234568e+02
1.23�!
Size = 5850

**Comment by vitaut** [comment]
You are trying to print the content of a buffer which is not null terminated. The fix is to either add a null terminator or convert the buffer to a sized view e.g. `string_view`:

```c++
  fmt::print("{}\n", fmt::string_view(ptrToFormattedData, sizeOfFormattedData));
```

https://godbolt.org/z/437acbqc9

**Comment by toritesh** [comment]
Thanks for your quick answer.

**Comment by toritesh** [comment]
Could you update this information in documentation.

**Comment by vitaut** [comment]
Good idea, clarified in https://github.com/fmtlib/fmt/commit/dd5a9691f992f7f257243cbecb516a4ab584dcde.
