### ISSUE TITLE
Q: how to thousands separator?

### ISSUE THREAD

**Issue by apivovarov** [fmtlib/fmt#3532]
How to format integer number with thousands separator?
python Example:
```python
>>> print(f"{1234:,}")
1,234
```

**Comment by vitaut** [comment]
You can either use a locale or [`fmt::group_digits`](https://fmt.dev/latest/api.html#_CPPv4I0EN3fmt12group_digitsE17group_digits_viewI1TE1T).

**Comment by apivovarov** [comment]
Is it possible to combine thousand separator and .precision formatting for floats?
For example
```python
a=12345.6789
print(f"{a:,.3f}")
12,345.679
```
