### ISSUE TITLE
Question about custom formatters and inline namespace

### ISSUE THREAD

**Issue by xvitaly** [fmtlib/fmt#3534]
Is it possible to use custom formatters without adding them to `fmt:vX` namespace?

We have [issues with building](https://github.com/microsoft/vcpkg-tool/pull/1117) against different versions of fmt.

**Comment by vitaut** [comment]
You shouldn't be using inline namespaces manually, see the docs: https://fmt.dev/latest/api.html#formatting-user-defined-types.
