### ISSUE TITLE
Erroneous fixed-precision formatting for `long double`

### ISSUE THREAD

**Issue by inicula** [fmtlib/fmt#3539]
Code:

```cpp
#include <fmt/core.h>
#include <sstream>

int main()
{
        const char *str = "0.000000001";
        std::stringstream ss(str);

        long double x;
        ss >> x;

        fmt::print("{:.1f}\n", x); // 0.000000001
}
```

Godbolt: https://godbolt.org/z/16TWs8c8M

**Comment by vitaut** [comment]
Good catch, this should be 0.0.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/388bc296b77141db73d17c9f39dceba42284d8f4. Thanks for reporting!

**Comment by vitaut** [comment]
Good catch, thanks @ToppDev. Fixed in https://github.com/fmtlib/fmt/commit/06311ed1ced891f0b360a25b352cefafa0d98c46.
