### ISSUE TITLE
Error	C2039	'format': is not a member of 'fmt::v10::formatter<float [256],Char,void>'

### ISSUE THREAD

**Issue by Hong0903** [fmtlib/fmt#3546]
the project is created by vs2010, but it had converted to vs2019, and does not use C++20，another project is working ，but this one still show the issues .  does some body  know why the issue happen？ help!!

//////////////////////libfmt
#if _MSC_VER > 1600
#define FMT_HEADER_ONLY
#include ".\3rdparty\fmt\include\core.h"    //c++11
using namespace fmt;
#endif

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'format': is not a member of 'fmt::v10::formatter<float [256],Char,void>'	
..\3rdparty\fmt\include\core.h	1300	
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'parse': is not a member of 'fmt::v10::formatter<float [256],Char,void>'	
..\3rdparty\fmt\include\core.h	1297	

i guess maybe need add some macros or project options.

**Comment by vitaut** [comment]
Looks like you are trying to format `float[256]` without including `fmt/ranges.h` where it's formatter is defined.

**Comment by Hong0903** [comment]
> Looks like you are trying to format `float[256]` without including `fmt/ranges.h` where it's formatter is defined.

thanks ,it solved now
