### ISSUE TITLE
How to minimize the size of fmt?

### ISSUE THREAD

**Issue by jaskij** [fmtlib/fmt#3547]
I'm evaluating using `fmt` for microcontroller code. Unfortunately, simply adding

```cpp
auto [out, size] = fmt::format_to_n(buffer.begin(), buffer.size(), "Foo no {}\n", counter);
*out = '\0';
```

Results in ~260k extra of flash usage (I'm assuming it's mostly executable code) to my binary. That's four times the amount of flash I have available for the whole program.

Reading the README, I can only assume I am doing something wrong with how I am including the library?

Using the rough equivalent below, results in a binary with total size of 19k.

```cpp
        size_t size = snprintf(buffer.data(), buffer.size(), "Foo no %lu\n", counter);
        buffer[size] = '\0';
```

I am compiling with `-flto -Os`, using GCC 12.2 (latest official gcc-arm-none-eabi release from ARM), using `newlib-nano` as the C library. Actual numbers below, the only difference between the two builds is using snprintf vs fmt.

Using fmt
```
Memory region         Used Size  Region Size  %age Used
             RAM:        8984 B         8 KB    109.67%
           FLASH:      286928 B        64 KB    437.82%
```

Using newlib-nano snprintf
```
Memory region         Used Size  Region Size  %age Used
             RAM:        4040 B         8 KB     49.32%
           FLASH:       19312 B        64 KB     29.47%
```

Am I doing something wrong, are there options for `fmt` I could turn on/off, are there features I should avoid using? Or did I simply get bamboozled, not reading the small print under the code size table in the README (that it's uinsg fmt as a shared library?).

**Comment by jaskij** [comment]
To be fair, the printf in newlib-nano does not support floating point at all, but it is not necessary in my application. I suspect that simply the ability to disable that support would cut the code size greatly. From personal experience, using an FP-disabled version of printf in newlib (not nano) saves about two-thirds of the code size of the full-sized printf.

**Comment by mwinterb** [comment]
https://github.com/fmtlib/fmt/blob/3dec65b7fd8df55bd5904a1e22dd907038634cf0/include/fmt/format.h#L820

For floating point specifically, there are several #define's that you can
set to 0 when building and using the library.

**Comment by vitaut** [comment]
In addition to disabling floating-point formatting per @mwinterb's comment above you could also disable locale support via `FMT_STATIC_THOUSANDS_SEPARATOR`. Note that by default {fmt} optimizes for per-call size, if you have few calls you could try using format string compilation which will trade constant library size for larger per-call size.

**Comment by jaskij** [comment]
Ah, please disregard the numbers in the OP (will edit in a minute), I have mistakenly left `__attribute__((flatten))` on the calling function.

Updated numbers without it:

No defines:

```
Memory region         Used Size  Region Size  %age Used
             RAM:        8992 B         8 KB    109.77%
           FLASH:      212684 B        64 KB    324.53%
```

with `-DFMT_STATIC_THOUSANDS_SEPARATOR='.'`

```
Memory region         Used Size  Region Size  %age Used
             RAM:        4072 B         8 KB     49.71%
           FLASH:       52108 B        64 KB     79.51%
```

with 

```
-DFMT_STATIC_THOUSANDS_SEPARATOR='.'
-DFMT_USE_FLOAT=0
-DFMT_USE_DOUBLE=0
-DFMT_USE_LOND_DOUBLE=0
-DFMT_USE_FLOAT128=0
```

```
Memory region         Used Size  Region Size  %age Used
             RAM:        4072 B         8 KB     49.71%
           FLASH:       48172 B        64 KB     73.50%
```

With all defines and `FMT_COMPILE` (single call site):

```
Memory region         Used Size  Region Size  %age Used
             RAM:        4040 B         8 KB     49.32%
           FLASH:       16168 B        64 KB     24.67%
```

**Comment by vitaut** [comment]
Thanks for the update! Glad to see such a big binary size reduction.

**Comment by vitaut** [comment]
BTW it looks like you have a typo in one of the macros which could affect results: it should be `FMT_USE_LONG_DOUBLE` instead of FMT_USE_LOND_DOUBLE`.

**Comment by jaskij** [comment]
> BTW it looks like you have a typo in one of the macros which could affect results: it should be `FMT_USE_LONG_DOUBLE` instead of `FMT_USE_LOND_DOUBLE`.

Thanks for the catch! That shaved off another 15k off that size (edited the post with updated sizes).

Overall seems like `fmt` is entirely viable even on relatively small microcontrollers, like the one I'm using. Debug builds are a bit big (171k with defines, 58k with compiling), but that's acceptable, as it doesn't impact the product's cost.

**Comment by vitaut** [comment]
@Viatorus, interesting project but this is a place to report issues with {fmt} not advertise your projects.
