### ISSUE TITLE
 error: lookup of 'value_type' in 'fmt::v5::basic_memory_buffer<char>' is ambiguous

### ISSUE THREAD

**Issue by 07anhad** [fmtlib/fmt#3553]
Hi @vitaut,

While using the FMT library V5.2.1, when I have implemented `fmt::memory_buffer` and `fmt::format_to(std::back_inserter)` like

From this 

```cpp
char Str1[1000] = {'\0'};
char Str2[1000] ;

sprintf(add(Str1),"%s ", Str2);
```

To this

```cpp
fmt::memory_buffer Str1;
string Str2;

fmt::format_to(std::back_inserter(Str1), "{ } ", Str2.c_str())

```
On running this, this error is arising, what can be the fix for this

**###NOTE - Its working fine with FMT V10.0.0 ###** but I want it for V5.2.1

`/path/to/include/c++/6.3.0/bits/stl_iterator.h:: error: lookup of 'value_type' in 'fmt::v5::basic_memory_buffer<char>' is ambiguous
 operator=(const typename _Container::value_type& __value)`

**Comment by vitaut** [comment]
{fmt} 5 is very old and no longer supported. I recommend switching to a newer version where the issue has been fixed.
