### ISSUE TITLE
Q: How to combine thousands separator and .precision formatting for floats?

### ISSUE THREAD

**Issue by apivovarov** [fmtlib/fmt#3557]
Is it possible to combine thousands separator and .precision formatting for floats?
For example
```python
a=12345.6789
print(f"{a:,.3f}")
12,345.679
```

**Comment by vitaut** [comment]
`,` is not supported but you should be able to combine precision with other methods described in #3532.

**Comment by apivovarov** [comment]
But how exactly to combine fmt::group_digits with .precision formatting?

**Comment by vitaut** [comment]
You could do it as follows (https://godbolt.org/z/hPnzhea33):

```c++
auto loc = std::locale("en_US.UTF-8");
auto s2 = fmt::format(loc, "{:Lf}", x);
```

**Comment by apivovarov** [comment]
ok, to return 3 decimal points and apply thousands separator we can use `{:.3Lf}` format string.
```
  double x = 12345.6789;
  auto loc = std::locale("en_US.UTF-8");
  auto s2 = fmt::format(loc, "{:.3Lf}", x);   // 12,345.679
  fmt::print("{}", s2);
```
I'm not sure if this case is clearly described in the [documentation](https://fmt.dev/latest/api.html)

**Comment by vitaut** [comment]
Locale API is documented in https://fmt.dev/latest/api.html#locale including an example that shows separators.
