### ISSUE TITLE
Define name conflict for platformio + esp32

### ISSUE THREAD

**Issue by cr1tbit** [fmtlib/fmt#3559]
https://registry.platformio.org/libraries/fmtlib/fmt

I looked at the platformio registry and there's no contact info, and the author's name is "fmtlib" so I assume this library might be maintained by someone from here.

The problem is, that the library uses `B1` and `B2` for its template code, which gets replaced by the define from the unholy abomination of a header file included for esp32 platformio projects by default:

https://github.com/espressif/arduino-esp32/blob/21b88659b9ded3fcc1082f23f498bc2a04cd4f1b/cores/esp32/binary.h#L31
https://github.com/fmtlib/fmt/blob/757564f5cd2fa78b634dd698c63dbf069818e6fd/include/fmt/core.h#L1204

Maybe `B`, `B1` and `B2` could be renamed to something with less potential of name collisions.

On the side note, originally I also used `#define B2` to name a pin attached to "button 2", just some quirks of embedded development.

**Comment by vitaut** [comment]
Please report to the library that defines the problematic macros. We don't normally rename symbols because of collisions with random third-party projects.

**Comment by cr1tbit** [comment]
I was kind of hoping for a patch for platformio release. But maybe that's not very important.

For future people stumbling upon this, putting `#undef B1` after `#include <Arduino.h>` fixes the issue without the need to modify fmtlib's source.

**Comment by ktrzeciaknubisa** [comment]
hey, thanks a lot @cr1tbit ,that really helped 👍
