### ISSUE TITLE
How to format custom data type

### ISSUE THREAD

**Issue by freak82** [fmtlib/fmt#356]
I'm unable to build the example, provided in the documentation.

class Date {
  int year_, month_, day_;
 public:
  Date(int year, int month, int day) : year_(year), month_(month), day_(day) {}

  friend std::ostream &operator<<(std::ostream &os, const Date &d) {
    return os << d.year_ << '-' << d.month_ << '-' << d.day_;
  }
};

std::string s = fmt::format("The date is {}", Date(2012, 12, 9));

The actual error is:
no matching function for call to ‘format(fmt::BasicFormatter<char>&, const Char*&, const Date&)'.

I can see from your unit tests that you explicitly define format function for your custom Date type such as:
void format(fmt::BasicFormatter<char> &f, const char *, const Date &d) {        
  f.writer() << d.year() << '-' << d.month() << '-' << d.day();                 
} 

Do I need to define the format function for my type? 
It was more convenient as it was in the example (IMO) because other utilities/libraries, that I use, use the streaming operator<< and now my user defined types I should define both the operator and the format function.

**Comment by vitaut** [comment]
`std::ostream` support has been moved to a separate header, `fmt/ostream.h`. You have to include it to use `operator<<` as described in http://fmtlib.net/latest/api.html#std-ostream-support:

```c++
#include "fmt/ostream.h"

class Date {
  int year_, month_, day_;
public:
  Date(int year, int month, int day) : year_(year), month_(month), day_(day) {}

  friend std::ostream&operator<<(std::ostream&os, const Date &d) {
    return os << d.year_ << '-' << d.month_ << '-' << d.day_;
  }
};

std::string s = fmt::format("The date is {}", Date(2012, 12, 9));
// s == "The date is 2012-12-9"
```

**Comment by freak82** [comment]
My bad. I didn't see this in the docs. Sorry for bothering you.

**Comment by vitaut** [comment]
No worries. I updated the readme too: https://github.com/fmtlib/fmt/commit/c110c6eca7dbca963b7153640135102356707e3d
