### ISSUE TITLE
Precision for long double

### ISSUE THREAD

**Issue by sukolenvo** [fmtlib/fmt#3564]
Hi, here is sample code to reproduce the problem I struggle with:
```cpp
#include <fmt/core.h>

int main(int argc, char ** argv) {    
    fmt::print("{:.2f}\n",  0.099f);
    fmt::print("{:.2f}\n",  0.099L);
    return 0;
}
```
Output is :
```
0.10
0.1
```

https://godbolt.org/z/rxMb5nEGP

Is there a reason why precision 2 is working differently for long double compared to float?

PS Output also vary by compiler:
clang 14, gcc 12 output is 0.1
vs 2022 output is 0.10

**Comment by ilyapopov** [comment]
In MSVC, `long double` is the same as `double`. See https://learn.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp?view=msvc-170

> Microsoft-specific: The representation of long double and double is identical. However, long double and double are treated as distinct types by the compiler. The Microsoft C++ compiler uses the 4- and 8-byte IEEE-754 floating-point representations.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/d4248623196991b434b8cb7689affb83fd04aca2. Thanks for reporting.
