### ISSUE TITLE
Regression: v10.0 does not accept anymore custom arguments which have a std::string_view operator

### ISSUE THREAD

**Issue by omascia** [fmtlib/fmt#3565]
A custom type having an implicit conversion operator to std::string_view could be used as an argument in a fmt::format(f, custom), until v9.1.  Since v10.0, it can't compile and insist on implementing a custom formatter, which is useless code to add since there is a std::string_view conversion operator anyway.

**Comment by vitaut** [comment]
Implicit conversions are problematic and have been intentionally disabled. You can use `format_as` to opt into the conversion.

**Comment by omascia** [comment]
format_as would be a nice opt-in solution (per type) for implicit conversions, if it worked too for arguments passed to printf variations, too. Currently it does not. The nice support of printf variations was one major advantage, for our needs, of using {fmt} over standard C++ implementation. Facing a huge code base where those fmt::format() or fmt::sprintf() are hidden behind historic interface functions, it is a fantastic convenience to be able to slowly updates the remaining % masks to {} masks, while doing other maintenance work.
Using format_as had been tested, as well as implementing a proper formatter, that's the nice way to go for format. But when you have some generic historical functions which have to decide on doing format or sprintf based on the mask content, you can't compile anymore if the sprintf branch barks because it does not obey the format_as, nor accepts implicit conversions.
I have the nice solution to stick with 9.1 code base, which works very very well for my needs.
Or to see either format_as support come to printf_formatter world, or implicit conversions be enabled again *on printf side of things*.

So... Maybe this should become a feature request for either:

- format_as support for printf family (to overcome, on an opt-in fashion, the disabling of implicit conversions) ;
- implicit conversions enabled again: on printf family would be enough.
