### ISSUE TITLE
10.0.0 can no longer format enums or user types that cast to primitive types

### ISSUE THREAD

**Issue by Sainan** [fmtlib/fmt#3566]
Repro: https://godbolt.org/z/jh8vnEcfo

What I understand from the changelog is that this is intentional. I just want to point out that I don't think this is a good direction to take.

Why should I have to define customer formatters for every enum and wrapper type I might want to use in my format strings or with fmt::to_string? This isn't a restriction that std::to_string has either.

**Comment by vitaut** [comment]
You don't have to define a custom formatter for every enum, you can have a single `format_as` function that handles multiple (possibly all) your enums. The only difference with the old behavior is that it is no longer implicit for legacy enums.

**Comment by Sainan** [comment]
I don't understand how a single format_as function is supposed to handle this. You mean make a templated function like this?
```C++
template <typename T>
std::string format_as(const T& val)
{
	return std::to_string(val);
}
```

**Comment by vitaut** [comment]
> You mean make a templated function like this?

Right and {fmt} already provides one so all you need is injecting it into your namespace:
https://github.com/fmtlib/fmt/blob/8a4bec5cf53387356738a06ba0cf4fdf086241ae/include/fmt/format.h#L4121

**Comment by vitaut** [comment]
ADL works per namespace but `formatter` specializations can be defined for types in multiple namespaces. However, you might want to properly constrain such specializations.
