### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by foonathan** [fmtlib/fmt#357]
If you pass in a type that cannot be formatted, the error messages aren't.. exactly nice.

There are strategies to provide better error messages, namely a fallback functions that gets chosen as last resort with a static_assert() upon instantiation (I wrote [a blog post](https://foonathan.github.io/blog/2015/11/02/overload-resolution-2.html) if you are not aware of such techniques).

It would be nice if you implement something like this.

**Comment by vitaut** [comment]
Thanks for the suggestions. I agree that it would be nice to improve error reporting in this case. The only problem is that the most general template-based overload is already taken for `std::ostream` support here: https://github.com/fmtlib/fmt/blob/0d5ef5c2a66026409b0cfbafa1d2f46cdc5aa4d0/fmt/ostream.h#L72

Great blog post BTW!

**Comment by foonathan** [comment]
Hm, maybe disable it via expression SFINAE (on compilers that support it...)?
And then add a fallback.

**Comment by xaxxon** [comment]
Is this the "not exactly nice" error message?

/usr/local/include/fmt/format.h:1182:5: error: no matching function for call to 'format'
    format(*static_cast<Formatter*>(formatter),
    ^~~~~~
/usr/local/include/fmt/format.h:1273:22: note: in instantiation of function template specialization
      'fmt::internal::MakeValue<fmt::BasicFormatter<char, fmt::ArgFormatter<char> > >::format_custom_arg<MapCoordinate>' requested here
    custom.format = &format_custom_arg<T>;
                     ^
/usr/local/include/fmt/format.h:2081:20: note: in instantiation of function template specialization
      'fmt::internal::MakeValue<fmt::BasicFormatter<char, fmt::ArgFormatter<char> > >::MakeValue<MapCoordinate>' requested here
    Value result = MakeValue<Formatter>(value);
                   ^
/usr/local/include/fmt/format.h:3436:1: note: in instantiation of function template specialization 'fmt::internal::ArgArray<1,
      true>::make<fmt::BasicFormatter<char, fmt::ArgFormatter<char> >, MapCoordinate>' requested here
FMT_VARIADIC(std::string, format, CStringRef)
^
/usr/local/include/fmt/format.h:3408:3: note: expanded from macro 'FMT_VARIADIC'
  FMT_VARIADIC_(char, ReturnType, func, return func, __VA_ARGS__)
  ^
/usr/local/include/fmt/format.h:3342:26: note: expanded from macro 'FMT_VARIADIC_'
      ArgArray::template make<fmt::BasicFormatter<Char> >(args)...}; \
                         ^
/Users/xaxxon/apb/include/utility.h:122:16: note: in instantiation of function template specialization 'fmt::format<MapCoordinate>' requested here
                        reason(fmt::format(reason, std::forward<Ts>(ts)...))
                                    ^
/Users/xaxxon/apb/src/map.cpp:52:9: note: in instantiation of function template specialization 'ApbException::ApbException<const MapCoordinate &>'
      requested here
                throw ApbException("Position not in map {}", position);
                      ^
/usr/local/include/fmt/format.h:3436:27: note: candidate function [with Args = <const char *, MapCoordinate>] not viable: no known conversion from
      'fmt::BasicFormatter<char, fmt::ArgFormatter<char> >' to 'CStringRef' (aka 'BasicCStringRef<char>') for 1st argument
FMT_VARIADIC(std::string, format, CStringRef)
                          ^
/usr/local/include/fmt/format.h:3408:35: note: expanded from macro 'FMT_VARIADIC'
  FMT_VARIADIC_(char, ReturnType, func, return func, __VA_ARGS__)
                                  ^
/usr/local/include/fmt/format.h:3338:14: note: expanded from macro 'FMT_VARIADIC_'
  ReturnType func(FMT_FOR_EACH(FMT_ADD_ARG_NAME, __VA_ARGS__), \
             ^
/usr/local/include/fmt/format.h:3437:30: note: candidate function [with Args = <const char *, MapCoordinate>] not viable: no known conversion from
      'fmt::BasicFormatter<char, fmt::ArgFormatter<char> >' to 'WCStringRef' (aka 'BasicCStringRef<wchar_t>') for 1st argument
FMT_VARIADIC_W(std::wstring, format, WCStringRef)
                             ^
/usr/local/include/fmt/format.h:3411:38: note: expanded from macro 'FMT_VARIADIC_W'
  FMT_VARIADIC_(wchar_t, ReturnType, func, return func, __VA_ARGS__)
                                     ^
/usr/local/include/fmt/format.h:3338:14: note: expanded from macro 'FMT_VARIADIC_'
  ReturnType func(FMT_FOR_EACH(FMT_ADD_ARG_NAME, __VA_ARGS__), \
             ^
/usr/local/include/fmt/format.h:3147:21: note: candidate function not viable: requires 2 arguments, but 3 were provided
inline std::wstring format(WCStringRef format_str, ArgList args) {
                    ^
/usr/local/include/fmt/format.h:3141:20: note: candidate function not viable: requires 2 arguments, but 3 were provided
inline std::string format(CStringRef format_str, ArgList args) {
                   ^

**Comment by vitaut** [comment]
@xaxxon Yes, looks like it.

**Comment by vitaut** [comment]
Improved error reporting is implemented in https://github.com/fmtlib/fmt/commit/31e7e80130a0d0ce1ea02041c78c3c119bc02c3e. Now it will give:

```
...
fmt/format.h:1156:43: error: static assertion failed: Cannot format argument. To 
enable the use of ostream operator<< include fmt/ostream.h. Otherwise provide 
an overload of format_arg.
```

**Comment by xaxxon** [comment]
That's awesome.

**Comment by courtney-g** [comment]
I'm trying to use fmt::hex and am seeing this error. I tried adding #include "fmt/ostream.h" and then get:

external/fmtlib/fmt/ostream.h:82:10: error: invalid operands to binary expression ('std::basic_ostream<char>' and 'const fmt::IntFormatSpec<unsigned int, fmt::TypeSpec<'x'>, char>')
  output << value;
  ~~~~~~ ^  ~~~~~
...

Suggestions?

**Comment by vitaut** [comment]
It looks that you are trying to use fmt::hex with iostreams while it should be used with a writer. If this is not the case please post the code that causes the error.
