### ISSUE TITLE
Format chrono: implemented glibc extension for padding seconds, minutes and hours

### ISSUE THREAD

**Issue by LukashonakV** [fmtlib/fmt#3572]
Dear @ShawnZhong ,
Thank you for your great PR #2959, #3271 .
For simple sys_time time points it works well.
Is it possible to extend this functionality on the whole chrono.. for example for all time zone API which is included into C++20 standard. ? 
The issue here: waybar uses date::zoned_time class which is std::chrono::zoned_time (See [zoned_time](https://en.cppreference.com/w/cpp/chrono/zoned_time)) .. and for this TZ API padding seconds, minutes, hours doesn't work :(

Here an example of waybar code: [clock.cpp:166](https://github.com/Alexays/Waybar/blob/94c34a29c4e377bd9b2ab08e07a034336ed93e27/src/modules/clock.cpp#L166) . Then when we try to get formatted output at [clock.cpp:178](https://github.com/Alexays/Waybar/blob/94c34a29c4e377bd9b2ab08e07a034336ed93e27/src/modules/clock.cpp#L178) we got wrong printed result. In the same time all other common format masks work well with zoned_time.

**Comment by vitaut** [comment]
This can be done with a custom formatter but a PR to support zoned time would be welcome if the extension makes sense there.

**Comment by bradrn** [comment]
> a PR to support zoned time would be welcome if the extension makes sense there.

I see no reason why it shouldn’t make sense there — if the time can be printed with a leading `0`, it can surely be printed with a leading space too! If I get time I might look into making a PR, but until then perhaps this issue should be re-opened.
