### ISSUE TITLE
format time has Fractional Part

### ISSUE THREAD

**Issue by v-dao** [fmtlib/fmt#3581]
```cpp
#include <fmt/format.h>
#include <fmt/chrono.h>
int main()
{
  auto now = std::chrono::system_clock::now();
  fmt::print("{}\n", now);
  return 0;
}
```
Output:
```
ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 0
2023-08-11 15:11:08.565882791
```
refer to https://hackingcpp.com/cpp/libs/fmt.html#chrono-format
shoud output 2023-08-11 15:11:08?

**Comment by vitaut** [comment]
{fmt}'s behavior matches [the C++ spec](https://eel.is/c++draft/time.format#tab:time.format.spec):

> If the precision of the input cannot be exactly represented with seconds, then the format is a decimal floating-point number with a fixed format and a precision matching that of the precision of the input (or to a microseconds precision if the conversion to floating-point decimal seconds cannot be made within 18 fractional digits)[.](https://eel.is/c++draft/time.format#tab:time.format.spec-row-26-column-2-sentence-3)

Please report an issue to the author of hacking C++.
