### ISSUE TITLE
Header for forward includes

### ISSUE THREAD

**Issue by bjadamson** [fmtlib/fmt#3585]
Is it possible to add a header just for forward includes? Something like this:
https://github.com/skypjack/entt/blob/master/src/entt/fwd.hpp

In my project, to reduce compile times I maintain a header that has forward declarations in it. I maintain the following definition so that I can pass around a memory buffer by reference without including the full fmt headers in my header files:

```C++
namespace fmt
{
inline namespace v10
{
template <typename T, size_t SIZE,
          typename Allocator>
class basic_memory_buffer;
}
} // namespace fmt::v10

using FmtBuffer = fmt::v10::basic_memory_buffer<wchar_t, 500, std::allocator<wchar_t>>;
```

This way in my header files I can pass around FmtBuffer by reference, without including all of libfmt in my header files. It's not too much trouble, but I do have to make sure when I update to newer versions that the values stay up to date. If I change the 500 to some other number, it still compiles for me but I think that is undefined behavior. Would it be possible to expose the type names through a header file such as the one entt maintains I linked above, or do you have some thoughts on why this wouldn't be a good idea?

Thanks so much for your time.

**Comment by vitaut** [comment]
Buffer types are not essential to {fmt}'s core functionality and not worth adding extra headers. For those part that are essential we already have a header with minimal dependencies, `fmt/core.h`. BTW you probably don't want to have `basic_memory_buffer` at the API boundaries.
