### ISSUE TITLE
`formatted_size` with format specifiers & `FMT_COMPILE`

### ISSUE THREAD

**Issue by elbeno** [fmtlib/fmt#3586]
`formatted_size` doesn't work with format specifications when using `FMT_COMPILE`.
(See also: issue #2141)

https://godbolt.org/z/G595Y78ns

CE currently uses 10.0.0 but the same issue is on master.
It does work with `{:d}` but not with `{:x}` or `{:b}`. `{:s}` doesn't work either (obviously for a stringish case). I haven't tried more complex format specs. `{:x}` and `{:b}` work if I mark https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L1390 as `constexpr`, but I'm not sure that's a good fix (and doesn't address `{:s}`).

**Comment by vitaut** [comment]
Making `format_uint` (conditionally) `constexpr` is the right solution and a PR is welcome. Similarly, for string formatting some additional constexprification is needed.
