### ISSUE TITLE
Intended effect of: "Disallowed passing temporaries to make_format_args to improve API safety by preventing dangling references."?

### ISSUE THREAD

**Issue by thraneh** [fmtlib/fmt#3589]
Is this the intended effect of (from the 10.1.0 release notes)

> Disallowed passing temporaries to make_format_args to improve API safety by preventing dangling references.

```cpp
template <typename... Args>
constexpr auto test_format(std::string_view const &format_str, Args &&...args) -> std::string {
  return fmt::vformat(format_str, fmt::make_format_args(std::forward<Args>(args)...));
}
auto foo(auto value) {
  return value + 1;
}
```

Both of these cases will fail

```cpp
test_format("{}", 123);
test_format("{}", foo(123));
```

Using gcc 13.1.0

```
error: cannot bind non-const lvalue reference of type 'int&' to an rvalue of type 'int'
[...]
note:   initializing argument 1 of 'constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<_Args>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {int}]'
```

This will work

```cpp
auto value = foo(123);
test_format("{}", value);
```

However, a very common use case

```cpp
try {
  throw std::runtime_error{"test"};
} catch (std::exception &e) {
  test_format("{}", e.what());
}
```

Which will now fail with

```
error: cannot bind non-const lvalue reference of type 'const char*&' to an rvalue of type 'const char*'
```

Edit: Corrected the try-catch example.

**Comment by vitaut** [comment]
The usage of `make_format_args` in your example is incorrect - there should be no forwarding, see e.g. https://fmt.dev/latest/api.html#argument-lists. And I recommend using `format` instead of `vformat` to ensure that format strings are checked at compile time.

**Comment by TobiSchluter** [comment]
Can you link here or to the corresponding section of the documentation from the release notes? I was surprised by this as well.

Also, isn't something where `make_format_args` is itself a temporary and used in the obvious way, e.g.
```
template <typename... Args>
constexpr auto test_format(std::string_view const &format_str, Args &&...args) -> std::string {
  return fmt::vformat(format_str, fmt::make_format_args(args...));
}
constexpr auto foo() {
  return std::string("temporary");
}

...
test_format("bla {}\n", foo());
```
well-defined but now rejected? At least in my (weak) understanding, the `format_args`' lifetime is guaranteed to be less than that of the result of `foo()` as the full expression containing `make_format_args` finishes evaluating before `test_format()` returns and thus before the call to `test_format` finishes.

**Comment by thraneh** [comment]
The answer was spot on. But I also then had to study why it was wrong to use `std::forward`. It was this [commit](https://github.com/fmtlib/fmt/commit/8f18e72df576ebfbd088a57a5c6cae8d4d0fc3dc) that changed `&&` to `&`.

**Comment by aaron-michaux** [comment]
Doesn't this create a performance issue in generic code? What if a parameter pack has a mixture of L and R references... won't the following make unnecessary copies of the L references?

```
auto instantiated{std::make_tuple(std::forward<Args>(args)...)};
```

I appreciate the intent here; however, asan/valgrind should catch dangling references!

**Comment by vitaut** [comment]
{fmt} doesn't need to copy (or move) arguments because they are in scope for the duration of formatting.

**Comment by aaron-michaux** [comment]
This is TRUE, however, it opens up an issue when using `vformat`. Like:

```
fmt::vformat(bespoke_pattern, fmt::make_format_args(...))
```

But I _cannot_ `fmt::make_format_args(fmt::join(data, ", "), ...)` because `fmt::join` returns an rvalue reference.

Okay, I have this in logging code. I can:
(1) Go and change all the logging sites, and `fmt::join(data, ", ")`, assign it to a variable, before passing it to the log. Ouch.
(2) Create a cheeky generic function that converts all rvalue references to lvalue reference, in which case, why did you make me do that! Crazy.
(3) Assign everything to a tuple in my generic logging code. Neat for rvalue reference, but what if there's an lvalue reference! Performance.

So I have to choose between: Ouch, Crazy, and Performance. Since we're C++ devs, we'll always choose Ouch and Crazy.

**Comment by vitaut** [comment]
There is no reason to use `make_format_args` or `vformat` here, just use `format`.

**Comment by aaron-michaux** [comment]
> There is no reason to use `make_format_args` or `vformat` here, just use `format`.

We have a large codebase, where formats are specified in the configuration of the program. So the `vformat` arg is ultimately coming from outside the process, long after it has been compiled.

Don't at me: I didn't write it.

However, it's simply not true that the world can "just use `format`"

**Comment by vitaut** [comment]
You can wrap format strings that are only known at runtime in `fmt::runtime`: https://fmt.dev/11.1/api/#runtime. `vformat` should only be used for **implementing** some custom formatting functions.

**Comment by aaron-michaux** [comment]
Thank you.
