### ISSUE TITLE
fmt::sprintf nonexistant

### ISSUE THREAD

**Issue by chaosfissure** [fmtlib/fmt#359]
I'm currently working on a logging library that makes use of fmt.  

The Format API reference indicates that a fmt::sprintf function exists here: http://fmtlib.net/latest/api.html?highlight=sprintf#_CPPv2N3fmt7sprintfE10CStringRef7ArgList

I have code that uses fmt::sprintf as mentioned per the API, but it does not compile:

```
	template <class ...Args>
	inline void HandlePrintfStyle(const char* src, std::unordered_set<std::string>&& tags, const char* format, Args&& ...args)
	{
		LogPrintfStyle(src, std::move(tags), fmt::sprintf(format, std::forward<Args>(args)...));
	}
```
The error message I receive is this:

> MSVC2015: Error C2039 'sprintf': is not a member of 'fmt' (compiling source file ...)

Doing a search through "format.h", there is no reference to a "sprintf" function.

**Comment by chaosfissure** [comment]
It turns out I was missing the printf header from my include chain.  Once I included it, I was able to compile the code.

Similar to the date and time formatting example (http://fmtlib.net/latest/api.html?highlight=sprintf#date-and-time-formatting), would it be possible to include references to what headers would be necessary to make use of certain functions from within the API?

**Comment by vitaut** [comment]
I've clarified in the docs that `fmt/printf.h` is needed to use the `printf` functionality: http://fmtlib.net/dev/api.html#printf-formatting. Thanks!
