### ISSUE TITLE
std::filesystem::path no longer quoted since 10.1.0

### ISSUE THREAD

**Issue by Dani-Hub** [fmtlib/fmt#3590]
Starting with 10.1.0, the `std::filesystem::path` formatter does no longer add quotes to the path name (except when activating the debug flag), as demonstrated here:

https://godbolt.org/z/rKfzqhKha

This seems to be an undocumented, breaking change and also is not consistent with the most recent suggestions to define a formatter for `std::filesystem::path` (e.g. [P2845R1](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2845r1.html)), where quoting is enabled by _default_.

This change makes it currently not possible for us to use the most recent version, since we use formatting `std::filesystem::path` to large amounts.

**Comment by vitaut** [comment]
The exact format is not specified and subject to change until standardized. It addresses the C++ committee feedback.

**Comment by vitaut** [comment]
Yeah, will update the changelog. BTW you can get the quoted format with the `?` specifier similarly to strings.
