### ISSUE TITLE
user defined types formatting with sprintf

### ISSUE THREAD

**Issue by stefan301** [fmtlib/fmt#3603]
I'm currently upgrading fmtlib from 8.1.1 to 10.1.0 in our application. We use fmt::format most of the time but still have many fmt::sprintf calls. Because this is a MFC application we use CString a lot.
While fmt::sprintf worked with CString in 8.1.1 those calls fail to compile with 10.1.0 and didn't find a way to define a formatter. Neither format_as nor a defined wostream for CString works.

Is there any way to tell sprintf to format a CString like a wstring/wstring_view?

`
#include <afx.h>
#include <fmt/format.h>
#include <fmt/printf.h>
#include <fmt/xchar.h>
#include <string>
#include <iostream>
#include <ostream>

#if FMT_VERSION > 80101		// not needed with fmt 8.1.1
namespace ATL
{
	auto format_as(CString s) { return std::wstring_view(s.GetString(), s.GetLength() + 1); }
}

std::wostream& operator<<(std::wostream& os, const CString& value)
{
	os << value.GetString();
	return os;
}
#endif

int main()
{
	std::wstring_view sv = L"Hello World";

	std::wcout << fmt::format(L"fmt::format(std::wstring_view): {}\n", sv);
	std::wcout << fmt::sprintf(L"fmt::sprintf(std::wstring_view): %s\n", sv);

	CString s = L"Hello World";

	std::wcout << fmt::format(L"fmt::format(CString): {}\n", s);

	// this call doesn't compile with fmt 10.1.0 (even with format_as and operator<<)
	//std::wcout << fmt::sprintf(L"fmt::sprintf(CString): %s\n", s);
}
`

**Comment by vitaut** [comment]
No, user-defined types are only supported by the format family of functions. `fmt::printf` is mostly for making legacy code safer and not recommended for anything else.
