### ISSUE TITLE
Add means to check if a given format string can be bounded to a max length.

### ISSUE THREAD

**Issue by ldrozdz93** [fmtlib/fmt#3604]
I'm not sure how to phrase the title, but the case is: I'm using `fmt::format` to create some labels for telemetry in my app. The heap allocation has a considerable impact on performance (it's on the top of the perf benchmarks). 

The format is well-defined (mostly constexpr strings and runtime numbers). If I could check if a given `format+args` combination has some maximum possible lenght and I could get that length, then I could by default fallback to using some stack buffer aka. `static_string` or sth similar. 

The pseudo-code I'm interested in is:
```c++
template<typename... T>
auto format_maybe_static(format_string<T...> fmt, T&&... args) {
  if constexpr (is_bounded_to_some_max_lenght(fmt)) 
  {
    constexpr auto max_possible_length = max_len(fmt);
    static_string<max_possible_length> result{};
    fmt::format_to_n(result.begin(), fmt, FWD(args));
    return result;
  } 
  else {
    return fmt::format(fmt, FWD(args));
  }
}
```

I haven't found it possible with the current `fmtlib`, though of course I might have missed it.

Best regards,
Łukasz

**Comment by vitaut** [comment]
{fmt} doesn't have anything like that.
