### ISSUE TITLE
[MSVC][/Zc:wchar_t-] xchar.h

### ISSUE THREAD

**Issue by thegoodtgg** [fmtlib/fmt#3613]
Template specialization error.
https://godbolt.org/z/8Wxv1P6h1

**Comment by vitaut** [comment]
{fmt} requires a somewhat standard-compliant compiler which msvc with `/Zc:wchar_t-` is not.

**Comment by thegoodtgg** [comment]
I guess so. I would use "fmt::wformat" wrapper of "fmt::format" to work around the problem in my project.
