### ISSUE TITLE
Odd AVX math behavior with FMT_EXCEPTIONS 0 -- maybe compiler bug or UB?

### ISSUE THREAD

**Issue by lgritz** [fmtlib/fmt#3620]
Apologies in advance, I have been unable to reproduce this heisenbug outside of my complicated code base, and I'm running around in circles unable to narrow it down to a small repro case or make a demo in godbolt. But rather than sweep it under the rug, I want to at least mention as much as I can describe here, in the hopes that it triggers an "aha" in somebody reading this.

The basic situation is that in some unit tests for vector SIMD (avx, etc.) classes, I'm getting weird results (WRONG values for some math, NaNs for some). Not everywhere, just one particular sequence of math operations. Of course, if I extract that from its environment in any way, it works fine. Even putting the same calculations elsewhere in the application also works fine.

It is important to note that it's NOT in or directly involving a fmt call. However, it started happening on my CI tests when I bumped to fmt 10.1.0. Specifically, I have bisected the fmt version and found that I do not get the error up to and including commit e0fc0e85e31b457b, but I get the failures starting at commit 9a034b0d557718e1, and all the way up to the current top of your master.  The curious thing is that this is a very innocuous commit, consisting solely of

```diff
----------------------------- include/fmt/format.h -----------------------------
index f6dd742d..a6265b79 100644
@@ -114,10 +114,8 @@ FMT_END_NAMESPACE
 #      define FMT_THROW(x) throw x
 #    endif
 #  else
-#    define FMT_THROW(x)               \
-      do {                             \
-        FMT_ASSERT(false, (x).what()); \
-      } while (false)
+#    define FMT_THROW(x) \
+      ::fmt::detail::assert_fail(__FILE__, __LINE__, (x).what())
 #  endif
 #endif
```

I'm really at a loss to describe why this change in particular seems to be triggering strange math behavior elsewhere in the module of my code.

I should note that I have `#define FMT_EXCEPTIONS 0` in my headers prior to including the fmt headers. It's been like that for years, I added it when I upgraded to fmt 6.1.1, but unfortunately I cannot remember why I did it or what problem I thought I was fixing by adding that define.

Some other oddities:

* If I remove my disabling of FMT_EXCEPTIONS (or alternately, if I define FMT_THROW(x) to `throw x`, the problem goes away. Also it works fine if I define FMT_THROW myself to print to stderr and call abort().
* The problem only occurs with gcc (can't seem to repro with clang), and only for gcc >= 11. When using gcc 9, it's fine.
* Commenting out other code in my module (sometimes not even especially close to the spot having the problem) can make the issue come and go.

I'm suspecting either a compiler bug or undefined behavior that this is tripping over, but I don't have a concrete hypothesis for why.

I should also say that my code does `#define FMT_HEADER_ONLY`, so it's seeing the format-inl.h, including the definition of fmt::detail::assert_fail. 

I've spun on this (on and off, it's not an emergency) for days without making much progress. My workaround for now is not to disable fmt exceptions, but that makes me a little nervous because I'm not sure why it was deemed necessary in the first place, and I'm worried that users of my software might be dependent on being exception-free.

I'm hoping maybe somebody reading has had a similar issue or has some ideas for what might be up.
Thanks for your attention.

**Comment by vitaut** [comment]
Have you tried running with ubsan?

**Comment by lgritz** [comment]
ubsan didn't turn up anything interesting.

**Comment by vitaut** [comment]
I am going to close this issue since it's not actionable and disabling exceptions is not recommended anyway but feel free to reopen with a repro or more information.
