### ISSUE TITLE
Using Manipulators With Arguments

### ISSUE THREAD

**Issue by sergegers** [fmtlib/fmt#3621]
It will be nice to implement boost::format feature allowing to support manipulators with arguments. Like this:

`std::cout << (boost::format("my int: %1%\n") %boost::io::group(std::hex, std::showbase, 3));`

https://godbolt.org/z/s6KznYaGb

**Comment by vitaut** [comment]
You can already do this via the extension API: https://fmt.dev/latest/api.html#formatting-user-defined-types.

**Comment by sergegers** [comment]
> You can already do this via the extension API
Nop, this is not the same. I can't use manipulators "inline", I need to overload a function format_as() or specialize formater template.

**Comment by vitaut** [comment]
You can write a single formatter that does exactly what you want. I wouldn't recommend it though since manipulators are very verbose and inefficient.

**Comment by sergegers** [comment]
I have about one hundred custom manipulators and I do not want to write 100 formatters. Ok. You haven't plans to support manipulators. I understand.

**Comment by vitaut** [comment]
You can write a single formatter that supports arbitrary manipulators (a formatter for something like `boost::io::group`).
