### ISSUE TITLE
A Wdeprecated error

### ISSUE THREAD

**Issue by cyyever** [fmtlib/fmt#3629]
fmt/include/fmt/chrono.h:340:24: error: redundant redeclaration of ‘constexpr’ static data member ‘fmt::v10::detail::codecvt_result<CodeUnit>::max_size’ [-Werror=deprecated]
  340 | constexpr const size_t codecvt_result<CodeUnit>::max_size;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by vitaut** [comment]
Fixing all possible warnings is a non-goal but a PR would be welcome.
