### ISSUE TITLE
add %1, %2, ... support to printf API

### ISSUE THREAD

**Issue by Joker2387089590** [fmtlib/fmt#3635]
When I want to format a string to JSON, the `{}` conflicted, so I found that `https://fmt.dev/latest/api.html#printf-api`.
But it requires me to provide the exact type of arguments, which is so complicated.
Usually I use Qt's `QString::arg` [https://doc.qt.io/qt-6/qstring.html#arg-14] to do so, however I need a std::string or my program may be running without Qt support.
I think this function can be supported by printf API or maybe increase another new API.

**Comment by vitaut** [comment]
I don't think we should add another format API but you could probably create one yourself by reusing some of the {fmt} infra.
