### ISSUE TITLE
expose formatter specs member for better reuse

### ISSUE THREAD

**Issue by zhuoqiang** [fmtlib/fmt#3640]
currently the `specs_` is private in the build-in formatter class. I am wondering if it could be exposed for public read / write, so that the formatter class could be reused in more situation.

for example, if there is a customized `Price` type, and it should always be output no more than 2 precision, it would be possible to reuse `formatter<double>` like following if `specs_` could be accessed and modified in derived class:

``` cpp
template <>
struct formatter<Price> : formatter<double> {
    auto parse(format_parse_context& ctx) {
        const auto it = formatter<double>::parse(ctx);
        // compile error now: specs_ is private
        // but if it is accessable, we could cap it to 2
        this->specs_.precision = min(this->specs_.precision, 2);
        return it;
    }

    auto format(const Price& d, format_context& ctx) const {
        return formatter<double>::format(static_cast<double>(d), ctx);
    }
};

```

**Comment by vitaut** [comment]
Thanks for the suggestion but this is an internal API and shouldn't be exposed.
