### ISSUE TITLE
helper method for char array as string view

### ISSUE THREAD

**Issue by zhuoqiang** [fmtlib/fmt#3641]
suppose we need to format `char name[3]` as string. and there maybe 

- `\0` in the middle of the array
- or no `\0` at all (3 chars are all used as name)

we have to take care of it manually.

I was wondering if we could add a helper method in fmtlib, just like `fmt::ptr()` does

something like following `AsString()` helper method: 

https://godbolt.org/z/eWjGGsxWd

```cpp
#include <fmt/core.h>
#include <array>
#include <cstring>

// a dedicated type for wrapping char array
// do not use std::array directly since it will be formatted like a container in fmt
template <size_t N>
struct CharArrayAsStringWrapper {
    std::array<char, N> data;
};

// helper method for end user
template <size_t N>
constexpr auto AsString(const char (&a)[N]) noexcept {
    return CharArrayAsStringWrapper<N>{.data = std::to_array(a)};
}

namespace fmt {

// special formatter for char array wrapper
template <size_t N>
struct formatter<CharArrayAsStringWrapper<N>> : formatter<string_view> {
    auto format(const CharArrayAsStringWrapper<N>& d,
                format_context& ctx) const -> format_context::iterator {
        // treated it like a normal null-terminated c string
        const auto length = ::strnlen(d.data.data(), d.data.size());
        return format_to(ctx.out(), "{}", string_view(d.data.data(), length));
    }
};
} // namespace fmt


int main() {
    char a[3] = {'1', '\0', '3'};
    char b[3] = {'a', 'b', 'c'};
    // output will be garbaged
    // fmt::print("{} {}", a, b);

    fmt::print("{} {}", AsString(a), AsString(b));
    return 0;
}
```

or we could use `string_view` as the wrapper directly:

https://godbolt.org/z/bo83E9T1K

``` cpp
#include <fmt/core.h>
#include <cstring>
#include <string_view>

// helper method for end user
template <size_t N>
constexpr auto as_string_view(const char (&a)[N]) noexcept {
    const size_t length = ::strnlen(a, N);
    return std::string_view(a, length);
}

int main() {
    char a[3] = {'1', '\0', '3'};
    char b[3] = {'a', 'b', 'c'};
    // output will be garbaged
    // fmt::print("{} {}", a, b);

    fmt::print("{} {}", as_string_view(a), as_string_view(b));
    return 0;
}
```

**Comment by zhuoqiang** [comment]
look like a similar issue as #203

**Comment by vitaut** [comment]
Thanks for the suggestion but you can already write such function if you have to deal with embedded NULs often, it doesn't need to be added to the core library.

**Comment by zhuoqiang** [comment]
> Thanks for the suggestion but you can already write such function if you have to deal with embedded NULs often, it doesn't need to be added to the core library.

there is a security issue if fmt treats c char array like null-terminated c string. If there's no `\0` in the array:

https://godbolt.org/z/3E7rjoWod

```cpp
#include <fmt/core.h>

int main() {
    union
    {
      char no_0[2];
      char mid_0[6]{'1', '2', '3', '4', '\0', '6'};
    } char_arrays;

    // should output 12, but got 1234 instead:
    fmt::print("{}", char_arrays.no_0);
    return 0;
}
```

It is better to use `strnlen()` / `strnlen_s()` for calculating the length of c char array inside fmtlib

**Comment by vitaut** [comment]
That's how C strings are handled in all of the standard library. It doesn't make sense to do any heroics here.

**Comment by zhuoqiang** [comment]
C strings have a well-known reputation for being insecure.

One of the major advantage of c++/fmtlib against c/printf is the type safety and security for free.

It would be great if fmtlib could take advantage of the compile time length information encoded in the type of `char[N]` to make it safer
