### ISSUE TITLE
Unexpected output from intel fmt::fprint

### ISSUE THREAD

**Issue by gsjaardema** [fmtlib/fmt#3645]
With the following program:
```
#include <fmt/printf.h>
int main()
{
    fmt::printf("%d:%d %f %s\n", 3, 1234, 12.345, "weekend");
}
```
I get the expected output on most compiler and lib::fmt version combinations:
```
3:1234 12.345000 weekend
```

However, if I use the intel compiler with either 10.0.0 or trunk, I get:
```
3:1234 12.345001 weekend
```
Notice the `1` at the end of the floating point output.  I'm not sure where this is coming from or how to get the same output on intel with 10.0.X as I get with intel and earlier lib::fmt versions or with all other compilers I have tried.

Here is a compiler explorer link:  https://godbolt.org/z/MzG7T9bfr

**Comment by gsjaardema** [comment]
I added the c-library printf call:
```
    printf("%d:%d %f %s\n", 3, 1234, 12.345, "weekend");
```
And that gives me the "expected" output:
```
3:1234 12.345000 weekend
```

**Comment by gsjaardema** [comment]
I also tried with the `%g` format specifier for the double parameter and get:
```
3:1234 12.3451 weekend
``` 
which is worse accuracy.

If I loop from 0.345 to 100.345:
```
include <fmt/printf.h>
int main()
{
   for (int i = 0; i < 100; i++) { 
        double di = (double)i;
        fmt::printf("%d:%d %g %s\n", 3, 1234, i+.345, "weekend");
    }
}
```
The extraneous `1` is added on for these values:
```
3:1234 7.345 weekend
3:1234 8.34501 weekend
3:1234 9.34501 weekend
3:1234 10.3451 weekend
3:1234 11.3451 weekend
3:1234 12.3451 weekend
3:1234 13.3451 weekend
3:1234 14.3451 weekend
3:1234 15.3451 weekend
3:1234 16.345 weekend
```

**Comment by vitaut** [comment]
Interestingly, the issue doesn't happen with `print`: https://godbolt.org/z/1s3ebbv9K.

**Comment by gsjaardema** [comment]
> Interestingly, the issue doesn't happen with `print`: https://godbolt.org/z/1s3ebbv9K.

Yes, I noticed that.  The assembly output is also much cleaner and smaller.

**Comment by gsjaardema** [comment]
We found another strangeness:
```
int main()
{
    fmt::printf("%g %g\n", -10., 2.);
}
```
Returns:
```
-10.0001 2.00001
```

**Comment by vitaut** [comment]
Could be related to #3262.

**Comment by gsjaardema** [comment]
> Could be related to #3269.

That is where a git bisect points for me also.

**Comment by gsjaardema** [comment]
> Interestingly, the issue doesn't happen with `print`: https://godbolt.org/z/1s3ebbv9K.

Although it does it you define `FMT_HEADER_ONLY`.  https://godbolt.org/z/vazbMba97

**Comment by vitaut** [comment]
Maybe @jk-jeon has some insights regarding what might be causing this.

**Comment by jk-jeon** [comment]
I guess this is probably because the rounding criteria is evaluated wrongly. Possible line of problem I think is:
https://github.com/fmtlib/fmt/blob/a3a74fa7f3a6803f34459b36640b0c665a5a60d9/include/fmt/format.h#L3527

Assuming the input is `12.345`, the values of involved variables must be
```
prod = 31880000U
fractional_part = 31880000U
number_of_digits_to_print = 8
data::fractional_part_rounding_thresholds[8 - number_of_digits_to_print] = 2576980378U
digits = 0
second_third_subsegments = 63
has_more_segments = true
```
and the condition should evaluate as `false`. 

But somehow `data::fractional_part_rounding_thresholds[0]` is evaluated as `0`. 

Actually, it seems that every entry of `data::fractional_part_rounding_thresholds` is initialized to zero for some reason I am not aware of. Fixing that will fix this issue I believe.

**Comment by jk-jeon** [comment]
It really sounds like a compiler bug: https://godbolt.org/z/hM33819Gv

**Comment by gsjaardema** [comment]
So does `basic_data` need to be a template struct?  I did remove the `template <typename T = void>` from `struct basic_data` and verified that it did fix the bug, but I don't know enough about the internals to know why it is a template structure...

**Comment by vitaut** [comment]
> So does basic_data need to be a template struct?

Yes, for the header-only mode. However, we are moving away from it in favor of storing such tables as static constexpr variables in functions which can be applied as a workaround here.

In any case, this is a severe bug in the Intel compiler, please report it.

**Comment by vitaut** [comment]
Thanks, @jk-jeon, for investigating!

**Comment by phprus** [comment]
> It really sounds like a compiler bug: https://godbolt.org/z/9MKsa8xjq.
> Apparently it only happens when the containing struct is a template and the member is an array.

This is EDG frontend and C++ >= 17 bug.
More info: https://github.com/fmtlib/fmt/pull/3043
