### ISSUE TITLE
version 10.0.0 is ok，but latest version raise error '_' uses undefined struct 'fmt::v10::detail::type_is_unformattable_for<T,char>'

### ISSUE THREAD

**Issue by liyqxtu** [fmtlib/fmt#3648]
fmt\include\fmt\core.h(1578,63): error C2079: '_' uses undefined struct 'fmt::v10::detail::type_is_unformattable_for<T,char>'
1>        with
1>        [
1>            T=nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>>
1>        ]
fmt\include\fmt\core.h(1582,7): error C2338: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt

**Comment by vitaut** [comment]
The error simply means that the type `nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>>` is not formattable. See https://fmt.dev/latest/api.html#formatting-user-defined-types.

**Comment by hoho965191737** [comment]
Hi, I was wondering if you solved the problem yet? How did you solve it
