### ISSUE TITLE
can't compile with vc2015

### ISSUE THREAD

**Issue by qicosmos** [fmtlib/fmt#365]
using FMT_HEADER_ONLY. compile error: "fmt\printf.h(345)"

**Comment by vitaut** [comment]
Could you post the full error message?

**Comment by vitaut** [comment]
The following example compiles fine on vc2015:

```c++
#define FMT_HEADER_ONLY 1
#include "fmt/printf.h"

int main() {
  fmt::printf("%d", 42);
}
```

so I'm closing this issue, but feel free to reopen providing more details on reproducing it.

**Comment by qicosmos** [comment]
@vitaut I found why the code compile error, the min/max function confilict with vc2015, so i use the pre-define micore NOMINMAX, and the code compile success.
