### ISSUE TITLE
fmt::sprintf  and char16_t/char32_t problems

### ISSUE THREAD

**Issue by ruifig** [fmtlib/fmt#3651]
I'm using Windows (latest VS 2022), and latest of fmt (a3a74fa7f3a6803f34459b36640b0c665a5a60d9), and I'm having the following problem, which I'm not sure it's expected...

`fmt::format` seems to work ok with any string type I pass, while `fmt::sprintf` does not.
Specifically, I'm having problems with std::u16string/char16_t and std::u32string/char32_t. 
The following code shows what is happening:

```
#include <string>
#include <fmt/printf.h>
#include <fmt/xchar.h>

void fmttest()
{
	{
		std::string str1    = fmt::sprintf( "%d %s", 42,  "test"); // Result is: 42 test
		std::u16string str2 = fmt::sprintf(u"%d %s", 42, u"test"); // Result is: 42 0x7ff6f1dff350
		std::u32string str3 = fmt::sprintf(U"%d %s", 42, U"test"); // Result is: 42 0x7ff6f1dff370
		std::wstring str4   = fmt::sprintf(L"%d %s", 42, L"test"); // Result is: 42 test
	}

	{
		std::string str1    = fmt::format( "{} {}", 42,  "test"); // Result is: 42 test
		std::u16string str2 = fmt::format(u"{} {}", 42, u"test"); // Result is: 42 test
		std::u32string str3 = fmt::format(U"{} {}", 42, U"test"); // Result is: 42 test
		std::wstring str4   = fmt::format(L"{} {}", 42, L"test"); // Result is: 42 test
	}
}
```

Looks like `fmt::sprintf` for `char16_t` and `char32_t` is printing `"test"` as a pointer, while `fmt::format` works fine.
Is this expected behaviour?

**Comment by vitaut** [comment]
As their standard counterpart, `fmt::sprintf` only supports `char` and `wchar_t`. Made it more explicit in https://github.com/fmtlib/fmt/commit/72e883e163996b6196b85e5aa8c97189894ddc16. More exotic code unit types are only supported in `fmt::format`.
