### ISSUE TITLE
Compilation fails using Clang 17 toolchain

### ISSUE THREAD

**Issue by Steveice10** [fmtlib/fmt#3654]
MSYS2 just updated their clang and associated packages to 17.0.1. We are now seeing the following compilation error:

```
fmt/include/fmt/ostream.h:17:12: fatal error: '__std_stream' file not found

   17 | #  include <__std_stream>

      |            ^~~~~~~~~~~~~~
```

This seems to be related to the following change in libcxx: https://reviews.llvm.org/D147855

**Comment by vitaut** [comment]
Removed the nonportable include in https://github.com/fmtlib/fmt/commit/2dd4fa8742fdac36468f8d8ea3e06e78215551f8. Thanks for reporting.

**Comment by Steveice10** [comment]
Works now, thanks.

**Comment by lazka** [comment]
Note that there is still one include left here: https://github.com/fmtlib/fmt/blob/79dbd3f19285f2a6ce0c90932f06c173e424e25b/src/fmt.cc#L66-L68 which makes the build with "cmake -DFMT_MODULE=ON" fail.

**Comment by vitaut** [comment]
@lazka, could you submit a PR to remove it too?

**Comment by lazka** [comment]
sure, #3663

**Comment by Roman-Koshelev** [comment]
@vitaut wouldn't it make more sense to leave this hack for libc++ < 17? (native_handle() should be at 18)

**Comment by vitaut** [comment]
I don't think it's spending any efforts on conditionally supporting this hack for iostreams which are a legacy API.
