### ISSUE TITLE
non-obvious formatting of floating point numbers

### ISSUE THREAD

**Issue by Roman-Koshelev** [fmtlib/fmt#3657]
1. If the value representation type is not specified, then it is not g. A mandatory zero is added after the period. The number does not match the shortest representation.
2. Fixed point has a fixed precision of 6 digits. Only significant digits are expected (it doesn't matter if there are more than 6 or less)
https://godbolt.org/z/EEEedePaf

Somewhere it was written about compatibility with std. Will this be fixed?

**Comment by vitaut** [comment]
`std::to_chars` is a completely different API and we don't provide any compatibility guarantees with it.

**Comment by Roman-Koshelev** [comment]
But std::format is built on top of it and is compatible. fmt::format won't be fully compatible with std ?

**Comment by vitaut** [comment]
`std::format` is specified in terms of `std::to_chars` but for your examples to make sense you need to correctly form invocations to the latter. It doesn't make a lot of sense to talk about abstract compatibility of the two APIs. `fmt::format` is compatible with `std::format` on numeric types with one exception related to precision already tracked in https://github.com/fmtlib/fmt/issues/3649.
