### ISSUE TITLE
printf-like format to user supplied buffer

### ISSUE THREAD

**Issue by andreas-wehrmann** [fmtlib/fmt#3658]
I'm currrently in the process of updating my internal tracing library
(which is C based and uses printf format strings) so that it uses fmtlib internally
to finally get rid of all the issues that go along with the legacy print functions.

Currently, each log statement calls a function and is supplied: the logging context, loglevel, format-string, varargs...
Inside the function, the log is first printed to a buffer on the stack (zero terminated) and then it passes
the printed log on via a callback, where the printed text is simply passed as `const char*`.

My updated implementation of the C interface looks something like this (which works fine):

```
template<typename... ARGS>
void TraceLog( const char* func,
               const std::size_t lineno,
               const TraceSpec_t* ts,
               TraceLevel_t level,
               const ARGS&... args )
{
    try
    {
        ts->writeLine( ts->user_data, level, fmt::sprintf( args... ).c_str() );
    }
    catch( const fmt::format_error& )
    {
        TraceFormatStringError( ts, func, lineno );
    }
}
```

The thing is, `fmt::sprintf()` returns a `std::string` and many of the lines to be written out
are too long to benefit from SSO inside `std::string` meaning I'll have lots of dynamic allocations
which I _really_ don't want.

Maybe I'm missing something, but is there a way to use printf-like formatting with fmtlib
to a user supplied buffer, like it is possible with the "regular" format-style of fmtlib?

I found out that with "regular" style format I can do something like this:
```
std::array< char, 128 > buf;
auto res = fmt::format_to_n( buf.data(),
                             (buf.size() - 1),
                             "{}", 42 );
*res.out = '\0';
std::printf( "%s\n", buf.data() );
```
I basically need the same functionality for printf-like formatting.

**Comment by vitaut** [comment]
There is no way to format to a supplied buffer using `fmt::sprintf`. You could either copy the result to a buffer with truncation or use `format_to_n` (recommended).
