### ISSUE TITLE
Allow Exception Hooking in Builds with Binaries (Shared Lib)

### ISSUE THREAD

**Issue by ingo-loehken** [fmtlib/fmt#3659]
Hi,

Brief Description
- we need to redirect any `FMT_THROW` from the fmt to add stacktrace and other infos in a mixin type for error analysis.
- we currently build in a higly productive environment with fmt symbols located in an extra shared-lib
- there are three source locations in *fmt/format-inl.h* that use `FMT_THROW` and can therefore not be redirected (via redefining the macro) in builds using a shared-lib.

Proposed Change
- all three source locations with `FMT_THROW` from *fmt/format-inl.h* should be moved into *fmt/format.h* to allow redirection

Is there any chance a PR would be accepted ?

**Comment by vitaut** [comment]
What you are suggesting is not possible with separate compilation because it essentially requires moving all logic to headers. You should either compile {fmt} with `FMT_THROW` customized or use the header-only mode (which is similar to what you propose and not recommended).

**Comment by ingo-loehken** [comment]
Sorry, but, it as far as i analyzed the code, it should be possible, just to move the throw calls to headers, especially the throw call already wrapped in a function and just taking a const char*, would greatly improve tracability, by redirecting to mixin types.

Once applied, I will come-up with a PR, so that proposed changes get viewable.

**Comment by ingo-loehken** [comment]
Your were right, in that not all exceptions can be redirected by redefining FMT_THROW.

Therefore i rebuild fmt redirecting FMT_THROW to a hookable callback function, allowing to forward exceptions to the application level.

Thx.
