### ISSUE TITLE
Formatting durations

### ISSUE THREAD

**Issue by Richardk2n** [fmtlib/fmt#3662]
https://godbolt.org/z/x5MfPr1KW
The doc says, that durations can be formatted.
However, it only specifies how 'q' 'Q' and 'j' behave (with 'j' not being implemented; see #3643)
If I format a duration of e.g., 25h with 'H' `fmt::format` gives 01 `std::format` gives 25
What is supposed to happen?

Also, the new durations added in C++ 20 are seemingly not implemented in fmt.

fmt and std also use different suffixes for minutes.

On a more general note I would like to add, that within this standard durations can be formatted as either basically a time or in the lowest unit used. However, both feel very unnatural. Usually one would write durations using several as large as possible units.

Would it be possible to give durations more options and a natural default format?

**Comment by vitaut** [comment]
The definition of `%H` in the standard is a bit vague (https://eel.is/c++draft/time#tab:time.format.spec-row-15-column-2-sentence-1):

> The hour (24-hour clock) as a decimal number.

but I think 01 is correct and libc++ which has a more complete `std::format` implementation agrees: https://godbolt.org/z/Kaco7brjM.

> Also, the new durations added in C++ 20 are seemingly not implemented in fmt.
> fmt and std also use different suffixes for minutes.

Thanks for fixing these.

> Would it be possible to give durations more options and a natural default format?

Could you give an example illustrating what you mean by the natural format?

**Comment by Richardk2n** [comment]
When formatting `std::chrono::seconds(3700);` for example from a time measurement or a calculated eta, a natural output for me would be `1h 1min 40s` or even `1h 2min`.

**Comment by vitaut** [comment]
It is an intriguing idea but I don't think we need a format specifier for this. You can create a custom formatter instead.
