### ISSUE TITLE
fmtlib with clang HEAD and libstdc++ is failing due to missing `numeric_limits<_Float128>`

### ISSUE THREAD

**Issue by danakj** [fmtlib/fmt#3669]
https://godbolt.org/z/r895foc4s

* With clang HEAD and `-stdlib=libc++` there is no error.
* With clang HEAD and libstdc++ there **is** an error.
* With clang 16/17 and libstdc++ there is no error.
* With gcc there is no error.

**Comment by robert-andrzejuk** [comment]
Related? : https://github.com/llvm/llvm-project/issues/68168

**Comment by vitaut** [comment]
Yeah, looks like a clang issue.
