### ISSUE TITLE
An Infinite loop in the time formatter

### ISSUE THREAD

**Issue by danpla** [fmtlib/fmt#367]
`+` has higher precedence than `?:`, so [this line](https://github.com/fmtlib/fmt/blob/9dbb60c4c8019c0d851ce2e61f99cb5c74696369/fmt/time.h#L40) will not expand the buffer, giving an infinite loop with long `strftime` results. It should be:
```c++
buffer.reserve(buffer.capacity() + (size > MIN_GROWTH ? size : MIN_GROWTH));
```

Simple test:
```c++
    std::string s = "{:";
    for (int i = 0; i < 30; ++i)
        s += "%c";
    s += "}\n";

    auto t = std::time(nullptr);
    fmt::print(s, *std::localtime(&t));
```

**Comment by danpla** [comment]
An excerpt from [the manual](http://man7.org/linux/man-pages/man3/strftime.3.html):
>Note that the return value 0 does not necessarily indicate an error. For example, in many locales %p yields an empty string.  An empty format string will likewise yield an empty string.

Which is, again, will give an infinite loop with out of memory error. It probably makes sense to use [Python's approach](https://github.com/python/cpython/blob/382de664165ca4a3a422efee18f3be3937608ed6/Modules/timemodule.c#L670).

**Comment by vitaut** [comment]
Thanks for catching these! The first issue should be fixed in https://github.com/fmtlib/fmt/commit/1a23f9c274071a91edde9fc28895c45940d4e90d.

**Comment by vitaut** [comment]
The second issue should be fixed in https://github.com/fmtlib/fmt/commit/a5d0adf3953f0ae3e698d5b5702d1e5a7bf3d87e. Thanks again.
