### ISSUE TITLE
Printing enums as integers without explicit casts

### ISSUE THREAD

**Issue by kwaegel** [fmtlib/fmt#3671]
I'm trying to migrate some old logging framework code, and came across a behavior discrepancy between `printf` and `fmt::printf` when trying to print `enum` types. Specifically, the old `printf` command allows printing `enum` types as an integer without an explicit cast to int (since C/C++ allow for implicit casting of enums), but all `fmt` calls seem to require an explicit cast.

I'm trying to figure out if this is intended behavior, or a bug.

(Note that this question is specifically for `enum` types. C++11 `enum class` types would be expected to require a cast or use `fmt::underlying`, since one of the intended benefits of those is the removal of implicit casting.)

Example code: https://godbolt.org/z/b93cd74rf
```
#include <fmt/core.h>
#include <fmt/printf.h>

enum MyEnum { TestVal = 0 };

int main() {
    MyEnum val = TestVal;

    printf("%d", val);         // Works, prints '0'

    fmt::printf("%d", val);  // Compiler error, unformattable type.
    //fmt::print("{:d}", val);  // Compiler error, unformattable type.
    //fmt::print("{}", val);  // Compiler error, unformattable type.
    //fmt::print(fmt::runtime("{}"), val);  // Compiler error, unformattable type.
}
```

**Comment by vitaut** [comment]
This is intentional: both kinds of enums are handled identically in {fmt}. You can make them formattable via `format_as`.

**Comment by kwaegel** [comment]
Okay, I can work with that.

Is there a different place I should ask questions without cluttering up the GitHub issue tracker, or is this the preferred forum?

**Comment by vitaut** [comment]
You could ask them on StackOverflow with the fmt tag: https://stackoverflow.com/questions/tagged/fmt.
