### ISSUE TITLE
Format to raw pointer

### ISSUE THREAD

**Issue by zhiqiang-hhhh** [fmtlib/fmt#3672]
Hello, i am using fmt 7.x and formating output direct to a native char*  like this
```cpp
int FastDoubleToBuffer(double value, char* buffer) {
    auto end = fmt::format_to(buffer, "{:.15g}", value);
    *end = '\0';
    return end - buffer;
}
```
Currently , I want to use fmt 10.x, but it seems that `fmt::format_to` do not support format to a raw pointer anymore?

I am wandering what is the best practice in this situation? 

Thank you.

**Comment by vitaut** [comment]
It is supported: https://godbolt.org/z/aT4ssv5Ex.
