### ISSUE TITLE
Documentation:  User defined types

### ISSUE THREAD

**Issue by strtok** [fmtlib/fmt#368]
The features list mentions "user defined types", but I can't find any documentation or tests for these. Is it possible to allow an arbitrary class to print itself? (e.g. by overloading operator<<, or providing a std::string to_string() method like in java).

Thanks for this awesome library!

**Comment by mwinterb** [comment]
overloading operator<<:
http://fmtlib.net/latest/api.html#std-ostream-support
As mentioned, make sure to include fmt/ostream.h.

Also, defining a custom format() function has been mentioned as a supported extension point if you need custom format parsing here https://github.com/fmtlib/fmt/issues/341#issuecomment-224598777, but I don't know if there are any docs covering that (namely, what are preconditions and postconditions for the second parameter).

**Comment by vitaut** [comment]
Custom format string parsing is not documented yet, but as @mwinterb wrote ostream `operator<<` is supported and documented.
