### ISSUE TITLE
Float specs with at least one decimal

### ISSUE THREAD

**Issue by sunmy2019** [fmtlib/fmt#3681]
Do we have a float format spec describing "at least one decimal"?

```cpp
    fmt::println("{}", 1.0);      // 1
    fmt::println("{:.0f}", 1.0);  // 1
    fmt::println("{:.1f}", 1.0);  // 1.0
    fmt::println("{:.2f}", 1.0);  // 1.00
    fmt::println("{:.3f}", 1.0);  // 1.000
```

My use case is that, in JSON format, `fmt::print("{}", 1.0)` will be interpreted as an integer. But I need it to be a float.

https://godbolt.org/z/W7bWj8YP9

Do we have specs acting like Python? 
``` py
>>> f"{1.0}"
'1.0'
```
```cpp
fmt::println("{:???}", 1.0);      // 1.0
```

**Comment by vitaut** [comment]
You could use `#` to preserve the decimal point.

**Comment by sunmy2019** [comment]
Thanks! I overlooked it.

**Comment by sunmy2019** [comment]
> You could use `#` to preserve the decimal point.

I tried it today. How to add one more `0` after, since JSON did not recognize `1.` as a valid float.

**Comment by vitaut** [comment]
You might need to add it manually.
