### ISSUE TITLE
What exactly happens at compile time

### ISSUE THREAD

**Issue by nuuSolutions** [fmtlib/fmt#3682]
... and could that be documented a little better?

**Comment by vitaut** [comment]
Not sure what you are asking about but both compile-time checks and format string compilation are documented in https://fmt.dev/latest/api.html. If you are interested in implementation details a better place to ask is https://stackoverflow.com/questions/tagged/fmt.

**Comment by vitaut** [comment]
I think most of these are either already explained, e.g. 

> Format string compilation can generate more binary code compared to the default API and is only recommended in places where formatting is a performance bottleneck.

In other cases we cannot give general advice because you'll need to do an actual perf measurements for your case.

If you have specific suggestions to improve the wording, a PR would be welcome.

**Comment by nuuSolutions** [comment]
I have spent 2 hours with your lib, do you really think I should write the documentation?

Would it be perv if YOU provided some 'perf' results and further insights?
