### ISSUE TITLE
Inconsistency between fmt::to_string(_) and fmt::format("{}", _)

### ISSUE THREAD

**Issue by avikivity** [fmtlib/fmt#3684]
```c++
#include <fmt/format.h>
#include <iostream>
#include <vector>
#include <fmt/ranges.h>

int main() {
    std::vector<std::string> x = { "abc", "def"};

    std::cout << fmt::format("{}", std::string("abc")) << std::endl;
    std::cout << fmt::format("{}", x) << std::endl;
    std::cout << fmt::to_string(x) << std::endl;
    return 0;
}
```

prints

```
abc
["abc", "def"]
[abc, def]
```

to_string() and fmt::format() return different results. I understood to_string() to be a simpler/faster fmt::format() with everything defaulted.

Why does the range formatter insert unnecessary escapes? Maybe it would be better to only insert them to make the output unambiguous.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/19276d73254f2b06e5d466f45c7390f1ccf0354e, thanks for reporting. Conditional escaping is an interesting idea but it might be confusing to users and the format is pretty much fixed anyway.
