### ISSUE TITLE
Specializing std::pair formatter leads to compile failures

### ISSUE THREAD

**Issue by avikivity** [fmtlib/fmt#3685]
```c++
#include <map>
#include <fmt/format.h>
#include <fmt/ranges.h>
#include <fmt/std.h>
#include <fmt/ostream.h>

struct x {};

template <typename K>
struct fmt::formatter<std::pair<K, x>> : fmt::formatter<std::string_view> {
    auto format(const std::pair<K, x>& p, auto& ctx) const {
        return fmt::format_to(ctx.out(), "x/x");
    }
};

int main() {
    std::map<x, x> v{{}, {}};
    fmt::print("{}\n", v);
    return 0;
}
```

This doesn't build, since map's formatter calls the pair formatter's set_brackets() and set_separator(), which don't exist.

set_brackets() and set_separator() are undocumented, so it's not reasonable to expect them to exist.

I think map's formatter should check to see if it's using the standard pair formatter before calling undocumented methods.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/16cec4f5913ef4c5c734290cd0d1eda39cf36bd0, thanks for reporting. I recommend opening an LWG issue since the standard map formatter introduced in P2286 likely has the same problem.

**Comment by avikivity** [comment]
How does one file an LWG issue?

**Comment by Dani-Hub** [comment]
> How does one file an LWG issue?

Read [How to submit an LWG issue](https://cplusplus.github.io/LWG/lwg-active.html#submit_issue)
The email address is provided in the top part of the same document

**Comment by avikivity** [comment]
Done, thanks.

**Comment by avikivity** [comment]
Unfortunately my report was rejected. I was too lazy to port it to <format>, but when I did I couldn't reproduce as none of the trunk stdlibs on godbolt support formatting maps [1], which is a prerequisite for a reproducer.

[1] though llvm/llvm-project@b23735407008948829ab24036d979427ddbbe121 mentions it's implemented

**Comment by vitaut** [comment]
I don't think we need a repro, the broken behavior is clear from the spec: https://eel.is/c++draft/format#range.fmtmap-2.

**Comment by avikivity** [comment]
If you want me to read standardese, then I want a raise

**Comment by vitaut** [comment]
https://cplusplus.github.io/LWG/issue4107
