### ISSUE TITLE
build warning with gcc trunk tautological-compare

### ISSUE THREAD

**Issue by qdztxc** [fmtlib/fmt#3686]
ThirdParty/include/quill/bundled/fmt/ranges.h:215:59: error: self-comparison always evaluates to true [-Werror=tautological-compare]
  215 |                                integer_sequence<bool, (Is == Is)...>);
      |                                                        ~~~^~~~~

**Comment by vitaut** [comment]
Thanks for reporting but fixing all possible warnings is a non-goal. That said a PR to suppress it would be welcome provided that it is not very intrusive.
