### ISSUE TITLE
Incorrect call to fflush() inside write_console()

### ISSUE THREAD

**Issue by dimztimz** [fmtlib/fmt#3688]
In this very recent change 3b7f58a8b3e35cfee57558a41e3e897b0ba7106a which originates from this PR #3668, the added call to `fflush` is incorrect and may brake the `std::ostream` overloads of `print()`. The intention was to implement the paper https://wg21.link/P2539/ in FMT here.

The correct behavior is to remove `fflush` from `write_console()` and call it before calling `write_console()`, but only from the C stream overloads of print, i.e. `print(FILE*,...)`. For the ostream overloads one should call `ostream::flush()`.

**Comment by vitaut** [comment]
It is not incorrect, just unnecessary. A PR to remove it would be welcome.
