### ISSUE TITLE
C++11 compile flag gets added to C compile flags

### ISSUE THREAD

**Issue by maddinat0r** [fmtlib/fmt#369]
I have a project that adds the fmt library via `add_subdirectory`. My project additionally has a C file. [`target_compile_options`](https://github.com/fmtlib/fmt/blob/1a23f9c274071a91edde9fc28895c45940d4e90d/fmt/CMakeLists.txt#L19) seems to add the C++11 flag (`FMT_USE_CPP11` is set to true) not only to all of my C++ compile flags, but also to the C compile flags. While GCC only gives a warning, clang on macOS throws an error ("`-std=c++11` is not a valid C compile option" or something like that).
I managed to fix this by replacing the `PUBLIC` keyword with `PRIVATE`. That way my project doesn't inherit this flag. I'm not sure though if this is a valid solution, since projects that do not specify the C++11 flag by themselves (just like I do in my said project) will end up with errors, since they'd end up having C++11 code in the fmt headers.

**Comment by vitaut** [comment]
You can link `<target>` with `fmt` without propagating flags as follows:

```cmake
add_dependencies(<target> fmt)
target_link_libraries(<target> $<TARGET_FILE:fmt>)
```
