### ISSUE TITLE
Print a simple vector from the tutorial - no longer works on master

### ISSUE THREAD

**Issue by a2nath** [fmtlib/fmt#3690]
This is no longer supported in the latest API. 

#include \<vector\>
#include <fmt/ranges.h>

int main() {
  std::vector<int> v = {1, 2, 3};
  fmt::print("{}\n", v);
}

VS 2019 error says : 
C2338	Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt	core.h	1580

**Comment by vitaut** [comment]
I was not able to repro the issue (https://godbolt.org/z/dP7d9vdqK) on the current master.
