### ISSUE TITLE
format uint8_t as char

### ISSUE THREAD

**Issue by ahao1995** [fmtlib/fmt#3692]
```
char test[10] = {'1', '2'};
fmt::format("{}", test); //12
uint8_t test1[10] = {'1', '2'};
fmt::format("{}", test1); //[49, 50, 0, 0, 0, 0, 0, 0, 0, 0]
```
how can I format uint8_t as char,thanks

**Comment by vitaut** [comment]
`uint8_t` is an integer type and formatted as such. You can use the extension API to write your own formatter (via a wrapper type): https://fmt.dev/latest/api.html#formatting-user-defined-types.
