### ISSUE TITLE
cannot convert 'main()::<lambda()>::FMT_COMPILE_STRING' to 'fmt::v10::format_string<const char (&)[6]>

### ISSUE THREAD

**Issue by MacroModel** [fmtlib/fmt#3704]
https://godbolt.org/z/TaYfxqExP
x86-64 gcc trunk(20231106) -Ofast -std=c++23
```cpp
#include <fmt/os.h>
#include <fmt/compile.h>

int main() {
  auto out = fmt::output_file("guide.txt");
  out.print(FMT_COMPILE("Don't {}"), "Panic");
}
```

<source>:6:13: error: cannot convert 'main()::<lambda()>::FMT_COMPILE_STRING' to 'fmt::v10::format_string<const char (&)[6]>' {aka 'fmt::v10::basic_format_string<char, const char (&)[6]>'}
    6 |   out.print(FMT_COMPILE("Don't {}"), "Panic");
      |             ^~~~~~~~~~~
      |             |
      |             main()::<lambda()>::FMT_COMPILE_STRING
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/os.h:423:59: note:   initializing argument 1 of 'void fmt::v10::ostream::print(fmt::v10::format_string<T ...>, T&& ...) [with T = {const char (&)[6]}; fmt::v10::format_string<T ...> = fmt::v10::basic_format_string<char, const char (&)[6]>]'
  423 |   template <typename... T> void print(format_string<T...> fmt, T&&... args) {
      |                                       ~~~~~~~~~~~~~~~~~~~~^~~

**Comment by MacroModel** [comment]
May I ask if this feature has not been implemented yet.

**Comment by vitaut** [comment]
`ostream::print` doesn't support format string compilation. This is the only API provided: https://fmt.dev/latest/api.html#system-apis.

**Comment by MacroModel** [comment]
thanks
