### ISSUE TITLE
documentation says: Small code size both in terms of source code (the core library consists of a single header file and a single source file) and compiled code. 

### ISSUE THREAD

**Issue by xaxxon** [fmtlib/fmt#371]
but I seem to have to include a lot of other header files.  like ostream.h  or maybe printf.h.

**Comment by nabijaczleweli** [comment]
what

**Comment by xaxxon** [comment]
you don't get all the functionality by including fmt/format.h, right?

**Comment by nabijaczleweli** [comment]
Just like you don't get the the whole fucking standard library by `#include`ing `<standard>`

**Comment by xaxxon** [comment]
I was pointing out the inconsistency between the documentation and the implementation.

No need to be hostile.

**Comment by vitaut** [comment]
The core library does consist of a single header file (``format.h``) and a single source file (``format.cc``). The rest is completely optional.

**Comment by vitaut** [comment]
And keep it classy, @nabijaczleweli =). This is a good feedback.

**Comment by xaxxon** [comment]
Coming from a previous version where including ostream.h or printf.h wasn't
a requirement (I had been using package-manager-installed versions), not
seeing a change in the documentation was confusing for me and cost me quite
a bit of time.

The new error messages would have taken care of my issue, though.

**Comment by vitaut** [comment]
Sorry for the breaking changes. They were done to reduce compile time for the case when iostream support is not needed. This is documented in release notes https://github.com/fmtlib/fmt/releases/tag/3.0.0, but I agree that the README could do a better job.

**Comment by xaxxon** [comment]
I really like the changes.   It just wasn't clear what was going on.   You
guys seem to be very much on the right track.

Thanks for the great library.


One thing I'd really like that would let me stop using boost format all
together would be the ability to programmatically put together an
expansion.  Right now in certain use cases I need to know how many
substitutions a format will need and then put together the expansion from
another data source.   Boost format lets me do that easily.    In boost
format you can query the format string add some parameters and even get the
number of remaining needed parameters.

**Comment by vitaut** [comment]
It is possible to construct an argument list dynamically as described in #330, but it's not straightforward and relies on some internal APIs at the moment.

**Comment by xaxxon** [comment]
That doesn't really appear to be similar, as it requires the number of
arguments to be known at compile time.

Boost lets you query the format string to find out how many arguments it's
expecting (allowing for dynamic format strings) and then just write a for
loop to populate the data based on that count.  This is required
functionality for me as I'm substituting user-defined arguments into a
defined format string and boost allows it to be done safely.

--Zac

**Comment by vitaut** [comment]
Right, you can't query the number of arguments from the format string parser, because parsing itself depends on the types of arguments. You can get the number of arguments by doing a simplified parsing (basically counting the number of non-repeated `{`). And you can give maximum number of arguments to `ArgArray`. Unused arguments will be ignored.
