### ISSUE TITLE
Fresh update of CMakeLists.txt incorrect?

### ISSUE THREAD

**Issue by anvvv** [fmtlib/fmt#3714]
I am having issues compiling using CMake (3.16). 

```
CMake Error at CMakeLists.txt:397 (install):
install TARGETS given unknown argument "FILE_SET".
```

This is from a freshly cloned repository, master branch.

My conjecture is that `FILE_SET` only gets defined for versions 3.28 and above, as per line 109.

This change is quite fresh in master (from one hour ago) , in https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt 

It seems to have been introduced with https://github.com/fmtlib/fmt/commit/cbb18c237a41b703d1b92a1c76aa8d2148165e52

**Comment by anvvv** [comment]
The issue seems to be that `FILE_SET` only gets defined for versions 3.23 and above, as per line 109.

**Comment by artorhem** [comment]
I have exactly the same issue.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/045b05d79e8c827ea815d765e62d92b879184b41.
