### ISSUE TITLE
fmt chrono compile failure on MinGW gcc when `-Werror` flag is present

### ISSUE THREAD

**Issue by AltairFromAquila** [fmtlib/fmt#3717]
I found an issue when compiling the following line with the `-Werror` flag present:
```cpp
fmt::format("{:%FT%T}Z", std::chrono::time_point_cast<std::chrono::seconds>(timePoint));
```
I've got the following error:
```
error: conversion from 'time_t' {aka 'long long int'} to 'long int' may change value [-Werror=conversion]
[build]  1287 |     long offset = gt - lt;
[build]       |                   ~~~^~~~
```
Currently, I'm using the MinGW gcc 13.2.0 compiler, and I believe it only happens with that compiler.

I can apply a fix to this issue, so feel free to assign me!

**Comment by vitaut** [comment]
In general fixing all possible warnings is a non-goal but a PR is welcome provided that it is not too intrusive.
