### ISSUE TITLE
Do not perfect forward args unnecessarily

### ISSUE THREAD

**Issue by tomilov** [fmtlib/fmt#3718]
It is common (anti)pattern in the current version of sources to accept arguments via `T&&... args`, then to forward them `std::forward<Args>(args)...` to deeper levels (can be found in `fmt/core.h`, `fmt/compile.h`, `fmt/ostream.h`, `fmt/ranges.h`, `fmt/xchar.h`). At the very end they always used as lvalue references: `fmt::make_format_args(args...)`.

It is not required at all and can be fixed: either `std::forward<Args>(args)...` can be changed to `args...` or both can be changed: `T&&... args` -> `const T&... args` and `std::forward<Args>(args)...` -> `args...`.

This can save some compile time and improve readability.

**Comment by vitaut** [comment]
This is not an antipattern but an intentional part of the design that, among other things, allows detecting some lifetime issues and supporting `std::generator`-like types.

**Comment by tomilov** [comment]
Any `std::generator`-like objects and other non-idempotent functors (and other "lazy" approaches) will suffer from [unspecified order of evaluation of function arguments](https://en.cppreference.com/w/cpp/language/eval_order) if passed twice. Therefore it is UB to use them or rely on them. Hence one can conclude, that this is not an argument.

Perfect forwarding until inevitable final using as l-value is not any better then passing as l-value reference from the very beginning till the very end. There is no additional value provided by perfect forwarding in the case.

What do you mean by "allowing to detect lifetime issues"? How perfect forwarding can help with that?

**Comment by tomilov** [comment]
Definitely self-mutability of custom formattable args is antipattern: https://godbolt.org/z/h185zMz5a. Users should not be encouraged to do this.
