### ISSUE TITLE
Linking errors on Windows

### ISSUE THREAD

**Issue by esrever** [fmtlib/fmt#372]
I get the below linker errors in Release build only.

fmt.lib(format.obj) : error LNK2005: "public: virtual __cdecl fmt::FormatError::~FormatError(void)" (??1FormatError@fmt@@UEAA@XZ) already defined in utils.obj
1>fmt.lib(format.obj) : error LNK2005: "void __cdecl fmt::internal::report_unknown_type(char,char const *)" (?report_unknown_type@internal@fmt@@YAXDPEBD@Z) already defined in utils.obj

where utils is one of my files. I'm not using the header-only version. Any ideas?

I'm using Visual Studio 2015 x64 as the compiler

**Comment by vitaut** [comment]
What version do you use?

**Comment by esrever** [comment]
Got the latest version a few weeks ago

**Comment by vitaut** [comment]
`~FormatError()` is defined in https://github.com/fmtlib/fmt/blob/master/fmt/format.cc#L85, so it shouldn't appear in `utils.obj` unless you include `format.cc` there. Please check that you don't set `FMT_HEADER_ONLY` (it can also be set by a third-party library such as spdlog).

**Comment by esrever** [comment]
Aha, spdlog was the culprit. many many thanks!!

**Comment by RealMG** [comment]
@esrever Could you please how to deal with this ? I ' m using spdlog and also got this link error. Thanks!

**Comment by vitaut** [comment]
@RealMG The solution is not to include `format.cc` in the build since spdlog uses fmt as a header-only library.

**Comment by dungdoggy2** [comment]
many many thanks too!!
