### ISSUE TITLE
LICENSE question

### ISSUE THREAD

**Issue by makslevental** [fmtlib/fmt#3721]
Sorry if this is a n00b/trivial question but the license here is MIT with exception right? I did a diff (lol) between the license and https://github.com/nlohmann/json/blob/develop/LICENSE.MIT (just as an example) and got only whitespace differences. If this is the case, would it be possible for you to rename the license file to LICENSE.MIT just so my bosses don't ask silly questions :stuck_out_tongue:.

Edit: err sorry just saw this in the REAMDE

> Ease of use: small self-contained code base, no external dependencies, permissive MIT [license](https://github.com/fmtlib/fmt/blob/master/LICENSE.rst)

So indeed it's MIT.

**Comment by vitaut** [comment]
Yes, it's MIT with an (optional) exception.
