### ISSUE TITLE
`fmt::basic_format_runtime<charT>` with charT != char not accepted in `fmt::format_to`

### ISSUE THREAD

**Issue by ingo-loehken** [fmtlib/fmt#3728]
While adding utf8 format support it turned out, that fmt::runtime_format_string is not supported with fmt::format_to

```cpp
using U8FormatContext = fmt::basic_format_context<std::back_insert_iterator<fmt::detail::buffer<char8_t>>, char8_t>;

auto u8foo(U8FormatContext& ctx, fmt::runtime_format_string<char8_t> const& formatString)
{
    return fmt::format_to(ctx.out(), formatString, 1); // compile error, cannot deal with fmt::runtime_format_string<char8_t>
}
```
[godbolt: all char types](https://www.godbolt.org/z/j6TdGb1vh)

Expectation
`fmt::format_to` works with all char-types.

**Comment by vitaut** [comment]
`basic_format_runtime` is not supposed to be used directly. See https://fmt.dev/latest/api.html for the public API.

**Comment by ingo-loehken** [comment]
Please see the modified code, that shows that the same problem is present with the `fmt::runtime` call for char-types other than char ...

[godbolt](https://www.godbolt.org/z/W78sMbccx)

Furthermore, it can be expected that ppl use the `runtime_format_string` in vcalls to reduce redundant code along inheritance hierarchies, because otherwise any leaf call may required wrapping via `fmt::runtime`, where `runtime_format_string` is quite more expressive.

*Maybe Off Topic*
Ofc you may argue, that `fmt::runtime` was only specified for char, but i`d really like that fmt does try to add support for all char types. This is also the reason, that we use fmt rather than std::format, which is quite restricted in what modern c++ can deliver, where char8_t solves all problems under windows and i was quite happy that SG-16 managed to bring it into the standard ... except that not all standard library entities (like locales, streams and other) are already present.

I'd also followed the discussion about how std::format should act (auto-transcoding ?, auto-conversion ?) and think that the way fmt brings it to the developer is a good way to deliver value without producing locked-in-effects.
