### ISSUE TITLE
Can't compile with C++/CLI because of inline namespace

### ISSUE THREAD

**Issue by JulZimmermann** [fmtlib/fmt#3731]
#1897 fixed a problem because of which `fmt` didn't compile with MSVC and `/clr` but 1aeed2d removed the workaround.

`8.0.1` seems to be the last version working with C++/CLI

When using any newer version I get
```
fmt\core.h(252,1): error C2049: 'fmt::v10': non-inline namespace cannot be reopened as inline
```

Could a workaround be added again?

Thanks!

**Comment by vitaut** [comment]
{fmt} requires a C++ compiler reasonably compliant with the standard. There are no plans to bring this hack back but you might be able to workaround the issue in C++/CLI by overriding `FMT_BEGIN_NAMESPACE` / `FMT_END_NAMESPACE`. I also recommend reporting a bug to Microsoft.

**Comment by bj8sk** [comment]
What I found, when a C++/CLI project was referencing another CLI assembly, that also uses fmt, I got the error.
Compiling without the referenced assembly was fine.
"reopened" makes sense in that context, somehow the referenced project export the inline namespace, it's already there and you get clash.

**Comment by bj8sk** [comment]
If you in the referenced assembly encapsulate the fmt includes and calls within unmanaged sections, you can observe in ILSpy that those namespace are no longer exported, and the project builds and runs
![image](https://github.com/fmtlib/fmt/assets/76002125/5a90ea98-a9f0-4084-a177-4f915f9aba94)
