### ISSUE TITLE
Q: fmt::format std::variant

### ISSUE THREAD

**Issue by angelskieglazki** [fmtlib/fmt#3735]
Hello!
Default format function for std::variant formating to "variant('some_value')". I want to make it so that only the some_value remains.
I should inherit from the standard formatter and override the format-function, am I right?
regards, max

**Comment by Folling** [comment]
In case you want to have a default formatter for all `std::variant<Ts...>` where all `Ts...` being formattable, this could be a starting point:

```cpp
template<typename... Ts>
struct fmt::formatter<std::variant<Ts...>> {
    template<typename FormatParseContext>
    constexpr static auto parse(FormatParseContext& ctx) {
        return ctx.end();
    }

     constexpr static auto format(std::variant<Ts...> const& value, fmt::format_context& ctx) {
        return std::visit(
            [&ctx](auto const v) {
                return fmt::format_to(ctx.out(), "variant({})", v);
            },
            value
        );
     }
};
```

**Comment by Finkman** [comment]
But, does it mean to conserve the format_context somehow? I am missing something to call `formatter< data_type>::parse`.

**Comment by phprus** [comment]
@vitaut 
Idea for ``std::tuple`` and ``std::variant`` formatter:

```c++
std::tuple<std::optional<formatter<Ts>>...> formatters_;

parse(ctx) {
    foreach T in Ts {
      if format-string is allowed for T then set formatter into formatters_;
    }
}

format() {
    if (formatters_ for actual T is set) {
        formatters_[idx].format(..);
    } else {
       throw ERROR or use default formatter for actual T;
    }
}
```

**Comment by Finkman** [comment]
T is unknown inside `parse`

**Comment by vitaut** [comment]
That's an interesting idea but it would be quite inefficient because we would need to call parse for each individual formatter and store all these formatters despite needing only one. I think it's better to delay parsing to `format`.

**Comment by Finkman** [comment]
@vitaut: could you help me with your proposal? From where can I get the `ctx` inside `format()`?.

**Comment by vitaut** [comment]
> could you help me with your proposal? From where can I get the ctx inside format()?.

You could do something like this:

```c++
#include <fmt/format.h>
#include <algorithm>
#include <variant>

struct my_variant {
  std::variant<int, double> value;
};

template <>
struct fmt::formatter<my_variant> {
 private:
  string_view fmt_;

 public:
  constexpr auto parse(format_parse_context& ctx) {
    auto it = ctx.begin(), end = ctx.end();
    fmt_ = {it, static_cast<size_t>(end - it)};
    while (it != end && *it != '}') ++it;
    return it;
  }

  auto format(const my_variant& v, format_context& ctx) const {
    auto parse_ctx = format_parse_context(fmt_);
    if (const int* i = std::get_if<0>(&v.value)) {
      auto f = formatter<int>();
      f.parse(parse_ctx);
      return f.format(*i, ctx);
    }
    double d = std::get<1>(v.value);
    auto f = formatter<double>();
    f.parse(parse_ctx);
    return f.format(d, ctx);
  }
};

int main() {
  fmt::print("{:x}\n", my_variant{42});
}
```

https://www.godbolt.org/z/rqErnY6qs

It would need a bit more work if you need to support dynamic width/precision but this example illustrates the basic idea.

**Comment by Finkman** [comment]
Thanks for that. That helped me a lot in understanding it in general.
