### ISSUE TITLE
Compilation error with clang in CUDA mode

### ISSUE THREAD

**Issue by msimberg** [fmtlib/fmt#3740]
When compiling https://github.com/fmtlib/fmt/blob/6f95000b7ad8c2fa63af1cf80da4da1992f87917/include/fmt/std.h#L418-L419 with clang in CUDA mode, compilation fails because `std::free` is an overloaded function. This small reproducer shows the problem on compiler explorer: https://godbolt.org/z/1bdKf86f9 (unfortunately for an older version of clang and cuda and without fmt, but the issue is the same). Device overloads are considered separate overloads with clang in CUDA mode, which means that taking the address of `std::free` doesn't work.

Note, we're not trying to use `fmt` in device code and don't expect this to work in device code, this is purely host code that just happens to be included in a `.cu` file.

This code seems to have been added in https://github.com/fmtlib/fmt/pull/3076, and so the problem appears from version 10.0.0 onwards.

Would you accept a patch to
- e.g. choose the `#else` branch of that implementation when in CUDA mode with clang?
- replace `decltype(&std::free)` with `void(void*)`?
- some other workaround?

**Comment by vitaut** [comment]
I think replacing `decltype(&std::free)` with `void(void*)` is reasonable. A PR is welcome.
