### ISSUE TITLE
Add way to control how types are formatted

### ISSUE THREAD

**Issue by gnzlbg** [fmtlib/fmt#375]
Currently the library uses `operator<<` to format any user-defined type. 

I would like to be able to specify what function is called to format user-defined types. 

**Problems with `operator<<`:**

- it assumes there is only one way to print a type, but I want to format the same type differently for debugging purposes than for logging purposes. 
- adding `operator<<` to namespaces outside of one control gets messy fast (and is undefined behavior for `std`)

**A solution:** allow the user to pass a function (or function object with `operator()`) that is used to format user-defined types, like, e.g., this:

```c++
fmt::print(stderr, debug_format, "A: {}", A{});
```

Here `debug_format` is a function object (or function) with the following interface:

```c++
template <typename OStream, typename T>
OStream& debug_format(OStream&, T const&);
```

This gives me _a lot_ of flexibility, since I can then add these functions to either the associated namespace of a type, or to a new namespace under my control. It also allows me to add fall backs to `operator<<` or some member function if I wish.

**Comment by vitaut** [comment]
Thanks for the suggestions, but I am not sure it is possible to implement this in C++. In particular, how would you pass an overloaded function name through the call hierarchy?

**Comment by gnzlbg** [comment]
`fmtlib` just needs to:
 - allow users to pass a function object and use that for the formatting in one of the `format` overloads. 
 - rewrite the current overloads in term of the new one, and pass a function object that calls `operator<<` (to keep the current behavior by default).

To implement a function object that calls `operator<<` you can just follow the guidelines in [N4381 - Suggested Design for Customization Points](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4381.html).

Basically you: 

- create a new internal namespace
- add the implementations of operator<< that you want to be found there for types without operator<<
- add a function object that uses ADL to find operator<<
- construct that function object in a way that avoids ODR issues (anyonymous namespace for C++ <17 and using inline variables in C++ >=17). 

In a nutshell (and from the top of my head, compiled on a buggy biological computer with an imperfect C++ implementation):

```c++
namespace fmt {

namespace fmt_detail { 

// Add here the overloads of operator<< that you want to provide by default
// It would probably be better to not provide any, but I don't know if this library
// already provides some. It could, for example, provide one for std::vector:

template<typename OStream, typename T, typename A>
OStream& operator<<(OStream& os, std::vector<T, A> const& v) {
    for (auto&& i : v) os << i; // this is bad, but it could be better
    return os;
}

// Provide a function object for formatting using operator<<
// (read the functions inside here from bottom to top).
struct default_formatter_fn {

  // This impl is only selected if the other one fails (the type of 0 is int, 
  // so the conversion to long makes this a worse overload).
  // This impl tries to find an operator<< in the fmt_detail namespace or
  // via ADL (so this currently works like it works now)
  template<typename OStream, typename T>
  static constexpr OStream& impl(OStream& os, T&& t, long)
  DECLTYPE_AUTO_RETURN_NOEXCEPT(os << t); 

  // This impl allows users to override the default formatter by providing
  // an "default_formatter(OStream, T)" function for their types that
  // can be found via ADL
  template<typename OStream, typename T>
  static constexpr OStream& impl(OStream& os, T&& t, int)
  DECLTYPE_AUTO_RETURN_NOEXCEPT(default_formatter(os, t)); 

  template<typename OStream, typename T>
  constexpr OStream& operator()(OStream& os, T&& t) const
  DECLTYPE_AUTO_RETURN_NOEXCEPT(impl(os, t, 0)); 
  //^ this macro does the "noexcept(noexcept(...)) -> decltype(...) { return ...; }" dance
};

} // namespace fmt_detail

// Now for convenience we create a function object that can be used
// Since this is a header file, we need to dance a bit against ODR, so that
// if somebody tries to take an address of this object, this address is the same
// in all TUs (see the paper for the static const solution that works in C++11 and above,
// in C++17 and above we could just use inline variables).
namespace  {
    static constexpr auto const& default_formatter = static_const<default_formatter>::value;
}                          

} // namespace fmt
```

So this default formatter already would allow users to override operator<< by defining a non-member non-friend `default_formatter` function that can be found via ADL for their own types (or even types outside their control). But if they need more control they can write their own function with whatever semantics they want. They can just rely on free functions that get found by ADL but have a different name, or they can even make it more complicated than this one by adding multiple layers of fall backs (try this free function, else try this member function, else ... , else give up all hope and fall back to operator<<).

My point is not really how complicated should the "default formatter" be for this library, but rather that we should allow users to hook up complicated ones if they want to.

**Comment by abolz** [comment]
This is possible today by wrapping all arguments in a function object which forwards its arguments to another function (object). But I agree that a library solution would be cleaner.

    #include <fmt/format.h>
    #include <fmt/ostream.h>

    namespace fmt_x // namespace fmt ??
    {
        template <typename F, typename T>
        struct FormatFn
        {
            F const& format;
            T const& t;
        };

        template <typename F, typename T>
        FormatFn<F, T> format_fn(F const& format, T const& t)
        {
            return { format, t };
        }

        template <typename OStream, typename F, typename T>
        OStream& operator <<(OStream& stream, FormatFn<F, T> const& fn)
        {
            fn.format(stream, fn.t);
            return stream;
        }

        template <typename F, typename ...Args>
        void print_fn(F&& formatter, fmt::CStringRef format, Args const&... args)
        {
            fmt::print(format, format_fn(formatter, args)...);
        }
    }

    int main()
    {
        auto debug_format = [](auto& stream, auto const& x) {
            stream << "<<" << x << ">>";
        };

        fmt_x::print_fn(debug_format, "A {}\n", 3.1415);
    }

**Comment by vitaut** [comment]
@gnzlbg OK, passing a function object instead of a function may work. Moreover, it should already be possible to do by providing a [custom argument formatter](http://fmtlib.net/dev/api.html#argument-formatters) unless I'm missing something. The existing API is more powerful because one can customize formatting of built-in types too, but if you like you can implement your API on top of it.

**Comment by gnzlbg** [comment]
>  Moreover, it should already be possible to do by providing a custom argument formatter unless I'm missing something. 

How do you do this? 

I have some:

```c++
template <typename OStream, typename T>
OStream& custom_formatter(OStream& os, T&& t);
```

function. How do I hook that into the custom argument formatter? 

From the docs I guess I need to write something like:

```c++
class CustomArgFormatter :
  public fmt::BasicArgFormatter<CustomArgFormatter, char> {
  public:
  CustomArgFormatter(fmt::BasicFormatter<char, CustomArgFormatter> &f,
                     fmt::FormatSpec &s, const char *fmt)
    : fmt::BasicArgFormatter<CustomArgFormatter, char>(f, s, fmt) {}

  template <typename T>
  void visit_custom(T value) {
      custom_format(???, value); 
  }
};
```

but it is not clear to me at all how to do that. (Maybe the example could be improved).

**Comment by abolz** [comment]
@gnzlbg `ref_or_val<T>` is actually just the `T` as deduced in the `wrap` function. E.g.

    auto w = wrap(fn_returning_bar());
    fmt::print(stderr, "bar {}", w);

should work.

**Comment by gnzlbg** [comment]
@abolz `wrap` will deduce an rvalue as `T&&`, but you want to store it as `T`.

**Comment by abolz** [comment]
Yes, I meant the plain `T`, without the two `&&`. `wrap(fn_returning_bar())` will deduce `T` as `bar` (not as `bar&&`). So `std::forward` will move the `bar` object into the `custom_formatter_object`.

**Comment by gnzlbg** [comment]
FWIW I ended up implementing and using this solution, so i basically write code that looks like  `fmt::print(stdout, "....", a, b, wrap(c), d);`. I can ignore `wrap` _sometimes_ if the type has an `operator<<` but my wrapper type defaults to that anyways, so I would still like it to be able to customize output by passing a "formatter" object, `fmt::print(stdout, formatter, "....", a,b,c,d);`. 

I think that would be more flexible.

**Comment by vitaut** [comment]
> How do you do this?

The implementation will be very similar to https://github.com/fmtlib/fmt/blob/a00006119fe80c6e2e66e280b44f3921e4a965b9/fmt/ostream.h#L94 with `operator<<` replaced with your custom format function.

**Comment by gnzlbg** [comment]
@vitaut so should I add an overload of `format_arg` to the `fmt` namespace?

**Comment by gnzlbg** [comment]
So this is what I have so far, I don't know what I am missing, but for some reason it seems that the `format_arg` function is not being picked up:

```c++
namespace my_ns {

template <typename OStream, typename T>
OStream& custom_write(OStream& o, T const& t) {
  if (std::is_same<T, int>{}) {
    o << 10;
  } else {
    o << t;
  }
  return o;
}

template <typename Char>
class CustomArgFormatter
 : public fmt::BasicArgFormatter<CustomArgFormatter<Char>, Char> {
 public:
  CustomArgFormatter(fmt::BasicFormatter<Char, CustomArgFormatter<Char>>& f,
                     fmt::FormatSpec& s, const Char* fmt)
   : fmt::BasicArgFormatter<CustomArgFormatter<Char>, Char>(f, s, fmt) {}
};

template <typename Char, typename T>
void format_arg(CustomArgFormatter<Char>& f, const Char*& format_str,
                const T& value) {
  fmt::internal::MemoryBuffer<Char, fmt::internal::INLINE_BUFFER_SIZE> buffer;

  fmt::internal::FormatBuf<Char> format_buf(buffer);
  std::basic_ostream<Char> output(&format_buf);

  custom_write(output, value);

  fmt::BasicStringRef<Char> str(&buffer[0], format_buf.size());
  typedef fmt::internal::MakeArg<CustomArgFormatter<Char>> MakeArg;
  format_str = f.format(format_str, MakeArg(str));
}

std::string custom_format(const char* format_str, fmt::ArgList args) {
  fmt::MemoryWriter writer;
  // Pass custom argument formatter as a template arg to BasicFormatter.
  fmt::BasicFormatter<char, CustomArgFormatter<char>> formatter(args, writer);
  formatter.format(format_str);
  return writer.str();
}
FMT_VARIADIC(std::string, custom_format, const char*)

void print_custom(const char* format, fmt::ArgList args) {
  std::string s = custom_format(format, args);
  fmt::print("{}", s);
}
FMT_VARIADIC(void, print_custom, const char*)

}  // namespace my_ns

int main() {
  my_ns::print_custom("abc {}\n", 5); // should print 10
  my_ns::print_custom("abc {}\n", 5.0); // should print 5.0

  return 0;
}
```

**Comment by gnzlbg** [comment]
After going through the whole implementation details of the library, I really do not think this is possible without overriding `format_custom_arg`... which cannot be done because it is an static member function :/

**Comment by vitaut** [comment]
> so should I add an overload of format_arg to the fmt namespace?

No, I meant that you can use similar implementation in `CustomArgFormatter::visit_custom`. Just adding an overload will have no effect because it won't be called from anywhere. Sorry for confusion.

> I think it that to get this done it would really help me if you could explain how the custom formatter, the custom format_arg, etc. all fit together.

A formatter performs parsing of a format string and calls an argument formatter for individual arguments. `format_arg` is used by the standard formatter as an extension mechanism - it can be overloaded for user-defined types. AFAIU `format_arg` won't fit your needs because you want two types of formatting, using standard `operator<<` and your own. That's why you need a custom argument formatter.

Your example uses an integer argument which is handled internally and not passed to `format_arg` at all. To customize its formatting you should add an appropriate visit method to `CustomArgFormatter`, e.g.

```c++
  template <typename T>
  void visit_any_int(T value) {
    // perform custom formatting here
  }
```

Hope it makes more sense now.

**Comment by gnzlbg** [comment]
The thing is, I want to be able to customize the formatting with a generic formatting function: 

    template<typename OStream, typename T>
    OStream& foo(OStream&,T const&);

Do I then need to hijack all visit methods calling that function first (and if it fails because it cannot handle the type, fall back to the default)? I guess so, and this is a lot of boilerplate, but I guess it might be doable. 

Even if that is the case, I still haven't figured out how to obtain the type `T` when overriding `visit_custom` so that I can call my `foo(OStream&, Tconst&)` formatter there. How do you do that? 

The only place I've found in the whole library that does this is, as mentioned above, `format_custom_arg`.

**Comment by vitaut** [comment]
> Do I then need to hijack all visit methods calling that function first (and if it fails because it cannot handle the type, fall back to the default)?

Yes. You might be able to do it in the templated visit method to avoid boilerplate.

> Even if that is the case, I still haven't figured out how to obtain the type T when overriding visit_custom so that I can call my foo(OStream&, Tconst&) formatter there. How do you do that?

For user-defined arguments you still need to overload `format_arg`.

> maybe you could show a minimal working example of how to override formatting when passing a formatter like foo ?

OK, I've done a few changes to your example to make it work.

```c++
#include "fmt/format.h"
#include "fmt/ostream.h"
#include <iostream>

namespace my_ns {

// If T is int, always prints 10, otherwise just forwards to operator<<
template <typename OStream, typename T>
OStream& custom_write(OStream& o, T const& t) {
  if (std::is_same<T, int>{}) {
    o << 10;
  } else {
    o << "custom " << t;
  }
  return o;
}

// The Custom formater class
template <typename CharType>
class CustomArgFormatter
 : public fmt::BasicArgFormatter<CustomArgFormatter<CharType>, CharType> {
 public:
  typedef CharType Char;
  CustomArgFormatter(fmt::BasicFormatter<Char, CustomArgFormatter<Char>>& f,
                     fmt::FormatSpec& s, const Char* fmt)
   : fmt::BasicArgFormatter<CustomArgFormatter<Char>, Char>(f, s, fmt) {}

  template <typename T>
  void visit_any_int(T value) {
    custom_write(std::cout, value); // use the actual stream instead of cout
  }
};

typedef fmt::BasicFormatter<char, CustomArgFormatter<char>> CustomFormatter;

template <typename T>
void format_arg(CustomFormatter& f, const char*& format_str, const T& value) {
  fmt::internal::MemoryBuffer<char, fmt::internal::INLINE_BUFFER_SIZE> buffer;

  fmt::internal::FormatBuf<char> format_buf(buffer);
  std::basic_ostream<char> output(&format_buf);

  // Here I call my function instead of operator<<
  custom_write(output, value);

  fmt::BasicStringRef<char> str(&buffer[0], format_buf.size());
  typedef fmt::internal::MakeArg<CustomArgFormatter<char>> MakeArg;
  format_str = f.format(format_str, MakeArg(str));
}

std::string custom_format(const char* format_str, fmt::ArgList args) {
  fmt::MemoryWriter writer;
  // Pass custom argument formatter as a template arg to BasicFormatter.
  CustomFormatter formatter(args, writer);
  formatter.format(format_str);
  return writer.str();
}

template <typename... Args>
std::string custom_format(const char *format_str, const Args & ... args) {
  typedef fmt::internal::ArgArray<sizeof...(Args)> ArgArray;
  typename ArgArray::Type array{
    ArgArray::template make<CustomFormatter>(args)...};
  return custom_format(format_str,
    fmt::ArgList(fmt::internal::make_type(args...), array));
}

// My custom print function that uses custom_format
void print_custom(const char* format, fmt::ArgList args) {
  std::string s = custom_format(format, args);
  fmt::print("{}", s);
}

template <typename... Args>
void print_custom(const char *format_str, const Args & ... args) {
  typedef fmt::internal::ArgArray<sizeof...(Args)> ArgArray;
  typename ArgArray::Type array{
    ArgArray::template make<CustomFormatter>(args)...};
  print_custom(format_str,
    fmt::ArgList(fmt::internal::make_type(args...), array));
}
}  // namespace my_ns

struct S {};

std::ostream& operator<<(std::ostream& os, S) {
  return os << "S";
}

int main() {
  my_ns::print_custom("abc {}\n", S());
}
```

Note that the extension API is still work in progress and relies on some internal details. In the next version it will be much easier to write variadic functions like `print_custom` and handle formatting arguments.

**Comment by gnzlbg** [comment]
The test in Example A (see below) prints: 

```shell
abc custom S
10abc 
abc 42
```

but it should print

```
abc custom S
abc 10
abc 10
```

I guess I would need to overload in this case also `visit_any_double`, and for this to always work for any `T` I would really need to overload all the variant methods. It seems that you think that I just want `custom_write` to switch on `int`s, but the implementation of `custom_write` should be _opaque_, it takes a `T` (any T), and no matter what it does internally the library should always work. In this case it was trivial to break the solution by just switching on double. 

Another thing that I want to do (and that works, see example B below) is to not have to provide an `operator<<` for `S`, but rather, provide an associated function (in this case `custom_write`) that is found by adl. The example B prints:

```
abc non-custom B
abc 10
abc 10
```

which means that the correct function is found via ADL.

Example A: 

```c++
#include <hm3/utility/fmt.hpp>
#include <iostream>

namespace my_ns {

// If T is int, always prints 10, otherwise just forwards to operator<<
template <typename OStream, typename T>
OStream& custom_write(OStream& o, T const& t) {
  if (std::is_same<T, int>{}) {
    o << 10;
  } else if (std::is_same<T, double>{}) {
    o << 5.0;
  } else {
    o << "custom " << t;
  }
  return o;
}

// The Custom formater class
template <typename CharType>
class CustomArgFormatter
 : public fmt::BasicArgFormatter<CustomArgFormatter<CharType>, CharType> {
 public:
  typedef CharType Char;
  CustomArgFormatter(fmt::BasicFormatter<Char, CustomArgFormatter<Char>>& f,
                     fmt::FormatSpec& s, const Char* fmt)
   : fmt::BasicArgFormatter<CustomArgFormatter<Char>, Char>(f, s, fmt) {}

  template <typename T>
  void visit_any_int(T value) {
    custom_write(std::cout, value); // use the actual stream instead of cout
  }
};

typedef fmt::BasicFormatter<char, CustomArgFormatter<char>> CustomFormatter;

template <typename T>
void format_arg(CustomFormatter& f, const char*& format_str, const T& value) {
  fmt::internal::MemoryBuffer<char, fmt::internal::INLINE_BUFFER_SIZE> buffer;

  fmt::internal::FormatBuf<char> format_buf(buffer);
  std::basic_ostream<char> output(&format_buf);

  // Here I call my function instead of operator<<
  custom_write(output, value);

  fmt::BasicStringRef<char> str(&buffer[0], format_buf.size());
  typedef fmt::internal::MakeArg<CustomArgFormatter<char>> MakeArg;
  format_str = f.format(format_str, MakeArg(str));
}

std::string custom_format(const char* format_str, fmt::ArgList args) {
  fmt::MemoryWriter writer;
  // Pass custom argument formatter as a template arg to BasicFormatter.
  CustomFormatter formatter(args, writer);
  formatter.format(format_str);
  return writer.str();
}

template <typename... Args>
std::string custom_format(const char *format_str, const Args & ... args) {
  typedef fmt::internal::ArgArray<sizeof...(Args)> ArgArray;
  typename ArgArray::Type array{
    ArgArray::template make<CustomFormatter>(args)...};
  return custom_format(format_str,
    fmt::ArgList(fmt::internal::make_type(args...), array));
}

// My custom print function that uses custom_format
void print_custom(const char* format, fmt::ArgList args) {
  std::string s = custom_format(format, args);
  fmt::print("{}", s);
}

template <typename... Args>
void print_custom(const char *format_str, const Args & ... args) {
  typedef fmt::internal::ArgArray<sizeof...(Args)> ArgArray;
  typename ArgArray::Type array{
    ArgArray::template make<CustomFormatter>(args)...};
  print_custom(format_str,
    fmt::ArgList(fmt::internal::make_type(args...), array));
}
}  // namespace my_ns

struct S {};

std::ostream& operator<<(std::ostream& os, S) {
  return os << "S";
}

int main() {
  my_ns::print_custom("abc {}\n", S());
  my_ns::print_custom("abc {}\n", int(42));
  my_ns::print_custom("abc {}\n", double(42.0));
}
```

Example B:

```c++
#include <hm3/utility/fmt.hpp>
#include <iostream>

namespace my_ns {

// If T is int, always prints 10, otherwise just forwards to operator<<
template <typename OStream, typename T>
OStream& custom_write(OStream& o, T const& t) {
  if (std::is_same<T, int>{}) {
    o << 10;
  } else if (std::is_same<T, double>{}) {
    o << 5.0;
  } else {
    o << "custom " << t;
  }
  return o;
}

// The Custom formater class
template <typename CharType>
class CustomArgFormatter
 : public fmt::BasicArgFormatter<CustomArgFormatter<CharType>, CharType> {
 public:
  typedef CharType Char;
  CustomArgFormatter(fmt::BasicFormatter<Char, CustomArgFormatter<Char>>& f,
                     fmt::FormatSpec& s, const Char* fmt)
   : fmt::BasicArgFormatter<CustomArgFormatter<Char>, Char>(f, s, fmt) {}

  template <typename T>
  void visit_any_int(T value) {
    custom_write(std::cout, value);  // use the actual stream instead of cout
  }
};

typedef fmt::BasicFormatter<char, CustomArgFormatter<char>> CustomFormatter;

template <typename T>
void format_arg(CustomFormatter& f, const char*& format_str, const T& value) {
  fmt::internal::MemoryBuffer<char, fmt::internal::INLINE_BUFFER_SIZE> buffer;

  fmt::internal::FormatBuf<char> format_buf(buffer);
  std::basic_ostream<char> output(&format_buf);

  // Here I call my function instead of operator<<
  custom_write(output, value);

  fmt::BasicStringRef<char> str(&buffer[0], format_buf.size());
  typedef fmt::internal::MakeArg<CustomArgFormatter<char>> MakeArg;
  format_str = f.format(format_str, MakeArg(str));
}

std::string custom_format(const char* format_str, fmt::ArgList args) {
  fmt::MemoryWriter writer;
  // Pass custom argument formatter as a template arg to BasicFormatter.
  CustomFormatter formatter(args, writer);
  formatter.format(format_str);
  return writer.str();
}

template <typename... Args>
std::string custom_format(const char* format_str, const Args&... args) {
  typedef fmt::internal::ArgArray<sizeof...(Args)> ArgArray;
  typename ArgArray::Type array{
   ArgArray::template make<CustomFormatter>(args)...};
  return custom_format(format_str,
                       fmt::ArgList(fmt::internal::make_type(args...), array));
}

// My custom print function that uses custom_format
void print_custom(const char* format, fmt::ArgList args) {
  std::string s = custom_format(format, args);
  fmt::print("{}", s);
}

template <typename... Args>
void print_custom(const char* format_str, const Args&... args) {
  typedef fmt::internal::ArgArray<sizeof...(Args)> ArgArray;
  typename ArgArray::Type array{
   ArgArray::template make<CustomFormatter>(args)...};
  print_custom(format_str,
               fmt::ArgList(fmt::internal::make_type(args...), array));
}
}  // namespace my_ns

namespace B {
struct S {};

// this one should be preferred
template <typename OStream>
OStream& custom_write(OStream& o, S const& t) {
  o << "non-custom B";
  return o;
}

// this one should be hijacked by custom_write
template <typename OStream>
OStream& operator<<(OStream& o, S const& t) {
  o << "another-custom B";
  return o;
}
}

int main() {
  my_ns::print_custom("abc {}\n", B::S());
  my_ns::print_custom("abc {}\n", int(42));
  my_ns::print_custom("abc {}\n", double(42.0));
}
```

**Comment by gnzlbg** [comment]
So... all in all, there remains only the issue with the ordering, (e.g. ints do not get formatted to the correct position), the enormous amount of boiler plate required to hijack `operator<<` for UDTs as the default printing function to call, and possibly a way to write these custom functions so that they can make use of the `{args...}` easily, and forward to default behavior when desired. 

I really would like to just have to write:

```c++
template <typename OStream, typename T, typename Spec>
OStream& custom_write(OStream& o, T const& t, Spec s) {
  if (std::is_same<T, int>{} and s.value() == "boo") {
    o << 10;
  } else if (std::is_same<T, double>{} and s.value() == "meh") {
    o << 5.0;
  } else {
    return fmtlib_default_write(o, t, s);
  }
  return o;
}

print(stdout, custom_write, "hello {boo} and {} and {meh} and {}", 2, 2, 6.0, 6.0);
// prints "help 10 2 5 6"
```

So ideally `fmtlib_default_write` would just format to the defaults. This is a completely different customization API than the one the library currently offers. I think both are equally powerful, but I find something like this much easier to use.

**Comment by vitaut** [comment]
>  It seems that you think that I just want custom_write to switch on ints, but the implementation of custom_write should be opaque, it takes a T (any T), and no matter what it does internally the library should always work. In this case it was trivial to break the solution by just switching on double.

No, I just made minimal changes for your example to make it compile and illustrate how it can be done. Obviously you need to handle all types and pass the correct stream (via formatter) as I wrote in the comment:

```c++
// use the actual stream instead of cout
```

> I guess I would need to overload in this case also visit_any_double, and for this to always work for any T I would really need to overload all the variant methods.

Yes, this will be addressed in the next version where you'll be able to handle all types in a single function template (similar to `std::visit`).

I don't think the API you suggest will work because there is no spec for user-defined types and there is no ostream object to pass to `custom_write`. However, I think the new visit API will solve most of your concerns regarding boilerplate.

**Comment by gnzlbg** [comment]
> However, I think the new visit API will solve most of your concerns regarding boilerplate.

Nice to hear, once you get it to a working state please ping me so that i can try it out :)
