### ISSUE TITLE
Green Day Support

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#3758]
{fmt} doesn't support printing green day at the moment:

```c++
#include <fmt/chrono.h>
#include <fmt/color.h>

int main() {
  fmt::print(fg(fmt::color::green), "{}", std::chrono::day());
}
```

Error:

```
include/fmt/core.h:1594:63: error: implicit instantiation of undefined template 'fmt::detail::type_is_unformattable_for<const std::chrono::day, char>'
    type_is_unformattable_for<T, typename Context::char_type> _;
                                                              ^
...
include/fmt/core.h:1597:3: error: static assertion failed due to requirement 'formattable': Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
  static_assert(
  ^
2 errors generated.

**Comment by zivshek** [comment]
Looking at this, not only day(), but also month() or year().

**Comment by vitaut** [comment]
The C++ standard mentions these formatters (https://eel.is/c++draft/time):

```c++
  template<class charT> struct formatter<chrono::day, charT>;
  template<class charT> struct formatter<chrono::month, charT>;
  template<class charT> struct formatter<chrono::year, charT>;
```

**Comment by zivshek** [comment]
> The C++ standard mentions these formatters (https://eel.is/c++draft/time):
> 
> ```c++
>   template<class charT> struct formatter<chrono::day, charT>;
>   template<class charT> struct formatter<chrono::month, charT>;
>   template<class charT> struct formatter<chrono::year, charT>;
> ```

you're right, std should have those formatters, but __cpp_lib_format is false, did some research, is it std::format not supported yet in MSVC?

**Comment by vitaut** [comment]
> why you had to define the formatters for duration, weekday etc. in fmt in the first place? I think the issue is to make fmt make use the std::formatter's.

Good question. `std::chrono` is usually wider available than `std::format` and considering that day/month/year formatters should be easy to implement I think we should just do it ourselves.

**Comment by vitaut** [comment]
Aslo `year_month_day` mentioned in #3772.

**Comment by razaqq** [comment]
There are a couple more of interest.

![grafik](https://github.com/fmtlib/fmt/assets/5948878/83eb25df-35fc-4cb8-b1fa-e0bc43c3ba20)
