### ISSUE TITLE
Locale-specific integer formatting doesn't work on iOS

### ISSUE THREAD

**Issue by olliwang** [fmtlib/fmt#376]
Hi, I was trying to print pretty integer on iOS. However, it seems `std::setlocale()` is not allowed in iOS (http://stackoverflow.com/questions/32594377/setlocale-works-in-ios-simulator-but-fails-on-device). Is it possible to provide other way to achieve this in iOS? Thanks.

**Comment by vitaut** [comment]
The library doesn't use `setlocale`. Could you post the code and an error that you get on iOS?

**Comment by olliwang** [comment]
I tried the following code as described in #305 

    std::setlocale(LC_ALL, "en_US.utf8");
    fmt::print("cppformat: {:n}\n", 1234567);

However, the first line always returns `NULL` and the commas never printed.

**Comment by vitaut** [comment]
I see. Since iOS doesn't seem to support locales, I guess you can provide your own imlementation of `fmt::std::localeconv` as it is done in [`format-test`](https://github.com/fmtlib/fmt/blob/0d25f6fcbbf0a867b939a5501965ee4462b21ee6/test/format-test.cc#L55), something like:

```
namespace fmt {
namespace std {
lconv *localeconv() {
  static lconv lc = {...}; // initialize thousands_sep here
  return &lc;
}
}
}
```

**Comment by olliwang** [comment]
Thanks @vitaut. This approach seems a bit tricky. Writing a custom function to add separates would be easier for me. However, it would be great if fmt can support iOS out-of-box.
