### ISSUE TITLE
call to 'round' is ambiguous

### ISSUE THREAD

**Issue by razaqq** [fmtlib/fmt#3761]
```
include\fmt\chrono.h(1108,55): error : call to 'round' is ambiguous
   1108 |     if (num_fractional_digits < 6 && static_cast<rep>(round(val)) != val)
```

The problem arises [here](https://github.com/fmtlib/fmt/blob/b8f81dede502a4b6dbcd1787d6a35008e8d3e5be/include/fmt/chrono.h#L1151) from the fact that fmt uses a free function `round` here, which there are multiple definitions of for me (there is another one from a 3rd party library too.

![grafik](https://github.com/fmtlib/fmt/assets/5948878/46c6176f-74cf-494f-9fec-250109f8373d)

Would it be possible to be explicit with which function to use?

**Comment by Dani-Hub** [comment]
@razaqq  I think you should provide a complete minimal reproducer

**Comment by vitaut** [comment]
The problem is likely in a third-party library providing an overload that conflicts with standard library `round`. Please report there. If you think it's a bug in {fmt}, feel free to reopen with a self-contained repro, ideally on godbolt.

**Comment by razaqq** [comment]
> The problem is likely in a third-party library providing an overload that conflicts with standard library `round`. Please report there. If you think it's a bug in {fmt}, feel free to reopen with a self-contained repro, ideally on godbolt.

That is precisely the case, which is why i suggested you be specific with your use of round (`std::round`) to avoid this

**Comment by vitaut** [comment]
Unfortunately we cannot use `std::round` there. Due to compatibility reasons we have to use the C `round`.

**Comment by razaqq** [comment]
Why dont you check if `std::round` is available with cmake `CheckCXXSymbolExists` or `CheckCXXSourceCompiles`, set some `FMT_HAVE_STD_ROUND` and only if not available default to C `round`?

**Comment by vitaut** [comment]
We shouldn't implement workarounds for broken third-party libraries.
