### ISSUE TITLE
`format_as` converting struct to `tuple` no longer works

### ISSUE THREAD

**Issue by hewillk** [fmtlib/fmt#3763]
```cpp
#include <fmt/ranges.h>

struct Data {
  int a = 3;
  double b = 0.42;
};

auto format_as(const Data& data)
{ return std::tie(data.a, data.b); }

int main() {
  fmt::println("{}", Data{});
}
```
https://godbolt.org/z/d8a7EsKb4

The above code works on 10.1.1, but not on trunk.

**Comment by vitaut** [comment]
Bisected the regression to #3713.

**Comment by vitaut** [comment]
It's essentially the same issue as #3752 except that the repro is simpler.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/3eb3aef5753b91d689b496a629b9dc5c4a7cd348. Thanks for reporting.
