### ISSUE TITLE
Compile-time checks are not performed for `u8string`.

### ISSUE THREAD

**Issue by andrewerf** [fmtlib/fmt#3766]
**Problem:** neither Clang nor GCC performs compile-time checks (`constexpr auto formatter::parse(...)`) for u8-strings. Code with ordinal strings works as expected.

**Code**: the following code could be used to reproduce the problem ([godbolt](https://godbolt.org/z/8KqGfK5js)):
```cxx
#include <fmt/format.h>
#include <fmt/xchar.h>
#include <iostream>


int main()
{
    // compilation failed on GCC and Clang!
    //auto s = fmt::format( "{} {}", 15 );
    
    // runtime error on GCC and Clang
    auto ss = fmt::format( u8"{} {}", 15 );
}
```

This code fails in runtime, but if we uncommented the line with `s` assignment, it would produce a compilation error.

**Comment by vitaut** [comment]
u8 strings are pretty much unusable in their current form and there are no plans to add compile time checks for them at the moment.
