### ISSUE TITLE
Can't use `fmt::printf` for custom types

### ISSUE THREAD

**Issue by feliwir** [fmtlib/fmt#3767]
Hello,

we are currently migrating from fmt v7 to fmt v10, and are having trouble to support our custom sting type in `fmt::printf`. In v7 it worked without any changes. We know about issues #1499 and #3678 however due to our large codebase it's not viable to switch to `fmt::format`.

According to the discussion inside the docs one does only need to have an `ostream` implementation for the type like this:
```c++
class String
{
public:
std::string m_internal;
};
std::ostream& operator<< (std::ostream& o, const String& s) { return o << s.m_string; }
```
Here is a minimal example that reproduces our issue:
https://godbolt.org/z/s7ErMrr8v

I'd appreciate any help to get this working. Thanks!

**Comment by vitaut** [comment]
We don't maintain conan packages but you could probably create a package yourself or vendor specific version of the library.
