### ISSUE TITLE
`fmt::print` vs. `fmt::println` API inconsistency

### ISSUE THREAD

**Issue by GuillaumeDua** [fmtlib/fmt#3768]
How to reproduce ? https://godbolt.org/z/h1YbenGza

Using compile-time strings `FMT_COMPILE_STRING`, the API of `print` and `println` is not consistent.

**Question**: Will it remain like this for technical reason, or can we expect to see such a feature integrated at some point ?

Thx <3

**Comment by vitaut** [comment]
Format string compilation is just an optimization and only supports a minimal subset of the API. `println` doesn't fit into that because it is trivially expressed via `print`.
