### ISSUE TITLE
C++17 vs. C++20/23 regression for printing `*this`

### ISSUE THREAD

**Issue by GuillaumeDua** [fmtlib/fmt#3770]
Reproduction: https://godbolt.org/z/Kv4qnbrYE

While it might not makes much sens, some codebases have types with self-printing.  
Is there a work-around for printing `*this` in C++ >=20 ?

Forward declaration cannot be used here, as the type is used in type-traits.

**Comment by vitaut** [comment]
The formatter must be visible when calling `print` so one fix is to outline `point::print_me`: https://godbolt.org/z/vs99e48Pr.
