### ISSUE TITLE
Better static analysis to prevent inconsistent number of braces and arguments

### ISSUE THREAD

**Issue by amosbird** [fmtlib/fmt#3771]
At present, fmt does not produce any errors or warnings when the number of arguments exceeds the number of braces. You can see an example of this behavior at https://godbolt.org/z/6hP8cq49d. Ideally, fmt should fail the compilation in the same manner as when the number of arguments is less than the number of braces.

**Comment by vitaut** [comment]
This is intentional, please see #492.

**Comment by amosbird** [comment]
I'm aware that the library follows Python's str.format conventions. With the help of pylint, it will warn you about this:  E1305: Too many arguments for format string (too-many-format-args). I think it's useful to configure fmtlib so that it can generate some warnings.

**Comment by vitaut** [comment]
This could be done via a separate lint (e.g. clang-tidy). There are no plans to provide such lint in the library itself but if someone makes one we'll be happy to link to it.
