### ISSUE TITLE
Format precision not match when missing type

### ISSUE THREAD

**Issue by shfxia** [fmtlib/fmt#3773]
I want to print double with precision but missing type, so that it can automatically set type according to the value, for example it's 'f' for big double, it's 'g' for small double,
```
fmt::print("{:.10}\n", 45723.2342350689402234);
```
the result is 45723.23424
```
fmt::print("{:.10}\n", .000002342350689402234);
```
the result is 2.342350689e-06

In the above example, the result is 10 significand digits. But what I expect is 10 precision fraction.

My system is Windows 11, fmtlib version is 10.1.1

**Comment by vitaut** [comment]
There is no built-in way of doing this. You could probably write your own formatter (via a wrapper type) that selects the required presentation.
