### ISSUE TITLE
chrono-test failing on i386 and armhf on Ubuntu

### ISSUE THREAD

**Issue by trldp** [fmtlib/fmt#3774]
When building libfmt on Ubuntu, the test chrono-test.timestamps gives the following errors
```
3: [ RUN      ] chrono_test.timestamps_ratios
3: unknown file: Failure
3: C++ exception with description "cannot format duration" thrown in the test body.
3: [  FAILED  ] chrono_test.timestamps_ratios (0 ms)
```

The failure occurs on different versions of Ubuntu. Full build logs from for instance 22.04 (the latest LTS release) can be found here

- i386: https://launchpadlibrarian.net/705397090/buildlog_ubuntu-jammy-i386.fmtlib_9.1.0-1~git202312241939+5~ubuntu22.04.1_BUILDING.txt.gz
- armhf: https://launchpadlibrarian.net/705399663/buildlog_ubuntu-jammy-armhf.fmtlib_9.1.0-1~git202312241939+5~ubuntu22.04.1_BUILDING.txt.gz

**Comment by vitaut** [comment]
The log mentions version 9.1. Do you still get an error on the current version of the library?

**Comment by trldp** [comment]
The source should be a copy of the latest git version (master branch). The version number is set manually in the accompanying debian branch (see https://code.launchpad.net/~trldp/+git/libfmt-debian, I've updated it now), and should not have an influence on the build itself.

**Comment by vitaut** [comment]
Godbolt repro: https://www.godbolt.org/z/1Pfd7T51d

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/be57ec7ec0c24a0fcfef774bf1e586ef10686070. Thanks for reporting.
