### ISSUE TITLE
Documentation for `println` functions is missing

### ISSUE THREAD

**Issue by RAnders00** [fmtlib/fmt#3775]
These functions are included in the latest release:
https://github.com/fmtlib/fmt/blob/f5e54359df4c26b6230fc61d38aa294581393084/include/fmt/core.h#L2902

But they are not documented on https://fmt.dev/latest/api.html#core-api !

**Comment by vitaut** [comment]
Documented in https://github.com/fmtlib/fmt/commit/0147e08225db261f5689fc17a986ede7f1db56f0.
