### ISSUE TITLE
fmt.cc includes os.cc regardless of the FMT_OS option.

### ISSUE THREAD

**Issue by gabime** [fmtlib/fmt#3777]
I think it should avoid it if FMT_OS is set to OFF.

**Comment by vitaut** [comment]
Makes sense in general but is there any concrete problem you are trying to solve?

**Comment by gabime** [comment]
In spdlog ver 2.x fmt is [fetched and compiled](https://github.com/gabime/spdlog/blob/2a4aa8f2d10ea362f2be324aef8e896ed0d91b83/cmake/fmtlib.cmake#L14) as a dependency. Since spdlog doesn’t require the os features of fmt it sets FMT_OS to OFF.

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/398ddb8fec18eb4dfd1d0c8b1b8222afdb8b6307.

**Comment by gabime** [comment]
Thanks. However it still includes “os.cc” unconditionally [here](https://github.com/fmtlib/fmt/blob/398ddb8fec18eb4dfd1d0c8b1b8222afdb8b6307/src/fmt.cc#L110C2-L110C2).

**Comment by vitaut** [comment]
Take 2: https://github.com/fmtlib/fmt/commit/9659f22d36acd801fc89f6056ccd846d967ef473.

**Comment by vitaut** [comment]
Take 3: #3783. Thanks to @phprus.
