### ISSUE TITLE
Breaking ABI change in Windows builds of 10.2.0

### ISSUE THREAD

**Issue by saraedum** [fmtlib/fmt#3785]
On some Windows builds, the signature of `fmt::v10::detail::write_console` has changed:

```patch
- bool __cdecl fmt::v10::detail::write_console(struct _iobuf * __ptr64,class fmt::v10::basic_string_view<char>)
+ bool __cdecl fmt::v10::detail::write_console(int,class fmt::v10::basic_string_view<char>)
```

This causes dynamic linking errors. The problem seems to be caused by this change https://github.com/fmtlib/fmt/commit/2a2c6e676f4c2100b2b0f6b3390543ba94ca4b3d

See e.g., https://github.com/mamba-org/mamba/issues/3095 for where this breaks a library on Windows.

**Comment by saraedum** [comment]
This also happens on Linux upon closer inspection (somehow I missed this initually.)

```patch
-fmt::v10::detail::write_console(_IO_FILE*, fmt::v10::basic_string_view<char>)
+fmt::v10::detail::write_console(int, fmt::v10::basic_string_view<char>)
```

**Comment by saraedum** [comment]
The function `write_console` is, however, only used when `_WIN32` is defined. So the symbol changing does not matter on Linux and macOS.

**Comment by saraedum** [comment]
A proposed fix is in https://github.com/fmtlib/fmt/pull/3786.

**Comment by vitaut** [comment]
Thanks for reporting. I'll merge the fix into a separate branch (since master has a bunch of experimental changes) and make a patch release.
