### ISSUE TITLE
Should someone run the whole codebase through a static analyzer?

### ISSUE THREAD

**Issue by zencatalyst** [fmtlib/fmt#3787]
I'm asking to see whether or not this is done from time to time. Would the maintainers of the project accept such an effort by some contributors?

The number of suggested changes by the analyzers might be too many. So naturally the first steps could be just fixing trivial stuff. If done well, we can do more serious fixes and remove code smells as well.

**Comment by vitaut** [comment]
Folks have been occasionally checking {fmt}'s code with static analyzers but the recent reports haven't provided anything useful, just a bunch of false positives. As usual, if you discover any real issues with static analyzer or not, a PR will be welcome.
