### ISSUE TITLE
Feature request: engineering notation 

### ISSUE THREAD

**Issue by JVApen** [fmtlib/fmt#3790]
[Engineering notation](https://en.m.wikipedia.org/wiki/Engineering_notation) is a hybrid between scientific notation and regular notation (milli, micro, nano ...) 
Whenever a power of 10 is used, that should be dividable by 3. E3 => kilo, E6 => Mega E-3 => Milli ...
Though at the moment, no standard functionality (printf, std::format, fmt::format exists while this makes it easier to grasp the actual number)

**Comment by vitaut** [comment]
Thanks for the suggestion but the format string syntax for standard types is pretty much fixed at this point. You can add support for engineering notation using the extension API: https://fmt.dev/latest/api.html#formatting-user-defined-types.
