### ISSUE TITLE
Incorrect output and segfault with `std::optional<std::string>` and `FMT_COMPILE`

### ISSUE THREAD

**Issue by TomCrypto** [fmtlib/fmt#3795]
We've run into an issue that we've tracked down to formatting `std::optional<std::string>` with {fmt} in conjunction with the `FMT_COMPILE` macro. We have observed both incorrect formatted strings and also segmentation faults. I've created a minimal repro case on godbolt with clang trunk and {fmt} trunk:

https://godbolt.org/z/rE5xadqf1

The issue does not seem to occur if `FMT_COMPILE` is not used or if the literal passed to it is just `"{}"`, but as soon as the literal contains more than just that, issues crop up when formatting string optionals. I haven't checked if it happens with other std types. It doesn't appear to occur when formatting plain strings, or `std::optional<int>`, etc...

The documentation suggests this should be a valid use of `FMT_COMPILE` so I'm submitting this as a bug.

**Comment by phprus** [comment]
Simple test case:
https://godbolt.org/z/qe5zK9Phx

**Comment by phprus** [comment]
@vitaut 

This error has been present since the commit: https://github.com/fmtlib/fmt/commit/a34a97cc1d7d50ed6b05bd315ecef7aeb97f1364

New test:
```c++
TEST(compile_test, format_escape) {
  EXPECT_EQ(fmt::format(FMT_COMPILE("{:?}"), "string"), "\"string\"");
  EXPECT_EQ(fmt::format(FMT_COMPILE("0{:?}"), "string"), "0\"string\"");
  EXPECT_EQ(fmt::format(FMT_COMPILE("{:?}0"), "string"), "\"string\"0");
}
```
