### ISSUE TITLE
Missing formatter leads to compiler crash for clang 15 or below

### ISSUE THREAD

**Issue by BobIsOnFire** [fmtlib/fmt#3796]
Thank you for your outstanding work on exposing compiler bugs! Even if it's not intentional, it is still outstanding :)

Here is minimal godbolt repro: https://godbolt.org/z/exoe9nKeh. Notes:
* Reproduces ever since fmt 10.1.0;
* If I write a formatter for `MyStruct`, crash is gone;
* If I select clang 16.0.0 or above, crash is gone;
* If I set `-std=c++14` or below, crash is gone;
* In my local testing, replacing two last lines in [`check_format_string`](https://github.com/fmtlib/fmt/blob/10.2.1/include/fmt/core.h#L2707) with plain `parse_format_string<true>(s, checker(s))` seems to avoid the crash.

We would like to use new fmt version, but we're not ready yet to upgrade our toolchain to clang 16 or above. Even though the crash reproduces only if formatter is missing, the crash itself hides the real problem from the user -- they might think that compiler is just bad, and ignore the error above about missing formatter.

Do you think this is something that can be fixed or worked around in fmt codebase? If not, please advise if/how we can use new fmt versions with older clang.

**Comment by vitaut** [comment]
I'll take a look but could you also submit a bug report to clang?

**Comment by vitaut** [comment]
Considering that the issue only affects invalid code and fairly narrow configuration I don't think we should be implementing any workarounds in {fmt}. You can workaround compiler crash by compiling with the `FMT_CONSTEVAL` macro defined: https://godbolt.org/z/EfvnbqT8W.

**Comment by BobIsOnFire** [comment]
Hi @vitaut,

Thank you for a provided workaround! Unfortunately, it doesn't work in all use cases for me. See modified example: https://godbolt.org/z/qn364nn97, where I explicitly use `FMT_STRING` to trigger compile-time checks in C++17 code. Same symptoms, and also doesn't reproduce with clang 16 or above.

**Comment by vitaut** [comment]
Are you mixing consteval-based format string checks (from your original example) with legacy compile-time checks (`FMT_STRING`)?

**Comment by BobIsOnFire** [comment]
Second example is adapted from our codebase, where we use C++17 and thus require FMT_STRING to perform compile-time argument checks.

I've changed it in the original example to use C++20 and consteval, just to show that it could reproduce on more modern code. Sorry for the confusion.

**Comment by vitaut** [comment]
Worked around in https://github.com/fmtlib/fmt/commit/7e58af4eafc11c2b0f92abf111b0e198c9aa0dc7. Thanks for reporting.

**Comment by BobIsOnFire** [comment]
Thank you!
