### ISSUE TITLE
Overrun in fmt::detail::dragonbox::shorter_interval_case<float>

### ISSUE THREAD

**Issue by XiuliangWang** [fmtlib/fmt#3799]
It can be reproduced using following simple code:
```C++
#include "fmt/format-inl.h"

int main() {
    const int exponent = -2985;
    auto ret = fmt::detail::dragonbox::shorter_interval_case<float>(exponent);
    return 0;
}
```

And build it with:
`g++ -DFMT_HEADER_ONLY test-fmt.cc`

The error is:
./a.out 
fmt/format-inl.h:260: assertion failed: k is out of rangeterminate called without an active exception
Aborted (core dumped)

It can be reproduced in 10.2.1.

**Comment by vitaut** [comment]
`fmt::detail::dragonbox::shorter_interval_case` is an internal function that is not supposed to be called directly and, as the assertion message says, the argument is out of range.
