### ISSUE TITLE
chrono glibc '-' ext applies to following components within a spec

### ISSUE THREAD

**Issue by durka** [fmtlib/fmt#3811]
In the latest version, @ShawnZhong implemented #2959 via #3271. This allows the use of `-` as a modifier in chrono format specs to omit the leading zero from `H`, `M`, and `S`.

However, a difference from `std::strftime` is that the modification "sticks" to an entire format spec, so `{:-M:%S}` behaves differently than `{:%-M}{:%S}` (the former strips the leading zero from minutes *and* seconds, while the latter only modifies the minutes). Is this intended behavior?

Here is a [godbolt repro](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:49,endLineNumber:8,positionColumn:49,positionLineNumber:8,selectionStartColumn:49,selectionStartLineNumber:8,startColumn:49,startLineNumber:8),source:'%23include+%3Ciostream%3E%0A%23include+%3Cfmt/format.h%3E%0A%23include+%3Cfmt/chrono.h%3E%0A%0Aint+main()+%7B%0A++++auto+t+%3D+std::chrono::seconds(125)%3B%0A%0A++++std::cout+%3C%3C+%22fmt::format(%7B:%25-M:%25S%7D)%5Ct+++++++++BUG%5Ct%22+%3C%3C+fmt::format(%22%7B:%25-M:%25S%7D%22,+t,+t)+%3C%3C+std::endl%3B%0A++++std::cout+%3C%3C+%22fmt::format(%7B:%25-M%7D:%7B:%25S%7D)+workaround%5Ct%22+%3C%3C+fmt::format(%22%7B:%25-M%7D:%7B:%25S%7D%22,+t,+t)+%3C%3C+std::endl%3B%0A++++%0A++++char+buffer%5B128%5D%3B%0A++++auto+tt+%3D+std::time_t(t.count())%3B%0A++++std::strftime(buffer,+sizeof(buffer),+%22%25-M:%25S%22,+std::localtime(%26tt))%3B%0A++++std::cout+%3C%3C+%22std::strftime(%25-M:%25S)%5Ct%5Ct%5Ct%22+%3C%3C+buffer+%3C%3C+std::endl%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:35.747520288548245,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g75,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'1',directives:'0',execute:'0',intel:'1',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:fmt,ver:trunk)),options:'',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+7.5+(Editor+%231)',t:'0')),k:16.82236248872858,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+7.5',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+7.5+(Compiler+%231)',t:'0')),k:47.43011722272317,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

As a side note, unless I missed it the `-` extension for chrono specs is not mentioned in the documentation.

**Comment by phprus** [comment]
Fix: #3812

**Comment by durka** [comment]
That was fast!

**Comment by phprus** [comment]
@durka 
Please, test this PR
