### ISSUE TITLE
Define a "namespace" for user-defined format specifiers

### ISSUE THREAD

**Issue by YehezkelShB** [fmtlib/fmt#3827]
Use-case: When I define a customized formatter for my type, I'd like to:
1. add my own format specifiers (e.g. `r` to print my `complex` number in polar form)
2. provide the same specifiers provided for `double` (my underlying type)

Problem: maybe the library might add `r` as a format specifier for `double` in the future (let's say for rounding the number to the closest integer, for example), and then I'll have to choose between renaming my format specifier and "renaming" the library's specifier when using my type. Anyway, older versions of my library will have a surprising behavior for users, who might expect my type to respect the library's specifier.

Suggestion: like was done in the standard for UDLs, let's keep a "namespace" for user-defined specifiers. My suggestion is to document that `__` (double underscore) is reserved, and will never be used, and user-defined formatters can use it as a signal to stop processing "standard" specifiers and start interpreting all specifiers as custom ones.

(Single underscore isn't suitable IMO, because it might be the first specifier for string types, to note a fill character)

**Comment by YehezkelShB** [comment]
(Sorry for the too-early sending with partial title and no details 🙈)

**Comment by vitaut** [comment]
Thanks for the suggestion. `__` won't work because it is a valid format spec for chrono but you could already handle nested specifiers similarly to ranges: https://eel.is/c++draft/format#range.formatter-2. Nothing is necessary for this from the {fmt} or `std::format` side.

**Comment by YehezkelShB** [comment]
IIUC, the suggestion for such a formatter is to define the syntax as: `{:^6:r{04X:y}{b:t}}` if Point supports different formatting for each of its 2 coordinates and have `r` format for Point and support also `y` and `t` custom formatting (whatever those would be) for the elements themselves. OK, it makes sense. I'm still not sure about the train of `:`s that will be created when nesting them inside ranges or tuples, though. `:` already has meaning there and here one of them is stolen for the custom format separator

**Comment by vitaut** [comment]
Something like that except that I wouldn't recommend using `{...}` since it already has meaning in {fmt}. Also controlling formatting of each individual element via a format string might be too clunky. You might want to do it via a view instead.
