### ISSUE TITLE
no `flockfile` and `funlockfile` on esp32

### ISSUE THREAD

**Issue by dominicpoeschko** [fmtlib/fmt#3829]
Since 6b68dff there is a locked file buffer.
On ESP32 platform there are no implementations for `flockfile` and `funlockfile`.

https://github.com/dominicpoeschko/libfmt_link_error_esp32/actions/runs/7666041796/job/20893071698

Shows the corresponding linker error

```
/opt/esp/tools/riscv32-esp-elf/esp-13.2.0_20230928/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: format.cc:(.text._ZN3fmt3v106detail17file_print_bufferD2Ev[_ZN3fmt3v106detail17file_print_bufferD5Ev]+0x3a): undefined reference to `funlockfile'
```
```
/opt/esp/tools/riscv32-esp-elf/esp-13.2.0_20230928/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: _deps/fmt-build/libfmt.a(format.cc.obj): in function `.L0 ': format.cc: .text._ZN3fmt3v106detail17file_print_bufferC2EP7__sFILE[_ZN3fmt3v106detail17file_print_bufferC5EP7__sFILE]+0x38): undefined reference to `flockfile'
```

previous to 6b68dff it builds without problems.

I have tested the recommended feature test macros for `funlockfile` but they also are true for the ESP32 platform :(

**Comment by vitaut** [comment]
What C library is this?

We might need to check flockfile/fulockfile availability with SFINAE.

**Comment by dominicpoeschko** [comment]
Some kind of Newlib

**Comment by vitaut** [comment]
> the functions are defined but Not implemented

It looks like a bug in the standard library implementation to me. I would recommend reporting to your library vendor.

**Comment by vitaut** [comment]
Possibly related to https://github.com/espressif/esp-idf/issues/2565.

**Comment by vitaut** [comment]
Closing as this is clearly a bug in the standard library implementation. As a workaround you could provide empty definitions for these functions and link with those.
