### ISSUE TITLE
Is it possible to clear/reset fmt::MemoryWriter?

### ISSUE THREAD

**Issue by mh321** [fmtlib/fmt#383]
Hi,

Is it possible to clear/reset/reuse `fmt::MemoryWriter`?

Thanks

**Comment by chronoxor** [comment]
I think yes. Its public parent class BasicWriter contains clear() method which can be used to clear/reset buffer size. Moreover you can access to its raw data using data() or buffer() methods!

**Comment by vitaut** [comment]
Yes, as @chronoxor wrote, you can use the `clear` method.
