### ISSUE TITLE
g++-14 warning on self-comparison

### ISSUE THREAD

**Issue by rcasellas** [fmtlib/fmt#3830]
Dear all,

FYI, updated to g++-14 in development Ubuntu Noble. Unless mistke on my part, I am using master branch

I am getting the following warning:

ext/fmt/include/fmt/ranges.h:164:49: warning: self-comparison always evaluates to true [-Wtautological-compare]
  164 |                      integer_sequence<bool, (Is == Is)...>) -> std::true_type;

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/8e62172ab6742c0e399d906456f54c927ebd4f3a. Thanks for reporting.
