### ISSUE TITLE
For footprint optimization: Add  define FMT_SUPPORTS_LOCALE

### ISSUE THREAD

**Issue by RalfOb** [fmtlib/fmt#3831]
Running the format library on embedded systems with low resources might be challenging due the huge foortprint (several 100k) the fmt library produces. 
The footprint can be significantly reduced if the references to localization and time formatting code can be avoided. This can be done by setting e.g.
FMT_STATIC_THOUSANDS_SEPARATOR='.'

From the technical point ok, but hard to find out. Especially it does more than expected - in a very positive manner.

To help other developers and make the way to small footprint more obvious, it would be good to have some explicit define available which controls the usage/access to localization like:
FMT_SUPPORTS_LOCALE

Before start implementing this, I would like to hear opinions about that.

**Comment by vitaut** [comment]
Sounds reasonable with one minor change that the macro should be named `FMT_USE_LOCALE` for consistency with other similar macros. A PR to add it would be welcome.

**Comment by vitaut** [comment]
Anyway I don't think we need to track this as an issue so I'm going to close this but a PR would still be welcome.
