### ISSUE TITLE
FMT_STATIC_THOUSANDS_SEPARATOR broken in 10.0.0

### ISSUE THREAD

**Issue by vuvova** [fmtlib/fmt#3835]
It seems that FMT_STATIC_THOUSANDS_SEPARATOR no longer works in 10.0.0. The following test succeeds in 8.0.1 but fails in 10.0.0:
```c++
#define FMT_STATIC_THOUSANDS_SEPARATOR ','
#define FMT_HEADER_ONLY 1
#include <fmt/format-inl.h>
int main() {
  int answer= 4321;
  fmt::format_args::format_arg arg=
    fmt::detail::make_arg<fmt::format_context>(answer);
  return fmt::vformat("{:L}", fmt::format_args(&arg, 1)).compare("4,321");
}
```

References: https://jira.mariadb.org/browse/MDEV-32815

**Comment by vitaut** [comment]
Bisected to https://github.com/fmtlib/fmt/commit/b98ffb7dbdb7d97e14ea65fad757cb5bb853d98b.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/44c3fe1ebb466ab5c296e1a1a6991c7c7b51b72e, thanks for reporting.
