### ISSUE TITLE
Custom thousand separator

### ISSUE THREAD

**Issue by razaqq** [fmtlib/fmt#3840]
Lets say you have the number 1343213 and would like it formatted as `1 343 213` or `1#343#213` or any other thousands separator, how is that possible? I have tried setting `#define FMT_STATIC_THOUSANDS_SEPARATOR ' '` but that didnt work. Thanks

**Comment by vitaut** [comment]
You can do it with locale: https://en.cppreference.com/w/cpp/locale/numpunct.
