### ISSUE TITLE
Formatting nested custom types with indentation

### ISSUE THREAD

**Issue by florianhumblot** [fmtlib/fmt#3842]
I'm trying to create formatters for my custom types. 
If a user defined type has a member that is another user defined type, it would be great if the indentation level would match whatever is being printed.

```c++
struct Userinfo_t {
    etl::string_view username;
    std::optional<etl::string_view> password;
};

struct Authority_t {
    std::optional<Userinfo_t> userinfo;
    etl::string_view host;
    std::optional<uint16_t> port;
};
```

Say I have the two structs above, if I only wanted to format/print `Userinfo_t` I would want it to look something like this:
```
Userinfo_t {
    username: ...,
    password: std::nullopt
}
```

but if I want to format/print `Authority_t`, I would like it to look like:
```
Authority_t {
	userinfo: Userinfo_t {
	        host: "www.example.com", 
	        port: "std::nullopt"
        }, 
	path: ""
	query: "std::nullopt"
	fragment: "std::nullopt"
}
```

This is what I tried so far:
https://godbolt.org/z/EjY5Kz7hr

Is there something I'm overlooking ?

**Comment by vitaut** [comment]
There is no concept of indentation in {fmt} so you'll need to handle it yourself. Regarding specific ideas how to do it, I would recommend asking on StackOverflow with the tag `[fmt]`: https://stackoverflow.com/questions/tagged/fmt.
