### ISSUE TITLE
Request to add println to fmt

### ISSUE THREAD

**Issue by askraskr** [fmtlib/fmt#3845]
please consider adding `println()` to `fmt`. (Similar to `std::println()`)
`fmt::print()` is already available. it would be great if `fmt` had `fmt::println()` too.

**Comment by vitaut** [comment]
https://fmt.dev/dev/api.html#_CPPv4IDpEN3fmt7printlnEv13format_stringIDp1TEDpRR1T

**Comment by askraskr** [comment]
Thank you.
Haven't read the documentation again in long time.
Just been using the library for a long time.
