### ISSUE TITLE
core.h does not exist.

### ISSUE THREAD

**Issue by askraskr** [fmtlib/fmt#3847]
after installing fmt, I tried to use `core.h`, but I realized that it was not installed with other header files.
the header file `core.h` is not available after install fmt.

![Screenshot_2024-02-10_11-05-04](https://github.com/fmtlib/fmt/assets/143619332/bdd8b0ab-07a7-459c-ac6d-2ccdc08b3c45)

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/7a63e233d283bcaf40f77ee048ae4ad39808aa92, thanks for reporting.
