### ISSUE TITLE
Feature request: `print` overload for `char8_t` in `xchar.h` suggested

### ISSUE THREAD

**Issue by Dani-Hub** [fmtlib/fmt#3848]
The following code,

https://godbolt.org/z/ddsE65fer

which attempts to call the `fmt::print` function using a `char8_t` string literal is currently unsupported, even though calling `std::format(u8"Something")` is supported. The infrastructure to implement this function seems already to exist, since it would correspond to the non-mojibake `vprint` variant.

The availability of that new overload would be very helpful, especially for Windows environments, where it is often not possible to ensure that all parties agree on using an UTF-8 encoded `char` source base, and would allow to realize portable Unicode I/O on the `FILE` level.

Would a PULL request for such a feature be welcome?

**Comment by vitaut** [comment]
We definitely don't want to encourage `char8_t` use but you can create such overload in your codebase for legacy code.

**Comment by Dani-Hub** [comment]
What is the reason for this strong position? `char8_t` is part of the C++ standard and it has the advantage that it clearly indicates a character encoding regardless of the literal encoding. It looks a bit odd to me that `fmt::format` calls are supported for `char8_t` strings, but `fmt::print` should not be. Could you elaborate?

**Comment by vitaut** [comment]
There is a number of problems with `char8_t`, see e.g. https://www.think-cell.com/en/career/devblog/char8_t-was-a-bad-idea for a subset, and it's generally misused. Pretty much the only use case for `char8_t` is migrating legacy code on Windows and it doesn't do a very good job there either. Therefore usage of `char8_t` is discouraged and we shouldn't spend valuable resources on supporting it. For legacy use cases you can define your own `print` function.

**Comment by Febbe** [comment]
It's right, that an Tag struct for the encoding of a string/string_view would be better, but we now have char8_t and the support for it would be good. Especially for Windows systems. A Softwareprovider can't control the complete hardware and software stack of any customer. Also std::filesystem returns std::u8string. Which can't be formatted correctly without writing a custom formatter.

**Comment by Febbe** [comment]
It's right, that an Tag struct for the encoding of a string/string_view would be better, but we now have char8_t and the support for it would be good. Especially for Windows systems. A Softwareprovider can't control the complete hardware and software stack of any customer. Also std::filesystem returns std::u8string. Which can't be formatted correctly without writing a custom formatter.
