### ISSUE TITLE
Is C++ 20 a minimum requirement to build the lib?

### ISSUE THREAD

**Issue by playgithub** [fmtlib/fmt#3862]
for that `vcpkg` needs a universal C++ standard for all libs

**Comment by vitaut** [comment]
No, quoting the docs (https://fmt.dev/latest/index.html#portability):

> The library is highly portable and relies only on a small set of C++11 features

**Comment by playgithub** [comment]
What does the feature of `fmt` below mean?

Implementation of [C++20 std::format](https://en.cppreference.com/w/cpp/utility/format) and [C++23 std::print](https://en.cppreference.com/w/cpp/io/print)

**Comment by vitaut** [comment]
It means that {fmt} implements these APIs (in the fmt namespace).

**Comment by insunaa** [comment]
fmt.cc uses
```cpp
#include <version>
```
which is requires C++20, so at least if you try to compile `fmt.cc` you will require C++20

**Comment by phprus** [comment]
@insunaa
No.
``fmt.cc`` is used only to build the C++20 ``fmt`` module.
You can compile ``fmt`` library using C++11 and later.

**Comment by playgithub** [comment]
> fmt.cc uses
> 
> ```c++
> #include <version>
> ```
> 
> which requires C++20, so at least if you try to compile `fmt.cc` you will require C++20
> 
> Edit: To consume a pre-compiled `fmt` library however you should not need C++20, only if you want to build it yourself

@vitaut
Is it true?

**Comment by insunaa** [comment]
Please don't ping people unnecessarily, lol. It's accurate that fmt.cc as I have said, requires C++20 to build. As for "only when building the C++20 fmt module" yes also correct, but some development environments are a bit stupid (PlatformIO for example) they see that a CMakeLists.txt contains any sort of target and try to build it, so the current version of fmtlib/fmt as it is on GitHub cannot be used as a dependency in PlatformIO when using a toolchain that doesn't support C++20. This isn't something that {fmt} has to or should fix, but it's something that people who want to use {fmt} might want to be aware of. (Tho again: it's not the duty of {fmt} to educate people on that)

**Comment by playgithub** [comment]
OK, thanks very much.

**Comment by vitaut** [comment]
insunaa's comment is not 100% correct. The fmt target doesn't contain fmt.cc if modules are disabled so it doesn't introduce a C++20 dependency even on CMake level.

**Comment by insunaa** [comment]
That doesn't stop PlatformIO from trying to compile it, tho to be fair they may do something even more stupid than that and just try to compile every .cpp or .cc file in whatever directory tree the dependency is. It's a niche issue not directly caused by fmt either way.

much funnier is that you have to use static_cast<std::string>() on std::string variables to be able to use them as arguments in fmt::format(), but that also has nothing to do with the topic at hand :laughing:
