### ISSUE TITLE
Proposal to add syntax for removing leading zeros in time formatting

### ISSUE THREAD

**Issue by centuryboy774** [fmtlib/fmt#3867]
I believe it would be highly beneficial to add syntax that allows for the removal of leading zeros in both 12-hour and 24-hour time formats. This would enable applications and utilities using this library to create cleaner and more visually appealing time displays.

Currently, users like myself who utilize tools like Waybar (which relies on the FMT library) often have to resort to workarounds due to the lack of this functionality.  Adding a simple syntax option to remove leading zeros would be incredibly convenient and valuable for developers and end-users alike.

This is a widely desired feature, not a niche request. Many people, myself included, would greatly appreciate its implementation. While I'm not a direct contributor to the project, I humbly request that you consider adding this useful feature. I love how efficiently fast this library is and I believe that adding new syntax to support getting rid of the leading zero wouldn't affect how fast it is.

**Comment by vitaut** [comment]
Same as #2959.
