### ISSUE TITLE
`fmt@v10.1.1` has CMake package version 10.1.0

### ISSUE THREAD

**Issue by trxcllnt** [fmtlib/fmt#3868]
Version 10.1.1 [isn't reflected in core.h for tag 10.1.1](https://github.com/fmtlib/fmt/blob/10.1.1/include/fmt/core.h#L21), yielding a CMake package with version 10.1.0. This leads to `find_package(fmt 10.1.1)` failing if a user configures and installs `fmt` from the 10.1.1 tag.

Is it possible to update the version and regenerate the 10.1.1 tag?

**Comment by vitaut** [comment]
I don't think it's a good idea to change tags retroactively but this has already been addressed in newer versions.
