### ISSUE TITLE
Build fails on non Desktop App Windows API family

### ISSUE THREAD

**Issue by mp-t** [fmtlib/fmt#3870]
Usage of `_isatty` is guarded by `_WIN32` however the include for it is guarded as such:
```
#if defined(_WIN32) && !defined(FMT_WINDOWS_NO_WCHAR)
#  include <io.h>  // _isatty
#endif
```

Resulting in a failed build on Windows platforms that have to set `FMT_WINDOWS_NO_WCHAR` due to unavailable functions in the specific Windows API family.

**Comment by vitaut** [comment]
We don't actively support such Windows versions but a PR would be welcome.
