### ISSUE TITLE
[feature-request] make `fmt::detail::file_print_buffer` public

### ISSUE THREAD

**Issue by TheClonerx** [fmtlib/fmt#3871]
I find myself chaining print/format calls to `FILE*` streams quite often, could it be doable to expose something like `fmt::detail::file_print_buffer` for this use case?
<details><summary>Here's an example of what I mean</summary>

```cpp
#include <fmt/chrono.h>
#include <fmt/format.h>

enum class Level { debug, info, error, };

constexpr char const* to_string(Level level) {
    switch (level) {
        case Level::debug: return "debug";
        case Level::info: return "info";
        case Level::error: return "error";
        default: return "unknown";
    }
}

template <typename... Args>
void log(Level level, fmt::format_string<Args...> format, Args const&... args) {
    fmt::print(stderr, "[{}] [{}] ", to_string(level), std::chrono::system_clock::now());
    fmt::vprint(stderr, format, fmt::make_format_args(args...));
    fmt::print(stderr, "\n");
}

int main() {
    log(Level::info, "hello {}", "world");
}
```
</details>

Another way of achieving this is by either using an intermediary buffer (`fmt::memory_buffer`) which `fmt::print` is trying to avoid, or by surrounding the prints with `flockfile`/`funlockfile` (since these are recursive) which would be duplicate effort by the user.

**Comment by TheClonerx** [comment]
I think an API like this would be good as it matches the current `fmt::memory_buffer` pattern.
```cpp
template <typename... Args>
void log(Level level, fmt::format_string<Args...> format, Args const&... args) {
    auto out = fmt::file_buffer(stderr);
    fmt::format_to(std::back_inserter(out), "[{}] [{}] ", to_string(level), std::chrono::system_clock::now());
    fmt::vformat_to(std::back_inserter(out), format, fmt::make_format_args(args...));
    fmt::format_to(std::back_inserter(out), "\n");
}

**Comment by vitaut** [comment]
Thanks for the suggestion. I think it would expose too many implementation details of {fmt} but you can achieve something similar via a custom formatter that writes the prefix and the formatted message.

**Comment by TheClonerx** [comment]
For future reference, here's how that'd look:
https://godbolt.org/z/EYY69MeTd
