### ISSUE TITLE
[feature-request] Built-in formatter for exception classes derived from std::exception

### ISSUE THREAD

**Issue by kkarbowiak** [fmtlib/fmt#3872]
Would you consider adding a built-in formatter for exception classes derived from `std::exception`?

This would reduce the following code
```c++
#include <fmt/core.h>
#include <stdexcept>

int main() {
    try {
        throw std::runtime_error("Very bad error!");
    } catch (std::exception const & e) {
        fmt::print("Caught exception: {}\n", e.what());
    }
}
```
to the simpler (notice the lack of need to call exception's `what` function)
```c++
#include <fmt/core.h>
#include <stdexcept>

int main() {
    try {
        throw std::runtime_error("Very bad error!");
    } catch (std::exception const & e) {
        fmt::print("Caught exception: {}\n", e);
    }
}
```
[Version above on Compiler Explorer](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:47,endLineNumber:8,positionColumn:47,positionLineNumber:8,selectionStartColumn:47,selectionStartLineNumber:8,startColumn:47,startLineNumber:8),source:'%23include+%3Cfmt/core.h%3E%0A%23include+%3Cstdexcept%3E%0A%0Aint+main()+%7B%0A++++try+%7B%0A++++++++throw+std::runtime_error(%22Very+bad+error!!%22)%3B%0A++++%7D+catch+(std::exception+const+%26+e)+%7B%0A++++++++fmt::print(%22Caught+exception:+%7B%7D%5Cn%22,+e)%3B%0A++++%7D%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:g102,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:fmt,ver:'700')),options:'-O',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+10.2+(Editor+%231)',t:'0')),k:50,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+10.2+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

Do you think it's worth the effort? I can try and work on a PR.

**Comment by mwinterb** [comment]
This is available in fmt/std.h as of version 10.
https://godbolt.org/z/afqhhcar4

**Comment by kkarbowiak** [comment]
> This is available in fmt/std.h as of version 10. https://godbolt.org/z/afqhhcar4

Haven't noticed this. Thank you!
