### ISSUE TITLE
Where is the implementation for FMT_API auto vformat(string_view fmt, format_args args) -> std::string;?

### ISSUE THREAD

**Issue by sunlong169** [fmtlib/fmt#3873]
I can see the declaration for `vformat(string_view fmt, format_args args) in `[core.h](https://github.com/fmtlib/fmt/blob/9.1.0/include/fmt/core.h). 

```
FMT_API auto vformat(string_view fmt, format_args args) -> std::string;   //line number 3190
```

But I can't find the implementation for said funciton after I have carefully searched and read the project.

I only can see the declaration and implementation of `fmt::v9::detail::vformat(const Locale& loc, basic_string_view<Char> format_str,
             basic_format_args<buffer_context<type_identity_t<Char>>> args)` in [format.h](https://github.com/fmtlib/fmt/blob/9.1.0/include/fmt/format.h), but it not what I am looking for.
```
template <typename Locale, typename Char>
auto vformat(const Locale& loc, basic_string_view<Char> format_str,
             basic_format_args<buffer_context<type_identity_t<Char>>> args)
    -> std::basic_string<Char> {
  basic_memory_buffer<Char> buffer;
  detail::vformat_to(buffer, format_str, args, detail::locale_ref(loc));
  return {buffer.data(), buffer.size()};
}

```

**Comment by vitaut** [comment]
https://github.com/fmtlib/fmt/blob/a33701196adfad74917046096bf5a2aa0ab0bb50/include/fmt/format-inl.h#L1468
