### ISSUE TITLE
Exception with fmt::arg as floating-point precision, FMT version 100202

### ISSUE THREAD

**Issue by BorysLysyansky** [fmtlib/fmt#3874]
I have the following minimal code compiled with GCC 13.2 (Windows), -DFMT_HEADER_ONLY:
```
#include <iostream>
#include <string>
#include <fmt/format.h>

int main() {
    std::cout << "Hello World! " << FMT_VERSION << std::endl;
    std::string suffix = "suffix";
    try {
        std::cout << fmt::format("{:.{p}f} {}", 1.0, suffix, fmt::arg("p", 4)) << std::endl;
    } catch (std::exception& ex) {
        std::cout << "Exception: " << ex.what() << std::endl;
    }
    return 0;
}
```
Link to the godbolt: [https://godbolt.org/z/5qEeEv6Ma](https://godbolt.org/z/5qEeEv6Ma)

The current FMT version generates exception:
**Hello World! FMT_VERSION=100202
Exception: cannot switch from manual to automatic argument indexing**

The previous FMT version has provided the following expected result:
**Hello World! FMT_VERSION=100100
1.0000 suffix**

Is it some expected behavior or is it some bug?

**Comment by vitaut** [comment]
#3817
