### ISSUE TITLE
formatting double with fixed format, but no trailing zeros

### ISSUE THREAD

**Issue by zaphod71** [fmtlib/fmt#3877]
I would like to switch from boot.format to fmt. i like fmt much better, also because of the performance. only one thing is missing for my application, which has already been mentioned several times (according to my research). It is a special formatting of double values - fixed format but without following zeros.
Examples with 3 decimal places, like .3f

1.23555 -> 1.236
1.10000 -> 1.1
1.00000 -> 1
0.00000 -> 0

it should also work with the decimal point that always appears, sth like #.3f

1.23555 -> 1.236
1.10000 -> 1.1
1.00000 -> 1.
0.00000 -> 0.

My question now is, couldn't a new formatting type be introduced for the behavior described above?
I don't understand the argument to be close to the current standard C++20 std::format, then you could also use that. Also solving the problem with a custom type is not a solution for me, existing projects use the double type.

An important argument in favor of fmt would be that it is better and more comprehensive than the standard.

I am looking forward to the answers/discussion.

**Comment by vitaut** [comment]
Looks the same as #2155.

**Comment by zaphod71** [comment]
I don't think you can express it in a format string directly but you can use the f specifier and then remove trailing zeros and the decimal point. 

[As you meant: #2155]((https://github.com/fmtlib/fmt/issues/2155#issuecomment-787183293) 
Of course it works, even with printf - I would just like it to be more convenient, as would others.

[The format string syntax is pretty much fixed at this point for compatibility with std::format. That said you can implement this functionality via the extension API without changes to the core library.](https://github.com/fmtlib/fmt/issues/2155#issuecomment-999092813)

that it is close to the standard - is very good, but why not extend it, that does not harm the fmt library, if the standard works, but there would still be extensions, everything so far continues to work exactly....

**Comment by zaphod71** [comment]
Hi,

i implemented the new type in the current version. Do you want to see the code?

this is an example output for the double value:

```
	double w = -0.00000001;

	fmt::print("{{:+.3v}}={:+.3v} {{:+#.3v}}={:+#.3v}\n", w, w);
	fmt::print("{{:-.3v}}={:-.3v} {{:-#.3v}}={:-#.3v}\n", w, w);
	fmt::print("{{:.3v}}={:.3v} {{:#.3v}}={:#.3v}\n", w, w);
	fmt::print("{{:*>12.3v}}={:*>12.3v} {{:#.3v}}={:#.3v}\n", w, w);
```

output:

{:+.3v}=-0 {:+#.3v}=-0.
{:-.3v}=-0 {:-#.3v}=-0.
{:.3v}=0 {:#.3v}=0.
{:*>12.3v}=***********0 {:#.3v}=0.

**Comment by zaphod71** [comment]
should i make a PR to be able to present the enhancements?

**Comment by vitaut** [comment]
No but you can post an example of a user-defined formatter that does this.

**Comment by zaphod71** [comment]
As i understand it, i can't define a user-defined formatter for a standard type like double. that's why i integrated the new type for formatting. i only have to add/change about 40 lines. everything existing should work as before.
is there a change that this change can be integrated into the library in an upcoming version?

If not, what are the reasons for this. I would be happy to start a discussion on this.

**Comment by vitaut** [comment]
You can define a custom formatter for this via a wrapper type.

**Comment by zaphod71** [comment]
I apologise for being so harsh, I don't want to annoy anyone.
I have understood that and I know how to implement it.
What are the reasons for not including the new format type?
- performance?
- no standard?
- no need?
- no time/resources to implement?

in my use case i sometimes have more than a million double values to format. just to wrap the value in a wrapper type and then edit it in a custom formatter makes no sense and costs unnecessary performance.

the use case is quite common in industry, especially with nc machines, such as milling and turning machines, also 3d printers. it is nc code or gcode. the new format reduces the file size and is more readable.
