### ISSUE TITLE
[qtest-parallel testing] C++ exception with description "cannot open file test-file: No such file or directory" thrown in the test body.

### ISSUE THREAD

**Issue by vgorrX** [fmtlib/fmt#3878]
Probably, there are some problems with test sources for FMT project.
When I start the testing with **qtest-parallel** the following exception is thrown sometimes:
_C++ exception with description "cannot open file test-file: No such file or directory" thrown in the test body._

Possible, I've found out a root cause of this issue and I'm going to share my concerns with you.
Lets to consider two tests, namely:

_TEST(file_test, read_error) {_
_file f(**"test-file"**, file::WRONLY);_
_char buf; // We intentionally read from a file opened in the write-only mode to_
_// cause error._
_EXPECT_SYSTEM_ERROR(f.read(&buf, 1), EBADF, "cannot read from file");_
_}_

_TEST(file_test, write_error) {_
_file f(**"test-file"**, file::RDONLY);_
_// We intentionally write to a file opened in the read-only mode to_
_// cause error._
_EXPECT_SYSTEM_ERROR(f.write(" ", 1), EBADF, "cannot write to file");
}_

These tests work w/ the file that has a similar name, namely, **test-file** .
I suppose, this file can be removed when one test closes it whereas another uses this file a while.
Certainly, I mean the testing in the parallel mode. In my opinion here the exception mentioned above can be thrown rarely.

Could you please confirm or deny my guesses?

Thanks in advance,
Vladimir.

PS. I've prepared a patch that we're using for our CI stand to suppress the problem described there.
      You can look at it if you're wondering.

[fmt.patch.txt](https://github.com/fmtlib/fmt/files/14472582/fmt.patch.txt)

**Comment by vitaut** [comment]
In general we don't support parallel tests but if it's the only issue, a PR to change file name(s) to avoid conflict would be welcome.

**Comment by vgorrX** [comment]
Indeed the problem described here can be resolved as the following:

_TEST(file_test, read_error) {
file f("test-file", file::WRONLY **|  file::CREATE**);
char buf; // We intentionally read from a file opened in the write-only mode to
// cause error.
EXPECT_SYSTEM_ERROR(f.read(&buf, 1), EBADF, "cannot read from file");
}_

I've detected this bug when moved this test case on the top of file.
In other word this test case worked only because it used the **test-file** as artefact of another test cases.
