### ISSUE TITLE
Embedded/Freestanding support?

### ISSUE THREAD

**Issue by elbeno** [fmtlib/fmt#3885]
What are the chances that fmt could someday support freestanding? Or if not freestanding by the letter of the standard, an implementation of the STL that is commonly used for embedded, for example https://github.com/modm-io/avr-libstdcpp ?

Here's the issue: fmt is really valuable for compile-time formatting, and that is totally suitable for embedded work. Likewise formatting to fixed buffers and such. But including `<string>` and `<stdexcept>` (and maybe some other things, I haven't made an exhaustive study) doesn't play well with embedded platforms. I don't know if this issue has already been brought up and discussed, but a search of the issues for "freestanding" didn't turn up any results.

So - is there a path to being able to use fmt -- potentially in a compile-time only manner -- in an embedded or freestanding toolchain environment? Do you have thoughts @vitaut ?

This problem isn't unique to fmt by the way; being able to use "the full STL" at compile-time only on freestanding toolchains is an open problem in C++ standardization, getting more important all the time given how many things are becoming constexpr-usable.

**Comment by lukevalenty** [comment]
This would be extremely helpful. 👍🏽

**Comment by vitaut** [comment]
We recently got rid of `std::string` dependency in `fmt/base.h` but in general it is problematic to do in a maintainable way. I think the best option would be to create a stub `<string>` header that provides a minimal subset of the API. I am a bit surprised that avr-libstdcpp doesn't do it already. BTW {fmt} is used on embedded platforms, you might want to look through older issues for some ideas and working configurations.

**Comment by vitaut** [comment]
Closing for now but specific suggestions how to improve embedded support are welcome.
