### ISSUE TITLE
unresolved external symbol __CxxFrameHandler4

### ISSUE THREAD

**Issue by scorp08** [fmtlib/fmt#3888]
Hello
I am building Freecad with fmt last version , however MSVC is complaining from linking problem. Tried with clean build but could not figure it out.

[FreeCADBase.log](https://github.com/fmtlib/fmt/files/14553854/FreeCADBase.log)

**Comment by vitaut** [comment]
{fmt} doesn't use this symbol directly and it looks like a toolchain issue. Make sure to use the same compiler version for compiling {fmt} and your code.

**Comment by vitaut** [comment]
Closing it doesn't look like a bug in {fmt} but feel free to reopen with a self-contained repro.
