### ISSUE TITLE
Disambiguate `std::variant` formatting

### ISSUE THREAD

**Issue by HolyBlackCat** [fmtlib/fmt#3889]
Currently it's sometimes ambiguous which element of `std::variant` is active:
```cpp
fmt::println("{}", std::variant<int, float>{42.f}); // variant(42)
fmt::println("{}", std::variant<int, int>(std::in_place_index<1>, 42)); // variant(42)
```
It would be nice to disambiguate those in some way, by printing the active element index and/or its type name.

**Comment by vitaut** [comment]
Do you know how other languages handle this?

**Comment by adalisk-emikhaylov** [comment]
Nope.

At least for my code, I decided to go with `(float)42` and `(int#1)42` respectively (adding index for types that appear more than once).

**Comment by vitaut** [comment]
Unless there is some established practice in other formatting APIs, I don't think we should handle this specially. If necessary one can print the index manually.
