### ISSUE TITLE
Problem with ranges and nested_formatter

### ISSUE THREAD

**Issue by spinicist** [fmtlib/fmt#3893]
Hello, thanks for creating `nested_formatter`. It looks to be just what I want for formatting Eigen types easily. However I've hit the problem that if I include the `fmt/ranges.h` header, the compiler gets very confused as to which formatter I want. I get different errors with different compilers.

Here is a Godbolt link: https://godbolt.org/z/441eaEaM9

If the `#include <fmt/ranges.h>` at the top is commented out, the code compiles and does what I want.

I suspect I have to constrain the template further somehow, but I am out of my depth. Also - I suspect there is a better way to write the formatter, I am very open to suggestions.

**Comment by vitaut** [comment]
This is essentially the same as #2735.

**Comment by spinicist** [comment]
Oh cool - sorry I didn't find that before posting.
