### ISSUE TITLE
Represent per-call code size in benchmarks

### ISSUE THREAD

**Issue by hchataing** [fmtlib/fmt#3902]
The code-size benchmark on the main Readme page seems to display the code size of the entire binary, i.e. it includes the runtime associated with the tested print method.

While this information is pertinent, it would be interesting to measure the cost of a single invocation and represent the relative cost of using printf vs fmt::print vs ostream etc.

**Comment by vitaut** [comment]
Thanks for the suggestion. The bloat benchmark is already indicative of the per-call code size (this is why {fmt} is linked dynamically there). You can also find another benchmark here: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0645r10.html#BinaryCode.
