### ISSUE TITLE
Give more details on an exception ?

### ISSUE THREAD

**Issue by char990** [fmtlib/fmt#3904]
When I got an exception "!!! main exception :unmatched '}' in format string", it's hard to find where the problem is.

Finally I found it:
auto str = fmt::format("ID={}}", id);

Is is possible to provide more details when throw an exception, like:
"unmatched '}' in format string : \"ID={}}\""

**Comment by vitaut** [comment]
Thanks for the suggestion. We don't plan to add more details in the error message but if you have a compiler with C++20 `consteval` support it will give you a compile-time error.
