### ISSUE TITLE
enum class support

### ISSUE THREAD

**Issue by daviswalker** [fmtlib/fmt#391]
Hello - this library is a godsend. Thank you. I'm working in a project that uses a number of enum classes, e.g:

enum class ErrorCode : int {
   SOME_ERROR;
}

I'm interested in formatting these objects as ints, but the built-in support wants to treat them as custom objects. I can't change these classes to add ostream support. What is the easiest way to do this? I tried adding a templatized report_arg overload, which works if I add it to the C file generating the log statement, but not if I add it the header from which I'm including format.h

template<class T,class=typename std::enable_if< std::is_enum<T>::value >::type>
void format_arg(fmt::BasicFormatter<char> &f, const char *, const T &e) {
  f.writer() << (int)e;
}

Any suggestions would be very appreciated.

Dave

**Comment by daviswalker** [comment]
Similar question is how best to add formatting support for a templated type like std::optional<T> from the standard library that doesn't support the << operator.

Thanks again.

**Comment by vitaut** [comment]
I'm glad you like the library =).

To format a enum class you'll have to provide an overloaded `operator<<` because there is no implicit conversion to `int` there:

```c++
enum class ErrorCode : int {
  SOME_ERROR
};

std::ostream &operator<<(std::ostream& os, ErrorCode ec) {
  return os << static_cast<int>(ec);
}

int main() {
  fmt::print("{}", ErrorCode::SOME_ERROR);
}
```

If you don't want to overload `operator<<`, you can provide a `format_arg` function instead but it is more evolved and not yet documented:

```c++
template <typename ArgFormatter>
void format_arg(fmt::BasicFormatter<char, ArgFormatter> &f,
                const char *&format_str, ErrorCode e) {
  f.writer() << (int)e;
}
```
There is an example here: https://github.com/fmtlib/fmt/blob/master/fmt/time.h#L18.

The same can be done for `std::optional`.

**Comment by daviswalker** [comment]
Okay got it thanks! Is it possible to template this? e.g.

`template<typename T>
std::ostream &operator<<(std::ostream& os, optional<T> o) {
    if (o) {
        return os << o;
    } else {
        return os << "<nullopt>";
    }
}
`

When I use this with a stringstream it compiles fine, e.g.:

`std::optional<string> test = nullopt;
stringstream ss;
ss << test;`

But if I do the same thing with fmt::format it doesn't resolve the template.

**Comment by vitaut** [comment]
It should be possible to do that, but keep in mind that overloaded `operator<<` should either be declared before it is used in `fmt/ostream.h` or placed in the std namespace for ADL.

**Comment by daviswalker** [comment]
Yes indeed - include order was my issue. Thank you for pointing me in the right direction.

**Comment by Paxxi** [comment]
We wanted to have something that "just work" for the whole project so based on the advice in this thread we ended up with this.

```cpp
#include <ostream>
#include <type_traits>

// clang-format off
// This is required to format enum classes with fmt as they're not implicitly
// convertible to int.
// This operator has to be declared before including format.h and ostream.h.
// We keep clang format disabled to avoid reordering and breaking things
// https://github.com/fmtlib/fmt/issues/391
template<typename T, typename std::enable_if_t<std::is_enum<T>::value, int> = 0>
std::ostream& operator<<(std::ostream& os, const T& value)
{
  return os << static_cast<int>(value);
}

#include <fmt/format.h>
#include <fmt/ostream.h>
// clang-format on
```

Put this in a header file like `enum_format.hpp` and include that instead of `fmt/format.h` and enums should just work everywhere in the project.

**Comment by vitaut** [comment]
In recent versions of {fmt} enum classes are formatted as integers by default (https://godbolt.org/z/3Z9sj4):

```c++
#include <fmt/core.h>

enum class ErrorCode : int {
  SOME_ERROR
};

int main() {
  fmt::print("{}", ErrorCode::SOME_ERROR);
}
```

**Comment by DominicTobias** [comment]
@vitaut unfortunately it didn't work for me with 8.1.1 or the most recent commit as of this comment (ba6f89c76ee20d4665c05f18e212b1446fe8d126)

In order to avoid these errors:

```
***/build/_deps/fmt-src/include/fmt/core.h:1706:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
***/build/_deps/fmt-src/include/fmt/core.h:1832:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, OrderSide &, 0>' requested here
        data_{detail::make_arg<
```

I followed the link in the error and wrote a template which fixed the error:

```cpp
enum class OrderStatus {
  open,
  partial_fill,
  filled,
  cancelled,
};

template <> struct fmt::formatter<OrderStatus> : formatter<string_view> {
  template <typename FormatContext> auto format(OrderStatus order_status, FormatContext &ctx) {
    string_view name = "unknown";
    switch (order_status) {
    case OrderStatus::open:
      name = "open";
      break;
    case OrderStatus::partial_fill:
      name = "partial_fill";
      break;
    case OrderStatus::filled:
      name = "filled";
      break;
    case OrderStatus::cancelled:
      name = "cancelled";
      break;
    }
    return formatter<string_view>::format(name, ctx);
  }
};
```

That's very verbose to write for each enum though and I would be ok if `int` worked out the box 🤔

**Comment by vitaut** [comment]
Scoped enum are not implicitly convertible to integers in C++ but the current master support a simplified API if you want to make an enum formattable as an underlying (integral) type:

```c++
auto format_as(OrderStatus s) { return fmt::underlying(s); }
```

**Comment by pagogc** [comment]
Same Problem as [DominicTobias] with 8.1.1

But i have implemented the operator<< for my Enum-Class (and it works correctly before)
`	std::ostream& operator<<(std::ostream& os, KonfigSetWatchType ec) {
		return os << static_cast<int>(ec);
	}`

So not possible anymore?

MSVC 17.1.0, -std=C++20

**Comment by vitaut** [comment]
ostream `operator<<` is supported: https://fmt.dev/dev/api.html#ostream-api

**Comment by pagogc** [comment]
Thanks, i missed the template specialization.
Now it works as expected.

Thanks again for this amazing, performant lib of yours!

**Comment by aserebryakov** [comment]
@vitaut,
> ostream `operator<<` is supported: https://fmt.dev/dev/api.html#ostream-api

Just in case I want write some template function like:
```
template <typename T>
std::string toString(const T& value) {
    return fmt::format("{}", value);
}
```

that should accept `enum class`. Should I provide the formatter specialization per type?

**Comment by vitaut** [comment]
You can either provide formatter specializations or use `format_as` mentioned above.

**Comment by Inori** [comment]
> @Inori, no but you can define a single `format_as` for all enums in your namespace.

Ok，thanks for the reply.
