### ISSUE TITLE
std::chrono::current_zone() is not meant to return the local time zone

### ISSUE THREAD

**Issue by hvenev** [fmtlib/fmt#3927]
[fmt::localtime](https://github.com/fmtlib/fmt/blob/5eb68c0ef25070fe21861c37e6f8458b08453588/include/fmt/chrono.h#L523) uses ` std::chrono::current_zone()` to determine the local time zone. However, per https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114645, the intended behavior of `std::chrono::current_zone()` is to read `/etc/localtime`, which does not match how libc determines the local time zone. The `TZ` environment variable should also be considered.

**Comment by vitaut** [comment]
Thanks for reporting but {fmt} is a C++ library and doesn't have to replicate legacy C behaviors. If you believe there is something wrong with `std::chrono::current_zone` please open an LWG issue.

**Comment by vitaut** [comment]
It's just a fallback. We could make it more consistent with `std::chrono::current_zone` but it's not critical.
