### ISSUE TITLE
Support for a single `char` separator in `fmt::join()`

### ISSUE THREAD

**Issue by jimmy-park** [fmtlib/fmt#3936]
I thought I could do this at the first place, but I failed.

```cpp
fmt::format("{}", fmt::join(vec, '\n'));
```

It turns out `fmt::join()` only supports `fmt::string_view`-convertible separators.
So I just replace `'\n'` to `"\n"`, and it works fine.

It would be nice to have this kind of APIs when handling a single character.
@vitaut Would you accept adding more APIs just to support `char` parameters?

**Comment by vitaut** [comment]
Thanks for the suggestion but you can already pass a single code unit (character):

```c++
fmt::format("{}", fmt::join(vec, "\n"));
```
so there is no reason to add another API for this especially considering that strings are multi-byte.
