### ISSUE TITLE
Question: what's the difference between string-like formatters and where are they defined?

### ISSUE THREAD

**Issue by tocic** [fmtlib/fmt#3942]
It's not clear for me from the docs if [this test project](https://godbolt.org/#z:OYLghAFBqd5QCxAFwE4FN0BoCWIIDGAtgIYDW6AgqsAM4gDkAtACIDCAspQNICiA%2BgCEAqgEkAMi34AVAJoAFXgFIAzCxboARgFdgDLAQD2RAA44ANulTiSAO2DaSwdKIAmIAkoBMg74IPatMjGAPLayCbhAGIW6LYkROgoCOj86AAe6AThJJqWWABmsfSw6K44wahuIABshbHVAIwALPWW8YkgpDi2AHQEJiZYoAz6OLSitgTm2q5ljAAMY7QcJD0AyobaqARJDI3LISZxi/rmdsDVowCUWBBlFYZV7kyNbS7ujQCs7x1JnOR0OJxshaL1kOlkMNGMRAfwiD0cERtER%2BBgAI7aHAYVwQABqvAASutRCEAHIAahUvUaC2uSgWlAZlBMqEMACsssgILQECRjrR6YzmSRXK5%2BOYcJpUCRUABPCCSzQUpX9QYqqW9BBCyjIWXOZASnpkI3S2U4dC0RVSinyQmiPGUaS8CkFIjIVw6kVitKZbJ6vLoCDIFK%2BrI5QMU7p9AYmHV6mjoQ2S2wmpUy1AWq0h1IZcMByy2%2B2O50a5Vuj065aTaazeYMJa4FZrWybba7U5No4nfZnC7VWEUW73cqVaoqd5NACcvwSSVVsehoybNZmc3cDeWqw2Wx2ewOXeOtk753sVwYw4eY/crSKlmqXgWs86qoQS%2BrUzX9cb423rd3Ha9oePaNqelwbhetzjACFDyGynIEMgnbsiAby2OgADuMT3u4XiNLc5iMF8%2BjHpuWCGIw0gYOgFLeCoB5IZu1y3GQICPr0XzNAA7FOzRfI%2BnE8XxrSEQwzQkZ2FHLvQT6MUsw4wFAikQEgRhzLwo5PLg%2BB3nEc5dC2apDAUhi2Mg6wECQliobepnIMItDoPI6TIbUWBgR4fh%2BFgjmWIhOCmfgcSuGwhgzEQx5vMFwLoWSKKaFYIAABxYCYhi0BUAW2KF4WRal6WZaZMXoHFRAJagyU%2BegfnIFl6wJsgOUonlvlcnVDXFaV5WVUEsqNWFzWoT5HU9CV8WJUlty0ABex0T0tZzLRXheK%2B3heMyG1eCo81frRKhsBWAD0RgYFqqjKMKjI9MgUYthA1y0VxviMhSr2uu6IAgKy10QGtShPSAABUShfLwKgLP9LAg2wthrVgFLIJaSEgEyT2Q/SKjPajUOMhe7lERJZEUdGRlYHJeMqR4hjqZpqDaRAul/CAC6DIUdkWVZSQtGzZkOU5LlkShE4eZ4Pjea1/mBfctghQNEVsVg0WjV1iWNBOaUZbVplNfLXj5ZrWWdeNFVq1VNXtX1OvHnrEta62I2xcbqETr1qD9blCuu8gRtlarKhTTNjBzZ%2BdZLStmoIH9l1MltO2h6obBBJm9jnRtwqxyHi0J0dJmoKQyBnSoF1Moyfy0CYJC7O9N3/VjIrhIYrpPPniOoAniNBJ9TJF59uf54QplBAjSNd94NQUiQ8N9yQhpGGZGTIGPFKIekD1z0PTDnU3ecz/wc%2BI5Cn0VFYM9PI9WNvRSGDINstjby3VgJ0E7ggEnPTAOdvfNzPEAkOChj8DfvYe68MV4YzrlxHGJdsZ41EsRLApFGwURZkMcmw5VLU3QBpR4dM8AM1iEzV8PNzKWWstzEyvNHLOVciJC4nkxY%2BDNm1KWwUraoRSkrR2vsKo/A1oVbKctIopT4XbH23Ufi2wtm7NhjQUqSNMvVPqYjEoSIajIuRDsxrcJAF8AO7ZZpbVZE4UgFJTK7DTjHbamcaLZ3dMdJ46BC7F02lYhaNj9pAI/kXCxZcK5Vw7jXNG0ck7aEQhSSg59mSX2uhPPaLAKSNC2qoOuL03okAbgjABnj7rL0HjdTeRcKTP0%2Bp4yJqTL6vWvrfIpHpPrBEAWgd%2Bv9wFRLepDDakDkkWPadHXxlcaIVjKdAxGphziIz2mwVOjIQlhOnsgVu7cR4oy3iAe%2BM8FkeNqa/RpKdCm11aa9dJwQ1ncnXjdAJo8vDj0nicvedkF5LzAbk2wG8t5zLufPQ%2BIBj4ykqF04UnTMbdMga9Q6h0KR9KrhWCxsCCYIMkszCOZNTjMSwCkUUiUQGsWaElXozR8UEsJYS/GYl9BEB0U%2BRB%2BgpL6HoHrNBdxlLKQwaYWIuD8BGFZZYCqwBEkTjvK3egEBNCdk0D0WUcpGAHjFfEeUIRNAIUYgeTliQzIhFsOYSVZE5g6GAGwKy5h6BATmKQew1ltXYjagAN0tJ2PM/o9g/nnqJUCUoMxylCnMTsjTyVARtagTQ6V0AaFNcAFMIx5KFHOHQPEFoMLdlIgeChJDOY2WIXzahgsQDCzoaLXwjClQlCgEzCsWB/VSoWHhSC5ETB2yNUwZ%2BqgWB5r8I%2Bal/rMxzCLVNaqzDjzS1lh7KKMtlEm31vwmR47RHKydm8eR9tLaCKGvOxRbtR3LrUUuudmiVYm1uGgTAqECJwqpeRRgFJ0hJRqEwGozQKTAAIAQBJXhegqApBAKimAlr0WuPoNBtx0VzAqlinR1JOI1AWFOKcXgpwLC4klBYasRKMHElgclVzegLAWF8Li3FEm3pUDUeD8KiaMFpSAWSKLGXwEplsCI4R6bJo5mQ2ylD%2BauQnAe9AOBPhYAwjKEwUrYUMHgaeqSYR6M3UMAUC9V6b13ofU%2BxJr732hS5VYb9/s/0ooA%2BgDFwHj2krQyALi1IoPNC8PxJKpmvg1BUFtEjSCyM%2BQo8ipiLEdGNA4l8Hzvm/M%2BbqKJFQhMnPLn/VgViPE8X8Ww9xXiMXbMkq8GS1CWHHPUuc%2BF0SyX0tnrCzpstVgMqBWaEAA%3D%3D) is correct. What are the differences between `fmt::formatter<const char*>`, `fmt::formatter<std::string_view>`, `fmt::formatter<std::string>`? Can I include only `fmt/core.h` in headers (as in the second example [here](https://fmt.dev/latest/api.html#formatting-user-defined-types))? I thought the CE in fmt 10.2.1 (not on trunk) was related to [this issue](https://github.com/fmtlib/fmt/issues/3584), but now I'm not sure.

**Comment by vitaut** [comment]
Those are specializations for different string types. I will investigate why your example doesn't work with `std::string` formatter but in the meantime you can use a formatter for `fmt::string_view` which works: https://godbolt.org/z/eo4Y7d7nP.

**Comment by vitaut** [comment]
Documented the list of formatter specializations provided by `fmt/base.h` (which will superseed `fmt/core.h`): https://github.com/fmtlib/fmt/commit/f30f1fd5141dd22afdcd32fafaa1f58f10bae8fc. In general it should be sufficient to use `fmt::string_view` but if you want a formatter of `std::string` for some reason you could include `fmt/format.h`.
