### ISSUE TITLE
Add support for grouping numbers and '_', ',' separators

### ISSUE THREAD

**Issue by amal-khailtash** [fmtlib/fmt#3954]
C++ 14 supports optional [digit separators](https://en.cppreference.com/w/cpp/language/integer_literal) like `1'000'000`,  `0b1010'1010`, or `0xFF'FF'FF`

Underscores are also acceptable in literals as described in [PEP 498](https://peps.python.org/pep-0498/) and  [PEP-515](https://peps.python.org/pep-0515/) using `"{number:,}"`, also for larger numbers a comma separated thousand separator is accepted as in `"{number:,}"`.

It would be great if grouping numbers with separators `("_", "'", ",")` are supported.  Python groups decimal numbers in 3 digits (thousands), binary, octal and hex numbers are grouped in 4 digits (4 bits, 12 bits, or 32 bits respectively).

**NOTE**: Python does not allow grouping by a single quote though! `"'"`

More references here:
* https://en.cppreference.com/w/cpp/language/integer_literal
* https://www.pythonmorsels.com/string-formatting/
* https://discuss.python.org/t/add-underscore-as-a-thousandths-separator-for-string-formatting/7407

**Comment by vitaut** [comment]
Same as #3840.
