### ISSUE TITLE
format_as support in fmt/core.h

### ISSUE THREAD

**Issue by cruisercoder** [fmtlib/fmt#3959]
format_as covers a large number of use cases where you need custom formatters but don't need custom format strings and you want a simpler function that can be next to the type's definition in it's namespace.  

Even though the doc says I need fmt/format.h for custom formatters, I was able to include just fmt/core.h with specialization, but not with format_as.   Could format_as be migrated to core without much impact?

**Comment by vitaut** [comment]
If you mean example in https://fmt.dev/latest/api.html#formatting-user-defined-types including `fmt/format.h` then it is only needed for `fmt::underlying`. `format_as` by itself doesn't require any {fmt} includes at all, you just map one formattable type to another.
