### ISSUE TITLE
Warnings with GCC 14

### ISSUE THREAD

**Issue by boxerab** [fmtlib/fmt#3977]
These warnings seem to have popped up in GCC 14
Warnings listed [here](https://gist.github.com/boxerab/b0bd38dadf7b5c951af2b16bb90661fa)

Note: I am using `fmt` via `spdlog` project.

Thanks!

**Comment by vitaut** [comment]
Please provide a self-contained repro (ideally on godbolt) that doesn't involve spdlog.

**Comment by vitaut** [comment]
No problem. Glad it has been resolved.
