### ISSUE TITLE
Cannot find source file: `api.rst`

### ISSUE THREAD

**Issue by seanmiddleditch** [fmtlib/fmt#3987]
On the very latest on master (`e3910b8a9cdb8ab81979af39357eedd5deb94941`) I get this error generating the CMake projects on Windows/MSVC:

```
1> [CMake] -- CMake version: 3.28.3-msvc11
1> [CMake] -- {fmt} version: 10.2.2
1> [CMake] -- Build type: Debug
1> [CMake] -- FMT_PEDANTIC: OFF
1> [CMake] -- Configuring done (0.5s)
1> [CMake] CMake Error at doc/CMakeLists.txt:18 (add_custom_target):
1> [CMake]   Cannot find source file:
1> [CMake] 
1> [CMake]     api.rst
```

I have Doxygen installed, so it looks like the project is trying to build the docs in `doc/`, which appears to not be the case in GitHub Actions (https://github.com/fmtlib/fmt/actions/runs/9331997765/job/25687295919) which might explain why the builds are passing CI?

There's a `doc/api.md` file but no `doc/api.rst` file in the repository, and I don't see any scripts or build steps that would generate a `.rst` version, though I do see a few various references to `.rst` files and not the `.md` files.

I'm guessing this broke as of https://github.com/fmtlib/fmt/commit/19927462497c249d8aa01293da0e1aacace51686

**Comment by vitaut** [comment]
The documentation is being migrated to mkdocs. The doc target itself is fixed in https://github.com/fmtlib/fmt/commit/250456d5a3a892fa53c31c659cfe0d39f303e114 although the migration is still in progress.
