### ISSUE TITLE
Failed to detect trunk clang to support pre-compiled format

### ISSUE THREAD

**Issue by yujincheng08** [fmtlib/fmt#4000]
This one does not compile: https://godbolt.org/z/x315Y9q8Y

However, once we manually define `FMT_USE_NONTYPE_TEMPLATE_ARGS`, it does compile: https://godbolt.org/z/nf1YPfMvG

**Comment by vitaut** [comment]
The compiler reports class types in non-type template parameters as not supported: https://godbolt.org/z/5G1ro8G35. But we could check the clang version explicitly and enable this anyway (a PR is welcome).

**Comment by yujincheng08** [comment]
You are right, https://en.cppreference.com/w/cpp/compiler_support also mentions this.

**Comment by yujincheng08** [comment]
PRed
