### ISSUE TITLE
Manually construct ArgList and pass to fmt::print

### ISSUE THREAD

**Issue by Mark-Joy** [fmtlib/fmt#401]
Hello,

Is there a way to manually construct the ArgList, add new arg to ArgList and then pass it to fmt::print.
Something like:

```
fmt::ArgList argl(int val1, string str2, double db3);
argl.add(string str4);

fmt::print(string str, argl)
```

Thank you

**Comment by vitaut** [comment]
Yes, although this method relies on internal APIs at the moment: https://github.com/fmtlib/fmt/issues/330#issuecomment-220064331

**Comment by Mark-Joy** [comment]
Hello,

I just updated latest version of fmtlib to my project and the old code won't compile. How to achieve the same thing as #330 with latest version?

```
enum {NUM_ARGS = 2};
  typedef fmt::internal::ArgArray<2> ArgArray;
  typename ArgArray::Type array;
  array[0] = ArgArray::template make<fmt::BasicFormatter<char> >(42);
  array[1] = ArgArray::template make<fmt::BasicFormatter<char> >(43);
  fmt::ArgList args(fmt::internal::make_type(42, 43), array);
  fmt::printf("%d %d", args);
```

**Comment by vitaut** [comment]
@Mark-Joy, it is much simpler in the latest version and you don't need to use internal APIs any more:

```c++
  fmt::vprintf("%d %d", fmt::make_printf_args(42, 43));
```
Compiler Explorer: https://godbolt.org/g/74wSR7

**Comment by Mark-Joy** [comment]
@vitaut, Thank you for your answer.
I suppose I would use make_format_args for:

`fmt::vprint("%d %d", fmt::make_format_args(42, 43));`

How about constructing arglist using a for loop as in [this comment](https://github.com/fmtlib/fmt/issues/330#issuecomment-257130213) ?

**Comment by vitaut** [comment]
@Mark-Joy there is no API for constructing arglist in a for loop unfortunately. It should be possible to write one, but noone has done it yet.
