### ISSUE TITLE
MSVC warning C4702 for compile.h

### ISSUE THREAD

**Issue by oold** [fmtlib/fmt#4044]
MSVC (VS 16.11.37, toolset v142) emits warning C4702 (unreachable code) at warning level 4 for this line: https://github.com/fmtlib/fmt/blame/e69e5f977d458f2650bb346dadf2ad30c5320281/include/fmt/compile.h#L151

I wasn't able to test this on Godbolt since MSVC wouldn't find the fmt headers on there. Code looks about the same in trunk, so I'd assume the warning would be emitted, too.

**Comment by vitaut** [comment]
Fixing all possible warnings (especially level 4 which have tons of false positive) is a non-goal but you can suppress them with FMT_SYSTEM or other means.

**Comment by litterbug23** [comment]
> Fixing all possible warnings (especially level 4 which have tons of false positive) is a non-goal but you can suppress them with FMT_SYSTEM or other means.

Warnings will still be reported.

**Comment by litterbug23** [comment]
> MSVC (VS 16.11.37, toolset v142) emits warning C4702 (unreachable code) at warning level 4 for this line: https://github.com/fmtlib/fmt/blame/e69e5f977d458f2650bb346dadf2ad30c5320281/include/fmt/compile.h#L151
> 
> I wasn't able to test this on Godbolt since MSVC wouldn't find the fmt headers on there. Code looks about the same in trunk, so I'd assume the warning would be emitted, too.

Excuse me, how can this warning be removed?

**Comment by litterbug23** [comment]
const T& arg = get_arg_checked<T, N>(args...);
    if constexpr (std::is_convertible_v<T, basic_string_view<Char>>) {
      auto s = basic_string_view<Char>(arg);
      return copy_str<Char>(s.begin(), s.end(), out);
    }
    ### else
     return write<Char>(out, arg);

**Comment by litterbug23** [comment]
const T& arg = get_arg_checked<T, N>(args...);
if constexpr (std::is_convertible_v<T, basic_string_view<Char>>) {
  auto s = basic_string_view<Char>(arg);
  return copy_str<Char>(s.begin(), s.end(), out);
}
else
 return write<Char>(out, arg);

**Comment by litterbug23** [comment]
" if constexpr (std::is_convertible_v<T, basic_string_view>)   "
msvc  compile is always true. 
so "return write(out, arg);" is  unreachable code.
