### ISSUE TITLE
inline namespace has previous version in 11.0.0

### ISSUE THREAD

**Issue by odygrd** [fmtlib/fmt#4047]
Inline namespace is still v10 in 11.0.0 release

https://github.com/fmtlib/fmt/blob/c4f6fa71357b223b0ab8ac29577c6228fde8853d/include/fmt/base.h#L265

**Comment by vitaut** [comment]
Good catch, thanks! Need to update the release script to catch this or bump automatically.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/503e183b9e3284317e5c12ebbf1747b54de33008.
