### ISSUE TITLE
You can (not) control the Unicode support via the CMake `FMT_UNICODE` option.

### ISSUE THREAD

**Issue by grooverdan** [fmtlib/fmt#4051]
version: 11.0.0

It looks like its true, but you can't compile on MSVC without it.

As a subproject the option needs to be enabled for the `target_compile_options` to be applied.

[include/fmt/base.h](https://github.com/fmtlib/fmt/blob/9d946a2fc426f1e1c48c252e55dfadcacf79a3c6/include/fmt/base.h#L290) forces the define to true.

Line 457 will assert if the /utf8 isn't set.

ref: https://buildbot.mariadb.org/#/builders/234/builds/30730/steps/8/logs/stdio

**Comment by vitaut** [comment]
Thanks for reporting. Just to clarify: are you trying to disable Unicode support? Setting `FMT_UNICODE` macro was missing from the CMake config which is fixed in https://github.com/fmtlib/fmt/commit/e50c8b6bd870eb743b2cf13850d5aafcf7d1bad8.

**Comment by grooverdan** [comment]
I just noticed it was there. I'm happy to enable unicode.

**Comment by vitaut** [comment]
Closing as disabling Unicode has been fixed but if there is more to it please let me know.

**Comment by Cazadorro** [comment]
I don't think this is fixed when using CUDA, tried with out cuda and it worked, but when using CUDA, the same exact  /utf8 error:

```
Repos\cuda_experiments\cmake-build-debug\vcpkg_installed\x64-windows\include\fmt\base.h(465):
 error: static assertion failed with "Unicode support requires compiling with /utf-8"
  static_assert(!1 || use_utf8,
```

In fact, I don't see /utf-8 passed to CUDA when using fmt through vcpkg (october 2025 release). 

`nvcc.exe -forward-unknown-to-host-compiler -DFMT_SHARED -isystem Repos\cuda_experiments\cmake-build-debug\vcpkg_installed\x64-windows\include --allow-unsupported-compiler   -D_WINDOWS -Xcompiler=" /EHsc" -Xcompiler=" -Ob0 -Od" -std=c++20 "--generate-code=arch=compute_75,code=[compute_75,sm_75]" -Xcompiler=-MDd -Xcompiler=-RTC1 -Xcompiler=-Zi --expt-relaxed-constexpr -MD -MT CMakeFiles\cuda_experiments.dir\main.cu.obj -MF CMakeFiles\cuda_experiments.dir\main.cu.obj.d -x cu -c Repos\cuda_experiments\main.cu -o CMakeFiles\cuda_experiments.dir\main.cu.obj -Xcompiler=-FdCMakeFiles\cuda_experiments.dir\,-FS`

**Comment by Cazadorro** [comment]
Never mind, it appears to just be this issue https://github.com/fmtlib/fmt/issues/4167
