### ISSUE TITLE
v11.0+ fails to build on Amiga and Xbox

### ISSUE THREAD

**Issue by glebm** [fmtlib/fmt#4054]
fmt from v11.0.0 onwards (https://github.com/fmtlib/fmt/commit/6b68dff90185efd6dd618fd315b5325b9fd0df16)  [no longer builds](https://github.com/diasurgical/devilutionX/pull/7181) for Amiga and Xbox, with the same error on both:

```c++
fmt/format-inl.h:1638:5: error: 'flockfile' was not declared in this scope
 1638 |     flockfile(f);
      |     ^~~~~~~~~
fmt/format-inl.h: In destructor 'fmt::v11::detail::file_print_buffer::~file_print_buffer()':
fmt/format-inl.h:1646:5: error: 'funlockfile' was not declared in this scope; did you mean 'fallback_file'?
 1646 |     funlockfile(file_);
      |     ^~~~~~~~~~~
      |     fallback_file
```

Would it be possible to add a define to avoid using lock/unlock/getc_unlocked, so that it can be built on platforms that do not support these functions?

**Comment by vitaut** [comment]
Just removing these calls might be undesirable. I think we should figure out what `printf` does on these systems and do something similar.

**Comment by vitaut** [comment]
Looks like this is what used on Amiga: 

https://github.com/bebbo/libnix/blob/152139ecbaa9f1349ceec5944d181d1786a84789/sources/headers/stdio.h#L81

**Comment by glebm** [comment]
Got a response in the Xbox issue: https://github.com/XboxDev/nxdk/issues/672#issuecomment-2212445131

**Comment by jwillikers** [comment]
I see these same errors attempting to build for a microcontroller with newlib and picolibc:

```
In file included from /home/jordan/.conan2/p/b/fmtc75dbc04c5faa/b/src/src/format.cc:8:
/home/jordan/.conan2/p/b/fmtc75dbc04c5faa/b/src/include/fmt/format-inl.h: In constructor 'fmt::v11::detail::file_print_buffer::file_print_buffer(FILE*)':
/home/jordan/.conan2/p/b/fmtc75dbc04c5faa/b/src/include/fmt/format-inl.h:1638:5: error: 'flockfile' was not declared in this scope; did you mean '_flockfile'?
 1638 |     flockfile(f);
      |     ^~~~~~~~~
      |     _flockfile
/home/jordan/.conan2/p/b/fmtc75dbc04c5faa/b/src/include/fmt/format-inl.h: In destructor 'fmt::v11::detail::file_print_buffer::~file_print_buffer()':
/home/jordan/.conan2/p/b/fmtc75dbc04c5faa/b/src/include/fmt/format-inl.h:1646:5: error: 'funlockfile' was not declared in this scope; did you mean '_funlockfile'?
 1646 |     funlockfile(file_);
      |     ^~~~~~~~~~~
      |     _funlockfile
```

**Comment by xiyoo0812** [comment]
Similarly, it is not possible to build on PS4 and PS5

**Comment by vitaut** [comment]
Added `flockfile` detection in https://github.com/fmtlib/fmt/commit/486838f26fd1192de9bc1bd9caa09896470118a2. Note that providing `flockfile`/`funlockfile` is a better solution especially on platforms targeted by these C library implementations because it prevents dynamic memory allocations in the common case.

**Comment by vitaut** [comment]
@glebm could you verify that it fixes the problem on Amiga?

**Comment by glebm** [comment]
@vitaut The build is still failing but now the errors are different

* Amiga: https://github.com/diasurgical/devilutionX/actions/runs/9846219340/job/27183525051?pr=7181
* Xbox: https://github.com/diasurgical/devilutionX/actions/runs/9846219369/job/27183524301?pr=7181

**Comment by vitaut** [comment]
A more complete fix: https://github.com/fmtlib/fmt/commit/92227c77a4eed4c12f97f7916041ace4d5ca02d4.

**Comment by glebm** [comment]
All builds are now green! Thank you for the fix!
