### ISSUE TITLE
Incomplete support for nested replacement fields

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#406]
[Format String Syntax](http://fmtlib.net/latest/syntax.html) says:
`A format_spec field can also include nested replacement fields within it. These nested replacement fields can contain only an argument index; format specifications are not allowed. `

I expect that 'can also include' means 'can also include _anywhere_', same as in Python. However, let's try to dynamically specify a fill character:

`auto str = fmt::format(L"{0:{1}^10}", L"foo", L'-');`

Expected: '---foo----'
Actual: "width is not integer" exception.

Looking at the code, nested replacement fields are actually supported only for with and precision specifiers.

Also, "These nested replacement fields can contain only an argument index" sentence above isn't quite correct, as they can also contain named arguments.

**Comment by vitaut** [comment]
For efficiency nested replacement fields are not allowed anywhere, only in width and precision, similarly to `printf`. See the exact grammar here: http://fmtlib.net/latest/syntax.html#grammar-token-width.

The new documentation uses slightly better language:

> A *format_spec* field can also include nested replacement fields in certain
positions within it.

I've changed "index" to "id" in "These nested replacement fields can contain only an argument index".

Thanks!

**Comment by alabuzhev** [comment]
I'm not arguing that efficiency is important, but in case of fill you're [already checking](https://github.com/fmtlib/fmt/blob/8f455c1/fmt/format.h#L3640) for '{' there:

            if (c == '{')
              FMT_THROW(FormatError("invalid fill character '{'"));

- so if you add replacement field handling instead of throwing it will cost you _nothing_, wouldn't it?

And align, sign, type and int_type are handled via switch. Presuming that compiler will generate jump tables (as those switches are very small), adding one more case shouldn't cost you anything as well from the performance perspective.

**Comment by vitaut** [comment]
Good point. I am open to a PR that adds support for this functionality provided that it is supported by benchmark results that show that there is no significant performance regression for non-dynamic format strings (existing benchmarks can be used).
