### ISSUE TITLE
https://fmt.dev/latest/api.html in error message is a 404

### ISSUE THREAD

**Issue by madeso** [fmtlib/fmt#4073]
https://godbolt.org/z/EhM6b7Gf5

clang:
> fmt/base.h:1644:7: error: static assertion failed due to requirement 'formattable': Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt

gcc:
> fmt/base.h:1644:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt

https://github.com/fmtlib/fmt/blob/master/include/fmt/base.h#L1646

edit: update to use fmt trunk

**Comment by vitaut** [comment]
The URL is working now, thanks for reporting.
