### ISSUE TITLE
Formatting `year_month_day` does not work on clang 18.1.0 or earlier, on GCC 13.3 and earlier

### ISSUE THREAD

**Issue by remyjette** [fmtlib/fmt#4074]
With clang, formatting `year_month_day` only compiles in Compiler Explorer on trunk. 18.1.0 and earlier do not compile.
If I switch to `-stdlib=libc++`, it doesn't compile on trunk either.

With GCC, formatting `year_month_day` only compiles in Compiler Explorer on 14.1 or trunk. 13.3 and earlier do not compile.

https://godbolt.org/z/3ahfo1eKd

Given that the `year_month_day` type itself is available and fmt supports these compilers I would love to see support.

**Comment by vitaut** [comment]
We check `__cpp_lib_chrono` which is technically correct but a PR to enable the use of these chrono types more widely would be welcome.

**Comment by vitaut** [comment]
Closing as there doesn't seem to be much interest in this but a PR would still be welcome.
