### ISSUE TITLE
Cannot compile any date formatter for std::chrono::seconds

### ISSUE THREAD

**Issue by AJIOB** [fmtlib/fmt#4075]
I cannot compile any of `%F`, `%H`, `%m` & `%d` formatters for `std::chrono::seconds` type neither in clang nor in gcc.

OS: Linux
GCC: 8.3.0, 14.1, trunk
CLang: 18.1, trunk
C++: 17, 20
fmtlib: 10.2.1, trunk

[Reproducible example on godbolt](https://godbolt.org/z/c9s81Gq15)

It's possibly related to #4074, but this one also isn't compiled on gcc 14.1 & clang 18.1

**Comment by AJIOB** [comment]
@vitaut, please, provide more user-friendly message for this case, such as, `Specifiers that have a calendaric component such as 'd' (the day of month) are valid only for std::tm and time points but not durations`

**Comment by AJIOB** [comment]
Also, just for your note, `std::chrono::time_point` doesn't always work: https://godbolt.org/z/9s1fsWP19

It works for `std::chrono::time_point<std::chrono::system_clock>`, but not for `std::chrono::time_point<std::chrono::seconds>`.

That's not clear.

P.S. if you need, I can post it as a dedicated issue

**Comment by vitaut** [comment]
Similarly to `std::format`, {fmt} provides formatters for standard clocks such as `std::chrono::system_clock`. I don't think `std::chrono::time_point<std::chrono:: seconds >` even makes sense because the first argument should be a clock, not a duration.
