### ISSUE TITLE
How toi format to std::pmr::string

### ISSUE THREAD

**Issue by tksuoran** [fmtlib/fmt#4076]
What would be a smarter way to do the following?
```C++
std::pmr::string foo = std::pmr::string{fmt::format(...)};
```
Thanks!

**Comment by vitaut** [comment]
You can use `format_to` to format into `std::pmr::string` directly and, if needed, wrap it in a function.

**Comment by microcai** [comment]
> You can use `format_to` to format into `std::pmr::string` directly and, if needed, wrap it in a function.

any examples?

**Comment by vitaut** [comment]
> any examples?

Take a look at https://fmt.dev/11.0/api/#custom-allocators.
