### ISSUE TITLE
11.0.1 Compile error with no OS

### ISSUE THREAD

**Issue by mike919192** [fmtlib/fmt#4078]
Hi, I am currently successfully using fmt 10.2.1 on an embedded project with no operating system.  I tried to upgrade to 11.0.1 and I get this compile error.

```
In file included from XXX\include/fmt/format.h:4409,
                 from XXX\include/fmt/base.h:3059,
XXX\include/fmt/format-inl.h: In constructor 'fmt::v11::detail::file_print_buffer::file_print_buffer(FILE*)':
XXX\include/fmt/format-inl.h:1638:5: error: 'flockfile' was not declared in this scope; did you mean '_flockfile'?
 1638 |     flockfile(f);
      |     ^~~~~~~~~
      |     _flockfile
XXX\include/fmt/format-inl.h: In destructor 'fmt::v11::detail::file_print_buffer::~file_print_buffer()':
XXX\include/fmt/format-inl.h:1646:5: error: 'funlockfile' was not declared in this scope; did you mean '_funlockfile'?
 1646 |     funlockfile(file_);
      |     ^~~~~~~~~~~
      |     _funlockfile
```

I can't say for sure but this seems related to no operating system, because I have no files :)

Some more details:

- Using -DFMT_HEADER_ONLY and -fno-exceptions
- Compiler is gcc 12.2 gcc-arm-none-eabi

Let me know if there is any more information I can provide.

**Comment by vitaut** [comment]
Essentially the same as #4054 (already fixed).

**Comment by mike919192** [comment]
I tried again to compile using head of master and I also confirm the fix works for me.  Thanks
