### ISSUE TITLE
Consider being "Wzero-as-null-pointer-constant"-clean

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#408]
gcc 4.7 added a new command-line option `-Wzero-as-null-pointer-constant` to warn when a literal '0' is used as null pointer constant, which is useful to catch subtle errors as early as possible.

If this diagnostic is enabled project-wide, fmt produces a gazillion warnings because of things like `Char *start = 0;` in templates in the format.h. And since templates are instantiated in the user code, it's impossible to suppress this warning for fmt headers only.

Either nullptr or NULL should make gcc happy.
`#define nullptr NULL` is perfectly fine for pre-C++11 compilers.

**Comment by vitaut** [comment]
Using `NULL` sounds reasonable. Would you be willing to submit a PR?
