### ISSUE TITLE
microseconds formatting requires unicode

### ISSUE THREAD

**Issue by odygrd** [fmtlib/fmt#4088]
https://github.com/fmtlib/fmt/blob/ffdc3fdbd90385429dd2ea6a774848e39d4f957a/include/fmt/chrono.h#L652

is displayed as `┬Ás ` on some terminals, would it be possible to change it to `us` ?

**Comment by Anm01Chandel** [comment]
so, you want to change output to "us" if it can't return "µs"

**Comment by odygrd** [comment]
it can always return `us` for simplicity. 
Another solution would be if `FMT_UNICODE == 0` then it should return `us`

**Comment by Anm01Chandel** [comment]
changing code to code below shouls work
 if (std::is_same<Period, std::micro>::value) return "us";

**Comment by odygrd** [comment]
Yes, it works. My request is to consider changing it in future versions of the library

**Comment by vitaut** [comment]
Switched to "us" when Unicode is disabled: https://github.com/fmtlib/fmt/commit/1db227496677bdddabc21cadaee63a1923bf3a3d.
