### ISSUE TITLE
std::iterator_traits specialisation for fmt::appender breaks std::output_iterator concept

### ISSUE THREAD

**Issue by teemu-torma** [fmtlib/fmt#4092]
`fmt::basic_appender<char>` does not match libstdc++ `std::output_iterator` concept, because `std::iterator_traits<fmt::appender>` does not match incrementable iterator concept. 

Either removing the `std::iterator_traits` specialisation, or adding `difference_type` to it fixes the problem.

The specialisation was added in version 11.0.2

**Comment by vitaut** [comment]
We should add `difference_type`. A PR would be welcome.

**Comment by phprus** [comment]
PR #4093
