### ISSUE TITLE
Wide char to UTF-8 conversion drops surrogate pairs

### ISSUE THREAD

**Issue by ptc-tgamper** [fmtlib/fmt#4094]
The convert function,
https://github.com/fmtlib/fmt/blob/6e462b89aa22fd5f737ed162d0150e145ccb1914/include/fmt/format.h#L1409 decodes the surrogate pair, https://github.com/fmtlib/fmt/blob/6e462b89aa22fd5f737ed162d0150e145ccb1914/include/fmt/format.h#L1422 but does not write the resulting unicode character to the output buffer.

Walked into this when printing a std::filesystem::path on Windows, that uses smiley characters, such as 😀. The character is simply dropped.

**Comment by phprus** [comment]
Fix: #4095
