### ISSUE TITLE
Perfect forwarding that works with both normal and compiled format strings

### ISSUE THREAD

**Issue by 0xjc** [fmtlib/fmt#4097]
Godbolt: https://godbolt.org/z/TjdEc74EP

I would like to replicate the interface of functions such as `fmt::print` or `fmt::format_to_n` via perfect forwarding, in a way that works with both normal and compiled format strings.

The only way I have found to be able to replicate the SFINAE of checking for `fmt::compiled_string` as in my `write3` example. However, it requires writing a bunch of template boilerplate, and more importantly requires me to duplicate whatever else I want to do in my function.

Is there any better way I can do this?

**Comment by vitaut** [comment]
I don't think there is a way around having two overloads but you could probably move your common code into a separate function and reuse.
