### ISSUE TITLE
has_format_as doesn't work when enum is encapsulated within a templated class.

### ISSUE THREAD

**Issue by another-pjohnson** [fmtlib/fmt#4101]
It's not possible to use a templated function for `format_as` for enum -> int conversion.

See Compiler Explorer repro: https://godbolt.org/z/ha3GWq5s6

**Comment by vitaut** [comment]
I'm afraid that's just how C++ works. In your example

```c++
format_as(t_class<char>::VALUE_ONE);
```
doesn't compile and therefore `has_format_as` correctly returns `false`.

**Comment by vitaut** [comment]
BTW you can fix it by making `format_as` a non-template friend function.
