### ISSUE TITLE
ambiguous overload of `count_digits()` on xtensa esp32s3 gcc 12.2.0 (20230208)

### ISSUE THREAD

**Issue by m-mcgowan** [fmtlib/fmt#4109]
[godbolt repro](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:5,positionColumn:2,positionLineNumber:5,selectionStartColumn:2,selectionStartLineNumber:5,startColumn:2,startLineNumber:5),source:'%23include+%3Cfmt/core.h%3E%0A%0Aint+main()+%7B%0A++fmt::print(%22Don!'t+panic!!%5Cn%22)%3B%0A%7D'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:esp32s3g20230208,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:fmt,ver:trunk)),options:'-O2',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+Xtensa+ESP32-S3+gcc+12.2.0+(20230208)+(Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

```
In file included from /opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h:5,
                 from <source>:1:
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h: In function 'constexpr OutputIt fmt::v11::detail::write_exponent(int, OutputIt)':
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:1608:56: error: call of overloaded 'count_digits(unsigned int&)' is ambiguous
 1608 |     return format_decimal<Char>(out, uexp, count_digits(uexp));
      |                                            ~~~~~~~~~~~~^~~~~~
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:1183:29: note: candidate: 'int fmt::v11::detail::count_digits(uint64_t)'
 1183 | FMT_CONSTEXPR20 inline auto count_digits(uint64_t n) -> int {
      |                             ^~~~~~~~~~~~
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:1233:29: note: candidate: 'int fmt::v11::detail::count_digits(uint32_t)'
 1233 | FMT_CONSTEXPR20 inline auto count_digits(uint32_t n) -> int {
      |                             ^~~~~~~~~~~~
Compiler returned: 1
```

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/98314319ad756cfd9cb83ca5d68692a4a47e3beb. Thanks for reporting!

**Comment by m-mcgowan** [comment]
Thank you for the fix! I looked at the code, but couldn't grasp it well enough to suggest a fix.
