### ISSUE TITLE
wstring formatting issue

### ISSUE THREAD

**Issue by hsdk123** [fmtlib/fmt#4112]
Hi, I don't seem to be able to use a custom type to format to a wstring.
Ex. https://godbolt.org/z/dPb9Mcj8f

May I request some help

**Comment by Dani-Hub** [comment]
What's the purpose of calling `fmt::underlying` given that `std::wstring` is not an enumeration type?

**Comment by vitaut** [comment]
Yeah, `fmt::underlying` doesn't belong there and if you remove it the error goes away.
