### ISSUE TITLE
Using back_inserter without the std:: prefix

### ISSUE THREAD

**Issue by thraneh** [fmtlib/fmt#4113]
I have a custom container with appropriate iterators, `push_back` method, etc. This used to work up until fmt 10.0.2

I haven't yet been able to set up a minimal example to reproduce this.

However, the issue arise from this line where `back_inserter` is used without the `std::` prefix (maybe you wanted to use your own `invoke_back_inserter`?)

* https://github.com/fmtlib/fmt/blob/9f0c0c468be45357d85efc1788b7561fafbdebb1/include/fmt/base.h#L1098

The issue was seen when compiling C++23

GCC 14.1.0 (Linux)
```
.../opt/conda/envs/dev/include/fmt/base.h:1089:48: error: 'back_inserter' was not declared in this scope; did you mean 'std::back_inserter'?
 1089 |   auto out() -> OutputIt { return back_inserter(container_); }
      |                                   ~~~~~~~~~~~~~^~~~~~~~~~~~
      |                                   std::back_inserter
```

Clang 18.1.8 (MacOS)
```
.../opt/conda/envs/dev/include/fmt/base.h:1089:35: error: use of undeclared identifier 'back_inserter'
 1089 |   auto out() -> OutputIt { return back_inserter(container_); }
      |
```

I can work around this by defining `back_inserter` in the global namespace before including any of the fmt headers.

**Comment by vitaut** [comment]
I think we could add `using namespace std;` just before calling `back_inserter` which would handle both ADL and `std::back_inserter` case. Could you submit a PR?

**Comment by thraneh** [comment]
I could submit a PR for that small change, but I'm lacking enough detailed knowledge about your library.

Clearly, you have a reason for preferring `using namespace std;` / `back_inserter` to simply using `std::back_inserter`.

In `base.h` there's a `namespace adl` which has `invoke_back_inserter` and otherwise does something similar to what you just suggested.

My problem is that an isolated PR with this small change just doesn't seem right. You have some idea behind the "adl" that I'm not familiar with.

**Comment by vitaut** [comment]
`invoke_back_inserter` is irrelevant here but in any case this is fixed in https://github.com/fmtlib/fmt/commit/bf870ae3d15c576bdb78e5c0ce1106fab9f0275a in a slightly simpler way.
