### ISSUE TITLE
Docs for chrono type `S` decimal point locale does not match code

### ISSUE THREAD

**Issue by tearfur** [fmtlib/fmt#4117]
The decimal point character for the chrono type `'S'` seems to be locale-independent, contrary to what the docs says. Reproduced at https://godbolt.org/z/TKxcq5hf6.

From the docs:

> The character for the decimal point is localized according to the locale. The modified command %OS produces the locale's alternative representation.

Relevant code (I think):

https://github.com/fmtlib/fmt/blob/3135421257e71f456a4d745313d0be798354f34f/include/fmt/chrono.h#L1148

https://github.com/fmtlib/fmt/blob/3135421257e71f456a4d745313d0be798354f34f/include/fmt/chrono.h#L1153

https://github.com/fmtlib/fmt/blob/3135421257e71f456a4d745313d0be798354f34f/include/fmt/chrono.h#L1195

**Comment by tearfur** [comment]
I wonder if I missed something, `std::format` behaves the same way too... https://godbolt.org/z/Ynd7P4ETM

**Comment by vitaut** [comment]
`%S` is locale-independent by default. We should update the docs.

**Comment by tearfur** [comment]
Relevant material: https://wg21.link/P2372R3

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/589898e28bb2f7f3ea19868c081ce9a3b5636fef. Thanks for reporting.
