### ISSUE TITLE
Visual Studio update breaks is_utf8_enabled()

### ISSUE THREAD

**Issue by emveepee** [fmtlib/fmt#4119]
I just updated to the latest VS 2022 and had tons of fmt warning which were removed when I updated to 11.0.2 and it reduced it to one that is repeating which might relate to https://github.com/fmtlib/fmt/pull/2297   The compiler shows the assert message "Unicode support requires compiling with /utf-8"  but it doesn't matter if /utf-8 is added or not.  

For now I am just returning true from is_utf8_enabled in base.h and haven't noticed anything.  Is this a known issue or did the compiler fix get released change PR 2297?

**Comment by vitaut** [comment]
Please provide a repro, ideally on godbolt.

**Comment by emveepee** [comment]
> I was not able to repro this issue on MSVC 2022 (v19.30): https://www.godbolt.org/z/fo4aKMao7. Most likely the problem is in your build config, make sure that `/utf-8` is correctly passed to the compiler.

Yes sorry that was it I didn't pass /utf-8 in both debug and release.  Sorry to bother you.

**Comment by vitaut** [comment]
No worries, glad the issue has been resolved.
