### ISSUE TITLE
fmtlog fails a test with fmtlib 11+

### ISSUE THREAD

**Issue by Arniiiii** [fmtlib/fmt#4120]
Hello. I'm just a guy that wanted to use fmtlog .

I've updated cmake for it long ago.

But now I wanted to update it a little bit more: make it use latest fmtlib to extent to be usable, but with as less changes to code as possible.

First of all I've changed fmtlib to current latest version.
Then I got that `fmt::detail::throw_format_error` now is `fmt::throw_format_error` . Just fixed.

Then I've build tests. 

And now I have a test fails to compile. It seems to be a const issue.

Here's godbolt with selected code with the problem: https://godbolt.org/z/YYbTMM7hT

It fails with versions of fmtlib greater or equal 11.0.0

My attempt to make fmtlog usable from cmake: https://github.com/Arniiiii/fmtlog_cmake_fix , test is enc_dec_test.cc

The question: how should it be solved?

**Comment by mwinterb** [comment]
This formatter's format function will need to be const, which is compatible with 10.2.1:
https://github.com/MengRao/fmtlog/blob/acd521b1a64480354136a745c511358da1ec7dc5/test/enc_dec_test.cc#L46

See: https://github.com/fmtlib/fmt/issues/3447

**Comment by Arniiiii** [comment]
> This formatter's format function will need to be const, which is compatible with 10.2.1: https://github.com/MengRao/fmtlog/blob/acd521b1a64480354136a745c511358da1ec7dc5/test/enc_dec_test.cc#L46
> 
> See: #3447

Yep, you are right, making the method const, seems to work. Thanks.
