### ISSUE TITLE
What's the required minimum gcc version?

### ISSUE THREAD

**Issue by byplusone** [fmtlib/fmt#4121]
I tried to build with devtoolset-7, which has gcc version: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5), but it came with the compiling error:
```
.../fmt/base.h:2024:66: internal compiler error: unexpected expression ‘count_named_args<const char [12], std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, const char [21]>’ of kind template_id_expr
           size_t NUM_NAMED_ARGS = detail::count_named_args<T...>(),
```

**Comment by vitaut** [comment]
Minimum version is 4.8 (https://fmt.dev/11.0/) but it looks like your version of gcc has a compiler bug.

**Comment by zRegle** [comment]
@byplusone same problem, how did u fix this?
