### ISSUE TITLE
About the -Wstringop-overflow= issues

### ISSUE THREAD

**Issue by nunojpg** [fmtlib/fmt#4133]
I've opened this GCC bug for the case where FMT_SYSTEM_HEADERS workaround doesn't work.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116515

It appears when using LTO the warnings happen at link system and GCC doesn't respect isystem at link time.

**Comment by sunmy2019** [comment]
related issue: https://github.com/fmtlib/fmt/issues/4125

**Comment by vitaut** [comment]
Thanks for the information. All the known cases of `-Wstringop-overflow=` warnings (false positives) have been fixed but if you see more please provide a repro.

**Comment by nunojpg** [comment]
This one from master:

`fmt/include
In function 'copy',
    inlined from 'for_each_codepoint' at fmt/include/fmt/format.h:682:13,
    inlined from 'find_escape' at fmt/include/fmt/format.h:1852:21,
    inlined from 'write_escaped_string' at fmt/include/fmt/format.h:1944:30,
    inlined from 'write_escaped_path' at fmt/include/fmt/std.h:105:60,
    inlined from 'format' at fmt/include/fmt/std.h:157:31:
fmt/include/fmt/base.h:1220:31: warning: writing 8 bytes into a region of size 7 [-Wstringop-overflow=]
 1220 |   while (begin != end) *out++ = static_cast<T>(*begin++);
      |    
...`

**Comment by vitaut** [comment]
Please provide a godbolt repro.

**Comment by nunojpg** [comment]
https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:12,positionColumn:2,positionLineNumber:12,selectionStartColumn:2,selectionStartLineNumber:12,startColumn:2,startLineNumber:12),source:'%23define+FMT_HEADER_ONLY%0A%0A%23include+%3Cfilesystem%3E%0A%0A%23include+%3Cfmt/std.h%3E%0A%0Aint+main(int,+char+**argv)%0A%7B%0A++++std::filesystem::path+p%7Bargv%5B0%5D%7D%3B%0A++++fmt::print(%22%7B%7D%22,+p)%3B%0A++++return+0%3B%0A%7D'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:50.82881548529258,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:g142,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:fmt,ver:trunk)),options:'-Wextra+-O3+-DNDEBUG+-flto%3Dauto',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+14.2+(Editor+%231)',t:'0')),header:(),k:49.17118451470742,l:'4',m:70.64451158106748,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+(trunk)',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+14.2+(Compiler+%231)',t:'0')),header:(),l:'4',m:29.35548841893253,n:'0',o:'',s:0,t:'0')),k:49.17118451470742,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

**Comment by vitaut** [comment]
Thanks, reopening.

**Comment by vitaut** [comment]
Worked around in https://github.com/fmtlib/fmt/commit/a16ff5787b104945f735b1a2250b85c441a1af8e (ignore the commit message - it was accidentally messed up 🤦).
