### ISSUE TITLE
Multiple {} for one object?

### ISSUE THREAD

**Issue by nuuSolutions** [fmtlib/fmt#4136]
```
println( "{}{}{}", 1, 2, 3 );                        // valid
println( "{}", std::tuple(1, 'b', 1.0/3.0) );        // valid
println( "{.2f}", std::tuple(1, 'b', 1.0/3.0) );     // error

// what I'd like and what an average user would expect to work
println( "{} {} {.2f}", std::tuple(1, 'b', 1.0/3.0) );
```
Question 1: can I let my own tuple-like type consume multiple {}s
Question 2: why is std::tuple only taking one {}

**Comment by nuuSolutions** [comment]
I still wonder why the design choice was single {} for one tuple
rather than n {}s

**Comment by vitaut** [comment]
{fmt} is modeled after Python's format which made this design choice. But even putting Python aside, autodestructuring would be extremely confusing with multiple arguments.
