### ISSUE TITLE
Cant add a formatter to a custom c++11 string_view

### ISSUE THREAD

**Issue by AnonimiAngels** [fmtlib/fmt#4146]
Here is a minimal reproducible code
https://godbolt.org/z/KKW7xTY6v

**Comment by mwinterb** [comment]
Your `format` function needs to be `const` and it needs to return `FormatContext::iterator`, not `std::string`.
https://fmt.dev/dev/api/#formatting-user-defined-types
https://godbolt.org/z/Pjvjnfzo7
