### ISSUE TITLE
Broken fmt::is_formattable<void>

### ISSUE THREAD

**Issue by phprus** [fmtlib/fmt#4147]
Expect:
```
fmt::is_formattable<void>::value == false
```

Actual (build error):
```
In file included from /opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:41,
                 from <source>:1:
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/base.h: In substitution of 'template<class T, class Char> using is_formattable = fmt::v11::bool_constant<(! std::is_base_of<fmt::v11::detail::unformattable, decltype (fmt::v11::detail::arg_mapper<Char>::map(declval<T&>()))>::value)> [with T = void; Char = char]':
<source>:6:44:   required from here
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/base.h:1269:73: error: forming reference to void
 1269 | using mapped_t = decltype(detail::arg_mapper<Char>::map(std::declval<T&>()));
      |                                                         ~~~~~~~~~~~~~~~~^~
Execution build compiler returned: 1

```

godbolt (new link):
https://godbolt.org/z/xro8619b4

**Comment by vitaut** [comment]
I think it's fine for `is_formattable` to give a compile-time error for `void` because it's not something that can be passed as an argument to a formatting function.

**Comment by phprus** [comment]
But a compile-time error breaks a possible ``enable_if`` condition like ``std::is_void<T>::value || is_formattable<T, Char>::value``.
See: #4148

**Comment by Dani-Hub** [comment]
> But a compile-time error breaks a possible `enable_if` condition like `std::is_void<T>::value || is_formattable<T, Char>::value`. See: #4148

A possible workaround in this situation is to replace the `||` by `disjunction_v` (Untested - that assumes that `is_formattable` is suitable as such a predicate).

**Comment by phprus** [comment]
> A possible workaround in this situation is to replace the `||` by `disjunction_v` (Untested - that assumes that `is_formattable` is suitable as such a predicate).

No, this is not working
https://godbolt.org/z/jvqja873h

**Comment by vitaut** [comment]
Thinking more of it, other traits do work with `void` so let's make `is_formattable` work with it too.

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/3df47a467717580aeaa01a4c8e3963939bf343f0. Thanks for the suggestion.

**Comment by vitaut** [comment]
> What about using std::is_void instead of std::is_same<void, ...>? This would also work for cv void.

A PR would be welcome.

**Comment by phprus** [comment]
> A PR would be welcome.

I made this change in a separate commit in PR #4148
