### ISSUE TITLE
Implementation of pointer formatting

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#415]
`fmt::format("{0}", (void*)1);`
`0x1`

`printf("%p", (void*)1);`
MSVC: `0000000000000001`
gcc: `0x1`

Standard says that pointer conversion is implementation-defined, so both printf results are perfectly valid.
And it looks like fmt follows gcc approach which is perfectly valid too, but not so useful: usually pointers are printed for some debugging purposes like memory dump, traceback etc., using some table-based layout, which implies alignment for readability.

From the fmt perspective pointer is not even a numeric type, so something like `"{0:016}"` will throw "format specifier 0 requires numeric argument", so I have to do something like
`format(L"0x{0:0{1}X}", reinterpret_cast<uintptr_t>(ptr), sizeof(void*) * 2);` to get something useful, which works, but looks unnecessarily verbose.

So, is it a deliberate choice to follow gcc approach?

**Comment by vitaut** [comment]
The choice of the default pointer format is more or less arbitrary (I personally prefer gcc's because it produces less noise), but I agree that it should be possible to control formatting without a cast. It can be implemented in the same way as enabling integer format specifiers for `bool`: https://github.com/fmtlib/fmt/commit/9d09214e7aefdf2daf529a91632488d17933811e.

**Comment by alabuzhev** [comment]
Cast seems to be inevitable for typed pointers anyway, as only void* is acceptable.

**Comment by vitaut** [comment]
Yes, cast to `void*` is required right now, but that's a separate question.

BTW you can have custom pointer formatting right now with a simple wrapper type:

```c++
#include "fmt/ostream.h"

class ptr {
 private:
  const void *p_;
 public:
  ptr(const void *p) : p_(p) {}

  friend std::ostream &operator<<(std::ostream &os, ptr p) {
    return os << p.p_; // change formatting here
  }
};

int main() {
  fmt::print("{}", ptr((void*)1));
}
```

**Comment by vitaut** [comment]
The `std` branch now provides the `ptr` method to simplify pointer formatting:

```c++
fmt::format("{}", fmt::ptr(p));
```
Similar method can be used to implement non-default pointer formatting.
