### ISSUE TITLE
Crash when using fmt with gcc to print chinese character

### ISSUE THREAD

**Issue by WennerChen** [fmtlib/fmt#4162]
I want to print chinese character with fmt::print. Here is my code.

```cpp
#define FMT_HEADER_ONLY
#include <fmt/printf.h>
int main() {
    fmt::print(" 我喜欢fmt \n");
    fmt::print("I like fmt\n");
    while (1) {
        // do nothing
    }
    return 0;
}
```

My toolchain is mingw-w64 + gcc8.5.0, and my source file is saved as utf-8. When built with options -finput-charset=utf-8 -fexec-charset=gb2312, the generated exe prints nothing but just exits. 

FMT-11.0.2 and FMT-10.2.1 are both tested, and the results are same.

**Comment by vitaut** [comment]
GCC doesn't have `-finput-character` and `-fexec-character`. Did you mean `-finput-charset` and `-fexec-charset`?

**Comment by WennerChen** [comment]
> GCC doesn't have `-finput-character` and `-fexec-character`. Did you mean `-finput-charset` and `-fexec-charset`?

Yes. Sorry about that.

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/b329ff194ff2defafaf7c61ca63a0eebc5d8bcb5 but note that using legacy encoding is not recommended.
