### ISSUE TITLE
compiler warning [-Wstringop-overflow=] when formatting compiled format strings with styled args

### ISSUE THREAD

**Issue by moshelooks** [fmtlib/fmt#4165]
I was working on a PR to add color support for compiled format strings when I hit an issue with the existing code (`master`) that I'm not sure how to handle. https://github.com/moshelooks/fmt adds a test that illustrates this:

```
fmt::format(FMT_COMPILE("x{}"), fmt::styled("foo", fmt::text_style()));
```

Gives warning like:

```
include/fmt/base.h:1981:31: warning: writing 8 bytes into a region of size 7 [-Wstringop-overflow=]
``` 

Full `make` output (Fedora, `g++ (GCC) 14.2.1 20240801 (Red Hat 14.2.1-1)`): [warnings.txt](https://github.com/user-attachments/files/17050060/warnings.txt). Thank you!

**Comment by vitaut** [comment]
Same as #4133.
