### ISSUE TITLE
/utf-8 in nvcc + msvc

### ISSUE THREAD

**Issue by DWin233** [fmtlib/fmt#4167]
Sorry to interrupt.
I used fmt::format(...) for the host function in the .cu file, which should theoretically be compiled by the host compiler (i.e. msvc), and I also passed the /utf-8 flag via -Xcompiler. 
But I'm still getting this error output. `error: static assertion failed with "Unicode support requires compiling with /utf-8"`
How do I fix this?
Here is an example. 
```
// main.cu 
// utf-8
#include <fmt/core.h>
int main() { fmt::print("{} in cuda.\n", 42); }
```
And here is the command and the output.
```
(base) PS D:\Code\Mycode\code_demo_test\cuda>  &"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin\nvcc.exe" `
>> --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64"`
>> -x cu -rdc=true  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -I"C:\dev\vcpkg\installed\x64-windows\include" `
>>  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include"  -G   --keep-dir test_code_cuda1\x64\Debug  -maxrregcount=0  --machine 64 `
>> --compile -cudart shared --std=c++20  --expt-relaxed-constexpr -g  -DFMT_HEADER_ONLY -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE `
>>  -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MDd " -Xcompiler "/Fdtest_code_cuda1\x64\Debug\vc143.pdb" `
>> -o D:\Code\Mycode\code_demo_test\cuda\test_code_cuda1\x64\Debug\main.cu.obj "D:\Code\Mycode\code_demo_test\cuda\src\main.cu" -Xcompiler "/utf-8"
main.cu
C:\dev\vcpkg\installed\x64-windows\include\fmt\base.h(458): error: static assertion failed with "Unicode support requires compiling with /utf-8"
  static_assert(!1 || use_utf8(),
  ^

C:\dev\vcpkg\installed\x64-windows\include\fmt\format.h(3222): warning #27-D: character value is out of range
    return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
             ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\dev\vcpkg\installed\x64-windows\include\fmt\format.h(3222): warning #27-D: character value is out of range
    return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
                       ^

C:\dev\vcpkg\installed\x64-windows\include\fmt\format.h(3222): warning #27-D: character value is out of range
    return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
                                 ^

C:\dev\vcpkg\installed\x64-windows\include\fmt\format.h(3222): warning #27-D: character value is out of range
    return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
                                           ^

C:\dev\vcpkg\installed\x64-windows\include\fmt\format.h(3222): warning #27-D: character value is out of range
    return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
                                                     ^

C:\dev\vcpkg\installed\x64-windows\include\fmt\format.h(3222): warning #27-D: character value is out of range
    return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
                                                               ^

C:\dev\vcpkg\installed\x64-windows\include\fmt\format.h(3223): warning #27-D: character value is out of range
           U"\x800001ae\x8000002b"[index];
             ^

C:\dev\vcpkg\installed\x64-windows\include\fmt\format.h(3223): warning #27-D: character value is out of range
           U"\x800001ae\x8000002b"[index];
                       ^

1 error detected in the compilation of "D:/Code/Mycode/code_demo_test/cuda/src/main.cu".
```

**Comment by vitaut** [comment]
You'll need to check your compiler documentation how to set the literal (execution) encoding to UTF-8. As a potential workaround you could try

```
#pragma execution_character_set("utf-8")
```

**Comment by lorenzoedoardofrancesco** [comment]
I have the same problem. As a solution I patched the function with

```cpp
constexpr auto fractional_part_rounding_thresholds(int index) -> uint32_t {
  constexpr std::array<unsigned int, 8> arr = { 0x9999999a, 0x828f5c29, 0x80418938, 0x80068db9, 0x8000a7c6, 0x800010c7, 0x800001ae, 0x8000002b };
  return arr[index];
}
```

It works in C++17 and nvcc for CUDA 11.8

By the way, if I'm not wrong, since C++23 [you can permit static constexpr variables in constexpr functions](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2647r1.html) so maybe the code could be updated with a `__cplusplus` macro to use static constexpr arrays instead of string litteral, which can have a problem with some compilers.

**Comment by NBickford-NV** [comment]
Hi! Just wanted to bring this up again since I ran into it in one of my team's samples. There was a bug in NVCC where `is_utf8_enabled()` would incorrectly return 0; that's now fixed in NVCC 13.1, and the compiler flags required for UTF-8 are `-Xcompiler="/utf-8" -Xcudafe=--unicode_source_kind=UTF-8 -Xcicc=--unicode_source_kind=UTF-8`.

However, I think the Unicode string workaround for MSVC in `fractional_part_rounding_thresholds` is implementation-defined; the [C++ specification states](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/n4950.pdf) in § 5.13.5/[lex.string] (10.1):

> If a character lacks representation in the associated character encoding, then the string-literal is conditionally-supported and an implementation-defined code unit sequence is encoded.

In this case, each of the characters in fractional_part_rounding_thresholds lacks representation, since UTF-32 only goes up to U+10FFFF.

I can file a bug to see if NVIDIA can change the implementation-defined behavior and make cudafe pass through invalid UTF-32 characters unchanged and without an error, but in the meantime, maybe fmtlib could do something like this?

```cpp
#ifndef __CUDACC__
  return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
         U"\x800001ae\x8000002b"[index];
#else
  constexpr uint32_t thresholds[8] = {0x9999999au, 0x828f5c29u, 0x80418938u,
    0x80068db9, 0x8000a7c6u, 0x800010c7u, 0x800001aeu, 0x8000002bu};
  return thresholds[index];
#endif
```

Thanks!

**Comment by vitaut** [comment]
I am open to a PR to change the literal to an array but instead of conditional on CUDA it should be conditional on constant evaluation similarly to how static arrays are supported in other cases.

**Comment by Cazadorro** [comment]
I'm running into the same issue with 

```
"error: character value is out of range 
    return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
             ^" when setting the flags for CUDA to support utf8. 
```

What does "CUDA it should be conditional on constant evaluation" mean here? Do you mean checking for the C++23 feature?  Why not just not put the array outside? 

```
//pre C++23 does not allow static constexpr inside of constexpr functions
static constexpr uint32_t utf8_raw_thresholds[8] = {0x9999999au, 0x828f5c29u, 0x80418938u, 0x80068db9, 0x8000a7c6u, 0x800010c7u, 0x800001aeu, 0x8000002bu};
constexpr auto fractional_part_rounding_thresholds(int index) -> uint32_t {
    // For checking rounding thresholds.
    // The kth entry is chosen to be the smallest integer such that the
    // upper 32-bits of 10^(k+1) times it is strictly bigger than 5 * 10^k.
    // It is equal to ceil(2^31 + 2^32/10^(k + 1)).
    // These are stored in a string literal because we cannot have static arrays
    // in constexpr functions and non-static ones are poorly optimized.
        return utf8_raw_thresholds[index];
}

```

**Comment by Cazadorro** [comment]
Well disabling UNICODE straight up doesn't work and nor does `#pragma execution_character_set("utf-8")` so I'm submitting a PR for this anyway.
