### ISSUE TITLE
Optional support for default value for NULL string values

### ISSUE THREAD

**Issue by nick42** [fmtlib/fmt#417]
I don't know if this is of-interest, but...

I've written a local customization to allow a default value of "(null)" to be used when NULL string values are specified (in keeping with the default handling of such for CString on Windows). I did it was an optional #define to activate, such that it would have no performance/other impact in the "normal" usage case. The code probably isn't as clean as it could be, but I thought I'd post it, in case there is any interest in incorporating something similar into the main project, and/or anyone else finds it useful.

I'll attach the diff, generated from the local git repo, for reference.

[diff.txt](https://github.com/fmtlib/fmt/files/579863/diff.txt)

**Comment by vitaut** [comment]
Thanks for the diff. I'm not sure if it is worth including in the core library, but maybe someone will find it useful.
