### ISSUE TITLE
Breaking changes in 11.0.0

### ISSUE THREAD

**Issue by Yaraslaut** [fmtlib/fmt#4171]
fmt 11 broke the following usage  [godbolt](https://godbolt.org/z/3aY7c778d)

And code:
```
#include <fmt/core.h>
int main() 
{
    fmt::print("{comment} This is an advance option. Use with care! \n{comment}\n{}", 10, fmt::arg("comment", "#"));
    return 1;
}
```
With desired output 
```
# This is an advance option. Use with care! 
#
10
```

**Comment by vitaut** [comment]
Mixing manual and automatic indexing is intentionally disallowed but happened to "work" by accident in older versions of {fmt} due to a missing check (#3817).
