### ISSUE TITLE
Minimal supported library subset

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#418]
[Documentation](http://fmtlib.net/latest/usage.html) says that including format.h and format.cc should be enough, but format.cc also includes printf.h and printf.h includes ostream.h.
I've experimented a little, looks like #include "printf.h" in format.cc required only for explicit instantiations of PrintfFormatter for char and wchar_t.
Maybe it's possible to move them to printf.cc?
Do you have any plans to make format.h/cc self-contained?
If no - it's probably worth to update the docs.

**Comment by vitaut** [comment]
Good catch, there indeed should be `printf.cc` and `format.cc` shouldn't be including `printf.h`.
