### ISSUE TITLE
Am I holding memory_buffer wrong? Or: how to format from a memory_buffer?

### ISSUE THREAD

**Issue by jevinskie** [fmtlib/fmt#4193]
Is there any way other than digging into fmt::detail::copy to write/copy a memory_buffer to ctx.out()? Should I just format_to a std::string instead? I already have to pay for the copy in ehexdump that converts a memory_buffer from ehexdump_mb to a std::string. I’m almost certainly not getting SSO anyways due to minimum widths I enforce.

cringeworthy code is here: https://gist.github.com/jevinskie/cf3f34569a86bdab8395293f3cebe80b#file-ehexdump-hpp-L555

**Comment by vitaut** [comment]
You can use `std::copy` or we could move `fmt::detail::copy` to the public API.
