### ISSUE TITLE
Easy way to convert

### ISSUE THREAD

**Issue by WeleSS2** [fmtlib/fmt#4196]
IM using msvc and have terrible problems with spdlogs (They are based on fmt).

Im trying to add some custom arguments and parse string to fmt but i can't figure out how to convert it, it's getting incredibly annoying.

Basically i have

```
template <typename CharT, typename... Args>
    struct basicString : std::basic_format_string<CharT, Args...> {
        template <typename T>
        consteval basicString(const T& fmt, const std::source_location loc = std::source_location::current())
        : std::basic_format_string<CharT, Args...>{fmt}, loc{loc} {};
        
        std::source_location loc;
    };
        template <typename... Args>
    using cString = basicString<char, std::type_identity_t<Args>...>;
  ```

Which is supposed to get location and parse it later to log as arguments (spd solution with macro is from 15y ago...), then i need to translate it into fmt 
```
template <typename... Args>
static constexpr void cLogs::Debug(const cString<Args...> str, Args&&... args)
{
    //fString<Args...> fstr{str};
        
    if (spdlog::get_level() <= SPDLOG_LEVEL_DEBUG)
    {
        spdlog::debug(std::format(str), std::forward<Args>(args)...);
...
```

```
template <typename... Args>
inline void debug(format_string_t<Args...> fmt, Args &&...args) {
    default_logger_raw()->debug(fmt, std::forward<Args>(args)...);
}
```

```
template <typename... Args>
using format_string_t = fmt::format_string<Args...>;
```

Was looking through docs but solution which are there are giving const error (msvc changed 2y ago std::format so it need to be const), did anyone have any solution for that? To convert const char* aka std::string to fmt string? Or just to make fString based on fmt instead of std

**Comment by vitaut** [comment]
I am not 100% sure what you are asking but this part is definitely incorrect:

> spdlog::debug(std::format(str), std::forward<Args>(args)...);

because the call to `format` should take arguments and not just the format string.

You might want to check the docs at https://fmt.dev/11.0/api/#compile-time-checks and spdlog docs.
