### ISSUE TITLE
Exception formatting is undocumented

### ISSUE THREAD

**Issue by robinchrist** [fmtlib/fmt#4203]
Formatting for exceptions exists (e.g. via https://github.com/fmtlib/fmt/pull/3062 or https://github.com/fmtlib/fmt/pull/3076).
This is not documented (missing in the list at https://github.com/fmtlib/fmt/blob/cc2ba8f9ede4e5ae3262f43f3e4d07a22a9acdfc/doc/api.md#L491-L505).

Additionally, there seem to be different ways to format exceptions (without any specified and with `{:t}`), as can be seen from the tests:
https://github.com/fmtlib/fmt/blob/cc2ba8f9ede4e5ae3262f43f3e4d07a22a9acdfc/test/std-test.cc#L311-L318

This is undocumented in https://github.com/fmtlib/fmt/blob/cc2ba8f9ede4e5ae3262f43f3e4d07a22a9acdfc/doc/syntax.md. The only reference in the docs to `t` is `A horizontal-tab character.` for chrono

**Comment by vitaut** [comment]
Formatting of `std::exception` is still WIP/experimental and exact format string syntax is subject to change but I added it to the list in https://fmt.dev/dev/api/#standard-library-types-formatting.
