### ISSUE TITLE
fmt/include\fmt/format-inl.h:1417:3: error: cannot use 'try' with exceptions disabled

### ISSUE THREAD

**Issue by sergio-nsk** [fmtlib/fmt#4207]
Getting this error while compiling with LLVM clang++.exe on Windows, the exceptions are disabled `-fno-exceptions` and `-fms-compatibility` is not used: 
```
fmt/include\fmt/format-inl.h:1417:3: error: cannot use 'try' with exceptions disabled
 1417 |   FMT_TRY {
      |   ^
fmt/include\fmt\base.h:175:19: note: expanded from macro 'FMT_TRY'
  175 | #  define FMT_TRY try
      |  
```
Looks like relevant to #70 that does not seem to be properly/completely fixed.
The {fmt} version is [11.0.2](https://github.com/fmtlib/fmt/releases/tag/11.0.2).

**Comment by vitaut** [comment]
There is no `FMT_TRY` at that location in the current version and it's likely been fixed. If not please provide a godbolt repro.

**Comment by sergio-nsk** [comment]
@vitaut This is a bad joke! The last version https://github.com/fmtlib/fmt/blob/0c9fce2ffefecfdce794e1859584e25877b7b592/include/fmt/format-inl.h#L1417. The master https://github.com/fmtlib/fmt/blob/a16ff5787b104945f735b1a2250b85c441a1af8e/include/fmt/format-inl.h#L1426

**Comment by vitaut** [comment]
As I wrote "it's likely been fixed" so please provide a repro on the current master.

**Comment by sergio-nsk** [comment]
Bad kidding and unfriendly behavior again. "likely" must not be a reason of closing the issue until I confirm the fix.

**Comment by sergio-nsk** [comment]
The issue on 'master' persists:
```
fmt/include\fmt/format-inl.h:137:3: error: cannot use 'throw' with exceptions disabled
  137 |   throw format_error(message);
      |   ^
fmt/include\fmt/format-inl.h:1426:3: error: cannot use 'try' with exceptions disabled
 1426 |   FMT_TRY {
      |   ^
fmt/include\fmt\base.h:155:19: note: expanded from macro 'FMT_TRY'
  155 | #  define FMT_TRY try
      |                   ^
```

**Comment by sergio-nsk** [comment]
> If not please provide a godbolt repro.

I think @vitaut, the {fmt} author, should be aware of missing LLVM clang for Windows on Matt Godbolt's compiler explorer. The only option is MinGW clang that does not have {fmt} installed.
