### ISSUE TITLE
Ability to format with color and alignment

### ISSUE THREAD

**Issue by deadlocklogic** [fmtlib/fmt#4212]
I am trying to print a formatted colored output with alignment:
Like: `fmt::format("{:<10} {:<5}", fmt::format(fmt::fg(fmt::terminal_color::red), "test1"), "test2")`
Seems like the color code length is counted within the string, which is expected but not intended in my case.
I pretty much expect that using 2 nested format won't likely be the solution.
Is there a way to avoid the color code length from begin included?
Thanks.

**Comment by vitaut** [comment]
You'll have to first apply width and alignment and then the color, something like

```
fmt::format("{} {:<5}", fmt::format(fmt::fg(fmt::terminal_color::red), "{:<10}", "test1"), "test2")
```

**Comment by Richardk2n** [comment]
Using your example with `fmt::emphasis::underline` instead of color underlines the padded spaces. As the padding gets formatted as well. Correct me if I am wrong, but there is no workaround for that. Either the padding gets formatted or the formatting gets counted.
Would it be theoretically be possible to not count the formatting chars in the padding calculation?

**Comment by vitaut** [comment]
You could probably write your own formatter that skips ANSI escapes.

**Comment by Richardk2n** [comment]
Assuming I would understand how to write a custom formatter (which is honestly a little confusing), this is likely possible. What I was wondering is why this is not the default or at least an option. Aside from highly technical reasons (buffers of limited size) from my perspective, there is not a single use case where I would want them to be counted. Also counting them is confusing as the perceived length of the output does not match the specified one. I get, that implementing that would of course be potentially quite some work, but is there another reason I am missing?

**Comment by vitaut** [comment]
It is not the default because ANSI escape sequences only apply to the terminal output. {fmt} provides basic support for colors and styles, for anything more advanced you'll have to write custom code or use a more specialized library.
