### ISSUE TITLE
Adapting {fmt} for embedded?

### ISSUE THREAD

**Issue by beewoolie** [fmtlib/fmt#4216]
I'm looking to evaluate the code side (more than performance) of this library with an embedded application.  I can get it to compile, but it wants an adaptation of FILE which we don't have when we use the simplest fmt::print().

So, the request is for some guidance about where to poke in {fmt} to wire-up what could be a _write() function to emit formatted strings to the various devices and ports where it should go.

Of course, I'll continue to investigate on my own to see if I can determine what should be changed.  Just asking for a little help.

**Comment by vitaut** [comment]
The relevant FILE output logic is in `vprint` implementations here: https://github.com/fmtlib/fmt/blob/4daa3d591f6715671e6716a298ec39f0a34058c5/include/fmt/format-inl.h#L1718-L1752

**Comment by vitaut** [comment]
Most (all?) of them go through this `fwrite` call:

https://github.com/fmtlib/fmt/blob/4daa3d591f6715671e6716a298ec39f0a34058c5/include/fmt/format-inl.h#L77

**Comment by beewoolie** [comment]
Thanks for the response.  And...I need to think a bit on this.  I don't have a FILE and I certainly don't have std::FILE.  So, either I need to make an adaptation of that or I need to unhook the places where {fmt} references it.  The firmware, now, uses vsprintf kinds of invocations to format into buffers and then emit those buffers.  That might end-up being a more direct avenue.

**Comment by beewoolie** [comment]
This is an FYI.   I added a single line to a test program:

```
#if 0
    ::printf ("Hello %d times\n",91);
#else
    ::printf ("%s", fmt::format ("Hello {} times\n", 91).c_str ());
#endif
```
The code size for the first one is 22.8K.  The second is 208K.  On Arm Cortex M4.  There are going to be a lot of things I don't (didn't) anticipate about the build and link to {fmt}.  I'm not sure I'm skilled enough to bring this down to compete with nanolibc.  I'd be over the moon to have the features available with this formatting methodology.  But, I'm mostly trying to reduce the footprint of the libc support code which is on the order to 16K for basic formatting.

**Comment by beewoolie** [comment]
One more detail, should this be helpful.  What I see in the `nm` dump when I look at the largest contributors to the code are below.  What I was hoping for was to only pay the cost of features I am using.  Locale is among the top contributors and those can probably be removed (based on perusal of the headers.).   Even though I have gc options enabled, I'm seeing functions that are not explicitly needed.

I removed the full type signatures to make the list readable.  The second column is the size of each function.  None of these are included without the call to format().  I recognize that not all of these entries are unique.

```
0802c8f8 00000c5c T _dtoa_r
080260f0 00000bf8 T _strtod_l
0802bca8 00000b38 T _svfwprintf_r
080157dc 00000b08 t std::__cxx11::time_get
080157dc 00000b08 W std::__cxx11::time_get
08010fcc 00000afc t std::__cxx11::time_get
08010fcc 00000afc W std::__cxx11::time_get
08020164 00000ae0 t std::time_get
08020164 00000ae0 W std::time_get
08019ac4 00000ad8 t std::time_get
08019ac4 00000ad8 W std::time_get
080286ec 000009e8 t __strftime.isra.0
080277e0 000009dc t __strftime.isra.0
0800af24 00000744 T std::locale::_Impl::_Impl(unsigned int)
0800af24 00000744 T std::locale::_Impl::_Impl(unsigned int)
08006d58 000004b4 W int fmt::v11::detail::format_float<double>(double, int, fmt::v11::format_specs const&, bool, fmt::v11::detail::buffer<char>&)
08013a54 00000488 T std::locale::facet::_M_sso_shim(std::locale::id const*) const
0800e0d8 00000488 T std::locale::facet::_M_cow_shim(std::locale::id const*) const
20003944 00000474 B main_console$
080281e4 00000444 T _tzset_unlocked_r
080297e0 00000420 T __gethex
0801c794 000003f0 W std::istreambuf_iterator
0801cb84 000003f0 W std::istreambuf_iterator
0801a59c 000003e8 W std::num_get
08022d20 000003e8 W std::istreambuf_iterator
08023108 000003e8 W std::istreambuf_iterator
0801bc2c 000003e4 W std::istreambuf_iterator
08011ef4 000003de W std::istreambuf_iterator
080122d4 000003de W std::istreambuf_iterator
08016704 000003d6 W std::istreambuf_iterator
08016adc 000003d6 W std::istreambuf_iterator
```

**Comment by vitaut** [comment]
You can disable locale by compiling with `FMT_USE_LOCALE=0`. Also check out https://vitaut.net/posts/2024/binary-size/.

**Comment by beewoolie** [comment]
There are a few other things I've found.  With the options you added to limit the size of the library, I'm seeing something like a 13K lower bound on the code size when using {fmt}.

However, there is an odd inclusion which I've not yet been able to identify its source.  When I add a call to format, I see

0800466c 000003cc T _strerror_r

added to the link.  Given the scale of our measurements, this ~1k seems like an undesirable extra.

**Comment by vitaut** [comment]
> I'm seeing something like a 13K lower bound on the code size when using {fmt}.

Nice!

As for `_strerror_r` I'm not 100% sure where it is coming from. Possibly `system_error` but the latter is not tied to `format` calls.
