### ISSUE TITLE
fmt's /utf-8 option breaks MSVC builds using /source-charset:windows-1252

### ISSUE THREAD

**Issue by martingalvan-volue** [fmtlib/fmt#4221]
Hi, I have a small test project built on Windows with MSVC, with fmt 11.0.2 installed through vcpkg.

My test project uses the `/source-charset:windows-1252` compile option for its own sources:

```
cmake_minimum_required(VERSION 3.29.0 FATAL_ERROR)

set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE PATH "")

project(Test CXX)

find_package(fmt CONFIG REQUIRED)

add_executable(main
    main.cpp
)

target_compile_options(main PRIVATE
    /source-charset:windows-1252
)

target_link_libraries(main PRIVATE
    fmt::fmt
)
```

However, when try to build it I get the following error:

```
C:\PROGRA~1\MIB055~1\2022\PROFES~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x64\cl.exe  /nologo /TP -DFMT_SHARED -external:IC:\Users\martin\fmt_test\build\vcpkg_installed\x64-windows\include -external:W0 /DWIN32 /D_WINDOWS /EHsc /Ob0 /Od /RTC1 -MDd -Zi /source-charset:windows-1252 /utf-8 /showIncludes /FoCMakeFiles\main.dir\main.cpp.obj /FdCMakeFiles\main.dir\ /FS -c C:\Users\martin\fmt_test\main.cpp
cl : Command line error D8016 : '/source-charset:windows-1252' and '/utf-8' command-line options are incompatible
```

I believe the reason for this is the `/utf-8` option being set as `PUBLIC` for the `fmt` target, here:

https://github.com/fmtlib/fmt/blob/0c9fce2ffefecfdce794e1859584e25877b7b592/CMakeLists.txt#L362

which results on the following code being generated by vcpkg's CMake machinery (on fmt-targets.cmake):

```
set_target_properties(fmt::fmt PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "FMT_SHARED"
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_COMPILE_OPTIONS "\$<\$<AND:\$<COMPILE_LANGUAGE:CXX>,\$<CXX_COMPILER_ID:MSVC>>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```

I believe this ends up propagating the `/utf-8` option to my own sources, and thus breaking the build.

That being said, I'm not sure whether this should be fixed on the fmt or the vcpkg side, since technically vcpkg could have a way for the user to disable `FMT_UNICODE` if needed. I'm not sure of the effect of setting `/utf-8` to `PRIVATE` for the `fmt` target, either.

**Comment by vitaut** [comment]
Using legacy encodings is not recommended (even by Microsoft) but you can use them if you opt out of Unicode support via `FMT_UNICODE`. For vcpkg questions please refer to their documentation or ask vcpkg maintainers.
