### ISSUE TITLE
Consider not using _ecvt_s

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#423]
- "The procedure entry point _ecvt_s could not be located in the dynamic link library msvcrt.dll"

This happens on Windows XP if compiled with MinGW, as XP's msvcrt.dll is too old and doesn't include that function, and MinGW doesn't use the static runtime library for copyright reasons.

_ecvt_s is used in implementation of `bool isnegative(double x)` ("Portable version of signbit").
Probably it's better to just use `signbit` if it's available. MinGW defines this macro in `math.h`.

**Comment by vitaut** [comment]
`isnegative` already uses `signbit` by default and I'd expect the call to `_ecvt_s` to be optimized away if `signbit` is available. Do you get this error when compiling without optimizations?

**Comment by alabuzhev** [comment]
http://www.cplusplus.com/reference/cmath/signbit/

> In C, this is implemented as a macro that returns an **int** value. The type of x shall be float, double or long double
> In C++, it is implemented with function overloads for each floating-point type, each returning a **bool** value.

So, `if (const_check(sizeof(signbit(x)) == sizeof(int)))` is actually `if (false)`.

I compile with -O3, so I presume it will be optimised away indeed, just not the branch you expect.

**Comment by vitaut** [comment]
Good catch. Does changing 
```c++
    if (const_check(sizeof(signbit(x)) == sizeof(int)))
```
to 
```c++
    if (const_check(sizeof(signbit(x)) == sizeof(int)) || const_check(sizeof(signbit(x)) == sizeof(bool)))
```
solve the problem?

**Comment by alabuzhev** [comment]
Yes, with that change I can't find any traces of _ecvt_s in the binary and it works.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/def687462c32ec40757e49eb6069f109d50236d6.
