### ISSUE TITLE
More details are needed in the "argument not found" exception

### ISSUE THREAD

**Issue by ujos** [fmtlib/fmt#4238]
Could you add the format string associated with the "argument not found" exception?

Consider the following code:

```cpp
fmt::format("test: {} {}", 1);
```

Would be great if exception text thrown would contain the "test: {} {}" text. For instance:

```
argument not found. Format string: test: {} {}
```

That would help a lot in finding the root of the issue.

**Comment by vitaut** [comment]
There are not plans to do this but in C++20 you'll get a compile-time error pointing to exact location of invalid format string.

**Comment by ujos** [comment]
Just wonder, why are you against this change? Does it introduce any problems?

**Comment by vitaut** [comment]
There are multiple issues with it but most importantly we shouldn't add new functionality when a better solution (in this case compile-time check) is available.

**Comment by fosterbrereton** [comment]
Sometimes a use case is willing to trade off compile-time checks against runtime flexibility. The presence of [`runtime_format`](https://en.cppreference.com/w/cpp/utility/format/runtime_format) admits this is a reasonable tradeoff (and meets this need). In such case, the actual call site will often obscure either the format string, its arguments, or both. If the `fmt` runtime is detecting this error, it is useful not to throw it away. To [quote Alex Stepanov](https://www.fluentcpp.com/2020/08/07/if-you-see-cut-paste-it-is-rotate/), "if you've already done the work to get some useful result, don't throw it away. Return it to the caller." The law of useful return applies to error messages, too.
