### ISSUE TITLE
Extend the interface of join to pass nested separator down

### ISSUE THREAD

**Issue by correaa** [fmtlib/fmt#4240]
With fmt, one can pass a range and a separator to `fmt::join`.
I wonder if it is possible to extend the interface of `join` (or something with another name) to pass extra parameters that will be utilized internally, if other calls to `std::join` are made recursively.

So if a nested vector is passed: `std::vector<std::vector<T>>` is passed to `fmt::join( vv, ",", "~")` then the top level is separated by "," and the lower level is separated by "~".

(It is possible that it could be a hard error if join is not called internally, or alternative, that the subsequent argument is ignored if not used --more elegant--)

This will replace something like:

```cpp
...
   constexpr auto join_sp = [](auto&& row) { return fmt::join(row, "~"); };
    fmt::print(
        "{}",
        fmt::join(
            std::views::transform(arr, join_sp),
            ", "
        )
    );
```
with this: `fmt::print( "{}", fmt::join(arr, ", ", "~") )`.

https://godbolt.org/z/nKcas4Ka4

See here:
https://stackoverflow.com/questions/79193937/control-fmt-formatting-of-nested-containers-ranges/79194118#79194118

PS: I know this has a flaw that is that the enclosing opening and closing format is still not specified, that needs more though I guess.

Feel free to close this issue if you think that is out of the scope of the library.

**Comment by vitaut** [comment]
It's an interesting idea but it seems a bit niche. I think it belongs to a custom formatter rather than the {fmt} library.

**Comment by vitaut** [comment]
I think the default formatting is sufficient and if anything more fancy is desired it can be done through an adapter.
