### ISSUE TITLE
Cannot dispatch to fmt::formatter for vector types

### ISSUE THREAD

**Issue by nextsilicon-itay-bookstein** [fmtlib/fmt#4243]
See here: https://clang.godbolt.org/z/b8qrPP153
Debugging this myself I think the issue is with the predicate `fmt::detail::use_formatter`, where vector types are neither classes, nor enums, nor unions, nor arrays.

**Comment by vitaut** [comment]
Closing as this seems a pretty niche non-standard feature and it is possible to write a formatter via a wrapper type.
