### ISSUE TITLE
fmt::print() ignores duplicate, buffered output?

### ISSUE THREAD

**Issue by bertulli** [fmtlib/fmt#4248]
Hi, first, thank you for your amazing work. I'm using fmt on a project communicating on a serial port (RS232). To debug an issue I was having, I added code similar to this:
```c++
get_line_r() {
  // [...]
  while (bytes_read < sizeof(buffer)) {

    auto res = read(fd, buffer + bytes_read, 1);
    fmt::print("read {}: {:c} ({:#x})\n", res, *(buffer + bytes_read), *(buffer + bytes_read));  // <--- NOTE HERE
    bytes_read++;
  }
}
int main() {
  // [...]
  while (main_loop_continue) {
    // Gather needed data
    serial.send(buffer, 2);
    std::string serial_answer = get_line_r();
    std::cerr << "Got answer '" << serial_answer << "'\n";               // <--- AND HERE
  }
}
```
The device at the other side of the communication answers with strings of the form `'   200,  1200, AA123AA, BB123BB'` (without the quotes, space padded). What I see from my output is similar to:
```
read 1:   (0x20)
read 1: 2 (0x32)  // <--- NOTE HERE
read 1: 0 (0x30)
read 1: , (0x2c)
read 1:   (0x20)
read 1: 1 (0x31)
read 1: 2 (0x32) // <--- AND HERE
read 1: 0 (0x30)
read 1: , (0x2c)
read 1:   (0x20)
read 1: A (0x41)
read 1: 1 (0x31)
read 1: 2 (0x32)
read 1: 3 (0x33)
read 1: A (0x41)
read 1: , (0x2c)
read 1:   (0x20)
read 1: B (0x42)
read 1: 1 (0x31)
read 1: 2 (0x32)
read 1: 3 (0x33)
read 1: B (0x42)
[15B blob data]
Here!
Got answer '   200,  1200, AA123AA, BB123BB'
```
Notice how, when printing out char by char the string, identical chars next to each other got skipped, but the string is read correctly, as you can see in the last line. Moreover, if I change the print line to this
```c++
    fmt::print("read {:d} (byte {:d}): {:c} ({:#x})\n", res, bytes_read, *(buffer + bytes_read), *(buffer + bytes_read));
```
the output seems to follow what's happening:
```
read 1 (byte 0):   (0x20)
read 1 (byte 1):   (0x20)
read 1 (byte 2):   (0x20)
read 1 (byte 3): 1 (0x31)
read 1 (byte 4): 0 (0x30)
read 1 (byte 5): 0 (0x30)
read 1 (byte 6): , (0x2c)
read 1 (byte 7):   (0x20)
read 1 (byte 8):   (0x20)
read 1 (byte 9): 1 (0x31)
read 1 (byte 10): 1 (0x31)
read 1 (byte 11): 0 (0x30)
read 1 (byte 12): 0 (0x30)
read 1 (byte 13): , (0x2c)
read 1 (byte 14):   (0x20)
read 1 (byte 15): A (0x41)
read 1 (byte 16): A (0x41)
read 1 (byte 17): 1 (0x31)
read 1 (byte 18): 2 (0x32)
read 1 (byte 19): 3 (0x33)
read 1 (byte 20): A (0x41)
read 1 (byte 21): A (0x41)
read 1 (byte 22): , (0x2c)
read 1 (byte 23):   (0x20)
read 1 (byte 24): B (0x42)
read 1 (byte 25): B (0x42)
read 1 (byte 26): 1 (0x31)
read 1 (byte 27): 2 (0x32)
read 1 (byte 28): 3 (0x33)
read 1 (byte 29): B (0x42)
read 1 (byte 30): B (0x42)
[25B blob data]
Here!
Got answer '   100,  1100, AA123AA, BB123BB'
```
Is this due to a buffering behaviour? Or is it a bug? Or am I doing something incorrectly?

I'm sorry I can't produce a MWE because this setting involves reading from a RS232. Thanks!

**Comment by vitaut** [comment]
It is possible that the `FILE` detection logic in https://github.com/fmtlib/fmt/blob/385c01dc7b23481246e3a0eb7cdb1e8495285e87/include/fmt/format-inl.h#L1640-L1651

detects your implementation as a known one while it is incompatible. Does compiling with `FMT_USE_FALLBACK_FILE` defined to 1 solve the issue?

**Comment by bertulli** [comment]
Hi, no it doesn't solve it.

I changed my CMakeLists.txt to (I was using FetchContent before)
```cmake
#######
# fmt #
#######

add_compile_definitions(FMT_USE_FALLBACK_FILE=1)
add_subdirectory(fmt)
# [...]
target_include_directories(my_target PUBLIC ${FMT_INC_DIR})
target_link_libraries(my_target fmt)
```
and checking with `VERBOSE=1 ninja` it seems it is correctly set.

**Comment by vitaut** [comment]
It doesn't seem actionable on our side without a repro so I'm going to close it but feel free to reopen with more details. You might want to debug what exactly happens to the output after formatting.
