### ISSUE TITLE
"Unicode support requires compiling with /utf-8" error while thats enabled in vs 2019

### ISSUE THREAD

**Issue by hoho965191737** [fmtlib/fmt#4249]
error C2338: Unicode support requires compiling with /utf-8  I want to know how to fix this problem?

![image](https://github.com/user-attachments/assets/35685851-3337-4d2a-8a9d-cebeaf509536)

**Comment by hoho965191737** [comment]
I tried it In the "Additional Options" field, add "/utf-8" (without quotes). Have no effect

**Comment by vitaut** [comment]
I would recommend using CMake in which case this option will be added automatically unless opted out of Unicode support. Otherwise please refer to the MSVC documentation.
