### ISSUE TITLE
Calling convert should be done using the fully qualified name of the convert function

### ISSUE THREAD

**Issue by gabime** [fmtlib/fmt#425]
As discussed in [this](http://stackoverflow.com/q/40685992) stackoverflow question about spdlog, seems that the call to convert in line 1276 in format.h should be done using fully qulified name of convert, or the compiler produces an error (due to conflicting 'convert' function from another library).

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/796beaaddb5226162fe00c2c55e322d80d26f3d8. Thanks for reporting!
