### ISSUE TITLE
fmt could be faster if it didn't do char-by-char

### ISSUE THREAD

**Issue by travisdowns** [fmtlib/fmt#4263]
Core functions like `fmt::format_to` take an output iterator, which lets you write directly into almost any type of buffer, or even directly to a device or file, etc. However, it also means that formatting writes into the buffer character-by-character, even when fmt "knows" that it just needs to copy a bunch of chars from its internal buffers or the format string to the output. If the output iterator is not totally trivial (e.g., it may resize the underlying buffer if is exhausted), the compiler can't really optimize this complexity away.

Is there currently any way for the iterator to expose addtional methods (e.g., write_n which writes multiple chars to the buffer) that fmt would take advantage of?

**Comment by travisdowns** [comment]
Looking at `copy_str` it does seem there is a specialization for when the output iterator is a `char *`: in that case `memcpy` is called so this avoids the char-by-char problem, but it is often hard to usefully use `char *` without knowing the maximum size of the formatted value.

**Comment by vitaut** [comment]
Currently there are some optimizations for contiguous iterators and back insert iterators into contiguous containers (like vector or string). Is your iterator one of those or something more complex?

`upper_length_bound` is not implementable in general, only for a small subset of types and when dynamic specs are not used.

**Comment by vitaut** [comment]
Anyway, the most important cases are already optimized but a PR to add some kind of customization to other types of iterators in would be welcome. For future reference this is the place that handles general iterators: https://github.com/fmtlib/fmt/blob/7c3d0152e559f5141138d7ae28ba7a9e84b1e344/include/fmt/base.h#L1839
