### ISSUE TITLE
missing space between ‘""’ and suffix identifier

### ISSUE THREAD

**Issue by Eternal-embers** [fmtlib/fmt#4265]
### make error
fmt/include/fmt/format.h:4004:16: error: missing space between ‘""’ and suffix identifier
fmt/include/fmt/xchar.h:131:13: error: missing space between ‘""’ and suffix identifie
error snippet: `operator""_a`, just need to add a space between `""` and `_a`

**Comment by vitaut** [comment]
Looks related to #3607. Please provide a godbolt repro.

**Comment by vitaut** [comment]
This is a bug in gcc 4.8 (https://godbolt.org/z/WcW7e16G1). Per docs in https://fmt.dev/dev/ {fmt} requires gcc 4.9 or later which correctly handles UDLs: https://godbolt.org/z/r3o5vGbz8.
