### ISSUE TITLE
format std:chrono::time_point question

### ISSUE THREAD

**Issue by aengusjiang** [fmtlib/fmt#4266]
I see that the fmt::print api can print the std:chrono::time_point:
#include <fmt/chrono.h>

int main() {
  auto now = std::chrono::system_clock::now();
  fmt::print("Date and time: {}\n", now);
  fmt::print("Time: {:%H:%M}\n", now);
}
Output:

Date and time: 2023-12-26 19:10:31.557195597
Time: 19:10

My question:
1.How to set the sub second such as show as microsconds 2023-12-26 19:10:31.557195 or show as milliseconds 2023-12-26 19:10:31.557?
 fmt::print("Time with microseconds: {:%H:%M:%S.%f}\n", now); //  print with microseconds failure
2.  fmt::format("{:%m-%d %H:%M:%S}", now)；ok
 fmt::format("{}", now)；KO
how use fmt::format timepoint with milliseconds, microsecond and nanoseconds?

**Comment by vitaut** [comment]
You can do it by converting the time point to the desired precision, e.g.

```
fmt::print("Date and time: {}\n",
           std::chrono::time_point_cast<std::chrono::milliseconds>(now));
```
https://www.godbolt.org/z/nosE78531
