### ISSUE TITLE
lazys formating

### ISSUE THREAD

**Issue by porkybrain** [fmtlib/fmt#427]
This is probably not a resolvable issue for this lib but just in case this is useful input:

I would love to use this lib in a bare metal super resource constrained context, however since my design does not have a heap I can't. Zero allocation would obviously also be a big performance boost for other users so I dumped my thoughts in [this blog post](http://metaporky.blogspot.de/2016/11/thoughts-on-lazy-formatting.html) about how the lib could be changes in order to be zero allocation and lazy evaluated if anyone is interested.

**Comment by vitaut** [comment]
Thanks for the feedback!

Regarding dynamic memory allocation & writing to a buffer, both can be easily avoided with the current API by using an appropriate writer such as [BasicArrayWriter](http://fmtlib.net/latest/api.html#_CPPv2N3fmt16BasicArrayWriterE) which can write to a fixed-size array allocated on stack. `fmt::format` is just a simple convenience function that formats into `std::string`. Note that in general it is not possible to compute the output size at compile time even in simple cases, e.g. `fmt::format("{:{}}", 42, width)`.

Also I'm not sure that it's possible to provide an efficient FSM-style API even for integers, not to mention floating-point numbers. But I'd love to see real code that attempts that and benchmarks.
