### ISSUE TITLE
Unreachable code warning

### ISSUE THREAD

**Issue by TLCFEM** [fmtlib/fmt#4273]
With version 11.1.0, the unreachable code warning is emitted at the following locations with MSVC.

```
\fmt\base.h(1310): warning C4702: unreachable code
\fmt\base.h(1394): warning C4702: unreachable code
\fmt\base.h(1524): warning C4702: unreachable code
\fmt\base.h(1528): warning C4702: unreachable code
\fmt\base.h(1551): warning C4702: unreachable code
\fmt\base.h(1579): warning C4702: unreachable code
\fmt\base.h(1586): warning C4702: unreachable code
\fmt\base.h(879): warning C4702: unreachable code
\fmt\format.h(3439): warning C4702: unreachable code
\fmt\format.h(3522): warning C4702: unreachable code
```

Return after throwing, for example,

https://github.com/fmtlib/fmt/blob/0e8aad961d66904cfda8d7cc894f6f6eee2d9f30/include/fmt/base.h#L1309-L1310

Maybe it can be improved so that as a user I do not need to push and pop to ignore this warning, or maybe nothing needs to be done.

**Comment by vitaut** [comment]
Fixing all possible warnings (especially level 4 which have tons of false positive) is a non-goal but you can suppress them with FMT_SYSTEM or other means.
