### ISSUE TITLE
missing space between ‘""’ and suffix identifier

### ISSUE THREAD

**Issue by aengusjiang** [fmtlib/fmt#4274]
v11.1.0 build on Centos7.9 gcc 4.8.5 failed. Does it require higher c++ standard in this version?
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON -DFMT_TEST=OFF -DCMAKE_BUILD_TYPE=Release -B build

![image](https://github.com/user-attachments/assets/2d8bf5fb-05b3-438e-975a-78f3194046ae)

**Comment by vitaut** [comment]
Same as #4265.
