### ISSUE TITLE
Alignment issue printing ranges of std::optional

### ISSUE THREAD

**Issue by hughcars** [fmtlib/fmt#4281]
I am attempting to modify the existing formatter for `std::optional` to allow writing column aligned data within one cpp file in an application. I'm hoping to have fixed column widths independent of optional status, and replace non-existant entries with a null string, leaving others alone. 

Presently given
```
    vector<double> numbers{1.0,2.0,3.0,4.0};
    vector<optional<double>> maybe{1.0, nullopt, 3.0, nullopt};
    vector<string> strings{"none", "none", "none", "none"};

    fmt::print("{:{}}\n", fmt::join(numbers, ","), 15);
    fmt::print("{:>{}}\n", fmt::join(strings, ","), 15);
    fmt::print("{:>{}}\n", fmt::join(maybe, ","), 15);
```
the output is 
```
              1,              2,              3,              4
optional(              1),none,optional(              3),none
           none,           none,           none,           none
```
If I change the parse/format methods within the optional parser from std.h to
```
template <typename T, typename Char>
struct formatter<std::optional<T>, Char,
                 std::enable_if_t<is_formattable<T, Char>::value>> {
 private:
  formatter<T, Char> underlying_;
  formatter<basic_string_view<Char>, Char> stringy_;
  static constexpr basic_string_view<Char> none =
      detail::string_literal<Char, 'n', 'o', 'n', 'e'>{};
 public:
  auto parse(parse_context<Char>& ctx) {
    stringy_.parse(ctx);
    return underlying_.parse(ctx);
  }

  template <typename FormatContext>
  auto format(const std::optional<T>& opt, FormatContext& ctx) const
      -> decltype(ctx.out()) {
    if (!opt) return stringy_.format(none, ctx);
    return underlying_.format(*opt, ctx);
  }
};
```
then 
```
    fmt::print("{:{}}\n", fmt::join(numbers, ","), 15);
    fmt::print("{:>{}}\n", fmt::join(strings, ","), 15);
    fmt::print("{:>15}\n", fmt::join(maybe, ","));
```
prints
```
              1,              2,              3,              4
           none,           none,           none,           none
              1,           none,              3,           none
```
as desired, but `fmt::print("{:>{}}\n", fmt::join(maybe, ","), 15);` fails with `fmt::v11::format_error`. Good chance I am missing something on how to treat the "double parsing" (if there's a better way to handle this, I would be all ears). Changing to only using `parse` once succeeds, but then the alignment and width requirements are lost on one of the outputs.

I've tried reading the custom type extension documentation but am stuck, any help appreciated, a godbolt reproducing is available [here](https://godbolt.org/z/4a58dPK6e)

**Comment by vitaut** [comment]
Double parsing of the same specs won't work for multiple reasons, e.g. dynamic width will be consumed twice. Moreover, you shouldn't be specializing formatters for types that you don't own like `std::optional`.

**Comment by hughcars** [comment]
Ok, so dropping `std::optional` and double parsing: Changing then to 
```
struct MyOptionalDouble
{
 double val;
 bool valid;
}
```
is there a way to follow the approach with optional of `formatter<double, Char>` in parsing the ctx for use with the double if `valid` is true, then to extract the width and alignment from that formatter, that it can be used to make a format string for the `"null"` object (or initializing a `formatter<basic_string_view>` to do that) if valid is false. The ultimate aim is to avoid writing an entirely custom parser, given a double is already so reliably parsed. Searching through `base.h` it seems like `specs_` is private and I couldn't see anything on introspecting a formatter in the documentation, so this might be a non starter, but I thought it worth asking first.

**Comment by vitaut** [comment]
`formatter` doesn't provide an API to retrieve width and alignment. You'll need to parse those separately and then invoke `parse` for the subobject if needed.
