### ISSUE TITLE
3.0.1 release doesn't contain documentation like previous release

### ISSUE THREAD

**Issue by daveisfera** [fmtlib/fmt#430]
The .zip file for the previous releases contained the documentation, but the 3.0.1 does not.

**Comment by foonathan** [comment]
This might have been my fault.

But the 3.0.1 is a pure bugfix release, just use the 3.0.0 documentation, there are no visible changes/additions/etc.

**Comment by daveisfera** [comment]
I'm the packager for Fedora/RHEL and using the documentation when building the 3.0.1 isn't realistically possible.

**Comment by foonathan** [comment]
Ah, I see. Well I don't know how to generate the documentation, you'll have to wait for @vitaut for that.

**Comment by vitaut** [comment]
The release script doesn't build the package with the documentation yet (I've added this as an item in #431), so it needs to be done manually by running `make doc` and then copying the `html` directory to the `.zip` package automatically generated by github. I've added the package with the docs to the [3.0.1 release](https://github.com/fmtlib/fmt/releases/tag/3.0.1).

Thanks for reporting!

**Comment by daveisfera** [comment]
Honestly, I would prefer to build the documentation as part of packaging, but it appears that very specific versions of some packages are required for it to work and I couldn't get it to work on Fedora. Would it be possible to change anything so that those requirements weren't so strict?

**Comment by vitaut** [comment]
You should be able to build the documentation as described in http://fmtlib.net/latest/usage.html#building-the-documentation. Feel free to open an issue if this doesn't work.
