### ISSUE TITLE
Improve the release script

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#431]
- [x] Update the list of published versions in the release script: https://github.com/fmtlib/fmt/blob/796beaaddb5226162fe00c2c55e322d80d26f3d8/support/manage.py#L116
- [x] Include the package with the docs in the release

**Comment by foonathan** [comment]
Should something be done regarding the first point?

**Comment by vitaut** [comment]
Thanks for reminding me of this, @foonathan. I've done the first item here and updated the website.

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/ac5f95208c6c487e3071fc362ac13067a00a5c01.
