### ISSUE TITLE
Fix test compilation for FreeBSD

### ISSUE THREAD

**Issue by WscriChy** [fmtlib/fmt#433]
A small patch (made against 3.0.1 tag) that fixes test for FreeBSD.
    
    
    --- test/posix-mock-test.cc.orig        2016-12-01 18:09:30 UTC
    +++ test/posix-mock-test.cc
    @@ -502,7 +502,7 @@ LocaleType newlocale(int category_mask,
       return LocaleMock::instance->newlocale(category_mask, locale, base);
     }
    
    -#ifdef __APPLE__
    +#if defined(__APPLE__) || defined(__FreeBSD__)
     typedef int FreeLocaleResult;
     #else
     typedef void FreeLocaleResult;

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/fac5546321031b9a32e9ea90c001bc4cef174589. Thanks!
