### ISSUE TITLE
Terminate called after throwing an instance of 'fmt::FormatError'   what():  missing '}' in format string

### ISSUE THREAD

**Issue by s7jones** [fmtlib/fmt#434]
I encountered this error:

> Terminate called after throwing an instance of 'fmt::FormatError'  
>     what():  missing '}' in format string

This is for the following format which I believe to be correct - at least it doesn't seem to be missing a '}'.

`fmt::print("x min max step:\t{%f}\t{%f}\t{%f}\n",xmin,xmax,xstepi);`

Any help is much appreciated.

**Comment by vitaut** [comment]
The format syntax doesn't allow `%` after `{`. You can fix this as follows:

```c++
fmt::print("x min max step:\t{:f}\t{:f}\t{:f}\n",xmin,xmax,xstepi);
```

See also http://fmtlib.net/latest/syntax.html.
