### ISSUE TITLE
Partially format string, i.e. keep some (named) replacement fields untouched

### ISSUE THREAD

**Issue by BerserkerTroll** [fmtlib/fmt#435]
I think it would be great to have such feature: use somethink like `fmt::ignore` and/or `fmt::ignore("name")` (or `fmt::keep`?) to keep some replacement fields verbatim so that `fmt::format("({x:d}, {y:d})", fmt::arg("x", 42), fmt::ignore("y"))` will  give `"(42, {y:d})"`.

**Comment by vitaut** [comment]
Thanks for the suggestion.

You can already do this by providing a proper definition of `ignore`:

```c++
struct ignore_val {};

void format_arg(fmt::BasicFormatter<char> &f,
                const char *&format_str, ignore_val) {
  const char *start = format_str;
  while (*start != '{')
    --start;
  while (char c = *format_str) {
    ++format_str;
    if (c == '}')
      break;
  }
  f.writer() << fmt::StringRef(start, format_str - start);
}

auto ignore(const char *name) {
  return fmt::arg(name, ignore_val());
}

int main() {
  fmt::print("({x:d}, {y:d})", fmt::arg("x", 42), ignore("y"));
}
```

I don't this this needs to be in the core library.

**Comment by BerserkerTroll** [comment]
Function named `format_arg`  doesn't work for me; `format` does.
