### ISSUE TITLE
Not enough examples in documentation, especially on dynamic-width justification

### ISSUE THREAD

**Issue by ddevienne** [fmtlib/fmt#438]
I've used in the past, forgot the syntax, and tried to find it in the doc, w/o success.
Had to hunt it down in my own code, now _littered_ with `fmt::format` :)

I think I discovered the syntax, e.g. `fmt::format("{:>{}}", text, width)` reading the unit test code, not the doc. Needs to be in the syntax doc IMHO, which needs many more example.

**Comment by vitaut** [comment]
Thanks for the suggestion. You are right, the docs could benefit from more examples. I'm focused on finished the standardization proposal right now, but PRs are very welcome.

> now littered with `fmt::format`

=)

**Comment by mrkgnao** [comment]
I was looking for this! I'm so happy the obvious "recursive" syntax works!

> littered with `fmt::format`

That makes two of us! :)

**Comment by VictorEijkhout** [comment]
I could use some hints on how to set width/precision & to use scientific notation. You know, the stuff that normally comes from iomanip.

**Comment by vitaut** [comment]
Added examples on dynamic width and precision in https://github.com/fmtlib/fmt/commit/ca96acbe4ffb445eed7d6b847a627b55da55e9a5. Feel free to submit more.
