### ISSUE TITLE
Allow %s as generic format specifier

### ISSUE THREAD

**Issue by mojoBrendan** [fmtlib/fmt#449]
Porting from another library (tinyformat), which allows %s to be used to get the default format for any parameter. At the moment this causes fmt to throw.

It would be nice (and I think straightforward) if %s could be supported for all types in the printf style functions.

**Comment by vitaut** [comment]
Sounds like a reasonable suggestion. This is already supported for `bool` and should be straightforward to do for other types. However it may take some time till I get to this since I'm busy with other stuff. Perhaps someone could contribute?

**Comment by mojoBrendan** [comment]
Sounds great. I have something working at the moment. Let me clean it up a bit. I'll get a pull request happening next week.
