### ISSUE TITLE
Grouping option

### ISSUE THREAD

**Issue by insideloop** [fmtlib/fmt#451]
Hi. Thanks for this fantastic library.

As far as I can see, there is no grouping option as in Python to group integers by pack of 3 digits. It might be nice to have:

   fmt::print("{:_}\n", 1000000);

print 1_000_000. Is it something that is just not implemented or something that might conflict with the current format?

**Comment by vitaut** [comment]
Thanks for the suggestion. Your example doesn't seem to work in Python:

```
>>> "{:_}\n".format(1000000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Unknown format code '_' for object of type 'int'
```

but it might be possible to do something like this with locale-specific formatting and a custom thousands separator.

**Comment by insideloop** [comment]
My mistake. The correct Python way is:

`"{0:,}".format(45000)`

**Comment by vitaut** [comment]
You can do the same with locales:

```
  setlocale(LC_NUMERIC, "en_US.UTF-8");
  fmt::print("{:n}", 45000); // prints "45,000"
```

which is somewhat more powerful.
