### ISSUE TITLE
Two fonctions return values, but they shouldn't

### ISSUE THREAD

**Issue by Mappy-team-LBS** [fmtlib/fmt#459]
In format.cc, the function PrintfArgFormatter::visit_bool (line 382) and PrintfArgFormatter::visit_pointer(line 421) both return something, but they are supposed to return void.

**Comment by vitaut** [comment]
Both cases are valid because the return expressions are calls to functions returning `void`.

**Comment by Mappy-team-LBS** [comment]
Why do you not just call them, instead of using return ?

**Comment by vitaut** [comment]
Because in both cases return is also necessary.
