### ISSUE TITLE
MinGW compilation problem

### ISSUE THREAD

**Issue by mapgccv** [fmtlib/fmt#461]
Trying to compile the library with WinGW (gcc 5.3.0) gives:

```
D:\Development\fmt\fmt\format.cc: In instantiation of 'static int fmt::internal::CharTraits<char>::format_float(char*, std::size_t, const char*, unsigned int, int, T) [with T = double; std::size_t = unsigned int]':
D:\Development\fmt\fmt\format.cc:518:48:   required from here
D:\Development\fmt\fmt\format.cc:240:21: error: 'snprintf' was not declared in this scope
         FMT_SNPRINTF(buffer, size, format, value) :
                     ^
D:\Development\fmt\fmt\format.cc:241:21: error: 'snprintf' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
         FMT_SNPRINTF(buffer, size, format, precision, value);
                     ^
D:\Development\fmt\fmt\format.cc:240:21: note: 'snprintf' declared here, later in the translation unit
         FMT_SNPRINTF(buffer, size, format, value) :
                     ^
D:\Development\fmt\fmt\format.cc:244:19: error: 'snprintf' was not declared in this scope
       FMT_SNPRINTF(buffer, size, format, width, value) :
```
and a bunch of similar errors for `snwprintf`.

Any advice?

**Comment by foonathan** [comment]
Shot in the dark: missing include in format.cc? ( @vitaut )

**Comment by vitaut** [comment]
Yes, looks like an include problem. @mapgccv, does replacing `snprintf` with `std::snprintf`in https://github.com/fmtlib/fmt/blob/master/fmt/format.cc#L90 help?

**Comment by mapgccv** [comment]
@vitaut: thanks, but nope. I have found a workaround, which is to define the symbol `_ISOC99_SOURCE` before including `cstdio` in `format.h`.

**Comment by vitaut** [comment]
What version of MinGW do you use?

**Comment by mapgccv** [comment]
MinGW version: 2013072300
GNU Make 3.82.90
gcc (GCC) 5.3.0

**Comment by vitaut** [comment]
Technically `snprintf` is a part of C99. Does including `<stdio.h>` in `format.cc` fix the issue?

**Comment by mapgccv** [comment]
Nope, sorry

**Comment by vitaut** [comment]
Then I am afraid you should continue to use `_ISOC99_SOURCE`. BTW mingw32 is known to be broken and I highly recommend using mingw64 instead.

**Comment by vitaut** [comment]
Implemented a workaround in https://github.com/fmtlib/fmt/commit/db0d54f855878792cf703fcdbda37aef6d3e8d34.
