### ISSUE TITLE
Ahead of time validation of format strings

### ISSUE THREAD

**Issue by netheril96** [fmtlib/fmt#467]
One problem I encounters with `fmt` is that the validation of format strings is deferred to runtime, while in GCC and Clang `snprintf` is checked at compile time (when the format string is a literal). When I use `fmt` for logging errors, I get a formatting error instead because I missed an argument.

I would like to see an macro that in debug mode expands to a `fmt::print` followed by a global registration. Then I can run a `checkAll()` or similar methods from this global registration that validates all of the format strings and argument types in my program without waiting for the execution path to reach them.

**Comment by vitaut** [comment]
I am not sure if it is possible to write such macro. However, for `printf`-style formatting you can enable a compile-time check with a simple trick described in https://github.com/fmtlib/fmt/issues/62#issuecomment-77490707.

**Comment by vitaut** [comment]
Compile-time format string checks are now available: http://zverovich.net/2017/11/05/compile-time-format-strings.html
