### ISSUE TITLE
format.h to fmt.h

### ISSUE THREAD

**Issue by polyvertex** [fmtlib/fmt#468]
Completely useless (yet utterly crucial) question from a single-minded developer: besides backward compatibility, is there any reason why you haven't renamed `format.{h|cc}` to `fmt.{h|cc}`? At least in the `std` branch? #justbecause

**Comment by vitaut** [comment]
That's a fair question. The name reflects its function: `format.h` is a header providing formatting functionality and there are other headers on the same level that provide other features. Also the project name is already reflected in the include directory.
