### ISSUE TITLE
Support for thousands separator for floats/doubles

### ISSUE THREAD

**Issue by eligt** [fmtlib/fmt#470]
I notice the library supports thousands separators (read from locale) for integers as integers' formatting is custom-made but it looks like double/float formatting relies on `snprintf` built-in formatting. 

The POSIX snprintf supports thousands separator with the single quote (') format specifier and indeed if I place one manually in the `write_double` function it works but I'm not sure what format specifier you'd want to add (similar to using `{:n}` to display locale-friendly integers).

**Comment by vitaut** [comment]
`'` is a POSIX extension and may not be supported on some platforms. Once Grisu or similar floating-point formatting algorithm is implemented (#147), we'll be able to add support for thousands separator in a portable way. For now I don't see a good way to do this.
