### ISSUE TITLE
fmt::MemoryWriter | how to ensure that the buffer gets cleared?

### ISSUE THREAD

**Issue by sntnupl** [fmtlib/fmt#471]
I am struggling to reuse `fmt::MemoryWriter`.
Essentially I have a code like the following:

```cpp
unsigned i = 0;
while (i != 2) {
    cout << "\n===============\n";
    fmt::MemoryWriter raw;
    cout << "Initial data: " << raw.data() << '\n';
    
    raw.write("Hello {}", "world!");
    cout << raw.data() << '\n';
    
    raw.write("Bye {}", "world!");
    cout << raw.data() << endl;

    ++i;
}
```

Running this code gives me the following o/p:

```sh
===============
Initial data:
Hello world!
Hello world!Bye world!

===============
Initial data: Hello world!Bye world!
Hello world!Bye world!
Hello world!Bye world!
```

I have an issue with the o/p wrt the second loop run.
I do not expect to see that the `Initial Data` to print `Hello World!Bye World!` second time around. What should I do to make sure that the buffer inside `fmt::MemoryWriter` gets cleared? Please note that `clear()` does not seem to solve the issue.

Am I missing anything?

I am using release **3.0.1**

**Comment by effzeh** [comment]
`data()` does not return a null-terminated C-string. Use `c_str()` instead. This method ensures that the returned string is null-terminated. It just happens that the `MemoryWriter` object reuses the same part of the stack in each loop.

**Comment by sntnupl** [comment]
Understood. Thanks @effzeh
