### ISSUE TITLE
Trouble upgrading from v2 to v3

### ISSUE THREAD

**Issue by ddevienne** [fmtlib/fmt#472]
Old v2 code customized the formatting of a custom type as shown below.
```
namespace fmt {
    template <typename Char>
    void format(BasicFormatter<Char> &f, const Char *&format_str, const my_ns::MyType &value) {
        format(f, format_str, value.transformItToSomeStdString());
    }
} // fmt
```

I'm also getting a different failure for another custom type, which does have a op<< operator (see below), which previously CppFormat v2 was calling implicitly:
```
namespace another_ns {
  ...
  inline std::ostream& operator<<(std::ostream& os, const AnotherType& v) { return v.print(os); }
}
```

In all cases, the error is 
> error C2665: 'fmt::format' : none of the 5 overloads could convert all the argument types

This doesn't compile anymore. How is one supposed to do that?
Is there a porting from v2 to v3 guide in the documentation?

Thanks, --DD

PS: Note that the doc still mentioned a single header/impl files, when v3 comes with additional files (ostream, posix, time), which I didn't use in my port from v2 to v3. Is this related to my 2nd issue? i.e. must use that ostream.h header for interop with op<< which used to come bundled in v2? Why the change?

PPS: Also note that my primary motivation to upgrade to v3 was for the thousand separator, but I'm surprised the format for it is `{:n}` instead of `{:,}` like in Python (I think), and I actually don't care/want about a Locale-aware thousand separator, but would prefer to use , systematically w/o to force the locale on the whole application.

**Comment by vitaut** [comment]
The name of the custom format function has been changed from `format` to `format_arg` in version 3:

```c++
    template <typename Char>
    void format_arg(BasicFormatter<Char> &f, ...
```

and the ostream support has been moved to `fmt/ostream.h`.

> Is there a porting from v2 to v3 guide in the documentation?

No, but the list of changes (with examples) is available here: https://github.com/fmtlib/fmt/releases/tag/3.0.0.

> Note that the doc still mentioned a single header/impl files, when v3 comes with additional files (ostream, posix, time), which I didn't use in my port from v2 to v3. Is this related to my 2nd issue? i.e. must use that ostream.h header for interop with op<< which used to come bundled in v2? Why the change?

The core library still consist of a single header and source file, the rest is optional. The optional headers were introduced to reduce compile times.

> Also note that my primary motivation to upgrade to v3 was for the thousand separator, but I'm surprised the format for it is {:n} instead of {:,} like in Python (I think), and I actually don't care/want about a Locale-aware thousand separator, but would prefer to use , systematically w/o to force the locale on the whole application.

Unfortunately `{:,}` is not supported yet. Patches are very welcome!
