### ISSUE TITLE
Please provide fmt::printf which writes to BasicArrayWriter

### ISSUE THREAD

**Issue by sirzooro** [fmtlib/fmt#476]
I would like to replace `snprintf` calls in my app with your lib. For performance reasons I do not want to use `fmt::sprintf` and then copy created string to its destination. Better approach would be to wrap memory buffer with `BasicArrayWriter` and write there. However at this moment fmt lib does not provide appropriate API for this. Please add it.

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/6f8006c2cecf2b9266351f23896601eb160adac4.

Now this should work:

```c++
fmt::MemoryWriter writer;
printf(writer, "%d", 42);
```

**Comment by sirzooro** [comment]
Thanks! I will give it a try tomorrow.
