### ISSUE TITLE
cxx11 module stomps on existing flags for cxx14 features

### ISSUE THREAD

**Issue by jeremyong** [fmtlib/fmt#478]
I noticed that I had to disable the C++11 feature detection support module to support more modern features which is a bit surprising. C++14 is broadly supported enough now that it may be worth including it or at least not using the cxx11 module if the library is not the "master" project and is included transitively.

**Comment by vitaut** [comment]
You can disable C++11 flags by defining CMake variable `FMT_USE_CPP11` to `False` before including fmt. Also the options are set per target and PRIVATE, so they shouldn't propagate to other targets.
