### ISSUE TITLE
<utility> included twice in format.h, once unconditionally, the other under #if FMT_USE_RVALUE_REFERENCES

### ISSUE THREAD

**Issue by ddevienne** [fmtlib/fmt#479]
Noticed in 3.0.1 (line 41 and line 156), but latest code seems to be the same. FYI. --DD

**Comment by vitaut** [comment]
You are right, the second include is redundant. Removed in https://github.com/fmtlib/fmt/commit/cc736e761106b4121a4ba0d10e6cc3e37df2127f, thanks!
