### ISSUE TITLE
stack corruption with big write

### ISSUE THREAD

**Issue by Sumenia** [fmtlib/fmt#480]
I'm getting a `libc: stack corruption detected` when using ```MemoryWriter::write("{}", msg)``` with a big (> 5k) string as `msg`.

This is happening on Android (Nougat).

any idea ?

**Comment by vitaut** [comment]
Could you post a reproducible example?

**Comment by Sumenia** [comment]
Ok I ran some experiments and found out that this code reproduces the problem :

``` 
   std::string msg;

    for (uint32_t i = 0; i < 5420; ++i) {
        msg += "s";
    }

    fmt::MemoryWriter writer;
    writer.clear();
    writer << "info";
    writer << msg;
```
This depends on the calling context (either if this code is split between functions or not, etc).

The ```writer << "info";``` is important as the code works fine without it.

The stack corruption only appears on the next function return.

**Comment by vitaut** [comment]
Does it happen on the latest `master`?

**Comment by Quentin01** [comment]
Not the last commit on `master` but the previous one `789ebea8637cce4a7deef`.

**Comment by vitaut** [comment]
I've traced your example code in the debugger and don't see anything that might cause stack corruption. However, note that `MemoryWriter` uses an inline buffer of size 500 chars, which can cause problems if the stack size limit is small. If this is the case you can use `StringWriter` instead.

**Comment by vitaut** [comment]
Might be related to #491 which has just been fixed.
