### ISSUE TITLE
name conflict of `False`

### ISSUE THREAD

**Issue by zhaohuaxishi** [fmtlib/fmt#483]
if i include `<X11/Xlib.h>` before `format.h`, compile will complain:

```
../../src/contrib/fmt/format.h:1209:8: error: expected identifier before numeric constant
 struct False { enum { value = 0 }; };
```

but if i exchange the include order, everything will be fine.

it seems that ` <X11/Xlib.h>` has defined `False` as value 0.

is name `False`  too common to be a type identifier in header file.

**Comment by FrankStain** [comment]
@zhaohuaxishi , can you check the `False` is a macro in <X11/Xlib.h> or not?

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/fbc8ea8c3eb78f00c298c8e9b82f650d827b9797, thanks for reporting!
