### ISSUE TITLE
std::ostream specializations have to be in namespace std

### ISSUE THREAD

**Issue by jcelerier** [fmtlib/fmt#486]
The following code : 

    #include <array>
    #include <iostream>
    #include <sstream>
    #include <fmt/ostream.h>
    
    // namespace std {
    std::ostream& operator<<(std::basic_ostream<char>& e, const std::array<float, 2>& ar) {
      return e;
    }
    // }
    
    void testcase()
    {
      std::stringbuf b;
      std::ostream c(&b);
    
      std::array<float, 2> ar;
      c << ar;
    
      fmt::format("foo {}", ar);
    }
    

fails to build with current fmt master. 
It works if I uncomment `namespace std`.

This used to work by commit e0251fdcefcde75641ba359d535438691be8e1eb

**Comment by jcelerier** [comment]
Maybe the commit 67662702aa8b444df00696b68b6e9b4069c0a898 is related ?

**Comment by vitaut** [comment]
Unfortunately I don't think this can be solved on the library level - this is how lookup works in general. For example

```c++
#include <array>
#include <sstream>

template <typename T>
void f(const T& value) {
  std::stringbuf b;
  std::ostream c(&b);
  c << value;
}

std::ostream& operator<<(std::basic_ostream<char>& e, const std::array<float, 2>& ar) {
  return e;
}

int main() {
  std::array<float, 2> ar;
  f(ar);
}
```

fails to compile as well:

```
test.cc:8:5: error: call to function 'operator<<' that is neither visible in the template definition nor found by argument-dependent lookup
  c << value;
    ^
```

The solution is to make sure that `operator<<` is visible via an appropriate include before including `fmt/ostream.h` or using ADL.
