### ISSUE TITLE
fmt::internal::is_streamable is not working on gcc 4.7

### ISSUE THREAD

**Issue by zhaohuaxishi** [fmtlib/fmt#498]
1.  `operator<<(BasicWriter<Char> &writer, const T &value)` use `internal::is_streamable<T>::value` when `__cplusplus >= 201103L` (fmt/osteam.h line 128)

```
#if __cplusplus >= 201103L
...
operator<<(BasicWriter<Char> &writer, const T &value) {
  FMT_STATIC_ASSERT(internal::is_streamable<T>::value, "T must be Streamable");
...
}
#endif
```

but `internal::is_streamable<T>::value` is defined only when `FMT_HAS_DECLTYPE_INCOMPLETE_RETURN_TYPES` is defined ( fmt/ostream.h line 79)

```
#if FMT_HAS_DECLTYPE_INCOMPLETE_RETURN_TYPES
template<typename T>
class is_streamable {
  template<typename U>
  static auto test(int) -> decltype(std::declval<std::ostream &>() << std::declval<U>(), std::true_type());

  template<typename>
  static auto test(...) -> std::false_type;

public:
  static constexpr bool value = decltype(test<T>(0))::value;
};
#endif
```

but `FMT_HAS_DECLTYPE_INCOMPLETE_RETURN_TYPES` is not equals to  `__cplusplus >= 201103L` :

```
#define FMT_HAS_DECLTYPE_INCOMPLETE_RETURN_TYPES \
    (FMT_HAS_FEATURE(cxx_decltype_incomplete_return_types) || \
    (FMT_GCC_VERSION >= 408 && FMT_HAS_GXX_CXX11) || \
    FMT_MSC_VER >= 1900 || \
    FMT_ICC_VERSION >= 1200)

```

i use gcc 4.7 with -std=c++11, which makes `FMT_HAS_GXX_CXX11` true, but `FMT_GCC_VERSION < 408`

i modify the defination as

```
#define FMT_HAS_DECLTYPE_INCOMPLETE_RETURN_TYPES \
    ...
    (FMT_GCC_VERSION >= 407 && FMT_HAS_GXX_CXX11) || \
    ...
```

it seems complies. is it safe to do that?

**Comment by vitaut** [comment]
> is it safe to do that?

I think it should be safe. `constexpr` was introduced in gcc 4.6 and new function declarator syntax even earlier according to https://gcc.gnu.org/projects/cxx-status.html. Could you submit a PR?

**Comment by zhaohuaxishi** [comment]
[#499](https://github.com/fmtlib/fmt/pull/499)
