### ISSUE TITLE
Xcode issue compiling due to calling private constructor

### ISSUE THREAD

**Issue by mobileben** [fmtlib/fmt#501]
I encountered this issue when using spdlog. It was reported as an issue in spdlog, and the author requested the OP to open the issue (https://github.com/gabime/spdlog/issues/384).

I'm getting this when passing along arguments from a variadic. Code looks like:

```
    va_list args;
    va_start(args, message);
#ifdef USE_SPDLOGGER
    consoleLogger->info(message, args);
#endif /* USE_SPDLOGGER */
    va_end(args);
```

The error is:

> In file included from ../3rdParty/spdlog/include/spdlog/fmt/fmt.h:21:
> ../3rdParty/spdlog/include/spdlog/fmt/bundled/format.h:2496:20: error: calling a private constructor of class 'fmt::internal::MakeValue<fmt::BasicFormatter<char, fmt::ArgFormatter<char> > >'
>     Value result = MakeValue<Formatter>(value);

As a quick experiment, I made ```MakeValue``` public in ```class MakeValue``` (around line 1366). However, after doing this, it compiles, but then the there is a linker error:

> Undefined symbols for architecture x86_64:
>   "fmt::internal::MakeValue<fmt::BasicFormatter<char, fmt::ArgFormatter<char> > >::MakeValue<__va_list_tag>(__va_list_tag const*)", referenced from:
>       fmt::internal::Value fmt::internal::ArgArray<1u, true>::make<fmt::BasicFormatter<char, fmt::ArgFormatter<char> >, __va_list_tag [1]>(__va_list_tag const (&) [1]) in logger.o

**Comment by vitaut** [comment]
You cannot pass `va_list` to a formatting function. For type safety reasons, the library uses variadic templates instead of varargs.
