### ISSUE TITLE
wrong length detected for atomic<uint64_t>

### ISSUE THREAD

**Issue by tamboril** [fmtlib/fmt#507]
For some reason, a `uint64_t` is formatted fine, but an `std::atomic<uint64_t>`, which defines
`operator uint64()` gets truncated to an `int`.

So these yield different output:

```
auto c = std::atomic<uint64_t> { 0x0000'0001'0000'0021ull };
cout << fmt::format("{}", c) << endl;
cout << fmt::format("{}", c.load()) << endl;

Output: 
33
4294967329
```

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/07ed4215212324145bee94b94e34656923a4e9b4. Thanks for the great bug report!
