### ISSUE TITLE
Is possible to write a formatted stuffs to a stack-based buffer like sprintf without using std::string?

### ISSUE THREAD

**Issue by haquocviet** [fmtlib/fmt#508]
Hi,
I am so interested in this library because of its simple and efficiency.
Currently, I use fmtlib to format something to a buffer like below:

std::string str = fmt::format("{} {}", 1234, "abcd");

However, when I want to format data to a stack buffer, I have to write:
char buffer[32];
fmt::ArrayWriter writer(buffer);
writer.write("{} {}", 1234, "abcd");

Though the job is done but it looks not so neat. I wonder if there is another simpler way to do so?
Thanks

**Comment by vitaut** [comment]
You can simplify your code in a number of ways:

1. Use `MemoryWriter` instead of `ArrayWriter`:

   ```c++
   fmt::MemoryWriter writer;
   writer.write("{} {}", 1234, "abcd");
   ```
   It will still allocate on stack if the output is small.

2. Write a wrapper function:

   ```c++
   template <typename... Args>
   void myformat(char (&buffer)[32], const char* format_str, const Args&... args) {
     fmt::ArrayWriter writer(buffer);
     writer.write(format_str, args...);
   }
   ```
   and use it in your code:
   ```c++
   char buffer[32];
   myformat(buffer, "{} {}", 1234, "abcd");
   ```
