### ISSUE TITLE
sprintf link problem

### ISSUE THREAD

**Issue by ericcurtin** [fmtlib/fmt#512]
Can't seem to use your sprintf implementation:

https://travis-ci.org/ericcurtin/ape
https://github.com/ericcurtin/ape

**Comment by ericcurtin** [comment]
https://travis-ci.org/ericcurtin/ape/builds/234562224

**Comment by vitaut** [comment]
It seems that you are trying to use varargs with `fmt::sprintf` which is not permitted for safety reasons. See also #501.
