### ISSUE TITLE
Random data on formatting integers with Clang with Microsoft CodeGen

### ISSUE THREAD

**Issue by Cleroth** [fmtlib/fmt#519]
Put simply, when I write this:

	cout << fmt::format("{}", 100u) << "\n";
	cout << fmt::format("{}", 100) << "\n";
	cout << fmt::format("{}", "aoeu") << "\n";
	cout << fmt::format("{}", 2.5) << "\n";
	cout << fmt::format("{} - {} - {}", 2.5, 3, "a") << "\n";

I get:

	♀õôw100
	0¸+
	aoeu
	2.5
	2.5 - Í×©O/☺P§3 - a

The characters seem to be random, varying every time I run the program.
I have ostreams included, if that matters.

Compiler: Visual Studio 2017 - Clang with Microsoft CodeGen (v141_clang_c2)

**Comment by Cleroth** [comment]
The problem occurs because of `FMT_BUILTIN_CLZ`. The intrinsic version is wrong.
`# define FMT_BUILTIN_CLZ(n) (31 - __builtin_clz(n))`
should be:
`# define FMT_BUILTIN_CLZ(n) __builtin_clz(n)`

And similar for the 64-bit version.

**Comment by Cleroth** [comment]
Also, I'm concerned about the intrinsic being used by default with some compilers. I'm not sure if _all_ current CPUs actually support it.

**Comment by vitaut** [comment]
Thanks for the bug report and the PR. As I commented on the PR, a simple workaround is to conditionally compile `FMT_BUILTIN_CLZ`.

> Also, I'm concerned about the intrinsic being used by default with some compilers. I'm not sure if all current CPUs actually support it.

I would expect compilers provide a fallback implementation in the runtime.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/569c5bdbf166e7227f2933ed83c7322263659bd9.
