### ISSUE TITLE
I cannot generate fmt library with cygwin in Windows

### ISSUE THREAD

**Issue by logangha** [fmtlib/fmt#521]
I am using Cygwin that´s why I used below generator (Besides I can not afford for Microsoft Visual Studio). But I get an error, see below (fileno and strdup are not recognized)

D:\C++\fmt-master>cmake -G "CodeBlocks - Unix Makefiles"

D:\C++\fmt-master>make
Scanning dependencies of target fmt
[  2%] Building CXX object fmt/CMakeFiles/fmt.dir/format.cc.o
[  5%] Building CXX object fmt/CMakeFiles/fmt.dir/ostream.cc.o
[  7%] Building CXX object fmt/CMakeFiles/fmt.dir/printf.cc.o
[ 10%] Linking CXX static library libfmt.a
[ 10%] Built target fmt
Scanning dependencies of target gmock
[ 12%] Building CXX object test/CMakeFiles/gmock.dir/gmock-gtest-all.cc.o
In file included from D:/C++/fmt-master/test/gmock-gtest-all.cc:39:0:
D:/C++/fmt-master/test/gtest/gtest.h: In function 'int testing::internal::posix:
:FileNo(FILE*)':
D:/C++/fmt-master/test/gtest/gtest.h:2852:51: error: 'fileno' was not declared i
n this scope
 inline int FileNo(FILE* file) { return fileno(file); }
                                                   ^
D:/C++/fmt-master/test/gtest/gtest.h: In function 'char* testing::internal::posi
x::StrDup(const char*)':
D:/C++/fmt-master/test/gtest/gtest.h:2858:57: error: 'strdup' was not declared i
n this scope
 inline char* StrDup(const char* src) { return strdup(src); }
                                                         ^
D:/C++/fmt-master/test/gtest/gtest.h: In function 'FILE* testing::internal::posi
x::FDOpen(int, const char*)':
D:/C++/fmt-master/test/gtest/gtest.h:2890:71: error: 'fdopen' was not declared i
n this scope
 inline FILE* FDOpen(int fd, const char* mode) { return fdopen(fd, mode); }
                                                                       ^
D:/C++/fmt-master/test/gmock-gtest-all.cc: In constructor 'testing::internal::Ca
pturedStream::CapturedStream(int)':
D:/C++/fmt-master/test/gmock-gtest-all.cc:8766:50: error: 'mkstemp' was not decl
ared in this scope
     const int captured_fd = mkstemp(name_template);
                                                  ^
make[2]: *** [test/CMakeFiles/gmock.dir/build.make:64: test/CMakeFiles/gmock.dir
/gmock-gtest-all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:228: test/CMakeFiles/gmock.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

What can I do in order to get this solved?

**Comment by vitaut** [comment]
This is a [Google Test](https://github.com/google/googletest) issue, so I recommend reporting it there (if it reproduces with the latest version of Google Test). You can still build the library itself with `make fmt`.
