### ISSUE TITLE
Pass arguments on the go to fmt::format

### ISSUE THREAD

**Issue by Loodoor** [fmtlib/fmt#522]
Hi there !

(I am only using format.cc and format.h)

I would like to know if it is possible to pass arguments "on the go" to fmt::format, because I am need to do some things on my arguments before passing them to the function (and I do not know how many arguments I will have, each time my code is running).

A code is better than a big explanation, so :

```cpp
std::string msg = fmt::format(s, a);
fmt::format(s, b);
// ...
```

I need to this because I am creating a programming language, and I have a list of arguments (with at least 1 argument, the maximum is related to the RAM your are giving to my interpreter) as following : 

```cpp
cell format(const cells& c)  // cells is a list of cell which is a struct
{
    // cell is a struct with an attribute type (enum) and a value (string, I am casting it into whatever is needed)
    // some internal code to check if we can use the function ...
    RAISE_IF(c.size() < 2, "'str-format' needs at least 2 arguments")
    HANDLE_EXCEPTION(c[0])
    RAISE_IF(c[0].type != String, "'str-format' first argument should be of type string, not of type " << convert_htbtype(c[0].type))
    // ok I checked everything, now I need to format
    std::string msg = fmt::format(c[0].val, ??);
    // just returning what we did into a type readable by my language
    return cell(String, msg);
}
```

I do not really know if I can play with fmt::ArgList easily to do what I want x')

Thanks for your help

**Comment by vitaut** [comment]
You can create your own formatting function which wraps `fmt::format`:

```
template <typename... Args>
std::string myformat(const char* format_str, Args&& args) {
  // Process arguments
  return fmt::format(format_str, args...);
}
```
Here you can process arguments before passing them to `fmt::format`.

**Comment by Loodoor** [comment]
Thanks, I will try that and tell you if I can get that stuff to compile ;)

**Comment by Loodoor** [comment]
Hum ... could not get it to work, probably because I am using a std::list of home made struct (I need an heterogeneous container to keep my processed arguments (which I have, but only working under C++17 and I am on C++11 ahah)).

So, no way to do as boost with `for (int i = 0; i < 10; ++i) f % array[i];` :/
