### ISSUE TITLE
How to build a header-only version?

### ISSUE THREAD

**Issue by ruipacheco** [fmtlib/fmt#524]
Is there a way to make CMake create a header only version of the library?

**Comment by vitaut** [comment]
You don't need CMake for that, just define `FMT_HEADER_ONLY` macro to 1 when including `fmt/format.h`.

**Comment by ruipacheco** [comment]
I'd like to include fmt in a library though. Is there a way to make it generate a single header?

**Comment by vitaut** [comment]
> Is there a way to make it generate a single header?

Nope and even if there was I wouldn't recommend it because it would increase build times. Why not include the `fmt` directory (from `include`) in your library and, possibly, define `FMT_HEADER_ONLY` as `spdlog` does?

**Comment by vitaut** [comment]
Possibly increased compile times as you'll get more code pulled into headers which would normally compiled into a library.
