### ISSUE TITLE
3.0.2 release doesn't contain documentation like previous release

### ISSUE THREAD

**Issue by daveisfera** [fmtlib/fmt#525]
Same issue as with the 3.0.1 release: https://github.com/fmtlib/fmt/issues/430

**Comment by foonathan** [comment]
Sorry, forgot, I've added them now: https://github.com/fmtlib/fmt/releases/tag/3.0.2

**Comment by daveisfera** [comment]
I just downloaded the .zip file and there still wasn't any html documentation in it.

**Comment by foonathan** [comment]
Sorry, now ːD

**Comment by daveisfera** [comment]
That worked. Thanks.
