### ISSUE TITLE
Consider moving headers to a separate directory

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#530]
https://www.reddit.com/r/cpp/comments/6k0jkh/release_40_of_fmt_a_formatting_library_for_c_is/djistaf/

**Comment by niosHD** [comment]
I don't have a strong feeling on moving the headers into a separate directory or not. However, I want to point out that the criticized behavior (`-I<fmt project root directory>` and including with `#include <fmt/fmt.h>`) is (currently) the correct way to use the library. There is even a check in https://github.com/fmtlib/fmt/blob/master/fmt/string.h#L11 for that.

Also, note that we install (`make install`) all headers into the fmt subdirectory (e.g., `/usr/local/include/fmt`). Subsequently, using a system wide installed version of the fmt library works with `#include <fmt/fmt.h>` as well. In case something on the layout is changed, I strongly recommend to keep this (or a similar) consistent behavior.

**Comment by vitaut** [comment]
I'm thinking of just introducing an extra level in the project, i.e. `fmtlib/fmt/format.h` -> `fmtlib/include/fmt/format.h`. The user code should remain the same:

```c++
#include <fmt/format.h>
```

Installation directories will remain the same although there is another issue that might change that: #532.

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/170f5c671f509d875dd84fd8ddf097989c43af60.
