### ISSUE TITLE
Library versioning

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#532]
It is inevitable that there will be backward-incompatible API changes between major library versions and therefore it should be possible to install multiple versions of `fmt` and user should be able to pick a specific version. Moreover, we should support linking against multiple versions of the library because it is sometimes included in the user's project directly and via a third-party library such as spdlog and versions may not match.

**Comment by vitaut** [comment]
@daveisfera, I know that you were concerned about compatibility issues and I'd like to address this in a systematic way. Please let me know if you have any specific ideas on the matter.

**Comment by vitaut** [comment]
Interestingly, Boost doesn't seem to solve this problem: https://stackoverflow.com/q/2907882/471164

**Comment by daveisfera** [comment]
Boost is a difficult library to point to. It's more a collection of libraries than a library and some of them do a great job with backwards compatibility and others not so much. Also, Boost is notorious in RedHat for having multiple versions being packaged for exactly this reason and it makes working with it quite a pain across all currently supported versions of RHEL.

Here's an example, with 4.0 some of the functions were moved to a new header. I totally understand refactoring and its benefits but this could have been done in a manner that better maintained backwards compatibility. For example, move the functions to the new header, but keep them included in the existing headers and then make a new smaller/minimal header for new code or code that can commit to 4.0+.

This is annoying and can be a major pain but I think that backwards compatibility should be one of the top concerns of a library that is aiming for wide spread use. C++ has adopted this mindset and I think it's served it very well. Yes, we still have more warts in the language than we'd like, but old code still works with modern compilers and when talking about libraries/languages with wide scale adoption (which I assume is the hope for `fmt`) that's a HUGE benefit that far outweighs little cleanups that can come from breaking backwards compatibility.

**Comment by vitaut** [comment]
Would it help if we release 4.0.1 that will include all headers if some compatibility macro like `FMT_COMPAT` is defined?

For the following releases I'm thinking of installing headers under

```
<prefix>/include/fmt-<version>/fmt
```

and using inline namespaces

```c++
namespace fmt {
inline namespace v5 {
/// ...
}
}
```

**Comment by daveisfera** [comment]
Putting the version in the path and the namespace just makes things worse in my opinion. I understand that it helps isolate things and opens the door for parallel installs, but it makes writing code that works with multiple versions even harder.

**Comment by vitaut** [comment]
Then I think we should just freeze the public API and only accept bug fixes in the main branch. Most of the development is in the `std` branch, which implements the standards proposal, anyway.
