### ISSUE TITLE
Make a range-based interface

### ISSUE THREAD

**Issue by ericniebler** [fmtlib/fmt#533]
There's no fundamental reason why we shouldn't be able to do formatting with any range of characters, as opposed to a string-based one. This will become super-important once the standard library moves more in the direction of ranges and range combinators. A lower-level `format` function should accept (possibly lazy) ranges of characters and return a (possibly lazy) range of characters. Higher-lever interfaces that operate on strings could be built on top.

**Comment by ericniebler** [comment]
There may be a need for Unicode code point manipulation / enumeration in a good standard text formatting library. I'll just leave this here: http://wg21.link/p0244

**Comment by vitaut** [comment]
Thanks for the suggestion. Using ranges for output seems reasonable if it can be done efficiently. But I'm not entirely sure what would be the benefit of using ranges for input (format string). Normally the format string is just a literal. You could generate it dynamically I guess but it seems like an overkill.

**Comment by beojan** [comment]
A range interface to `fmt::join` would also be very useful.

On that note, can you add `fmt::join` to the documentation? I didn't realize it existed and was use a range-for loop with a `MemoryWriter`.

**Comment by vitaut** [comment]
> A range interface to `fmt::join` would also be very useful.

There is one already: https://github.com/fmtlib/fmt/blob/bef89db6e7d10499a91affca7a933f264c7956d5/fmt/format.h#L4000

> On that note, can you add `fmt::join` to the documentation?

This part of API used to be experimental but I think there's little reason not to document it now. PRs are very welcome =).

**Comment by vitaut** [comment]
The library now supports `format_to` and `format_to_n` functions that take output iterators and have similar API to that of the standard library algorithms like `copy` and `copy_n`. There is also a proposal to add `format_iterator` in #972. I don't see what else can be done in this area so closing this issue, but specific suggestions are welcome.
