### ISSUE TITLE
Compiler error in posix.cc with FMT_USE_WINDOWS_H=0

### ISSUE THREAD

**Issue by staylor774** [fmtlib/fmt#537]
I'm getting a compiler error in posix.cc on VS2015 using `FMT_USE_WINDOWS_H=0`.

`posix.cc(141): error C3861: 'WindowsError': identifier not found`

Inside function:
`fmt::LongLong fmt::File::size() const`
Due to line:
`FMT_THROW(WindowsError(GetLastError(), "cannot get file size"));`

I think it's because `WindowsError` is defined within an `#if FMT_USE_WINDOWS_H` in format.h, but the code in posix.cc doesn't check `FMT_USE_WINDOWS_H`.

Unfortunately I can't submit a patch due to corporate restrictions, but I thought I should let you know. Thanks for the fantastic library!

**Comment by vitaut** [comment]
Thanks for the bug report but this is expected. `posix.cc` requires compilation with `FMT_USE_WINDOWS_H=1` which is the default on Windows to be able to report system errors. You can still use the core library, just make sure to remove `posix.cc` from the build.
