### ISSUE TITLE
Custom char type

### ISSUE THREAD

**Issue by Yelnats321** [fmtlib/fmt#543]
I was wondering what would be the most idiomatic way of creating a `BasicMemoryWriter` that operates on a custom char type. My motivation for this use case is to be able to use a custom class of basic types, which in addition to holding the primitive also hold some additional information (such as color or attribute for things like italics or boldface). So, instead of using an `int` I would use an `extended_arg<int>` as an argument which holds both the `int` and the additional information. The basic unit would then be an `extended_arg<char>`, and so data can be stored in something like a `std::basic_string`. When an `extended_arg` is formatted, the returned `extended_arg<char>` should hold the same properties as the argument that went in. For instance, a use would be `format("Example {}", 43_format.color(Green))`.

The library seems to provide some support for a templated `Char` type, but I am running into issues how I should go about adding support for my custom type. It seems I need to specialize `internal::CharTraits` for some of this. Am I on the right track? Or was the templated `Char` only supposed to be used to differentiate between the width of the chars.

**Comment by vitaut** [comment]
> It seems I need to specialize internal::CharTraits for some of this. Am I on the right track?

Yes, you have to provide a specialization of `fmt::internal::CharTraits`. It should be a part of the public API eventually but might need some cleanup and documentation. Also providing floating-point formatting for characters other than `char` and `wchar_t` can be problematic because you won't be able to use the standard C API.
