### ISSUE TITLE
constexpr checks of format strings

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#546]
Add a `check_format` `constexpr` function for performing a compile-time format string check and a section explaining why such check cannot be incorporated in the format function itself at the moment.  As discussed in #492 and the main problem is the lack of ability to handle the format string in `constexpr` context when other arguments are not `constexpr`.

Also Zach Laine suggested to mention the benefits of "compile-time strings":

> But the other part of what I want is for people to see how nice the interface would be if you *could* treat the format string as a constant expression.

**Comment by vitaut** [comment]
Potentially relevant discussion about constexpr function parameters: https://groups.google.com/a/isocpp.org/d/msg/std-proposals/RdAK-0RyiY0/F3h-qF_jWbIJ

**Comment by vitaut** [comment]
It is possible to access the format string and argument types at compile time using UDLs:

```c++
#include <string>

template <char... Chars>
struct formatter {
  template <typename... Args>
  constexpr std::string operator()(Args...) const;
};

template <typename T, T... Chars>
constexpr auto operator""_format() {
  return formatter<Chars...>();
}

int main() {
  return "{}"_format(42).size();
}
```

**Comment by ldionne** [comment]
Not only could you perform the safety checks at compile-time, but you could also generate optimal code by parsing everything at compile-time.

**Comment by vitaut** [comment]
Parsing of format specs is now `constexpr` and works with GCC 6.3, AppleClang 7.3 and Visual C++ 2017. Now need to figure out how to report errors at compile time. Can't use `static_assert` because it requires message to be a string literal.

**Comment by Rush** [comment]
@vitaut tried to compile your std branch with "g++ (SUSE Linux) 7.2.1 20171020 [gcc-7-branch revision 253932]" but got a lof of errors. Is your CI catching those?

**Comment by vitaut** [comment]
@Rush, the current revision (https://github.com/fmtlib/fmt/commit/d0f6d969a61f41b6ea07cf4dae9669d5e3922dc6) is broken at the moment. Please use https://github.com/fmtlib/fmt/commit/dfdb1adea5253e9ce0d5f5919594159b06f28922 instead. I'll fix it shortly.

**Comment by vitaut** [comment]
@Rush, the `std` branch should be fixed now. Let me know if you still see errors on your version of gcc.

**Comment by vitaut** [comment]
As of https://github.com/fmtlib/fmt/commit/f03a35a67934ebf22667136792a00b1efbd6160c the format string checks are complete. Opened a separate issue for optimal code generation: #613.
