### ISSUE TITLE
Shared library linkage error.

### ISSUE THREAD

**Issue by evgen231** [fmtlib/fmt#548]
I've tried using fmt in shared library, but got such error.

```
...
/usr/bin/ld: fmt/fmt/libfmt.a(format.cc.o): relocation R_X86_64_32S against `_ZTVN3fmt8internal12RuntimeErrorE' can not be used when making a shared object; recompile with -fPIC
fmt/fmt/libfmt.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
...
```

Compilers: gcc, clang
Platform: Linux

Minimal code:
```cmake
# ,,,
add_library(foo SHARED foo.cc)
target_link_libraries(foo PRIVATE fmt::fmt)
```
```c++
#include <fmt/format.h>
void foo() {
  fmt::print("");
}
```
Could be fixed by adding `POSITION_INDEPENDENT_CODE` property (at list for Linux platform).

**Comment by vitaut** [comment]
Thanks for the bug report, but the static library is built without `-fPIC` by default intentionally as discussed in #446. You can override this with a CMake variable `CMAKE_POSITION_INDEPENDENT_CODE `.
