### ISSUE TITLE
noreturn function throwing exception gives "noreturn func returns"

### ISSUE THREAD

**Issue by Manu343726** [fmtlib/fmt#552]
The function `internal::report_unknown_type()` declared at `format.h:935` as `noreturn` is throwing an exception on exceptions-enabled through the `FMT_THROW` macro. I've caugh this by building a dependent project with `-Werror -Wall -Wextra -pedantic` enabled on GCC 7.1.1. There's an unconditional throw at the end of the function, so as far as I'm concerned the function should not be triggering the error.

I've tried to write a minimal reproducible case (http://coliru.stacked-crooked.com/a/a7b0ef79054ac456) but as you can see there's no error there.
As far I can see the warning should not be triggered in that function, my output is more or less (could not make the clipboard copy work...):

```
fmt/format.cc:296:1: error: the 'noreturn' function returns
```

**Comment by vitaut** [comment]
Thanks for the bug report. Could you give the full compiler invocation command with all options as given e.g. by `make VERBOSE=1`? I wasn't able to repro this with just `-Werror -Wall -Wextra -pedantic`.

**Comment by Manu343726** [comment]
I've added a job to the CI build with the same original config and after a custom patch to fix integer conversion warnings the error is no longer reproduced: https://travis-ci.org/Manu343726/cppast/jobs/263927793 (Same in my local build of fmt with [that patch](https://github.com/Manu343726/fmt/commit/29a7e2c8a88294be181c58278b4d1a0c8e443870)).

I'm quite annoyed, definitely the purpose of `[[noreturn]]` is to troll me. I will close this as no longer reproducible, but I will ping you here if it happens again... Sorry :(

BTW, tomorrow I will try to PR that patch to your master branch.

Thanks for all.
