### ISSUE TITLE
Non-Variadic support for more than 16 arguments

### ISSUE THREAD

**Issue by vinshlusen** [fmtlib/fmt#554]
Hi,
 
I am using just format.h and format.cc (4.0.0) working with an older VS2010 compiler.
I am constructing strings with more than 15 arguments, a feature which is not supported by the library.

I modified the code, trying to raise this limit until I hit this wall:

```
struct ArgType {
  uint64_t type;
  ArgType() : type(0) {}
  template <typename T>
  ArgType(const T &arg) : type(make_type(arg)) {}
};
#define FMT_ARG_TYPE_DEFAULT(n) ArgType t##n = ArgType()
inline uint64_t make_type(FMT_GEN15(FMT_ARG_TYPE_DEFAULT)) {
  return t0.type | (t1.type << 4) | (t2.type << 8) | (t3.type << 12) |
      (t4.type << 16) | (t5.type << 20) | (t6.type << 24) | (t7.type << 28) |
      (t8.type << 32) | (t9.type << 36) | (t10.type << 40) | (t11.type << 44) |
      (t12.type << 48) | (t13.type << 52) | (t14.type << 56);
}
```

You are using a 64 bit integer to pack the 4-bit type identifiers of the arguments, shifting it in here, and later shifting it out when needed.  Naturally since we have no 128 bit integer we are limited here to 16(\15?) such 4 bits of type identifiers. 
Have you considered using a different container for this information? Why not just std::array?
This seems to be the only implementation detail limiting the usage of more than 15 arguments.

**Comment by Spartan322** [comment]
std::array is a C++11 feature, and the purpose of the implementation of the current variadic system is to allow type safe variadic templates regardless of the C++ compiler version, at least using a C++11 library only feature kinda negates the point of the entire thing.

**Comment by vitaut** [comment]
Unfortunately supporting larger number of arguments on legacy compilers will unnecessarily complicate the implementation (you'll need to store types differently and manually create even more versions of all the helper macros) and 15 is already a pretty large number. If you need more than 15 arguments only in a few places, then I'd just split such calls to formatting functions into two and concatenated the results (or use the writer API).
