### ISSUE TITLE
std branch?

### ISSUE THREAD

**Issue by polyvertex** [fmtlib/fmt#558]
What is the status/purpose of the `std` branch? Is it meant to replace `master` once ratified and stabilized (long shot it seems)? Also, is #518 meant to be the route plan for it somehow?

**Comment by vitaut** [comment]
> What is the status/purpose of the `std` branch?

The `std` branch is an implementation of the [standards proposal](http://fmtlib.net/Text%20Formatting.html).

> Is it meant to replace `master` once ratified and stabilized (long shot it seems)?

Yes, eventually.

> Also, is #518 meant to be the route plan for it somehow?

Kind of. It collects the proposal feedback, some of the items there are worth addressing and will be implemented in the `std` branch, some are not but might still need clarification in the paper.
