### ISSUE TITLE
Move ArgMap::init into format.h

### ISSUE THREAD

**Issue by Yelnats321** [fmtlib/fmt#560]
Currently, `internal::ArgMap<Char>::init` is defined inside `format.cc` and explicitly instantiated for `char` and `wchar_t`, even though the function itself is char type agnostic. This leads to issues using a character type other than these two. The easiest solution is to simply move the function definition into `format.h`. I am unsure on the compile time impact of such a change, although it would seem to be negligible, especially considering that most other functions are not explicitly instantiated (with the exception of `format_float` for understandable reasons and `FixedBuffer::grow`).

**Comment by vitaut** [comment]
Seems reasonable. Could you by any chance submit a PR?

**Comment by Yelnats321** [comment]
Yeah sure just give me a day or two.
