### ISSUE TITLE
Could you support container output?

### ISSUE THREAD

**Issue by shrinktofit** [fmtlib/fmt#562]
Assume the syntax:
```cpp
{[],<the_delim_to_join>}
```
saying that the corresponding argument is treated as a "container".

For example, the invocation
```cpp
std::vector<std::string> choices = {"apple", "pear", "banana"};
fmt::printf("Your can choose {[], or}!", fmt::make_container_arg(choices.begin(), choices.end()))
```

give:
```cpp
You can choose apple or pear or banana!
```

**Comment by vitaut** [comment]
This is already supported with a slightly different syntax:

```c++
  std::vector<std::string> choices = {"apple", "pear", "banana"};
  fmt::print("Your can choose {}!", fmt::join(choices, " or "));
```
prints

```
Your can choose apple or pear or banana!
```

**Comment by shrinktofit** [comment]
I think it isn't what I sugguest.

Consider we want implement the i18n, we want print the prompt in different language. the **program fragment**
```cpp
fmt::join(choices, " or "));
```
is not the best solution becase it hard code the "or" part.
You may read the "or" from the "configuration file" too, as:
```cpp
const char* THE_OR  = /*read from config file*/;
fmt::join(choices, THE_OR));
```
But it's elaborated and lack of the flexibility. In a word, "or" should be present alone with the setence "Your can choose {}".

**Comment by vitaut** [comment]
There is no built-in way to specify separator in the format string, but you can easily write your own class similar to [`ArgJoin`](https://github.com/fmtlib/fmt/blob/master/fmt/format.h#L3934) that takes a separator as part of the format string:

```c++
fmt::print("You can choose {: or }!", myjoin(choices));
```
