### ISSUE TITLE
Supporting C++17 std::string_view

### ISSUE THREAD

**Issue by thelostt** [fmtlib/fmt#570]
Any plans on this? It'd be useful to support `std::string_view` now that C++17 is practically done, and at least GCC and Clang have it implemented already.

I did a test[1] and it seems to work fine alongside `fmt::StringRef`.

[1] https://github.com/thelostt/fmt/tree/feature-string-view

**Comment by vitaut** [comment]
I don't have any specific plans but PRs are very welcome.

**Comment by thelostt** [comment]
Closed. See #571.
