### ISSUE TITLE
Incorrect width with #0*x format specifier

### ISSUE THREAD

**Issue by In3xess** [fmtlib/fmt#575]
`fmt::print("{0:#08x}", 1);`

The output is 0x000001 when it should be 0x00000001.
The reason is that the width is being applied on the full string rather than just on the value. It seems to take '0x' in account when doing the padding, which in my opinion is wrong.

Furthermore, but that's another discussion, I'd suggest to use `:X4` rather than `:4X`, à la C# for formatting integers.

**Comment by vitaut** [comment]
`fmt::print` follows both Python's and `printf`'s behavior here:

```python
>>> "{0:#08x}".format(1)
'0x000001'
```

The width **is** applied to the value, not the full string, but prefix including sign and base indicators are considered part of the value. You can easily account for the prefix size in width.
