### ISSUE TITLE
iostreams eat exceptions by default, this can lead to incorrect/truncated result

### ISSUE THREAD

**Issue by crusader-mike** [fmtlib/fmt#581]
In code snippet below if `buffer`'s underflow() throws an exception (e.g. std::bad_alloc) -- it is going to be silently eaten by `output` and execution will continue.

```
// Formats a value.
template <typename Char, typename ArgFormatter_, typename T>
void format_arg(BasicFormatter<Char, ArgFormatter_> &f,
                const Char *&format_str, const T &value) {
  internal::MemoryBuffer<Char, internal::INLINE_BUFFER_SIZE> buffer;

  internal::FormatBuf<Char> format_buf(buffer);
  std::basic_ostream<Char> output(&format_buf);
  output << value;

  BasicStringRef<Char> str(&buffer[0], buffer.size());
  typedef internal::MakeArg< BasicFormatter<Char> > MakeArg;
  format_str = f.format(format_str, MakeArg(str));
}
```

**Comment by vitaut** [comment]
Good catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/2c077dd44224606994f2a5569b4839324d0e3d26.

**Comment by crusader-mike** [comment]
an interesting thought -- what if T's op<< explicitly sets bad/fail bit instead of throwing an exception?

**Comment by vitaut** [comment]
> what if T's op<< explicitly sets bad/fail bit instead of throwing an exception?

¯\_(ツ)_/¯. I guess it could be translated into an exception.

**Comment by crusader-mike** [comment]
Turns out in this case `ios_base::failure` will be thrown.
