### ISSUE TITLE
Can't find appropriate way to format string with vector.

### ISSUE THREAD

**Issue by sbrednikhin** [fmtlib/fmt#584]
What I need:
I have format string
`std::string t_string ("Some {0} template {2} string {1}");`
and vector or other standard container 
`std::vector val= {15, 16, 22};`

How can I get something like 
`std::string res = fmf::format(t_string, val);`
with resulting string "Some 15 template 22 string 16"?
It looks like useful feature, but I can't find sample in documentation.

**Comment by vitaut** [comment]
It won't work because argument indices should refer to individual arguments rather than elements of a container, but you can implement your own vector formatting that does something like:

```c++
auto res = fmt::format("Some {0:0} template {0:2} string {0:1}", val);
```

**Comment by sbrednikhin** [comment]
Looks like i wanted this:
https://github.com/fmtlib/fmt/issues/528
