### ISSUE TITLE
Standalone header file for ArgList

### ISSUE THREAD

**Issue by ludekvodicka** [fmtlib/fmt#590]
Would be possible to separate ArgList class to standalone header file?

Because fmt::ArgList is used on a lot of places, it would be great to be able to include fmt::ArgList only instead of including the whole format.h.

**Comment by vitaut** [comment]
It has been already suggested in https://github.com/fmtlib/fmt/issues/528#issuecomment-313003473. I think it's a reasonable suggestion and can be done in the next version together with an API to construct argument lists.

**Comment by vitaut** [comment]
Moved the core API that deals with argument lists to a separate header, `include/core.h`, in the `std` branch. The new header is very small, just 672 significant LOC as reported by cloc

```
$ cloc include/fmt/core.h
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     1            183            148            672
-------------------------------------------------------------------------------
```
and has only few dependencies (I plan to reduce dependencies even more later).

With these changes compile times are now >40% better compared to IOStreams on bloat-test:

```
============ =============== ==================== ==================
Method       Compile Time, s Executable size, KiB Stripped size, KiB
============ =============== ==================== ==================
printf                   2.6                   29                 26
IOStreams               35.0                   59                 55
fmt                     24.2                   37                 34
tinyformat              49.2                  103                 97
Boost Format           113.0                  762                739
Folly Format           147.7                  102                 87
============ =============== ==================== ==================
```
