### ISSUE TITLE
printf: FormatSpec::fill_ character is invalid for CustomValue argument

### ISSUE THREAD

**Issue by M-Schiller** [fmtlib/fmt#594]
FormatSpec::fill_ is not initialized according to the format string for custom types. 

For example ```my_printf("%03d %03d, 5, my_custom_type);``` shows '0' as the fill character for the first (int) argument and  ' ' (space) as the fill character for the second (custom type) argument. 

Attached is a minimal example to demonstrate this behavior using fmt-4.0.0.

[fmt-Fill.zip](https://github.com/fmtlib/fmt/files/1431078/fmt-Fill.zip)

**Comment by vitaut** [comment]
This is expected. '0' flag can only be used for numeric types.
