### ISSUE TITLE
[SUGGESTIONS?] Replacing curly braces with something else | Application crashing with bad format

### ISSUE THREAD

**Issue by IstuntmanI** [fmtlib/fmt#599]
Sorry if these were already discussed, but I didn't look at all "issues" of this project here on GitHub. For now, I have few problems with it. These questions are fitting better in a forum/group (as I don't know if they are already possible somehow), but there's no forum/group for this library, so here we go:
1. I don't like that we have to use `{` and `}` as place holders. For example, in GTA SA-MP (a multiplayer mod) sending messages to the clients as "`Hello {FF0000}there`" would send "Hello" with some previously specified color and "there" in red, so if we want to use `fmt::format` in it we have to format it like "`Hello {{FF0000}}there`" and these colors are used quite frequently. Instead, it would be nice to allow us to replace them somehow (example: "`<:2d>`", "`>:2d<`"), to avoid escaping in every `fmt::format` for cases like mine. Ideally at run-time. Also, maybe it would be possible to allow us to end it with the same character ? Using "`^:2d^`" would be pretty fine I guess.
2. I noticed that in some cases the whole application crashes if using some bad formats, would be nice to format the whole string as "`{badfmt}`" instead, if possible, or even better: just the placeholder that was detected as a bad one, if the placeholder contains both `{` and `}`. For example, this one crashes right away:
```cpp
std::cout << fmt::format( "{:06X}|{:06X}|", 0x1FFFF >> 8 ) << std::endl;
```
(just missing one argument, ideally the format should look like "`0001FF|{badfmt}`")

Also, maybe it would be possible to improve compiling the code, maybe it could print out some warnings if there are some obvious problems with the format, like `snprintf` does in VC++ ?

**Comment by vitaut** [comment]
Thanks for the suggestions.

1. You can use the `printf`-like syntax (see `fmt/printf.h`) or implement your own formatter that re-uses most of the infrastructure, but has slightly different format string parser in the same way printf parser does.

2. Right now all errors are reported as exceptions, but some work is under way to (1) make error reporting configurable (#566) and (2) catch errors at compile time (#546).

BTW there is an fmt Gitter chat if discussion in Issues seems too heavyweight: https://gitter.im/fmtlib/fmt
