### ISSUE TITLE
Tests are congusing

### ISSUE THREAD

**Issue by yurivict** [fmtlib/fmt#601]
README has the "Running the tests" section that recommends to download a separate project from github.

CMakeFile.txt has FMT_TEST option that "Generates the test target."

README should explain the relationship of the cmake FMT_TEST option to testing.

**Comment by vitaut** [comment]
Clarified the purpose of `FMT_TEST` in https://github.com/fmtlib/fmt/commit/11415bce3c77d8300307bc757d002adb3b6eb73b.
