### ISSUE TITLE
What are the downsides to disabling the private MakeValue::MakeValue<T *> overloads?

### ISSUE THREAD

**Issue by mikecrowe** [fmtlib/fmt#608]
I have a large set of code that currently uses a logging mechanism with printf-style formatting with C-style variable argument lists that I'd like to convert to using fmt. This code contains many uses of %p to log pointer values.

From https://github.com/fmtlib/fmt/issues/288 I know that I can do so if I cast the pointers to void pointers (or use fmt::ptr) but I'd need to change a lot of code to do so.

https://github.com/fmtlib/fmt/issues/415 says that the cast is required "right now" which might be taken as a hint that the cast may not always be necessary.

I tried removing the private overloads of MakeValue::MakeValue that currently inhibit the formatting of arbitrary pointers. This mostly worked, but function pointers were not formatted properly - I suspect that they were being converted to booleans as they came out as simple `1`.

So, I added explicit template overloads:

```
class MakeValue : ... {
  ...
  
  template <typename T>
  MakeValue(T *value) {
    pointer = reinterpret_cast<const void *>(value);
  }
  template <typename T>
  static uint64_t type(T *) { return Arg::POINTER; }

  template <typename T>
  MakeValue(const T *value) {
    pointer = reinterpret_cast<const void *>(value);
  }
  template <typename T>
  static uint64_t type(const T *) { return Arg::POINTER; }

  template <typename T>
  MakeValue(volatile T *value) {
    pointer = reinterpret_cast<const void *>(const_cast<T *>(value));
  }
  template <typename T>
  static uint64_t type(volatile T *) { return Arg::POINTER; }

  template <typename T>
  MakeValue(const volatile T *value) {
    pointer = reinterpret_cast<const void *>(const_cast<const T *>(value));
  }
  template <typename T>
  static uint64_t type(const volatile T *) { return Arg::POINTER; }
}
```

and I was then able to output arbitrary pointers by modifying PrintfTest:

```
  int n;
  void *p = &n;
  int *q = &n;
  const int *cq = &n;
  const void *cp = &n;
  volatile int *vq = &n;
  volatile void *vp = &n;
  EXPECT_PRINTF(fmt::format("{}", p), "%p", p);
  EXPECT_PRINTF(fmt::format("{}", p), "%p", q);
  EXPECT_PRINTF(fmt::format("{}", p), "%p", cp);
  EXPECT_PRINTF(fmt::format("{}", p), "%p", cq);
  EXPECT_PRINTF(fmt::format("{}", p), "%p", vp);
  EXPECT_PRINTF(fmt::format("{}", p), "%p", vq);
  EXPECT_PRINTF(fmt::format("{}", p), "%s", p);

  ArbitraryStruct foo;
  EXPECT_PRINTF(fmt::format("{}", (void *)(&foo)), "%p", &foo);
  EXPECT_PRINTF(fmt::format("{}", (void *)(&a_function)), "%p", &a_function);
```

But, I can't help thinking that I've missed something obvious. The only downside to this I can see is that it would stop code adding custom formatters for pointers to arbitrary types.

Would you accept patches to implement formatting of arbitrary pointers?

Thanks.

Mike.

**Comment by vitaut** [comment]
The main reason why printing arbitrary pointers is disallowed is that it prevents issues like this:

```c++
std::cout << L"foo";
```
where a wide string is formatted as a pointer. We could allow printing other types of pointers but this would be inconsistent. Instead fmt requires you to explicitly mark the argument with `ptr` if you want to format it as a pointer (or use cast).

The other reason is the one that you mentioned:

> it would stop code adding custom formatters for pointers to arbitrary types.

See also section "Defective argument types" in [An Introduction to Fast Format (Part 1): The State of the Art](https://accu.org/index.php/journals/1539).

So I'm a bit reluctant to relax this requirement in general. However, I understand that it might be useful for migration purposes as in your case. Since it only affects the printf formatter I'm OK with relaxing the pointer requirement there but not in the new API.

**Comment by mikecrowe** [comment]
Thanks for the quick response.

vitaut wrote:
> std::cout << L"foo";

Ah yes, I can see how that would be a problem. A private overload for `const wchar_t *` would stop the that being accepted. But, of course, that wouldn't help with the other case that Matthew Wilson describes.

> So I'm a bit reluctant to relax this requirement in general. However, I understand that it might be useful for migration purposes as in your case. Since it only affects the printf formatter I'm OK with relaxing the pointer requirement there but not in the new API.

That sounds perfect for me. What would be your preferred way to make the changes only apply to the printf formatter? Specialisation of the `MakeValue` class for `PrintfFormatter` in printf.h? A `support_arbitrary_pointers` flag type in `PrintfFormatter` for `MakeValue` to check with `enable_if`?

Thanks.

Mike.

**Comment by vitaut** [comment]
> What would be your preferred way to make the changes only apply to the printf formatter? Specialisation of the MakeValue class for PrintfFormatter in printf.h? A support_arbitrary_pointers flag type in PrintfFormatter for MakeValue to check with enable_if?

Specialization of `MakeValue` seems reasonable because it's local to the printf formatter.

**Comment by mikecrowe** [comment]
vitaut wrote:
> Specialization of `MakeValue` seems reasonable because it's local to the printf formatter.

OK. I don't think that the current implementation of `MakeValue` lends itself to doing this. As I understand it, a specialised `template <> MakeValue<PrintfFormatter>` would need to duplicate all of the existing functionality of `template <Formatter> MakeValue<Formatter>`. Some of the functionality in `MakeValue` could be extracted to a base class, but most of its value is in its constructors and I can't see a way to avoid duplicating those.

An alternative would be to turn `MakeValue`, and its static member functions, into free functions within the internal namespace so individual overloads can be added outside the class. `make_type` already exists as such a function that currently forwards to a `MakeValue` static method. I haven't tried doing this though, so there may be pitfalls that I have not considered.

What is your opinion?

Thanks.

Mike.

**Comment by vitaut** [comment]
That's unfortunate. Then I suggest going with `enable_if` solution. This seems simpler than refactoring `MakeValue`.

**Comment by mikecrowe** [comment]
I finally got round to giving this a go. Unfortunately it seems that at the point MakeValue is created, the Formatter is BasicFormatter<char>, even when using fmt::printf, so my speciailizations have no effect. :(

In case it is of interest, my non-working solution is at https://github.com/mikecrowe/fmt/commit/9f92e28c9ebe010fdd0475f534ed822877eed672

**Comment by vitaut** [comment]
This is a bit difficult to fix in the `master` branch because of the variadic template emulation macros. However, the `std` branch, which will be the basis for the next major release, gets rid of the emulation and passes the correct context (an equivalent of `Formatter` in `master`) to `make_*` functions: https://github.com/fmtlib/fmt/blob/6f2769d0b4c2a026a15727b8c7013f9c8afe45ee/include/fmt/printf.h#L542.
So it might be easier to port the changes to the `std` branch then trying to make them work on `master`.

**Comment by vitaut** [comment]
I'm going to close this, but PRs are welcome.
