### ISSUE TITLE
fmt's CMakeLists.txt is polluting the compiler's include path

### ISSUE THREAD

**Issue by meldavis** [fmtlib/fmt#611]
The file "source/fmt/CMakeLists.txt" file is adding too many directories to the compiler's search path.  

The problem is this section (and the similar one for fmt-header-only):
```cmake
target_include_directories(fmt PUBLIC
  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}>
  $<INSTALL_INTERFACE:include>)
``` 
The build interface brings into the compiler's include search path -- not only the "fmt" folder containing the header files -- but also the "doc", "support" and "test" folders.   

The problem is most evident when I'm typing an include path and the IDE tries to auto-complete; -- it offers up these other folders for headers.

A fix would be to rename the "fmt" folder to something like "include/fmt". And changing the BUILD_INTERFACE for fmt and fmt-header-only to: 
```cmake
target_include_directories(fmt PUBLIC
  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
  $<INSTALL_INTERFACE:include>)
``` 
This way the only files the compiler sees are fmt's header files; and not all it's supporting files.

**Comment by vitaut** [comment]
Thanks for the bug report! This is already fixed in the `std` branch (#530) and will be a part of the next major release.
