### ISSUE TITLE
_format support for string containing \0

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [fmtlib/fmt#619]
Code:
```C++
std::cout << u8"te\0st"_format() << std::endl;
std::cout << u8"te\0st"_format().size() << std::endl;
```
Output:
```
te
2
```
Expected:
```
te st
5
```

Looks like code in `master` branch doesn't support format strings containing `'\0'`. Apparently `std` branch supports them, but `_format` literal still not.

**Comment by vitaut** [comment]
Good catch!

I think it can be easily fixed by changing `const Char *` to `basic_string_view` in https://github.com/fmtlib/fmt/blob/84bd2f196228e585a232f2465ff84eaa40b8398a/include/fmt/format.h#L4096 and passing the size when constructing `udl_formatter`. Could you submit a PR?

**Comment by WPMGPRoSToTeMa** [comment]
@vitaut, ok. Looks like `_a` should be fixed too.
