### ISSUE TITLE
When will version 4.0.1 be released?

### ISSUE THREAD

**Issue by hestad** [fmtlib/fmt#621]
Hi, spdlog is releasing in a couple of days: https://github.com/gabime/spdlog/issues/571#issuecomment-349647321

Since spdlog has fmt as a bundled dependency I was wondering if the time was right to release fmt 4.0.1? It would be very convenient with a co-release!

**Comment by vitaut** [comment]
We could do a patch release in the next few days or so.

**Comment by hestad** [comment]
:+1:

**Comment by gabime** [comment]
@vitaut That would be great. I will wait with spdlog’s new release until fmt releases 4.0.1

**Comment by foonathan** [comment]
@vitaut Should I prepare a changelog? I can find time on Saturday.

**Comment by vitaut** [comment]
> Should I prepare a changelog? I can find time on Saturday.

That would be awesome, thanks a lot!

**Comment by foonathan** [comment]
I haven't forgotten about it, I'll have it ready this evening.

There are a couple of new features (string view support, to_wstring etc) that don't break anything, so I'd suggest releasing a 4.1.0 instead of 4.0.1.

Only one question about #581: this is technically a breaking change, isn't it? Should I include it in 4.1.0?

**Comment by vitaut** [comment]
> Only one question about #581: this is technically a breaking change, isn't it? Should I include it in 4.1.0?

I'm for including #581 because it's a bug fix. If the code relies on incorrect behavior, it deserves to be broken =).

**Comment by foonathan** [comment]
Okay, pushed to release-4.0 branch: https://github.com/fmtlib/fmt/tree/release-4.0

(I'll merge it once the release is done anyway, so no point in renaming it).

**Comment by foonathan** [comment]
Any update?

**Comment by vitaut** [comment]
There is a missing underscore after:
```
`#563 <https://github.com/fmtlib/fmt/pull/563>`
```
Otherwise looks great!

**Comment by vitaut** [comment]
I did a few small tweaks (most importantly cherry picked the new release script from the `std` branch) and pushed the release: https://github.com/fmtlib/fmt/releases/tag/4.1.0. Thanks for your help, @foonathan!

**Comment by foonathan** [comment]
Oh, sorry I forgot about it. Thanks.

**Comment by vitaut** [comment]
No problem, it was almost ready =).
