### ISSUE TITLE
abort() called when mixing anonymous and non-anonymous replacement fields

### ISSUE THREAD

**Issue by woytazGOG** [fmtlib/fmt#623]
Visual Studio 2015, fmt version 4.0.0

Both of the following result in `abort` being called:
```c++
fmt::format("{} {1}", 1, 2);
```
```c++
fmt::format("{} {two}", 1, "two"_a=2);
```
I think the second example should be valid because mixing numeric and string IDs already is: `fmt::format("{0} {two} {0}", 1, "two"_a=2);` returns `"1 2 1"`.

**Comment by vitaut** [comment]
Good catch, thanks! The issue should be fixed in https://github.com/fmtlib/fmt/commit/971fb584c3ea548c12dcfa813b0bafb94e1c0fde.

**Comment by woytazGOG** [comment]
Awesome, thanks for the quick fix.
