### ISSUE TITLE
Passing a named arg in place of numeric-ID arg replaces both

### ISSUE THREAD

**Issue by woytazGOG** [fmtlib/fmt#624]
Visual Studio 2015, fmt version 4.0.0

`fmt::format("{0} {one} {0}", "one"_a=1)` returns `"1 1 1"`.

My expectation was that this would result in an error, saying that there are not enough arguments passed in to `format`.

**Comment by vitaut** [comment]
This is expected. Named arguments can be referred to either by name or by index.

**Comment by woytazGOG** [comment]
Pointing this out in the documentation would be good then since it's quite a big difference between fmt and Python's `str.format()`: `"{0} {one} {0}".format(one=1)` in Python (tested in 3.5 and 3.6) throws an exception ("tuple index out of range").

**Comment by vitaut** [comment]
Clarified in https://github.com/fmtlib/fmt/commit/cabce31f45fee785fdf2877921a2638881dbcc2f.
