### ISSUE TITLE
fmt::format being able to output { and } without escaping

### ISSUE THREAD

**Issue by IstuntmanI** [fmtlib/fmt#634]
I opened an issue related to this before: https://github.com/fmtlib/fmt/issues/599, but now I have a better idea. To output `{RRGGBB}testing` we currently have to use `fmt::format` as
```cpp
fmt::format( "{{{:06X}}}testing", FunctionReturningRGBA( ) >> 8 );
```
(doing that if the color is in the RGBA format, to avoid outputting the alpha, as it isn't required in this case, as a side note) or if there's no argument required we can do it directly as
```cpp
fmt::format( "{{FFFFFF}}testing" );
```
As you can see in the first example, we have to use three curly braces just to output one of them. One of them is for the placeholder and two of them are for escaping.

The ideal suggestion, in my opinion: if the placeholder isn't valid, it should simply be outputted and skipped, while also keeping double curly braces to escape for backwards compatibility. In this way we could change those examples to:
```cpp
fmt::format( "{{:06X}}testing", FunctionReturningRGBA( ) >> 8 );
```
(the placeholder would have a bigger priority, so it will be transformed into `{FFFFFF}` for example) and
```cpp
fmt::format( "{FFFFFF}testing" );
```
while the first examples are still valid for backwards compatibility.

Another example of the current problem: just look how ridiculous this is, it requires a lot of escaping for those curly braces while also accepting a placeholder and nothing else inside the escaped curly braces:
```cpp
fmt::format( "{{FFFF00}}{}. {{{:06X}}}{}\t{{C3C3C3}}{}\t{{{:06X}}}{}\t{{{:06X}}}{}...\n", i + 1, Utility::Color::EmbeddedHex( lNameColor ), some_string, some_other_string, Utility::Color::EmbeddedHex( lIPColor ), another_string, Utility::Color::EmbeddedHex( liSerialColor ), yet_another_string );
```

I find this library to be amazing and `fmt::format` is definitely my favorite function. I won't start using `printf`-like functions from `fmtlib` because I'd just keep using C's bad `std::snprintf` function which I don't like either. I like the new features that `fmt::format` provide and I would have no reason to go back to using `printf`-like functions. Also, I really need to output those curly braces, as this is the way this multiplayer mod uses to embed colors into texts.

I hope this won't be ignored. This suggestion combined with compile-time warnings/errors for invalid input would be amazing.

EDIT: Not sure if this is already possible, but being able to add a custom specifier to force the output would be amazing too, we could easily do things like
```cpp
FMT_SPECIFIER:color( int argument )
{
    return fmt::format( "{{{:06X}}}", argument ); // or some other way ?
}

fmt::format( "{:color}", 0xFFFFFF >> 8 ); // outputs {FFFFFF}
```
without needing to create a new class, which would be nice and could even help us further with the issue I described above.

(I really want this to be addressed before it would be standardized - by the way, good luck with that ! C++ indeed misses a fine alternative to format strings in modern ways)

**Comment by vitaut** [comment]
Thanks for the suggestion.

> The ideal suggestion, in my opinion: if the placeholder isn't valid, it should simply be outputted and skipped, while also keeping double curly braces to escape for backwards compatibility.

Unfortunately this won't work because for backward compatibility `{{` and `}}` in `"{{:06X}}testing"` would have to be treated as `{` and `}` producing `"{:06X}testing"` with argument ignored. Even if the backward compatibility was broken, it would create a problem of how to output the string `"{:06X}testing"` itself.

> Not sure if this is already possible, but being able to add a custom specifier to force the output would be amazing too

This on the other hand is possible with a somewhat different API:

```c++
struct color {
  explicit color(int val) : value(val) {}
  int value;
};

void format_arg(fmt::BasicFormatter<char> &f, const char *&format_str, color c) {
  f.writer().write("{{{:06X}}}", c.value);
}

fmt::format("{}", color(0xFFFFFF >> 8)); // outputs {FFFFFF}
```

**Comment by IstuntmanI** [comment]
That's a fair point about removing the need to escape brackets, it may also create some other problems I guess.

Yeah, I know about that possibility already, but I don't really feel comfortable to construct an object every time I need to output a color. I guess I'll just use this method for now, as it is at least better than escaping a lot everytime.

The only suggestion left in this topic seems to be the idea about a custom overloaded type placeholder (or whatever its name would be), we could do things like I specified in the edited section of the main post:
```cpp
// of course, the FMT_SPECIFIER: part would look more like the code you provided to be able to format custom types
FMT_SPECIFIER:color( int argument )
{
    return fmt::format( "{{{:06X}}}", argument >> 8 );
}

FMT_SPECIFIER:money( int argument )
{
    return fmt::format( "{}$", FormatNumber( argument ) ); // transforming 1234567 into 1,234,567$
}

FMT_SPECIFIER:player( int argument )
{
    return fmt::format( "{:color}{}({})", PlayerColor( argument ), PlayerName( argument ), argument ); // transforming 1234567 into 1,234,567$
}

fmt::format( "{:player} {:color} has {:color}{:money}", 5, 0xFFFFFFFF, 0x33AA33FF, PlayerMoney( 5 ) ); // outputs {RRGGBB}PlayerName(ID) {FFFFFF}has {33AA33}1,234,567$
```

I don't think that's possible now. It would be amazing to overload like this already existing types, by specifying a custom type.

**Comment by vitaut** [comment]
> Yeah, I know about that possibility already, but I don't really feel comfortable to construct an object every time I need to output a color.

What concerns do you have? It's very cheap to construct such an object as it is tiny (integer sized) and allocated on stack.

> The only suggestion left in this topic seems to be the idea about a custom overloaded type placeholder

Implementing this feature will require a global registry of custom specifiers indexed by strings and have a negative performance implications due to extra parsing and lookup at runtime as well as synchronization. This will also complicate parsing affecting processing of standard format specifiers even for the cases when the feature is not used. 

From the API perspective there isn't much difference to the existing approach. Using lightweight temporary objects will not only be faster, but if `PlayerMoney` is a separate type or a function returning a money type, also shorter:

```c++
fmt::format("{:player} {:color} has {:color}{:money}", 5, 0xFFFFFFFF, 0x33AA33FF, PlayerMoney(5));
fmt::format("{} {} has {}{}", player(5), color(0xFFFFFFFF), color(0x33AA33FF), PlayerMoney(5));
```

Moreover, it might be a good idea to pass around strongly typed objects instead of integers in the first place:

```c++
fmt::format("{} {} has {}{}", player, bg_color, fg_color, PlayerMoney(player));
```

**Comment by IstuntmanI** [comment]
Well, I guess I'll just stick to constructing objects (I can't always create a global object from it, so it has to be temporary), considering the lookup speed problem you specified. Thanks.

**Comment by andry81** [comment]
Why not to just use "%{}" instead python-liky "{}"??
Escape sequence becomes print-like escape "%%{}" and no problems with escaping both brackets at all.

**Comment by vitaut** [comment]
`%` will add extra syntactic noise especially for the most common case of the default formatting and slow down parsing for no extra benefits. Besides the current syntax is widely used and familiar to many.

**Comment by andry81** [comment]
I don't see how simple double-% escaping can slow down anything here.

**Comment by vitaut** [comment]
Not escaping, but an overhead of processing extra `%` for every replacement field `{}`.

**Comment by vitaut** [comment]
BTW the {fmt} library provides printf implementation if you want to use `%`.

**Comment by andry81** [comment]
Re: [fmtlib/fmt] fmt::format being able to output { and } without escaping (#634)


Hello Victor,

Wednesday, October 17, 2018, 4:38:46 PM, you wrote:





Not escaping, but an overhead of processing extra % for every replacement field {}.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.



Так в чём разница в оверхеде? Там и там нужно искать эскейп последовательности. Количество вхождений у {} будет больше чем у %. Отсюда оверхед у {} больше.
Так где же меньше?

-- 
Best regards,
 Andry                            mailto:andry@inbox.ru

**Comment by vitaut** [comment]
The common case is not escaping, but processing the default specifier which you propose to change from `{}` to `%{}` which is 50% more characters. There are other issues with changing the grammar, but even the first one is a non-starter.

**Comment by andry81** [comment]
Where did you get information about 50%? How the escape character has been processing before then? I don't get it why the %-folded escape sequence has to be slower than anythin else, when the "%%" character sequence can not fill 50% of a string space?

**Comment by vitaut** [comment]
Didn't you suggest replacing `{}` with `%{}`?

> Why not to just use "%{}" instead of python-liky "{}"??

If yes, then the common case of

```c++
fmt::format("{}", 42);
```
would become
```c++
fmt::format("%{}", 42);
```
adding the overhead I was referring to. This is highly undesirable.

If this is not what you were proposing then please elaborate.

**Comment by andry81** [comment]
> adding the overhead I was referring to. This is highly undesirable.

Can you be more specific about the overhead? Why is that would be undesirable when everybody around the world already uses it in the printf-like functions? How exactly it is compared to the "{}" with proofs?

**Comment by vitaut** [comment]
> Can you be more specific about the overhead? 

You increase the format string size by 50% for one of the most common cases given above.

> Why is that would be undesirable when everybody around the world already uses it in the printf-like functions?

`%` is not the same as `%{}`.

Moreover, changing the syntax in such way would break all the uses, so it's not going to happen even if we decided that overheads are manageable. 

If you are interested in `%` I recommend using the printf-like API provided by {fmt}.

**Comment by andry81** [comment]
> You increase the format string size by 50% for one of the most common cases given above.

Where?
strlen("{blabla}") vs strlen("%{blabla}") much less than 50%

> Moreover, changing the syntax in such way would break all the uses, so it's not going to happen even if we decided that overheads are manageable.
It still CAN BE changed before the C++ standard release

**Comment by vitaut** [comment]
> Where?

In the example from https://github.com/fmtlib/fmt/issues/634#issuecomment-431180453.

Anyway, you are welcome to explore the alternative format syntax possibly using the {fmt} infrastructure which is flexible enough to enough to support this.

**Comment by andry81** [comment]
> In the example from #634 (comment).
That example does not explain why is should be parsed slower

**Comment by vitaut** [comment]
> That example does not explain why it would be parsed slower

This adds a read and a conditional branch on the fast path.

>  it makes simplier to do external parsing to find placeholders in a formatting text

It is not true, because you still need to find matching `}` and process nested format specifiers in both cases. The parsing logic is trivial for `{}` and you can reuse the existing parser which has been done before.

Anyway, as I wrote before

> you are welcome to explore the alternative format syntax possibly using the {fmt} infrastructure which is flexible enough to support this.

I don't plan to support format syntaxes other than printf's and Python's in the nearest future.

**Comment by spitzak** [comment]
Comment is correct that the proposed syntax would make it impossible to print a literal string that looks like a format.

However does anybody have an explanation of why this curly-brace syntax was chosen? They could have used "%...s" syntax, parsed exactly like printf, with the various flags, numbers, and the final character sent to the print method for the object (so it is ok if you use 's' everywhere, but they could use the fact that you typed another letter to change the formatting). The obvious advantage of this is that it is trivial to convert printf statements to println.

**Comment by vitaut** [comment]
{fmt} is based on Python's str.format: https://docs.python.org/3/library/string.html#format-string-syntax.
