### ISSUE TITLE
Debug library suffix missing

### ISSUE THREAD

**Issue by ixSci** [fmtlib/fmt#636]
Just tried to use the fmt library and stumbled upon either inconsistency or my misunderstanding. I've downloaded the latest library archive, unzipped it and generated an MSVC solution out of it. So far so good. Then I've built the solution both for Debug and Release configuration and then installed both of them to the previously set install prefix. The thing is both Debug and Release library have the same name: `fmt.lib` and whichever configuration gets installed last will be at the target dir.

I've skimmed over the cmake files the library provides and it looks like (according to fmt-targets-debug.cmake) it actually rightfully expects to have `fmtd.lib` for the Debug configuration. I locally fixed the issue by adding `set(CMAKE_DEBUG_POSTFIX "d")` to the fmt CMake script.

Am I doing something wrong or the library build script does not actually generate a separate name for the Debug build?

**Comment by vitaut** [comment]
Good catch, it's definitely a bug that the debug version of the library doesn't have a distinct suffix when installed. Could you submit a PR?

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/c15710032e095e4ddb9da29e4eabc92b7acaa63b. Thanks for reporting!

**Comment by ytimenkov** [comment]
Unfortunately this messes up things :( on non-MSVC platforms: the resulting library is `libfmtd.a`, but (for example) `fmt.pc` still has `-lfmt`.

Having `set_target_properties` in cmake script makes it impossible for packager to change the behavior.

I would rather leave this option to one who creates the package: ones who need `fmtd` can always add `-DCMAKE_DEBUG_POSTFIX` to the cmake invocation (or at least provide an overridable default).

I myself making a Conan package for fmt and would rather have a well-defined name even if I have to use VS.

**Comment by vitaut** [comment]
> the resulting library is libfmtd.a, but (for example) fmt.pc still has -lfmt.

I suggest fixing `fmt.pc` although there is little reason to distribute debug binaries.
