### ISSUE TITLE
CXXFLAGS from the environment should used while detecting compiler features

### ISSUE THREAD

**Issue by sztomi** [fmtlib/fmt#637]
cxx11.cmake performs the compiler checks by only trying the `std=c++11` parameter. However, on macOS, the stdlib parameter is also important, since clang (upstream or Apple) does not support C++11 with libstdc++. Ultimately, cmake will respect the environment flags so the library compilation will happen using those flags.

Disregarding the environment variables also leads to weird command lines where multiple -std flags might be specified. For example, in my environment:

```
clang++   -Ifmt-4.1.0-135ab5c-0 -fPIC -DPIC -mmacosx-version-min=10.9 -fno-stack-protector -std=gnu++98 -Werror=partial-availability -Os -stdlib=libstdc++ -O3 -DNDEBUG -isysroot /Applications/Xcode_8.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9   -std=c++11 -MD -MT fmt/CMakeFiles/fmt.dir/format.cc.o -MF fmt/CMakeFiles/fmt.dir/format.cc.o.d -o fmt/CMakeFiles/fmt.dir/format.cc.o -c fmt-4.1.0-135ab5c-0/fmt/format.cc
```

And I have

```
CXXFLAGS=-fPIC -DPIC -mmacosx-version-min=10.9 -fno-stack-protector -std=gnu++98 -Werror=partial-availability -Os -stdlib=libstdc++
```

With this environment I can only compile fmt if I explicitly specify `-DFMT_USE_CPP11=OFF`. That's good enough for me, but I think this may cause other subtle compiler detection errors in other environments so that's why I'm reporting it.

**Comment by vitaut** [comment]
Thanks for the bug report. AFAICS CMake already uses `CXXFLAGS` in checks, you just need to set this environment variable when running it:

```
env CXXFLAGS=-stdlib=libstdc++ cmake ...
```

For example, it detects that initializer lists and type traits are not supported when using libstdc++:
```
-- Performing Test SUPPORTS_INITIALIZER_LIST
-- Performing Test SUPPORTS_INITIALIZER_LIST - Failed
-- Performing Test SUPPORTS_ENUM_BASE
-- Performing Test SUPPORTS_ENUM_BASE - Success
-- Performing Test SUPPORTS_TYPE_TRAITS
-- Performing Test SUPPORTS_TYPE_TRAITS - Failed
```
