### ISSUE TITLE
join doesn't work with nested replacement fields

### ISSUE THREAD

**Issue by peterbell10** [fmtlib/fmt#638]
Running the following results in `FormatError("unmatched '}' in format string")` being thrown.
```cpp
float test[10]{};
fmt::format("{0:.{1}f}", fmt::join(std::begin(test), std::end(test), ", "), 2);
```

This happens because `ArgJoin`'s `format_arg`  only advances the format string past the first '}' leaving "f}" to be formatted.
https://github.com/fmtlib/fmt/blob/c719d94473fa97ce48213bb321b25437c7f5a661/fmt/format.h#L4116-L4117

**Comment by vitaut** [comment]
Good catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/6822466aa390523d588d4ee475be98bb90042e25.
