### ISSUE TITLE
BasicWriter::c_str is thread-unsafe

### ISSUE THREAD

**Issue by sam-lunt** [fmtlib/fmt#643]
The C++ standard requires standard library implementations to avoid data races in const member functions. Specifically, section 17.6.5.9 (Data race avoidance) specifies in item 3 that:

> A C++ standard library function shall not directly or indirectly modify objects (1.10) accessible by threads other than the current thread unless the objects are accessed directly or indirectly via the function’s non-const arguments, including `this`.

While I recognize that this library is not part of the standard library, the restrictions placed on `const` member functions by the standard seem reasonable and prudent for all libraries (at least in my opinion). Plus, a subset is proposed for inclusion ([P0645R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0645r0.html)) in the standard library (though it doesn't seem like BasicWriter is part of that proposal).

The issue is that calls to `c_str` modify the underlying buffer in order to add a terminating null character (see the source code [here](https://github.com/fmtlib/fmt/blob/c96062bff59284e2afb82781ed6d95e91cc7e31b/fmt/format.h#L2739)).

So if the call to `reserve` requires allocating new memory for the buffer, it could lead to invalid memory accesses in another thread. For example, if I call `BasicWriter::str` (which must allocate a buffer and copy the data into it) in one thread and `BasicWriter::c_str` in another thread, if the call to `c_str` requires growing the buffer, then while the first thread is performing its copy, the data will be deallocated from underneath it, even though both threads only called `const` functions.

I don't see a good solution for this problem. The only option that truly avoids the problem is to simply remove the `c_str` function. When available, `std::basic_string_view` would be a useful alternative. If someone truly needs a C style string, they could call `str` and then `c_str` on the result of that call (which obviously has the downside of an extra allocation, copy, and deallocation).

At the very least, it seems useful to document the potential issues with `c_str`

**Comment by vitaut** [comment]
Thanks for raising this issue. The `c_str` method has already been removed from the writer API in the `std` branch (reference implementation of P0645R0) which will be the basis for the next release.
