### ISSUE TITLE
Please keep a branch for 3.0 alive

### ISSUE THREAD

**Issue by smurfix** [fmtlib/fmt#647]
Currently there's a tag for version 3.0.2 but the actual 3.0 branch appears to be gone. This is not optimal since at least one project (knxd) depends on fetching the latest 3.x version of libfmt if the OS doesn't have it.

Please resurrect. Thanks.

**Comment by vitaut** [comment]
I don't think you need a branch to fetch any older version with git. For example, you can just fetch commit https://github.com/fmtlib/fmt/commit/5708bf8fcc1bc2f26b73335dae49a601ecb8882d for version 3.0.2. You can get commit numbers from the releases page (https://github.com/fmtlib/fmt/releases).

**Comment by smurfix** [comment]
I know that I don't *need* a branch. However I *want* a branch, instead of a fixed commit, so that I can benefit from bug fixes without pulling incompatible changes.

I switched knxd to the 4.x branch. Please don't delete that too – 4.x at least works, which cannot be said for master currently, at least not on my system.

**Comment by vitaut** [comment]
Got it. 3.x branch was no longer receiving updates and that's why it was deleted so it's good that you've updated to 4.x. The latter will be kept for those who need C++98 support and it will receive fixes.
