### ISSUE TITLE
Formatting of custom types is broken

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#650]
If a custom type only provides streaming to std::**w**ostream, this code in ostream.h breaks the compilation, as it only tests std::ostream:

```
struct test_stream : std::ostream {
 private:
  struct null;
  // Hide all operator<< from std::ostream.
  void operator<<(null);
};

// Disable conversion to int if T has an overloaded operator<< which is a free
// function (not a member of std::ostream).
template <typename T>
class convert_to_int<T, true> {
 private:
  template <typename U>
  static decltype(
    std::declval<test_stream&>() << std::declval<U>(), std::true_type())
      test(int);

  template <typename>
  static std::false_type test(...);

 public:
  static const bool value = !decltype(test<T>(0))::value;
};
```
fmt supports wide streams in all other places and this worked fine before and works now if the code above is commented.

**Comment by alabuzhev** [comment]
Moreover, this logic is questionable in the first place, since it shadows the primary convert_to_int template instead of extending it.

. The comment says:
> **Disable** conversion to int if T **has** an overloaded operator<<

But what what the code *actually* does is:
> **Enable** conversion to int if T **does not have** an overloaded operator<<

Which means that `struct foo {};` is literally convertible to int from the library's perspective.

**Comment by vitaut** [comment]
Good catch, fixed in https://github.com/fmtlib/fmt/commit/91721caa42a7d509974d9938fc76a29adf9101a6.

> Moreover, this logic is questionable in the first place, since it shadows the primary convert_to_int template instead of extending it.

I'm not a big fan of this approach either. Suggestions on how to improve it are welcome.

> Which means that struct foo {}; is literally convertible to int from the library's perspective.

Not really, because of an enum check in

```c++
template <typename C, typename T>
inline typename std::enable_if<
    convert_to_int<T, typename C::char_type>::value && std::is_enum<T>::value,
    typed_value<C, int_type>>::type
  make_value(const T &val) { return static_cast<int>(val); }
```

All this is basically needed to handle enums properly because they (1) can be implicitly convertible to int and (2) can have overloaded operator<<.

**Comment by alabuzhev** [comment]
Thank you!

> All this is basically needed to handle enums properly

Shouldn't `is_enum` check go first then to not even try to instantiate all that magic for custom types?
This might also slightly improve the compilation time.

**Comment by vitaut** [comment]
> Shouldn't is_enum check go first then to not even try to instantiate all that magic for custom types?

Good idea. Done in https://github.com/fmtlib/fmt/commit/0ee4273b042d5ce8fc2da1542c942867797e0ae4.
