### ISSUE TITLE
Support types that are already convertible to strings without providing operator<<

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#651]
If a custom type provides `operator int()`, fmt is able to utilise it, which is nice.

However, if a custom type is implicitly convertible to one of the "string" types that fmt is aware of (basic_string, basic_string_view, const char_type*...) the library does nothing and still requires `operator <<`.

Please consider using an implicit conversion if `operator <<` is not available.

**Comment by vitaut** [comment]
It is already possible:

```c++
#include "fmt/format.h"

struct S {
  operator const char *() const { return "foo"; }
};

int main() {
  fmt::print("{}", "foo");
}
```

**Comment by alabuzhev** [comment]
Yes, it works with raw C strings indeed (apologies).

This, however, does not work:
```C++
struct S
{
	operator const std::string&() const
	{
		return str;
	}

	std::string str;
};

fmt::print("{}", S{});

```
`core.h(894): error C2665: 'fmt::internal::make_value': none of the 24 overloads could convert all the argument types`

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/18ac98700edc60a4401ebe18bff6a64420fe7e8c.

**Comment by alabuzhev** [comment]
Thank you!

Does it work for operator std::string_view too?

This doesn't compile:
```C++
struct s
{
	operator std::string_view() const
	{
		return std::string_view{ s };
	}
	std::string str;
};

auto str = format("{0}", s{});
```
> core.h(577): error C2440: 'static_cast': cannot convert from 'std::basic_string_view<char,std::char_traits<char>>' to 'const std::basic_string<char,std::char_traits<char>,std::allocator<char>> &'

It's convenient to have std::string_view operator instead of std::string as it cam be much cheaper.

**Comment by vitaut** [comment]
Oops, missed that. Should be fixed in https://github.com/fmtlib/fmt/commit/24d249b0b44fa74aeb0604aabf6b00d41dd29b44. Thanks!

**Comment by alabuzhev** [comment]
Thank you!
