### ISSUE TITLE
Arguments serialization/deserialization into custom byte buffer

### ISSUE THREAD

**Issue by chronoxor** [fmtlib/fmt#652]
Hello!

I have some code that serializes arguments into byte buffer and deserialize them in separate logging thread to perform format and IO. The problem that API changed. Maybe it possible to do serialization/deserialization much more easier? Or I have to adapt my code carefully to the new API?

[serialization.txt](https://github.com/fmtlib/fmt/files/1724462/serialization.txt)

**Comment by vitaut** [comment]
I think the easiest way to pass objects to another thread for formatting is by using a tuple:

```c++
template <typename... Args>
auto capture(const Args&... args) {
  return std::make_tuple(args...);
}

auto log_message = [](const auto&... args) {
  fmt::print(args...);
};

int main() {
  auto args = capture("{} {}", 42, "foo");
  // in another thread:
  std::apply(log_message, args);
}
```

Unlike serialization of `format_args`, this will work with any argument type and is way simpler. You may just add projection of some argument types, for example converting `const char*` to `std::string`.

**Comment by chronoxor** [comment]
The problem that I use async logging and want to store different formatting string and arguments in some buffer (I take care to have only base types and not to have some danger objects that can be out of scope) and then restore them, perform formatting and IO in background string.

Creating lambda and passing it into logging thread it not my way because of performance issues (heap allocation for params). I'll try to analyse all changes in internal api any try to adapt by serialization code.
 
And I want to know are you planning to continue change fmt lib heavy in near future or you finished and perform just cosmetic changes?

**Comment by vitaut** [comment]
> And I want to know are you planning to continue change fmt lib heavy in near future or you finished and perform just cosmetic changes?

The current development (`master`) branch is tracking the standards proposal http://fmtlib.net/Text%20Formatting.html and might change depending on the outcome of the standards committee meeting in Jacksonville in mid March. If you are interested in a stable version, I recommend using version 4.1 available from the [Releases page](https://github.com/fmtlib/fmt/releases/tag/4.1.0). The 4.x branch API is frozen and won't change.

**Comment by chronoxor** [comment]
Wow that's cool! I wish you to successfully finished all proposals and to get close to standard!

Then I'll continue with serialization a little bit later. I've already forked 4.x into my github. And my production build ships with it.

Good luck!

**Comment by vitaut** [comment]
Thanks!
