### ISSUE TITLE
Support switch-like formatting syntax

### ISSUE THREAD

**Issue by feroldi** [fmtlib/fmt#654]
```c++
fmt::format("Hello {0:world|1:people}", i);
```

Depending on `i`'s value, the formatter's output would equal `"Hello world"` or `"Hello people"`. The grammar used in the above example is merely for illustration, so it's subjective to change. I've needed this feature a few times, specially in cases where I only have information about `i`'s value, but not the string it represents.

I don't have any implementation for demonstration yet.

**Comment by vitaut** [comment]
I am not sure if this should be a part of the core library but you can already get similar effect in two ways:

1. Move condition out of the format string:

   ```c++
   fmt::format("Hello {}", i ? "world" : "people");
   ```

2. Define a type to represent the value you are switching on and use the extension API to parse corresponding format string:

   ```c++
   struct selector { int i; };
   namespace fmt {
   struct formatter<selector> {
     auto parse(fmt::parse_context &ctx) {
       // Parse the format specifiers (ctx.begin() will point to "0:world|1:people").
     }

     template <typename FormatContext>
     auto format(selector s, FormatContext& ctx) {
       // Write the selected value to the output iterator ctx.begin().
     }
   };
   }
   fmt::format("Hello {:0:world|1:people}", selector(i));
```
