### ISSUE TITLE
Not compatible with VS2017 string_view

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#657]
In VS2017 `basic_string_view::iterator` is not a raw pointer but an internal class, `_String_view_iterator`.

fmt does not expect that and fails to compile:

> format.h(3119): error C2664: 'void fmt::basic_parse_context<char,fmt::internal::error_handler>::advance_to(std::_String_view_iterator<_Traits>)': cannot convert argument 1 from 'const char *' to 'std::_String_view_iterator<_Traits>

**Note**: there is a flaw in the current build system: VS2017 only provides <string_view> header if `/std:c++latest` is specified. fmt, however, does not set that flag and therefore uses it's own, "fallback" string_view implementation, which renders this issue invisible for your build system.

**Comment by vitaut** [comment]
Fixed by using fallback string_view (#664). Thanks for reporting!
