### ISSUE TITLE
`fmt::join` helper overloads gated with `FMT_HAS_GXX_CXX11`

### ISSUE THREAD

**Issue by TheOnlyRew** [fmtlib/fmt#659]
The salient line in format.h (ce4a65f is master at the time of writing);
https://github.com/fmtlib/fmt/blob/ce4a65f/include/fmt/format.h#L3230

This `#if` block caused a rather surprising behavioral difference between Apple clang-900.0.39.2 (9.0.0) and MSVC 19.13.26118.0 (which I believe is 15.3, I'll double check what that builder is using and update this issue). The below lines compile cleanly in clang, but not MSVC;
```
std::vector<std::string>> foo {"a", "b", "c"};
fmt::join(foo , ", ");
```

Removing the `#if` block allows the above to compile in MSVC, so I'm not sure why that particular symbol was used to gate the two-argument overloads. I'm guessing the intention was to avoid compiling the C++11 trailing-return when not building in a >=C++11 context, but I have to imagine a more correct check could be used.

I didn't see anything in format.h that would be immediately more correct, so it may be the case that another `#if (__cplusplus >= 12345 || FMT_MSC_VER >= 6789)` is needed.

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/a7ae5666a02b1b9cee5e44a07758dcaa244b5b62. Thanks for reporting.
