### ISSUE TITLE
Dev documentation broken

### ISSUE THREAD

**Issue by beojan** [fmtlib/fmt#663]
The documentation at http://fmtlib.net/dev is broken (presumably since the `std` branch was merged).

**Comment by vitaut** [comment]
Yes, I'm working on it. The dust from the `std` merge hasn't settled yet.

**Comment by vitaut** [comment]
The documentation should be mostly working now except for the Write API which is still WIP.

**Comment by beojan** [comment]
There are still a couple of doxygen warnings elsewhere:
```


Warning

doxygenclass: Cannot find class “fmt::ArgVisitor” in doxygen xml output for project “format” from directory: /home/travis/build/fmtlib/fmt/doxyxml

Warning

doxygenclass: Cannot find class “fmt::arg_formatter_base” in doxygen xml output for project “format” from directory: /home/travis/build/fmtlib/fmt/doxyxml
```

**Comment by vitaut** [comment]
The dev documentation should be working now. Thanks for reporting!
