### ISSUE TITLE
Argument collections

### ISSUE THREAD

**Issue by rokups** [fmtlib/fmt#666]
Is it possible to have reusable argument collections? For instance i would like to do this:

```cpp
auto vars = fmt::args(
    fmt::arg("foo", "bar"),
    fmt::arg("foo2", "bar2")
);
// Or if my other suggestion was accepted it could look just like initializing `std::map`:
auto vars = fmt::args({
    {"foo", "bar"},
    {"foo2", "bar2"}
});

fmt::format("{foo} {foo2}", vars);
fmt::format("{foo2} {foo}", vars);
```

I tried making such `fmt::args` function from `FMT_VARIADIC_` macro returning `fmt::ArgList`, however i bumped into strange crashes and errors. Is there something that i am unaware of preventing such usage? This is what i tried:
```cpp
template <typename... Args> fmt::ArgList args(const Args&... args)
{
    typedef fmt::internal::ArgArray<sizeof...(Args)> ArgArray;
    typename ArgArray::Type array{
      ArgArray::template make<fmt::BasicFormatter<char> >(args)...};
    return fmt::ArgList(fmt::internal::make_type(args...), array);
}
```

Nature of application i work on is such that many format strings share same arguments so reusing them would be extremely convenient.

**Comment by vitaut** [comment]
Generally no because argument lists store references to, not copies of arguments so it's unsafe to store and reuse them. If you want to capture arguments safely, just use a tuple as shown in https://github.com/fmtlib/fmt/issues/652#issuecomment-366551952.

**Comment by rokups** [comment]
Oh that might be good enough. Thank you very much for clarification.

**Comment by rokups** [comment]
Hey @vitaut i just noticed that `std::apply` is c++17-only. Any idea if this is doable with c++11 somehow?

**Comment by vitaut** [comment]
Should be doable in C++11, see https://stackoverflow.com/a/7858971/471164 for example.

**Comment by sinall** [comment]
This is very useful feature, could you please consider having such API?

**Comment by vitaut** [comment]
@sinall, it already works with the current API, see comments above.
