### ISSUE TITLE
Recommended method for adding formatter for third-party custom type

### ISSUE THREAD

**Issue by mikecrowe** [fmtlib/fmt#669]
I'd like to add a formatter for std::chrono::duration in the style of https://github.com/fmtlib/fmt/issues/392 . This is straightforward to do:

```C++
template <typename Rep, typename Period>void format_arg(fmt::BasicFormatter<char> &f,                                                                                                                                             
                const char *&format_str, const std::chrono::duration<Rep, Period> &ms) {
    f.writer().write("{}s", std::chrono::duration<double>(ms).count());
}
```

But, in order for argument-dependent lookup to work, this function needs to either be in the `fmt` or `std::chrono` namespaces. I don't believe that I'm [supposed](http://en.cppreference.com/w/cpp/language/extending_std) to put it in the `std` namespace, so that leaves putting it in `fmt`. Is that acceptable, or is there a better way?

Thanks.

Mike.

**Comment by vitaut** [comment]
> Is that acceptable, or is there a better way?

Defining extension functions in the `fmt` namespace is perfectly acceptable.

Note, however, that the extension API will change in the next major version to accommodate constexpr format string checks and output iterators per standards committee feedback. The API is still WIP, but will likely look as follows: http://fmtlib.net/dev/api.html#formatting-user-defined-types. The 4.x branch will remain supported for compatibility with older compilers so migration to the new API is optional.

**Comment by mikecrowe** [comment]
Thanks for the quick answer!

Mike.
