### ISSUE TITLE
fmt::hex doesn't compile with fmt::MemoryWriter.write()

### ISSUE THREAD

**Issue by dwwork** [fmtlib/fmt#672]
The MemoryWriter class doesn't compile when trying to output a fmt::hex object using the write() API. Take the following example:

```cpp
MemoryWriter w; 
w << 42;      // Works
w << fmt::hex(42); // Works
w.write("{}",fmt::hex(42)); // Compile Error
```

I'm using 4.1.0 and g++ 4.8.5.

The resulting error message is in format.h:1330 , saying error: size of array is negative.
The offending line is:
`typedef int FMT_CONCAT_(Assert, __LINE__)[(cond) ? 1 : -1] FMT_UNUSED`

I can get around the issue in my code, using the << operator, but it is ugly.
Any thoughts on why this might be happening?

Thanks.

Dalon

**Comment by vitaut** [comment]
The write function accepts format strings rather than iostream-like "manipulators" (https://godbolt.org/g/sjRwz2), for example:

```c++
#include <fmt/format.h>

int main() {
  fmt::MemoryWriter w; 
  w.write("{:x}", 42); 
}
```

See also http://fmtlib.net/4.1.0/api.html#_CPPv2N3fmt11BasicWriter5writeE15BasicCStringRefI4CharE7ArgList

**Comment by dwwork** [comment]
Ah okay I understand now. Thanks!
