### ISSUE TITLE
Problem when used as shared library and use gold linker to link with application

### ISSUE THREAD

**Issue by zzhang97** [fmtlib/fmt#673]
Summary:
When I build "fmt" as a shared library and use "[gold](https://en.wikipedia.org/wiki/Gold_(linker))" linker to link application code with libfmt.so, certain static variables are not properly initialized causing integer formatting not working.

Setup:
OS: linux
fmt: 4.1.0 release, built from source into shared library, used "cmake -DBUILD_SHARED_LIBS=TRUE"
gcc/g++: 5.4.0
gold: GNU gold (GNU Binutils for Debian 2.22) 1.11

Application code example, test.cpp:

```
#include <iostream>
#include <fmt/format.h>

int main() {
    std::clog << "DIGITS: " << fmt::internal::BasicData<void>::DIGITS << std::endl;
    std::clog << "POWERS_OF_10_32: " << fmt::internal::BasicData<void>::POWERS_OF_10_32[1] << std::endl;
    std::clog << "Example:" << fmt::format("{}", 123456) << std::endl;
    return 0;
}

```

What's not working: use gold as linker:
```
$ g++ -fuse-ld=gold test.cpp -lfmt  && ./a.out 
DIGITS: 
POWERS_OF_10_32: 0
Example:
```
It shows formatting "123456" does not work as expected. And reason is that the fmt::internal::BasicData<void> data structure is not initialized.

In contrast, what's working: use ld as linker:
```
$ g++ test.cpp -lfmt  && ./a.out 
DIGITS: 00010203040506070809101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899
POWERS_OF_10_32: 10
Example:123456
```

**Comment by vitaut** [comment]
What Linux distro and version are you using?

**Comment by zzhang97** [comment]
Debian 2.22

**Comment by vitaut** [comment]
2.22 seems like glibc version. I was more interested in the [release of Debian](https://www.electrictoolbox.com/debian-release-names/) you use e.g. Stretch, Jessie or other.

**Comment by zzhang97** [comment]
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"

```

**Comment by vitaut** [comment]
It seems like a bug in gold and in the new version of the linker (1.15) this works:
```
$ g++-5 -fuse-ld=gold test.cc -lfmt -I. -Lfmt
$ ./a.out
DIGITS: 00010203040506070809101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899
POWERS_OF_10_32: 10
Example:123456
$ gold --version
GNU gold (GNU Binutils for Debian 2.30) 1.15
```

As a workaround you can use {fmt} as a static or even header-only library.

**Comment by zzhang97** [comment]
Thank you for your troubleshooting.
Let me try a newer version of gold.
Yes I'm already using header-only as a work-around.

**Comment by vitaut** [comment]
Closing because this doesn't appear to be a bug in the library.
