### ISSUE TITLE
Allocated buffer of size UINT_MAX

### ISSUE THREAD

**Issue by sth** [fmtlib/fmt#675]
A 4GB buffer is allocated internally when formatting this:

    fmt::format("{:= }", 1.0)

In [format.h:2790][1], `as.width_` is zero and wraps to `UINT_MAX` when being decremented.

I'm not sure if the calculation is also off by one in other cases.

 [1]: https://github.com/fmtlib/fmt/blob/9facc119a603824b3c5063b31a9b4508c68d4dc1/include/fmt/format.h#L2790

**Comment by vitaut** [comment]
Great catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/7db0e94b9e5a54efcee27ebd6abb344836b68c8e.
