### ISSUE TITLE
request: move the print function out of the shared library

### ISSUE THREAD

**Issue by nolange** [fmtlib/fmt#677]
I have a weird request, namely to remove the definitions from some small functions (print, print_colored) from the implementation and move them into the header as inline-function.

reason is that this would be beneficial in case you need the ability to run different C libraries (and variants thereof), removing all hard "hooks" is the easiest way to do that.
more specifically my use-case is Xenomai, and this will wrap the standard C library functions to some real-time capable stubs, but this wrapping of course does not affect previously compiled libraries.

Having the "glue" to the output functions in your app is an easy way to maybe the library agnostic to whether its running in RT or Linux.

If that's not an option, I already made a stub solving this for myself, please tell me if this is a sane way or if it depends on interna that might change.

```cxx
namespace myns
{
void print(std::FILE *f, fmt::CStringRef format_str, fmt::ArgList args) {
  fmt::MemoryWriter w;
  w.write(format_str, args);
  ::fwrite(w.data(), 1, w.size(), f);
}

FMT_FUNC void print(fmt::CStringRef format_str, fmt::ArgList args) {
    myns::print(stdout, format_str, args);
}

FMT_VARIADIC(void, myns::print, fmt::CStringRef)
}
```

**Comment by vitaut** [comment]
Thanks for the suggestion. You can already do this by using the header-only version of the library.

> please tell me if this is a sane way or if it depends on interna that might change.

This is fine too and it doesn't rely on internal API. It will change in the next major version which is based on the standards proposal http://fmtlib.net/Text%20Formatting.html, but you can continue using the 4.x branch which will continue to be supported for compatibility with older compilers.

**Comment by nolange** [comment]
Hello,

First I dont know whether there is a better place to ask, is there a forum of some sorts?
The std proposal seems to omit the print method, is this on purpose or will it be back?

I would prefer not using std::string (or other immediate storage) and instead dump everything to a file descriptor or shared memory.

eg. I would want to write a function similar to this:
```c++
inline int myprint(FILE *f, string_view format_str, format_args args) {
  memory_buffer buffer;
  vformat_to(buffer, format_str, args);
  return fwrite(buffer.begin(), 1, buffer.size(), f);
}
```

I am aware that I could implement an own buffer, but it would be nice if I could use the memory_buffer from the fmt implementation. AFAIK this is not possible yet (as not defined in the proposal). Would be nice if some capability would be available - one option is having the type standardized so the implementation above would be conform.

Or keep the memory_buffer private, and provide piping the result into an function object/lambda accepting a string_view.

```c++
template <typename TSink, typename TChar = char>
inline auto fmt_output(TSink &&sink, string_view format_str, format_args args) {
  basic_memory_buffer<TChar> buffer;
  vformat_to(buffer, format_str, args);
  return sink(basic_string_view<TChar>(buffer.begin(), buffer.size()));
}
```

**Comment by vitaut** [comment]
> First I dont know whether there is a better place to ask, is there a forum of some sorts?

Yes, there is a Gitter chat: https://gitter.im/fmtlib/fmt

> The std proposal seems to omit the print method, is this on purpose or will it be back?

This is on purpose. The paper deals only with formatting and intentionally avoid anything related to I/O and special containers because these features are orthogonal. However, you can easily implement a print function on top of the provided iterator-based API (https://godbolt.org/g/pJkRfX):

```c++
#include <vector>
#include <fmt/format.h>

template <typename... Args>
int myprint(FILE *f, fmt::string_view format_str, const Args&... args) {
  std::vector<char> buffer;
  fmt::format_to(std::back_inserter(buffer), format_str, args...);
  return fwrite(&buffer[0], 1, buffer.size(), f);
}

int main() {
  myprint(stdout, "{}", 42);
}
```

**Comment by vitaut** [comment]
You can continue to use the {fmt}'s `basic_memory_buffer`. Also there is a standards proposal for pretty much the same container: https://github.com/gnzlbg/fixed_capacity_vector
