### ISSUE TITLE
macos 10.13.3 link issue 

### ISSUE THREAD

**Issue by chiumichael** [fmtlib/fmt#683]
hi all,

fmt seems to build properly, but when i try to link it, i get weird errors like

`/Library/Developer/CommandLineTools/usr/include/c++/v1/stdexcept:83:32: error: unknown type name 'string'
    explicit logic_error(const string&);`

which seems to be related to some macos-specific C libraries for some reason. ive scoured the web for similar issues in other projects and they suggest adding `-D_DARWIN_C_SOURCE` to the cxxflags

which i did with

`set(CMAKE_CXX_FLAGS "-D_DARWIN_C_SOURCE")`

any help would be appreciated, tx.

**Comment by vitaut** [comment]
What version of {fmt} and what compiler version do you use?

**Comment by chiumichael** [comment]
fmt 4.1.0 and Apple LLVM version 9.0.0 (clang-900.0.39.2)

**Comment by vitaut** [comment]
Could you post the build commands to reproduce the error?

I tried to repro on macOD 10.13.3 with clang-900.0.39.2, but the following works:
```
wget https://github.com/fmtlib/fmt/releases/download/4.1.0/fmt-4.1.0.zip
unzip fmt-4.1.0.zip
cd fmt-4.1.0/
cmake .
make
```

**Comment by chiumichael** [comment]
thanks for the quick reply. and sorry for this. i had a dumb issue while linking. it works perfectly!!

**Comment by chiumichael** [comment]
thanks for the quick reply. and sorry for this. i had a dumb issue while linking. it works perfectly!!
