### ISSUE TITLE
Implementation of basic_string_view clashes with std

### ISSUE THREAD

**Issue by Kronuz** [fmtlib/fmt#686]
I had to remove the implementation of ``std::basic_string_view`` for pre-C++17 since it didn't allow me to pass string_view object to `fmt`, it said (it didn't know how to convert from `basic_string_view` to `basic_string_view`). After that, it worked.

**Comment by vitaut** [comment]
There is an implicit conversion from `std::basic_string_view` to `fmt::basic_string_view`: https://github.com/fmtlib/fmt/blob/84e520b79c9c894c6e71a979660fc1278e032dd4/include/fmt/core.h#L240 so the following should work:

```c++
fmt::format(std::string_view("{}"), 42);
```
provided that `string_view` is detected on your platform. Which compiler version do you use?

**Comment by Kronuz** [comment]
I’m using clang 5 in macOS it didn’t work until I removed the custom basic_string_view; and apparently it did detect it.

**Comment by vitaut** [comment]
Hmm, according to godbolt `std::string_view` is detected and works: https://godbolt.org/g/3n2XBe

Could you post a reproducible example and the full error message?

**Comment by Kronuz** [comment]
Done! Probably detection isn’t lacking, since std::string_view is available since c++14 in clang 4 and 5. Simply change to `-std=c++14` so you see it fail (note it does have `std::string_view` available anyway)

**Comment by vitaut** [comment]
C++14 doesn't have `std::string_view`, so the error is expected. You can use `std::experimental::string_view` with C++14: https://godbolt.org/g/eFMRTQ

**Comment by Kronuz** [comment]
...well, I’m successfully using std::string_view all over the place in clang 4 and 5 c++14, so I guess we could support it too, couldn’t we?

**Comment by vitaut** [comment]
What compiler flags do you use? `std::string_view` is not supported with `-std=c++14`: https://godbolt.org/g/LLKw3P

**Comment by mwinterb** [comment]
libc++ supports it in C++14, and apparently back to C++03, see
https://github.com/abseil/abseil-cpp/issues/2

**Comment by Kronuz** [comment]
https://wandbox.org/permlink/5wvB24tzaF3ggxgb

**Comment by vitaut** [comment]
Fixed, thanks for reporting!
