### ISSUE TITLE
Visual Studio Warning 4244

### ISSUE THREAD

**Issue by sebkoenig** [fmtlib/fmt#688]
I get a warning 4244: "conversion from 'const wchar_t' to 'char', possible loss of data", during instantiation of the template `padded_int_writer<char*>`

```
  template <typename F>
  struct padded_int_writer {
    string_view prefix;
    wchar_t fill;
    std::size_t padding;
    F f;

    template <typename It>
    void operator()(It &&it) const {
      if (prefix.size() != 0)
        it = std::copy_n(prefix.data(), prefix.size(), it);
      it = std::fill_n(it, padding, fill);  // <-- warning 4244
      f(it);
    }
  };
```
Calling std::fill_n with (char*, size_t, wchar_t) will lead to implicit conversion from wchar_t to char which Visual Studio warns about.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/a24005d5fd74d6cbd60aad9252ce1ba022c7a934, thanks for reporting!
