### ISSUE TITLE
FormatError when formatting empty std::string_view

### ISSUE THREAD

**Issue by dermojo** [fmtlib/fmt#689]
When trying to format an empty string_view, fmtlib raises a FormatError because the contained pointer is nullptr. Minimal example:

```
#include <string_view>
#include <fmt/format.h>

int main()
{
  std::string_view x;
  fmt::print("{}\n", x);
  return 0;
}
```

I'd expect an empty string to be printed.

**Comment by vitaut** [comment]
Good catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/8c29459eda1d9f846afef43892b5777f410d2743.

**Comment by dermojo** [comment]
Thanks!
