### ISSUE TITLE
[feature request] Allow CMake to find fmt via find_package

### ISSUE THREAD

**Issue by omtcvxyz** [fmtlib/fmt#695]
As [usage page](http://fmtlib.net/latest/usage.html#header-only-usage-with-cmake) suggests fmtlib should be used via `add_subdirectory(fmt)` in CMake. While this is a viable solution, this certainly not a very practical one. I would very much like to have a FindFMT.cmake provided for CMake's [find_package](https://cmake.org/cmake/help/latest/command/find_package.html).

There is a [simple script](https://github.com/fmtlib/fmt/issues/133#issuecomment-264416560) found on the Issue tracker, it's probably not optimal but it could be a good start.

**Comment by vitaut** [comment]
Thanks for the suggestion. Could you by any chance submit a PR?

**Comment by omtcvxyz** [comment]
I'm honestly not very good at writing idiomatic CMake scripts and do not know too much from the developer's (as opposed to user's) perspective, but I'll try to do that when I have some spare time.

A friend of mine suggested that a better way to allow finding the package is `${package}Config.cmake` and config mode (see [config-file packages](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#config-file-packages) and [find-package](https://cmake.org/cmake/help/latest/command/find_package.html#command:find_package) for refernece). I might have to carefully study those myself before producing something useful.

In the meantime if anybody willing to contribute sees it - feel free to send a PR if there isn't one yet!

**Comment by henryiii** [comment]
This might help in making a Config script:
https://cliutils.gitlab.io/modern-cmake/chapters/install/installing.html

(And yes, a library author should write a Config, not a Find script).

**Comment by vitaut** [comment]
There is a package config file already https://github.com/fmtlib/fmt/blob/48ae0506de166a2915257f01bb135cebf3f907ce/CMakeLists.txt#L171 so I'm closing the issue, but any improvements are welcome.
