### ISSUE TITLE
Support for char16_t/u16string?

### ISSUE THREAD

**Issue by Boddlnagg** [fmtlib/fmt#698]
What would be the easiest way to use `fmt::format` and `fmt::print` with strings based on char16_t?

`fmt::format("{}", "foo");` and `fmt::format(L"{}", L"foo");` both work, but `fmt::format(u"{}", u"foo");` does not.

**Comment by vitaut** [comment]
In theory it should be possible to do as follows:

```c++
#include "fmt/format-inl.h"

typedef fmt::basic_string_view<char16_t> u16string_view;
typedef fmt::buffer_context<char16_t>::type u16context;

std::u16string vformat(u16string_view format_str,
                       fmt::basic_format_args<u16context> args) {
  fmt::basic_memory_buffer<char16_t> buf;
  // Need to simplify this part and avoid reliance on internal API.
  typedef fmt::back_insert_range<fmt::internal::basic_buffer<char16_t>> range;
  fmt::vformat_to<fmt::arg_formatter<range>>(buf, format_str, args);
  return to_string(buf);
}

template <typename... Args>
inline std::u16string format(u16string_view format_str, const Args & ... args) {
  return vformat(format_str, fmt::make_format_args<u16context>(args...));
}
```

However, it doesn't work at the moment because `std::numpunct<char16_t>` doesn't exist for some reason.

**Comment by vitaut** [comment]
There is also a problem with `char_traits::format_float` which needs to be specialized for `char16_t` but the latter can probably be solved by formatting into a char buffer and then copying (since there is no `(s)printf` overload or equivalent for `char16_t`).

**Comment by vitaut** [comment]
Floating-point formatting should work with all character types now and with @DanielaE's recent changes everything is now parameterized on string type. So it only remains to make locale support character-independent.

**Comment by vitaut** [comment]
`char16_t`/`u16string`, `char32_t`/`u32string` as well as other character and string types are supported as of https://github.com/fmtlib/fmt/commit/324eac1aa5b5328a274bb50b1ecf154d3c9b6607, for example:

```c++
std::u16string s = fmt::format(u"{The answer is {}.}", 42);
```
