### ISSUE TITLE
GCC version is wrongly calculated

### ISSUE THREAD

**Issue by Kronuz** [fmtlib/fmt#699]
It should be calculated as:

```
# define FMT_GCC_VERSION (__GNUC__ * 100 + __GNUC_MINOR__ * 10 + __GNUC_PATCHLEVEL__)
```

**Comment by Kronuz** [comment]
...although that probably won’t work for versions with minor numbers above 9; but for gcc 5.5.0, for example, the current FMT_GCC_VERSION is 505.

**Comment by vitaut** [comment]
`FMT_GCC_VERSION` is an implementation details and `__GNUC_PATCHLEVEL__` is not used, so there is no need to change.
