### ISSUE TITLE
string_view is not detected for GCC 5.5

### ISSUE THREAD

**Issue by Kronuz** [fmtlib/fmt#700]
GCC 5.5 has `<experimental/string_view>` available, yet fmt doesn’t detect this.

This issue is similar to fmt not detecting `<strig_view>` under clang 4; so I wonder... why not simply use and trust `__has_include` when available?

**Comment by Kronuz** [comment]
Apparently <experimental/string_view> is available since gcc 4.9

**Comment by vitaut** [comment]
The use of experimental `string_view` was explicitly disabled because on GCC version prior to 7.3 it was not `constexpr`-ready. However, now that `fmt::string_view` is used to pass format strings, this restriction can be removed.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/44cc0346519707402f233713575dbe544124835c, thanks for reporting!
