### ISSUE TITLE
Failed to compile my code because fmt::MemoryWriter class is removed

### ISSUE THREAD

**Issue by hungptit** [fmtlib/fmt#710]
I use fmt::MemoryWriter in my projects and this class is removed recently. What is the replacement?

**Comment by christianparpart** [comment]
`fmt::basic_memory_buffer`

http://fmtlib.net/dev/api.html#_CPPv2N3fmt19basic_memory_bufferE

**Comment by hungptit** [comment]
fmt::basic_memory_buffer is not 100% compatible to fmt::MemoryWriter. However, I do like the new syntax. Thank a lot for the information.
