### ISSUE TITLE
fmt::scan

### ISSUE THREAD

**Issue by gsliepen** [fmtlib/fmt#711]
I would really like to see fmtlib also support scanning, aka. a type-safe `scanf()` replacement, so that you could write something like:

    std::string foo = fmt::format("{} = {}", "answer", 42);
    std::string variable;
    int value;
    int conversions = fmt::scan(foo, "{} = {}", variable, value);
    assert(conversions == 2);
    assert(variable == "answer");
    assert(value == 42);

Is something like this already planned?

**Comment by vitaut** [comment]
> Is something like this already planned?

Interesting idea. There are no plans to add anything like this at the moment and I think it's a bit out of scope of the current project. Despite some similarities in the API, I don't think it will be even possible to reuse the argument handling API.

**Comment by myrgy** [comment]
maybe related: https://github.com/afborchert/fmt-scan

**Comment by mheiskan** [comment]
Also related:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1729r0.html
https://github.com/eliaskosunen/scnlib
