### ISSUE TITLE
Time formatting doesn't work with wide format strings

### ISSUE THREAD

**Issue by DanielaE** [fmtlib/fmt#713]
Similar to the API documentation:
```
auto t = std::time(nullptr);
// Prints "The date is 2016-04-29." (with the current date)
auto Result = fmt::format("The date is {:%Y-%B-%d}.", *std::localtime(&t));
auto wResult = fmt::format(L"The date is {:%Y-%B-%d}.", *std::localtime(&t));
```
The 3rd line compiles, the fourth doesn't. The custom formatter for `std::tm` can't deal with `wchar_t` format strings. My PR#712 rectifies this issue.

**Comment by vitaut** [comment]
Thank you for reporting and fixing this.
