### ISSUE TITLE
`FMT_USE_TRAILING_RETURN` not defined on clang, causes warnings

### ISSUE THREAD

**Issue by eliaskosunen** [fmtlib/fmt#715]
Please see this CE snippet: https://godbolt.org/g/CVWCax

As a solution, I propose either:
 * adding a macro `FMT_HAS_CXX11`, that checks for `__cplusplus` and/or compiler versions. 
 * defining `FMT_HAS_GXX_CXX11` as a non-zero value on clang as well

I'm not proposing:
 * defining `FMT_USE_TRAILING_RETURN` to zero instead of not defining it at all,

as this would lead to trailing returns to not be used on clang.

Once we reach a solution, I can submit a PR.

**Comment by eliaskosunen** [comment]
As an aside, to avoid these kinds of problems in the future, Travis CI could test with more compilers. At the moment, only g++-6 is used on Linux. Clang with `-Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-padded -Wno-exit-time-destructors` yields, in my opinion, much better warnings than g++.

**Comment by vitaut** [comment]
I think the simplest fix is to define `FMT_USE_TRAILING_RETURN` whenever `__has_feature(cxx_trailing_return)` is defined (in addition to the existing conditions). PR is welcome!
