### ISSUE TITLE
What is the merit/demerit of shared library version of fmt?

### ISSUE THREAD

**Issue by xylosper** [fmtlib/fmt#718]
Although fmt can be used as header-only library, it is possible to build fmt as shared library.
Usually, I expect from shared library:

Pros
* Reduced compile time overhead

Cons
* Relatively low performance for non-inlined function

Is there any other point to use fmt as a shared library?

**Comment by vitaut** [comment]
I don't think there will be noticeable performance difference because the functions that should be inlined are inlined in both cases.

> Is there any other point to use fmt as a shared library?

Not really, the main benefit is compile time but you can get the same with a static library which is the default.
