### ISSUE TITLE
Cannot compile format_test for GCC 7.1 with c++17 enabled

### ISSUE THREAD

**Issue by alexleemanfui** [fmtlib/fmt#722]
cd /root/fmt-4.1.0/build/test && /usr/bin/c++  -DFMT_USE_ENUM_BASE=1 -DFMT_USE_FILE_DESCRIPTORS=1 -DFMT_USE_TYPE_TRAITS=1 -DGTEST_HAS_STD_WSTRING=1 -I/root/fmt-4.1.0/test/. -I/root/fmt-4.1.0 rmat-test.dir/format-test.cc.o -c /root/fmt-4.1.0/test/format-test.cc
In file included from /root/fmt-4.1.0/test/gmock/gmock.h:238:0,
                 from /root/fmt-4.1.0/test/format-test.cc:41:
/root/fmt-4.1.0/test/format-test.cc: In member function ‘virtual void CStringRefTest_Ctor_Test::TestBody()’:
/root/fmt-4.1.0/test/format-test.cc:177:59: error: no matching function for call to ‘fmt::BasicCStringRef<char>::BasicCStringRef(std::basic_string_view<char>)’
   EXPECT_STREQ("hijk", CStringRef(std::string_view("hijk")).c_str());

**Comment by vitaut** [comment]
Thanks for reporting, this should be fixed in the [4.x branch](https://github.com/fmtlib/fmt/tree/4.x) already.
