### ISSUE TITLE
Support for ranges, containers and types with tuple interface. 

### ISSUE THREAD

**Issue by Remotion** [fmtlib/fmt#727]
[Here is C++17 code](https://github.com/Remotion/fmt_extension) add support for ranges, containers and types with tuple interface. 

May this could be added to fmt in one or another way.

**Comment by Morwenn** [comment]
Just dropping a link to [the Reddit discussion][1] which has some interesting comments which might also be discussed here :)

  [1]: https://www.reddit.com/r/cpp/comments/8gy8ne/fmt_support_for_ranges_containers_and_types_with/

**Comment by vitaut** [comment]
@Remotion, this is super cool!

> May this could be added to fmt in one or another way.

Definitely. I think this can be added in a separate header such as `fmt/ranges.h` or something (naming ideas are welcome). Could you submit a PR?

**Comment by Remotion** [comment]
Yes I will prepare PR. 

Do we also need structured binding support?  But it will be a bit macro heavy for now.

**Comment by vitaut** [comment]
> Do we also need structured binding support?

I'm not sure. How would structured building support look like from the user perspective?

**Comment by vitaut** [comment]
Yeah, let's focus on ranges first.

**Comment by vitaut** [comment]
Closing since #735 has been merged. Thanks again!
