### ISSUE TITLE
Version 5 status

### ISSUE THREAD

**Issue by ukreator** [fmtlib/fmt#737]
Hi,
We're planning to include fmtlib into our new project but not sure which version to use (4.1 vs master). The project will not be used in production for some time, so maybe it makes sense to use current master and then just switch to version 5 right away instead of fixing every invocation of ```fmt::*``` later.

Any ETA for version 5.0 stabilisation? Maybe add a few words in README about current status and what are the plans for supporting old API?

Thanks

**Comment by vitaut** [comment]
I plan to release version 5.0 within the next few weeks. The 4.x branch will continue to be maintained because it provides legacy compiler support, but if you don't need that I recommend using `master` or waiting to version 5.0.

**Comment by ukreator** [comment]
Got it, thanks!
