### ISSUE TITLE
format_arg weirdness

### ISSUE THREAD

**Issue by dimavs** [fmtlib/fmt#741]
There are couple of weird issues with format_arg and user-defined types.

First, format_arg must be either in global or fmt::internal namespace or it can't be found. API page example puts it into user namespace (local) - http://fmtlib.net/latest/api.html

Second, format_arg function must consume format_spec from format_str, cause of this line https://github.com/fmtlib/fmt/blob/4.x/fmt/format.h#L3885, which is also missed in examples.

That's actually a testcase which fails

```
template <typename Char>
void format_arg(fmt::BasicFormatter<Char> &f, const Char *, Answer) {
  f.writer() << "42";
}

TEST(FormatterTest, CustomFormat) {
  EXPECT_EQ("42   ", format("{0:<5}", Answer()));
}
```

And this testcase works fine:
```
template <typename Char>
void format_arg(fmt::BasicFormatter<Char> &f, const Char *& format_str, Answer) {
  format_str = f.format(format_str, fmt::internal::MakeArg<fmt::BasicFormatter<Char>>("42"));
}

TEST(FormatterTest, CustomFormat) {
  EXPECT_EQ("42   ", format("{0:<5}", Answer()));
}

```

**Comment by vitaut** [comment]
> First, format_arg must be either in global or fmt::internal namespace or it can't be found.

`format_arg` should be in the same namespace as the argument type and found by ADL, see https://godbolt.org/g/845ZdF for an example.

> Second, format_arg function must consume format_spec from format_str

Yes, `format_arg` should parse the passed format string if that's what you mean.

**Comment by dimavs** [comment]
> format_arg should be in the same namespace as the argument type
Ah, yeah, sorry, my bad

> Yes, format_arg should parse the passed format string if that's what you mean.
It should not only parse it, it must update it. I'll create a patch with failing test today later today.

**Comment by vitaut** [comment]
Closing per comment above, but a PR to clarify the 4.x documentation is welcome.
