### ISSUE TITLE
No __cpp_lib_integer_sequence in Visual Studio .

### ISSUE THREAD

**Issue by Remotion** [fmtlib/fmt#746]
https://github.com/fmtlib/fmt/blob/6ebc1a967d9a54f8209b3c415039aff3979dd762/include/fmt/ranges.h#L131

This test do not work for Visual Studio. It does not support feature detection macros.

**Comment by foonathan** [comment]
The newest/next version will FWIW.

**Comment by DanielaE** [comment]
Any references for that claim? SD6 isn't even part of the standard yet.

**Comment by foonathan** [comment]
https://twitter.com/StephanTLavavej/status/996826195193819137?s=19

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/147807c9115dc13edc04d5f951b571d64083a9a5, thanks!
