### ISSUE TITLE
Strings in ranges/containers should be in quotes

### ISSUE THREAD

**Issue by SuperWig** [fmtlib/fmt#747]
Using the example but with std::string
   
    #include <fmt/ranges.h>

    std::vector<std::string> v = {"1", "hello", "3"};
    fmt::print("{}", v); // prints {1, hello,  3}
Whereas I think it should print `{"1", "hello", "3"}`.

**Comment by Remotion** [comment]
I need to agree. Especially looking at example code below. 

`    std::tuple<std::string, int, float, const char*> t{"1", 1, 1.0, "1"};
    fmt::print("{}\n", t); // prints (1, 1, 1, 1)
`

**Comment by vitaut** [comment]
Good idea, PRs are welcome!

**Comment by Remotion** [comment]
Once I get some time I will make PR for this.

**Comment by SuperWig** [comment]
Well I added single quote's for char's.

**Comment by Remotion** [comment]
Well here is PR for this  
https://github.com/fmtlib/fmt/pull/763

**Comment by SuperWig** [comment]
>What happens exactly and how ?
```
wchar_t wch{ L'c' };
fmt::print(L"{}\n", wch);

std::vector<wchar_t> wch_vec{ L'W', L'c'};
fmt::print(L"{}\n", wch_vec);
```
For the vector I get
> error: request for member 'begin' in 'range', which is of non-class type 'const wchar_t'
> error: request for member 'end' in 'range', which is of non-class type 'const wchar_t'

Also shouldn't strings be in double quotes and chars in single? As opposed to both in single?

**Comment by vitaut** [comment]
Done in #763 (thanks to @Remotion).
