### ISSUE TITLE
VisualStudio 15.7.x compilation error in /W4 /WX

### ISSUE THREAD

**Issue by christophe-calmejane** [fmtlib/fmt#748]
Using just released v5.0, I've got some compilation errors using VS15.7.x compiler when /W4 and /WX flags are set: "Unreachable code"

I've a workaround that consists of disabling this warning before including fmt, but it's not very "clean". Maybe there is a way to fix this warning (or to add the pragma push/disable/pop) directly in fmt headers.

This simple code (compiled in release) cause a compilation error with /W4 /WX:
`#include <fmt/format.h>
int main(int, char**)
{
	fmt::format("Test");
	return 0;
}
`

The current fix for this is (win32 only)
`#pragma warning(push)
#pragma warning(disable:4702)
#include <fmt/format.h>
#pragma warning(pop)
`

Haven't tested on clang/gcc yet.

**Comment by vitaut** [comment]
Could you post the full warning message? I don't have access to a Windows machine and the warning doesn't reproduce on godbolt: https://godbolt.org/g/c67EiY

**Comment by christophe-calmejane** [comment]
> 1>test.cpp
1>c:\dev\test\fmtlib\include\fmt\format.h(1672): error C2220: warning treated as error - no 'object' file generated
1>c:\dev\test\fmtlib\include\fmt\format.h(1672): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1672): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1672): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1672): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1672): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1672): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1672): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1672): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1672): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1648): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1648): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1648): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1648): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1648): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1648): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1648): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1648): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1648): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\core.h(744): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(1267): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(2004): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(2048): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(2062): warning C4702: unreachable code
1>c:\dev\test\fmtlib\include\fmt\format.h(2066): warning C4702: unreachable code
1>Done building project "Test.vcxproj" -- FAILED.

This is using commitID 5386f1df20392a08844f5034e8436c6ec7ce0b03 (release branch)

**Comment by mwinterb** [comment]
Does this occur with the optimizer disabled? If not, when the optimizer is
on, are you also compiling with link time code generation enabled?

**Comment by mwinterb** [comment]
Ah, header-only, that's probably why I haven't encountered it. What's
likely happening is the optimizer is seeing through the on_error
abstractions, seeing that they always throw, and reporting that the return
statements are unreachable. (Just to be needlessly clear on my part.)

It's probably reasonable for fmt to suppress that warning in header only
mode. I think the same problem would occur with LTCG/WPO, but I'm unaware
if Microsoft provides a way to introspect optimization levels at compile
time.

I don't see anything in #736 to explicitly address this case, but it is
well past my bedtime, so I may have missed it.

**Comment by christophe-calmejane** [comment]
Yeah sorry I should have pasted the cmake source before :)
Like I said, right now I've to disable the warnings (win32 only) before including fmt, so if it can be done directly in the header it would be better for everyone.
Ty (and gn)

**Comment by Remotion** [comment]
Can we simple use such such code to disable unreachable code warning ?

```cpp
#if _MSC_VER && !defined(__clang__) && !defined(__INTEL_COMPILER)
#pragma warning( push )
#pragma warning( disable: 4702 ) // unreachable code
#endif
```

```cpp
#if _MSC_VER && !defined(__clang__) && !defined(__INTEL_COMPILER)
#pragma warning( pop )
#endif // warning 4702 is back
```

**Comment by christophe-calmejane** [comment]
It's what I'm doing before including fmt (except I don't care about excluding vs_clang or intel, but the idea is here).

**Comment by vitaut** [comment]
@christophe-calmejane what's the complete list of command-line options passed to cl (in addition to /W4 /WX)? Maybe I could repro it on godbolt after all.

**Comment by christophe-calmejane** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\CL.exe /c /IC:\test\fmtlib\include /nologo /W4 /WX /diagnostics:classic /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D FMT_HEADER_ONLY=1 /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"Test.dir\Release\\" /Fd"Test.dir\Release\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:queue C:\test\test.cpp

**Comment by vitaut** [comment]
Had to temporarily revert part of the fix because of some MSVC issue, but will bring it back.

**Comment by vitaut** [comment]
On further inspection, it turned out that the above commit doesn't solve the issue, reopening.

**Comment by vitaut** [comment]
Here goes a proper fix: https://github.com/fmtlib/fmt/commit/252f11f85d33b8861f4b2b2409f1bc02f8d3fd89
