### ISSUE TITLE
Two warnings under NVCC

### ISSUE THREAD

**Issue by henryiii** [fmtlib/fmt#752]
When compiling with CUDA 8 and moving from fmt 4 to 5, I get hundreds of pages of warnings that I think boil down to two:

# 1

```
extern/fmt/include/fmt/core.h(978): warning: integer conversion resulted in a change of sign
```

https://github.com/fmtlib/fmt/blob/5386f1df20392a08844f5034e8436c6ec7ce0b03/include/fmt/core.h#L976-L979

I'm not sure how this could be correct, -int is returned as uint without explicit cast?

# 2

```
extern/fmt/include/fmt/core.h(791): warning: nonstandard use of "auto" to both deduce the type from an initializer and to announce a trailing return type
```

https://github.com/fmtlib/fmt/blob/5386f1df20392a08844f5034e8436c6ec7ce0b03/include/fmt/core.h#L789-L797

Could this odd auto and comma be replaced by a decltype? (and comma, unfortunately)

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/911a75114be6023538991f7f73bae1cdc9879ada, thanks.
