### ISSUE TITLE
Cannot print tuples

### ISSUE THREAD

**Issue by furkanusta** [fmtlib/fmt#760]
I've decided to new container and tuple printing. Although I can print vectors I couldn't make it work with tuple.

I have FMT_VERSION 50100
I've tried with both g++ 8.1 and clang 6.0 

```C++
#include <iostream>
#include <tuple>
#include <fmt/format.h>
#include <fmt/ranges.h>
#include <fmt/printf.h>

int main() {
    std::tuple<int, char> tup = {1, 'a'};
    fmt::print("{}\n", tup);
}

```

Output of gcc:

> In file included from /usr/local/include/fmt/format.h:40,
>                  from fmt.cpp:3:
> /usr/local/include/fmt/core.h: In instantiation of ‘static void fmt::v5::internal::value<Context>::format_custom_arg(const void*, Context&) [with T = std::tuple<int, char>; Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>]’:
> /usr/local/include/fmt/core.h:515:19:   required from ‘fmt::v5::internal::value<Context>::value(const T&) [with T = std::tuple<int, char>; Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>]’
> /usr/local/include/fmt/core.h:541:63:   required from ‘constexpr fmt::v5::internal::typed_value<Context, TYPE>::typed_value(const T&) [with T = std::tuple<int, char>; Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>; fmt::v5::internal::type TYPE = (fmt::v5::internal::type)13]’
> /usr/local/include/fmt/core.h:637:37:   required from ‘typename std::enable_if<((! fmt::v5::internal::convert_to_int<T, Char>::value) && (! std::is_convertible<T, fmt::v5::basic_string_view<Char> >::value)), fmt::v5::internal::typed_value<C, (fmt::v5::internal::type)13> >::type fmt::v5::internal::make_value(const T&) [with C = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>; T = std::tuple<int, char>; Char = char; typename std::enable_if<((! fmt::v5::internal::convert_to_int<T, Char>::value) && (! std::is_convertible<T, fmt::v5::basic_string_view<Char> >::value)), fmt::v5::internal::typed_value<C, (fmt::v5::internal::type)13> >::type = fmt::v5::internal::typed_value<fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>, (fmt::v5::internal::type)13>]’
> /usr/local/include/fmt/core.h:944:29:   required from ‘typename std::enable_if<IS_PACKED, fmt::v5::internal::value<Context> >::type fmt::v5::internal::make_arg(const T&) [with bool IS_PACKED = true; Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>; T = std::tuple<int, char>; typename std::enable_if<IS_PACKED, fmt::v5::internal::value<Context> >::type = fmt::v5::internal::value<fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >]’
> /usr/local/include/fmt/core.h:997:51:   required from ‘fmt::v5::format_arg_store<Context, Args>::format_arg_store(const Args& ...) [with Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>; Args = {std::tuple<int, char>}]’
> /usr/local/include/fmt/core.h:1292:45:   required from ‘void fmt::v5::print(fmt::v5::string_view, const Args& ...) [with Args = {std::tuple<int, char>}; fmt::v5::string_view = fmt::v5::basic_string_view<char>]’
> fmt.cpp:9:27:   required from here
> /usr/local/include/fmt/core.h:529:56: error: ‘fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>::formatter_type<std::tuple<int, char> >::type f’ has incomplete type
>      typename Context::template formatter_type<T>::type f;
>                        

Output of the gcc looks rather cryptic, so here is clang as well:

> In file included from fmt.cpp:3:
> In file included from /usr/local/include/fmt/format.h:40:
> /usr/local/include/fmt/core.h:529:56: error: implicit instantiation of undefined template
>       'fmt::v5::formatter<std::__1::tuple<int, char>, char, void>'
>     typename Context::template formatter_type<T>::type f;
>                                                        ^
> /usr/local/include/fmt/core.h:515:22: note: in instantiation of function template specialization
>       'fmt::v5::internal::value<fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char>
>       >, char> >::format_custom_arg<std::__1::tuple<int, char> >' requested here
>     custom.format = &format_custom_arg<T>;
>                      ^
> /usr/local/include/fmt/core.h:541:45: note: in instantiation of function template specialization
>       'fmt::v5::internal::value<fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char>
>       >, char> >::value<std::__1::tuple<int, char> >' requested here
>   FMT_CONSTEXPR typed_value(const T &val) : value<Context>(val) {}
>                                             ^
> /usr/local/include/fmt/core.h:944:10: note: in instantiation of function template specialization
>       'fmt::v5::internal::make_value<fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char>
>       >, char>, std::__1::tuple<int, char>, char>' requested here
>   return make_value<Context>(value);
>          ^
> /usr/local/include/fmt/core.h:997:23: note: in instantiation of function template specialization
>       'fmt::v5::internal::make_arg<true,
>       fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char>
>       >, char>, std::__1::tuple<int, char> >' requested here
>     : data_{internal::make_arg<IS_PACKED, Context>(args)...} {}
>                       ^
> /usr/local/include/fmt/core.h:1292:45: note: in instantiation of member function
>       'fmt::v5::format_arg_store<fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char>
>       >, char>, std::__1::tuple<int, char> >::format_arg_store' requested here
>   format_arg_store<format_context, Args...> as{args...};
>                                             ^
> fmt.cpp:9:10: note: in instantiation of function template specialization
>       'fmt::v5::print<std::__1::tuple<int, char> >' requested here
>     fmt::print("{}\n", tup);
>          ^
> /usr/local/include/fmt/core.h:303:8: note: template is declared here
> struct formatter;
>        ^
> 1 error generated.

**Comment by Remotion** [comment]
This one work well for me using GCC 7.3 but if I also include `<fmt/printf.h>`  then it stop working.
So somehow `<fmt/printf.h>` seems to block tuple detection.
```
#include <tuple>
#define FMT_HEADER_ONLY
#include <fmt/format.h>
#include <fmt/ranges.h>
// #include <fmt/printf.h>

int main() {
    std::tuple<int, char> tup = {1, 'a'};
    fmt::print("{}\n", tup);
}
```

**Comment by vitaut** [comment]
A @Remotion wrote, the example compiles in the latest `master` branch: https://godbolt.org/g/dJUYKP. Also you don't need to include `fmt/printf.h` or `fmt/format.h` in your example.
