### ISSUE TITLE
_format literal fails when the input type is char

### ISSUE THREAD

**Issue by furkanusta** [fmtlib/fmt#761]
Tested with:
G++ 8.1
Clang 6.0

FMT_VERSION 50100

```C++
#include <iostream>
#include <tuple>
#include <fmt/core.h>
#include <fmt/ostream.h>
#include <fmt/posix.h>
#include <fmt/format.h>
#include <fmt/ranges.h>
#include <fmt/printf.h>

using namespace fmt::literals;

int main() {
    std::cout << "{}"_format(1);   // Works
    std::cout << "{}"_format(1.23);   // Works
    std::cout << "{}"_format('a'); // Does not Work
}
```

Error from clang is:

> In file included from fmt.cpp:4:
> In file included from /usr/local/include/fmt/ostream.h:11:
> /usr/local/include/fmt/format.h:2212:50: error: ambiguous partial specializations of
>       'formatter<char, char, void>'
>   formatter<T, typename ParseContext::char_type> f{};
>                                                  ^
> /usr/local/include/fmt/format.h:2222:21: note: in instantiation of function template specialization
>       'fmt::v5::internal::parse_format_specs<char, fmt::v5::basic_parse_context<char,
>       fmt::v5::internal::error_handler> >' requested here
>       parse_funcs_{&parse_format_specs<Args, parse_context_type>...} {}
>                     ^
> /usr/local/include/fmt/format.h:2269:54: note: in instantiation of member function
>       'fmt::v5::internal::format_string_checker<char, fmt::v5::internal::error_handler,
>       char>::format_string_checker' requested here
>   format_string_checker<Char, ErrorHandler, Args...> checker(s, eh);
>                                                      ^
> /usr/local/include/fmt/format.h:3634:9: note: in instantiation of function template specialization
>       'fmt::v5::internal::check_format_string<char, fmt::v5::internal::error_handler, char>'
>       requested here
>         check_format_string<Char, error_handler, Args...>(
>         ^
> fmt.cpp:14:29: note: in instantiation of function template specialization
>       'fmt::v5::internal::udl_formatter<char, '{', '}'>::operator()<char>' requested here
>     std::cout << "{}"_format('a'); // Does not Work
>                             ^
> /usr/local/include/fmt/format.h:3155:8: note: partial specialization matches
>       [with T = char, Char = char]
> struct formatter<
>        ^
> /usr/local/include/fmt/ostream.h:117:8: note: partial specialization matches
>       [with T = char, Char = char]
> struct formatter<T, Char,
>        ^
> 1 error generated.

**Comment by furkanusta** [comment]
It looks like the error occurs only if I include both <fmt/format.h> and <fmt/ostream.h>

and according to godbolt there is no error in 4.1.0 https://godbolt.org/g/4vxgDh

**Comment by vitaut** [comment]
This has been fixed already (https://godbolt.org/g/mkKNry), but thanks for reporting.
