### ISSUE TITLE
RGB print support for {fmt}

### ISSUE THREAD

**Issue by Remotion** [fmtlib/fmt#762]
What do you think about this RGB print support? 
https://github.com/Remotion/fmt_extension/blob/develop/include/fmt_rgb.h

```cpp
fmt::print(fmt::rgb(120,55,220), "some colored  text");

fmt::print(fmt::AliceBlue, "some colored text");
```

This also work on Windows 10 too.

**Comment by eliaskosunen** [comment]
There's `(v)print_colored` already: https://github.com/fmtlib/fmt/blob/dd1a5ef7f9a122a017204ef00d97c9a06636abe7/include/fmt/core.h#L1167, although it's not documented anywhere and the comments deem it as experimental.

**Comment by Remotion** [comment]
Yes I know this, but it does support only 8 colors and not full RGB.

Also writing `fmt::print_colored(fmt::rgb(120,55,220)` is too long without any benefit.

**Comment by vitaut** [comment]
> What do you think about this RGB print support?

I think it can be useful and, as @eliaskosunen already pointed out, there is a limited support for this already. PRs to extend this functionality are welcome.

> Also writing fmt::print_colored(fmt::rgb(120,55,220), "some colored text"); is too long without any benefit.

You are probably right, overloading `fmt::print` should be harmless provided that there are no undesirable conversions to `rgb`.
