### ISSUE TITLE
printing wide strings

### ISSUE THREAD

**Issue by melak47** [fmtlib/fmt#765]
Using the 5.0.0 release on windows, printing wide strings with `fmt::print` doesn't seem to work right. For example, given:
```cpp
#include <fmt/format.h>

int main() {
    fmt::print(L"Hello, world!\n");
}
```

Produces:
```
H e l l o ,   w o r l d !
```

The reason is the implementation of `vprint`: https://github.com/fmtlib/fmt/blob/5386f1df20392a08844f5034e8436c6ec7ce0b03/include/fmt/format-inl.h#L502-L506
It just writes the buffer content to the FILE pointer. Is that intentional, and does that provide the expected output on *any* platform?

**Comment by melak47** [comment]
I'm not sure if there's a perfect solution on windows when you have to consider that `f` may be a console or file. How do you write a wide string to a file of unknown encoding?
Still, the current behavior isn't very useful - maybe `= delete`ing or otherwise annotating it as not implemented on windows would be more helpful?

**Comment by vitaut** [comment]
I think that for this to work the file stream needs to be in the wide mode which you can do with the [`fwide`](http://en.cppreference.com/w/cpp/io/c/fwide) function.

**Comment by melak47** [comment]
That should work, but doesn't on Windows/MSVC.
It can be made to work using the MS-CRT-specific [`_setmode`](https://docs.microsoft.com/en-gb/cpp/c-runtime-library/reference/setmode) with either `_O_U8TEXT` or `_O_U16TEXT`.

Is it reasonable to assume the user wants UTF-8 output when `f` is a file (either explicitly passed to `fmt::print`, or redirected stdout/stderr)?

If so, it could be implemented like this:
```diff
diff --git a/include/fmt/format-inl.h b/include/fmt/format-inl.h
index 223ed51..c355fce 100644
--- a/include/fmt/format-inl.h
+++ b/include/fmt/format-inl.h
@@ -22,2 +22,7 @@

+#ifdef _WIN32
+# include <fcntl.h>
+# include <io.h>
+#endif
+
 #if defined(_WIN32) && defined(__MINGW32__)
@@ -504,2 +509,7 @@ FMT_FUNC void vprint(std::FILE *f, wstring_view format_str, wformat_args args) {
   vformat_to(buffer, format_str, args);
+#ifdef _WIN32
+  _setmode(_fileno(f), _O_U8TEXT);
+#else
+  std::fwide(f, 1);
+#endif
   std::fwrite(buffer.data(), sizeof(wchar_t), buffer.size(), f);
```

**Comment by vitaut** [comment]
Seems reasonable but I think `fwide/_setmode` should be called once per file by the client, not on every call to `print`. I added a note to the docs: http://fmtlib.net/dev/api.html#_CPPv2N3fmt5printEPNSt4FILEE12wstring_viewDpRK4Args . Thanks!
