### ISSUE TITLE
format_to for basic_memory_writer

### ISSUE THREAD

**Issue by scamille** [fmtlib/fmt#776]
I tried to port my existing ArrayWriter code to the new fmt::basic_memory_writer in Release 5.0.0.

Example which does not work:
```
fmt::basic_memory_buffer<char, 100> buffer;
fmt::format_to(buffer, "{}", "foo");
```

What does work:
```
fmt::memory_buffer buffer;
fmt::format_to(buffer, "{}", "foo");
```

Would it be possible to provide a fmt::format_to overload which accepts all fmt::basic_memory_writer's, and not just the particular fmt::memory_writer typedef?

Thanks for all the hard work. We are using the library successfully in a medium sized open source project, both as a modern formatting library, as well as a replacement for legacy printf code.

**Comment by vitaut** [comment]
> Would it be possible to provide a fmt::format_to overload which accepts all fmt::basic_memory_writer's, and not just the particular fmt::memory_writer typedef?

Yes, done in https://github.com/fmtlib/fmt/commit/ab2d88ca8e6db84c9a048dd685de32a58d752818.

> Thanks for all the hard work. We are using the library successfully in a medium sized open source project, both as a modern formatting library, as well as a replacement for legacy printf code.

Thanks! Glad that it works for you.
