### ISSUE TITLE
Null terminating a memory_buffer in version 5.0

### ISSUE THREAD

**Issue by BlakeTheAwesome** [fmtlib/fmt#777]
I have a memory_buffer which I want to format into then pass into something requiring a c_str, and I don't really want to allocate a std::string in the middle for conversion.

It looks like older versions had a null-terminating c_str() function on MemoryWriter, but there doesn't appear to be any equivalent on memory_buffer.

Can we get a null-terminating c_str() function on memory_buffer? If not, what is the best way to convert from a memory_buffer to a c_str?

**Comment by vitaut** [comment]
You can append the terminating null with `push_back(0)` in which case `data()` will return a null-terminated string.
