### ISSUE TITLE
format_to_n do not write characters

### ISSUE THREAD

**Issue by ck3d** [fmtlib/fmt#778]
```
std::array<char, 1> field{};
assert(fmt::format_to_n(field.begin(), 1, "{}", 'a').size, 1); // passes
assert(field[0] == 'a'); // failes, field[0] == \0
```
No problems with format_to.

**Comment by vitaut** [comment]
This works on the latest `master`:

```c++
#include "fmt/format.h"
#include <array>

int main() {
  std::array<char, 1> field{};
  fmt::format_to_n(field.begin(), 1, "{}", 'a');
  fmt::print("{}", field[0]); // prints 'a'
}
```
Not sure if it is related, but your first assert seems invalid (probably should be `==` instead of `,`).

**Comment by wkenyon** [comment]
This may work on master, but it is broken in the latest release, 5.0.0.
Perhaps it's worth releasing 5.0.1 with this fixed? It seems like a pretty serious bug.

**Comment by vitaut** [comment]
Yes, I plan to release a new minor version soon.

**Comment by vitaut** [comment]
Version 5.1.0 which includes this fix among other things has been released: https://github.com/fmtlib/fmt/releases/tag/5.1.0
