### ISSUE TITLE
The new extension API ? 

### ISSUE THREAD

**Issue by blackball** [fmtlib/fmt#781]
I am referring to the new extension API from @vitaut 's CppCon slides.  I wonder when the new extension API will be ready: 

```c++
template <typename T>
struct formatter<vector<T>> : formatter<T> {
void format(buffer& buf, const vector<T>& values,
context& ctx) {
buf.push_back('{');
auto it = values.begin(), end = values.end();
if (it != end) {
formatter<T>::format(buf, *it, ctx);
for (++it; it != end; ++it) {
format_to(buf, ", ");
formatter<T>::format(buf, *it, ctx);
}
}
buf.push_back('}');
}
};
vector<int> v{11, 22, 33};
auto str = format("{:04}", v);
// str == "{0011, 0022, 0033}"
```

If I want to do the same thing above, how should I do it with current fmtlib ? 
Thanks!

**Comment by vitaut** [comment]
The new extension API is ready and part of version 5.0 (with minor differences from what was described in my cppcon talk). See http://fmtlib.net/5.0.0/api.html#formatting-user-defined-types

**Comment by blackball** [comment]
Hi @vitaut ,

I adopted the example codes in above link to fmt vector types: 
 
```c++
template <typename T>
struct formatter< vector<T> > {
    template <typename ParseContext>
    constexpr auto parse(ParseContext &ctx) { return ctx.begin(); }
    template <typename FormatContext>
    auto format(const vector<T> &v, FormatContext &ctx) {
        auto iter = ctx.begin();
        auto size = v.size();
        if (size > 0) {
            for (auto i = 0; i < size - 1; ++i) {
                iter = format_to(iter, "{},", v[i]);
            }
        }
        return format_to(iter, "{}", v.back());
    }
};
```

It turned out the above implementation is way slower than simply using stringstream. Is there any way to support batch format a vector type efficiently with fmtlib ? 

Thanks!

**Comment by vitaut** [comment]
@blackball, how do you compare to stringstream? Could you post a complete example including timing code?

**Comment by blackball** [comment]
`c++
#include <fmt/format.h>
#include <vector>
#include <string>
#include <iostream>
#include <sstream>
#include <chrono>
#include <thread>

using std::vector; 

inline uint64_t
CurrentTime_Milliseconds() {
    return std::chrono::duration_cast<std::chrono::milliseconds>
        (std::chrono::high_resolution_clock::now().time_since_epoch()).count();
}

class ScopedTimer {
public:
    ScopedTimer(const std::string name) : name_(name) {
        ms_ = CurrentTime_Milliseconds();
    }

    ~ScopedTimer() {
        std::cout << name_ << ": " << CurrentTime_Milliseconds() - ms_ << " ms\n";
    }
private:
    std::string name_;
    uint64_t ms_;
};

namespace fmt
{

template <typename T>
struct formatter< vector<T> > {
    template <typename ParseContext>
    constexpr auto parse(ParseContext &ctx) { return ctx.begin(); }
    template <typename FormatContext>
    auto format(const vector<T> &v, FormatContext &ctx) {
        auto iter = ctx.begin();
        const auto size = v.size();
        if (size > 0) {
            for (auto i = 0; i < size - 1; ++i) {
                iter = format_to(iter, "{},", v[i]);
            }
            iter = format_to(iter, "{}", v.back());
        }
        return iter;
    }
};

}

template<typename T>
inline std::string
Join_Use_Fmt(const std::vector<T> &v) {
    return fmt::format("{}", v);
}

template<typename T>
inline std::string
Join_Use_StdCopy (const std::vector<T>& vec, const std::string &del = ",") {
    std::stringstream ss;
    if (vec.size() > 0) {
        std::copy(vec.begin(), vec.end() - 1, std::ostream_iterator<T>(ss, del.c_str()));
        ss << vec.back();
    }
    return ss.str();
}

template<typename T>
inline std::string
Join_Use_SS (const std::vector<T>& vec, const std::string del = ",") {
    std::stringstream ss;
    const auto size = vec.size();
    if (size > 0) {
        for (unsigned int i = 0; i < size - 1; ++i) {
            ss << vec[i] << del;
        }
        ss << vec.back();
    }    
    return ss.str();
}

int
main(int argc, char *argv[]) {
    vector<double> v;
    for (int i = 0; i < 1000000; ++i) {
        v.push_back(static_cast<double>(i));
    }
    
#define TEST(NAME)                              \
    {                                           \
        ScopedTimer _(#NAME);                   \
        auto s = NAME(v);                       \
    }
    //std::cout << s << std::endl;              

    TEST(Join_Use_StdCopy);
    TEST(Join_Use_SS);
    TEST(Join_Use_Fmt);
    
    return 0;
}

/*
  -------------------------------------------------------------
  On my machine: Intel i7-7700k

  g++ -march=native main.cpp -I/path/to/Install/FmtLib/include

  The output is:

  Join_Use_StdCopy: 414 ms
  Join_Use_SS: 386 ms
  Join_Use_Fmt: 912 ms

  -------------------------------------------------------------
*/
`

**Comment by eliaskosunen** [comment]
You should try enabling optimizations. The standard library is precompiled with optimizations enabled but it seems like you are compiling fmt with none.

**Comment by blackball** [comment]
@eliaskosunen Yes you're right. I thought -march=native will enable some optimization automatically. Now when I try -O3, the fmtlib is the fastest. Thanks! 
 
@vitaut please ignore my above codes. Solved.

**Comment by vitaut** [comment]
Glad to hear that the problem is solved. Thanks, @eliaskosunen.
