### ISSUE TITLE
fmt() macro in format_to

### ISSUE THREAD

**Issue by eglimi** [fmtlib/fmt#783]
The `fmt()` macro is very useful to check if arguments are valid. As far as I can see, this is only possible for `format`. E.g. (from the documentation):

```
std::string s = fmt::format(fmt("{:d}"), "foo"); // Produces compiler error
```

I would like to be able to use the macro also in `format_to`, in order to avoid allocations from `std::string`. For example

```
fmt::memory_buffer buf;
fmt::format_to(buf, fmt("{:d}"), "foo");
```

Is this planned, or do I miss something?

Thank you for your support and the great work on fmtlib!

**Comment by vitaut** [comment]
> Is this planned, or do I miss something?

It is planned, I just need to figure out how to do it in a clean way without proliferation of overloads.

**Comment by Milerius** [comment]
<img width="1169" alt="capture d ecran 2018-07-20 a 23 07 09" src="https://user-images.githubusercontent.com/21139416/43025943-ef12c42c-8c73-11e8-83aa-275943b6a08f.png">

<3

**Comment by vitaut** [comment]
@Milerius, you can easily disable the `fmt` macro by defining `FMT_NO_FMT_STRING_ALIAS`.

**Comment by Milerius** [comment]
@vitaut Thank's !

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/ffe414cad13d66c7dcefa412d41f377c9635b80c. Now your example produces an expected compile-time error:

```
include/fmt/format.h:2312:27: error: constexpr variable 'invalid_format' must be initialized by a constant expression
  FMT_CONSTEXPR_DECL bool invalid_format =
                          ^
include/fmt/format.h:3532:13: note: in instantiation of function template specialization 'fmt::v5::internal::check_format_string<char [4], S>' requested here
  internal::check_format_string<Args...>(format_str);
            ^
test.cc:5:6: note: in instantiation of function template specialization 'fmt::v5::format_to<S, char [4], 500>' requested here
fmt::format_to(buf, fmt("{:d}"), "foo");
     ^
include/fmt/format.h:1418:13: note: non-constexpr function 'on_error' cannot be used in a constant expression
    handler.on_error("invalid type specifier");
            ^
```
Also refactored the code so that it's possible to handle both compile-time and dynamically checked format strings in one function template.
