### ISSUE TITLE
Range to fill out multiple args

### ISSUE THREAD

**Issue by SuperWig** [fmtlib/fmt#784]
Would it possible to have something like this?
```
std::vector<int> vec = { 1, 2, 3 };
fmt::print("first: {}\nsecond: {}\nthird: {}", vec)
```
With the output
```
first: 1
second: 2
third: 3
```

**Comment by vitaut** [comment]
No, each replacement field should refer to a separate argument.

**Comment by SuperWig** [comment]
How would you go about formatting runtime arguments then?

Wouldn't it be possible via a different function or type? i.e.
```
std::string formatted = fmt::format_unwrap(str, vec);
//or
std::string formatted = fmt::format(str, fmt::unwrap(vec));
```
Or perhaps one/n at a time? i.e.
```
std::string str = "first: {}\nsecond: {}\nthird: {}";
str = fmt::format_single(str, 1); //first: 1\nsecond: {}\nthird: {}
str = fmt::format_n<2>(str, 2, 3); //first: 1\nsecond: 2\nthird: 3
```

**Comment by vitaut** [comment]
If you can pass arguments in a tuple instead of a vector, then you can use the method described in #652. Otherwise, you can convert vector to tuple as described in https://stackoverflow.com/q/28410697/471164 first.
