### ISSUE TITLE
static constexpr class members are required to have a definition

### ISSUE THREAD

**Issue by kivadiu** [fmtlib/fmt#788]
The following program does not compile with clang++ 5.0.2. With g++ 7.3.0, it does not compile in debug mode but compiles with -O2. The error is that the class static constexpr int i is required to have an address because fmt::format takes its arguments by const reference. However I do not understand why g++ work in release mode! Would it be possible that fmt::format takes its arguments by universal references &&? Would that improve this situation?

```
#include <iostream>
#include <fmt/format.h>

struct Foo {
  static constexpr auto i = 42;
  void operator()() const { std::cout << fmt::format("{}\n", i); }
};

int main() {
  Foo{}();
  return 0;
}
```

**Comment by vitaut** [comment]
I don't see any error with clang 5.0: https://godbolt.org/g/DrbUZe

**Comment by kivadiu** [comment]
The problem is not at compile time but at link time:
```
clang++ -o build/obj/6ee6fd61/Progs/fmt_constexpr.o -c -O2 -DTARGETID=2 -DNDEBUG -Wall -Wextra -Wnon-virtual-dtor -Werror=delete-non-virtual-dtor -pipe -march=native -std=c++14 -I. -ILibraries Progs/fmt_constexpr.cpp
clang++ -o build/clang-release/bin/fmt_constexpr build/obj/6ee6fd61/Libraries/fmt/format.o build/obj/6ee6fd61/Progs/fmt_constexpr.o -fuse-ld=lld -s
/usr/bin/ld.lld: error: undefined symbol: Foo::i
>>> referenced by Progs/fmt_constexpr.cpp
>>>               build/obj/6ee6fd61/Progs/fmt_constexpr.o:(main)
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by vitaut** [comment]
> Would it be possible that fmt::format takes its arguments by universal references &&? Would that improve this situation?

No, it wouldn't, e.g.

```c++
struct Foo {
  static constexpr auto i = 42;
};

template <typename T>
void f(T&& i) {}

int main() {
  f(Foo::i);
}
```
gives
```
Undefined symbols for architecture x86_64:
  "Foo::i", referenced from:
      _main in test1-c21676.o
```

According to [[basic.def.odr]](http://eel.is/c++draft/basic.def.odr#10):

> Every program shall contain exactly one definition of every non-inline function or variable that is odr-used in that program outside of a discarded statement; no diagnostic required.

This requirement was relaxed in C++17, so your example should compile there. On C++14 and earlier you should provide an out-of-class definition of your variable.

**Comment by kivadiu** [comment]
In fact with c++17, it fails both with g++ 8.1.0 and clang 6.0.0 with a much less easy to understand message.
https://godbolt.org/g/dAnHxG

**Comment by vitaut** [comment]
That's because Compiler Explorer doesn't link with the fmt library.  Your example compiles when using header-only mode: https://godbolt.org/g/DhyUfd

**Comment by kivadiu** [comment]
OK, thanks, I did not know that godbolt could not link with libraries.
