### ISSUE TITLE
Abseil str_format Library

### ISSUE THREAD

**Issue by Remotion** [fmtlib/fmt#789]
Abseil has now str_format Library https://abseil.io/blog/20180622-format
It would be interesting to compare it to {fmt}. 

Also there is float to string conversion code inside that supposed to be fast. 
https://github.com/abseil/abseil-cpp/tree/master/absl/strings/internal/str_format

**Comment by vitaut** [comment]
Interesting. As usual PRs are welcome (to the benchmark repo, not this one).
