### ISSUE TITLE
Failure to format a matrix from the eigen c++ library

### ISSUE THREAD

**Issue by lawrencem99** [fmtlib/fmt#794]
Matrices from the eigen library are streamable with std c++ streams, so I think this might be a limitation/bug.

This particular object is definitely working with operator << and std::cout.

From GCC:
error: 'fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>::formatter_type<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float, float>, const Eigen::Block<Eigen::Product<Eigen::Matrix<float, 4, 4>, Eigen::Matrix<float, 4, 1>, 0>, -1, 1, false>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Matrix<float, -1, 1, 0, 4, 1> > > >::type f' has incomplete type
     typename Context::template formatter_type<T>::type f;

From MSVC:
c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(529): error C2079: 'f' uses undefined struct 'fmt::v5::formatter<T,char,void>'
          with
          [
              T=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(515): note: see reference to function template instantiation 'void fmt::v5::internal::value<Context>::format_custom_arg<T>(const void *,Context &)' being compiled
          with
          [
              Context=fmt::v5::format_context,
              T=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(515): note: see reference to function template instantiation 'void fmt::v5::internal::value<Context>::format_custom_arg<T>(const void *,Context &)' being compiled
          with
          [
              Context=fmt::v5::format_context,
              T=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(541): note: see reference to function template instantiation 'fmt::v5::internal::value<Context>::value<T>(const T &)' being compiled
          with
          [
              Context=fmt::v5::format_context,
              T=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(541): note: see reference to function template instantiation 'fmt::v5::internal::value<Context>::value<T>(const T &)' being compiled
          with
          [
              Context=fmt::v5::format_context,
              T=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(637): note: see reference to function template instantiation 'fmt::v5::internal::typed_value<Context,fmt::v5::internal::custom_type>::typed_value<T>(const T &)' being compiled
          with
          [
              Context=fmt::v5::format_context,
              T=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(637): note: see reference to function template instantiation 'fmt::v5::internal::typed_value<Context,fmt::v5::internal::custom_type>::typed_value<T>(const T &)' being compiled
          with
          [
              Context=fmt::v5::format_context,
              T=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(943): note: see reference to function template instantiation 'fmt::v5::internal::typed_value<Context,fmt::v5::internal::custom_type> fmt::v5::internal::make_value<Context,Eigen::Transpose<Derived>,char>(const T &)' being compiled
          with
          [
              Context=fmt::v5::format_context,
              Derived=Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>,
              T=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(994): note: see reference to function template instantiation 'fmt::v5::internal::value<Context> fmt::v5::internal::make_arg<true,Context,_Ty>(const T &)' being compiled
          with
          [
              Context=fmt::v5::format_context,
              _Ty=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>,
              T=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(994): note: while compiling class template member function 'fmt::v5::format_arg_store<fmt::v5::format_context,_Ty,int,int>::format_arg_store(const _Ty &,const int &,const int &)'
          with
          [
              _Ty=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(1244): note: see reference to function template instantiation 'fmt::v5::format_arg_store<fmt::v5::format_context,_Ty,int,int>::format_arg_store(const _Ty &,const int &,const int &)' being compiled
          with
          [
              _Ty=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(1240): note: see reference to class template instantiation 'fmt::v5::format_arg_store<fmt::v5::format_context,_Ty,int,int>' being compiled
          with
          [
              _Ty=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  C:\Users\Losquonzia\Projects\workspace\fmt\include\fmt/format.h(3575): note: see reference to function template instantiation 'std::string fmt::v5::format<_Ty,int,int>(fmt::v5::string_view,const _Ty &,const int &,const int &)' being compiled
          with
          [
              _Ty=Eigen::Transpose<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>>
          ]
  C:\Users\Losquonzia\Projects\workspace\lmlib\test\src\geometry.cpp(89): note: see reference to function template instantiation 'std::string fmt::v5::internal::udl_formatter<char>::operator ()<Eigen::Transpose<Derived>,int&,int&>(Eigen::Transpose<Derived> &&,int &,int &) const' being compiled
          with
          [
              Derived=Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>
          ]
  C:\Users\Losquonzia\Projects\workspace\lmlib\test\src\geometry.cpp(88): note: see reference to function template instantiation 'std::string fmt::v5::internal::udl_formatter<char>::operator ()<Eigen::Transpose<Derived>,int&,int&>(Eigen::Transpose<Derived> &&,int &,int &) const' being compiled
          with
          [
              Derived=Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float,float>,const Eigen::Block<Eigen::Product<Eigen::Matrix<float,4,4,0,4,4>,Eigen::Matrix<float,4,1,0,4,1>,0>,-1,1,false>,const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>,const Eigen::Matrix<float,-1,1,0,4,1>>>
          ]
c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(531): error C2228: left of '.parse' must have class/struct/union
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(531): note: type is 'int'
c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(532): error C2228: left of '.format' must have class/struct/union
  c:\users\losquonzia\projects\workspace\fmt\include\fmt\core.h(532): note: type is 'int'

**Comment by vitaut** [comment]
Have you included `fmt/ostream.h`?

**Comment by lawrencem99** [comment]
#797
