### ISSUE TITLE
Undefined reference to vformat

### ISSUE THREAD

**Issue by k0zmo** [fmtlib/fmt#795]
Following program fails in linker stage with an undefined reference to `vformat`. It happens with GCC 7.3 (MSYS2) and MSVC 14.1 but only in release-flavour configurations (all three of them). I suspect the `inline` keyword on `vformat()` definition in `format.h` can be a culprit here (in debug configuration compiler does not optimize aggressively inline functions).

It doesn't exhibit any problems if I change include `fmt/format.h` instead of `fmt/core.h`.

```cmake
cmake_minimum_required(VERSION 3.0)
project(fmt-test)

add_subdirectory(fmt)

add_executable(fmt-test main.cpp)
target_link_libraries(fmt-test PRIVATE fmt::fmt)
```

```cpp
#include <fmt/core.h>

int main(int argc, char* argv[])
{
    fmt::format("{}", argc);
}

```

**Comment by vitaut** [comment]
Could you post the output of `nm libfmt.a` (or dumpbin fmt.lib)?

**Comment by vitaut** [comment]
https://github.com/fmtlib/fmt/commit/323b92bffef75c9cf99dd8666bfc2f7e11fb8cb0 is a tentative fix, although I wasn't able to repro the issue on my version of gcc. Please let me know if it works for you and I'll merge into master.

**Comment by k0zmo** [comment]
This fixes it in both GCC and MSVC. 

Here's the output from `nm | c++filt | grep vformat`:
[nm.after.log](https://github.com/fmtlib/fmt/files/2161997/nm.after.log)
[nm.before.log](https://github.com/fmtlib/fmt/files/2161998/nm.before.log)

and `objdump /SYMBOLS | grep vformat`:
[dumpbin.after.log](https://github.com/fmtlib/fmt/files/2161995/dumpbin.after.log)
[dumpbin.before.log](https://github.com/fmtlib/fmt/files/2161996/dumpbin.before.log)

**Comment by vitaut** [comment]
Merged the fix into `master`, thanks for reporting and confirming that it works!
