### ISSUE TITLE
can we do Jason formatting using this lib?

### ISSUE THREAD

**Issue by naveenpinto** [fmtlib/fmt#799]
can we do JSON formatting using this lib?

**Comment by eliaskosunen** [comment]
Do you mean JSON?

**Comment by naveenpinto** [comment]
yes JSON format

**Comment by vitaut** [comment]
Sure, but you might be better off using a dedicated JSON serialization library.

**Comment by naveenpinto** [comment]
how do we do JSON  using SPD log, is there some examples????

**Comment by damienhocking** [comment]
I realize this is old, but it shows up in Google searches. I added a wiki entry for doing this:

https://github.com/gabime/spdlog/wiki/Setting-up-JSON-logging-with-spdlog
