### ISSUE TITLE
MSVC: Missing symbols while linking dynamically

### ISSUE THREAD

**Issue by jimpark** [fmtlib/fmt#808]
MSVC 17.5.5 complains about two internal functions missing from the DLL.

```c
fp operator*(fp x, fp y);
fp get_cached_power(int min_exponent, int &pow10_exponent);
```

They need to be declared fully inlined or decorated with FMT_API.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/c99a259739930cda9532d1f0c58f8ac25bc54eac, thanks for reporting.
