### ISSUE TITLE
Why fmt::to_string does not support user-defined types?

### ISSUE THREAD

**Issue by emptyVoid** [fmtlib/fmt#816]

**Comment by vitaut** [comment]
`fmt::to_string` uses a low-level formatting API which is somewhat faster because it doesn't need to parse the format string but doesn't support user-defined formatters. For user-defined types you can use `fmt::format("{}", x)` instead.

**Comment by emptyVoid** [comment]
IMO this makes the API inconsistent, and there's no mention of said behavior in the documentation.

**Comment by foonathan** [comment]
It is meant to be a drop-in replacement for std::to_string().

**Comment by vitaut** [comment]
I clarified this in the docs: https://github.com/fmtlib/fmt/commit/48dff9f3c5ea5508d56a719f05d5a9203d6925f6.
