### ISSUE TITLE
Suggestion to add pop_back() method to basic_buffer

### ISSUE THREAD

**Issue by MikePopoloski** [fmtlib/fmt#817]
Thanks for adding the clear() method to basic_buffer. The one other utility method I have added locally is a pop_back() method; it makes it a lot easier to implement the common problem of looping and appending comma (or other delimiter) separated items. The most efficient and straightforward way to do that is to always append the comma and then pop the last one at the end.

**Comment by vitaut** [comment]
`basic_buffer` is a bit of an implementation detail even though it's currently exposed via `basic_memory_buffer`, so I'd rather not extend it's API unless there are strong reasons to do so. Can't you do `resize(size() - 1)` to achieve the same effect? It's a bit verbose but it seems like a rare use case.

**Comment by MikePopoloski** [comment]
I don't know if it's all that rare; anyone formatting a comma-separated list of things will probably find it to be the easiest / most efficient method of doing so. resize() does work fine though; I had overlooked that. As long as that's there I don't feel a pressing need for the pop_back.
