### ISSUE TITLE
Please make format_enum switcher public

### ISSUE THREAD

**Issue by emptyVoid** [fmtlib/fmt#818]
Currently `format_enum` resides in an internal namespace preventing user from disabling enum-as-int behavior in a forward-compatible manner.

There're two main issues with the current enum-as-int implementation, which could be remedied by introduction of the "user level" switch:
1. User (like myself) might not want enums to be silently converted to ints under no circumstances.
2. Current implementation doesn't work for `enum class` and prevents partial template specializations of `fmt::formatter` for enums.

**Comment by vitaut** [comment]
`format_enum` doesn't control formatting of enums and was making `formatter` unusable for enums due to ambiguity so I removed it in https://github.com/fmtlib/fmt/commit/c68bab701473686ab77e15bac6bb743d86dfa5b6. Anything convertible to `int`, including enums, can be formatted as an integers. Could you elaborate why you want to disable this behavior?

**Comment by emptyVoid** [comment]
I want user friendly and readable strings in the logs, so that anyone who sees the enumeration's string representation (e.g. QA) would know what the value stands for, not some arbitrary integer which could potentially change from version to version (since for internal enumerations I care for alphabetical order and not for the underlying value).
Thus I'd like to spot "untraited" enums at compile time instead of in the field.

**Comment by vitaut** [comment]
One option is to make `format_to_int` public and disable conversion of enums to `int` by specializing it:

```c++
template <>
struct format_to_int<my_enum> : std::false_type {};
```

**Comment by vitaut** [comment]
So, @emptyVoid, will making `convert_to_int` public work for you?

**Comment by emptyVoid** [comment]
Sure if it could be applied to all enums, like this one:
```c++
FMT_BEGIN_NAMESPACE
    namespace internal
    {
        // disable built-in formatting of enumerations
        template <typename T>
        struct format_enum<T, std::enable_if_t<std::is_enum_v<T>>> : std::false_type
        {};
    }
FMT_END_NAMESPACE
```

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/987514761eb29e3ce9d9ec93b3a2ca6cfeb77fd9. The following should disable `enum` formatting:

```c++
template <typename T>
struct fmt::convert_to_int<T, char, std::enable_if_t<std::is_enum_v<T>>> : std::false_type {};
```

**Comment by emptyVoid** [comment]
Great, thanks!
