### ISSUE TITLE
Need to create ArgList iteratively

### ISSUE THREAD

**Issue by abrownsword** [fmtlib/fmt#821]
I haven't found an obvious way to do this (even in 5.1).  I have an array of objects that I need to pass as arguments to fmt::vformat, but they require a bit of conversion to extract the native types understood by fmt.  I think what I want to do is create a format_arg_store, but add to it incrementally rather than via a single variadic call.  Is there an existing mechanism to do this?  If not, could one be added?  I can specify the arg count up front.

**Comment by vitaut** [comment]
This has already been discussed in #814 and addressed in #819.

**Comment by abrownsword** [comment]
Thanks -- wasn't sure what to look for in terms of existing issues, and I've only downloaded the last release not pulled from HEAD.
