### ISSUE TITLE
How can I print thread id?

### ISSUE THREAD

**Issue by joyforever** [fmtlib/fmt#824]
I want to print the thread id using code below:
```
#include <thread>
#include <fmt/format.h>

int main() {
    fmt::print("main thread id: {}\n", std::this_thread::get_id());
}
```
but failed to compile. It can be done easily with `std::cout`, but how with `fmt::print`?

**Comment by mwinterb** [comment]
If you include the fmt/ostream.h header, types with an overloaded
operator<< can be formatted.

**Comment by elvenfighter** [comment]
The formatter for the std::thread::id is in the fmt/std.h. 
https://github.com/fmtlib/fmt/blob/master/include/fmt/std.h#L91
