### ISSUE TITLE
unexpected output using precision

### ISSUE THREAD

**Issue by draeger-charles-wilson** [fmtlib/fmt#826]
[Visual Studio 2017 / C++17]

constexpr auto pi{ 3.1415926535 };

cout << format ("{:.2}", pi) << endl;  ====> 3.1
cout << format ("{:.1}", pi) << endl;  ====> 3
cout << format ("{:.0}", pi) << endl;  ====> 3

cout << format ("{:.1f}", pi) << endl;  ====> 3.1
cout << format ("{:.0f}", pi) << endl;  ====> 3

The explicit floating point format has expected behavior, but the implicit does not.

It obviously picks up that floating point is required ".<precision>", but the output is random-ish.

**Comment by vitaut** [comment]
The default format specifier for float is `g` where precision specifies the number of digits before and after decimal point:

> The precision is a decimal number indicating how many digits should be displayed after the decimal point for a floating-point value formatted with 'f' and 'F', or before and after the decimal point for a floating-point value formatted with 'g' or 'G'

Please see the docs for more details: http://fmtlib.net/dev/syntax.html

**Comment by draeger-charles-wilson** [comment]
I can accept the 'g' is default. The precision related to 'g' being the total digits before and after is inconsistent with the concept of width. Given your above explanation, "{:.0}" should be completely invalid.

So, if this is an invalid specifier, should an exception not have been thrown?

**Comment by vitaut** [comment]
> A precision of 0 is treated as equivalent to a precision of 1.

**Comment by draeger-charles-wilson** [comment]
I now see that in the spec (P0645R2). For clarity, I would recommend that the wording reference the mantissa (with a floor of 1 digit) rather than the magnitude.

Given that:

constexpr auto pi{ 3.1415926535 * 100.0 };

	cout << format ("{:.2}", pi) << endl;
	cout << format ("{:.1}", pi) << endl;
	cout << format ("{:.0}", pi) << endl;

the output of:

3.1e+02
3e+02
3e+02

makes sense.

**Comment by vitaut** [comment]
Mantissa is usually understood as binary in FP, so this might add confusion.

**Comment by draeger-charles-wilson** [comment]
True.

I'm bothered by there not being a way to explain this that doesn't resort to examples or pictures.

Although I appreciated 'g' as the default type specifier, in the 38 years I've worked with code that uses printf-style formats (I won't count the FORTRAN years), I've never seen 'g' in the wild. I would have thought that 'f' would be the default representation because it is more common, even though 'g' is more general (literally).

**Comment by vitaut** [comment]
The choice of `g` being the default is due to the proposal being based on [PEP 3101 -- Advanced String Formatting](https://www.python.org/dev/peps/pep-3101/). Although they don't explain why it was chosen as the default I think the reason is that `g` selects the most readable of the two other formats based on the input.
