### ISSUE TITLE
fmt-5.1.0.zip corrupted

### ISSUE THREAD

**Issue by peergynt** [fmtlib/fmt#828]
The release zip:
[https://github.com/fmtlib/fmt/releases/download/5.1.0/fmt-5.1.0.zip](https://github.com/fmtlib/fmt/releases/download/5.1.0/fmt-5.1.0.zip)
seems to be corrupted.

I tried to download the file from a couple of different machines but same issue.

For some reason, the file does not start with the PK header but with following:
--e5ee1881be1d480abdbab2384c5a401b
Content-Disposition: form-data; name="fmt-5.1.0.zip"; filename="fmt-5.1.0.zip"

Thank you!

**Comment by vitaut** [comment]
Good catch, thanks! Fixed in https://github.com/fmtlib/fmt/commit/0f04ec68a918d3bb59f20a2574f5130ff9871e22 and re-uploaded the package.
