### ISSUE TITLE
Performance regression from 4.1.0 to 5.1.0?

### ISSUE THREAD

**Issue by rob-p** [fmtlib/fmt#829]
Hi,

  First, I'd like to thank you for the *fantastic* library.  It's incredibly nice to have a sane, fast, and easy-to-use formatting library in modern C++. I was recently trying to upgrade to spdlog 1.0, which bundles fmt 5.1.0 in an application that previously used spdlog v0.16.3 (with fmt 4.1.0).  I also have parts of the code that use fmt directly (i.e. not through spdlog).

  When upgrading the code to use fmt 5.1.0, I noted considerable performance regressions in parts of the code that were heavily writing into memory buffers.  That part of the code became almost twice as slow, and now shows up as a major bottleneck when profiling, where it was not before.  The relevant code (using the old library) was doing formatting like what you can see [here](https://github.com/COMBINE-lab/RapMap/blob/develop-salmon/src/RapMapUtils.cpp#L339).  Since this API seems to be removed from fmt 5.1.0, I was trying to replace it with `format_to()` writing to a memory buffer.  That was _much_ slower.  I also tried creating a `basic_writer` and repeatedly calling `write()` directly on that.  That seems faster than `format_to`, but still considerably slower than the `fmt::MemoryWriter` based version.

  Any idea what might be causing this, or how to get fmt 5.1.0 to perform on par with 4.1.0?

Thanks!
Rob

**Comment by rob-p** [comment]
Thanks for keying me in to the longer term solution.  I am, indeed sticking with 4.1.0 for the time being.  However, I guess this restricts me to spdlog < 1.0, right? Is there any supported way to have both fmt4 and fmt5 in the same project? Also, this is somewhat tangential, but why is using the writer class in 5.1 slower than memory writer in 4.1 ... is that expected as well?

**Comment by vitaut** [comment]
> However, I guess this restricts me to spdlog < 1.0, right?

fmt uses inline namespaces for versioning, so you should be able to use both fmt version 5 (and therefore spdlog 1.0) and 4 in the same project although probably not in the same translation unit because macros are unversioned.

> why is using the writer class in 5.1 slower than memory writer in 4.1 ... is that expected as well?

This is unexpected, could you post the both variants (using fmt 4.1 and 5.1) of the code you are comparing?

**Comment by vitaut** [comment]
There were huge performance improvements in version 5.2 (https://github.com/fmtlib/fmt/releases/tag/5.2.0). Further optimizations will be added as part of #613, so closing this issue for now.
