### ISSUE TITLE
missing '}' in format string

### ISSUE THREAD

**Issue by sinall** [fmtlib/fmt#832]
```
std::string formatStr = "{:\0^30}"s;
auto result = fmt::format(formatStr, "centered");  // use '\0' as a fill char

```

**Comment by vitaut** [comment]
This is a bug in the documentation, fixed in https://github.com/fmtlib/fmt/commit/ba95e36a583e803d7d9e4d0b3a8ca6f1471cf5f4. Thanks for reporting,.
