### ISSUE TITLE
fmt link error on visual studio with shared library

### ISSUE THREAD

**Issue by uilianries** [fmtlib/fmt#833]
Hi!

I'm one maintainer of fmt Conan recipe on Bincrafters project:  
https://github.com/bincrafters/conan-fmt/

Bincrafters distributes fmt for Linux, OSX and Windows. We observed an error when fmt is built on Windows, using Visual Studio and shared library is active and ranges support is required.

It's possible to run ranges examples when fmt is distributed as header-only or BUILD_SHARED_LIBS=OFF, however it doesn't work when BUILD_SHARED_LIBS=ON.

Essentially the current error is:
```
test_ranges.obj : error LNK2019: unresolved external symbol "public: static unsigned int const * const fmt::v5::internal::basic_data<void>::POWERS_OF_10_32" (?POWERS_OF_10_32@?$basic_data@X@internal@v5@fmt@@2QBIB) referenced in function "public: void __thiscall fmt::v5::basic_writer<class fmt::v5::back_insert_range<class fmt::v5::internal::basic_buffer<char> > >::int_writer<char,class fmt::v5::basic_format_specs<char> >::on_dec(void)" (?on_dec@?$int_writer@DV?$basic_format_specs@D@v5@fmt@@@?$basic_writer@V?$back_insert_range@V?$basic_buffer@D@internal@v5@fmt@@@v5@fmt@@@v5@fmt@@QAEXXZ) [C:\projects\conan-fmt\test_package\build\7114e75d218303cf2a5694937d88d86cc3064c2c\test_ranges\test_ranges.vcxproj]
```

This error appears on Visual Studio 2015 and Visual Studio 2017.

@sinall reported this error by the issue: https://github.com/bincrafters/community/issues/399

You could check our Appveyor log:
The build starts here:
https://ci.appveyor.com/project/BinCrafters/conan-fmt/build/1.0.63/job/g2k4wkxjnd6u3jfc#L1093
And fails here:
https://ci.appveyor.com/project/BinCrafters/conan-fmt/build/1.0.63/job/g2k4wkxjnd6u3jfc#L1477

The example code used on Appveyor is here:
https://github.com/bincrafters/conan-fmt/blob/testing/5.1.0/test_package/test_ranges/test_ranges.cpp

The same code works well on Linux and OSX.

I'm not able to reproduce this error using godbolt, but tell me if you need more information to understand this case.

**fmt version**: 5.1.0
**OS**: Windows
**compiler**: MSVC 14, MSVC 15
**seetings**: CMAKE_BUILD_TYPE=Release, BUILD_SHARED_LIBS=ON

**Comment by vitaut** [comment]
Thanks for reporting the issue. Are you defining the `FMT_SHARED` macro when building against the shared library? It is automatically defined when using the fmt's CMake config https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt#L189 but it seems that you have a different build config.

**Comment by uilianries** [comment]
It's working! thanks for your help!
