### ISSUE TITLE
How to pass list / container of values to format instead of parameters

### ISSUE THREAD

**Issue by eligt** [fmtlib/fmt#835]
I'm probably missing something but I can't find documentation on how to achieve something like this:

	std::vector<std::string> vals;
	vals.push_back("first");
	vals.push_back("second");
	vals.push_back("third");
	
	std::string s = fmt::format("{} / {} ---> {}", vals);
	
	// expect s to be "first / second ---> third"

**Comment by vitaut** [comment]
It is not supported at the very least because it would be ambiguous with formatting a vector itself. However, you can construct and the argument list dynamically: http://fmtlib.net/dev/api.html#argument-lists.

**Comment by tankorsmash** [comment]
> It is not supported at the very least because it would be ambiguous with formatting the vector itself. However, you can construct and the argument list dynamically: http://fmtlib.net/dev/api.html#argument-lists.

Could you clarify on how you'd use argument lists for making a dynamic list of `fmt::Args`? `fmt::make_format_args` seems like a start but I'm not sure.

**Comment by eligt** [comment]
I think `fmt::make_format_args` is only useful when you know in advance what the length of the argument list is going to be (i.e. at compile time).

This is what I use in my code to create a "dynamic" list (I actually use a pre-allocated array on the stack only supporting a maximum of 12 arguments, but it's good enough for my use case).

	fmt::format_args::format_arg args[12];
	int count = 0;
	// ...
	args[count++] = fmt::internal::make_arg<fmt::format_context>(value);
	// ...
	auto text = fmt::vformat(format_str, fmt::format_args(args, count));

Might not be the 100% correct way to do it but it seems to work, the author can maybe provide a better method.

**Comment by vitaut** [comment]
That's the only way to do it right now. Also mind the argument lifetimes since `format_arg` may only store references to arguments, not copies.
