### ISSUE TITLE
Replacement for fmt::MemoryWriter::operator<<(std::string)

### ISSUE THREAD

**Issue by apanloco** [fmtlib/fmt#836]
Hey!

I'm in the process of upgrading fmt::MemoryWriter to fmt::memory_buffer (actually spdlog 0.14.0 => 1.0.0). I'm trying to find an efficient replacement for:

NOTE: edited a few times for clarification

```
fmt::MemoryWriter s;
s << get_string();
return s.str();
```

which is no longer available.

I've found a few variants:

```
fmt::memory_buffer s;

// needs to parse format string
format_to(s, "{}", get_string());

// still needs to check every char for formatting
format_to(s, get_string());

// needs one more object to write a string
fmt::writer w(s);
w.write(get_string());

// needs the string in a separate variable
const std::string test = get_string();
s.append(test.data(), test.data() + test.size());

// and finally
return to_string(s);
```

Would appreciate some suggestions here...

**Comment by vitaut** [comment]
```c++
fmt::MemoryWriter s;
s << get_string();
return s.str();
```
is equivalent to `fmt::to_string(s)`.

Alternatively you can use `fmt::format(...)` which provides more formatting options.

BTW since you are formatting a string to a string you can skip formatting altogether.

**Comment by apanloco** [comment]
I think we're talking past each other. I'm asking about how to append an r-value string to a memory_buffer without the performance penalty of formatting a string. In fmt::MemoryWriter there was an operator<< that did this. But I have not found a way with memory_buffer that works on r-values.

Summary:
- format_to is slower than operator<< was
- fmt::writer requires an extra object (uncertain how much of a runtime penalty this is, but it's definitely more to write)
- append requires l-value, since we need to reference it twice (to get pointer and size).

Would appreciate one more go at this. Sorry for bumping.

**Comment by vitaut** [comment]
>  I'm asking about how to append an r-value string to a memory_buffer without the performance penalty of formatting a string.

You can just use append for that (your next to last case) and, possibly write a tiny helper function if you need this more than once. There will be no copy overhead if you extend the lifetime of a temporary:

```c++
const std::string &test = get_string();
s.append(test.data(), test.data() + test.size());
```

**Comment by apanloco** [comment]
Thanks!
