### ISSUE TITLE
How to store  fmt::format_args for later use?

### ISSUE THREAD

**Issue by gabime** [fmtlib/fmt#837]
I am trying to store a vector of  fmt::format_args for a later use (maybe even for different thread to consume later).

Is there a way to achieve this ?

Here is an example of what I am trying:
```c++

struct Msg
{
    const char* fmt_string;
    fmt::format_args fmt_args;

    template <typename... Args>
    Msg(const char *format_str, const Args &... args):
       fmt_string(format_str),
       fmt_args(fmt::make_format_args(args...)) {}  
};



int main(int, char *[])
{
    std::vector<Msg> messages;
    for(int i = 0; i < 3; i++)
    {
        Msg m("Hello {}", i);
        messages.push_back(m);
    }
    for(auto &msg : messages)
    {
        fmt::vprint(msg.fmt_string, msg.fmt_args);
    }
    return 0;
}
```
And the output (invalid as expected) :

> Hello 2
> Hello 2
> Hello 2

**Comment by vitaut** [comment]
fmt doesn't provide any API for storing arguments, but you can just use `std::tuple` for that as explained here: https://github.com/fmtlib/fmt/issues/652#issuecomment-366551952
