### ISSUE TITLE
Support '\0' as a fill char?

### ISSUE THREAD

**Issue by sinall** [fmtlib/fmt#840]
As you mentioned in #832, fmt doesn't support '\0' for fill char.

My case is that I'm trying to build packet for socket protocol. The protocol requires '\0' as fill char for some fields.

**Comment by vitaut** [comment]
Is there any reason '\0' should be a fill char and not an argument as in `fmt::format("{:10}", '\0')`?

**Comment by sinall** [comment]
For example, the user account has 8 to 12 chars, but in the protocol the account field should take 12 chars length.

Currently, I need to create a temp variable like this:
```
auto tmpAccount = account_;
tmpAccount.resize(12, '\0');
```
I can create a utility method to do a `resize_copy` thing to make code simpler. Then I realize this could be a feature of fmt library.

**Comment by vitaut** [comment]
Restriction on `\0` is an artifact from the time format string was passed as a null-terminated string. Technically it should be possible to lift it with some changes to the parser.

**Comment by vitaut** [comment]
`\0` fill is supported as of https://github.com/fmtlib/fmt/commit/8668639ae200631c77cecddd9569fb8ea1371b9c.
