### ISSUE TITLE
expected a file name error 

### ISSUE THREAD

**Issue by naveenpinto** [fmtlib/fmt#842]
i am getting this error in core.h. does anyone have a solution for this issue, it is on visual studio C++ 2015.

![image](https://user-images.githubusercontent.com/10204541/44582153-3b944e00-a7be-11e8-9174-ab3bffd436d7.png)

Severity	Code	Description	Project	File	Line
Error (active)	expected a file name	GExport	c:\Users\JNP014\Documents\Visual Studio 2015\Projects\staticlogger\staticlogger\spdlog\fmt\bundled\core.h	183

It points to this code

// libc++ supports string_view in pre-c++17.
#if (FMT_HAS_INCLUDE(<string_view>) && (__cplusplus > 201402L || defined(_LIBCPP_VERSION))) || 
(defined(_MSVC_LANG) && _MSVC_LANG > 201402L && _MSC_VER >= 1910)
#include <string_view>
#define FMT_USE_STD_STRING_VIEW
#elif (FMT_HAS_INCLUDE(<experimental / string_view>) && __cplusplus >= 201402L)
#include <experimental/string_view>
#define FMT_USE_EXPERIMENTAL_STRING_VIEW
#endif

has anyone encountered this????

![image](https://user-images.githubusercontent.com/10204541/44582263-9fb71200-a7be-11e8-93d6-023166fceb42.png)

**Comment by naveenpinto** [comment]
any solution for this bug would be appreciated!!!!!

**Comment by vitaut** [comment]
This is strange. MSVC 2015 doesn't have `__has_include` (https://godbolt.org/z/070ovR), so `FMT_HAS_INCLUDE` should just expand to 0. Could you try compiling 

```c++
#if defined(__has_include)
# error __has_include
#else
# error no __has_include
#endif
```
and posting the output here?

**Comment by mwinterb** [comment]
Does the error occur at compile time, or just in the IDE? The Intellisense frontend is uses EDG which may have limited __has_include support partly enabled even in VS2015.

**Comment by naveenpinto** [comment]
@vitaut below is the output of the code you have supplied 

![image](https://user-images.githubusercontent.com/10204541/44768656-a0192980-ab7f-11e8-8a11-2fc054aaa618.png)

**Comment by naveenpinto** [comment]
@vitaut below is the compilation error

![image](https://user-images.githubusercontent.com/10204541/44769046-ec189e00-ab80-11e8-82a7-abf31f3f589d.png)

**Comment by naveenpinto** [comment]
@vitaut thanks a lot for the inputs!!!!!
