### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by ChristianOL** [fmtlib/fmt#843]
Is there an example how to install and use this library? I have downloaded 5.0.0 release,
I am using DevC++ 5.11 to compile a simple program. I copied all headers and the src/format.cc files. Are there more steps needed? This is my code, when compiling I, get a bunch of errors. 

Code:
#include <iostream>
#include "fmt/format.h" 
#include "fmt/ostream.h"
#include "fmt/core.h"
int main() {
	fmt::print("The answer is {}.", 42); 
        return 0;
}

First error by compiler:
17	30	C:\Users\chris\fmt-5.0.0\include\fmt\time.h	[Error] macro "localtime_r" requires 2 arguments, but only 1 given.

Code lines marked by compiler on time.h file:
#ifndef FMT_TIME_H_
#define FMT_TIME_H_
#include "format.h"
#include <ctime>
FMT_BEGIN_NAMESPACE
namespace internal{
inline null<> localtime_r(...) { return null<>(); } // <-- ERROR IS MARKED HERE
inline null<> localtime_s(...) { return null<>(); }
inline null<> gmtime_r(...) { return null<>(); }
inline null<> gmtime_s(...) { return null<>(); }
}

Screenshot:
[fmt_error](https://user-images.githubusercontent.com/42178511/44628035-0f510c80-a939-11e8-8c1d-5dc3e3df4c06.png)

**Comment by vitaut** [comment]
The `localtime_r` issue should be fixed in https://github.com/fmtlib/fmt/commit/e4cf4041b51fc9c2facc4bd7d34385cf2dae9cfd.

You can enable the header-only mode by defining the `FMT_HEADER_ONLY` macro to 1 in which case you don't need to compile the library.

**Comment by ChristianOL** [comment]
Thank you very much. I was able to use the fmt. I incorrectly understood that creating a library was needed. I see it is optional.
