### ISSUE TITLE
Formatting type with << operator does not compile

### ISSUE THREAD

**Issue by ScottLangham** [fmtlib/fmt#847]
With the latest version of fmt I can no longer format a type that defines operator <<.
I've tried both wide and single byte format strings and neither work.
This used to work in the version of fmt I grabbed a couple of years ago.
Visual Studio sample solution attached.
I used Visual Studio 15.7.3

```
// FmtTest.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"

#define FMT_HEADER_ONLY
#include "fmt\format.h"


class My
{
public:
	int x = 7;
};

inline std::wostream& operator<<(std::wostream& os, const My& g)
{
	return os << g.x;
}

inline std::ostream& operator<<(std::ostream& os, const My& g)
{
	return os << g.x;
}


int main()
{
	auto g = My{};

	auto msg2 = fmt::format(L"{}", g);

    return 0;
}
```

[FmtTest.zip](https://github.com/fmtlib/fmt/files/2332510/FmtTest.zip)

**Comment by ScottLangham** [comment]
Errors are:

1>------ Build started: Project: FmtTest, Configuration: Debug Win32 ------
1>FmtTest.cpp
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(572): error C2079: 'f' uses undefined struct 'fmt::v5::formatter<T,wchar_t,void>'
1>        with
1>        [
1>            T=My
1>        ]
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(558): note: see reference to function template instantiation 'void fmt::v5::internal::value<Context>::format_custom_arg<T>(const void *,Context &)' being compiled
1>        with
1>        [
1>            Context=fmt::v5::wformat_context,
1>            T=My
1>        ]
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(558): note: see reference to function template instantiation 'void fmt::v5::internal::value<Context>::format_custom_arg<T>(const void *,Context &)' being compiled
1>        with
1>        [
1>            Context=fmt::v5::wformat_context,
1>            T=My
1>        ]
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(584): note: see reference to function template instantiation 'fmt::v5::internal::value<Context>::value<T>(const T &)' being compiled
1>        with
1>        [
1>            Context=fmt::v5::wformat_context,
1>            T=My
1>        ]
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(584): note: see reference to function template instantiation 'fmt::v5::internal::value<Context>::value<T>(const T &)' being compiled
1>        with
1>        [
1>            Context=fmt::v5::wformat_context,
1>            T=My
1>        ]
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(692): note: see reference to function template instantiation 'fmt::v5::internal::typed_value<Context,fmt::v5::internal::custom_type>::typed_value<T>(const T &)' being compiled
1>        with
1>        [
1>            Context=context_t,
1>            T=My
1>        ]
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(692): note: see reference to function template instantiation 'fmt::v5::internal::typed_value<Context,fmt::v5::internal::custom_type>::typed_value<T>(const T &)' being compiled
1>        with
1>        [
1>            Context=context_t,
1>            T=My
1>        ]
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(990): note: see reference to function template instantiation 'fmt::v5::internal::typed_value<Context,fmt::v5::internal::custom_type> fmt::v5::internal::make_value<Context,My,wchar_t>(const T &)' being compiled
1>        with
1>        [
1>            Context=context_t,
1>            T=My
1>        ]
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(1047): note: see reference to function template instantiation 'fmt::v5::internal::value<Context> fmt::v5::internal::make_arg<true,Context,My>(const T &)' being compiled
1>        with
1>        [
1>            Context=fmt::v5::wformat_context,
1>            T=My
1>        ]
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(1047): note: while compiling class template member function 'fmt::v5::format_arg_store<context_t,My>::format_arg_store(const My &)'
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(1394): note: see reference to function template instantiation 'fmt::v5::format_arg_store<context_t,My>::format_arg_store(const My &)' being compiled
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(1387): note: see reference to class template instantiation 'fmt::v5::format_arg_store<context_t,My>' being compiled
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmttest.cpp(31): note: see reference to function template instantiation 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> fmt::v5::format<wchar_t[3],My>(const String (&),const My &)' being compiled
1>        with
1>        [
1>            String=wchar_t [3]
1>        ]
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(574): error C2228: left of '.parse' must have class/struct/union
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(574): note: type is 'int'
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(575): error C2228: left of '.format' must have class/struct/union
1>c:\users\scottl\documents\visual studio 2017\projects\fmttest\fmttest\fmt\core.h(575): note: type is 'int'
1>Done building project "FmtTest.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by vitaut** [comment]
You should include `fmt/ostream.h` for ostream formatting support: http://fmtlib.net/5.1.0/api.html#std-ostream-support
