### ISSUE TITLE
Custom formatting of built in types sample doesn't compile

### ISSUE THREAD

**Issue by ScottLangham** [fmtlib/fmt#850]
When I used fmt a year or two ago I had some code for formatting custom types. I've upgraded to the latest version of fmt and the API in this area appears to have changed. So, I'm following the documentation at the following link to try and reimplement this.

http://fmtlib.net/latest/api.html#custom-formatting-of-built-in-types

I'm using the code below in a Visual Studio 15.7.3 console app, and the errors are below that.

Am I doing something wrong?

```
// FmtTest.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"

#define FMT_HEADER_ONLY
#include "fmt\format.h"
#include "fmt\ostream.h"

using arg_formatter =
fmt::arg_formatter<fmt::back_insert_range<fmt::internal::buffer>>;

// A custom argument formatter that formats negative integers as unsigned
// with the ``x`` format specifier.
class custom_arg_formatter : public arg_formatter {
public:
	custom_arg_formatter(fmt::format_context &ctx, fmt::format_specs &spec)
		: arg_formatter(ctx, spec) {}

	using arg_formatter::operator();

	void operator()(int value) {
		if (spec().type() == 'x')
			(*this)(static_cast<unsigned>(value)); // convert to unsigned and format
		else
			arg_formatter::operator()(value);
	}
};

std::string custom_vformat(fmt::string_view format_str, fmt::format_args args) {
	fmt::memory_buffer buffer;
	// Pass custom argument formatter as a template arg to vformat_to.
	fmt::vformat_to<custom_arg_formatter>(buffer, format_str, args);
	return fmt::to_string(buffer);
}

template <typename ...Args>
inline std::string custom_format(
	fmt::string_view format_str, const Args &... args) {
	return custom_vformat(format_str, fmt::make_format_args(args...));
}

int main()
{
	std::string s = custom_format("{:x}", -42); // s == "ffffffd6"
	return 0;
}
```

--------------

> 1>------ Build started: Project: FmtTest, Configuration: Debug Win32 ------
> 1>SampleCustomFormatting.cpp
> 1>c:\fmttest\fmt\format.h(3393): error C2664: 'void fmt::v5::internal::context_base<OutputIt,fmt::v5::basic_format_context<OutputIt,Char>,Char>::advance_to(std::back_insert_iterator<fmt::v5::internal::basic_buffer<char>>)': cannot convert argument 1 from 'void' to 'std::back_insert_iterator<fmt::v5::internal::basic_buffer<char>>'
> 1>        with
> 1>        [
> 1>            OutputIt=std::back_insert_iterator<fmt::v5::internal::basic_buffer<char>>,
> 1>            Char=char
> 1>        ]
> 1>c:\fmttest\fmt\format.h(3393): note: Expressions of type void cannot be converted to other types
> 1>c:\fmttest\fmt\format.h(3380): note: while compiling class template member function 'fmt::v5::internal::null_terminating_iterator<Char> fmt::v5::format_handler<ArgFormatter,Char,Context>::on_format_specs(fmt::v5::internal::null_terminating_iterator<Char>)'
> 1>        with
> 1>        [
> 1>            Char=char,
> 1>            ArgFormatter=custom_arg_formatter,
> 1>            Context=fmt::v5::format_context
> 1>        ]
> 1>c:\fmttest\fmt\format.h(2254): note: see reference to function template instantiation 'fmt::v5::internal::null_terminating_iterator<Char> fmt::v5::format_handler<ArgFormatter,Char,Context>::on_format_specs(fmt::v5::internal::null_terminating_iterator<Char>)' being compiled
> 1>        with
> 1>        [
> 1>            Char=char,
> 1>            ArgFormatter=custom_arg_formatter,
> 1>            Context=fmt::v5::format_context
> 1>        ]
> 1>c:\fmttest\fmt\format.h(3406): note: see reference to class template instantiation 'fmt::v5::format_handler<ArgFormatter,Char,Context>' being compiled
> 1>        with
> 1>        [
> 1>            ArgFormatter=custom_arg_formatter,
> 1>            Char=char,
> 1>            Context=fmt::v5::format_context
> 1>        ]
> 1>c:\fmttest\samplecustomformatting.cpp(35): note: see reference to function template instantiation 'OutputIt fmt::v5::vformat_to<custom_arg_formatter,char,fmt::v5::format_context>(fmt::v5::back_insert_range<fmt::v5::internal::buffer>,fmt::v5::basic_string_view<char>,fmt::v5::basic_format_args<fmt::v5::format_context>)' being compiled
> 1>        with
> 1>        [
> 1>            OutputIt=std::back_insert_iterator<fmt::v5::internal::basic_buffer<char>>
> 1>        ]
> 1>Done building project "FmtTest.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> 
>

**Comment by ScottLangham** [comment]
Ok, possibly its the documentation that needs updating?
If I change the return type of `void operator()(int value)` to `auto` and get it to return `out()` it seems to work.

**Comment by vitaut** [comment]
Good catch, thanks! Updated the docs in https://github.com/fmtlib/fmt/commit/8671689449acfd7b960e8adee302c29c2e643aff.
