### ISSUE TITLE
Support for 'multiplication' pattern with lambda

### ISSUE THREAD

**Issue by rafaelhamdan** [fmtlib/fmt#856]
It would be very useful if we could replicate patterns in strings using fmt. For example:

`std::string str = fmt::format("{[{}]}*10", lambda(int i));`

In this case, I want to replicate the pattern [{}] 10 times, and for every replacement a lambda function would be called receiving the corresponding index.

**Comment by vitaut** [comment]
There is no need to change the core library to support this specific use case. You can easily implement it via the extension API. For example

```c++
#include "fmt/format.h"

template <typename F>
struct repeated {
  int n;
  F f;
};

template <typename F>
using result_t = decltype(std::declval<F>()(0));

template <typename F>
repeated<F> rep(int n, F f) { return {n, f}; }

template <typename F>
struct fmt::formatter<repeated<F>>: fmt::formatter<result_t<F>> {
  template <typename FormatContext>
  auto format(const repeated<F> &r, FormatContext &ctx) {
    auto it = ctx.begin();
    for (int i = 0; i < r.n; ++i)
      it = fmt::formatter<result_t<F>>::format(r.f(i), ctx);
    return it;
  }
};

int main() {
  fmt::print("{:3}\n", rep(10, [](int i){ return i * i; }));
}
```
prints
```
  0  1  4  9 16 25 36 49 64 81
```

**Comment by eullerborges** [comment]
That's an elegant solution. thanks @vitaut .
