### ISSUE TITLE
How to handle long serialization mechanism in fmt 5 ? 

### ISSUE THREAD

**Issue by jcelerier** [fmtlib/fmt#859]
I have a bunch of code with 4.x which uses a single fmt::MemoryWriter to write a lot of things - the things being written can change according to runtime conditions, e.g.

     void debug_stuff(fmt::MemoryWriter& wr, some_stuff, some_other_stuff, ...) { 
       if(whatever)
       {
          wr << some_stuff << some_other_stuff;
       }
       else
       {
         wr << "boop boop" << some_stuff << "beep beep";
         debug_other_stuff(wr, other_stuff);
       }
     }

how to handle these cases with fmt 5.x ?

**Comment by jcelerier** [comment]
e.g. here's an actual example code I had: 

    void format(fmt::MemoryWriter& wr, const ossia::net::node_base& n) {
      auto parent = n.get_parent();
      while (parent != nullptr)
      {
        w << '\t';
        parent = parent->get_parent();
      }
      w << n.get_name();
      if (auto addr = n.get_parameter())
      {
        w << " : " << value_to_pretty_string(addr->value()) << ", AccessMode("
          << addr->get_access() << ")"
          << ", BoundingMode(" << addr->get_bounding() << ")"
          << ", Domain(" << addr->get_domain() << ")"
          << ", Unit(" << ossia::get_pretty_unit_text(addr->get_unit()) << ")";
      }
    }

    return w;

**Comment by vitaut** [comment]
You can call `format_to` repeatedly, e.g.

```
void debug_stuff(fmt::memory_buffer& wr, int some_stuff, int some_other_stuff) { 
   if (whatever)
   {
     format_to(wr, "{}{}", some_stuff, some_other_stuff);
   }
   else
   {
     format_to(wr, "boop boop{}beep beep", some_stuff);
     debug_other_stuff(wr, some_other_stuff);
   }
 }
```
