### ISSUE TITLE
compiling error if included both "fmt/ranges.h" and "fmt/ostream.h"

### ISSUE THREAD

**Issue by hhggit** [fmtlib/fmt#865]
The following code would compile failed with error `ambiguous template instantiation for ‘struct fmt::v5::formatter<fmt::v5::basic_string_view<char>, char, void>’`  if uncommented the line `//#include <fmt/ranges.h>`
``` c++
#define FMT_HEADER_ONLY
#include <fmt/format.h>
#include <fmt/ostream.h>
//#include <fmt/ranges.h>

struct foo {
  friend std::ostream& operator<<(std::ostream& os, const foo&) {
    return os << "foo";
  }
};
int main() {
  fmt::print("{}", foo{});
}
```

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/70a6a4bb010db3b278c850569d894d95f01400f3. Thanks for reporting and fixing the issue!
