### ISSUE TITLE
arbitrary buffer support in `format_to`

### ISSUE THREAD

**Issue by seanmiddleditch** [fmtlib/fmt#869]
The only overload for `format_to` for buffers works explicitly with `basic_memory_buffer` and not arbitrary buffer types or even the provided `basic_fixed_buffer` type. Easy to workaround, but annoying.

```
template <typename String, typename... Args, std::size_t SIZE = inline_buffer_size>
inline format_context::iterator format_to(basic_memory_buffer<char, SIZE> &buf, const String &format_str, const Args & ... args);
```

should maybe be something more like:

```
template <typename String, typename... Args>
inline format_context::iterator format_to(internal::basic_buffer<format_string_traits<String>::char_type> &buf, const String& format_str, const Args & ... args);
```

**Comment by vitaut** [comment]
This is intentional. The buffer API has been superseded by the iterator-based API (`fmt::format_to`): http://fmtlib.net/latest/api.html#output-iterator-support, following the LEWG feedback. `basic_fixed_buffer` was left by accident and will be removed, thanks for bringing this to my attention.
