### ISSUE TITLE
compatability with prettyprint

### ISSUE THREAD

**Issue by nevion** [fmtlib/fmt#871]
fmt used to work/integrate well with https://github.com/louisdx/cxx-prettyprint , however I do not find that to be the case since 5.0, outputting something like a std::list of data no longer works.

Reproducing program:
```
#include <list>

#include <fmt/format.h>
#include <prettyprint.hpp>

int main( int argc, char **argv ) {

  std::list<int> container;

  for( size_t i = 0; i < 10; ++i){
    container.push_back( (int) i );
  }
  fmt::print("container = {}", container);

  return 0;
}
```

Errors compiling with gcc 5.4:

> In file included from external/fmt/include/fmt/format.h:54:0,
>                  from fmttest/main.cpp:4:
> external/fmt/include/fmt/core.h: In instantiation of 'static void fmt::v5::internal::value<Context>::format_custom_arg(const void*, Context&) [with T = std::__cxx11::list<int>; Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>]':
> external/fmt/include/fmt/core.h:563:19:   required from 'fmt::v5::internal::value<Context>::value(const T&) [with T = std::__cxx11::list<int>; Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>]'
> external/fmt/include/fmt/core.h:591:76:   required from 'fmt::v5::internal::init<Context, T, TYPE>::operator fmt::v5::internal::value<Context>() const [with Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>; T = const std::__cxx11::list<int>&; fmt::v5::internal::type TYPE = (fmt::v5::internal::type)13u]'
> external/fmt/include/fmt/core.h:995:35:   required from 'typename std::enable_if<IS_PACKED, fmt::v5::internal::value<Context> >::type fmt::v5::internal::make_arg(const T&) [with bool IS_PACKED = true; Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>; T = std::__cxx11::list<int>; typename std::enable_if<IS_PACKED, fmt::v5::internal::value<Context> >::type = fmt::v5::internal::value<fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >]'
> external/fmt/include/fmt/core.h:1053:51:   required from 'fmt::v5::format_arg_store<Context, Args>::format_arg_store(const Args& ...) [with Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>; Args = {std::__cxx11::list<int, std::allocator<int> >}]'
> external/fmt/include/fmt/core.h:1431:55:   required from 'void fmt::v5::print(fmt::v5::string_view, const Args& ...) [with Args = {std::__cxx11::list<int, std::allocator<int> >}; fmt::v5::string_view = fmt::v5::basic_string_view<char>]'
> fmttest/main.cpp:14:41:   required from here
> external/fmt/include/fmt/core.h:577:56: error: 'fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>::formatter_type<std::__cxx11::list<int> >::type f' has incomplete type
>      typename Context::template formatter_type<T>::type f;

**Comment by foonathan** [comment]
You need to include <fmt/ostream.h>.
