### ISSUE TITLE
MemoryWriter not a class of fmt.

### ISSUE THREAD

**Issue by oneStarCai** [fmtlib/fmt#876]
When I defined a variable like 'fmt::MemoryWriter m_sql '. it accurs error! And I hadn't found where the definition of the class MemoryWriter. So how should I user this class?

**Comment by vitaut** [comment]
`fmt::MemoryWriter` is a part of fmt version 4: https://github.com/fmtlib/fmt/releases/tag/4.1.0, but has been removed in version 5 in favor of the iterator-based API.
