### ISSUE TITLE
fp(Double d) ctor adds static_assert that sizeof(double) == sizeof(uint64_t)

### ISSUE THREAD

**Issue by jgennis** [fmtlib/fmt#878]
It looks like fmt 5.1.0 introduced the fp class, which includes a ctor that calls bit_cast<uint64_t>(d). This ctor gets called from various places such that the type of d is double. In fmt 5.1.0 the first place that triggers the static_assert is in basic_writer<Range>::write_double. In fmt 5.2.1 the first place is in grisu2_format_positive.

I've been using fmt up to 5.0.0 targeting an architecture that doesn't support 64-bit floats, and so has both float and double defined to be 32-bit. Even though FMT_USE_GRISU is presumably 0 (I didn't define it, and it looks like it defaults to 0), the static_assert still triggers, preventing use of fmt 5.1.0 and 5.2.1 (I haven't tried 5.2.0, but I assume it has the same issue).

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/d7f17613f5d7f0411c263a563bca8295bd062575. Thanks for reporting!
