### ISSUE TITLE
format_to(OutputIt)

### ISSUE THREAD

**Issue by huangqinjin** [fmtlib/fmt#880]
```c++
std::vector<char> buf;
fmt::format_to(std::back_inserter(buf), "{}", 0);
```

The above works, but not the below.

```c++
std::vector<wchar_t> buf;
fmt::format_to(std::back_inserter(buf), L"{}", 0);
```

**Comment by vitaut** [comment]
Added `wchar_t` support to `format_to` in https://github.com/fmtlib/fmt/commit/e4ca37ccf6723bd041a3fc677614551e32bf1f12. Thanks for reporting.
