### ISSUE TITLE
to_string and _format UDL do not work with struct tm

### ISSUE THREAD

**Issue by marack** [fmtlib/fmt#884]
There seems to be a problem when trying to format the `struct tm` type when using the `to_string()` function or the `_format` UDL, even though the type format correctly when using `format()`.

For example:
```c++
struct tm tmm;
...
fmt::format("{}", tmm); // okay
fmt::to_string(tmm); // compilation error
"{}"_format(tmm); // compilation error
```

The compilation error I get boils down to:
```
.../fmt/format.h: In instantiation of ‘std::__cxx11::string fmt::v5::to_string(const T&) [with T = tm; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
.../format.cc:203:3:   required from here
.../fmt/format.h:3428:3: error: no matching function for call to ‘fmt::v5::basic_writer<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::write(const tm&)’
   writer(buf).write(value);
   ^~~~~~
```

Using the current master branch with gcc 8.1.1.

**Comment by vitaut** [comment]
`_format` is defined in the `fmt::literals` namespace (https://godbolt.org/z/HhCkbF):

```c++
#include <fmt/time.h>

int main() {
  tm tmm;
  using namespace fmt::literals;
  "{}"_format(tmm);
}
```

As for `fmt::to_string`, it doesn't support user-defined formatters at the moment. This will be addressed in one of the future versions.

**Comment by marack** [comment]
Sorry I over simplified my example.  The `_format` version still breaks if you provide any arguments to the formatter (https://godbolt.org/z/oVBUW0):

```c++
#include <fmt/time.h>

int main() {
  tm tmm;
  using namespace fmt::literals;
  "{:%Y}"_format(tmm);
}
```

Thanks for the info about `fmt::to_string`.  I'll avoid it for now.

**Comment by vitaut** [comment]
`_format` tries to do compile-time checks while `tm` formatting is based on `std::strftime` which is not `constexpr`, thus the error. You can use `fmt::format("{:%Y}", tmm)` instead. #864 might address the issue by providing `constexpr`-ready format string parsing for times.

**Comment by vitaut** [comment]
Closing in favor of #864.
