### ISSUE TITLE
No format check at compile time

### ISSUE THREAD

**Issue by stayprivates** [fmtlib/fmt#893]
The doc says:

> Format strings can be checked at compile time:
> 
> // test.cc
> #define FMT_STRING_ALIAS 1
> #include <fmt/format.h>
> std::string s = format(fmt("{2}"), 42);
> $ c++ -Iinclude -std=c++14 test.cc

I'm using gcc 4.8.3 with -std=gnu++11, but I'm not getting any compiler error. I've the exact same code as in the doc. Tried gnu++1y,  which is the highest level of language support available, same thing.

Is this expected? Do I need to switch to C++14 to get this capability?

Thanks!

**Comment by vitaut** [comment]
This is expected. The compile-time format string checks require relaxed constexpr support (C++14 feature) which is available in gcc since version 6. Without it the checks fallback to runtime.
