### ISSUE TITLE
Supporting custom char type

### ISSUE THREAD

**Issue by Yelnats321** [fmtlib/fmt#900]
Things have changed since 4.x, so I was wondering what the correct way to use `fmt` to format a custom character type would be. The use case is fine grained color support (not using VT100 escape codes), so ideally I can eventually write something like this:
`format("Test string {}"_color(red), 3.14_color(blue))`
Therefore I need to support a string type that has color information.

Using `core.h` with a custom char type I got unresolved issues with `vformat` being an unresolved symbol (although I compiled with `FMT_HEADER_ONLY`) and using `format.h` I got issues with `vformat_to`. What is the path of least resistance to get the results I want?

**Comment by vitaut** [comment]
Most formatting functions have been recently parameterized on character (and string) type, but some more work is needed to fully support custom character types (and you do need to include `fmt/format.h`). PRs are welcome.

**Comment by vitaut** [comment]
Merging into #698 which is essentially the same issue.
