### ISSUE TITLE
Visual studio 2017 format locale number string got exception

### ISSUE THREAD

**Issue by Joe-Yeh** [fmtlib/fmt#905]
the following code in the microsoft visual studio 2017 got exception

  unsigned int nValu1=0xFFFFFFFF;
  fmt::print("{:n}",nValu1);

**Comment by vitaut** [comment]
What {fmt} library version do you use and what was the exception message?

**Comment by Joe-Yeh** [comment]
1. {{fmt}} library version ==>  #define FMT_VERSION 50201
2. exception point ==> in format.h line 1073 => return internal::copy_str<OutChar>(buffer, buffer + num_digits, out);
3. exception data ==> Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted. occurred
4. seems allocated working buffer is not enough.

**Comment by vitaut** [comment]
Good catch. Fixed in https://github.com/fmtlib/fmt/commit/ddd7caf38eeb281641f0881634c576b50c637c38, thanks!
