### ISSUE TITLE
Add fmt check to clang-tidy

### ISSUE THREAD

**Issue by stayprivates** [fmtlib/fmt#908]
Hello,

I'm kind of reluctant to let the whole team use ftm.  My experimentation shows that the following statement does not produce any compiler warning/error:

fmt::print("{} {}\n", 0 );

while a printf with a similar bad format will trigger the compiler.

printf("%d %d\n", 0);

Fmt is so nice to use that it's very tempting to ignore this and use it at will, but having fmt::print generate exception at run time is worrisome.  I guess better unit test, code coverage, etc will mitigate that difference in behaviour, it's not a solution in the short term.

So I thought why not add a check to clang-tidy that will validate the format. When fmt makes it into the C++ standard, I guess the compiler should be able to issue the warning, much like it does for printf familiy of function but, in the meantime, clang-tidy might be a good option.

I'd be willing to give a stab at it (have already customized some existing checks), but for the next two months I'm on a tight deadline and don't want to risk getting behind. Best I could do for now is throw the idea out there.

Regards,
-Mario

**Comment by vitaut** [comment]
Thanks for the suggestion. A clang-tidy check would be nice and you can reuse the format string parser provided by {fmt} for that. It's internal right now but I can make it a part of the public API. You can also get compile-time checks by wrapping the format string in the `fmt()` macro

```
#define FMT_STRING_ALIAS 1
#include <fmt/format.h>

int main() {
  print(fmt("{} {}\n"), 0);
}
```

See https://godbolt.org/z/7_coMZ.

**Comment by stayprivates** [comment]
Great thanks.

In another issue I openned you mention C++14, so I though I could just have our continuous integration machine do a pass with a different gcc/clang run with C++14 enable and something like -fsyntax-only)

In my testing, with clang7, I could not trigger a compile error if I did something like 

`print(fmt("{%s}\n"),  4);`

That's why I was looking for a solution, because I really want to include fmt in our stuff ;-)

**Comment by vitaut** [comment]
Yeah, a separate CI run with C++14 and compile-time checks enabled is how I'd recommend going about it. The checks should work on clang 7, unless you pass `-std=c++11` or lower.

**Comment by vitaut** [comment]
Closing the issue since compile-time checks are already supported.
