### ISSUE TITLE
Add pkg-config files

### ISSUE THREAD

**Issue by DanySpin97** [fmtlib/fmt#912]
Add pkg-config files to easily add fmt as a system dependency.

**Comment by vitaut** [comment]
The library already provides CMake package configs that serve essentially the same purpose: https://cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html

**Comment by DanySpin97** [comment]
CMake package configs are not supported by Makefile, autoconf and meson.

**Comment by vitaut** [comment]
Sure, but it should be trivial to link against the library (or even use the header-only config) in any of those. What is the advantage of pkg-config?

**Comment by DanySpin97** [comment]
> but it should be trivial to link against the library

I disagree. Consider for example cross-compiling, where libs and include are stored in different folders than usual.

pkg-config has the same advantage that CMake package has, plus it can be used anywhere and support every build systemd or script. Cross-compile toolchain usually use a wrapper over pkg-config, like x86_64-pkg-config and arm-pkg-config.

Also, CMake supports pkg-config: https://cmake.org/cmake/help/v3.9/module/FindPkgConfig.html

You're supporting CMake and that's great, I would be glad if you could support meson and the other build systems out of the box so it will be really simple to include your library.

**Comment by vitaut** [comment]
Contributions are welcome, provided that the pkg-config support doesn't add maintenance burden. In particular, it should be auto-generated from the CMake config which is the source of truth.

**Comment by vitaut** [comment]
pkg-config support was added in #916.
