### ISSUE TITLE
fmt::string_view ctor under Clang (in pre c++17) much slower than of gcc

### ISSUE THREAD

**Issue by gabime** [fmtlib/fmt#914]
**Version**: fmt 5.2.1, Clang 6.0

**Summary**
Constructing ```fmt::string_view``` with ```const char*``` of size 515 bytes takes about ~180 ns  under Clang, while under gcc it takes less than 1ns.

**Cause**
The cause is that https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h@L217 
```c++
FMT_CONSTEXPR size_t length(const char *s) { return std::strlen(s); }
```

is only enabled for gcc (why?) so clang ends up using the much slower implementation (https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h@L210)

Just to be sure I tried to enable for clang as well, and performance went from 180 to 1ns:
```c++
#if FMT_GCC_VERSION || defined(__clang__)
FMT_CONSTEXPR size_t length(const char *s) { return std::strlen(s); }
#endif
```

**Comment by vitaut** [comment]
The problem is that `strlen` is not `constexpr` on clang, only on gcc. It can be solved by using `__builtin_strlen` on clang I think.

**Comment by gabime** [comment]
Confirmed. Same performance for clang and g++ now.
Thanks for the quick resolution

**Comment by vitaut** [comment]
@gabime 180 -> 1 ns seems like excessively big difference though. Out of curiosity, could you give the details about your setup: clang version, what optimization level you used and test code?

**Comment by gabime** [comment]
Sure. Here is the test:
```c++
#include "benchmark/benchmark.h" //google bencmark
#include "fmt/core.h"

void bench_sv(benchmark::State& state)
{
    const char *msg = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pharetra metus cursus "
                      "lacus placerat congue. Nulla egestas, mauris a tincidunt tempus, enim lectus volutpat mi, eu consequat sem "
                      "libero nec massa. In dapibus ipsum a diam rhoncus gravida. Etiam non dapibus eros. Donec fringilla dui sed "
                      "augue pretium, nec scelerisque est maximus. Nullam convallis, sem nec blandit maximus, nisi turpis ornare "
                      "nisl, sit amet volutpat neque massa eu odio. Maecenas malesuada quam ex, posuere congue nibh turpis duis.";


    for (auto _ : state)
    {
        fmt::string_view sv(msg);
        benchmark::DoNotOptimize(sv);
    }
}

BENCHMARK(bench_sv);

BENCHMARK_MAIN();
```

Compiled with:
```
g++ latency.cpp -o latency -march=native -Wall -Wextra -pedantic -std=c++11 -pthread -I../include -fmax-errors=1  -I./fmt/include -Ofast -flto -Wl,--no-as-needed -lbenchmark
```
