### ISSUE TITLE
Non-throwing version of basic_fixed_buffer

### ISSUE THREAD

**Issue by oktal** [fmtlib/fmt#915]
I would like to use `fmt::basic_fixed_buffer<CharT>` in combination with `fmt::writer` to format content in a fixed-size buffer.

However, I would like to keep formatting until I reach the capacity of the buffer and be notified when it happens. Currently, I'm relying on the fact that `basic_fixed_buffer::grow()` throws a `std::runtime_error` to know whether my buffer is full or not but I think it's not ideal.

I propose non-throwing version of `grow()` and `write` functions. For example, I'd like to write:

```cpp
char buffer[MAX_BODY_SIZE];
fmt::basic_fixed_buffer<char> buf(buffer);
fmt::writer writer(buf);

if (!writer.try_write(sequence_number))
{
    // Do something
}
```

Thanks.

**Comment by vitaut** [comment]
`basic_fixed_buffer` was an artefact of a legacy API and was removed in #902. Please use the format API instead, e.g.

```c++
fmt::format_to_n(buffer, MAX_BODY_SIZE, "{}", sequence_number);
```
