### ISSUE TITLE
Printf support size limit

### ISSUE THREAD

**Issue by fancl20** [fmtlib/fmt#917]
Does fmt::printf or fmt::sprintf support size limit like std::snprintf or fmt::format_to_n ? c_str Arguments contains dirty data may hang the program without size limit.

**Comment by vitaut** [comment]
No, but it should be relatively straightforward to implement one in the same way as `format_to_n`. PRs are welcome!

**Comment by DanielaE** [comment]
@vitaut : the requested feature is implemented, may be you like it. Merging it requires a merge of #995 before.

**Comment by vitaut** [comment]
@DanielaE, awesome, looking forward for the PR!
