### ISSUE TITLE
Problem with linking fmt using CMake after installing library

### ISSUE THREAD

**Issue by tehKaiN** [fmtlib/fmt#923]
So I'm trying to use this lib with my project and in cmakelists.txt I've written something like this:

``` cmake
#wjwwood-serial
find_package(serial REQUIRED)
include_directories(${serial_INCLUDE_DIRS})
target_link_libraries(romprg serial) # <- this works

#fmt
find_package(fmt REQUIRED)
include_directories(${fmt_INCLUDE_DIRS})
target_link_libraries(romprg fmt) #<- that ain't working
# this also ain't working
target_link_libraries(romprg PRIVATE fmt-header-only)
# that too - ftm_LIBS is empty
target_link_libraries(romprg ${fmt_LIBS}
```

my setup is such that I'm cloning various libs and install them in my os via `make install` after generating makefile using cmake so that I don't have different copies of same libs on my os. I really like to do it that way and I don't want to change my habits without serious reason. Other libs don't make such problems, so I guess that's something with your cmakelists, but I'm a cmake noob so I'm not sure.

Thanks for any help ;)

**Comment by tehKaiN** [comment]
Okay, I've got it, should be:

``` cmake
#fmt
find_package(fmt REQUIRED)
include_directories(${fmt_INCLUDE_DIRS})
target_link_libraries(romprg fmt::fmt)
```

I think this info should be highlighted in docs, because it seems it's not as obvious as it should be. ;)

**Comment by foonathan** [comment]
You shouldn't need the `include_directories()`.

**Comment by vitaut** [comment]
Updated docs in https://github.com/fmtlib/fmt/commit/43731538001f4feb2c47da7bc14ee23c32a88536, thanks.
