### ISSUE TITLE
Strange issue with fmt::printf

### ISSUE THREAD

**Issue by nick42** [fmtlib/fmt#925]
So I'm trying to convert some code which used a previous version of the library (from ~2 years ago) to current, and I've run into an issue I can't figure out. Godbolt demo of issue: https://godbolt.org/z/F0Wn_X

Summary: For some reason, the internal template expansion is doing something strange with the ErrorHandler parameter. Other usage cases work, but something related to using %c seems to be breaking it.

Ideas?

BTW, suspicious this might be related: printf.h, line ~552:
      case 'c':
        // TODO: handle wchar_t better?

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/a23d592472b375a92df9c6040ccbe4b9065b5d6d, thanks for reporting.
