### ISSUE TITLE
Lintian warning

### ISSUE THREAD

**Issue by trebmuh** [fmtlib/fmt#927]
While building a .deb intended for Debian Stretch of a downstream project named [Sysexxer-NG](https://github.com/linuxmao-org/sysexxer-ng/) (which depends on _fmidi_ which itself depends on _fmt_), Lintian (a Debian packaging checker tool) is telling me the following:

```
E: sysexxer-ng source: source-is-missing thirdparty/fmidi/thirdparty/fmt/doc/_static/bootstrap.min.js
N: 
N:    The source of the following file is missing. Lintian checked a few
N:    possible paths to find the source, and did not find it.
N:    
N:    Please repack your package to include the source or add it to
N:    "debian/missing-sources" directory.
N:    
N:    If this is a false-positive, please report a bug against Lintian.
N:    
N:    Severity: serious, Certainty: possible
N:    
N:    Check: cruft, Type: source
N: 
```

[This has been reported to downstream](https://github.com/jpcima/fmidi/issues/1) (fmidi) which advise to report it here.

Hope that helps.

**Comment by vitaut** [comment]
You can ignore this warning. Bootstrap is just for the docs and there is no point in including its unminified source.

**Comment by vitaut** [comment]
Reopened and a PR to fix/suppress this will be welcome provided that it's not too intrusive.

**Comment by vitaut** [comment]
BTW fmt is available in Debian as `libfmt-dev` so you should probably use it in your deb package. This will avoid the lint warning and potential issues due to conflicting dependencies.

**Comment by vitaut** [comment]
So I think the correct solution is to use `libfmt-dev` in the deb package but a PR would be welcome if it doesn't involve adding unused bootstrap source code to the repo.
