### ISSUE TITLE
Unresolved external symbol with FMT_HEADER_ONLY defined

### ISSUE THREAD

**Issue by TrueBers** [fmtlib/fmt#929]
Using VS 2017 15.8.9 compiling the following code:
```
#define FMT_HEADER_ONLY
#include <fmt/core.h>

inf main(){
     fmt::print("Got data {}", 42);

     return 0;
}
```

Got an error:
`error LNK2019: unresolved external symbol "void __cdecl fmt::v5::vprint(class fmt::v5::basic_string_view<char>,struct fmt::v5::format_args)" (?vprint@v5@fmt@@YAXV?$basic_string_view@D@12@Uformat_args@12@@Z) referenced in function "void __cdecl fmt::v5::print<char [14],unsigned int>(char const (&)[14],unsigned int const &)" (??$print@$$BY0O@DI@v5@fmt@@YAXAAY0O@$$CBDABI@Z)`

Why is it trying to link something when `FMT_HEADER_ONLY` is defined?

**Comment by vitaut** [comment]
You should include `<fmt/format.h>` when using the header-only configuration. `<fmt/core.h>` is a header that contains a lightweight subset of the API that is described in http://fmtlib.net/latest/api.html#core-api .

**Comment by BlackTeaAttenuation** [comment]
For anyone who meets the error like :     **"LNK2001 unresolved external symbol "public: static unsigned int const * const fmt::v6::internal::basic_data<void>::zero_or_powers_of_10_32" "**  **---especially in visual studio**  

Please try adding  **#define FMT_HEADER_ONLY**     at the beginning of the code.
