### ISSUE TITLE
warnings in msvc2015 around localtime and gmtime

### ISSUE THREAD

**Issue by andry81** [fmtlib/fmt#931]
> fmt/time.h(51): warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
> fmt/time.h(86): warning C4996: 'gmtime': This function or variable may be unsafe. Consider using gmtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

These warnings goes spammed almost everythere in sources.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/fecb2d6f0d6c97986c72c7b28f6ff52b3af6348c.
