### ISSUE TITLE
Missing wide string overload for format_to?

### ISSUE THREAD

**Issue by jeanga** [fmtlib/fmt#935]
Hi,

I am not sure but it seems format.h misses one overload of format_to for wchar.

Specifically, I am looking for this overload but for wchar (format.h, line 3510): 
```c++
template <typename OutputIt, typename... Args>
inline OutputIt format_to(OutputIt out, string_view format_str,
                          const Args & ... args) {
  return vformat_to(out, format_str,
      make_format_args<typename format_context_t<OutputIt>::type>(args...));
}
```
adding this overload:
```c++
template <typename OutputIt, typename... Args>
inline OutputIt format_to(OutputIt out, wstring_view format_str,
	const Args & ... args) {
	return vformat_to(out, format_str,
		make_format_args<typename format_context_t<OutputIt, wchar_t>::type>(args...));
}
```

Seems to solve my compilation issue but I'm not sure this is correct…

On a more general note, is libfmt compatible with unicode strings or there is very little testing with these strings?

Any way, thanks for any help!
Jean

**Comment by vitaut** [comment]
`format_to` is parameterized on string type in the `master` branch and should work with `char_t` and other character types: https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L3496

> On a more general note, is libfmt compatible with unicode strings or there is very little testing with these strings?

Yes, Unicode strings are supported. However in some places (width and fill) code units are used where more high level units would be more appropriate.

**Comment by jeanga** [comment]
Seems to be a version issue (currently using 5.2.1).
master seems correct.
(time for a new release?)
thanks!
