### ISSUE TITLE
Major release prep

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#940]
Things that need to be done in the next major release (because they are API breaking and cannot be done right now):

- [x] Remove `context_base::begin`.
- [x] Remove `arg_formatter(context_type &ctx, format_specs &spec)`.
- [x] Remove `context_base::args()`.
- [x] Refactor undocumented `format_specs` API to make its components follow naming conventions and support a variable-width fill.
- [x] Remove deprecated color formatting.
- [x] Remove `fmt::visit`.
- [x] Merge `time.h` into `chrono.h` and remove the former because it may collide with system's `time.h` if users specify include directories incorrectly.
- [x] Move `basic_writer`, `writer`, and `wwriter` to the internal namespace, since they are an implementation detail as of version 5.
- [x] Replace workarounds for lack of alias templates with proper alias templates.

**Comment by Rakete1111** [comment]
Can we add "Remove deprecated color formatting" to the list?

**Comment by vitaut** [comment]
> Can we add "Remove deprecated color formatting" to the list?

Done.
