### ISSUE TITLE
Extend Core API

### ISSUE THREAD

**Issue by Leandros** [fmtlib/fmt#942]
Make the following part of the Core API:

- `format_to_n` 
- `formatted_size`

**Comment by vitaut** [comment]
`fmt/core.h` provides a lightweight subset of the API. Iterator support doesn't belong there and with modules it will be redundant anyway.

**Comment by vitaut** [comment]
`format_to_n` and `formatted_size` are now part of the core API (this became possible after the recent improvements to buffering).
