### ISSUE TITLE
Make a minor release for packagers

### ISSUE THREAD

**Issue by bemeurer** [fmtlib/fmt#948]
Pkg-config support, which is a must when trying to build meson projects that rely of fmtlib, was added after the last tagged release. I'd like to ask for a new minor release to be made so that package maintainers can pick up this change and make the pc files available on their respective distributions.

**Comment by vitaut** [comment]
Sure, I am planning to do a release in the next couple of weeks.

**Comment by vitaut** [comment]
Here you go: https://github.com/fmtlib/fmt/releases/tag/5.3.0
