### ISSUE TITLE
Implicit conversion warning and x86 only signed/unsigned comparison warnings

### ISSUE THREAD

**Issue by AGraber** [fmtlib/fmt#955]
Sometimes, this warning appears on MSVC 17:
`\lib\fmt\include\fmt\core.h(1284): warning C4244: 'return': conversion from 'unsigned __int64' to 'unsigned int', possible loss of data`

https://github.com/fmtlib/fmt/blob/e7e2ab107035a54216c6927b14aa8d140c5c761a/include/fmt/core.h#L1284-L1285

When compiling on x86, two more warnings appear:
`\lib\fmt\include\fmt\format-inl.h(625): warning C4018: '<': signed/unsigned mismatch`
https://github.com/fmtlib/fmt/blob/e7e2ab107035a54216c6927b14aa8d140c5c761a/include/fmt/format-inl.h#L625

And:
`\lib\fmt\include\fmt\format-inl.h(649): warning C4018: '>': signed/unsigned mismatch`
https://github.com/fmtlib/fmt/blob/e7e2ab107035a54216c6927b14aa8d140c5c761a/include/fmt/format-inl.h#L649

**Comment by vitaut** [comment]
Warnings in `core.h` and `format-inl.h` should be fixed now: https://ci.appveyor.com/project/vitaut/fmt/builds/20795873/job/qolsauqk7psv2dtt
