### ISSUE TITLE
Windows strftime issue

### ISSUE THREAD

**Issue by shirolimit** [fmtlib/fmt#965]
There is a problem with time formatting on Windows. Sometimes it can throw SEH exception.

The problem is in CRT strftime implementation, which fmtlib uses for time formatting.
Code from https://github.com/fmtlib/fmt/blob/master/include/fmt/time.h#L358
```
std::size_t size = buf.capacity() - start;
std::size_t count =
internal::strftime(&buf[start], size, &tm_format[0], &tm);
```

If the size of the buffer equals it's capacity, so that the value of `size` variable results in 0, then CRT throws SEH exception.

The reason is that MS implementation checks validity of the second parameter of strftime function (it is not standard compliant, btw, so maybe they'll fix).

Code snippet from MS strftime implementation:
```
extern "C" size_t __cdecl _Strftime_l (
    _Out_writes_z_(maxsize) char * const string,
    _In_ size_t                    const maxsize,
    _In_z_ const char *            const format,
    _In_ const tm *                const timeptr,
    _In_ void *                    const lc_time_arg,
    _In_opt_ _locale_t             const locale
    )
{
    _LocaleUpdate locale_update(locale);
    unsigned int const lc_time_cp = locale_update.GetLocaleT()->locinfo->lc_time_cp;

    _VALIDATE_RETURN(string != nullptr, EINVAL, 0)
    _VALIDATE_RETURN(maxsize != 0,      EINVAL, 0)
```

Possible fixes:
1) check for zero buffer size prior to strftime call
2) set invalid parameter handler via `_set_invalid_parameter_handler`, to avoid SEH exceptions (bad idea, cause it also need to store previous one, and could be replaced)

**Comment by vitaut** [comment]
Implemented a workaround in https://github.com/fmtlib/fmt/commit/acfa95d4a87f88ac4caedddd5d01d5773091aaa1, thanks for reporting.
