### ISSUE TITLE
Safer overloads for fmt::print and fmt::format without arguments

### ISSUE THREAD

**Issue by Dwarfobserver** [fmtlib/fmt#966]
Hello,

From what I understand, `fmt::format(x)` and `fmt::print(x)` interpret the string `x`.
But, I don't see any benefit to do so, and it can crash on some text that we want to print (eg. if it contains `{}`).

Wouldn't be better if we had overloads for these functions, where : 
 - `fmt::format(x)` simply returns `x`
 - `fmt::print(x)` resolves to `fmt::print("{}", x)`
And so on (eg. for `fmt::print(stdout, x)` as well) ?

**Comment by vitaut** [comment]
I think making formatting functions not perform formatting would be counter-intuitive and would create an unnecessary special case. Right now it won't crash but report an error if you refer to a non-existing argument which may catch actual bugs. You can also catch errors at compile time.
