### ISSUE TITLE
Error: "unmatched '}' in format string" when format string contains such substring: {{0}{1}}

### ISSUE THREAD

**Issue by olena-lizina** [fmtlib/fmt#975]
I've tried to format following string:
format_string("{{0}:{1}}", "Score", 32)
I've got the next error:
"unmatched '}' in format string"
How can I fix it?

**Comment by foonathan** [comment]
If you want to print a literal '{' or '}' you need to write it twice, '{{' and '}}'.

So: `"{{{0}:{1}}}"`
