### ISSUE TITLE
the latest color API doesn't work

### ISSUE THREAD

**Issue by kenjichanhkg** [fmtlib/fmt#976]
Hi,
The following code works in previous version but not in the latest version.
fmt::print(fmt::color::red, "{}", 123);

Why is that?

**Comment by Rakete1111** [comment]
In the newest version there is only one style argument. This means that you can combine them however you like. A side effect of this change is that it's not clear whether a color is supposed to be the foreground or the background. You'll need to call `fmt::fg` or `fmt::bg`:

```c++
fmt::print(fg(fmt::color::red), "{}", 123); // foreground color is red

fmt::print(bg(fmt::color::red), "{}", 123); // background is red
```

**Comment by kenjichanhkg** [comment]
I'm using FMT_VERSION 50201.

I can't find the fmt::fg and fmt::bg. I can find the functions:

```
inline void print(rgb fd, string_view format_str, const Args & ... args) ;
inline void print(rgb fd, rgb bg, string_view format_str, const Args & ... args) ;

```

so I suppose the first parameter is the foreground color, 2nd can be the background color.
My code can compile, but my print color still doesn't work.

**Comment by kenjichanhkg** [comment]
I've found that, it works in iTerm, but not Terminal in mac.

**Comment by vitaut** [comment]
Yeah, `Terminal.app` doesn't support 24-bit color. However, you should be able to use 3/4-bit colors once we reintroduce support for them: #968.
