### ISSUE TITLE
Including "WinSock2.h" *after* fmtlib (header only) include does not compile on MSVC

### ISSUE THREAD

**Issue by aletschhorn** [fmtlib/fmt#978]
I am not sure whether this is an issue of fmtlib or the windows sdk, but when I use fmt as header-only lib and include "WinSock2.h", MSVC does raise a lot of compiling errors like 

`Error	C2375	'WSAUnhookBlockingHook': redefinition; different linkage	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CMakeLists.txt	C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\WinSock2.h	2444	`

When using the non-header version or when including fmt afterwards, it compiles perfectly.

I used the master branch of fmtlib.

**Comment by vitaut** [comment]
Looks like a bug with inclusion order in Windows headers: https://social.msdn.microsoft.com/Forums/vstudio/en-US/6177f9bc-db75-4317-9904-02ef55b527d0/linking-problem-with-winsock2?forum=vcgeneral . Please report there or use one of the workarounds you've found.
