### ISSUE TITLE
printing chrono time_point

### ISSUE THREAD

**Issue by bigerl** [fmtlib/fmt#985]
I can't print a [time_point](https://en.cppreference.com/w/cpp/chrono/time_point)s. 
e.g.:
```cpp
#include <fmt/format.h>
#include <fmt/time.h>
#include <fmt/chrono.h>

int main(){
    // fails to compile
    fmt::print("{}", std::chrono::system_clock::now());
}
``` 

I had a look at [time.h](https://github.com/fmtlib/fmt/blob/master/include/fmt/time.h) and it looks like only c style std::time is supported right now.

Does anybody now an easy handy hack to acquire formatting chrono `time_point`s? 

Otherwise, and anyways, this is also a feature request. ;)

Further, while this code succeeds:
```cpp
#include <fmt/format.h>
#include <fmt/time.h>
#include <fmt/chrono.h>

int main(){
    // prints correct result
    std::time_t t = std::time(nullptr);
    fmt::print("{:%Y-%m-%d}", *std::localtime(&t));
}
``` 
this code fails to compile:
```cpp
#include <fmt/format.h>
#include <fmt/time.h>
#include <fmt/chrono.h>
#include <iostream>
int main(){
    using namespace std::chrono;
    //  fails to compile
    std::time_t t = std::time(nullptr);
    std::cout << "{:%Y-%m-%d}"_format(*std::localtime(&t)) << std::endl;
}
``` 
Seems to be a bug, doesn't it?

I am using the most recent commit [3e01376e089ffcf993adeb20aea0c0019bf66ee2](https://github.com/fmtlib/fmt/commit/3e01376e089ffcf993adeb20aea0c0019bf66ee2).

This issue questions [this post](https://github.com/fmtlib/fmt/issues/864#issuecomment-445647904) in issue #864.

**Comment by remyabel** [comment]
Right now you can format/print a duration, but not a time_point. It doesn't really make sense to directly output a time_point. This functionality isn't available in the stdlib either, though in C++20 you can do `std::cout << duration`, so fmtlib is already ahead of the curve. So change your code to:

    fmt::print("{}", std::chrono::system_clock::now().time_since_epoch());

**Comment by vitaut** [comment]
@remyabel is right about durations and time points. Regarding your other question,

> Seems to be a bug, doesn't it?

Not really, `_format` will give an expected compile-time error if the formatter's `parse` function is not `constexpr` which is the case with `strftime` formatting. You should use the normal `format` function instead.
