### ISSUE TITLE
compile error with user-defined formatter for vector<bool>

### ISSUE THREAD

**Issue by jope12** [fmtlib/fmt#991]
I've programmed a generic formatter for vectors, which works, except in the case of vector\<bool\> AND the inclusion of 'fmt/ostream.h' or 'fmt/ranges.h'.
 In this case I get the following compiler error (gcc 8.1.0, x86_64, Windows / version define from core.h: FMT_VERSION 50202).

../fmt/core.h:622:56: error: ambiguous template instantiation for 'struct fmt::v5::formatter<std::vector\<bool\>, char, void>'

**Comment by jope12** [comment]
Thanks, 
I did not realize that with `fmt/ranges.h`, there is an error with every vector.
But why is there an error with `fmt/ostream.h` and vector\<bool\>?

**Comment by vitaut** [comment]
AFAICS, `fmt/ostream.h` doesn't introduce a formatter for `vector<bool>`: https://godbolt.org/z/AVyn51. Please post a reproducible example if you want me to investigate this further.

**Comment by jope12** [comment]
For the sake of giving a minimal example,  I ripped out all the guts from my formatter, so there's basically nothing left and useless, but it compiles without error when`fmt/ostream.h` is not included, but gives the error mentioned in my first comment when `fmt/ostream.h` is included:
```
template <typename Char, typename VecType> struct fmt::formatter<std::vector<VecType>, Char>
{
  template <typename ParseContext> auto parse(ParseContext &ctx) -> decltype(ctx.begin())
  {
    return 0;
  }

  template <typename FormatContext> auto format(const std::vector<VecType> &vec, FormatContext &ctx) -> decltype(ctx.out())
  {
    basic_memory_buffer<Char> buf; 
    return std::copy(buf.begin(), buf.end(), ctx.out());
  }
};
```
And main (includes left out):
```
int main(int argc, char **argv)
{
  vector<bool> buf = {true, false};
  print("buf = {}", buf);
}
```

**Comment by vitaut** [comment]
Seems to compile OK (https://godbolt.org/z/IRbg06):

```c++
#include <vector>
#include <fmt/ostream.h>

template <typename Char, typename VecType> struct fmt::formatter<std::vector<VecType>, Char>
{
  template <typename ParseContext> auto parse(ParseContext &ctx) -> decltype(ctx.begin())
  {
    return 0;
  }

  template <typename FormatContext> auto format(const std::vector<VecType> &vec, FormatContext &ctx) -> decltype(ctx.out())
  {
    basic_memory_buffer<Char> buf; 
    return std::copy(buf.begin(), buf.end(), ctx.out());
  }
};

int main(int argc, char **argv)
{
  std::vector<bool> buf = {true, false};
  fmt::print("buf = {}", buf);
}
```

**Comment by jope12** [comment]
Please take my sincere apologies for wasting your time. 
I found the error,  I had an ostream operator for vector<bool> in one of my header files I had forgotten about...

**Comment by vitaut** [comment]
No worries. Glad you've found the cause.
