### ISSUE TITLE
string_view cannot be used as the format string in fmt::format

### ISSUE THREAD

**Issue by lukedan** [fmtlib/fmt#992]
I'm using the version of fmt provided by vcpkg with VS2017. The following code does not compile for me:

    std::string_view sv("{0} + {1}");
    std::cout << fmt::format(sv, 1, 2);

However, `fmt::print` works just fine.

**Comment by vitaut** [comment]
Works on master: https://godbolt.org/z/1KRmsb

**Comment by vitaut** [comment]
> So it's a pending release then?

Yes: #948
