### ISSUE TITLE
mkvtoolnix-gui

### ISSUE THREAD

**Issue by medioman** [fmtlib/fmt#996]
Hello,
after updating fmt with archlinux, mkvtolnix-gui will not start.
I have this error in the terminal with mkvtoonix-gui

[code]me~ $ mkvtoolnix-gui
mkvtoolnix-gui: symbol lookup error: mkvtoolnix-gui: undefined symbol: _ZN3fmt2v58internal13thousands_sepIcEET_PNS0_15locale_providerE
[/code]

If I downgrade your package everything works.
Hi, happy new year

**Comment by vitaut** [comment]
Looks like you need to rebuild `mkvtoolnix-gui` with the new version of {fmt}. I would also recommend using {fmt} as a static library to prevent such issues (report to `mkvtoolnix-gui` project owners?)

**Comment by medioman** [comment]
Thank




  ----Messaggio originale----
 
 Da: notifications@github.com
 
 Data: 1-gen-2019 15.30
 
 A: "fmtlib/fmt"<fmt@noreply.github.com>
 
 Cc: "medioman"<sonbello@alice.it>, "Author"<author@noreply.github.com>
 
 Ogg: Re: [fmtlib/fmt] mkvtoolnix-gui (#996)
 

 

 
Closed #996.

**Comment by medioman** [comment]
Yes, today he fixed the bug with a new version of mkvtoolnix-gui and cli.




  ----Messaggio originale----
 
 Da: notifications@github.com
 
 Data: 1-gen-2019 15.30
 
 A: "fmtlib/fmt"<fmt@noreply.github.com>
 
 Cc: "medioman"<sonbello@alice.it>, "Author"<author@noreply.github.com>
 
 Ogg: Re: [fmtlib/fmt] mkvtoolnix-gui (#996)
 

 

 
Looks like you need to rebuild mkvtoolnix-gui with the new version of {fmt}. I would also recommend using {fmt} as a static library to prevent such issues (report to mkvtoolnix-gui project owners?)

**Comment by mbunkus** [comment]
I'm the MKVToolNix author. The upstream MKVToolNix source tarball does contain `fmt` as a bundled library and will use it if no system-wide installed version is found. Preferring system-wide installed versions is what pretty much all distribution packages want, but then it's their responsibility to rebuild packages when their dependencies change in ABI-incompatible ways.

The Arch Linux package was rebuilt two days ago.

The whole process is pretty much working as intended.
