### ISSUE TITLE
fmt::format chooses wrong formatter when implicit conversion is available

### ISSUE THREAD

**Issue by asynts** [fmtlib/fmt#997]
The following code example reproduces the issue:
```c++
#include <string_view>
#include <iostream>

#include <fmt/core.h>

struct A {
  operator int() const { return 0; }      // #1
};

namespace fmt {
  template <>
  struct formatter<A> {
    template <typename ParseContext>
    constexpr auto parse(ParseContext &ctx) { return ctx.begin(); }

    template <typename FormatContext>
    auto format(const A&, FormatContext &ctx) {
      std::string_view text{"hello"};
      return std::copy(text.begin(), text.end(), ctx.begin());
    }
  };
}

int main() {
  std::cout << fmt::format("{}\n", A{});  // #2
}
```
The statement `#2` writes `0\n` to stdout, I would expect `hello\n`. Adding `explicit` to the conversion operator (`#1`) changes that, but I need the implicit conversion elsewhere.

_Is it possible to provide a formatter for a type which provides an implicit conversion?_

---
I have the following setup:
* debian sid
* clang++ 7.0.1
* libfmt 5.3.0

The compiler is invoked the following way:
```
clang++ -I"$HOME/include" -L"$HOME/lib" -std=c++2a main.cc -lfmt
```

**Comment by vitaut** [comment]
You can disable conversion to `int` by specializing `fmt::convert_to_int`:

```c++
template <> struct fmt::convert_to_int<A, char> : std::false_type {};
```
in which case you'll get the expected output ("hello\n").

I plan to look into a way to automatically prevent implicit conversion if `formatter` is specialized.

**Comment by asynts** [comment]
If I had searched properly I could have found #818 which goes into a similar direction.

Sorry for wasting your time.

**Comment by vitaut** [comment]
No worries. This was helpful as it reminded me to look into the problem (that's why I'm keeping this issue open).

**Comment by vitaut** [comment]
As of https://github.com/fmtlib/fmt/commit/b3cf8613b1916be2e81e5dc3b91726677aa53cbd `formatter` specializations take precedence over implicit conversions. Your example now prints "hello" as expected.
